# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - doxygen
    - graphviz

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: false

formats:
  - pdf

search:
  ignore:
    - doxy/*
