#!/bin/bash

if [ ! -d "${TRUST_ROOT}" ]; then
	echo "TRUST env is not initialized !"
	exit -1
fi

cp $TRUST_ROOT/Validation/Outils/documentation/source/stats.rst .
cp $TRUST_ROOT/Validation/Outils/documentation/source/trustutils.* .

rm -rf python_cloned_srcs
mkdir python_cloned_srcs

cp -r $TRUST_ROOT/Validation/Outils/trustutils python_cloned_srcs/.
cp -r $TRUST_ROOT/Outils/TRUST_STATS_JUPYTER/stats python_cloned_srcs/.
