name: rtd38
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - doxygen=1.9.8
  - sphinx-material
  - numpy
  - matplotlib
  - scipy
  - pandas
  - ipywidgets
  - graphviz
  - sphinx>=7.0,<8.0  
  - sphinx-book-theme>=1.1.2  
  - myst-parser
  - sphinxcontrib-bibtex

