//
// Warning : DO NOT EDIT ! file generated automatically
// TRUST_NO_INDENT
//
#include <verifie_pere.h>
#include <Comm_Group_MPI.h>
#include <Comm_Group_Noparallel.h>
#include <Deactivate_SIGINT_Catch.h>
#include <Disable_TU.h>
#include <EFichier.h>
#include <EFichierBin.h>
#include <EcrFicCollecte.h>
#include <EcrFicCollecteBin.h>
#include <EcrFicPartage.h>
#include <EcrFicPartageBin.h>
#include <EcrFicPartageMPIIO.h>
#include <Ecrire.h>
#include <Ecrire_Fichier.h>
#include <Ecrire_Fichier_Formatte.h>
#include <Execute_parallel.h>
#include <Interprete.h>
#include <Interprete_bloc.h>
#include <LecFicDiffuse.h>
#include <LecFicDiffuseBin.h>
#include <LecFicDiffuse_JDD.h>
#include <LecFicDistribue.h>
#include <LecFicDistribueBin.h>
#include <Lecture_Table.h>
#include <Lire.h>
#include <Lire_Fichier.h>
#include <Lire_Fichier_Bin.h>
#include <Liste_bloc.h>
#include <Motcle.h>
#include <MultipleFiles.h>
#include <Nom.h>
#include <Noms.h>
#include <Objet_a_lire.h>
#include <Read_unsupported_ASCII_file_from_ICEM.h>
#include <SFichier.h>
#include <SFichierBin.h>
#include <System.h>
#include <TRUST_Deriv.h>
#include <Typer_Lire.h>
#include <ptrParam.h>
void instancie_src_Kernel_Utilitaires() {
Cerr << "src_Kernel_Utilitaires" << finl;
Comm_Group_MPI inst1;verifie_pere(inst1);
Comm_Group_Noparallel inst2;verifie_pere(inst2);
Deactivate_SIGINT_Catch inst3;verifie_pere(inst3);
Disable_TU inst4;verifie_pere(inst4);
EFichier inst5;verifie_pere(inst5);
EFichierBin inst6;verifie_pere(inst6);
EcrFicCollecte inst7;verifie_pere(inst7);
EcrFicCollecteBin inst8;verifie_pere(inst8);
EcrFicPartage inst9;verifie_pere(inst9);
EcrFicPartageBin inst10;verifie_pere(inst10);
EcrFicPartageMPIIO inst11;verifie_pere(inst11);
Ecrire inst12;verifie_pere(inst12);
Ecrire_Fichier inst13;verifie_pere(inst13);
Ecrire_Fichier_Formatte inst14;verifie_pere(inst14);
Execute_parallel inst15;verifie_pere(inst15);
Interprete inst16;verifie_pere(inst16);
Interprete_bloc inst17;verifie_pere(inst17);
LecFicDiffuse inst18;verifie_pere(inst18);
LecFicDiffuseBin inst19;verifie_pere(inst19);
LecFicDiffuse_JDD inst20;verifie_pere(inst20);
LecFicDistribue inst21;verifie_pere(inst21);
LecFicDistribueBin inst22;verifie_pere(inst22);
Lecture_Table inst23;verifie_pere(inst23);
Lire inst24;verifie_pere(inst24);
Lire_Fichier inst25;verifie_pere(inst25);
Lire_Fichier_Bin inst26;verifie_pere(inst26);
Liste_bloc inst27;verifie_pere(inst27);
Motcle inst28;verifie_pere(inst28);
Motcles inst29;verifie_pere(inst29);
MultipleFiles inst30;verifie_pere(inst30);
Nom inst31;verifie_pere(inst31);
Noms inst32;verifie_pere(inst32);
Objet_a_lire inst33;verifie_pere(inst33);
Read_unsupported_ASCII_file_from_ICEM inst34;verifie_pere(inst34);
SFichier inst35;verifie_pere(inst35);
SFichierBin inst36;verifie_pere(inst36);
System inst37;verifie_pere(inst37);
TRUST_Deriv_Objet_U inst38;verifie_pere(inst38);
Typer_Lire inst39;verifie_pere(inst39);
ptrParam inst40;verifie_pere(inst40);
}
