CEA TRUST Platform: Vitesse_derive_Forces Class Reference
Vitesse_derive_Forces Class Reference
#include <Vitesse_derive_Forces.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
vitesse de derive entre une phase gaz et une phase liquide -> correlation de Ishii de la forme : v_g = C0 * (alpha_g * v_g + alpha_l * v_l) + v_g0
Member Function Documentation
needs_grad_alpha()
bool Vitesse_derive_Forces::needs_grad_alpha () const inline override virtual
Reimplemented from Vitesse_relative_base.
References needs_grad_alpha_.
needs_vort()
bool Vitesse_derive_Forces::needs_vort () const inline override virtual
Reimplemented from Vitesse_relative_base.
References needs_vort_.
completer()
void Vitesse_derive_Forces::completer () override virtual
Reimplemented from Correlation_base.
References Probleme_base::creer_champ(), Process::exit(), Probleme_base::has_correlation(), needs_grad_alpha_, needs_vort_, and Objet_U::que_suis_je().
set_param()
void Vitesse_derive_Forces::set_param (Param & param) override virtual
Reimplemented from Vitesse_derive_base.
References Param::ajouter(), alpha_lim_, and Vitesse_derive_base::set_param().
evaluate_C0_vg0()
void Vitesse_derive_Forces::evaluate_C0_vg0 (const input_t & input) const override protected virtual
Implements Vitesse_derive_base.
References Dispersion_bulles_base::input_t::alpha, Portance_interfaciale_base::input_t::alpha, Vitesse_relative_base::input_t::alpha, alpha_lim_, Vitesse_derive_base::C0, Portance_interfaciale_base::output_t::Cl, Frottement_interfacial_base::coefficient(), Dispersion_bulles_base::coefficient(), Portance_interfaciale_base::coefficient(), Dispersion_bulles_base::output_t::Ctd, Dispersion_bulles_base::input_t::d_bulles, Portance_interfaciale_base::input_t::d_bulles, Vitesse_relative_base::input_t::d_bulles, Vitesse_relative_base::input_t::dh, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), Vitesse_relative_base::input_t::g, Probleme_base::get_correlation(), Vitesse_relative_base::input_t::gradAlpha, Probleme_base::has_correlation(), Vitesse_relative_base::input_t::k, Dispersion_bulles_base::input_t::k_turb, Portance_interfaciale_base::input_t::k_turb, Dispersion_bulles_base::input_t::mu, Portance_interfaciale_base::input_t::mu, Vitesse_relative_base::input_t::mu, Vitesse_relative_base::n_g, Vitesse_relative_base::n_l, Dispersion_bulles_base::input_t::nut, Vitesse_relative_base::input_t::nut, Dispersion_bulles_base::input_t::nv, Portance_interfaciale_base::input_t::nv, Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Dispersion_bulles_base::input_t::rho, Portance_interfaciale_base::input_t::rho, Vitesse_relative_base::input_t::rho, Dispersion_bulles_base::input_t::sigma, Portance_interfaciale_base::input_t::sigma, Vitesse_relative_base::input_t::sigma, Vitesse_derive_base::vg0, and Vitesse_relative_base::input_t::vort.
Member Data Documentation
needs_grad_alpha_
bool Vitesse_derive_Forces::needs_grad_alpha_ = 0 protected
Referenced by completer(), and needs_grad_alpha().
needs_vort_
bool Vitesse_derive_Forces::needs_vort_ = 0 protected
Referenced by completer(), and needs_vort().
alpha_lim_
double Vitesse_derive_Forces::alpha_lim_ =1.e-5 protected
Referenced by evaluate_C0_vg0(), and set_param().