CEA TRUST Platform: Champ_Fonc_Elem_PolyMAC_P0_TC Class Reference
Champ_Fonc_Elem_PolyMAC_P0_TC Class Reference
Additional Inherited Members
Public Member Functions inherited from Champ_Fonc_P0_base
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
int fixer_nb_valeurs_nodales (int nb_noeuds) override
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void resetTime (double time) override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
This field is a Champ_Fonc_Elem_PolyMAC_P0 with 1 value per element and per phase :
Champ_Fonc_Elem_PolyMAC_P0_TC::valeurs()(e, n) returns the value of phase n in element e The shear rate is calculated using shear rate = sqrt(2*Sij*Sij) Sij = 1/2(grad(u)+t grad(u))
Member Function Documentation
mettre_a_jour()
void Champ_Fonc_Elem_PolyMAC_P0_TC::mettre_a_jour (double) override virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented from Champ_Fonc_P0_base.
References me_calculer(), Champ_Fonc_base::mettre_a_jour(), and Champ_base::temps().
me_calculer()
void Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer (double tps)
References champ_a_deriver(), Objet_U::dimension, Champ_Fonc_base::domaine(), Champ_Inc_base::domaine_vf(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Navier_Stokes_std::get_champ(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by mettre_a_jour().
associer_champ()
void Champ_Fonc_Elem_PolyMAC_P0_TC::associer_champ (const Champ_Face_PolyMAC_P0 & ch) inline
Referenced by PolyMAC_P0_discretisation::taux_cisaillement().
champ_a_deriver() [1/2]
virtual Champ_Face_PolyMAC_P0& Champ_Fonc_Elem_PolyMAC_P0_TC::champ_a_deriver () inline virtual
Referenced by me_calculer().
champ_a_deriver() [2/2]
virtual const Champ_Face_PolyMAC_P0& Champ_Fonc_Elem_PolyMAC_P0_TC::champ_a_deriver () const inline virtual
OBS_PTR()
Champ_Fonc_Elem_PolyMAC_P0_TC::OBS_PTR (Champ_Face_PolyMAC_P0) protected