CEA TRUST Platform: Assembleur_P_VDF Class Reference
Assembleur_P_VDF Class Reference
#include <Assembleur_P_VDF.h>
Public Member Functions
int assembler (Matrice &) override
int assembler_QC (const DoubleTab &, Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
int modifier_secmem (DoubleTab &) override
Public Member Functions inherited from Assembleur_base
int set_resoudre_en_u (int flag)
int set_resoudre_increment_pression (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int construire (Matrice &la_matrice)
int liste_faces_periodiques (ArrOfInt &faces)
void modifier_secmem_pression_imposee (const Neumann_sortie_libre &cond_lim, const Front_VF &frontiere_vf, DoubleTab &secmem)
void modifier_secmem_vitesse_imposee (const Entree_fluide_vitesse_imposee &cond_lim, const Front_VF &frontiere_vf, DoubleTab &secmem)
int remplir (Matrice &la_matrice, const DoubleVect &volumes_entrelaces, const Champ_Don_base *rho_ptr)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Function Documentation
associer_domaine_dis_base()
void Assembleur_P_VDF::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis) override virtual
Implements Assembleur_base.
associer_domaine_cl_dis_base()
void Assembleur_P_VDF::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis) override virtual
Implements Assembleur_base.
domaine_dis_base()
const Domaine_dis_base & Assembleur_P_VDF::domaine_dis_base () const override virtual
Implements Assembleur_base.
domaine_Cl_dis_base()
const Domaine_Cl_dis_base & Assembleur_P_VDF::domaine_Cl_dis_base () const override virtual
Implements Assembleur_base.
assembler()
int Assembleur_P_VDF::assembler (Matrice & matrice) override virtual
Assemblage de la matrice de pression M telle que M*P = div(porosite * grad (P))
et calcul des coefficients pour modifier_secmem.
Implements Assembleur_base.
References construire(), Process::je_suis_maitre(), remplir(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), and Domaine_VF::volumes_entrelaces().
assembler_mat()
int Assembleur_P_VDF::assembler_mat (Matrice & matrice, const DoubleVect & volumes_entrelaces, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_base.
References construire(), Process::je_suis_maitre(), remplir(), Assembleur_base::set_resoudre_en_u(), and Assembleur_base::set_resoudre_increment_pression().
assembler_rho_variable()
int Assembleur_P_VDF::assembler_rho_variable (Matrice & matrice, const Champ_Don_base & rho) override virtual
Assemblage de la matrice de pression M telle que M*P = div(porosite/rho * grad (P))
et calcul des coefficients pour modifier_secmem.
Parameters
(matrice) La matrice a assembler. Contrainte: Soit la matrice n'est pas encore typee (alors on la "construit"), soit c'est la meme que lors de l'appel precedent.
(rho)
Reimplemented from Assembleur_base.
References construire(), Assembleur_base::get_resoudre_en_u(), Assembleur_base::get_resoudre_increment_pression(), Process::je_suis_maitre(), remplir(), and Domaine_VF::volumes_entrelaces().
assembler_QC()
int Assembleur_P_VDF::assembler_QC (const DoubleTab & tab_rho, Matrice & matrice) override virtual
Assemble la matrice de pression pour un fluide quasi compressible.
La matrice M est telle que M*P = div(porosite * grad(P)). Le drapeau resoudre_increment_pression est mis a zero s'il n'a pas encore ete assigne.
Parameters
(DoubleTab& tab_rho) mass volumique
Returns
(int) renvoie toujours 1
Reimplemented from Assembleur_base.
References construire(), Process::exit(), Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Assembleur_base::get_resoudre_increment_pression(), Process::je_suis_maitre(), Matrice_Morse::nb_colonnes(), Matrice_Morse::nb_lignes(), remplir(), Matrice_Sym::set_est_definie(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), and Domaine_VF::volumes_entrelaces().
modifier_secmem()
int Assembleur_P_VDF::modifier_secmem (DoubleTab & secmem) override virtual
Modification du second membre pour appliquer les conditions aux limites.
Les conditions prises en charge sont Neumann_sortie_libre, Entree_fluide_vitesse_imposee, Dirichlet_paroi_defilante (rien a faire), Dirichlet_paroi_fixe (rien a faire), Symetrie (rien a faire)
Implements Assembleur_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Cond_lim_base::frontiere_dis(), Domaine_Cl_dis_base::les_conditions_limites(), modifier_secmem_pression_imposee(), modifier_secmem_vitesse_imposee(), Domaine_Cl_dis_base::nb_cond_lim(), and Objet_U::que_suis_je().
modifier_solution()
int Assembleur_P_VDF::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
References has_P_ref, and Process::mp_min().
completer()
void Assembleur_P_VDF::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
dimensionner_continuite()
void Assembleur_P_VDF::dimensionner_continuite (matrices_t matrices, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Pb_Multiphase::equation(), and Equation_base::probleme().
assembler_continuite()
void Assembleur_P_VDF::assembler_continuite (matrices_t matrices, DoubleTab & secmem, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
References Pb_Multiphase::equation(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Equation_base::probleme().
norme_continuite()
DoubleTab Assembleur_P_VDF::norme_continuite () const override virtual
Reimplemented from Assembleur_base.
construire()
int Assembleur_P_VDF::construire (Matrice & la_matrice) protected
Determine les elements non nuls de la matrice et prepare le stockage.
Matrice creuse de taille nb_elements (lignes) * nb_elem_tot (colonnes) Codee comme une matrice bloc composee de deux matrices morse:
Matrice carree symetrique nb_elements * nb_elements (contient les termes M(i,j) ou i et j sont des numeros d'elements reels)
Matrice rectangle nb_elements * (nb_elem_tot - nb_elem) (contient les termes M(i,j) ou i est reel et j est virtuel
References Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), Domaine_VF::face_voisins(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), les_coeff_pression, liste_faces_periodiques(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces_bord(), Domaine_VF::nb_faces_internes(), Domaine_VF::premiere_face_int(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by assembler(), assembler_mat(), assembler_QC(), and assembler_rho_variable().
remplir()
int Assembleur_P_VDF::remplir (Matrice & la_matrice, const DoubleVect & volumes_entrelaces, const Champ_Don_base * rho_ptr) protected
Calcul des coefficients de la matrice de pression avec un champ de rho.
Si rho_ptr == 0, on calcule la matrice -div(porosite * grad P), sinon on calcule -div(porosite/rho grad P) et *rho_ptr doit etre un Champ_Fonc_Face_VDF.
References Objet_U::bidim_axi, Option_VDF::coeff_P_neumann, Matrice_Morse::compacte(), Process::exit(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_tab2(), has_P_ref, Frontiere_dis_base::le_nom(), les_coeff_pression, liste_faces_periodiques(), Process::mp_max(), Domaine_dis_base::nb_elem(), Front_VF::nb_faces(), Domaine_VF::nb_faces_internes(), Front_VF::num_premiere_face(), Objet_U::precision_geom, Domaine_VF::premiere_face_int(), and Champ_Don_base::valeurs().
Referenced by assembler(), assembler_mat(), assembler_QC(), and assembler_rho_variable().
modifier_secmem_pression_imposee()
void Assembleur_P_VDF::modifier_secmem_pression_imposee (const Neumann_sortie_libre & cond_lim, const Front_VF & frontiere_vf, DoubleTab & secmem) protected
Modification du second membre du solveur en pression pour une condition "Neumann_sortie_libre".
Calcul en "increment de pression" : ajouter l'increment de pression, c'est a dire zero (c.l. instationnaire non supportee) Calcul en "pression" : Ajout du terme Pimpose * surface / volume_entrelace au second membre dans la discretisation de la pression au bord (entre un element elem0 et un element fictif exterieur a pression imposee) : grad P = (P(elem0) - Pimpose) * surface / volume_entrelace
References Domaine_VF::face_voisins(), Neumann::flux_impose(), Assembleur_base::get_resoudre_increment_pression(), les_coeff_pression, Front_VF::nb_faces(), and Front_VF::num_premiere_face().
Referenced by modifier_secmem().
modifier_secmem_vitesse_imposee()
void Assembleur_P_VDF::modifier_secmem_vitesse_imposee (const Entree_fluide_vitesse_imposee & cond_lim, const Front_VF & frontiere_vf, DoubleTab & secmem) protected
Modification du second membre du systeme en pression pour une condition aux limites de vitesse imposee.
Si on resout en increment de pression, ... sinon rien a faire.
References Cond_lim_base::champ_front(), Champ_front_base::derivee_en_temps(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Assembleur_base::get_resoudre_en_u(), Champ_front_base::instationnaire(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Domaine_VDF::orientation().
Referenced by modifier_secmem().
liste_faces_periodiques()
int Assembleur_P_VDF::liste_faces_periodiques (ArrOfInt & faces) protected
Remplit le tableau faces avec la liste des indices des faces periodiques dans le tableau faces_voisins.
Chaque face periodique figure deux fois dans faces_voisins (a chaque face correspond la face opposee). On ne met dans le tableau faces que celle des deux qui a l'indice le + petit dans la liste des faces de chaque bord periodique. Valeur de retour: nombre de faces periodiques (egal a la taille du tableau faces).
References Periodique::face_associee(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by construire(), and remplir().
OBS_PTR() [1/2]
Assembleur_P_VDF::OBS_PTR (Domaine_VDF) protected
OBS_PTR() [2/2]
Assembleur_P_VDF::OBS_PTR (Domaine_Cl_VDF) protected
Member Data Documentation
les_coeff_pression
ArrOfDouble Assembleur_P_VDF::les_coeff_pression protected
Referenced by construire(), modifier_secmem_pression_imposee(), and remplir().
has_P_ref
int Assembleur_P_VDF::has_P_ref protected
Referenced by modifier_solution(), and remplir().