CEA TRUST Platform: Simpler Class Reference
Simpler Class Reference
#include <Simpler.h>
Member Function Documentation
iterer_NS()
void Simpler::iterer_NS (Equation_base & eqn, DoubleTab & current, DoubleTab & pression, double dt, Matrice_Morse & matrice, double seuil_resol, DoubleTrav & secmem, int nb_iter, int & converge, int & ok) override virtual
Reimplemented from Simple.
References Operateur_Div::ajouter(), Equation_base::assembler_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Simpler_Base::assembler_matrice_pression_implicite(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Simple::calculer_correction_en_vitesse(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Simpler_Base::get_and_set_parametre_implicite(), Navier_Stokes_std::has_interface_blocs(), Probleme_base::is_dilatable(), Navier_Stokes_std::matrice_pression(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Equation_base::probleme(), SolveurSys::resoudre_systeme(), Parametre_implicite::solveur(), Navier_Stokes_std::solveur_pression(), and Debog::verifier().