CEA TRUST Platform: Traitement_particulier_NS_canal_VDF Class Reference
Traitement_particulier_NS_canal_VDF Class Reference
#include <Traitement_particulier_NS_canal_VDF.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
pour le calcul d'un canal plan :
    * conservation du debit
    * calculs de moyennes
See also
Navier_Stokes_Turbulent, Traitement_particulier_base, Traitement_particulier_VDF
Member Function Documentation
lire() [1/2]
Entree & Traitement_particulier_NS_canal_VDF::lire (const Motcle & , Entree &)
lire() [2/2]
Entree & Traitement_particulier_NS_canal_VDF::lire (Entree & is) override virtual
Reimplemented from Traitement_particulier_NS_canal.
References Traitement_particulier_NS_canal::lire().
remplir_Y()
void Traitement_particulier_NS_canal_VDF::remplir_Y (DoubleVect & tab_Y, DoubleVect & tab_compt, int & nNy) const override protected virtual
Implements Traitement_particulier_NS_canal.
References Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::xp().
remplir_Tab_recap()
void Traitement_particulier_NS_canal_VDF::remplir_Tab_recap (IntTab & Tab_rec) const override protected virtual
Reimplemented from Traitement_particulier_NS_canal.
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VDF::elem_voisin(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Traitement_particulier_NS_canal::Ny, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Domaine_VF::xp(), and Traitement_particulier_NS_canal::Y.
calculer_moyenne_spatiale_vitesse_rho_mu()
void Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu (DoubleTab & val_moy) const override protected virtual
Implements Traitement_particulier_NS_canal.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Milieu_base::masse_volumique(), Domaine_32_64< _SIZE_ >::nb_elem(), Traitement_particulier_NS_canal::Tab_recap, Champ_Don_base::valeurs(), Champ_Proto::valeurs(), and Fluide_base::viscosite_dynamique().
calculer_moyenne_spatiale_nut()
void Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut (DoubleTab & val_moy) const override protected virtual
Implements Traitement_particulier_NS_canal.
References Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::nb_elem(), Traitement_particulier_NS_canal::Tab_recap, TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), and Modele_turbulence_hyd_base::viscosite_turbulente().
calculer_moyenne_spatiale_Temp()
void Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_Temp (DoubleTab & val_moy) const override protected virtual
Implements Traitement_particulier_NS_canal.
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_32_64< _SIZE_ >::nb_elem(), and Traitement_particulier_NS_canal::Tab_recap.