CEA TRUST Platform: Champ_Som_PolyMAC Class Reference
Champ_Som_PolyMAC Class Reference
#include <Champ_Som_PolyMAC.h>
Additional Inherited Members
Public Member Functions inherited from Champ_Inc_P1_base
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Static Public Member Functions inherited from Champ_implementation_P1
static void init_from_file (DoubleTab &val, const Domaine &dom, int nb_comp, double tolerance, Entree &input)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
imprime()
int Champ_Som_PolyMAC::imprime (Sortie & os, int ncomp) const override virtual
Reimplemented from Champ_Inc_base.
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Champ_Inc_base::domaine(), Domaine_dis_base::domaine(), Champ_Inc_base::domaine_dis_base(), Field_base::nb_compo_, Domaine_32_64< _SIZE_ >::nb_som(), and Champ_Inc_base::valeurs().