CEA TRUST Platform: Comm_Group Class Reference
Comm_Group Class Reference abstract
Public Member Functions
int get_new_tag () const
int rank () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
virtual void init_group (const ArrOfInt &pe_list)
void init_group_node (int nproc, int loc_rank, int glob_rank)
void init_group_trio (int nproc, int rank)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
une portion de code s'execute simultanement. Elle fournit toutes les methodes permettant d'echanger des donnees entre les processeurs du groupe (mpsum, send, recv, ...), et de synchroniser les processeurs (barrier). Elle est specialisee selon le support reseau (MPI, PVM, ...) Attention, ces methodes sont reservees a des operations de bas niveau (noyau TRUST). Dans le code courant, il faut utiliser les methodes classes de communications de haut niveau : (envoyer(), envoyer_broadcast(), class Schema_Comm, class Process, etc) Pour creer un nouveau groupe et l'utiliser, voir class PE_Groups Pour la procedure d'initialisation, voir PE_Groups::Initialize()
Member Enumeration Documentation
Collective_Op
enum Comm_Group::Collective_Op
Enumerator
COLL_SUM
COLL_MIN
COLL_MAX
COLL_PARTIAL_SUM
TypeHint
enum Comm_Group::TypeHint
Enumerator
CHAR
INT
DOUBLE
FLOAT
Constructor & Destructor Documentation
Comm_Group() [1/2]
Comm_Group::Comm_Group ()
~Comm_Group()
Comm_Group::~Comm_Group () override
Destructeur (pour l'instant, rien a faire)
Comm_Group() [2/2]
Comm_Group::Comm_Group (const Comm_Group & a) protected
Le constructeur par copie est interdit !
References Process::exit().
Member Function Documentation
abort()
virtual void Comm_Group::abort () const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
Referenced by Process::exit().
mp_collective_op() [1/6]
virtual void Comm_Group::mp_collective_op (const double * x, double * resu, int n, Collective_Op op) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
Referenced by Process::mp_and(), Process::mp_or(), Process::mp_sum(), Process::mppartial_sum(), Process::mpsum_multiple(), and TRUST_2_PDI::share_TRUSTTab_dimensions().
mp_collective_op() [2/6]
virtual void Comm_Group::mp_collective_op (const double * x, double * resu, const Collective_Op * op, int n) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
mp_collective_op() [3/6]
virtual void Comm_Group::mp_collective_op (const float * x, float * resu, int n, Collective_Op op) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
mp_collective_op() [4/6]
virtual void Comm_Group::mp_collective_op (const float * x, float * resu, const Collective_Op * op, int n) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
mp_collective_op() [5/6]
virtual void Comm_Group::mp_collective_op (const int * x, int * resu, int n, Collective_Op op) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
mp_collective_op() [6/6]
virtual void Comm_Group::mp_collective_op (const int * x, int * resu, const Collective_Op * op, int n) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
barrier()
virtual void Comm_Group::barrier (int tag) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
Referenced by Process::barrier(), Schema_Comm::begin_comm(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::end_comm(), PE_Groups::enter_group(), PE_Groups::exit_group(), init_group(), and Schema_Comm::operator=().
get_new_tag()
int Comm_Group::get_new_tag () const inline
Cette fonction renvoie un nouveau tag de communication pour le groupe.
Effet de bord : incremente le membre group_communication_tag_.
rank()
int Comm_Group::rank () const inline
Renvoie le rang du processeur local dans le groupe *this.
ou -1 si je ne suis pas dans le groupe.
Referenced by TRUST_2_PDI::init(), Process::je_suis_maitre(), Process::me(), and Process::node_master().
nproc()
int Comm_Group::nproc () const inline
Renvoie le nombre de processeurs dans le groupe *this.
Referenced by Schema_Comm_Vecteurs_Static_Data::init(), TRUST_2_PDI::init(), init_group(), init_group_node(), and Process::nproc().
get_node_id()
int Comm_Group::get_node_id () const inline
Retrieve ID of my numa node.
References node_id_.
Referenced by TRUST_2_PDI::init().
get_number_of_nodes()
int Comm_Group::get_number_of_nodes () const inline
References nb_nodes_.
Referenced by TRUST_2_PDI::prepareRestart(), and Save_Restart::sauver().
check_enabled()
int Comm_Group::check_enabled () inline static
Referenced by Schema_Comm::begin_comm(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::end_comm(), Schema_Comm_Vecteurs::end_init(), PE_Groups::enter_group(), PE_Groups::exit_group(), init_group(), Schema_Comm::operator=(), and Schema_Comm::set_send_recv_pe_list().
send_recv_start()
virtual void Comm_Group::send_recv_start (const ArrOfInt & send_list, const ArrOfInt & send_size, const char *const *const send_buffers, const ArrOfInt & recv_list, const ArrOfInt & recv_size, char *const *const recv_buffers, TypeHint typehint = CHAR) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
Referenced by Schema_Comm_Vecteurs::exchange().
send_recv_finish()
virtual void Comm_Group::send_recv_finish () const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
Referenced by Schema_Comm_Vecteurs::exchange().
send()
virtual void Comm_Group::send (int pe, const void * buffer, int size, int tag) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
recv()
virtual void Comm_Group::recv (int pe, void * buffer, int size, int tag) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
Referenced by EcrFicPartage::syncfile().
broadcast()
virtual void Comm_Group::broadcast (void * buffer, int size, int pe_source) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
all_to_all()
virtual void Comm_Group::all_to_all (const void * src_buffer, void * dest_buffer, int data_size) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
all_gather()
virtual void Comm_Group::all_gather (const void * src_buffer, void * dest_buffer, int data_size) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
Referenced by init_group_node().
gather()
virtual void Comm_Group::gather (const void * src_buffer, void * dest_buffer, int data_size, int root) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
all_gatherv()
virtual void Comm_Group::all_gatherv (const void * src_buffer, void * dest_buffer, int send_size, const True_int * recv_size, const True_int * displs) const pure virtual
Implemented in Comm_Group_Noparallel, and Comm_Group_MPI.
set_check_enabled()
void Comm_Group::set_check_enabled (int flag) static
Referenced by mon_main::init_parallel().
operator=()
const Comm_Group & Comm_Group::operator= (const Comm_Group &) protected
La copie est interdite !
References Process::exit().
init_group()
void Comm_Group::init_group (const ArrOfInt & pe_list) protected virtual
Cette fonction doit etre appelee simultanement par tous les PEs du groupe current_group avec les memes parametres.
Les processeurs de la pe_list sont les rangs dans current_group() des processeurs du nouveau groupe. Le maitre du groupe est le premier de la liste, le rang du processeur courant, s'il est dans le groupe est determine par son rang dans la liste. Il ne doit pas y avoir de doublon. Cette fonction est appelee par les methodes init_group des classes derivees.
Reimplemented in Comm_Group_Noparallel.
References barrier(), TRUSTArray< _TYPE_, _SIZE_ >::begin(), check_enabled(), PE_Groups::current_group(), TRUSTArray< _TYPE_, _SIZE_ >::end(), Process::exit(), PE_Groups::groupe_TRUST(), Process::me(), nproc(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by PE_Groups::create_group(), PE_Groups::init_group(), and Comm_Group_Noparallel::init_group().
init_group_node()
void Comm_Group::init_group_node (int nproc, int loc_rank, int glob_rank) protected
Initialize all the information relative to world sizes and ranks for node communicator.
This method is called by derived classes when initializing communicator on node
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), all_gather(), TRUSTArray< _TYPE_, _SIZE_ >::data(), PE_Groups::groupe_TRUST(), nproc(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
init_group_trio()
void Comm_Group::init_group_trio (int nproc_tot, int arank) protected
Initialise le groupe_TRUST().
Cette methode est appelee par init_group_trio() des classes derivees
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Comm_Group_Noparallel::Comm_Group_Noparallel().
Friends And Related Function Documentation
PE_Groups
friend class PE_Groups friend
Member Data Documentation
node_id_
int Comm_Group::node_id_ = -1 protected
Referenced by get_node_id().
nb_nodes_
int Comm_Group::nb_nodes_ = -1 protected
Referenced by get_number_of_nodes().