CEA TRUST Platform: Convection_Diffusion_Espece_Multi_WC Class Reference
Convection_Diffusion_Espece_Multi_WC Class Reference
Public Member Functions
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
Public Member Functions inherited from Convection_Diffusion_Espece_Multi_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_Espece_Fluide_Dilatable_base
std::vector< YAML_data > data_a_sauvegarder () const override
void discretiser () override
const Motcle & domaine_application () const override
int preparer_calcul () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_base
int impr (Sortie &os) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
Probleme_base & probleme ()
const Probleme_base & probleme () const
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Detailed Description
pour un fluide quasi conpressible quand le scalaire subissant le transport est
la fraction massique
See also
Convection_Diffusion_Espece_Multi_base
Member Function Documentation
completer()
void Convection_Diffusion_Espece_Multi_WC::completer () override virtual
Associe l inconnue de l equation a la loi d etat,.
Reimplemented from Equation_base.
References Loi_Etat_Multi_GP_base::associer_inconnue(), Equation_base::completer(), and Convection_Diffusion_Fluide_Dilatable_base::fluide().
assembler()
void Convection_Diffusion_Espece_Multi_WC::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
References Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl().
diffusivite_pour_pas_de_temps()
const Champ_base & Convection_Diffusion_Espece_Multi_WC::diffusivite_pour_pas_de_temps () const override virtual
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
vitesse_pour_transport()
const Champ_base & Convection_Diffusion_Espece_Multi_WC::vitesse_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
References Equation_base::probleme(), and Navier_Stokes_std::rho_la_vitesse().
assembler_blocs_avec_inertie()
void Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) override virtual
Reimplemented from Equation_base.
References Perf_counters::begin_count().
derivee_en_temps_inco()
DoubleTab & Convection_Diffusion_Espece_Multi_WC::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Implements Convection_Diffusion_Espece_Fluide_Dilatable_base.
References Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl().