CEA TRUST Platform: Navier_Stokes_IBM Class Reference
Navier_Stokes_IBM Class Reference
Public Member Functions
bool initTimeStep (double dt) override
int preparer_calcul () override
Public Member Functions inherited from Navier_Stokes_std
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
const Nom & le_nom () const override
int limpr () const
Probleme_base & probleme ()
const Probleme_base & probleme () const
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Navier_Stokes_std
virtual void discretiser_assembleur_pression ()
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_sources (Entree &)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
set_param()
void Navier_Stokes_IBM::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_IBM_Turbulent.
References Param::ajouter(), correction_calcul_pression_initiale_, correction_matrice_pression_, correction_matrice_projection_initiale_, correction_pression_modifie_, correction_vitesse_modifie_, correction_vitesse_projection_initiale_, gradient_pression_qdm_modifie_, matrice_pression_penalisee_H1_, Param::OPTIONAL, Navier_Stokes_std::set_param(), and Equation_IBM_proto::set_param_ibm_proto().
Referenced by Navier_Stokes_IBM_Turbulent::set_param().
preparer_calcul()
int Navier_Stokes_IBM::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_IBM_Turbulent.
References Operateur::ajouter(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Source_PDF_base::calculer(), Navier_Stokes_std::calculer_la_pression_en_pa(), Equation_base::calculer_pas_de_temps(), Source_PDF_base::calculer_pdf(), Equation_IBM_proto::champ_coeff_pdf_som_, Source_PDF_base::correct_incr_pressure(), correction_calcul_pression_initiale_, correction_matrice_pression_, correction_matrice_projection_initiale_, Navier_Stokes_std::divergence, Navier_Stokes_std::divergence_U, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Navier_Stokes_std::fluide(), Navier_Stokes_std::gradient, Navier_Stokes_std::gradient_P, Equation_IBM_proto::i_source_pdf_, Navier_Stokes_std::inconnue(), Probleme_base::is_dilatable(), Navier_Stokes_std::la_pression, Navier_Stokes_std::matrice_pression(), Navier_Stokes_std::matrice_pression_, matrice_pression_penalisee_H1_, Navier_Stokes_std::methode_calcul_pression_initiale_, Sources::mettre_a_jour(), Source_PDF_base::multiply_coeff_volume(), Navier_Stokes_std::nombre_d_operateurs(), Navier_Stokes_std::operateur(), Equation_base::preparer_calcul(), Equation_IBM_proto::preparer_calcul_ibm_proto(), Equation_base::probleme(), Navier_Stokes_std::projection_a_faire(), Navier_Stokes_std::projection_initiale, Navier_Stokes_std::projeter(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), Navier_Stokes_std::solveur_pression_, Equation_base::sources(), Schema_Temps_base::temps_courant(), and Debog::verifier().
Referenced by Navier_Stokes_IBM_Turbulent::preparer_calcul().
initTimeStep()
bool Navier_Stokes_IBM::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_IBM_Turbulent.
References Equation_IBM_proto::champ_coeff_pdf_som_, Source_PDF_base::compute_coeff_matrice(), correction_matrice_pression_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Source_PDF_base::get_matrice_pression_variable_bool_(), Equation_IBM_proto::i_source_pdf_, Navier_Stokes_std::initTimeStep(), Equation_IBM_proto::initTimeStep_ibm_proto(), Navier_Stokes_std::matrice_pression(), matrice_pression_penalisee_H1_, Source_PDF_base::multiply_coeff_volume(), Equation_IBM_proto::set_champ_coeff_pdf_som(), Equation_base::sources(), and Source_PDF_base::updateChampRho().
Referenced by Navier_Stokes_IBM_Turbulent::initTimeStep().
assembler()
void Navier_Stokes_IBM::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Reimplemented from Equation_base.
References Equation_IBM_proto::assembler_ibm_proto().
derivee_en_temps_inco_sources()
void Navier_Stokes_IBM::derivee_en_temps_inco_sources (DoubleTrav & secmem) override virtual
Reimplemented from Equation_base.
References Equation_IBM_proto::derivee_en_temps_inco_ibm_proto().
verify_scheme()
void Navier_Stokes_IBM::verify_scheme () override virtual
Reimplemented from Equation_base.
References Process::abort(), and Equation_base::equation_non_resolue().
get_matrice_pression_penalisee_H1()
int Navier_Stokes_IBM::get_matrice_pression_penalisee_H1 () const inline
References matrice_pression_penalisee_H1_.
get_correction_matrice_pression()
int Navier_Stokes_IBM::get_correction_matrice_pression () const inline
References correction_matrice_pression_.
get_correction_vitesse_modifie()
int Navier_Stokes_IBM::get_correction_vitesse_modifie () const inline
References correction_vitesse_modifie_.
get_correction_pression_modifie()
int Navier_Stokes_IBM::get_correction_pression_modifie () const inline
References correction_pression_modifie_.
get_gradient_pression_qdm_modifie()
int Navier_Stokes_IBM::get_gradient_pression_qdm_modifie () const inline
References gradient_pression_qdm_modifie_.
get_correction_vitesse_projection_initiale()
int Navier_Stokes_IBM::get_correction_vitesse_projection_initiale () const inline
References correction_vitesse_projection_initiale_.
get_correction_calcul_pression_initiale()
int Navier_Stokes_IBM::get_correction_calcul_pression_initiale () const inline
References correction_calcul_pression_initiale_.
get_correction_matrice_projection_initiale()
int Navier_Stokes_IBM::get_correction_matrice_projection_initiale () const inline
References correction_matrice_projection_initiale_.
modify_initial_variable()
void Navier_Stokes_IBM::modify_initial_variable () override protected virtual
Reimplemented from Navier_Stokes_std.
References Equation_IBM_proto::correction_variable_initiale_, correction_vitesse_projection_initiale_, and Equation_IBM_proto::modify_initial_variable_ibm_proto().
modify_initial_gradP()
void Navier_Stokes_IBM::modify_initial_gradP (DoubleTrav & gradP) override protected virtual
Reimplemented from Navier_Stokes_std.
References Equation_IBM_proto::champ_coeff_pdf_som_, and correction_vitesse_projection_initiale_.
Member Data Documentation
correction_matrice_projection_initiale_
int Navier_Stokes_IBM::correction_matrice_projection_initiale_ = 0 protected
Referenced by get_correction_matrice_projection_initiale(), preparer_calcul(), and set_param().
correction_calcul_pression_initiale_
int Navier_Stokes_IBM::correction_calcul_pression_initiale_ = 0 protected
Referenced by get_correction_calcul_pression_initiale(), preparer_calcul(), and set_param().
correction_vitesse_projection_initiale_
int Navier_Stokes_IBM::correction_vitesse_projection_initiale_ = 1 protected
Referenced by get_correction_vitesse_projection_initiale(), modify_initial_gradP(), modify_initial_variable(), and set_param().
correction_matrice_pression_
int Navier_Stokes_IBM::correction_matrice_pression_ = 1 protected
Referenced by get_correction_matrice_pression(), initTimeStep(), preparer_calcul(), and set_param().
matrice_pression_penalisee_H1_
int Navier_Stokes_IBM::matrice_pression_penalisee_H1_ = 0 protected
Referenced by get_matrice_pression_penalisee_H1(), initTimeStep(), preparer_calcul(), and set_param().
correction_vitesse_modifie_
int Navier_Stokes_IBM::correction_vitesse_modifie_ = 1 protected
Referenced by get_correction_vitesse_modifie(), and set_param().
correction_pression_modifie_
int Navier_Stokes_IBM::correction_pression_modifie_ = 0 protected
Referenced by get_correction_pression_modifie(), and set_param().
gradient_pression_qdm_modifie_
int Navier_Stokes_IBM::gradient_pression_qdm_modifie_ = 0 protected
Referenced by get_gradient_pression_qdm_modifie(), and set_param().