CEA TRUST Platform: Echange_impose_base Class Reference
Echange_impose_base Class Reference
Public Member Functions
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Elle correspond a imposer un echange de chaleur avec l'exterieur du domaine en imposant une temperature exterieure T_ext et un coefficient d'echange h_imp. Le terme de flux calcule a partir du couple(h_imp,T_ext) s'ecrit : h_t(T_ext - T_entier)*Surf avec h_t : coefficient d'echange global. Il figure au second membre de l'equation d'energie. Soit l'utilisateur donne un coefficient d'echange qui correspond uniquement a la paroi, auquel cas le programme calculera la diffusion sur la demi-maille pres de la paroi, soit il donne un coefficient d'echange global qui tient compte directement des deux precedents. Les deux classes derivees Echange_externe_impose et Echange_global_impose representent ces deux possibilites.
See also
Cond_lim_base Echange_externe_impose Echange_global_impose
Member Function Documentation
has_emissivite()
bool Echange_impose_base::has_emissivite () const inline
References emissivite_.
Referenced by Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_contribution(), associer_fr_dis_base(), avancer(), changer_temps_futur(), Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face(), emissivite(), fixer_nb_valeurs_temporelles(), Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face(), initialiser(), T_paroi_Champ_P0_VDF::me_calculer(), mettre_a_jour(), reculer(), and set_temps_defaut().
has_h_imp()
bool Echange_impose_base::has_h_imp () const inline
Referenced by associer_fr_dis_base(), avancer(), changer_temps_futur(), fixer_nb_valeurs_temporelles(), h_imp(), initialiser(), mettre_a_jour(), reculer(), and set_temps_defaut().
text()
const DoubleTab & Echange_impose_base::text (double temps = DMAXFLOAT) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and T_ext().
Referenced by Op_Diff_VEF_Face::ajouter_cas_scalaire().
himp()
const DoubleTab & Echange_impose_base::himp (double temps = DMAXFLOAT) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::frontiere_dis(), h_imp(), Front_VF::nb_faces_tot(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Op_Diff_VEF_Face::ajouter_cas_scalaire(), and Op_Diff_VEF_Face::ajouter_contribution().
eps()
const DoubleTab & Echange_impose_base::eps (double temps = DMAXFLOAT) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), emissivite(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces_tot(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Op_Diff_VEF_Face::ajouter_cas_scalaire(), and Op_Diff_VEF_Face::ajouter_contribution().
T_ext() [1/4]
double Echange_impose_base::T_ext (int i) const virtual
Renvoie la valeur de la temperature imposee sur la i-eme composante du champ de frontiere.
Parameters
(int i) l'indice de la composante du champ de de frontiere
Returns
(double)
Reimplemented in Echange_externe_impose_H, and Echange_global_impose_turbulent.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), T_ext(), and Champ_front_base::valeurs().
Referenced by Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_EF_base::dimensionner(), Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face(), T_paroi_Champ_P0_VDF::me_calculer(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_VEF_Face_Gen< DERIVED_T >::modifie_pour_cl_gen(), and Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_face().
T_ext() [2/4]
double Echange_impose_base::T_ext (int i, int j) const virtual
Renvoie la valeur de la temperature imposee sur la (i,j)-eme composante du champ de frontiere.
Parameters
(int i)
(int j)
Returns
(double)
Reimplemented in Echange_externe_impose_H, and Echange_global_impose_turbulent.
References Objet_U::dimension, T_ext(), and Champ_front_base::valeurs().
h_imp() [1/4]
double Echange_impose_base::h_imp (int i) const virtual
Renvoie la valeur du coefficient d'echange de chaleur impose sur la i-eme composante.
du champ de frontiere.
Parameters
(int i)
Returns
(double)
Reimplemented in Echange_global_impose_turbulent.
References Process::exit(), and has_h_imp().
Referenced by Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_contribution_bord_gen(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Diff_DG_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face(), T_paroi_Champ_P0_VDF::me_calculer(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_VEF_Face_Gen< DERIVED_T >::modifie_pour_cl_gen(), and Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_face().
h_imp() [2/4]
double Echange_impose_base::h_imp (int i, int j) const virtual
Renvoie la valeur du coefficient d'echange de chaleur impose sur la i-eme composante.
du champ de frontiere.
Parameters
(int i)
(int j)
Returns
(double)
Reimplemented in Echange_global_impose_turbulent.
References has_h_imp().
emissivite() [1/4]
double Echange_impose_base::emissivite (int i) const
Renvoie la valeur de l'emissivite impose sur la i-eme composante.
du champ de frontiere.
Parameters
(int i)
Returns
(double)
References emissivite_, Process::exit(), and has_emissivite().
Referenced by Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face(), Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face(), and T_paroi_Champ_P0_VDF::me_calculer().
emissivite() [2/4]
double Echange_impose_base::emissivite (int i, int j) const
Renvoie la valeur de l'emissivite impose sur la i-eme composante.
du champ de frontiere.
Parameters
(int i)
(int j)
Returns
(double)
References emissivite_, and has_emissivite().
T_ext() [3/4]
virtual Champ_front_base& Echange_impose_base::T_ext () inline virtual
Renvoie le champ T_ext de temperature imposee a la frontiere.
Returns
(Champ_front_base&) le champ T_ext de temperature imposee a la frontiere
Reimplemented in Echange_global_impose_turbulent, and Echange_externe_impose_H.
Referenced by Echange_contact_PolyMAC::completer(), Echange_interne_global_impose::completer(), Echange_contact_Correlation_VDF::completer(), Echange_contact_VDF::completer(), Echange_interne_impose::completer(), Echange_interne_impose::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_VDF::mettre_a_jour(), Echange_global_impose_turbulent::T_ext(), T_ext(), Echange_couplage_thermique::T_p(), text(), and Echange_contact_PolyMAC::update_coeffs().
T_ext() [4/4]
virtual const Champ_front_base& Echange_impose_base::T_ext () const inline virtual
Reimplemented in Echange_global_impose_turbulent, and Echange_externe_impose_H.
h_imp() [3/4]
virtual Champ_front_base& Echange_impose_base::h_imp () inline virtual
Reimplemented in Echange_global_impose_turbulent.
References has_h_imp().
Referenced by Echange_global_impose_turbulent::h_imp(), and himp().
h_imp() [4/4]
virtual const Champ_front_base& Echange_impose_base::h_imp () const inline virtual
Reimplemented in Echange_global_impose_turbulent.
References has_h_imp().
emissivite() [3/4]
Champ_front_base& Echange_impose_base::emissivite () inline
References emissivite_, and has_emissivite().
Referenced by eps().
emissivite() [4/4]
const Champ_front_base& Echange_impose_base::emissivite () const inline
References emissivite_, and has_emissivite().
liste_faces_loi_paroi()
virtual void Echange_impose_base::liste_faces_loi_paroi (IntTab &) inline virtual
Reimplemented in Echange_global_impose_turbulent.
mettre_a_jour()
void Echange_impose_base::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps des conditions aux limites.
Lors du premier appel des initialisations sont effectuees: h_imp(0,0) = (rho(0,0)*Cp(0,0))
Parameters
(double temps) le temp de mise a jour
Reimplemented from Cond_lim_base.
Reimplemented in Echange_contact_VDF, Echange_contact_Correlation_VDF, Echange_contact_PolyMAC, Echange_interne_impose, Echange_global_impose_turbulent, Echange_couplage_thermique, and Echange_contact_PolyMAC_P0P1NC.
References emissivite_, has_emissivite(), has_h_imp(), and Cond_lim_base::mettre_a_jour().
Referenced by Echange_global_impose::mettre_a_jour(), Echange_interne_impose::mettre_a_jour(), and Echange_contact_PolyMAC::mettre_a_jour().
initialiser()
int Echange_impose_base::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour Contrairementaux methodes mettre_a_jour, les methodes initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose, Echange_contact_VDF, Echange_couplage_thermique, Echange_global_impose_turbulent, and Echange_contact_PolyMAC.
References Cond_lim_base::domaine_Cl_dis(), emissivite_, has_emissivite(), has_h_imp(), and Cond_lim_base::initialiser().
Referenced by Echange_global_impose::initialiser(), Echange_contact_PolyMAC::initialiser(), and Echange_interne_impose::initialiser().
a_mettre_a_jour_ss_pas_dt()
int Echange_impose_base::a_mettre_a_jour_ss_pas_dt () inline override virtual
Cette methode indique si cette condition aux limites doit etre mise a jour dans des sous pas de temps d'un schema en temps tel que RK.
Par defaut elle renvoie 0 pour indiquer qu'aucune mise a jour n'est necessaire ; il faut la surcharger pour renvoyer 1 au besoin (exemple Echange_impose_base)
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Cond_lim_base.
set_temps_defaut()
void Echange_impose_base::set_temps_defaut (double temps) override virtual
Change le i-eme temps futur de la cl.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose, Echange_couplage_thermique, and Echange_global_impose_turbulent.
References emissivite_, has_emissivite(), has_h_imp(), and Cond_lim_base::set_temps_defaut().
Referenced by Echange_global_impose::set_temps_defaut(), and Echange_interne_impose::set_temps_defaut().
fixer_nb_valeurs_temporelles()
void Echange_impose_base::fixer_nb_valeurs_temporelles (int nb_cases) override virtual
Appele par Conds_lim::completer Appel cha_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose, and Echange_global_impose_turbulent.
References emissivite_, Cond_lim_base::fixer_nb_valeurs_temporelles(), has_emissivite(), and has_h_imp().
Referenced by Echange_interne_impose::fixer_nb_valeurs_temporelles().
changer_temps_futur()
void Echange_impose_base::changer_temps_futur (double temps, int i) override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose, Echange_contact_VDF, Echange_couplage_thermique, and Echange_global_impose_turbulent.
References Cond_lim_base::changer_temps_futur(), emissivite_, has_emissivite(), and has_h_imp().
Referenced by Echange_global_impose::changer_temps_futur(), and Echange_interne_impose::changer_temps_futur().
avancer()
int Echange_impose_base::avancer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose, Echange_contact_VDF, Echange_couplage_thermique, and Echange_global_impose_turbulent.
References Cond_lim_base::avancer(), emissivite_, has_emissivite(), and has_h_imp().
Referenced by Echange_global_impose::avancer(), and Echange_interne_impose::avancer().
reculer()
int Echange_impose_base::reculer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose, Echange_contact_VDF, and Echange_couplage_thermique.
References emissivite_, has_emissivite(), has_h_imp(), and Cond_lim_base::reculer().
Referenced by Echange_global_impose::reculer(), and Echange_interne_impose::reculer().
associer_fr_dis_base()
void Echange_impose_base::associer_fr_dis_base (const Frontiere_dis_base & fr) override virtual
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre OWN_PTR(Champ_front_base) de l'objet Cond_lim_base qui represente le champ des conditions aux limites imposees a la frontiere.
Parameters
(Frontiere_dis_base& fr) la frontiere sur laquelle on impose les conditions aux limites
Reimplemented from Cond_lim_base.
Reimplemented in Echange_interne_impose, and Echange_global_impose_turbulent.
References Cond_lim_base::associer_fr_dis_base(), emissivite_, has_emissivite(), and has_h_imp().
Referenced by Echange_interne_impose::associer_fr_dis_base().
has_h_imp_grad()
virtual bool Echange_impose_base::has_h_imp_grad () const inline virtual
Reimplemented in Echange_global_impose_turbulent.
Referenced by Op_Grad_P0_to_Face::ajouter_blocs().
h_imp_grad() [1/2]
virtual double Echange_impose_base::h_imp_grad (int num) const inline virtual
Reimplemented in Echange_global_impose_turbulent.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Op_Grad_P0_to_Face::ajouter_blocs().
h_imp_grad() [2/2]
virtual double Echange_impose_base::h_imp_grad (int num, int k) const inline virtual
Reimplemented in Echange_global_impose_turbulent.
References Process::exit(), and Objet_U::que_suis_je().
OWN_PTR()
Echange_impose_base::OWN_PTR (Champ_front_base) protected
Member Data Documentation
emissivite_
Echange_impose_base::emissivite_ protected
Referenced by associer_fr_dis_base(), avancer(), changer_temps_futur(), emissivite(), fixer_nb_valeurs_temporelles(), has_emissivite(), initialiser(), mettre_a_jour(), reculer(), and set_temps_defaut().