CEA TRUST Platform: PrecondA Class Reference
PrecondA Class Reference
Public Member Functions
int supporte_matrice_morse_sym () override
Public Member Functions inherited from Precond_base
int preconditionner (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)
void prepare (const Matrice_Base &, const DoubleVect &src)
void reinit (Init_Status x=REINIT_ALL)
void set_echange_espace_virtuel_resultat (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void prepare_ (const Matrice_Base &, const DoubleVect &src) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
PrecondA()
PrecondA::PrecondA ()
Member Function Documentation
supporte_matrice_morse_sym()
int PrecondA::supporte_matrice_morse_sym () inline override virtual
returns 1 if the implementation accepts Matrice_Morse_Sym matrices, otherwise 0.
(must be reimplemented if answer is 0)
Reimplemented from Precond_base.
set_param()
void PrecondA::set_param (Param & param) protected
References Param::ajouter(), alpha_0, alpha_1, alpha_a, le_precond_1, and le_precond_a.
preconditionner_()
int PrecondA::preconditionner_ (const Matrice_Base & matrice, const DoubleVect & src, DoubleVect & solution) override protected virtual
Calcule la solution du systeme lineaire: A * solution = b avec la methode de relaxation PrecondA.
Implements Precond_base.
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute(), Matrice_Base::ajouter_multvect(), Matrice_Base::ajouter_multvectT(), alpha_0, alpha_1, alpha_a, Process::exit(), Matrice_Bloc_Sym::get_bloc(), le_precond_1, le_precond_a, Matrice_Base::multvect(), Matrice_Bloc::nb_bloc_colonnes(), Matrice_Bloc::nb_bloc_lignes(), and TRUSTTab_parts< _TYPE_ >::size().
prepare_()
void PrecondA::prepare_ (const Matrice_Base & m, const DoubleVect & v) override protected virtual
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_(). Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise status will be put to READY) and use get_status() to know what should be prepared.
Reimplemented from Precond_base.
References Matrice_Bloc_Sym::get_bloc(), Precond_base::get_status(), le_precond_1, le_precond_a, Precond_base::prepare_(), and ConstTRUSTTab_parts< _TYPE_ >::size().
OWN_PTR()
PrecondA::OWN_PTR (Precond_base) protected
Member Data Documentation
le_precond_1
PrecondA::le_precond_1 protected
Referenced by preconditionner_(), prepare_(), and set_param().
le_precond_a
PrecondA::le_precond_a protected
Referenced by preconditionner_(), prepare_(), and set_param().
alpha_0
double PrecondA::alpha_0 = -100. protected
Referenced by preconditionner_(), and set_param().
alpha_1
double PrecondA::alpha_1 = -100. protected
Referenced by preconditionner_(), and set_param().
alpha_a
double PrecondA::alpha_a = -100. protected
Referenced by preconditionner_(), and set_param().