CEA TRUST Platform: Domaine_EF_axi Class Reference
Domaine_EF_axi Class Reference
Additional Inherited Members
Public Member Functions inherited from Domaine_EF
void reordonner (Faces &) override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
const Frontiere_dis_base & frontiere_dis (const Nom &) const
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
calculer_IPhi()
void Domaine_EF_axi::calculer_IPhi (const Domaine_Cl_dis_base & zcl) override virtual
Reimplemented from Domaine_EF.
References Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), domaine_axi(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Domaine_EF::IPhi_, Domaine_EF::IPhi_thilde_, Domaine_32_64< _SIZE_ >::les_elems(), Equation_base::milieu(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_som_elem(), origine_repere_, Milieu_base::porosite_elem(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
calculer_Bij_gen()
void Domaine_EF_axi::calculer_Bij_gen (DoubleTab & bij_) override virtual
Reimplemented from Domaine_EF.
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_axi(), Domaine_VF::elem_faces_, Domaine_VF::face_normales(), Domaine_VF::face_sommets_, Domaine_VF::face_surfaces(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_VF::nb_som_face(), Domaine_EF::oriente_normale(), and origine_repere_.
remplir_tableau_origine()
void Domaine_EF_axi::remplir_tableau_origine ()
References DomaineAxi1d_32_64< _SIZE_ >::associer_origine_repere(), Domaine_32_64< _SIZE_ >::calculer_centres_gravite(), DomaineAxi1d_32_64< _SIZE_ >::champ_origine(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, domaine_axi(), Process::exit(), DomaineAxi1d_32_64< _SIZE_ >::has_champ_origine(), origine_repere_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_base::valeur_aux().
Referenced by discretiser().
discretiser()
void Domaine_EF_axi::discretiser () override virtual
Reimplemented from Domaine_EF.
References Domaine_EF::discretiser(), Domaine_dis_base::domaine(), remplir_tableau_origine(), Domaine_EF::typer_elem(), and verifie_compatibilite_domaine().
domaine_axi() [1/2]
const DomaineAxi1d & Domaine_EF_axi::domaine_axi () const
References Domaine_dis_base::domaine().
Referenced by calculer_Bij_gen(), calculer_IPhi(), and remplir_tableau_origine().
domaine_axi() [2/2]
DomaineAxi1d & Domaine_EF_axi::domaine_axi ()
References Domaine_dis_base::domaine().
verifie_compatibilite_domaine()
void Domaine_EF_axi::verifie_compatibilite_domaine () override virtual
Reimplemented from Domaine_EF.
References Domaine_dis_base::domaine(), Process::exit(), and Objet_U::que_suis_je().
Referenced by discretiser().
Member Data Documentation
origine_repere_
DoubleTab Domaine_EF_axi::origine_repere_ protected
Referenced by calculer_Bij_gen(), calculer_IPhi(), and remplir_tableau_origine().