CEA TRUST Platform: Op_Dift_EF_Q1 Class Reference
Op_Dift_EF_Q1 Class Reference
Public Member Functions
double calculer_dt_stab () const override
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
void contribuer_au_second_membre (DoubleTab &) const override
void dimensionner (Matrice_Morse &matrice) const override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Dift_EF_base
void completer () override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Op_Diff_EF_base
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_EF_base
void dimensionner (const Domaine_EF &, const Domaine_Cl_EF &, Matrice_Morse &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
La discretisation est EF Le champ diffuse est scalaire Le champ de diffusivite est uniforme
Member Function Documentation
associer_diffusivite()
void Op_Dift_EF_Q1::associer_diffusivite (const Champ_base & diffu) override virtual
associe le champ de diffusivite
Implements Operateur_Diff_base.
diffusivite() [1/2]
const Champ_base& Op_Dift_EF_Q1::diffusivite () const inline override virtual
Implements Operateur_Diff_base.
Referenced by diffusivite(), and remplir_nu().
diffusivite() [2/2]
double Op_Dift_EF_Q1::diffusivite (int) const inline
References diffusivite(), and Champ_Proto::valeurs().
ajouter()
DoubleTab & Op_Dift_EF_Q1::ajouter (const DoubleTab & tab_inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References ajouter_new(), ajouter_scalaire_dim2_nbn_4(), ajouter_scalaire_dim3_nbn_8(), ajouter_scalaire_gen(), ajouter_vectoriel_dim2_nbn_4(), ajouter_vectoriel_dim3_nbn_8(), ajouter_vectoriel_gen(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), Process::exit(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nature_du_champ(), Domaine_32_64< _SIZE_ >::nb_som_elem(), nouvelle_expression_, Op_Diff_EF_base::nu_, and remplir_nu().
Referenced by calculer().
ajouter_new()
DoubleTab & Op_Dift_EF_Q1::ajouter_new (const DoubleTab & tab_inconnue, DoubleTab & resu) const
References ajouter_bords(), Domaine_EF::Bij(), Domaine_EF::Bij_thilde(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Domaine_dis_base::domaine(), Op_EF_base::elem_contribue(), MorEqn::equation(), Domaine_32_64< _SIZE_ >::les_elems(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Op_Diff_EF_base::nu_, remplir_marqueur_elem_CL_paroi(), remplir_nu(), transpose_, transpose_partout_, and Domaine_VF::volumes().
Referenced by ajouter().
calculer()
DoubleTab & Op_Dift_EF_Q1::calculer (const DoubleTab & tab_inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References ajouter().
calculer_dt_stab()
double Op_Dift_EF_Q1::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Op_Diff_EF_base.
References Domaine_EF::carre_pas_maille(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Op_Diff_Turbulent_base::diffusivite_turbulente(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Equation_base::inconnue(), Process::mp_min(), Field_base::nature_du_champ(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_dis_base::nb_elem_tot(), Op_Diff_EF_base::nu_, Objet_U::que_suis_je(), remplir_nu(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Champ_Proto::valeurs().
calculer_pour_post()
void Op_Dift_EF_Q1::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from MorEqn.
verifier()
void Op_Dift_EF_Q1::verifier () const
remplir_nu()
void Op_Dift_EF_Q1::remplir_nu (DoubleTab & nu) const override virtual
Implements Op_Diff_EF_base.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), diffusivite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), MD_Vector::non_nul(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Champ_Proto::valeurs().
Referenced by ajouter(), ajouter_contribution(), ajouter_contribution_new(), ajouter_new(), and calculer_dt_stab().
remplir_marqueur_elem_CL_paroi()
void Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi (ArrOfInt & marqueur, const Domaine_EF & domaine_EF, const Domaine_Cl_EF & domaine_Cl_EF) const
References Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by ajouter_contribution(), ajouter_contribution_new(), and ajouter_new().
dimensionner()
void Op_Dift_EF_Q1::dimensionner (Matrice_Morse & mat) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_EF_base::dimensionner().
modifier_pour_Cl()
void Op_Dift_EF_Q1::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_EF_base::modifier_pour_Cl().
contribuer_a_avec()
void Op_Dift_EF_Q1::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Dift_EF_Q1::contribuer_au_second_membre (DoubleTab &) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References ajouter_bords(), MorEqn::equation(), Equation_base::inconnue(), and Champ_Inc_base::valeurs().
ajouter_bords()
void Op_Dift_EF_Q1::ajouter_bords (const DoubleTab & tab_inconnue, DoubleTab & resu, int contrib_interne = 1) const
References Domaine_EF::Bij(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Process::exit(), Champ_front_calc_interne::face_map(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Operateur_base::flux_bords_, Echange_couplage_thermique::flux_exterieur_impose(), Neumann::flux_impose(), Echange_impose_base::h_imp(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_32_64< _SIZE_ >::les_elems(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Op_EF_base::modifier_flux(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_VF::nb_som_face(), Op_Diff_EF_base::nu_, Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Domaine_VF::surface(), Echange_interne_global_impose::surface_gap(), Echange_impose_base::T_ext(), Op_Dift_EF_base::tau_tan_, Domaine_VF::volumes(), and Domaine_EF::volumes_thilde().
Referenced by ajouter_new(), and contribuer_au_second_membre().
ajouter_contribution()
void Op_Dift_EF_Q1::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
References ajouter_contribution_new(), ajouter_contributions_bords(), Domaine_EF::Bij(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Domaine_dis_base::domaine(), Op_EF_base::elem_contribue(), MorEqn::equation(), Domaine_32_64< _SIZE_ >::les_elems(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), nouvelle_expression_, Op_Diff_EF_base::nu_, remplir_marqueur_elem_CL_paroi(), remplir_nu(), transpose_, transpose_partout_, Domaine_VF::volumes(), and Domaine_EF::volumes_thilde().
Referenced by contribuer_a_avec().
ajouter_contributions_bords()
void Op_Dift_EF_Q1::ajouter_contributions_bords (Matrice_Morse & matrice) const
References Matrice_Morse::coef(), Echange_global_impose::derivee_flux_exterieur_imposee(), Domaine_VF::elem_faces(), MorEqn::equation(), Champ_front_calc_interne::face_map(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Echange_impose_base::h_imp(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Domaine_VF::nb_som_face(), Front_VF::num_premiere_face(), Domaine_VF::surface(), Echange_interne_global_impose::surface_gap(), Echange_impose_base::T_ext(), and Champ_Inc_base::valeurs().
Referenced by ajouter_contribution().
ajouter_contribution_new()
void Op_Dift_EF_Q1::ajouter_contribution_new (const DoubleTab & transporte, Matrice_Morse & matrice) const
References Domaine_EF::Bij(), Domaine_EF::Bij_thilde(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Domaine_dis_base::domaine(), Op_EF_base::elem_contribue(), MorEqn::equation(), Domaine_32_64< _SIZE_ >::les_elems(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Op_Diff_EF_base::nu_, remplir_marqueur_elem_CL_paroi(), remplir_nu(), transpose_, transpose_partout_, and Domaine_VF::volumes().
Referenced by ajouter_contribution().
ajouter_cas_scalaire()
void Op_Dift_EF_Q1::ajouter_cas_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Domaine_Cl_EF & domaine_Cl_EF, const Domaine_EF & domaine_EF) const
ajouter_cas_vectoriel()
void Op_Dift_EF_Q1::ajouter_cas_vectoriel (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Domaine_Cl_EF & domaine_Cl_EF, const Domaine_EF & domaine_EF, int nb_comp) const
OBS_PTR()
Op_Dift_EF_Q1::OBS_PTR (Champ_base) protected
ajouter_scalaire_dim3_nbn_8()
DoubleTab & Op_Dift_EF_Q1::ajouter_scalaire_dim3_nbn_8 (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Referenced by ajouter().
ajouter_scalaire_dim2_nbn_4()
DoubleTab & Op_Dift_EF_Q1::ajouter_scalaire_dim2_nbn_4 (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Referenced by ajouter().
ajouter_scalaire_gen()
DoubleTab & Op_Dift_EF_Q1::ajouter_scalaire_gen (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Referenced by ajouter().
ajouter_scalaire_template()
template<AJOUTE_SCAL _T_> DoubleTab & Op_Dift_EF_Q1::ajouter_scalaire_template (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
ajouter_vectoriel_dim3_nbn_8()
DoubleTab & Op_Dift_EF_Q1::ajouter_vectoriel_dim3_nbn_8 (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Referenced by ajouter().
ajouter_vectoriel_dim2_nbn_4()
DoubleTab & Op_Dift_EF_Q1::ajouter_vectoriel_dim2_nbn_4 (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Referenced by ajouter().
ajouter_vectoriel_gen()
DoubleTab & Op_Dift_EF_Q1::ajouter_vectoriel_gen (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Referenced by ajouter().
ajouter_vectoriel_template()
template<AJOUTE_VECT _T_> DoubleTab & Op_Dift_EF_Q1::ajouter_vectoriel_template (const DoubleTab & tab_inconnue, DoubleTab & resu) const protected
Member Data Documentation
transpose_
int Op_Dift_EF_Q1::transpose_ protected
Referenced by ajouter_contribution(), ajouter_contribution_new(), and ajouter_new().
transpose_partout_
int Op_Dift_EF_Q1::transpose_partout_ protected
Referenced by ajouter_contribution(), ajouter_contribution_new(), and ajouter_new().
nouvelle_expression_
int Op_Dift_EF_Q1::nouvelle_expression_ protected
Referenced by ajouter(), and ajouter_contribution().