CEA TRUST Platform: Liste_bloc_curseur Class Reference
Liste_bloc_curseur Class Reference
#include <Liste_bloc.h>
Constructor & Destructor Documentation
Liste_bloc_curseur()
Liste_bloc_curseur::Liste_bloc_curseur (const Liste_bloc & a_list) inline
References Liste_bloc::est_vide().
Member Function Documentation
valeur() [1/2]
const Objet_U & Liste_bloc_curseur::valeur () const inline
Referenced by Liste_bloc::operator[]().
valeur() [2/2]
Objet_U & Liste_bloc_curseur::valeur () inline
operator->() [1/2]
Objet_U * Liste_bloc_curseur::operator-> () inline
operator->() [2/2]
const Objet_U * Liste_bloc_curseur::operator-> () const inline
list() [1/2]
const Liste_bloc & Liste_bloc_curseur::list () const inline
Referenced by Liste_bloc::dernier().
list() [2/2]
Liste_bloc & Liste_bloc_curseur::list () inline
operator bool()
Liste_bloc_curseur::operator bool () const inline
operator++()
void Liste_bloc_curseur::operator++ () inline
operator=()
Liste_bloc & Liste_bloc_curseur::operator= (const Liste_bloc & a_list) inline