CEA TRUST Platform: Sonde_Int Class Reference
Sonde_Int Class Reference
#include <Sonde_Int.h>
Public Member Functions
void associer_post (const Postraitement &)
SFichier & fichier ()
void fixer_periode (double)
void initialiser (const Domaine &)
const IntVect & le_tableau () const
const IntVect & les_poly () const
const DoubleTab & les_positions () const
void mettre_a_jour (double temps, double tinit)
void ouvrir_fichier ()
void postraiter (double)
Sonde_Int (const Nom &)
double temps () const
~Sonde_Int () override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
On choisit l'ensemble des points sur lesquels on veut sonder un champ et
la periodicite des observations. Les objets Postraitement porte des
des sondes sur les champs a observer, une sonde porte d'ailleurs une
reference sur un postraitement.
See also
Postraitement Sonde_Ints
Constructor & Destructor Documentation
Sonde_Int()
Sonde_Int::Sonde_Int (const Nom & nom) inline
Constructeur d'une sonde a partir de son nom.
Parameters
(Nom& nom) le nom de la sonde a construire
~Sonde_Int()
Sonde_Int::~Sonde_Int () inline override
Destructeur.
Ferme le fichier avant de detruire l'objet.
References fermer_fichier().
Member Function Documentation
associer_post()
void Sonde_Int::associer_post (const Postraitement & le_post)
Associer le postraitement a la sonde.
Parameters
(Postraitement& le_post) le postraitement a associer
References Process::exit().
initialiser()
void Sonde_Int::initialiser (const Domaine & domaine_geom)
Initialise la sonde.
Dimensionne les tableaux, de valeurs, verifie si les points specifies sont bien dans le domaine de calcul.
Parameters
(Domaine& domaine_geom) le domaine de calcul qui sera sondee
Exceptions
point de sondage en dehors du domaine de calcul
References Domaine_32_64< _SIZE_ >::chercher_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::je_suis_maitre(), Process::mp_max(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
mettre_a_jour()
void Sonde_Int::mettre_a_jour (double un_temps, double tinit)
Effectue une mise a jour en temps de la sonde effectue le postraitement.
Parameters
(double temps) le temps de mise a jour
(double tinit) le temps initial de la sonde
References postraiter().
postraiter()
void Sonde_Int::postraiter (double un_temps)
Effectue un postraitement.
Imprime les valeurs du tableau aux positions demandees sur le fichier associe.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), fichier(), Sortie_Fichier_base::flush(), Process::je_suis_maitre(), Process::me(), and Process::nproc().
Referenced by mettre_a_jour().
ouvrir_fichier()
void Sonde_Int::ouvrir_fichier ()
Ouvre le fichier associe a la sonde.
(*.son)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, fichier(), Process::je_suis_maitre(), les_positions(), Objet_U::nom_du_cas(), Sortie_Fichier_base::precision(), and Sortie_Fichier_base::setf().
fermer_fichier()
void Sonde_Int::fermer_fichier () inline
Ferme le fichier sur laquelle la sonde ecrit.
Referenced by ~Sonde_Int().
le_tableau()
const IntVect & Sonde_Int::le_tableau () const inline
Renvoie le champ associe.
Returns
(Champ_base&) le champ associe
les_positions()
const DoubleTab & Sonde_Int::les_positions () const inline
Renvoie le tableau des positions du champ qui sont sondees.
Returns
(DoubleTab&) les positions sondees
Referenced by ouvrir_fichier().
les_poly()
const IntVect & Sonde_Int::les_poly () const inline
Renvoie le tableau des elements qui sont sondes.
Returns
(IntVect&) les ments qui sont sondes
fixer_periode()
void Sonde_Int::fixer_periode (double pe) inline
Fixe la periode avec laquelle on sonde le champ.
Parameters
(double pe) la periode de sondage du champ
temps()
double Sonde_Int::temps () const inline
Le temps ecoule.
Returns
(double) le temps ecoule
fichier()
SFichier & Sonde_Int::fichier () inline
Renvoie un flot de sortie Fichier, pointant sur le fichier de sortie utilise par la sonde.
Returns
(SFichier&) le fichier de sortie utilise par la sonde
Referenced by ouvrir_fichier(), and postraiter().