CEA TRUST Platform: Echange_contact_PolyMAC_P0 Class Reference
Echange_contact_PolyMAC_P0 Class Reference
#include <Echange_contact_PolyMAC_P0.h>
Additional Inherited Members
Public Member Functions inherited from Echange_contact_PolyMAC_P0P1NC
void mettre_a_jour (double temps) override
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
void set_modifier_val_imp (int)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
cette classe possede un autre champ_front avec autant de valeurs temporelles qui represente la temperature dans l'autre probleme.
Member Function Documentation
init_op()
void Echange_contact_PolyMAC_P0::init_op () const
References Champ_front_calc::creer(), Cond_lim_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Champ_front_calc::equation(), MorEqn::equation(), Process::exit(), Champ_front_calc::front_dis(), Cond_lim_base::frontiere_dis(), Echange_contact_PolyMAC_P0P1NC::i_fvf, Echange_contact_PolyMAC_P0P1NC::i_o_fvf, Operateur::l_op_base(), Objet_U::le_nom(), Probleme_U::le_nom(), Nom::le_nom(), Echange_contact_PolyMAC_P0P1NC::nom_autre_pb_, Echange_contact_PolyMAC_P0P1NC::nom_bord_, Echange_contact_PolyMAC_P0P1NC::nom_champ_, Equation_base::nombre_d_operateurs(), o_diff, Echange_contact_PolyMAC_P0P1NC::o_fvf, Equation_base::operateur(), Equation_base::probleme(), and Domaine_dis_base::rang_frontiere().
OBS_PTR()
Echange_contact_PolyMAC_P0::OBS_PTR (Op_Diff_PolyMAC_P0_Elem) mutable
init_fs_dist()
void Echange_contact_PolyMAC_P0::init_fs_dist () const
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), Echange_contact_PolyMAC_P0P1NC::f_dist, fs_dist_init_, Nom::le_nom(), Echange_contact_PolyMAC_P0P1NC::o_fvf, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and s_dist.
Member Data Documentation
o_diff
Echange_contact_PolyMAC_P0::o_diff
Referenced by init_op().
s_dist
std::map<int, int> Echange_contact_PolyMAC_P0::s_dist mutable
Referenced by init_fs_dist().
fs_dist_init_
int Echange_contact_PolyMAC_P0::fs_dist_init_ = 0 mutable
Referenced by init_fs_dist().