CEA TRUST Platform: Echange_contact_VDF Class Reference
Echange_contact_VDF Class Reference
Public Member Functions
int initialiser (double temps) override
void mettre_a_jour (double) override
Public Member Functions inherited from Echange_global_impose
int compatible_avec_discr (const Discretisation_base &discr) const override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void calculer_coeffs_echange (double temps)
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
completer()
void Echange_contact_VDF::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Echange_global_impose.
References Champ_front_base::associer_fr_dis_base(), Champ_front_base::completer(), Echange_global_impose::completer(), Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Champ_front_base::fixer_nb_valeurs_temporelles(), Cond_lim_base::frontiere_dis(), Schema_Temps_base::nb_valeurs_temporelles(), Equation_base::schema_temps(), T_autre_pb(), and Echange_impose_base::T_ext().
initialiser()
int Echange_contact_VDF::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour Contrairementaux methodes mettre_a_jour, les methodes initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Echange_global_impose.
References autre_h, Milieu_base::conductivite(), Champ_front_calc::creer(), MD_Vector_tools::creer_tableau_distribue(), Frontiere_32_64< _SIZE_ >::creer_tableau_faces(), Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Equation_base::domaine_application(), Cond_lim_base::domaine_Cl_dis(), Domaine_Cl_dis_base::domaine_dis(), Champ_front_calc::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_front_calc::equation(), Process::exit(), Domaine_VF::face_voisins(), Champ_front_calc::front_dis(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Domaine_VDF::init_virt_e_map(), Echange_global_impose::initialiser(), Champ_front_calc::initialiser(), item, Frontiere_dis_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Domaine_32_64< _SIZE_ >::md_vector_elements(), Process::me(), Champ_front_calc::milieu(), monolithic, Field_base::nb_comp(), Front_VF::nb_faces(), nom_autre_pb_, nom_bord, nom_champ, Front_VF::num_face(), Domaine_32_64< _SIZE_ >::raccord(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), T_autre_pb(), verifier_correspondance(), and Domaine_VDF::virt_e_map.
verifier_correspondance()
int Echange_contact_VDF::verifier_correspondance () const
References Objet_U::dimension, Domaine_dis_base::domaine(), Cond_lim_base::domaine_Cl_dis(), Champ_front_calc::domaine_dis(), Process::exit(), Champ_front_calc::front_dis(), Cond_lim_base::frontiere_dis(), Frontiere_dis_base::le_nom(), Domaine_base::le_nom(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), T_autre_pb(), and Domaine_VF::xv().
Referenced by initialiser().
mettre_a_jour()
void Echange_contact_VDF::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Echange_global_impose.
References autre_h, calculer_h_autre_pb(), calculer_h_mon_pb(), calculer_Teta_equiv(), calculer_Teta_paroi(), Milieu_base::conductivite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), h_paroi, Champ_front_base::mettre_a_jour(), Echange_global_impose::mettre_a_jour(), Champ_front_calc::milieu(), Field_base::nb_comp(), T_autre_pb(), Echange_impose_base::T_ext(), and T_wall_.
calculer_h_autre_pb()
void Echange_contact_VDF::calculer_h_autre_pb (DoubleTab & tab, double invhparoi, int opt)
References Milieu_base::conductivite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Cond_lim_base::domaine_Cl_dis(), Domaine_Cl_dis_base::domaine_dis(), Champ_front_calc::domaine_dis(), Champ_front_calc::equation(), Process::exit(), Champ_front_calc::front_dis(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Frontiere_32_64< _SIZE_ >::le_nom(), Champ_front_calc::milieu(), Field_base::nb_comp(), Champ_front_calc::nom_bord_oppose(), Domaine_32_64< _SIZE_ >::raccord(), and T_autre_pb().
Referenced by mettre_a_jour().
calculer_h_mon_pb()
void Echange_contact_VDF::calculer_h_mon_pb (DoubleTab & tab, double invhparoi, int opt)
References Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Cond_lim_base::frontiere_dis(), and Equation_base::milieu().
Referenced by mettre_a_jour().
T_autre_pb() [1/2]
virtual Champ_front_base& Echange_contact_VDF::T_autre_pb () inline virtual
Referenced by avancer(), calculer_h_autre_pb(), calculer_Teta_equiv(), calculer_Teta_paroi(), changer_temps_futur(), completer(), Op_Diff_VDF_base::init_op_ext(), initialiser(), mettre_a_jour(), reculer(), and verifier_correspondance().
T_autre_pb() [2/2]
virtual const Champ_front_base& Echange_contact_VDF::T_autre_pb () const inline virtual
calculer_Teta_paroi()
void Echange_contact_VDF::calculer_Teta_paroi (DoubleTab & tab_p, const DoubleTab & mon_h, const DoubleTab & autre_h, int is_pb_fluide, double temps) virtual
remplit Teta_p utilise T_autre_pb au temps passe en parametre
References Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Domaine_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Equation_base::inconnue(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), T_autre_pb(), Champ_Inc_base::valeurs(), and Champ_front_base::valeurs_au_temps().
Referenced by mettre_a_jour().
calculer_Teta_equiv()
void Echange_contact_VDF::calculer_Teta_equiv (DoubleTab & Teta_equiv, const DoubleTab & mon_h, const DoubleTab & autre_h, int is_pb_fluide, double temps) virtual
remplit Teta_eq utilise T_autre_pb au temps passe en parametre
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), T_autre_pb(), and Champ_front_base::valeurs_au_temps().
Referenced by mettre_a_jour().
T_wall()
const DoubleTab& Echange_contact_VDF::T_wall () const inline
References T_wall_.
h_autre_pb()
const DoubleTab& Echange_contact_VDF::h_autre_pb () const inline
References autre_h.
get_remote_elems()
const IntTab& Echange_contact_VDF::get_remote_elems () const inline
References remote_elems_.
nom_autre_pb()
const Nom& Echange_contact_VDF::nom_autre_pb () const inline
References nom_autre_pb_.
Referenced by Op_Diff_VDF_Elem_base::contribuer_termes_croises(), and Op_Diff_VDF_Elem_base::dimensionner_termes_croises().
changer_temps_futur()
void Echange_contact_VDF::changer_temps_futur (double temps, int i) override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Echange_global_impose.
References Champ_front_base::changer_temps_futur(), Cond_lim_base::changer_temps_futur(), and T_autre_pb().
avancer()
int Echange_contact_VDF::avancer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Echange_global_impose.
References Champ_front_base::avancer(), Cond_lim_base::avancer(), and T_autre_pb().
reculer()
int Echange_contact_VDF::reculer (double temps) override virtual
Tourne la roue de la CL.
Reimplemented from Echange_global_impose.
References Champ_front_base::reculer(), Cond_lim_base::reculer(), and T_autre_pb().
OWN_PTR()
Echange_contact_VDF::OWN_PTR (Champ_front_base) protected
Member Data Documentation
item
IntTab Echange_contact_VDF::item mutable
Referenced by Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), and initialiser().
monolithic
int Echange_contact_VDF::monolithic = 0
Referenced by initialiser().
h_paroi
double Echange_contact_VDF::h_paroi = -100. protected
Referenced by mettre_a_jour().
autre_h
DoubleTab Echange_contact_VDF::autre_h protected
Referenced by h_autre_pb(), initialiser(), and mettre_a_jour().
T_wall_
DoubleTab Echange_contact_VDF::T_wall_ protected
Referenced by mettre_a_jour(), and T_wall().
nom_autre_pb_
Nom Echange_contact_VDF::nom_autre_pb_ protected
Referenced by initialiser(), and nom_autre_pb().
nom_bord
Nom Echange_contact_VDF::nom_bord protected
Referenced by initialiser().
nom_champ
Motcle Echange_contact_VDF::nom_champ protected
Referenced by initialiser().
remote_elems_
IntTab Echange_contact_VDF::remote_elems_ protected
Referenced by get_remote_elems().