CEA TRUST Platform: Loi_Etat_rhoT_GR_QC Class Reference
Loi_Etat_rhoT_GR_QC Class Reference
#include <Loi_Etat_rhoT_GR_QC.h>
Public Member Functions
double calculer_masse_volumique (double, double) const override
double calculer_temperature (double, double) override
Public Member Functions inherited from Loi_Etat_GR_base
double Cp_calc (double, double) const
void remplir_T () override
const Nom type_fluide () const override
Public Member Functions inherited from Loi_Etat_base
virtual void associer_fluide (const Fluide_Dilatable_base &)
void assoscier_probleme (const Probleme_base &pb)
void mettre_a_jour (double)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Associe a un fluide incompressible, elle definit un fluide quasi compressible
dont la loi d'etat est :
    rho=rho(Pth,H)
    T  =  T(Pth,H)
See also
Fluide_Quasi_Compressible Loi_Etat_GR_base
Member Function Documentation
calculer_masse_volumique() [1/2]
void Loi_Etat_rhoT_GR_QC::calculer_masse_volumique () override virtual
Recalcule la masse volumique.
Reimplemented from Loi_Etat_GR_base.
References Loi_Etat_GR_base::calculer_masse_volumique().
calculer_temperature()
double Loi_Etat_rhoT_GR_QC::calculer_temperature (double P, double h) override virtual
Calcule la temperature ponctuelle.
Parameters
(double P) pression
(double h) enthalpie
Returns
(double) masse volumique correspondante
Implements Loi_Etat_GR_base.
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), PolyT_, and Loi_Etat_GR_base::R.
calculer_H()
double Loi_Etat_rhoT_GR_QC::calculer_H (double Pth_, double T_) const override virtual
Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
Implements Loi_Etat_GR_base.
References Process::abort(), Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), PolyT_, and Loi_Etat_GR_base::R.
Drho_DP()
double Loi_Etat_rhoT_GR_QC::Drho_DP (double P, double h) const override virtual
Implements Loi_Etat_GR_base.
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), PolyRho_, and Loi_Etat_GR_base::R.
Drho_DT()
double Loi_Etat_rhoT_GR_QC::Drho_DT (double P, double h) const override virtual
Implements Loi_Etat_GR_base.
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), PolyRho_, and Loi_Etat_GR_base::R.
DT_DH()
double Loi_Etat_rhoT_GR_QC::DT_DH (double P, double h) const override virtual
Implements Loi_Etat_GR_base.
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), PolyT_, and Loi_Etat_GR_base::R.
calculer_masse_volumique() [2/2]
double Loi_Etat_rhoT_GR_QC::calculer_masse_volumique (double P, double h) const override virtual
Calcule la masse volumique ponctuelle.
Parameters
(double P) pression
(double h) enthalpie
Returns
(double) masse volumique correspondante
Implements Loi_Etat_GR_base.
References Loi_Etat_GR_base::Cp_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), PolyRho_, and Loi_Etat_GR_base::R.
Member Data Documentation
PolyRho_
DoubleTab Loi_Etat_rhoT_GR_QC::PolyRho_ protected
Referenced by calculer_masse_volumique(), Drho_DP(), and Drho_DT().
PolyT_
DoubleTab Loi_Etat_rhoT_GR_QC::PolyT_ protected
Referenced by calculer_H(), calculer_temperature(), and DT_DH().