CEA TRUST Platform: Format_Post_CGNS Class Reference
Format_Post_CGNS Class Reference
Public Member Functions
int ecrire_champ (const Domaine &, const Noms &, const Noms &, int, double, const Nom &, const Nom &, const Nom &, const Nom &, const DoubleTab &) override
int ecrire_domaine (const Domaine &, const int) override
int ecrire_item_int (const Nom &, const Nom &, const Nom &, const Nom &, const Nom &, const IntVect &, const int) override
int ecrire_temps (const double) override
int initialize_by_default (const Nom &) override
Public Member Functions inherited from Format_Post_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
The CFD General Notation System (CGNS) provides a general, portable, and extensible standard for the storage and retrieval of computational fluid dynamics (CFD) analysis data. It consists of a collection of conventions, and free and open software implementing those conventions. It is self-descriptive, machine-independent, well-documented, and administered by an international steering committee.
It is also an American Institute of Aeronautics and Astronautics (AIAA) Recommended Practice. The system consists of two parts: (1) a standard data model and mapping format for recording the data, and (2) software that reads, writes, and modifies data in that format. The format is a conceptual entity established by the documentation; the software is a physical product supplied to enable developers to access and produce data recorded in that format.
The CGNS system is designed to facilitate the exchange of data between sites and applications, and to help stabilize the archiving of aerodynamic data. The data are stored in a compact, binary format and are accessible through a complete and extensible library of functions. The API (Application Program Interface) is platform independent and can be easily implemented in C, C++, Fortran and Fortran90 applications.
CGNS is self-describing, allowing an application to interpret the structure and contents of a file without any outside information. CGNS can make use of either two different low-level data formats:
an internally developed and supported method called Advanced Data Format (ADF), based on a common file format system previously in use at McDonnell Douglas,
- HDF5, a widely used hierarchical data format
see : https://cgns.github.io/cgns-modern.github.io/index.html https://en.wikipedia.org/wiki/CGNS
Constructor & Destructor Documentation
Format_Post_CGNS()
Format_Post_CGNS::Format_Post_CGNS ()
References reset().
Member Function Documentation
reset()
void Format_Post_CGNS::reset () override virtual
Implements Format_Post_base.
Referenced by Format_Post_CGNS().
set_param()
void Format_Post_CGNS::set_param (Param & param) override virtual
Implements Format_Post_base.
References Param::ajouter(), and Param::REQUIRED.
set_postraiter_domain()
void Format_Post_CGNS::set_postraiter_domain () override virtual
Reimplemented from Format_Post_base.
set_deformable_domain()
void Format_Post_CGNS::set_deformable_domain () override virtual
Reimplemented from Format_Post_base.
set_loc_vector()
void Format_Post_CGNS::set_loc_vector (const std::vector< std::string > & vec) override virtual
Reimplemented from Format_Post_base.
initialize_by_default()
int Format_Post_CGNS::initialize_by_default (const Nom & file_basename) override virtual
Initialise le fichier avec des parametres appropries pour son format (exemple: format ascii, efface le fichier existant, un.
fichier unique pour tous les processeurs etc...) Methode a surcharger dans les classes derivees. Valeur de retour: 1 si l'operation a reussi, 0 sinon.
Reimplemented from Format_Post_base.
initialize()
int Format_Post_CGNS::initialize (const Nom & file_basename, const int format, const Nom & option_para) override virtual
Reimplemented from Format_Post_base.
completer_post()
int Format_Post_CGNS::completer_post (const Domaine & , const int , const Nature_du_champ & , const int , const Noms & , const Motcle & , const Nom &) inline override virtual
Reimplemented from Format_Post_base.
preparer_post()
int Format_Post_CGNS::preparer_post (const Nom & , const int , const int , const double) inline override virtual
Reimplemented from Format_Post_base.
ecrire_entete()
int Format_Post_CGNS::ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) override virtual
Reimplemented from Format_Post_base.
References Noms::contient_(), and Process::exit().
ecrire_temps()
int Format_Post_CGNS::ecrire_temps (const double temps) override virtual
Commence l'ecriture d'un pas de temps.
La classe derivee doit accepter de recevoir plusieurs appels consecutifs a cette methode avec le meme temps.
Reimplemented from Format_Post_base.
finir()
int Format_Post_CGNS::finir (const int est_le_dernier_post) override virtual
Reimplemented from Format_Post_base.
finir_ecriture()
int Format_Post_CGNS::finir_ecriture (double temps_courant) override virtual
Reimplemented from Format_Post_base.
ecrire_domaine_dual()
void Format_Post_CGNS::ecrire_domaine_dual (const Domaine & domaine, const int est_le_premier_post) override virtual
Reimplemented from Format_Post_base.
ecrire_domaine_dis()
int Format_Post_CGNS::ecrire_domaine_dis (const Domaine & domaine, const OBS_PTR(Domaine_dis_base)& domaine_dis_base, const int est_le_premier_post) override virtual
Reimplemented from Format_Post_base.
References ecrire_domaine().
ecrire_domaine()
int Format_Post_CGNS::ecrire_domaine (const Domaine & domaine, const int est_le_premier_post) override virtual
Ecriture d'un maillage.
L'ecriture du domaine a lieu soit au debut, avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique), mais ce n'est pas forcement supporte par le postraitement.
Parameters
(id_domaine) le nom affecte au domaine dans le fichier lata.
(type_elem) le type de l'element geometrique (un type supporte par la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE", "TRIANGLE" et "RECTANGLE")
(dimension) la dimension du domaine (nombre de coordonnees des sommets) On peut avoir un domaine de dimension 3 et des elements de type triangle (postraitement d'une interface ou du bord d'un domaine volumique).
(sommets) Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
(elements) Indices des sommets de chaque element. dimension(1) doit correspondre au type de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
Reimplemented from Format_Post_base.
References ecrire_domaine_low_level(), and Format_Post_base::OBS_PTR().
Referenced by ecrire_domaine_dis().
ecrire_domaine_low_level()
int Format_Post_CGNS::ecrire_domaine_low_level (const Domaine * dom, const Nom & nom_dom, const DoubleTab & som, const IntTab & elem, const Motcle & type_e)
Referenced by ecrire_domaine().
ecrire_item_int()
int Format_Post_CGNS::ecrire_item_int (const Nom & id_item, const Nom & id_du_domaine, const Nom & id_domaine, const Nom & localisation, const Nom & reference, const IntVect & data, const int reference_size) inline override virtual
Ecriture d'un tableau d'entiers dans le fichier de postraitement.
See also
ecrire_champ
Parameters
(reference) Nom d'un autre tableau deja ecrit. data[i] est un indice dans ce tableau (exemple: on peut ecrire le tableau FACES_VOISINS, localisation=FACES, reference=ELEMENTS car le tableau est indexe par un numero de face et contient des indices d'elements) L'ecriture d'un domaine entraine automatiquement l'existence d'une tableau SOMMETS et d'un tableau ELEMENTS
(reference_size) la taille (locale) du tableau cite en reference (dimension(0) du tableau). Cette dimension est utilisee pour renumeroter le contenu du tableau data afin de creer une numerotation globale lorsque tous les processeurs ecrivent dans un fichier unique.
Reimplemented from Format_Post_base.
ecrire_champ()
int Format_Post_CGNS::ecrire_champ (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const Nom & nature, const DoubleTab & data) override virtual
Ecriture d'un champ dans le fichier de postraitement.
Parameters
(id_du_champ) identifiant du champ (permet d'identifier un champ unique si on donne en plus un numero de pas de temps)
(id_du_domaine) identifiant du domaine sur lequel le champ est defini Ce domaine doit avoir ete ecrit avant par "ecrire_domaine".
(localisation) localisation des valeurs du champ (SOMMETS, ELEMENTS, ou tout autre id. de tableau deja ecrit) (tout n'est pas obligatoirement supporte par tous les postraitements)
(data) tableau de valeurs a postraiter. Le nombre de lignes du tableau doit etre egal au nombre de lignes du tableau "localisation" (nombre de sommets, d'elements ou de faces ou autre). Valeur de retour: 1 si operation reussie, 0 sinon (par exemple, preconditions non remplies ou fonctionnalite non supportee par le format).
Reimplemented from Format_Post_base.