CEA TRUST Platform: Convection_Diffusion_Espece_Binaire_Turbulent_QC Class Reference
Convection_Diffusion_Espece_Binaire_Turbulent_QC Class Reference
Public Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_Turbulent
int preparer_calcul ()
Public Member Functions inherited from Convection_Diffusion_Espece_Binaire_base
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
Public Member Functions inherited from Convection_Diffusion_Espece_Fluide_Dilatable_base
void discretiser () override
const Motcle & domaine_application () const override
Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_base
int impr (Sortie &os) const override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
const Nom & le_nom () const override
int limpr () const
Probleme_base & probleme ()
const Probleme_base & probleme () const
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Detailed Description
convection diffusion turbulente lorsque
le fluide est quasi compressible. L'inconnue est
  la fraction massique
Cette classe herite de Convection_Diffusion_Turbulent qui contient
le modele de turbulence et de Convection_Diffusion_Espece_Binaire_QC
qui modelise l'equation non turbulente associe a un fluide quasi compressible
iso-therme et iso-bar
See also
Convection_Diffusion_Turbulent Convection_Diffusion_Espece_Binaire_QC
Member Function Documentation
set_param()
void Convection_Diffusion_Espece_Binaire_Turbulent_QC::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
References Param::ajouter_non_std(), Param::REQUIRED, and Convection_Diffusion_Espece_Binaire_base::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_Espece_Binaire_base.
References Operateur_Diff::associer_diffusivite(), Operateur_Diff::associer_diffusivite_pour_pas_de_temps(), Operateur_Diff::diffusivite(), Convection_Diffusion_Espece_Binaire_base::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Fluide_Dilatable_base::diffusivite_pour_transport(), Convection_Diffusion_Turbulent::lire_modele(), Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Convection_Diffusion_std::terme_diffusif, and TRUST_Ref_Objet_U::valeur().
initTimeStep()
bool Convection_Diffusion_Espece_Binaire_Turbulent_QC::initTimeStep (double dt) override virtual
Reimplemented from Convection_Diffusion_Turbulent.
References Equation_base::initTimeStep(), and Convection_Diffusion_Turbulent::initTimeStep().
get_modele()
const RefObjU & Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_modele (Type_modele type) const override virtual
Reimplemented from Equation_base.
References Equation_base::get_modele(), TRUST_Ref_Objet_U::non_nul(), and TRUST_Ref_Objet_U::valeur().
creer_champ()
void Convection_Diffusion_Espece_Binaire_Turbulent_QC::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
References Equation_base::creer_champ().
get_champ()
const Champ_base & Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Equation_base::get_champ(), Nom::getString(), and Equation_base::has_champ().
has_champ() [1/2]
bool Convection_Diffusion_Espece_Binaire_Turbulent_QC::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
has_champ() [2/2]
bool Convection_Diffusion_Espece_Binaire_Turbulent_QC::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Equation_base::has_champ().
get_noms_champs_postraitables()
void Convection_Diffusion_Espece_Binaire_Turbulent_QC::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
References Equation_base::get_noms_champs_postraitables().