CEA TRUST Platform: Pred_Cor Class Reference
Pred_Cor Class Reference
#include <Pred_Cor.h>
Public Member Functions
int nb_valeurs_futures () const override
int nb_valeurs_temporelles () const override
double temps_defaut () const override
double temps_futur (int i) const override
Public Member Functions inherited from Schema_Temps_base
virtual void changer_temps_courant (const double)
virtual bool corriger_dt_calcule (double &dt) const
int diffusion_implicite () const
double & facteur_securite_pas ()
double facteur_securite_pas () const
virtual int impr (Sortie &os) const
virtual int impr (Sortie &os, Probleme_base &pb) const
virtual void imprimer (Sortie &os) const
void imprimer (Sortie &os, Probleme_base &pb) const
virtual bool isStationary () const
const Nom & le_nom () const override
int limpr () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int mettre_a_jour ()
int nb_impr () const
int nb_pas_dt () const
int nb_pas_dt_max () const
int nb_pas_dt_max_atteint () const
int nb_sauv_max () const
void nommer (const Nom &) override
double pas_de_temps () const
double & pas_temps_max ()
double pas_temps_max () const
double & pas_temps_min ()
double pas_temps_min () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
double seuil_statio () const
virtual int stop () const
int stop_lu () const
double temps_calcul () const
double temps_courant () const
int temps_final_atteint () const
double temps_impr () const
double temps_init () const
double temps_max () const
double temps_precedent () const
double temps_sauv () const
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Schema_Temps_base
Member Function Documentation
nb_valeurs_temporelles()
int Pred_Cor::nb_valeurs_temporelles () const override virtual
Renvoie le nombre de valeurs temporelles a conserver.
Ici : n et n+1, donc 2.
Implements Schema_Temps_base.
nb_valeurs_futures()
int Pred_Cor::nb_valeurs_futures () const override virtual
Renvoie le nombre de valeurs temporelles futures.
Ici : n+1, donc 1.
Implements Schema_Temps_base.
temps_futur()
double Pred_Cor::temps_futur (int i) const override virtual
Renvoie le le temps a la i-eme valeur future.
Ici : t(n+1)
Implements Schema_Temps_base.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
temps_defaut()
double Pred_Cor::temps_defaut () const override virtual
Renvoie le le temps le temps que doivent rendre les champs a l'appel de valeurs()
Ici : t(n+1)
Implements Schema_Temps_base.
References Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::temps_courant().
faire_un_pas_de_temps_eqn_base()
int Pred_Cor::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) override virtual
Implements Schema_Temps_base.
References Champ_Inc_base::avancer(), Equation_base::derivee_en_temps_inco(), Equation_base::domaine_Cl_dis(), Schema_Temps_base::dt_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Inc_base::futur(), Domaine_Cl_dis_base::imposer_cond_lim(), Equation_base::inconnue(), Schema_Temps_base::pas_de_temps(), Champ_Inc_base::reculer(), Schema_Temps_base::temps_courant(), Schema_Temps_base::update_critere_statio(), and Champ_Inc_base::valeurs().
completer()
void Pred_Cor::completer () inline override virtual
Implements Schema_Temps_base.