CEA TRUST Platform: Champ_Generique_Gradient Class Reference
Champ_Generique_Gradient Class Reference
#include <Champ_Generique_Gradient.h>
Public Member Functions
Entity get_localisation (const int index=-1) const override
const Noms get_property (const Motcle &query) const override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Generique_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
La classe porte un operateur statistique "gradient"
Member Function Documentation
get_property()
const Noms Champ_Generique_Gradient::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References Objet_U::dimension, Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Gen_de_Champs_Gen::nb_comp, Champ_Generique_base::nom_post_, and Motcles::search().
get_localisation()
Entity Champ_Generique_Gradient::get_localisation (const int index = -1) const override virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un.
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans parametre, sauf si on sait quoi faire pour les champs multi-supports.
See also
get_nb_localisations() Parametre : index Signification : index de la localisation demandee (pour les champs multi-support). Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support. Si index >= 0 : on renvoie le i-ieme support. Valeur par defaut : -1 Exceptions:
GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques (il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::nom_post_, and Op_Grad_.
get_directive_pour_discr()
const Motcle Champ_Generique_Gradient::get_directive_pour_discr () const override virtual
Renvoie la directive (champ_elem, champ_sommets, champ_face ou pression) pour lancer la discretisation de l espace de stockage rendu par get_champ()
Reimplemented from Champ_Gen_de_Champs_Gen.
References Op_Grad_.
get_champ()
const Champ_base & Champ_Generique_Gradient::get_champ (OWN_PTR(Champ_base)& espace_stockage) const override
References Solveur_Masse_base::appliquer(), Operateur_Grad::calculer(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Process::exit(), Champ_Generique_base::get_champ(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Op_Grad_, Champ_Gen_de_Champs_Gen::OWN_PTR(), Objet_U::que_suis_je(), Equation_base::solv_masse(), and Champ_Proto::valeurs().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Gradient::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const override virtual
Implements Champ_Generique_base.
References Objet_U::dimension, Process::exit(), Op_Grad_, and Champ_Gen_de_Champs_Gen::OWN_PTR().
Operateur() [1/2]
const Operateur_base & Champ_Generique_Gradient::Operateur () const inline override virtual
Implements Champ_Generique_Operateur_base.
References Op_Grad_.
Operateur() [2/2]
Operateur_base & Champ_Generique_Gradient::Operateur () inline override virtual
Implements Champ_Generique_Operateur_base.
References Op_Grad_.
completer()
void Champ_Generique_Gradient::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References MorEqn::associer_eqn(), Operateur_base::associer_eqn(), Champ_Gen_de_Champs_Gen::completer(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Probleme_base::equation(), Process::exit(), Champ_Generique_base::get_champ(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), Champ_Gen_de_Champs_Gen::get_source(), Equation_base::inconnue(), Operateur_Grad::l_op_base(), Equation_base::le_nom(), Field_base::le_nom(), Probleme_base::nombre_d_equations(), Op_Grad_, Champ_Gen_de_Champs_Gen::OWN_PTR(), Objet_U::que_suis_je(), and Operateur_Grad::typer().
nommer_source()
void Champ_Generique_Gradient::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
Member Data Documentation
Op_Grad_
Operateur_Grad Champ_Generique_Gradient::Op_Grad_ protected
Referenced by completer(), get_champ(), get_champ_without_evaluation(), get_directive_pour_discr(), get_localisation(), Operateur(), and Operateur().