CEA TRUST Platform: Interprete_geometrique_base_32_64< _SIZE_ > Class Template Reference
Interprete_geometrique_base_32_64< _SIZE_ > Class Template Reference abstract
Public Member Functions
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Interprete_geometrique_base_32_64< _SIZE_ >
See also
Classe abstraite dont les interpretes geometriques qui modifient un ou plusieurs domaines doivent deriver., Une reference est faite a chaque domaine. L'invalidation de l'octree apres modification du domaine, (par interpreter_(is)) est factorisee dans la methode interpreter(), Methodes abstraites:, int nombre_d_operateurs() const
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Interprete_geometrique_base_32_64< _SIZE_ >::int_t = _SIZE_
Domaine_t
template<typename _SIZE_ > using Interprete_geometrique_base_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Member Function Documentation
interpreter()
template<typename _SIZE_ > Entree & Interprete_geometrique_base_32_64< _SIZE_ >::interpreter (Entree & is) override virtual
Implements Interprete.
References Bords_32_64< _SIZE_ >::associer_domaine(), Bords_Internes_32_64< _SIZE_ >::associer_domaine(), Groupes_Faces_32_64< _SIZE_ >::associer_domaine(), Joints_32_64< _SIZE_ >::associer_domaine(), Raccords_32_64< _SIZE_ >::associer_domaine(), Domaine_32_64< _SIZE_ >::bords_int(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_32_64< _SIZE_ >::fixer_premieres_faces_frontiere(), Domaine_32_64< _SIZE_ >::groupes_faces(), Process::imprimer_ram_totale(), Domaine_32_64< _SIZE_ >::invalide_octree(), and Domaine_32_64< _SIZE_ >::set_mc_mesh_ready().
Referenced by Extraire_plan::interpreter_().
associer_domaine() [1/3]
template<typename _SIZE_ > void Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine (Nom & nom_dom)
Referenced by Calculer_Moments::interpreter_(), Decouper_Bord_coincident::interpreter_(), Dilate::interpreter_(), Discretiser_domaine::interpreter_(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Imprimer_flux::interpreter_(), Imprimer_flux_sum::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Remove_elem::interpreter_(), Rotation::interpreter_(), Triangulation_base::interpreter_(), Postraiter_domaine::interpreter_(), VerifierCoin::interpreter_(), Orienter_Simplexes::interpreter_(), Rectify_Mesh::interpreter_(), Refine_Mesh::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), ScatterMED::lire_domaine(), and Postraiter_domaine::lire_motcle_non_standard().
associer_domaine() [2/3]
template<typename _SIZE_ > void Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine (Entree & is)
References Objet_U::que_suis_je().
associer_domaine() [3/3]
template<typename _SIZE_ > void Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine (Domaine_t & dom)
domaine() [1/2]
template<typename _SIZE_ > Domaine_t& Interprete_geometrique_base_32_64< _SIZE_ >::domaine (int i = 0) inline
Referenced by Rectify_Mesh::apply(), Refine_Mesh::apply(), Rectify_Mesh::apply_2D(), Refine_Mesh::apply_2D(), Rectify_Mesh::apply_3D(), Refine_Mesh::apply_3D(), Refine_Mesh::build_edges(), Refine_Mesh::build_new_boundary_faces_2D(), Refine_Mesh::build_new_boundary_faces_3D(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_connector_faces_2D(), Refine_Mesh::build_new_connector_faces_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_internal_frontier_faces_2D(), Refine_Mesh::build_new_internal_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), Refine_Mesh::build_new_sub_domaines_descriptions(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Rectify_Mesh::check_cell_type(), Refine_Mesh::check_cell_type(), Remove_elem::creer_faces(), Tetraedriser_homogene_compact::creer_sommet(), Tetraedriser_homogene_fin::creer_sommet(), Decouper_Bord_coincident::decouper_(), Postraiter_domaine::ecrire(), Decouper_multi::interpreter(), Calculer_Moments::interpreter_(), Decouper_Bord_coincident::interpreter_(), Dilate::interpreter_(), Discretiser_domaine::interpreter_(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Imprimer_flux::interpreter_(), Imprimer_flux_sum::interpreter_(), Lire_Ideas::interpreter_(), Lire_Tgrid::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), Remove_elem::interpreter_(), Triangulation_base::interpreter_(), VerifierCoin::interpreter_(), Orienter_Simplexes::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Decouper_multi::lire_motcle_non_standard(), Remove_elem::remove_elem_(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_H::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_cells(), Refine_Mesh::update_connector_faces(), Refine_Mesh::update_internal_frontier_faces(), Refine_Mesh::update_nodes(), Refine_Mesh::update_octree(), and Refine_Mesh::update_sub_domaines().
domaine() [2/2]
template<typename _SIZE_ > const Domaine_t& Interprete_geometrique_base_32_64< _SIZE_ >::domaine (int i = 0) const inline
LIST() [1/2]
template<typename _SIZE_ > Interprete_geometrique_base_32_64< _SIZE_ >::LIST (OBS_PTR(Domaine_t)) & inline
Referenced by Create_domain_from_sub_domain::interpreter_(), and Remove_Invalid_Internal_Boundaries::interpreter_().
mettre_a_jour_sous_domaine()
template<typename _SIZE_ > void Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine (Domaine_t & domaine, int_t & elem, int_t num_premier_elem, int_t nb_elem) const
Ajoute dans les sous-domaines les nouveaux elements
References Sous_Domaine_32_64< _SIZE_ >::add_elem(), Sous_Domaine_32_64< _SIZE_ >::le_nom(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_ss_domaines(), and Domaine_32_64< _SIZE_ >::ss_domaine().
Referenced by Decouper_Bord_coincident::decouper_(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), VerifierCoin::interpreter_(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), and Trianguler_H::trianguler().
interpreter_()
template<typename _SIZE_ > virtual Entree& Interprete_geometrique_base_32_64< _SIZE_ >::interpreter_ (Entree & is) protected pure virtual
Implemented in Verifier_Simplexes_32_64< _SIZE_ >, Verifier_Qualite_Raffinements_32_64< _SIZE_ >, Remove_Invalid_Internal_Boundaries, Refine_Mesh, Rectify_Mesh, Raffiner_Simplexes_32_64< _SIZE_ >, Orienter_Simplexes, Corriger_frontiere_periodique_32_64< _SIZE_ >, VerifierCoin, Postraiter_domaine, Read_MED_For_Testing_No_Verify_Option, LireMED_32_64< _SIZE_ >, TroisDto2D_32_64< _SIZE_ >, Triangulation_base, Transformer_32_64< _SIZE_ >, SupprimeBord_32_64< _SIZE_ >, Rotation, Reorienter_triangles_32_64< _SIZE_ >, Reorienter_tetraedres_32_64< _SIZE_ >, Reordonner_32_64< _SIZE_ >, Remove_elem, RegroupeBord_32_64< _SIZE_ >, Redresser_hexaedres_vdf, Raffiner_anisotrope_32_64< _SIZE_ >, Polyedriser_32_64< _SIZE_ >, OrienteFacesBord_32_64< _SIZE_ >, NettoieNoeuds_32_64< _SIZE_ >, Modif_bord_to_raccord_32_64< _SIZE_ >, Mailler_32_64< _SIZE_ >, Lire_Tgrid, Lire_Ideas, Imprimer_flux_sum, Imprimer_flux, Extruder_en3, Extruder_en20, Extruder, ExtrudeParoi, ExtrudeBord, Extraire_surface, Extraire_plan, Extraire_domaine, Distanceparoi, Discretiser_domaine, Dilate, Decouper_Bord_coincident, DecoupeBord_32_64< _SIZE_ >, Create_domain_from_sub_domain, and Calculer_Moments.
LIST() [2/2]
template<typename _SIZE_ > Interprete_geometrique_base_32_64< _SIZE_ >::LIST (OBS_PTR(Domaine_t)) protected