CEA TRUST Platform: Perte_Charge_PolyMAC Class Reference
Perte_Charge_PolyMAC Class Reference
#include <Perte_Charge_PolyMAC.h>
Detailed Description
Perte_Charge_Isotrope, Perte_Charge_Directionnelle et Perte_Charge_Anisotrope heritent de Perte_Charge_PolyMAC. Elles doivent surcharger essentiellement readOn() et perte_charge(). readOn() est suppose lire au moins diam_hydr et sous_domaine.
Ces classes sont censees remplacer Perte_Charge_PolyMAC_Face et Perte_Charge_PolyMAC_P1NC.
Member Function Documentation
ajouter()
DoubleTab & Perte_Charge_PolyMAC::ajouter (DoubleTab & resu) const override
Appelle perte_charge pour chaque face ou cela est necessaire.
References Source_base::ajouter(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_Face_base::fcl(), le_dom_poly(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Champ_base::valeur_a_compo(), and Champ_Don_base::valeurs().
contribuer_a_avec()
void Perte_Charge_PolyMAC::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const override
References Source_base::contribuer_a_avec(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_Face_base::fcl(), le_dom_poly(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Champ_base::valeur_a_compo(), and Champ_Don_base::valeurs().
ajouter_blocs()
void Perte_Charge_PolyMAC::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override
References Multiplicateur_diphasique_base::coefficient(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Pb_Multiphase::equation_masse(), Champ_Face_base::fcl(), Probleme_base::get_correlation(), Milieu_composite::get_saturation(), Interface_base::get_sigma_tab(), Nom::getString(), Probleme_base::has_correlation(), Milieu_composite::has_saturation(), Equation_base::inconnue(), Field_base::le_nom(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Champ_Inc_base::passe(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_base::valeur_a_compo(), and Champ_Don_base::valeurs().
le_dom_poly()
const Domaine_PolyMAC & Perte_Charge_PolyMAC::le_dom_poly () const inline
Referenced by ajouter(), and contribuer_a_avec().