CEA TRUST Platform: Op_Conv_EF_Stab_PolyMAC_Face Class Reference
Op_Conv_EF_Stab_PolyMAC_Face Class Reference
#include <Op_Conv_EF_Stab_PolyMAC_Face.h>
Public Member Functions
void completer () override
void dimensionner (Matrice_Morse &mat) const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Conv_PolyMAC_base
double calculer_dt_stab () const override
void completer () override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
completer()
void Op_Conv_EF_Stab_PolyMAC_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
Reimplemented in Op_Conv_EF_Stab_PolyMAC_P0_Face.
References Op_Conv_PolyMAC_base::completer(), Process::exit(), porosite_e, porosite_f, and TRUSTVect< _TYPE_, _SIZE_ >::ref().
ajouter()
DoubleTab & Op_Conv_EF_Stab_PolyMAC_Face::ajouter (const DoubleTab & inco, DoubleTab & resu) const inline override virtual
Reimplemented from Operateur_base.
References Operateur_base::ajouter(), alpha_, Objet_U::dimension, MorEqn::equation(), Champ_Face_base::fcl(), Operateur_base::has_interface_blocs(), Operateur_Conv_base::incompressible_, porosite_e, and porosite_f.
contribuer_a_avec()
void Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice.
Reimplemented from Operateur_base.
References alpha_, Operateur_base::contribuer_a_avec(), MorEqn::equation(), Champ_Face_base::fcl(), Operateur_base::has_interface_blocs(), Operateur_Conv_base::incompressible_, porosite_e, and porosite_f.
modifier_pour_Cl()
void Op_Conv_EF_Stab_PolyMAC_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
dimensionner()
void Op_Conv_EF_Stab_PolyMAC_Face::dimensionner (Matrice_Morse & mat) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Operateur_base::dimensionner(), MorEqn::equation(), Champ_Face_base::fcl(), and Operateur_base::has_interface_blocs().
set_incompressible()
void Op_Conv_EF_Stab_PolyMAC_Face::set_incompressible (const int flag) override virtual
Reimplemented from Operateur_Conv_base.
References Operateur_Conv_base::incompressible_, and Objet_U::que_suis_je().
Member Data Documentation
alpha_
double Op_Conv_EF_Stab_PolyMAC_Face::alpha_ = 1 protected
Referenced by ajouter(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), and contribuer_a_avec().
porosite_f
DoubleVect Op_Conv_EF_Stab_PolyMAC_Face::porosite_f protected
Referenced by ajouter(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), completer(), and contribuer_a_avec().
porosite_e
DoubleVect Op_Conv_EF_Stab_PolyMAC_Face::porosite_e protected
Referenced by ajouter(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), completer(), and contribuer_a_avec().