CEA TRUST Platform: Sortie_Fichier_base Class Reference
Sortie_Fichier_base Class Reference
Public Member Functions
Sortie & flush () override
Public Member Functions inherited from Sortie
virtual Sortie & operator<< (const char *ob)
virtual Sortie & operator<< (const Objet_U &ob)
void set_bin (bool bin) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Attributes
ofstream * ofstream_ = nullptr
Protected Attributes inherited from Sortie
std::unique_ptr< ostream > ostream_
Protected Attributes inherited from AbstractIO
bool avoid_conversion_ = false
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Sortie_Fichier_base() [1/3]
Sortie_Fichier_base::Sortie_Fichier_base ()
Sortie_Fichier_base() [2/3]
Sortie_Fichier_base::Sortie_Fichier_base (const Sortie_Fichier_base &) default
Sortie_Fichier_base() [3/3]
Sortie_Fichier_base::Sortie_Fichier_base (const char * name, IOS_OPEN_MODE mode = ios::out)
References ouvrir().
Member Function Documentation
get_ofstream()
ofstream & Sortie_Fichier_base::get_ofstream ()
References ofstream_.
Referenced by Format_Post_Lata::ecrire_champ(), Format_Post_Lata::ecrire_domaine_low_level(), Format_Post_Lata::finir_sans_reprise(), Ecrire_Fichier::interpreter_(), is_open(), and Format_Post_Lata::reconstruct().
close()
void Sortie_Fichier_base::close ()
References ofstream_.
Referenced by Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), EcrFicPartage::close(), Champ_front_contact_VEF::connectivity_failed(), DecoupeBord_32_64< _SIZE_ >::decouper(), Op_Div_VEFP1B_Elem::degres_liberte(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), Sonde::fermer_fichier(), Schema_Temps_base::finir(), Format_Post_Lata::finir_sans_reprise(), Loi_horaire::imprimer(), Sch_CN_iteratif::iterateTimeStep(), Champ_front_recyclage::lire_fichier_format3(), Navier_Stokes_std::lire_motcle_non_standard(), Format_Post_Lata::reconstruct(), Traitement_particulier_NS_Profils_thermo_VDF::sauver_stat(), Verifier_Qualite_Raffinements_32_64< _SIZE_ >::verifier_qualite_raffinements(), IJK_Striped_Writer::write_data_parallele_plan_template(), IJK_Striped_Writer::write_data_template(), EcrFicCollecteBin::~EcrFicCollecteBin(), and EcrFicPartageMPIIO::~EcrFicPartageMPIIO().
precision()
void Sortie_Fichier_base::precision (int pre) override virtual
Reimplemented from Sortie.
References ofstream_.
Referenced by DecoupeBord_32_64< _SIZE_ >::decouper(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Fichier_Lata::Fichier_Lata(), Fichier_Lata_maitre::Fichier_Lata_maitre(), Format_Post_Lata::finir_sans_reprise(), Loi_horaire::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Schema_Temps_base::imprimer_temps_courant(), Sonde::ouvrir_fichier(), Sonde_Int::ouvrir_fichier(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Traitement_particulier_NS_EC::ouvrir_fichier(), Format_Post_Lata::reconstruct(), Debog_Pb::write_geometry_data(), and Matrice_Morse::WriteFileMTX().
get_precision()
int Sortie_Fichier_base::get_precision () virtual
Reimplemented in EcrFicPartage.
References ofstream_.
Referenced by Schema_Temps_base::imprimer_temps_courant().
setf()
void Sortie_Fichier_base::setf (IOS_FORMAT code) override virtual
Reimplemented from Sortie.
References ofstream_.
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Champ_P1NC::calcul_h_conv(), DecoupeBord_32_64< _SIZE_ >::decouper(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Fichier_Lata::Fichier_Lata(), Fichier_Lata_maitre::Fichier_Lata_maitre(), Format_Post_Lata::finir_sans_reprise(), Loi_horaire::imprimer(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Sonde::ouvrir_fichier(), Sonde_Int::ouvrir_fichier(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Traitement_particulier_NS_EC::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Format_Post_Lata::reconstruct(), Ch_front_Vortex::sauvegarder_vortex(), Traitement_particulier_NS_canal::sauver_stat_canal(), Terme_Source_Canal_perio::source(), Terme_Source_Canal_perio::write_flow_rate(), and Matrice_Morse::WriteFileMTX().
is_open()
bool Sortie_Fichier_base::is_open ()
References get_ofstream(), and ofstream_.
Referenced by Schema_Temps_base::finir(), Sonde::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Terme_Source_Canal_perio::source(), Terme_Source_Canal_perio::write_flow_rate(), and Schema_Temps_base::write_progress().
ouvrir()
int Sortie_Fichier_base::ouvrir (const char * name, IOS_OPEN_MODE mode = ios::out) virtual
Reimplemented in EcrFicPartage, and EcrFicCollecte.
References AbstractIO::bin_, Process::exception_sur_exit, Process::exit(), Nom::finit_par(), AbstractIO::is_64b_, Process::je_suis_maitre(), ofstream_, Sortie::ostream_, and root.
Referenced by Format_Post_Med::completer_post_med(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::dumplata_scalar(), Format_Post_Med::ecrire_champ_med(), Format_Post_Med::ecrire_domaine_med(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Format_Post_Med::ecrire_temps_med(), Fichier_Lata::Fichier_Lata(), Format_Post_Med::finir_med(), Loi_horaire::imprimer(), DebogIJK::interpreter(), DecoupeBord_32_64< _SIZE_ >::interpreter_(), Ecrire_Fichier::interpreter_(), Sch_CN_iteratif::iterateTimeStep(), EcrFicCollecte::ouvrir(), EcrFicPartage::ouvrir(), Sonde::ouvrir_fichier(), Terme_Source_Constituant::ouvrir_fichier(), Source_PDF_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), Source_base::ouvrir_fichier(), Traitement_particulier_NS_EC::ouvrir_fichier(), Format_Post_Med::preparer_post_med(), SFichierBin::SFichierBin(), Sortie_Fichier_base(), Terme_Source_Canal_perio::source(), IJK_Striped_Writer::write_data_parallele_plan_template(), IJK_Striped_Writer::write_data_template(), Terme_Source_Canal_perio::write_flow_rate(), and Schema_Temps_base::write_progress().
flush()
Sortie & Sortie_Fichier_base::flush () override virtual
Force l'ecriture sur disque des donnees dans le tampon Utilise l'implementation de la classe ofstream.
Returns
(Sortie&) *this
Reimplemented from Sortie.
References ofstream_.
Referenced by Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_spat_thermo(), Traitement_particulier_Solide_canal_VDF::ecriture_fichier_moy_temp_thermo(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), Sonde::postraiter(), Sonde_Int::postraiter(), and Traitement_particulier_NS_Profils_thermo_VDF::sauver_stat().
set_root()
void Sortie_Fichier_base::set_root (const std::string dirname) static
References root.
Referenced by Couplage_U::resetTime(), and Probleme_base_interface_proto::resetTimeWithDir_impl().
operator=()
Sortie_Fichier_base& Sortie_Fichier_base::operator= (const Sortie_Fichier_base & f) inline protected
References Process::exit().
Member Data Documentation
root
std::string Sortie_Fichier_base::root = "" static
Referenced by Ecrire_MED_32_64< int >::ecrire_champ(), Probleme_base::init_postraitements(), ouvrir(), Couplage_U::resetTime(), Ecrire_MED_32_64< _SIZE_ >::set_file_name_and_dom(), and set_root().
ofstream_
ofstream* Sortie_Fichier_base::ofstream_ = nullptr protected
This pointer is just a (typed) view on the smart ptr hold by the base class (Sortie). The base class is managing the memory.
Referenced by close(), flush(), get_ofstream(), get_precision(), is_open(), ouvrir(), precision(), setf(), and SFichierBin::SFichierBin().