CEA TRUST Platform: IJK_VDF_converter Class Reference
IJK_VDF_converter Class Reference
Public Member Functions
const Nom & le_nom () const override
void nommer (const Nom &n) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
get_domaine()
const Domaine_IJK& IJK_VDF_converter::get_domaine () const inline
References domaine_ijk_.
Referenced by Multigrille_Adrien::completer().
get_vdf_to_ijk()
const VDF_to_IJK & IJK_VDF_converter::get_vdf_to_ijk (Domaine_IJK::Localisation loc) const
References Domaine_IJK::ELEM, Process::exit(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, Domaine_IJK::NODES, vdf_to_ijk_elem_, vdf_to_ijk_i_, vdf_to_ijk_j_, vdf_to_ijk_k_, and vdf_to_ijk_nodes_.
Referenced by Multigrille_base::convert_from_ijk(), and Multigrille_base::convert_to_ijk().
nommer()
void IJK_VDF_converter::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References object_name_.
le_nom()
const Nom& IJK_VDF_converter::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
References object_name_.
get_conventional_name()
const char * IJK_VDF_converter::get_conventional_name () static
Referenced by Multigrille_Adrien::completer(), Multigrille_base::convert_from_ijk(), and Multigrille_base::convert_to_ijk().
Member Data Documentation
object_name_
Nom IJK_VDF_converter::object_name_ protected
Referenced by le_nom(), and nommer().
domaine_ijk_
Domaine_IJK IJK_VDF_converter::domaine_ijk_ protected
Referenced by get_domaine().
vdf_to_ijk_i_
VDF_to_IJK IJK_VDF_converter::vdf_to_ijk_i_ protected
Referenced by get_vdf_to_ijk().
vdf_to_ijk_j_
VDF_to_IJK IJK_VDF_converter::vdf_to_ijk_j_ protected
Referenced by get_vdf_to_ijk().
vdf_to_ijk_k_
VDF_to_IJK IJK_VDF_converter::vdf_to_ijk_k_ protected
Referenced by get_vdf_to_ijk().
vdf_to_ijk_elem_
VDF_to_IJK IJK_VDF_converter::vdf_to_ijk_elem_ protected
Referenced by get_vdf_to_ijk().
vdf_to_ijk_nodes_
VDF_to_IJK IJK_VDF_converter::vdf_to_ijk_nodes_ protected
Referenced by get_vdf_to_ijk().