CEA TRUST Platform: IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ > Class Template Reference
IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ > Class Template Reference
Protected Member Functions
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
const Nom & que_suis_je () const
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
template<typename _TYPE_, typename _TYPE_ARRAY_>
class IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >
Allocate array with resize(n, ghost). tab[i] is valid for "-ghost <= i < n + ghost"
Constructor & Destructor Documentation
IJKArray_with_ghost()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::IJKArray_with_ghost () inline
Referenced by IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::duplique().
Member Function Documentation
taille_memoire()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > unsigned IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::taille_memoire () const inline override protected virtual
Implements Objet_U.
duplique()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::duplique () const inline override protected virtual
Implements Objet_U.
References Process::exit(), IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::IJKArray_with_ghost(), and Objet_U::numero().
printOn()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Sortie& IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > Entree& IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::readOn (Entree & s) inline override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
resize()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::resize (int n, int new_ghost) inline
References IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost_, and IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::tab_.
Referenced by Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_inv_rho_cst_i_cst_j_var_k(), Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_rho_cst_i_cst_j_var_k(), and Domaine_IJK::get_local_mesh_delta().
operator[]() [1/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::operator[] (int i) const inline
References IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost_, and IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::tab_.
operator[]() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_& IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::operator[] (int i) inline
References IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost_, and IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::tab_.
data()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > const _TYPE_ARRAY_& IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::data () const inline
References IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::tab_.
size()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::size () const inline
References IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost_, and IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::tab_.
ghost()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost () const inline
References IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost_.
Referenced by Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_inv_rho_cst_i_cst_j_var_k(), and Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_rho_cst_i_cst_j_var_k().
echange_espace_virtuel()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel (int pe_min, int pe_max) inline
References Perf_counters::begin_count().
Member Data Documentation
tab_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > _TYPE_ARRAY_ IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::tab_ protected
Referenced by IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::data(), IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::operator[](), IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::resize(), and IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::size().
ghost_
template<typename _TYPE_ , typename _TYPE_ARRAY_ > int IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost_ protected
Referenced by IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost(), IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::operator[](), IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::resize(), and IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::size().