CEA TRUST Platform: Op_Dift_VDF_Face_base Class Reference
Op_Dift_VDF_Face_base Class Reference abstract
Public Member Functions
double calculer_dt_stab () const override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Dift_VDF_base
void contribuer_au_second_membre (DoubleTab &) const override
Public Member Functions inherited from Op_Diff_VDF_base
void completer () override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void dimensionner (Matrice_Morse &) const
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Constructor & Destructor Documentation
Op_Dift_VDF_Face_base()
Op_Dift_VDF_Face_base::Op_Dift_VDF_Face_base (const Iterateur_VDF_base & iter_base) inline
Member Function Documentation
calculer_dt_stab() [1/2]
double Op_Dift_VDF_Face_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
Reimplemented in Op_Dift_Multiphase_VDF_Face.
References Domaine_dis_base::domaine().
Referenced by Op_Dift_VDF_Face_Axi_base::calculer_dt_stab().
calculer_dt_stab() [2/2]
double Op_Dift_VDF_Face_base::calculer_dt_stab (const Domaine_VDF & domaine_VDF) const
References diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Domaine_VDF::dim_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_max(), Domaine_dis_base::nb_elem(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
calculer_borne_locale()
void Op_Dift_VDF_Face_base::calculer_borne_locale (DoubleVect & borne_visco_turb, double dt, double dt_diff_sur_dt_conv) const override virtual
Reimplemented from Operateur_Diff_base.
References diffusivite(), Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_dis_base::nb_elem(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Proto::valeurs().
diffusivite()
const Champ_base& Op_Dift_VDF_Face_base::diffusivite () const override pure virtual
Implements Operateur_Diff_base.
Implemented in Op_Dift_VDF_Face_Axi, Op_Dift_VDF_Face, and Op_Dift_Multiphase_VDF_Face.
Referenced by calculer_borne_locale(), and calculer_dt_stab().
associer_loipar()
void Op_Dift_VDF_Face_base::associer_loipar (const Turbulence_paroi_base &) inline
modifier_pour_Cl()
void Op_Dift_VDF_Face_base::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_VDF_Face::modifier_pour_Cl().
dimensionner_blocs()
void Op_Dift_VDF_Face_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
References Op_VDF_Face::dimensionner(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), Field_base::le_nom(), and Matrice_Morse::nb_colonnes().