CEA TRUST Platform: Constituant Class Reference
Constituant Class Reference
Public Member Functions
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Elle contient un champ alpha representant le coefficient de diffusion du constituant. Lorsqu'un objet de type Constituant represente plusieurs constituant le champ alpha est vectoriel avec autant de composantes qu'il y a de constituants.
See also
Milieu_base
Member Function Documentation
set_param()
void Constituant::set_param (Param & param) override virtual
Reimplemented from Milieu_base.
References Param::ajouter(), Param::ajouter_non_std(), Param::REQUIRED, and Milieu_base::set_param().
diffusivite_constituant()
const Champ_Don_base& Constituant::diffusivite_constituant () const inline
Referenced by TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::create_constituants_echaines(), Convection_Diffusion_Concentration::diffusivite_pour_transport(), and TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::lire_resize_medium().
mettre_a_jour()
void Constituant::mettre_a_jour (double temps) inline override virtual
Reimplemented from Milieu_base.
Referenced by Convection_Diffusion_Concentration::mettre_a_jour().
discretiser()
void Constituant::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Milieu_base.
References discretiser_multi_concentration().
discretiser_multi_concentration()
void Constituant::discretiser_multi_concentration (const Nom & nm, const Probleme_base & pb, const Discretisation_base & dis)
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Milieu_base::champs_compris_, Milieu_base::discretiser(), Equation_base::domaine_dis(), Probleme_base::equation(), and Discretisation_base::nommer_completer_champ_physique().
Referenced by discretiser().
initialiser()
int Constituant::initialiser (const double temps) inline override virtual
Reimplemented from Milieu_base.
Referenced by Convection_Diffusion_Concentration::preparer_calcul().
nb_constituants()
int Constituant::nb_constituants () const inline
References diffusion_multi_scalaire_.
Referenced by Convection_Diffusion_Concentration::discretiser(), and TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::lire_resize_medium().
lire_motcle_non_standard()
int Constituant::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Milieu_base.
References diffusion_multi_scalaire_, and Milieu_base::lire_motcle_non_standard().
OWN_PTR()
Constituant::OWN_PTR (Champ_Don_base) protected
Member Data Documentation
diffusion_multi_scalaire_
bool Constituant::diffusion_multi_scalaire_ = false protected
Referenced by lire_motcle_non_standard(), and nb_constituants().