CEA TRUST Platform: Prepro_IBM_base Class Reference
Prepro_IBM_base Class Reference
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Function Documentation
set_param()
void Prepro_IBM_base::set_param (Param & param)
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), c_prepro_, eps_, Param::OPTIONAL, and save_prepro_.
lire_motcle_non_standard()
int Prepro_IBM_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Process::abort(), c_prepro_, Objet_U::dimension, dimTab_, eps_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
OWN_PTR() [1/8]
Prepro_IBM_base::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [2/8]
Prepro_IBM_base::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [3/8]
Prepro_IBM_base::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [4/8]
Prepro_IBM_base::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [5/8]
Prepro_IBM_base::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [6/8]
Prepro_IBM_base::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [7/8]
Prepro_IBM_base::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [8/8]
Prepro_IBM_base::OWN_PTR (Champ_Don_base) protected
Friends And Related Function Documentation
Source_PDF_base
friend class Source_PDF_base friend
Interpolation_IBM_base
friend class Interpolation_IBM_base friend
Member Data Documentation
eps_
double Prepro_IBM_base::eps_ = 1.0e-12 protected
Referenced by lire_motcle_non_standard(), and set_param().
c_prepro_
double Prepro_IBM_base::c_prepro_ = 0. protected
Referenced by lire_motcle_non_standard(), and set_param().
dimTab_
IntTab Prepro_IBM_base::dimTab_ protected
Referenced by lire_motcle_non_standard().
save_prepro_
bool Prepro_IBM_base::save_prepro_ = false protected
Referenced by set_param().
champ_aire_
Prepro_IBM_base::champ_aire_ protected