CEA TRUST Platform: Op_EF_base Class Reference
Op_EF_base Class Reference
Public Member Functions
void dimensionner (const Domaine_EF &, const Domaine_Cl_EF &, Matrice_Morse &) const
Member Function Documentation
dimensionner()
void Op_EF_base::dimensionner (const Domaine_EF & le_dom, const Domaine_Cl_EF & le_dom_cl, Matrice_Morse & la_matrice) const
Dimensionnement de la matrice qui devra recevoir les coefficients provenant de la convection, de la diffusion pour le cas des faces.
Cette matrice a une structure de matrice morse. Nous commencons par calculer les tailles des tableaux tab1 et tab2.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Matrice_Morse::dimensionner(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Process::exit(), Champ_front_calc_interne::face_map(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Cond_lim_base::frontiere_dis(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Matrice_Morse::imprimer_formatte(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_32_64< _SIZE_ >::les_elems(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), matrice_sto_, Process::mp_sum(), Matrice_Morse::nb_colonnes(), Domaine_Cl_dis_base::nb_cond_lim(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Front_VF::nb_faces(), Domaine_dis_base::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_VF::nb_som_face(), Domaine_dis_base::nb_som_tot(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Echange_impose_base::T_ext(), and Champ_Inc_base::valeurs().
Referenced by Op_Conv_EF::dimensionner(), Op_Diff_EF::dimensionner(), and Op_Dift_EF_Q1::dimensionner().
modifier_pour_Cl()
void Op_EF_base::modifier_pour_Cl (const Domaine_EF & le_dom, const Domaine_Cl_EF & le_dom_cl, Matrice_Morse & la_matrice, DoubleTab & secmem) const
Modification des coef de la matrice et du second membre pour les conditions de Dirichlet.
References Matrice_Morse::coef(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Process::exit(), Domaine_VF::face_sommets(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nature_du_champ(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Dirichlet::val_imp(), Dirichlet_homogene::val_imp(), and Champ_Inc_base::valeurs().
Referenced by Op_Conv_EF::modifier_pour_Cl(), Op_Diff_EF::modifier_pour_Cl(), and Op_Dift_EF_Q1::modifier_pour_Cl().
modifier_flux()
void Op_EF_base::modifier_flux (const Operateur_base & op) const
multiplie le flux bordpar rho cp ou rho si necessaire
References Nom::debute_par(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Equation_base::domaine_dis(), MorEqn::equation(), Operateur_base::flux_bords(), Milieu_base::masse_volumique(), Probleme_base::milieu(), Equation_base::milieu(), Domaine_VF::nb_faces_bord(), Equation_base::probleme(), Objet_U::que_suis_je(), and Champ_Proto::valeurs().
Referenced by Op_Diff_EF::ajouter_bords(), and Op_Dift_EF_Q1::ajouter_bords().
impr()
int Op_EF_base::impr (Sortie & os, const Operateur_base & op) const
Impression des flux d'un operateur EF aux faces (ie: diffusion, convection)
References Sortie::add_col(), Domaine_VF::calculer_xgr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), MorEqn::equation(), Process::exit(), Operateur_base::flux_bords(), Equation_base::inconnue(), Process::je_suis_maitre(), Field_base::le_nom(), Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_base::moments_a_imprimer(), Process::mp_sum(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), EcrFicPartage::syncfile(), Schema_Temps_base::temps_courant(), and Domaine_VF::xv().
Referenced by Op_Conv_EF_base::impr(), and Op_Diff_EF_base::impr().
elem_contribue()
int Op_EF_base::elem_contribue (const int elem) const
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), and Op_Conv_EF::calculer_dt_stab().
marque_elem()
void Op_EF_base::marque_elem (const Equation_base & eqn)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::get_champ(), Equation_base::has_champ(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Champ_Proto::valeurs().
Referenced by Op_Conv_EF_base::completer(), Op_Diff_EF::completer(), and Op_Dift_EF_base::completer().
Member Data Documentation
matrice_sto_
Matrice_Morse Op_EF_base::matrice_sto_ protected
Referenced by dimensionner().