CEA TRUST Platform: Op_Diff_PolyMAC_Face Class Reference
Op_Diff_PolyMAC_Face Class Reference
#include <Op_Diff_PolyMAC_Face.h>
Member Function Documentation
completer()
void Op_Diff_PolyMAC_Face::completer () override
References Process::exit(), Champ_Face_PolyMAC::init_ra(), TRUST_Ref_Objet_U::valeur(), and Modele_turbulence_hyd_base::viscosite_turbulente().
ajouter()
DoubleTab & Op_Diff_PolyMAC_Face::ajouter (const DoubleTab & inco, DoubleTab & resu) const inline override
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_Face_base::fcl(), Champ_Face_PolyMAC::racf, Champ_Face_PolyMAC::raci, Champ_Face_PolyMAC::radeb, Champ_Face_PolyMAC::rajf, and Champ_Face_PolyMAC::raji.
contribuer_a_avec()
void Op_Diff_PolyMAC_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override
References Champ_Face_base::fcl(), Champ_Face_PolyMAC::raci, Champ_Face_PolyMAC::radeb, and Champ_Face_PolyMAC::raji.
modifier_pour_Cl()
void Op_Diff_PolyMAC_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override
dimensionner()
void Op_Diff_PolyMAC_Face::dimensionner (Matrice_Morse & mat) const override
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Champ_Face_base::fcl(), Champ_Face_PolyMAC::radeb, and Champ_Face_PolyMAC::raji.