CEA TRUST Platform: Matrice_Bloc Class Reference
Matrice_Bloc Class Reference
#include <Matrice_Bloc.h>
Public Member Functions
void block_to_morse (Matrice_Morse &matrix) const
Public Member Functions inherited from Matrice_Base
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Matrice_Bloc()
Matrice_Bloc::Matrice_Bloc (int N = 0, int M = 0)
References dimensionner(), and Matrice_Base::is_stencil_up_to_date_.
Member Function Documentation
ordre()
int Matrice_Bloc::ordre () const override virtual
If square matrix, returns number of lines, otherwise 0.
Implements Matrice_Base.
References M_, and N_.
nb_lignes()
int Matrice_Bloc::nb_lignes () const override virtual
Return local number of lines (=size on the current proc)
Implements Matrice_Base.
References get_bloc(), M_, and N_.
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), build_stencil(), check_block_matrix_structure(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), get_stencil(), Matrice_Bloc_Sym::get_stencil(), Matrice_Bloc_Sym::get_stencil_and_coefficients(), get_stencil_coeff_templ(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), and SETS::iterer_NS().
nb_colonnes()
int Matrice_Bloc::nb_colonnes () const override virtual
Return local number of columns (=size on the current proc)
Implements Matrice_Base.
References get_bloc(), and M_.
Referenced by check_block_matrix_structure(), and Matrice_Bloc_Sym::check_symmetric_block_matrix_structure().
ajouter_multvect_()
DoubleVect & Matrice_Bloc::ajouter_multvect_ (const DoubleVect & x, DoubleVect & r) const override virtual
Implements Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), get_bloc(), M_, N_, TRUSTVect< _TYPE_, _SIZE_ >::ref_data(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
ajouter_multvectT_()
DoubleVect & Matrice_Bloc::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & r) const override virtual
Implements Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), get_bloc(), M_, N_, TRUSTVect< _TYPE_, _SIZE_ >::ref_data(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
ajouter_multTab_()
DoubleTab & Matrice_Bloc::ajouter_multTab_ (const DoubleTab & x, DoubleTab & r) const override virtual
Implements Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
References Process::exit().
scale()
void Matrice_Bloc::scale (const double x) override virtual
Implements Matrice_Base.
References get_bloc(), nb_bloc_colonnes(), nb_bloc_lignes(), and Matrice_Base::scale().
Referenced by operator*=().
clean()
void Matrice_Bloc::clean () override virtual
Reimplemented from Matrice_Base.
References blocs_non_nuls_, Matrice_Base::clean(), Matrice_Base::is_stencil_up_to_date_, and nb_blocs_.
get_stencil()
void Matrice_Bloc::get_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
References assert_check_block_matrix_structure(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_bloc(), Matrice_Base::get_stencil(), Matrice_Base::is_stencil_up_to_date_, nb_bloc_colonnes(), nb_bloc_lignes(), Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), nb_lignes(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Matrice_Base::stencil_, and VECT().
get_stencil_and_coefficients()
void Matrice_Bloc::get_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Matrice_Base::is_stencil_up_to_date_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Matrice_Base::stencil_.
get_stencil_and_coeff_ptrs()
void Matrice_Bloc::get_stencil_and_coeff_ptrs (IntTab & stencil, std::vector< const double * > & coeff_ptr) const override virtual
Reimplemented from Matrice_Base.
References Process::abort(), and Matrice_Base::is_stencil_up_to_date_.
imprimer()
Sortie & Matrice_Bloc::imprimer (Sortie & s) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
References get_bloc(), M_, and N_.
imprimer_formatte()
Sortie & Matrice_Bloc::imprimer_formatte (Sortie & s) const override virtual
Reimplemented from Matrice_Base.
Reimplemented in Matrice_Bloc_Sym.
References get_bloc(), M_, and N_.
dimensionner()
void Matrice_Bloc::dimensionner (int N, int M) virtual
Reimplemented in Matrice_Bloc_Sym.
References M_, N_, and nb_blocs_.
Referenced by Assembleur_P_EF::assembler_mat(), Matrice_Grossiere::build_matrix(), Assembleur_P_VDF::construire(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), Simple::iterer_eqs(), SETS::iterer_NS(), Matrice_Bloc(), remplir(), remplir(), and Assembleur_P_VEF::remplir().
get_bloc() [1/2]
const Matrice & Matrice_Bloc::get_bloc (int i, int j) const virtual
Reimplemented in Matrice_Bloc_Sym.
References Process::exit(), M_, and N_.
Referenced by ajouter_multvect_(), ajouter_multvectT_(), Assembleur_P_EF::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), Matrice_Grossiere::build_matrix(), build_stencil(), check_block_matrix_structure(), Assembleur_P_VDF::construire(), Solv_Externe::construit_matrice_morse_intermediaire(), Champ_P1NC_implementation::dimensionner_Mat_Bloc_Morse_Sym(), get_stencil(), get_stencil_coeff_templ(), imprimer(), imprimer_formatte(), Simple::iterer_eqs(), SETS::iterer_NS(), Solveur_U_P::iterer_NS(), Champ_P1NC_implementation::Mat_Morse_to_Mat_Bloc(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), nb_colonnes(), nb_lignes(), SSOR::preconditionner_(), ILU_SP::prepare_(), Precond_local::prepare_(), Solv_GCP::prepare_data(), remplir(), remplir(), remplir(), Assembleur_P_VEF::remplir(), Assembleur_P_VDF::remplir(), Solv_Cholesky::resoudre_systeme(), Solv_Gen::resoudre_systeme(), Solv_Gmres::resoudre_systeme(), Multigrille_base::resoudre_systeme_template(), scale(), and SSOR::ssor().
get_bloc() [2/2]
Matrice & Matrice_Bloc::get_bloc (int i, int j) virtual
Reimplemented in Matrice_Bloc_Sym.
References Process::exit(), M_, and N_.
build_stencil()
void Matrice_Bloc::build_stencil () override virtual
Reimplemented from Matrice_Base.
References blocs_non_nuls_, column_offsets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_bloc(), Matrice_Base::get_stencil(), Matrice_Base::is_stencil_up_to_date_, line_offsets_, nb_bloc_colonnes(), nb_bloc_lignes(), Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), nb_lignes(), offsets_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Matrice_Base::stencil_, and VECT().
dim()
int Matrice_Bloc::dim (int d) const
References M_, and N_.
nb_bloc_lignes()
int Matrice_Bloc::nb_bloc_lignes () const
References N_.
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), build_stencil(), check_block_matrix_structure(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), get_stencil(), get_stencil_coeff_templ(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), PrecondA::preconditionner_(), Solv_Cholesky::resoudre_systeme(), Solv_Gmres::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), scale(), and SSOR::ssor().
nb_bloc_colonnes()
int Matrice_Bloc::nb_bloc_colonnes (void) const
References M_.
Referenced by build_stencil(), check_block_matrix_structure(), Matrice_Bloc_Sym::check_symmetric_block_matrix_structure(), get_stencil(), get_stencil_coeff_templ(), Matrice_Bloc_Sym::get_symmetric_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients(), PrecondA::preconditionner_(), Solv_GCP_NS::resoudre_systeme(), and scale().
remplir() [1/3]
void Matrice_Bloc::remplir (const IntLists & voisins, const DoubleLists & valeurs, const DoubleVect & terme_diag, const int i, const int n)
References dimensionner(), get_bloc(), and remplir().
Referenced by remplir(), and remplir().
remplir() [2/3]
void Matrice_Bloc::remplir (const IntLists & voisins, const DoubleLists & valeurs, const int i, const int n, const int j, const int m)
References dimensionner(), get_bloc(), and remplir().
remplir() [3/3]
void Matrice_Bloc::remplir (const IntLists & voisins, const DoubleLists & valeurs, const DoubleVect & terme_diag, const int i, const int n, const int j, const int m)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Matrice_Morse::compacte(), Matrice_Morse::dimensionner(), Matrice_Morse::formeF(), get_bloc(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
block_to_morse()
void Matrice_Bloc::block_to_morse (Matrice_Morse & result) const
Remplissage d'une Matrice_Morse par une Matrice_Bloc de Matrice_Morse quelconques
References Matrix_tools::convert_to_morse_matrix().
block_to_morse_with_ptr()
void Matrice_Bloc::block_to_morse_with_ptr (Matrice_Morse & result, std::vector< const double * > & coeffs) const
References Matrix_tools::convert_to_morse_matrix_with_ptrs().
BlocToMatMorse()
void Matrice_Bloc::BlocToMatMorse (Matrice_Morse & matrix) const
References Matrix_tools::convert_to_morse_matrix().
Referenced by Solv_Externe::construit_matrice_morse_intermediaire().
operator*=()
Matrice_Bloc & Matrice_Bloc::operator*= (double x)
References scale().
check_block_matrix_structure()
bool Matrice_Bloc::check_block_matrix_structure () const
References get_bloc(), nb_bloc_colonnes(), nb_bloc_lignes(), nb_colonnes(), and nb_lignes().
Referenced by assert_check_block_matrix_structure().
assert_check_block_matrix_structure()
void Matrice_Bloc::assert_check_block_matrix_structure () const
References check_block_matrix_structure(), and Process::exit().
Referenced by get_stencil(), and get_stencil_coeff_templ().
VECT()
Matrice_Bloc::VECT (Matrice) protected
Referenced by build_stencil(), get_stencil(), Matrice_Bloc_Sym::get_symmetric_stencil(), and Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients().
get_stencil_coeff_templ()
template<typename _TAB_T_ , typename _VAL_T_ > void Matrice_Bloc::get_stencil_coeff_templ (IntTab & stencil, _TAB_T_ & coeff_sp) const protected
References assert_check_block_matrix_structure(), blocs_non_nuls_, column_offsets_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), get_bloc(), Matrice_Base::is_stencil_up_to_date_, line_offsets_, nb_bloc_colonnes(), nb_bloc_lignes(), Matrice_Base::nb_colonnes(), Matrice_Base::nb_lignes(), nb_lignes(), offsets_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Matrice_Base::stencil_.
Member Data Documentation
blocs_non_nuls_
std::vector<Matrice_Base*> Matrice_Bloc::blocs_non_nuls_ protected
Referenced by build_stencil(), clean(), and get_stencil_coeff_templ().
N_
int Matrice_Bloc::N_ protected
Referenced by ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), ajouter_multvectT_(), dim(), dimensionner(), Matrice_Bloc_Sym::dimensionner(), get_bloc(), get_bloc(), Matrice_Bloc_Sym::get_bloc(), Matrice_Bloc_Sym::get_bloc(), imprimer(), Matrice_Bloc_Sym::imprimer(), imprimer_formatte(), Matrice_Bloc_Sym::imprimer_formatte(), nb_bloc_lignes(), nb_lignes(), and ordre().
M_
int Matrice_Bloc::M_ protected
Referenced by ajouter_multvect_(), ajouter_multvectT_(), dim(), dimensionner(), Matrice_Bloc_Sym::dimensionner(), get_bloc(), get_bloc(), Matrice_Bloc_Sym::get_bloc(), Matrice_Bloc_Sym::get_bloc(), imprimer(), Matrice_Bloc_Sym::imprimer(), imprimer_formatte(), Matrice_Bloc_Sym::imprimer_formatte(), nb_bloc_colonnes(), nb_colonnes(), nb_lignes(), and ordre().
nb_blocs_
int Matrice_Bloc::nb_blocs_ protected
Referenced by clean(), dimensionner(), Matrice_Bloc_Sym::dimensionner(), Matrice_Bloc_Sym::get_symmetric_stencil(), and Matrice_Bloc_Sym::get_symmetric_stencil_and_coefficients().
offsets_
ArrOfInt Matrice_Bloc::offsets_ protected
Referenced by build_stencil(), and get_stencil_coeff_templ().
line_offsets_
std::vector<int> Matrice_Bloc::line_offsets_ protected
Referenced by build_stencil(), and get_stencil_coeff_templ().
column_offsets_
std::vector<int> Matrice_Bloc::column_offsets_ protected
Referenced by build_stencil(), and get_stencil_coeff_templ().