CEA TRUST Platform: Partitionneur_base_32_64< _SIZE_ > Class Template Reference
Partitionneur_base_32_64< _SIZE_ > Class Template Reference abstract
Public Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static int_t calculer_graphe_connexions_periodiques (const Domaine_t &domaine, const Noms &liste_bords_periodiques, const Static_Int_Lists_t &som_elem, const int_t my_offset, Static_Int_Lists_t &graph)
static int_t corriger_bords_avec_graphe (const Static_Int_Lists_t &graph_elements_perio, const Static_Int_Lists_t &som_elem, const Domaine_t &domaine, const Noms &liste_bords_perio, BigIntVect_ &elem_part)
static void corriger_bords_avec_liste (const Domaine_t &dom, const Noms &liste_bords_periodiques, const int_t my_offset, BigIntVect_ &elem_part)
static void corriger_elem0_sur_proc0 (BigIntVect_ &elem_part)
static int_t corriger_multiperiodique (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
static int_t corriger_sommets_bord (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Additional Inherited Members
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Partitionneur_base_32_64< _SIZE_ >
Cette classe decrit l'interface commune a tous les partitionneurs: Exemple :
// Creation d'un instance de la classe: Partitionneur_xxx part; // Association du domaine de calcul a decouper part.associer_domaine(domaine); // Initialisation des parametres specifiques a la classe derivee! fichier_data >> part; // Lecture des parametres dans le jdd ou part.initialiser(nb_parties); // Initialisation directe (depend de la classe) // Si besoin : part.declarer_bords_periodiques(liste_noms_bords_perio); // Construction du tableau de decoupage: ArrOfInt elem_part; part.construire_partition(elem_part);
ATTENTION: en principe, l'implementation de la methode construire_partition() doit assurer que le decoupage est valide (application des corrections pour les bords periodiques et autres...)
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Partitionneur_base_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Partitionneur_base_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntVect_t
template<typename _SIZE_ > using Partitionneur_base_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Partitionneur_base_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Partitionneur_base_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Static_Int_Lists_t
template<typename _SIZE_ > using Partitionneur_base_32_64< _SIZE_ >::Static_Int_Lists_t = Static_Int_Lists_32_64<_SIZE_>
Bord_t
template<typename _SIZE_ > using Partitionneur_base_32_64< _SIZE_ >::Bord_t = Bord_32_64<_SIZE_>
BigArrOfInt_
template<typename _SIZE_ > using Partitionneur_base_32_64< _SIZE_ >::BigArrOfInt_ = TRUSTArray<int, _SIZE_>
BigIntVect_
template<typename _SIZE_ > using Partitionneur_base_32_64< _SIZE_ >::BigIntVect_ = TRUSTVect<int, _SIZE_>
Member Function Documentation
set_param()
template<typename _SIZE_ > virtual void Partitionneur_base_32_64< _SIZE_ >::set_param (Param & param) pure virtual
Implemented in Partitionneur_Union, Partitionneur_Tranche_32_64< _SIZE_ >, Partitionneur_Sous_Domaines, Partitionneur_Sous_Domaine, Partitionneur_Ptscotch, Partitionneur_Partition, Partitionneur_Parmetis, Partitionneur_Metis_32_64< _SIZE_ >, Partitionneur_Fichier_MED, and Partitionneur_Fichier_Decoupage.
lire_motcle_non_standard()
template<typename _SIZE_ > int Partitionneur_base_32_64< _SIZE_ >::lire_motcle_non_standard (const Motcle & motlu, Entree & is) inline override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
Reimplemented in Partitionneur_Ptscotch, Partitionneur_Parmetis, and Partitionneur_Metis_32_64< _SIZE_ >.
Referenced by Partitionneur_Metis_32_64< _SIZE_ >::lire_motcle_non_standard(), Partitionneur_Parmetis::lire_motcle_non_standard(), and Partitionneur_Ptscotch::lire_motcle_non_standard().
associer_domaine()
template<typename _SIZE_ > virtual void Partitionneur_base_32_64< _SIZE_ >::associer_domaine (const Domaine_t & domaine) pure virtual
Implemented in Partitionneur_Tranche_32_64< _SIZE_ >, and Partitionneur_Metis_32_64< _SIZE_ >.
declarer_bords_periodiques()
template<typename _SIZE_ > virtual void Partitionneur_base_32_64< _SIZE_ >::declarer_bords_periodiques (const Noms & noms_bords_periodiques) inline virtual
References Partitionneur_base_32_64< _SIZE_ >::liste_bords_periodiques_.
Referenced by Decouper_32_64< _SIZE_ >::interpreter(), and Decouper_multi::interpreter().
construire_partition()
template<typename _SIZE_ > virtual void Partitionneur_base_32_64< _SIZE_ >::construire_partition (BigIntVect_ & elem_part, int & nb_parts_tot) const pure virtual
Implemented in Partitionneur_Tranche_32_64< _SIZE_ >, and Partitionneur_Metis_32_64< _SIZE_ >.
Referenced by Decouper_32_64< _SIZE_ >::interpreter(), and Decouper_multi::interpreter().
corriger_elem0_sur_proc0()
template<typename _SIZE_ > void Partitionneur_base_32_64< _SIZE_ >::corriger_elem0_sur_proc0 (BigIntVect_ & elem_part) static
corrige la partition pour que l'element 0 du domaine initial se trouve sur le premier sous-domaine de la partition.
On echange le premier sous-domaine et celui qui contient l'element 0.
References TRUSTVect< _TYPE_, _SIZE_ >::size_reelle().
Referenced by Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Parmetis::construire_partition(), and Partitionneur_Ptscotch::construire_partition().
calculer_graphe_connexions_periodiques()
template<typename _SIZE_ > Partitionneur_base_32_64< _SIZE_ >::int_t Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques (const Domaine_t & domaine, const Noms & liste_bords_periodiques, const Static_Int_Lists_t & som_elem, const int_t my_offset, Static_Int_Lists_t & graph) static
Calcul d'un graphe de connectivite entre les elements lies par des faces periodiques.
Si l'element i est voisin de l'element j par une face periodique, alors il existe k tel que graph(i,k)==j et il existe k2 tel que graph(j,k2)==i.
Parameters
(domaine) le domaine a traiter
(liste_bords_periodiques) liste des noms des bords periodiques. ATTENTION: on suppose que les faces des bords periodiques sont rangees selon la convention des bords periodiques. Voir check_faces_periodiques().
(som_elem) la connectivite sommets-elements pour le domaine donnee.
(graph) On y stocke le resultat. Valeur de retour: nombre d'elements dans le graphe (egal au nombre de faces periodiques)
References Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Noms::contient_(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Frontiere_32_64< _SIZE_ >::faces(), Frontiere_32_64< _SIZE_ >::le_nom(), Faces_32_64< _SIZE_ >::les_sommets(), Frontiere_32_64< _SIZE_ >::nb_faces(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Static_Int_Lists_32_64< _SIZE_ >::set_list_sizes(), Static_Int_Lists_32_64< _SIZE_ >::set_value(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Domain_Graph::construire_graph_elem_elem().
corriger_bords_avec_graphe()
template<typename _SIZE_ > Partitionneur_base_32_64< _SIZE_ >::int_t Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_graphe (const Static_Int_Lists_t & graph_elements_perio, const Static_Int_Lists_t & som_elem, const Domaine_t & domaine, const Noms & liste_bords_perio, BigIntVect_ & elem_part) static
corrige la partition elem_part pour qu'un element i se trouve sur la meme partition elem_part[i] que tous les elements auxquels il est lie dans le graphe
(elements d'indices graph_elements_perio(i, j) pour tout j).
Parameters
(graph_elements_perio) graphe calcule par la methode calculer_graphe_connexions_periodiques
(elem_part) pour chaque element, a quelle partie appartient-il. Valeur de retour: nombre d'elements dont la partition a ete corrigee.
References Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), Static_Int_Lists_32_64< _SIZE_ >::get_nb_lists(), Process::is_parallel(), and Reordonner_faces_periodiques_32_64< _SIZE_ >::renum_som_perio().
corriger_bords_avec_liste()
template<typename _SIZE_ > void Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_liste (const Domaine_t & dom, const Noms & liste_bords_periodiques, const int_t my_offset, BigIntVect_ & elem_part) static
Calcul des graphes de connectivite elements periodiques et appel a corriger_periodique_avec_graphe.
(Methode a utiliser quand on ne dispose pas encore du graphe de de connectivite, si on a le graphe sous la main, appeler directement corriger_periodique_avec_graphe)
References Domaine_32_64< _SIZE_ >::les_elems(), and Domaine_32_64< _SIZE_ >::nb_som_tot().
Referenced by Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), and Partitionneur_Sous_Domaines::construire_partition().
corriger_sommets_bord()
template<typename _SIZE_ > Partitionneur_base_32_64< _SIZE_ >::int_t Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord (const Domaine_t & domaine, const Noms & liste_bords_perio, const ArrOfInt_t & renum_som_perio, const Static_Int_Lists_t & som_elem, BigIntVect_ & elem_part) static
Modifie elem_part pour assurer les proprietes suivantes : 1) Les elements possedant un sommet de bord sont associes.
a un processeur possedant une face de bord adjacente a ce sommet.
2) Si un processeur possede un sommet periodique reel, il possede forcement le renum_som_perio associe (donc un element qui possede ce sommet et un face periodique). Cette propriete est indispensable pour le periodique (existence de renum_som_perio pour tous les sommets). Pour les autres bords, cette correction est peut-etre inutile, mais pas sur. Sans cette correction, il peut exister des sommets de bord isoles (un processeur possede un sommet de bord mais aucune face). Si on cherche les sommets de bord en parcourant les faces de bord, c'est faux. Avec cette correction, cet algorithme est correct.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Noms::contient_(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Frontiere_32_64< _SIZE_ >::faces(), Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), Frontiere_32_64< _SIZE_ >::le_nom(), Faces_32_64< _SIZE_ >::les_sommets(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
corriger_multiperiodique()
template<typename _SIZE_ > Partitionneur_base_32_64< _SIZE_ >::int_t Partitionneur_base_32_64< _SIZE_ >::corriger_multiperiodique (const Domaine_t & domaine, const Noms & liste_bords_perio, const ArrOfInt_t & renum_som_perio, const Static_Int_Lists_t & som_elem, BigIntVect_ & elem_part) static
applique des corrections a elem_part pour que le multi-periodique soit correct :
Si un sommet appartient a plusieurs frontieres periodiques, tous les elements adjacents sont rattaches au meme processeur.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Frontiere_32_64< _SIZE_ >::faces(), Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), Frontiere_32_64< _SIZE_ >::le_nom(), Faces_32_64< _SIZE_ >::les_sommets(), and TRUSTLists< _TYPE_ >::size().
Member Data Documentation
liste_bords_periodiques_
template<typename _SIZE_ > Noms Partitionneur_base_32_64< _SIZE_ >::liste_bords_periodiques_ protected
Referenced by Partitionneur_Fichier_Decoupage::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_Sous_Domaines::construire_partition(), and Partitionneur_base_32_64< _SIZE_ >::declarer_bords_periodiques().