CEA TRUST Platform: Masse_VDF_base Class Reference
Masse_VDF_base Class Reference
#include <Masse_VDF_base.h>
Additional Inherited Members
Public Member Functions inherited from Solveur_Masse_base
virtual DoubleTab & appliquer (DoubleTab &) const
virtual void assembler ()
virtual void mettre_a_jour (double temps)
virtual void resetTime (double temps)
void set_name_of_coefficient_temporel (const Nom &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
check_multiphase_compatibility()
void Masse_VDF_base::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
associer_domaine_dis_base()
void Masse_VDF_base::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis_base) override virtual
Implements Solveur_Masse_base.
associer_domaine_cl_dis_base()
void Masse_VDF_base::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis_base) override virtual
Implements Solveur_Masse_base.
has_interface_blocs()
int Masse_VDF_base::has_interface_blocs () const inline override virtual
Reimplemented from Solveur_Masse_base.
dimensionner_blocs()
void Masse_VDF_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Solveur_Masse_base.
Reimplemented in Masse_VDF_Face, and Masse_VDF_Elem.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Matrice_Morse::dimensionner(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Inc_base::valeurs().
Referenced by Masse_VDF_Face::dimensionner_blocs(), and Masse_VDF_Elem::dimensionner_blocs().
ajouter_blocs()
void Masse_VDF_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const override virtual
Reimplemented from Solveur_Masse_base.
Reimplemented in Masse_VDF_Elem, and Masse_VDF_Face.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Solveur_Masse_base::appliquer(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_max(), Champ_Inc_base::passe(), Solveur_Masse_base::penalisation_flag_, penalisation_matrice_, penalisation_secmem_, and Champ_Inc_base::valeurs().
Referenced by Masse_VDF_Elem::ajouter_blocs(), and Masse_VDF_Face::ajouter_blocs().
OBS_PTR() [1/2]
Masse_VDF_base::OBS_PTR (Domaine_Cl_VDF) protected
OBS_PTR() [2/2]
Masse_VDF_base::OBS_PTR (Domaine_VDF) protected
Member Data Documentation
penalisation_matrice_
double Masse_VDF_base::penalisation_matrice_ mutable protected
Referenced by ajouter_blocs().
penalisation_secmem_
double Masse_VDF_base::penalisation_secmem_ protected
Referenced by ajouter_blocs().