CEA TRUST Platform: Comm_Group_MPI Class Reference
Comm_Group_MPI Class Reference
Public Member Functions
void barrier (int tag) const override
Comm_Group_MPI ()
void send (int pe, const void *buffer, int size, int tag) const override
void send_recv_start (const ArrOfInt &send_list, const ArrOfInt &send_size, const char *const *const send_buffers, const ArrOfInt &recv_list, const ArrOfInt &recv_size, char *const *const recv_buffers, TypeHint typehint=CHAR) const override
Public Member Functions inherited from Comm_Group
int get_new_tag () const
int rank () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Comm_Group
virtual void init_group (const ArrOfInt &pe_list)
void init_group_node (int nproc, int loc_rank, int glob_rank)
void init_group_trio (int nproc, int rank)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe represente un groupe de communication qui repose sur MPI.
Construction de l'objet : voir init_group_trio() pour le groupe_TRUST et init_group() pour les autres.
Constructor & Destructor Documentation
Comm_Group_MPI()
Comm_Group_MPI::Comm_Group_MPI ()
Constructeur par defaut.
Il faut ensuite appeler init_group() ou init_group_trio() pour finir la construction du groupe.
~Comm_Group_MPI()
Comm_Group_MPI::~Comm_Group_MPI () override
Member Function Documentation
abort()
void Comm_Group_MPI::abort () const override virtual
appel a MPI_Abort et rend la main
Implements Comm_Group.
mp_collective_op() [1/6]
void Comm_Group_MPI::mp_collective_op (const double * x, double * resu, int n, Collective_Op op) const override virtual
Implements Comm_Group.
mp_collective_op() [2/6]
void Comm_Group_MPI::mp_collective_op (const double * x, double * resu, const Collective_Op * op, int n) const override virtual
Implements Comm_Group.
mp_collective_op() [3/6]
void Comm_Group_MPI::mp_collective_op (const float * x, float * resu, int n, Collective_Op op) const override virtual
Implements Comm_Group.
mp_collective_op() [4/6]
void Comm_Group_MPI::mp_collective_op (const float * x, float * resu, const Collective_Op * op, int n) const override virtual
Implements Comm_Group.
mp_collective_op() [5/6]
void Comm_Group_MPI::mp_collective_op (const int * x, int * resu, int n, Collective_Op op) const override virtual
Implements Comm_Group.
mp_collective_op() [6/6]
void Comm_Group_MPI::mp_collective_op (const int * x, int * resu, const Collective_Op * op, int n) const override virtual
Implements Comm_Group.
barrier()
void Comm_Group_MPI::barrier (int tag) const override virtual
Point de synchronisation de tous les processeurs du groupe (permet de verifier que tout le monde est la.
..). Si check_enabled() est non nul, on utilise le tag pour verifier que tous les processeurs sont bien en train d'attendre le meme tag, sinon c'est une barriere simple. Le tag doit verifier 0 <= tag < max_tag (soit 32).
Implements Comm_Group.
References Perf_counters::begin_count().
send_recv_start()
void Comm_Group_MPI::send_recv_start (const ArrOfInt & send_list, const ArrOfInt & send_size, const char *const *const send_buffers, const ArrOfInt & recv_list, const ArrOfInt & recv_size, char *const *const recv_buffers, TypeHint typehint = CHAR) const override virtual
Demarre l'envoi et la reception des buffers.
Les buffers doivent rester valide jusqu'au retour de send_recv_finish(). Le graphe de communication et la taille des buffers doivent etre corrects !
send_list : liste des processeurs (numerotation sur groupe courant) a qui envoyer send_size : taille en octets de chaque message send_buffers : adresse des donnees a envoyer. recv_... : idem pour les donnees en reception.
Implements Comm_Group.
References Perf_counters::begin_count().
send_recv_finish()
void Comm_Group_MPI::send_recv_finish () const override virtual
Attend que l'ensemble des communications lancees par send_recv_start soient finie.
Implements Comm_Group.
References Perf_counters::end_count().
send()
void Comm_Group_MPI::send (int pe, const void * buffer, int size, int tag) const override virtual
Envoi blocant.
Pour etre bien certain que le code est safe, on force une communication synchrone pour forcer le blocage en mode check (voir check_enabled()). Sinon, on utilise MPI_Send qui est en general non blocant pour les petits messages (donc de meilleures performances).
Implements Comm_Group.
References Perf_counters::begin_count().
recv()
void Comm_Group_MPI::recv (int pe, void * buffer, int size, int tag) const override virtual
Reception blocante d'un message.
Implements Comm_Group.
References Perf_counters::begin_count().
broadcast()
void Comm_Group_MPI::broadcast (void * buffer, int size, int pe_source) const override virtual
Implements Comm_Group.
References Perf_counters::begin_count().
all_to_all()
void Comm_Group_MPI::all_to_all (const void * src_buffer, void * dest_buffer, int data_size) const override virtual
Implements Comm_Group.
References Perf_counters::begin_count().
all_gather()
void Comm_Group_MPI::all_gather (const void * src_buffer, void * dest_buffer, int data_size) const override virtual
Implements Comm_Group.
References Perf_counters::begin_count().
gather()
void Comm_Group_MPI::gather (const void * src_buffer, void * dest_buffer, int data_size, int root) const override virtual
Implements Comm_Group.
References Perf_counters::begin_count().
all_gatherv()
void Comm_Group_MPI::all_gatherv (const void * src_buffer, void * dest_buffer, int send_size, const True_int * recv_size, const True_int * displs) const override virtual
Implements Comm_Group.
References Perf_counters::begin_count().