CEA TRUST Platform: Marqueur_Lagrange_base Class Reference
Marqueur_Lagrange_base Class Reference abstract
#include <Marqueur_Lagrange_base.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Actuellement une seule classe instanciable derivant : Marqueur_FT
Un marqueur est destine a suivre le mouvement du fluide en integrant la trajectoire
d un ensemble de particules a partir de la vitesse (interpolee) du fluide.
-l ensemble des points suivis est attribut de Marqueur_FT car de type Maillage_FT_Disc
-le postraitement est realise sur le nombre de particules par maille (densite_particules_)
 ou sur le nuage de points
-l integration est demarree a partir d un temps t_debut_integr_ fixe par l utilisateur
   ou egal a t_init par defaut
See also
Classe abstraite., Methodes abstraites:, Ensemble_Lagrange_base& ensemble_points(), void calculer_valeurs_champs()
Constructor & Destructor Documentation
Marqueur_Lagrange_base()
Marqueur_Lagrange_base::Marqueur_Lagrange_base ()
References t_debut_integr_.
Member Function Documentation
ensemble_points() [1/2]
virtual Ensemble_Lagrange_base & Marqueur_Lagrange_base::ensemble_points () pure virtual
Referenced by discretiser().
ensemble_points() [2/2]
virtual const Ensemble_Lagrange_base & Marqueur_Lagrange_base::ensemble_points () const pure virtual
calculer_valeurs_champs()
virtual void Marqueur_Lagrange_base::calculer_valeurs_champs () pure virtual
Referenced by mettre_a_jour().
temps_debut_integration()
const double & Marqueur_Lagrange_base::temps_debut_integration () const inline
References t_debut_integr_.
discretiser()
void Marqueur_Lagrange_base::discretiser (const Probleme_base & pb, const Discretisation_base & dis) virtual
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Ensemble_Lagrange_base::associer_domaine(), Discretisation_base::discretiser_champ(), Probleme_base::domaine(), Equation_base::domaine_dis(), ensemble_points(), Probleme_base::equation(), Probleme_base::schema_temps(), t_debut_integr_, Schema_Temps_base::temps_courant(), and Schema_Temps_base::temps_init().
mettre_a_jour()
void Marqueur_Lagrange_base::mettre_a_jour (double temps) virtual
References calculer_valeurs_champs().
creer_champ()
void Marqueur_Lagrange_base::creer_champ (const Motcle & motlu) inline override virtual
Implements Champs_compris_interface.
get_champ()
const Champ_base & Marqueur_Lagrange_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::get_champ().
get_noms_champs_postraitables()
void Marqueur_Lagrange_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
has_champ() [1/2]
bool Marqueur_Lagrange_base::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
References Champs_compris_T< FIELD_TYPE >::has_champ().
has_champ() [2/2]
bool Marqueur_Lagrange_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
OWN_PTR()
Marqueur_Lagrange_base::OWN_PTR (Champ_Fonc_base) protected
Member Data Documentation
t_debut_integr_
double Marqueur_Lagrange_base::t_debut_integr_ protected
Referenced by discretiser(), Marqueur_Lagrange_base(), and temps_debut_integration().