CEA TRUST Platform: Op_Diff_PolyMAC_P0P1NC_Face Class Reference
Op_Diff_PolyMAC_P0P1NC_Face Class Reference
Public Member Functions
double calculer_dt_stab () const override
void completer () override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Diff_PolyMAC_P0P1NC_base
void mettre_a_jour (double t) override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
completer()
void Op_Diff_PolyMAC_P0P1NC_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_PolyMAC_P0P1NC_base.
References Op_Diff_PolyMAC_P0P1NC_base::completer(), Objet_U::dimension, MorEqn::equation(), Process::exit(), Operateur_base::flux_bords_, Equation_base::inconnue(), Champ_Face_PolyMAC_P0P1NC::init_auxiliary_variables(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Operateur_Diff_base::op_ext, porosite_e, porosite_f, TRUSTVect< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
modifier_pour_Cl()
void Op_Diff_PolyMAC_P0P1NC_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
has_interface_blocs()
int Op_Diff_PolyMAC_P0P1NC_Face::has_interface_blocs () const inline override virtual
Reimplemented from Op_Diff_PolyMAC_P0P1NC_base.
calculer_dt_stab()
double Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Process::mp_min(), Op_Diff_PolyMAC_Gen_base::nu_, Milieu_base::porosite_elem(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
dimensionner_blocs_ext()
void Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t & semi_impl = { }) const override virtual
Implements Op_Diff_PolyMAC_P0P1NC_base.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Champ_Face_base::fcl(), Nom::getString(), Matrice33::inverse(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Op_Diff_PolyMAC_Gen_base::nu_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), and Champ_Inc_base::valeurs().
ajouter_blocs_ext()
void Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const override virtual
Implements Op_Diff_PolyMAC_P0P1NC_base.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine_Cl_dis(), MorEqn::equation(), Champ_Face_base::fcl(), Nom::getString(), Matrice33::inverse(), Field_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Op_Diff_PolyMAC_Gen_base::nu_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), Op_Diff_PolyMAC_P0P1NC_base::t_last_aux_, Schema_Temps_base::temps_courant(), Op_Diff_PolyMAC_P0P1NC_base::update_aux(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::use_aux_, Champ_Inc_base::valeurs(), and Op_Diff_PolyMAC_P0P1NC_base::var_aux.
check_multiphase_compatibility()
void Op_Diff_PolyMAC_P0P1NC_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Member Data Documentation
porosite_e
DoubleVect Op_Diff_PolyMAC_P0P1NC_Face::porosite_e protected
Referenced by completer().
porosite_f
DoubleVect Op_Diff_PolyMAC_P0P1NC_Face::porosite_f protected
Referenced by completer().