CEA TRUST Platform: ConstTRUSTTab_parts< _TYPE_ > Class Template Reference
ConstTRUSTTab_parts< _TYPE_ > Class Template Reference
Detailed Description
template<typename _TYPE_>
class ConstTRUSTTab_parts< _TYPE_ >
It is designed to preserve the const-ness of the object.
Constructor & Destructor Documentation
ConstTRUSTTab_parts() [1/2]
template<typename _TYPE_ > ConstTRUSTTab_parts< _TYPE_ >::ConstTRUSTTab_parts () inline
ConstTRUSTTab_parts() [2/2]
template<typename _TYPE_ > ConstTRUSTTab_parts< _TYPE_ >::ConstTRUSTTab_parts (const TRUSTVect< _TYPE_ > & vect)
Member Function Documentation
initialize()
template<typename _TYPE_ > void ConstTRUSTTab_parts< _TYPE_ >::initialize (const TRUSTVect< _TYPE_ > & vect)
Referenced by SSOR::ssor().
reset()
template<typename _TYPE_ > void ConstTRUSTTab_parts< _TYPE_ >::reset () inline
References TRUST_Vector< _CLASSE_ >::dimensionner_force().
operator[]()
template<typename _TYPE_ > const TRUSTTab<_TYPE_>& ConstTRUSTTab_parts< _TYPE_ >::operator[] (int i) const inline
size()
template<typename _TYPE_ > int ConstTRUSTTab_parts< _TYPE_ >::size () const inline
References TRUST_Vector< _CLASSE_ >::size().
Referenced by Debog_Pb::ecrire_partie(), SETS::eliminer(), PrecondA::prepare_(), and Debog_Pb::verifier_partie().