CEA TRUST Platform: Op_Dift_VEF_Face_Gen< DERIVED_T > Class Template Reference
Op_Dift_VEF_Face_Gen< DERIVED_T > Class Template Reference
#include <Op_Dift_VEF_Face_Gen.h>
Member Function Documentation
fill_grad_Re()
template<typename DERIVED_T > template<Type_Champ _TYPE_> void Op_Dift_VEF_Face_Gen< DERIVED_T >::fill_grad_Re (const DoubleTab & tab_inconnue, const DoubleTab & tab_resu, const DoubleTab & tab_nu, const DoubleTab & tab_nu_turb) const
modifie_pour_cl_gen()
template<typename DERIVED_T > template<bool _IS_STAB_> void Op_Dift_VEF_Face_Gen< DERIVED_T >::modifie_pour_cl_gen (const DoubleTab & tab_inconnue, DoubleTab & tab_resu, DoubleTab & tab_flux_bords) const
References Periodique::face_associee(), Domaine_VF::face_surfaces(), Neumann::flux_impose(), Echange_impose_base::h_imp(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), and Echange_impose_base::T_ext().
ajouter_bord_gen() [1/2]
template<typename DERIVED_T > template<Type_Champ _TYPE_, bool _IS_RANS_> std::enable_if_t< _TYPE_==Type_Champ::VECTORIEL, void > Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_bord_gen (const DoubleTab & tab_inconnue, DoubleTab & tab_resu, DoubleTab & tab_flux_bords, const DoubleTab & tab_nu, const DoubleTab & tab_nu_turb) const
References Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
ajouter_interne_gen() [1/2]
template<typename DERIVED_T > template<Type_Champ _TYPE_, bool _IS_RANS_> std::enable_if_t< _TYPE_==Type_Champ::VECTORIEL, void > Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_interne_gen (const DoubleTab & tab_inconnue, DoubleTab & tab_resu, DoubleTab & flux_bords, const DoubleTab & tab_nu, const DoubleTab & tab_nu_turb) const
References Domaine_VF::face_normales(), Domaine_VF::face_voisins(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_VF::nb_faces(), and Domaine_VF::premiere_face_int().
ajouter_bord_gen() [2/2]
template<typename DERIVED_T > template<Type_Champ _TYPE_, bool _IS_RANS_> std::enable_if_t< _TYPE_==Type_Champ::SCALAIRE, void > Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_bord_gen (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & tab_flux_bords, const DoubleTab & nu, const DoubleTab & nu_turb) const
References Domaine_Cl_dis_base::les_conditions_limites(), and Domaine_dis_base::nb_front_Cl().
ajouter_interne_gen() [2/2]
template<typename DERIVED_T > template<Type_Champ _TYPE_, bool _IS_RANS_ = false> std::enable_if_t< _TYPE_== Type_Champ::SCALAIRE, void > Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_interne_gen (const DoubleTab & inco, DoubleTab & resu, DoubleTab & , const DoubleTab & nu, const DoubleTab & nu_turb) const inline
ajouter_contribution_bord_gen()
template<typename DERIVED_T > template<Type_Champ _TYPE_, bool _IS_STAB_, bool _IS_RANS_> void Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_contribution_bord_gen (const DoubleTab & transporte, Matrice_Morse & matrice, const DoubleTab & nu, const DoubleTab & nu_turb, const DoubleVect & porosite_eventuelle) const
References Domaine_VF::face_surfaces(), Echange_impose_base::h_imp(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), and Front_VF::num_premiere_face().
ajouter_contribution_interne_gen()
template<typename DERIVED_T > template<Type_Champ _TYPE_, bool _IS_STAB_ = false, bool _IS_RANS_ = false> void Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_contribution_interne_gen (const DoubleTab & inco, Matrice_Morse & mat, const DoubleTab & nu, const DoubleTab & nu_turb, const DoubleVect & porosite_eventuelle) const inline
Member Data Documentation
grad_
template<typename DERIVED_T > DoubleTab Op_Dift_VEF_Face_Gen< DERIVED_T >::grad_ mutable protected
Re_
template<typename DERIVED_T > DoubleTab Op_Dift_VEF_Face_Gen< DERIVED_T >::Re_ protected