CEA TRUST Platform: Op_Diff_PolyMAC_P0P1NC_Elem Class Reference
Op_Diff_PolyMAC_P0P1NC_Elem Class Reference
Public Member Functions
double calculer_dt_stab () const override
void completer () override
void modifier_pour_Cl (Matrice_Morse &la_matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Diff_PolyMAC_P0P1NC_base
void mettre_a_jour (double t) override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Constructor & Destructor Documentation
Op_Diff_PolyMAC_P0P1NC_Elem()
Op_Diff_PolyMAC_P0P1NC_Elem::Op_Diff_PolyMAC_P0P1NC_Elem ()
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
Member Function Documentation
completer()
void Op_Diff_PolyMAC_P0P1NC_Elem::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_PolyMAC_P0P1NC_base.
References Op_Diff_PolyMAC_P0P1NC_base::completer(), MorEqn::equation(), Process::exit(), Operateur_base::flux_bords_, Equation_base::inconnue(), Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
init_op_ext()
void Op_Diff_PolyMAC_P0P1NC_Elem::init_op_ext () const override virtual
Reimplemented from Operateur_Diff_base.
References Equation_base::domaine_Cl_dis(), MorEqn::equation(), Echange_contact_PolyMAC_P0P1NC::init_op(), Domaine_Cl_dis_base::les_conditions_limites(), Echange_contact_PolyMAC_P0P1NC::o_diff, Echange_contact_PolyMAC_P0P1NC::o_idx, and Operateur_Diff_base::op_ext.
Referenced by ajouter_blocs_ext(), and dimensionner_blocs_ext().
calculer_dt_stab()
double Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Process::abort(), Op_Diff_PolyMAC_Gen_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Equation_base::inconnue(), Equation_base::milieu(), Process::mp_min(), Op_Diff_PolyMAC_Gen_base::nu_, Milieu_base::porosite_elem(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
dimensionner_blocs_ext()
void Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t & semi_impl = { }) const override virtual
Implements Op_Diff_PolyMAC_P0P1NC_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Echange_contact_PolyMAC_P0P1NC::f_dist, Champ_Inc_P0_base::fcl(), Nom::getString(), Operateur_base::has_champ_inco(), Equation_base::inconnue(), Echange_contact_PolyMAC_P0P1NC::init_f_dist(), init_op_ext(), Objet_U::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Operateur_base::mon_inconnue(), Process::mp_sum_as_double(), Echange_contact_PolyMAC_P0P1NC::o_diff, Operateur_Diff_base::op_ext, and Champ_Inc_base::valeurs().
ajouter_blocs_ext()
void Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const override virtual
Implements Op_Diff_PolyMAC_P0P1NC_base.
References Process::abort(), TRUSTArray< _TYPE_, _SIZE_ >::addr(), Flux_parietal_base::input_t::alpha, Milieu_base::capacite_calorifique(), Milieu_base::conductivite(), Flux_parietal_base::input_t::Cp, Flux_parietal_base::input_t::D_ch, Flux_parietal_base::input_t::D_h, Milieu_base::diametre_hydraulique_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Flux_parietal_base::output_t::dTf_qpi, Flux_parietal_base::output_t::dTf_qpk, Flux_parietal_base::output_t::dTp_qpi, Flux_parietal_base::output_t::dTp_qpk, MorEqn::equation(), Pb_Multiphase::equation_masse(), Pb_Multiphase::equation_qdm(), Flux_parietal_base::input_t::f, Champ_Inc_P0_base::fcl(), Operateur_base::flux_bords_, Nom::getString(), Operateur_base::has_champ_inco(), Equation_base::inconnue(), init_op_ext(), Flux_parietal_base::input_t::lambda, Objet_U::le_nom(), Milieu_base::masse_volumique(), Probleme_base::milieu(), Operateur_base::mon_inconnue(), Flux_parietal_base::input_t::mu, Flux_parietal_base::input_t::N, Flux_parietal_base::output_t::nonlinear, Operateur_Diff_base::op_ext, Flux_parietal_base::input_t::p, Schema_Temps_base::pas_de_temps(), Champ_Proto::passe(), Champ_Inc_base::passe(), Flux_parietal_base::output_t::qpi, Flux_parietal_base::output_t::qpk, Flux_parietal_base::input_t::rho, Equation_base::schema_temps(), Flux_parietal_base::input_t::T, Op_Diff_PolyMAC_P0P1NC_base::t_last_aux_, Schema_Temps_base::temps_courant(), Flux_parietal_base::input_t::Tp, Op_Diff_PolyMAC_P0P1NC_base::update_aux(), Op_Diff_PolyMAC_P0P1NC_base::use_aux_, Flux_parietal_base::input_t::v, Champ_Inc_base::valeurs(), and Op_Diff_PolyMAC_P0P1NC_base::var_aux.
modifier_pour_Cl()
void Op_Diff_PolyMAC_P0P1NC_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.