CEA TRUST Platform: Turbulence_paroi_base Class Reference
Turbulence_paroi_base Class Reference abstract
Public Member Functions
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
virtual void imprimer_premiere_ligne_ustar (int, const LIST(Nom)&, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const LIST(Nom)&, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Static Public Member Functions
static void typer_lire_turbulence_paroi (OWN_PTR(Turbulence_paroi_base)&, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Additional Inherited Members
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
de calcul des grandeurs turbulentes aux voisinages des parois. Contient une reference a un modele de turbulence.
See also
Paroi_std_hyd_VDF Paroi_std_scal_hyd_VDF, Classe abstraite, Methodes abstraites, void associer(const Domaine_dis_base&, const Domaine_Cl_dis_base&), int init_lois_paroi(), int calculer_hyd(DoubleTab&), int calculer_hyd(DoubleTab& , DoubleTab&)
Member Function Documentation
typer_lire_turbulence_paroi()
void Turbulence_paroi_base::typer_lire_turbulence_paroi (OWN_PTR(Turbulence_paroi_base)& , const Modele_turbulence_hyd_base & , Entree &) static
Lit les caracteristques de la loi de parois a partir d'un flot d'entree.
Format: type_de_loi_de_paroi Les valeurs possibles du type de loi de paroi sont:
"loi_standard_hydr"
"negligeable"
"loi_VanDriest"
References associer(), associer_modele(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Modele_turbulence_hyd_base::equation(), Process::exit(), and Objet_U::que_suis_je().
Referenced by Modele_turbulence_hyd_base::lire_motcle_non_standard().
set_param()
virtual void Turbulence_paroi_base::set_param (Param & param) inline virtual
associer_modele()
void Turbulence_paroi_base::associer_modele (const Modele_turbulence_hyd_base & le_modele) inline
Associe un modele de turbulence a l'objet.
Parameters
(Modele_turbulence_hyd_base& le_modele) le modele de turbulence hydraulique a associer a l'objet
Referenced by typer_lire_turbulence_paroi().
associer()
virtual void Turbulence_paroi_base::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base &) pure virtual
Implemented in Paroi_hyd_base_VEF, Paroi_hyd_base_VDF, and Paroi_hyd_base_EF.
Referenced by typer_lire_turbulence_paroi().
completer()
virtual void Turbulence_paroi_base::completer () inline virtual
init_lois_paroi()
virtual int Turbulence_paroi_base::init_lois_paroi () pure virtual
Implemented in Paroi_negligeable_VEF, Paroi_negligeable_VDF, and Paroi_negligeable_EF.
Referenced by Navier_Stokes_IBM_Turbulent::preparer_calcul(), and Navier_Stokes_Turbulent::preparer_calcul().
calculer_hyd() [1/4]
int Turbulence_paroi_base::calculer_hyd (Champ_Inc_base & ch) inline
Simple appel a int calculer_hyd(DoubleTab&).
Parameters
(Champ_Inc_base& ch)
Returns
(int) code de retour propage
References Champ_Inc_base::valeurs().
Referenced by calculer_hyd().
calculer_hyd() [2/4]
int Turbulence_paroi_base::calculer_hyd (Champ_Fonc_base & ch1, Champ_Fonc_base & ch2) inline
Simple appel a int calculer_hyd(DoubleTab&, DoubleTab&).
Parameters
(Champ_Inc_base& ch1)
(Champ_Inc_base& ch2)
Returns
(int) code de retour propage
References calculer_hyd(), and Champ_Don_base::valeurs().
calculer_hyd() [3/4]
virtual int Turbulence_paroi_base::calculer_hyd (DoubleTab &) pure virtual
Implemented in Paroi_negligeable_VEF, Paroi_negligeable_VDF, and Paroi_negligeable_EF.
calculer_hyd() [4/4]
virtual int Turbulence_paroi_base::calculer_hyd (DoubleTab & , DoubleTab &) pure virtual
Implemented in Paroi_negligeable_VEF, Paroi_negligeable_VDF, and Paroi_negligeable_EF.
calculer_hyd_BiK()
virtual int Turbulence_paroi_base::calculer_hyd_BiK (DoubleTab & , DoubleTab &) pure virtual
Implemented in Paroi_negligeable_VEF, Paroi_negligeable_VDF, and Paroi_negligeable_EF.
corriger_derivee_impl()
virtual DoubleTab& Turbulence_paroi_base::corriger_derivee_impl (DoubleTab & d) const inline virtual
Reimplemented in Paroi_hyd_base_VEF, and Paroi_hyd_base_EF.
imprimer_ustar()
virtual void Turbulence_paroi_base::imprimer_ustar (Sortie &) const inline virtual
imprimer_premiere_ligne_ustar()
void Turbulence_paroi_base::imprimer_premiere_ligne_ustar (int , const LIST(Nom)& , const Nom &) const virtual
Writes header line for u* (friction velocity) statistics file.
Parameters
boundaries_ Flag to control boundary selection (0: all boundaries, 1: specified boundaries)
boundaries_list List of boundary names to process
nom_fichier_ Output filename
Creates header line with column names for u* and d+ statistics. Format: "Time Mean(u*) Mean(d+) [boundary1(u*) boundary1(d+) ...]" Writes warning messages if specified boundaries are not of correct wall type (Dirichlet_paroi_fixe or Dirichlet_paroi_defilante).
References Nom::contient(), Process::je_suis_maitre(), ouvrir_fichier_partage(), and EcrFicPartage::syncfile().
imprimer_ustar_mean_only()
void Turbulence_paroi_base::imprimer_ustar_mean_only (Sortie & , int , const LIST(Nom)& , const Nom &) const virtual
Prints mean friction velocity (u*) statistics to a file for specified boundaries.
Parameters
os Output stream for messages
boundaries_ Flag to control boundary selection (0: all boundaries, 1: specified boundaries)
boundaries_list List of boundary names to process when boundaries_=1
nom_fichier_ Output filename
Calculates and writes average u* (friction velocity) and d+ values for wall boundaries. Results are written for all boundaries combined and then for each boundary separately. Only processes fixed walls (Dirichlet_paroi_fixe) and moving walls (Dirichlet_paroi_defilante). Output format: time mean_u* mean_d+ [boundary1_u* boundary1_d+ boundary2_u* boundary2_d+ ...]
References Nom::contient(), Probleme_base::equation(), Process::je_suis_maitre(), Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), ouvrir_fichier_partage(), Equation_base::probleme(), Probleme_base::schema_temps(), EcrFicPartage::syncfile(), tab_d_plus(), tab_u_star(), and Schema_Temps_base::temps_courant().
Cisaillement_paroi()
const DoubleTab & Turbulence_paroi_base::Cisaillement_paroi () const inline
References Cisaillement_paroi_.
Referenced by Traitement_particulier_NS_canal::calcul_reynolds_tau(), and Champ_P1NC_implementation::filtrer_L2().
tab_u_star() [1/2]
const DoubleVect & Turbulence_paroi_base::tab_u_star () const inline
References tab_u_star_.
Referenced by Paroi_negligeable_VEF::calculer_hyd(), and imprimer_ustar_mean_only().
tab_u_star() [2/2]
double Turbulence_paroi_base::tab_u_star (int face) const inline
References tab_u_star_.
tab_d_plus() [1/2]
const DoubleVect & Turbulence_paroi_base::tab_d_plus () const inline
References tab_d_plus_.
Referenced by Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), and imprimer_ustar_mean_only().
tab_d_plus() [2/2]
double Turbulence_paroi_base::tab_d_plus (int face) const inline
References tab_d_plus_.
sauvegarder()
int Turbulence_paroi_base::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
reprendre()
int Turbulence_paroi_base::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
data_a_sauvegarder()
virtual std::vector<YAML_data> Turbulence_paroi_base::data_a_sauvegarder () const inline virtual
creer_champ()
void Turbulence_paroi_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), champs_compris_, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), and Equation_base::probleme().
get_champ()
const Champ_base & Turbulence_paroi_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champs_compris_, Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champs_compris_T< FIELD_TYPE >::get_champ(), Nom::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Equation_base::schema_temps(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), tab_u_star_, and Schema_Temps_base::temps_courant().
get_noms_champs_postraitables()
void Turbulence_paroi_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References champs_compris_, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
Referenced by Paroi_hyd_base_EF::get_noms_champs_postraitables().
has_champ() [1/2]
bool Turbulence_paroi_base::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
has_champ() [2/2]
bool Turbulence_paroi_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champs_compris_, Champs_compris_T< FIELD_TYPE >::has_champ(), and Nom::le_nom().
ouvrir_fichier_partage() [1/2]
void Turbulence_paroi_base::ouvrir_fichier_partage (EcrFicPartage & Ustar, const Nom & extension) const
Ouverture/creation d'un fichier d'impression de Face, uplus_, dplus_, tab_u_star, Cisaillement_paroi_.
References Probleme_base::equation(), Process::je_suis_maitre(), Probleme_U::le_nom(), nb_impr_, Objet_U::nom_du_cas(), EcrFicPartage::ouvrir(), Equation_base::probleme(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by imprimer_premiere_ligne_ustar(), and imprimer_ustar_mean_only().
ouvrir_fichier_partage() [2/2]
void Turbulence_paroi_base::ouvrir_fichier_partage (EcrFicPartage & fichier, const Nom & nom_fichier, const Nom & extension) const
Ouverture/creation d'un fichier d'impression de moyennes de uplus_, dplus_, tab_u_star.
References Probleme_base::equation(), nb_impr0_, EcrFicPartage::ouvrir(), Equation_base::probleme(), and Probleme_base::reprise_effectuee().
use_shear()
virtual bool Turbulence_paroi_base::use_shear () const inline virtual
Reimplemented in Paroi_negligeable_VEF, Paroi_negligeable_VDF, and Paroi_negligeable_EF.
Referenced by Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), and Champ_Face_VDF::calcul_y_plus().
OBS_PTR() [1/3]
Turbulence_paroi_base::OBS_PTR (Modele_turbulence_hyd_base) protected
OWN_PTR()
Turbulence_paroi_base::OWN_PTR (Champ_Fonc_base) mutable protected
OBS_PTR() [2/3]
Turbulence_paroi_base::OBS_PTR (Domaine_VF) protected
OBS_PTR() [3/3]
Turbulence_paroi_base::OBS_PTR (Domaine_Cl_dis_base) protected
Member Data Documentation
Cisaillement_paroi_
DoubleTab Turbulence_paroi_base::Cisaillement_paroi_ protected
Referenced by Cisaillement_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), and Paroi_hyd_base_VEF::init_lois_paroi_().
tab_u_star_
DoubleVect Turbulence_paroi_base::tab_u_star_ protected
Referenced by Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_hyd_base_EF::get_champ(), get_champ(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), and tab_u_star().
tab_d_plus_
DoubleVect Turbulence_paroi_base::tab_d_plus_ protected
Referenced by Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), and tab_d_plus().
nb_impr_
int Turbulence_paroi_base::nb_impr_ = 0 mutable protected
Referenced by ouvrir_fichier_partage().
nb_impr0_
int Turbulence_paroi_base::nb_impr0_ = 0 protected
Referenced by ouvrir_fichier_partage().
champs_compris_
Champs_compris Turbulence_paroi_base::champs_compris_ protected
Referenced by Paroi_hyd_base_EF::creer_champ(), creer_champ(), Paroi_hyd_base_EF::get_champ(), get_champ(), get_noms_champs_postraitables(), has_champ(), and Paroi_hyd_base_EF::has_champ().