CEA TRUST Platform: Octree_Double_32_64< _SIZE_ > Class Template Reference
Octree_Double_32_64< _SIZE_ > Class Template Reference
Public Member Functions
template<class _TAB_TYPE_ >
void build_elements (const _TAB_TYPE_ &coords, const IntTab_t &elements, const double epsilon, const bool include_virtual)
void build_nodes (const DoubleTab_t &coords, const bool include_virtual, const double epsilon=0.)
int_t search_elements (double x, double y, double z, int_t &index) const
Static Public Member Functions
static int_t search_nodes_close_to (const ArrOfDouble &point, const DoubleTab_t &coords, ArrOfInt_t &node_list, double epsilon)
static int_t search_nodes_close_to (double x, double y, double z, const DoubleTab_t &coords, ArrOfInt_t &node_list, double epsilon)
Protected Member Functions
template<class _TAB_TYPE_ >
void compute_origin_factors (const _TAB_TYPE_ &coords, const double epsilon, const int include_virtual)
bool integer_position (double x, int direction, int &ix) const
Detailed Description
template<typename _SIZE_>
class Octree_Double_32_64< _SIZE_ >
Cet objet est base sur Octree_Int. Astuces: Pour chercher des points a epsilon pres on peut faire: 1) build_nodes(coord, include_virt, 0.) suivi de search_elements_box(center, epsilon, elements);
2) build_nodes(coord, include_virt, epsilon) suivi de search_elements(x,y,z,...) La premiere solution prend plus de temps pour construire l'octree mais la recherche est plus rapide La deuxieme, c'est inverse... et on peut choisir epsilon pour chaque point.
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Octree_Double_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Octree_Double_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Octree_Double_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
ArrOfDouble_t
template<typename _SIZE_ > using Octree_Double_32_64< _SIZE_ >::ArrOfDouble_t = ArrOfDouble_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Octree_Double_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Member Function Documentation
reset()
template<typename _SIZE_ > void Octree_Double_32_64< _SIZE_ >::reset
build_elements()
template<typename _SIZE_ > template<class _TAB_TYPE_ > void Octree_Double_32_64< _SIZE_ >::build_elements (const _TAB_TYPE_ & coords, const IntTab_t & elements, const double epsilon, const bool include_virtual)
Construit un octree a partir d'elements volumiques decrits par des ensembles de sommets.
On stocke dans l'octree les parallelipipdes englobant chaque element (contenant tous les sommets de l'element) plus une marge de epsilon. Si include_virtual=1, on stocke elements.dimension_tot(0) elements, sinon on en stocke elements.dimension(0)
Template car on a besoin de la version float pour lata tools.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
build_nodes()
template<typename _SIZE_ > void Octree_Double_32_64< _SIZE_ >::build_nodes (const DoubleTab_t & coords, const bool include_virtual, const double epsilon = 0.)
construit un octree contenant les points de coordonnees coords.
Si include_virtual=1, on stocke coords.dimension_tot(0) elements, sinon on en stocke coords.dimension(0) Si epsilon = 0, on construit un octree de points de taille nulle (chaque point se trouve dans un seul octree_floor) Sinon, on construit un octree d'elements cubiques centres sur les coords, de demie-largeur epsilon. Un point peut alors se trouver dans plusieurs octree_floor.
Referenced by Debog_Pb::add_renum_item(), Domaine_32_64< _SIZE_ >::ajouter(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Redresser_hexaedres_vdf::interpreter_(), and Domaine_VEF::lecture_ok_arete().
search_elements()
template<typename _SIZE_ > Octree_Double_32_64< _SIZE_ >::int_t Octree_Double_32_64< _SIZE_ >::search_elements (double x, double y, double z, int_t & index) const
cherche les elements ou les points contenus dans l'octree_floor qui contient le point (x,y,z).
Renvoie le nombre n de ces elements. Les indices des elements sont dans floor_elements()[index+i] pour 0 <= i < n
search_elements_box() [1/2]
template<typename _SIZE_ > Octree_Double_32_64< _SIZE_ >::int_t Octree_Double_32_64< _SIZE_ >::search_elements_box (double xmin, double ymin, double zmin, double xmax, double ymax, double zmax, ArrOfInt_t & elements) const
cherche tous les elements ou points ayant potentiellement une intersection non vide avec la boite donnee.
References TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Domaine_32_64< _SIZE_ >::ajouter(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Redresser_hexaedres_vdf::interpreter_(), and Domaine_VEF::lecture_ok_arete().
search_nodes_close_to() [1/2]
template<typename _SIZE_ > Octree_Double_32_64< _SIZE_ >::int_t Octree_Double_32_64< _SIZE_ >::search_nodes_close_to (double x, double y, double z, const DoubleTab_t & coords, ArrOfInt_t & node_list, double epsilon) static
Methode hors classe Cherche parmi les sommets de la liste node_list ceux qui sont a une.
distance inferieure a epsilon du point (x,y,z). node_list contient des indices de sommets dans le tableau coords. La liste des noeuds verifiant le critere est mise dans node_list. On renvoie l'indice dans le tableau coords du sommet le plus proche.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Domaine_32_64< _SIZE_ >::ajouter(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), and Domaine_VEF::lecture_ok_arete().
search_elements_box() [2/2]
template<typename _SIZE_ > Octree_Double_32_64< _SIZE_ >::int_t Octree_Double_32_64< _SIZE_ >::search_elements_box (const ArrOfDouble & center, const double radius, ArrOfInt_t & elements) const
cherche tous les elements ou points ayant potentiellement une intersection non vide avec la boite donnee (centre + ou - radius dans chaque direction)
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
search_nodes_close_to() [2/2]
template<typename _SIZE_ > Octree_Double_32_64< _SIZE_ >::int_t Octree_Double_32_64< _SIZE_ >::search_nodes_close_to (const ArrOfDouble & point, const DoubleTab_t & coords, ArrOfInt_t & node_list, double epsilon) static
Idem que search_nodes_close_to(double x, double y, double z, .
..)
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
dimension()
template<typename _SIZE_ > int Octree_Double_32_64< _SIZE_ >::dimension () const inline
References Octree_Double_32_64< _SIZE_ >::dim_.
floor_elements()
template<typename _SIZE_ > const ArrOfInt_t& Octree_Double_32_64< _SIZE_ >::floor_elements () const inline
References Octree_Double_32_64< _SIZE_ >::octree_int_.
integer_position()
template<typename _SIZE_ > bool Octree_Double_32_64< _SIZE_ >::integer_position (double x, int direction, int & ix) const inline protected
Convertit une coordonnee reelle en coordonnee entiere pour l'octree_int.
Valeur de retour: 1 si ok, 0 si coordonnee hors de l'octree
integer_position_clip()
template<typename _SIZE_ > bool Octree_Double_32_64< _SIZE_ >::integer_position_clip (double xmin, double xmax, int & x0, int & x1, int direction) const inline protected
compute_origin_factors()
template<typename _SIZE_ > template<class _TAB_TYPE_ > void Octree_Double_32_64< _SIZE_ >::compute_origin_factors (const _TAB_TYPE_ & coords, const double epsilon, const int include_virtual) protected
methode outil pour build_nodes et build_elements (calcul des facteurs de conversion entre reels et entiers pour Octree_Int
epsilon est ajoute aux coordonnees min et max pour la bounding box de l'octree.
Template car on a besoin de la version float pour lata tools.
Member Data Documentation
octree_int_
template<typename _SIZE_ > Octree_Int_32_64<_SIZE_> Octree_Double_32_64< _SIZE_ >::octree_int_ protected
Referenced by Octree_Double_32_64< _SIZE_ >::floor_elements().
origin_
template<typename _SIZE_ > ArrOfDouble Octree_Double_32_64< _SIZE_ >::origin_ protected
factor_
template<typename _SIZE_ > ArrOfDouble Octree_Double_32_64< _SIZE_ >::factor_ protected
dim_
template<typename _SIZE_ > int Octree_Double_32_64< _SIZE_ >::dim_ = 0 protected
Referenced by Octree_Double_32_64< _SIZE_ >::dimension().