CEA TRUST Platform: Echange_global_impose_turbulent Class Reference
Echange_global_impose_turbulent Class Reference abstract
Public Member Functions
void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &zcl) override
void associer_fr_dis_base (const Frontiere_dis_base &fr) override
void calculer_coeffs_echange (double temps) override
const Frontiere_dis_base & frontiere_dis () const override
Frontiere_dis_base & frontiere_dis () override
double h_imp (int i) const override
double h_imp (int i, int j) const override
virtual int initialiser (double temps) override
void mettre_a_jour (double tps) override
Champ_front_base & T_ext () override
double T_ext (int i) const override
double T_ext (int i, int k) const override
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Echange_global_impose
int compatible_avec_discr (const Discretisation_base &discr) const override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
double emissivite (int num) const
double emissivite (int num, int k) const
Public Member Functions inherited from Cond_lim_base
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
void set_modifier_val_imp (int)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Classe de base pour les CL turbulentes de type Echange_global_impose Utilisee seulement pour la turbulence de Pb_Multiphase
Member Function Documentation
compatible_avec_eqn()
int Echange_global_impose_turbulent::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Reimplemented from Cond_lim_base.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
initialiser()
int Echange_global_impose_turbulent::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour Contrairementaux methodes mettre_a_jour, les methodes initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Echange_global_impose.
References Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Probleme_base::get_correlation(), h_, h_grad_, Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and T_.
avancer()
virtual int Echange_global_impose_turbulent::avancer (double temps) inline override virtual
Tourne la roue de la CL.
Reimplemented from Echange_global_impose.
mettre_a_jour()
void Echange_global_impose_turbulent::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Echange_global_impose.
References me_calculer(), and mon_temps.
liste_faces_loi_paroi()
void Echange_global_impose_turbulent::liste_faces_loi_paroi (IntTab & tab) override virtual
Reimplemented from Echange_impose_base.
References TRUSTVect< _TYPE_, _SIZE_ >::line_size().
associer_fr_dis_base()
void Echange_global_impose_turbulent::associer_fr_dis_base (const Frontiere_dis_base & fr) inline override virtual
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre OWN_PTR(Champ_front_base) de l'objet Cond_lim_base qui represente le champ des conditions aux limites imposees a la frontiere.
Parameters
(Frontiere_dis_base& fr) la frontiere sur laquelle on impose les conditions aux limites
Reimplemented from Echange_impose_base.
associer_domaine_cl_dis_base()
void Echange_global_impose_turbulent::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & zcl) inline override virtual
Associe le Domaine_Cl_dis_base (Domaine des conditions aux limites discretisees) a l'objet.
Ce Domaine_Cl_dis_base stocke (reference) toutes les conditions aux limites relative a un Domaine geometrique.
Parameters
(Domaine_Cl_dis_base& zcl) un Domaine des conditions aux limites discretisees a laquelle l'objet Cond_lim_base se rapporte
Reimplemented from Cond_lim_base.
fixer_nb_valeurs_temporelles()
void Echange_global_impose_turbulent::fixer_nb_valeurs_temporelles (int nb_cases) inline override virtual
Appele par Conds_lim::completer Appel cha_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Echange_impose_base.
frontiere_dis() [1/2]
Frontiere_dis_base& Echange_global_impose_turbulent::frontiere_dis () inline override virtual
Renvoie la frontiere discretisee a laquelle les conditions aux limites s'appliquent.
Returns
(Frontiere_dis_base&) la frontiere discretisee a laquelle les conditions aux limites sont associees
Reimplemented from Cond_lim_base.
frontiere_dis() [2/2]
const Frontiere_dis_base& Echange_global_impose_turbulent::frontiere_dis () const inline override virtual
Renvoie la frontiere discretisee a laquelle les conditions aux limites s'appliquent.
(version const)
Returns
(Frontiere_dis_base&) la frontiere discretisee a laquelle les conditions aux limites sont associees
Reimplemented from Cond_lim_base.
changer_temps_futur()
void Echange_global_impose_turbulent::changer_temps_futur (double temps, int i) inline override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Echange_global_impose.
set_temps_defaut()
void Echange_global_impose_turbulent::set_temps_defaut (double temps) inline override virtual
Change le i-eme temps futur de la cl.
Reimplemented from Echange_global_impose.
calculer_coeffs_echange()
void Echange_global_impose_turbulent::calculer_coeffs_echange (double temps) inline override virtual
Calcul des coefficient d'echange pour un couplage par Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de l'inconnue. Ils doivent donc etre faits chaque fois que l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et stockes dans les CLs. WEC : Les Champ_front_contact_VEF devraient disparaitre et cette methode avec !!!
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Cond_lim_base.
verifie_ch_init_nb_comp()
void Echange_global_impose_turbulent::verifie_ch_init_nb_comp () const inline override virtual
Appel la verification du champ lu par l intermediaire de l equation pour laquelle on considere la condition limite.
La methode est surchargee dans les cas ou l utilisateur doit specifier le champ frontiere
Reimplemented from Cond_lim_base.
T_ext() [1/4]
Champ_front_base& Echange_global_impose_turbulent::T_ext () inline override virtual
Renvoie le champ T_ext de temperature imposee a la frontiere.
Returns
(Champ_front_base&) le champ T_ext de temperature imposee a la frontiere
Reimplemented from Echange_impose_base.
References Process::exit(), Objet_U::que_suis_je(), and Echange_impose_base::T_ext().
T_ext() [2/4]
const Champ_front_base& Echange_global_impose_turbulent::T_ext () const inline override virtual
Reimplemented from Echange_impose_base.
References Process::exit(), Objet_U::que_suis_je(), and Echange_impose_base::T_ext().
h_imp() [1/4]
virtual Champ_front_base& Echange_global_impose_turbulent::h_imp () inline override virtual
Reimplemented from Echange_impose_base.
References Process::exit(), Echange_impose_base::h_imp(), and Objet_U::que_suis_je().
h_imp() [2/4]
virtual const Champ_front_base& Echange_global_impose_turbulent::h_imp () const inline override virtual
Reimplemented from Echange_impose_base.
References Process::exit(), Echange_impose_base::h_imp(), and Objet_U::que_suis_je().
has_h_imp_grad()
bool Echange_global_impose_turbulent::has_h_imp_grad () const inline override virtual
Reimplemented from Echange_impose_base.
h_imp() [3/4]
double Echange_global_impose_turbulent::h_imp (int i) const inline override virtual
Renvoie la valeur du coefficient d'echange de chaleur impose sur la i-eme composante.
du champ de frontiere.
Parameters
(int i)
Returns
(double)
Reimplemented from Echange_impose_base.
References h_.
h_imp() [4/4]
double Echange_global_impose_turbulent::h_imp (int i, int j) const inline override virtual
Renvoie la valeur du coefficient d'echange de chaleur impose sur la i-eme composante.
du champ de frontiere.
Parameters
(int i)
(int j)
Returns
(double)
Reimplemented from Echange_impose_base.
References h_.
h_imp_grad() [1/2]
double Echange_global_impose_turbulent::h_imp_grad (int i) const inline override virtual
Reimplemented from Echange_impose_base.
References h_grad_.
h_imp_grad() [2/2]
double Echange_global_impose_turbulent::h_imp_grad (int i, int j) const inline override virtual
Reimplemented from Echange_impose_base.
References h_grad_.
T_ext() [3/4]
double Echange_global_impose_turbulent::T_ext (int i) const inline override virtual
Renvoie la valeur de la temperature imposee sur la i-eme composante du champ de frontiere.
Parameters
(int i) l'indice de la composante du champ de de frontiere
Returns
(double)
Reimplemented from Echange_impose_base.
References T_.
T_ext() [4/4]
double Echange_global_impose_turbulent::T_ext (int i, int j) const inline override virtual
Renvoie la valeur de la temperature imposee sur la (i,j)-eme composante du champ de frontiere.
Parameters
(int i)
(int j)
Returns
(double)
Reimplemented from Echange_impose_base.
References T_.
me_calculer()
virtual void Echange_global_impose_turbulent::me_calculer () protected pure virtual
Referenced by mettre_a_jour().
OBS_PTR() [1/2]
Echange_global_impose_turbulent::OBS_PTR (Correlation_base) protected
OBS_PTR() [2/2]
Echange_global_impose_turbulent::OBS_PTR (Frontiere_dis_base) protected
Member Data Documentation
mon_temps
double Echange_global_impose_turbulent::mon_temps = -1.e8 protected
Referenced by mettre_a_jour().
h_
DoubleTab Echange_global_impose_turbulent::h_ protected
Referenced by h_imp(), and initialiser().
h_grad_
DoubleTab Echange_global_impose_turbulent::h_grad_ protected
Referenced by h_imp_grad(), and initialiser().
T_
DoubleTab Echange_global_impose_turbulent::T_ protected
Referenced by initialiser(), and T_ext().