CEA TRUST Platform: Evaluateur_Source Class Reference
Evaluateur_Source Class Reference abstract
Constructor & Destructor Documentation
Evaluateur_Source() [1/2]
Evaluateur_Source::Evaluateur_Source () inline
Evaluateur_Source() [2/2]
Evaluateur_Source::Evaluateur_Source (const Evaluateur_Source & eval) inline
~Evaluateur_Source()
virtual Evaluateur_Source::~Evaluateur_Source () inline virtual
Member Function Documentation
calculer_terme_source()
template<typename Type_Double > void Evaluateur_Source::calculer_terme_source (int , Type_Double &) const inline
References Process::exit().
mettre_a_jour()
virtual void Evaluateur_Source::mettre_a_jour () pure virtual
Implemented in Eval_Source_C_VEF_Face, Eval_Puiss_Th_VEF_Face, Eval_Puiss_Th_QC_VEF_Face, Eval_Forchheimer_VEF_Face, Eval_Dirac_VEF_Face, Eval_Darcy_VEF_Face, Eval_Source_C_VDF_Elem, Eval_Puiss_Th_VDF_Elem, Eval_Puiss_Th_QC_VDF_Elem, Eval_Puiss_Neutr_VDF_Elem, Eval_Gravite_VDF_Face, Eval_Forchheimer_VDF_Face, Eval_Echange_Himp_VDF_Elem, Eval_Dirac_VDF_Elem, Eval_Darcy_VDF_Face, Eval_Source_C_PolyMAC_Elem, Eval_Puiss_Th_PolyMAC_Elem, Eval_Puiss_Th_QC_EF, Eval_Puiss_Th_EF, and Eval_Puiss_Th_DG_Elem.
completer()
virtual void Evaluateur_Source::completer () pure virtual
Implemented in Evaluateur_Source_VEF_Face, Eval_Source_C_VEF_Face, Eval_Puiss_Th_VEF_Face, Eval_Puiss_Th_QC_VEF_Face, Eval_Puiss_Neutr_VDF_Elem, Evaluateur_Source_Face, Evaluateur_Source_Elem, Evaluateur_Source_EF_Som, Eval_Puiss_Th_QC_EF, and Eval_Puiss_Th_EF.
Referenced by associer_domaines().
associer_domaines()
void Evaluateur_Source::associer_domaines (const Domaine_dis_base & domaine, const Domaine_Cl_dis_base & domaine_cl) inline
References completer().
Referenced by Terme_Puissance_Thermique_DG_Elem::associer_domaines(), Puissance_Thermique_EF::associer_domaines(), Puissance_Thermique_QC_EF::associer_domaines(), Terme_Puissance_Thermique_PolyMAC_Elem::associer_domaines(), Terme_Source_Constituant_PolyMAC_Elem::associer_domaines(), Source_Darcy_VDF_Face::associer_domaines(), Source_Dirac_VDF_Elem::associer_domaines(), Source_Echange_Th_VDF::associer_domaines(), Source_Forchheimer_VDF_Face::associer_domaines(), Source_Neutronique_VDF::associer_domaines(), Terme_Gravite_VDF_Face::associer_domaines(), Terme_Puissance_Thermique_QC_VDF_Elem::associer_domaines(), Terme_Puissance_Thermique_VDF_Elem::associer_domaines(), Terme_Source_Constituant_VDF_Elem::associer_domaines(), Source_Darcy_VEF_Face::associer_domaines(), Source_Dirac_VEF_Face::associer_domaines(), Source_Forchheimer_VEF_Face::associer_domaines(), Terme_Puissance_Thermique_QC_VEF_Face::associer_domaines(), Terme_Puissance_Thermique_VEF_Face::associer_domaines(), and Terme_Source_Constituant_VEF_Face::associer_domaines().
OBS_PTR() [1/2]
Evaluateur_Source::OBS_PTR (Domaine_dis_base) protected
OBS_PTR() [2/2]
Evaluateur_Source::OBS_PTR (Domaine_Cl_dis_base) protected