CEA TRUST Platform: Champ_Face_VDF_implementation Class Reference
Champ_Face_VDF_implementation Class Reference abstract
Member Function Documentation
valeur_a_elem()
DoubleVect & Champ_Face_VDF_implementation::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face_VDF.
References Champ_implementation::le_champ().
Referenced by Champ_Face_VDF::valeur_a_elem(), Champ_Fonc_Face_VDF::valeur_a_elem(), and valeur_aux_sommets().
valeur_a_elem_compo()
double Champ_Face_VDF_implementation::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face_VDF.
References Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vdf(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_sommets(), interpolation(), Champ_implementation::le_champ(), and Champ_Proto::valeurs().
Referenced by Champ_Face_VDF::valeur_a_elem_compo(), Champ_Fonc_Face_VDF::valeur_a_elem_compo(), valeur_aux_elems_compo(), and valeur_aux_sommets_compo().
valeur_aux_elems()
DoubleTab & Champ_Face_VDF_implementation::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face_VDF.
References Champ_implementation::le_champ().
Referenced by Champ_Face_VDF::valeur_aux_elems(), and Champ_Fonc_Face_VDF::valeur_aux_elems().
valeur_aux_elems_passe()
DoubleTab & Champ_Face_VDF_implementation::valeur_aux_elems_passe (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const
References Champ_implementation::le_champ().
Referenced by Champ_Face_VDF::valeur_aux_elems_passe().
valeur_aux_elems_compo()
DoubleVect & Champ_Face_VDF_implementation::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face_VDF.
References Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and valeur_a_elem_compo().
Referenced by Champ_Face_VDF::valeur_aux_elems_compo(), and Champ_Fonc_Face_VDF::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Face_VDF_implementation::valeur_aux_sommets (const Domaine & dom, DoubleTab & ch_som) const override virtual
Implements Champ_implementation_divers.
Reimplemented in Champ_Fonc_Face_VDF.
References Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, Process::exit(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_32_64< _SIZE_ >::sommet_elem(), valeur_a_elem(), and Champ_Proto::valeurs().
Referenced by Champ_Face_VDF::valeur_aux_sommets(), and Champ_Fonc_Face_VDF::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Face_VDF_implementation::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & ch_som, int ncomp) const override virtual
Implements Champ_implementation_divers.
Reimplemented in Champ_Fonc_Face_VDF.
References Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, Process::exit(), Champ_implementation::le_champ(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_32_64< _SIZE_ >::sommet_elem(), and valeur_a_elem_compo().
Referenced by Champ_Face_VDF::valeur_aux_sommets_compo(), and Champ_Fonc_Face_VDF::valeur_aux_sommets_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Face_VDF_implementation::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face_VDF.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), Champ_implementation::get_domaine_dis(), Domaine_VF::nb_faces_tot(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), and Domaine_VF::xv().
Referenced by Champ_Face_VDF::remplir_coord_noeuds(), Champ_Fonc_Face_VDF::remplir_coord_noeuds(), and remplir_coord_noeuds_et_polys().
remplir_coord_noeuds_et_polys()
int Champ_Face_VDF_implementation::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const override virtual
Implements Champ_implementation.
Reimplemented in Champ_Fonc_Face_VDF.
References domaine_vdf(), Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), remplir_coord_noeuds(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by Champ_Face_VDF::remplir_coord_noeuds_et_polys(), and Champ_Fonc_Face_VDF::remplir_coord_noeuds_et_polys().
imprime_Face()
int Champ_Face_VDF_implementation::imprime_Face (Sortie & os, int ncomp) const
References Objet_U::dimension, Champ_implementation::le_champ(), Objet_U::nom_du_cas(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by Champ_Face_VDF::imprime(), and Champ_Fonc_Face_VDF::imprime().
valeur_aux_faces_post_impl()
DoubleTab & Champ_Face_VDF_implementation::valeur_aux_faces_post_impl (const Domaine_VDF & vdf, DoubleTab & result) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), Domaine_VDF::face_normales(), Domaine_VF::face_surfaces(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nb_comp(), Domaine_VF::nb_faces(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Proto::valeurs().
Referenced by Champ_Face_VDF::valeur_aux_faces_post(), and Champ_Fonc_Face_VDF::valeur_aux_faces_post().
domaine_vdf()
virtual const Domaine_VDF& Champ_Face_VDF_implementation::domaine_vdf () const protected pure virtual
Implemented in Champ_Fonc_Face_VDF, and Champ_Face_VDF.
Referenced by remplir_coord_noeuds_et_polys(), trace(), and valeur_a_elem_compo().
interpolation()
double Champ_Face_VDF_implementation::interpolation (const double val1, const double val2, const double psi) const protected
Referenced by valeur_a_elem_compo().
trace()
DoubleTab & Champ_Face_VDF_implementation::trace (const Frontiere_dis_base & fr, const DoubleTab & y, DoubleTab & x, int distant) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_vdf(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Domaine_VDF::orientation().
Referenced by Champ_Face_VDF::trace(), and Champ_Fonc_Face_VDF::trace().