CEA TRUST Platform: Partitionneur_Sous_Domaine Class Reference
Partitionneur_Sous_Domaine Class Reference
Additional Inherited Members
Public Member Functions inherited from Partitionneur_base_32_64< _SIZE_ >
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Partitionneur_base_32_64< _SIZE_ >
static int_t calculer_graphe_connexions_periodiques (const Domaine_t &domaine, const Noms &liste_bords_periodiques, const Static_Int_Lists_t &som_elem, const int_t my_offset, Static_Int_Lists_t &graph)
static int_t corriger_bords_avec_graphe (const Static_Int_Lists_t &graph_elements_perio, const Static_Int_Lists_t &som_elem, const Domaine_t &domaine, const Noms &liste_bords_perio, BigIntVect_ &elem_part)
static void corriger_bords_avec_liste (const Domaine_t &dom, const Noms &liste_bords_periodiques, const int_t my_offset, BigIntVect_ &elem_part)
static void corriger_elem0_sur_proc0 (BigIntVect_ &elem_part)
static int_t corriger_multiperiodique (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
static int_t corriger_sommets_bord (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
"conforme" avec le domaine complet.
Utilisation:
creer un domaine global, et deux sous-domaines (qui se recouvrent partiellement) pour Domaine1 et Domaine2
decouper le domaine global et ecrire le fichier de decoupe
creer Domaine1 et Domaine2 par Create_domain_from_sub_domain
decouper D1 et D2 par Partitionneur sous_domaine en prenant pour source le decoupage du domaine global.
Syntaxe: Decouper dom_N { partitionneur sous_domaine { fichier decoup/domaine_glob.txt fichier_ssz sous_domaine_dom_N.file OU nom_ssz sous_domaine } Nom_Domaines decoup/dom_N }
See also
Partitionneur_Union Create_domain_from_sub_domain
Member Function Documentation
set_param()
void Partitionneur_Sous_Domaine::set_param (Param & param) override virtual
Implements Partitionneur_base_32_64< _SIZE_ >.
References Param::ajouter(), filename_, filename_ssz_, name_ssz_, and Param::REQUIRED.
associer_domaine()
void Partitionneur_Sous_Domaine::associer_domaine (const Domaine & dom) inline override
construire_partition()
void Partitionneur_Sous_Domaine::construire_partition (IntVect & elem_part, int & nb_parts_tot) const override
Lit le contenu du fichier "filename_" et stocke le resultat dans elem_part.
References Entree_Fichier_base::close(), Process::exit(), filename_, filename_ssz_, Entree_Fichier_base::good(), name_ssz_, Interprete::objet(), Entree_Fichier_base::ouvrir(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Member Data Documentation
filename_
Nom Partitionneur_Sous_Domaine::filename_ protected
Referenced by construire_partition(), and set_param().
filename_ssz_
Nom Partitionneur_Sous_Domaine::filename_ssz_ protected
! Nom du fichier de decoupe globale
Referenced by construire_partition(), and set_param().
name_ssz_
Nom Partitionneur_Sous_Domaine::name_ssz_ protected
Referenced by construire_partition(), and set_param().