CEA TRUST Platform: Motcles Class Reference
Motcles Class Reference
Public Member Functions
Motcles (int)
Constructor & Destructor Documentation
Motcles()
Motcles::Motcles (int i)
Constructeur Cree un tableau de i elements.
Parameters
(int i) nombre de mots cles
Member Function Documentation
rang()
int Motcles::rang (const char *const ch) const
Referenced by contient_(), Op_Conv_VDF_base::creer_champ(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::creer_champ(), QDM_Multiphase::creer_champ(), Navier_Stokes_std::lire_cond_init(), Navier_Stokes_std::lire_motcle_non_standard(), and Debog_Pb::test_ignore_msg().
contient_()
int Motcles::contient_ (const char *const ch) const
References rang().
Referenced by Sonde::completer(), Sonde::create_champ_generique(), Postraitement::lire_champs_a_postraiter(), and Postraitement::verifie_nom_et_sources().
search()
int Motcles::search (const Motcle & t) const
Referenced by Modele_turbulence_hyd_0_eq_base::a_pour_Champ_Fonc(), Objet_a_lire::add_dict(), Champ_Generique_base::composante(), Modele_turbulence_hyd_0_eq_base::comprend_champ(), Champ_Generique_Predefini::construit_expression(), Solv_Petsc::create_solver(), EF_discretisation::discretiser_champ(), VDF_discretisation::discretiser_champ(), DG_discretisation::discretiser_champ(), PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), VEF_discretisation::discretiser_champ(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Generique_Correlation::get_property(), Champ_Generique_Divergence::get_property(), Champ_Generique_Ecart_Type::get_property(), Champ_Generique_Extraction::get_property(), Champ_Generique_Gradient::get_property(), Champ_Generique_Interpolation::get_property(), Champ_Generique_Moyenne::get_property(), Champ_Generique_Predefini::get_property(), Champ_Generique_Reduction_0D::get_property(), Champ_Generique_refChamp::get_property(), Champ_Generique_Transformation::get_property(), Champ_Post_Operateur_Eqn::get_property(), Champ_Generique_Tparoi_VEF::get_property(), Piso::lire(), Simple::lire(), Traitement_particulier_NS_canal::lire(), Traitement_particulier_NS_chmoy_faceperio::lire(), Traitement_particulier_NS_EC::lire(), Traitement_particulier_NS_Profils::lire(), Traitement_particulier_NS_temperature::lire(), Traitement_particulier_NS_THI::lire(), Traitement_particulier_NS_THI_new::lire(), Traitement_particulier_Solide_canal::lire(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Terme_Source_Acceleration::lire_data(), Perte_Charge_Reguliere::lire_donnees(), Perte_Charge_Singuliere::lire_donnees(), Champ_front_recyclage::lire_info_moyenne_imposee(), Champ_front_recyclage::lire_info_moyenne_recyclee(), Schema_Temps_base::lire_motcle_non_standard(), Fluide_Dilatable_base::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Fluide_Quasi_Compressible::lire_motcle_non_standard(), Postraitements::lire_postraitements(), Schema_Temps_base::lire_residuals(), Objet_a_lire::read(), Champ_Generique_Interpolation::set_localisation(), Champ_Generique_Interpolation::set_methode(), Option_VDF::test_mot(), Faces_32_64< _SIZE_ >::type(), Champ_Generique_Transformation::verifier_coherence_donnees(), and Champ_Generique_Transformation::verifier_localisation().