CEA TRUST Platform: Vitesse_derive_base Class Reference
Vitesse_derive_base Class Reference abstract
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
correlations de vitesse de derive de la forme
ur = ((C0 - 1) * v_l + vg0) / (1 - C0 alpha_g)
Member Function Documentation
vitesse_relative()
void Vitesse_derive_base::vitesse_relative (const input_t & input, output_t & output) const override virtual
Implements Vitesse_relative_base.
References Vitesse_relative_base::input_t::alpha, alpha_min_, C0, Objet_U::dimension, Vitesse_relative_base::output_t::dvr, evaluate_C0_vg0(), Vitesse_relative_base::n_g, Vitesse_relative_base::n_l, Vitesse_relative_base::input_t::v, vg0, and Vitesse_relative_base::output_t::vr.
set_param()
void Vitesse_derive_base::set_param (Param & param) override virtual
Reimplemented from Vitesse_relative_base.
Reimplemented in Vitesse_derive_Ishii, Vitesse_derive_Forces, and Vitesse_derive_constante.
References Param::ajouter(), alpha_min_, and Vitesse_relative_base::set_param().
Referenced by Vitesse_derive_constante::set_param(), Vitesse_derive_Forces::set_param(), and Vitesse_derive_Ishii::set_param().
evaluate_C0_vg0()
virtual void Vitesse_derive_base::evaluate_C0_vg0 (const input_t & input) const protected pure virtual
Implemented in Vitesse_derive_Ishii, Vitesse_derive_Forces, and Vitesse_derive_constante.
Referenced by vitesse_relative().
Member Data Documentation
C0
double Vitesse_derive_base::C0 = -1 mutable protected
Referenced by Vitesse_derive_Ishii::evaluate_C0_vg0(), Vitesse_derive_constante::set_param(), and vitesse_relative().
vg0
ArrOfDouble Vitesse_derive_base::vg0 mutable protected
Referenced by Vitesse_derive_Ishii::evaluate_C0_vg0(), Vitesse_derive_constante::set_param(), and vitesse_relative().
alpha_min_
double Vitesse_derive_base::alpha_min_ = 0.0 protected
Referenced by set_param(), and vitesse_relative().