CEA TRUST Platform: Loi_Etat_GP_base Class Reference
Loi_Etat_GP_base Class Reference
Public Member Functions
void associer_fluide (const Fluide_Dilatable_base &) override
void remplir_T () override
const Nom type_fluide () const override
Public Member Functions inherited from Loi_Etat_base
void assoscier_probleme (const Probleme_base &pb)
void mettre_a_jour (double)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Elle definit un fluide dilatable dont la loi d'etat est :
   Pth = rho*R*T
See also
Fluide_Dilatable_base Loi_Etat_base
Constructor & Destructor Documentation
Loi_Etat_GP_base()
Loi_Etat_GP_base::Loi_Etat_GP_base ()
Member Function Documentation
type_fluide()
const Nom Loi_Etat_GP_base::type_fluide () const override virtual
Renvoie le type de fluide associe.
Parameters
(Sortie& os) le flot de sortie pour l'impression
Returns
(Sortie&) le flot de sortie modifie
Implements Loi_Etat_base.
associer_fluide()
void Loi_Etat_GP_base::associer_fluide (const Fluide_Dilatable_base & fl) override virtual
Associe le fluide a la loi d'etat.
Parameters
(Fluide_Dilatable_base& fl) le fluide associe
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_Melange_GP_base.
References Loi_Etat_base::associer_fluide(), and Cp_.
calculer_lambda()
void Loi_Etat_GP_base::calculer_lambda () override virtual
Calcule la conductivite.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_TPPI_base, and Loi_Etat_Multi_GP_base.
References Cp_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Champ_Don_base::mettre_a_jour(), Loi_Etat_base::Pr_, and Champ_Don_base::valeurs().
calculer_alpha()
void Loi_Etat_GP_base::calculer_alpha () override virtual
Calcule la diffusivite.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_TPPI_base, and Loi_Etat_Multi_GP_base.
References Cp_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Don_base::valeurs().
remplir_T()
void Loi_Etat_GP_base::remplir_T () override virtual
Remplit le tableau de la temperature : T=temp+273.
15
Implements Loi_Etat_base.
Referenced by initialiser().
calculer_Cp()
void Loi_Etat_GP_base::calculer_Cp () override virtual
Calcule le Cp NE FAIT RIEN : le Cp est constant.
Implements Loi_Etat_base.
Reimplemented in Loi_Etat_TPPI_WC_base, Loi_Etat_TPPI_QC_base, and Loi_Etat_Multi_GP_base.
initialiser()
void Loi_Etat_GP_base::initialiser () override virtual
Initialise la loi d'etat : calcul Pth.
Implements Loi_Etat_base.
References remplir_T(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Loi_Etat_base::tab_rho_n.
calculer_masse_volumique() [1/4]
double Loi_Etat_GP_base::calculer_masse_volumique (double P, double T) const inline override virtual
Implements Loi_Etat_base.
Reimplemented in Loi_Etat_Multi_GP_WC, Loi_Etat_GP_WC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_GP_QC, Loi_Etat_TPPI_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_WC, and Loi_Etat_Binaire_GP_QC.
calculer_masse_volumique() [2/4]
KOKKOS_INLINE_FUNCTION double Loi_Etat_GP_base::calculer_masse_volumique (double P, double T, double R) const inline
inverser_Pth()
double Loi_Etat_GP_base::inverser_Pth (double T, double rho) override virtual
Calcule la pression avec la temperature et la masse volumique.
Implements Loi_Etat_base.
Reimplemented in Loi_Etat_GP_WC, Loi_Etat_TPPI_base, and Loi_Etat_rhoT_GP_QC.
References R_.
R()
double Loi_Etat_GP_base::R () const inline
References R_.
Referenced by Loi_Etat_GP_QC::compute_tab_rho(), and EDO_Pression_th_VDF_Gaz_Parfait::resoudre().
calculer_masse_volumique() [3/4]
void Loi_Etat_base::calculer_masse_volumique virtual
Recalcule la masse volumique.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_TPPI_WC_base, and Loi_Etat_TPPI_QC_base.
Referenced by Loi_Etat_GP_QC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), and Loi_Etat_GP_QC::compute_tab_rho().
calculer_masse_volumique() [4/4]
virtual double Loi_Etat_base::calculer_masse_volumique virtual
Recalcule la masse volumique.
Reimplemented from Loi_Etat_base.
Reimplemented in Loi_Etat_TPPI_WC_base, and Loi_Etat_TPPI_QC_base.
Member Data Documentation
Cp_
double Loi_Etat_GP_base::Cp_ protected
Referenced by associer_fluide(), calculer_alpha(), Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), calculer_lambda(), and Loi_Etat_Multi_GP_base::calculer_lambda().
R_
double Loi_Etat_GP_base::R_ protected
Referenced by Loi_Etat_GP_QC::compute_tab_rho(), inverser_Pth(), and R().