CEA TRUST Platform: Op_PolyMAC_Elem Class Reference
Op_PolyMAC_Elem Class Reference
#include <Op_PolyMAC_Elem.h>
Member Function Documentation
dimensionner()
void Op_PolyMAC_Elem::dimensionner (const Domaine_PolyMAC & le_domaine, const Domaine_Cl_PolyMAC & le_domaine_cl, Matrice_Morse & la_matrice) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Matrice_Morse::dimensionner(), Domaine_dis_base::domaine(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_voisins(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), and Champ_Inc_base::valeurs().
Referenced by Op_Conv_Amont_PolyMAC_Elem::dimensionner(), and Op_Conv_Centre_PolyMAC_Elem::dimensionner().
dimensionner_bloc_vitesse()
void Op_PolyMAC_Elem::dimensionner_bloc_vitesse (const Domaine_PolyMAC & le_domaine, const Domaine_Cl_PolyMAC & le_domaine_cl, Matrice_Morse & matrice) const
References Matrix_tools::allocate_morse_matrix(), Domaine_VF::face_voisins(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Op_Conv_Amont_PolyMAC_Elem::dimensionner_bloc_vitesse(), and Op_Conv_Centre_PolyMAC_Elem::dimensionner_bloc_vitesse().
modifier_pour_Cl()
void Op_PolyMAC_Elem::modifier_pour_Cl (const Domaine_PolyMAC & le_domaine, const Domaine_Cl_PolyMAC & le_domaine_cl, Matrice_Morse & la_matrice, DoubleTab & secmem) const
Referenced by Op_Conv_Amont_PolyMAC_Elem::modifier_pour_Cl(), and Op_Conv_Centre_PolyMAC_Elem::modifier_pour_Cl().