CEA TRUST Platform: Parametre_implicite Class Reference
Parametre_implicite Class Reference
#include <Parametre_implicite.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
options specifiques pour piso ou simpler
Member Function Documentation
solveur() [1/2]
SolveurSys & Parametre_implicite::solveur () inline
References le_solveur_.
Referenced by Simple::iterer_eqn(), Simple::iterer_eqs(), SETS::iterer_NS(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), and Solveur_U_P::iterer_NS().
solveur() [2/2]
const SolveurSys & Parametre_implicite::solveur () const inline
References le_solveur_.
seuil_generation_solveur()
double & Parametre_implicite::seuil_generation_solveur () inline
References seuil_generation_solveur_.
seuil_verification_solveur()
double & Parametre_implicite::seuil_verification_solveur () inline
References seuil_verification_solveur_.
Referenced by Simple::iterer_eqn().
seuil_test_preliminaire_solveur()
double & Parametre_implicite::seuil_test_preliminaire_solveur () inline
References seuil_test_preliminaire_solveur_.
Referenced by Simple::iterer_eqn().
seuil_convergence_implicite()
double & Parametre_implicite::seuil_convergence_implicite () inline
References seuil_convergence_implicite_.
Referenced by Simple::iterer_eqn(), and Simple::iterer_eqs().
seuil_diffusion_implicite()
double & Parametre_implicite::seuil_diffusion_implicite () inline
References seuil_diffusion_implicite_.
Referenced by Simple::iterer_eqn().
nb_it_max()
int & Parametre_implicite::nb_it_max () inline
References nb_it_max_.
calcul_explicite()
bool & Parametre_implicite::calcul_explicite () inline
References calcul_explicite_.
Referenced by Equation_base::derivee_en_temps_inco(), and Simple::iterer_eqn().
equation_frequence_resolue()
int Parametre_implicite::equation_frequence_resolue (double t) inline
References equation_frequence_resolue_, Parser_U::eval(), and Parser_U::setVar().
Referenced by Simple::iterer_eqn().
set_seuil_solveur_avec_seuil_convergence_solveur()
void Parametre_implicite::set_seuil_solveur_avec_seuil_convergence_solveur (double seuil_convergence_solveur)
permet de mettre les seuils equivalents a ceux de la 161 pour l'instant warning ensuite ereur.
References Process::exit(), seuil_generation_solveur_, seuil_test_preliminaire_solveur_, and seuil_verification_solveur_.
seuil_test_preliminaire_lu()
int Parametre_implicite::seuil_test_preliminaire_lu () const inline
References seuil_test_preliminaire_lu_.
Member Data Documentation
le_solveur_
SolveurSys Parametre_implicite::le_solveur_ protected
Referenced by solveur(), and solveur().
seuil_generation_solveur_
double Parametre_implicite::seuil_generation_solveur_ protected
Referenced by set_seuil_solveur_avec_seuil_convergence_solveur(), and seuil_generation_solveur().
seuil_test_preliminaire_solveur_
double Parametre_implicite::seuil_test_preliminaire_solveur_ protected
Referenced by set_seuil_solveur_avec_seuil_convergence_solveur(), and seuil_test_preliminaire_solveur().
seuil_verification_solveur_
double Parametre_implicite::seuil_verification_solveur_ protected
Referenced by set_seuil_solveur_avec_seuil_convergence_solveur(), and seuil_verification_solveur().
seuil_test_preliminaire_lu_
int Parametre_implicite::seuil_test_preliminaire_lu_ protected
Referenced by seuil_test_preliminaire_lu().
seuil_convergence_implicite_
double Parametre_implicite::seuil_convergence_implicite_ protected
Referenced by seuil_convergence_implicite().
nb_it_max_
int Parametre_implicite::nb_it_max_ protected
Referenced by nb_it_max().
calcul_explicite_
bool Parametre_implicite::calcul_explicite_ = false protected
Referenced by calcul_explicite().
seuil_diffusion_implicite_
double Parametre_implicite::seuil_diffusion_implicite_ protected
Referenced by seuil_diffusion_implicite().
equation_frequence_resolue_
Parser_U Parametre_implicite::equation_frequence_resolue_ protected
Referenced by equation_frequence_resolue().