CEA TRUST Platform: Traitement_particulier_NS_Brech_VEF Class Reference
Traitement_particulier_NS_Brech_VEF Class Reference
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
pour le calcul des flux pour le cas Brech :
See also
Navier_Stokes_Turbulent, Traitement_particulier_base, Traitement_particulier_VEF
Constructor & Destructor Documentation
Traitement_particulier_NS_Brech_VEF()
Traitement_particulier_NS_Brech_VEF::Traitement_particulier_NS_Brech_VEF ()
Member Function Documentation
post_traitement_particulier()
void Traitement_particulier_NS_Brech_VEF::post_traitement_particulier () inline override virtual
Implements Traitement_particulier_NS_base.
lire()
Entree & Traitement_particulier_NS_Brech_VEF::lire (Entree & is) override virtual
Implements Traitement_particulier_NS_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Champ_Fonc_base::associer_domaine_dis_base(), ch_p, ch_ri, Traitement_particulier_NS_base::champs_compris_, Process::exit(), Field_base::fixer_nb_comp(), Champ_Fonc_P1NC::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Field_base::nommer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Motcles::search().
Member Data Documentation
ch_ri
Champ_Fonc_P1NC Traitement_particulier_NS_Brech_VEF::ch_ri protected
Referenced by lire().
ch_p
Champ_Fonc_P1NC Traitement_particulier_NS_Brech_VEF::ch_p protected
Referenced by lire().