CEA TRUST Platform: Solv_Externe Class Reference
Solv_Externe Class Reference
#include <Solv_Externe.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Common stuff for several external solvers.
Note: here we use trustIdType for potentially big identifiers, this maps to PetscInt type in Solv_Petsc class (type equality between the both is checked when creating the solver).
Constructor & Destructor Documentation
Solv_Externe()
Solv_Externe::Solv_Externe () inline
~Solv_Externe()
Solv_Externe::~Solv_Externe () inline
Member Function Documentation
construit_matrice_morse_intermediaire()
void Solv_Externe::construit_matrice_morse_intermediaire (const Matrice_Base & la_matrice, Matrice_Morse & matrice_morse_intermediaire) protected
References Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Matrice_Bloc::BlocToMatMorse(), Matrice_Morse::dimensionner(), Process::exit(), Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Process::je_suis_maitre(), matrice_symetrique_, MorseSymToMorse(), Objet_U::que_suis_je(), and SolveurSys_base::solveur_direct().
Referenced by Solv_Petsc::resoudre_systeme(), and Solv_rocALUTION::resoudre_systeme().
construit_renum()
void Solv_Externe::construit_renum (const DoubleVect & b) protected
References MD_Vector_tools::creer_tableau_distribue(), decalage_local_global_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector_base::get_sequential_items_flags(), index_, items_to_keep_, ix, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_sum(), Process::mppartial_sum(), nb_items_to_keep_, nb_rows_, nb_rows_tot_, renum_, TRUSTTab< _TYPE_, _SIZE_ >::reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), secmem_sz_, ArrOfBit_32_64< _SIZE_ >::size_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUSTVect< _TYPE_, _SIZE_ >::size_totale().
Referenced by Solv_Petsc::resoudre_systeme(), and Solv_rocALUTION::resoudre_systeme().
MorseSymToMorse()
void Solv_Externe::MorseSymToMorse (const Matrice_Morse_Sym & MS, Matrice_Morse & M) protected
References Matrice_Morse::nb_vois(), Matrice_Morse::ordre(), and Matrice_Morse::transpose().
Referenced by construit_matrice_morse_intermediaire().
Create_lhs_rhs_onDevice()
void Solv_Externe::Create_lhs_rhs_onDevice () protected
References lhs_, nb_rows_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), and rhs_.
Update_lhs_rhs()
template<typename ExecSpace > void Solv_Externe::Update_lhs_rhs (const DoubleVect & b, DoubleVect & x) protected
References index_, lhs_, rhs_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Update_solution()
template<typename ExecSpace > void Solv_Externe::Update_solution (DoubleVect & x) protected
References index_, lhs_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Solv_Petsc::resoudre_systeme().
Member Data Documentation
renum_
TIDTab Solv_Externe::renum_ protected
Referenced by construit_renum(), and Solv_rocALUTION::resoudre_systeme().
index_
IntTab Solv_Externe::index_ protected
Referenced by construit_renum(), Update_lhs_rhs(), and Update_solution().
items_to_keep_
ArrOfBit Solv_Externe::items_to_keep_ protected
Referenced by construit_renum().
ix
ArrOfTID Solv_Externe::ix protected
Referenced by construit_renum().
nb_items_to_keep_
int Solv_Externe::nb_items_to_keep_ protected
Referenced by construit_renum().
nb_rows_
int Solv_Externe::nb_rows_ protected
Referenced by construit_renum(), Create_lhs_rhs_onDevice(), Solv_Petsc::resoudre_systeme(), and Solv_rocALUTION::resoudre_systeme().
nb_rows_tot_
trustIdType Solv_Externe::nb_rows_tot_ protected
Referenced by construit_renum(), Solv_Petsc::resoudre_systeme(), and Solv_rocALUTION::resoudre_systeme().
decalage_local_global_
trustIdType Solv_Externe::decalage_local_global_ protected
Referenced by construit_renum().
matrice_symetrique_
int Solv_Externe::matrice_symetrique_ protected
Referenced by construit_matrice_morse_intermediaire(), Solv_Petsc::create_solver(), and Solv_Petsc::resoudre_systeme().
secmem_sz_
int Solv_Externe::secmem_sz_ protected
Referenced by construit_renum(), and Solv_Petsc::resoudre_systeme().
lhs_
ArrOfDouble Solv_Externe::lhs_ protected
Referenced by Create_lhs_rhs_onDevice(), Solv_rocALUTION::resoudre_systeme(), Update_lhs_rhs(), and Update_solution().
rhs_
ArrOfDouble Solv_Externe::rhs_ protected
Referenced by Create_lhs_rhs_onDevice(), Solv_rocALUTION::resoudre_systeme(), and Update_lhs_rhs().