CEA TRUST Platform: Domaine_PolyMAC_P0 Class Reference
Domaine_PolyMAC_P0 Class Reference
Public Member Functions
void fgrad (int N, int is_p, const Conds_lim &cls, const IntTab &fcl, const DoubleTab *nu, const IntTab *som_ext, int virt, int full_stencil, IntTab &phif_d, IntTab &phif_e, DoubleTab &phif_c) const
void init_stencils () const
Public Member Functions inherited from Domaine_Poly_base
void reordonner (Faces &) override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
const Frontiere_dis_base & frontiere_dis (const Nom &) const
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
discretiser()
void Domaine_PolyMAC_P0::discretiser () override virtual
Reimplemented from Domaine_PolyMAC.
References MD_Vector_composite::add_part(), MD_Vector::copy(), Objet_U::dimension, Domaine_Poly_base::discretiser(), Domaine_dis_base::domaine(), Domaine_VF::md_vector_faces(), and mdv_ch_face.
init_stencils()
void Domaine_PolyMAC_P0::init_stencils () const
Initializes the face stencils for gradient computation.
This method builds the connectivity stencils required for face-based gradient calculations in the PolyMAC P0 discretization scheme. It establishes the relationship between faces and all elements/boundary faces that are connected through shared vertices.
The stencil for each face includes:
All elements connected to the face through any of its vertices
All boundary faces connected to the face through shared vertices
The face's direct neighboring elements
Note
This method is called lazily - it only performs initialization if stencils haven't been built yet (checked via fsten_d.size())
The method populates two main data structures:
fsten_d: Index array for stencil boundaries
fsten_eb: Flat array containing all stencil elements/boundary faces
Algorithm overview:
Build vertex-to-element connectivity (som_eb)
Add boundary faces to vertex connectivity
For each face, collect all elements/boundary faces connected via vertices
Store results in compressed sparse format
Postcondition
After execution:
fsten_d(f) gives the starting index in fsten_eb for face f's stencil
fsten_d(f+1) gives the ending index (exclusive) for face f's stencil
fsten_eb contains the actual element/boundary face indices
Boundary faces are represented as (ne_tot + face_index)
Note
Memory is optimized using CRIMP() to reduce storage overhead
Only processes faces that have at least one valid neighbor:
Internal faces: both neighbors must be valid
Boundary faces: at least one neighbor must be valid
See also
fgrad() which uses these stencils for gradient computation
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_VF::fbord(), fsten_d, fsten_eb, Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces_tot(), Domaine_32_64< _SIZE_ >::nb_som_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by fgrad().
fgrad()
void Domaine_PolyMAC_P0::fgrad (int N, int is_p, const Conds_lim & cls, const IntTab & fcl, const DoubleTab * nu, const IntTab * som_ext, int virt, int full_stencil, IntTab & phif_d, IntTab & phif_e, DoubleTab & phif_c) const
Computes field gradient interpolation at faces while preserving constant fields.
This method computes the interpolation [n_f.grad T]_f (if nu_grad = 0) or [n_f.nu.grad T]_f while exactly preserving fields satisfying [nu grad T]_e = constant. It uses MPFA (Multi-Point Flux Approximation) methods with three strategies:
Attempt 0: Standard MPFA-O
Attempt 1: MPFA-eta: variant of MPFA-O where auxiliary variables are not in the barycenter of the face
Attempt 2: Symmetric MPFA if previous attempts fail (coercive but not always consistent, especially on complex meshes)
Parameters
N Number of field components
is_p Pressure field indicator (1 for pressure, 0 otherwise) Controls Neumann/Dirichlet inversion for boundary conditions
cls Domain boundary conditions
fcl Boundary condition data fcl(f, 0/1/2): (BC type, BC index, index within BC) See Champ_{P0,Face}_PolyMAC_P0 for format
nu Element diffusivity (optional, can be nullptr) Array nu(e, n, ..) for element e and component n
som_ext List of vertices to exclude from processing (optional) Example: direct treatment of Echange_Contact in Op_Diff_PolyMAC_P0_Elem
virt Virtual faces indicator (1 to include, 0 otherwise)
full_stencil Complete stencil indicator (1 for full dimensioning)
[out] phif_d Start/end indices in phif_{e,c} / phif_{pe,pc} phif_d(f, 0/1): flux indices at face f in interval [phif_d(f, 0/1), phif_d(f + 1, 0/1)[
[out] phif_e Element indices in stencil for each contribution phif_e(i): element index for i-th contribution
[out] phif_c Stencil coefficients phif_c(i, n, c): coefficient for element i, component n, contribution c Contains local indices/coefficients (without Echange_contact) and diagonal terms (independent components)
Note
The method checks positivity of bilinear form eigenvalues to ensure scheme stability and choose the MPFA method accordingly
The method returns also a percentage of which MPFA method is used. Be careful of the validity of the solution if the percentage of MPFA-sym is high
Special handling for different boundary condition types:
Dirichlet/Neumann
Imposed global/external friction
Imposed global/external exchange
References Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), fsten_eb, init_stencils(), Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_Poly_base::som_elem(), Domaine_VF::volumes_entrelaces(), and Domaine_Poly_base::volumes_entrelaces_dir().
Member Data Documentation
fsten_d
IntTab Domaine_PolyMAC_P0::fsten_d mutable
Referenced by init_stencils().
fsten_eb
IntTab Domaine_PolyMAC_P0::fsten_eb
Referenced by fgrad(), and init_stencils().
mdv_ch_face
MD_Vector Domaine_PolyMAC_P0::mdv_ch_face
Referenced by discretiser().
first_fgrad_
int Domaine_PolyMAC_P0::first_fgrad_ = 1 mutable protected