CEA TRUST Platform: Op_Diff_PolyMAC_P0_Elem Class Reference
Op_Diff_PolyMAC_P0_Elem Class Reference
Public Member Functions
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={}) const override
double calculer_dt_stab () const override
void completer () override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={}) const override
void mettre_a_jour (double t) override
void modifier_pour_Cl (Matrice_Morse &la_matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Constructor & Destructor Documentation
Op_Diff_PolyMAC_P0_Elem()
Op_Diff_PolyMAC_P0_Elem::Op_Diff_PolyMAC_P0_Elem ()
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
Member Function Documentation
completer()
void Op_Diff_PolyMAC_P0_Elem::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_PolyMAC_P0_base.
References Couplage_Parietal_PolyMAC_helper::associer(), Op_Diff_PolyMAC_P0_base::completer(), Couplage_Parietal_PolyMAC_helper::completer_d_nuc(), MorEqn::equation(), Process::exit(), Operateur_base::flux_bords_, Probleme_base::get_correlation(), Probleme_base::has_correlation(), Equation_base::inconnue(), Probleme_base::is_coupled(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
init_op_ext()
void Op_Diff_PolyMAC_P0_Elem::init_op_ext () const override virtual
Reimplemented from Operateur_Diff_base.
References Couplage_Parietal_PolyMAC_helper::init_op_ext(), Operateur_Diff_base::op_ext, and Op_Diff_PolyMAC_P0_base::som_ext_init_.
Referenced by ajouter_blocs(), and dimensionner_blocs().
has_interface_blocs()
int Op_Diff_PolyMAC_P0_Elem::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
calculer_dt_stab()
double Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Op_Diff_PolyMAC_Gen_base::diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Process::exit(), Champ_Inc_P0_base::fcl(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Equation_base::inconnue(), Equation_base::milieu(), Process::mp_min(), Op_Diff_PolyMAC_Gen_base::nu_, Milieu_base::porosite_elem(), Objet_U::que_suis_je(), Option_PolyMAC::TRAITEMENT_AXI, Op_Diff_PolyMAC_P0_base::update_nu(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
dimensionner_blocs()
void Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Dimensions the matrix blocks for the linear system.
Allocates and sizes the sparse matrix structure for the diffusion operator. The method:
Determines the matrix stencil based on the discretization scheme
Accounts for variable diffusivity when computing the stencil
Parameters
matrices Map of matrices to be dimensioned
semi_impl Map of semi-implicit fields
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Couplage_Parietal_PolyMAC_helper::dimensionner_blocs(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), init_op_ext(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_sum_as_double(), Matrice_Morse::nb_colonnes(), Op_Diff_PolyMAC_Gen_base::nu_constant_, Op_Diff_PolyMAC_P0_base::phif_c, Op_Diff_PolyMAC_P0_base::phif_d, Op_Diff_PolyMAC_P0_base::phif_e, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Op_Diff_PolyMAC_P0_base::update_phif(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Diff_PolyMAC_P0_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Assembles the diffusion contribution to the linear system.
This is the core method that computes and adds the diffusion terms to both the matrix and the right-hand side vector. The method:
Computes diffusive fluxes across all faces using the phi_f coefficients
Handles various boundary conditions (Dirichlet, Neumann, heat exchange)
Assembles matrix coefficients for implicit treatment
Updates the right-hand side with explicit contributions
Stores boundary fluxes for post-processing
Parameters
matrices Map of matrices to be filled
secmem Right-hand side vector to update
semi_impl Map of semi-implicit fields
Reimplemented from Operateur_base.
References Couplage_Parietal_PolyMAC_helper::ajouter_blocs(), Equation_base::domaine_Cl_dis(), MorEqn::equation(), Process::exit(), Champ_Inc_P0_base::fcl(), Operateur_base::flux_bords_, Nom::getString(), Operateur_base::has_champ_inco(), Equation_base::inconnue(), init_op_ext(), Field_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Operateur_base::mon_inconnue(), Op_Diff_PolyMAC_P0_base::phif_c, Op_Diff_PolyMAC_P0_base::phif_d, Op_Diff_PolyMAC_P0_base::phif_e, Op_Diff_PolyMAC_P0_base::update_phif(), and Champ_Inc_base::valeurs().
modifier_pour_Cl()
void Op_Diff_PolyMAC_P0_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
mettre_a_jour()
void Op_Diff_PolyMAC_P0_Elem::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Op_Diff_PolyMAC_P0_base.
References Couplage_Parietal_PolyMAC_helper::d_nuc_a_jour(), and Op_Diff_PolyMAC_P0_base::mettre_a_jour().
d_nucleation()
const DoubleTab & Op_Diff_PolyMAC_P0_Elem::d_nucleation () const
References Couplage_Parietal_PolyMAC_helper::d_nuc(), Couplage_Parietal_PolyMAC_helper::d_nuc_a_jour(), and Process::exit().
has_echange_contact()
const bool& Op_Diff_PolyMAC_P0_Elem::has_echange_contact () const inline
couplage_parietal_helper()
const Couplage_Parietal_PolyMAC_helper& Op_Diff_PolyMAC_P0_Elem::couplage_parietal_helper () const inline
Referenced by Couplage_Parietal_PolyMAC_helper::init_op_ext().