CEA TRUST Platform: Force_Centrifuge_VDF_Face_Axi Class Reference
Force_Centrifuge_VDF_Face_Axi Class Reference
Public Member Functions
void completer () override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int initialiser (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe represente la force centrifuge a prendre en compte dans les equations de Navier-Stokes en coordonnees cylindriques pour une dicretisation VDF
See also
Source_base
Member Function Documentation
associer_pb()
void Force_Centrifuge_VDF_Face_Axi::associer_pb (const Probleme_base &) override virtual
Implements Source_base.
calculer()
DoubleTab & Force_Centrifuge_VDF_Face_Axi::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Source_base::ajouter().
completer()
void Force_Centrifuge_VDF_Face_Axi::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::completer(), and MorEqn::equation().
mettre_a_jour()
void Force_Centrifuge_VDF_Face_Axi::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
dimensionner_blocs()
void Force_Centrifuge_VDF_Face_Axi::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Force_Centrifuge_VDF_Face_Axi::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
References Objet_U::dimension, elem_faces, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), orientation, porosite_surf, Domaine_VF::premiere_face_int(), volume_entrelaces, and xv.
has_interface_blocs()
int Force_Centrifuge_VDF_Face_Axi::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
OBS_PTR() [1/3]
Force_Centrifuge_VDF_Face_Axi::OBS_PTR (Domaine_VDF) protected
OBS_PTR() [2/3]
Force_Centrifuge_VDF_Face_Axi::OBS_PTR (Domaine_Cl_VDF) protected
OBS_PTR() [3/3]
Force_Centrifuge_VDF_Face_Axi::OBS_PTR (Champ_Face_VDF) protected
associer_domaines()
void Force_Centrifuge_VDF_Face_Axi::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
References Domaine_VF::elem_faces(), elem_faces, Domaine_VDF::orientation(), orientation, porosite_surf, TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTVect< _TYPE_, _SIZE_ >::ref(), volume_entrelaces, Domaine_VF::volumes_entrelaces(), Domaine_VF::xp(), xp, Domaine_VF::xv(), and xv.
Member Data Documentation
elem_faces
IntTab Force_Centrifuge_VDF_Face_Axi::elem_faces protected
Referenced by ajouter_blocs(), and associer_domaines().
orientation
IntVect Force_Centrifuge_VDF_Face_Axi::orientation protected
Referenced by ajouter_blocs(), and associer_domaines().
xp
DoubleTab Force_Centrifuge_VDF_Face_Axi::xp protected
Referenced by associer_domaines().
xv
DoubleTab Force_Centrifuge_VDF_Face_Axi::xv protected
Referenced by ajouter_blocs(), and associer_domaines().
volume_entrelaces
DoubleVect Force_Centrifuge_VDF_Face_Axi::volume_entrelaces protected
Referenced by ajouter_blocs(), and associer_domaines().
porosite_surf
DoubleVect Force_Centrifuge_VDF_Face_Axi::porosite_surf protected
Referenced by ajouter_blocs(), and associer_domaines().