CEA TRUST Platform: Op_Dift_VDF_Elem_base Class Reference
Op_Dift_VDF_Elem_base Class Reference abstract
#include <Op_Dift_VDF_Elem_base.h>
Public Member Functions
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Dift_VDF_base
void contribuer_au_second_membre (DoubleTab &) const override
Public Member Functions inherited from Op_Diff_VDF_base
void completer () override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void dimensionner (Matrice_Morse &) const
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Constructor & Destructor Documentation
Op_Dift_VDF_Elem_base()
Op_Dift_VDF_Elem_base::Op_Dift_VDF_Elem_base (const Iterateur_VDF_base & iter_base) inline
Member Function Documentation
calculer_dt_stab_elem()
double Op_Dift_VDF_Elem_base::calculer_dt_stab_elem () const
References alpha_(), Nom::debute_par(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Domaine_VDF::dist_face(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Process::mp_max(), Domaine_dis_base::nb_elem(), Objet_U::que_suis_je(), and Champ_Don_base::valeurs().
Referenced by Op_Dift_VDF_Elem::calculer_dt_stab(), and Op_Dift_VDF_Multi_inco_Elem::calculer_dt_stab().
calculer_dt_stab_elem_axi()
double Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi () const
References alpha_(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Domaine_VDF::dist_face_axi(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_dis_base::nb_elem(), and Champ_Don_base::valeurs().
Referenced by Op_Dift_VDF_Elem_Axi::calculer_dt_stab(), and Op_Dift_VDF_Multi_inco_Elem_Axi::calculer_dt_stab().
calculer_dt_stab_elem_var_axi()
double Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi () const
References alpha_(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Objet_U::dimension, Domaine_VDF::dist_face_axi(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_dis_base::nb_elem(), and Champ_Don_base::valeurs().
modifier_pour_Cl()
void Op_Dift_VDF_Elem_base::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_VDF_Elem::modifier_pour_Cl().
dimensionner_blocs()
void Op_Dift_VDF_Elem_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
References Op_VDF_Elem::dimensionner(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), Field_base::le_nom(), and Matrice_Morse::nb_colonnes().
alpha_()
virtual double Op_Dift_VDF_Elem_base::alpha_ (const int) const protected pure virtual
Implemented in Op_Dift_Multiphase_VDF_Elem, Op_Dift_VDF_Elem, Op_Dift_VDF_Elem_Axi, Op_Dift_VDF_Multi_inco_Elem, and Op_Dift_VDF_Multi_inco_Elem_Axi.
Referenced by calculer_dt_stab_elem(), calculer_dt_stab_elem_axi(), and calculer_dt_stab_elem_var_axi().