CEA TRUST Platform: Joint_Items_32_64< _SIZE_ > Class Template Reference
Joint_Items_32_64< _SIZE_ > Class Template Reference
Public Member Functions
int nb_items_reels () const
ArrOfInt_t & set_items_communs ()
ArrOfInt_t & set_items_distants ()
IntTab_t & set_renum_items_communs ()
Detailed Description
template<typename _SIZE_>
class Joint_Items_32_64< _SIZE_ >
Ces structures sont initialisees dans Scatter. Elles sont ensuite utilisees par exemple pour creer un tableau distribue indexe par les indices des items geometriques.
See also
class Joint
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Joint_Items_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Joint_Items_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Joint_Items_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
Constructor & Destructor Documentation
Joint_Items_32_64()
template<typename _SIZE_ > Joint_Items_32_64< _SIZE_ >::Joint_Items_32_64
constructeur par defaut
Member Function Documentation
reset()
template<typename _SIZE_ > void Joint_Items_32_64< _SIZE_ >::reset
remise dans l'etat initial obtenu apres constructeur par defaut
nb_items_reels()
template<typename _SIZE_ > int Joint_Items_32_64< _SIZE_ >::nb_items_reels
Pas encore utilise (prevu pour faciliter la creation des tableaux distribues, mais les joints ne sont pas le bon endroit.
pour stocker cette valeur: il faut pouvoir la stocker meme s'il n'y a aucun processeur voisin).
items_communs()
template<typename _SIZE_ > const ArrOfInt_t& Joint_Items_32_64< _SIZE_ >::items_communs () const inline
Referenced by Scatter::calculer_renum_items_communs(), and Scatter::construire_md_vector().
items_distants()
template<typename _SIZE_ > const Joint_Items_32_64< _SIZE_ >::ArrOfInt_t & Joint_Items_32_64< _SIZE_ >::items_distants
Voir items_distants_.
Referenced by Scatter::calculer_nb_items_virtuels().
nb_items_virtuels()
template<typename _SIZE_ > int Joint_Items_32_64< _SIZE_ >::nb_items_virtuels
Voir nb_items_virtuels_.
Referenced by Scatter::construire_md_vector().
renum_items_communs()
template<typename _SIZE_ > const Joint_Items_32_64< _SIZE_ >::IntTab_t & Joint_Items_32_64< _SIZE_ >::renum_items_communs
Voir renum_items_communs_.
Referenced by Scatter::calculer_espace_distant().
set_nb_items_reels()
template<typename _SIZE_ > void Joint_Items_32_64< _SIZE_ >::set_nb_items_reels (int n)
Pas encore utilise.
set_items_communs()
template<typename _SIZE_ > Joint_Items_32_64< _SIZE_ >::ArrOfInt_t & Joint_Items_32_64< _SIZE_ >::set_items_communs
Renvoie le tableau items_communs_ pour le remplir.
(BM: ce tableau n'est pas encore rempli)
set_items_distants()
template<typename _SIZE_ > Joint_Items_32_64< _SIZE_ >::ArrOfInt_t & Joint_Items_32_64< _SIZE_ >::set_items_distants
Renvoie le tableau items_distants_ pour le remplir Voir Scatter::calculer_espace_distant,.
 Scatter::calculer_espace_distant_faces_frontieres,
 Scatter::calculer_espace_distant_elements
Referenced by Scatter::calculer_espace_distant().
set_nb_items_virtuels()
template<typename _SIZE_ > void Joint_Items_32_64< _SIZE_ >::set_nb_items_virtuels (int n)
Voir nb_items_virtuels_ Voir Scatter::calculer_nb_items_virtuels.
Referenced by Scatter::calculer_nb_items_virtuels().
set_renum_items_communs()
template<typename _SIZE_ > Joint_Items_32_64< _SIZE_ >::IntTab_t & Joint_Items_32_64< _SIZE_ >::set_renum_items_communs
Voir renum_items_communs_ Voir Scatter::calculer_colonne0_renum_faces_communes.
 Scatter::construire_correspondance_sommets_par_coordonnees
Referenced by Scatter::calculer_renum_items_communs().