CEA TRUST Platform: Discret_Thermique Class Reference
Discret_Thermique Class Reference
Additional Inherited Members
Public Member Functions inherited from Discretisation_base
virtual void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, OWN_PTR(Champ_Inc_base)&champ, const Nom &sous_type=NOM_VIDE) const
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const OBS_PTR(Champ_base)&champ_supp=OBS_PTR(Champ_base)()) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Discretisation_base
static void creer_champ (OWN_PTR(Champ_Don_base)&ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (OWN_PTR(Champ_Fonc_base)&ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (OWN_PTR(Champ_Inc_base)&ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
spatiale appliquee aux problemes thermiques. Les methodes virtuelles pures sont a implementer dans les classes derivees pour typer et discretiser les champs portes par les equations liees a la discretisation.
See also
Discretisation_base, Classe abstraite, Methodes abstraites, void temperature(const Schema_Temps_base&, Domaine_dis_base&, Champ_Inc_base&) const, void proprietes_physiques_milieu(Domaine_dis_base& ,Milieu_base& ,const Champ_Inc_base&) const
Member Function Documentation
temperature()
void Discret_Thermique::temperature (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Inc_base)& ch, int nb_comp = 1) const
References Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), and Schema_Temps_base::temps_courant().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Temperature::discretiser(), Energie_Multiphase::discretiser(), and Conduction::discretiser().
enthalpie()
void Discret_Thermique::enthalpie (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Inc_base)& ch, int nb_comp = 1) const
References Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), and Schema_Temps_base::temps_courant().
Referenced by Energie_Multiphase_Enthalpie::discretiser().
flux_neutronique()
void Discret_Thermique::flux_neutronique (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Inc_base)& ch, int nb_comp = 1) const
References Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), and Schema_Temps_base::temps_courant().
Fluctu_Temperature()
void Discret_Thermique::Fluctu_Temperature (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Inc_base)& ch) const
References Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), Field_base::nommer(), and Schema_Temps_base::temps_courant().
Flux_Chaleur_Turb()
void Discret_Thermique::Flux_Chaleur_Turb (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Inc_base)& ch) const
References Objet_U::dimension, Discretisation_base::discretiser_champ(), Schema_Temps_base::nb_valeurs_temporelles(), and Schema_Temps_base::temps_courant().
t_paroi()
virtual void Discret_Thermique::t_paroi (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)& ch) const inline virtual
Reimplemented in VEF_discretisation, and VDF_discretisation.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Convection_Diffusion_Temperature_base::creer_champ(), and Conduction::creer_champ().