CEA TRUST Platform: IJK_Striped_Writer Class Reference
IJK_Striped_Writer Class Reference
Public Member Functions
template<typename _OUT_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ >
void redistribute (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > &input, BigTRUSTArray< _OUT_TYPE_ > &output, const int nitot, const int njtot, const int nktot, const int nbcompo, int component)
template<typename _IN_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ >
void redistribute_load (const BigTRUSTArray< _IN_TYPE_ > &input, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > &output, const int nitot, const int njtot, const int nktot, const int nbcompo, const int component)
Detailed Description
Converts the input field to a linear lexicographic file written with optimized striping for lustre filesystem (splits the data into chunks of size "stripesize", give the chunks to different nodes of the MPI job and each node writes some of the chunks to maximize bandwidth). striping not yet implemented, all data is collected on the master node !
Member Function Documentation
write_data_template() [1/2]
template<typename _OUT_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ > Size_t IJK_Striped_Writer::write_data_template (const char * filename, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & f)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Sortie_Fichier_base::close(), Domaine_IJK::ELEM, Process::exit(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), Parallel_io_parameters::get_max_block_size(), Domaine_IJK::get_nb_items_global(), Process::je_suis_maitre(), Domaine_IJK::NODES, Sortie_Fichier_base::ouvrir(), Sortie::put(), redistribute(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Sortie::set_bin(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::dumplata_scalar().
write_data_template() [2/2]
template<typename _OUT_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ > Size_t IJK_Striped_Writer::write_data_template (const char * filename, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vx, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vy, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vz)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Sortie_Fichier_base::close(), Domaine_IJK::ELEM, Process::exit(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), Parallel_io_parameters::get_max_block_size(), Domaine_IJK::get_nb_items_global(), Process::je_suis_maitre(), Sortie_Fichier_base::ouvrir(), Sortie::put(), redistribute(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Sortie::set_bin(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
write_data_parallele_plan_template() [1/2]
template<typename _OUT_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ > Size_t IJK_Striped_Writer::write_data_parallele_plan_template (const char * filename, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vx, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vy, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vz)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Sortie_Fichier_base::close(), Domaine_IJK::ELEM, Process::exit(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_local_slice_index(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_nb_items_local(), Domaine_IJK::get_nprocessor_per_direction(), Sortie_Fichier_base::ouvrir(), Sortie::put(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Sortie::set_bin(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
write_data_parallele_plan_template() [2/2]
template<typename _OUT_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ > Size_t IJK_Striped_Writer::write_data_parallele_plan_template (const char * filename, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & f)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Sortie_Fichier_base::close(), Domaine_IJK::ELEM, Process::exit(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_nb_items_local(), Domaine_IJK::NODES, Sortie_Fichier_base::ouvrir(), Sortie::put(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Sortie::set_bin(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
write_data_parallel_template() [1/2]
template<typename _OUT_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ > Size_t IJK_Striped_Writer::write_data_parallel_template (const char * filename, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vx, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vy, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vz)
References Domaine_IJK::ELEM, Process::exit(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), and Domaine_IJK::get_nb_items_global().
write_data_parallel_template() [2/2]
template<typename _OUT_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ > Size_t IJK_Striped_Writer::write_data_parallel_template (const char * filename, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & f)
References Domaine_IJK::ELEM, Process::exit(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), Domaine_IJK::get_nb_items_global(), and Domaine_IJK::NODES.
write_data_parallel2_template()
template<typename _OUT_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Striped_Writer::write_data_parallel2_template (const char * filename, const int file_ni_tot, const int file_nj_tot, const int file_nk_tot, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vx, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vy, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & vz)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Process::barrier(), Schema_Comm::begin_comm(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Entree::eof(), Process::exit(), Entree::get(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Parallel_io_parameters::get_max_block_size(), Parallel_io_parameters::get_nb_writing_processes(), Domaine_IJK::get_offset_local(), Process::me(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Process::nproc(), Sortie::put(), Schema_Comm::recv_buffer(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Schema_Comm::send_buffer(), Schema_Comm::set_all_to_allv_flag(), Schema_Comm::set_send_recv_pe_list(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
redistribute()
template<typename _OUT_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Striped_Writer::redistribute (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & input, BigTRUSTArray< _OUT_TYPE_ > & output, const int nitot, const int njtot, const int nktot, const int nbcompo, int component)
Redistribute data from input (distributed ijk scalar field) to ouput (striped linear storage) output is a 'big' array (might contain more than 32b) les n_compo_tot sont inutiles ici !!!
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_IJK::ELEM, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_local_slice_index(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_localisation(), Domaine_IJK::get_nb_elem_local(), Domaine_IJK::get_nprocessor_per_direction(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_periodic_flag(), Domaine_IJK::get_processor_mapping(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), Process::je_suis_maitre(), Process::me(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by write_data_template().
redistribute_load()
template<typename _IN_TYPE_ , typename _TYPE_ , typename _TYPE_ARRAY_ > void IJK_Striped_Writer::redistribute_load (const BigTRUSTArray< _IN_TYPE_ > & input, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & output, const int nitot, const int njtot, const int nktot, const int nbcompo, const int component)
Redistribute data read by master procs to all other procs.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_nb_elem_local(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_processor_mapping(), Process::je_suis_maitre(), Process::me(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().