CEA TRUST Platform: Iterateur_PolyMAC_Elem< _TYPE_ > Class Template Reference
Iterateur_PolyMAC_Elem< _TYPE_ > Class Template Reference
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Iterateur_PolyMAC_Elem() [1/2]
template<class _TYPE_ > Iterateur_PolyMAC_Elem< _TYPE_ >::Iterateur_PolyMAC_Elem () inline
Iterateur_PolyMAC_Elem() [2/2]
template<class _TYPE_ > Iterateur_PolyMAC_Elem< _TYPE_ >::Iterateur_PolyMAC_Elem (const Iterateur_PolyMAC_Elem< _TYPE_ > & iter) inline
References Iterateur_PolyMAC_Elem< _TYPE_ >::elem, and TRUSTTab< _TYPE_, _SIZE_ >::ref().
Member Function Documentation
evaluateur() [1/2]
template<class _TYPE_ > Evaluateur_PolyMAC & Iterateur_PolyMAC_Elem< _TYPE_ >::evaluateur inline override virtual
Implements Iterateur_PolyMAC_base.
evaluateur() [2/2]
template<class _TYPE_ > const Evaluateur_PolyMAC & Iterateur_PolyMAC_Elem< _TYPE_ >::evaluateur inline override virtual
Implements Iterateur_PolyMAC_base.
calculer()
template<class _TYPE_ > DoubleTab & Iterateur_PolyMAC_Elem< _TYPE_ >::calculer (const DoubleTab & inco, DoubleTab & resu) const override virtual
Implements Iterateur_PolyMAC_base.
ajouter()
template<class _TYPE_ > DoubleTab & Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter (const DoubleTab & donne, DoubleTab & resu) const override virtual
Implements Iterateur_PolyMAC_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
calculer_flux_bord()
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord (const DoubleTab & donnee) const override virtual
Reimplemented from Iterateur_PolyMAC_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), Frontiere_dis_base::le_nom(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
contribuer_au_second_membre()
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre (DoubleTab & resu) const override virtual
Implements Iterateur_PolyMAC_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTTab< _TYPE_, _SIZE_ >::nb_dim().
ajouter_contribution()
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution (const DoubleTab & inco, Matrice_Morse & matrice) const override virtual
Implements Iterateur_PolyMAC_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
ajouter_contribution_vitesse()
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const override virtual
Implements Iterateur_PolyMAC_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTTab< _TYPE_, _SIZE_ >::nb_dim().
completer_()
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::completer_ inline override virtual
Implements Iterateur_PolyMAC_base.
impr()
template<class _TYPE_ > int Iterateur_PolyMAC_Elem< _TYPE_ >::impr (Sortie & os) const override virtual
Implements Iterateur_PolyMAC_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Frontiere_dis_base::le_nom(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), EcrFicPartage::syncfile(), and Schema_Temps_base::temps_courant().
modifier_flux()
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::modifier_flux
References Domaine_VF::face_voisins(), Field_base::nb_comp(), Domaine_VF::nb_faces_bord(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
ajouter_bords() [1/2]
template<class _TYPE_ > DoubleTab & Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_bords (const DoubleTab & donnee, DoubleTab & resu) const protected
References Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
ajouter_bords() [2/2]
template<class _TYPE_ > DoubleTab & Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_bords (const DoubleTab & donnee, DoubleTab & resu, int ncomp) const protected
References Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
ajouter_interne() [1/2]
template<class _TYPE_ > DoubleTab & Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_interne (const DoubleTab & donnee, DoubleTab & resu) const protected
References Domaine_VF::nb_faces(), and Domaine_VF::premiere_face_int().
ajouter_interne() [2/2]
template<class _TYPE_ > DoubleTab & Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_interne (const DoubleTab & donnee, DoubleTab & resu, int ncomp) const protected
References Domaine_VF::nb_faces(), and Domaine_VF::premiere_face_int().
contribuer_au_second_membre_bords() [1/2]
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_bords (DoubleTab & resu) const protected
References Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
contribuer_au_second_membre_bords() [2/2]
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_bords (DoubleTab & resu, int ncomp) const protected
References Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
contribuer_au_second_membre_interne() [1/2]
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_interne (DoubleTab & resu) const protected
References Domaine_VF::nb_faces(), and Domaine_VF::premiere_face_int().
contribuer_au_second_membre_interne() [2/2]
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_interne (DoubleTab & resu, int ncomp) const protected
References Domaine_VF::nb_faces(), and Domaine_VF::premiere_face_int().
ajouter_contribution_bords() [1/2]
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords (const DoubleTab & inco, Matrice_Morse & matrice) const protected
References Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
ajouter_contribution_bords() [2/2]
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords (const DoubleTab & inco, Matrice_Morse & matrice, int ncomp) const protected
References Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
ajouter_contribution_interne() [1/2]
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_interne (const DoubleTab & inco, Matrice_Morse & matrice) const protected
References Domaine_VF::nb_faces(), and Domaine_VF::premiere_face_int().
ajouter_contribution_interne() [2/2]
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_interne (const DoubleTab & inco, Matrice_Morse & matrice, int ncomp) const protected
References Domaine_VF::nb_faces(), and Domaine_VF::premiere_face_int().
ajouter_contribution_interne_vitesse()
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_interne_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const protected
References Domaine_VF::nb_faces(), and Domaine_VF::premiere_face_int().
ajouter_contribution_bords_vitesse()
template<class _TYPE_ > void Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const protected
References Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
milieu()
template<class _TYPE_ > const Milieu_base & Iterateur_PolyMAC_Elem< _TYPE_ >::milieu protected
Member Data Documentation
flux_evaluateur
template<class _TYPE_ > _TYPE_ Iterateur_PolyMAC_Elem< _TYPE_ >::flux_evaluateur protected
elem
template<class _TYPE_ > IntTab Iterateur_PolyMAC_Elem< _TYPE_ >::elem protected
Referenced by Iterateur_PolyMAC_Elem< _TYPE_ >::Iterateur_PolyMAC_Elem().
Flux
template<class _TYPE_ > SFichier Iterateur_PolyMAC_Elem< _TYPE_ >::Flux mutable protected