CEA TRUST Platform: Fluide_Quasi_Compressible Class Reference
Fluide_Quasi_Compressible Class Reference
Public Member Functions
void completer (const Probleme_base &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Fluide_Dilatable_base
void calculer_alpha () override
void set_Cp (double)
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Fluide_base
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Protected Member Functions inherited from Milieu_base
void ecrire (Sortie &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
c'est a dire heritant de fluide dilatable
See also
Milieu_base Fluide_Dilatable_base
Member Function Documentation
set_param()
void Fluide_Quasi_Compressible::set_param (Param & param) override virtual
Reimplemented from Fluide_Dilatable_base.
References Param::ajouter(), Param::ajouter_non_std(), omega_drho_dt_, Param::REQUIRED, Fluide_Dilatable_base::set_param(), and temps_debut_prise_en_compte_drho_dt_.
completer()
void Fluide_Quasi_Compressible::completer (const Probleme_base & pb) override virtual
Complete le fluide avec les champs inconnus associes au probleme.
Parameters
(Pb_Thermohydraulique& pb) le probleme a resoudre
Reimplemented from Fluide_Dilatable_base.
References Fluide_Dilatable_base::completer(), Process::exit(), Fluide_Dilatable_base::Pth_, and Fluide_Dilatable_base::traitement_PTh_.
discretiser()
void Fluide_Quasi_Compressible::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Fluide_Dilatable_base.
References Fluide_Dilatable_base::ch_temperature(), Fluide_Dilatable_base::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Probleme_base::equation(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and Fluide_Dilatable_base::type_fluide().
lire_motcle_non_standard()
int Fluide_Quasi_Compressible::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Fluide_Dilatable_base.
References Process::exit(), Fluide_Dilatable_base::lire_motcle_non_standard(), Fluide_Dilatable_base::Pth_, Fluide_Dilatable_base::Pth_n_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), Motcles::search(), and traitement_rho_gravite_.
Resoudre_EDO_PT()
void Fluide_Quasi_Compressible::Resoudre_EDO_PT () inline override virtual
Implements Fluide_Dilatable_base.
References Process::abort(), Fluide_Dilatable_base::Pth_, Fluide_Dilatable_base::Pth_n_, and Fluide_Dilatable_base::traitement_PTh_.
secmembre_divU_Z()
void Fluide_Quasi_Compressible::secmembre_divU_Z (DoubleTab & tab_W) const inline override virtual
Implements Fluide_Dilatable_base.
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute_sans_ech_esp_virt(), Fluide_Dilatable_base::ch_vitesse_, Process::je_suis_maitre(), omega_drho_dt_, TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), tab_W_old_, and temps_debut_prise_en_compte_drho_dt_.
get_traitement_rho_gravite()
int Fluide_Quasi_Compressible::get_traitement_rho_gravite () const inline
References traitement_rho_gravite_.
Referenced by Source_QC_Gravite_VEF::ajouter(), and Source_QC_Gravite_VDF::ajouter_blocs().
Member Data Documentation
traitement_rho_gravite_
int Fluide_Quasi_Compressible::traitement_rho_gravite_ = 0 protected
Referenced by get_traitement_rho_gravite(), and lire_motcle_non_standard().
temps_debut_prise_en_compte_drho_dt_
double Fluide_Quasi_Compressible::temps_debut_prise_en_compte_drho_dt_ = -DMAXFLOAT protected
Referenced by secmembre_divU_Z(), and set_param().
omega_drho_dt_
double Fluide_Quasi_Compressible::omega_drho_dt_ = 1. protected
Referenced by secmembre_divU_Z(), and set_param().
tab_W_old_
DoubleTab Fluide_Quasi_Compressible::tab_W_old_ mutable protected
Referenced by secmembre_divU_Z().