CEA TRUST Platform: Convection_Diffusion_Temperature_IBM Class Reference
Convection_Diffusion_Temperature_IBM Class Reference
Public Member Functions
bool initTimeStep (double dt) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Temperature
void associer_milieu_base (const Milieu_base &) override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Motcle & domaine_application () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Temperature_base
void associer_milieu_base (const Milieu_base &) override
Fluide_base & fluide ()
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
set_param()
void Convection_Diffusion_Temperature_IBM::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
References Convection_Diffusion_Temperature::set_param(), and Equation_IBM_proto::set_param_ibm_proto().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::set_param().
assembler()
void Convection_Diffusion_Temperature_IBM::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override virtual
Reimplemented from Equation_base.
References Equation_IBM_proto::assembler_ibm_proto().
preparer_calcul()
int Convection_Diffusion_Temperature_IBM::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
References Equation_base::preparer_calcul(), and Equation_IBM_proto::preparer_calcul_ibm_proto().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::preparer_calcul().
initTimeStep()
bool Convection_Diffusion_Temperature_IBM::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_IBM_Turbulent.
References Equation_base::initTimeStep(), and Equation_IBM_proto::initTimeStep_ibm_proto().
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::initTimeStep().
derivee_en_temps_inco_sources()
void Convection_Diffusion_Temperature_IBM::derivee_en_temps_inco_sources (DoubleTrav & secmem) override virtual
Reimplemented from Equation_base.
References Equation_IBM_proto::derivee_en_temps_inco_ibm_proto().
verify_scheme()
void Convection_Diffusion_Temperature_IBM::verify_scheme () override virtual
Reimplemented from Equation_base.
References Process::abort(), Equation_base::equation_non_resolue(), and Equation_IBM_proto::is_IBM().