CEA TRUST Platform: Modele_turbulence_scal_Prandtl Class Reference
Modele_turbulence_scal_Prandtl Class Reference
#include <Modele_turbulence_scal_Prandtl.h>
Public Member Functions
void mettre_a_jour (double) override
Public Member Functions inherited from Modele_turbulence_scal_diffturb_base
void associer_viscosite_turbulente (const Champ_Fonc_base &)
void completer () override
int reprendre (Entree &) override
Public Member Functions inherited from Modele_turbulence_scal_base
virtual void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &)
void associer_eqn (const Equation_base &)
virtual void imprimer (Sortie &) const
int limpr_nusselt (double, double, double, double) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Turbulence_paroi_scal_base & loi_paroi ()
const Turbulence_paroi_scal_base & loi_paroi () const
int loi_paroi_non_nulle () const
virtual int preparer_calcul ()
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Protected Member Functions
virtual Champ_Fonc_base & calculer_diffusivite_turbulente ()
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour la diffusivite turbulente: alpha_turb = visco_turb / Prdt_turb;
See also
Mod_Turb_scal_diffuturb_base
Member Function Documentation
mettre_a_jour()
void Modele_turbulence_scal_Prandtl::mettre_a_jour (double) override virtual
Calcule la diffusivite turbulente et la loi de paroi.
Parameters
(double)
Implements Modele_turbulence_scal_base.
References calculer_diffusivite_turbulente(), Milieu_base::capacite_calorifique(), Modele_turbulence_scal_base::diffusivite_turbulente_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Modele_turbulence_scal_base::equation(), Modele_turbulence_scal_base::loi_paroi_non_nulle(), Milieu_base::masse_volumique(), Probleme_base::milieu(), Equation_base::probleme(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
set_param()
void Modele_turbulence_scal_Prandtl::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_scal_base.
References Param::ajouter(), definition_fonction_, LePrdt_fct_, and Modele_turbulence_scal_base::set_param().
calculer_diffusivite_turbulente()
Champ_Fonc_base & Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente () protected virtual
Calcule la diffusivite turbulente.
diffusivite_turbulente = viscosite_turbulente / Prdt_turbulent
Returns
(Champ_Fonc_base&) la diffusivite turbulente nouvellement calculee
Exceptions
les champs diffusivite_turbulente et viscosite_turbulente doivent avoir le meme nombre de valeurs nodales
References definition_fonction_, Milieu_base::diffusivite(), Modele_turbulence_scal_base::diffusivite_turbulente_, Modele_turbulence_scal_base::equation(), Parser_U::eval(), Process::exit(), fonction1_, fonction_, Milieu_base::has_diffusivite(), LePrdt_, LePrdt_fct_, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Parser_U::setVar(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Don_base::valeurs().
Referenced by mettre_a_jour().
Member Data Documentation
LePrdt_
double Modele_turbulence_scal_Prandtl::LePrdt_ = 0.9 protected
Referenced by calculer_diffusivite_turbulente().
LePrdt_fct_
Nom Modele_turbulence_scal_Prandtl::LePrdt_fct_ protected
Referenced by calculer_diffusivite_turbulente(), and set_param().
definition_fonction_
Nom Modele_turbulence_scal_Prandtl::definition_fonction_ protected
Referenced by calculer_diffusivite_turbulente(), and set_param().
fonction_
Parser_U Modele_turbulence_scal_Prandtl::fonction_ protected
Referenced by calculer_diffusivite_turbulente().
fonction1_
Parser_U Modele_turbulence_scal_Prandtl::fonction1_ protected
Referenced by calculer_diffusivite_turbulente().