CEA TRUST Platform: Interpolation_IBM_mean_gradient_proto Class Reference
Interpolation_IBM_mean_gradient_proto Class Reference
Detailed Description
Pure C++ class to allow multiple inheritance in Interpolation_IBM_hybrid
Member Function Documentation
getSommetsVoisinsOf()
IntList& Interpolation_IBM_mean_gradient_proto::getSommetsVoisinsOf (int i) inline
References sommets_voisins_.
computeSommetsVoisins()
void Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins (Domaine_dis_base & le_dom_EF, const Champ_Don_base & solid_points, const Champ_Don_base & corresp_elems, bool has_corres) protected
References Domaine_32_64< _SIZE_ >::chercher_elements(), Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_dis_base::domaine(), Process::exit(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_dis_base::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_dis_base::nb_som_tot(), sommets_voisins_, and Champ_Don_base::valeurs().
Referenced by Interpolation_IBM_hybrid::discretise(), Interpolation_IBM_power_law_tbl_u_star::discretise(), and Interpolation_IBM_mean_gradient::discretise().
OWN_PTR() [1/4]
Interpolation_IBM_mean_gradient_proto::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [2/4]
Interpolation_IBM_mean_gradient_proto::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [3/4]
Interpolation_IBM_mean_gradient_proto::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [4/4]
Interpolation_IBM_mean_gradient_proto::OWN_PTR (Champ_Don_base) protected
Member Data Documentation
sommets_voisins_
IntLists Interpolation_IBM_mean_gradient_proto::sommets_voisins_ protected
Referenced by computeSommetsVoisins(), Interpolation_IBM_hybrid::getSommetsVoisinsOf(), Interpolation_IBM_mean_gradient::getSommetsVoisinsOf(), getSommetsVoisinsOf(), and Interpolation_IBM_power_law_tbl_u_star::getSommetsVoisinsOf().