CEA TRUST Platform: Champ_Elem_PolyMAC Class Reference
Champ_Elem_PolyMAC Class Reference
#include <Champ_Elem_PolyMAC.h>
Public Member Functions
DoubleTab & trace (const Frontiere_dis_base &fr, DoubleTab &x, double t, int distant) const override
Public Member Functions inherited from Champ_Inc_P0_base
Champ_base & affecter_ (const Champ_base &) override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
affecter_()
Champ_base & Champ_Elem_PolyMAC::affecter_ (const Champ_base & ch) override virtual
Implements Champ_base.
Reimplemented in Champ_Elem_PolyMAC_P0, and Champ_Elem_PolyMAC_P0P1NC.
References Champ_Inc_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_base::valeur_aux(), and Champ_Inc_base::valeurs().
imprime()
int Champ_Elem_PolyMAC::imprime (Sortie & os, int ncomp) const override virtual
Implements Champ_base.
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Champ_Inc_base::domaine(), Domaine_dis_base::domaine(), Champ_Inc_base::domaine_dis_base(), Field_base::nb_compo_, Domaine_32_64< _SIZE_ >::nb_som(), and Champ_Inc_base::valeurs().
fixer_nb_valeurs_nodales()
int Champ_Elem_PolyMAC::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_base.
Reimplemented in Champ_Elem_PolyMAC_P0P1NC.
References Champ_Inc_base::creer_tableau_distribue(), Champ_Inc_base::domaine(), and Champ_Inc_base::domaine_dis_base().
valeur_aux_faces()
DoubleTab & Champ_Elem_PolyMAC::valeur_aux_faces (DoubleTab & result) const override virtual
renvoie la valeur du champ aux faces
Reimplemented from Champ_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_Inc_base::domaine(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and Champ_Inc_base::valeurs().
trace()
DoubleTab & Champ_Elem_PolyMAC::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const inline override virtual
Calcule la trace d'un champ sur une frontiere au temps tps.
WEC : La frontiere passee en parametre doit faire partie du domaine sur lequel s'appuie le champ Le resultat est calcule sur cette frontiere et la taille du DoubleTab x correspond au nombre de faces de la frontiere. x peut avoir un espace virtuel, la fonction trace apelle echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF : Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Parameters
(Frontiere_dis_base&) frontiere discretisee sur laquelle on veut calculer la trace du champ au temps tps
(DoubleTab& x , double tps) les valeurs du champ sur la frontiere au temps tps
Returns
(DoubleTab&) les valeurs du champ sur la frontiere au temps tps
Reimplemented from Champ_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_Inc_base::domaine(), Champ_Inc_base::domaine_dis_base(), Frontiere_dis_base::frontiere(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Front_VF::nb_faces(), MD_Vector::non_nul(), Front_VF::num_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Frontiere_32_64< _SIZE_ >::trace_face_distant(), Frontiere_32_64< _SIZE_ >::trace_face_local(), and Champ_Inc_base::valeurs().