CEA TRUST Platform: Champ_front_tangentiel_VEF Class Reference
Champ_front_tangentiel_VEF Class Reference
#include <Champ_front_tangentiel_VEF.h>
Public Member Functions
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_var_instationnaire
int avancer (double temps) override
int initialiser (double temps, const Champ_Inc_base &inco) override
int reculer (double temps) override
const DoubleTab & valeurs_au_temps (double temps) const override
DoubleTab & valeurs_au_temps (double temps) override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
virtual void mettre_a_jour (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Classe derivee de Champ_front_base qui represente les champs aux frontieres tangentiels :
See also
Champ_front_base
Member Function Documentation
initialiser()
int Champ_front_tangentiel_VEF::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees externes a l'equation (couplage). Si mettre_a_jour le fait, alors initialiser ne doit pas appeler mettre_a_jour.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Ch_front_var_instationnaire_dep.
References Champ_front_base::domaine_dis(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Champ_front_base::frontiere_dis(), Ch_front_var_instationnaire_dep::initialiser(), Champ_front_base::les_valeurs, Roue::nb_cases(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VEF::oriente_normale(), and Champ_front_tangentiel::vit_tang.