CEA TRUST Platform: Fluide_Weakly_Compressible Class Reference
Fluide_Weakly_Compressible Class Reference
Public Member Functions
void completer (const Probleme_base &) override
Public Member Functions inherited from Fluide_Dilatable_base
void calculer_alpha () override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void set_Cp (double)
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Fluide_base
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Protected Member Functions inherited from Milieu_base
void ecrire (Sortie &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
c'est a dire heritant de Fluide_Dilatable_base
See also
Milieu_base Fluide_Dilatable_base
Member Function Documentation
set_param()
void Fluide_Weakly_Compressible::set_param (Param & param) override virtual
Reimplemented from Fluide_Dilatable_base.
References Param::ajouter(), Fluide_Dilatable_base::Pth_, Fluide_Dilatable_base::set_param(), time_activate_ptot_, use_grad_pression_eos_, use_hydrostatic_pressure_, and use_total_pressure_.
completer()
void Fluide_Weakly_Compressible::completer (const Probleme_base & pb) override virtual
Complete le fluide avec les champs inconnus associes au probleme.
Parameters
(Pb_Thermohydraulique& pb) le probleme a resoudre
Reimplemented from Fluide_Dilatable_base.
References Milieu_base::a_gravite(), Champ_base::affecter_(), ch_pression_eos_, ch_pression_hydro_, ch_unsolved_species_, checkTraitementPth(), Fluide_Dilatable_base::completer(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Probleme_base::equation(), Process::exit(), Milieu_base::masse_volumique(), Fluide_Dilatable_base::Pth_, Fluide_Dilatable_base::Pth_n_, Pth_n_tab_, Pth_tab_, Objet_U::que_suis_je(), time_activate_ptot_, use_hydrostatic_pressure_, use_pth_xyz(), use_saved_data(), use_total_hydro_pressure(), use_total_pressure_, Champ_Proto::valeurs(), and Fluide_base::viscosite_dynamique().
checkTraitementPth()
void Fluide_Weakly_Compressible::checkTraitementPth (const Domaine_Cl_dis_base & domaine_cl) override virtual
Reimplemented from Fluide_Dilatable_base.
References Fluide_Dilatable_base::checkTraitementPth(), Process::exit(), and Fluide_Dilatable_base::traitement_PTh_.
Referenced by completer().
discretiser()
void Fluide_Weakly_Compressible::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Fluide_Dilatable_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), ch_pression_eos_, ch_pression_hydro_, Fluide_Dilatable_base::ch_temperature(), ch_unsolved_species_, Milieu_base::champs_compris_, Fluide_Dilatable_base::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Probleme_base::equation(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), Schema_Temps_base::temps_courant(), and Fluide_Dilatable_base::type_fluide().
abortTimeStep()
void Fluide_Weakly_Compressible::abortTimeStep () override virtual
Reimplemented from Fluide_Dilatable_base.
References Fluide_Dilatable_base::abortTimeStep(), Fluide_Dilatable_base::Pth_, Fluide_Dilatable_base::Pth_n_, Pth_n_tab_, and Pth_tab_.
calculer_pression_tot()
void Fluide_Weakly_Compressible::calculer_pression_tot () override virtual
Calcule la pression totale : pression thermodynamique + pression hydrodynamique.
Reimplemented from Fluide_Dilatable_base.
References Fluide_Dilatable_base::calculer_pression_tot(), and use_total_hydro_pressure().
update_pressure_fields()
void Fluide_Weakly_Compressible::update_pressure_fields (double temps) override virtual
Reimplemented from Fluide_Dilatable_base.
References Milieu_base::a_gravite(), ch_pression_eos_, ch_pression_hydro_, Pth_tab_, and Fluide_Dilatable_base::update_pressure_fields().
write_mean_edo()
void Fluide_Weakly_Compressible::write_mean_edo (double temps) override virtual
Reimplemented from Fluide_Dilatable_base.
References Process::je_suis_maitre(), Fluide_Dilatable_base::output_file_, Fluide_Dilatable_base::Pth_, Pth_tab_, Fluide_Dilatable_base::traitement_PTh_, use_hydrostatic_pressure(), and use_total_pressure().
write_header_edo()
void Fluide_Weakly_Compressible::write_header_edo () override virtual
Reimplemented from Fluide_Dilatable_base.
References Process::je_suis_maitre(), Fluide_Dilatable_base::output_file_, Fluide_Dilatable_base::Pth_, use_hydrostatic_pressure(), and use_total_pressure().
Resoudre_EDO_PT()
void Fluide_Weakly_Compressible::Resoudre_EDO_PT () inline override virtual
Implements Fluide_Dilatable_base.
References Milieu_base::a_gravite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Process::exit(), Fluide_Dilatable_base::Pth_, Fluide_Dilatable_base::Pth_n_, Pth_n_tab_, Pth_tab_, Fluide_Dilatable_base::traitement_PTh_, use_hydrostatic_pressure(), and use_total_pressure().
pression_hydro() [1/2]
const Champ_Don_base& Fluide_Weakly_Compressible::pression_hydro () const inline
References ch_pression_hydro_.
pression_hydro() [2/2]
Champ_Don_base& Fluide_Weakly_Compressible::pression_hydro () inline
References ch_pression_hydro_.
pression_eos() [1/2]
const Champ_Don_base& Fluide_Weakly_Compressible::pression_eos () const inline
References ch_pression_eos_.
pression_eos() [2/2]
Champ_Don_base& Fluide_Weakly_Compressible::pression_eos () inline
References ch_pression_eos_.
fraction_massique_nonresolue() [1/2]
const Champ_Don_base& Fluide_Weakly_Compressible::fraction_massique_nonresolue () const inline
References ch_unsolved_species_.
Referenced by Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), and Loi_Etat_Multi_GP_WC::initialiser_inco_ch().
fraction_massique_nonresolue() [2/2]
Champ_Don_base& Fluide_Weakly_Compressible::fraction_massique_nonresolue () inline
References ch_unsolved_species_.
pression_th_tab() [1/2]
const DoubleTab& Fluide_Weakly_Compressible::pression_th_tab () const inline
References Pth_tab_.
Referenced by Source_WC_Chaleur::ajouter_(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_TPPI_WC_base::calculer_masse_volumique(), and Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
pression_th_tab() [2/2]
DoubleTab& Fluide_Weakly_Compressible::pression_th_tab () inline
References Pth_tab_.
pression_thn_tab() [1/2]
const DoubleTab& Fluide_Weakly_Compressible::pression_thn_tab () const inline
References Pth_n_tab_.
Referenced by Source_WC_Chaleur::ajouter_().
pression_thn_tab() [2/2]
DoubleTab& Fluide_Weakly_Compressible::pression_thn_tab () inline
References Pth_n_tab_.
secmembre_divU_Z()
void Fluide_Weakly_Compressible::secmembre_divU_Z (DoubleTab & tab_W) const inline override virtual
Implements Fluide_Dilatable_base.
set_pression_th_tab()
void Fluide_Weakly_Compressible::set_pression_th_tab (DoubleTab & Pth_tab) inline
References Pth_n_tab_, and Pth_tab_.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
set_resume_flag()
void Fluide_Weakly_Compressible::set_resume_flag () inline
References sim_resumed_.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
use_total_pressure()
bool Fluide_Weakly_Compressible::use_total_pressure () inline
References use_total_pressure_.
Referenced by Resoudre_EDO_PT(), write_header_edo(), and write_mean_edo().
use_hydrostatic_pressure()
bool Fluide_Weakly_Compressible::use_hydrostatic_pressure () inline
References use_hydrostatic_pressure_.
Referenced by Resoudre_EDO_PT(), write_header_edo(), and write_mean_edo().
use_pth_xyz()
bool Fluide_Weakly_Compressible::use_pth_xyz () inline
Referenced by completer().
use_total_hydro_pressure()
bool Fluide_Weakly_Compressible::use_total_hydro_pressure () inline
References use_hydrostatic_pressure_, and use_total_pressure_.
Referenced by Source_WC_Chaleur::ajouter_(), calculer_pression_tot(), and completer().
use_saved_data()
bool Fluide_Weakly_Compressible::use_saved_data () inline
References sim_resumed_.
Referenced by completer().
use_grad_pression_eos()
bool Fluide_Weakly_Compressible::use_grad_pression_eos () inline
References use_grad_pression_eos_.
Referenced by Source_WC_Chaleur::ajouter_().
OWN_PTR()
Fluide_Weakly_Compressible::OWN_PTR (Champ_Don_base) protected
Member Data Documentation
ch_pression_hydro_
Fluide_Weakly_Compressible::ch_pression_hydro_ protected
Referenced by completer(), discretiser(), pression_hydro(), and update_pressure_fields().
ch_pression_eos_
Fluide_Weakly_Compressible::ch_pression_eos_ protected
Referenced by completer(), discretiser(), pression_eos(), and update_pressure_fields().
ch_unsolved_species_
Fluide_Weakly_Compressible::ch_unsolved_species_ protected
Referenced by completer(), discretiser(), and fraction_massique_nonresolue().
Pth_tab_
DoubleTab Fluide_Weakly_Compressible::Pth_tab_ protected
Referenced by abortTimeStep(), completer(), pression_th_tab(), Resoudre_EDO_PT(), set_pression_th_tab(), update_pressure_fields(), and write_mean_edo().
Pth_n_tab_
DoubleTab Fluide_Weakly_Compressible::Pth_n_tab_ protected
Referenced by abortTimeStep(), completer(), pression_thn_tab(), Resoudre_EDO_PT(), and set_pression_th_tab().
P_NS_elem_
DoubleTab Fluide_Weakly_Compressible::P_NS_elem_ protected
use_total_pressure_
int Fluide_Weakly_Compressible::use_total_pressure_ = 0 protected
Referenced by completer(), set_param(), use_total_hydro_pressure(), and use_total_pressure().
use_hydrostatic_pressure_
int Fluide_Weakly_Compressible::use_hydrostatic_pressure_ = 0 protected
Referenced by completer(), set_param(), use_hydrostatic_pressure(), and use_total_hydro_pressure().
use_grad_pression_eos_
int Fluide_Weakly_Compressible::use_grad_pression_eos_ = 1 protected
Referenced by set_param(), and use_grad_pression_eos().
sim_resumed_
int Fluide_Weakly_Compressible::sim_resumed_ = 0 protected
Referenced by set_resume_flag(), and use_saved_data().
time_activate_ptot_
double Fluide_Weakly_Compressible::time_activate_ptot_ = -1. protected
Referenced by completer(), and set_param().