CEA TRUST Platform: Champ_Fonc_MED Class Reference
Champ_Fonc_MED Class Reference
#include <Champ_Fonc_MED.h>
Public Member Functions
void mettre_a_jour (double) override
DoubleTab & remplir_coord_noeuds (DoubleTab &) const override
int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
int fixer_nb_valeurs_nodales (int nb_noeuds) override
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void resetTime (double time) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Champ_Fonc_P0
Member Function Documentation
associer_domaine_dis_base()
void Champ_Fonc_MED::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis_base) inline override virtual
Reimplemented from Champ_Fonc_base.
domaine_dis_base()
const Domaine_dis_base & Champ_Fonc_MED::domaine_dis_base () const override virtual
Reimplemented from Champ_Fonc_base.
References domainebidon_inst.
domaine_vf()
const Domaine_VF & Champ_Fonc_MED::domaine_vf () const inline override virtual
Reimplemented from Champ_Fonc_base.
mettre_a_jour()
void Champ_Fonc_MED::mettre_a_jour (double un_temps) override virtual
Mise a jour en temps du champ.
Parameters
(double temps) le temps de mise a jour
Reimplemented from Champ_Fonc_base.
Reimplemented in Champ_Fonc_MED_Tabule.
References lire().
Referenced by Pb_MED::get_champ().
creer()
int Champ_Fonc_MED::creer (const Nom & nom_fic, const Domaine & dom, const Motcle & localisation, ArrOfDouble & temps_sauv)
References Domaine_dis_base::associer_domaine(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Noms::contient_(), domainebidon_inst, Process::exit(), Field_base::fixer_nb_comp(), Champ_Fonc_base::fixer_nb_valeurs_nodales(), Nom::getString(), le_champ(), Field_base::le_nom(), Nom::le_nom(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_som(), nom_champ_dans_fichier_med_, nom_fichier_med_, nom_maillage_, and Field_base::nommer().
Referenced by Pb_MED::creer_champ().
domaine()
const Domaine & Champ_Fonc_MED::domaine () const inline
Referenced by Partitionneur_Fichier_MED::construire_partition(), and valeur_a().
lire()
void Champ_Fonc_MED::lire (double tps, int given_iteration = -1) virtual
Reimplemented in Champ_Fonc_MED_Table_Temps.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domainebidon_inst, Process::exit(), filter, Nom::getString(), last_time_only_, le_champ(), Field_base::le_nom(), Champ_Fonc_base::mettre_a_jour(), nb_dt, Domaine_dis_base::nb_elem(), nom_champ_dans_fichier_med_, nom_fichier_med_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), temps_sauv_, Champ_Don_base::valeurs(), and valeurs().
Referenced by Champ_Fonc_MED_Tabule::mettre_a_jour(), and mettre_a_jour().
nb_pas_temps()
int Champ_Fonc_MED::nb_pas_temps () inline
References nb_dt.
valeurs() [1/2]
DoubleTab & Champ_Fonc_MED::valeurs () inline override virtual
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
Returns
(DoubleTab&) le tableau des valeurs du champs
Reimplemented from Champ_Don_base.
References le_champ(), and Champ_Don_base::valeurs().
Referenced by Partitionneur_Fichier_MED::construire_partition(), lire(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), and Champ_Fonc_MED_Tabule::mettre_a_jour().
valeurs() [2/2]
const DoubleTab & Champ_Fonc_MED::valeurs () const inline override virtual
Reimplemented from Champ_Don_base.
References le_champ(), and Champ_Don_base::valeurs().
valeur_aux_elems()
DoubleTab & Champ_Fonc_MED::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References le_champ(), and Champ_base::valeur_aux_elems().
Referenced by Partitionneur_Fichier_MED::construire_partition().
valeur_aux_elems_compo()
DoubleVect & Champ_Fonc_MED::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_base.
References le_champ(), and Champ_base::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Fonc_MED::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
References le_champ(), and Champ_base::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc_MED::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const inline override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
References le_champ(), and Champ_base::valeur_aux_sommets_compo().
valeur_a()
DoubleVect & Champ_Fonc_MED::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const inline override virtual
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle valeur_aux(const DoubleTab &, DoubleTab &)
Parameters
(DoubleVect&) les coordonnees du point ou evaluer le champ
(DoubleVect& valeurs) En entree: doit avoir la bonne taille (nb_comp), en sortie contient les composantes du champ.
Returns
(reference a "valeurs")
Reimplemented from Champ_base.
References Domaine_32_64< _SIZE_ >::chercher_elements(), Domaine_dis_base::domaine(), domaine(), domainebidon_inst, le_champ(), and Champ_base::valeur_a_elem().
valeur_a_elem()
DoubleVect & Champ_Fonc_MED::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
References le_champ(), and Champ_base::valeur_a().
remplir_coord_noeuds()
DoubleTab & Champ_Fonc_MED::remplir_coord_noeuds (DoubleTab & coord) const inline override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab& coord)
Returns
(DoubleTab&) renvoie toujours le parametre coord
Reimplemented from Champ_Fonc_base.
References le_champ(), and Champ_Fonc_base::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Fonc_MED::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented from Champ_Fonc_base.
References le_champ(), and Champ_Fonc_base::remplir_coord_noeuds_et_polys().
le_champ() [1/2]
const Champ_Fonc_base & Champ_Fonc_MED::le_champ () const inline virtual
Referenced by creer(), Pb_MED::creer_champ(), Pb_MED::get_champ(), lire(), Champ_Fonc_MED_Table_Temps::lire(), remplir_coord_noeuds(), remplir_coord_noeuds_et_polys(), valeur_a(), valeur_a_elem(), valeur_aux_elems(), valeur_aux_elems_compo(), valeur_aux_sommets(), valeur_aux_sommets_compo(), valeurs(), and valeurs().
le_champ() [2/2]
Champ_Fonc_base & Champ_Fonc_MED::le_champ () inline virtual
get_saved_times()
const ArrOfDouble & Champ_Fonc_MED::get_saved_times () const
References temps_sauv_.
OBS_PTR()
Champ_Fonc_MED::OBS_PTR (Domaine) protected
OWN_PTR()
Champ_Fonc_MED::OWN_PTR (Champ_Fonc_base) protected
set_param()
void Champ_Fonc_MED::set_param (Param & param) protected virtual
Reimplemented in Champ_Fonc_MED_Table_Temps.
References Param::ajouter(), Param::ajouter_flag(), last_time_only_, loc_, nom_champ_, nom_decoup_, nom_dom_, nom_fichier_med_, nom_maillage_, Param::OPTIONAL, Param::REQUIRED, temps_, and use_existing_domain_.
Referenced by Champ_Fonc_MED_Table_Temps::set_param().
readOn_old_syntax()
void Champ_Fonc_MED::readOn_old_syntax (Entree & is, Nom & chaine_lue, bool & nom_decoup_lu) protected
Member Data Documentation
nom_fichier_med_
Nom Champ_Fonc_MED::nom_fichier_med_ protected
Referenced by creer(), lire(), and set_param().
nom_champ_
Nom Champ_Fonc_MED::nom_champ_ protected
Referenced by set_param().
nom_decoup_
Nom Champ_Fonc_MED::nom_decoup_ protected
Referenced by set_param().
nom_dom_
Nom Champ_Fonc_MED::nom_dom_ protected
Referenced by set_param().
nom_maillage_
Nom Champ_Fonc_MED::nom_maillage_ protected
Referenced by creer(), and set_param().
loc_
Motcle Champ_Fonc_MED::loc_ protected
Referenced by set_param().
use_existing_domain_
bool Champ_Fonc_MED::use_existing_domain_ = false protected
Referenced by set_param().
temps_
double Champ_Fonc_MED::temps_ =0.0 protected
Referenced by set_param().
last_time_only_
bool Champ_Fonc_MED::last_time_only_ = false protected
Referenced by lire(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), and set_param().
dom_med_
Domaine Champ_Fonc_MED::dom_med_ protected
domainebidon_inst
Domaine_VF_inst Champ_Fonc_MED::domainebidon_inst protected
Referenced by creer(), domaine_dis_base(), lire(), Champ_Fonc_MED_Table_Temps::lire(), Champ_Fonc_MED_Table_Temps::lire_donnees_champ(), and valeur_a().
numero_ch
int Champ_Fonc_MED::numero_ch = -10 protected
nb_dt
int Champ_Fonc_MED::nb_dt = -10 protected
Referenced by lire(), and nb_pas_temps().
nom_champ_dans_fichier_med_
Nom Champ_Fonc_MED::nom_champ_dans_fichier_med_ protected
Referenced by creer(), and lire().
filter
std::vector<trustIdType> Champ_Fonc_MED::filter protected
Referenced by lire().
temps_sauv_
ArrOfDouble Champ_Fonc_MED::temps_sauv_ protected
Referenced by get_saved_times(), lire(), and Champ_Fonc_MED_Tabule::mettre_a_jour().