CEA TRUST Platform: Frontiere_dis_base Class Reference
Frontiere_dis_base Class Reference
Public Member Functions
void associer_frontiere (const Frontiere &)
Frontiere & frontiere ()
const Frontiere & frontiere () const
const Nom & le_nom () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Les objets Frontiere_dis_base contiennent un reference vers l'objet geometrique Frontiere.
See also
Frontiere Domaine_dis
Member Function Documentation
associer_frontiere()
void Frontiere_dis_base::associer_frontiere (const Frontiere & fr)
Associe l'objet frontiere geometrique a la frontiere discretisee.
Parameters
(Frontiere& fr) la frontiere geometrique
associer_Domaine_dis()
void Frontiere_dis_base::associer_Domaine_dis (const Domaine_dis_base & z)
frontiere() [1/2]
const Frontiere & Frontiere_dis_base::frontiere () const
Renvoie la frontiere geometrique associee.
(version const)
Returns
(Frontiere&) la frontiere geometrique associee
Referenced by Ch_front_input::buildSommetsFaces(), Champ_front_recyclage::calcul_moyenne_recyclee(), Traitement_particulier_NS_EC::calculer_Ec(), Echange_contact_VDF::calculer_h_autre_pb(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Equation_base::completer(), Periodique::completer(), Terme_Source_Canal_perio::completer(), Echange_interne_global_impose::completer(), Domaine_Cl_VDF::completer(), Champ_Generique_Extraction::completer(), Champ_Generique_Extraction::get_champ(), Ch_front_input::getTemplate(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Ch_front_Vortex::initialiser(), Champ_front_lu::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Champ_front_var::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_contact_VEF::initialiser(), Champ_front_calc::initialiser(), Domaine_Cl_dis_base::la_cl_de_la_face(), Champ_front_synt::mettre_a_jour(), Ch_front_Vortex::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_local_face(), Front_VF::num_premiere_face(), Champ_front_MED::remplir_tab(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), Champ_implementation_P0::trace(), Champ_implementation_sommet::trace(), Champ_P1NC_implementation::trace(), Champ_Q1NC_implementation::trace(), Champ_Elem_PolyMAC::trace(), Champ_front_contact_VEF::trace_face_raccord(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Champ_front_base::valeurs_face(), and Ecrire_fichier_xyz_valeur::write_fields().
frontiere() [2/2]
Frontiere & Frontiere_dis_base::frontiere ()
Renvoie la frontiere geometrique associee.
Returns
(Frontiere&) la frontiere geometrique associee
domaine_dis()
const Domaine_dis_base & Frontiere_dis_base::domaine_dis () const
Referenced by Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_calc_interne::completer(), Champ_front_base::domaine_dis(), Champ_front_recyclage::get_coord_faces(), Champ_front_contact_VEF::initialiser(), Champ_front_calc::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), and Champ_front_txyz::mettre_a_jour().
le_nom()
const Nom & Frontiere_dis_base::le_nom () const override virtual
Renvoie le nom de la frontiere geometrique.
Returns
(Nom&) le nom de la frontiere geometrique
Reimplemented from Objet_U.
References Nom::le_nom().
Referenced by Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_bords(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Champ_front_contact_VEF::associer_front_vf_et_ch_front_autre_pb(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Operateur_base::completer(), Source_Masse_Fluide_Dilatable_base::completer(), Terme_Source_Canal_perio::completer(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Champ_front_fonc_gradient::condition_limite(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_bords(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Paroi_scal_hyd_base_EF::equivalent_distance_name(), Paroi_scal_hyd_base_VEF::equivalent_distance_name(), Paroi_scal_hyd_base_VDF::equivalent_distance_name(), Source_Masse_Fluide_Dilatable_base::fill_val_flux_tab(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Iterateur_VDF_Elem< _TYPE_ >::impr(), Iterateur_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Turbulence_paroi_scal_base::imprimer_nusselt_mean_only(), Turbulence_paroi_base::imprimer_ustar_mean_only(), Echange_contact_VDF::initialiser(), Champ_front_recyclage::lire_fichier_format3(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Operateur_base::ouvrir_fichier(), Domaine_dis_base::rang_frontiere(), Assembleur_P_VDF::remplir(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_Face_VDF_implementation::trace(), and Echange_contact_VDF::verifier_correspondance().
OBS_PTR() [1/2]
Frontiere_dis_base::OBS_PTR (Frontiere) protected
OBS_PTR() [2/2]
Frontiere_dis_base::OBS_PTR (Domaine_dis_base) protected