CEA TRUST Platform: PE_Groups Class Reference
PE_Groups Class Reference
Static Public Member Functions
static void create_group (const ArrOfInt &liste_pe, OWN_PTR(Comm_Group) &group, int force_Comm_Group_NoParallel=0)
static int enter_group (const Comm_Group &group)
static void exit_group ()
static void finalize ()
static void init_group (const ArrOfInt &liste_pe, OWN_PTR(Comm_Group) &group)
static void initialize (const Comm_Group &groupe_trio_u)
static int rank_translate (int rank, const Comm_Group &group, const Comm_Group &dest_group=current_group())
Detailed Description
destruction et le changement du groupe de processeurs actif. La creation du groupe principal doit etre dans le MAIN.cpp et il faut initialiser PE_Groups en lui donnant le groupe principal. Les autres groupes crees seront du meme type.
See also
la class Comm_Group
Member Function Documentation
current_group()
const Comm_Group & PE_Groups::current_group () inline static
renvoie une reference au groupe de processeurs actif courant
Referenced by Process::barrier(), Schema_Comm::begin_comm(), Solv_Petsc::create_solver(), Schema_Comm::echange_messages(), Schema_Comm::echange_taille(), Schema_Comm::end_comm(), enter_group(), Schema_Comm_Vecteurs::exchange(), exit_group(), mon_main::finalize(), Comm_Group::init_group(), Process::je_suis_maitre(), Process::me(), Process::mp_and(), Process::mp_or(), Process::mp_sum(), Process::mppartial_sum(), Process::mpsum_multiple(), Process::nproc(), Schema_Comm::operator=(), Solv_rocALUTION::resoudre_systeme(), Schema_Comm::Schema_Comm(), Schema_Comm::set_group(), Schema_Comm::set_send_recv_pe_list(), and EcrFicPartage::syncfile().
create_group()
void PE_Groups::create_group (const ArrOfInt & liste_pe, OWN_PTR(Comm_Group) & group, int force_Comm_Group_NoParallel = 0) static
Creation d'un nouveau groupe de processeurs (utilisation possible n'importe ou dans le code)
Il faut l'appeler simultanement sur tous les processeurs du groupe current_group() avec le meme tableau liste_pe. liste_pe est la liste des rangs dans le groupe courant des processeurs que l'on veut inclure dans le groupe. Le premier de la liste sera le maitre du groupe. La liste ne doit pas comporter de doublon et doit contenir au moins un processeur. La methode type et initialize l'objet group. Il faut ensuite appeler enter_group() et exit_group() (autant de fois qu'on veut)
References Comm_Group::init_group(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Execute_parallel::interpreter(), My_Comm_Group::interpreter(), Lata_2_Other::interpreter(), and Debog_Pb::read_geometry_data().
init_group()
void PE_Groups::init_group (const ArrOfInt & liste_pe, OWN_PTR(Comm_Group) & group) static
Initialisation d'un nouveau groupe de processeurs deja instantie (utilisation possible n'importe ou dans le code)
Il faut l'appeler simultanement sur tous les processeurs du groupe current_group() avec le meme tableau liste_pe. liste_pe est la liste des rangs dans le groupe courant des processeurs que l'on veut inclure dans le groupe. Le premier de la liste sera le maitre du groupe. La liste ne doit pas comporter de doublon et doit contenir au moins un processeur. La methode type et initialize l'objet group. Il faut ensuite appeler enter_group() et exit_group() (autant de fois qu'on veut)
References Comm_Group::init_group().
enter_group()
int PE_Groups::enter_group (const Comm_Group & group) static
Si le processeur local appartient au groupe, le groupe courant pour ce processeur devient "group" et on renvoie 1, sinon on renvoie 0.
Une reference au groupe actuel est sauvegardee et sera restauree quand on appellera exit_group(). Cette methode doit etre appelee simultanement sur tous les processeurs du groupe "group". Attention: a chaque enter_group() doit correspondre un exit_group(). Cependant, il n'est pas interdit d'entrer plusieurs fois de suite dans le meme groupe, ni d'entrer dans un groupe plus grand que le groupe actuel. Exemple : group1 et group2 forment une partition du groupe_TRUST()
int sync_point(int x) { PE_Groups::enter_group(groupe_TRUST()); int i = mp_sum(x); PE_Groups::exit_group(); return i; } if (PE_Groups::enter_group(group1)) { s1 = mp_sum(x); // Somme sur le groupe 2 // Point de synchro avec l'autre groupe: s_all = sync_point(x); } else if (PE_Groups::enter_group(group2)) { s2 = mp_sum(x); // Point de synchro avec l'autre groupe: s_all = sync_point(x); } else { Cerr << "Error: processor " << me() << " is not within a subgroup."; exit(); } PE_Groups::exit_group(); // Sort du sous-groupe
References Comm_Group::barrier(), Comm_Group::check_enabled(), current_group(), Process::exit(), and rank_translate().
Referenced by Execute_parallel::interpreter(), Lata_2_Other::interpreter(), and Debog_Pb::read_geometry_data().
exit_group()
void PE_Groups::exit_group () static
Retourne dans le groupe ou l'on etait avant le dernier enter_group() reussi (dont le resultat a ete 1).
Cette methode doit etre appelee simultanement sur tous les processeurs du current_group() actif juste avant exit_group()).
References Comm_Group::barrier(), Comm_Group::check_enabled(), current_group(), and Process::exit().
Referenced by Execute_parallel::interpreter(), Lata_2_Other::interpreter(), and Debog_Pb::read_geometry_data().
get_nb_groups()
const int & PE_Groups::get_nb_groups () static
Referenced by Solv_Petsc::create_solver().
rank_translate()
int PE_Groups::rank_translate (int rank, const Comm_Group & group, const Comm_Group & dest_group = current_group()) static
Calcule le rank dans le groupe courant du processeur de rang "rank" dans le "group".
Il faut que 0 <= rank < group.nproc() Si le processeur en question n'appartient pas au groupe courant, renvoie -1.
Referenced by enter_group().
groupe_TRUST()
const Comm_Group & PE_Groups::groupe_TRUST () static
Renvoie une reference au groupe de tous les processeurs TRUST.
Referenced by Process::exit(), Schema_Comm_Vecteurs_Static_Data::init(), Comm_Group::init_group(), and Comm_Group::init_group_node().
get_node_group()
const Comm_Group & PE_Groups::get_node_group () static
Renvoie une reference au groupe sur les noeuds.
Referenced by TRUST_2_PDI::init(), Process::node_master(), and TRUST_2_PDI::share_TRUSTTab_dimensions().
get_node_master()
const Comm_Group & PE_Groups::get_node_master () static
Renvoie le groupe contenant le maitre de mon noeud.
Referenced by TRUST_2_PDI::init().
get_user_defined_group()
const Comm_Group & PE_Groups::get_user_defined_group () static
Renvoie une reference au groupe sur defini par l'utilisateur.
Referenced by Process::exit(), and mon_main::finalize().
has_user_defined_group()
bool PE_Groups::has_user_defined_group () static
Referenced by Process::exit(), and mon_main::finalize().
initialize()
void PE_Groups::initialize (const Comm_Group & groupe_trio_u) static
Methode a appeler au debut de l'execution (MAIN.
cpp) Elle initialise current_group() avec groupe_trio_u
Referenced by mon_main::init_parallel().
initialize_node()
void PE_Groups::initialize_node (const Comm_Group & ngrp) static
Methode a appeler apres l'initialisation de trio_u_world et l'initialisation des compteurs statistiques de TRUST.
Referenced by mon_main::dowork().
initialize_node_master()
void PE_Groups::initialize_node_master (const Comm_Group & ngrp) static
Methode a appeler apres l'initialisation de trio_u_world et de node_group et l'initialisation des compteurs statistiques de TRUST.
Referenced by mon_main::dowork().
initialize_user_defined_group()
void PE_Groups::initialize_user_defined_group (const Comm_Group & ngrp) static
Referenced by My_Comm_Group::interpreter().
finalize()
void PE_Groups::finalize () static
Methode a appeler en fin d'execution, une fois qu'on est revenu dans le groupe_TRUST() et juste avant de detruire de Comm_Group.
principal.
Referenced by Process::exit(), and mon_main::~mon_main().