CEA TRUST Platform: Op_Diff_DG_Elem Class Reference
Op_Diff_DG_Elem Class Reference
Public Member Functions
void completer () override
void contribuer_au_second_membre (DoubleTab &resu) const override
void dimensionner (Matrice_Morse &mat) const override
void modifier_pour_Cl (Matrice_Morse &la_matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Diff_DG_base
double calculer_dt_stab () const override
int impr (Sortie &os) const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
calculer_flux_bord()
virtual void Op_Diff_DG_Elem::calculer_flux_bord (const DoubleTab & inco) const virtual delete
modifier_pour_Cl()
void Op_Diff_DG_Elem::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
completer()
void Op_Diff_DG_Elem::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_DG_base.
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente(), Op_Diff_DG_base::completer(), Modele_turbulence_scal_base::conductivite_turbulente(), Nom::debute_par(), MorEqn::equation(), Process::exit(), Champ_Inc_P0_base::fcl(), Operateur_base::flux_bords_, Equation_base::get_modele(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUST_Ref_Objet_U::valeur(), and Champ_Inc_base::valeurs().
dimensionner()
void Op_Diff_DG_Elem::dimensionner (Matrice_Morse & mat) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_Elem_DG::get_order(), Champ_Elem_DG::indices_glob_elem(), and Option_DG::Nb_col_from_order().
Referenced by dimensionner_blocs().
has_interface_blocs()
int Op_Diff_DG_Elem::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
dimensionner_blocs()
void Op_Diff_DG_Elem::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
References dimensionner(), MorEqn::equation(), Nom::getString(), Equation_base::inconnue(), Operateur_Diff_base::init_op_ext(), Field_base::le_nom(), and Operateur_Diff_base::op_ext.
ajouter_blocs()
void Op_Diff_DG_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Operateur_base.
References Objet_U::dimension, MorEqn::equation(), Champ_Elem_DG::get_eta_facet(), Nom::getString(), Equation_base::inconnue(), Champ_Elem_DG::indices_glob_elem(), Field_base::le_nom(), Champ_Elem_DG::nb_bfunc(), Quadrature_base::nb_pts_integ_max(), Op_Diff_DG_base::update_nu(), and Champ_Inc_base::valeurs().
dimensionner_termes_croises()
void Op_Diff_DG_Elem::dimensionner_termes_croises (Matrice_Morse & matrice, const Probleme_base & autre_pb, int nl, int nc) const override virtual
Reimplemented from Operateur_base.
ajouter_termes_croises()
void Op_Diff_DG_Elem::ajouter_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
contribuer_termes_croises()
void Op_Diff_DG_Elem::contribuer_termes_croises (const DoubleTab & inco, const Probleme_base & autre_pb, const DoubleTab & autre_inco, Matrice_Morse & matrice) const override virtual
Reimplemented from Operateur_base.
contribuer_au_second_membre()
void Op_Diff_DG_Elem::contribuer_au_second_membre (DoubleTab &) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Cond_lim_base::champ_front(), Quadrature_base::compute_integral_on_facet(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Champ_Elem_DG::eval_bfunc_on_facets(), Champ_Elem_DG::eval_grad_bfunc_on_facets(), Champ_Elem_DG::get_eta_facet(), Quadrature_base::get_integ_points_facets(), Champ_Elem_DG::nb_bfunc(), Front_VF::nb_faces(), Op_Diff_DG_base::nu_, Front_VF::num_face(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant(), and Champ_front_txyz::valeur_au_temps_et_au_point().