CEA TRUST Platform: Convection_Diffusion_std Class Reference
Convection_Diffusion_std Class Reference abstract
Public Member Functions
void associer_vitesse (const Champ_base &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
d'un scalaire.
Cette classe porte les termes communs a l'equation
de transport d'un scalaire en regime laminaire.
On se place sous l'hypothese de fluide incompressible.
    DT/dt = div(terme visqueux) + termes sources/rho_0
avec DT/dt : derivee particulaire du scalaire
Rq: l'implementation de la classe permet bien sur de negliger
    certains termes de l'equation (le terme diffusif,
    le terme convectif,tel ou tel terme source).
See also
Equation_base, Classe abstraite, Methodes abstraites:, Entree& lire(const Motcle&, Entree&), const Champ_Inc_base& inconnue() const, Champ_Inc_base& inconnue()
Member Function Documentation
set_param()
void Convection_Diffusion_std::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Temperature, Masse_Multiphase, and Energie_Multiphase.
References Param::ajouter_non_std(), and Equation_base::set_param().
Referenced by Energie_Multiphase::set_param(), Convection_Diffusion_Fluide_Dilatable_base::set_param(), Convection_Diffusion_Concentration::set_param(), and Convection_Diffusion_Temperature::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_std::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Temperature_Turbulent, Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Concentration_Turbulent, Convection_Diffusion_Chaleur_Turbulent_QC, Masse_Multiphase, Energie_Multiphase, and Convection_Diffusion_Temperature.
References Operateur_Diff::associer_diffusivite(), Operateur_Diff::associer_diffusivite_pour_pas_de_temps(), Operateur_Conv::associer_vitesse(), associer_vitesse(), diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), Equation_base::lire_motcle_non_standard(), terme_convectif, terme_diffusif, and vitesse_pour_transport().
Referenced by Convection_Diffusion_Fluide_Dilatable_base::lire_motcle_non_standard(), Convection_Diffusion_Concentration::lire_motcle_non_standard(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Energie_Multiphase::lire_motcle_non_standard(), and Masse_Multiphase::lire_motcle_non_standard().
nombre_d_operateurs()
int Convection_Diffusion_std::nombre_d_operateurs () const override virtual
Renvoie le nombre d'operateurs de l'equation: 2 pour une equation de diffusion.
Returns
(int) le nombre d'operateurs de l'equation
Implements Equation_base.
Reimplemented in Masse_Multiphase, and Aire_interfaciale.
Referenced by Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Temperature::assembler_blocs(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), operateur(), and Convection_Diffusion_Temperature::transport_ibc().
operateur() [1/2]
const Operateur & Convection_Diffusion_std::operateur (int i) const override virtual
Renvoie l'operateur specifie par son index: renvoie terme_diffusif si i = 0.
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur specifie
Exceptions
l'equation n'a pas plus de 2 operateurs
Implements Equation_base.
Reimplemented in Masse_Multiphase, and Aire_interfaciale.
References Process::exit(), nombre_d_operateurs(), terme_convectif, and terme_diffusif.
Referenced by Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), and Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl().
operateur() [2/2]
Operateur & Convection_Diffusion_std::operateur (int i) override virtual
Renvoie l'operateur specifie par son index: renvoie terme_diffusif si i = 0.
renvoie terme_convectif si i = 1
exit si i>1
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur specifie
Exceptions
l'equation n'a pas plus de 2 operateurs
Implements Equation_base.
Reimplemented in Masse_Multiphase, and Aire_interfaciale.
References Process::exit(), nombre_d_operateurs(), terme_convectif, and terme_diffusif.
associer_vitesse()
void Convection_Diffusion_std::associer_vitesse (const Champ_base & vit) inline
Associe la vitesse transportante a l'equation.
Parameters
(Champ_Inc_base& vit) le champ a affecter a la vitesse transportante
Referenced by Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), and lire_motcle_non_standard().
vitesse_transportante()
const Champ_Inc_base & Convection_Diffusion_std::vitesse_transportante () const inline
Renvoie une reference sur le champ representant la vitesse transportante.
Returns
(Champ_Inc_base&) le champ representant la vitesse transportante
inconnue() [1/2]
const Champ_Inc_base& Convection_Diffusion_std::inconnue () const override pure virtual
Implements Equation_base.
Implemented in Masse_Multiphase, Energie_Multiphase, Aire_interfaciale, Convection_Diffusion_Temperature, Convection_Diffusion_Concentration, and Convection_Diffusion_Fluide_Dilatable_base.
Referenced by Modele_turbulence_scal_base::a_faire(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Convection_Diffusion_Temperature_base::creer_champ(), and Convection_Diffusion_Temperature_base::get_champ().
inconnue() [2/2]
Champ_Inc_base& Convection_Diffusion_std::inconnue () override pure virtual
Implements Equation_base.
Implemented in Masse_Multiphase, Energie_Multiphase, Aire_interfaciale, Convection_Diffusion_Temperature, Convection_Diffusion_Concentration, and Convection_Diffusion_Fluide_Dilatable_base.
diffusivite_pour_transport()
const Champ_Don_base & Convection_Diffusion_std::diffusivite_pour_transport () const virtual
Reimplemented in Energie_Multiphase_Enthalpie, Convection_Diffusion_Temperature_base, Convection_Diffusion_Concentration, and Convection_Diffusion_Fluide_Dilatable_base.
References Milieu_base::diffusivite(), and Equation_base::milieu().
Referenced by lire_motcle_non_standard(), Transport_turbulent_GGDH::modifier_mu(), Transport_turbulent_Prandtl::modifier_mu(), and Transport_turbulent_SGDH::modifier_mu().
diffusivite_pour_pas_de_temps()
const Champ_base & Convection_Diffusion_std::diffusivite_pour_pas_de_temps () const virtual
Reimplemented in Convection_Diffusion_Espece_Fluide_Dilatable_base, Energie_Multiphase_Enthalpie, Convection_Diffusion_Temperature_base, Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Espece_Multi_QC, Convection_Diffusion_Espece_Binaire_base, and Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References Operateur_Diff::diffusivite(), and terme_diffusif.
Referenced by lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard(), Transport_turbulent_GGDH::modifier_mu(), Transport_turbulent_Prandtl::modifier_mu(), and Transport_turbulent_SGDH::modifier_mu().
vitesse_pour_transport()
const Champ_base & Convection_Diffusion_std::vitesse_pour_transport () const virtual
Reimplemented in Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Espece_Binaire_base, and Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References Probleme_base::get_champ(), and Equation_base::probleme().
Referenced by lire_motcle_non_standard().
sauvegarder_base()
int Convection_Diffusion_std::sauvegarder_base (Sortie & os) const
References Equation_base::sauvegarder().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
reprendre_base()
int Convection_Diffusion_std::reprendre_base (Entree & is)
References Equation_base::reprendre().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC().
data_a_sauvegarder_base()
std::vector< YAML_data > Convection_Diffusion_std::data_a_sauvegarder_base () const
References Equation_base::data_a_sauvegarder().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::data_a_sauvegarder().
OBS_PTR()
Convection_Diffusion_std::OBS_PTR (Champ_Inc_base) protected
Member Data Documentation
terme_convectif
Operateur_Conv Convection_Diffusion_std::terme_convectif protected
Referenced by Masse_Multiphase::completer(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), lire_motcle_non_standard(), operateur(), Aire_interfaciale::operateur(), and Masse_Multiphase::operateur().
terme_diffusif
Operateur_Diff Convection_Diffusion_std::terme_diffusif protected
Referenced by diffusivite_pour_pas_de_temps(), Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard(), operateur(), and Aire_interfaciale::operateur().