CEA TRUST Platform: Terme_Source_VEF_base Class Reference
Terme_Source_VEF_base Class Reference
#include <Terme_Source_VEF_base.h>
Public Member Functions
void completer () override
int initialiser (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Terme_Source_VEF_base()
Terme_Source_VEF_base::Terme_Source_VEF_base (const Iterateur_Source_base & iter_base) inline
Member Function Documentation
ajouter()
DoubleTab & Terme_Source_VEF_base::ajouter (DoubleTab & resu) const inline override virtual
Reimplemented from Source_base.
calculer()
DoubleTab & Terme_Source_VEF_base::calculer (DoubleTab & resu) const inline override virtual
Reimplemented from Source_base.
completer()
void Terme_Source_VEF_base::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::completer().
initialiser()
int Terme_Source_VEF_base::initialiser (double temps) override virtual
Contrairement aux methodes mettre_a_jour, les methodes initialiser des sources ne peuvent pas dependre de l'exterieur.
(lui-meme peut ne pas etre initialise) Par defaut, mettre_a_jour
Reimplemented from Source_base.
References Source_base::initialiser().
Referenced by Terme_Puissance_Thermique_VEF_base::initialiser().
OWN_PTR()
Terme_Source_VEF_base::OWN_PTR (Iterateur_Source_base) protected