CEA TRUST Platform: QDM_Multiphase Class Reference
QDM_Multiphase Class Reference
Public Member Functions
void abortTimeStep () override
void completer () override
int impr (Sortie &os) const override
bool initTimeStep (double dt) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Navier_Stokes_std
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
const Nom & le_nom () const override
int limpr () const
Probleme_base & probleme ()
const Probleme_base & probleme () const
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Protected Member Functions
Entree & lire_cond_init (Entree &) override
int preparer_calcul () override
Protected Member Functions inherited from Navier_Stokes_std
virtual void discretiser_assembleur_pression ()
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_sources (Entree &)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour un fluide sans modelisation de la turbulence. On suppose l'hypothese de fluide quasi compressible. Sous ces hypotheses, on utilise la forme suivante des equations de Navier_Stokes: DU/dt = div(terme visqueux) - gradP/rho + sources/rho div U = W avec DU/dt : derivee particulaire de la vitesse rho : masse volumique Rq : l'implementation de la classe permet bien sur de negliger certains termes de l'equation (le terme visqueux, le terme convectif, tel ou tel terme source). L'inconnue est le champ de vitesse.
See also
Equation_base Pb_Thermohydraulique_QC Navier_Stokes_std
Member Function Documentation
set_param()
void QDM_Multiphase::set_param (Param & param) override virtual
Reimplemented from Navier_Stokes_std.
References Param::ajouter_non_std(), and Navier_Stokes_std::set_param().
lire_motcle_non_standard()
int QDM_Multiphase::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Navier_Stokes_std.
References evanescence_, and Navier_Stokes_std::lire_motcle_non_standard().
completer()
void QDM_Multiphase::completer () override virtual
Complete l'equation base, associe la pression a l'equation,.
complete la divergence, le gradient et le solveur pression. Ajout de 2 termes sources: l'un representant la force centrifuge dans le cas axi-symetrique,l'autre intervenant dans la resolution en 2D axisymetrique
Reimplemented from Navier_Stokes_std.
References MorEqn::check_multiphase_compatibility(), Navier_Stokes_std::completer(), MorEqn::equation(), Navier_Stokes_std::gradient, Navier_Stokes_std::inconnue(), Field_base::le_nom(), Equation_base::les_sources, Objet_U::que_suis_je(), Navier_Stokes_std::terme_convectif, and Navier_Stokes_std::terme_diffusif.
discretiser_vitesse()
void QDM_Multiphase::discretiser_vitesse () override virtual
Reimplemented from Navier_Stokes_std.
References Equation_base::discretisation(), Equation_base::domaine_dis(), Equation_base::probleme(), Equation_base::schema_temps(), and Discret_Thyd::vitesse().
discretiser_grad_p()
void QDM_Multiphase::discretiser_grad_p () override virtual
Reimplemented from Navier_Stokes_std.
mettre_a_jour()
void QDM_Multiphase::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double) et met a jour la pression. Integration des points suivis si le fluide est marque Mise a jour du champ postraitable correspondant
Parameters
(double temps) le temps de mise a jour
Reimplemented from Navier_Stokes_std.
References Process::abort(), Operateur_Grad::ajouter(), Solveur_Masse_base::appliquer_impl(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::discretisation(), Equation_base::domaine_dis(), Navier_Stokes_std::grad_u, grad_vit_phases_, Navier_Stokes_std::gradient, Navier_Stokes_std::gradient_P, Navier_Stokes_std::inconnue(), Discretisation_base::is_vdf(), Navier_Stokes_std::la_pression, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::mettre_a_jour(), Champ_Inc_base::mettre_a_jour(), Domaine_dis_base::nb_elem(), Navier_Stokes_std::pression(), Navier_Stokes_std::pression_pa(), Equation_base::probleme(), TRUSTTab_parts< _TYPE_ >::size(), Equation_base::solv_masse(), Navier_Stokes_std::Taux_cisaillement, and vit_phases_.
impr()
int QDM_Multiphase::impr (Sortie & os) const inline override virtual
Effectue quelques impressions sur un flot de sortie: - maximum de div U.
  - terme convectif
  - terme diffusif
  - divergence
  - gradient
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Navier_Stokes_std.
References Equation_base::impr().
initTimeStep()
bool QDM_Multiphase::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Navier_Stokes_std.
References Champ_Inc_base::changer_temps_futur(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_Inc_base::futur(), Equation_base::initTimeStep(), Schema_Temps_base::nb_valeurs_futures(), Navier_Stokes_std::pression(), Navier_Stokes_std::pression_pa(), Equation_base::schema_temps(), Schema_Temps_base::temps_futur(), and Champ_Inc_base::valeurs().
abortTimeStep()
void QDM_Multiphase::abortTimeStep () override virtual
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne, par exemple parce que le calcul a diverge. Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
Exceptions
WrongContext
Reimplemented from Navier_Stokes_std.
References Equation_base::abortTimeStep().
dimensionner_matrice_sans_mem()
void QDM_Multiphase::dimensionner_matrice_sans_mem (Matrice_Morse & matrice) override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::dimensionner_matrice_sans_mem(), and evanescence_.
has_interface_blocs()
int QDM_Multiphase::has_interface_blocs () const override virtual
Reimplemented from Navier_Stokes_std.
References evanescence_, and Navier_Stokes_std::has_interface_blocs().
dimensionner_blocs()
void QDM_Multiphase::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::dimensionner_blocs(), and evanescence_.
Referenced by SETS::iterer_NS().
diffusivite_pour_transport()
const Champ_Don_base & QDM_Multiphase::diffusivite_pour_transport () const override virtual
Reimplemented from Navier_Stokes_std.
diffusivite_pour_pas_de_temps()
const Champ_base & QDM_Multiphase::diffusivite_pour_pas_de_temps () const override virtual
Reimplemented from Navier_Stokes_std.
vitesse_pour_transport()
const Champ_base & QDM_Multiphase::vitesse_pour_transport () const override virtual
Reimplemented from Navier_Stokes_std.
assembler_blocs_avec_inertie()
void QDM_Multiphase::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) override virtual
Reimplemented from Equation_base.
References Equation_base::assembler_blocs_avec_inertie(), and evanescence_.
Referenced by SETS::iterer_NS().
creer_champ()
void QDM_Multiphase::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Navier_Stokes_std.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Navier_Stokes_std::creer_champ(), Objet_U::dimension, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Navier_Stokes_std::grad_u, grad_vit_phases_, Discret_Thyd::gradient_P(), Navier_Stokes_std::gradient_P, noms_grad_vit_phases_, noms_vit_phases_, Equation_base::probleme(), Motcles::rang(), Equation_base::schema_temps(), and vit_phases_.
get_noms_champs_postraitables()
void QDM_Multiphase::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Navier_Stokes_std.
References Navier_Stokes_std::get_noms_champs_postraitables(), Pb_Multiphase::nb_phases(), noms_grad_vit_phases_, noms_vit_phases_, and Equation_base::probleme().
alpha_res()
double QDM_Multiphase::alpha_res () const
References evanescence_, Process::exit(), Pb_Multiphase::nb_phases(), and Equation_base::probleme().
lire_cond_init()
Entree & QDM_Multiphase::lire_cond_init (Entree & is) override protected virtual
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant: { Nom [DOIT ETRE LE NOM DE L'INCONNUE] [LIRE UN CHAMP DONNE] }
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
erreur de format, accolade ouvrante attendue
mauvais nom pour l'inconnue
erreur de format, accolade fermante attendue
Reimplemented from Navier_Stokes_std.
References Process::exit(), Navier_Stokes_std::la_pression, Navier_Stokes_std::la_pression_en_pa, Navier_Stokes_std::OWN_PTR(), Equation_base::probleme(), Objet_U::que_suis_je(), and Equation_base::verifie_ch_init_nb_comp().
preparer_calcul()
int QDM_Multiphase::preparer_calcul () override protected virtual
cf Equation_base::preparer_calcul() Assemblage du solveur pression et
initialisation de la pression.
assemblage du systeme en pression
Returns
(int) renvoie toujours 1
Reimplemented from Navier_Stokes_std.
References Champ_Inc_base::changer_temps(), evanescence_, Equation_base::preparer_calcul(), Navier_Stokes_std::pression(), Navier_Stokes_std::pression_pa(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
Member Data Documentation
vit_phases_
std::vector<OWN_PTR(Champ_Inc_base)> QDM_Multiphase::vit_phases_ protected
Referenced by creer_champ(), and mettre_a_jour().
noms_vit_phases_
Motcles QDM_Multiphase::noms_vit_phases_ protected
Referenced by creer_champ(), and get_noms_champs_postraitables().
grad_vit_phases_
std::vector<OWN_PTR(Champ_Fonc_base)> QDM_Multiphase::grad_vit_phases_ protected
Referenced by creer_champ(), and mettre_a_jour().
noms_grad_vit_phases_
Motcles QDM_Multiphase::noms_grad_vit_phases_ protected
Referenced by creer_champ(), and get_noms_champs_postraitables().
evanescence_
Operateur_Evanescence QDM_Multiphase::evanescence_ protected
Referenced by alpha_res(), assembler_blocs_avec_inertie(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), has_interface_blocs(), lire_motcle_non_standard(), and preparer_calcul().