CEA TRUST Platform: Eval_Puiss_Th_QC_EF Class Reference
Eval_Puiss_Th_QC_EF Class Reference
#include <Eval_Puiss_Th_QC_EF.h>
Constructor & Destructor Documentation
Eval_Puiss_Th_QC_EF()
Eval_Puiss_Th_QC_EF::Eval_Puiss_Th_QC_EF () inline
Member Function Documentation
completer()
void Eval_Puiss_Th_QC_EF::completer () inline override virtual
Implements Evaluateur_Source.
References Evaluateur_Source_EF_Som::completer().
mettre_a_jour()
void Eval_Puiss_Th_QC_EF::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
associer_puissance()
void Eval_Puiss_Th_QC_EF::associer_puissance (const Champ_Don_base & Q) inline
References puissance, TRUSTTab< _TYPE_, _SIZE_ >::ref(), and Champ_Don_base::valeurs().
Referenced by Puissance_Thermique_QC_EF::associer_pb().
calculer_terme_source()
template<typename Type_Double > void Eval_Puiss_Th_QC_EF::calculer_terme_source (const int num_elem, Type_Double & source) const
References Process::exit(), and puissance.
OBS_PTR()
Eval_Puiss_Th_QC_EF::OBS_PTR (Champ_Don_base) protected
Member Data Documentation
puissance
DoubleTab Eval_Puiss_Th_QC_EF::puissance protected
Referenced by associer_puissance(), and calculer_terme_source().