CEA TRUST Platform: InputCommBuffer Class Reference
InputCommBuffer Class Reference
Additional Inherited Members
Public Member Functions inherited from Entree
virtual int get (char *buf, std::streamsize bufsize)
void set_bin (bool bin) override
virtual void set_check_types (bool flag)
Protected Member Functions inherited from Entree
virtual int error_handle_ (int fail_flag)
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Attributes inherited from AbstractIO
bool avoid_conversion_ = false
Detailed Description
C'est une classe derivee de Entree dont le stream est de type istringstream (les donnees lues par operator>> sont prises dans un buffer). On utilise la classe comme suit: (1) on reserve un buffer d'une certaine taille avec char * buf = input_comm_buffer.reserve_buffer(taille); (2) on remplit le buffer avec des donnees: for (i=0; i<taille; i++) buf[i] = .....; (3) on cree un stream a partir du buffer: input_comm_buffer.create_stream(); (4) on peut ensuite lire les donnees a travers l'operateur>>: input_comm_buffer >> x >> y >> chaine >> ... ; (5) quand on a fini de lire avec operateur>> on fait input_comm_buffer.clear(); et on peut refaire (1)
Constructor & Destructor Documentation
InputCommBuffer()
InputCommBuffer::InputCommBuffer ()
References AbstractIO::avoid_conversion_, AbstractIO::bin_, Entree::ERROR_CONTINUE, and Entree::set_error_action().
~InputCommBuffer()
InputCommBuffer::~InputCommBuffer () override
Member Function Documentation
reserve_buffer()
char * InputCommBuffer::reserve_buffer (int bufsize)
Referenced by Schema_Comm::echange_messages().
create_stream_from_output_stream()
void InputCommBuffer::create_stream_from_output_stream (OutputCommBuffer & output_buf)
References OutputCommBuffer::get_buffer(), OutputCommBuffer::get_buffer_size(), and Entree::set_istream().
Referenced by Schema_Comm::echange_messages().
create_stream()
void InputCommBuffer::create_stream ()
References Entree::set_istream().
Referenced by Schema_Comm::echange_messages().
clear()
void InputCommBuffer::clear ()
References Entree::set_istream().
Referenced by Schema_Comm::end_comm().