CEA TRUST Platform: EChaineJDD Class Reference
EChaineJDD Class Reference
#include <EChaineJDD.h>
Public Member Functions
virtual int get (char *buf, std::streamsize bufsize)
int get (char *ob, std::streamsize bufsize) override
Public Member Functions inherited from Entree
void set_bin (bool bin) override
virtual void set_check_types (bool flag)
Additional Inherited Members
Protected Member Functions inherited from Entree
virtual int error_handle_ (int fail_flag)
Constructor & Destructor Documentation
EChaineJDD() [1/2]
EChaineJDD::EChaineJDD ()
References Entree::set_check_types().
EChaineJDD() [2/2]
EChaineJDD::EChaineJDD (const char * str)
References init(), and Entree::set_check_types().
~EChaineJDD()
EChaineJDD::~EChaineJDD () override
Member Function Documentation
init()
void EChaineJDD::init (const char * str)
References istrstream_, and Entree::set_istream().
Referenced by EChaineJDD(), and LecFicDiffuse_JDD::ouvrir().
operator>>() [1/13]
Entree & EChaineJDD::operator>> (True_int & ob) override virtual
Reimplemented from Entree.
operator>>() [2/13]
Entree & EChaineJDD::operator>> (double & ob) override virtual
Reimplemented from Entree.
get() [1/7]
int EChaineJDD::get (char * ob, std::streamsize bufsize) override virtual
Lecture d'une chaine dans ostream_ bufsize est la taille du buffer alloue pour ob (y compris.
le caractere 0 final). La chaine contient toujours un 0 meme en cas d'echec. La methode renvoie 1 si la lecture est bonne, 0 sinon. Si le buffer est trop petit, pour l'instant on fait exit() mais par la suite on pourra tester: si strlen(ob)==bufsize-1, alors refaire lire() jusqu'a arriver au bout. Si le lire() suivant renvoie une chaine de longueur nulle, cela signifie que la taille de la chaine etait exactement bufsize-1. Attention: le comportement est different en binaire et en ascii. En binaire, on lit la chaine jusqu'au prochain '\0'. En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
Reimplemented from Entree.
References file_cur_line_, Entree::get(), Entree::jumpOfLines(), and track_lines_.
Referenced by operator_template().
set_track_lines()
void EChaineJDD::set_track_lines (bool b) inline
References track_lines_.
Referenced by LecFicDiffuse_JDD::track_lines().
operator_template()
template<typename _TYPE_ > Entree & EChaineJDD::operator_template (_TYPE_ & ob) protected
References get(), and istrstream_.
operator>>() [3/13]
Entree & Entree::operator>> (Entree &(*)(Entree &) f)
operator>>() [4/13]
Entree & Entree::operator>> (istream &(*)(istream &) f)
operator>>() [5/13]
Entree & Entree::operator>> (ios &(*)(ios &) f)
operator>>() [6/13]
template<typename T > Entree & Entree::operator>> (const TRUST_Ref< T > &) inline
operator>>() [7/13]
Entree & Entree::operator>> (const TRUST_Ref_Objet_U &) inline
operator>>() [8/13]
Entree & Entree::operator>> (True_int & ob) virtual
Reimplemented from Entree.
operator>>() [9/13]
Entree & Entree::operator>> (long & ob) virtual
Reimplemented from Entree.
operator>>() [10/13]
Entree & Entree::operator>> (long long & ob) virtual
Reimplemented from Entree.
operator>>() [11/13]
Entree & Entree::operator>> (float & ob) virtual
Reimplemented from Entree.
operator>>() [12/13]
Entree & Entree::operator>> (double & ob) virtual
Reimplemented from Entree.
operator>>() [13/13]
Entree & Entree::operator>> (Objet_U & ob) final virtual
Reimplemented from Entree.
get() [2/7]
int Entree::get (True_int * ob, std::streamsize n) virtual
Reimplemented from Entree.
get() [3/7]
int Entree::get (long * ob, std::streamsize n) virtual
Reimplemented from Entree.
get() [4/7]
int Entree::get (long long * ob, std::streamsize n) virtual
Reimplemented from Entree.
get() [5/7]
int Entree::get (float * ob, std::streamsize n) virtual
Reimplemented from Entree.
get() [6/7]
int Entree::get (double * ob, std::streamsize n) virtual
Reimplemented from Entree.
get() [7/7]
int Entree::get (char * ob, std::streamsize bufsize) virtual
Lecture d'une chaine dans ostream_ bufsize est la taille du buffer alloue pour ob (y compris.
le caractere 0 final). La chaine contient toujours un 0 meme en cas d'echec. La methode renvoie 1 si la lecture est bonne, 0 sinon. Si le buffer est trop petit, pour l'instant on fait exit() mais par la suite on pourra tester: si strlen(ob)==bufsize-1, alors refaire lire() jusqu'a arriver au bout. Si le lire() suivant renvoie une chaine de longueur nulle, cela signifie que la taille de la chaine etait exactement bufsize-1. Attention: le comportement est different en binaire et en ascii. En binaire, on lit la chaine jusqu'au prochain '\0'. En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
Reimplemented from Entree.
Member Data Documentation
file_cur_line_
int EChaineJDD::file_cur_line_ = 1 static
Referenced by Process::exit(), and get().
istrstream_
istringstream* EChaineJDD::istrstream_ protected
Referenced by init(), and operator_template().
track_lines_
bool EChaineJDD::track_lines_ protected
Referenced by get(), and set_track_lines().