CEA TRUST Platform: Champ_Generique_Tparoi_VEF Class Reference
Champ_Generique_Tparoi_VEF Class Reference
Public Member Functions
const Noms get_property (const Motcle &query) const override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
Entity get_localisation (const int index=-1) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Generique_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
get_property()
const Noms Champ_Generique_Tparoi_VEF::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Gen_de_Champs_Gen::nb_comp, Champ_Generique_base::nom_post_, and Motcles::search().
get_champ()
const Champ_base & Champ_Generique_Tparoi_VEF::get_champ (OWN_PTR(Champ_base)& espace_stockage) const override
References Objet_U::dimension, Discretisation_base::discretiser_champ(), Domaine_dis_base::domaine(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Turbulence_paroi_scal_base::equivalent_distance(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Champ_Generique_base::get_champ(), Champ_Gen_de_Champs_Gen::get_directive_pour_discr(), Champ_Gen_de_Champs_Gen::get_discretisation(), Turbulence_paroi_scal_base::get_flag_calcul_ldp_en_flux_impose(), Equation_base::get_modele(), Champ_Gen_de_Champs_Gen::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Domaine_Cl_dis_base::les_conditions_limites(), Modele_turbulence_scal_base::loi_paroi(), Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), TRUST_Ref_Objet_U::non_nul(), Front_VF::num_face(), Domaine_VEF::oriente_normale(), Champ_Gen_de_Champs_Gen::OWN_PTR(), Turbulence_paroi_scal_base::use_equivalent_distance(), TRUST_Ref_Objet_U::valeur(), Champ_Proto::valeurs(), and Domaine_VF::volumes().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Tparoi_VEF::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const override virtual
Implements Champ_Generique_base.
References Discretisation_base::discretiser_champ(), Champ_Generique_base::get_champ_without_evaluation(), Champ_Gen_de_Champs_Gen::get_directive_pour_discr(), Champ_Gen_de_Champs_Gen::get_discretisation(), Champ_Gen_de_Champs_Gen::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, and Champ_Gen_de_Champs_Gen::OWN_PTR().
nommer_source()
void Champ_Generique_Tparoi_VEF::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().