CEA TRUST Platform: Modele_turbulence_scal_diffturb_base Class Reference
Modele_turbulence_scal_diffturb_base Class Reference
Public Member Functions
void associer_viscosite_turbulente (const Champ_Fonc_base &)
void completer () override
int reprendre (Entree &) override
Public Member Functions inherited from Modele_turbulence_scal_base
virtual void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &)
void associer_eqn (const Equation_base &)
virtual void imprimer (Sortie &) const
int limpr_nusselt (double, double, double, double) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
Turbulence_paroi_scal_base & loi_paroi ()
const Turbulence_paroi_scal_base & loi_paroi () const
int loi_paroi_non_nulle () const
virtual int preparer_calcul ()
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
pour la diffusivite turbulente: alpha_turb = visco_turb / coeff_turb;
See also
Modele_turbulence_scal_base
Member Function Documentation
associer_viscosite_turbulente()
void Modele_turbulence_scal_diffturb_base::associer_viscosite_turbulente (const Champ_Fonc_base & visc_turb)
Associe une viscosite turbulente au modele de turbulence.
Parameters
(Champ_Fonc_base& visc_turb) le champ fonction representant la viscosite turbulente a associer.
Referenced by completer().
completer()
void Modele_turbulence_scal_diffturb_base::completer () override virtual
Complete le modele de turbulence: Appelle Modele_turbulence_scal_base::completer()
associe la viscosite turbulente du probleme au modele de turbulence.
Reimplemented from Modele_turbulence_scal_base.
References associer_viscosite_turbulente(), Modele_turbulence_scal_base::completer(), Modele_turbulence_scal_base::equation(), Probleme_base::equation(), Equation_base::get_modele(), Equation_base::probleme(), TRUST_Ref_Objet_U::valeur(), and Modele_turbulence_hyd_base::viscosite_turbulente().
reprendre()
int Modele_turbulence_scal_diffturb_base::reprendre (Entree & is) override virtual
NE FAIT RIEN.
Parameters
(Entree&) un flot d'entree
Returns
(int) renvoie toujours 1
Reimplemented from Modele_turbulence_scal_base.
OBS_PTR()
Modele_turbulence_scal_diffturb_base::OBS_PTR (Champ_Fonc_base) protected