CEA TRUST Platform: Memoire Class Reference
Memoire Class Reference
Public Member Functions
int add (Objet_U *)
int imprime () const
Objet_U & objet_u (int)
const Objet_U & objet_u (int) const
Objet_U * objet_u_ptr (int)
const Objet_U * objet_u_ptr (int) const
int rang (const Nom &nom) const
int rang (const Nom &type, const Nom &nom) const
int suppr (int)
int verifie () const
Static Public Member Functions
static Memoire & Instance ()
Friends
Sortie & operator<< (Sortie &, const Memoire &)
Constructor & Destructor Documentation
Memoire()
Memoire::Memoire () protected
Constructeur Initialize une zone de travail pour les Objet_U, les "double" et les "int".
Referenced by Instance().
Member Function Documentation
Instance()
Memoire & Memoire::Instance () static
Retourne un pointeur sur l'instance de la memoire Cree un nouvel objet memoire si aucune instance n'a deja ete creee.
Returns
(Memoire*) pointeur sur l'instance de la memoire
References Memoire().
Referenced by MD_Vector::copy(), Objet_U_ptr::get_Objet_U_ptr(), Objet_U_ptr::get_Objet_U_ptr_check(), Objet_U::Objet_U(), Objet_U_ptr::recopie(), and Objet_U::~Objet_U().
add()
int Memoire::add (Objet_U * obj)
Ajoute un Objet_U dans la Memoire de TRUST.
Parameters
(Objet_U* obj) pointeur sur l'Objet_U a ajouter
Returns
(int) le numero affecte a l'objet dans la memoire
References Process::exit(), Memoire_ptr::next, and Memoire_ptr::set().
Referenced by Objet_U::Objet_U().
suppr()
int Memoire::suppr (int num)
Suppression de la memoire de l'Objet_U de numero num L'Objet_U n'est pas supprime, seul son pointeur dans la memoire l'est.
Parameters
(int num) le numero de l'Objet_U a supprimer
Returns
(int) code de retour, retourne toujours 1
References compacte(), Memoire_ptr::next, and Memoire_ptr::set().
Referenced by Objet_U::~Objet_U().
objet_u() [1/2]
Objet_U & Memoire::objet_u (int num)
Retoune une reference sur l'Objet_U de rang num dans la memoire.
Parameters
(int num) le rang de l'objet dans la memoire
Returns
(Objet_U&) reference sur l'Objet_U trouve
Exceptions
Sort en erreur si la memoire comporte une erreur a la case de rang num
References Process::exit(), Objet_U::numero(), and Memoire_ptr::obj().
Referenced by compacte(), Objet_U_ptr::get_Objet_U_ptr(), Objet_U_ptr::get_Objet_U_ptr_check(), and Objet_U_ptr::recopie().
objet_u() [2/2]
const Objet_U & Memoire::objet_u (int num) const
Retoune une reference constante sur l'Objet_U de rang num dans la memoire.
Parameters
(int num) le rang de l'objet dans la memoire
Returns
(const Objet_U&) reference sur l'Objet_U trouve
Exceptions
Sort en erreur si la memoire comporte une erreur a la case de rang num
References Process::exit(), Objet_U::numero(), and Memoire_ptr::obj().
objet_u_ptr() [1/2]
Objet_U * Memoire::objet_u_ptr (int num)
Retoune un pointeur sur l'Objet_U de rang num dans la memoire.
Parameters
(int num) le rang de l'objet dans la memoire
Returns
(Objet_U&) reference sur l'Objet_U trouve
Exceptions
Sort en erreur si la memoire comporte une erreur a la case de rang num
References Process::exit(), Objet_U::numero(), and Memoire_ptr::obj().
Referenced by MD_Vector::copy().
objet_u_ptr() [2/2]
const Objet_U * Memoire::objet_u_ptr (int num) const
Retoune un pointeur constant sur l'Objet_U de rang num dans la memoire.
Parameters
(int num) le rang de l'objet dans la memoire
Returns
(Objet_U&) reference sur l'Objet_U trouve
Exceptions
Sort en erreur si la memoire comporte une erreur a la case de rang num
References Process::exit(), Objet_U::numero(), and Memoire_ptr::obj().
rang() [1/2]
int Memoire::rang (const Nom & type, const Nom & nom) const
Retourne le rang dans la memoire de l'objet de type et de nom indiques.
Parameters
(const Nom& type) le type de l'objet
(const Nom& nom) le nom de l'objet
Returns
(int) le rang de l'objet s'il est trouve dans la memoire, -1 sinon
References Memoire_ptr::libre(), and Memoire_ptr::obj().
rang() [2/2]
int Memoire::rang (const Nom & nom) const
Retourne le rang dans la memoire de l'objet de nom indique.
Parameters
(const Nom& nom) le nom de l'objet
Returns
(int) le rang de l'objet s'il est trouve dans la memoire, -1 sinon
References Memoire_ptr::libre(), and Memoire_ptr::obj().
compacte()
void Memoire::compacte ()
Compacte la memoire Ce compactage est effectue automatiquement lorsqu'il devient necessaire.
References Objet_U::change_num(), Process::exit(), objet_u(), and verifie().
Referenced by suppr().
verifie()
int Memoire::verifie () const
Verifie le contenu de toutes les cases de la memoire.
Returns
(int) code de retour; retourne toujours 1
References Process::exit(), and imprime().
Referenced by compacte().
imprime()
int Memoire::imprime () const
Imprime un etat sur la memoire sur la sortie des erreurs.
Returns
(int) code de retour; retourne toujours 1
References Objet_U::le_nom(), Objet_U::le_type(), Objet_U::numero(), Memoire_ptr::obj(), and Objet_U::taille_memoire().
Referenced by verifie().
Friends And Related Function Documentation
operator<<
Sortie& operator<< (Sortie & , const Memoire &) friend
Operateur d'affichage d'un etat de la memoire mem sur le flot de sortie os.
Parameters
(Sortie& os) le flot de sortie a utiliser
(const Memoire& mem) la memoire a examiner
Returns
(Sortie& le flot de sortie modifie)