CEA TRUST Platform: Solv_rocALUTION Class Reference
Solv_rocALUTION Class Reference
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Solv_rocALUTION() [1/2]
Solv_rocALUTION::Solv_rocALUTION ()
Solv_rocALUTION() [2/2]
Solv_rocALUTION::Solv_rocALUTION (const Solv_rocALUTION & org)
References SolveurSys_base::get_chaine_lue(), and Objet_U::readOn().
~Solv_rocALUTION()
Solv_rocALUTION::~Solv_rocALUTION () override
Member Function Documentation
solveur_direct()
int Solv_rocALUTION::solveur_direct () const inline override virtual
Implements SolveurSys_base.
resoudre_systeme() [1/2]
int Solv_rocALUTION::resoudre_systeme (const Matrice_Base & a, const DoubleVect & b, DoubleVect & x, int niter_max) inline override virtual
Reimplemented from SolveurSys_base.
References resoudre_systeme().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_rocALUTION::resoudre_systeme (const Matrice_Base & a, const DoubleVect & b, DoubleVect & x) override virtual
Implements SolveurSys_base.
References Solv_Externe::construit_matrice_morse_intermediaire(), Solv_Externe::construit_renum(), PE_Groups::current_group(), TRUSTVect< _TYPE_, _SIZE_ >::ecrit(), TRUSTArray< _TYPE_, _SIZE_ >::ensureDataOnHost(), Matrice_Morse::imprimer_formatte(), TRUSTArray< _TYPE_, _SIZE_ >::isDataOnDevice(), Process::Journal(), Solv_Externe::lhs_, Solv_Externe::nb_rows_, Solv_Externe::nb_rows_tot_, SolveurSys_base::nouvelle_matrice(), Solv_Externe::renum_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), Solv_Externe::rhs_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
create_solver()
void Solv_rocALUTION::create_solver (Entree & entree)
References Process::exit(), SolveurSys_base::fixer_limpr(), SolveurSys_base::get_chaine_lue(), EChaine::init(), and SolveurSys_base::lecture().