CEA TRUST Platform: Partitionneur_Parmetis Class Reference
Partitionneur_Parmetis Class Reference
Public Member Functions
void construire_partition (IntVect &elem_part, int &nb_parts_tot) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Partitionneur_base_32_64< _SIZE_ >
static int_t calculer_graphe_connexions_periodiques (const Domaine_t &domaine, const Noms &liste_bords_periodiques, const Static_Int_Lists_t &som_elem, const int_t my_offset, Static_Int_Lists_t &graph)
static int_t corriger_bords_avec_graphe (const Static_Int_Lists_t &graph_elements_perio, const Static_Int_Lists_t &som_elem, const Domaine_t &domaine, const Noms &liste_bords_perio, BigIntVect_ &elem_part)
static void corriger_bords_avec_liste (const Domaine_t &dom, const Noms &liste_bords_periodiques, const int_t my_offset, BigIntVect_ &elem_part)
static void corriger_elem0_sur_proc0 (BigIntVect_ &elem_part)
static int_t corriger_multiperiodique (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
static int_t corriger_sommets_bord (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Voir construire_partition
Member Function Documentation
set_param()
void Partitionneur_Parmetis::set_param (Param & param) override virtual
Implements Partitionneur_base_32_64< _SIZE_ >.
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_flag(), and Param::REQUIRED.
lire_motcle_non_standard()
int Partitionneur_Parmetis::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Partitionneur_base_32_64< _SIZE_ >.
References Partitionneur_base_32_64< _SIZE_ >::lire_motcle_non_standard().
associer_domaine()
void Partitionneur_Parmetis::associer_domaine (const Domaine & domaine) override
construire_partition()
void Partitionneur_Parmetis::construire_partition (IntVect & elem_part, int & nb_parts_tot) const override
Calcule le graphe de connectivite pour parmetis, appelle le partitionneur et remplit elem_part (pour chaque element, numero de la partie qui lui.
est attribuee).
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Domain_Graph::adjncy, Domain_Graph::construire_graph_elem_elem(), Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_liste(), Partitionneur_base_32_64< _SIZE_ >::corriger_elem0_sur_proc0(), MD_Vector_tools::creer_tableau_distribue(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domain_Graph::ewgts, Process::exit(), Static_Int_Lists_32_64< _SIZE_ >::get_nb_lists(), Partitionneur_base_32_64< _SIZE_ >::liste_bords_periodiques_, Domain_Graph::nvtxs, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Domain_Graph::vtxdist, Domain_Graph::vwgts, Domain_Graph::weightflag, and Domain_Graph::xadj.