CEA TRUST Platform: VEF_discretisation Class Reference
VEF_discretisation Class Reference
#include <VEF_discretisation.h>
Public Member Functions
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, OWN_PTR(Champ_Don_base)&champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, OWN_PTR(Champ_Fonc_base)&champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, OWN_PTR(Champ_Inc_base)&champ, const Nom &sous_type=NOM_VIDE) const override
void proprietes_physiques_fluide_Ostwald (const Domaine_dis_base &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc_base &) const override
Public Member Functions inherited from Discretisation_base
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const OBS_PTR(Champ_base)&champ_supp=OBS_PTR(Champ_base)()) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Discretisation_base
static void creer_champ (OWN_PTR(Champ_Don_base)&ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (OWN_PTR(Champ_Fonc_base)&ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (OWN_PTR(Champ_Inc_base)&ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
discretiser_champ() [1/3]
void VEF_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, int nb_pas_dt, double temps, OWN_PTR(Champ_Inc_base)& champ, const Nom & sous_type = NOM_VIDE) const override virtual
Discretisation d'un champ pour le VEFP1B en fonction d'une directive de discretisation.
La directive est un Motcle comme "pression", "divergence_vitesse" (cree un champ de type P1_isoP1Bulle). Cette methode determine le type du champ a creer en fonction du type d'element et de la directive de discretisation. Elle determine ensuite le nombre de ddl et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt, nom(s), unite(s), nature du champ et attribue un temps) et associe le Domaine_dis au champ. Voir le code pour avoir la correspondance entre les directives et le type de champ cree.
Reimplemented from Discretisation_base.
References Discretisation_base::creer_champ(), Discretisation_base::DEMANDE_DESCRIPTION, Process::exit(), Objet_U::que_suis_je(), and Motcles::search().
Referenced by distance_paroi_globale().
discretiser_champ() [2/3]
void VEF_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, OWN_PTR(Champ_Fonc_base)& champ) const override virtual
Idem que VEF_discretisation::discretiser_champ(.
.. , Champ_Inc)
Reimplemented from Discretisation_base.
discretiser_champ() [3/3]
void VEF_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, OWN_PTR(Champ_Don_base)& champ) const override virtual
Idem que VEF_discretisation::discretiser_champ(.
.. , Champ_Inc)
Reimplemented from Discretisation_base.
distance_paroi()
void VEF_discretisation::distance_paroi (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Fonc_base)& ch) const
References Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Schema_Temps_base::temps_courant().
distance_paroi_globale()
void VEF_discretisation::distance_paroi_globale (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Fonc_base)& ch) const override virtual
Reimplemented from Discret_Thyd.
References discretiser_champ().
proprietes_physiques_fluide_Ostwald()
void VEF_discretisation::proprietes_physiques_fluide_Ostwald (const Domaine_dis_base & z, Fluide_Ostwald & le_fluide, const Navier_Stokes_std & eqn_hydr, const Champ_Inc_base & ch_temper) const override virtual
discretise en VEF le fluide incompressible, donc K e N
Parameters
(Domaine_dis_base&) domaine a discretiser
(Fluide_Ostwald&) fluide a discretiser
(Champ_Inc_base&) vitesse
(Champ_Inc_base&) temperature
Reimplemented from Discret_Thyd.
References Champ_Ostwald_VEF::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_Ostwald_VEF::associer_eqn(), Champ_Ostwald::associer_fluide(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Navier_Stokes_std::inconnue(), Domaine_dis_base::nb_elem(), Champ_base::temps(), and Fluide_base::viscosite_dynamique().
domaine_cl_dis_type()
Nom VEF_discretisation::domaine_cl_dis_type () const inline override virtual
Implements Discretisation_base.
vorticite()
void VEF_discretisation::vorticite (Domaine_dis_base & z, const Champ_Inc_base & ch_vitesse, OWN_PTR(Champ_Fonc_base)& ch) const
References Rotationnel_Champ_P1NC::associer_champ(), Rotationnel_Champ_Q1NC::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Process::exit(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), Champ_base::temps(), and Domaine_VEF::type_elem().
creer_champ_vorticite()
void VEF_discretisation::creer_champ_vorticite (const Schema_Temps_base & sch, const Champ_Inc_base & ch_vitesse, OWN_PTR(Champ_Fonc_base)& ch) const override virtual
Reimplemented from Discret_Thyd.
References Rotationnel_Champ_P1NC::associer_champ(), Rotationnel_Champ_Q1NC::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Champ_Inc_base::domaine_dis_base(), Process::exit(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Schema_Temps_base::temps_courant().
critere_Q()
void VEF_discretisation::critere_Q (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & vitesse, OWN_PTR(Champ_Fonc_base)& ch) const override virtual
Reimplemented from Discret_Thyd.
References Critere_Q_Champ_P1NC::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Champ_base::temps().
y_plus()
void VEF_discretisation::y_plus (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & vitesse, OWN_PTR(Champ_Fonc_base)& ch) const override virtual
Reimplemented from Discret_Thyd.
References Y_plus_Champ_P1NC::associer_champ(), Y_plus_Champ_P1NC::associer_domaine_Cl_dis_base(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Champ_base::temps().
grad_T()
void VEF_discretisation::grad_T (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & temperature, OWN_PTR(Champ_Fonc_base)& ch) const override virtual
Reimplemented from Discret_Thyd.
References grad_T_Champ_P1NC::associer_champ(), grad_T_Champ_P1NC::associer_domaine_Cl_dis_base(), Discretisation_base::creer_champ(), Objet_U::dimension, Domaine_dis_base::nb_elem(), and Champ_base::temps().
grad_u()
void VEF_discretisation::grad_u (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & temperature, OWN_PTR(Champ_Fonc_base)& ch) const override virtual
Reimplemented from Discret_Thyd.
References grad_U_Champ_P1NC::associer_champ(), grad_U_Champ_P1NC::associer_domaine_Cl_dis_base(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Champ_base::temps().
h_conv()
void VEF_discretisation::h_conv (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & temperature, OWN_PTR(Champ_Fonc_base)& ch, Motcle & nom, int temp_ref) const override virtual
Reimplemented from Discret_Thyd.
References h_conv_Champ_P1NC::associer_champ(), h_conv_Champ_P1NC::associer_domaine_Cl_dis_base(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), h_conv_Champ_P1NC::temp_ref(), and Champ_base::temps().
taux_cisaillement()
void VEF_discretisation::taux_cisaillement (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & ch_vitesse, OWN_PTR(Champ_Fonc_base)& champ) const override virtual
Reimplemented from Discret_Thyd.
References Taux_cisaillement_P0_VEF::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Champ_base::temps().
residu()
void VEF_discretisation::residu (const Domaine_dis_base & z, const Champ_Inc_base & ch_inco, OWN_PTR(Champ_Fonc_base)& champ) const override virtual
Reimplemented from Discretisation_base.
References Discretisation_base::discretiser_champ(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Champ_base::temps(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
t_paroi()
void VEF_discretisation::t_paroi (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & ch_temp, OWN_PTR(Champ_Fonc_base)& ch) const override virtual
Reimplemented from Discret_Thermique.
References Domaine_dis_base::nb_elem(), and Champ_base::temps().
is_vef()
bool VEF_discretisation::is_vef () const inline override virtual
Reimplemented from Discretisation_base.
get_P1Bulle()
int VEF_discretisation::get_P1Bulle () const inline
Referenced by Domaine_VEF::discretiser_suite().
get_alphaE()
int VEF_discretisation::get_alphaE () const inline
Referenced by Domaine_VEF::discretiser_suite().
get_alphaS()
int VEF_discretisation::get_alphaS () const inline
Referenced by Domaine_VEF::discretiser_suite().
get_alphaA()
int VEF_discretisation::get_alphaA () const inline
Referenced by Domaine_VEF::discretiser_suite().
get_alphaRT()
int VEF_discretisation::get_alphaRT () const inline
Referenced by Domaine_VEF::discretiser_suite().
get_modif_div_face_dirichlet()
int VEF_discretisation::get_modif_div_face_dirichlet () const inline
Referenced by Domaine_VEF::discretiser_suite().
get_cl_pression_sommet_faible()
int VEF_discretisation::get_cl_pression_sommet_faible () const inline
Referenced by Domaine_VEF::discretiser_suite().