CEA TRUST Platform: Assembleur_P_PolyMAC_P0P1NC Class Reference
Assembleur_P_PolyMAC_P0P1NC Class Reference
#include <Assembleur_P_PolyMAC_P0P1NC.h>
Additional Inherited Members
Public Member Functions inherited from Assembleur_P_PolyMAC
int assembler_QC (const DoubleTab &, Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
Public Member Functions inherited from Assembleur_base
int set_resoudre_en_u (int flag)
int set_resoudre_increment_pression (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
assembler_mat()
int Assembleur_P_PolyMAC_P0P1NC::assembler_mat (Matrice & la_matrice, const DoubleVect & diag, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_P_PolyMAC.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Statistiques::begin_count(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Statistiques::end_count(), Assembleur_P_PolyMAC::equation(), Champ_Face_base::fcl(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Assembleur_P_PolyMAC::has_P_ref, Statistiques::last_time(), Process::me(), Equation_base::milieu(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Matrice_Morse::set_nb_columns(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), Assembleur_P_PolyMAC::stencil_done, Assembleur_P_PolyMAC::tab1, and Assembleur_P_PolyMAC::tab2.
modifier_secmem()
int Assembleur_P_PolyMAC_P0P1NC::modifier_secmem (DoubleTab &) inline override virtual
Reimplemented from Assembleur_P_PolyMAC.
modifier_solution()
int Assembleur_P_PolyMAC_P0P1NC::modifier_solution (DoubleTab & pression) override virtual
Reimplemented from Assembleur_P_PolyMAC.
References Assembleur_P_PolyMAC::has_P_ref, and Debog::verifier().
dimensionner_continuite()
void Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite (matrices_t matrices, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Assembleur_P_PolyMAC::equation(), Equation_base::get_champ(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
assembler_continuite()
void Assembleur_P_PolyMAC_P0P1NC::assembler_continuite (matrices_t matrices, DoubleTab & secmem, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
References Process::abort(), Equation_base::champ_conserve(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Assembleur_P_PolyMAC::equation(), Pb_Multiphase::equation_masse(), Probleme_base::get_champ(), Equation_base::inconnue(), Equation_base::milieu(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Equation_base::probleme(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
norme_continuite()
DoubleTab Assembleur_P_PolyMAC_P0P1NC::norme_continuite () const override virtual
Reimplemented from Assembleur_base.
References Assembleur_P_PolyMAC::equation(), Equation_base::milieu(), and Milieu_base::porosite_elem().
modifier_secmem_pour_incr_p()
void Assembleur_P_PolyMAC_P0P1NC::modifier_secmem_pour_incr_p (const DoubleTab & press, const double fac, DoubleTab & incr) const override virtual
Reimplemented from Assembleur_base.
References Assembleur_P_PolyMAC::equation(), Champ_Face_base::fcl(), Probleme_base::get_champ(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::probleme(), and Champ_Proto::valeurs().
corriger_vitesses()
void Assembleur_P_PolyMAC_P0P1NC::corriger_vitesses (const DoubleTab & dP, DoubleTab & dv) const inline override virtual
Reimplemented from Assembleur_P_PolyMAC.
References Process::exit().