CEA TRUST Platform: Convection_Diffusion_Concentration Class Reference
Convection_Diffusion_Concentration Class Reference
Public Member Functions
void associer_constituant (const Constituant &)
void associer_milieu_base (const Milieu_base &) override
Constituant & constituant ()
const Constituant & constituant () const
const Motcle & domaine_application () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nb_constituants () const
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
pour un ou plusieurs constituants.
Dans le cas de plusieurs constituants les champs
concentration et diffusivite sont vectoriels.
See also
Convection_Diffusion_std
Constructor & Destructor Documentation
Convection_Diffusion_Concentration()
Convection_Diffusion_Concentration::Convection_Diffusion_Concentration ()
Member Function Documentation
set_param()
void Convection_Diffusion_Concentration::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Concentration_Turbulent.
References Param::ajouter(), Param::ajouter_non_std(), masse_molaire_, and Convection_Diffusion_std::set_param().
Referenced by Convection_Diffusion_Concentration_Turbulent::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_Concentration::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Concentration_Turbulent.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::diffusion_multi_scalaire_, inconnue(), Field_base::le_nom(), Convection_Diffusion_std::lire_motcle_non_standard(), and Field_base::nommer().
Referenced by Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard().
milieu() [1/2]
const Milieu_base & Convection_Diffusion_Concentration::milieu () const override virtual
Renvoie le milieu physique de l'equation.
(un Constituant upcaste en Milieu_base) (version const)
Returns
(Milieu_base&) le Constituant upcaste en Milieu_base
Implements Equation_base.
References constituant().
milieu() [2/2]
Milieu_base & Convection_Diffusion_Concentration::milieu () override virtual
Renvoie le milieu physique de l'equation.
(un Constituant upcaste en Milieu_base)
Returns
(Milieu_base&) le Constituant upcaste en Milieu_base
Implements Equation_base.
References constituant().
constituant() [1/2]
const Constituant & Convection_Diffusion_Concentration::constituant () const
Renvoie le constituant (si il a ete associe).
(version const)
Returns
(Constituant&) le constituant associe a l'equation
References Process::exit(), Probleme_U::le_nom(), and Equation_base::probleme().
Referenced by diffusivite_pour_transport(), discretiser(), mettre_a_jour(), milieu(), and preparer_calcul().
constituant() [2/2]
Constituant & Convection_Diffusion_Concentration::constituant ()
Renvoie le constituant (si il a ete associe).
Returns
(Constituant&) le constituant associe a l'equation
References Process::exit().
associer_milieu_base()
void Convection_Diffusion_Concentration::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation, le milieu est en fait caste en Constituant et associe a l'equation.
Parameters
(Milieu_base& un_milieu)
Exceptions
diffusivite du constituant dans le fluide non definie
Implements Equation_base.
References associer_constituant().
Referenced by Pb_Hydraulique_Concentration::associer_milieu_base(), Pb_Thermohydraulique_Concentration::associer_milieu_base(), Pb_Hydraulique_Concentration_Turbulent::associer_milieu_base(), and Pb_Thermohydraulique_Concentration_Turbulent::associer_milieu_base().
associer_constituant()
void Convection_Diffusion_Concentration::associer_constituant (const Constituant & un_constituant) inline
Associe un constituant a l'equation.
Parameters
(Constituant& un_constituant) un constituant a associer a l'equation
Referenced by associer_milieu_base().
discretiser()
void Convection_Diffusion_Concentration::discretiser () override virtual
Discretise l'equation.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Discret_Thyd::concentration(), constituant(), Equation_base::discretisation(), Equation_base::discretiser(), Equation_base::domaine_dis(), Constituant::nb_constituants(), nb_constituants_, and Equation_base::schema_temps().
inconnue() [1/2]
const Champ_Inc_base & Convection_Diffusion_Concentration::inconnue () const inline override virtual
Renvoie le champ inconnue de l'equation: la concentration.
(version const)
Returns
(Champ_Inc_base&) le champ inconnue de l'equation, la concentration.
Implements Convection_Diffusion_std.
Referenced by Chimie::completer(), and lire_motcle_non_standard().
inconnue() [2/2]
Champ_Inc_base & Convection_Diffusion_Concentration::inconnue () inline override virtual
Renvoie le champ inconnue de l'equation: la concentration.
Returns
(Champ_Inc_base&) le champ inconnue de l'equation, la concentration.
Implements Convection_Diffusion_std.
nb_constituants()
int Convection_Diffusion_Concentration::nb_constituants () const inline
Renvoie le nombre de constituants du "Constituant" de l'equation.
Returns
(int) le nombre de constituants de l'equation
References nb_constituants_.
impr()
int Convection_Diffusion_Concentration::impr (Sortie & os) const override virtual
Impression des flux sur les bords sur un flot de sortie.
Appelle Equation_base::impr(Sortie&)
Parameters
(Sortie& os) un flot de sortie
Returns
(int) code de retour propage
Reimplemented from Equation_base.
References Equation_base::impr().
preparer_calcul()
int Convection_Diffusion_Concentration::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Concentration_Turbulent.
References constituant(), Constituant::initialiser(), Equation_base::preparer_calcul(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by Convection_Diffusion_Concentration_Turbulent::preparer_calcul().
mettre_a_jour()
void Convection_Diffusion_Concentration::mettre_a_jour (double temps) override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre. Elle met aussi a jour les proprietes du milieu.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Concentration_Turbulent.
References constituant(), Equation_base::mettre_a_jour(), and Constituant::mettre_a_jour().
Referenced by Convection_Diffusion_Concentration_Turbulent::mettre_a_jour().
diffusivite_pour_transport()
const Champ_Don_base & Convection_Diffusion_Concentration::diffusivite_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
References constituant(), and Constituant::diffusivite_constituant().
Referenced by Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard().
domaine_application()
const Motcle & Convection_Diffusion_Concentration::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Concentration".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
masse_molaire()
const double & Convection_Diffusion_Concentration::masse_molaire () const
References masse_molaire_.
Referenced by Chimie::completer().
get_champ_compris()
Champs_compris& Convection_Diffusion_Concentration::get_champ_compris () inline
References Equation_base::champs_compris_.
OWN_PTR()
Convection_Diffusion_Concentration::OWN_PTR (Champ_Inc_base) protected
OBS_PTR()
Convection_Diffusion_Concentration::OBS_PTR (Constituant) const protected
Referenced by Convection_Diffusion_Concentration_Turbulent::get_champ().
Member Data Documentation
nb_constituants_
int Convection_Diffusion_Concentration::nb_constituants_ protected
Referenced by discretiser(), nb_constituants(), and Convection_Diffusion_Concentration_Turbulent::set_param().
masse_molaire_
double Convection_Diffusion_Concentration::masse_molaire_ protected
Referenced by masse_molaire(), and set_param().