CEA TRUST Platform: Tetraedriser_homogene_compact Class Reference
Tetraedriser_homogene_compact Class Reference
Additional Inherited Members
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Le maillage obtenu n'a pas de directions preferentielles
See also
Interprete
Member Function Documentation
decoupe()
void Tetraedriser_homogene_compact::decoupe (Domaine & domaine, Faces & faces, IntTab & new_soms_old_elems, IntTab & fait_sommet, int nface) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), Faces_32_64< _SIZE_ >::les_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Faces_32_64< _SIZE_ >::voisins().
trianguler()
void Tetraedriser_homogene_compact::trianguler (Domaine & domaine) const override virtual
Implements Triangulation_base.
References Domaine_32_64< _SIZE_ >::construit_octree(), creer_sommet(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Interprete_geometrique_base_32_64< _SIZE_ >::domaine(), Process::exit(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::invalide_octree(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine(), Domaine_32_64< _SIZE_ >::nb_som(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Faces_32_64< _SIZE_ >::typer(), and Domaine_32_64< _SIZE_ >::typer().
creer_sommet()
int Tetraedriser_homogene_compact::creer_sommet (Domaine & domaine, DoubleTab & new_soms, IntTab & elem_traite, IntTab & new_soms_old_elems, int NbSom, IntTab & sommets, int & compteur, int oldnbsom, int & nbnewsoms, IntTab & fait_sommet, int & nface) const
References Domaine_32_64< _SIZE_ >::coord_sommets(), and Interprete_geometrique_base_32_64< _SIZE_ >::domaine().
Referenced by trianguler().
dimension_application()
int Tetraedriser_homogene_compact::dimension_application () const inline override virtual
Implements Triangulation_base.