CEA TRUST Platform: Bords_Internes_32_64< _SIZE_ > Class Template Reference
Bords_Internes_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void associer_domaine (const Domaine_t &)
int_t nb_faces () const
int_t nb_faces (Type_Face type) const
Detailed Description
template<typename _SIZE_>
class Bords_Internes_32_64< _SIZE_ >
See also
Bords_Interne
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Bords_Internes_32_64< _SIZE_ >::int_t = _SIZE_
Domaine_t
template<typename _SIZE_ > using Bords_Internes_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Member Function Documentation
associer_domaine()
template<typename _SIZE_ > void Bords_Internes_32_64< _SIZE_ >::associer_domaine (const Domaine_t & un_domaine)
Associe un domaine a tous les objets Bord_Interne de la liste.
Parameters
(Domaine& un_domaine) le domaine a associer aux Bord_Interne de la liste
Referenced by Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), and Domaine_32_64< _SIZE_ >::merge_wo_vertices_with().
nb_faces() [1/2]
template<typename _SIZE_ > Bords_Internes_32_64< _SIZE_ >::int_t Bords_Internes_32_64< _SIZE_ >::nb_faces
Renvoie le nombre total de faces contenues dans la liste des Bord_Interne, i.
e. la somme de toutes les faces de tous les objet Bords_Interne contenu dans la liste.
Returns
(int) le nombre total de faces contenues dans la liste des Bord_Interne
Referenced by Domaine_32_64< _SIZE_ >::nb_faces_bords_int().
nb_bords_internes()
template<typename _SIZE_ > int Bords_Internes_32_64< _SIZE_ >::nb_bords_internes () const inline
Referenced by Domaine_32_64< _SIZE_ >::nb_frontieres_internes().
nb_faces() [2/2]
template<typename _SIZE_ > Bords_Internes_32_64< _SIZE_ >::int_t Bords_Internes_32_64< _SIZE_ >::nb_faces (Type_Face type) const
Renvoie le nombre total de faces de type specifie contenues dans la liste des Bord_Interne.
i.e. la somme de toutes les faces de type specifie de tous les objet Bord_Interne contenu dans la liste.
Parameters
(Type_Face type) le type des faces a compter
Returns
(int) le nombre total de faces contenues dans la liste des Bord_Interne