CEA TRUST Platform: Associer Class Reference
Associer Class Reference
#include <Associer.h>
Public Member Functions
Entree & interpreter (Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
[DANS LE JEU DE DONNEES] Associer ob1 ob2
See also
Interprete
Member Function Documentation
interpreter()
Entree & Associer::interpreter (Entree & is) override virtual
Fonction principale de l'interprete Associer: associer deux objets.
On essaye d'associer 1 a 2 et 2 a 1, provoque une erreur si cela echoue.
Parameters
(Entree& is) un flot d'entree, a partir duquel on lit les noms des objets a associer
Returns
(Entree&) le flot d'entree modifie
Exceptions
on ne sait pas associer obj1 et obj2
Implements Interprete.
References Objet_U::associer_(), Entree::eof(), Process::exit(), Interprete::objet(), and Objet_U::que_suis_je().