CEA TRUST Platform: Champ_Generique_base Class Reference
Champ_Generique_base Class Reference abstract
Public Member Functions
virtual void get_copy_domain (Domaine &) const
virtual void get_copy_values (DoubleTab &) const
virtual int get_dimension () const
virtual Entity get_localisation (const int index=-1) const
virtual const Noms get_property (const Motcle &query) const
virtual const IntTab & get_ref_connectivity (Entity index1, Entity index2) const
virtual const DoubleTab & get_ref_coordinates () const
virtual const Domaine & get_ref_domain () const
virtual const Domaine_dis_base & get_ref_domaine_dis_base () const
virtual const DoubleTab & get_ref_values () const
virtual void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Classe de base des champs generiques pour importation d un champ discret et actions elementaires sur ce champ
(postraitement, etc) Attention: toutes les methodes sont PARALLELES, il faut les appeler simultanement sur tous les processeurs (get_domain() peut par exemple construire le domaine parallele avant de le renvoyer).
Member Function Documentation
data_a_sauvegarder()
virtual std::vector<YAML_data> Champ_Generique_base::data_a_sauvegarder () const inline virtual
Reimplemented in Champ_Generique_Statistiques_base, and Champ_Gen_de_Champs_Gen.
sauvegarder()
int Champ_Generique_base::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
reprendre()
int Champ_Generique_base::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
set_param()
virtual void Champ_Generique_base::set_param (Param & param) pure virtual
Implemented in Champ_Generique_modifier_pour_QC, Champ_Post_Operateur_Eqn, Champ_Generique_Transformation, Champ_Generique_Statistiques_base, Champ_Generique_refChamp_special, Champ_Generique_refChamp, Champ_Generique_Reduction_0D, Champ_Generique_Predefini, Champ_Generique_Moyenne, Champ_Generique_Morceau_Equation, Champ_Generique_Interpolation, Champ_Generique_Extraction, and Champ_Gen_de_Champs_Gen.
lire_motcle_non_standard()
int Champ_Generique_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
Referenced by Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Champ_Generique_Predefini::lire_motcle_non_standard(), and Champ_Generique_refChamp::lire_motcle_non_standard().
get_dimension()
int Champ_Generique_base::get_dimension () const virtual
Renvoie la dimension de l'espace dans lequel le champ est defini.
Il s'agit du nombre de composantes des coordonnees qu'il faut fournir dans get_xyz_values. (par exemple, un champ defini sur une surface peut etre de dimension 3 si les coordonnees des sommets sont 3D, ou de dimension 2 s'il s'agit de coordonnees curvilignes le long de la surface)
Reimplemented in Champ_Generique_refChamp, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_dimension().
get_time()
double Champ_Generique_base::get_time () const virtual
Renvoie le temps du Champ_Generique_base.
Reimplemented in Champ_Generique_refChamp, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Generique_Extraction::get_champ(), and Champ_Gen_de_Champs_Gen::get_time().
get_ref_pb_base()
const Probleme_base & Champ_Generique_base::get_ref_pb_base () const virtual
Renvoie le probleme qui porte le champ cible.
Reimplemented in Champ_Generique_refChamp, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_ref_pb_base().
get_discretisation()
const Discretisation_base & Champ_Generique_base::get_discretisation () const virtual
Renvoie la discretisation associee au probleme.
Reimplemented in Champ_Gen_de_Champs_Gen.
References Probleme_base::discretisation(), Objet_U::interprete(), nom_pb_, and Interprete::objet().
Referenced by Champ_Generique_Extraction::get_champ(), and Champ_Gen_de_Champs_Gen::get_discretisation().
get_directive_pour_discr()
const Motcle Champ_Generique_base::get_directive_pour_discr () const virtual
Renvoie la directive (champ_elem, champ_sommets, champ_face ou pression) pour lancer la discretisation de l espace de stockage rendu par get_champ()
Reimplemented in Champ_Generique_Transformation, Champ_Generique_refChamp, Champ_Generique_Morceau_Equation, Champ_Generique_Interpolation, Champ_Generique_Gradient, Champ_Generique_Extraction, Champ_Generique_Divergence, Champ_Generique_Correlation, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Generique_Transformation::completer(), Champ_Generique_Transformation::get_champ(), and Champ_Gen_de_Champs_Gen::get_directive_pour_discr().
nommer()
void Champ_Generique_base::nommer (const Nom &) override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References nom_post_.
Referenced by Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), Champ_Generique_refChamp::lire_motcle_non_standard(), Champ_Generique_Correlation::nommer_source(), Champ_Generique_Divergence::nommer_source(), Champ_Generique_Ecart_Type::nommer_source(), Champ_Generique_Extraction::nommer_source(), Champ_Generique_Gradient::nommer_source(), Champ_Generique_Interpolation::nommer_source(), Champ_Generique_Moyenne::nommer_source(), Champ_Generique_Reduction_0D::nommer_source(), Champ_Generique_Transformation::nommer_source(), Champ_Post_Operateur_Eqn::nommer_source(), Champ_Generique_modifier_pour_QC::nommer_source(), Champ_Generique_Tparoi_VEF::nommer_source(), and Champ_Generique_refChamp::nommer_source().
get_nom_post()
const Nom & Champ_Generique_base::get_nom_post () const virtual
Reimplemented in Champ_Generique_Predefini.
References nom_post_.
composante()
int Champ_Generique_base::composante (const Nom & nom_test, const Nom & nom, const Noms & composantes, const Noms & synonyms) inline static
References Process::exit(), and Motcles::search().
Referenced by Sonde::completer(), Postraitement::creer_champ_post(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_Interpolation::get_champ_without_evaluation(), and Postraitement::postprocess_field_values().
get_property_names()
void Champ_Generique_base::get_property_names (Motcles & list) const virtual
Renvoie la liste des "query" possibles pour le champ.
Reimplemented in Champ_Generique_refChamp, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_property_names().
get_property()
const Noms Champ_Generique_base::get_property (const Motcle & query) const virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented in Champ_Generique_Tparoi_VEF, Champ_Post_Operateur_Eqn, Champ_Generique_Transformation, Champ_Generique_refChamp, Champ_Generique_Reduction_0D, Champ_Generique_Predefini, Champ_Generique_Moyenne, Champ_Generique_Morceau_Equation, Champ_Generique_Interpolation, Champ_Generique_Gradient, Champ_Generique_Extraction, Champ_Generique_Ecart_Type, Champ_Generique_Divergence, Champ_Generique_Correlation, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Generique_Correlation::completer(), Champ_Generique_Ecart_Type::completer(), Champ_Generique_Reduction_0D::completer(), Champ_Generique_Transformation::completer(), comprend_champ_post(), Champ_Generique_Moyenne::comprend_champ_post(), Champ_Generique_Transformation::creer_expression_macro(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Transformation::get_champ(), get_champ_post(), Champ_Generique_Moyenne::get_champ_post(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Generique_Divergence::get_property(), Champ_Generique_Ecart_Type::get_property(), Champ_Generique_Extraction::get_property(), Champ_Generique_Gradient::get_property(), Champ_Generique_Interpolation::get_property(), Champ_Generique_Moyenne::get_property(), Champ_Generique_Reduction_0D::get_property(), Champ_Generique_Tparoi_VEF::get_property(), has_champ_post(), Champ_Generique_Moyenne::has_champ_post(), Postraitement::lire_champs_a_postraiter(), Champ_Generique_Correlation::nommer_source(), Champ_Generique_Divergence::nommer_source(), Champ_Generique_Ecart_Type::nommer_source(), Champ_Generique_Extraction::nommer_source(), Champ_Generique_Gradient::nommer_source(), Champ_Generique_Interpolation::nommer_source(), Champ_Generique_Moyenne::nommer_source(), Champ_Generique_Reduction_0D::nommer_source(), Champ_Generique_modifier_pour_QC::nommer_source(), Champ_Generique_Tparoi_VEF::nommer_source(), and Champ_Generique_Transformation::preparer_macro().
get_localisation()
Entity Champ_Generique_base::get_localisation (const int index = -1) const virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un.
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans parametre, sauf si on sait quoi faire pour les champs multi-supports.
See also
get_nb_localisations() Parametre : index Signification : index de la localisation demandee (pour les champs multi-support). Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support. Si index >= 0 : on renvoie le i-ieme support. Valeur par defaut : -1 Exceptions:
GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques (il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented in Champ_Post_Operateur_Eqn, Champ_Generique_Transformation, Champ_Generique_refChamp, Champ_Generique_Morceau_Equation, Champ_Generique_Interpolation, Champ_Generique_Gradient, Champ_Generique_Extraction, Champ_Generique_Divergence, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_localisation(), and Postraitement::lire_champs_a_postraiter().
get_nb_localisations()
int Champ_Generique_base::get_nb_localisations () const virtual
get_ref_values()
const DoubleTab & Champ_Generique_base::get_ref_values () const virtual
Renvoie une reference au tableau de valeurs discretes s'il existe en memoire.
La reference est valide au moins jusqu'au prochain appel a une methode non const. Le maillage sur lequel ces valeurs sont definies est accessible par les methodes get_node_coordinates(), get_connectivity(), get_field_type(). Exceptions:
GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire, il faut utiliser get_copy_values();
GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie
Reimplemented in Champ_Generique_refChamp_special, Champ_Generique_refChamp, Champ_Generique_Interpolation, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_ref_values().
get_copy_values()
void Champ_Generique_base::get_copy_values (DoubleTab & values) const virtual
Remplit le tableau values avec les valeurs discretes du champ (cree une copie).
Exceptions:
GenericFieldError::XYZ_ONLY : les valeurs ne sont accessibles que par get_xyz_values
GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie
Reimplemented in Champ_Generique_refChamp, Champ_Generique_Interpolation, and Champ_Gen_de_Champs_Gen.
get_xyz_values()
void Champ_Generique_base::get_xyz_values (const DoubleTab & coords, DoubleTab & values, ArrOfBit & validity_flag) const virtual
Calcule la valeur ponctuelle du champ aux coordonnees donnees dans coords et les met dans values.
validity_flag est rempli avec 1 si la valeur est valide (coordonnees a l'interieur du domaine), 0 sinon. Attention en parallele: Chaque processeur traite le tableau coords qui lui est fourni : on peut soit faire calculer le meme tableau a tout le monde: dans ce cas, validity_flag indique sur chaque processeur quelles valeurs chaque processeur a pu calculer, soit on sait par avance quelles coordonnees sont calculable par chaque processeur et on donne au processeur local uniquement des coordonnees qu'il possede. Si une meme coordonnee est demandee a plusieurs processeurs, on ne garantit pas que tous donnent le meme resultat. En general, un seul aura le validity_flag mis pour cette coordonnee. Exceptions:
GenericFieldError::NOT_IMPLEMENTED : le paresseux n'a pas code les methodes d'interpolation il faut se debrouiller avec le maillage et les valeurs discretes.
GenericFieldError::MESH_ONLY : le champ ne porte pas de valeurs, il sert uniquement a decrire une geometrie
Reimplemented in Champ_Generique_refChamp, and Champ_Gen_de_Champs_Gen.
get_ref_domain()
const Domaine & Champ_Generique_base::get_ref_domain () const virtual
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented in Champ_Generique_Interpolation, Champ_Generique_Extraction, and Champ_Gen_de_Champs_Gen.
References Domaine_dis_base::domaine(), Probleme_base::domaine_dis(), Objet_U::interprete(), nom_pb_, and Interprete::objet().
Referenced by Champ_Generique_Extraction::completer(), Champ_Generique_Interpolation::completer(), get_copy_domain(), Champ_Generique_refChamp::get_ref_coordinates(), Champ_Gen_de_Champs_Gen::get_ref_domain(), Champ_Generique_Interpolation::get_ref_domain(), and Champ_Generique_refChamp::nommer_source().
get_copy_domain()
void Champ_Generique_base::get_copy_domain (Domaine & domain) const virtual
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented in Champ_Generique_Interpolation, Champ_Generique_Extraction, and Champ_Gen_de_Champs_Gen.
References get_ref_domain().
Referenced by Champ_Gen_de_Champs_Gen::get_copy_domain().
get_ref_domaine_dis_base()
const Domaine_dis_base & Champ_Generique_base::get_ref_domaine_dis_base () const virtual
Renvoie une ref au domaine_discretisee du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented in Champ_Generique_Interpolation, Champ_Generique_Extraction, and Champ_Gen_de_Champs_Gen.
References Probleme_base::domaine_dis(), Objet_U::interprete(), nom_pb_, and Interprete::objet().
Referenced by Champ_Generique_Extraction::completer(), Champ_Generique_Reduction_0D::completer(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_refChamp::get_directive_pour_discr(), and Champ_Gen_de_Champs_Gen::get_ref_domaine_dis_base().
get_ref_zcl_dis_base()
const Domaine_Cl_dis_base & Champ_Generique_base::get_ref_zcl_dis_base () const virtual
Renvoie une ref au domaine_cl_discretisee de l equation portant le champ cible.
Reimplemented in Champ_Generique_refChamp, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_ref_zcl_dis_base().
get_ref_coordinates()
const DoubleTab & Champ_Generique_base::get_ref_coordinates () const virtual
Renvoie une reference au tableau des coordonnees des sommets du maillage support du champ, s'il existe.
Le tableau a toujours deux dimensions : dimension(0) = nombre de sommets reels dimension(1) = get_dimension() (dimension de l'espace dans lequel est defini le champ) En parallele, le tableau est un tableau distribue avec items communs. Exceptions:
GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire, il faut utiliser get_copy_coordinates();
Reimplemented in Champ_Generique_refChamp, Champ_Generique_Interpolation, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_ref_coordinates().
get_copy_coordinates()
void Champ_Generique_base::get_copy_coordinates (DoubleTab &) const virtual
Reimplemented in Champ_Generique_refChamp, Champ_Generique_Interpolation, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_copy_coordinates().
get_ref_connectivity()
const IntTab & Champ_Generique_base::get_ref_connectivity (Entity index1, Entity index2) const virtual
Renvoie le tableau de connectivite entre l'entite geometrique index1 et l'entite index2.
Par exemple get_ref_connectivity(ELEM, NODE) = Domaine::mes_elems get_ref_connectivity(ELEM, FACE) = DomaineVF::elem_faces_ get_ref_connectivity(FACE, ELEM) = DomaineVF::face_voisins_ Le tableau a toujours deux dimensions : dimension(0) = nombre d'entites "index1" reelles dimension(1) = nombre d'entites "index2" connectees a chaque entite "index1" En parallele, le tableau est un tableau distribue avec items communs Exceptions:
GenericFieldError::INVALID : le tableau n'existe pas (champ analytique ...)
GenericFieldError::NO_REF : les valeurs ne sont pas stockees en memoire, il faut utiliser get_copy_connectivity();
Reimplemented in Champ_Generique_refChamp, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_ref_connectivity().
get_copy_connectivity()
void Champ_Generique_base::get_copy_connectivity (Entity index1, Entity index2, IntTab &) const virtual
Reimplemented in Champ_Generique_refChamp, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_copy_connectivity().
reset()
virtual void Champ_Generique_base::reset () pure virtual
Implemented in Champ_Generique_refChamp, Champ_Generique_Interpolation, and Champ_Gen_de_Champs_Gen.
completer()
virtual void Champ_Generique_base::completer (const Postraitement_base & post) pure virtual
Implemented in Champ_Generique_modifier_pour_QC, Champ_Post_Operateur_Eqn, Champ_Generique_Transformation, Champ_Generique_refChamp, Champ_Generique_Reduction_0D, Champ_Generique_Predefini, Champ_Generique_Moyenne, Champ_Generique_Morceau_Equation, Champ_Generique_Interpolation, Champ_Generique_Gradient, Champ_Generique_Extraction, Champ_Generique_Ecart_Type, Champ_Generique_Divergence, Champ_Generique_Correlation, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::completer().
mettre_a_jour()
virtual void Champ_Generique_base::mettre_a_jour (double temps) pure virtual
Implemented in Champ_Generique_Statistiques_base, Champ_Generique_refChamp, and Champ_Gen_de_Champs_Gen.
get_champ()
virtual const Champ_base& Champ_Generique_base::get_champ (OWN_PTR(Champ_base) & espace_stockage) const pure virtual
Referenced by Op_Correlation::associer(), Op_Ecart_type::associer(), Op_Moyenne::associer(), Champ_Generique_Extraction::completer(), Champ_Generique_Gradient::completer(), Champ_Generique_Morceau_Equation::completer(), Champ_Post_Operateur_Eqn::completer(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), and Champ_Generique_Transformation::preparer_macro().
get_champ_without_evaluation()
virtual const Champ_base& Champ_Generique_base::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const pure virtual
Implemented in Champ_Generique_Tparoi_VEF, Champ_Generique_modifier_pour_QC, Champ_Post_Operateur_Eqn, Champ_Generique_Transformation, Champ_Generique_refChamp, Champ_Generique_Reduction_0D, Champ_Generique_Predefini, Champ_Generique_Moyenne, Champ_Generique_Morceau_Equation, Champ_Generique_Interpolation, Champ_Generique_Gradient, Champ_Generique_Extraction, Champ_Generique_Ecart_Type, Champ_Generique_Divergence, and Champ_Generique_Correlation.
Referenced by Champ_Generique_Transformation::completer(), Champ_Generique_Extraction::get_champ_without_evaluation(), Champ_Generique_Interpolation::get_champ_without_evaluation(), Champ_Generique_Reduction_0D::get_champ_without_evaluation(), Champ_Generique_modifier_pour_QC::get_champ_without_evaluation(), Champ_Generique_Tparoi_VEF::get_champ_without_evaluation(), and Champ_Generique_Transformation::preparer_macro().
get_champ_post()
const Champ_Generique_base & Champ_Generique_base::get_champ_post (const Motcle & nom) const virtual
Reimplemented in Champ_Generique_Moyenne, and Champ_Gen_de_Champs_Gen.
References get_property(), Nom::getString(), and OBS_PTR().
Referenced by Postraitement::get_champ_post(), and Champ_Gen_de_Champs_Gen::get_champ_post().
has_champ_post()
bool Champ_Generique_base::has_champ_post (const Motcle & nom) const virtual
Reimplemented in Champ_Generique_Moyenne, and Champ_Gen_de_Champs_Gen.
References get_property().
Referenced by Champ_Gen_de_Champs_Gen::get_champ_post(), and Champ_Gen_de_Champs_Gen::has_champ_post().
comprend_champ_post()
int Champ_Generique_base::comprend_champ_post (const Motcle & identifiant) const virtual
Reimplemented in Champ_Generique_Moyenne, and Champ_Gen_de_Champs_Gen.
References get_property().
Referenced by Champ_Gen_de_Champs_Gen::comprend_champ_post().
get_info_type_post()
virtual int Champ_Generique_base::get_info_type_post () const pure virtual
Implemented in Champ_Generique_refChamp, Champ_Generique_Correlation, and Champ_Gen_de_Champs_Gen.
Referenced by Champ_Gen_de_Champs_Gen::get_info_type_post().
fixer_identifiant_appel()
void Champ_Generique_base::fixer_identifiant_appel (const Nom & identifiant) inline
References identifiant_appel_.
fixer_noms_compo()
virtual const Noms& Champ_Generique_base::fixer_noms_compo (const Noms & noms) inline virtual
Reimplemented in Champ_Generique_refChamp, and Champ_Generique_Interpolation.
References Objet_U::que_suis_je().
fixer_noms_synonyms()
virtual const Noms& Champ_Generique_base::fixer_noms_synonyms (const Noms & noms) inline virtual
Reimplemented in Champ_Generique_refChamp, and Champ_Generique_Interpolation.
References Objet_U::que_suis_je().
assert_parallel()
static void Champ_Generique_base::assert_parallel (int) static protected
OBS_PTR()
Champ_Generique_base::OBS_PTR (Probleme_base) protected
Referenced by Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Moyenne::get_champ(), get_champ_post(), Champ_Generique_Moyenne::get_champ_post(), Champ_Generique_Ecart_Type::get_champ_without_evaluation(), and Champ_Generique_Moyenne::get_champ_without_evaluation().
Member Data Documentation
nom_post_
Nom Champ_Generique_base::nom_post_ protected
Referenced by Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_Transformation::completer(), Champ_Generique_Morceau_Equation::get_directive_pour_discr(), get_nom_post(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Generique_Divergence::get_property(), Champ_Generique_Ecart_Type::get_property(), Champ_Generique_Extraction::get_property(), Champ_Generique_Gradient::get_property(), Champ_Generique_Interpolation::get_property(), Champ_Generique_Moyenne::get_property(), Champ_Generique_Reduction_0D::get_property(), Champ_Generique_refChamp::get_property(), Champ_Generique_Transformation::get_property(), Champ_Post_Operateur_Eqn::get_property(), Champ_Generique_Tparoi_VEF::get_property(), nommer(), Champ_Generique_Correlation::nommer_source(), Champ_Generique_Divergence::nommer_source(), Champ_Generique_Ecart_Type::nommer_source(), Champ_Generique_Extraction::nommer_source(), Champ_Generique_Gradient::nommer_source(), Champ_Generique_Interpolation::nommer_source(), Champ_Generique_Moyenne::nommer_source(), Champ_Generique_Reduction_0D::nommer_source(), Champ_Generique_Transformation::nommer_source(), Champ_Post_Operateur_Eqn::nommer_source(), Champ_Generique_modifier_pour_QC::nommer_source(), Champ_Generique_Tparoi_VEF::nommer_source(), Champ_Generique_refChamp::nommer_source(), and Champ_Generique_Transformation::preparer_macro().
identifiant_appel_
Nom Champ_Generique_base::identifiant_appel_ protected
Referenced by fixer_identifiant_appel(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), and Champ_Generique_Interpolation::get_champ_without_evaluation().
nom_pb_
Nom Champ_Generique_base::nom_pb_ protected
Referenced by Champ_Gen_de_Champs_Gen::completer(), Champ_Generique_refChamp_special::get_champ(), get_discretisation(), get_ref_domain(), get_ref_domaine_dis_base(), and Champ_Generique_refChamp::lire_motcle_non_standard().