CEA TRUST Platform: Solveur_Lineaire_Std Class Reference
Solveur_Lineaire_Std Class Reference
#include <Solveur_Lineaire_Std.h>
Member Function Documentation
iterer_eqn()
bool Solveur_Lineaire_Std::iterer_eqn (Equation_base & equation, const DoubleTab & inconnue, DoubleTab & result, double dt, int numero_iteration, int & ok) override
References Equation_base::assembler_avec_inertie(), Equation_base::dimensionner_matrice(), SolveurSys::resoudre_systeme(), and solveur.
solveur_sys() [1/2]
SolveurSys & Solveur_Lineaire_Std::solveur_sys () inline
References solveur.
solveur_sys() [2/2]
const SolveurSys & Solveur_Lineaire_Std::solveur_sys () const inline
References solveur.
set_param()
void Solveur_Lineaire_Std::set_param (Param & param) protected
References Param::ajouter_non_std(), and Param::REQUIRED.
lire_motcle_non_standard()
int Solveur_Lineaire_Std::lire_motcle_non_standard (const Motcle & mot, Entree & is) override protected
References SolveurSys::nommer(), and solveur.
Member Data Documentation
solveur
SolveurSys Solveur_Lineaire_Std::solveur protected
Referenced by iterer_eqn(), lire_motcle_non_standard(), solveur_sys(), and solveur_sys().