CEA TRUST Platform: EOS_to_TRUST Class Reference
EOS_to_TRUST Class Reference
#include <EOS_to_TRUST.h>
Detailed Description
Interface commune pour TRUST et ses baltiks qui permet appeler les methodes de la lib EOS Methods disponibles en temperature et enthalpie, egalement pour la saturation
Constructor & Destructor Documentation
~EOS_to_TRUST()
EOS_to_TRUST::~EOS_to_TRUST () inline override
Member Function Documentation
desactivate_handler()
void EOS_to_TRUST::desactivate_handler (bool op = true) override virtual
Reimplemented from TPPI.
tppi_get_p_min()
double EOS_to_TRUST::tppi_get_p_min () const final override virtual
Implements TPPI.
Referenced by all_unknowns_range().
tppi_get_p_max()
double EOS_to_TRUST::tppi_get_p_max () const final override virtual
Implements TPPI.
Referenced by all_unknowns_range().
tppi_get_h_min()
double EOS_to_TRUST::tppi_get_h_min () const final override virtual
Implements TPPI.
Referenced by all_unknowns_range().
tppi_get_h_max()
double EOS_to_TRUST::tppi_get_h_max () const final override virtual
Implements TPPI.
Referenced by all_unknowns_range().
tppi_get_T_min()
double EOS_to_TRUST::tppi_get_T_min () const final override virtual
Implements TPPI.
Referenced by all_unknowns_range().
tppi_get_T_max()
double EOS_to_TRUST::tppi_get_T_max () const final override virtual
Implements TPPI.
Referenced by all_unknowns_range().
tppi_get_rho_min()
double EOS_to_TRUST::tppi_get_rho_min () const final override virtual
Implements TPPI.
Referenced by all_unknowns_range().
tppi_get_rho_max()
double EOS_to_TRUST::tppi_get_rho_max () const final override virtual
Implements TPPI.
Referenced by all_unknowns_range().
tppi_get_p_crit()
double EOS_to_TRUST::tppi_get_p_crit () const final override virtual
Implements TPPI.
tppi_get_h_crit()
double EOS_to_TRUST::tppi_get_h_crit () const final override virtual
Implements TPPI.
tppi_get_T_crit()
double EOS_to_TRUST::tppi_get_T_crit () const final override virtual
Implements TPPI.
tppi_get_rho_crit()
double EOS_to_TRUST::tppi_get_rho_crit () const final override virtual
Implements TPPI.
all_unknowns_range()
MRange EOS_to_TRUST::all_unknowns_range () final override virtual
Reimplemented from TPPI.
References tppi_get_h_max(), tppi_get_h_min(), tppi_get_p_max(), tppi_get_p_min(), tppi_get_rho_max(), tppi_get_rho_min(), tppi_get_T_max(), and tppi_get_T_min().
compute_eos_field() [1/2]
int EOS_to_TRUST::compute_eos_field (const SpanD P, SpanD res, const char *const pt, const char *const pn, bool is_T = false) const protected
Referenced by EOS_to_TRUST_generique::tppi_get_beta_pT(), EOS_to_TRUST_Sat_generique::tppi_get_p_sat_T(), and EOS_to_TRUST_Sat_generique::tppi_get_sigma_pT().
compute_eos_field() [2/2]
int EOS_to_TRUST::compute_eos_field (const SpanD P, const SpanD T, SpanD res, const char *const pt, const char *const pn) const protected
compute_eos_field_h()
int EOS_to_TRUST::compute_eos_field_h (const SpanD P, const SpanD H, SpanD res, const char *const pt, const char *const pn) const protected
Referenced by EOS_to_TRUST_Sat_generique::tppi_get_sigma_ph().