CEA TRUST Platform: OutputCommBuffer Class Reference
OutputCommBuffer Class Reference
Additional Inherited Members
Public Member Functions inherited from Sortie
virtual Sortie & operator<< (const char *ob)
virtual Sortie & operator<< (const Objet_U &ob)
void set_bin (bool bin) override
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Attributes inherited from Sortie
std::unique_ptr< ostream > ostream_
Protected Attributes inherited from AbstractIO
bool avoid_conversion_ = false
Detailed Description
C'est une classe derivee de Entree dont le stream est de type ostrstream (les donnees sont ecrites par operator<< dans un buffer en memoire). On utilise la classe comme suit: (1) on ecrit des donnees avec operator<< dans le buffer ouput_comm_buffer << x << y << chaine << ... ; (2) on recupere l'ensemble des donnees ecrites sous la forme d'un bloc de memoire contigu de taille "get_buffer_size()" situe a l'adresse "get_buffer()". (3) on reinitialise le buffer avec "clear()" et on peut refaire (1)
Constructor & Destructor Documentation
OutputCommBuffer()
OutputCommBuffer::OutputCommBuffer ()
References AbstractIO::avoid_conversion_, AbstractIO::bin_, and Sortie::ostream_.
~OutputCommBuffer()
OutputCommBuffer::~OutputCommBuffer () override
References clear().
Member Function Documentation
clear()
void OutputCommBuffer::clear ()
Referenced by Schema_Comm::end_comm(), and ~OutputCommBuffer().
get_buffer()
const char * OutputCommBuffer::get_buffer ()
Referenced by InputCommBuffer::create_stream_from_output_stream(), and Schema_Comm::echange_messages().
get_buffer_size()
int OutputCommBuffer::get_buffer_size ()
Referenced by InputCommBuffer::create_stream_from_output_stream(), Schema_Comm::echange_messages(), and Schema_Comm::echange_taille_et_messages().
get_stream()
ostringstream& OutputCommBuffer::get_stream () inline