CEA TRUST Platform: OctreeFloor_32_64< _SIZE_ > Class Template Reference
OctreeFloor_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void construire (Octree_t *, const ArrOfInt_t &, const OctreeLoc &)
int_t rang_elem_depuis_loc (const OctreeLoc &, int_t prems, double x, double y=0, double z=0) const override
int_t rang_elem_loc (const OctreeLoc &, double x, double y=0, double z=0) const override
int_t taille () const override
Public Member Functions inherited from Octree_32_64< _SIZE_ >
void construire (int, const ArrOfInt_t &, const OctreeLoc &, Octree_t *p=0)
Additional Inherited Members
Protected Member Functions inherited from Octree_32_64< _SIZE_ >
void detruire ()
Detailed Description
template<typename _SIZE_>
class OctreeFloor_32_64< _SIZE_ >
See also
OctreeLoc Octree OctreeRoot
Member Typedef Documentation
int_t
template<typename _SIZE_ > using OctreeFloor_32_64< _SIZE_ >::int_t = _SIZE_
Octree_t
template<typename _SIZE_ > using OctreeFloor_32_64< _SIZE_ >::Octree_t = Octree_32_64<_SIZE_>
ArrOfInt_t
template<typename _SIZE_ > using OctreeFloor_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
Constructor & Destructor Documentation
OctreeFloor_32_64()
template<typename _SIZE_ > OctreeFloor_32_64< _SIZE_ >::OctreeFloor_32_64 (Octree_t * mon_pere, const ArrOfInt_t & val, const OctreeLoc & loc) inline
References OctreeFloor_32_64< _SIZE_ >::construire(), Objet_U::dimension, OctreeFloor_32_64< _SIZE_ >::pos, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Member Function Documentation
construire()
template<typename _SIZE_ > void OctreeFloor_32_64< _SIZE_ >::construire (Octree_t * pe, const ArrOfInt_t & Tab, const OctreeLoc & loc)
Parameters
(Octree* pe)
(ArrOfInt& Tab)
(OctreeLoc& loc)
References TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array().
Referenced by OctreeFloor_32_64< _SIZE_ >::OctreeFloor_32_64().
rang_elem_loc()
template<typename _SIZE_ > OctreeFloor_32_64< _SIZE_ >::int_t OctreeFloor_32_64< _SIZE_ >::rang_elem_loc (const OctreeLoc & loc, double x, double y = 0, double z = 0) const override virtual
Parameters
(OctreeLoc& loc)
(double x)
(double y)
(double z)
Returns
(int)
Reimplemented from Octree_32_64< _SIZE_ >.
References Objet_U::dimension.
rang_elem_depuis_loc()
template<typename _SIZE_ > OctreeFloor_32_64< _SIZE_ >::int_t OctreeFloor_32_64< _SIZE_ >::rang_elem_depuis_loc (const OctreeLoc & loc, int_t prems, double x, double y = 0, double z = 0) const override virtual
Parameters
(OctreeLoc& loc)
(int prems)
(double x)
(double y)
(double z)
Returns
(int)
Reimplemented from Octree_32_64< _SIZE_ >.
References Objet_U::dimension.
printOn()
template<typename _SIZE_ > Sortie& OctreeFloor_32_64< _SIZE_ >::printOn (Sortie & is) const inline override virtual
Reimplemented from Octree_32_64< _SIZE_ >.
References Octree_32_64< _SIZE_ >::printOn().
readOn()
template<typename _SIZE_ > Entree& OctreeFloor_32_64< _SIZE_ >::readOn (Entree & is) inline override virtual
Reimplemented from Octree_32_64< _SIZE_ >.
References Octree_32_64< _SIZE_ >::readOn().
taille()
template<typename _SIZE_ > OctreeFloor_32_64< _SIZE_ >::int_t OctreeFloor_32_64< _SIZE_ >::taille override virtual
Renvoie la taille de l'octree.
Returns
(unsigned) la taille de l'octree
Reimplemented from Octree_32_64< _SIZE_ >.
Member Data Documentation
num_elem
template<typename _SIZE_ > ArrOfInt_t OctreeFloor_32_64< _SIZE_ >::num_elem protected
pos
template<typename _SIZE_ > ArrOfDouble OctreeFloor_32_64< _SIZE_ >::pos mutable protected
Referenced by OctreeFloor_32_64< _SIZE_ >::OctreeFloor_32_64().
les_octrees
template<typename _SIZE_ > Octree_32_64** Octree_32_64< _SIZE_ >::les_octrees protected
pere
template<typename _SIZE_ > Octree_32_64* Octree_32_64< _SIZE_ >::pere protected