CEA TRUST Platform: Saturation_base Class Reference
Saturation_base Class Reference abstract
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
set_param()
void Saturation_base::set_param (Param & param) override virtual
Reimplemented from Interface_base.
Reimplemented in Saturation_generique_EOS, and Saturation_generique_CoolProp.
References Param::ajouter(), P_ref_, Interface_base::set_param(), and T_ref_.
Referenced by Saturation_generique_CoolProp::set_param(), and Saturation_generique_EOS::set_param().
get_Pref()
double Saturation_base::get_Pref () const inline
References P_ref_.
mettre_a_jour()
void Saturation_base::mettre_a_jour (double temps) override virtual
Reimplemented from Interface_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Pb_Multiphase::equation_qdm(), TRUSTVect< _TYPE_, _SIZE_ >::get_span(), TRUSTVect< _TYPE_, _SIZE_ >::get_span_tot(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Interface_base::sigma(), and Tsat().
discretiser_Tsat()
void Saturation_base::discretiser_Tsat (const Nom & Tsat_nom, double temps)
References Discretisation_base::discretiser_champ().
Referenced by Milieu_composite::discretiser().
get_Tsat_champ() [1/2]
Champ_Don_base& Saturation_base::get_Tsat_champ () inline
Referenced by Milieu_composite::discretiser().
get_Tsat_champ() [2/2]
const Champ_Don_base& Saturation_base::get_Tsat_champ () const inline
get_Tsat_tab() [1/2]
DoubleTab& Saturation_base::get_Tsat_tab () inline
get_Tsat_tab() [2/2]
const DoubleTab& Saturation_base::get_Tsat_tab () const inline
Tsat() [1/2]
void Saturation_base::Tsat (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References P_ref_.
Referenced by Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Flux_parietal_diphasique_simple_lineaire::fraction_flux_vap(), mettre_a_jour(), and Flux_parietal_diphasique_simple_lineaire::qp().
dP_Tsat() [1/2]
void Saturation_base::dP_Tsat (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References P_ref_.
Referenced by Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), and Flux_parietal_diphasique_simple_lineaire::fraction_flux_vap().
Psat() [1/2]
void Saturation_base::Psat (const SpanD T, SpanD res, int ncomp = 1, int ind = 0) const
Referenced by Changement_phase_Silver_Simpson::calculer().
dT_Psat() [1/2]
void Saturation_base::dT_Psat (const SpanD T, SpanD res, int ncomp = 1, int ind = 0) const
Lvap() [1/2]
void Saturation_base::Lvap (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References P_ref_.
dP_Lvap() [1/2]
void Saturation_base::dP_Lvap (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References P_ref_.
Hls() [1/2]
void Saturation_base::Hls (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References P_ref_.
dP_Hls() [1/2]
void Saturation_base::dP_Hls (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References P_ref_.
Hvs() [1/2]
void Saturation_base::Hvs (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References P_ref_.
dP_Hvs() [1/2]
void Saturation_base::dP_Hvs (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const
References P_ref_.
get_sigma()
void Saturation_base::get_sigma (const SpanD T, const SpanD P, SpanD sig, int ncomp = 1, int ind = 0) const final virtual
References Interface_base::sigma_().
get_sigma_h()
void Saturation_base::get_sigma_h (const SpanD H, const SpanD P, SpanD sig, int ncomp = 1, int ind = 0) const final virtual
References Interface_base::sigma_h_().
compute_all_flux_interfacial_pb_multiphase()
void Saturation_base::compute_all_flux_interfacial_pb_multiphase (const SpanD P, MSatSpanD sats, int ncomp = 1, int ind = 0) const virtual
Reimplemented in Saturation_generique_TPPI_base.
Tsat() [2/2]
double Saturation_base::Tsat (const double P) const inline
dP_Tsat() [2/2]
double Saturation_base::dP_Tsat (const double P) const inline
Psat() [2/2]
double Saturation_base::Psat (const double T) const inline
dT_Psat() [2/2]
double Saturation_base::dT_Psat (const double T) const inline
Lvap() [2/2]
double Saturation_base::Lvap (const double P) const inline
dP_Lvap() [2/2]
double Saturation_base::dP_Lvap (const double P) const inline
Hls() [2/2]
double Saturation_base::Hls (const double P) const inline
dP_Hls() [2/2]
double Saturation_base::dP_Hls (const double P) const inline
Hvs() [2/2]
double Saturation_base::Hvs (const double P) const inline
dP_Hvs() [2/2]
double Saturation_base::dP_Hvs (const double P) const inline
OWN_PTR()
Saturation_base::OWN_PTR (Champ_Don_base) protected
Member Data Documentation
P_ref_
double Saturation_base::P_ref_ = -1 protected
Referenced by dP_Hls(), dP_Hvs(), dP_Lvap(), dP_Tsat(), get_Pref(), Hls(), Hvs(), Lvap(), set_param(), and Tsat().
T_ref_
double Saturation_base::T_ref_ = -1 protected
Referenced by set_param().