CEA TRUST Platform: Source_PDF_EF Class Reference
Source_PDF_EF Class Reference
Additional Inherited Members
Public Member Functions inherited from Source_PDF_base
void mettre_a_jour (double) override
void ouvrir_fichier (SFichier &, const Nom &, const int) const override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int initialiser (double temps)
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_pb()
void Source_PDF_EF::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References Process::abort(), PDF_model::affecter_variable_imposee(), Source_PDF_base::champ_aire_, Source_PDF_base::champ_aire_lu_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, compute_indicateur_nodal_champ_aire(), compute_variable_imposee_projete(), PDF_model::dim_variable_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), PDF_model::echelle_relax_, Source_PDF_base::echelle_relax_, MorEqn::equation(), Equation_base::inconnue(), Source_PDF_base::interpolation_bool_, Objet_U::le_nom(), PDF_model::local_, Source_PDF_base::matrice_pression_variable_bool_, Source_PDF_base::modele_lu_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), rotate_imposed_velocity(), tab_u_star_ibm_, tab_y_plus_ibm_, PDF_model::temps_relax_, Source_PDF_base::temps_relax_, Source_PDF_base::transpose_rotation_, PDF_model::type_variable_imposee_, Source_PDF_base::type_variable_imposee_, Source_PDF_base::updateChampRho(), Champ_Inc_base::valeurs(), and Source_PDF_base::variable_imposee_.
ajouter_() [1/2]
DoubleTab & Source_PDF_EF::ajouter_ (const DoubleTab & variable, DoubleTab & resu) const override virtual
Implements Source_dep_inco_base.
Referenced by verif_ajouter_contrib().
ajouter_() [2/2]
DoubleTab & Source_PDF_EF::ajouter_ (const DoubleTab & variable, DoubleTab & resu, const int i_traitement_special) const override virtual
Reimplemented from Source_PDF_base.
References Source_PDF_base::champ_aire_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, compute_pond(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), PDF_model::eta_, Process::exit(), Domaine_32_64< _SIZE_ >::les_elems(), Source_PDF_base::modele_lu_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), and Domaine_EF::volumes_thilde().
contribuer_a_avec()
void Source_PDF_EF::contribuer_a_avec (const DoubleTab & , Matrice_Morse & mat) const override virtual
contribution a la matrice implicite des termes sources par defaut pas de contribution
Reimplemented from Source_base.
References Source_PDF_base::champ_aire_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, Matrice_Morse::coef(), compute_pond(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), PDF_model::eta_, Process::exit(), Equation_base::inconnue(), Domaine_32_64< _SIZE_ >::les_elems(), Source_PDF_base::modele_lu_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Champ_Inc_base::valeurs(), and Domaine_EF::volumes_thilde().
verif_ajouter_contrib()
void Source_PDF_EF::verif_ajouter_contrib (const DoubleTab & variable, Matrice_Morse & matrice) const
References ajouter_(), Matrice_Morse::ajouter_multvect_(), Source_PDF_base::champ_aire_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and Domaine_32_64< _SIZE_ >::nb_som_elem().
compute_coeff_elem()
DoubleTab Source_PDF_EF::compute_coeff_elem () const override virtual
Reimplemented from Source_PDF_base.
References Source_PDF_base::champ_aire_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, diag_coeff_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), PDF_model::eta_, Process::exit(), Source_PDF_base::fonct_coeff(), Equation_base::inconnue(), Domaine_32_64< _SIZE_ >::les_elems(), Source_PDF_base::modele_lu_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), Probleme_base::schema_temps(), and Champ_Inc_base::valeurs().
diag_coeff_elem()
DoubleVect Source_PDF_EF::diag_coeff_elem (ArrOfDouble & variable_elem, const DoubleTab & rotation, int num_elem) const override virtual
Reimplemented from Source_PDF_base.
References Objet_U::dimension, and Source_PDF_base::get_tuvw_local().
Referenced by compute_coeff_elem(), and compute_coeff_matrice().
compute_coeff_matrice()
DoubleTab Source_PDF_EF::compute_coeff_matrice () const override virtual
Reimplemented from Source_PDF_base.
References Source_PDF_base::champ_aire_, Source_PDF_base::champ_rho_, Source_PDF_base::champ_rotation_, diag_coeff_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), PDF_model::eta_, Process::exit(), Source_PDF_base::fonct_coeff(), Equation_base::inconnue(), Domaine_32_64< _SIZE_ >::les_elems(), Source_PDF_base::modele_lu_, Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_32_64< _SIZE_ >::nb_som_tot(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), Probleme_base::schema_temps(), and Champ_Inc_base::valeurs().
multiply_coeff_volume()
void Source_PDF_EF::multiply_coeff_volume (DoubleTab & coeff) const override virtual
Reimplemented from Source_PDF_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Process::exit(), and TRUSTVect< _TYPE_, _SIZE_ >::size_totale().
correct_variable()
void Source_PDF_EF::correct_variable (const DoubleTab & coeff_node, DoubleTab & variable) const override virtual
Reimplemented from Source_PDF_base.
References Process::abort(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Source_PDF_base::variable_imposee_.
test()
void Source_PDF_EF::test (Matrice &) const
updateChampRho()
void Source_PDF_EF::updateChampRho ()
correct_pressure()
void Source_PDF_EF::correct_pressure (const DoubleTab & coeff_node, DoubleTab & pression, const DoubleTab & correction_en_pression) const override virtual
Reimplemented from Source_PDF_base.
References Source_PDF_base::champ_aire_.
correct_incr_pressure()
void Source_PDF_EF::correct_incr_pressure (const DoubleTab & coeff_node, DoubleTab & correction_en_pression) const override virtual
Reimplemented from Source_PDF_base.
References Source_PDF_base::champ_aire_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), filtre_CLD(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_som_elem(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
impr()
int Source_PDF_EF::impr (Sortie & os) const override virtual
Reimplemented from Source_base.
References Source_base::bilan_, Source_PDF_base::calculer(), Equation_base::derivee_en_temps_conv(), PDF_model::dim_variable_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Process::exit(), filtre_CLD(), Source_base::Flux, Equation_base::inconnue(), Process::je_suis_maitre(), Field_base::le_nom(), Source_PDF_base::modele_lu_, Navier_Stokes_std::nombre_d_operateurs(), Source_base::out_, Source_PDF_base::ouvrir_fichier(), Schema_Temps_base::pas_de_temps(), PDF_model::pdf_bilan(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::schema_temps(), Source_PDF_base::sec_mem_pdf, TRUSTVect< _TYPE_, _SIZE_ >::size(), Schema_Temps_base::temps_courant(), Champ_Inc_base::valeurs(), and Navier_Stokes_std::vitesse_pour_transport().
creer_champ()
void Source_PDF_EF::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Source_base::champs_compris_, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), MorEqn::equation(), Source_PDF_base::imm_wall_law_, and Equation_base::probleme().
get_champ()
const Champ_base & Source_PDF_EF::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Source_base::champs_compris_, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Champs_compris_T< FIELD_TYPE >::get_champ(), Nom::getString(), Domaine_32_64< _SIZE_ >::nb_som(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), tab_u_star_ibm_, and tab_y_plus_ibm_.
Referenced by has_champ().
has_champ() [1/2]
bool Source_PDF_EF::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
References Source_base::champs_compris_, get_champ(), and Champs_compris_T< FIELD_TYPE >::has_champ().
has_champ() [2/2]
bool Source_PDF_EF::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Source_base::champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
get_noms_champs_postraitables()
void Source_PDF_EF::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References Source_base::champs_compris_, Source_base::get_noms_champs_postraitables(), Source_PDF_base::imm_wall_law_, and Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
OWN_PTR() [1/3]
Source_PDF_EF::OWN_PTR (Champ_Don_base) protected
compute_variable_imposee_projete()
void Source_PDF_EF::compute_variable_imposee_projete (const DoubleTab & marqueur, const DoubleTab & points, double val, double eps) override protected virtual
Reimplemented from Source_PDF_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), PDF_model::get_variable_imposee(), Equation_base::inconnue(), Source_PDF_base::modele_lu_, and Champ_Inc_base::valeurs().
Referenced by associer_pb().
calculer_variable_imposee_hybrid()
void Source_PDF_EF::calculer_variable_imposee_hybrid () override protected virtual
Reimplemented from Source_PDF_base.
References Domaine_32_64< _SIZE_ >::coord(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), TRUSTListElem< _TYPE_ >::est_vide(), Interpolation_IBM_hybrid::getSommetsVoisinsOf(), Source_PDF_base::modele_lu_, Domaine_32_64< _SIZE_ >::nb_som(), TRUSTList< _TYPE_ >::size(), Champ_Inc_base::valeurs(), Champ_implementation_Q1::value_interpolation(), and Source_PDF_base::variable_imposee_.
calculer_variable_imposee_elem_fluid()
void Source_PDF_EF::calculer_variable_imposee_elem_fluid () override protected virtual
Reimplemented from Source_PDF_base.
References Domaine_32_64< _SIZE_ >::coord(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), Source_PDF_base::modele_lu_, Domaine_32_64< _SIZE_ >::nb_som(), Champ_Inc_base::valeurs(), Champ_implementation_Q1::value_interpolation(), and Source_PDF_base::variable_imposee_.
calculer_variable_imposee_mean_grad()
void Source_PDF_EF::calculer_variable_imposee_mean_grad () override protected virtual
Reimplemented from Source_PDF_base.
References Domaine_32_64< _SIZE_ >::coord(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), TRUSTListElem< _TYPE_ >::est_vide(), Interpolation_IBM_mean_gradient::getSommetsVoisinsOf(), Equation_base::inconnue(), Source_PDF_base::modele_lu_, Domaine_32_64< _SIZE_ >::nb_som(), TRUSTList< _TYPE_ >::size(), Champ_Inc_base::valeurs(), and Source_PDF_base::variable_imposee_.
calculer_vitesse_imposee_power_law_tbl()
void Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl () override protected virtual
Reimplemented from Source_PDF_base.
References Process::abort(), Domaine_32_64< _SIZE_ >::coord(), Operateur_Diff_base::diffusivite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), Process::exit(), Interpolation_IBM_power_law_tbl_proto::get_A_pwl(), Interpolation_IBM_power_law_tbl_proto::get_B_pwl(), Interpolation_IBM_power_law_tbl::get_formulation_linear_pwl(), Interpolation_IBM_base::get_impr(), Interpolation_IBM_base::get_N_histo(), Interpolation_IBM_power_law_tbl_proto::get_y_c_p_pwl(), Source_PDF_base::indicateur_nodal_champ_aire_, Source_PDF_base::modele_lu_, Domaine_32_64< _SIZE_ >::nb_som(), Equation_base::nombre_d_operateurs(), tab_u_star_ibm_, tab_y_plus_ibm_, Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Champ_implementation_Q1::value_interpolation(), and Source_PDF_base::variable_imposee_.
calculer_vitesse_imposee_power_law_tbl_u_star()
void Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star () override protected virtual
Reimplemented from Source_PDF_base.
References Process::abort(), Domaine_32_64< _SIZE_ >::coord(), Operateur_Diff_base::diffusivite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), TRUSTListElem< _TYPE_ >::est_vide(), Process::exit(), Interpolation_IBM_power_law_tbl_proto::get_A_pwl(), Interpolation_IBM_power_law_tbl_proto::get_B_pwl(), Interpolation_IBM_base::get_impr(), Interpolation_IBM_base::get_N_histo(), Interpolation_IBM_power_law_tbl_proto::get_y_c_p_pwl(), Interpolation_IBM_power_law_tbl_u_star::getSommetsVoisinsOf(), Equation_base::inconnue(), Source_PDF_base::modele_lu_, Domaine_32_64< _SIZE_ >::nb_som(), Equation_base::nombre_d_operateurs(), TRUSTList< _TYPE_ >::size(), tab_u_star_ibm_, tab_y_plus_ibm_, Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Source_PDF_base::variable_imposee_.
rotate_imposed_velocity()
void Source_PDF_EF::rotate_imposed_velocity (DoubleTab & vitesse_imposee) override protected virtual
Reimplemented from Source_PDF_base.
References Source_PDF_base::champ_rotation_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), Probleme_base::get_champ(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_32_64< _SIZE_ >::nb_som_tot(), Equation_base::probleme(), and Champ_Proto::valeurs().
Referenced by associer_pb().
compute_pond()
DoubleTab Source_PDF_EF::compute_pond (const DoubleTab & rho_m, const DoubleTab & aire, const DoubleVect & volume_thilde, int & nb_som_elem, int & nb_elems) const protected
References MorEqn::equation(), Source_PDF_base::fonct_coeff(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_min(), Equation_base::probleme(), and Probleme_base::schema_temps().
Referenced by ajouter_(), and contribuer_a_avec().
filtre_CLD()
void Source_PDF_EF::filtre_CLD (DoubleTab & flag_cl) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_sommets(), Domaine_Cl_EF::imposer_symetrie(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), and Front_VF::num_face().
Referenced by correct_incr_pressure(), and impr().
OBS_PTR() [1/2]
Source_PDF_EF::OBS_PTR (Domaine_EF) protected
OBS_PTR() [2/2]
Source_PDF_EF::OBS_PTR (Domaine_Cl_EF) protected
associer_domaines()
void Source_PDF_EF::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.
compute_indicateur_nodal_champ_aire()
void Source_PDF_EF::compute_indicateur_nodal_champ_aire () override protected virtual
Reimplemented from Source_PDF_base.
References Source_PDF_base::champ_aire_, Domaine_dis_base::domaine(), Source_PDF_base::indicateur_nodal_champ_aire_, Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), and Domaine_32_64< _SIZE_ >::nb_som_tot().
Referenced by associer_pb().
OWN_PTR() [2/3]
Source_PDF_EF::OWN_PTR (Champ_Fonc_base) mutable protected
Champ pour postraitement.
OWN_PTR() [3/3]
Source_PDF_EF::OWN_PTR (Champ_Fonc_base) mutable protected
Champ pour postraitement.
Member Data Documentation
tab_u_star_ibm_
DoubleVect Source_PDF_EF::tab_u_star_ibm_ protected
valeurs des u* IBM calculees localement
Referenced by associer_pb(), calculer_vitesse_imposee_power_law_tbl(), calculer_vitesse_imposee_power_law_tbl_u_star(), and get_champ().
tab_y_plus_ibm_
DoubleVect Source_PDF_EF::tab_y_plus_ibm_ protected
valeurs des d+ IBM calculees localement
Referenced by associer_pb(), calculer_vitesse_imposee_power_law_tbl(), calculer_vitesse_imposee_power_law_tbl_u_star(), and get_champ().