CEA TRUST Platform: Op_Diff_VEF_Face_Stab Class Reference
Op_Diff_VEF_Face_Stab Class Reference
#include <Op_Diff_VEF_Face_Stab.h>
Public Member Functions
void completer () override
Public Member Functions inherited from Op_Diff_VEF_Face
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Diff_VEF_base
double calculer_dt_stab () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
La discretisation est VEF Le champ diffuse est scalaire
Constructor & Destructor Documentation
Op_Diff_VEF_Face_Stab()
Op_Diff_VEF_Face_Stab::Op_Diff_VEF_Face_Stab ()
References Support_Champ_Masse_Volumique::declare_support_masse_volumique().
Member Function Documentation
ajouter()
DoubleTab & Op_Diff_VEF_Face_Stab::ajouter (const DoubleTab & inconnue_org, DoubleTab & resu) const override virtual
Reimplemented from Op_Diff_VEF_Face.
References ajouter_antidiffusion(), ajouter_diffusion(), ajouter_operateur_centre(), calculer_coefficients(), Domaine_dis_base::domaine(), MorEqn::equation(), Equation_base::milieu(), modifie_pour_Cl(), Op_VEF_Face::modifier_flux(), Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), and Op_Diff_VEF_base::remplir_nu().
completer()
void Op_Diff_VEF_Face_Stab::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_VEF_Face.
References Op_Diff_VEF_Face::completer(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces_tot(), Front_VF::nb_faces_tot(), Front_VF::num_face(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
ajouter_contribution()
void Op_Diff_VEF_Face_Stab::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
References Op_Diff_VEF_Face::ajouter_contribution(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Domaine_VF::premiere_face_int(), Op_Diff_VEF_base::remplir_nu(), and Op_Diff_VEF_base::viscA().
Referenced by contribuer_a_avec().
ajouter_contribution_multi_scalaire()
void Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire (const DoubleTab & transporte, Matrice_Morse & matrice) const
References Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Domaine_VF::premiere_face_int(), Op_Diff_VEF_base::remplir_nu(), and Op_Diff_VEF_base::viscA().
Referenced by contribuer_a_avec().
contribuer_a_avec()
void Op_Diff_VEF_Face_Stab::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice.
Reimplemented from Op_Diff_VEF_Face.
References ajouter_contribution(), ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::contribuer_a_avec(), MorEqn::equation(), Equation_base::inconnue(), and Field_base::nature_du_champ().
calculer_coefficients()
void Op_Diff_VEF_Face_Stab::calculer_coefficients (const DoubleTab & nu, DoubleTab & Aij) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), and Domaine_VF::volumes().
Referenced by ajouter().
calculer_min()
void Op_Diff_VEF_Face_Stab::calculer_min (const DoubleTab & inconnueTab, int & dim, DoubleTab & Minima) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Periodique::face_associee(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_VF::nb_faces_tot(), Front_VF::nb_faces_tot(), and Front_VF::num_face().
Referenced by ajouter_antidiffusion().
calculer_max()
void Op_Diff_VEF_Face_Stab::calculer_max (const DoubleTab & inconnueTab, int & dim, DoubleTab & Maxima) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Periodique::face_associee(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_VF::nb_faces_tot(), Front_VF::nb_faces_tot(), and Front_VF::num_face().
Referenced by ajouter_antidiffusion().
calculer_gradients()
double Op_Diff_VEF_Face_Stab::calculer_gradients (int facei, const DoubleTab & rij) const protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_VF::get_num_fac_loc(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), and Domaine_VF::volumes().
Referenced by ajouter_antidiffusion().
modifie_pour_Cl()
void Op_Diff_VEF_Face_Stab::modifie_pour_Cl (const DoubleTab & inconnue, DoubleTab & resu) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Periodique::face_associee(), Operateur_base::flux_bords_, Neumann::flux_impose(), Echange_impose_base::h_imp(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Front_VF::num_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::surface(), and Echange_impose_base::T_ext().
Referenced by ajouter().
ajouter_operateur_centre()
void Op_Diff_VEF_Face_Stab::ajouter_operateur_centre (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), and Domaine_32_64< _SIZE_ >::nb_faces_elem().
Referenced by ajouter().
ajouter_diffusion()
void Op_Diff_VEF_Face_Stab::ajouter_diffusion (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), and Domaine_32_64< _SIZE_ >::nb_faces_elem().
Referenced by ajouter().
ajouter_antidiffusion()
void Op_Diff_VEF_Face_Stab::ajouter_antidiffusion (const DoubleTab & Aij, const DoubleTab & inconnueTab, DoubleTab & resuTab) const protected
References calculer_gradients(), calculer_max(), calculer_min(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Process::je_suis_maitre(), Process::mp_max(), Process::mp_min(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_VF::nb_faces_tot(), and Domaine_VF::xv().
Referenced by ajouter().