CEA TRUST Platform: Navier_Stokes_std Class Reference
Navier_Stokes_std Class Reference
Public Member Functions
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
const Nom & le_nom () const override
int limpr () const
Probleme_base & probleme ()
const Probleme_base & probleme () const
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Protected Member Functions
virtual void discretiser_assembleur_pression ()
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_sources (Entree &)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour un fluide sans modelisation de la turbulence. On suppose l'hypothese de fluide incompressible: div U = 0 On considere la masse volumique constante (egale a rho_0) sauf dans le terme des forces de gravite (hypotheses de Boussinesq). Sous ces hypotheses, on utilise la forme suivante des equations de Navier_Stokes: DU/dt = div(terme visqueux) - gradP/rho_0 + Bt(T-T0)g + autres sources/rho_0 div U = 0 avec DU/dt : derivee particulaire de la vitesse rho_0 : masse volumique de reference T0 : temperature de reference Bt : coefficient de dilatabilite du fluide g : vecteur gravite Rq : l'implementation de la classe permet bien sur de negliger certains termes de l'equation (le terme visqueux, le terme convectif, tel ou tel terme source). L'inconnue est le champ de vitesse.
Pour le traitement des cas un peu particulier : ajout de Traitement_particulier exemple : THI, canal (CA)
See also
Equation_base Pb_Hydraulique Pb_Thermohydraulique
Constructor & Destructor Documentation
Navier_Stokes_std()
Navier_Stokes_std::Navier_Stokes_std ()
References cumulative_, dt_projection, max_div_U, projection_initiale, raison_seuil_divU, seuil_divU, seuil_projection, and seuil_uzawa.
Member Function Documentation
set_param()
void Navier_Stokes_std::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent, and QDM_Multiphase.
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_flag(), Param::ajouter_non_std(), Param::OPTIONAL, postraiter_gradient_pression_sans_masse_, projection_initiale, Param::REQUIRED, Equation_base::set_param(), and seuil_uzawa.
Referenced by Navier_Stokes_Fluide_Dilatable_base::set_param(), QDM_Multiphase::set_param(), Navier_Stokes_IBM::set_param(), and Navier_Stokes_Turbulent::set_param().
lire_motcle_non_standard()
int Navier_Stokes_std::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent, and QDM_Multiphase.
References Operateur_Diff::associer_diffusivite(), Operateur_Diff::associer_diffusivite_pour_pas_de_temps(), Operateur_Conv::associer_vitesse(), Sortie_Fichier_base::close(), diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), Equation_base::discretisation(), dt_projection, Process::exit(), Process::je_suis_maitre(), Equation_base::lire_motcle_non_standard(), max_div_U, methode_calcul_pression_initiale_, SolveurSys::nommer(), Objet_U::que_suis_je(), raison_seuil_divU, Motcles::rang(), seuil_divU, seuil_projection, solveur_pression_, terme_convectif, terme_diffusif, and vitesse_pour_transport().
Referenced by Navier_Stokes_IBM_Turbulent::lire_motcle_non_standard(), QDM_Multiphase::lire_motcle_non_standard(), Navier_Stokes_Turbulent::lire_motcle_non_standard(), and Navier_Stokes_Fluide_Dilatable_base::lire_motcle_non_standard().
associer_pb_base()
void Navier_Stokes_std::associer_pb_base (const Probleme_base & pb) override virtual
S'associe au probleme: apelle Equation_base::associer_pb_base(const Probleme_base&)
s'associe avec les operateurs de divergence et de gradient.
Parameters
(Probleme_base& pb) le probleme auquel s'associer
Reimplemented from Equation_base.
References MorEqn::associer_eqn(), Equation_base::associer_pb_base(), divergence, and gradient.
associer_fluide()
void Navier_Stokes_std::associer_fluide (const Fluide_base & un_fluide) inline
Referenced by associer_milieu_base().
milieu() [1/2]
const Milieu_base & Navier_Stokes_std::milieu () const override virtual
Renvoie le milieu physique de l'equation (le Fluide_base upcaste en Milieu_base)
Returns
(Milieu_base&) le Fluide_base de l'equation upcaste en Milieu_base
Implements Equation_base.
References Process::exit(), Probleme_U::le_nom(), and Equation_base::probleme().
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), calculer_la_pression_en_pa(), calculer_pression_hydrostatique(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Navier_Stokes_Fluide_Dilatable_base::get_champ(), Navier_Stokes_Turbulent_QC::get_champ(), Navier_Stokes_Turbulent_QC::has_champ(), Navier_Stokes_Fluide_Dilatable_base::has_champ(), and SETS::iterer_NS().
milieu() [2/2]
Milieu_base & Navier_Stokes_std::milieu () override virtual
Renvoie le milieu physique de l'equation (le Fluide_base upcaste en Milieu_base)
(version const)
Returns
(Milieu_base&) le Fluide_base de l'equation upcaste en Milieu_base
Implements Equation_base.
References Process::exit(), Probleme_U::le_nom(), and Equation_base::probleme().
fluide() [1/2]
const Fluide_base & Navier_Stokes_std::fluide () const
Renvoie le fluide incompressible (milieu physique de l'equation) associe a l'equation.
(version const)
Returns
(Fluide_base&) le fluide incompressible associe a l'equation
Referenced by creer_champ(), Navier_Stokes_IBM_Turbulent::diffusivite_pour_pas_de_temps(), Navier_Stokes_Turbulent::diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), Navier_Stokes_IBM_Turbulent::diffusivite_pour_transport(), Navier_Stokes_Turbulent::diffusivite_pour_transport(), Navier_Stokes_Turbulent_QC::diffusivite_pour_transport(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Navier_Stokes_IBM::preparer_calcul(), and preparer_calcul().
fluide() [2/2]
Fluide_base & Navier_Stokes_std::fluide ()
Renvoie le fluide incompressible (milieu physique de l'equation) associe a l'equation.
Returns
(Fluide_base&) le fluide incompressible associe a l'equation
associer_milieu_base()
void Navier_Stokes_std::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un mileu physique a l'equation en construisant dynamiquement (cast) un objet de type Fluide_base.
a partir de l'objet Milieu_base passe en parametre.
Parameters
(Milieu_base& un_milieu) le milieu a associer a l'equation
Implements Equation_base.
References associer_fluide(), and Process::exit().
Referenced by Pb_Hydraulique_IBM::associer_milieu_base(), Pb_Hydraulique_IBM_Turbulent::associer_milieu_base(), Pb_Thermohydraulique_IBM_Turbulent::associer_milieu_base(), Pb_Hydraulique::associer_milieu_base(), Pb_Hydraulique_Concentration::associer_milieu_base(), Pb_Hydraulique_Concentration_Turbulent::associer_milieu_base(), Pb_Hydraulique_Turbulent::associer_milieu_base(), Pb_Thermohydraulique_Concentration_Turbulent::associer_milieu_base(), and Pb_Thermohydraulique_Turbulent::associer_milieu_base().
nombre_d_operateurs()
int Navier_Stokes_std::nombre_d_operateurs () const override virtual
Renvoie le nombre d'operateurs de l'equation: Pour Navier Stokes Standard c'est 2.
Returns
(int) le nombre d'operateur de l'equation
Implements Equation_base.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), derivee_en_temps_inco(), Source_PDF_EF::impr(), operateur(), operateur_fonctionnel(), Navier_Stokes_IBM::preparer_calcul(), and preparer_calcul().
nombre_d_operateurs_tot()
int Navier_Stokes_std::nombre_d_operateurs_tot () const override virtual
Reimplemented from Equation_base.
operateur() [1/2]
const Operateur & Navier_Stokes_std::operateur (int i) const override virtual
Renvoie le i-eme operateur de l'equation: - le terme_diffusif si i = 0.
 - le terme_convectif si i = 1
exit si i>1
(version const)
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur indexe par i
Implements Equation_base.
References Process::exit(), nombre_d_operateurs(), terme_convectif, and terme_diffusif.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), derivee_en_temps_inco(), Navier_Stokes_IBM::preparer_calcul(), and preparer_calcul().
operateur() [2/2]
Operateur & Navier_Stokes_std::operateur (int i) override virtual
Renvoie le i-eme operateur de l'equation: - le terme_diffusif si i = 0.
 - le terme_convectif si i = 1
exit si i>1
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur indexe par i
Implements Equation_base.
References Process::exit(), nombre_d_operateurs(), terme_convectif, and terme_diffusif.
operateur_fonctionnel() [1/2]
const Operateur & Navier_Stokes_std::operateur_fonctionnel (int i) const override virtual
Reimplemented from Equation_base.
References divergence, Process::exit(), gradient, and nombre_d_operateurs().
Referenced by operateur_fonctionnel().
operateur_fonctionnel() [2/2]
Operateur & Navier_Stokes_std::operateur_fonctionnel (int i) override virtual
Reimplemented from Equation_base.
References divergence, Process::exit(), gradient, nombre_d_operateurs(), and operateur_fonctionnel().
operateur_divergence() [1/2]
Operateur_Div & Navier_Stokes_std::operateur_divergence ()
Renvoie l'operateur de calcul de la divergence associe a l'equation.
Returns
(Operateur_Div&) l'operateur de calcul de la divergence.
References divergence.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), and Champ_front_pression_from_u::mettre_a_jour().
operateur_divergence() [2/2]
const Operateur_Div & Navier_Stokes_std::operateur_divergence () const
Renvoie l'operateur de calcul de la divergence associe a l'equation.
(version const)
Returns
(Operateur_Div&) l'operateur de calcul de la divergence
References divergence.
operateur_gradient() [1/2]
Operateur_Grad & Navier_Stokes_std::operateur_gradient ()
Renvoie l'operateur de calcul du gradient associe a l'equation.
Returns
(Operateur_Grad&) l'operateur de calcul du gradient
References gradient.
operateur_gradient() [2/2]
const Operateur_Grad & Navier_Stokes_std::operateur_gradient () const
Renvoie l'operateur de calcul du gradient associe a l'equation.
(version const)
Returns
(Operateur_Grad&) l'operateur de calcul du gradient
References gradient.
operateur_diff() [1/2]
Operateur_Diff & Navier_Stokes_std::operateur_diff ()
References terme_diffusif.
operateur_diff() [2/2]
const Operateur_Diff & Navier_Stokes_std::operateur_diff () const
References terme_diffusif.
inconnue() [1/2]
const Champ_Inc_base & Navier_Stokes_std::inconnue () const override virtual
Renvoie la vitesse (champ inconnue de l'equation) (version const)
Returns
(Champ_Inc_base&) le champ inconnue representant la vitesse
Implements Equation_base.
Referenced by Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), Terme_Source_Acceleration_VEF_Face::calculer_vitesse_faces(), Navier_Stokes_Fluide_Dilatable_base::completer(), completer(), QDM_Multiphase::completer(), derivee_en_temps_inco(), Fluide_Ostwald::discretiser(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), Navier_Stokes_Turbulent_QC::initTimeStep(), SETS::iterer_NS(), lire_cond_init(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), QDM_Multiphase::mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), preparer_calcul(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), and Convection_Diffusion_Chaleur_QC::vitesse_pour_transport().
inconnue() [2/2]
Champ_Inc_base & Navier_Stokes_std::inconnue () override virtual
Renvoie la vitesse (champ inconnue de l'equation)
Returns
(Champ_Inc_base&) le champ inconnue representant la vitesse
Implements Equation_base.
solveur_pression()
SolveurSys & Navier_Stokes_std::solveur_pression ()
Renvoie le solveur en pression (version const)
Returns
(SolveurSys&) le solveur en pression
References solveur_pression_.
Referenced by Simpler_Base::assembler_matrice_pression_implicite(), and SETS::iterer_NS().
discretiser()
void Navier_Stokes_std::discretiser () override virtual
Dicretise l'equation.
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent_QC.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Operateur_base::associer_eqn(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), discretiser_assembleur_pression(), discretiser_grad_p(), discretiser_vitesse(), divergence, Discret_Thyd::divergence_U(), divergence_U, Equation_base::domaine_dis(), gradient, Operateur_Div::l_op_base(), Operateur_Grad::l_op_base(), la_pression, la_pression_en_pa, Discret_Thyd::pression(), Discret_Thyd::pression_en_pa(), Equation_base::schema_temps(), Operateur_Div::typer(), and Operateur_Grad::typer().
Referenced by Navier_Stokes_Fluide_Dilatable_base::discretiser(), and Navier_Stokes_Turbulent_QC::discretiser().
discretiser_vitesse()
void Navier_Stokes_std::discretiser_vitesse () virtual
Reimplemented in QDM_Multiphase.
References Equation_base::discretisation(), Equation_base::domaine_dis(), Equation_base::schema_temps(), and Discret_Thyd::vitesse().
Referenced by discretiser().
discretiser_grad_p()
void Navier_Stokes_std::discretiser_grad_p () virtual
Reimplemented in QDM_Multiphase.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::domaine_dis(), Discret_Thyd::gradient_P(), gradient_P, and Equation_base::schema_temps().
Referenced by discretiser().
completer()
void Navier_Stokes_std::completer () override virtual
Complete l'equation base, associe la pression a l'equation,.
complete la divergence, le gradient et le solveur pression. Ajout de 2 termes sources: l'un representant la force centrifuge dans le cas axi-symetrique,l'autre intervenant dans la resolution en 2D axisymetrique Association d une equation de transport d interface a l ensemble de points suivis si le fluide est marque
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent_QC, Navier_Stokes_Turbulent, and QDM_Multiphase.
References Objet_U::axi, Equation_base::completer(), Operateur::completer(), Equation_base::discretisation(), divergence, divergence_U, Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), gradient, gradient_P, inconnue(), Equation_base::initialise_residu(), la_pression, la_pression_en_pa, Equation_base::les_sources, Objet_U::que_suis_je(), Nom::suffix(), and Source::typer_direct().
Referenced by Navier_Stokes_Fluide_Dilatable_base::completer(), Navier_Stokes_IBM_Turbulent::completer(), QDM_Multiphase::completer(), and Navier_Stokes_Turbulent::completer().
lire_cond_init()
Entree & Navier_Stokes_std::lire_cond_init (Entree & is) override virtual
Lecture des conditions initiales dans un flot d'entree.
Le format de lecture est le suivant: { Nom [DOIT ETRE LE NOM DE L'INCONNUE] [LIRE UN CHAMP DONNE] }
Parameters
(Entree& is) le flot d'entree
Returns
(Entree&) le flot d'entree modifie
Exceptions
erreur de format, accolade ouvrante attendue
mauvais nom pour l'inconnue
erreur de format, accolade fermante attendue
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
References Champ_base::affecter(), Process::exit(), inconnue(), Field_base::nb_comp(), OWN_PTR(), pression(), Objet_U::que_suis_je(), Motcles::rang(), and Equation_base::verifie_ch_init_nb_comp().
initTimeStep()
bool Navier_Stokes_std::initTimeStep (double dt) override virtual
Allocation et initialisation de l'inconnue et des CLs jusqu'a present+dt.
autres initialisations pour les calculs sur le prochain pas de temps : operateurs, solveur_masse->
Returns
(0 en cas d'erreur, 1 sinon)
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent_QC, Navier_Stokes_Turbulent, and QDM_Multiphase.
References Champ_Inc_base::changer_temps_futur(), Champ_Inc_base::futur(), Equation_base::initTimeStep(), Schema_Temps_base::nb_valeurs_futures(), pression(), pression_pa(), Schema_Temps_base::temps_futur(), and Champ_Inc_base::valeurs().
Referenced by Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), Navier_Stokes_IBM::initTimeStep(), and Navier_Stokes_Turbulent::initTimeStep().
mettre_a_jour()
void Navier_Stokes_std::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de l'equation.
Appelle Equation_base::mettre_a_jour(double) et met a jour la pression. Integration des points suivis si le fluide est marque Mise a jour du champ postraitable correspondant
Parameters
(double temps) le temps de mise a jour
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent_QC, Navier_Stokes_Turbulent, and QDM_Multiphase.
References Operateur_Div::calculer(), Operateur_Grad::calculer(), calculer_la_pression_en_pa(), critere_Q, divergence, divergence_U, solv_iteratif::get_seuil(), grad_u, gradient, gradient_P, la_pression, Equation_base::mettre_a_jour(), postraiter_gradient_pression_sans_masse_, projection_a_faire(), projeter(), raison_seuil_divU, Reynolds_maille, solv_iteratif::set_seuil(), seuil_divU, solveur_pression_, Taux_cisaillement, and Debog::verifier().
Referenced by Navier_Stokes_Fluide_Dilatable_base::mettre_a_jour(), Navier_Stokes_IBM_Turbulent::mettre_a_jour(), and Navier_Stokes_Turbulent::mettre_a_jour().
abortTimeStep()
void Navier_Stokes_std::abortTimeStep () override virtual
Reinitialiser ce qui doit l'etre.
Cette methode est appelee lorsqu'un pas de temps est abandonne, par exemple parce que le calcul a diverge. Il faut donc nettoyer ce qui pourrait polluer la nouvelle resolution.
Exceptions
WrongContext
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
References Equation_base::abortTimeStep(), pression(), and Champ_Inc_base::valeurs().
resetTime()
void Navier_Stokes_std::resetTime (double time) override virtual
Reset current time of the equation. Used from ICoCo. See documentation of Problem_base::resetTime()
Reimplemented from Equation_base.
References pression(), Equation_base::resetTime(), and Champ_Inc_base::resetTime().
impr()
int Navier_Stokes_std::impr (Sortie & os) const override virtual
Effectue quelques impressions sur un flot de sortie: - maximum de div U.
  - terme convectif
  - terme diffusif
  - divergence
  - gradient
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase, and Navier_Stokes_Turbulent_QC.
References Objet_U::bidim_axi, cumulative_, Objet_U::dimension, divergence, divergence_U, Probleme_base::domaine(), Process::exit(), solv_iteratif::get_seuil(), gradient, Equation_base::impr(), Operateur::impr(), la_pression, Probleme_U::le_nom(), Process::nproc(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Objet_U::que_suis_je(), Equation_base::schema_temps(), seuil_divU, solveur_pression_, and Domaine_32_64< _SIZE_ >::volume_total().
Referenced by Navier_Stokes_Turbulent_QC::impr(), and Navier_Stokes_Fluide_Dilatable_base::impr().
dimensionner_matrice_sans_mem()
void Navier_Stokes_std::dimensionner_matrice_sans_mem (Matrice_Morse & matrice) override virtual
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
References Equation_base::dimensionner_matrice_sans_mem(), and gradient.
Referenced by QDM_Multiphase::dimensionner_matrice_sans_mem().
has_interface_blocs()
int Navier_Stokes_std::has_interface_blocs () const override virtual
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
References gradient, and Equation_base::has_interface_blocs().
Referenced by QDM_Multiphase::has_interface_blocs().
dimensionner_blocs()
void Navier_Stokes_std::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Equation_base.
Reimplemented in QDM_Multiphase.
References Equation_base::dimensionner_blocs(), and gradient.
Referenced by QDM_Multiphase::dimensionner_blocs().
assembler_blocs()
void Navier_Stokes_std::assembler_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Equation_base.
References Equation_base::assembler_blocs(), and gradient.
data_a_sauvegarder()
std::vector< YAML_data > Navier_Stokes_std::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent.
References Equation_base::data_a_sauvegarder(), la_pression, and pression().
Referenced by Navier_Stokes_IBM_Turbulent::data_a_sauvegarder(), and Navier_Stokes_Turbulent::data_a_sauvegarder().
sauvegarder()
int Navier_Stokes_std::sauvegarder (Sortie & os) const override virtual
Appelle Equation_base::sauvegarder(Sortie&) et sauvegarde la pression sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie sur lequel sauvegarder
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent.
References la_pression, Equation_base::sauvegarder(), and sauver().
Referenced by Navier_Stokes_IBM_Turbulent::sauvegarder(), and Navier_Stokes_Turbulent::sauvegarder().
reprendre()
int Navier_Stokes_std::reprendre (Entree & is) override virtual
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre() et reprend la pression.
Parameters
(Entree& is) un flot d'entree
Returns
(int) renvoie toujours 1
Exceptions
la reprise a echoue, identificateur de la pression non trouve
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent.
References Probleme_base::domaine(), TRUST_2_PDI::is_PDI_restart(), la_pression, Domaine_base::le_nom(), Equation_base::probleme(), Equation_base::reprendre(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by Navier_Stokes_IBM_Turbulent::reprendre(), and Navier_Stokes_Turbulent::reprendre().
derivee_en_temps_inco()
DoubleTab & Navier_Stokes_std::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent_QC.
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse_base::ajouter_masse(), Operateur_Grad::calculer(), Equation_base::derivee_en_temps_inco(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Operateur_base::get_decal_temps(), Operateur_base::get_matrice(), Operateur_base::get_solveur(), gradient, gradient_P, Equation_base::implicite_, inconnue(), Operateur::l_op_base(), la_pression, Equation_base::les_sources, nombre_d_operateurs(), operateur(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Operateur_base::set_matrice(), Operateur_base::set_solveur(), Equation_base::solv_masse(), Equation_base::sys_invariant_, and uzawa().
corriger_derivee_expl()
DoubleTab & Navier_Stokes_std::corriger_derivee_expl (DoubleTab & derivee) override virtual
Add a specific term for Navier Stokes (-gradP(n)) if necessary.
Reimplemented from Equation_base.
References Operateur_Grad::calculer(), gradient, gradient_P, and la_pression.
corriger_derivee_impl()
DoubleTab & Navier_Stokes_std::corriger_derivee_impl (DoubleTab & derivee) override virtual
Resolution de la pression, inconnue implicitee de Navier Stokes.
Reimplemented from Equation_base.
References Operateur_Div::calculer(), Operateur_Grad::calculer(), div_ale_derivative(), div_u_nul_et_non_dsurdt_divu_, divergence, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), gradient, gradient_P, la_pression, Equation_base::limpr(), matrice_pression_, Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), renewing_jacobians(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), Probleme_base::schema_temps(), solveur_pression_, and terme_convectif.
preparer_calcul()
int Navier_Stokes_std::preparer_calcul () override virtual
cf Equation_base::preparer_calcul() Assemblage du solveur pression et
initialisation de la pression.
assemblage du systeme en pression
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent_QC, Navier_Stokes_Turbulent, and QDM_Multiphase.
References Operateur::ajouter(), Sources::ajouter(), Operateur_Div::calculer(), Operateur_Grad::calculer(), calculer_la_pression_en_pa(), Equation_base::calculer_pas_de_temps(), divergence, divergence_U, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), fluide(), gradient, gradient_P, inconnue(), Probleme_base::is_dilatable(), la_pression, matrice_pression_, methode_calcul_pression_initiale_, Sources::mettre_a_jour(), nombre_d_operateurs(), operateur(), Equation_base::preparer_calcul(), Equation_base::probleme(), projection_a_faire(), projeter(), SolveurSys::resoudre_systeme(), Equation_base::schema_temps(), solveur_pression_, Equation_base::sources(), Schema_Temps_base::temps_courant(), and Debog::verifier().
Referenced by Navier_Stokes_Fluide_Dilatable_base::preparer_calcul(), and Navier_Stokes_Turbulent::preparer_calcul().
matrice_pression()
Matrice& Navier_Stokes_std::matrice_pression () inline
References matrice_pression_.
Referenced by Navier_Stokes_IBM::initTimeStep(), and Navier_Stokes_IBM::preparer_calcul().
OWN_PTR() [1/6]
Navier_Stokes_std::OWN_PTR (Assembleur_base) & inline
Referenced by lire_cond_init(), and QDM_Multiphase::lire_cond_init().
has_grad_P()
bool Navier_Stokes_std::has_grad_P () const inline
References gradient_P.
grad_P() [1/2]
Champ_Inc_base& Navier_Stokes_std::grad_P () inline
References gradient_P.
Referenced by Source_WC_Chaleur_VDF::compute_interpolate_gradP().
grad_P() [2/2]
const Champ_Inc_base& Navier_Stokes_std::grad_P () const inline
References gradient_P.
pression() [1/2]
Champ_Inc_base& Navier_Stokes_std::pression () inline
References la_pression.
Referenced by abortTimeStep(), calculer_la_pression_en_pa(), data_a_sauvegarder(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Sortie_libre_Gradient_Pression_libre_VEF::flux_impose(), initTimeStep(), QDM_Multiphase::initTimeStep(), SETS::iterer_NS(), lire_cond_init(), QDM_Multiphase::mettre_a_jour(), Schema_Backward_Differentiation_base::modify_equation_parameters(), QDM_Multiphase::preparer_calcul(), resetTime(), Schema_Backward_Differentiation_base::store_equation_parameters(), and Neumann_sortie_libre::verifie_ch_init_nb_comp().
pression() [2/2]
const Champ_Inc_base& Navier_Stokes_std::pression () const inline
References la_pression.
pression_pa() [1/2]
Champ_Inc_base& Navier_Stokes_std::pression_pa () inline
References la_pression_en_pa.
Referenced by Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), initTimeStep(), QDM_Multiphase::initTimeStep(), QDM_Multiphase::mettre_a_jour(), and QDM_Multiphase::preparer_calcul().
pression_pa() [2/2]
const Champ_Inc_base& Navier_Stokes_std::pression_pa () const inline
References la_pression_en_pa.
div() [1/2]
Champ_Inc_base& Navier_Stokes_std::div () inline
References divergence_U.
Referenced by Navier_Stokes_Fluide_Dilatable_Proto::impr_impl().
div() [2/2]
const Champ_Inc_base& Navier_Stokes_std::div () const inline
References divergence_U.
diffusivite_pour_transport()
const Champ_Don_base & Navier_Stokes_std::diffusivite_pour_transport () const virtual
Reimplemented in Navier_Stokes_Turbulent_QC, Navier_Stokes_Turbulent, QDM_Multiphase, Navier_Stokes_IBM_Turbulent, and Navier_Stokes_Fluide_Dilatable_base.
References fluide(), and Fluide_base::viscosite_cinematique().
Referenced by lire_motcle_non_standard().
diffusivite_pour_pas_de_temps()
const Champ_base & Navier_Stokes_std::diffusivite_pour_pas_de_temps () const virtual
Reimplemented in Navier_Stokes_Turbulent, QDM_Multiphase, Navier_Stokes_IBM_Turbulent, and Navier_Stokes_Fluide_Dilatable_base.
References Operateur_Diff::diffusivite(), and terme_diffusif.
Referenced by lire_motcle_non_standard().
vitesse_pour_transport()
const Champ_base & Navier_Stokes_std::vitesse_pour_transport () const virtual
Reimplemented in QDM_Multiphase, and Navier_Stokes_Fluide_Dilatable_base.
Referenced by Source_PDF_EF::impr(), and lire_motcle_non_standard().
creer_champ()
void Navier_Stokes_std::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent, and QDM_Multiphase.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Discret_Thyd::courant_maille(), Courant_maille, Equation_base::creer_champ(), Discret_Thyd::creer_champ_vorticite(), Discret_Thyd::critere_Q(), critere_Q, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Discret_Thyd::distance_paroi_globale(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), fluide(), Discret_Thyd::grad_u(), grad_u, pression_hydrostatique_, Discret_Thyd::reynolds_maille(), Reynolds_maille, Equation_base::schema_temps(), Discret_Thyd::taux_cisaillement(), Taux_cisaillement, Discret_Thyd::y_plus(), and y_plus.
Referenced by Navier_Stokes_IBM_Turbulent::creer_champ(), QDM_Multiphase::creer_champ(), and Navier_Stokes_Turbulent::creer_champ().
get_champ()
const Champ_base & Navier_Stokes_std::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent_QC, and Navier_Stokes_Turbulent.
References calculer_pression_hydrostatique(), Equation_base::champs_compris_, Courant_maille, critere_Q, Champs_compris_T< FIELD_TYPE >::get_champ(), Nom::getString(), grad_u, Equation_base::has_champ(), Champ_Fonc_base::mettre_a_jour(), OBS_PTR(), pression_hydrostatique_, Reynolds_maille, Equation_base::schema_temps(), Taux_cisaillement, Champ_base::temps(), Schema_Temps_base::temps_init(), and y_plus.
Referenced by Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), and Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D().
has_champ() [1/2]
bool Navier_Stokes_std::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
Referenced by Navier_Stokes_Fluide_Dilatable_base::get_champ(), Navier_Stokes_IBM_Turbulent::get_champ(), Navier_Stokes_Turbulent::get_champ(), Navier_Stokes_IBM_Turbulent::has_champ(), Navier_Stokes_Turbulent::has_champ(), and Navier_Stokes_Fluide_Dilatable_base::has_champ().
has_champ() [2/2]
bool Navier_Stokes_std::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent_QC, and Navier_Stokes_Turbulent.
References Courant_maille, critere_Q, grad_u, Equation_base::has_champ(), pression_hydrostatique_, Reynolds_maille, Taux_cisaillement, and y_plus.
get_noms_champs_postraitables()
void Navier_Stokes_std::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
Reimplemented in Navier_Stokes_Turbulent, and QDM_Multiphase.
References Equation_base::champs_compris_, Equation_base::get_noms_champs_postraitables(), and Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
Referenced by Navier_Stokes_IBM_Turbulent::get_noms_champs_postraitables(), QDM_Multiphase::get_noms_champs_postraitables(), and Navier_Stokes_Turbulent::get_noms_champs_postraitables().
domaine_application()
const Motcle & Navier_Stokes_std::domaine_application () const override virtual
Renvoie le nom du domaine d'application: "Hydraulique".
Returns
(Motcle&) lenom representant le domaine d'application
Reimplemented from Equation_base.
vitesse() [1/2]
virtual const Champ_Inc_base& Navier_Stokes_std::vitesse () const inline virtual
Referenced by Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Reel::resoudre(), and EDO_Pression_th_VEF_Gaz_Reel::resoudre().
vitesse() [2/2]
virtual Champ_Inc_base& Navier_Stokes_std::vitesse () inline virtual
projeter()
void Navier_Stokes_std::projeter () virtual
Calcule la solution U des equations: | M(U-V)/dt + BtP = 0.
     |-BU=0
On resoud le probleme en pression: -BM-1BtP = -BV/dt sachant que -BV represente le calcul de la divergence de V On resoud le probleme en vitesse en appliquant le solveur de masse au gradient de P: U=V - dt*M-1BtP
Exceptions
pas de temps trop petit
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute(), Operateur_Div::calculer(), Equation_base::calculer_pas_de_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), divergence, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), solv_iteratif::get_seuil(), gradient, gradient_P, la_pression, matrice_pression_, modify_initial_gradP(), modify_initial_variable(), Equation_base::probleme(), projection_initiale, SolveurSys::resoudre_systeme(), solv_iteratif::set_seuil(), seuil_projection, solveur_pression_, and Debog::verifier().
Referenced by mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), and preparer_calcul().
projection_a_faire()
int Navier_Stokes_std::projection_a_faire () virtual
References dt_projection, and projection_initiale.
Referenced by mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), and preparer_calcul().
sauver()
void Navier_Stokes_std::sauver () const virtual
Referenced by sauvegarder().
calculer_la_pression_en_pa()
void Navier_Stokes_std::calculer_la_pression_en_pa () virtual
Calcul de "la_pression_en_pa" en fonction de "la_pression".
Si le champ milieu().masse_volumique() est uniforme, on suppose que la_pression est P* = P/rho, et on multiplie par rho. Sinon, la_pression est deja en Pa. Cette methode est surchargee en front-tracking.
References TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), la_pression, la_pression_en_pa, Milieu_base::masse_volumique(), milieu(), pression(), Champ_base::temps(), and Champ_Proto::valeurs().
Referenced by mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), and preparer_calcul().
calculer_pression_hydrostatique()
void Navier_Stokes_std::calculer_pression_hydrostatique (Champ_base & pression_hydro) const virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Milieu_base::gravite(), Domaine_32_64< _SIZE_ >::les_sommets(), Milieu_base::masse_volumique(), milieu(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by get_champ().
verif_Cl()
int Navier_Stokes_std::verif_Cl () const override virtual
Verifie la compatibilite des conditions limites avec l'equation.
voir Conds_lim::compatible_avec_eqn().
Returns
(int)
Reimplemented from Equation_base.
References Equation_base::verif_Cl().
rho_la_vitesse()
const Champ_Inc_base & Navier_Stokes_std::rho_la_vitesse () const virtual
Reimplemented in Navier_Stokes_Turbulent_QC, and Navier_Stokes_Fluide_Dilatable_base.
References Process::exit().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport(), Convection_Diffusion_Espece_Binaire_base::vitesse_pour_transport(), and Convection_Diffusion_Espece_Multi_WC::vitesse_pour_transport().
get_terme_convectif()
Operateur_Conv& Navier_Stokes_std::get_terme_convectif () inline
References terme_convectif.
renewing_jacobians()
void Navier_Stokes_std::renewing_jacobians (DoubleTab & derivee) virtual
Referenced by corriger_derivee_impl().
div_ale_derivative()
void Navier_Stokes_std::div_ale_derivative (DoubleTrav & derivee_ale, double timestep, DoubleTab & derivee, DoubleTrav & secmemP) virtual
Referenced by corriger_derivee_impl().
updateFluidForce()
virtual void Navier_Stokes_std::updateFluidForce (DoubleTab &) inline virtual
getCouplingInfoForFiltering()
virtual bool Navier_Stokes_std::getCouplingInfoForFiltering () const inline virtual
Referenced by Op_Grad_VEF_P1B_Face::calculer_flux_bords().
getPressureTimeN()
DoubleTab Navier_Stokes_std::getPressureTimeN () inline
setPressureTimeN()
virtual void Navier_Stokes_std::setPressureTimeN () inline virtual
Referenced by Piso::iterer_NS().
update_y_plus()
void Navier_Stokes_std::update_y_plus (const DoubleTab & tab)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Process::exit(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Objet_U::que_suis_je(), and y_plus.
discretiser_assembleur_pression()
void Navier_Stokes_std::discretiser_assembleur_pression () protected virtual
Typage de l'assembleur pression.
Le nom de l'assembleur utilise est construit comme : Assembleur_P_xxx" ou "xxx" est le nom de la discretisation. Cette methode est virtuelle et surchargee dans le front-tracking. Elle est appelee par Navier_Stokes_std::discretiser()
References Equation_base::discretisation(), Equation_base::domaine_dis(), and Objet_U::que_suis_je().
Referenced by discretiser().
modify_initial_variable()
virtual void Navier_Stokes_std::modify_initial_variable () inline protected virtual
Reimplemented in Navier_Stokes_IBM.
Referenced by projeter().
modify_initial_gradP()
virtual void Navier_Stokes_std::modify_initial_gradP (DoubleTrav &) inline protected virtual
Reimplemented in Navier_Stokes_IBM.
Referenced by projeter().
OBS_PTR()
Navier_Stokes_std::OBS_PTR (Fluide_base) protected
Referenced by Navier_Stokes_Fluide_Dilatable_base::get_champ(), get_champ(), Navier_Stokes_Turbulent::get_champ(), and Navier_Stokes_Turbulent_QC::get_champ().
OWN_PTR() [2/6]
Navier_Stokes_std::OWN_PTR (Champ_Inc_base) protected
OWN_PTR() [3/6]
Navier_Stokes_std::OWN_PTR (Champ_Fonc_base) protected
OWN_PTR() [4/6]
Navier_Stokes_std::OWN_PTR (Champ_Fonc_base) protected
OWN_PTR() [5/6]
Navier_Stokes_std::OWN_PTR (Assembleur_base) protected
OWN_PTR() [6/6]
Navier_Stokes_std::OWN_PTR (Traitement_particulier_NS_base) protected
uzawa()
void Navier_Stokes_std::uzawa (const DoubleTab & secmem, const Matrice_Base & A, SolveurSys & solveur, DoubleTab & U, DoubleTab & P) protected
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute(), TRUSTTab< _TYPE_, _SIZE_ >::copy(), Solveur_Masse_base::corriger_solution(), divergence, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), gradient, Process::je_suis_maitre(), SolveurSys::nommer(), SolveurSys::resoudre_systeme(), seuil_uzawa, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Equation_base::solv_masse().
Referenced by derivee_en_temps_inco().
Member Data Documentation
la_pression
Navier_Stokes_std::la_pression protected
Referenced by calculer_la_pression_en_pa(), completer(), corriger_derivee_expl(), corriger_derivee_impl(), data_a_sauvegarder(), derivee_en_temps_inco(), discretiser(), impr(), QDM_Multiphase::lire_cond_init(), mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), preparer_calcul(), pression(), projeter(), reprendre(), and sauvegarder().
divergence_U
Navier_Stokes_std::divergence_U protected
Referenced by completer(), discretiser(), div(), impr(), mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), and preparer_calcul().
gradient_P
Navier_Stokes_std::gradient_P protected
Referenced by completer(), corriger_derivee_expl(), corriger_derivee_impl(), QDM_Multiphase::creer_champ(), derivee_en_temps_inco(), discretiser_grad_p(), grad_P(), has_grad_P(), mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), preparer_calcul(), and projeter().
la_pression_en_pa
Navier_Stokes_std::la_pression_en_pa protected
Referenced by calculer_la_pression_en_pa(), completer(), discretiser(), QDM_Multiphase::lire_cond_init(), and pression_pa().
grad_u
Navier_Stokes_std::grad_u protected
Referenced by creer_champ(), QDM_Multiphase::creer_champ(), get_champ(), has_champ(), mettre_a_jour(), and QDM_Multiphase::mettre_a_jour().
critere_Q
Navier_Stokes_std::critere_Q protected
Referenced by creer_champ(), get_champ(), has_champ(), and mettre_a_jour().
pression_hydrostatique_
Navier_Stokes_std::pression_hydrostatique_ protected
Referenced by creer_champ(), get_champ(), and has_champ().
combinaison_champ
Navier_Stokes_std::combinaison_champ protected
y_plus
Navier_Stokes_std::y_plus protected
Referenced by creer_champ(), get_champ(), has_champ(), and update_y_plus().
Reynolds_maille
Navier_Stokes_std::Reynolds_maille protected
Referenced by creer_champ(), get_champ(), has_champ(), and mettre_a_jour().
Courant_maille
Navier_Stokes_std::Courant_maille protected
Referenced by creer_champ(), get_champ(), and has_champ().
Taux_cisaillement
Navier_Stokes_std::Taux_cisaillement protected
Referenced by creer_champ(), get_champ(), has_champ(), mettre_a_jour(), and QDM_Multiphase::mettre_a_jour().
terme_convectif
Operateur_Conv Navier_Stokes_std::terme_convectif protected
Referenced by QDM_Multiphase::completer(), corriger_derivee_impl(), get_terme_convectif(), lire_motcle_non_standard(), and operateur().
terme_diffusif
Operateur_Diff Navier_Stokes_std::terme_diffusif protected
Referenced by QDM_Multiphase::completer(), diffusivite_pour_pas_de_temps(), Navier_Stokes_IBM_Turbulent::lire_motcle_non_standard(), lire_motcle_non_standard(), Navier_Stokes_Turbulent::lire_motcle_non_standard(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), operateur(), and operateur_diff().
divergence
Operateur_Div Navier_Stokes_std::divergence protected
Referenced by associer_pb_base(), completer(), corriger_derivee_impl(), discretiser(), impr(), mettre_a_jour(), operateur_divergence(), operateur_fonctionnel(), Navier_Stokes_IBM::preparer_calcul(), preparer_calcul(), projeter(), and uzawa().
gradient
Operateur_Grad Navier_Stokes_std::gradient protected
Referenced by assembler_blocs(), associer_pb_base(), completer(), QDM_Multiphase::completer(), corriger_derivee_expl(), corriger_derivee_impl(), derivee_en_temps_inco(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), discretiser(), has_interface_blocs(), impr(), mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), operateur_fonctionnel(), operateur_gradient(), Navier_Stokes_IBM::preparer_calcul(), preparer_calcul(), projeter(), and uzawa().
matrice_pression_
Matrice Navier_Stokes_std::matrice_pression_ protected
Referenced by corriger_derivee_impl(), matrice_pression(), Navier_Stokes_IBM::preparer_calcul(), preparer_calcul(), and projeter().
solveur_pression_
SolveurSys Navier_Stokes_std::solveur_pression_ protected
Referenced by corriger_derivee_impl(), impr(), lire_motcle_non_standard(), mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), preparer_calcul(), projeter(), and solveur_pression().
projection_initiale
int Navier_Stokes_std::projection_initiale protected
Referenced by Navier_Stokes_std(), Navier_Stokes_IBM::preparer_calcul(), projection_a_faire(), projeter(), and set_param().
dt_projection
double Navier_Stokes_std::dt_projection protected
Referenced by lire_motcle_non_standard(), Navier_Stokes_std(), and projection_a_faire().
seuil_projection
double Navier_Stokes_std::seuil_projection protected
Referenced by lire_motcle_non_standard(), Navier_Stokes_std(), and projeter().
seuil_uzawa
double Navier_Stokes_std::seuil_uzawa protected
Referenced by Navier_Stokes_std(), set_param(), and uzawa().
max_div_U
double Navier_Stokes_std::max_div_U protected
Referenced by lire_motcle_non_standard(), and Navier_Stokes_std().
seuil_divU
double Navier_Stokes_std::seuil_divU protected
Referenced by impr(), lire_motcle_non_standard(), mettre_a_jour(), and Navier_Stokes_std().
raison_seuil_divU
double Navier_Stokes_std::raison_seuil_divU protected
Referenced by lire_motcle_non_standard(), mettre_a_jour(), and Navier_Stokes_std().
cumulative_
double Navier_Stokes_std::cumulative_ mutable protected
Referenced by impr(), and Navier_Stokes_std().
chaine_champ_combi
Nom Navier_Stokes_std::chaine_champ_combi protected
methode_calcul_pression_initiale_
int Navier_Stokes_std::methode_calcul_pression_initiale_ protected
Referenced by lire_motcle_non_standard(), Navier_Stokes_IBM::preparer_calcul(), and preparer_calcul().
postraiter_gradient_pression_sans_masse_
bool Navier_Stokes_std::postraiter_gradient_pression_sans_masse_ = false protected
Referenced by mettre_a_jour(), and set_param().
div_u_nul_et_non_dsurdt_divu_
int Navier_Stokes_std::div_u_nul_et_non_dsurdt_divu_ protected
Referenced by corriger_derivee_impl().