CEA TRUST Platform: EOS_to_TRUST_Sat_generique Class Reference
EOS_to_TRUST_Sat_generique Class Reference
#include <EOS_to_TRUST_Sat_generique.h>
Detailed Description
Interface commune pour TRUST et ses baltiks qui permet appeler les methodes de la lib EOS Methods disponibles pour la saturation en temperature et enthalpie
See also
EOS_to_TRUST
Member Function Documentation
set_saturation_generique()
void EOS_to_TRUST_Sat_generique::set_saturation_generique (const char *const model_name, const char *const fluid_name) override virtual
Reimplemented from TPPI.
tppi_get_p_sat_T()
int EOS_to_TRUST_Sat_generique::tppi_get_p_sat_T (const SpanD T, SpanD res, int ncomp = 1, int ind = 0) const override virtual
Reimplemented from TPPI.
References EOS_to_TRUST::compute_eos_field().
tppi_get_p_sat_d_T_T()
int EOS_to_TRUST_Sat_generique::tppi_get_p_sat_d_T_T (const SpanD T, SpanD res, int ncomp = 1, int ind = 0) const override virtual
Reimplemented from TPPI.
tppi_get_lvap_p()
int EOS_to_TRUST_Sat_generique::tppi_get_lvap_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const override virtual
Reimplemented from TPPI.
References TPPI::tppi_get_h_l_sat_p(), and TPPI::tppi_get_h_v_sat_p().
tppi_get_lvap_d_p_p()
int EOS_to_TRUST_Sat_generique::tppi_get_lvap_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const override virtual
Reimplemented from TPPI.
References TPPI::tppi_get_h_l_sat_d_p_p(), and TPPI::tppi_get_h_v_sat_d_p_p().
tppi_get_sigma_pT()
int EOS_to_TRUST_Sat_generique::tppi_get_sigma_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int id = 0) const override virtual
Reimplemented from TPPI.
References EOS_to_TRUST::compute_eos_field().
tppi_get_sigma_ph()
int EOS_to_TRUST_Sat_generique::tppi_get_sigma_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int id = 0) const override virtual
Reimplemented from TPPI.
References EOS_to_TRUST::compute_eos_field_h(), and Process::exit().
tppi_get_all_flux_interfacial_pb_multiphase()
int EOS_to_TRUST_Sat_generique::tppi_get_all_flux_interfacial_pb_multiphase (const SpanD P, MSatSpanD sats, int ncomp = 1, int id = 0) const override virtual
Reimplemented from TPPI.
tppi_get_all_sat_loi_F5()
int EOS_to_TRUST_Sat_generique::tppi_get_all_sat_loi_F5 (const MSpanD input, MSatSpanD sats, int ncomp = 1, int id = 0) const override virtual
Reimplemented from TPPI.
set_user_uniform_sigma()
void EOS_to_TRUST_Sat_generique::set_user_uniform_sigma (const double sigma) inline override virtual
Reimplemented from TPPI.