CEA TRUST Platform: BilanQdmVEF Class Reference
BilanQdmVEF Class Reference
Member Function Documentation
bilan_qdm()
void BilanQdmVEF::bilan_qdm (const DoubleTab & dudt, const Domaine_Cl_VEF & domaine_Cl_VEF, ArrOfDouble & bilan) static
References Domaine_Cl_dis_base::domaine_dis(), Periodique::face_associee(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Terme_Source_Qdm_VEF_Face::ajouter().
bilan_energie()
void BilanQdmVEF::bilan_energie (const DoubleTab & dudt, const DoubleTab & u, const Domaine_Cl_VEF & domaine_Cl_VEF, ArrOfDouble & bilan) static
References Domaine_Cl_dis_base::domaine_dis(), Periodique::face_associee(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Terme_Source_Qdm_VEF_Face::ajouter().