CEA TRUST Platform: Solv_Gen Class Reference
Solv_Gen Class Reference
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Solv_Gen()
Solv_Gen::Solv_Gen ()
References solv_iteratif::seuil_.
Member Function Documentation
resoudre_systeme() [1/2]
int Solv_Gen::resoudre_systeme (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
References Process::exit(), Matrice_Bloc::get_bloc(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and solve().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_Gen::resoudre_systeme (const Matrice_Base & M, const DoubleVect & A, DoubleVect & B, int niter_max) inline override virtual
Reimplemented from SolveurSys_base.
References resoudre_systeme().
OWN_PTR() [1/5]
Solv_Gen::OWN_PTR (SolvElem_base) & inline
OWN_PTR() [2/5]
const Solv_Gen::OWN_PTR (SolvElem_base) const & inline
OWN_PTR() [3/5]
const Solv_Gen::OWN_PTR (Precond_base) const & inline
set_precond()
void Solv_Gen::set_precond (const OWN_PTR(Precond_base)& pre) inline
reinit()
void Solv_Gen::reinit () override virtual
Reimplemented from SolveurSys_base.
set_param()
void Solv_Gen::set_param (Param & param) protected
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), force_, SolveurSys_base::return_on_error_, SolveurSys_base::save_matrice_, and solv_iteratif::seuil_.
lire_motcle_non_standard()
int Solv_Gen::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References SolveurSys_base::fixer_limpr(), nb_it_max_, and nb_it_max_flag.
solve()
int Solv_Gen::solve (const Matrice_Base & matrice, const Matrice_Base & mat_loc, const DoubleVect & secmem, DoubleVect & solution) protected
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), force_, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Process::je_suis_maitre(), SolveurSys_base::limpr(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_sum(), Matrice_Base::multvect(), Matrice_Base::multvectT(), nb_it_max_, nb_it_max_flag, TRUSTTab< _TYPE_, _SIZE_ >::ref_array(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), SolveurSys_base::return_on_error_, TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector(), solv_iteratif::seuil_, TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and ILU_SP::type_precond().
Referenced by resoudre_systeme().
OWN_PTR() [4/5]
Solv_Gen::OWN_PTR (Precond_base) protected
OWN_PTR() [5/5]
Solv_Gen::OWN_PTR (SolvElem_base) protected
Member Data Documentation
nb_it_max_
int Solv_Gen::nb_it_max_ = 1000000 protected
Referenced by lire_motcle_non_standard(), and solve().
nb_it_max_flag
int Solv_Gen::nb_it_max_flag = 0 protected
Referenced by lire_motcle_non_standard(), and solve().
force_
bool Solv_Gen::force_ = false protected
Referenced by set_param(), and solve().