CEA TRUST Platform: Quadrature_base Class Reference
Quadrature_base Class Reference abstract
Public Member Functions
virtual void compute_integ_points ()=0
virtual void compute_integ_points_on_facet ()=0
double compute_integral (DoubleTab &vals_pts_integ) const
double compute_integral (Parser_U &parser) const
double compute_integral_on_elem (int num_elem, DoubleTab &val_pts_integ) const
double compute_integral_on_elem (int num_elem, Parser_U &parser) const
double compute_integral_on_elem (Parser_U &parser) const
double compute_integral_on_facet (int num_facet, DoubleTab &val_pts_integ) const
double compute_integral_on_facet (int num_facet, Parser_U &parser) const
Constructor & Destructor Documentation
Quadrature_base()
Quadrature_base::Quadrature_base (const Domaine_DG & dom) inline
~Quadrature_base()
virtual Quadrature_base::~Quadrature_base () inline virtual
Member Function Documentation
get_integ_points()
const DoubleTab& Quadrature_base::get_integ_points () const inline
References integ_points_.
Referenced by Champ_Elem_DG::affecter_(), Champ_Fonc_P1_DG::affecter_(), Champ_Elem_DG::eval_bfunc(), Champ_Elem_DG::eval_grad_bfunc(), and Domaine_DG::get_position().
get_integ_points_facets()
const DoubleTab& Quadrature_base::get_integ_points_facets () const inline
References integ_points_facets_.
Referenced by Op_Diff_DG_Elem::contribuer_au_second_membre(), Champ_Elem_DG::eval_bfunc_on_facets(), and Champ_Elem_DG::eval_grad_bfunc_on_facets().
get_weights()
const DoubleTab& Quadrature_base::get_weights () const inline
References weights_.
Referenced by Champ_Elem_DG::eval_invMassMatrix().
get_weights_facets()
const DoubleTab& Quadrature_base::get_weights_facets () const inline
References weights_facets_.
get_tab_nb_pts_integ()
const IntTab& Quadrature_base::get_tab_nb_pts_integ () const inline
References tab_nb_pts_integ_.
Referenced by Champ_Elem_DG::build_local_mass_matrix(), Champ_Elem_DG::build_mass_matrix(), Champ_Elem_DG::build_transition_matrix(), and Domaine_DG::get_nb_integ_points().
get_ind_pts_integ()
const IntTab& Quadrature_base::get_ind_pts_integ () const inline
References ind_pts_integ_.
Referenced by Domaine_DG::get_ind_integ_points().
compute_integ_points()
virtual void Quadrature_base::compute_integ_points () pure virtual
Compute for the whole domain the exact location of integration points per element
Implemented in Quadrature_Ord5_Polygone, Quadrature_Ord3_Polygone, and Quadrature_Ord1_Polygone.
compute_integ_points_on_facet()
virtual void Quadrature_base::compute_integ_points_on_facet () pure virtual
Compute for the whole domain the exact location of integration points per facet
Implemented in Quadrature_Ord5_Polygone, Quadrature_Ord3_Polygone, and Quadrature_Ord1_Polygone.
nb_pts_integ_max()
int Quadrature_base::nb_pts_integ_max () const inline
References nb_pts_integ_max_.
Referenced by Champ_Elem_DG::affecter_(), Op_Diff_DG_Elem::ajouter_blocs(), Champ_Elem_DG::build_local_mass_matrix(), Champ_Elem_DG::build_mass_matrix(), Champ_Elem_DG::build_transition_matrix(), Eval_Puiss_Th_DG_Elem::calculer_terme_source(), Domaine_DG::compute_L1_norm(), Domaine_DG::compute_L2_norm(), Champ_Elem_DG::eval_bfunc(), Champ_Elem_DG::eval_elem(), Champ_Elem_DG::eval_grad_bfunc(), Champ_Elem_DG::eval_invMassMatrix(), Champ_Elem_DG::valeur_aux(), Champ_Elem_DG::valeur_aux_elems(), and Champ_Fonc_P1_DG::valeur_aux_elems().
nb_pts_integ()
int Quadrature_base::nb_pts_integ (int e) const inline
References tab_nb_pts_integ_.
Referenced by Champ_Elem_DG::affecter_(), Champ_Fonc_P1_DG::affecter_(), Eval_Puiss_Th_DG_Elem::calculer_terme_source(), Domaine_DG::compute_L1_norm(), Domaine_DG::compute_L2_norm(), Champ_Elem_DG::eval_bfunc(), Champ_Elem_DG::eval_elem(), Champ_Elem_DG::eval_grad_bfunc(), Champ_Elem_DG::eval_invMassMatrix(), Champ_Elem_DG::valeur_aux_elems(), and Champ_Fonc_P1_DG::valeur_aux_elems().
nb_pts_integ_facets()
int Quadrature_base::nb_pts_integ_facets () const inline
References nb_pts_integ_facets_.
Referenced by Champ_Elem_DG::eval_bfunc_on_facets(), and Champ_Elem_DG::eval_grad_bfunc_on_facets().
ind_pts_integ()
int Quadrature_base::ind_pts_integ (int e) const inline
References ind_pts_integ_.
Referenced by Champ_Elem_DG::affecter_(), Champ_Fonc_P1_DG::affecter_(), Champ_Elem_DG::eval_bfunc(), Champ_Elem_DG::eval_grad_bfunc(), and Champ_Elem_DG::eval_invMassMatrix().
compute_integral() [1/2]
double Quadrature_base::compute_integral (Parser_U & parser) const
Compute the integral of a function on the whole domain
References compute_integral_on_elem(), and Process::mp_sum().
compute_integral() [2/2]
double Quadrature_base::compute_integral (DoubleTab & vals_pts_integ) const
Compute the integral of a function on the whole domain with its values on integration points
References ind_pts_integ_, Process::mp_sum(), tab_nb_pts_integ_, and weights_.
compute_integral_on_elem() [1/3]
double Quadrature_base::compute_integral_on_elem (int num_elem, Parser_U & parser) const
Compute the integral of a function on one triangle
References Parser_U::eval(), ind_pts_integ_, integ_points_, Parser_U::setVar(), and tab_nb_pts_integ_.
Referenced by Champ_Elem_DG::affecter_(), Champ_Elem_DG::build_local_mass_matrix(), Champ_Elem_DG::build_mass_matrix(), Eval_Puiss_Th_DG_Elem::calculer_terme_source(), compute_integral(), Domaine_DG::compute_L1_norm(), Domaine_DG::compute_L2_norm(), Champ_Elem_DG::gramSchmidt(), Champ_Elem_DG::valeur_aux_elems(), and Champ_Fonc_P1_DG::valeur_aux_elems().
compute_integral_on_elem() [2/3]
double Quadrature_base::compute_integral_on_elem (Parser_U & parser) const
Compute the integral of a function on each triangle
compute_integral_on_elem() [3/3]
double Quadrature_base::compute_integral_on_elem (int num_elem, DoubleTab & val_pts_integ) const
Compute the integral of a function on one triangle with its value on integration points
References ind_pts_integ_, tab_nb_pts_integ_, and weights_.
compute_integral_on_facet() [1/2]
double Quadrature_base::compute_integral_on_facet (int num_facet, Parser_U & parser) const
Compute the integral of a function on each triangle with its value on integration points
Compute the integral of a function on one facet
References Parser_U::eval(), integ_points_facets_, nb_pts_integ_facets_, and Parser_U::setVar().
Referenced by Op_Diff_DG_Elem::contribuer_au_second_membre().
compute_integral_on_facet() [2/2]
double Quadrature_base::compute_integral_on_facet (int num_facet, DoubleTab & val_pts_integ) const
Compute the integral of a function on one facet with its value on integration points
References nb_pts_integ_facets_, and weights_facets_.
OBS_PTR()
Quadrature_base::OBS_PTR (Domaine_DG) protected
triangleArea()
double Quadrature_base::triangleArea (double x1, double y1, double x2, double y2, double x3, double y3) protected
Referenced by calculateWeightScale().
calculateWeightScale() [1/2]
double Quadrature_base::calculateWeightScale (const IntTab & vert_elems, const DoubleTab & xs, DoubleVect & volumes, int e, int s1, int s2, int s3) protected
References triangleArea().
Referenced by Quadrature_Ord1_Polygone::compute_integ_points(), Quadrature_Ord3_Polygone::compute_integ_points(), and Quadrature_Ord5_Polygone::compute_integ_points().
calculateWeightScale() [2/2]
double Quadrature_base::calculateWeightScale (double ve, double s1x, double s1y, double s2x, double s2y, double s3x, double s3y) protected
References triangleArea().
Member Data Documentation
nb_pts_integ_quad_
int Quadrature_base::nb_pts_integ_quad_ protected
nb_pts_integ_tri_
int Quadrature_base::nb_pts_integ_tri_ protected
nb_pts_integ_facets_
int Quadrature_base::nb_pts_integ_facets_ protected
Referenced by Quadrature_Ord1_Polygone::compute_integ_points_on_facet(), Quadrature_Ord3_Polygone::compute_integ_points_on_facet(), Quadrature_Ord5_Polygone::compute_integ_points_on_facet(), compute_integral_on_facet(), and nb_pts_integ_facets().
nb_pts_integ_max_
int Quadrature_base::nb_pts_integ_max_ protected
Referenced by Quadrature_Ord1_Polygone::compute_integ_points(), Quadrature_Ord3_Polygone::compute_integ_points(), Quadrature_Ord5_Polygone::compute_integ_points(), and nb_pts_integ_max().
tab_nb_pts_integ_
IntTab Quadrature_base::tab_nb_pts_integ_ protected
Referenced by Quadrature_Ord1_Polygone::compute_integ_points(), Quadrature_Ord3_Polygone::compute_integ_points(), Quadrature_Ord5_Polygone::compute_integ_points(), compute_integral(), compute_integral_on_elem(), get_tab_nb_pts_integ(), and nb_pts_integ().
ind_pts_integ_
IntTab Quadrature_base::ind_pts_integ_ protected
Referenced by Quadrature_Ord1_Polygone::compute_integ_points(), Quadrature_Ord3_Polygone::compute_integ_points(), Quadrature_Ord5_Polygone::compute_integ_points(), compute_integral(), compute_integral_on_elem(), get_ind_pts_integ(), and ind_pts_integ().
parser_
Parser_U Quadrature_base::parser_ protected
integ_points_
DoubleTab Quadrature_base::integ_points_ protected
Referenced by Quadrature_Ord1_Polygone::compute_integ_points(), Quadrature_Ord3_Polygone::compute_integ_points(), Quadrature_Ord5_Polygone::compute_integ_points(), compute_integral_on_elem(), and get_integ_points().
integ_points_facets_
DoubleTab Quadrature_base::integ_points_facets_ protected
Referenced by Quadrature_Ord1_Polygone::compute_integ_points_on_facet(), Quadrature_Ord3_Polygone::compute_integ_points_on_facet(), Quadrature_Ord5_Polygone::compute_integ_points_on_facet(), compute_integral_on_facet(), and get_integ_points_facets().
weights_
DoubleTab Quadrature_base::weights_ protected
Referenced by Quadrature_Ord1_Polygone::compute_integ_points(), Quadrature_Ord3_Polygone::compute_integ_points(), Quadrature_Ord5_Polygone::compute_integ_points(), compute_integral(), compute_integral_on_elem(), and get_weights().
weights_quad_
DoubleTab Quadrature_base::weights_quad_ protected
weights_tri_
DoubleTab Quadrature_base::weights_tri_ protected
Referenced by Quadrature_Ord1_Polygone::compute_integ_points(), Quadrature_Ord3_Polygone::compute_integ_points(), and Quadrature_Ord5_Polygone::compute_integ_points().
weights_facets_
DoubleTab Quadrature_base::weights_facets_ protected
Referenced by Quadrature_Ord1_Polygone::compute_integ_points_on_facet(), Quadrature_Ord3_Polygone::compute_integ_points_on_facet(), Quadrature_Ord5_Polygone::compute_integ_points_on_facet(), compute_integral_on_facet(), and get_weights_facets().