CEA TRUST Platform: Operateur_Diff Class Reference
Operateur_Diff Class Reference
Public Member Functions
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void associer_diffusivite (const Champ_base &)
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
const Champ_base & diffusivite () const
const Operateur_base & l_op_base () const override
Operateur_base & l_op_base () override
void typer (const Nom &)
Public Member Functions inherited from Operateur
DoubleTab & ajouter (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
virtual void completer ()
const Discretisation_base & discretisation () const
int impr (Sortie &os) const
void imprimer (Sortie &os) const
int limpr () const
Entree & lire (Entree &)
virtual void mettre_a_jour (double temps)
const Champ_Inc_base & mon_inconnue () const
const Nom & type () const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Detailed Description
de diffusion. Un objet Operateur_Diff peut referencer n'importe quel objet derivant de Operateur_Diff_base.
See also
Operateur_Diff_base Operateur
Member Function Documentation
l_op_base() [1/2]
Operateur_base & Operateur_Diff::l_op_base () override virtual
Renvoie l'objet sous-jacent upcaste en Operateur_base.
Returns
(Operateur_base&) l'objet sous-jacent upcaste en Operateur_base
Implements Operateur.
Referenced by Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), and Transport_2eq_base::lire_op_diff_turbulent().
l_op_base() [2/2]
const Operateur_base & Operateur_Diff::l_op_base () const override virtual
Renvoie l'objet sous-jacent upcaste en Operateur_base (version const)
Returns
(Operateur_base&) l'objet sous-jacent upcaste en Operateur_base
Implements Operateur.
ajouter()
DoubleTab & Operateur_Diff::ajouter (const DoubleTab & donnee, DoubleTab & resu) const override virtual
Appel a l'objet sous-jacent.
Ajoute la contribution de l'operateur au tableau passe en parametre
Parameters
(DoubleTab& donnee) tableau contenant les donnees sur lesquelles on applique l'operateur.
(DoubleTab& resu) tableau auquel on ajoute la contribution de l'operateur
Returns
(DoubleTab&) le tableau contenant le resultat
Implements Operateur.
References Perf_counters::begin_count().
calculer()
DoubleTab & Operateur_Diff::calculer (const DoubleTab & donnee, DoubleTab & resu) const override virtual
Appel a l'objet sous-jacent.
Initialise le tableau passe en parametre avec la contribution de l'operateur.
Parameters
(DoubleTab& donnee) tableau contenant les donnees sur lesquelles on applique l'operateur.
(DoubleTab& resu) tableau dans lequel stocke la contribution de l'operateur
Returns
(DoubleTab&) le tableau contenant le resultat
Implements Operateur.
References Perf_counters::begin_count().
associer_diffusivite()
void Operateur_Diff::associer_diffusivite (const Champ_base & nu)
Associe la diffusivite a l'operateur.
Parameters
(Champ_Don_base& nu) le champ representant la diffusivite
Returns
le champ representant la diffusivite
Referenced by TRUSTProblem_Cloned_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::clone_equations(), Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), Navier_Stokes_IBM_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_std::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard(), Navier_Stokes_Turbulent::lire_motcle_non_standard(), Conduction::lire_motcle_non_standard(), Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), and Transport_2eq_base::lire_op_diff_turbulent().
associer_diffusivite_pour_pas_de_temps()
void Operateur_Diff::associer_diffusivite_pour_pas_de_temps (const Champ_base & nu)
Referenced by TRUSTProblem_Cloned_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::clone_equations(), Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), Convection_Diffusion_Temperature_IBM_Turbulent::lire_motcle_non_standard(), Navier_Stokes_IBM_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_std::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Concentration_Turbulent::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Temperature_Turbulent::lire_motcle_non_standard(), Navier_Stokes_Turbulent::lire_motcle_non_standard(), and Conduction::lire_motcle_non_standard().
diffusivite()
const Champ_base & Operateur_Diff::diffusivite () const
Renvoie le champ representant la diffusivite.
Returns
(Champ_Don_base&) le champ representant la diffusivite
Referenced by Convection_Diffusion_std::diffusivite_pour_pas_de_temps(), Navier_Stokes_std::diffusivite_pour_pas_de_temps(), Conduction::diffusivite_pour_pas_de_temps(), Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), Transport_2eq_base::lire_op_diff_turbulent(), and typer().
typer() [1/2]
void Operateur_Diff::typer () override virtual
Type l'operateur: se type "Op_Diff_"+discretisation() + ("_"ou"_Multi_inco_") + inconnue().suffix Associe la diffusivite a l'operateur base.
Implements Operateur.
References diffusivite(), Equation_base::discretisation(), Discretisation_base::get_name_of_type_for(), and Operateur::typ.
Referenced by Convection_Diffusion_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_IBM_Turbulent::lire_op_diff_turbulent(), Navier_Stokes_Turbulent::lire_op_diff_turbulent(), Transport_2eq_base::lire_op_diff_turbulent(), and typer().
typer() [2/2]
void Operateur_Diff::typer (const Nom & un_type)
Type l'operateur.
Parameters
(Nom& typ) le nom representant le type de l'operateur
References typer().
op_non_nul()
int Operateur_Diff::op_non_nul () const inline override virtual
Implements Operateur.
OBS_PTR()
Operateur_Diff::OBS_PTR (Champ_base) protected