CEA TRUST Platform: Multigrille_Adrien Class Reference
Multigrille_Adrien Class Reference
#include <Multigrille_Adrien.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Multigrille_Adrien()
Multigrille_Adrien::Multigrille_Adrien ()
Member Function Documentation
completer()
int Multigrille_Adrien::completer (const Equation_base & eq)
References initialize(), and Interprete_bloc::objet_global().
initialize()
void Multigrille_Adrien::initialize (const Domaine_IJK & split)
References completer_double_for_residue(), Multigrille_base::precision_double_, Multigrille_base::precision_float_, Multigrille_base::precision_mix_, and Multigrille_base::solver_precision_.
Referenced by completer(), and IJK_Test_Multigrille::interpreter().
nb_grid_levels()
int Multigrille_Adrien::nb_grid_levels () const inline override virtual
Implements Multigrille_base.
set_rho() [1/2]
void Multigrille_Adrien::set_rho (const DoubleVect & rho)
References Statistiques::begin_count(), Multigrille_base::convert_to_ijk(), Statistiques::end_count(), Statistiques::new_counter(), Multigrille_base::precision_float_, set_rho(), and Multigrille_base::solver_precision_.
Referenced by IJK_Test_Multigrille::interpreter(), and set_rho().
set_rho() [2/2]
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_Adrien::set_rho (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & rho)
References Multigrille_base::precision_double_, Multigrille_base::precision_float_, and Multigrille_base::solver_precision_.
reset_rho()
void Multigrille_Adrien::reset_rho ()
set_inv_rho()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_Adrien::set_inv_rho (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & inv_rho)
References Multigrille_base::precision_double_, Multigrille_base::precision_float_, and Multigrille_base::solver_precision_.
set_inv_rho_template()
template<typename _TYPE_FUNC_ , typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_Adrien::set_inv_rho_template (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & rho, bool set_coarse_matrix_flag, bool use_coeffs_from_double)
References Matrice_Grossiere::build_matrix(), Multigrille_base::set_coarse_matrix(), and TRUST_Vector< _CLASSE_ >::size().
prepare_secmem() [1/2]
void Multigrille_Adrien::prepare_secmem (IJK_Field_float & x) const inline override virtual
Implements Multigrille_base.
prepare_secmem() [2/2]
void Multigrille_Adrien::prepare_secmem (IJK_Field_double & x) const inline override virtual
Implements Multigrille_base.
alloc_field() [1/2]
void Multigrille_Adrien::alloc_field (IJK_Field_float & x, int level, bool with_additional_k_layers = false) const inline override virtual
Implements Multigrille_base.
alloc_field() [2/2]
void Multigrille_Adrien::alloc_field (IJK_Field_double & x, int level, bool with_additional_k_layers = false) const inline override virtual
Implements Multigrille_base.
dump_lata() [1/2]
void Multigrille_Adrien::dump_lata (const Nom & field, const IJK_Field_float & data, int tstep) const inline override virtual
Implements Multigrille_base.
dump_lata() [2/2]
void Multigrille_Adrien::dump_lata (const Nom & field, const IJK_Field_double & data, int tstep) const inline override virtual
Implements Multigrille_base.
ajouter_param()
void Multigrille_Adrien::ajouter_param (Param & param) override protected virtual
Reimplemented from Multigrille_base.
References Param::ajouter(), and Multigrille_base::ajouter_param().
needed_kshift_for_jacobi()
int Multigrille_Adrien::needed_kshift_for_jacobi (int level) const override protected virtual
Implements Multigrille_base.
References Multigrille_base::nsweeps_jacobi_residu().
completer_template()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_Adrien::completer_template (const Domaine_IJK & split) protected
References TRUST_Vector< _CLASSE_ >::dimensionner(), Process::Journal(), and Multigrille_base::nsweeps_jacobi_residu().
setup_coarse_grid()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_Adrien::setup_coarse_grid (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & fine, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & coarse) const protected
compute_coefficients()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_Adrien::compute_coefficients (IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & coeffs_faces, const int grid_level) const protected
set_rho_template()
template<typename _TYPE_FUNC_ , typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_Adrien::set_rho_template (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & rho, bool set_coarse_matrix, bool use_coeffs_from_double) protected
References Matrice_Grossiere::build_matrix(), Multigrille_base::set_coarse_matrix(), and TRUST_Vector< _CLASSE_ >::size().
completer_double_for_residue()
void Multigrille_Adrien::completer_double_for_residue (const Domaine_IJK & splitting) protected
References TRUST_Vector< _CLASSE_ >::dimensionner(), and Multigrille_base::nsweeps_jacobi_residu().
Referenced by initialize().
jacobi_residu() [1/2]
void Multigrille_Adrien::jacobi_residu (IJK_Field_float & x, const IJK_Field_float * secmem, const int grid_level, const int n_jacobi, IJK_Field_float * residu) const inline override protected virtual
Implements Multigrille_base.
Referenced by multigrille_failure().
jacobi_residu() [2/2]
void Multigrille_Adrien::jacobi_residu (IJK_Field_double & x, const IJK_Field_double * secmem, const int grid_level, const int n_jacobi, IJK_Field_double * residu) const inline override protected virtual
Implements Multigrille_base.
coarsen() [1/2]
void Multigrille_Adrien::coarsen (const IJK_Field_float & fine, IJK_Field_float & coarse, int fine_level) const inline override protected virtual
Implements Multigrille_base.
coarsen() [2/2]
void Multigrille_Adrien::coarsen (const IJK_Field_double & fine, IJK_Field_double & coarse, int fine_level) const inline override protected virtual
Implements Multigrille_base.
interpolate_sub_shiftk() [1/2]
void Multigrille_Adrien::interpolate_sub_shiftk (const IJK_Field_float & coarse, IJK_Field_float & fine, int fine_level) const inline override protected virtual
Implements Multigrille_base.
interpolate_sub_shiftk() [2/2]
void Multigrille_Adrien::interpolate_sub_shiftk (const IJK_Field_double & coarse, IJK_Field_double & fine, int fine_level) const inline override protected virtual
Implements Multigrille_base.
get_storage_float()
IJK_Field_float & Multigrille_Adrien::get_storage_float (StorageId si, int level) inline override protected virtual
Implements Multigrille_base.
get_storage_double()
IJK_Field_double & Multigrille_Adrien::get_storage_double (StorageId si, int level) inline override protected virtual
Implements Multigrille_base.
Referenced by multigrille_failure().
multigrille_failure()
double Multigrille_Adrien::multigrille_failure () override protected virtual
Implements Multigrille_base.
References Matrice_Grossiere::build_matrix(), Multigrille_base::coarse_solver(), get_storage_double(), jacobi_residu(), Multigrille_base::set_coarse_matrix(), Multigrille_base::STORAGE_RESIDUE, Multigrille_base::STORAGE_RHS, and Multigrille_base::STORAGE_X.