CEA TRUST Platform: SolveurSys Class Reference
SolveurSys Class Reference
#include <SolveurSys.h>
Detailed Description
derivee de la classe SolveurSys_base
See also
Jacobi Gauss_Seidel SOR SolveurSys_base
Member Function Documentation
resoudre_systeme()
int SolveurSys::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution)
References Statistiques::begin_count(), Statistiques::end_count(), Statistiques::last_time(), and le_nom().
Referenced by Multigrille_base::coarse_solver(), Navier_Stokes_std::corriger_derivee_impl(), Equation_base::derivee_en_temps_inco(), Champ_P1NC_implementation::filtrer_resu(), Solveur_Lineaire_Std::iterer_eqn(), Simple::iterer_eqn(), Simple::iterer_eqs(), SETS::iterer_NS(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), Solveur_U_P::iterer_NS(), Precond_local::precond(), PrecondSolv::preconditionner_(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), Solv_Optimal::resoudre_systeme(), SolveurPP1B::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), Solv_Optimal::resoudre_systeme(), and Navier_Stokes_std::uzawa().
le_nom()
const Nom & SolveurSys::le_nom () const inline override
Referenced by resoudre_systeme().
nommer()
void SolveurSys::nommer (const Nom & nom) inline override
Referenced by Op_Dift_VEF_P1NCP1B_Face::associer(), Champ_P1NC_implementation::Champ_P1NC_implementation(), Solv_GCP_NS::lire_motcle_non_standard(), Parametre_diffusion_implicite::lire_motcle_non_standard(), Solveur_Lineaire_Std::lire_motcle_non_standard(), Navier_Stokes_std::lire_motcle_non_standard(), and Navier_Stokes_std::uzawa().