CEA TRUST Platform: Champ_Face_VDF Class Reference
Champ_Face_VDF Class Reference
#include <Champ_Face_VDF.h>
Public Member Functions
DoubleTab & calcul_duidxj (const DoubleTab &, DoubleTab &) const
DoubleTab & calcul_duidxj (const DoubleTab &, DoubleTab &, const Domaine_Cl_VDF &) const
DoubleVect & calcul_S_barre_sans_contrib_paroi (const DoubleTab &, DoubleVect &, const Domaine_Cl_VDF &) const
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &tab_valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
que les composantes normales aux faces en VDF.Il n'y a donc qu'un degre de liberte par face et l'attribut nb_comp_ d'un objet de type Champ_Face vaut 1. On peut neammoins imposer toutes les composantes du champ sur le bord. Si n est le nombre de faces total du domaine et nb_faces_bord le nombre de faces de bord le tableau de valeurs associe au champ est construit comme suit:
n valeurs pour representer les composantes normales aux faces
nb_faces_bord*dimension pour stocker les valeurs imposees sur les faces de bord Rq : cette classe est specifique au module VDF
See also
Champ_Inc_base
Member Function Documentation
fixer_nb_valeurs_nodales()
int Champ_Face_VDF::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Reimplemented from Champ_base.
References Champ_Inc_base::creer_tableau_distribue(), Objet_U::dimension, domaine_vdf(), Domaine_VF::md_vector_faces(), and Field_base::nb_compo_.
Referenced by EOS_Tools_VDF::associer_domaines().
domaine_vdf()
const Domaine_VDF & Champ_Face_VDF::domaine_vdf () const inline override virtual
Implements Champ_Face_VDF_implementation.
Referenced by affecter(), affecter(), affecter(), affecter_(), calcul_critere_Q(), calcul_duidxj(), calcul_duidxj(), calcul_grad_u(), calcul_S_barre(), calcul_S_barre_sans_contrib_paroi(), calcul_y_plus(), calculer_dercov_axi(), calculer_dscald_centre_element(), calculer_rotationnel_ordre2_centre_element(), compo_normale_sortante(), dimensionner_tenseur_Grad(), fixer_nb_valeurs_nodales(), Domaine_Cl_VDF::imposer_cond_lim(), and v_norm().
affecter_()
Champ_base & Champ_Face_VDF::affecter_ (const Champ_base & ch) override virtual
Implements Champ_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_vdf(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Domaine_VDF::orientation(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_base::valeur_aux(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Domaine_VF::xv().
affecter() [1/3]
const Champ_Proto & Champ_Face_VDF::affecter (const double x1, const double x2) virtual
References domaine_vdf(), Domaine_VDF::orientation(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Inc_base::valeurs().
affecter() [2/3]
const Champ_Proto & Champ_Face_VDF::affecter (const double x1, const double x2, const double x3) virtual
References domaine_vdf(), Domaine_VDF::orientation(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Inc_base::valeurs().
affecter() [3/3]
const Champ_Proto & Champ_Face_VDF::affecter (const DoubleTab & v) virtual
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_vdf(), Process::exit(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VDF::orientation(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Inc_base::valeurs().
verifie_valeurs_cl()
void Champ_Face_VDF::verifie_valeurs_cl () override virtual
Reimplemented from Champ_Inc_base.
References Champ_Inc_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Periodique::face_associee(), Cond_lim_base::frontiere_dis(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Champ_Inc_base::valeurs().
compo_normale_sortante()
int Champ_Face_VDF::compo_normale_sortante (int num_face) const
References domaine_vdf(), and Champ_Inc_base::valeurs().
tau_diag() [1/2]
const DoubleTab & Champ_Face_VDF::tau_diag () const inline
tau_croises() [1/2]
const DoubleTab & Champ_Face_VDF::tau_croises () const inline
tau_diag() [2/2]
DoubleTab & Champ_Face_VDF::tau_diag () inline
tau_croises() [2/2]
DoubleTab & Champ_Face_VDF::tau_croises () inline
dimensionner_tenseur_Grad()
void Champ_Face_VDF::dimensionner_tenseur_Grad ()
References Objet_U::dimension, domaine_vdf(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Op_Dift_VDF_Face_Axi_base::completer().
calculer_rotationnel_ordre2_centre_element()
void Champ_Face_VDF::calculer_rotationnel_ordre2_centre_element (DoubleTab & rot) const
References Objet_U::dimension, domaine_vdf(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Domaine_dis_base::nb_elem(), and Champ_Inc_base::valeurs().
Referenced by Rotationnel_Champ_Face::me_calculer().
imprime()
int Champ_Face_VDF::imprime (Sortie & os, int ncomp) const override virtual
Implements Champ_base.
References Champ_Face_VDF_implementation::imprime_Face().
trace()
DoubleTab & Champ_Face_VDF::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
Calcule la trace d'un champ sur une frontiere au temps tps.
WEC : La frontiere passee en parametre doit faire partie du domaine sur lequel s'appuie le champ Le resultat est calcule sur cette frontiere et la taille du DoubleTab x correspond au nombre de faces de la frontiere. x peut avoir un espace virtuel, la fonction trace apelle echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF : Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Parameters
(Frontiere_dis_base&) frontiere discretisee sur laquelle on veut calculer la trace du champ au temps tps
(DoubleTab& x , double tps) les valeurs du champ sur la frontiere au temps tps
Returns
(DoubleTab&) les valeurs du champ sur la frontiere au temps tps
Reimplemented from Champ_base.
References Champ_Face_VDF_implementation::trace(), and Champ_Inc_base::valeurs().
mettre_a_jour()
void Champ_Face_VDF::mettre_a_jour (double) override virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented from Champ_base.
References Champ_Inc_base::mettre_a_jour().
calculer_dscald_centre_element()
void Champ_Face_VDF::calculer_dscald_centre_element (DoubleTab & dscald) const
References Objet_U::dimension, domaine_vdf(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Domaine_dis_base::nb_elem(), and Champ_Inc_base::valeurs().
calcul_critere_Q()
void Champ_Face_VDF::calcul_critere_Q (DoubleTab & Q, const Domaine_Cl_VDF & domaine_Cl_VDF)
References calcul_duidxj(), Objet_U::dimension, domaine_vdf(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Objet_U::que_suis_je(), and Champ_Inc_base::valeurs().
Referenced by Critere_Q_Champ_Face::me_calculer().
calcul_grad_u()
void Champ_Face_VDF::calcul_grad_u (const DoubleTab & vitesse, DoubleTab & grad_u, const Domaine_Cl_VDF & domaine_Cl_VDF)
References calcul_duidxj(), Objet_U::dimension, domaine_vdf(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), and Domaine_dis_base::nb_elem_tot().
Referenced by grad_U_Champ_Face::me_calculer().
calcul_y_plus()
void Champ_Face_VDF::calcul_y_plus (DoubleTab & y_plus, const Domaine_Cl_VDF & domaine_Cl_VDF)
References Objet_U::axi, Objet_U::dimension, Domaine_VDF::dist_norm_bord(), Domaine_VDF::dist_norm_bord_axi(), domaine_vdf(), MorEqn::equation(), Domaine_VF::face_voisins(), Equation_base::get_modele(), Domaine_Cl_dis_base::les_conditions_limites(), Modele_turbulence_hyd_base::loi_paroi(), Equation_base::milieu(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), TRUST_Ref_Objet_U::non_nul(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Turbulence_paroi_base::tab_d_plus(), Turbulence_paroi_base::use_shear(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Fluide_base::viscosite_cinematique().
calcul_y_plus_diphasique()
void Champ_Face_VDF::calcul_y_plus_diphasique (DoubleTab & , const Domaine_Cl_VDF &)
calcul_duidxj() [1/2]
DoubleTab & Champ_Face_VDF::calcul_duidxj (const DoubleTab & in_vel, DoubleTab & gij) const
Methode qui renvoie gij aux elements a partir de la vitesse aux elements (gij represente la derivee partielle dui/dxj)
A partir de gij, on peut calculer Sij = 0.5(gij(i,j)+gij(j,i))
References Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vdf(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Domaine_32_64< _SIZE_ >::nb_elem_tot().
Referenced by calcul_critere_Q(), calcul_grad_u(), calcul_S_barre(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_S_barre(), and Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_Sij2().
calcul_duidxj() [2/2]
DoubleTab & Champ_Face_VDF::calcul_duidxj (const DoubleTab & vitesse, DoubleTab & gij, const Domaine_Cl_VDF & domaine_Cl_VDF) const
Methode qui renvoie gij aux elements a partir de la vitesse aux faces (gij represente la derivee partielle dui/dxj)
A partir de gij, on peut calculer Sij = 0.5(gij(i,j)+gij(j,i))
References Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_VDF::dist_face(), Domaine_VDF::dist_face_period(), Domaine_VDF::dist_norm_bord(), Domaine_dis_base::domaine(), Champ_Inc_base::domaine_Cl_dis(), domaine_vdf(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_VDF::nb_aretes_bord(), Domaine_VDF::nb_aretes_coin(), Domaine_VDF::nb_aretes_internes(), Domaine_VDF::nb_aretes_mixtes(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_VDF::orientation(), Domaine_VDF::premiere_arete_bord(), Domaine_VDF::premiere_arete_coin(), Domaine_VDF::premiere_arete_interne(), Domaine_VDF::premiere_arete_mixte(), Domaine_VDF::Qdm(), Option_VDF::traitement_coins, Option_VDF::traitement_gradients, Domaine_Cl_VDF::type_arete_bord(), and Domaine_Cl_VDF::type_arete_coin().
calcul_S_barre()
DoubleVect & Champ_Face_VDF::calcul_S_barre (const DoubleTab & vitesse, DoubleVect & SMA_barre, const Domaine_Cl_VDF & domaine_Cl_VDF) const
References calcul_duidxj(), Objet_U::dimension, domaine_vdf(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), and Domaine_dis_base::nb_elem_tot().
calcul_S_barre_sans_contrib_paroi()
DoubleVect & Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi (const DoubleTab & vitesse, DoubleVect & SMA_barre, const Domaine_Cl_VDF & domaine_Cl_VDF) const
Methode qui renvoie SMA_barre aux elements a partir de la vitesse aux faces.
SMA_barre = Sij*Sij (sommation sur les indices i et j)
On calcule directement S_barre(num_elem)!!!!!!!!!! Le parametre contribution_paroi (ici fixe a 0) permet de ne pas prendre en compte la contribution de la paroi au produit SMA_barre = Sij*Sij
References Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_VDF::dist_face_period(), Domaine_VDF::dist_norm_bord(), Domaine_dis_base::domaine(), domaine_vdf(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Domaine_VDF::nb_aretes_bord(), Domaine_VDF::nb_aretes_coin(), Domaine_VDF::nb_aretes_internes(), Domaine_VDF::nb_aretes_mixtes(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VDF::orientation(), Domaine_VDF::premiere_arete_bord(), Domaine_VDF::premiere_arete_coin(), Domaine_VDF::premiere_arete_interne(), Domaine_VDF::premiere_arete_mixte(), Domaine_VDF::Qdm(), Option_VDF::traitement_coins, Option_VDF::traitement_gradients, Domaine_Cl_VDF::type_arete_bord(), and Domaine_Cl_VDF::type_arete_coin().
calculer_dercov_axi()
void Champ_Face_VDF::calculer_dercov_axi (const Domaine_Cl_VDF & domaine_Cl_VDF)
References Objet_U::dimension, domaine_vdf(), Domaine_VF::elem_faces(), Process::exit(), TypeAreteBordVDF::FLUIDE_FLUIDE, Domaine_VDF::nb_aretes(), Domaine_VDF::nb_aretes_bord(), Domaine_dis_base::nb_elem(), Domaine_VDF::orientation(), TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, Domaine_VDF::premiere_arete_bord(), Domaine_VDF::premiere_arete_mixte(), Domaine_VF::premiere_face_bord(), Domaine_VDF::Qdm(), Domaine_Cl_VDF::type_arete_bord(), Champ_Inc_base::valeurs(), Domaine_VF::xp(), and Domaine_VF::xv().
valeur_a_elem()
DoubleVect & Champ_Face_VDF::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
References Champ_Face_VDF_implementation::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Face_VDF::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
References Champ_Face_VDF_implementation::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_Face_VDF::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References Champ_Face_VDF_implementation::valeur_aux_elems().
valeur_aux_elems_passe()
DoubleTab & Champ_Face_VDF::valeur_aux_elems_passe (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) const inline override virtual
Implements Champ_Face_base.
References Champ_Face_VDF_implementation::valeur_aux_elems_passe().
valeur_aux_elems_compo()
DoubleVect & Champ_Face_VDF::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_base.
References Champ_Face_VDF_implementation::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Face_VDF::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
References Champ_Face_VDF_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Face_VDF::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const inline override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
References Champ_Face_VDF_implementation::valeur_aux_sommets_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Face_VDF::remplir_coord_noeuds (DoubleTab & positions) const inline override virtual
Implements Champ_Inc_base.
References Champ_Face_VDF_implementation::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Face_VDF::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN Methode a surcharger.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented from Champ_Inc_base.
References Champ_Face_VDF_implementation::remplir_coord_noeuds_et_polys().
v_norm()
double Champ_Face_VDF::v_norm (const DoubleTab & val, const DoubleTab & val_f, int e, int f, int k, int l, double * v_ext, double * dnv) const inline
References Objet_U::dimension, Champ_Inc_base::domaine(), domaine_vdf(), and TRUSTVect< _TYPE_, _SIZE_ >::line_size().
Referenced by Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), and Portance_interfaciale_VDF::ajouter_blocs().