CEA TRUST Platform: Sous_Domaine_32_64< _SIZE_ > Class Template Reference
Sous_Domaine_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void add_elem (const int_t poly)
int associer_ (Objet_U &) override
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Sous_Domaine_32_64< _SIZE_ >
It bears a reference to the Domaine it subdivides
See also
Domaine Sous_Domaines
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntVect_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
ArrOfDouble_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::ArrOfDouble_t = ArrOfDouble_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
DoubleTabs_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::DoubleTabs_t = DoubleTabs_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Sous_Domaine_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Member Function Documentation
lire_motcle_non_standard()
template<typename _SIZE_ > int Sous_Domaine_32_64< _SIZE_ >::lire_motcle_non_standard (const Motcle & motlu, Entree & is) inline override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
le_nom()
template<typename _SIZE_ > const Nom& Sous_Domaine_32_64< _SIZE_ >::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
References Sous_Domaine_32_64< _SIZE_ >::nom_.
Referenced by Partitionneur_Sous_Domaines::construire_partition(), Postraiter_domaine::ecrire(), and Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine().
operator()()
template<typename _SIZE_ > int_t Sous_Domaine_32_64< _SIZE_ >::operator() (int_t i) const inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_.
operator[]()
template<typename _SIZE_ > int_t Sous_Domaine_32_64< _SIZE_ >::operator[] (int_t i) const inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_.
nb_elem_tot()
template<typename _SIZE_ > int_t Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot () const inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Refine_Mesh::build_new_sub_domaines_descriptions(), TRUSTChamp_Morceaux_generique< _TYPE_ >::complete_readOn(), Partitionneur_Sous_Domaines::construire_partition(), Partitionneur_Union::construire_partition(), Perte_Charge_PolyMAC::contribuer_a_avec(), Postraiter_domaine::ecrire(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_val_tot_sur_vol_base::evaluer(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Create_domain_from_sub_domain::interpreter_(), Extraire_domaine::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine(), Porosites::remplir_champ(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), and Champ_input_P0::setValue().
associer_domaine()
template<typename _SIZE_ > void Sous_Domaine_32_64< _SIZE_ >::associer_domaine (const Domaine_t & d) inline
associer_()
template<typename _SIZE_ > int Sous_Domaine_32_64< _SIZE_ >::associer_ (Objet_U & ob) override virtual
Associe un Objet_U au sous-domaine.
On controle le type de l'objet a associer dynamiquement.
Parameters
(Objet_U& ob) objet a associer au sous-domaine.
Returns
(int) renvoie 1 si l'association a reussi 0 sinon.
Reimplemented from Objet_U.
References Objet_U::associer_().
nommer()
template<typename _SIZE_ > void Sous_Domaine_32_64< _SIZE_ >::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References Sous_Domaine_32_64< _SIZE_ >::nom_.
add_elem()
template<typename _SIZE_ > void Sous_Domaine_32_64< _SIZE_ >::add_elem (const int_t poly)
Ajoute un polyedre au sous-domaine.
Returns
(int)
Referenced by Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine().
les_elems() [1/2]
template<typename _SIZE_ > const IntVect_t& Sous_Domaine_32_64< _SIZE_ >::les_elems () const inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_.
les_elems() [2/2]
template<typename _SIZE_ > IntVect_t& Sous_Domaine_32_64< _SIZE_ >::les_elems () inline
References Sous_Domaine_32_64< _SIZE_ >::les_elems_.
domaine() [1/2]
template<typename _SIZE_ > Domaine_t& Sous_Domaine_32_64< _SIZE_ >::domaine () inline
Referenced by Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Domaine_dis_base::discretiser_root(), and Postraitement::lire_motcle_non_standard().
domaine() [2/2]
template<typename _SIZE_ > const Domaine_t& Sous_Domaine_32_64< _SIZE_ >::domaine () const inline
OBS_PTR()
template<typename _SIZE_ > Sous_Domaine_32_64< _SIZE_ >::OBS_PTR (Domaine_t) protected
Member Data Documentation
les_elems_
template<typename _SIZE_ > IntVect_t Sous_Domaine_32_64< _SIZE_ >::les_elems_ protected
Referenced by Sous_Domaine_32_64< _SIZE_ >::les_elems(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Sous_Domaine_32_64< _SIZE_ >::operator()(), and Sous_Domaine_32_64< _SIZE_ >::operator[]().
nom_
template<typename _SIZE_ > Nom Sous_Domaine_32_64< _SIZE_ >::nom_ protected
Referenced by Sous_Domaine_32_64< _SIZE_ >::le_nom(), and Sous_Domaine_32_64< _SIZE_ >::nommer().