CEA TRUST Platform: Polyedre_32_64< _SIZE_ > Class Template Reference
Polyedre_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void calculer_centres_gravite (DoubleTab_t &xp) const override
void calculer_volumes (DoubleVect_t &vols) const override
int contient (const ArrOfDouble &pos, int_t elem) const override
int contient (const SmallArrOfTID_t &soms, int_t elem) const override
int face_sommet (int i, int j) const override
int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const override
int nb_faces (int=0) const override
int nb_som () const override
int nb_som_face (int=0) const override
const Nom & nom_lml () const override
Type_Face type_face (int=0) const override
Public Member Functions inherited from Poly_geom_base_32_64< _SIZE_ >
int nb_type_face () const override
Public Member Functions inherited from Elem_geom_base_32_64< _SIZE_ >
virtual void calculer_normales (const IntTab_t &faces_sommets, DoubleTab_t &face_normales) const
void creer_faces_elem (Faces_t &, int_t) const
virtual void creer_faces_elem (Faces_t &, int_t, Type_Face) const
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
virtual int num_face (int face, Type_Face &type) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Attributes inherited from Poly_geom_base_32_64< _SIZE_ >
ArrOfInt_t FacesIndex_
Detailed Description
template<typename _SIZE_>
class Polyedre_32_64< _SIZE_ >
Un polyedre est un element defini par ses faces de type Type_Face::polygone_3D
See also
Poly_geom_base Elem_geom
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Polyedre_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Polyedre_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
BigArrOfInt_t
template<typename _SIZE_ > using Polyedre_32_64< _SIZE_ >::BigArrOfInt_t = TRUSTArray<int, _SIZE_>
IntTab_t
template<typename _SIZE_ > using Polyedre_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Polyedre_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Polyedre_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Polyedre_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Polyedre_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Constructor & Destructor Documentation
Polyedre_32_64()
template<typename _SIZE_ > template<typename _SIZE_ > Polyedre_32_64< _SIZE_ >::Polyedre_32_64 ()
References Poly_geom_base_32_64< _SIZE_ >::FacesIndex_, Poly_geom_base_32_64< _SIZE_ >::nb_face_elem_max_, Poly_geom_base_32_64< _SIZE_ >::nb_som_elem_max_, Polyedre_32_64< _SIZE_ >::nb_som_face_max_, Polyedre_32_64< _SIZE_ >::PolyhedronIndex_, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Member Function Documentation
calculer_un_centre_gravite()
template<typename _SIZE_ > void Polyedre_32_64< _SIZE_ >::calculer_un_centre_gravite (const int_t elem, DoubleVect & xp) const override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
References Domaine_32_64< _SIZE_ >::coord(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
face_sommet()
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::face_sommet (int face, int sommet) const inline override virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de l'element.
Parameters
(int i) un numero de face
(int j) un numero de sommet
Returns
(int) le numero du j-ieme sommet de la i-ieme face
Implements Elem_geom_base_32_64< _SIZE_ >.
nb_som()
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::nb_som inline override virtual
Renvoie le nombre de sommets d'un Polyedre.
Returns
(int) le nombre de sommets maximum d'un polyedre
Implements Elem_geom_base_32_64< _SIZE_ >.
References Poly_geom_base_32_64< _SIZE_ >::get_nb_som_elem_max().
nb_faces()
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::nb_faces (int i = 0) const inline override virtual
Renvoie le nombre de faces du type specifie que possede l'element geometrique.
Un Polyedre a 1 type de faces: polygon_3D
Parameters
(int i) le type de face
Implements Elem_geom_base_32_64< _SIZE_ >.
References Process::exit(), and Poly_geom_base_32_64< _SIZE_ >::get_nb_face_elem_max().
nb_som_face()
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::nb_som_face (int i = 0) const inline override virtual
Renvoie le nombre maximum de sommets des faces du type specifie.
Parameters
(int i) le type de face
Returns
(int) le nombre de sommets des faces de type i
Implements Elem_geom_base_32_64< _SIZE_ >.
References Polyedre_32_64< _SIZE_ >::get_nb_som_face_max().
nom_lml()
template<typename _SIZE_ > const Nom & Polyedre_32_64< _SIZE_ >::nom_lml override virtual
Renvoie le nom LML d'un polyedre = "POLYEDRE_"+nb_som_max.
Returns
(Nom&) toujours egal a "PRISM6"
Implements Elem_geom_base_32_64< _SIZE_ >.
contient() [1/2]
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::contient (const ArrOfDouble & pos, int_t num_poly) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0.
Renvoie 1 si l'element "element" du domaine associe a l'element geometrique contient le point de coordonnees specifiees par le parametre "pos". Renvoie 0 sinon.
Parameters
(DoubleVect& pos) coordonnees du point que l'on cherche a localiser
(int element) le numero de l'element du domaine dans lequel on cherche le point.
Returns
(int) 1 si le point de coordonnees specifiees appartient a l'element "element" 0 sinon
Implements Elem_geom_base_32_64< _SIZE_ >.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Objet_U::precision_geom, Vecteur3::produit_scalaire(), and Vecteur3::produit_vectoriel().
contient() [2/2]
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::contient (const SmallArrOfTID_t & pos, int_t num_poly) const override virtual
NE FAIT RIEN: A CODER, renvoie toujours 0 Renvoie 1 si les sommets specifies par le parametre "pos".
sont les sommets de l'element "element" du domaine associe a l'element geometrique.
Parameters
(IntVect& pos) les numeros des sommets a comparer avec ceux de l'elements "element"
(int element) le numero de l'element du domaine dont on veut comparer les sommets
Returns
(int) 1 si les sommets passes en parametre sont ceux de l'element specifie, 0 sinon
Implements Elem_geom_base_32_64< _SIZE_ >.
type_face()
template<typename _SIZE_ > Type_Face Polyedre_32_64< _SIZE_ >::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un polyedre a 2 types de face: quadrangle et triangle
Parameters
(int i) le rang du type de face a renvoyer
Returns
(Type_Face) le type de la face i
Implements Elem_geom_base_32_64< _SIZE_ >.
calculer_volumes()
template<typename _SIZE_ > void Polyedre_32_64< _SIZE_ >::calculer_volumes (DoubleVect_t & volumes) const override virtual
NE FAIT RIEN: A CODER Calcule les volumes des elements du domaine associe.
Parameters
(DoubleVect& volumes) le vecteur contenant les valeurs des des volumes des elements du domaine
Implements Elem_geom_base_32_64< _SIZE_ >.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), and TRUSTVect< _TYPE_, _SIZE_ >::size_totale().
calculer_centres_gravite()
template<typename _SIZE_ > void Polyedre_32_64< _SIZE_ >::calculer_centres_gravite (DoubleTab_t & tab_xp) const override virtual
Compute all centers of mass of all elements in the domain.
Calcule les centres de gravites de tous les elements du domaine associe a l'element goemetrique.
Parameters
(DoubleTab& xp) le tableau contenant les coordonnees des centres de gravite
Reimplemented from Elem_geom_base_32_64< _SIZE_ >.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
get_tab_faces_sommets_locaux() [1/2]
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const override virtual
remplit le tableau faces_som_local(i,j)
Celui-ci donne pour 0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet sur l'element.
On a 0 <= faces_sommets_locaux(i,j) < nb_som()
Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees du tableau sont mises a -1 On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
Implements Poly_geom_base_32_64< _SIZE_ >.
get_tab_faces_sommets_locaux() [2/2]
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::get_tab_faces_sommets_locaux (IntTab & faces_som_local, int_t elem) const override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
References TRUSTTab< _TYPE_, _SIZE_ >::resize().
affecte_connectivite_numero_global()
template<typename _SIZE_ > void Polyedre_32_64< _SIZE_ >::affecte_connectivite_numero_global (const ArrOfInt_t & Nodes, const ArrOfInt_t & FacesIndex, const ArrOfInt_t & PolyhedronIndex, IntTab_t & les_elems)
References TRUSTList< _TYPE_ >::add_if_not(), Process::mp_max(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTList< _TYPE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUSTList< _TYPE_ >::vide().
Referenced by Polyedriser_32_64< _SIZE_ >::polyedriser().
get_nb_som_face_max()
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::get_nb_som_face_max () const inline
References Polyedre_32_64< _SIZE_ >::nb_som_face_max_.
Referenced by Polyedre_32_64< _SIZE_ >::nb_som_face().
set_nb_som_face_max()
template<typename _SIZE_ > void Polyedre_32_64< _SIZE_ >::set_nb_som_face_max (int s) inline
References Polyedre_32_64< _SIZE_ >::nb_som_face_max_.
get_somme_nb_faces_elem()
template<typename _SIZE_ > Polyedre_32_64< _SIZE_ >::int_t Polyedre_32_64< _SIZE_ >::get_somme_nb_faces_elem override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
getNodes()
template<typename _SIZE_ > const BigArrOfInt_t& Polyedre_32_64< _SIZE_ >::getNodes () const inline
References Polyedre_32_64< _SIZE_ >::Nodes_.
getsetNodes()
template<typename _SIZE_ > BigArrOfInt_t& Polyedre_32_64< _SIZE_ >::getsetNodes () inline
References Polyedre_32_64< _SIZE_ >::Nodes_.
getPolyhedronIndex()
template<typename _SIZE_ > const ArrOfInt_t& Polyedre_32_64< _SIZE_ >::getPolyhedronIndex () const inline
References Polyedre_32_64< _SIZE_ >::PolyhedronIndex_.
Referenced by Domaine_32_64< _SIZE_ >::build_mc_mesh().
getsetPolyhedronIndex()
template<typename _SIZE_ > ArrOfInt_t& Polyedre_32_64< _SIZE_ >::getsetPolyhedronIndex () inline
References Polyedre_32_64< _SIZE_ >::PolyhedronIndex_.
getElemIndex()
template<typename _SIZE_ > const ArrOfInt_t& Polyedre_32_64< _SIZE_ >::getElemIndex () const inline override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
References Polyedre_32_64< _SIZE_ >::PolyhedronIndex_.
remplir_Nodes_glob()
template<typename _SIZE_ > void Polyedre_32_64< _SIZE_ >::remplir_Nodes_glob (ArrOfInt_t & Nodes_glob, const IntTab_t & les_elems) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Domaine_32_64< _SIZE_ >::build_mc_mesh().
ajouter_elements()
template<typename _SIZE_ > void Polyedre_32_64< _SIZE_ >::ajouter_elements (const Elem_geom_base_32_64< _SIZE_ > & new_elem, const IntTab_t & new_elems, IntTab_t & les_elems)
on va ajouter les elements de type new_elem aux elements deja presents dans les_elems et dans new_elems
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
build_reduced()
template<typename _SIZE_ > void Polyedre_32_64< _SIZE_ >::build_reduced (OWN_PTR(Elem_geom_base_32_64< int >)& type_elem, const ArrOfInt_t & elems_sous_part) const override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Poly_geom_base_32_64< _SIZE_ >::FacesIndex_, Poly_geom_base_32_64< _SIZE_ >::nb_face_elem_max_, Poly_geom_base_32_64< _SIZE_ >::nb_som_elem_max_, Polyedre_32_64< _SIZE_ >::nb_som_face_max_, Polyedre_32_64< _SIZE_ >::Nodes_, Polyedre_32_64< _SIZE_ >::PolyhedronIndex_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
getFacesIndex()
template<typename _SIZE_ > const ArrOfInt_t& Polyedre_32_64< _SIZE_ >::getFacesIndex () const inline
References Poly_geom_base_32_64< _SIZE_ >::FacesIndex_.
Referenced by Domaine_32_64< _SIZE_ >::build_mc_mesh().
compute_virtual_index()
template<typename _SIZE_ > void Polyedre_32_64< _SIZE_ >::compute_virtual_index override virtual
Implements Poly_geom_base_32_64< _SIZE_ >.
Friends And Related Function Documentation
Polyedre_32_64
template<typename _SIZE_ > template<class T > friend class Polyedre_32_64 friend
Member Data Documentation
PolyhedronIndex_
template<typename _SIZE_ > ArrOfInt_t Polyedre_32_64< _SIZE_ >::PolyhedronIndex_ protected
PolyhedronIndex_[ele] gives the index of the first face of the polyedron 'ele' in FaceIndex_ (see base class)
Referenced by Polyedre_32_64< _SIZE_ >::build_reduced(), Polyedre_32_64< _SIZE_ >::getElemIndex(), Polyedre_32_64< _SIZE_ >::getPolyhedronIndex(), Polyedre_32_64< _SIZE_ >::getsetPolyhedronIndex(), and Polyedre_32_64< _SIZE_ >::Polyedre_32_64().
Nodes_
template<typename _SIZE_ > BigArrOfInt_t Polyedre_32_64< _SIZE_ >::Nodes_ protected
Nodes_[s] local index (in the reference frame of an element) of the vertex of a given face, where as elem(ele,s) will give the global index.
Referenced by Polyedre_32_64< _SIZE_ >::build_reduced(), Polyedre_32_64< _SIZE_ >::getNodes(), and Polyedre_32_64< _SIZE_ >::getsetNodes().
nb_som_face_max_
template<typename _SIZE_ > int Polyedre_32_64< _SIZE_ >::nb_som_face_max_ protected
Referenced by Polyedre_32_64< _SIZE_ >::build_reduced(), Polyedre_32_64< _SIZE_ >::get_nb_som_face_max(), Polyedre_32_64< _SIZE_ >::Polyedre_32_64(), and Polyedre_32_64< _SIZE_ >::set_nb_som_face_max().
dimension
template<typename _SIZE_ > int Objet_U::dimension static protected