CEA TRUST Platform: ParserView Class Reference
ParserView Class Reference
Public Member Functions
KOKKOS_INLINE_FUNCTION int acquire () const
ParserView ()
void parseString () override
Public Member Functions inherited from Parser
void addVar (const char *)
double eval ()
Parser ()
Parser (std::string &, int n=1)
void setImpulsion (double tinit, double periode)
virtual void setNbVar (int nvar)
void setVar (const char *sv, double val)
void setVar (const std::string &v, double val)
void setVar (int i, double val)
Constructor & Destructor Documentation
ParserView() [1/3]
ParserView::ParserView () inline
Constructors (generally by copy of a ParserU) See an example here: Champ_Generique_Transformation::get_champ()
ParserView() [2/3]
ParserView::ParserView (Parser_U & p) inline
ParserView() [3/3]
ParserView::ParserView (std::string & expr, int nvar) inline
Member Function Documentation
set()
void ParserView::set (Parser_U & p) inline
References Parser_U::getParser(), and Parser::set().
parseString()
void ParserView::parseString () inline override virtual
Parse string
Reimplemented from Parser.
References Parser::getNbVar(), Parser::parseString(), and Parser::PNodes.
Referenced by Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Extraire_surface::extraire_surface_without_cleaning(), Champ_Generique_Transformation::get_champ(), Extraire_domaine::interpreter_(), and Champ_Fonc_Tabule_P0_VEF::mettre_a_jour().
setVar()
KOKKOS_INLINE_FUNCTION void ParserView::setVar (int i, double val, int threadId) const inline
References Parser::ivar.
Referenced by Extraire_surface::extraire_surface_without_cleaning(), Champ_Generique_Transformation::get_champ(), Extraire_domaine::interpreter_(), and Champ_Fonc_Tabule_P0_VEF::mettre_a_jour().
eval()
KOKKOS_INLINE_FUNCTION double ParserView::eval (int threadId) const inline
References Parser::eval().
Referenced by Extraire_surface::extraire_surface_without_cleaning(), Champ_Generique_Transformation::get_champ(), Extraire_domaine::interpreter_(), and Champ_Fonc_Tabule_P0_VEF::mettre_a_jour().
acquire()
KOKKOS_INLINE_FUNCTION int ParserView::acquire () const inline
Token: get a unic threadId to fill safely les_var_view
Referenced by Extraire_surface::extraire_surface_without_cleaning(), Champ_Generique_Transformation::get_champ(), Extraire_domaine::interpreter_(), and Champ_Fonc_Tabule_P0_VEF::mettre_a_jour().
release()
KOKKOS_INLINE_FUNCTION void ParserView::release (int threadId) const inline
Referenced by Extraire_surface::extraire_surface_without_cleaning(), Champ_Generique_Transformation::get_champ(), Extraire_domaine::interpreter_(), and Champ_Fonc_Tabule_P0_VEF::mettre_a_jour().