CEA TRUST Platform: Champ_front_recyclage Class Reference
Champ_front_recyclage Class Reference
#include <Champ_front_recyclage.h>
Public Member Functions
int initialiser (double temps, const Champ_Inc_base &inco) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Champ_front_var_instationnaire
int avancer (double temps) override
int initialiser (double temps, const Champ_Inc_base &inco) override
int reculer (double temps) override
const DoubleTab & valeurs_au_temps (double temps) const override
DoubleTab & valeurs_au_temps (double temps) override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
                   delt_dist                                             delt_dist
   pb1           <---------->             pb2                            <-------->    pb
                            ch_fr2                                     ch_fr
_____________________         ____________________________               ____________________________
| | | | | | | | | dom1 | | | dom2 | | | dom | | ch1 | | |bord2 | |bord | ch | |_________________|___| |____________________________| |________|__________________| plan1 plan
     Fig. 1                                                        Fig. 2
Cette classe a pour objectif d evaluer les valeurs d un champ_front (ch_fr2) sur le bord d un domaine (bord2) en exploitant les valeurs d un champ 1 (ch1 dit champ evaluateur) evaluees dans un plan (plan1) distant de delt_dist de bord2 (Fig. 1).
Constructor & Destructor Documentation
Champ_front_recyclage()
Champ_front_recyclage::Champ_front_recyclage ()
References ampli_fluct_, ampli_moy_imposee_, ampli_moy_recyclee_, delt_dist, diametre, Objet_U::dimension, fich_impos_, fich_recycl_, methode_moy_impos_, methode_moy_recycl_, ndir, TRUSTVect< _TYPE_, _SIZE_ >::resize(), u_tau, and visco_cin.
Member Function Documentation
lire_info_moyenne_imposee()
int Champ_front_recyclage::lire_info_moyenne_imposee (Entree & is)
References diametre, Process::exit(), fcts_xyz, fich_impos_, fich_maillage_, ndir, Motcles::search(), u_tau, and visco_cin.
Referenced by lire_motcle_non_standard().
lire_info_moyenne_recyclee()
int Champ_front_recyclage::lire_info_moyenne_recyclee (Entree & is)
References Process::exit(), fich_maillage_, fich_recycl_, and Motcles::search().
Referenced by lire_motcle_non_standard().
calcul_moyenne_imposee()
void Champ_front_recyclage::calcul_moyenne_imposee (const DoubleTab & tab, double temps)
References Objet_U::dimension, Frontiere_dis_base::domaine_dis(), Process::exit(), methode_moy_impos_, moyenne_imposee_, Field_base::nb_compo_, Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Domaine_VF::xv().
Referenced by mettre_a_jour().
calcul_moyenne_recyclee()
void Champ_front_recyclage::calcul_moyenne_recyclee (const DoubleTab & tab, double temps)
References Faces_32_64< _SIZE_ >::calculer_surfaces(), Process::exit(), Frontiere_32_64< _SIZE_ >::faces(), Frontiere_dis_base::frontiere(), methode_moy_recycl_, moyenne_recyclee_, Process::mp_sum(), Field_base::nb_compo_, and Front_VF::nb_faces().
Referenced by mettre_a_jour().
initialiser_moyenne_imposee()
void Champ_front_recyclage::initialiser_moyenne_imposee (DoubleTab & moyenne)
References diametre, Objet_U::dimension, Frontiere_dis_base::domaine_dis(), fcts_xyz, fich_impos_, fich_maillage_, lire_fichier_format1(), lire_fichier_format2(), lire_fichier_format3(), methode_moy_impos_, moyenne_imposee_, Field_base::nb_compo_, Front_VF::nb_faces(), ndir, Front_VF::num_premiere_face(), u_tau, visco_cin, and Domaine_VF::xv().
Referenced by initialiser().
initialiser_moyenne_recyclee()
void Champ_front_recyclage::initialiser_moyenne_recyclee (DoubleTab & moyenne)
References fich_maillage_, fich_recycl_, lire_fichier_format1(), lire_fichier_format2(), lire_fichier_format3(), methode_moy_recycl_, and moyenne_recyclee_.
Referenced by initialiser().
associer_champ_evaluateur()
void Champ_front_recyclage::associer_champ_evaluateur (const Nom & un_nom_pb1, const Motcle & un_nom_inco1)
References Process::exit(), Interprete::objet(), and OBS_PTR().
Referenced by initialiser().
initialiser()
int Champ_front_recyclage::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees externes a l'equation (couplage). Si mettre_a_jour le fait, alors initialiser ne doit pas appeler mettre_a_jour.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Ch_front_var_instationnaire_dep.
References ampli_fluct_, ampli_moy_imposee_, ampli_moy_recyclee_, TRUSTArray< _TYPE_, _SIZE_ >::append_array(), associer_champ_evaluateur(), Process::barrier(), Domaine_32_64< _SIZE_ >::construit_octree(), delt_dist, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUST_Vector< _CLASSE_ >::dimensionner(), Process::exit(), Domaine_VF::face_voisins(), Frontiere_dis_base::frontiere(), get_coord_faces(), Domaine_32_64< int >::identifie_item_unique(), inconnues1_coords_to_eval_, inconnues1_elems_, inconnues2_faces_, Ch_front_var_instationnaire_dep::initialiser(), initialiser_moyenne_imposee(), initialiser_moyenne_recyclee(), Process::Journal(), Frontiere_32_64< _SIZE_ >::le_nom(), Process::me(), mettre_a_jour(), moyenne_imposee_, moyenne_recyclee_, Process::mp_or(), Field_base::nb_compo_, Domaine_32_64< _SIZE_ >::nb_elem(), Front_VF::nb_faces(), nom_inco1, nom_pb1, Process::nproc(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_tab(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_VF::xp().
mettre_a_jour()
void Champ_front_recyclage::mettre_a_jour (double temps) override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou sous-pas-de-temps, elle peut eventuellement utiliser des donnees exterieures a l'equation. A charge a l'algorithme de s'assurer que ces donnees sont pertinentes... Calcule la valeur de la condition aux limites au temps demande.
Parameters
(double)
Reimplemented from Champ_front_base.
References ampli_fluct_, ampli_moy_imposee_, ampli_moy_recyclee_, calcul_moyenne_imposee(), calcul_moyenne_recyclee(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), inconnues1_coords_to_eval_, inconnues1_elems_, inconnues2_faces_, TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), moyenne_imposee_, moyenne_recyclee_, Field_base::nb_compo_, Front_VF::nb_faces(), Process::nproc(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUST_Vector< _CLASSE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Champ_front_var_instationnaire::valeurs_au_temps().
Referenced by initialiser().
get_coord_faces()
void Champ_front_recyclage::get_coord_faces (const Frontiere_dis_base & fr_vf, DoubleTab & coords, const DoubleVect & delt_dist) static
References delt_dist, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Frontiere_dis_base::domaine_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::xv().
Referenced by initialiser(), and lire_fichier_format1().
lire_fichier_format1()
void Champ_front_recyclage::lire_fichier_format1 (DoubleTab & moyenne, const Frontiere_dis_base & fr_vf, const Nom & nom_fich)
References delt_dist, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), get_coord_faces(), ndir, and UPb().
Referenced by initialiser_moyenne_imposee(), and initialiser_moyenne_recyclee().
lire_fichier_format2()
void Champ_front_recyclage::lire_fichier_format2 (DoubleTab & moyenne, const Frontiere_dis_base & fr_vf, const Nom & nom_fich)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Entree_Fichier_base::close(), Objet_U::dimension, Frontiere_dis_base::domaine_dis(), Process::exit(), Lec_Diffuse_base::get(), Field_base::nb_compo_, Front_VF::nb_faces(), ndir, Front_VF::num_premiere_face(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_VF::xv().
Referenced by initialiser_moyenne_imposee(), and initialiser_moyenne_recyclee().
lire_fichier_format3()
void Champ_front_recyclage::lire_fichier_format3 (DoubleTab & moyenne, const Frontiere_dis_base & fr_vf, const Nom & nom_fich1, const Nom & nom_fich2)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Entree_Fichier_base::close(), Sortie_Fichier_base::close(), Objet_U::dimension, Frontiere_dis_base::domaine_dis(), Process::exit(), Lec_Diffuse_base::get(), Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), ndir, nom_pb1, Front_VF::num_premiere_face(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_VF::xv().
Referenced by initialiser_moyenne_imposee(), and initialiser_moyenne_recyclee().
UPb()
double Champ_front_recyclage::UPb (double y, Nom nom_fich)
References Entree_Fichier_base::close(), Entree_Fichier_base::eof(), Process::je_suis_maitre(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by lire_fichier_format1().
set_param()
void Champ_front_recyclage::set_param (Param & param) protected
References Param::ajouter(), Param::ajouter_non_std(), ndir, and Param::REQUIRED.
lire_motcle_non_standard()
int Champ_front_recyclage::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References ampli_fluct_, ampli_moy_imposee_, ampli_moy_recyclee_, delt_dist, Field_base::fixer_nb_comp(), lire_info_moyenne_imposee(), lire_info_moyenne_recyclee(), methode_moy_impos_, methode_moy_recycl_, nom_inco1, nom_pb1, and TRUSTVect< _TYPE_, _SIZE_ >::resize().
OBS_PTR()
Champ_front_recyclage::OBS_PTR (Champ_Inc_base) protected
Referenced by associer_champ_evaluateur().
VECT()
Champ_front_recyclage::VECT (Parser_U) protected
Member Data Documentation
delt_dist
DoubleVect Champ_front_recyclage::delt_dist protected
Referenced by Champ_front_recyclage(), get_coord_faces(), initialiser(), lire_fichier_format1(), and lire_motcle_non_standard().
nom_pb1
Nom Champ_front_recyclage::nom_pb1 protected
Referenced by initialiser(), lire_fichier_format3(), and lire_motcle_non_standard().
nom_inco1
Motcle Champ_front_recyclage::nom_inco1 protected
Referenced by initialiser(), and lire_motcle_non_standard().
moyenne_imposee_
DoubleTab Champ_front_recyclage::moyenne_imposee_ protected
Referenced by calcul_moyenne_imposee(), initialiser(), initialiser_moyenne_imposee(), and mettre_a_jour().
moyenne_recyclee_
DoubleTab Champ_front_recyclage::moyenne_recyclee_ protected
Referenced by calcul_moyenne_recyclee(), initialiser(), initialiser_moyenne_recyclee(), and mettre_a_jour().
ampli_fluct_
DoubleVect Champ_front_recyclage::ampli_fluct_ protected
Referenced by Champ_front_recyclage(), initialiser(), lire_motcle_non_standard(), and mettre_a_jour().
ampli_moy_imposee_
DoubleVect Champ_front_recyclage::ampli_moy_imposee_ protected
Referenced by Champ_front_recyclage(), initialiser(), lire_motcle_non_standard(), and mettre_a_jour().
ampli_moy_recyclee_
DoubleVect Champ_front_recyclage::ampli_moy_recyclee_ protected
Referenced by Champ_front_recyclage(), initialiser(), lire_motcle_non_standard(), and mettre_a_jour().
methode_moy_impos_
int Champ_front_recyclage::methode_moy_impos_ protected
Referenced by calcul_moyenne_imposee(), Champ_front_recyclage(), initialiser_moyenne_imposee(), and lire_motcle_non_standard().
methode_moy_recycl_
int Champ_front_recyclage::methode_moy_recycl_ protected
Referenced by calcul_moyenne_recyclee(), Champ_front_recyclage(), initialiser_moyenne_recyclee(), and lire_motcle_non_standard().
fich_impos_
Nom Champ_front_recyclage::fich_impos_ protected
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
fich_recycl_
Nom Champ_front_recyclage::fich_recycl_ protected
Referenced by Champ_front_recyclage(), initialiser_moyenne_recyclee(), and lire_info_moyenne_recyclee().
fich_maillage_
Nom Champ_front_recyclage::fich_maillage_ protected
Referenced by initialiser_moyenne_imposee(), initialiser_moyenne_recyclee(), lire_info_moyenne_imposee(), and lire_info_moyenne_recyclee().
ndir
int Champ_front_recyclage::ndir protected
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), lire_fichier_format1(), lire_fichier_format2(), lire_fichier_format3(), lire_info_moyenne_imposee(), and set_param().
fcts_xyz
Noms Champ_front_recyclage::fcts_xyz protected
Referenced by initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
u_tau
double Champ_front_recyclage::u_tau protected
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
diametre
double Champ_front_recyclage::diametre protected
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
visco_cin
double Champ_front_recyclage::visco_cin protected
Referenced by Champ_front_recyclage(), initialiser_moyenne_imposee(), and lire_info_moyenne_imposee().
inconnues1_coords_to_eval_
DoubleTabs Champ_front_recyclage::inconnues1_coords_to_eval_ protected
Referenced by initialiser(), and mettre_a_jour().
inconnues1_elems_
ArrsOfInt Champ_front_recyclage::inconnues1_elems_ protected
Referenced by initialiser(), and mettre_a_jour().
inconnues2_faces_
ArrsOfInt Champ_front_recyclage::inconnues2_faces_ protected
Referenced by initialiser(), and mettre_a_jour().