CEA TRUST Platform: Decouper_32_64< _SIZE_ > Class Template Reference
Decouper_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void ecrire (const Static_Int_Lists_t *som_raccord=nullptr)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Decouper_32_64< _SIZE_ >
Aucun algorithme ici, uniquement lecture de parametres dans le fichier .data et execution du partitionneur et du decoupeur. Voir la methode interprete()
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Decouper_32_64< _SIZE_ >::int_t = _SIZE_
BigIntVect_t
template<typename _SIZE_ > using Decouper_32_64< _SIZE_ >::BigIntVect_t = TRUSTVect<int, _SIZE_>
IntTab_t
template<typename _SIZE_ > using Decouper_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Decouper_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Partitionneur_base_t
template<typename _SIZE_ > using Decouper_32_64< _SIZE_ >::Partitionneur_base_t = Partitionneur_base_32_64<_SIZE_>
Static_Int_Lists_t
template<typename _SIZE_ > using Decouper_32_64< _SIZE_ >::Static_Int_Lists_t = Static_Int_Lists_32_64<_SIZE_>
Member Function Documentation
lire()
template<typename _SIZE_ > Entree & Decouper_32_64< _SIZE_ >::lire (Entree & is)
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_flag(), Param::ajouter_non_std(), Domaine_32_64< _SIZE_ >::imprimer(), Param::lire_avec_accolades_depuis(), and Param::REQUIRED.
Referenced by Decouper_multi::lire_motcle_non_standard().
lire_motcle_non_standard()
template<typename _SIZE_ > int Decouper_32_64< _SIZE_ >::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
interpreter()
template<typename _SIZE_ > Entree & Decouper_32_64< _SIZE_ >::interpreter (Entree & is) override virtual
Implements Interprete.
References Partitionneur_base_32_64< _SIZE_ >::construire_partition(), and Partitionneur_base_32_64< _SIZE_ >::declarer_bords_periodiques().
ecrire()
template<typename _SIZE_ > void Decouper_32_64< _SIZE_ >::ecrire (const Static_Int_Lists_t * som_raccord = nullptr)
Ecriture d'une partition elem_part donnee som_raccord (optionnel) : som_raccord[s] -> process auxquels est raccorde le sommet s par un raccord a un autre domaine
References Process::exit(), Process::force_single_file(), and Process::mp_max().
OWN_PTR()
template<typename _SIZE_ > Decouper_32_64< _SIZE_ >::OWN_PTR (Partitionneur_base_t) protected
print_more_infos_()
int Decouper_32_64< int >::print_more_infos_
Friends And Related Function Documentation
Decouper_multi
template<typename _SIZE_ > friend class Decouper_multi friend
Decouper_etendu
template<typename _SIZE_ > friend class Decouper_etendu friend
Member Data Documentation
print_more_infos_
template<typename _SIZE_ > int Decouper_32_64< _SIZE_ >::print_more_infos_ static
nb_parts_tot_
template<typename _SIZE_ > int Decouper_32_64< _SIZE_ >::nb_parts_tot_ = -1 protected
Referenced by Decouper_multi::interpreter().
liste_bords_periodiques_
template<typename _SIZE_ > Noms Decouper_32_64< _SIZE_ >::liste_bords_periodiques_ protected
Referenced by Decouper_multi::interpreter().
elem_part_
template<typename _SIZE_ > BigIntVect_t Decouper_32_64< _SIZE_ >::elem_part_ protected
Referenced by Decouper_multi::interpreter().
nom_domaine_
template<typename _SIZE_ > Nom Decouper_32_64< _SIZE_ >::nom_domaine_ protected
epaisseur_joint_
template<typename _SIZE_ > int Decouper_32_64< _SIZE_ >::epaisseur_joint_ = 1 protected
nom_domaines_decoup_
template<typename _SIZE_ > Nom Decouper_32_64< _SIZE_ >::nom_domaines_decoup_ = "?" protected
nom_fichier_decoupage_
template<typename _SIZE_ > Nom Decouper_32_64< _SIZE_ >::nom_fichier_decoupage_ = "?" protected
nom_fichier_decoupage_sommets_
template<typename _SIZE_ > Nom Decouper_32_64< _SIZE_ >::nom_fichier_decoupage_sommets_ = "?" protected
nom_fichier_lata_
template<typename _SIZE_ > Nom Decouper_32_64< _SIZE_ >::nom_fichier_lata_ = "?" protected
nom_fichier_med_
template<typename _SIZE_ > Nom Decouper_32_64< _SIZE_ >::nom_fichier_med_ = "?" protected
format_
template<typename _SIZE_ > DomainesFileOutputType Decouper_32_64< _SIZE_ >::format_ = DomainesFileOutputType::BINARY_MULTIPLE protected
reorder_
template<typename _SIZE_ > int Decouper_32_64< _SIZE_ >::reorder_ = 0 protected