CEA TRUST Platform: Redistribute_Field Class Reference
Redistribute_Field Class Reference
Member Function Documentation
initialize() [1/2]
void Redistribute_Field::initialize (const Domaine_IJK & input, const Domaine_IJK & output, const Domaine_IJK::Localisation loc)
initialize() [2/2]
void Redistribute_Field::initialize (const Domaine_IJK & input, const Domaine_IJK & output, const Domaine_IJK::Localisation loc, const VECT(IntTab) & redistribute_maps)
References Schema_Comm_Vecteurs::add_recv_area_template(), Schema_Comm_Vecteurs::add_send_area_template(), Schema_Comm_Vecteurs::begin_init(), compute_send_blocs(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Schema_Comm_Vecteurs::end_init(), Process::exit(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_processor_by_ijk(), Process::me(), recv_blocs_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), schema_comm_, send_blocs_, TRUSTVect< _TYPE_, _SIZE_ >::size(), and size_buffer_for_me_.
redistribute() [1/3]
void Redistribute_Field::redistribute (const IJK_Field_double & input_field, IJK_Field_double & output_field) inline
References redistribute_().
redistribute() [2/3]
template<class T , int N> void Redistribute_Field::redistribute (const IJK_Field_vector< T, N > & input_field, IJK_Field_vector< T, N > & output_field) inline
References redistribute_().
redistribute_add() [1/3]
void Redistribute_Field::redistribute_add (const IJK_Field_double & input_field, IJK_Field_double & output_field) inline
References redistribute_().
redistribute_add() [2/3]
template<class T , int N> void Redistribute_Field::redistribute_add (const IJK_Field_vector< T, N > & input_field, IJK_Field_vector< T, N > & output_field) inline
References redistribute_().
redistribute() [3/3]
void Redistribute_Field::redistribute (const IJK_Field_float & input_field, IJK_Field_float & output_field) inline
References redistribute_().
redistribute_add() [3/3]
void Redistribute_Field::redistribute_add (const IJK_Field_float & input_field, IJK_Field_float & output_field) inline
References redistribute_().
redistribute_() [1/2]
void Redistribute_Field::redistribute_ (const IJK_Field_double & input_field, IJK_Field_double & output_field, bool add) protected
References Schema_Comm_Vecteurs::begin_comm(), Perf_counters::begin_count(), Perf_counters::create_custom_counter(), recv_blocs_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), schema_comm_, send_blocs_, and size_buffer_for_me_.
Referenced by redistribute(), and redistribute_add().
redistribute_() [2/2]
void Redistribute_Field::redistribute_ (const IJK_Field_float & input_field, IJK_Field_float & output_field, bool add) protected
References Process::exit().
intersect()
void Redistribute_Field::intersect (const int s1, const int n1, int & s2, int & n2, int & s3) static protected
Referenced by compute_send_blocs().
compute_send_blocs()
void Redistribute_Field::compute_send_blocs (const Domaine_IJK & input, const Domaine_IJK & output, const Domaine_IJK::Localisation localisation, const int dir, const IntTab & global_index_mapping, IntTab & send_blocs) protected
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_IJK::get_nb_items_local(), Domaine_IJK::get_offset_local(), Domaine_IJK::get_slice_offsets(), Domaine_IJK::get_slice_size(), intersect(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by initialize().
Member Data Documentation
send_blocs_
FixedVector<IntTab, 3> Redistribute_Field::send_blocs_ protected
Referenced by initialize(), and redistribute_().
recv_blocs_
FixedVector<IntTab, 3> Redistribute_Field::recv_blocs_ protected
Referenced by initialize(), and redistribute_().
schema_comm_
Schema_Comm_Vecteurs Redistribute_Field::schema_comm_ protected
Referenced by initialize(), and redistribute_().
size_buffer_for_me_
int Redistribute_Field::size_buffer_for_me_ protected
Referenced by initialize(), and redistribute_().