CEA TRUST Platform: Perf_counters Class Reference
Perf_counters Class Reference
Public Member Functions
void begin_count (const std::string &custom_count_name, int counter_lvl=-100000)
void begin_count (const STD_COUNTERS &std_cnt, int counter_lvl=-100000)
void create_custom_counter (std::string counter_description, int counter_level, std::string counter_family="None", bool is_comm=false, bool is_gpu=false)
void end_count (const std::string &custom_count_name, int count_increment=1, long int quantity_increment=0)
void end_count (const STD_COUNTERS &std_cnt, int count_increment=1, long int quantity_increment=0)
void end_time_step (long int tstep)
void print_TU_files (const std::string &message)
Static Public Member Functions
static Perf_counters & getInstance ()
Member Typedef Documentation
clock
using Perf_counters::clock = std::chrono::high_resolution_clock
time_point
using Perf_counters::time_point = std::chrono::time_point<clock>
duration
using Perf_counters::duration = std::chrono::duration<double>
Constructor & Destructor Documentation
Perf_counters()
Perf_counters::Perf_counters (const Perf_counters &) delete
Member Function Documentation
now()
time_point Perf_counters::now () inline
Referenced by compute_time(), and start_clock().
start_clock()
time_point Perf_counters::start_clock () inline
Start a clock, return a time_point, not a double.
References now().
compute_time()
double Perf_counters::compute_time (time_point start)
return time since start in seconds
References now().
getInstance()
static Perf_counters& Perf_counters::getInstance () inline static
The class Perf_counters is based on a phoenix singleton pattern. To access to the unique object inside the code, use the getInstance() function.
Returns
the unique Perf_counters object
create_custom_counter()
void Perf_counters::create_custom_counter (std::string counter_description, int counter_level, std::string counter_family = "None", bool is_comm = false, bool is_gpu = false)
Create a new counter and add it to the map of custom counters.
Parameters
counter_level
counter_description
counter_family
is_comm
Returns
create a new counter
Note
If the counter description already exists, it will not create a new counter.
Referenced by Domaine_PolyMAC_P0::fgrad(), IJK_Test_Multigrille::interpreter(), Multigrille_base::multigrille_(), Redistribute_Field::redistribute_(), Parallel_io_parameters::run_bench_read(), Parallel_io_parameters::run_bench_write(), and Multigrille_Adrien::set_rho().
begin_count() [1/2]
void Perf_counters::begin_count (const STD_COUNTERS & std_cnt, int counter_lvl = -100000)
Standard counters, start the tracking of the wanted operation
Parameters
std_cnt reference to the standard counter
counter_lvl level of the counter you try to open, warning it changes the value of the counter level associated with counter std_cnt
Referenced by Operateur_Conv::ajouter(), Operateur_Diff::ajouter(), Operateur_Div::ajouter(), Operateur_Grad::ajouter(), Source::ajouter(), Comm_Group_MPI::all_gather(), Comm_Group_MPI::all_gatherv(), Comm_Group_MPI::all_to_all(), Equation_base::assembler_avec_inertie(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Binaire_base::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_QC::assembler_blocs_avec_inertie(), Convection_Diffusion_Espece_Multi_WC::assembler_blocs_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Comm_Group_MPI::barrier(), Comm_Group_MPI::broadcast(), Operateur_Conv::calculer(), Operateur_Diff::calculer(), Operateur_Div::calculer(), Operateur_Grad::calculer(), Source::calculer(), Operateur::calculer_pas_de_temps(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Comm_Group_MPI::gather(), ICoCo::ProblemTrio::initialize(), IJK_Test_Multigrille::interpreter(), Resoudre::interpreter(), Scatter::interpreter(), MaillerParallel::interpreter(), Pb_Dilatable_base::iterateTimeStep(), Scatter::lire_domaine(), Modele_turbulence_hyd_0_eq_base::mettre_a_jour(), Multigrille_base::multigrille_(), Probleme_base::postraiter(), Comm_Group_MPI::recv(), Redistribute_Field::redistribute_(), Probleme_base::reprendre(), Solv_Petsc::resoudre_systeme(), Solv_cuDSS::resoudre_systeme(), SolveurSys::resoudre_systeme(), Parallel_io_parameters::run_bench_read(), Parallel_io_parameters::run_bench_write(), Probleme_U::runUntil(), Probleme_base::sauver(), Save_Restart::sauver_xyz(), Comm_Group_MPI::send(), Comm_Group_MPI::send_recv_start(), Multigrille_Adrien::set_rho(), EcrFicPartage::syncfile(), and Schema_Temps_base::validateTimeStep().
begin_count() [2/2]
void Perf_counters::begin_count (const std::string & custom_count_name, int counter_lvl = -100000)
Custom counters, start the tracking of the wanted operation
Parameters
custom_count_name string key in the custom counter map
counter_lvl level of the counter you try to open, warning it changes the value of the level of the counter associated with custom_count_name
end_count() [1/2]
void Perf_counters::end_count (const std::string & custom_count_name, int count_increment = 1, long int quantity_increment = 0)
End the count of a counter and update the counter values.
Parameters
c is the counter to end the count
count_increment is the count increment. If not specified, then it is equal to 1
quantity_increment is the increment of custom variable quantity. If not specified, it is set to 0.
Referenced by Operateur_Div::ajouter(), Operateur_Grad::ajouter(), Op_Conv_ALE::ajouter(), Equation_base::assembler(), Convection_Diffusion_Temperature::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Equation_base::assembler_blocs(), Convection_Diffusion_Temperature::assembler_blocs(), Equation_IBM_proto::assembler_ibm_proto(), Operateur_Div::calculer(), Operateur_Grad::calculer(), IJK_Test_Multigrille::interpreter(), Schema_Temps_base::mettre_a_jour(), Multigrille_base::multigrille_(), Solv_Optimal::prepare_resol(), Solv_GCP::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), SolveurPP1B::resoudre_systeme(), Solv_AMG::resoudre_systeme(), Probleme_U::run(), Parallel_io_parameters::run_bench_read(), Parallel_io_parameters::run_bench_write(), Comm_Group_MPI::send_recv_finish(), Multigrille_Adrien::set_rho(), and ICoCo::ProblemTrio::terminate().
end_count() [2/2]
void Perf_counters::end_count (const STD_COUNTERS & std_cnt, int count_increment = 1, long int quantity_increment = 0)
End the count of a counter and update the counter values.
Parameters
c is the counter to end the count
count_increment is the count increment. If not specified, then it is equal to 1
quantity_increment is the increment of custom variable quantity. If not specified, it is set to 0.
stop_counters()
void Perf_counters::stop_counters ()
Stop all counters, has to be called on every processor simultaneously.
restart_counters()
void Perf_counters::restart_counters ()
Restart all counters, has to be called on every processor simultaneously.
reset_counters()
void Perf_counters::reset_counters ()
Reset counters to zero, used between the start-up of the computation, the computation itself and the post-processing.
print_TU_files()
void Perf_counters::print_TU_files (const std::string & message)
Function that encapsulate the two functions that writes the TU files.
Parameters
messsage can only take three values: "Computation start-up statistics", "Time loop statistics" or "Post-resolution statistics"
Note
It also resets the counters
Referenced by mon_main::dowork().
get_computation_time()
double Perf_counters::get_computation_time ()
Update computation_time_ and return its value as a double (in seconds)
Referenced by mon_main::dowork().
get_total_time() [1/2]
double Perf_counters::get_total_time (const STD_COUNTERS & name)
Give as a double the total time (in second) elapsed in the operation tracked by the standard counter call name.
get_total_time() [2/2]
double Perf_counters::get_total_time (const std::string & name)
Give as a double the total time (in second) elapsed in the operation tracked by the custom counter call name.
get_time_since_last_open() [1/2]
double Perf_counters::get_time_since_last_open (const STD_COUNTERS & name)
Give as a double the time (in second) elapsed in the operation tracked by the standard counter call name since the counter was last opened.
Referenced by IJK_Test_Multigrille::interpreter(), Parallel_io_parameters::run_bench_read(), Parallel_io_parameters::run_bench_write(), and Schema_Temps_base::write_progress().
get_time_since_last_open() [2/2]
double Perf_counters::get_time_since_last_open (const std::string & name)
Give as a double the time (in second) elapsed in the operation tracked by the standard counter call name since the counter was last opened.
is_running()
bool Perf_counters::is_running (const STD_COUNTERS & name)
Check whether a counter is already running. Should rarely be used!
start_timeloop()
void Perf_counters::start_timeloop ()
Set time_loop_ to true in order to account for cache properly.
Referenced by Probleme_U::runUntil().
end_timeloop()
void Perf_counters::end_timeloop ()
Set time_loop_ to false as we exit the time loop.
start_time_step()
void Perf_counters::start_time_step ()
, this function start statistics tracking for a time step. It has to be called at the start of each time step.
Referenced by Probleme_U::runUntil().
end_time_step()
void Perf_counters::end_time_step (long int tstep)
This function compute statistics per time steps of counters used at least once during a time step.
Parameters
tstep is the current time step number
set_nb_time_steps_elapsed()
void Perf_counters::set_nb_time_steps_elapsed (int n)
Referenced by Parallel_io_parameters::run_bench_read(), and Parallel_io_parameters::run_bench_write().
get_last_opened_counter_level()
int Perf_counters::get_last_opened_counter_level () const
start_gpu_timer()
void Perf_counters::start_gpu_timer ()
stop_gpu_timer()
void Perf_counters::stop_gpu_timer ()
is_gpu_verbose_on()
bool Perf_counters::is_gpu_verbose_on () const
Referenced by DeviceMemory::warning().
set_gpu_verbose()
void Perf_counters::set_gpu_verbose (bool on)
get_init_device()
bool Perf_counters::get_init_device () const
set_init_device()
void Perf_counters::set_init_device (bool init)
get_gpu_timer()
bool Perf_counters::get_gpu_timer () const
set_gpu_timer()
void Perf_counters::set_gpu_timer (bool timer)
add_to_gpu_timer_counter()
void Perf_counters::add_to_gpu_timer_counter (int to_add)
get_gpu_timer_counter()
int Perf_counters::get_gpu_timer_counter () const
stop_gpu_timer_and_compute_gpu_time()
double Perf_counters::stop_gpu_timer_and_compute_gpu_time ()
get_use_gpu()
bool Perf_counters::get_use_gpu () const
get_gpu_fence()
bool Perf_counters::get_gpu_fence () const
set_gpu_fence()
void Perf_counters::set_gpu_fence (bool fence)
operator=()
Perf_counters& Perf_counters::operator= (const Perf_counters &) delete