CEA TRUST Platform: Champ_Q1NC_implementation Class Reference
Champ_Q1NC_implementation Class Reference abstract
#include <Champ_Q1NC_implementation.h>
Constructor & Destructor Documentation
~Champ_Q1NC_implementation()
Champ_Q1NC_implementation::~Champ_Q1NC_implementation () inline override
Member Function Documentation
fonction_forme_2D()
double Champ_Q1NC_implementation::fonction_forme_2D (double x, double y, int le_poly, int face) inline
References fonction_forme_2D_normalise(), and tab_param.
Referenced by calcule_valeur_a_elem_compo(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
fonction_forme_2D_normalise()
double Champ_Q1NC_implementation::fonction_forme_2D_normalise (double x, double y, int face) inline static
References Process::exit().
Referenced by fonction_forme_2D().
fonction_forme_3D()
double Champ_Q1NC_implementation::fonction_forme_3D (double x, double y, double z, int le_poly, int face) inline
References fonction_forme_3D_normalise(), and tab_param.
Referenced by calcule_valeur_a_elem_compo(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
fonction_forme_3D_normalise()
double Champ_Q1NC_implementation::fonction_forme_3D_normalise (double x, double y, double z, int face) inline static
References Process::exit().
Referenced by fonction_forme_3D().
Derivee_fonction_forme_2D_normalise()
DoubleTab & Champ_Q1NC_implementation::Derivee_fonction_forme_2D_normalise (double u, double v, DoubleTab & DF) static
Derivee_fonction_forme_3D_normalise()
DoubleTab & Champ_Q1NC_implementation::Derivee_fonction_forme_3D_normalise (double u, double v, double w, DoubleTab & DF) static
valeur_a_elem()
DoubleVect & Champ_Q1NC_implementation::valeur_a_elem (const DoubleVect & position, DoubleVect & val, int le_poly) const override virtual
Implements Champ_implementation.
References Objet_U::dimension, domaine_vef(), Domaine_VF::elem_faces(), fonction_forme_2D(), fonction_forme_3D(), Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTVect< _TYPE_, _SIZE_ >::size(), tab_param, transforme_coord2D(), transforme_coord3D(), and Champ_Proto::valeurs().
Referenced by Champ_Fonc_Q1NC::valeur_a_elem(), and Champ_Q1NC::valeur_a_elem().
calcule_valeur_a_elem_compo()
double Champ_Q1NC_implementation::calcule_valeur_a_elem_compo (double xs, double ys, double zs, int le_poly, int ncomp) const
References Objet_U::dimension, domaine_vef(), Domaine_VF::elem_faces(), fonction_forme_2D(), fonction_forme_3D(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::size(), tab_param, transforme_coord2D(), transforme_coord3D(), and Champ_Proto::valeurs().
Referenced by valeur_a_elem_compo(), and valeur_a_sommet_compo().
valeur_a_elem_compo()
double Champ_Q1NC_implementation::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
Implements Champ_implementation.
References calcule_valeur_a_elem_compo(), and Objet_U::dimension.
Referenced by Champ_Fonc_Q1NC::valeur_a_elem_compo(), Champ_Q1NC::valeur_a_elem_compo(), valeur_aux_sommets(), and valeur_aux_sommets_compo().
valeur_a_sommet_compo()
double Champ_Q1NC_implementation::valeur_a_sommet_compo (int num_som, int le_poly, int ncomp) const
References calcule_valeur_a_elem_compo(), Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, and Champ_implementation::get_domaine_geom().
Referenced by Champ_Q1NC::valeur_a_sommet_compo().
valeur_aux_elems()
DoubleTab & Champ_Q1NC_implementation::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const override virtual
Implements Champ_implementation.
References Objet_U::dimension, domaine_vef(), Domaine_VF::elem_faces(), Process::exit(), fonction_forme_2D(), fonction_forme_3D(), Champ_implementation::le_champ(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), TRUSTVect< _TYPE_, _SIZE_ >::size(), tab_param, transforme_coord2D(), transforme_coord3D(), and Champ_Proto::valeurs().
Referenced by Champ_Fonc_Q1NC::valeur_aux_elems(), and Champ_Q1NC::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Q1NC_implementation::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) const override virtual
Implements Champ_implementation.
References Objet_U::dimension, domaine_vef(), Domaine_VF::elem_faces(), fonction_forme_2D(), fonction_forme_3D(), Champ_implementation::le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), tab_param, transforme_coord2D(), transforme_coord3D(), and Champ_Proto::valeurs().
Referenced by Champ_Fonc_Q1NC::valeur_aux_elems_compo(), and Champ_Q1NC::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Q1NC_implementation::valeur_aux_sommets (const Domaine & dom, DoubleTab & ch_som) const override virtual
Implements Champ_implementation_divers.
References Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, Domaine_dis_base::domaine(), Champ_implementation::get_domaine_dis(), Champ_implementation::le_champ(), Field_base::nb_comp(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_32_64< _SIZE_ >::sommet_elem(), and valeur_a_elem_compo().
Referenced by Champ_Fonc_Q1NC::valeur_aux_sommets(), and Champ_Q1NC::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Q1NC_implementation::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & ch_som, int ncomp) const override virtual
Implements Champ_implementation_divers.
References Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, Domaine_dis_base::domaine(), Champ_implementation::get_domaine_dis(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_32_64< _SIZE_ >::sommet_elem(), and valeur_a_elem_compo().
Referenced by Champ_Fonc_Q1NC::valeur_aux_sommets_compo(), and Champ_Q1NC::valeur_aux_sommets_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Q1NC_implementation::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_implementation.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_vef(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_VF::nb_faces(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), and Domaine_VF::xv().
Referenced by Champ_Fonc_Q1NC::remplir_coord_noeuds(), Champ_Q1NC::remplir_coord_noeuds(), and remplir_coord_noeuds_et_polys().
remplir_coord_noeuds_et_polys()
int Champ_Q1NC_implementation::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const override virtual
Implements Champ_implementation.
References domaine_vef(), Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), remplir_coord_noeuds(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by Champ_Fonc_Q1NC::remplir_coord_noeuds_et_polys(), and Champ_Q1NC::remplir_coord_noeuds_et_polys().
transforme_coord2D()
void Champ_Q1NC_implementation::transforme_coord2D ()
References domaine_vef(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets(), Champ_implementation::get_domaine_geom(), Domaine_32_64< _SIZE_ >::les_sommets(), Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and tab_param.
Referenced by calcule_valeur_a_elem_compo(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
transforme_coord3D()
void Champ_Q1NC_implementation::transforme_coord3D ()
References domaine_vef(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets(), Champ_implementation::get_domaine_geom(), Domaine_32_64< _SIZE_ >::les_sommets(), Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and tab_param.
Referenced by calcule_valeur_a_elem_compo(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
domaine_vef()
virtual const Domaine_VEF & Champ_Q1NC_implementation::domaine_vef () const protected pure virtual
Implemented in Champ_Fonc_Q1NC, and Champ_Q1NC.
Referenced by calcule_valeur_a_elem_compo(), remplir_coord_noeuds(), remplir_coord_noeuds_et_polys(), transforme_coord2D(), transforme_coord3D(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().
trace()
DoubleTab & Champ_Q1NC_implementation::trace (const Frontiere_dis_base & fr, const DoubleTab & y, DoubleTab & x, int distant) const inline protected
References Frontiere_dis_base::frontiere(), Frontiere_32_64< _SIZE_ >::trace_face_distant(), and Frontiere_32_64< _SIZE_ >::trace_face_local().
Referenced by Champ_Fonc_Q1NC::trace(), and Champ_Q1NC::trace().
Member Data Documentation
tab_param
DoubleTab Champ_Q1NC_implementation::tab_param protected
Referenced by calcule_valeur_a_elem_compo(), fonction_forme_2D(), fonction_forme_3D(), transforme_coord2D(), transforme_coord3D(), valeur_a_elem(), valeur_aux_elems(), and valeur_aux_elems_compo().