CEA TRUST Platform: Source Class Reference
Source Class Reference
#include <Source.h>
Public Member Functions
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
void typer (const Nom &, const Equation_base &)
void typer_direct (const Nom &)
Detailed Description
referencer n'importe quel d'objet derivant de Source_base.
La plupart des methodes appellent les methodes de l'objet Probleme
sous-jacent via la methode valeur() declaree grace a la macro
See also
Source_base
Member Function Documentation
ajouter()
DoubleTab & Source::ajouter (DoubleTab & xx) const
Appel a l'objet sous-jacent.
Ajoute la contribution de la source au tableau passe en parametre.
Parameters
(DoubleTab& xx) le tableau auquel on ajoute la contribution de la source
Returns
(DoubleTab&) le parametre xx modifie
References Statistiques::begin_count(), and Statistiques::end_count().
Referenced by Source_QC_QDM_Gen::ajouter().
calculer()
DoubleTab & Source::calculer (DoubleTab & xx) const
Appel a l'objet sous-jacent.
Affecte le terme source au tableau passe en parametre.
Parameters
(DoubleTab& xx) le tableau dans lequel on stocke la valeur de la source
Returns
(DoubleTab&) le parametre xx modifie
References Statistiques::begin_count(), and Statistiques::end_count().
typer_direct()
void Source::typer_direct (const Nom & typ)
Parameters
(Nom& typ) le nom de type a donner a la source
References typer().
Referenced by Navier_Stokes_QC::completer(), Navier_Stokes_WC::completer(), Navier_Stokes_std::completer(), Navier_Stokes_Turbulent_QC::completer(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard(), and Source_QC_QDM_Gen::readOn_spec().
typer()
void Source::typer (const Nom & typ, const Equation_base & eqn)
Type la source en calculant le nom du type necessaire grace aux parametres fournis.
Parameters
(Nom& typ) le debut du type
(Equation_base& eqn) l'equation associee a la source
References Equation_base::discretisation(), Discretisation_base::get_name_of_type_for(), Objet_U::que_suis_je(), and typer().
Referenced by typer(), and typer_direct().