CEA TRUST Platform: Op_Grad_PolyMAC_P0_Face Class Reference
Op_Grad_PolyMAC_P0_Face Class Reference
#include <Op_Grad_PolyMAC_P0_Face.h>
Public Member Functions
void completer () override
Public Member Functions inherited from Op_Grad_PolyMAC_P0P1NC_Face
void completer () override
Public Member Functions inherited from Op_Grad_PolyMAC_Face
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
void dimensionner (Matrice_Morse &) const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Grad_base
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
void dimensionner (Matrice_Morse &) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe represente l'operateur de gradient La discretisation est PolyMAC_P0 On calcule le gradient d'un champ_Elem_PolyMAC_P0 (la pression)
See also
Operateur_Grad_base
Member Function Documentation
completer()
void Op_Grad_PolyMAC_P0_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer(), MorEqn::equation(), Process::exit(), and Champ_Face_PolyMAC_P0::init_auxiliary_variables().
dimensionner_blocs()
void Op_Grad_PolyMAC_P0_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), Champ_Face_base::fcl(), fgrad_d, fgrad_e, Nom::getString(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), update_grad(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Grad_PolyMAC_P0_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Process::abort(), Statistiques::begin_count(), dgb_v_, dgf_gb_, dgf_pe_, dgp_gb_, Objet_U::dimension, Statistiques::end_count(), MorEqn::equation(), Champ_Face_base::fcl(), fgrad_c, fgrad_d, fgrad_e, Nom::getString(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and update_grad().
update_grad()
void Op_Grad_PolyMAC_P0_Face::update_grad (int full_stencil = 0) const
References MorEqn::equation(), Champ_Face_base::fcl(), fgrad_c, fgrad_d, fgrad_e, Equation_base::inconnue(), last_gradp_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Inc_base::recuperer_temps_passe().
Referenced by ajouter_blocs(), Assembleur_P_PolyMAC_P0::assembler_mat(), and dimensionner_blocs().
Member Data Documentation
fgrad_d
IntTab Op_Grad_PolyMAC_P0_Face::fgrad_d mutable
Referenced by ajouter_blocs(), Assembleur_P_PolyMAC_P0::assembler_mat(), dimensionner_blocs(), and update_grad().
fgrad_e
IntTab Op_Grad_PolyMAC_P0_Face::fgrad_e
Referenced by ajouter_blocs(), Assembleur_P_PolyMAC_P0::assembler_mat(), dimensionner_blocs(), and update_grad().
fgrad_c
DoubleTab Op_Grad_PolyMAC_P0_Face::fgrad_c mutable
Referenced by ajouter_blocs(), Assembleur_P_PolyMAC_P0::assembler_mat(), and update_grad().
last_gradp_
double Op_Grad_PolyMAC_P0_Face::last_gradp_ = -DBL_MAX mutable protected
Referenced by update_grad().
dgp_gb_
std::map<int, std::map<int, double> > Op_Grad_PolyMAC_P0_Face::dgp_gb_ mutable protected
Referenced by ajouter_blocs().
dgb_v_
std::map<int, std::map<int, double> > Op_Grad_PolyMAC_P0_Face::dgb_v_ mutable protected
Referenced by ajouter_blocs().
dgf_pe_
std::vector<std::vector<std::pair<int, double> > > Op_Grad_PolyMAC_P0_Face::dgf_pe_ mutable protected
Referenced by ajouter_blocs().
dgf_gb_
std::vector<std::vector<std::pair<int, double> > > Op_Grad_PolyMAC_P0_Face::dgf_gb_ mutable protected
Referenced by ajouter_blocs().