CEA TRUST Platform: Sonde Class Reference
Sonde Class Reference
#include <Sonde.h>
Public Member Functions
void associer_post (const Postraitement &)
SFichier & fichier ()
void fixer_periode (double)
virtual void initialiser ()
const Champ_Generique_base & le_champ () const
const IntVect & les_poly () const
const DoubleTab & les_positions_sondes_initiales () const
virtual void mettre_a_jour (double temps, double tinit)
void nommer (const Nom &n) override
void ouvrir_fichier ()
virtual void postraiter ()
Sonde (const Nom &)
double temps () const
~Sonde () override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
virtual void create_champ_generique (Entree &is, const Motcle &motlu)
virtual void fill_local_values ()
virtual void fix_probe_position ()
virtual void fix_probe_position_grav ()
virtual const Domaine & get_domaine_geom () const
virtual int get_nb_compo_champ () const
virtual const Noms get_noms_champ () const
virtual double get_temps_champ () const
virtual void update_source (double un_temps)
virtual void validate_position () const
virtual void validate_type (const Motcle &loc) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Attributes
int ncomp
bool nodes
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
On choisit l'ensemble des points sur lesquels on veut sonder un champ et
la periodicite des observations. Les objets Postraitement porte des
des sondes sur les champs a observer, une sonde porte d'ailleurs une
reference sur un postraitement.
See also
Postraitement Sondes
Constructor & Destructor Documentation
Sonde() [1/2]
Sonde::Sonde ()
Constructeur d'une sonde sans parametre.
Sonde() [2/2]
Sonde::Sonde (const Nom & nom)
Constructeur d'une sonde a partir de son nom.
Parameters
(Nom& nom) le nom de la sonde a construire
~Sonde()
Sonde::~Sonde () inline override
Destructeur.
Ferme le fichier avant de detruire l'objet.
References fermer_fichier().
Member Function Documentation
associer_post()
void Sonde::associer_post (const Postraitement & le_post)
Associer le postraitement a la sonde.
Parameters
(Postraitement& le_post) le postraitement a associer
References Process::exit(), and nom_.
initialiser()
void Sonde::initialiser () virtual
Initialise la sonde.
Dimensionne les tableaux, de valeurs, verifie si les points specifies sont bien dans le domaine de calcul.
Parameters
(Domaine& domaine_geom) le domaine de calcul qui sera sondee
Exceptions
point de sondage en dehors du domaine de calcul
References Domaine_32_64< _SIZE_ >::chercher_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUST_Vector< _CLASSE_ >::dimensionner(), Domaine_dis_base::domaine(), elem_, Domaine_VF::elem_faces(), Process::exit(), fix_probe_position(), fix_probe_position_grav(), get_domaine_geom(), get_nb_compo_champ(), get_noms_champ(), grav, gravcl, Process::je_suis_maitre(), Process::Journal(), Nom::le_nom(), Domaine_32_64< _SIZE_ >::les_elems(), les_positions_, les_positions_sondes_, les_positions_sondes_initiales_, Domaine_32_64< _SIZE_ >::les_sommets(), Process::me(), Process::mp_max(), Process::mp_sum(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), ncomp, nodes, nom_, Process::nproc(), numero_elem_, orientation_faces_, Domaine_VF::orientation_si_definie(), participant, Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), som, valeurs_locales, valeurs_sur_maitre, and Domaine_VF::xv().
Referenced by completer(), and mettre_a_jour().
mettre_a_jour()
void Sonde::mettre_a_jour (double un_temps, double tinit) virtual
Effectue une mise a jour en temps de la sonde effectue le postraitement.
Parameters
(double un_temps) le temps de mise a jour
(double tinit) le temps initial de la sonde
References get_temps_champ(), initialiser(), nb_bip, periode, postraiter(), and update_source().
postraiter()
void Sonde::postraiter () virtual
Effectue un postraitement.
Calcul les valeurs du champ aux position demandees et les imprime sur le fichier associe.
References dim, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), fichier(), fill_local_values(), Sortie_Fichier_base::flush(), gravcl, Process::je_suis_maitre(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::me(), mettre_a_jour_bords(), ncomp, nom_, Process::nproc(), ouvrir_fichier(), participant, valeurs_locales, and valeurs_sur_maitre.
Referenced by mettre_a_jour().
ouvrir_fichier()
void Sonde::ouvrir_fichier ()
Ouvre le fichier associe a la sonde.
(*.son)
References dim, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, fichier(), get_type(), Sortie_Fichier_base::is_open(), Process::je_suis_maitre(), le_fichier_, les_positions_sondes(), les_positions_sondes_, nbre_points1, nbre_points2, nbre_points3, ncomp, nom_, nom_champ_lu_, Objet_U::nom_du_cas(), nom_fichier_, Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), and Sortie_Fichier_base::setf().
Referenced by postraiter().
completer()
void Sonde::completer () virtual
References Champ_Generique_base::composante(), Motcles::contient_(), Motcle::debute_par(), Probleme_base::get_champ(), initialiser(), Nom::le_nom(), ncomp, nom_, nom_champ_lu_, OBS_PTR(), and Nom::suffix().
fermer_fichier()
void Sonde::fermer_fichier () inline
Ferme le fichier sur laquelle la sonde ecrit.
References Sortie_Fichier_base::close(), fichier(), and le_fichier_.
Referenced by ~Sonde().
le_champ()
const Champ_Generique_base & Sonde::le_champ () const inline
Renvoie le champ associe.
Returns
(Champ_base&) le champ associe
les_positions_sondes_initiales()
const DoubleTab & Sonde::les_positions_sondes_initiales () const inline
Renvoie le tableau des positions du champ qui sont sondees.
Returns
(DoubleTab&) les positions sondees
References les_positions_sondes_initiales_.
les_positions_sondes()
const DoubleTab & Sonde::les_positions_sondes () const inline
References les_positions_sondes_.
Referenced by ouvrir_fichier().
les_positions()
const DoubleTab & Sonde::les_positions () const inline
References les_positions_.
Referenced by fill_local_values().
les_poly()
const IntVect & Sonde::les_poly () const inline
Renvoie le tableau des elements qui sont sondes.
Returns
(IntVect&) les ments qui sont sondes
References elem_.
fixer_periode()
void Sonde::fixer_periode (double pe) inline
Fixe la periode avec laquelle on sonde le champ.
Parameters
(double pe) la periode de sondage du champ
References periode.
temps()
double Sonde::temps () const inline
Le temps ecoule.
Returns
(double) le temps ecoule
References nb_bip, and periode.
fichier()
SFichier & Sonde::fichier () inline
Renvoie un flot de sortie Fichier, pointant sur le fichier de sortie utilise par la sonde.
Returns
(SFichier&) le fichier de sortie utilise par la sonde
References le_fichier_.
Referenced by fermer_fichier(), ouvrir_fichier(), and postraiter().
get_nom()
const Nom & Sonde::get_nom () const inline
References nom_.
get_type()
const Nom & Sonde::get_type () const inline
References type_.
Referenced by ouvrir_fichier().
get_dim()
const int & Sonde::get_dim () const inline
References dim.
nommer()
void Sonde::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References nom_.
ajouter_bords()
void Sonde::ajouter_bords (const DoubleTab & coords_bords)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, elem_, Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), faces_bords_, les_positions_sondes_, and Domaine_VF::xv().
Referenced by fix_probe_position_grav().
init_bords()
void Sonde::init_bords ()
References Champ_Inc_base::domaine_Cl_dis(), faces_bords_, Probleme_base::get_champ(), gravcl, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), nom_champ_lu_, Front_VF::num_premiere_face(), OBS_PTR(), rang_cl_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
mettre_a_jour_bords()
void Sonde::mettre_a_jour_bords ()
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_Inc_base::domaine_Cl_dis(), Domaine_VF::face_voisins(), faces_bords_, Probleme_base::get_champ(), Domaine_Cl_dis_base::les_conditions_limites(), nom_champ_lu_, Front_VF::num_premiere_face(), OBS_PTR(), rang_cl_, TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Champ_Inc_base::valeurs(), and valeurs_locales.
Referenced by postraiter().
resetTime()
void Sonde::resetTime (double time) inline
References nb_bip, and periode.
get_domaine_geom()
const Domaine & Sonde::get_domaine_geom () const protected virtual
Retrieve the domain to be used for the probe
Referenced by initialiser().
get_noms_champ()
const Noms Sonde::get_noms_champ () const protected virtual
Retrieve the field names - overriden in IJK
Referenced by initialiser().
get_nb_compo_champ()
int Sonde::get_nb_compo_champ () const protected virtual
Retrieve the number of component for the field - overriden in IJK
Referenced by initialiser().
get_temps_champ()
double Sonde::get_temps_champ () const protected virtual
Retrieve the current time for the field - overriden in IJK
Referenced by mettre_a_jour().
validate_type()
virtual void Sonde::validate_type (const Motcle & loc) const inline protected virtual
Should exit if invalid type for a probe - overriden for IJK
validate_position()
virtual void Sonde::validate_position () const inline protected virtual
Should exit if invalid position has been set for a probe - overriden for IJK
create_champ_generique()
void Sonde::create_champ_generique (Entree & is, const Motcle & motlu) protected virtual
Creation des Champ_Generique_refChamp necessaire pour l initialisation de la REF a Champ_Generique_base Si le champ demande est un Champ_base connu du probleme on cree le Champ_Generique_refChamp correspondant
References Motcles::contient_(), Probleme_base::creer_champ(), Probleme_base::expression_predefini(), Probleme_base::get_champ(), Nom::le_nom(), nom_champ_lu_, and OBS_PTR().
fix_probe_position()
virtual void Sonde::fix_probe_position () inline protected virtual
Fix probe position - used by IJK
Referenced by initialiser().
fix_probe_position_grav()
void Sonde::fix_probe_position_grav () protected virtual
Fix probe position when keyword grav or gravcl is used
References ajouter_bords(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, elem_, gravcl, Process::Journal(), les_positions_sondes_, nom_, and Domaine_VF::xp().
Referenced by initialiser().
fill_local_values()
void Sonde::fill_local_values () protected virtual
Fill the array 'valeurs_locales' used by each proc to store prob local values
References chsom, elem_, les_positions(), ncomp, nom_champ_lu_, OBS_PTR(), Champ_base::valeur_aux_elems_compo_smooth(), Champ_base::valeur_aux_elems_smooth(), and valeurs_locales.
Referenced by postraiter().
update_source()
void Sonde::update_source (double un_temps) protected virtual
Update the underlying field source if needed
References nom_champ_lu_, and OBS_PTR().
Referenced by mettre_a_jour().
OBS_PTR() [1/3]
Sonde::OBS_PTR (Postraitement) protected
Referenced by completer(), create_champ_generique(), fill_local_values(), init_bords(), mettre_a_jour_bords(), and update_source().
OBS_PTR() [2/3]
Sonde::OBS_PTR (Champ_Generique_base) protected
OBS_PTR() [3/3]
Sonde::OBS_PTR (Operateur_Statistique_tps_base) protected
Member Data Documentation
nom_
Nom Sonde::nom_ protected
le nom de la sonde
Referenced by associer_post(), completer(), fix_probe_position_grav(), get_nom(), initialiser(), nommer(), ouvrir_fichier(), and postraiter().
nom_fichier_
Nom Sonde::nom_fichier_ protected
le nom du fichier contenant la sonde
Referenced by ouvrir_fichier().
dim
int Sonde::dim protected
la dimension de la sone (point:0,segment:1,plan:2,volume:3)
Referenced by get_dim(), ouvrir_fichier(), and postraiter().
ncomp
int Sonde::ncomp protected
Numero de la composante a sonder. Si ncomp = -1 la sonde s'applique a toutes les composantes du champ
Referenced by completer(), fill_local_values(), initialiser(), ouvrir_fichier(), and postraiter().
les_positions_sondes_initiales_
DoubleTab Sonde::les_positions_sondes_initiales_ protected
les coordonnees des sondes ponctuelles initiales
Referenced by initialiser(), and les_positions_sondes_initiales().
les_positions_sondes_
DoubleTab Sonde::les_positions_sondes_ protected
les coordonnees des sondes sur tout le domaine apres deplacement (uniquement sur le maitre)
Referenced by ajouter_bords(), fix_probe_position_grav(), initialiser(), les_positions_sondes(), and ouvrir_fichier().
les_positions_
DoubleTab Sonde::les_positions_ protected
les coordonnees des sondes locales sur chaque proc
Referenced by initialiser(), and les_positions().
numero_elem_
int Sonde::numero_elem_ protected
vaut -1 si pas defini et vaut le numero de l'elem sur le maitre
Referenced by initialiser().
elem_
IntVect Sonde::elem_ protected
les elements contenant les sondes ponctuelles locales
Referenced by ajouter_bords(), fill_local_values(), fix_probe_position_grav(), initialiser(), and les_poly().
periode
double Sonde::periode protected
periode d'echantillonnage
Referenced by fixer_periode(), mettre_a_jour(), resetTime(), and temps().
nodes
bool Sonde::nodes protected
cles pour typage des sondes (sondes redefinies aux noeuds ou d'apres les valeurs aux sommets ou au centre de gravite ou aux sommets)
Referenced by initialiser().
chsom
bool Sonde::chsom protected
Referenced by fill_local_values().
grav
bool Sonde::grav protected
Referenced by initialiser().
gravcl
bool Sonde::gravcl protected
Referenced by fix_probe_position_grav(), init_bords(), initialiser(), and postraiter().
som
bool Sonde::som protected
Referenced by initialiser().
valeurs_locales
DoubleTab Sonde::valeurs_locales protected
Referenced by fill_local_values(), initialiser(), mettre_a_jour_bords(), and postraiter().
valeurs_sur_maitre
DoubleTab Sonde::valeurs_sur_maitre protected
valeurs_locales les valeurs sur chaque proc, valeurs_sur_maitre les valeurs regroupes sur le maitre
Referenced by initialiser(), and postraiter().
nb_bip
double Sonde::nb_bip protected
Referenced by mettre_a_jour(), resetTime(), and temps().
le_fichier_
SFichier Sonde::le_fichier_ protected
Referenced by fermer_fichier(), fichier(), and ouvrir_fichier().
nom_champ_lu_
Motcle Sonde::nom_champ_lu_ protected
Referenced by completer(), create_champ_generique(), fill_local_values(), init_bords(), mettre_a_jour_bords(), ouvrir_fichier(), and update_source().
participant
ArrsOfInt Sonde::participant protected
Referenced by initialiser(), and postraiter().
type_
Nom Sonde::type_ protected
Referenced by get_type().
orientation_faces_
int Sonde::orientation_faces_ protected
Referenced by initialiser().
faces_bords_
ArrOfInt Sonde::faces_bords_ protected
array containing the indices of the boundary faces hit by the probe
Referenced by ajouter_bords(), init_bords(), and mettre_a_jour_bords().
rang_cl_
IntTab Sonde::rang_cl_ protected
for a given face, index of the CL that this face bears
Referenced by init_bords(), and mettre_a_jour_bords().
nbre_points1
int Sonde::nbre_points1 = -1 protected
Referenced by ouvrir_fichier().
nbre_points2
int Sonde::nbre_points2 = -1 protected
Referenced by ouvrir_fichier().
nbre_points3
int Sonde::nbre_points3 = -1 protected
faire des sonde_segment,sonde_plan,etc...
Referenced by ouvrir_fichier().