CEA TRUST Platform: Champs_compris_T< FIELD_TYPE > Class Template Reference
Champs_compris_T< FIELD_TYPE > Class Template Reference
Detailed Description
template<typename FIELD_TYPE>
class Champs_compris_T< FIELD_TYPE >
Operateur, Source, Traitement_particulier.
Parametrized by the type of field: typically Champ_base or IJK_Field_double
Member Function Documentation
get_champ()
template<typename FIELD_TYPE > const FIELD_TYPE & Champs_compris_T< FIELD_TYPE >::get_champ (const Motcle & nom) const
References Nom::getString().
Referenced by Source_PDF_EF::get_champ(), Paroi_hyd_base_EF::get_champ(), Loi_Fermeture_base::get_champ(), Milieu_base::get_champ(), Operateur_base::get_champ(), Source_base::get_champ(), Loi_Etat_base::get_champ(), Convection_Diffusion_Temperature::get_champ(), Convection_Diffusion_Temperature_base::get_champ(), Navier_Stokes_std::get_champ(), Marqueur_Lagrange_base::get_champ(), Traitement_particulier_NS_base::get_champ(), Diametre_bulles_champ::get_champ(), Diametre_bulles_constant::get_champ(), Diametre_bulles_musig::get_champ(), Gravite_Multiphase::get_champ(), Turbulence_paroi_base::get_champ(), Turbulence_paroi_scal_base::get_champ(), Conduction::get_champ(), and Traitement_particulier_Solide_base::get_champ().
has_champ() [1/2]
template<typename FIELD_TYPE > bool Champs_compris_T< FIELD_TYPE >::has_champ (const Motcle & nom, OBS_PTR(FIELD_TYPE)& ref_champ) const
References Nom::getString().
Referenced by Puissance_Thermique_QC_EF::get_champ(), Equation_base::get_champ(), Modele_turbulence_hyd_base::get_champ(), Modele_turbulence_scal_base::get_champ(), Correlation_base::has_champ(), Loi_Fermeture_base::has_champ(), Operateur_base::has_champ(), Loi_Etat_base::has_champ(), Turbulence_paroi_base::has_champ(), Turbulence_paroi_scal_base::has_champ(), Modele_turbulence_hyd_base::has_champ(), Modele_turbulence_scal_base::has_champ(), Source_PDF_EF::has_champ(), Puissance_Thermique_QC_EF::has_champ(), Paroi_hyd_base_EF::has_champ(), Equation_base::has_champ(), Milieu_base::has_champ(), Source_base::has_champ(), Marqueur_Lagrange_base::has_champ(), Traitement_particulier_NS_base::has_champ(), Diametre_bulles_champ::has_champ(), Diametre_bulles_constant::has_champ(), Diametre_bulles_musig::has_champ(), Gravite_Multiphase::has_champ(), and Traitement_particulier_Solide_base::has_champ().
has_champ() [2/2]
template<typename FIELD_TYPE > bool Champs_compris_T< FIELD_TYPE >::has_champ (const Motcle & nom) const
References Nom::getString().
ajoute_champ()
template<typename FIELD_TYPE > void Champs_compris_T< FIELD_TYPE >::ajoute_champ (const FIELD_TYPE & champ)
References Process::exit(), and Nom::le_nom().
Referenced by Equation_base::add_champs_compris(), Champs_compris_IJK::ajoute_champ_vectoriel(), Op_Conv_VDF_base::creer_champ(), Domaine_dis_base::creer_champ(), Source_PDF_EF::creer_champ(), Paroi_hyd_base_EF::creer_champ(), Equation_base::creer_champ(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::creer_champ(), Fluide_Dilatable_base::creer_champ(), Convection_Diffusion_Temperature::creer_champ(), Convection_Diffusion_Temperature_base::creer_champ(), Navier_Stokes_std::creer_champ(), QDM_Multiphase::creer_champ(), Source_Portance_interfaciale_base::creer_champ(), Turbulence_paroi_base::creer_champ(), Conduction::creer_champ(), Equation_base::discretiser(), Modele_turbulence_hyd_base::discretiser(), Modele_turbulence_scal_base::discretiser(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser(), Convection_Diffusion_Concentration::discretiser(), Convection_Diffusion_Temperature::discretiser(), Navier_Stokes_std::discretiser(), Aire_interfaciale::discretiser(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Modele_turbulence_hyd_0_eq_base::discretiser(), Conduction::discretiser(), Loi_Fermeture_Test::discretiser(), Milieu_base::discretiser(), Marqueur_Lagrange_base::discretiser(), Fluide_Dilatable_base::discretiser(), Fluide_Weakly_Compressible::discretiser(), Fluide_base::discretiser(), Fluide_Ostwald::discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), Solide::discretiser(), Navier_Stokes_std::discretiser_grad_p(), Constituant::discretiser_multi_concentration(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Traitement_particulier_NS_Pression_VEF::lire(), Terme_Source_Acceleration::lire_data(), and Convection_Diffusion_Concentration::lire_motcle_non_standard().
liste_noms_compris()
template<typename FIELD_TYPE > const Noms Champs_compris_T< FIELD_TYPE >::liste_noms_compris
Referenced by Source_PDF_EF::get_noms_champs_postraitables(), Puissance_Thermique_QC_EF::get_noms_champs_postraitables(), Domaine_dis_base::get_noms_champs_postraitables(), Equation_base::get_noms_champs_postraitables(), Loi_Fermeture_base::get_noms_champs_postraitables(), Milieu_base::get_noms_champs_postraitables(), Operateur_base::get_noms_champs_postraitables(), Source_base::get_noms_champs_postraitables(), Loi_Etat_base::get_noms_champs_postraitables(), Convection_Diffusion_Temperature::get_noms_champs_postraitables(), Convection_Diffusion_Temperature_base::get_noms_champs_postraitables(), Navier_Stokes_std::get_noms_champs_postraitables(), Marqueur_Lagrange_base::get_noms_champs_postraitables(), Traitement_particulier_NS_base::get_noms_champs_postraitables(), Turbulence_paroi_base::get_noms_champs_postraitables(), Turbulence_paroi_scal_base::get_noms_champs_postraitables(), Modele_turbulence_hyd_base::get_noms_champs_postraitables(), Modele_turbulence_scal_base::get_noms_champs_postraitables(), Conduction::get_noms_champs_postraitables(), and Traitement_particulier_Solide_base::get_noms_champs_postraitables().
clear_champs_compris()
template<typename FIELD_TYPE > void Champs_compris_T< FIELD_TYPE >::clear_champs_compris () inline
References Champs_compris_T< FIELD_TYPE >::liste_champs_.
Member Data Documentation
liste_champs_
template<typename FIELD_TYPE > std::unordered_map<std::string, OBS_PTR(FIELD_TYPE)> Champs_compris_T< FIELD_TYPE >::liste_champs_ protected
Referenced by Champs_compris_T< FIELD_TYPE >::clear_champs_compris(), Champs_compris_IJK::liste_noms_compris(), and Champs_compris_IJK::switch_ft_fields().