CEA TRUST Platform: Champ_Face_PolyMAC_P0 Class Reference
Champ_Face_PolyMAC_P0 Class Reference
Public Member Functions
Champ_base & affecter_ (const Champ_base &) override
void init_ve2 () const
int reprendre (Entree &fich) override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
void update_ve (DoubleTab &val) const
void update_ve2 (DoubleTab &val, int incr=0) const
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
Public Member Functions inherited from Champ_Face_PolyMAC_P0P1NC
int reprendre (Entree &fich) override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
Public Member Functions inherited from Champ_Face_PolyMAC
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Champ correspondant a une inconnue decrite par ses tangentes aux faces duales (ligne amont-aval, type vitesse) Les flux aux faces sont accessibles par les methodes valeurs_normales(), avec synchro automatique Degres de libertes : composantes tangentielles aux faces duales
Member Function Documentation
domaine_PolyMAC_P0()
const Domaine_PolyMAC_P0& Champ_Face_PolyMAC_P0::domaine_PolyMAC_P0 () const inline
Referenced by affecter_(), fixer_nb_valeurs_nodales(), init_auxiliary_variables(), init_ve2(), trace(), update_ve(), update_ve2(), v_norm(), valeur_aux_elems(), valeur_aux_elems_compo(), and valeur_aux_elems_passe().
fixer_nb_valeurs_nodales()
int Champ_Face_PolyMAC_P0::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_Face_PolyMAC.
References Champ_Inc_base::creer_tableau_distribue(), Objet_U::dimension, domaine_PolyMAC_P0(), and Field_base::nb_compo_.
init_auxiliary_variables()
void Champ_Face_PolyMAC_P0::init_auxiliary_variables () override virtual
Reimplemented from Champ_Face_PolyMAC_P0P1NC.
References domaine_PolyMAC_P0(), Champ_Inc_base::futur(), Champ_Inc_base::nb_valeurs_temporelles(), TRUSTTab< _TYPE_, _SIZE_ >::resize_dim0(), TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector(), and update_ve().
Referenced by affecter_(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Grad_PolyMAC_P0_Face::completer(), and Masse_PolyMAC_P0_Face::completer().
reprendre()
int Champ_Face_PolyMAC_P0::reprendre (Entree & fich) override virtual
Lecture d'un champ inconnue a partir d'un flot d'entree en vue d'une reprise.
Parameters
(Entree& fich) un flot d'entree
Returns
(int) renvoie toujours 1
Reimplemented from Champ_Inc_base.
References Champ_Inc_base::domaine(), MorEqn::equation(), MorEqn::mon_equation_non_nul(), Champ_Inc_base::reprendre(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector(), Champ_Inc_base::valeurs(), and Champ_Inc_base::via_ch_fonc_reprise().
valeur_aux_elems()
DoubleTab & Champ_Face_PolyMAC_P0::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_Face_PolyMAC.
References domaine_PolyMAC_P0(), Champ_Face_PolyMAC::le_champ(), Champ_Face_PolyMAC::valeur_aux_elems_(), and Champ_Inc_base::valeurs().
valeur_aux_elems_passe()
DoubleTab & Champ_Face_PolyMAC_P0::valeur_aux_elems_passe (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const override virtual
Reimplemented from Champ_Face_PolyMAC.
References domaine_PolyMAC_P0(), Champ_Face_PolyMAC::le_champ(), Champ_Inc_base::passe(), Champ_Face_PolyMAC::valeur_aux_elems_(), and Champ_Inc_base::valeurs().
valeur_aux_elems_compo()
DoubleVect & Champ_Face_PolyMAC_P0::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_Face_PolyMAC.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Objet_U::dimension, domaine_PolyMAC_P0(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_VF::nb_faces_tot(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), update_ve(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), and Champ_Inc_base::valeurs().
trace()
DoubleTab & Champ_Face_PolyMAC_P0::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Reimplemented from Champ_Face_PolyMAC.
References Objet_U::dimension, Champ_Inc_base::domaine(), domaine_PolyMAC_P0(), Champ_Face_PolyMAC::le_champ(), Field_base::nb_comp(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Champ_Face_PolyMAC_P0P1NC::trace(), and Champ_Inc_base::valeurs().
affecter_()
Champ_base & Champ_Face_PolyMAC_P0::affecter_ (const Champ_base & ch) override virtual
Affectation d'un OWN_PTR(Champ_base) generique (Champ_base) dans un champ inconnue.
Parameters
(Champ_base& ch) le champ partie droite de l'affectation
Returns
(Champ_base&) le resultat de l'affectation (*this)
Reimplemented from Champ_Face_PolyMAC.
References Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_Inc_base::domaine(), domaine_PolyMAC_P0(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), init_auxiliary_variables(), Champ_Inc_base::les_valeurs, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Roue::nb_cases(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), update_ve(), Champ_base::valeur_aux(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
update_ve()
void Champ_Face_PolyMAC_P0::update_ve (DoubleTab & val) const
Interpolates face-based velocity to element centers using a first-order method.
Computes the element-based velocity components by performing a weighted average of neighboring face velocities, projected onto the vector from face center to element center.
This method uses a first-order accurate stencil and does not include boundary corrections.
Parameters
[out] val Output field containing element-centered velocity components in the last D * number_of_elements entries.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), domaine_PolyMAC_P0(), MorEqn::equation(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), MorEqn::mon_equation_non_nul(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), and Champ_Inc_base::valeurs().
Referenced by affecter_(), Masse_PolyMAC_P0_Face::corriger_solution(), init_auxiliary_variables(), and valeur_aux_elems_compo().
init_ve2()
void Champ_Face_PolyMAC_P0::init_ve2 () const
Initializes second-order interpolation coefficients from faces to element centers.
This routine computes the interpolation stencil and weights for reconstructing the velocity at element centers with second-order accuracy.
Builds a least-squares system to correct the first-order estimate.
Handles internal and boundary faces (Neumann, Dirichlet).
Uses extended connectivity (neighboring elements via shared vertices).
Resulting coefficients are stored internally for later use in update_ve2().
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), domaine_PolyMAC_P0(), MorEqn::equation(), Champ_Face_base::fcl_, Champ_Face_base::init_fcl(), Matrice33::inverse(), Domaine_32_64< _SIZE_ >::les_elems(), Equation_base::milieu(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_som(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Inc_base::valeurs(), ve2bc, ve2bj, ve2c, ve2d, and ve2j.
Referenced by update_ve2().
update_ve2()
void Champ_Face_PolyMAC_P0::update_ve2 (DoubleTab & val, int incr = 0) const
Applies the second-order interpolation from face velocities to element centers.
Uses coefficients computed by init_ve2() to interpolate the face-based velocity field into element-centered values. Supports both internal faces and Dirichlet boundary conditions.
Parameters
[out] val Interpolated velocity at element centers. The last D * number_of_elements entries are updated.
[in] incr If non-zero, Dirichlet boundary contributions are ignored (for incremental updates).
References Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_Cl_dis(), domaine_PolyMAC_P0(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Face_base::fcl_, Champ_Face_base::init_fcl(), init_ve2(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem(), Champ_Inc_base::valeurs(), ve2bc, ve2bj, ve2c, ve2d, and ve2j.
Referenced by Masse_PolyMAC_P0_Face::corriger_solution().
v_norm()
double Champ_Face_PolyMAC_P0::v_norm (const DoubleTab & val, const DoubleTab & val_f, int e, int f, int k, int l, double * v_ext, double * dnv) const inline
References Objet_U::dimension, Champ_Inc_base::domaine(), and domaine_PolyMAC_P0().
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), and Portance_interfaciale_PolyMAC_P0::mettre_a_jour().
Member Data Documentation
ve2d
IntTab Champ_Face_PolyMAC_P0::ve2d mutable
Referenced by init_ve2(), and update_ve2().
ve2j
IntTab Champ_Face_PolyMAC_P0::ve2j
Referenced by init_ve2(), and update_ve2().
ve2bj
IntTab Champ_Face_PolyMAC_P0::ve2bj
Referenced by init_ve2(), and update_ve2().
ve2c
DoubleTab Champ_Face_PolyMAC_P0::ve2c mutable
Referenced by init_ve2(), and update_ve2().
ve2bc
DoubleTab Champ_Face_PolyMAC_P0::ve2bc
Referenced by init_ve2(), and update_ve2().