CEA TRUST Platform: Matrice Class Reference
Matrice Class Reference
#include <Matrice.h>
Detailed Description
Un objet de type Matrice peut referencer n'importe quel objet derivant de Matrice_Base. La plupart des methodes appellent les methodes de l'objet Probleme sous-jacent via la methode valeur()
Dans les commentaires des methodes A represente un objet Matrice.
Constructor & Destructor Documentation
Matrice()
Matrice::Matrice (const Matrice &) default
Member Function Documentation
operator=() [1/2]
Matrice & Matrice::operator= (const Matrice & matrix)
References operator=().
Referenced by operator=(), and operator=().
operator=() [2/2]
Matrice & Matrice::operator= (const Matrice_Base & matrix)
References operator=().
operator*=()
void Matrice::operator*= (const double & x) inline