CEA TRUST Platform: ScatterMED Class Reference
ScatterMED Class Reference
#include <ScatterMED.h>
Public Member Functions
void lire_domaine (Nom &, Noms &liste_bords_periodiques) override
Public Member Functions inherited from Scatter
Entree & interpreter (Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Scatter
static void ajouter_joints (Domaine &domaine, ArrOfInt &pe_voisins)
static void calculer_espace_distant (Domaine &domaine, const int nb_items_reels, const ArrsOfInt &items_to_send, const JOINT_ITEM type_item)
static void calculer_espace_distant_elements (Domaine &dom)
static void calculer_espace_distant_sommets (Domaine &dom, const Noms &liste_bords_periodiques)
static void calculer_nb_items_virtuels (Joints &joints, const JOINT_ITEM type_item)
static void calculer_renum_items_communs (Joints &joints, const JOINT_ITEM type_item)
static void check_consistancy_remote_items (Domaine &dom, const ArrOfInt &mergedDomaines)
static int Chercher_Correspondance (const DoubleTab &sommets1, const DoubleTab &sommets2, ArrOfInt &correspondance, const double epsilon)
static void construire_correspondance_aretes_par_coordonnees (Domaine_VF &zvf)
static void construire_correspondance_sommets_par_coordonnees (Domaine &dom)
static void construire_espace_virtuel_traduction (const MD_Vector &md_indice, const MD_Vector &md_valeur, IntTab &tableau, const int error_is_fatal=1)
static void construire_structures_paralleles (Domaine &dom, const Noms &liste_bords_perio)
static void corriger_espace_distant_elements_perio (Domaine &dom, const Noms &liste_bords_periodiques)
template<typename _SIZE_ >
static void init_sequential_domain (Domaine_32_64< _SIZE_ > &dom)
static void reordonner_faces_de_joint (Domaine &dom)
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Scatter
void read_domain_no_comm (Entree &fic)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
lire_domaine()
void ScatterMED::lire_domaine (Nom & nomentree, Noms & liste_bords_periodiques) override virtual
Lit le domaine dans le fichier de nom "nomentree", de type LecFicDistribueBin ou LecFicDistribue.
(selon fichier_domaine_format_binaire_) Le format historique n'est plus supporte. Format attendu : Domaine::ReadOn le Domaine est renomme comme le domaine (pour lance_test_seq_par)
Reimplemented from Scatter.
References Interprete_geometrique_base_32_64< _SIZE_ >::associer_domaine(), Process::barrier(), Scatter::domaine(), LireMED_32_64< _SIZE_ >::lire_geom(), Process::me(), Nom::nom_me(), and Nom::prefix().