CEA TRUST Platform: Op_Diff_PolyMAC_P0P1NC_base Class Reference
Op_Diff_PolyMAC_P0P1NC_base Class Reference abstract
Public Member Functions
void completer () override
void mettre_a_jour (double t) override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
Classe de base des operateurs de diffusion PolyMAC_P0P1NC
Member Function Documentation
completer()
void Op_Diff_PolyMAC_P0P1NC_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_PolyMAC_P0P1NC_Face, and Op_Diff_PolyMAC_P0P1NC_Elem.
References Operateur_base::completer(), Op_Diff_PolyMAC_Gen_base::diffusivite(), Objet_U::dimension, Op_Diff_PolyMAC_Gen_base::dimension_min_nu(), MorEqn::equation(), Process::exit(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Op_Diff_PolyMAC_Gen_base::nu_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::completer(), and Op_Diff_PolyMAC_P0P1NC_Face::completer().
mettre_a_jour()
void Op_Diff_PolyMAC_P0P1NC_base::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
References Operateur_base::mettre_a_jour(), Op_Diff_PolyMAC_Gen_base::nu_a_jour_, Op_Diff_PolyMAC_Gen_base::nu_constant_, and t_last_nu_.
dimensionner_blocs_ext()
virtual void Op_Diff_PolyMAC_P0P1NC_base::dimensionner_blocs_ext (int aux_only, matrices_t matrices, const tabs_t & semi_impl = { }) const pure virtual
Implemented in Op_Diff_PolyMAC_P0P1NC_Face, and Op_Diff_PolyMAC_P0P1NC_Elem.
Referenced by update_aux().
ajouter_blocs_ext()
virtual void Op_Diff_PolyMAC_P0P1NC_base::ajouter_blocs_ext (int aux_only, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const pure virtual
Implemented in Op_Diff_PolyMAC_P0P1NC_Face, and Op_Diff_PolyMAC_P0P1NC_Elem.
Referenced by update_aux().
has_interface_blocs()
int Op_Diff_PolyMAC_P0P1NC_base::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_PolyMAC_P0P1NC_Face.
dimensionner_blocs()
void Op_Diff_PolyMAC_P0P1NC_base::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const inline override virtual
Reimplemented from Operateur_base.
ajouter_blocs()
void Op_Diff_PolyMAC_P0P1NC_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const inline override virtual
Reimplemented from Operateur_base.
update_nu()
void Op_Diff_PolyMAC_P0P1NC_base::update_nu () const override virtual
Implements Op_Diff_PolyMAC_Gen_base.
References Process::abort(), TRUSTArray< _TYPE_, _SIZE_ >::addr(), Op_Diff_PolyMAC_Gen_base::diffusivite(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Op_Diff_PolyMAC_Gen_base::modifier_mu(), Op_Diff_PolyMAC_Gen_base::nu_, Op_Diff_PolyMAC_Gen_base::nu_a_jour_, Milieu_base::porosite_elem(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), and Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext().
update_aux()
void Op_Diff_PolyMAC_P0P1NC_base::update_aux (double t) const protected
References MD_Vector_composite::add_part(), ajouter_blocs_ext(), Matrice_Base::ajouter_multvect(), MD_Vector::copy(), MD_Vector_tools::creer_tableau_distribue(), Matrice_Bloc::dimensionner(), dimensionner_blocs_ext(), MorEqn::equation(), Matrice_Bloc::get_bloc(), Nom::getString(), Equation_base::inconnue(), Objet_U::le_nom(), mat_aux, Matrice_Bloc::nb_lignes(), Operateur_Diff_base::op_ext, SolveurSys::resoudre_systeme(), solv_aux, t_last_aux_, use_aux_, and var_aux.
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), and Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext().
Member Data Documentation
t_last_nu_
double Op_Diff_PolyMAC_P0P1NC_base::t_last_nu_ = -1e10 protected
Referenced by mettre_a_jour().
t_last_aux_
double Op_Diff_PolyMAC_P0P1NC_base::t_last_aux_ = -1e10 mutable protected
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), and update_aux().
use_aux_
int Op_Diff_PolyMAC_P0P1NC_base::use_aux_ = 0 mutable protected
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), and update_aux().
mat_aux
Matrice_Bloc Op_Diff_PolyMAC_P0P1NC_base::mat_aux mutable protected
Referenced by update_aux().
var_aux
DoubleTab Op_Diff_PolyMAC_P0P1NC_base::var_aux mutable protected
Referenced by Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), and update_aux().
solv_aux
SolveurSys Op_Diff_PolyMAC_P0P1NC_base::solv_aux mutable protected
Referenced by update_aux().