CEA TRUST Platform: FichierHDFPar Class Reference
FichierHDFPar Class Reference
Constructor & Destructor Documentation
FichierHDFPar()
FichierHDFPar::FichierHDFPar ()
References Process::exit().
~FichierHDFPar()
FichierHDFPar::~FichierHDFPar () override
Member Function Documentation
set_collective_op()
void FichierHDFPar::set_collective_op (bool b) inline
prepare_file_props()
void FichierHDFPar::prepare_file_props () override protected virtual
Reimplemented from FichierHDF.
References FichierHDF::prepare_file_props().
prepare_dataset_props()
void FichierHDFPar::prepare_dataset_props () override protected virtual
Reimplemented from FichierHDF.
References FichierHDF::prepare_dataset_props().