CEA TRUST Platform: TRUSTChamp_Divers_generique< _TYPE_ > Class Template Reference
TRUSTChamp_Divers_generique< _TYPE_ > Class Template Reference
#include <TRUSTChamp_Divers_generique.h>
Public Member Functions
DoubleVect & valeur_a (const DoubleVect &, DoubleVect &tab_valeurs) const override
double valeur_a_compo (const DoubleVect &x, int ncomp) const override
DoubleVect & valeur_a_elem (const DoubleVect &positions, DoubleVect &tab_valeurs, int) const override
double valeur_a_elem_compo (const DoubleVect &, int, int ncomp) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &, DoubleVect &tab_valeurs, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &, DoubleVect &tab_valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
affecter()
template<Champ_Divers_Type _TYPE_> Champ_base & TRUSTChamp_Divers_generique< _TYPE_ >::affecter (const Champ_base & ch) inline
References Champ_base::affecter(), and Champ_base::affecter_erreur().
valeur_a()
template<Champ_Divers_Type _TYPE_> DoubleVect & TRUSTChamp_Divers_generique< _TYPE_ >::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const inline override virtual
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle valeur_aux(const DoubleTab &, DoubleTab &)
Parameters
(DoubleVect&) les coordonnees du point ou evaluer le champ
(DoubleVect& valeurs) En entree: doit avoir la bonne taille (nb_comp), en sortie contient les composantes du champ.
Returns
(reference a "valeurs")
Reimplemented from Champ_base.
References Field_base::nb_comp(), and Champ_Don_base::valeurs_.
Referenced by TRUSTChamp_Divers_generique< _TYPE_ >::valeur_a_elem().
valeur_a_compo()
template<Champ_Divers_Type _TYPE_> double TRUSTChamp_Divers_generique< _TYPE_ >::valeur_a_compo (const DoubleVect & pos, int compo) const inline override virtual
Calcule la valeur ponctuelle de la composante "compo" du champ au point de coordonnees pos.
Dans la classe de base, l'implementation appelle valeur_a(const DoubleVect &, DoubleVect &)
Parameters
(DoubleVect&) les coordonnees du point de calcul
(int) l'index de la composante du champ a calculer
Returns
(double)
Reimplemented from Champ_base.
References Champ_base::valeur_a_compo(), and Champ_Don_base::valeurs_.
valeur_a_elem()
template<Champ_Divers_Type _TYPE_> DoubleVect & TRUSTChamp_Divers_generique< _TYPE_ >::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
References Field_base::nb_comp(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_a(), and Champ_Don_base::valeurs_.
valeur_a_elem_compo()
template<Champ_Divers_Type _TYPE_> double TRUSTChamp_Divers_generique< _TYPE_ >::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
References Champ_Don_base::valeurs_.
valeur_aux()
template<Champ_Divers_Type _TYPE_> DoubleTab & TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const inline override virtual
Provoque une erreur ! Doit etre surchargee par les classes derivees.
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References TRUSTArray< _TYPE_, _SIZE_ >::checkDataOnDevice(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nb_comp(), Champ_Don_base::valeurs(), and Champ_Don_base::valeurs_.
Referenced by TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems().
valeur_aux_compo()
template<Champ_Divers_Type _TYPE_> DoubleVect & TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const inline override virtual
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle valeur_aux(const DoubleTab &, DoubleTab &)
Parameters
(pos) le tableau des coordonnees des points de calcul (on ne traite pas l'espace virtuel du tableau)
(les_valeurs) tableau destination des valeurs a calculer. Le tableau valeurs doit avoir la bonne taille en entree, soit les_valeurs.size() == pos.dimension(0)
(compo) l'index de la composante du champ a calculer
Returns
(reference au tableau les_valeurs)
Reimplemented from Champ_base.
References Champ_Don_base::valeurs_.
Referenced by TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems_compo().
valeur_aux_elems()
template<Champ_Divers_Type _TYPE_> DoubleTab & TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References TRUSTArray< _TYPE_, _SIZE_ >::checkDataOnDevice(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nb_comp(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), Champ_Don_base::valeurs(), and Champ_Don_base::valeurs_.
valeur_aux_elems_compo()
template<Champ_Divers_Type _TYPE_> DoubleVect & TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_base.
References TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_compo(), and Champ_Don_base::valeurs_.