CEA TRUST Platform: Perte_Charge_Anisotrope_PolyMAC_Face Class Reference
Perte_Charge_Anisotrope_PolyMAC_Face Class Reference
#include <Perte_Charge_Anisotrope_PolyMAC_Face.h>
Detailed Description
Correspond a la somme d'une perte de charge d'intensite lambda dans la direction de v, et d'une perte de charge d'intensite lambda_ortho pour toute direction orthogonale a v.
Ou de facon equivalente a la somme d'une perte de charge isotrope d'intensite lambda_ortho, et d'une perte de charge directionnelle de vecteur v et d'intensite lamba - lambda_ortho. C'est ainsi que le calcul est code.
du/dt =
lambda_ortho(Re,x,y,z,t) * u * ||u|| / 2 Dh
(lambda(Re,x,y,z,t)-lambda_ortho(Re,x,y,z,t)) u.v * v * ||u|| / 2 Dh ||v||^2
Lecture des arguments :
Perte_Charge_Anisotrope_PolyMAC_Face diametre_hydraulique { lambda expression(Re,x,y,z,t) lambda_ortho expression(Re,x,y,z,t) diam_hydr champ_don direction champ_don [sous_domaine nom] }
Member Function Documentation
mettre_a_jour()
void Perte_Charge_Anisotrope_PolyMAC_Face::mettre_a_jour (double temps) inline override
set_param()
void Perte_Charge_Anisotrope_PolyMAC_Face::set_param (Param & titi) override protected
References Param::ajouter(), Param::ajouter_non_std(), and Param::REQUIRED.
lire_motcle_non_standard()
int Perte_Charge_Anisotrope_PolyMAC_Face::lire_motcle_non_standard (const Motcle & mot, Entree & is) override protected
References Parser_U::addVar(), Parser_U::parseString(), Parser_U::setNbVar(), and Parser_U::setString().
coeffs_perte_charge()
void Perte_Charge_Anisotrope_PolyMAC_Face::coeffs_perte_charge (const DoubleVect & u, const DoubleVect & pos, double t, double norme_u, double dh, double nu, double reynolds, double & coeff_ortho, double & coeff_long, double & u_l, DoubleVect & v_valeur) const override protected
Implemente le calcul effectif de la perte de charge pour un lieu donne.
References Parser_U::eval(), and Parser_U::setVar().