CEA TRUST Platform: EDO_Pression_th_VDF_Gaz_Reel Class Reference
EDO_Pression_th_VDF_Gaz_Reel Class Reference
#include <EDO_Pression_th_VDF_Gaz_Reel.h>
Public Member Functions
double resoudre (double) override
Public Member Functions inherited from EDO_Pression_th_VDF
double masse_totale (double P, const DoubleTab &T) override
Detailed Description
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VDF et pour les gaz reels.
See also
Fluide_Quasi_Compressible EDO_Pression_th_base
Member Function Documentation
resoudre() [1/2]
double EDO_Pression_th_VDF_Gaz_Reel::resoudre (double Pth_n) override
Resoud l'EDO.
Parameters
(double Pth_n) La pression a l'etape precedente
Returns
(double) La nouvelle valeur de la pression
References EDO_Pression_th_VDF::calculer_grad(), Domaine_VDF::dim_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_front_Cl(), Navier_Stokes_std::vitesse(), and Domaine_VF::volumes().
resoudre() [2/2]
void EDO_Pression_th_VDF_Gaz_Reel::resoudre (DoubleTab &) inline override
References Process::exit().