CEA TRUST Platform: Matrice_Grossiere Class Reference
Matrice_Grossiere Class Reference
#include <Matrice_Grossiere.h>
Member Function Documentation
build_matrix()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Matrice_Grossiere::build_matrix (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & coeffs_face)
References add_dist_bloc(), add_virt_bloc(), ajoute_coeff(), coeff_diag_, coeffs_, coeffs_virt_, MD_Vector::copy(), defilement_, Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), TRUSTLists< _TYPE_ >::dimensionner(), Matrice_Bloc::get_bloc(), MD_Vector_base::get_nb_items_reels(), MD_Vector_base::get_nb_items_tot(), ii_m_, ii_p_, interpolation_for_shear_periodicity(), mat_, md_, Process::me(), order_interpolation_poisson_solver_, ponderation_shear_m_, ponderation_shear_p_, Matrice_Morse::remplir(), renum(), renum_, TRUSTVect< _TYPE_, _SIZE_ >::reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), shear_x_time_, voisins_, and voisins_virt_.
Referenced by Multigrille_Adrien::multigrille_failure(), Multigrille_Adrien::set_inv_rho_template(), and Multigrille_Adrien::set_rho_template().
renum() [1/2]
const int & Matrice_Grossiere::renum (int i, int j, int k) const inline
References renum_.
Referenced by add_dist_bloc(), add_virt_bloc(), ajoute_coeff(), ajoute_coeff(), build_matrix(), and Multigrille_base::coarse_solver().
matrice()
const Matrice_Base & Matrice_Grossiere::matrice () const inline
References mat_.
Referenced by Multigrille_base::coarse_solver().
md_vector()
const MD_Vector & Matrice_Grossiere::md_vector () const inline
References md_.
Referenced by Multigrille_base::coarse_solver().
ajoute_coeff() [1/2]
void Matrice_Grossiere::ajoute_coeff (int i, int j, int k, int i_voisin, int j_voisin, int k_voisin, const double coeff, const double shear_perio) protected
ajoute deux coefficients diagonal/extra-diagonal a la matrice
References coeff_diag_, coeffs_, coeffs_virt_, ii_m_, ii_p_, order_interpolation_poisson_solver_, ponderation_shear_m_, ponderation_shear_p_, renum(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), voisins_, and voisins_virt_.
Referenced by build_matrix().
ajoute_coeff() [2/2]
void Matrice_Grossiere::ajoute_coeff (int i, int j, int k, int i_voisin, int j_voisin, int k_voisin, const double coeff) protected
References coeff_diag_, coeffs_, coeffs_virt_, renum(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), voisins_, and voisins_virt_.
renum() [2/2]
int & Matrice_Grossiere::renum (int i, int j, int k) inline protected
References renum_.
add_virt_bloc()
void Matrice_Grossiere::add_virt_bloc (int pe, int & count, int imin, int jmin, int kmin, int imax, int jmax, int kmax, ArrOfInt & virt_blocs) protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::me(), renum(), and renum_.
Referenced by build_matrix().
add_dist_bloc()
void Matrice_Grossiere::add_dist_bloc (int pe, int imin, int jmin, int kmin, int imax, int jmax, int kmax, ArrOfInt & items_to_send) protected
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Process::me(), and renum().
Referenced by build_matrix().
interpolation_for_shear_periodicity()
void Matrice_Grossiere::interpolation_for_shear_periodicity (const int i, const int send_i, const double istmp, const int real_size_i, const double shear_perio) protected
References ii_m_, ii_p_, order_interpolation_poisson_solver_, ponderation_shear_m_, ponderation_shear_p_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by build_matrix().
Member Data Documentation
mat_
Matrice_Bloc Matrice_Grossiere::mat_ protected
Referenced by build_matrix(), and matrice().
md_
MD_Vector Matrice_Grossiere::md_ protected
Referenced by build_matrix(), and md_vector().
shear_x_time_
double Matrice_Grossiere::shear_x_time_ protected
Referenced by build_matrix().
defilement_
int Matrice_Grossiere::defilement_ protected
Referenced by build_matrix().
order_interpolation_poisson_solver_
int Matrice_Grossiere::order_interpolation_poisson_solver_ protected
Referenced by ajoute_coeff(), build_matrix(), and interpolation_for_shear_periodicity().
renum_
IntTab Matrice_Grossiere::renum_ protected
Referenced by add_virt_bloc(), build_matrix(), renum(), and renum().
ii_p_
ArrOfInt Matrice_Grossiere::ii_p_ protected
Referenced by ajoute_coeff(), build_matrix(), and interpolation_for_shear_periodicity().
ii_m_
ArrOfInt Matrice_Grossiere::ii_m_ protected
Referenced by ajoute_coeff(), build_matrix(), and interpolation_for_shear_periodicity().
ponderation_shear_p_
ArrOfDouble Matrice_Grossiere::ponderation_shear_p_ protected
Referenced by ajoute_coeff(), build_matrix(), and interpolation_for_shear_periodicity().
ponderation_shear_m_
ArrOfDouble Matrice_Grossiere::ponderation_shear_m_ protected
Referenced by ajoute_coeff(), build_matrix(), and interpolation_for_shear_periodicity().
voisins_
IntLists Matrice_Grossiere::voisins_ protected
Referenced by ajoute_coeff(), ajoute_coeff(), and build_matrix().
coeffs_
DoubleLists Matrice_Grossiere::coeffs_ protected
Referenced by ajoute_coeff(), ajoute_coeff(), and build_matrix().
coeff_diag_
DoubleVect Matrice_Grossiere::coeff_diag_ protected
Referenced by ajoute_coeff(), ajoute_coeff(), and build_matrix().
voisins_virt_
IntLists Matrice_Grossiere::voisins_virt_ protected
Referenced by ajoute_coeff(), ajoute_coeff(), and build_matrix().
coeffs_virt_
DoubleLists Matrice_Grossiere::coeffs_virt_ protected
Referenced by ajoute_coeff(), ajoute_coeff(), and build_matrix().