CEA TRUST Platform: Traitement_particulier_NS_EC Class Reference
Traitement_particulier_NS_EC Class Reference
Protected Member Functions
virtual void calculer_Ec (double &)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
pour les calculs de  l'energie cinetique totale
See also
Navier_Stokes_Turbulent, Traitement_particulier_base, Traitement_particulier_VEF
Constructor & Destructor Documentation
~Traitement_particulier_NS_EC()
Traitement_particulier_NS_EC::~Traitement_particulier_NS_EC () inline override
Traitement_particulier_NS_EC()
Traitement_particulier_NS_EC::Traitement_particulier_NS_EC () inline
Member Function Documentation
lire()
Entree & Traitement_particulier_NS_EC::lire (Entree & is) override virtual
Implements Traitement_particulier_NS_base.
References Process::exit(), periode, repere_mobile_, and Motcles::search().
preparer_calcul_particulier()
void Traitement_particulier_NS_EC::preparer_calcul_particulier () override virtual
Implements Traitement_particulier_NS_base.
References calculer_Ec(), Process::je_suis_maitre(), nb_bip, ouvrir_fichier(), and tinit.
post_traitement_particulier()
void Traitement_particulier_NS_EC::post_traitement_particulier () override virtual
Implements Traitement_particulier_NS_base.
References calculer_Ec(), Process::je_suis_maitre(), nb_bip, ouvrir_fichier(), periode, and tinit.
en_cours_de_resolution()
void Traitement_particulier_NS_EC::en_cours_de_resolution (int , DoubleTab & , DoubleTab & , double) inline override virtual
Implements Traitement_particulier_NS_base.
sauver_stat()
void Traitement_particulier_NS_EC::sauver_stat () const inline override virtual
Implements Traitement_particulier_NS_base.
reprendre_stat()
void Traitement_particulier_NS_EC::reprendre_stat () inline override virtual
Implements Traitement_particulier_NS_base.
a_pour_Champ_Fonc()
int Traitement_particulier_NS_EC::a_pour_Champ_Fonc (const Motcle & mot, OBS_PTR(Champ_base)& ch_ref) const inline
comprend_champ()
int Traitement_particulier_NS_EC::comprend_champ (const Motcle & mot) const inline
ouvrir_fichier()
void Traitement_particulier_NS_EC::ouvrir_fichier (SFichier & s) const protected
References nb_bip, Objet_U::nom_du_cas(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), repere_mobile_, Probleme_base::reprise_effectuee(), and Sortie_Fichier_base::setf().
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
calculer_Ec()
void Traitement_particulier_NS_EC::calculer_Ec (double & energie_cinetique) protected virtual
Meme methode de calcul en VDF et en VEF.
Si aucun champ de masse volumique n'a ete associe, on calcule INTEGRALE de 1/2 * u^2 sur le domaine. Si un champ de masse volumique a ete associe, il doit etre de type "champ aux faces". On calcule INTEGRALE de 1/2 * rho * u^2. rho est un champ P0 aux elements, u est P0 sur les volumes entrelaces Valeur de retour: La somme sur tous les processeurs de l'integrale de 1/2*rho*u*u.
References Terme_Source_Acceleration::champ_vitesse(), Objet_U::dimension, Process::exit(), Domaine_VF::faces_doubles(), Domaine_VF::front_VF(), Frontiere_dis_base::frontiere(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Terme_Source_Acceleration::has_champ_vitesse(), Terme_Source_Acceleration::has_omega(), Process::mp_sum(), Frontiere_32_64< _SIZE_ >::nb_faces(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_internes(), Domaine_dis_base::nb_front_Cl(), Frontiere_32_64< _SIZE_ >::num_premiere_face(), Traitement_particulier_NS_base::OBS_PTR(), Terme_Source_Acceleration::omega(), Domaine_VF::premiere_face_int(), repere_mobile_, Champ_Don_base::valeurs(), Champ_Proto::valeurs(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xv().
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
Member Data Documentation
periode
double Traitement_particulier_NS_EC::periode = -100. protected
Referenced by lire(), and post_traitement_particulier().
tinit
double Traitement_particulier_NS_EC::tinit = -100. protected
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
nb_bip
double Traitement_particulier_NS_EC::nb_bip = 0. protected
Referenced by ouvrir_fichier(), post_traitement_particulier(), and preparer_calcul_particulier().
repere_mobile_
int Traitement_particulier_NS_EC::repere_mobile_ = 0 protected
Referenced by calculer_Ec(), lire(), and ouvrir_fichier().