CEA TRUST Platform: Operateur_Grad Class Reference
Operateur_Grad Class Reference
Public Member Functions
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
const Operateur_base & l_op_base () const override
Operateur_base & l_op_base () override
void typer () override
Public Member Functions inherited from Operateur
DoubleTab & ajouter (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & ajouter (DoubleTab &) const
DoubleTab & calculer (const Champ_Inc_base &, DoubleTab &) const
DoubleTab & calculer (DoubleTab &) const
virtual void completer ()
const Discretisation_base & discretisation () const
int impr (Sortie &os) const
void imprimer (Sortie &os) const
int limpr () const
Entree & lire (Entree &)
virtual void mettre_a_jour (double temps)
const Champ_Inc_base & mon_inconnue () const
const Nom & type () const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Detailed Description
d'un champ. Un objet Operateur_Grad peut referencer n'importe quel objet derivant de Operateur_Grad_base.
See also
Operateur_Grad_base Operateur
Member Function Documentation
l_op_base() [1/2]
Operateur_base & Operateur_Grad::l_op_base () inline override virtual
Renvoie l'objet sous-jacent upcaste en Operateur_base.
Returns
(Operateur_base&) l'objet sous-jacent upcaste en Operateur_base
Implements Operateur.
Referenced by Convection_Diffusion_Chaleur_WC::completer(), Masse_Multiphase::completer(), Champ_Generique_Gradient::completer(), Navier_Stokes_std::discretiser(), and Op_Evanescence_Homogene_VDF_Face::preparer_calcul().
l_op_base() [2/2]
const Operateur_base & Operateur_Grad::l_op_base () const inline override virtual
Renvoie l'objet sous-jacent upcaste en Operateur_base (version const)
Returns
(Operateur_base&) l'objet sous-jacent upcaste en Operateur_base
Implements Operateur.
ajouter()
DoubleTab & Operateur_Grad::ajouter (const DoubleTab & donnee, DoubleTab & resu) const override virtual
Ajoute la contribution de l'operateur au tableau passe en parametre.
Parameters
(DoubleTab& donnee) tableau contenant les donnees sur lesquelles on applique l'operateur.
(DoubleTab& resu) tableau auquel on ajoute la contribution de l'operateur
Returns
(DoubleTab&) le tableau contenant le resultat
Implements Operateur.
References Perf_counters::begin_count(), and Perf_counters::end_count().
Referenced by QDM_Multiphase::mettre_a_jour().
calculer()
DoubleTab & Operateur_Grad::calculer (const DoubleTab & donnee, DoubleTab & resu) const override virtual
Initialise le tableau passe en parametre avec la contribution de l'operateur.
Parameters
(DoubleTab& donnee) tableau contenant les donnees sur lesquelles on applique l'operateur.
(DoubleTab& resu) tableau dans lequel stocke la contribution de l'operateur
Returns
(DoubleTab&) le tableau contenant le resultat
Implements Operateur.
References Perf_counters::begin_count(), and Perf_counters::end_count().
Referenced by Dispersion_bulles_VDF::ajouter_blocs(), Op_Evanescence_Homogene_VDF_Face::calc_grad_alpha_faces(), Source_WC_Chaleur_VDF::compute_interpolate_gradP(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Navier_Stokes_std::corriger_derivee_expl(), Navier_Stokes_std::corriger_derivee_impl(), Navier_Stokes_std::derivee_en_temps_inco(), Champ_Generique_Gradient::get_champ(), Navier_Stokes_std::mettre_a_jour(), Navier_Stokes_IBM::preparer_calcul(), and Navier_Stokes_std::preparer_calcul().
typer()
void Operateur_Grad::typer () override virtual
Type l'operateur: se type "Op_Grad_"+discretisation()+.
"_"+inconnue().suffix
Implements Operateur.
References Equation_base::discretisation(), MorEqn::equation(), and Discretisation_base::get_name_of_type_for().
Referenced by Convection_Diffusion_Chaleur_WC::completer(), Masse_Multiphase::completer(), Champ_Generique_Gradient::completer(), Navier_Stokes_std::discretiser(), Op_Evanescence_Homogene_VDF_Face::preparer_calcul(), and typer_direct().
typer_direct()
void Operateur_Grad::typer_direct (const Nom & un_type)
References typer().
op_non_nul()
int Operateur_Grad::op_non_nul () const inline override virtual
Implements Operateur.