CEA TRUST Platform: EOS_Tools_VDF Class Reference
EOS_Tools_VDF Class Reference
#include <EOS_Tools_VDF.h>
Public Member Functions
void divu_discvit (const DoubleTab &, DoubleTab &) override
double moyenne_vol (const DoubleTab &) const override
const DoubleTab & rho_discvit () const override
void secmembre_divU_Z (DoubleTab &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Fluide_Dilatable_base EOS_Tools_base
Member Function Documentation
rho_discvit()
const DoubleTab & EOS_Tools_VDF::rho_discvit () const override virtual
Renvoie rho avec la meme discretisation que la vitesse : une valeur par face en VDF.
Returns
(DoubleTab&) rho discretise par face
Implements EOS_Tools_base.
References tab_rho_face_demi.
associer_domaines()
void EOS_Tools_VDF::associer_domaines (const Domaine_dis_base & dds, const Domaine_Cl_dis_base & domaine_cl) override virtual
Implements EOS_Tools_base.
References Champ_Inc_base::associer_domaine_dis_base(), Field_base::fixer_nb_comp(), Champ_Face_VDF::fixer_nb_valeurs_nodales(), tab_rho_face, tab_rho_face_demi, tab_rho_face_np1, and Champ_Inc_base::valeurs().
divu_discvit()
void EOS_Tools_VDF::divu_discvit (const DoubleTab & secmem1, DoubleTab & secmem2) override virtual
Renvoie div(u) avec la meme discretisation que la vitesse : une valeur par face en VDF.
Returns
div(u) discretise par face
Implements EOS_Tools_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel().
secmembre_divU_Z()
void EOS_Tools_VDF::secmembre_divU_Z (DoubleTab & tab_W) const override virtual
Calcule le second membre de l'equation de continuite : div(rhoU) = W = -dZ/dT avec Z=rho.
Returns
rho discretise par face
Implements EOS_Tools_base.
References MorEqn::equation(), le_fluide(), Schema_Temps_base::pas_de_temps(), Fluide_Dilatable_base::rho_n(), Fluide_Dilatable_base::rho_np1(), Equation_base::schema_temps(), Debog::verifier(), and Fluide_Dilatable_base::vitesse().
mettre_a_jour()
void EOS_Tools_VDF::mettre_a_jour (double temps) override virtual
Reimplemented from EOS_Tools_base.
References TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), tab_rho_face, tab_rho_face_demi, and tab_rho_face_np1.
calculer_rho_face_np1()
void EOS_Tools_VDF::calculer_rho_face_np1 (const DoubleTab & rho) override virtual
Implements EOS_Tools_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), tab_rho_face, tab_rho_face_demi, tab_rho_face_np1, and Debog::verifier().
moyenne_vol()
double EOS_Tools_VDF::moyenne_vol (const DoubleTab & tab) const override virtual
Calcule la moyenne volumique de la grandeur P0 donnee.
Returns
(DoubleTab&) rho discretise par face
Implements EOS_Tools_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
rho_face_n()
const DoubleTab & EOS_Tools_VDF::rho_face_n () const inline override virtual
Implements EOS_Tools_base.
References tab_rho_face.
rho_face_np1()
const DoubleTab & EOS_Tools_VDF::rho_face_np1 () const inline override virtual
Implements EOS_Tools_base.
References tab_rho_face_np1.
le_fluide()
const Fluide_Dilatable_base & EOS_Tools_VDF::le_fluide () const inline
Referenced by secmembre_divU_Z().
OBS_PTR() [1/2]
EOS_Tools_VDF::OBS_PTR (Domaine_VDF) protected
OBS_PTR() [2/2]
EOS_Tools_VDF::OBS_PTR (Domaine_Cl_dis_base) protected
Member Data Documentation
tab_rho_face
DoubleTab EOS_Tools_VDF::tab_rho_face protected
Referenced by associer_domaines(), calculer_rho_face_np1(), mettre_a_jour(), and rho_face_n().
tab_rho_face_demi
DoubleTab EOS_Tools_VDF::tab_rho_face_demi protected
Referenced by associer_domaines(), calculer_rho_face_np1(), mettre_a_jour(), and rho_discvit().
tab_rho_face_np1
DoubleTab EOS_Tools_VDF::tab_rho_face_np1 protected
Referenced by associer_domaines(), calculer_rho_face_np1(), mettre_a_jour(), and rho_face_np1().