CEA TRUST Platform: Assembleur_P_PolyMAC_P0 Class Reference
Assembleur_P_PolyMAC_P0 Class Reference
#include <Assembleur_P_PolyMAC_P0.h>
Additional Inherited Members
Public Member Functions inherited from Assembleur_P_PolyMAC
int assembler_QC (const DoubleTab &, Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
Public Member Functions inherited from Assembleur_base
int set_resoudre_en_u (int flag)
int set_resoudre_increment_pression (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
assembler_mat()
int Assembleur_P_PolyMAC_P0::assembler_mat (Matrice & la_matrice, const DoubleVect & diag, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_P_PolyMAC.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Statistiques::begin_count(), Statistiques::end_count(), Assembleur_P_PolyMAC::equation(), Op_Grad_PolyMAC_P0_Face::fgrad_c, Op_Grad_PolyMAC_P0_Face::fgrad_d, Op_Grad_PolyMAC_P0_Face::fgrad_e, Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Assembleur_P_PolyMAC::has_P_ref, Process::me(), Equation_base::milieu(), Process::mp_min(), Milieu_base::porosite_face(), TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Matrice_Morse::set_nb_columns(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Matrice_Morse::sort_stencil(), Assembleur_P_PolyMAC::stencil_done, Assembleur_P_PolyMAC::tab1, Assembleur_P_PolyMAC::tab2, and Op_Grad_PolyMAC_P0_Face::update_grad().
dimensionner_continuite()
void Assembleur_P_PolyMAC_P0::dimensionner_continuite (matrices_t matrices, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), and Assembleur_P_PolyMAC::equation().
assembler_continuite()
void Assembleur_P_PolyMAC_P0::assembler_continuite (matrices_t matrices, DoubleTab & secmem, int aux_only = 0) const override virtual
Reimplemented from Assembleur_base.
References Assembleur_P_PolyMAC::equation(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), and Milieu_base::porosite_elem().
modifier_secmem_pour_incr_p()
void Assembleur_P_PolyMAC_P0::modifier_secmem_pour_incr_p (const DoubleTab & press, const double fac, DoubleTab & incr) const inline override virtual
Reimplemented from Assembleur_base.