CEA TRUST Platform: Masse_PolyMAC_P0P1NC_Elem Class Reference
Masse_PolyMAC_P0P1NC_Elem Class Reference
#include <Masse_PolyMAC_P0P1NC_Elem.h>
Additional Inherited Members
Public Member Functions inherited from Solveur_Masse_base
virtual DoubleTab & appliquer (DoubleTab &) const
virtual void assembler ()
virtual void mettre_a_jour (double temps)
virtual void resetTime (double temps)
void set_name_of_coefficient_temporel (const Nom &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
preparer_calcul()
void Masse_PolyMAC_P0P1NC_Elem::preparer_calcul () override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_Elem_proto::associer_masse_proto(), and Solveur_Masse_Elem_proto::preparer_calcul_proto().
appliquer_impl()
DoubleTab & Masse_PolyMAC_P0P1NC_Elem::appliquer_impl (DoubleTab & sm) const override virtual
Implements Solveur_Masse_base.
References Solveur_Masse_Elem_proto::appliquer_impl_proto().
dimensionner_blocs()
void Masse_PolyMAC_P0P1NC_Elem::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_Elem_proto::dimensionner_blocs_proto().
ajouter_blocs()
void Masse_PolyMAC_P0P1NC_Elem::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_Elem_proto::ajouter_blocs_proto().