CEA TRUST Platform: Neumann Class Reference
Neumann Class Reference
Public Member Functions
const DoubleTab & flux_impose (bool nb_faces_tot=false) const
virtual double flux_impose (int i) const
virtual double flux_impose (int i, int j) const
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Une condition aux limites de type Neumann impose la valeur de la derivee d'un champ inconnue sur une frontiere, ce qui correspond a:
flux impose pour l'equation de transport d'un scalaire
contrainte imposee pour l'equation de quantite de mouvement
See also
Cond_lim_base Neumann_homogene
Member Function Documentation
flux_impose() [1/3]
double Neumann::flux_impose (int i) const virtual
Renvoie la valeur du flux impose sur la i-eme composante du champ representant le flux a la frontiere.
Parameters
(int i) indice suivant la premiere dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Exceptions
deuxieme dimension du champ de frontiere superieur a 1
Reimplemented in Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEF, Sortie_libre_Gradient_Pression_impose_VEF, Sortie_libre_Pression_imposee_Orlansky, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Text_H_ext, Sortie_libre_pression_moyenne_imposee, Sortie_libre_pression_imposee, and Sortie_libre_pression_imposee_QC.
References Process::exit().
Referenced by Op_Grad_PolyMAC_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Op_Grad_EF::ajouter_bord(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face(), flux_impose(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_VEF_Face_Gen< DERIVED_T >::modifie_pour_cl_gen(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VDF::modifier_secmem_pression_imposee(), and Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_face().
flux_impose() [2/3]
double Neumann::flux_impose (int i, int j) const virtual
Renvoie la valeur du flux impose sur la (i,j)-eme composante du champ representant le flux a la frontiere.
Parameters
(int i) indice suivant la premiere dimension du champ
(int j) indice suivant la deuxieme dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Reimplemented in Sortie_libre_Gradient_Pression_libre_VEFPreP1B, Sortie_libre_Gradient_Pression_libre_VEF, Sortie_libre_Gradient_Pression_impose_VEF, Sortie_libre_Pression_imposee_Orlansky, Sortie_libre_Gradient_Pression_impose, Sortie_libre_Text_H_ext, Sortie_libre_pression_moyenne_imposee, Sortie_libre_pression_imposee, and Sortie_libre_pression_imposee_QC.
flux_impose() [3/3]
const DoubleTab & Neumann::flux_impose (bool with_virtual_faces = false) const
Updates and returns the imposed flux array.
This function checks the total number of faces in the boundary and resizes the flux_impose_ array if necessary. It updates the values based on the imposed flux from the front field if the field is unsteady or if the dimensions have changed.
Returns
const DoubleTab& Reference to the updated imposed flux array.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), flux_impose(), flux_impose_, Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Member Data Documentation
flux_impose_
DoubleTab Neumann::flux_impose_ mutable protected
Referenced by flux_impose().