CEA TRUST Platform: List_Equations_Scalaires_Passifs_Especes Class Reference
List_Equations_Scalaires_Passifs_Especes Class Reference
#include <List_Equations_Scalaires_Passifs_Especes.h>
Public Member Functions
void discretiser () override
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
List_Equations_Scalaires_Passifs_Especes comprend une liste d'equations
de scalaires passifs ou especes et est vue comme une equation
elle porte une vraie liste d'equations
Member Function Documentation
equation() [1/2]
const Equation_base & List_Equations_Scalaires_Passifs_Especes::equation (int i) const inline
Referenced by associer_milieu_equation(), TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::equation(), and TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::equation().
nb_equation() [1/2]
int List_Equations_Scalaires_Passifs_Especes::nb_equation () inline
Referenced by associer_milieu_equation(), equation(), and TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::nombre_d_equations().
nb_equation() [2/2]
int List_Equations_Scalaires_Passifs_Especes::nb_equation () const inline
complete() [1/2]
int List_Equations_Scalaires_Passifs_Especes::complete () inline
References complet.
Referenced by TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::equation(), and TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::nombre_d_equations().
complete() [2/2]
int List_Equations_Scalaires_Passifs_Especes::complete () const inline
References complet.
discretiser()
void List_Equations_Scalaires_Passifs_Especes::discretiser () inline override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
associer_milieu_equation()
void List_Equations_Scalaires_Passifs_Especes::associer_milieu_equation () override virtual
Reimplemented from Equation_base.
References Equation_base::associer_milieu_equation(), equation(), and nb_equation().
associer_milieu_base()
void List_Equations_Scalaires_Passifs_Especes::associer_milieu_base (const Milieu_base & mil1) inline override virtual
Implements Equation_base.
Referenced by TRUSTProblem_sup_eqns< _DERIVED_TYPE_ >::associer_milieu_base().
milieu() [1/2]
const Milieu_base & List_Equations_Scalaires_Passifs_Especes::milieu () const inline override virtual
Implements Equation_base.
milieu() [2/2]
Milieu_base & List_Equations_Scalaires_Passifs_Especes::milieu () inline override virtual
Implements Equation_base.
nombre_d_operateurs()
int List_Equations_Scalaires_Passifs_Especes::nombre_d_operateurs () const inline override virtual
Implements Equation_base.
equation() [2/2]
Equation_base & List_Equations_Scalaires_Passifs_Especes::equation (int i) inline
References Process::exit(), and nb_equation().
operateur() [1/2]
const Operateur & List_Equations_Scalaires_Passifs_Especes::operateur (int) const inline override virtual
Implements Equation_base.
operateur() [2/2]
Operateur & List_Equations_Scalaires_Passifs_Especes::operateur (int) inline override virtual
Implements Equation_base.
inconnue() [1/2]
const Champ_Inc_base & List_Equations_Scalaires_Passifs_Especes::inconnue () const inline override virtual
Implements Equation_base.
inconnue() [2/2]
Champ_Inc_base & List_Equations_Scalaires_Passifs_Especes::inconnue () inline override virtual
Implements Equation_base.
LIST()
List_Equations_Scalaires_Passifs_Especes::LIST (OWN_PTR(Equation_base)) protected
References Equation_base::OWN_PTR().
OBS_PTR()
List_Equations_Scalaires_Passifs_Especes::OBS_PTR (Milieu_base) protected
Member Data Documentation
complet
int List_Equations_Scalaires_Passifs_Especes::complet = 0 protected
Referenced by complete(), and complete().