CEA TRUST Platform: Champ_Fonc_P1_isoP1Bulle Class Reference
Champ_Fonc_P1_isoP1Bulle Class Reference
#include <Champ_Fonc_P1_isoP1Bulle.h>
Public Member Functions
int fixer_nb_valeurs_nodales (int) override
void mettre_a_jour (double) override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &tab_valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void resetTime (double time) override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Champ_Fonc_base OWN_PTR(Champ_base) P1NC
Member Function Documentation
fixer_nb_valeurs_nodales()
int Champ_Fonc_P1_isoP1Bulle::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Fixe le nombre de degres de liberte par composante.
Parameters
(int nb_noeuds) le nombre de degre de liberte par composante
Reimplemented from Champ_Fonc_base.
References Champ_Fonc_base::creer_tableau_distribue(), domaine_vef(), and Domaine_VEF::md_vector_p1b().
mettre_a_jour()
void Champ_Fonc_P1_isoP1Bulle::mettre_a_jour (double un_temps) override virtual
Mise a jour en temps du champ.
Parameters
(double temps) le temps de mise a jour
Reimplemented from Champ_Fonc_base.
References Champ_Fonc_base::mettre_a_jour().
trace()
DoubleTab & Champ_Fonc_P1_isoP1Bulle::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
Calcule la trace d'un champ sur une frontiere au temps tps.
WEC : La frontiere passee en parametre doit faire partie du domaine sur lequel s'appuie le champ Le resultat est calcule sur cette frontiere et la taille du DoubleTab x correspond au nombre de faces de la frontiere. x peut avoir un espace virtuel, la fonction trace apelle echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF : Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Parameters
(Frontiere_dis_base&) frontiere discretisee sur laquelle on veut calculer la trace du champ au temps tps
(DoubleTab& x , double tps) les valeurs du champ sur la frontiere au temps tps
Returns
(DoubleTab&) les valeurs du champ sur la frontiere au temps tps
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::trace(), and Champ_Don_base::valeurs().
domaine_vef()
const Domaine_VEF & Champ_Fonc_P1_isoP1Bulle::domaine_vef () const inline override virtual
Implements Champ_P1iP1B_implementation.
Referenced by fixer_nb_valeurs_nodales().
valeur_a_elem()
DoubleVect & Champ_Fonc_P1_isoP1Bulle::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Fonc_P1_isoP1Bulle::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_Fonc_P1_isoP1Bulle::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Fonc_P1_isoP1Bulle::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Fonc_P1_isoP1Bulle::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc_P1_isoP1Bulle::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const inline override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_aux_sommets_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Fonc_P1_isoP1Bulle::remplir_coord_noeuds (DoubleTab & coord) const inline override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab& coord)
Returns
(DoubleTab&) renvoie toujours le parametre coord
Reimplemented from Champ_Fonc_base.
References Champ_P1iP1B_implementation::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Fonc_P1_isoP1Bulle::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented from Champ_Fonc_base.
References Champ_P1iP1B_implementation::remplir_coord_noeuds_et_polys().
completer()
void Champ_Fonc_P1_isoP1Bulle::completer (const Domaine_Cl_dis_base & zcl) override protected virtual
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::completer().
le_champ() [1/2]
const Champ_base & Champ_Fonc_P1_isoP1Bulle::le_champ () const inline override protected virtual
Implements Champ_implementation.
le_champ() [2/2]
Champ_base & Champ_Fonc_P1_isoP1Bulle::le_champ () inline override protected virtual
Implements Champ_implementation.