CEA TRUST Platform: Convection_Diffusion_Chaleur_QC Class Reference
Convection_Diffusion_Chaleur_QC Class Reference
#include <Convection_Diffusion_Chaleur_QC.h>
Public Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
Public Member Functions inherited from Convection_Diffusion_Chaleur_Fluide_Dilatable_base
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Motcle & domaine_application () const override
int remplir_cl_modifiee ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_base
int impr (Sortie &os) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Detailed Description
quand le scalaire subissant le transport est la temperature en gaz parfaits,
ou l'enthalpie en gaz reels.
(generalisation de Convection_Diffusion_Temperature pour les gaz reels)
See also
Conv_Diffusion_std Convection_Diffusion_Temperature
Constructor & Destructor Documentation
Convection_Diffusion_Chaleur_QC()
Convection_Diffusion_Chaleur_QC::Convection_Diffusion_Chaleur_QC ()
Member Function Documentation
set_param()
void Convection_Diffusion_Chaleur_QC::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Chaleur_Turbulent_QC.
References Param::ajouter_non_std(), and Equation_base::set_param().
Referenced by Convection_Diffusion_Chaleur_Turbulent_QC::set_param().
calculer_div_u_ou_div_rhou()
void Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou (DoubleTab & res) const override virtual
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References Operateur_Div::calculer(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), Navier_Stokes_std::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), mode_convection_, Convection_Diffusion_std::operateur(), Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::pression(), Equation_base::probleme(), and Champ_Inc_base::valeurs().
lire_motcle_non_standard()
int Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
Reimplemented in Convection_Diffusion_Chaleur_Turbulent_QC.
References Equation_base::discretisation(), Process::exit(), Equation_base::les_sources, Equation_base::lire_motcle_non_standard(), mode_convection_, Objet_U::que_suis_je(), Motcles::search(), Convection_Diffusion_std::terme_convectif, and Source::typer_direct().
Referenced by Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard().
preparer_calcul()
int Convection_Diffusion_Chaleur_QC::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Reimplemented in Convection_Diffusion_Chaleur_Turbulent_QC.
References mode_convection_, Convection_Diffusion_Chaleur_Fluide_Dilatable_base::preparer_calcul(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee().
Referenced by Convection_Diffusion_Chaleur_Turbulent_QC::preparer_calcul().
vitesse_pour_transport()
const Champ_base & Convection_Diffusion_Chaleur_QC::vitesse_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References Probleme_base::equation(), Navier_Stokes_std::inconnue(), mode_convection_, Equation_base::probleme(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport().
is_generic()
bool Convection_Diffusion_Chaleur_QC::is_generic () const inline override virtual
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References mode_convection_.
Member Data Documentation
mode_convection_
int Convection_Diffusion_Chaleur_QC::mode_convection_ protected
Referenced by calculer_div_u_ou_div_rhou(), is_generic(), lire_motcle_non_standard(), preparer_calcul(), and vitesse_pour_transport().