CEA TRUST Platform: Modele_turbulence_hyd_0_eq_base Class Reference
Modele_turbulence_hyd_0_eq_base Class Reference abstract
Public Member Functions
void imprimer (Sortie &) const override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
See also
Modele_turbulence_hyd_base
Member Function Documentation
set_param()
void Modele_turbulence_hyd_0_eq_base::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_Longueur_Melange_VEF, Modele_turbulence_hyd_LES_Wale_VEF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_LES_Smago_VDF, and Modele_turbulence_hyd_LES_base.
References Param::ajouter(), fichier_K_eps_sortie_, and Modele_turbulence_hyd_base::set_param().
Referenced by Modele_turbulence_hyd_Longueur_Melange_VDF::set_param(), and Modele_turbulence_hyd_Longueur_Melange_VEF::set_param().
reprendre()
int Modele_turbulence_hyd_0_eq_base::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_base.
comprend_mot()
int Modele_turbulence_hyd_0_eq_base::comprend_mot (const Motcle & mot) const
References comprend_champ().
a_pour_Champ_Fonc()
int Modele_turbulence_hyd_0_eq_base::a_pour_Champ_Fonc (const Motcle & mot, OBS_PTR(Champ_base) & ch_ref) const
References Process::exit(), and Motcles::search().
comprend_champ()
int Modele_turbulence_hyd_0_eq_base::comprend_champ (const Motcle & mot) const
References Process::exit(), and Motcles::search().
Referenced by comprend_mot().
associer()
void Modele_turbulence_hyd_0_eq_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Reimplemented from Modele_turbulence_hyd_base.
completer()
void Modele_turbulence_hyd_0_eq_base::completer () override virtual
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_LES_base.
References Discretisation_base::discretiser_champ(), Ecrire_MED_32_64< _SIZE_ >::ecrire_domaine(), fichier_K_eps_sortie_, Process::me(), and Nom::nom_me().
mettre_a_jour()
void Modele_turbulence_hyd_0_eq_base::mettre_a_jour (double) override virtual
Implements Modele_turbulence_hyd_base.
References Perf_counters::begin_count().
Referenced by Modele_turbulence_hyd_LES_base::preparer_calcul(), Modele_turbulence_hyd_Longueur_Melange_VDF::preparer_calcul(), and Modele_turbulence_hyd_Longueur_Melange_VEF::preparer_calcul().
discretiser()
void Modele_turbulence_hyd_0_eq_base::discretiser () override virtual
Discretise le modele de turbulence.
Reimplemented from Modele_turbulence_hyd_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Modele_turbulence_hyd_base::champs_compris_, Modele_turbulence_hyd_base::discretiser(), and Modele_turbulence_hyd_base::discretiser_K().
calculer_viscosite_turbulente()
virtual Champ_Fonc_base& Modele_turbulence_hyd_0_eq_base::calculer_viscosite_turbulente () pure virtual
Implemented in Modele_turbulence_hyd_Longueur_Melange_VEF, Modele_turbulence_hyd_LES_Wale_VEF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Wale_VDF, and Modele_turbulence_hyd_LES_Smago_VDF.
calculer_energie_cinetique_turb()
virtual void Modele_turbulence_hyd_0_eq_base::calculer_energie_cinetique_turb () pure virtual
Implemented in Modele_turbulence_hyd_Longueur_Melange_base, and Modele_turbulence_hyd_LES_base.
imprimer()
void Modele_turbulence_hyd_0_eq_base::imprimer (Sortie & os) const override virtual
Effectue l'impression si cela est necessaire.
Returns
renvoie toujours 1
Reimplemented from Modele_turbulence_hyd_base.
Reimplemented in Modele_turbulence_hyd_LES_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Modele_turbulence_hyd_base::dt_impr_ustar_, Modele_turbulence_hyd_base::dt_impr_ustar_mean_only_, Ecrire_MED_32_64< _SIZE_ >::ecrire_champ(), fichier_K_eps_sortie_, Modele_turbulence_hyd_base::imprimer(), Nom::le_nom(), Modele_turbulence_hyd_base::limpr_ustar(), Process::me(), Domaine_32_64< _SIZE_ >::nb_elem(), Nom::nom_me(), Schema_Temps_base::pas_de_temps(), Objet_U::que_suis_je(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_precedent(), and Modele_turbulence_hyd_base::wall_length_.
energie_cinetique_turbulente() [1/2]
virtual Champ_Fonc_base& Modele_turbulence_hyd_0_eq_base::energie_cinetique_turbulente () inline virtual
energie_cinetique_turbulente() [2/2]
virtual const Champ_Fonc_base& Modele_turbulence_hyd_0_eq_base::energie_cinetique_turbulente () const inline virtual
OWN_PTR() [1/2]
Modele_turbulence_hyd_0_eq_base::OWN_PTR (Champ_Fonc_base) protected
OWN_PTR() [2/2]
Modele_turbulence_hyd_0_eq_base::OWN_PTR (Champ_Inc_base) mutable protected
OBS_PTR() [1/2]
Modele_turbulence_hyd_0_eq_base::OBS_PTR (Domaine_VF) protected
OBS_PTR() [2/2]
Modele_turbulence_hyd_0_eq_base::OBS_PTR (Domaine_Cl_dis_base) protected
Member Data Documentation
fichier_K_eps_sortie_
Nom Modele_turbulence_hyd_0_eq_base::fichier_K_eps_sortie_ protected
Referenced by completer(), imprimer(), and set_param().