CEA TRUST Platform: Domaine_Cl_PolyMAC Class Reference
Domaine_Cl_PolyMAC Class Reference
Public Member Functions
int initialiser (double temps) override
Public Member Functions inherited from Domaine_Cl_dis_base
virtual int calculer_coeffs_echange (double temps)
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
int contient_Cl (const Nom &)
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
const Nom & le_nom () const override
Conds_lim & les_conditions_limites ()
const Conds_lim & les_conditions_limites () const
Cond_lim & les_conditions_limites (int)
const Cond_lim & les_conditions_limites (int) const
virtual void mettre_a_jour (double temps)
virtual void mettre_a_jour_ss_pas_dt (double temps)
int nb_cond_lim () const
void nommer (const Nom &nom) override
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
completer()
void Domaine_Cl_PolyMAC::completer (const Domaine_dis_base &) override virtual
Implements Domaine_Cl_dis_base.
References modif_perio_fait_.
initialiser()
int Domaine_Cl_PolyMAC::initialiser (double temps) override virtual
Initialise les CLs Contrairement aux methodes mettre_a_jour, les methodes.
initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(int) 1 si OK, 0 sinon
Reimplemented from Domaine_Cl_dis_base.
References Process::exit(), Domaine_Cl_dis_base::initialiser(), and nb_bord_periodicite().
imposer_cond_lim()
void Domaine_Cl_PolyMAC::imposer_cond_lim (Champ_Inc_base & ch, double temps) override virtual
Implements Domaine_Cl_dis_base.
References Objet_U::dimension, Champ_Inc_base::domaine_vf(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Cond_lim_base::frontiere_dis(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), modif_perio_fait_, Field_base::nature_du_champ(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), Dirichlet::val_imp_au_temps(), Champ_Inc_base::valeurs(), and Debog::verifier().
nb_faces_sortie_libre()
int Domaine_Cl_PolyMAC::nb_faces_sortie_libre () const
References Process::exit().
domaine_vf() [1/2]
Domaine_VF & Domaine_Cl_PolyMAC::domaine_vf ()
References Domaine_Cl_dis_base::domaine_dis().
domaine_vf() [2/2]
const Domaine_VF & Domaine_Cl_PolyMAC::domaine_vf () const
References Domaine_Cl_dis_base::domaine_dis().
nb_bord_periodicite()
int Domaine_Cl_PolyMAC::nb_bord_periodicite () const
References Domaine_Cl_dis_base::les_conditions_limites_.
Referenced by initialiser().
Member Data Documentation
modif_perio_fait_
int Domaine_Cl_PolyMAC::modif_perio_fait_ = 0 protected
Referenced by completer(), and imposer_cond_lim().