CEA TRUST Platform: Op_Correlation Class Reference
Op_Correlation Class Reference
#include <Op_Correlation.h>
Public Member Functions
const Nom & le_nom () const override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
le_nom()
const Nom & Op_Correlation::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Implements Operateur_Statistique_tps_base.
References integrale_tps_ab_, Integrale_tps_Champ::le_champ_calcule(), and Field_base::le_nom().
temps()
double Op_Correlation::temps () const inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_tps_ab_, Integrale_tps_Champ::le_champ_calcule(), and Champ_base::temps().
integrale()
const Integrale_tps_produit_champs & Op_Correlation::integrale () const inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_tps_ab_.
Referenced by Champ_Generique_Correlation::integrale(), and Champ_Generique_Correlation::temps().
la_moyenne_a()
const Op_Moyenne & Op_Correlation::la_moyenne_a () const inline
Referenced by completer(), and Champ_Generique_Correlation::get_directive_pour_discr().
la_moyenne_b()
const Op_Moyenne & Op_Correlation::la_moyenne_b () const inline
Referenced by completer().
valeurs_a()
const DoubleTab & Op_Correlation::valeurs_a () const inline
Referenced by completer().
valeurs_b()
const DoubleTab & Op_Correlation::valeurs_b () const inline
Referenced by completer().
valeurs_ab()
DoubleTab & Op_Correlation::valeurs_ab () inline
References integrale_tps_ab_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Don_base::valeurs().
Referenced by completer().
dt_integration_a()
double Op_Correlation::dt_integration_a () const inline
Referenced by calculer_valeurs().
dt_integration_b()
double Op_Correlation::dt_integration_b () const inline
Referenced by calculer_valeurs().
dt_integration_ab()
double Op_Correlation::dt_integration_ab () const inline
References Integrale_tps_Champ::dt_integration(), and integrale_tps_ab_.
Referenced by calculer_valeurs().
mettre_a_jour()
void Op_Correlation::mettre_a_jour (double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_tps_ab_, and Integrale_tps_produit_champs::mettre_a_jour().
initialiser()
void Op_Correlation::initialiser (double val) inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_tps_ab_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Don_base::valeurs().
associer() [1/3]
void Op_Correlation::associer (const Domaine_dis_base & une_zdis, const Champ_base & le_champ, double t1, double t2) inline
References Process::exit().
Referenced by Champ_Generique_Correlation::completer().
associer() [2/3]
void Op_Correlation::associer (const Domaine_dis_base & une_zdis, const Champ_Generique_base & le_champ, double t1, double t2) inline override virtual
Implements Operateur_Statistique_tps_base.
References Process::exit().
associer() [3/3]
void Op_Correlation::associer (const Domaine_dis_base & une_zdis, const Champ_Generique_base & le_champ_a, const Champ_Generique_base & le_champ_b, double t1, double t2) inline
References Integrale_tps_produit_champs::associer(), Champ_Fonc_base::associer_domaine_dis_base(), Nom::debute_par(), Champ_Generique_base::get_champ(), integrale_tps_ab_, Integrale_tps_Champ::le_champ_calcule(), Objet_U::que_suis_je(), Nom::suffix(), and Integrale_tps_Champ::typer_champ().
fixer_tstat_deb()
void Op_Correlation::fixer_tstat_deb (double tdeb, double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
References Integrale_tps_Champ::fixer_dt_integr(), Integrale_tps_Champ::fixer_t_debut(), Integrale_tps_Champ::fixer_tps_integrale(), and integrale_tps_ab_.
fixer_tstat_fin()
void Op_Correlation::fixer_tstat_fin (double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
References Integrale_tps_Champ::fixer_t_fin(), and integrale_tps_ab_.
completer_post_statistiques()
int Op_Correlation::completer_post_statistiques (const Domaine & dom, const int is_axi, Format_Post_base & format) override virtual
Reimplemented from Operateur_Statistique_tps_base.
data_a_sauvegarder()
std::vector< YAML_data > Op_Correlation::data_a_sauvegarder () const inline override virtual
for PDI IO: retrieve name, type and dimensions of the field to save/restore
Reimplemented from Operateur_Statistique_tps_base.
References Champ_Fonc_base::get_pdi_name(), Nom::getString(), integrale_tps_ab_, Integrale_tps_Champ::le_champ_calcule(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and Champ_Don_base::valeurs().
sauvegarder()
int Op_Correlation::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
References integrale_tps_ab_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Fonc_base::sauvegarder().
reprendre()
int Op_Correlation::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
References integrale_tps_ab_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Fonc_base::reprendre().
associer_op_stat()
void Op_Correlation::associer_op_stat (const Operateur_Statistique_tps_base & un_op_stat) inline override virtual
Reimplemented from Operateur_Statistique_tps_base.
References Process::exit().
Referenced by Champ_Generique_Correlation::completer().
completer()
void Op_Correlation::completer (const Probleme_base & Pb, const Nom & prefix) override virtual
Implements Operateur_Statistique_tps_base.
References Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Probleme_base::discretisation(), Field_base::fixer_nb_comp(), Champ_Fonc_base::fixer_nb_valeurs_nodales(), Field_base::fixer_noms_compo(), Field_base::fixer_unite(), Field_base::fixer_unites(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Op_Moyenne::integrale(), integrale_tps_ab_, la_moyenne_a(), la_moyenne_b(), Integrale_tps_Champ::le_champ_calcule(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Field_base::nommer(), Field_base::noms_compo(), OBS_PTR(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Probleme_base::schema_temps(), Champ_Fonc_base::set_pdi_name(), TRUSTVect< _TYPE_, _SIZE_ >::size_reelle_ok(), Nom::substr_old(), Integrale_tps_produit_champs::support_different(), Schema_Temps_base::temps_courant(), Integrale_tps_Champ::typer_champ(), valeurs_a(), valeurs_ab(), and valeurs_b().
Referenced by Champ_Generique_Correlation::completer().
calculer_valeurs()
DoubleTab Op_Correlation::calculer_valeurs () const override virtual
Implements Operateur_Statistique_tps_base.
References Integrale_tps_produit_champs::ajoute_produit_tensoriel(), dt_integration_a(), dt_integration_ab(), dt_integration_b(), integrale_tps_ab_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Don_base::valeurs().
Referenced by Champ_Generique_Correlation::get_champ().
OBS_PTR() [1/4]
Op_Correlation::OBS_PTR (Op_Moyenne) protected
Referenced by completer().
OBS_PTR() [2/4]
Op_Correlation::OBS_PTR (Op_Moyenne) protected
OBS_PTR() [3/4]
Op_Correlation::OBS_PTR (Integrale_tps_Champ) protected
OBS_PTR() [4/4]
Op_Correlation::OBS_PTR (Integrale_tps_Champ) protected
Member Data Documentation
integrale_tps_ab_
Integrale_tps_produit_champs Op_Correlation::integrale_tps_ab_ protected
Referenced by associer(), calculer_valeurs(), completer(), data_a_sauvegarder(), dt_integration_ab(), fixer_tstat_deb(), fixer_tstat_fin(), initialiser(), integrale(), le_nom(), mettre_a_jour(), reprendre(), sauvegarder(), temps(), and valeurs_ab().