CEA TRUST Platform: Op_Conv_EF_Stab_PolyMAC_P0_Face Class Reference
Op_Conv_EF_Stab_PolyMAC_P0_Face Class Reference
Public Member Functions
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={ }) const override
double calculer_dt_stab () const override
void completer () override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={ }) const override
Public Member Functions inherited from Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face
double calculer_dt_stab () const override
Public Member Functions inherited from Op_Conv_EF_Stab_PolyMAC_Face
void dimensionner (Matrice_Morse &mat) const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Conv_PolyMAC_base
double calculer_dt_stab () const override
void completer () override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
completer()
void Op_Conv_EF_Stab_PolyMAC_P0_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Conv_EF_Stab_PolyMAC_Face.
References Op_Conv_EF_Stab_PolyMAC_Face::completer().
calculer_dt_stab()
double Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab () const override virtual
Computes the stability time step for the convection operator.
This method calculates the maximum allowable time step based on the CFL stability condition for the convection operator. The computation considers incoming fluxes through each face of every element and determines the most restrictive time step constraint across the entire domain. For multiphase flows, elements with negligible phase presence are excluded from the time step calculation.
Returns
The global minimum stability time step across all MPI processes
Note
Only incoming convective fluxes are considered in the stability analysis.
For multiphase problems, elements with phase fraction below 1e-3 are ignored.
In axisymmetric calculations, boundary faces with specific conditions may be excluded.
The final time step is synchronized across all MPI processes using the minimum value.
Flux contributions account for face porosity and surface area weighting.
Reimplemented from Op_Conv_EF_Stab_PolyMAC_Face.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Champ_Face_base::fcl(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Process::mp_min(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), and Option_PolyMAC::TRAITEMENT_AXI.
dimensionner_blocs()
void Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const override virtual
Dimensions the matrix blocks for the PolyMAC P0 Face convection operator with EF stabilization.
This method constructs the sparsity pattern and allocates memory for the system matrix by analyzing face-element connectivity and establishing the stencil relationships between degrees of freedom. The resulting matrix structure accounts for face-face and element-element contributions based on the PolyMAC P0 Face discretization scheme.
Parameters
matrices Map containing the system matrices indexed by unknown field names
semi_impl Map of semi-implicit terms indexed by unknown field names
Note
The method returns early if no diagonal block exists or if semi-implicit treatment is requested.
For multiphase problems with added mass correlation, cross-coupling terms between phases are included.
The stencil construction handles face equivalence relationships and boundary conditions appropriately.
Duplicate entries in the stencil are automatically removed before matrix allocation.
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), Champ_Face_base::fcl(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const override virtual
Adds convection contributions to the system matrix and right-hand side vector.
This method implements the convection operator with EF stabilization for PolyMAC P0 Face discretization. It computes face-based convection fluxes using upwind stabilization and assembles the corresponding matrix coefficients and source terms. The method handles both face-face and element-element contributions, accounting for face equivalence relationships and boundary conditions.
Parameters
matrices Map containing the system matrices indexed by unknown field names
secmem Right-hand side vector to be updated with convection contributions
semi_impl Map of semi-implicit field values indexed by field names
Note
The convection flux computation uses a blended upwind scheme with stabilization parameter alpha_.
For multiphase flows, added mass correlations are included in the mass matrix contributions.
The method distinguishes between compressible and incompressible flow formulations.
Dirichlet boundary conditions are enforced through direct substitution in the source term.
Face equivalence relationships are handled to maintain consistency across mesh interfaces.
Performance statistics are automatically tracked during execution.
Reimplemented from Operateur_base.
References Masse_ajoutee_base::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::alpha_, Equation_base::champ_conserve(), Objet_U::dimension, MorEqn::equation(), Pb_Multiphase::equation_masse(), Champ_Face_base::fcl(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Operateur_Conv_base::incompressible_, Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Champ_Proto::passe(), Champ_Inc_base::passe(), Op_Conv_EF_Stab_PolyMAC_Face::porosite_e, Op_Conv_EF_Stab_PolyMAC_Face::porosite_f, and Champ_Inc_base::valeurs().