CEA TRUST Platform: Sondes Class Reference
Sondes Class Reference
Public Member Functions
void mettre_a_jour (double temps, double tinit)
Detailed Description
See also
Sonde Postraitement
Member Function Documentation
ouvrir_fichiers()
void Sondes::ouvrir_fichiers () inline
Ouvre tous les fichiers associes a chacune des sondes de la liste.
fermer_fichiers()
void Sondes::fermer_fichiers () inline
Ferme tous les fichiers des sondes de la liste.
Referenced by Postraitement::finir().
completer()
void Sondes::completer ()
References set_noms_champs_postraitables().
Referenced by Postraitement::completer_sondes().
init_bords()
void Sondes::init_bords () inline
Referenced by Postraitement::completer().
associer_post()
void Sondes::associer_post (const Postraitement & post)
Associe un postraitement a la liste des sondes.
Referenced by Postraitement::lire_motcle_non_standard().
postraiter()
void Sondes::postraiter ()
Effectue le postraitement sur chacune des sondes de la liste.
References clear_cache().
Referenced by Postraitement::postraiter_sondes().
mettre_a_jour()
void Sondes::mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de chacune des sondes de la liste.
Parameters
(double temps) le temps de mise a jour
(double tinit) le temps initial des sondes
References clear_cache().
Referenced by Postraitement::traiter_sondes().
OBS_PTR()
Sondes::OBS_PTR (Champ_base) &
clear_cache()
void Sondes::clear_cache ()
Referenced by mettre_a_jour(), and postraiter().
set_noms_champs_postraitables()
void Sondes::set_noms_champs_postraitables ()
Referenced by completer().
get_noms_champs_postraitables()
const Motcles& Sondes::get_noms_champs_postraitables () const inline
set_update_positions()
void Sondes::set_update_positions (bool update_positions)
Modifie le parametrage des sondes mobiles.
References update_positions.
Referenced by Postraitement::lire_motcle_non_standard().
get_update_positions()
bool Sondes::get_update_positions ()
Renvoie le parametrage des sondes mobiles.
References update_positions.
resetTime()
void Sondes::resetTime (double time) inline
Referenced by Postraitement::resetTime().
Member Data Documentation
nom_champ_lu_
const Nom& Sondes::nom_champ_lu_
update_positions
bool Sondes::update_positions =false
Referenced by get_update_positions(), and set_update_positions().