CEA TRUST Platform: Masse_Multiphase Class Reference
Masse_Multiphase Class Reference
#include <Masse_Multiphase.h>
Public Member Functions
void associer_fluide (const Fluide_base &)
void associer_milieu_base (const Milieu_base &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
int lire_motcle_non_standard (const Motcle &, Entree &) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
quand le scalaire subissant le transport est la fraction massique
See also
Conv_Diffusion_std
Member Function Documentation
set_param()
void Masse_Multiphase::set_param (Param & param) override virtual
Reimplemented from Convection_Diffusion_std.
References Param::ajouter_condition(), Param::ajouter_non_std(), and Equation_base::set_param().
lire_motcle_non_standard()
int Masse_Multiphase::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_std.
References evanescence_, and Convection_Diffusion_std::lire_motcle_non_standard().
associer_fluide()
void Masse_Multiphase::associer_fluide (const Fluide_base & un_fluide)
Associe un fluide de type Fluide_base a l'equation.
Parameters
(Fluide_base& un_fluide) le milieu a associer a l'equation
Referenced by associer_milieu_base().
inconnue() [1/2]
const Champ_Inc_base & Masse_Multiphase::inconnue () const inline override virtual
Renvoie le champ inconnue representant l'inconnue (T ou H) (version const)
Returns
(Champ_Inc_base&) le champ inconnue representant la temperature (GP) ou l'enthalpie (GR)
Implements Convection_Diffusion_std.
Referenced by completer().
inconnue() [2/2]
Champ_Inc_base & Masse_Multiphase::inconnue () inline override virtual
Renvoie le champ inconnue representant l'inconnue (T ou H)
Returns
(Champ_Inc_base&) le champ inconnue representant la temperature (GP) ou l'enthalpie (GR)
Implements Convection_Diffusion_std.
discretiser()
void Masse_Multiphase::discretiser () override virtual
Discretise l'equation.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Objet_U::dimension, Equation_base::discretisation(), Equation_base::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Pb_Multiphase::nb_phases(), Schema_Temps_base::nb_valeurs_temporelles(), Pb_Multiphase::nom_phase(), Equation_base::probleme(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
milieu() [1/2]
const Milieu_base & Masse_Multiphase::milieu () const override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base) (version const)
Returns
(Milieu_base&) le Fluide_base upcaste en Milieu_base
Implements Equation_base.
References fluide().
fluide() [1/2]
const Fluide_base & Masse_Multiphase::fluide () const
Renvoie le fluide incompressible associe a l'equation.
(version const)
Returns
(Fluide_base&) le fluide incompressible associe a l'equation
Exceptions
pas de fluide associe a l'eqaution
References Process::exit(), Probleme_U::le_nom(), and Equation_base::probleme().
Referenced by milieu(), and milieu().
fluide() [2/2]
Fluide_base & Masse_Multiphase::fluide ()
Renvoie le fluide incompressible associe a l'equation.
Returns
(Fluide_base&) le fluide incompressible associe a l'equation
Exceptions
pas de fluide associe a l'eqaution
milieu() [2/2]
Milieu_base & Masse_Multiphase::milieu () override virtual
Renvoie le milieu physique de l'equation.
(un Fluide_base upcaste en Milieu_base)
Returns
(Milieu_base&) le Fluide_base upcaste en Milieu_base
Implements Equation_base.
References fluide().
associer_milieu_base()
void Masse_Multiphase::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation, le milieu est en fait caste en Fluide_base.
Parameters
(Milieu_base& un_milieu)
Exceptions
les proprietes physiques du fluide ne sont pas toutes specifiees
Implements Equation_base.
References associer_fluide().
completer()
void Masse_Multiphase::completer () override virtual
Associe l inconnue de l equation a la loi d etat,.
Reimplemented from Equation_base.
References MorEqn::associer_eqn(), Operateur_base::associer_eqn(), MorEqn::check_multiphase_compatibility(), Equation_base::completer(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), inconnue(), Operateur_Grad::l_op_base(), Op_Grad_, Convection_Diffusion_std::terme_convectif, and Operateur_Grad::typer().
nombre_d_operateurs()
int Masse_Multiphase::nombre_d_operateurs () const inline override virtual
Renvoie le nombre d'operateurs de l'equation: 2 pour une equation de diffusion.
Returns
(int) le nombre d'operateurs de l'equation
Reimplemented from Convection_Diffusion_std.
Referenced by Source_Flux_interfacial_base::ajouter_blocs().
operateur() [1/2]
const Operateur & Masse_Multiphase::operateur (int i) const override virtual
Renvoie l'operateur specifie par son index: renvoie terme_diffusif si i = 0.
renvoie terme_convectif si i = 1
exit si i>1
(version const)
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur specifie
Exceptions
l'equation n'a pas plus de 2 operateurs
Reimplemented from Convection_Diffusion_std.
References Process::exit(), and Convection_Diffusion_std::terme_convectif.
Referenced by Source_Flux_interfacial_base::ajouter_blocs().
operateur() [2/2]
Operateur & Masse_Multiphase::operateur (int i) override virtual
Renvoie l'operateur specifie par son index: renvoie terme_diffusif si i = 0.
renvoie terme_convectif si i = 1
exit si i>1
Parameters
(int i) l'index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur specifie
Exceptions
l'equation n'a pas plus de 2 operateurs
Reimplemented from Convection_Diffusion_std.
References Process::exit(), and Convection_Diffusion_std::terme_convectif.
dimensionner_matrice_sans_mem()
void Masse_Multiphase::dimensionner_matrice_sans_mem (Matrice_Morse & matrice) override virtual
Reimplemented from Equation_base.
References Equation_base::dimensionner_matrice_sans_mem(), and evanescence_.
has_interface_blocs()
int Masse_Multiphase::has_interface_blocs () const override virtual
Reimplemented from Equation_base.
References evanescence_, and Equation_base::has_interface_blocs().
dimensionner_blocs()
void Masse_Multiphase::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Equation_base.
References Equation_base::dimensionner_blocs(), and evanescence_.
assembler_blocs_avec_inertie()
void Masse_Multiphase::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) override virtual
Reimplemented from Equation_base.
References Equation_base::assembler_blocs_avec_inertie(), and evanescence_.
calculer_alpha_rho()
void Masse_Multiphase::calculer_alpha_rho (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static
References Champ_base::a_un_domaine_dis_base(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::domaine_dis(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_base::valeur_aux(), Champ_base::valeur_aux_bords(), Champ_Inc_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by get_fonc_champ_conserve().
get_fonc_champ_conserve()
std::pair< std::string, fonc_calc_t > Masse_Multiphase::get_fonc_champ_conserve () const inline override virtual
Reimplemented from Equation_base.
References calculer_alpha_rho().
domaine_application()
const Motcle & Masse_Multiphase::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
operateur_gradient_inconnue()
const Operateur_Grad & Masse_Multiphase::operateur_gradient_inconnue () const inline
References Op_Grad_.
Referenced by Dispersion_bulles_VDF::ajouter_blocs().
OWN_PTR()
Masse_Multiphase::OWN_PTR (Champ_Inc_base) protected
OBS_PTR()
Masse_Multiphase::OBS_PTR (Fluide_base) protected
Member Data Documentation
Op_Grad_
Operateur_Grad Masse_Multiphase::Op_Grad_ protected
Referenced by completer(), and operateur_gradient_inconnue().
evanescence_
Operateur_Evanescence Masse_Multiphase::evanescence_ protected
Referenced by assembler_blocs_avec_inertie(), dimensionner_blocs(), dimensionner_matrice_sans_mem(), has_interface_blocs(), and lire_motcle_non_standard().