CEA TRUST Platform: Octree_32_64< _SIZE_ > Class Template Reference
Octree_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void construire (int, const ArrOfInt_t &, const OctreeLoc &, Octree_t *p=0)
virtual int_t rang_elem_depuis_loc (const OctreeLoc &, int_t prems, double x, double y=0, double z=0) const
virtual int_t rang_elem_loc (const OctreeLoc &, double x, double y=0, double z=0) const
virtual int_t taille () const
Protected Member Functions
void detruire ()
Detailed Description
template<typename _SIZE_>
class Octree_32_64< _SIZE_ >
See also
OctreeLoc OctreeRoot OctreeFloor
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Octree_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Octree_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Octree_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Octree_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Octree_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Vect_IntTab_t
template<typename _SIZE_ > using Octree_32_64< _SIZE_ >::Vect_IntTab_t = TRUST_Vector<IntTab_t>
Domaine_t
template<typename _SIZE_ > using Octree_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Octree_t
template<typename _SIZE_ > using Octree_32_64< _SIZE_ >::Octree_t = Octree_32_64<_SIZE_>
Constructor & Destructor Documentation
Octree_32_64() [1/2]
template<typename _SIZE_ > Octree_32_64< _SIZE_ >::Octree_32_64 () inline
~Octree_32_64()
template<typename _SIZE_ > virtual Octree_32_64< _SIZE_ >::~Octree_32_64 () inline virtual
References Octree_32_64< _SIZE_ >::detruire().
Octree_32_64() [2/2]
template<typename _SIZE_ > Octree_32_64< _SIZE_ >::Octree_32_64 (int n, Octree_32_64< _SIZE_ > * mon_pere, const ArrOfInt_t & val, const OctreeLoc & loc) inline
References Octree_32_64< _SIZE_ >::construire().
Member Function Documentation
rang_elem_loc()
template<typename _SIZE_ > Octree_32_64< _SIZE_ >::int_t Octree_32_64< _SIZE_ >::rang_elem_loc (const OctreeLoc & loc, double x, double y = 0, double z = 0) const virtual
Parameters
(OctreeLoc& loc)
(double x)
(double y)
(double z)
Returns
(int)
Reimplemented in OctreeFloor_32_64< _SIZE_ >.
References OctreeLoc::construire(), and OctreeLoc::direction().
Referenced by OctreeRoot_32_64< _SIZE_ >::rang_elem().
rang_elem_depuis_loc()
template<typename _SIZE_ > Octree_32_64< _SIZE_ >::int_t Octree_32_64< _SIZE_ >::rang_elem_depuis_loc (const OctreeLoc & loc, int_t prems, double x, double y = 0, double z = 0) const virtual
Parameters
(OctreeLoc& loc)
(int prems)
(double x)
(double y)
(double z)
Returns
(int)
Reimplemented in OctreeFloor_32_64< _SIZE_ >.
References OctreeLoc::construire(), and OctreeLoc::direction().
Referenced by OctreeRoot_32_64< _SIZE_ >::rang_elem_depuis(), and OctreeRoot_32_64< _SIZE_ >::rang_elems_sommet().
domaine()
template<typename _SIZE_ > virtual const Domaine_t& Octree_32_64< _SIZE_ >::domaine () const inline virtual
Reimplemented in OctreeRoot_32_64< _SIZE_ >.
References Octree_32_64< _SIZE_ >::domaine(), and Octree_32_64< _SIZE_ >::pere.
Referenced by Octree_32_64< _SIZE_ >::domaine(), and Octree_32_64< _SIZE_ >::get_epsilon().
construire()
template<typename _SIZE_ > void Octree_32_64< _SIZE_ >::construire (int nb_octrees, const ArrOfInt_t & Tab, const OctreeLoc & loc, Octree_t * pe = 0)
Parameters
(int nb_octrees)
(ArrOfInt& Tab)
(OctreeLoc& loc)
(Octree* pe)
References OctreeLoc::construire(), Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Process::exit(), Process::Journal(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_som_elem(), TRUST_Vector< _CLASSE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), OctreeLoc::xmax, OctreeLoc::xmin, OctreeLoc::ymax, OctreeLoc::ymin, OctreeLoc::zmax, and OctreeLoc::zmin.
Referenced by OctreeRoot_32_64< _SIZE_ >::construire(), and Octree_32_64< _SIZE_ >::Octree_32_64().
niveau()
template<typename _SIZE_ > int Octree_32_64< _SIZE_ >::niveau
taille()
template<typename _SIZE_ > Octree_32_64< _SIZE_ >::int_t Octree_32_64< _SIZE_ >::taille virtual
Renvoie la taille de l'octree.
Returns
(unsigned) la taille de l'octree
Reimplemented in OctreeFloor_32_64< _SIZE_ >.
References Octree_32_64< _SIZE_ >::nombre_d_octrees().
nombre_d_octrees()
template<typename _SIZE_ > static int Octree_32_64< _SIZE_ >::nombre_d_octrees () inline static
References Objet_U::dimension.
Referenced by Octree_32_64< _SIZE_ >::detruire(), Octree_32_64< _SIZE_ >::printOn(), and Octree_32_64< _SIZE_ >::taille().
printOn()
template<typename _SIZE_ > Sortie & Octree_32_64< _SIZE_ >::printOn (Sortie & is) const virtual
Reimplemented in OctreeFloor_32_64< _SIZE_ >.
References Octree_32_64< _SIZE_ >::nombre_d_octrees().
Referenced by OctreeFloor_32_64< _SIZE_ >::printOn().
readOn()
template<typename _SIZE_ > virtual Entree& Octree_32_64< _SIZE_ >::readOn (Entree & is) inline virtual
Reimplemented in OctreeFloor_32_64< _SIZE_ >.
Referenced by OctreeFloor_32_64< _SIZE_ >::readOn().
detruire()
template<typename _SIZE_ > void Octree_32_64< _SIZE_ >::detruire protected
Detruit l'octree.
Methode appelee par le destructeur
References Octree_32_64< _SIZE_ >::nombre_d_octrees().
Referenced by Octree_32_64< _SIZE_ >::~Octree_32_64().
ranger_elem_1D()
template<typename _SIZE_ > void Octree_32_64< _SIZE_ >::ranger_elem_1D (ArrOfInt & oks, int_t elem, int_t idx, int nb_som_elem, const DoubleTab_t & coords_som, const IntTab_t & les_elems, SmallArrOfTID_t & compteur, Vect_IntTab_t & sous_tab, double xmil) protected
ranger_elem_2D()
template<typename _SIZE_ > void Octree_32_64< _SIZE_ >::ranger_elem_2D (ArrOfInt & oks, int_t elem, int_t idx, int nb_som_elem, const DoubleTab_t & coords_som, const IntTab_t & les_elems, SmallArrOfTID_t & compteur, Vect_IntTab_t & sous_tab, double xmil, double ymil) protected
ranger_elem_3D()
template<typename _SIZE_ > void Octree_32_64< _SIZE_ >::ranger_elem_3D (ArrOfInt & oks, int_t elem, int_t idx, int nb_som_elem, const DoubleTab_t & coords_som, const IntTab_t & les_elems, SmallArrOfTID_t & compteur, Vect_IntTab_t & sous_tab, double xmil, double ymil, double zmil) protected
get_epsilon()
template<typename _SIZE_ > double Octree_32_64< _SIZE_ >::get_epsilon () const inline protected
References Octree_32_64< _SIZE_ >::domaine(), and Domaine_base::epsilon().
Member Data Documentation
les_octrees
template<typename _SIZE_ > Octree_32_64** Octree_32_64< _SIZE_ >::les_octrees protected
pere
template<typename _SIZE_ > Octree_32_64* Octree_32_64< _SIZE_ >::pere protected
Referenced by Octree_32_64< _SIZE_ >::domaine().