CEA TRUST Platform: Terme_Source_Constituant Class Reference
Terme_Source_Constituant Class Reference
#include <Terme_Source_Constituant.h>
Public Member Functions
void associer_champs (const Champ_base &)
void lire_donnees (Entree &)
Detailed Description
de type degagement volumique de puissance thermique.!!!!A MODIFIER Un objet Terme_Source_Constituant contient la puissance (OWN_PTR(Champ_base) donne utilisateur) et des references a la masse volumique (rho) et la chaleur. specifique (Cp).
See also
Classe non instanciable., L'implementation des termes dependra de leur discretisation.
Member Function Documentation
associer_champs()
void Terme_Source_Constituant::associer_champs (const Champ_base & rho) inline
Associe les champs donnes rho (masse volumique) et Cp (chaleur specifique) a l'objet.
Parameters
(Champ_Don_base& rho) champ donne representant la masse volumique
(Champ_Don_base& cp) champ donne representant la chaleur specifique
lire_donnees()
void Terme_Source_Constituant::lire_donnees (Entree & is)
Lit le terme de puissance a partir d'un flot d'entree.
Lit uniquement un champ donne representant la_puissance.
Parameters
(Entree& is) un flot d'entree
ouvrir_fichier()
void Terme_Source_Constituant::ouvrir_fichier (const Equation_base & eq, const Nom & out, const Nom & qsj, const Nom & description, SFichier & os, const Nom & type, const int flag) const
References Sortie::add_col(), colw_, Schema_Temps_base::gnuplot_header(), Equation_base::inconnue(), Probleme_U::le_nom(), Field_base::nb_comp(), Schema_Temps_base::nb_impr(), Field_base::noms_compo(), Sortie_Fichier_base::ouvrir(), Sortie_Fichier_base::precision(), Schema_Temps_base::precision_impr(), Equation_base::probleme(), Objet_U::que_suis_je(), Probleme_base::reprise_effectuee(), Probleme_base::schema_temps(), Sortie::set_col_width(), Sortie_Fichier_base::setf(), and Schema_Temps_base::wcol().
Referenced by Terme_Source_Constituant_VDF_Elem::ouvrir_fichier().
completer()
int Terme_Source_Constituant::completer (const Champ_Inc_base & inco)
References colw_, Field_base::nb_comp(), and Field_base::noms_compo().
Referenced by Terme_Source_Constituant_VDF_Elem::completer().
get_source()
const Champ_Don_base & Terme_Source_Constituant::get_source () const inline
mettre_a_jour()
void Terme_Source_Constituant::mettre_a_jour (double temps) inline
Referenced by Terme_Source_Constituant_PolyMAC_Elem::mettre_a_jour(), Terme_Source_Constituant_VDF_Elem::mettre_a_jour(), and Terme_Source_Constituant_VEF_Face::mettre_a_jour().
OBS_PTR()
Terme_Source_Constituant::OBS_PTR (Champ_base) protected
OWN_PTR()
Terme_Source_Constituant::OWN_PTR (Champ_Don_base) const protected
Member Data Documentation
colw_
int Terme_Source_Constituant::colw_ protected
Referenced by completer(), and ouvrir_fichier().