CEA TRUST Platform: Champ_Fonc_Tabule_Elem_PolyMAC Class Reference
Champ_Fonc_Tabule_Elem_PolyMAC Class Reference
#include <Champ_Fonc_Tabule_Elem_PolyMAC.h>
Public Member Functions
int initialiser (const double temps) override
void mettre_a_jour (double) override
Public Member Functions inherited from Champ_Fonc_Elem_PolyMAC
Champ_base & affecter_ (const Champ_base &ch) override
Public Member Functions inherited from Champ_Fonc_P0_base
Champ_base & affecter_ (const Champ_base &) override
int fixer_nb_valeurs_nodales (int n) override
int imprime (Sortie &, int) const override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
void resetTime (double time) override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_param()
void Champ_Fonc_Tabule_Elem_PolyMAC::associer_param (const VECT(OBS_PTR(Champ_base))& , const Table &)
mettre_a_jour()
void Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour (double un_temps) override virtual
Mise a jour en temps du champ.
Parameters
(double temps) le temps de mise a jour
Reimplemented from Champ_Fonc_P0_base.
References Process::abort(), TRUST_Vector< _CLASSE_ >::add(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Table::isfonction(), Champ_Fonc_base::mettre_a_jour(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Table::val(), Champ_Fonc_P0_base::valeur_aux_elems(), Champ_Don_base::valeurs(), Table::valeurs(), and Domaine_VF::xp().
Referenced by initialiser().
initialiser()
int Champ_Fonc_Tabule_Elem_PolyMAC::initialiser (const double un_temps) override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire
Reimplemented from Champ_Don_base.
References mettre_a_jour(), and Champ_base::temps().
VECT()
Champ_Fonc_Tabule_Elem_PolyMAC::VECT (OBS_PTR(Champ_base)) protected
References OBS_PTR().
OBS_PTR()
Champ_Fonc_Tabule_Elem_PolyMAC::OBS_PTR (Table) protected
Referenced by VECT().