CEA TRUST Platform: Perte_Charge_VEF Class Reference
Perte_Charge_VEF Class Reference abstract
Public Member Functions
void completer () override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don_base & source () const
Protected Member Functions
virtual void coeffs_perte_charge (const DoubleVect &u, const DoubleVect &pos, double t, double norme_u, double dh, double nu, double reynolds, double &coeff_ortho, double &coeff_long, double &u_l, DoubleVect &v_valeur) const =0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Perte_Charge_Isotrope, Perte_Charge_Directionnelle et Perte_Charge_Anisotrope heritent de Perte_Charge_VEF. Elles doivent surcharger essentiellement readOn() et perte_charge(). readOn() est suppose lire au moins diam_hydr et sous_domaine.
Ces classes sont censees remplacer Perte_Charge_VEF_Face et Perte_Charge_VEF_P1NC.
Member Function Documentation
ajouter()
DoubleTab & Perte_Charge_VEF::ajouter (DoubleTab & resu) const override virtual
Appelle perte_charge pour chaque face ou cela est necessaire.
Reimplemented from Source_base.
References coeffs_perte_charge(), Objet_U::dimension, MorEqn::equation(), Domaine_VF::face_voisins(), Sous_domaine_VF::les_faces(), Equation_base::milieu(), Domaine_VF::nb_faces(), Milieu_base::porosite_face(), Equation_base::schema_temps(), TRUSTVect< _TYPE_, _SIZE_ >::size(), sous_domaine, Schema_Temps_base::temps_courant(), Champ_base::valeur_a_compo(), Champ_Don_base::valeurs(), Domaine_VF::volumes_entrelaces(), Sous_domaine_VF::volumes_entrelaces(), and Domaine_VF::xv().
Referenced by Perte_Charge_Circulaire_QC_VEF_P1NC::ajouter_mere(), Perte_Charge_Anisotrope_QC_VEF_P1NC::ajouter_mere(), Perte_Charge_Directionnelle_QC_VEF_P1NC::ajouter_mere(), Perte_Charge_Isotrope_QC_VEF_P1NC::ajouter_mere(), and calculer().
contribuer_a_avec()
void Perte_Charge_VEF::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const override virtual
copie de ajouter sauf la derniere ligne
Reimplemented from Source_base.
References Matrice_Morse::coef(), coeffs_perte_charge(), Objet_U::dimension, MorEqn::equation(), Domaine_VF::face_voisins(), implicite_, Sous_domaine_VF::les_faces(), Equation_base::milieu(), Domaine_VF::nb_faces(), Milieu_base::porosite_face(), Equation_base::schema_temps(), TRUSTVect< _TYPE_, _SIZE_ >::size(), sous_domaine, Schema_Temps_base::temps_courant(), Champ_base::valeur_a_compo(), Champ_Don_base::valeurs(), Domaine_VF::volumes_entrelaces(), and Sous_domaine_VF::volumes_entrelaces().
calculer()
DoubleTab & Perte_Charge_VEF::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter().
associer_pb()
void Perte_Charge_VEF::associer_pb (const Probleme_base & pb) override virtual
associe le_fluide et la_vitesse
Implements Source_base.
References MorEqn::equation().
completer()
void Perte_Charge_VEF::completer () override virtual
Met a jour les references internes a l'objet Source_base.
Appelle 2 methodes virtuelles pures protegees: Source_base::associer_domaines(const Domaine_dis_base& ,const Domaine_Cl_dis_base&) Source_base::associer_pb(const Probleme_base&)
Reimplemented from Source_base.
References Source_base::completer(), Probleme_base::domaine(), MorEqn::equation(), Objet_U::est_egal_a(), Process::exit(), nom_sous_domaine, Domaine_dis_base::nombre_de_sous_domaines_dis(), Equation_base::probleme(), Sous_domaine_dis_base::sous_domaine(), sous_domaine, Domaine_dis_base::sous_domaine_dis(), and Domaine_32_64< _SIZE_ >::ss_domaine().
set_param()
void Perte_Charge_VEF::set_param (Param & param) protected virtual
Reimplemented in Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, and Perte_Charge_Anisotrope_VEF_P1NC.
References Param::ajouter(), Param::ajouter_non_std(), implicite_, and Param::REQUIRED.
Referenced by Perte_Charge_Anisotrope_VEF_P1NC::set_param(), Perte_Charge_Circulaire_VEF_P1NC::set_param(), and Perte_Charge_Directionnelle_VEF_P1NC::set_param().
lire_motcle_non_standard()
int Perte_Charge_VEF::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Parser_U::addVar(), Objet_U::dimension, Process::exit(), lambda, nom_sous_domaine, Objet_U::que_suis_je(), Parser_U::setString(), and sous_domaine.
Referenced by Perte_Charge_Anisotrope_VEF_P1NC::lire_motcle_non_standard(), and Perte_Charge_Circulaire_VEF_P1NC::lire_motcle_non_standard().
associer_domaines()
void Perte_Charge_VEF::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
associe le_dom_VEF et le_dom_Cl_VEF
Implements Source_base.
coeffs_perte_charge()
virtual void Perte_Charge_VEF::coeffs_perte_charge (const DoubleVect & u, const DoubleVect & pos, double t, double norme_u, double dh, double nu, double reynolds, double & coeff_ortho, double & coeff_long, double & u_l, DoubleVect & v_valeur) const protected pure virtual
Appele pour chaque face par ajouter()
Utilise les intermediaires de calcul : u, norme_u, dh_valeur, reynolds Retourne le resultat calcule dans p_charge.
Avantage : bonne factorisation. Inconvenient : cout de l'appel d'une methode virtuelle a l'interieur d'une boucle.
Parameters
u La vitesse a la face courante. 2 ou 3 composantes
pos toto
t titi
norme_u La norme de la vitesse a la face courante
dh Le diametre hydraulique a la face courante (tire de diam_hydr)
nu la viscosite cinematique
reynolds Le nombre de reynolds a la face courante : norme_u * dh_valeur / nu
coeff_ortho coefficient dans la direction orthogonale
coeff_long coefficient dans la direction longitudinale
u_l vitesse dans la direction longitudinale
v_valeur direction_longitudinale p_charge a 2 ou 3 composantes La perte de charge vaut -coeff_long*u_l*v_valeur -coeff_ortho(u -u_v*v_valeur)
Implemented in Perte_Charge_Isotrope_VEF_P1NC, Perte_Charge_Directionnelle_VEF_P1NC, Perte_Charge_Circulaire_VEF_P1NC, and Perte_Charge_Anisotrope_VEF_P1NC.
Referenced by ajouter(), and contribuer_a_avec().
OWN_PTR()
Perte_Charge_VEF::OWN_PTR (Champ_Don_base) protected
Diametre hydraulique utilise dans le calcul de la perte de charge.
OBS_PTR() [1/5]
Perte_Charge_VEF::OBS_PTR (Fluide_base) protected
Fluide associe au probleme.
OBS_PTR() [2/5]
Perte_Charge_VEF::OBS_PTR (Champ_Inc_base) protected
Vitesse associee a l'equation resolue.
OBS_PTR() [3/5]
Perte_Charge_VEF::OBS_PTR (Domaine_VEF) protected
Domaine dans laquelle s'applique la perte de charge.
OBS_PTR() [4/5]
Perte_Charge_VEF::OBS_PTR (Domaine_Cl_VEF) protected
OBS_PTR() [5/5]
Perte_Charge_VEF::OBS_PTR (Sous_domaine_VF) protected
Initialise dans completer()
Member Data Documentation
sous_domaine
bool Perte_Charge_VEF::sous_domaine =false protected
Le terme est-il limite a un sous-domaine ?
Referenced by ajouter(), completer(), contribuer_a_avec(), and lire_motcle_non_standard().
nom_sous_domaine
Nom Perte_Charge_VEF::nom_sous_domaine protected
Nom du sous-domaine, initialise dans readOn()
Referenced by completer(), and lire_motcle_non_standard().
implicite_
int Perte_Charge_VEF::implicite_ protected
Referenced by contribuer_a_avec(), and set_param().
lambda
Parser_U Perte_Charge_VEF::lambda mutable protected
Referenced by Perte_Charge_Anisotrope_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Directionnelle_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Isotrope_VEF_P1NC::coeffs_perte_charge(), Perte_Charge_Circulaire_VEF_P1NC::lire_motcle_non_standard(), and lire_motcle_non_standard().