CEA TRUST Platform: Navier_Stokes_QC Class Reference
Navier_Stokes_QC Class Reference
Public Member Functions
void completer () override
int impr (Sortie &os) const override
Public Member Functions inherited from Navier_Stokes_Fluide_Dilatable_base
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
bool initTimeStep (double dt) override
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
void mettre_a_jour (double temps) override
int preparer_calcul () override
Public Member Functions inherited from Navier_Stokes_std
void abortTimeStep () override
void associer_milieu_base (const Milieu_base &) override
void associer_pb_base (const Probleme_base &) override
virtual void calculer_la_pression_en_pa ()
void completer () override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
const Motcle & domaine_application () const override
Fluide_base & fluide ()
const Fluide_base & fluide () const
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
bool initTimeStep (double dt) override
Entree & lire_cond_init (Entree &) override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Operateur_Div & operateur_divergence ()
const Operateur_Div & operateur_divergence () const
Operateur_Grad & operateur_gradient ()
const Operateur_Grad & operateur_gradient () const
int preparer_calcul () override
virtual void projeter ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
SolveurSys & solveur_pression ()
int verif_Cl () const override
Public Member Functions inherited from Equation_base
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
const Nom & le_nom () const override
int limpr () const
Probleme_base & probleme ()
const Probleme_base & probleme () const
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Navier_Stokes_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_impl (Navier_Stokes_std &, DoubleTab &res)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Navier_Stokes_std
virtual void discretiser_assembleur_pression ()
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_sources (Entree &)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
pour un fluide sans modelisation de la turbulence. On suppose l'hypothese de fluide quasi compressible. Sous ces hypotheses, on utilise la forme suivante des equations de Navier_Stokes: DU/dt = div(terme visqueux) - gradP/rho + sources/rho div U = W avec DU/dt : derivee particulaire de la vitesse rho : masse volumique Rq : l'implementation de la classe permet bien sur de negliger certains termes de l'equation (le terme visqueux, le terme convectif, tel ou tel terme source). L'inconnue est le champ de vitesse.
See also
Navier_Stokes_Fluide_Dilatable_base
Member Function Documentation
completer()
void Navier_Stokes_QC::completer () override virtual
Complete l'equation base, associe la pression a l'equation,.
complete la divergence, le gradient et le solveur pression. Ajout de 2 termes sources: l'un representant la force centrifuge dans le cas axi-symetrique,l'autre intervenant dans la resolution en 2D axisymetrique
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
References Navier_Stokes_Fluide_Dilatable_base::completer(), Equation_base::discretisation(), Equation_base::les_sources, Objet_U::que_suis_je(), and Source::typer_direct().
impr()
int Navier_Stokes_QC::impr (Sortie & os) const override virtual
Imprime les operateurs de l'equation sur un flot de sortie, de facon inconditionnelle.
appelle Operateur_base::impr(os)
Parameters
(Sortie& os) le flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Navier_Stokes_Fluide_Dilatable_base.
References Navier_Stokes_Fluide_Dilatable_base::impr().