CEA TRUST Platform: Transport_Interfaces_base Class Reference
Transport_Interfaces_base Class Reference abstract
#include <Transport_Interfaces_base.h>
Additional Inherited Members
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Actuellement une seule classe instanciable derivant : Transport_Interfaces_FT_Disc
See also
Transport_Interfaces_FT_Disc, Methodes abstraites:, void modifier_vpoint_pour_imposer_vit(...), void integrer_ensemble_lagrange(...)
Member Function Documentation
modifier_vpoint_pour_imposer_vit()
virtual void Transport_Interfaces_base::modifier_vpoint_pour_imposer_vit (const DoubleTab & inco_val, DoubleTab & vpoint0, DoubleTab & vpoint, const DoubleTab & rho_faces, DoubleTab & source_val, const double temps, const double dt, const int is_explicite = 1, const double eta = 1.) pure virtual
get_mesh_tag()
virtual int Transport_Interfaces_base::get_mesh_tag () const pure virtual
Referenced by Convection_Diffusion_Temperature::mise_a_jour_tag_indicatrice_pena_glob(), and Convection_Diffusion_Temperature::verifier_tag_indicatrice_pena_glob().
get_update_indicatrice()
virtual const Champ_base & Transport_Interfaces_base::get_update_indicatrice () pure virtual
Referenced by Convection_Diffusion_Temperature::calcul_indic_pena_global(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), and Convection_Diffusion_Temperature::penalisation_L2().
integrer_ensemble_lagrange()
virtual void Transport_Interfaces_base::integrer_ensemble_lagrange (const double temps) pure virtual