CEA TRUST Platform: Parser Class Reference
Parser Class Reference
Public Member Functions
void addVar (const char *)
double eval ()
Parser ()
Parser (std::string &, int n=1)
virtual void parseString ()
void setImpulsion (double tinit, double periode)
virtual void setNbVar (int nvar)
void setVar (const char *sv, double val)
void setVar (const std::string &v, double val)
void setVar (int i, double val)
Detailed Description
See also
=
Constructor & Destructor Documentation
Parser() [1/3]
Parser::Parser ()
Initialise le parser avec une chaine "0" : ne sert a rien !!
References impuls_T, impuls_t0, impuls_tempo, impuls_tn, init_parser(), root, setNbVar(), state, and str.
Parser() [2/3]
Parser::Parser (const Parser & p)
References set().
~Parser()
Parser::~Parser () virtual
References root.
Parser() [3/3]
Parser::Parser (std::string & s, int n = 1)
Construit un objet Parser avec une chaine specifiee et un nb max de variables a indiquer avec la methode addVar.
References impuls_T, impuls_t0, impuls_tempo, impuls_tn, init_parser(), root, setNbVar(), state, and str.
Member Function Documentation
set()
void Parser::set (const Parser & p)
References impuls_T, impuls_t0, impuls_tempo, impuls_tn, init_parser(), ivar, les_var, les_var_names, maxvar, parseString(), root, setNbVar(), state, and str.
Referenced by Parser(), and ParserView::set().
init_parser()
void Parser::init_parser ()
References map_function_.
Referenced by Parser(), and set().
parseString()
void Parser::parseString () virtual
Construit l'arbre correspondant a la chaine de caracteres. Cet arbre doit etre construit une seule fois et la chaine de caractere est evaluee en parcourant cet arbre par la methode eval() autant de fois qu'on le souhaite.
Reimplemented in ParserView.
References StringTokenizer::check_GRP(), StringTokenizer::EOS, Process::exit(), PNode::left, PNodePod::left, StringTokenizer::nextToken(), PNode::nvalue, PNodePod::nvalue, parserState0(), parserState1(), parserState2(), PNodes, PNode::right, PNodePod::right, root, state, str, PNode::type, PNodePod::type, PNode::value, and PNodePod::value.
Referenced by Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Parser_U::parseString(), ParserView::parseString(), and set().
eval() [1/2]
double Parser::eval () inline
Sert a evaluer l'expression mathematique correspondante a la chaine de caracteres. Poru cela il faut avant toute chose construire l'arbre par la methode parseString().
References eval(), and PNodes.
Referenced by Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), eval(), Parser_U::eval(), ParserView::eval(), and Moyenne_volumique::eval_filtre().
setVar() [1/3]
void Parser::setVar (const char * sv, double val) inline
Fixe la valeur de la variable representee par une chaine sv.
References searchVar(), and setVar().
Referenced by Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Moyenne_volumique::eval_filtre(), setVar(), and Parser_U::setVar().
setVar() [2/3]
void Parser::setVar (const std::string & v, double val) inline
Fixe la valeur de la variable representee par v.
References searchVar(), and setVar().
Referenced by setVar().
setVar() [3/3]
void Parser::setVar (int i, double val) inline
Fixe la valeur de la variable de numero specifie. Ce numero correspondt a l'ordre de l'ajout des variables par la methode addVar().
References ivar, and les_var.
setNbVar()
void Parser::setNbVar (int nvar) virtual
Fixe le nombre max de variables a indiquer avec la methode addVar.
References ivar, les_var, les_var_names, maxvar, and TRUSTArray< _TYPE_, _SIZE_ >::resize().
Referenced by Parser(), set(), and Parser_U::setNbVar().
addVar()
void Parser::addVar (const char * vv)
permet d'ajouter une variable en specifiant sa chaine representative (par ex. : x, y1 etc...)
References Process::exit(), ivar, les_var, les_var_names, Nom::majuscule(), maxvar, TRUSTArray< _TYPE_, _SIZE_ >::resize(), and searchVar().
Referenced by Parser_U::addVar(), and Eval_Puiss_Neutr_VDF_Elem::associer_repartition().
getmaxVar()
int Parser::getmaxVar () inline
References maxvar.
Referenced by Parser_U::getmaxVar().
getNbVar()
int Parser::getNbVar () inline
References ivar.
Referenced by Parser_U::getNbVar(), and ParserView::parseString().
getString()
std::string& Parser::getString () inline
References str.
Referenced by Parser_U::getString().
setString()
void Parser::setString (const std::string & s) inline
References str.
Referenced by Parser_U::setString().
addCst()
void Parser::addCst (const Constante & cst)
Referenced by Parser_U::addCst().
setImpulsion()
void Parser::setImpulsion (double tinit, double periode) inline
Fixe le temps initial et la periode de la fonction impulsion
References impuls_T, impuls_t0, impuls_tempo, and impuls_tn.
Referenced by Parser_U::setImpulsion().
test_op_binaire()
int Parser::test_op_binaire (int type) protected
References StringTokenizer::ADD, StringTokenizer::AND, StringTokenizer::DIVIDE, StringTokenizer::EQ, StringTokenizer::GE, StringTokenizer::GT, StringTokenizer::LE, StringTokenizer::LT, StringTokenizer::MAX, StringTokenizer::MIN, StringTokenizer::MOD, StringTokenizer::MULTIPLY, StringTokenizer::NEQ, StringTokenizer::OR, StringTokenizer::POWER, and StringTokenizer::SUBTRACT.
Referenced by parserState2().
precedence()
int Parser::precedence (int op) static protected
References StringTokenizer::ADD, StringTokenizer::AND, StringTokenizer::DIVIDE, StringTokenizer::ENDGRP, StringTokenizer::EQ, StringTokenizer::GE, StringTokenizer::GRP, StringTokenizer::GT, StringTokenizer::LE, StringTokenizer::LT, StringTokenizer::MAX, StringTokenizer::MIN, StringTokenizer::MOD, StringTokenizer::MULTIPLY, StringTokenizer::NEQ, StringTokenizer::OR, StringTokenizer::POWER, and StringTokenizer::SUBTRACT.
Referenced by parserState2().
eval() [2/2]
double Parser::eval (const PNodePod & node) inline protected
References eval(), evalFunc(), evalOp(), Process::exit(), PNodePod::left, les_var, PNodePod::nvalue, PNodes, PNodePod::right, PNodePod::type, and PNodePod::value.
evalOp()
KOKKOS_INLINE_FUNCTION double Parser::evalOp (const PNodePod & node, double x, double y) protected
References Process::exit(), Process::Kokkos_exit(), and PNodePod::value.
Referenced by eval().
evalFunc()
KOKKOS_INLINE_FUNCTION double Parser::evalFunc (const PNodePod & node, double x) protected
References PNodePod::value.
Referenced by eval().
parserState0()
void Parser::parserState0 (StringTokenizer * tokenizer, PSTACK(PNode) * ob, STACK(int) * op) protected
References StringTokenizer::ADD, Process::exit(), StringTokenizer::getNValue(), StringTokenizer::getSValue(), StringTokenizer::GRP, les_var_names, StringTokenizer::NUMBER, PNode::nvalue, root, searchCst(), searchFunc(), searchVar(), state, str, StringTokenizer::STRING, StringTokenizer::SUBTRACT, PNode::type, StringTokenizer::type, and PNode::value.
Referenced by parseString().
parserState1()
void Parser::parserState1 (StringTokenizer * tokenizer, PSTACK(PNode) * ob, STACK(int) * op) protected
References Process::exit(), StringTokenizer::getNValue(), StringTokenizer::getSValue(), StringTokenizer::GRP, les_var_names, StringTokenizer::NUMBER, PNode::nvalue, searchCst(), searchFunc(), searchVar(), state, str, StringTokenizer::STRING, PNode::type, StringTokenizer::type, and PNode::value.
Referenced by parseString().
parserState2()
void Parser::parserState2 (StringTokenizer * tokenizer, PSTACK(PNode) * ob, STACK(int) * op) protected
References StringTokenizer::ADD, StringTokenizer::DIVIDE, StringTokenizer::ENDGRP, StringTokenizer::EOS, Process::exit(), StringTokenizer::GE, StringTokenizer::getNValue(), StringTokenizer::getSValue(), StringTokenizer::GRP, StringTokenizer::GT, StringTokenizer::LE, PNode::left, StringTokenizer::LT, StringTokenizer::MOD, StringTokenizer::MULTIPLY, StringTokenizer::NUMBER, StringTokenizer::POWER, precedence(), PNode::right, state, StringTokenizer::STRING, StringTokenizer::SUBTRACT, test_op_binaire(), PNode::type, StringTokenizer::type, and PNode::value.
Referenced by parseString().
searchVar() [1/2]
int Parser::searchVar (const std::string & s) inline protected
References searchVar().
Referenced by addVar(), parserState0(), parserState1(), searchVar(), and setVar().
searchVar() [2/2]
int Parser::searchVar (const char * sv) inline protected
References les_var_names, and Noms::rang().
searchCst()
int Parser::searchCst (const std::string & v) protected
References Constante::le_nom().
Referenced by parserState0(), and parserState1().
searchFunc()
int Parser::searchFunc (const std::string & v) protected
References map_function_.
Referenced by parserState0(), and parserState1().
LIST()
Parser::LIST (Constante) protected
Member Data Documentation
state
int Parser::state protected
Referenced by Parser(), parserState0(), parserState1(), parserState2(), parseString(), and set().
c_pi
Constante Parser::c_pi protected
impuls_T
double Parser::impuls_T protected
Referenced by Parser(), set(), and setImpulsion().
impuls_t0
double Parser::impuls_t0 protected
Referenced by Parser(), set(), and setImpulsion().
impuls_tn
double Parser::impuls_tn protected
Referenced by Parser(), set(), and setImpulsion().
impuls_tempo
double Parser::impuls_tempo protected
Referenced by Parser(), set(), and setImpulsion().
root
PNode* Parser::root protected
Referenced by Parser(), parserState0(), parseString(), set(), and ~Parser().
PNodes
std::vector<PNodePod> Parser::PNodes protected
Referenced by eval(), parseString(), and ParserView::parseString().
str
std::string Parser::str protected
Referenced by getString(), Parser(), parserState0(), parserState1(), parseString(), set(), and setString().
les_var
ArrOfDouble Parser::les_var protected
Referenced by addVar(), eval(), set(), setNbVar(), and setVar().
les_var_names
Noms Parser::les_var_names protected
Referenced by addVar(), parserState0(), parserState1(), searchVar(), set(), and setNbVar().
map_function_
std::map<std::string, int> Parser::map_function_ protected
Referenced by init_parser(), and searchFunc().
maxvar
int Parser::maxvar protected
Referenced by addVar(), getmaxVar(), set(), and setNbVar().
ivar
int Parser::ivar protected
Referenced by addVar(), getNbVar(), set(), setNbVar(), setVar(), and ParserView::setVar().