CEA TRUST Platform: Op_Ecart_type Class Reference
Op_Ecart_type Class Reference
Public Member Functions
const Nom & le_nom () const override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
le_nom()
const Nom& Op_Ecart_type::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Implements Operateur_Statistique_tps_base.
References integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), and Field_base::le_nom().
temps()
double Op_Ecart_type::temps () const inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_base::temps().
integrale()
const Integrale_tps_Champ& Op_Ecart_type::integrale () const inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_carre_champ_.
Referenced by Champ_Generique_Ecart_Type::integrale(), Champ_Generique_Ecart_Type::temps(), and Champ_Generique_Ecart_Type::valeurs_carre().
moyenne()
const Op_Moyenne& Op_Ecart_type::moyenne () const inline
Referenced by completer(), Champ_Generique_Ecart_Type::dt_integration(), and Champ_Generique_Ecart_Type::valeurs().
valeurs() [1/2]
DoubleTab& Op_Ecart_type::valeurs () inline
Referenced by calculer_valeurs().
valeurs() [2/2]
const DoubleTab& Op_Ecart_type::valeurs () const inline
valeurs_carre() [1/2]
DoubleTab& Op_Ecart_type::valeurs_carre () inline
References integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Don_base::valeurs().
Referenced by calculer_valeurs(), and completer().
valeurs_carre() [2/2]
const DoubleTab& Op_Ecart_type::valeurs_carre () const inline
References integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Don_base::valeurs().
dt_integration()
double Op_Ecart_type::dt_integration () const inline
Referenced by calculer_valeurs().
dt_integration_carre()
double Op_Ecart_type::dt_integration_carre () const inline
References Integrale_tps_Champ::dt_integration(), and integrale_carre_champ_.
Referenced by calculer_valeurs(), and Champ_Generique_Ecart_Type::dt_integration_carre().
mettre_a_jour()
void Op_Ecart_type::mettre_a_jour (double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_carre_champ_, and Integrale_tps_Champ::mettre_a_jour().
initialiser()
void Op_Ecart_type::initialiser (double val) inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Don_base::valeurs().
associer()
void Op_Ecart_type::associer (const Domaine_dis_base & une_zdis, const Champ_Generique_base & le_champ, double t1, double t2) inline override virtual
Implements Operateur_Statistique_tps_base.
References Integrale_tps_Champ::associer(), Champ_Fonc_base::associer_domaine_dis_base(), Nom::debute_par(), Champ_Generique_base::get_champ(), integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), Objet_U::que_suis_je(), Nom::suffix(), and Integrale_tps_Champ::typer_champ().
Referenced by Champ_Generique_Ecart_Type::completer().
fixer_tstat_deb()
void Op_Ecart_type::fixer_tstat_deb (double tdeb, double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
References Integrale_tps_Champ::fixer_dt_integr(), Integrale_tps_Champ::fixer_t_debut(), Integrale_tps_Champ::fixer_tps_integrale(), and integrale_carre_champ_.
fixer_tstat_fin()
void Op_Ecart_type::fixer_tstat_fin (double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
References Integrale_tps_Champ::fixer_t_fin(), and integrale_carre_champ_.
associer_op_stat()
void Op_Ecart_type::associer_op_stat (const Operateur_Statistique_tps_base & un_op_stat) inline override virtual
Reimplemented from Operateur_Statistique_tps_base.
Referenced by Champ_Generique_Ecart_Type::completer().
completer()
void Op_Ecart_type::completer (const Probleme_base & Pb, const Nom & prefix) override virtual
Implements Operateur_Statistique_tps_base.
References Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Probleme_base::domaine_dis(), Field_base::fixer_nb_comp(), Field_base::fixer_unite(), Field_base::fixer_unites(), Op_Moyenne::integrale(), integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), moyenne(), Field_base::nb_comp(), Field_base::nommer(), OBS_PTR(), TRUSTTab< _TYPE_, _SIZE_ >::reset(), Probleme_base::schema_temps(), Champ_Fonc_base::set_pdi_name(), Schema_Temps_base::temps_courant(), Field_base::unite(), Field_base::unites(), Champ_Proto::valeurs(), and valeurs_carre().
Referenced by Champ_Generique_Ecart_Type::completer().
calculer_valeurs()
DoubleTab Op_Ecart_type::calculer_valeurs () const override virtual
Implements Operateur_Statistique_tps_base.
References TRUSTVect< _TYPE_, _SIZE_ >::abs(), TRUSTVect< _TYPE_, _SIZE_ >::ajoute_carre(), dt_integration(), dt_integration_carre(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::racine_carree(), valeurs(), and valeurs_carre().
Referenced by Champ_Generique_Ecart_Type::get_champ().
data_a_sauvegarder()
std::vector< YAML_data > Op_Ecart_type::data_a_sauvegarder () const inline override virtual
for PDI IO: retrieve name, type and dimensions of the field to save/restore
Reimplemented from Operateur_Statistique_tps_base.
References Champ_Fonc_base::get_pdi_name(), Nom::getString(), integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and Champ_Don_base::valeurs().
sauvegarder()
int Op_Ecart_type::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
References integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Fonc_base::sauvegarder().
reprendre()
int Op_Ecart_type::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
References integrale_carre_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Fonc_base::reprendre().
OBS_PTR() [1/2]
Op_Ecart_type::OBS_PTR (Op_Moyenne) protected
Referenced by completer().
OBS_PTR() [2/2]
Op_Ecart_type::OBS_PTR (Integrale_tps_Champ) protected
Member Data Documentation
integrale_carre_champ_
Integrale_tps_Champ Op_Ecart_type::integrale_carre_champ_ protected
Referenced by associer(), completer(), data_a_sauvegarder(), dt_integration_carre(), fixer_tstat_deb(), fixer_tstat_fin(), initialiser(), integrale(), le_nom(), mettre_a_jour(), reprendre(), sauvegarder(), temps(), and valeurs_carre().