CEA TRUST Platform: Transport_2eq_base Class Reference
Transport_2eq_base Class Reference abstract
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
double calculer_pas_de_temps () const override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
Modele_turbulence_hyd_2_eq_base & modele_turbulence ()
const Modele_turbulence_hyd_2_eq_base & modele_turbulence () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual int impr (Sortie &os) const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
de transport des modeles a deux equations type k-DISSIP
Member Function Documentation
set_param()
void Transport_2eq_base::set_param (Param & param) override virtual
Reimplemented from Equation_base.
References Param::ajouter_condition(), Param::ajouter_flag(), Param::ajouter_non_std(), disable_VEF_mean_value_corrections_, and Equation_base::set_param().
associer()
void Transport_2eq_base::associer (const Equation_base & eqn_hydr)
References Equation_base::associer_domaine_dis(), Equation_base::associer_pb_base(), Equation_base::associer_sch_tps_base(), Equation_base::domaine_dis(), Equation_base::probleme(), and Equation_base::schema_temps().
associer_vitesse()
void Transport_2eq_base::associer_vitesse (const Champ_base & vit) inline
associer_milieu_base()
void Transport_2eq_base::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Associe un milieu physique a l'equation.
Parameters
(Milieu_base& un_milieu) le milieu physique a associer a l'equation
Implements Equation_base.
milieu() [1/2]
Milieu_base & Transport_2eq_base::milieu () override virtual
Renvoie le milieu (fluide) associe a l'equation.
Returns
(Milieu_base&) le milieu (fluide) associe a l'equation
Implements Equation_base.
References Process::exit(), and Objet_U::que_suis_je().
milieu() [2/2]
const Milieu_base & Transport_2eq_base::milieu () const override virtual
Renvoie le milieu (fluide) associe a l'equation.
(version const)
Returns
(Milieu_base&) le milieu (fluide) associe a l'equation
Implements Equation_base.
References Process::exit(), and Objet_U::que_suis_je().
calculer_pas_de_temps()
double Transport_2eq_base::calculer_pas_de_temps () const override virtual
Calcul du prochain pas de temps.
Renvoie l'inverse de la somme des inverses des pas de temps calcules par les operateurs. Ces pas de temps sont ceux pour le schema d'Euler explicite. Le pas de temps n'est pas majore par dt_max, ceci est fait dans corriger_dt_calcule
Returns
(double) inverse de la somme des inverses des pas de temps calcules par les operateurs
Reimplemented from Equation_base.
References Equation_base::calculer_pas_de_temps(), Probleme_base::equation(), and Equation_base::probleme().
modele_turbulence() [1/2]
const Modele_turbulence_hyd_2_eq_base & Transport_2eq_base::modele_turbulence () const inline
Renvoie le modele de turbulence associe a l'equation.
(version const)
Returns
(Modele_turbulence_hyd_base&) le modele de turbulence associe a l'equation
Referenced by lire_op_diff_turbulent().
modele_turbulence() [2/2]
Modele_turbulence_hyd_2_eq_base & Transport_2eq_base::modele_turbulence () inline
Renvoie le modele de turbulence associe a l'equation.
Returns
(Modele_turbulence_hyd_base&) le modele de turbulence associe a l'equation
associer_modele_turbulence()
virtual void Transport_2eq_base::associer_modele_turbulence (const Modele_turbulence_hyd_2_eq_base &) pure virtual
Referenced by Modele_turbulence_hyd_2_eq_base::lire_motcle_non_standard().
get_position_cells()
void Transport_2eq_base::get_position_cells (Nom & position, int & n) protected
References Objet_U::dimension, Equation_base::domaine_dis(), and Domaine_VF::xp().
get_position_faces()
void Transport_2eq_base::get_position_faces (Nom & position, int & n) protected
References Objet_U::dimension, Equation_base::domaine_dis(), and Domaine_VF::xv().
lire_op_diff_turbulent()
Entree & Transport_2eq_base::lire_op_diff_turbulent (Entree & is) protected
References Operateur_Diff::associer_diffusivite(), Operateur_base::associer_eqn(), Objet_U::axi, Nom::contient(), Operateur_Diff::diffusivite(), Equation_base::discretisation(), Modele_turbulence_hyd_base::equation(), Process::exit(), Equation_base::inconnue(), Operateur_Diff::l_op_base(), modele_turbulence(), Field_base::nb_comp(), Objet_U::que_suis_je(), Nom::suffix(), terme_diffusif, and Operateur_Diff::typer().
OBS_PTR() [1/3]
Transport_2eq_base::OBS_PTR (Milieu_base) protected
OBS_PTR() [2/3]
Transport_2eq_base::OBS_PTR (Champ_Inc_base) protected
OBS_PTR() [3/3]
Transport_2eq_base::OBS_PTR (Modele_turbulence_hyd_2_eq_base) protected
Member Data Documentation
terme_diffusif
Operateur_Diff Transport_2eq_base::terme_diffusif protected
Referenced by lire_op_diff_turbulent().
terme_convectif
Operateur_Conv Transport_2eq_base::terme_convectif protected
disable_VEF_mean_value_corrections_
bool Transport_2eq_base::disable_VEF_mean_value_corrections_ = false protected
Referenced by set_param().