CEA TRUST Platform: Op_Conv_EF_VEF_P1NC Class Reference
Op_Conv_EF_VEF_P1NC Class Reference
Additional Inherited Members
Public Member Functions inherited from Op_Conv_VEF_base
double calculer_dt_stab () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void completer ()
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe represente l'operateur de convection associe a une equation de transport d'un scalaire. La discretisation est VEF Le champ convecte est scalaire ou vecteur de type Champ_P1NC Le schema de convection est du type Amont Les methodes pour l'implicite sont codees.
See also
Operateur_Conv_base
Member Function Documentation
ajouter()
DoubleTab & Op_Conv_EF_VEF_P1NC::ajouter (const DoubleTab & transporte_2, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References antisym, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Champ_P1NC::filtrer_L2(), Champ_P1NC::filtrer_resu(), filtrer_resu, Op_Conv_VEF_base::fluent_, Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Op_VEF_Face::modifier_flux(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Op_Conv_VEF_base::phi_u_transportant(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), transportant_bar, transporte_bar, Champ_Inc_base::valeurs(), and Domaine_VF::volumes_entrelaces().
dimensionner()
void Op_Conv_EF_VEF_P1NC::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice au moyen de la methode dimensionner de la classe Op_VEF_Face.
Reimplemented from Operateur_base.
References Op_VEF_Face::dimensionner().
modifier_pour_Cl()
void Op_Conv_EF_VEF_P1NC::modifier_pour_Cl (Matrice_Morse & matrice, DoubleTab & secmem) const inline override virtual
On modifie le second membre et la matrice dans le cas des conditions de dirichlet.
Reimplemented from Operateur_base.
References Op_VEF_Face::modifier_pour_Cl().
contribuer_a_avec()
void Op_Conv_EF_VEF_P1NC::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice des inconnues implicite.
Reimplemented from Operateur_base.
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Conv_EF_VEF_P1NC::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
References contribue_au_second_membre().
contribue_au_second_membre()
void Op_Conv_EF_VEF_P1NC::contribue_au_second_membre (DoubleTab & resu) const
References Process::exit().
Referenced by contribuer_au_second_membre().
ajouter_contribution()
void Op_Conv_EF_VEF_P1NC::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
References Process::exit().
Referenced by contribuer_a_avec().
Member Data Documentation
transportant_bar
int Op_Conv_EF_VEF_P1NC::transportant_bar = 0 protected
Referenced by ajouter().
transporte_bar
int Op_Conv_EF_VEF_P1NC::transporte_bar = 1 protected
Referenced by ajouter().
filtrer_resu
int Op_Conv_EF_VEF_P1NC::filtrer_resu = 1 protected
Referenced by ajouter().
antisym
int Op_Conv_EF_VEF_P1NC::antisym = 1 protected
Referenced by ajouter().