CEA TRUST Platform: Op_Conv_EF_base Class Reference
Op_Conv_EF_base Class Reference
#include <Op_Conv_EF_base.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Op_EF_base
void dimensionner (const Domaine_EF &, const Domaine_Cl_EF &, Matrice_Morse &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Classe de base des operateurs de convection EF
Member Function Documentation
associer_vitesse()
void Op_Conv_EF_base::associer_vitesse (const Champ_base & vit) override virtual
Implements Operateur_Conv_base.
vitesse() [1/2]
const Champ_Inc_base & Op_Conv_EF_base::vitesse () const
vitesse() [2/2]
Champ_Inc_base & Op_Conv_EF_base::vitesse ()
associer()
void Op_Conv_EF_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base &) override virtual
Implements Operateur_base.
calculer()
DoubleTab & Op_Conv_EF_base::calculer (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::ajouter().
calculer_dt_stab()
double Op_Conv_EF_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Operateur_Conv_base::fixer_dt_stab_conv(), and Process::mp_min().
calculer_pour_post()
void Op_Conv_EF_base::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int) const override virtual
Reimplemented from MorEqn.
References Process::exit().
remplir_fluent()
void Op_Conv_EF_base::remplir_fluent () const virtual
References Operateur_base::ajouter(), MorEqn::equation(), and Operateur_base::flux_bords_.
impr()
int Op_Conv_EF_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Op_EF_base::impr().
associer_domaine_cl_dis()
void Op_Conv_EF_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base & domaine_cl_dis) override virtual
Reimplemented from Operateur_base.
phi_u_transportant()
int Op_Conv_EF_base::phi_u_transportant (const Equation_base & eq) const
definit si l'on convecte psi avec phi*u ou avec u
References Equation_base::inconnue(), and Field_base::le_nom().
completer()
void Op_Conv_EF_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer(), MorEqn::equation(), and Op_EF_base::marque_elem().
Referenced by Op_Conv_EF::completer().
OBS_PTR() [1/3]
Op_Conv_EF_base::OBS_PTR (Domaine_EF) protected
OBS_PTR() [2/3]
Op_Conv_EF_base::OBS_PTR (Domaine_Cl_EF) protected
OBS_PTR() [3/3]
Op_Conv_EF_base::OBS_PTR (Champ_Inc_base) protected
Member Data Documentation
fluent_
DoubleVect Op_Conv_EF_base::fluent_ mutable protected
Referenced by Op_Conv_EF::ajouter_sous_cond_template().