CEA TRUST Platform: TPPI Class Reference
TPPI Class Reference abstract
Detailed Description
Interface commune pour TRUST et ses baltiks qui permet appeler les methodes de la lib EOS/CoolProp Methods disponibles en temperature et enthalpie, egalement pour la saturation
Constructor & Destructor Documentation
TPPI()
TPPI::TPPI () default
~TPPI()
virtual TPPI::~TPPI () virtual default
Member Function Documentation
set_fluide_generique()
virtual void TPPI::set_fluide_generique (const char * const , const char * const) inline virtual
Reimplemented in EOS_to_TRUST_generique, and CoolProp_to_TRUST_generique.
set_saturation_generique()
virtual void TPPI::set_saturation_generique (const char * const , const char * const) inline virtual
Reimplemented in EOS_to_TRUST_Sat_generique, and CoolProp_to_TRUST_Sat_generique.
set_phase()
virtual void TPPI::set_phase (const Motcle &) inline virtual
Reimplemented in CoolProp_to_TRUST.
set_path_refprop()
virtual void TPPI::set_path_refprop () inline virtual
Reimplemented in CoolProp_to_TRUST.
verify_phase()
virtual void TPPI::verify_phase (const Motcle &) inline virtual
Reimplemented in CoolProp_to_TRUST.
desactivate_handler()
virtual void TPPI::desactivate_handler (bool op = true) inline virtual
Reimplemented in EOS_to_TRUST.
tppi_get_p_min()
virtual double TPPI::tppi_get_p_min () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_p_max()
virtual double TPPI::tppi_get_p_max () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_h_min()
virtual double TPPI::tppi_get_h_min () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_h_max()
virtual double TPPI::tppi_get_h_max () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_T_min()
virtual double TPPI::tppi_get_T_min () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_T_max()
virtual double TPPI::tppi_get_T_max () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_rho_min()
virtual double TPPI::tppi_get_rho_min () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_rho_max()
virtual double TPPI::tppi_get_rho_max () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_p_crit()
virtual double TPPI::tppi_get_p_crit () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_h_crit()
virtual double TPPI::tppi_get_h_crit () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_T_crit()
virtual double TPPI::tppi_get_T_crit () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
tppi_get_rho_crit()
virtual double TPPI::tppi_get_rho_crit () const pure virtual
Implemented in EOS_to_TRUST, and CoolProp_to_TRUST.
all_unknowns_range()
MRange TPPI::all_unknowns_range () virtual
Reimplemented in EOS_to_TRUST.
not_implemented()
template<typename TYPE > TYPE TPPI::not_implemented (const char * nom_funct) const inline
tppi_get_rho_pT()
virtual int TPPI::tppi_get_rho_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_rho_dp_pT()
virtual int TPPI::tppi_get_rho_dp_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_rho_dT_pT()
virtual int TPPI::tppi_get_rho_dT_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_h_pT()
virtual int TPPI::tppi_get_h_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
Referenced by CoolProp_to_TRUST::tppi_get_h_max(), and CoolProp_to_TRUST::tppi_get_h_min().
tppi_get_h_dp_pT()
virtual int TPPI::tppi_get_h_dp_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_h_dT_pT()
virtual int TPPI::tppi_get_h_dT_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_cp_pT()
virtual int TPPI::tppi_get_cp_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_cp_dp_pT()
virtual int TPPI::tppi_get_cp_dp_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_cp_dT_pT()
virtual int TPPI::tppi_get_cp_dT_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_mu_pT()
virtual int TPPI::tppi_get_mu_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_mu_dp_pT()
virtual int TPPI::tppi_get_mu_dp_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_mu_dT_pT()
virtual int TPPI::tppi_get_mu_dT_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_lambda_pT()
virtual int TPPI::tppi_get_lambda_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_lambda_dp_pT()
virtual int TPPI::tppi_get_lambda_dp_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_lambda_dT_pT()
virtual int TPPI::tppi_get_lambda_dT_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_sigma_pT()
virtual int TPPI::tppi_get_sigma_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in CoolProp_to_TRUST_Sat_generique, and EOS_to_TRUST_Sat_generique.
tppi_get_sigma_dp_pT()
virtual int TPPI::tppi_get_sigma_dp_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_sigma_dT_pT()
virtual int TPPI::tppi_get_sigma_dT_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_beta_pT()
virtual int TPPI::tppi_get_beta_pT (const SpanD P, const SpanD T, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in EOS_to_TRUST_generique.
tppi_get_rho_ph()
virtual int TPPI::tppi_get_rho_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_rho_dp_ph()
virtual int TPPI::tppi_get_rho_dp_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_rho_dh_ph()
virtual int TPPI::tppi_get_rho_dh_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_T_ph()
virtual int TPPI::tppi_get_T_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_T_dp_ph()
virtual int TPPI::tppi_get_T_dp_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_T_dh_ph()
virtual int TPPI::tppi_get_T_dh_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_cp_ph()
virtual int TPPI::tppi_get_cp_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_cp_dp_ph()
virtual int TPPI::tppi_get_cp_dp_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_cp_dh_ph()
virtual int TPPI::tppi_get_cp_dh_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_mu_ph()
virtual int TPPI::tppi_get_mu_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_mu_dp_ph()
virtual int TPPI::tppi_get_mu_dp_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_mu_dh_ph()
virtual int TPPI::tppi_get_mu_dh_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_lambda_ph()
virtual int TPPI::tppi_get_lambda_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_lambda_dp_ph()
virtual int TPPI::tppi_get_lambda_dp_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_lambda_dh_ph()
virtual int TPPI::tppi_get_lambda_dh_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_sigma_ph()
virtual int TPPI::tppi_get_sigma_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in CoolProp_to_TRUST_Sat_generique, and EOS_to_TRUST_Sat_generique.
tppi_get_sigma_dp_ph()
virtual int TPPI::tppi_get_sigma_dp_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_sigma_dh_ph()
virtual int TPPI::tppi_get_sigma_dh_ph (const SpanD P, const SpanD H, SpanD R, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_beta_ph()
virtual int TPPI::tppi_get_beta_ph (const SpanD P, const SpanD H, SpanD R, int ncomp, int ind) const inline virtual
Reimplemented in EOS_to_TRUST_generique.
tppi_get_T_sat_p()
virtual int TPPI::tppi_get_T_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_T_sat_d_p_p()
virtual int TPPI::tppi_get_T_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_p_sat_T()
virtual int TPPI::tppi_get_p_sat_T (const SpanD T, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in EOS_to_TRUST_Sat_generique.
tppi_get_p_sat_d_T_T()
virtual int TPPI::tppi_get_p_sat_d_T_T (const SpanD T, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in EOS_to_TRUST_Sat_generique.
tppi_get_h_l_sat_p()
virtual int TPPI::tppi_get_h_l_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_h_l_sat_d_p_p()
virtual int TPPI::tppi_get_h_l_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_h_v_sat_p()
virtual int TPPI::tppi_get_h_v_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_h_v_sat_d_p_p()
virtual int TPPI::tppi_get_h_v_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_lvap_p()
virtual int TPPI::tppi_get_lvap_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in EOS_to_TRUST_Sat_generique.
References tppi_get_single_sat_p_().
tppi_get_lvap_d_p_p()
virtual int TPPI::tppi_get_lvap_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in EOS_to_TRUST_Sat_generique.
References tppi_get_single_sat_p_().
tppi_get_rho_l_sat_p()
virtual int TPPI::tppi_get_rho_l_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_rho_l_sat_d_p_p()
virtual int TPPI::tppi_get_rho_l_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_rho_v_sat_p()
virtual int TPPI::tppi_get_rho_v_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_rho_v_sat_d_p_p()
virtual int TPPI::tppi_get_rho_v_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_cp_l_sat_p()
virtual int TPPI::tppi_get_cp_l_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_cp_l_sat_d_p_p()
virtual int TPPI::tppi_get_cp_l_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_cp_v_sat_p()
virtual int TPPI::tppi_get_cp_v_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_cp_v_sat_d_p_p()
virtual int TPPI::tppi_get_cp_v_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
References tppi_get_single_sat_p_().
tppi_get_lambda_l_sat_p()
virtual int TPPI::tppi_get_lambda_l_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in CoolProp_to_TRUST_Sat_generique.
tppi_get_lambda_l_sat_d_p_p()
virtual int TPPI::tppi_get_lambda_l_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_lambda_v_sat_p()
virtual int TPPI::tppi_get_lambda_v_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in CoolProp_to_TRUST_Sat_generique.
tppi_get_lambda_v_sat_d_p_p()
virtual int TPPI::tppi_get_lambda_v_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_mu_l_sat_p()
virtual int TPPI::tppi_get_mu_l_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in CoolProp_to_TRUST_Sat_generique.
tppi_get_mu_l_sat_d_p_p()
virtual int TPPI::tppi_get_mu_l_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_mu_v_sat_p()
virtual int TPPI::tppi_get_mu_v_sat_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
Reimplemented in CoolProp_to_TRUST_Sat_generique.
tppi_get_mu_v_sat_d_p_p()
virtual int TPPI::tppi_get_mu_v_sat_d_p_p (const SpanD P, SpanD res, int ncomp = 1, int ind = 0) const inline virtual
tppi_get_single_property_T_()
virtual int TPPI::tppi_get_single_property_T_ (Loi_en_T , const SpanD, const SpanD, SpanD , int , int) const inline protected virtual
tppi_get_single_property_h_()
virtual int TPPI::tppi_get_single_property_h_ (Loi_en_h , const SpanD, const SpanD, SpanD , int , int) const inline protected virtual
tppi_get_single_sat_p_()
virtual int TPPI::tppi_get_single_sat_p_ (SAT , const SpanD, SpanD , int , int , bool is_liq = true) const inline protected virtual
Referenced by tppi_get_cp_l_sat_d_p_p(), tppi_get_cp_l_sat_p(), tppi_get_cp_v_sat_d_p_p(), tppi_get_cp_v_sat_p(), tppi_get_h_l_sat_d_p_p(), tppi_get_h_l_sat_p(), tppi_get_h_v_sat_d_p_p(), tppi_get_h_v_sat_p(), tppi_get_lvap_d_p_p(), tppi_get_lvap_p(), tppi_get_rho_l_sat_d_p_p(), tppi_get_rho_l_sat_p(), tppi_get_rho_v_sat_d_p_p(), tppi_get_rho_v_sat_p(), tppi_get_T_sat_d_p_p(), and tppi_get_T_sat_p().
tppi_get_CPMLB_pb_multiphase_pT()
virtual int TPPI::tppi_get_CPMLB_pb_multiphase_pT (const MSpanD input, MLoiSpanD prop, int ncomp = 1, int id = 0) const inline virtual
Reimplemented in EOS_to_TRUST_generique, and CoolProp_to_TRUST_generique.
tppi_get_all_pb_multiphase_pT()
virtual int TPPI::tppi_get_all_pb_multiphase_pT (const MSpanD input, MLoiSpanD inter, MLoiSpanD bord, int ncomp = 1, int id = 0) const inline virtual
Reimplemented in EOS_to_TRUST_generique, and CoolProp_to_TRUST_generique.
tppi_get_CPMLB_pb_multiphase_ph()
virtual int TPPI::tppi_get_CPMLB_pb_multiphase_ph (const MSpanD input, MLoiSpanD_h prop, int ncomp = 1, int id = 0) const inline virtual
Reimplemented in EOS_to_TRUST_generique.
tppi_get_all_pb_multiphase_ph()
virtual int TPPI::tppi_get_all_pb_multiphase_ph (const MSpanD input, MLoiSpanD_h inter, MLoiSpanD_h bord, int ncomp = 1, int id = 0) const inline virtual
Reimplemented in EOS_to_TRUST_generique.
tppi_get_all_flux_interfacial_pb_multiphase()
virtual int TPPI::tppi_get_all_flux_interfacial_pb_multiphase (const SpanD P, MSatSpanD , int ncomp = 1, int id = 0) const inline virtual
Reimplemented in CoolProp_to_TRUST_Sat_generique, and EOS_to_TRUST_Sat_generique.
tppi_get_all_prop_loi_F5()
virtual int TPPI::tppi_get_all_prop_loi_F5 (const MSpanD, MLoiSpanD_h , int ncomp = 1, int id = 0, bool is_liq = true) const inline virtual
Reimplemented in EOS_to_TRUST_generique, and CoolProp_to_TRUST_generique.
tppi_get_all_sat_loi_F5()
virtual int TPPI::tppi_get_all_sat_loi_F5 (const MSpanD input, MSatSpanD sats, int ncomp = 1, int id = 0) const inline virtual
Reimplemented in CoolProp_to_TRUST_Sat_generique, and EOS_to_TRUST_Sat_generique.
set_user_uniform_sigma()
virtual void TPPI::set_user_uniform_sigma (const double) inline virtual
Reimplemented in EOS_to_TRUST_Sat_generique, and CoolProp_to_TRUST_Sat_generique.