CEA TRUST Platform: TRUSTTrav< _TYPE_ > Class Template Reference
TRUSTTrav< _TYPE_ > Class Template Reference
#include <TRUSTTrav.h>
Additional Inherited Members
Public Member Functions inherited from TRUSTTab< _TYPE_, int >
int dimension (int d) const
int dimension_int (int d) const
void from_tid_to_int (TRUSTTab< int, int > &out) const
void ref_array (TRUSTArray< _TYPE_, int > &, int start=0, int sz=-1) override
void ref_data (_TYPE_ *ptr, int size) override
void reset () override
void resize_tab (int n, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) override
Public Member Functions inherited from TRUSTVect< _TYPE_, _SIZE_ >
void ref_array (TRUSTArray< _TYPE_, _SIZE_ > &, _SIZE_ start=0, _SIZE_ sz=-1) override
void ref_data (_TYPE_ *ptr, _SIZE_ new_size) override
void resize_tab (_SIZE_ n, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) override
TRUSTVect (_SIZE_ n)
TRUSTVect (const TRUSTVect &v)
Public Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
_TYPE_ * addr ()
void append_array (_TYPE_ valeur)
TRUSTArray & inject_array (const TRUSTArray &source, _SIZE_ nb_elements=-1, _SIZE_ first_element_dest=0, _SIZE_ first_element_source=0)
TRUSTArray & operator*= (const _TYPE_ dy)
TRUSTArray & operator+= (const _TYPE_ dy)
TRUSTArray & operator+= (const TRUSTArray &y)
TRUSTArray & operator-= (const _TYPE_ dy)
TRUSTArray & operator-= (const TRUSTArray &y)
TRUSTArray & operator/= (const _TYPE_ dy)
TRUSTArray & operator= (_TYPE_ x)
TRUSTArray & operator= (const TRUSTArray &)
_TYPE_ & operator[] (_SIZE_ i)
void ordonne_array ()
void ref_as_small (TRUSTArray< float, int > &out) const
int ref_count () const
void resize_array (_SIZE_ new_size, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT)
void set_mem_storage (const STORAGE storage)
_SIZE_ size_array () const
TRUSTArray (const TRUSTArray &A)
virtual ~TRUSTArray ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
const Nom & que_suis_je () const
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from TRUSTVect< _TYPE_, _SIZE_ >
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
void attach_array (const TRUSTArray &a, _SIZE_ start=0, _SIZE_ size=-1)
bool detach_array ()
void resize_array_ (_SIZE_ n, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _TYPE_>
class TRUSTTrav< _TYPE_ >
Exactly the same as a TRUSTTab with a custom memory pool management allowing re-using previously allocated blocks See implementation in TRUSTTravPool class.
64 bits version is not defined, as those should be only used inside the timestepping algorithm.
Constructor & Destructor Documentation
TRUSTTrav() [1/8]
template<typename _TYPE_ > TRUSTTrav< _TYPE_ >::TRUSTTrav () inline
References TRUSTArray< _TYPE_, _SIZE_ >::set_mem_storage().
Referenced by TRUSTTrav< _TYPE_ >::duplique().
TRUSTTrav() [2/8]
template<typename _TYPE_ > TRUSTTrav< _TYPE_ >::TRUSTTrav (int n) inline
References TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::set_mem_storage().
TRUSTTrav() [3/8]
template<typename _TYPE_ > TRUSTTrav< _TYPE_ >::TRUSTTrav (int n1, int n2) inline
References TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::set_mem_storage().
TRUSTTrav() [4/8]
template<typename _TYPE_ > TRUSTTrav< _TYPE_ >::TRUSTTrav (int n1, int n2, int n3) inline
References TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::set_mem_storage().
TRUSTTrav() [5/8]
template<typename _TYPE_ > TRUSTTrav< _TYPE_ >::TRUSTTrav (int n1, int n2, int n3, int n4) inline
References TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::set_mem_storage().
TRUSTTrav() [6/8]
template<typename _TYPE_ > TRUSTTrav< _TYPE_ >::TRUSTTrav (const TRUSTVect< _TYPE_, int > & tab) inline
References TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::operator=(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::set_line_size_(), TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector(), TRUSTArray< _TYPE_, _SIZE_ >::set_mem_storage(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
TRUSTTrav() [7/8]
template<typename _TYPE_ > TRUSTTrav< _TYPE_ >::TRUSTTrav (const TRUSTTab< _TYPE_, int > & tab) inline
References TRUSTTab< _TYPE_, _SIZE_ >::copy(), TRUSTTab< _TYPE_, _SIZE_ >::operator=(), and TRUSTArray< _TYPE_, _SIZE_ >::set_mem_storage().
TRUSTTrav() [8/8]
template<typename _TYPE_ > TRUSTTrav< _TYPE_ >::TRUSTTrav (const TRUSTTrav< _TYPE_ > & tab) inline
Member Function Documentation
taille_memoire()
template<typename _TYPE_ > unsigned TRUSTTrav< _TYPE_ >::taille_memoire () const inline override protected virtual
Reimplemented from TRUSTTab< _TYPE_, int >.
printOn()
template<typename _TYPE_ > Sortie & TRUSTTrav< _TYPE_ >::printOn (Sortie & os) const inline override protected virtual
ecriture d'un tableau sequentiel (idem que TRUSTVect::printOn() on ne sait pas quoi faire de pertinent pour un tableau distribue).
Reimplemented from TRUSTTab< _TYPE_, int >.
References TRUSTTab< _TYPE_, _SIZE_ >::printOn().
readOn()
template<typename _TYPE_ > Entree & TRUSTTrav< _TYPE_ >::readOn (Entree & is) inline override protected virtual
lecture d'un tableau sequentiel
Reimplemented from TRUSTTab< _TYPE_, int >.
References TRUSTTab< _TYPE_, _SIZE_ >::readOn().
duplique()
template<typename _TYPE_ > int TRUSTTrav< _TYPE_ >::duplique () const inline override protected virtual
Reimplemented from TRUSTTab< _TYPE_, int >.
References Process::exit(), Objet_U::numero(), and TRUSTTrav< _TYPE_ >::TRUSTTrav().
operator=() [1/4]
template<typename _TYPE_ > TRUSTTrav & TRUSTTrav< _TYPE_ >::operator= (const TRUSTTrav< _TYPE_ > & tab) inline
References TRUSTTab< _TYPE_, _SIZE_ >::operator=().
operator=() [2/4]
template<typename _TYPE_ > TRUSTTrav & TRUSTTrav< _TYPE_ >::operator= (const TRUSTTab< _TYPE_, int > & tab) inline
References TRUSTTab< _TYPE_, _SIZE_ >::operator=().
operator=() [3/4]
template<typename _TYPE_ > TRUSTTrav & TRUSTTrav< _TYPE_ >::operator= (const TRUSTVect< _TYPE_, int > & tab) inline
References TRUSTTab< _TYPE_, _SIZE_ >::operator=().
operator=() [4/4]
template<typename _TYPE_ > TRUSTTrav & TRUSTTrav< _TYPE_ >::operator= (_TYPE_ d) inline
References TRUSTTab< _TYPE_, _SIZE_ >::operator=().