CEA TRUST Platform: Op_Dift_VDF_base Class Reference
Op_Dift_VDF_base Class Reference
#include <Op_Dift_VDF_base.h>
Public Member Functions
void contribuer_au_second_membre (DoubleTab &) const override
Public Member Functions inherited from Op_Diff_VDF_base
void completer () override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void dimensionner (Matrice_Morse &) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Constructor & Destructor Documentation
Op_Dift_VDF_base()
Op_Dift_VDF_base::Op_Dift_VDF_base (const Iterateur_VDF_base & iter_base) inline
Member Function Documentation
ajouter_blocs()
void Op_Dift_VDF_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Operateur_base.
References ajoute_terme_pour_axi_turb(), Statistiques::begin_count(), and Statistiques::end_count().
contribuer_au_second_membre()
void Op_Dift_VDF_base::contribuer_au_second_membre (DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Op_Diff_VDF_base.
Reimplemented in Op_Dift_VDF_Face_Axi_base.
References Process::exit().
associer_diffusivite_turbulente_base()
void Op_Dift_VDF_base::associer_diffusivite_turbulente_base (const Champ_Fonc_base & diff_turb) inline
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente().
completer_Op_Dift_VDF_base()
void Op_Dift_VDF_base::completer_Op_Dift_VDF_base () inline
References Op_Diff_VDF_base::completer().
Referenced by Op_Dift_Multiphase_VDF_Elem::completer(), and Op_Dift_Multiphase_VDF_Face::completer().
ajoute_terme_pour_axi_turb()
void Op_Dift_VDF_base::ajoute_terme_pour_axi_turb (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const protected
References Objet_U::bidim_axi, Equation_base::champ_conserve(), Eval_Dift_VDF::diffusivite_turbulente(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), MorEqn::equation(), Probleme_base::equation(), Process::exit(), Domaine_VF::face_voisins(), Eval_Diff_VDF::get_diffusivite(), Equation_base::get_modele(), Nom::getString(), Equation_base::inconnue(), Operateur_Diff_base::is_turb(), Field_base::le_nom(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VDF::orientation(), Champ_Inc_base::passe(), Equation_base::probleme(), Objet_U::que_suis_je(), Eval_Dift_Multiphase_VDF::tab_nu_t(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xv().
Referenced by ajouter_blocs().