CEA TRUST Platform: DomaineCutter_32_64< _SIZE_ > Class Template Reference
DomaineCutter_32_64< _SIZE_ > Class Template Reference
#include <DomaineCutter.h>
Public Member Functions
void construire_sous_domaine (const int part, DomaineCutter_Correspondance_t &correspondance, Domaine32 &sous_domaine, const Static_Int_Lists_t *som_raccord=nullptr) const
void ecrire_domaines (const Nom &basename, const DomainesFileOutputType format, const int reorder, const Static_Int_Lists_t *som_raccord=nullptr)
void initialiser (const Domaine_t &domaine_global, const BigIntVect_t &elem_part, const int nb_parts, const int epaisseur_joint, const Noms &bords_periodiques, const bool permissif=false)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class DomaineCutter_32_64< _SIZE_ >
See also
Partitionneur_base.
Member Typedef Documentation
int_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::ArrOfInt_t = TRUSTArray<_SIZE_, _SIZE_>
BigArrOfInt_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::BigArrOfInt_t = BigArrOfInt_T<_SIZE_>
BigIntVect_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::BigIntVect_t = BigIntVect_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
Static_Int_Lists_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::Static_Int_Lists_t = Static_Int_Lists_32_64<_SIZE_>
Domaine_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Domaine32
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::Domaine32 = Domaine_32_64<int>
Sous_Domaine_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::Sous_Domaine_t = Sous_Domaine_32_64<_SIZE_>
DomaineCutter_Correspondance_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::DomaineCutter_Correspondance_t = DomaineCutter_Correspondance_32_64<_SIZE_>
Frontiere_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::Frontiere_t = Frontiere_32_64<_SIZE_>
Decouper_t
template<typename _SIZE_ > using DomaineCutter_32_64< _SIZE_ >::Decouper_t = Decouper_32_64<_SIZE_>
Member Function Documentation
initialiser()
template<typename _SIZE_ > void DomaineCutter_32_64< _SIZE_ >::initialiser (const Domaine_t & domaine_global, const BigIntVect_t & elem_part, const int nb_parts, const int epaisseur_joint, const Noms & liste_bords_periodiques, const bool permissif = false)
Prepare les structures de donnees pour la construction des sous-domaines en fonction d'un decoupage fourni dans elem_part.
Parameters
(domaine_global) le domaine a decouper (doit avoir un domaine). On prend une ref a ce domaine (il doit donc rester valide).
(elem_part) pour chaque element, numero du sous-domaine auquel il appartient, avec 0 <= elem_part[i] < nb_parts. Attention, on prend une ref a ce tableau, on ne fait pas une copie local. Le tableau doit continuer a exister jusqu'a ce qu'on a fini d'utiliser DomaineCutter.
(nb_parts) nombre total de sous-domaines
(les_faces)
(epaisseur_joint)
References Objet_U::dimension, Process::exit(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_tot(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
reset()
template<typename _SIZE_ > void DomaineCutter_32_64< _SIZE_ >::reset ()
annule toutes les references et vide les tableaux
construire_sous_domaine() [1/2]
template<typename _SIZE_ > void DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine (const int part, DomaineCutter_Correspondance_t & correspondance, Domaine32 & sous_domain, const Static_Int_Lists_t * som_raccord = nullptr) const
Remplit la structure "correspondance" et le "sous_domaine" pour la partie "part".
On cherche les sommets qui appartiennent a la sous-partie, on calcule les tableaux de renumerotation des sommets et des elements entre numero global et numero local (structure correspondance), on remplit les structures de sous_domaine (sommets, elements, frontieres, joints, etc). Attention: sous_domaine doit etre un objet vierge (ne pas contenir de domaine)
References Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::joint(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), DomaineCutter_Correspondance_32_64< _SIZE_ >::liste_inverse_elements_, DomaineCutter_Correspondance_32_64< _SIZE_ >::liste_inverse_sommets_, DomaineCutter_Correspondance_32_64< _SIZE_ >::liste_sommets_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_joints(), Domaine_32_64< _SIZE_ >::nb_som_tot(), DomaineCutter_Correspondance_32_64< _SIZE_ >::partie_, Nom::prefix(), Scatter::trier_les_joints(), and Domaine_32_64< _SIZE_ >::typer().
Referenced by DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine().
construire_sous_domaine() [2/2]
template<typename _SIZE_ > void DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine (const int part, Domaine32 & sous_domaine) const inline
References DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine().
ecrire_domaines()
template<typename _SIZE_ > void DomaineCutter_32_64< _SIZE_ >::ecrire_domaines (const Nom & basename, const DomainesFileOutputType format, const int reorder, const Static_Int_Lists_t * som_raccord = nullptr)
Generation de tous les sous-domaines du calcul et ecriture sur disque des fichiers basename_000n.
Domaines pour 0 <= n < nb_parties_. Si des "sous-domaines" sont definies (dans le champ domaine.ss_domaines()), on genere aussi un fichier par sous-domaine.
WARNING: this method might change elem_part!!! (if 'reorder' option was specified)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), FichierHDF::close(), FichierHDF::create(), FichierHDF::create_and_fill_dataset_SW(), FichierHDF::create_datasets(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_32_64< _SIZE_ >::faces_joint(), FichierHDF::fill_dataset(), Sortie_Brute::get_size(), Process::is_parallel(), Process::je_suis_maitre(), DomaineCutter_Correspondance_32_64< _SIZE_ >::liste_inverse_elements_, Process::me(), Process::mp_max(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_som(), Nom::nom_me(), Process::nproc(), Sortie_Fichier_base::ouvrir(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Sortie::set_bin(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUSTVect< _TYPE_, _SIZE_ >::size_reelle().
bords_internes()
template<typename _SIZE_ > const Noms & DomaineCutter_32_64< _SIZE_ >::bords_internes () const inline