CEA TRUST Platform: Assembleur_P_VDF_Q4 Class Reference
Assembleur_P_VDF_Q4 Class Reference
Additional Inherited Members
Public Member Functions inherited from Assembleur_base
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
int set_resoudre_en_u (int flag)
int set_resoudre_increment_pression (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_domaine_dis_base()
void Assembleur_P_VDF_Q4::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis) override virtual
Implements Assembleur_base.
associer_domaine_cl_dis_base()
void Assembleur_P_VDF_Q4::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis) override virtual
Implements Assembleur_base.
domaine_dis_base()
const Domaine_dis_base & Assembleur_P_VDF_Q4::domaine_dis_base () const override virtual
Implements Assembleur_base.
domaine_Cl_dis_base()
const Domaine_Cl_dis_base & Assembleur_P_VDF_Q4::domaine_Cl_dis_base () const override virtual
Implements Assembleur_base.
assembler()
int Assembleur_P_VDF_Q4::assembler (Matrice & la_matrice) override virtual
Implements Assembleur_base.
References Objet_U::bidim_axi, Matrice_Morse::dimensionner(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), and Matrice_Morse::get_set_tab2().
modifier_secmem() [1/2]
int Assembleur_P_VDF_Q4::modifier_secmem (DoubleTab & secmem) override virtual
Implements Assembleur_base.
modifier_secmem() [2/2]
int Assembleur_P_VDF_Q4::modifier_secmem (const DoubleTab & tab_secmem_, DoubleVect & secmem)
References Objet_U::bidim_axi, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
modifier_solution()
int Assembleur_P_VDF_Q4::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
completer()
void Assembleur_P_VDF_Q4::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
OBS_PTR() [1/3]
Assembleur_P_VDF_Q4::OBS_PTR (Domaine_VDF) protected
OBS_PTR() [2/3]
Assembleur_P_VDF_Q4::OBS_PTR (Domaine_Cl_VDF) protected
OBS_PTR() [3/3]
Assembleur_P_VDF_Q4::OBS_PTR (Equation_base) protected