CEA TRUST Platform: Champ_implementation_Q1 Class Reference
Champ_implementation_Q1 Class Reference abstract
#include <Champ_implementation_Q1.h>
Detailed Description
Decrire ici la classe Champ_implementation_Q1
Constructor & Destructor Documentation
~Champ_implementation_Q1()
Champ_implementation_Q1::~Champ_implementation_Q1 () inline override
Member Function Documentation
value_interpolation()
void Champ_implementation_Q1::value_interpolation (const DoubleTab & positions, const ArrOfInt & cells, const DoubleTab & values, DoubleTab & resu, int ncomp = -1) const override virtual
Implements Champ_implementation_sommet.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Process::exit(), Champ_implementation::get_domaine_geom(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), and Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl().