CEA TRUST Platform: Traitement_particulier_NS_chmoy_faceperio Class Reference
Traitement_particulier_NS_chmoy_faceperio Class Reference abstract
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
pour les calculs de  l'energie cinetique totale
See also
Navier_Stokes_Turbulent, Traitement_particulier_base, Traitement_particulier_VEF
Constructor & Destructor Documentation
~Traitement_particulier_NS_chmoy_faceperio()
Traitement_particulier_NS_chmoy_faceperio::~Traitement_particulier_NS_chmoy_faceperio () inline override
Traitement_particulier_NS_chmoy_faceperio()
Traitement_particulier_NS_chmoy_faceperio::Traitement_particulier_NS_chmoy_faceperio () inline
Member Function Documentation
lire()
Entree & Traitement_particulier_NS_chmoy_faceperio::lire (Entree & is) override virtual
Implements Traitement_particulier_NS_base.
References Process::exit(), oui_stat, Motcles::search(), temps_deb, and temps_fin.
preparer_calcul_particulier()
void Traitement_particulier_NS_chmoy_faceperio::preparer_calcul_particulier () override virtual
Implements Traitement_particulier_NS_base.
References chmoy_faceperio, Objet_U::dimension, Process::exit(), init_calcul_stats(), oui_stat, and temps_deb.
post_traitement_particulier()
void Traitement_particulier_NS_chmoy_faceperio::post_traitement_particulier () override virtual
Implements Traitement_particulier_NS_base.
References calcul_chmoy_faceperio(), temps_deb, and temps_fin.
en_cours_de_resolution()
void Traitement_particulier_NS_chmoy_faceperio::en_cours_de_resolution (int , DoubleTab & , DoubleTab & , double) inline override virtual
Implements Traitement_particulier_NS_base.
sauver_stat()
void Traitement_particulier_NS_chmoy_faceperio::sauver_stat () const inline override virtual
Implements Traitement_particulier_NS_base.
reprendre_stat()
void Traitement_particulier_NS_chmoy_faceperio::reprendre_stat () inline override virtual
Implements Traitement_particulier_NS_base.
init_calcul_stats()
virtual void Traitement_particulier_NS_chmoy_faceperio::init_calcul_stats () protected pure virtual
Implemented in Traitement_particulier_NS_chmoy_faceperio_VEF.
Referenced by preparer_calcul_particulier().
calcul_chmoy_faceperio()
virtual void Traitement_particulier_NS_chmoy_faceperio::calcul_chmoy_faceperio (double , double , double) protected pure virtual
Implemented in Traitement_particulier_NS_chmoy_faceperio_VEF.
Referenced by post_traitement_particulier().
Member Data Documentation
chmoy_faceperio
DoubleTab Traitement_particulier_NS_chmoy_faceperio::chmoy_faceperio protected
Referenced by Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), and preparer_calcul_particulier().
temps_deb
double Traitement_particulier_NS_chmoy_faceperio::temps_deb = -100. protected
Referenced by lire(), post_traitement_particulier(), and preparer_calcul_particulier().
temps_fin
double Traitement_particulier_NS_chmoy_faceperio::temps_fin = -100. protected
Referenced by lire(), and post_traitement_particulier().
oui_stat
int Traitement_particulier_NS_chmoy_faceperio::oui_stat = 0 protected
Referenced by lire(), and preparer_calcul_particulier().
le_fichier
SFichier* Traitement_particulier_NS_chmoy_faceperio::le_fichier protected