CEA TRUST Platform: Pb_Hydraulique_Melange_Binaire_WC Class Reference
Pb_Hydraulique_Melange_Binaire_WC Class Reference
#include <Pb_Hydraulique_Melange_Binaire_WC.h>
Additional Inherited Members
Public Member Functions inherited from Pb_WC_base
void associer_milieu_base (const Milieu_base &) override
Public Member Functions inherited from Pb_Dilatable_base
void associer_sch_tps_base (const Schema_Temps_base &) override
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
virtual void finir ()
double futureTime () const override
void getInputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_U
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual bool run ()
virtual bool runUntil (double time)
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
 - Equations de Navier_Stokes en regime laminaire
 - Equation de conv/diff fraction massique en regime laminaire
See also
Probleme_base Navier_Stokes_WC Convection_Diffusion_Espece_Binaire_WC
Member Function Documentation
verifier()
int Pb_Hydraulique_Melange_Binaire_WC::verifier () override virtual
Teste la compatibilite des equations de la fraction massique et de l'hydraulique.
Reimplemented from Probleme_base.
References eq_frac_mass, eq_hydraulique, and Pb_Dilatable_Proto::verifier_impl().
nombre_d_equations()
int Pb_Hydraulique_Melange_Binaire_WC::nombre_d_equations () const override virtual
Renvoie 2 car il y a 2 equations : Navier_Stokes_WC et Convection_Diffusion_Espece_Binaire_WC.
Implements Probleme_base.
equation() [1/2]
const Equation_base & Pb_Hydraulique_Melange_Binaire_WC::equation (int i) const override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_WC si i=0 Renvoie l'equation de conv/diff fraction massique de type Convection_Diffusion_Espece_Binaire_WC si i=1.
Implements Probleme_base.
References eq_frac_mass, eq_hydraulique, and Pb_Dilatable_Proto::equation_impl().
equation() [2/2]
Equation_base & Pb_Hydraulique_Melange_Binaire_WC::equation (int i) override virtual
Implements Probleme_base.
References eq_frac_mass, eq_hydraulique, and Pb_Dilatable_Proto::equation_impl().
Member Data Documentation
eq_hydraulique
Navier_Stokes_WC Pb_Hydraulique_Melange_Binaire_WC::eq_hydraulique protected
Referenced by equation(), equation(), and verifier().
eq_frac_mass
Convection_Diffusion_Espece_Binaire_WC Pb_Hydraulique_Melange_Binaire_WC::eq_frac_mass protected
Referenced by equation(), equation(), and verifier().