CEA TRUST Platform: Domaine_EF Class Reference
Domaine_EF Class Reference
#include <Domaine_EF.h>
Public Member Functions
void reordonner (Faces &) override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
const Frontiere_dis_base & frontiere_dis (const Nom &) const
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
    Classe instanciable qui derive de Domaine_VF.
    Cette classe contient les informations geometriques que demande
    la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
    La classe porte un certain nombre d'informations concernant les faces
    Dans cet ensemble de faces on fait figurer aussi les faces du bord et
 des joints. Pour manipuler les faces on distingue 2 categories:
      - les faces non standard qui sont sur un joint, un bord ou qui sont
        internes tout en appartenant a un element du bord
      - les faces standard qui sont les faces internes n'appartenant pas
        a un element du bord
 Cette distinction correspond au traitement des conditions aux limites:les
 faces standard ne "voient pas" les conditions aux limites.
 L'ensemble des faces est numerote comme suit:
      - les faces qui sont sur un Domaine_joint apparaissent en premier
           (dans l'ordre du vecteur les_joints)
         - les faces qui sont sur un Domaine_bord apparaissent ensuite
       (dans l'ordre du vecteur les_bords)
         - les faces internes non standard apparaissent ensuite
      - les faces internes standard en dernier
 Finalement on trouve regroupees en premier toutes les faces non standard
 qui vont necessiter un traitement particulier
 On distingue deux types d'elements
      - les elements non standard : ils ont au moins une face de bord
      - les elements standard : ils n'ont pas de face de bord
 Les elements standard (resp. les elements non standard) ne sont pas ranges
 de maniere consecutive dans l'objet Domaine. On utilise le tableau
 rang_elem_non_std pour acceder de maniere selective a l'un ou
 l'autre des types d'elements
Member Function Documentation
typer_elem()
void Domaine_EF::typer_elem (Domaine & domaine_geom) override virtual
Reimplemented from Domaine_VF.
References Process::exit(), and Domaine_32_64< _SIZE_ >::typer().
Referenced by discretiser(), and Domaine_EF_axi::discretiser().
discretiser()
void Domaine_EF::discretiser () override virtual
Reimplemented from Domaine_dis_base.
Reimplemented in Domaine_EF_axi.
References Domaine_VF::creer_tableau_faces(), Domaine_32_64< _SIZE_ >::creer_tableau_sommets(), Objet_U::dimension, Domaine_VF::discretiser(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_normales_, Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), typer_elem(), and verifie_compatibilite_domaine().
Referenced by Domaine_EF_axi::discretiser().
swap()
void Domaine_EF::swap (int fac1, int fac2, int nb_som_faces)
reordonner()
void Domaine_EF::reordonner (Faces & les_faces) override virtual
Methode appelee par Domaine_VF::discretiser apres la creation des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard" au debut de la liste des faces. Les faces non standard sont celles dont les volumes de controles sont modifies par les conditions aux limites.
Reimplemented from Domaine_VF.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_elem_std_, Domaine_32_64< _SIZE_ >::nb_faces_frontiere(), Domaine_VF::rang_elem_non_std_, Domaine_VF::renumeroter(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Faces_32_64< _SIZE_ >::voisin().
modifier_pour_Cl()
void Domaine_EF::modifier_pour_Cl (const Conds_lim & conds_lim) override virtual
Implements Domaine_dis_base.
References calculer_Bij(), calculer_h_carre(), calculer_volumes_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), Periodique::face_associee(), Domaine_VF::face_normales_, Domaine_VF::face_voisins_, Cond_lim_base::frontiere_dis(), Process::Journal(), Domaine_VF::marquer_faces_double_contrib(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::volumes_, Domaine_VF::volumes_entrelaces_, Domaine_VF::xp_, and Domaine_VF::xv_.
type_elem()
const Elem_EF_base & Domaine_EF::type_elem () const inline
Referenced by EF_discretisation::discretiser_champ(), and EF_discretisation::vorticite().
nb_elem_Cl()
int Domaine_EF::nb_elem_Cl () const inline
References Domaine_dis_base::nb_elem(), and Domaine_VF::nb_elem_std_.
nb_faces_joint()
int Domaine_EF::nb_faces_joint () const inline
nb_faces_std()
int Domaine_EF::nb_faces_std () const inline
References Domaine_VF::nb_faces_std_.
nb_elem_std()
int Domaine_EF::nb_elem_std () const inline
References Domaine_VF::nb_elem_std_.
carre_pas_du_maillage()
double Domaine_EF::carre_pas_du_maillage () const inline
Referenced by Op_Diff_EF_base::calculer_dt_stab().
carre_pas_maille()
double Domaine_EF::carre_pas_maille (int i) const inline
Referenced by Op_Dift_EF_base::calculer_borne_locale(), Op_Diff_EF_base::calculer_dt_stab(), and Op_Dift_EF_Q1::calculer_dt_stab().
rang_elem_non_std() [1/2]
IntVect & Domaine_EF::rang_elem_non_std () inline
References Domaine_VF::rang_elem_non_std_.
rang_elem_non_std() [2/2]
const IntVect & Domaine_EF::rang_elem_non_std () const inline
References Domaine_VF::rang_elem_non_std_.
oriente_normale()
int Domaine_EF::oriente_normale (int face_opp, int elem2) const inline
References Domaine_VF::face_voisins().
Referenced by calculer_Bij_gen(), and Domaine_EF_axi::calculer_Bij_gen().
calculer_volumes_entrelaces()
void Domaine_EF::calculer_volumes_entrelaces ()
References Domaine_VF::creer_tableau_faces(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins_, Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_VF::premiere_face_int(), Domaine_VF::volumes_, and Domaine_VF::volumes_entrelaces_.
calculer_volumes_sommets()
void Domaine_EF::calculer_volumes_sommets (const Domaine_Cl_dis_base & zcl)
References calculer_IPhi(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), IPhi_, IPhi_thilde_, Domaine_32_64< _SIZE_ >::les_elems(), Equation_base::milieu(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_dis_base::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Milieu_base::porosite_elem(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_VF::volumes_.
Referenced by modifier_pour_Cl().
calculer_IPhi()
void Domaine_EF::calculer_IPhi (const Domaine_Cl_dis_base & zcl) virtual
Reimplemented in Domaine_EF_axi.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), IPhi_, IPhi_thilde_, Equation_base::milieu(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Milieu_base::porosite_elem(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::volumes().
Referenced by calculer_volumes_sommets().
calculer_Bij()
void Domaine_EF::calculer_Bij (DoubleTab & bij_) virtual
References calculer_Bij_gen(), interface_INITGAUSS::Compute(), Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), Process::exit(), IPhi_, IPhi_thilde_, Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_VF::nb_som_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Domaine_VF::volumes_.
Referenced by modifier_pour_Cl().
calculer_Bij_gen()
void Domaine_EF::calculer_Bij_gen (DoubleTab & bij) virtual
Reimplemented in Domaine_EF_axi.
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces_, Domaine_VF::face_normales(), Domaine_VF::face_sommets_, Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Domaine_VF::nb_som_face(), and oriente_normale().
Referenced by calculer_Bij().
volumes_thilde()
const DoubleVect & Domaine_EF::volumes_thilde () const inline
Referenced by Source_PDF_EF::ajouter_(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), Source_PDF_EF::contribuer_a_avec(), and Champ_Q1_EF::gradient().
volumes_sommets_thilde()
const DoubleVect & Domaine_EF::volumes_sommets_thilde () const inline
Referenced by Solveur_Masse_EF::appliquer_impl(), and Assembleur_P_EF::assembler().
porosite_sommet()
const DoubleVect & Domaine_EF::porosite_sommet () const inline
Referenced by Op_Div_EF::ajouter(), and Op_Grad_EF::ajouter_bord().
set_porosite_sommet()
DoubleVect & Domaine_EF::set_porosite_sommet () inline
calculer_h_carre()
void Domaine_EF::calculer_h_carre ()
References Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_surfaces(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::volumes().
Referenced by modifier_pour_Cl().
calculer_porosites_sommets()
void Domaine_EF::calculer_porosites_sommets ()
References Domaine_dis_base::nb_som(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Bij()
const DoubleTab & Domaine_EF::Bij () const inline
Referenced by Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_EF::ajouter_vectoriel_template(), and Op_Dift_EF_Q1::ajouter_vectoriel_template().
Bij_thilde()
const DoubleTab & Domaine_EF::Bij_thilde () const inline
Referenced by Op_Div_EF::ajouter(), Op_Grad_EF::ajouter(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Assembleur_P_EF::assembler_mat(), and Champ_Q1_EF::gradient().
IPhi()
const DoubleTab & Domaine_EF::IPhi () const inline
References IPhi_.
Referenced by Source_Scalaire_EF::ajouter().
IPhi_thilde()
const DoubleTab & Domaine_EF::IPhi_thilde () const inline
References IPhi_thilde_.
Referenced by Source_Qdm_EF::ajouter(), Op_Conv_EF::ajouter_contribution_sous_cond(), and Op_Conv_EF::ajouter_sous_cond_template().
verifie_compatibilite_domaine()
void Domaine_EF::verifie_compatibilite_domaine () virtual
Reimplemented in Domaine_EF_axi.
References Domaine_dis_base::domaine(), Process::exit(), and Objet_U::que_suis_je().
Referenced by discretiser().
Member Data Documentation
IPhi_
DoubleTab Domaine_EF::IPhi_ protected
Referenced by calculer_Bij(), calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), calculer_volumes_sommets(), and IPhi().
IPhi_thilde_
DoubleTab Domaine_EF::IPhi_thilde_ protected
Referenced by calculer_Bij(), calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), calculer_volumes_sommets(), and IPhi_thilde().