CEA TRUST Platform: Eval_Dift_VDF Class Reference
Eval_Dift_VDF Class Reference
#include <Eval_Dift_VDF.h>
Member Function Documentation
mettre_a_jour()
void Eval_Dift_VDF::mettre_a_jour () inline override virtual
Reimplemented from Eval_Diff_VDF.
Reimplemented in Eval_Dift_VDF_Multi_inco_Elem_Axi, Eval_Dift_VDF_Multi_inco_Elem, and Eval_Dift_VDF_Face.
References Eval_Diff_VDF::mettre_a_jour(), and update_equivalent_distance().
Referenced by Eval_Dift_VDF_Face::mettre_a_jour().
get_equivalent_distance()
double Eval_Dift_VDF::get_equivalent_distance (int boundary_index, int local_face) const inline override virtual
Reimplemented from Eval_Diff_VDF.
References equivalent_distance.
compute_heq_impl()
double Eval_Dift_VDF::compute_heq_impl (double d0, int i, double d1, int j, int compo) const inline
References Eval_Diff_VDF::compute_heq_impl(), is_multi_, and tab_diffusivite_turbulente.
nu_t_impl()
double Eval_Dift_VDF::nu_t_impl (int i, int compo) const inline
References is_multi_, and tab_diffusivite_turbulente.
nu_lam_impl_face()
double Eval_Dift_VDF::nu_lam_impl_face (int i, int j, int k, int l, int compo) const inline
References Eval_Diff_VDF::nu_2_impl_face().
nu_lam_impl_face2()
double Eval_Dift_VDF::nu_lam_impl_face2 (int i, int j, int compo) const inline
References Eval_Diff_VDF::nu_1_impl_face().
nu_1_impl()
double Eval_Dift_VDF::nu_1_impl (int i, int compo) const inline
References is_multi_, Eval_Diff_VDF::nu_1_impl(), and tab_diffusivite_turbulente.
nu_2_impl()
double Eval_Dift_VDF::nu_2_impl (int i, int compo) const inline
References Eval_Diff_VDF::nu_2_impl().
nu_1_impl_face()
double Eval_Dift_VDF::nu_1_impl_face (int i, int j, int compo) const inline
References is_multi_, and tab_diffusivite_turbulente.
nu_2_impl_face()
double Eval_Dift_VDF::nu_2_impl_face (int i, int j, int k, int l, int compo) const inline
References is_multi_, and tab_diffusivite_turbulente.
update_equivalent_distance()
void Eval_Dift_VDF::update_equivalent_distance () inline
References TRUST_Vector< _CLASSE_ >::dimensionner(), and equivalent_distance.
Referenced by mettre_a_jour(), Eval_Dift_VDF_Multi_inco_Elem_Axi::mettre_a_jour(), and Eval_Dift_VDF_Multi_inco_Elem::mettre_a_jour().
diffusivite_turbulente()
const Champ_Fonc_base & Eval_Dift_VDF::diffusivite_turbulente () const inline
Referenced by Op_Dift_VDF_base::ajoute_terme_pour_axi_turb().
associer_diff_turb()
void Eval_Dift_VDF::associer_diff_turb (const Champ_Fonc_base & diff_turb) inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), is_multi_, TRUSTTab< _TYPE_, _SIZE_ >::ref(), tab_diffusivite_turbulente, and Champ_Don_base::valeurs().
associer_loipar()
virtual void Eval_Dift_VDF::associer_loipar (const Turbulence_paroi_scal_base & loi_paroi) inline virtual
Reimplemented in Eval_Dift_Multiphase_VDF, and Eval_Dift_VDF_Elem.
Referenced by Eval_Dift_VDF_Elem::associer_loipar().
init_ind_fluctu_term()
virtual void Eval_Dift_VDF::init_ind_fluctu_term () inline virtual
Reimplemented in Eval_Dift_VDF_Elem.
OBS_PTR() [1/2]
Eval_Dift_VDF::OBS_PTR (Champ_Fonc_base) protected
OBS_PTR() [2/2]
Eval_Dift_VDF::OBS_PTR (Turbulence_paroi_scal_base) protected
Member Data Documentation
is_multi_
int Eval_Dift_VDF::is_multi_ = 0 protected
Referenced by Eval_Dift_Multiphase_VDF::associer_corr(), associer_diff_turb(), compute_heq_impl(), nu_1_impl(), nu_1_impl_face(), nu_2_impl_face(), and nu_t_impl().
equivalent_distance
DoubleVects Eval_Dift_VDF::equivalent_distance protected
Referenced by get_equivalent_distance(), and update_equivalent_distance().
tab_diffusivite_turbulente
DoubleTab Eval_Dift_VDF::tab_diffusivite_turbulente protected
Referenced by associer_diff_turb(), compute_heq_impl(), Eval_Dift_Multiphase_VDF::get_diffusivite_turbulente_multiphase(), nu_1_impl(), nu_1_impl_face(), nu_2_impl_face(), nu_t_impl(), and Eval_Dift_Multiphase_VDF::update_diffusivite_turbulente().