CEA TRUST Platform: Operateur_Conv_base Class Reference
Operateur_Conv_base Class Reference abstract
#include <Operateur_Conv_base.h>
Additional Inherited Members
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
un terme de convection dans une equation.
See also
Operateur_base, Classe abstraite, Methode abstraite, void associer_vitesse(const Champ_Inc_base& vit)
Member Function Documentation
associer_vitesse()
virtual void Operateur_Conv_base::associer_vitesse (const Champ_base & vit) pure virtual
Implemented in Op_Conv_EF_base, Op_Conv_negligeable, Op_Conv_Amont_PolyMAC_Elem, Op_Conv_Centre_PolyMAC_Elem, Op_Conv_PolyMAC_base, Op_Conv_DI_L2_VEF_Face, Op_Conv_VEF_base, Op_Conv_Amont_VDF_Elem, Op_Conv_Centre_VDF_Elem, Op_Conv_Centre4_VDF_Elem, Op_Conv_Quick_VDF_Elem, Op_Conv_Amont_VDF_Face, Op_Conv_Centre_VDF_Face, Op_Conv_Centre4_VDF_Face, Op_Conv_Quick_VDF_Face_Axi, Op_Conv_Quick_VDF_Face, and Op_Conv_ALE.
dt_stab_conv()
double Operateur_Conv_base::dt_stab_conv () const inline
References dt_stab_conv_.
Referenced by Modele_turbulence_hyd_base::limiter_viscosite_turbulente().
fixer_dt_stab_conv()
void Operateur_Conv_base::fixer_dt_stab_conv (double dt) inline
References dt_stab_conv_.
Referenced by Op_Conv_EF::calculer_dt_stab(), Op_Conv_EF_base::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), and Op_Conv_VEF_base::calculer_dt_stab().
associer_norme_vitesse()
void Operateur_Conv_base::associer_norme_vitesse (const Champ_base & norme_vitesse) virtual
References Process::je_suis_maitre(), Field_base::le_nom(), and Field_base::unite().
associer_vitesse_pour_pas_de_temps()
void Operateur_Conv_base::associer_vitesse_pour_pas_de_temps (const Champ_base & vitesse) virtual
set_incompressible()
void Operateur_Conv_base::set_incompressible (const int flag) virtual
Reimplemented in Op_Conv_EF_Stab_PolyMAC_Face, Op_Conv_VDF_base, and Op_Conv_negligeable.
References Process::exit(), incompressible_, and Objet_U::que_suis_je().
associer_champ_temp()
virtual void Operateur_Conv_base::associer_champ_temp (const Champ_Inc_base & , bool) const inline virtual
Reimplemented in Op_Conv_VDF_base.
OBS_PTR() [1/2]
Operateur_Conv_base::OBS_PTR (Champ_base) protected
OBS_PTR() [2/2]
Operateur_Conv_base::OBS_PTR (Champ_base) protected
Member Data Documentation
dt_stab_conv_
double Operateur_Conv_base::dt_stab_conv_ protected
Referenced by dt_stab_conv(), and fixer_dt_stab_conv().
incompressible_
int Operateur_Conv_base::incompressible_ = 1 protected
Referenced by Op_Conv_EF_Stab_PolyMAC_Face::ajouter(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_Face::contribuer_a_avec(), Op_Conv_EF_Stab_PolyMAC_Face::set_incompressible(), Op_Conv_VDF_base::set_incompressible(), and set_incompressible().