CEA TRUST Platform: Simd_template< _TYPE_ > Class Template Reference
Simd_template< _TYPE_ > Class Template Reference
Detailed Description
template<typename _TYPE_>
class Simd_template< _TYPE_ >
Functionalities provided by the class are :
load vector size aligned data from memory (SimdGet)
getting x[i-1] and x[i+1] for finite difference algorithms (SimdGetAtLeft, SimdGetAtRight, etc)
arithmetic operations (+ - * /)
conditional affectation (SimdSelect)
Member Typedef Documentation
value_type
template<typename _TYPE_ > using Simd_template< _TYPE_ >::value_type = _TYPE_
Constructor & Destructor Documentation
Simd_template() [1/2]
template<typename _TYPE_ > Simd_template< _TYPE_ >::Simd_template () inline
References Simd_template< _TYPE_ >::data_.
Simd_template() [2/2]
template<typename _TYPE_ > Simd_template< _TYPE_ >::Simd_template (_TYPE_ x) inline
Member Function Documentation
size()
template<typename _TYPE_ > static int Simd_template< _TYPE_ >::size () inline static
Referenced by Simd_template< _TYPE_ >::operator[](), and Simd_template< _TYPE_ >::sumReduction().
operator+=()
template<typename _TYPE_ > void Simd_template< _TYPE_ >::operator+= (Simd_template< _TYPE_ > a) inline
References Simd_template< _TYPE_ >::data_.
operator*=()
template<typename _TYPE_ > void Simd_template< _TYPE_ >::operator*= (Simd_template< _TYPE_ > a) inline
References Simd_template< _TYPE_ >::data_.
operator-=()
template<typename _TYPE_ > void Simd_template< _TYPE_ >::operator-= (Simd_template< _TYPE_ > a) inline
References Simd_template< _TYPE_ >::data_.
operator[]() [1/2]
template<typename _TYPE_ > _TYPE_& Simd_template< _TYPE_ >::operator[] (int idx) inline
References Simd_template< _TYPE_ >::data_, and Simd_template< _TYPE_ >::size().
operator[]() [2/2]
template<typename _TYPE_ > _TYPE_ Simd_template< _TYPE_ >::operator[] (int idx) const inline
References Simd_template< _TYPE_ >::data_, and Simd_template< _TYPE_ >::size().
sumReduction()
template<typename _TYPE_ > _TYPE_ Simd_template< _TYPE_ >::sumReduction () inline
References Simd_template< _TYPE_ >::data_, and Simd_template< _TYPE_ >::size().
Member Data Documentation
data_
template<typename _TYPE_ > _TYPE_ Simd_template< _TYPE_ >::data_
Referenced by Simd_template< _TYPE_ >::operator*=(), Simd_template< _TYPE_ >::operator+=(), Simd_template< _TYPE_ >::operator-=(), Simd_template< _TYPE_ >::operator[](), Simd_template< _TYPE_ >::Simd_template(), and Simd_template< _TYPE_ >::sumReduction().