CEA TRUST Platform: Op_Diff_RotRot Class Reference
Op_Diff_RotRot Class Reference
Additional Inherited Members
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
associer()
void Op_Diff_RotRot::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const Champ_Inc_base & inco) override virtual
Implements Operateur_base.
References assembler_matrice(), Op_Curl_VEFP1B::associer(), Op_Rot_VEFP1B::associer(), Champ_Inc_base::associer_domaine_dis_base(), curl_, Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_P1_isoP1Bulle::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), matrice_vorticite_, Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_som(), Field_base::nommer(), OWN_PTR(), rot_, Operateur_base::solveur, solveur_, and tester().
associer_diffusivite()
void Op_Diff_RotRot::associer_diffusivite (const Champ_base & diffu) override virtual
Implements Operateur_Diff_base.
diffusivite()
const Champ_base & Op_Diff_RotRot::diffusivite () const override virtual
Implements Operateur_Diff_base.
calculer()
DoubleTab & Op_Diff_RotRot::calculer (const DoubleTab & vitesse, DoubleTab & diffusion) const override virtual
Reimplemented from Operateur_base.
ajouter()
DoubleTab & Op_Diff_RotRot::ajouter (const DoubleTab & vitesse, DoubleTab & diffusion) const override virtual
Reimplemented from Operateur_base.
References Op_Curl_VEFP1B::calculer(), Op_Rot_VEFP1B::calculer(), calculer_vorticite(), curl_, matrice_vorticite_, and rot_.
tester()
int Op_Diff_RotRot::tester () const
References Matrice_Morse_Sym::imprimer_formatte(), matrice_vorticite_, Matrice_Morse::ordre(), Solv_GCP::resoudre_systeme(), solv_iteratif::set_seuil(), and solveur_.
Referenced by associer().
calculer_vorticite()
int Op_Diff_RotRot::calculer_vorticite (DoubleTab & solution, const DoubleTab & curl) const
References curl_, Domaine_dis_base::domaine(), domaine_vef(), Op_Curl_VEFP1B::elem_som_size(), Op_Curl_VEFP1B::elements_pour_sommet(), Process::is_sequential(), matrice_vorticite_, Matrice_Morse::ordre(), Solv_GCP::resoudre_systeme(), solv_iteratif::set_seuil(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and solveur_.
Referenced by ajouter().
assembler_matrice()
int Op_Diff_RotRot::assembler_matrice (Matrice & matrice)
References Entree_Fichier_base::close(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), elements_pour_sommet(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), LecFicDistribue::ouvrir(), remplir_elem_elem_EF(), remplir_elem_som_EF(), remplir_som_elem_EF(), remplir_som_som_EF(), TRUSTList< _TYPE_ >::size(), sommets_pour_element(), sommets_voisins(), and Tri().
Referenced by associer().
sommets_pour_element()
IntList Op_Diff_RotRot::sommets_pour_element (int numero_elem) const
References TRUSTList< _TYPE_ >::add_if_not(), Domaine_dis_base::domaine(), domaine_vef(), TRUSTListElem< _TYPE_ >::est_vide(), and TRUSTList< _TYPE_ >::vide().
Referenced by assembler_matrice(), and remplir_som_som_EF().
elements_pour_sommet()
IntList Op_Diff_RotRot::elements_pour_sommet (int numero_som) const
References TRUSTList< _TYPE_ >::add_if_not(), Domaine_dis_base::domaine(), domaine_vef(), TRUSTListElem< _TYPE_ >::est_vide(), and TRUSTList< _TYPE_ >::vide().
Referenced by assembler_matrice().
sommets_voisins()
IntList Op_Diff_RotRot::sommets_voisins (int numero_som, const IntList & liste) const
References TRUSTList< _TYPE_ >::add_if_not(), Domaine_dis_base::domaine(), domaine_vef(), and TRUSTList< _TYPE_ >::size().
Referenced by assembler_matrice().
remplir_elem_elem_EF()
double Op_Diff_RotRot::remplir_elem_elem_EF (const int numero_elem) const
References domaine_vef(), and Domaine_VF::volumes().
Referenced by assembler_matrice().
remplir_elem_som_EF()
double Op_Diff_RotRot::remplir_elem_som_EF (const int numero_elem, const int numero_som) const
References Objet_U::dimension, and domaine_vef().
Referenced by assembler_matrice().
remplir_som_elem_EF()
double Op_Diff_RotRot::remplir_som_elem_EF (const int numero_elem, const int numero_som) const
References Objet_U::dimension, and domaine_vef().
Referenced by assembler_matrice().
remplir_som_som_EF()
double Op_Diff_RotRot::remplir_som_som_EF (const int numero_som, const int sommet_voisin, const IntList & elem_voisins) const
References TRUSTList< _TYPE_ >::contient(), Objet_U::dimension, domaine_vef(), Process::exit(), TRUSTList< _TYPE_ >::size(), sommets_pour_element(), and Domaine_VF::volumes().
Referenced by assembler_matrice().
Tri()
void Op_Diff_RotRot::Tri (IntList & liste_a_trier) const
References TRUSTList< _TYPE_ >::add_if_not(), TRUSTListElem< _TYPE_ >::est_vide(), Process::exit(), TRUSTList< _TYPE_ >::size(), and TRUSTList< _TYPE_ >::suppr().
Referenced by assembler_matrice().
vecteur_normal()
DoubleTab Op_Diff_RotRot::vecteur_normal (const int face, const int elem) const
References Objet_U::dimension, Domaine_VF::face_normales(), and Domaine_VEF::oriente_normale().
domaine_vef()
const Domaine_VEF & Op_Diff_RotRot::domaine_vef () const
Referenced by assembler_matrice(), calculer_vorticite(), elements_pour_sommet(), remplir_elem_elem_EF(), remplir_elem_som_EF(), remplir_som_elem_EF(), remplir_som_som_EF(), sommets_pour_element(), and sommets_voisins().
OWN_PTR()
Op_Diff_RotRot::OWN_PTR (Champ_Inc_base) mutable protected
Referenced by associer().
OBS_PTR() [1/3]
Op_Diff_RotRot::OBS_PTR (Domaine_VEF) protected
OBS_PTR() [2/3]
Op_Diff_RotRot::OBS_PTR (Domaine_Cl_VEF) protected
OBS_PTR() [3/3]
Op_Diff_RotRot::OBS_PTR (Champ_Uniforme) protected
Member Data Documentation
matrice_vorticite_
Matrice Op_Diff_RotRot::matrice_vorticite_ protected
Referenced by ajouter(), associer(), calculer_vorticite(), and tester().
rot_
Op_Rot_VEFP1B Op_Diff_RotRot::rot_ protected
Referenced by ajouter(), and associer().
curl_
Op_Curl_VEFP1B Op_Diff_RotRot::curl_ protected
Referenced by ajouter(), associer(), and calculer_vorticite().
solveur_
SolveurSys Op_Diff_RotRot::solveur_ protected
Referenced by associer(), calculer_vorticite(), and tester().