CEA TRUST Platform: Champ_front_var Class Reference
Champ_front_var Class Reference
Public Member Functions
int initialiser (double temps, const Champ_Inc_base &inco) override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual int avancer (double temps)
virtual void calculer_coeffs_echange (double temps)
virtual void fixer_nb_valeurs_temporelles (int nb_cases)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
virtual void mettre_a_jour (double temps)
virtual int reculer (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
virtual void valeurs_face (int, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
une frontiere variable en espace (non uniforme).
Le DoubleTab est dimensionne au nombre de faces de la frontiere
par la methode initialiser et possede un espace virtuel.
Chaque modification du tableau de valeurs doit donc etre suivie
d'un appel a echange_espace_virtuel().
Les Champ_front_var sont classes suivant qu'ils sont
stationnaires (Champ_front_var_stationnaire) ou non
(Champ_front_var_instationnaire).
Dans le premier cas, le tableau de valeurs est rempli une fois
pour toutes par la methode initialiser. Dans le deuxieme, il
est aussi recalcule a chaque appel a mettre_a_jour.
See also
Champ_front_base Champ_Var
Member Function Documentation
initialiser()
int Champ_front_var::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Dimensionne le tableau de valeurs et cree son espace virtuel. Les classes derivees doivent imperativement appeler cette methode.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Champ_front_base.
Reimplemented in Champ_front_tangentiel_VEF, Champ_front_contact_VEF, Champ_front_synt, Champ_front_pression_from_u, Champ_front_softanalytique, Champ_front_recyclage, and Champ_front_var_instationnaire.
References Frontiere_32_64< _SIZE_ >::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Frontiere_dis_base::frontiere(), Champ_front_base::frontiere_dis(), Champ_front_base::les_valeurs, Roue::nb_cases(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_lu::initialiser(), Champ_front_var_instationnaire::initialiser(), and Champ_front_softanalytique::initialiser().