CEA TRUST Platform: Champ_val_tot_sur_vol_VEF Class Reference
Champ_val_tot_sur_vol_VEF Class Reference
#include <Champ_val_tot_sur_vol_VEF.h>
Additional Inherited Members
Public Member Functions inherited from TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >
int initialiser (const double temps) override
void mettre_a_jour (double temps) override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
int imprime (Sortie &, int) const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
sommation de vol_entrelaces*poro_surface pour les faces contenues dans la localisation loc
Member Function Documentation
eval_contrib_loc()
DoubleVect & Champ_val_tot_sur_vol_VEF::eval_contrib_loc (const Domaine_dis_base & zdis, const Domaine_Cl_dis_base & zcldis, DoubleVect & vol) override virtual
Implements Champ_val_tot_sur_vol_base.
References Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::face_voisins(), Domaine_VF::faces_doubles(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Process::mp_sum(), Domaine_dis_base::nb_elem(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Milieu_base::porosite_face(), Domaine_VEF::premiere_face_std(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Domaine_VF::volumes_entrelaces(), and Domaine_Cl_VEF::volumes_entrelaces_Cl().