CEA TRUST Platform: Op_Conv_EF Class Reference
Op_Conv_EF Class Reference
#include <Op_Conv_EF.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
void contribuer_au_second_membre (DoubleTab &resu) const override
void dimensionner (Matrice_Morse &matrice) const override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Conv_EF_base
double calculer_dt_stab () const override
void completer () override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Op_EF_base
void dimensionner (const Domaine_EF &, const Domaine_Cl_EF &, Matrice_Morse &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
transport d'un scalaire. La discretisation est EF Le champ convecte est scalaire ou vecteur de type Champ_P1NC Le schema de convection est du type Decentre ou Centre
Member Enumeration Documentation
type_operateur
enum Op_Conv_EF::type_operateur protected
Enumerator
amont
muscl
centre
Member Function Documentation
ajouter()
DoubleTab & Op_Conv_EF::ajouter (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References ajouter_sous_cond(), btd_hors_conv_, and hourglass_hors_conv_.
ajouter_a_la_diffusion()
DoubleTab & Op_Conv_EF::ajouter_a_la_diffusion (const DoubleTab & transporte, DoubleTab & resu) const
References ajouter_sous_cond(), btd_hors_conv_, and hourglass_hors_conv_.
calculer_dt_stab()
double Op_Conv_EF::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References btd_, calcul_dt_stab_, Operateur_base::calculer_dt_stab(), coefficient_correcteur_supg_, Objet_U::dimension, Champ_Don_base::dimensionner(), Domaine_dis_base::domaine(), Op_EF_base::elem_contribue(), MorEqn::equation(), Process::exit(), Operateur_Conv_base::fixer_dt_stab_conv(), Probleme_base::get_champ(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), max_ue_, min_dx_, Process::mp_max(), Process::mp_min(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Equation_base::probleme(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
dimensionner()
void Op_Conv_EF::dimensionner (Matrice_Morse & mat) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_EF_base::dimensionner().
modifier_pour_Cl()
void Op_Conv_EF::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_EF_base::modifier_pour_Cl().
contribuer_a_avec()
void Op_Conv_EF::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Conv_EF::contribuer_au_second_membre (DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References contribue_au_second_membre().
contribue_au_second_membre()
void Op_Conv_EF::contribue_au_second_membre (DoubleTab & resu) const
References ajouter_sous_cond(), btd_hors_conv_, btd_impl_, centre_impl_, MorEqn::equation(), hourglass_hors_conv_, and hourglass_impl_.
Referenced by contribuer_au_second_membre().
ajouter_contribution_sous_cond()
void Op_Conv_EF::ajouter_contribution_sous_cond (const DoubleTab & transporte, Matrice_Morse & matrice, int btd_impl, int hourglass_impl, int centre_impl) const
References amont, Domaine_EF::Bij(), Matrice_Morse::coef(), coefficient_btd(), Objet_U::dimension, Domaine_dis_base::domaine(), Op_EF_base::elem_contribue(), MorEqn::equation(), Probleme_base::get_champ(), hourglass, Domaine_EF::IPhi_thilde(), Domaine_32_64< _SIZE_ >::les_elems(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Equation_base::probleme(), TRUSTVect< _TYPE_, _SIZE_ >::size(), type_op, Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Domaine_VF::volumes(), and Domaine_EF::volumes_thilde().
Referenced by ajouter_contribution(), and ajouter_contribution_a_la_diffusion().
ajouter_contribution()
void Op_Conv_EF::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
References ajouter_contribution_sous_cond(), btd_hors_conv_, btd_impl_, centre_impl_, hourglass_hors_conv_, and hourglass_impl_.
Referenced by contribuer_a_avec().
ajouter_contribution_a_la_diffusion()
void Op_Conv_EF::ajouter_contribution_a_la_diffusion (const DoubleTab & transporte, Matrice_Morse & matrice) const
References ajouter_contribution_sous_cond(), btd_hors_conv_, btd_impl_, hourglass_hors_conv_, and hourglass_impl_.
contribue_au_second_membre_a_la_diffusion()
void Op_Conv_EF::contribue_au_second_membre_a_la_diffusion (DoubleTab & resu) const
References ajouter_sous_cond(), btd_hors_conv_, btd_impl_, MorEqn::equation(), hourglass_hors_conv_, and hourglass_impl_.
ajouter_sous_cond()
DoubleTab & Op_Conv_EF::ajouter_sous_cond (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const
References ajouter_sous_cond_dim3_nbn8_nbdim1(), ajouter_sous_cond_dim3_nbn8_nbdim2(), ajouter_sous_cond_gen(), Objet_U::dimension, Domaine_dis_base::domaine(), MorEqn::equation(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Domaine_32_64< _SIZE_ >::nb_som_elem().
Referenced by ajouter(), ajouter_a_la_diffusion(), contribue_au_second_membre(), and contribue_au_second_membre_a_la_diffusion().
coefficient_btd()
double Op_Conv_EF::coefficient_btd () const virtual
Reimplemented in Op_Conv_SUPG_EF.
References Objet_U::dimension, MorEqn::equation(), f_lu_, Schema_Temps_base::pas_de_temps(), and Equation_base::schema_temps().
Referenced by ajouter_contribution_sous_cond(), and ajouter_sous_cond_template().
completer()
void Op_Conv_EF::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References btd_hors_conv_, calcul_dt_stab_, Op_Conv_EF_base::completer(), MorEqn::equation(), and hourglass_hors_conv_.
get_btd()
double Op_Conv_EF::get_btd () const inline
References btd_.
get_champ()
const Champ_base & Op_Conv_EF::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References coefficient_correcteur_supg_, and Champs_compris_interface::get_champ().
has_champ() [1/2]
bool Op_Conv_EF::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
References coefficient_correcteur_supg_, and Champs_compris_interface::has_champ().
has_champ() [2/2]
bool Op_Conv_EF::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_interface::has_champ().
ajouter_sous_cond_gen()
DoubleTab & Op_Conv_EF::ajouter_sous_cond_gen (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const protected
Referenced by ajouter_sous_cond().
ajouter_sous_cond_dim3_nbn8_nbdim1()
DoubleTab & Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim1 (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const protected
Referenced by ajouter_sous_cond().
ajouter_sous_cond_dim3_nbn8_nbdim2()
DoubleTab & Op_Conv_EF::ajouter_sous_cond_dim3_nbn8_nbdim2 (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const protected
Referenced by ajouter_sous_cond().
ajouter_sous_cond_dim2_nbn4_nbdim1()
DoubleTab & Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim1 (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const protected
ajouter_sous_cond_dim2_nbn4_nbdim2()
DoubleTab & Op_Conv_EF::ajouter_sous_cond_dim2_nbn4_nbdim2 (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const protected
ajouter_sous_cond_template()
template<AJOUTE_COND _COND_> DoubleTab & Op_Conv_EF::ajouter_sous_cond_template (const DoubleTab & transporte, DoubleTab & resu, int btd_impl, int hourglass_impl, int centre_impl) const protected
References Process::abort(), TRUSTArray< _TYPE_, _SIZE_ >::addr(), amont, Domaine_EF::Bij(), coefficient_btd(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Op_EF_base::elem_contribue(), MorEqn::equation(), Op_Conv_EF_base::fluent_, Probleme_base::get_champ(), hourglass, Domaine_EF::IPhi_thilde(), Domaine_32_64< _SIZE_ >::les_elems(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Equation_base::probleme(), TRUSTVect< _TYPE_, _SIZE_ >::size(), type_op, Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Debog::verifier(), Domaine_VF::volumes(), and Domaine_EF::volumes_thilde().
Member Data Documentation
hourglass
double Op_Conv_EF::hourglass protected
Referenced by ajouter_contribution_sous_cond(), and ajouter_sous_cond_template().
hourglass_impl_
int Op_Conv_EF::hourglass_impl_ protected
Referenced by ajouter_contribution(), ajouter_contribution_a_la_diffusion(), contribue_au_second_membre(), and contribue_au_second_membre_a_la_diffusion().
btd_impl_
int Op_Conv_EF::btd_impl_ protected
Referenced by ajouter_contribution(), ajouter_contribution_a_la_diffusion(), contribue_au_second_membre(), and contribue_au_second_membre_a_la_diffusion().
centre_impl_
int Op_Conv_EF::centre_impl_ protected
Referenced by ajouter_contribution(), and contribue_au_second_membre().
hourglass_hors_conv_
int Op_Conv_EF::hourglass_hors_conv_ protected
Referenced by ajouter(), ajouter_a_la_diffusion(), ajouter_contribution(), ajouter_contribution_a_la_diffusion(), completer(), contribue_au_second_membre(), and contribue_au_second_membre_a_la_diffusion().
btd_hors_conv_
int Op_Conv_EF::btd_hors_conv_ protected
Referenced by ajouter(), ajouter_a_la_diffusion(), ajouter_contribution(), ajouter_contribution_a_la_diffusion(), completer(), contribue_au_second_membre(), and contribue_au_second_membre_a_la_diffusion().
f_lu_
double Op_Conv_EF::f_lu_ protected
Referenced by coefficient_btd().
calcul_dt_stab_
int Op_Conv_EF::calcul_dt_stab_ protected
Referenced by calculer_dt_stab(), and completer().
type_op
type_operateur Op_Conv_EF::type_op =amont protected
Referenced by ajouter_contribution_sous_cond(), and ajouter_sous_cond_template().
max_ue_
double Op_Conv_EF::max_ue_ =1e-8 mutable protected
Referenced by calculer_dt_stab(), and Op_Conv_SUPG_EF::coefficient_btd().
min_dx_
double Op_Conv_EF::min_dx_ =1e37 protected
Referenced by calculer_dt_stab(), and Op_Conv_SUPG_EF::coefficient_btd().
coefficient_correcteur_supg_
Champ_Uniforme Op_Conv_EF::coefficient_correcteur_supg_ mutable protected
Referenced by calculer_dt_stab(), get_champ(), and has_champ().
btd_
double Op_Conv_EF::btd_ =-1. protected
Referenced by calculer_dt_stab(), and get_btd().