CEA TRUST Platform: Eval_Quick_VDF_Face_Axi Class Reference
Eval_Quick_VDF_Face_Axi Class Reference
Detailed Description
Schema de convection Quick
Member Function Documentation
face_amont_princ()
int Eval_Quick_VDF_Face_Axi::face_amont_princ (int num_face, int i) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
face_amont_conj()
int Eval_Quick_VDF_Face_Axi::face_amont_conj (int num_face, int k, int i) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References Evaluateur_VDF::dimension, and Eval_Conv_VDF_tools::face_amont_conj_axi_impl().
dist_face()
double Eval_Quick_VDF_Face_Axi::dist_face (int n1, int n2, int k) const inline
References Eval_Conv_VDF_tools::dist_face_axi_impl().
Referenced by dim_elem(), and dist_elem_period().
dist_elem_period()
double Eval_Quick_VDF_Face_Axi::dist_elem_period (int n1, int n2, int k) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References dist_face().
dim_face()
double Eval_Quick_VDF_Face_Axi::dim_face (int n1, int k) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References dim_elem().
dist_elem()
double Eval_Quick_VDF_Face_Axi::dist_elem (int n1, int n2, int k) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References Eval_Conv_VDF_tools::dist_elem_axi_impl().
dim_elem()
double Eval_Quick_VDF_Face_Axi::dim_elem (int n1, int k) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References Evaluateur_VDF::dimension, and dist_face().
Referenced by dim_face().
conv_quick_sharp_plus()
double Eval_Quick_VDF_Face_Axi::conv_quick_sharp_plus (const double psc, const double vit_0, const double vit_1, const double vit_0_0, const double dx, const double dm, const double dxam) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References Eval_Conv_VDF_tools::conv_quick_sharp_plus_impl().
conv_quick_sharp_moins()
double Eval_Quick_VDF_Face_Axi::conv_quick_sharp_moins (const double psc, const double vit_0, const double vit_1, const double vit_1_1, const double dx, const double dm, const double dxam) const inline override virtual
Reimplemented from Eval_Conv_VDF_tools.
References Eval_Conv_VDF_tools::conv_quick_sharp_moins_impl().
Member Data Documentation
IS_AXI
constexpr bool Eval_Quick_VDF_Face_Axi::IS_AXI = true static constexpr
IS_QUICK
constexpr bool Eval_Quick_VDF_Face_Axi::IS_QUICK = true static
CALC_ARR_PERIO
constexpr bool Eval_Quick_VDF_Face_Axi::CALC_ARR_PERIO = false static
CALC_ARR_NAVIER_FL
constexpr bool Eval_Quick_VDF_Face_Axi::CALC_ARR_NAVIER_FL = false static