CEA TRUST Platform: Champ_Uniforme_inst Class Reference
Champ_Uniforme_inst Class Reference abstract
#include <Champ_Uniforme_inst.h>
Public Member Functions
void mettre_a_jour (double) override
Public Member Functions inherited from TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >
DoubleVect & valeur_a (const DoubleVect &, DoubleVect &tab_valeurs) const override
double valeur_a_compo (const DoubleVect &x, int ncomp) const override
DoubleVect & valeur_a_elem (const DoubleVect &positions, DoubleVect &tab_valeurs, int) const override
double valeur_a_elem_compo (const DoubleVect &, int, int ncomp) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &, DoubleVect &tab_valeurs, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &, DoubleVect &tab_valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe est abstraite, une classe concrete derivant de
Champ_Uniforme_inst devra surcharger la methode me_calculer(double t)
de calcul du champ en fonction du temps.
See also
Champ_Uniforme, Classe abstraite, Methode abstraite, void me_calculer(double t)
Member Function Documentation
mettre_a_jour()
void Champ_Uniforme_inst::mettre_a_jour (double un_temps) inline override virtual
Mise a jour en temps du champ.
Parameters
(double temps) temps de mise a jour
Reimplemented from Champ_Don_base.
References Champ_base::changer_temps(), and me_calculer().
me_calculer()
virtual void Champ_Uniforme_inst::me_calculer (double t) pure virtual
Implemented in Champ_Fonc_t, and Champ_Tabule_Temps.
Referenced by mettre_a_jour().