CEA TRUST Platform: Source_WC_Chaleur_VDF Class Reference
Source_WC_Chaleur_VDF Class Reference
Additional Inherited Members
Public Member Functions inherited from Source_Chaleur_Fluide_Dilatable_base
void completer () override
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int initialiser (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Source_WC_Chaleur
DoubleTab & ajouter_ (DoubleTab &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe represente un terme source supplementaire a prendre en compte dans les equations de la chaleur dans le cas ou le fluide est weakly compressible et pour une discretisation VDF
See also
Source_base Fluide_Weakly_Compressible Source_WC_Chaleur
Member Function Documentation
associer_domaines()
void Source_WC_Chaleur_VDF::associer_domaines (const Domaine_dis_base & domaine, const Domaine_Cl_dis_base & zcl) override protected virtual
Implements Source_Chaleur_Fluide_Dilatable_base.
References Source_Fluide_Dilatable_VDF_Proto::associer_domaines_impl(), Source_Fluide_Dilatable_VDF_Proto::associer_volume_porosite_impl(), Source_Chaleur_Fluide_Dilatable_base::porosites, and Source_Chaleur_Fluide_Dilatable_base::volumes.
compute_interpolate_gradP()
void Source_WC_Chaleur_VDF::compute_interpolate_gradP (DoubleTab & gradP, const DoubleTab & Ptot) const override protected virtual
Implements Source_WC_Chaleur.
References Operateur_Grad::calculer(), Source_WC_Chaleur::correct_grad_boundary(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Probleme_base::equation(), Navier_Stokes_std::grad_P(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Convection_Diffusion_Chaleur_WC::operateur_gradient_WC(), Equation_base::probleme(), Objet_U::que_suis_je(), Champ_Inc_base::valeurs(), and Navier_Stokes_std::vitesse().