CEA TRUST Platform: Convection_Diffusion_Chaleur_Fluide_Dilatable_base Class Reference
Convection_Diffusion_Chaleur_Fluide_Dilatable_base Class Reference abstract
#include <Convection_Diffusion_Chaleur_Fluide_Dilatable_base.h>
Public Member Functions
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Motcle & domaine_application () const override
int preparer_calcul () override
int remplir_cl_modifiee ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_base
int impr (Sortie &os) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Detailed Description
quand le scalaire subissant le transport est la temperature en gaz parfaits,
ou l'enthalpie en gaz reels.
(generalisation de Convection_Diffusion_Temperature pour les gaz reels)
See also
Conv_Diffusion_std Convection_Diffusion_Chaleur_Fluide_Dilatable_base
Member Function Documentation
discretiser()
void Convection_Diffusion_Chaleur_Fluide_Dilatable_base::discretiser () override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), Equation_base::domaine_dis(), Equation_base::schema_temps(), and Discret_Thermique::temperature().
preparer_calcul()
int Convection_Diffusion_Chaleur_Fluide_Dilatable_base::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Chaleur_QC, Convection_Diffusion_Chaleur_WC, and Convection_Diffusion_Chaleur_Turbulent_QC.
References Equation_base::preparer_calcul().
Referenced by Convection_Diffusion_Chaleur_QC::preparer_calcul(), and Convection_Diffusion_Chaleur_WC::preparer_calcul().
remplir_cl_modifiee()
int Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee ()
remplissage du domaine cl modifiee avec 1 partout au bord.
..
References Equation_base::domaine_Cl_dis().
Referenced by Convection_Diffusion_Chaleur_QC::preparer_calcul(), and Convection_Diffusion_Chaleur_WC::preparer_calcul().
diffusivite_pour_pas_de_temps()
const Champ_base & Convection_Diffusion_Chaleur_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps () const override virtual
Reimplemented from Convection_Diffusion_std.
References Milieu_base::diffusivite(), and Convection_Diffusion_Fluide_Dilatable_base::milieu().
Referenced by Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard().
assembler()
void Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & resu) override virtual
Reimplemented from Equation_base.
References Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl().
assembler_blocs_avec_inertie()
void Convection_Diffusion_Chaleur_Fluide_Dilatable_base::assembler_blocs_avec_inertie (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) override virtual
Reimplemented from Equation_base.
References Schema_Temps_base::ajouter_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Statistiques::begin_count(), Equation_base::discretisation(), Statistiques::end_count(), Nom::getString(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), Field_base::le_nom(), Equation_base::modifier_pour_Cl(), and Equation_base::schema_temps().
data_a_sauvegarder()
std::vector< YAML_data > Convection_Diffusion_Chaleur_Fluide_Dilatable_base::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name and type and dimensions of the thermo pressure
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Chaleur_Turbulent_QC.
References Equation_base::data_a_sauvegarder(), Probleme_base::domaine(), Nom::getString(), and Equation_base::probleme().
sauvegarder()
int Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
Reimplemented in Convection_Diffusion_Chaleur_WC, and Convection_Diffusion_Chaleur_Turbulent_QC.
References Probleme_base::domaine(), Nom::getString(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), EcritureLectureSpecial::is_ecriture_special(), Equation_base::probleme(), Equation_base::sauvegarder(), and Champ_base::temps().
reprendre()
int Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre (Entree & is) override virtual
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre() et reprend l'inconnue de la chaleur et la pression thermodynamique
Parameters
(Entree& is) un flot d'entree
Returns
(int) renvoie toujours 1
Exceptions
la reprise a echoue, identificateur de la pression non trouve
Reimplemented from Objet_U.
Reimplemented in Convection_Diffusion_Chaleur_WC, and Convection_Diffusion_Chaleur_Turbulent_QC.
References Probleme_base::domaine(), Nom::getString(), Equation_base::probleme(), Equation_base::reprendre(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
vitesse_pour_transport()
const Champ_base & Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
Reimplemented in Convection_Diffusion_Chaleur_QC, and Convection_Diffusion_Chaleur_WC.
References Probleme_base::equation(), Equation_base::probleme(), and Navier_Stokes_std::rho_la_vitesse().
Referenced by Convection_Diffusion_Chaleur_QC::vitesse_pour_transport(), and Convection_Diffusion_Chaleur_WC::vitesse_pour_transport().
domaine_application()
const Motcle & Convection_Diffusion_Chaleur_Fluide_Dilatable_base::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
derivee_en_temps_inco()
DoubleTab & Convection_Diffusion_Chaleur_Fluide_Dilatable_base::derivee_en_temps_inco (DoubleTab & derivee) override virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Reimplemented from Equation_base.
References Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl().
is_generic()
bool Convection_Diffusion_Chaleur_Fluide_Dilatable_base::is_generic () const override pure virtual
Implements Convection_Diffusion_Fluide_Dilatable_base.
Implemented in Convection_Diffusion_Chaleur_QC, and Convection_Diffusion_Chaleur_WC.
calculer_div_u_ou_div_rhou()
void Convection_Diffusion_Chaleur_Fluide_Dilatable_base::calculer_div_u_ou_div_rhou (DoubleTab & res) const override pure virtual
Implements Convection_Diffusion_Fluide_Dilatable_base.
Implemented in Convection_Diffusion_Chaleur_QC, and Convection_Diffusion_Chaleur_WC.
is_thermal()
bool Convection_Diffusion_Chaleur_Fluide_Dilatable_base::is_thermal () const inline override virtual
Implements Convection_Diffusion_Fluide_Dilatable_base.