CEA TRUST Platform: TroisDto2D_32_64< _SIZE_ > Class Template Reference
TroisDto2D_32_64< _SIZE_ > Class Template Reference
Public Member Functions
Entree & interpreter_ (Entree &) override
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class TroisDto2D_32_64< _SIZE_ >
See also
Interprete Pave, Actuellement le seul type d'objet reconnu par TRUST pour mailler un domaine est le Pave.
Member Typedef Documentation
int_t
template<typename _SIZE_ > using TroisDto2D_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using TroisDto2D_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using TroisDto2D_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using TroisDto2D_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using TroisDto2D_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Bord_t
template<typename _SIZE_ > using TroisDto2D_32_64< _SIZE_ >::Bord_t = Bord_32_64<_SIZE_>
Faces_t
template<typename _SIZE_ > using TroisDto2D_32_64< _SIZE_ >::Faces_t = Faces_32_64<_SIZE_>
Frontiere_t
template<typename _SIZE_ > using TroisDto2D_32_64< _SIZE_ >::Frontiere_t = Frontiere_32_64<_SIZE_>
Raccord_t
template<typename _SIZE_ > using TroisDto2D_32_64< _SIZE_ >::Raccord_t = OWN_PTR(Raccord_base_32_64<_SIZE_>)
Member Function Documentation
interpreter_()
template<typename _SIZE_ > Entree & TroisDto2D_32_64< _SIZE_ >::interpreter_ (Entree & is) override virtual
Fonction principale de l'interprete Extract_2D_from_3D Structure du jeu de donnee (en dimension 3) :
Extract_2D_from_3D dom3D bord3D dom2D
Parameters
(Entree& is) un flot d'entree
Returns
(Entree&) le flot d'entree
Exceptions
l'objet a mailler n'est pas du type Domaine
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Interprete_bloc::ajouter(), Domaine_32_64< _SIZE_ >::bord(), Objet_U::dimension, Process::exit(), Scatter::init_sequential_domain(), Interprete_bloc::interprete_courant(), Interprete_bloc::objet_global(), Interprete_bloc::objet_global_existant(), Objet_U_ptr::typer(), and Scatter::uninit_sequential_domain().
extraire_2D()
template<typename _SIZE_ > void TroisDto2D_32_64< _SIZE_ >::extraire_2D (const Domaine_t & dom3D, Domaine_t & dom2D, const Bord_t & bord3D, const Nom & nom_bord, int test_axi)
References Frontiere_32_64< _SIZE_ >::associer_domaine(), Raccords_32_64< _SIZE_ >::associer_domaine(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Process::exit(), Frontiere_32_64< _SIZE_ >::faces(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), Faces_32_64< _SIZE_ >::les_sommets(), Frontiere_32_64< _SIZE_ >::les_sommets_des_faces(), Frontiere_32_64< _SIZE_ >::nommer(), Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::reordonner(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_32_64< _SIZE_ >::typer(), Frontiere_32_64< _SIZE_ >::typer_faces(), and Faces_32_64< _SIZE_ >::voisins().
getXa()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getXa () inline
getYa()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getYa () inline
getZa()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getZa () inline
getIx()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getIx () inline
getIy()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getIy () inline
getIz()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getIz () inline
getJx()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getJx () inline
getJy()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getJy () inline
getJz()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getJz () inline
getKx()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getKx () inline
getKy()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getKy () inline
getKz()
template<typename _SIZE_ > double TroisDto2D_32_64< _SIZE_ >::getKz () inline
coupe()
template<typename _SIZE_ > int& TroisDto2D_32_64< _SIZE_ >::coupe () inline
References TroisDto2D_32_64< _SIZE_ >::coupe_.
Member Data Documentation
coupe_
template<typename _SIZE_ > int TroisDto2D_32_64< _SIZE_ >::coupe_ = 1 protected
Referenced by TroisDto2D_32_64< _SIZE_ >::coupe().