CEA TRUST Platform: Champ_Generique_Predefini Class Reference
Champ_Generique_Predefini Class Reference
Public Member Functions
const Noms get_property (const Motcle &query) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &) override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
Entity get_localisation (const int index=-1) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
Public Member Functions inherited from Champ_Generique_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
set_param()
void Champ_Generique_Predefini::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Param::ajouter_non_std(), and Param::REQUIRED.
lire_motcle_non_standard()
int Champ_Generique_Predefini::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::lire_motcle_non_standard(), nom_pb_, and type_champ_.
completer()
void Champ_Generique_Predefini::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
get_source()
const Champ_Generique_base & Champ_Generique_Predefini::get_source (int i) const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
get_property()
const Noms Champ_Generique_Predefini::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References Motcles::search(), and type_champ_.
get_champ()
const Champ_base & Champ_Generique_Predefini::get_champ (OWN_PTR(Champ_base)& espace_stockage) const override
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Predefini::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const override virtual
Implements Champ_Generique_base.
nommer()
void Champ_Generique_Predefini::nommer (const Nom &) override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
get_nom_post()
const Nom & Champ_Generique_Predefini::get_nom_post () const override virtual
Reimplemented from Champ_Generique_base.
nommer_source()
void Champ_Generique_Predefini::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
construit_expression()
Nom Champ_Generique_Predefini::construit_expression ()
References Objet_U::dimension, Process::exit(), nom_pb_, Motcles::search(), and type_champ_.
OWN_PTR()
Champ_Generique_Predefini::OWN_PTR (Champ_Generique_base) protected
Member Data Documentation
type_champ_
Nom Champ_Generique_Predefini::type_champ_ protected
Referenced by construit_expression(), get_property(), and lire_motcle_non_standard().
nom_pb_
Nom Champ_Generique_Predefini::nom_pb_ protected
Referenced by construit_expression(), and lire_motcle_non_standard().