CEA TRUST Platform: TRUSTVect< _TYPE_, _SIZE_ > Class Template Reference
TRUSTVect< _TYPE_, _SIZE_ > Class Template Reference
#include <TRUSTVect.h>
Public Member Functions
void ref_array (TRUSTArray< _TYPE_, _SIZE_ > &, _SIZE_ start=0, _SIZE_ sz=-1) override
void ref_data (_TYPE_ *ptr, _SIZE_ new_size) override
void resize_tab (_SIZE_ n, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) override
TRUSTVect (_SIZE_ n)
TRUSTVect (const TRUSTVect &v)
Public Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
_TYPE_ * addr ()
void append_array (_TYPE_ valeur)
TRUSTArray & inject_array (const TRUSTArray &source, _SIZE_ nb_elements=-1, _SIZE_ first_element_dest=0, _SIZE_ first_element_source=0)
TRUSTArray & operator*= (const _TYPE_ dy)
TRUSTArray & operator+= (const _TYPE_ dy)
TRUSTArray & operator+= (const TRUSTArray &y)
TRUSTArray & operator-= (const _TYPE_ dy)
TRUSTArray & operator-= (const TRUSTArray &y)
TRUSTArray & operator/= (const _TYPE_ dy)
TRUSTArray & operator= (_TYPE_ x)
TRUSTArray & operator= (const TRUSTArray &)
_TYPE_ & operator[] (_SIZE_ i)
void ordonne_array ()
void ref_as_small (TRUSTArray< float, int > &out) const
int ref_count () const
void resize_array (_SIZE_ new_size, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT)
void set_mem_storage (const STORAGE storage)
_SIZE_ size_array () const
TRUSTArray (const TRUSTArray &A)
virtual ~TRUSTArray ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
const Nom & que_suis_je () const
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from TRUSTArray< _TYPE_, _SIZE_ >
void attach_array (const TRUSTArray &a, _SIZE_ start=0, _SIZE_ size=-1)
bool detach_array ()
void resize_array_ (_SIZE_ n, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Typedef Documentation
Span_
template<typename _TYPE_ , typename _SIZE_ > using TRUSTVect< _TYPE_, _SIZE_ >::Span_ = tcb::span<_TYPE_>
Constructor & Destructor Documentation
~TRUSTVect()
template<typename _TYPE_ , typename _SIZE_ > virtual TRUSTVect< _TYPE_, _SIZE_ >::~TRUSTVect () inline virtual
TRUSTVect() [1/3]
template<typename _TYPE_ , typename _SIZE_ > TRUSTVect< _TYPE_, _SIZE_ >::TRUSTVect () inline
TRUSTVect() [2/3]
template<typename _TYPE_ , typename _SIZE_ > TRUSTVect< _TYPE_, _SIZE_ >::TRUSTVect (_SIZE_ n) inline
construction d'un vecteur de taille n.
Les elements du vecteur sont initialises a zero par defaut. Pour ne pas initialiser les valeurs, utiliser ceci: DoubleVect toto; toto.resize(n, RESIZE_OPTIONS::NOCOPY_NOINIT);
TRUSTVect() [3/3]
template<typename _TYPE_ , typename _SIZE_ > TRUSTVect< _TYPE_, _SIZE_ >::TRUSTVect (const TRUSTVect< _TYPE_, _SIZE_ > & v) inline
Constructeur par copie.
Il s'agit d'un "deep copy" voir ArrOfDouble::ArrOfDouble(const ArrOfDouble &) Remarque: il n'y a pas de constructeur par copie a partir de ArrOfDouble Ceci est volontaire, sinon on risque de grosses pertes de performances par creation implicite d'objets, difficile a trouver. (exemple: appel d'une methode toto(const IntVect &) avec un ArrOfInt produit une copie du tableau !) Utiliser copy() pour copier un ArrOfDouble dans un DoubleVect
Member Function Documentation
taille_memoire()
template<typename _TYPE_ , typename _SIZE_ > unsigned TRUSTVect< _TYPE_, _SIZE_ >::taille_memoire () const inline override protected virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
duplique()
template<typename _TYPE_ , typename _SIZE_ > int TRUSTVect< _TYPE_, _SIZE_ >::duplique () const inline override protected virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References Process::exit(), Objet_U::numero(), and TRUSTVect< _TYPE_, _SIZE_ >::TRUSTVect.
printOn()
template<typename _TYPE_ , typename _SIZE_ > Sortie & TRUSTVect< _TYPE_, _SIZE_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::md_vector_, MD_Vector::non_nul(), and TRUSTArray< _TYPE_, _SIZE_ >::printOn().
readOn()
template<typename _TYPE_ , typename _SIZE_ > Entree & TRUSTVect< _TYPE_, _SIZE_ >::readOn (Entree & is) inline override protected virtual
Lecture d'un vecteur sequentiel (comme un ArrOfDouble) Attention: appel invalide si le vecteur a un MD_Vector non nul.
(pour les vecteurs paralleles, utiliser une methode de sauvegarde/reprise)
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size_, TRUSTVect< _TYPE_, _SIZE_ >::md_vector_, MD_Vector::non_nul(), TRUSTArray< _TYPE_, _SIZE_ >::readOn(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and TRUSTVect< _TYPE_, _SIZE_ >::size_reelle_.
Referenced by TRUSTTab< _TYPE_, _SIZE_ >::readOn().
operator=() [1/2]
template<typename _TYPE_ , typename _SIZE_ > TRUSTVect< _TYPE_, _SIZE_ > & TRUSTVect< _TYPE_, _SIZE_ >::operator= (const TRUSTVect< _TYPE_, _SIZE_ > & v) inline
Referenced by TRUSTTab< _TYPE_, _SIZE_ >::operator=().
operator=() [2/2]
template<typename _TYPE_ , typename _SIZE_ > TRUSTVect< _TYPE_, _SIZE_ > & TRUSTVect< _TYPE_, _SIZE_ >::operator= (_TYPE_ x) inline
References TRUSTArray< _TYPE_, _SIZE_ >::operator=().
size()
template<typename _TYPE_ , typename _SIZE_ > _SIZE_ TRUSTVect< _TYPE_, _SIZE_ >::size () const inline
Referenced by Champ_Face_VDF::affecter(), Champ_Face_VDF::affecter(), Champ_Face_VDF::affecter(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Perte_Charge_Singuliere_PolyMAC_Face::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_Singuliere_VEF_Face::ajouter(), Perte_Charge_VEF::ajouter(), Source_WC_Chaleur::ajouter_(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Iterateur_VDF_Elem< _TYPE_ >::ajouter_blocs(), Op_Conv_EF::ajouter_contribution_sous_cond(), Solveur_Masse_base::ajouter_masse(), Solveur_Masse_base::ajouter_masse_dt_local(), Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), Matrice_Diagonale::ajouter_multTab_(), Matrice_Morse::ajouter_multvect_(), Matrice_Morse_Sym::ajouter_multvect_(), Matrice_Dense::ajouter_multvect_(), Matrice_Diagonale::ajouter_multvect_(), Matrice_Dense::ajouter_multvectT_(), Op_Conv_EF::ajouter_sous_cond_template(), Masse_VDF_Elem::appliquer_impl(), Assembleur_P_VEF::assembler(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_EF::assembler_mat(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Simpler_Base::assembler_matrice_pression_implicite(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Matrice_Dense::build_matrix_from_coefficients_column_by_column(), Matrice_Dense::build_matrix_from_coefficients_line_by_line(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Hexa_poly::calcul_xg(), Quadri_poly::calcul_xg(), Segment_poly::calcul_xg(), Tetra_poly::calcul_xg(), Hexa_EF::calcul_xg(), Point_EF::calcul_xg(), Quadri_EF::calcul_xg(), Segment_EF::calcul_xg(), Tetra_EF::calcul_xg(), Tri_EF::calcul_xg(), Hexa_VEF::calcul_xg(), Quadri_VEF::calcul_xg(), Tri_VEF::calcul_xg(), Champ_P1NC::calcul_y_plus(), Perte_Charge_Singuliere::calculate_Q(), Champ_Q1NC_implementation::calcule_valeur_a_elem_compo(), Loi_Etat_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Champ_front_xyz_debit::calculer_champ_vitesse(), Loi_Etat_GR_base::calculer_Cp(), Champ_front_Parametrique::calculer_derivee_en_temps(), Modele_turbulence_scal_Schmidt::calculer_diffusion_turbulente(), Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Modele_turbulence_hyd_LES_base::calculer_energie_cinetique_turb(), Domaine_Poly_base::calculer_h_carre(), Loi_Etat_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_QC::calculer_masse_molaire(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_TPPI_QC_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_TPPI_WC_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Loi_Etat_base::calculer_nu(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_tab_Cp(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Op_Diff_RotRot::calculer_vorticite(), Echange_global_impose::champ_exterieur(), Matrice_Morse::check_morse_matrix_structure(), Matrice_Morse::check_sorted_morse_matrix_structure(), Domaine_32_64< _SIZE_ >::chercher_elements(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Eval_Amont_PolyMAC_Elem::coeffs_face(), Eval_centre_PolyMAC_Elem::coeffs_face(), Eval_Amont_PolyMAC_Elem::coeffs_face(), Eval_centre_PolyMAC_Elem::coeffs_face(), Eval_Amont_PolyMAC_Elem::coeffs_face(), Eval_centre_PolyMAC_Elem::coeffs_face(), Eval_Amont_PolyMAC_Elem::coeffs_faces_interne(), Eval_centre_PolyMAC_Elem::coeffs_faces_interne(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Partitionneur_Sous_Domaines::construire_partition(), Perte_Charge_Singuliere_PolyMAC_Face::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_Singuliere_VEF_Face::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Source_PDF_EF::correct_incr_pressure(), Source_PDF_EF::correct_variable(), Perte_Charge_Reguliere::correction_direction(), Terme_Source_Solide_SWIFT_VDF::correspondance_SWIFT_coarse(), Domaine_VDF::creer_elements_fictifs(), Matrice_Morse::dimensionner(), Roue::dimensionner(), Roue::dimensionner(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::dimensionner_blocs(), DP_Impose_VEF_Face::dimensionner_blocs(), Format_Post_Lml::ecrire_item_int_lml(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_nut(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_Temp_old(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu(), Traitement_particulier_NS_canal::ecriture_fichiers_moy_vitesse_rho_mu_old(), Domaine_Poly_base::elem_arete_d(), Domaine_Poly_base::elem_som_d(), Matrix_tools::extend_matrix_stencil(), Champ_Generique_Reduction_0D::extraire(), ILU_SP::factorisation(), Domaine_PolyMAC_P0::fgrad(), Convection_Diffusion_Temperature::filtrage_si_appart_ibc(), Champ_P1NC_implementation::filtrer_L2(), Eval_Amont_PolyMAC_Elem::flux_face(), Eval_centre_PolyMAC_Elem::flux_face(), Eval_Amont_PolyMAC_Elem::flux_face(), Eval_centre_PolyMAC_Elem::flux_face(), Eval_Amont_PolyMAC_Elem::flux_face(), Eval_centre_PolyMAC_Elem::flux_face(), Eval_Amont_PolyMAC_Elem::flux_faces_interne(), Eval_centre_PolyMAC_Elem::flux_faces_interne(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Milieu_MUSIG::get_Diameter_Inf(), Milieu_MUSIG::get_Diameter_Sup(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), Matrice_Diagonale::get_stencil_and_coefficients(), Matrice_Morse::get_stencil_and_coefficients(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Ch_front_var_stationnaire::has_valeurs_au_temps(), Champ_front_instationnaire_base::has_valeurs_au_temps(), Champ_front_var_instationnaire::has_valeurs_au_temps(), Source_base::impr(), Champ_Fonc_P0_VDF::imprime(), Champ_P0_VDF::imprime(), Champ_Face_VDF_implementation::imprime_Face(), Echange_contact_Correlation_VDF::imprimer(), Echange_contact_Correlation_VEF::imprimer(), Champ_Elem_PolyMAC_P0::init_grad(), Domaine_PolyMAC_P0::init_stencils(), Champ_Face_PolyMAC_P0::init_ve2(), Sonde::initialiser(), Champ_front_recyclage::initialiser(), Champ_Face_PolyMAC::interp_ve(), Champ_Face_PolyMAC_P0P1NC::interp_ve(), Testeur::interpreter(), Lire_Tgrid::interpreter_(), Matrice_Morse::inverse(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Champ_Inc_base::lire_donnees(), Champ_Tabule_Temps::me_calculer(), Champ_front_pression_from_u::mettre_a_jour(), Modele_turbulence_scal_Prandtl::mettre_a_jour(), Echange_contact_Correlation_VDF::mettre_a_jour(), Correlation_Vec_Sca_VEF::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Integrale_tps_Champ::mettre_a_jour_integrale(), Tetra_VEF::modif_volumes_entrelaces_faces_joints(), Tri_VEF::modif_volumes_entrelaces_faces_joints(), Assembleur_P_VEFPreP1B::modifier_solution(), Matrice_Morse_Sym::multvect_et_prodscal(), Matrice_Morse::nb_coeff(), Matrice_Diagonale::nb_colonnes(), Matrice_Diagonale::nb_lignes(), Matrice_Morse::nb_lignes(), Champ_P1_isoP1Bulle::norme_L2(), Matrice_Diagonale::ordre(), Convection_Diffusion_Temperature::penalisation_L2(), Traitement_particulier_NS_canal::post_traitement_particulier(), Precond_local::precond(), ILU_SP::preconditionner_(), Solv_GCP::prepare_data(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), TRUSTChamp_Don_generique< _TYPE_ >::printOn(), Domaine_Poly_base::pvol_som(), Loi_Etat_Multi_GP_QC::rabot(), Reaction::reagir(), Table::remplir(), Champ_front_contact_VEF::remplir_faces_coin(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Domaine_VF::renumeroter(), Domaine_VDF::reordonner(), Precond_local::res_syst_loc_hybride(), Precond_local::res_syst_loc_simple(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), Solv_Gen::resoudre_systeme(), Modele_turbulence_hyd_base::sauvegarder(), Ch_front_Vortex::sauvegarder_vortex(), Eval_Amont_PolyMAC_Elem::secmem_face(), Eval_centre_PolyMAC_Elem::secmem_face(), Eval_Amont_PolyMAC_Elem::secmem_face(), Eval_centre_PolyMAC_Elem::secmem_face(), Champ_Input_Proto::setValueOnTab(), Solv_Gen::solve(), Matrice_Morse::sort_stencil(), Terme_Source_Canal_perio::source(), Champ_front_contact_VEF::test_faces_coin(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant(), Champ_front_contact_VEF::trace_face_raccord(), Convection_Diffusion_Temperature::transport_ibc(), Aretes::trier(), Aretes::trier_pour_debog(), Navier_Stokes_std::uzawa(), Table::val(), Dirichlet::val_imp_au_temps(), Table::val_simple(), Champ_base::valeur_a(), Champ_front_softanalytique::valeur_a(), Champ_som_lu_VEF::valeur_a_compo(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_sommet::valeur_a_elem(), Champ_Q1NC_implementation::valeur_a_elem(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_a_elem(), Champ_implementation_sommet::valeur_a_elem_compo(), Tayl_Green::valeur_aux(), Tayl_Green::valeur_aux_compo(), Champ_Q4_implementation::valeur_aux_elems(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_implementation::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_implementation_sommet::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_Q4_implementation::valeur_aux_elems_compo(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_elems_compo(), Champ_Face_VDF_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_Q1NC_implementation::valeur_aux_elems_compo(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_implementation_sommet::valeur_aux_elems_compo(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_Face_PolyMAC_P0::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Q4_implementation::valeur_aux_sommets(), Champ_Q4_implementation::valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_sommet::valeur_aux_sommets_compo_impl(), Table::valeurs(), Champ_Front_Composite::valeurs_face(), Domaine_VEF::vecteur_face_facette(), Debog_Pb::verifier_partie_std(), Domaine_Poly_base::vol_elem_som(), LireMED_32_64< _SIZE_ >::write_sub_dom_datasets(), and Roue::~Roue().
size_totale()
template<typename _TYPE_ , typename _SIZE_ > _SIZE_ TRUSTVect< _TYPE_, _SIZE_ >::size_totale () const inline
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Debog_Pb::add_renum_item(), TRUSTTab< _TYPE_, _SIZE_ >::ajoute_produit_tensoriel(), Matrice_Morse_Sym::ajouter_multvect_(), SETS::assembler(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Assembleur_P_VEFPreP1B::assembler_mat(), Milieu_base::calculate_face_hydr_diam(), Milieu_base::calculate_face_porosity(), Domaine_EF::calculer_Bij(), Assembleur_P_VEF::calculer_inv_volume(), Domaine_32_64< _SIZE_ >::calculer_volumes(), Solv_Cholesky::Cholesky(), Periodique::completer(), Solv_Externe::construit_renum(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Op_Div_PolyMAC_P0P1NC::dimensionner_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Source_Flux_interfacial_base::dimensionner_blocs(), Source_Force_Tchen_base::dimensionner_blocs(), Source_Frottement_interfacial_base::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Op_Conv_VDF_base::dimensionner_blocs_face(), Solveur_Masse_Face_proto::dimensionner_blocs_proto(), Milieu_base::discretiser_diametre_hydro(), Milieu_base::discretiser_porosite(), Loi_Etat_GP_base::initialiser(), Test_solveur::interpreter(), Simple::iterer_eqs(), EOS_Tools_VDF::mettre_a_jour(), Source_PDF_EF::multiply_coeff_volume(), Matrice_Morse_Sym::multvect_et_prodscal(), Champ_P1NC_implementation::nb_colonnes_tot(), SSOR::prepare_(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Domaine_EF::reordonner(), Domaine_Poly_base::reordonner(), Solv_GCP::resoudre_(), Solv_GCP_NS::resoudre_systeme(), Fluide_Quasi_Compressible::secmembre_divU_Z(), champ_init_canal_sinal::valeur_aux(), Init_par_partie::valeur_aux(), Tayl_Green::valeur_aux(), Tayl_Green::valeur_aux_compo(), Champ_Q4_implementation::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems_compo(), Champ_Q4_implementation::valeur_aux_elems_compo(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_elems_compo(), Champ_Face_VDF_implementation::valeur_aux_elems_compo(), Champ_Q1NC_implementation::valeur_aux_elems_compo(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_Face_PolyMAC_P0::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Debog_Pb::verifier_matrice(), Debog_Pb::verifier_partie_std(), and Op_Div_VEFP1B_Elem::volumique().
size_reelle()
template<typename _TYPE_ , typename _SIZE_ > _SIZE_ TRUSTVect< _TYPE_, _SIZE_ >::size_reelle () const inline
Referenced by Domaine_Cl_VDF::completer(), Partitionneur_base_32_64< _SIZE_ >::corriger_elem0_sur_proc0(), DomaineCutter_32_64< _SIZE_ >::ecrire_domaines(), TRUSTVect< _TYPE_, _SIZE_ >::get_span(), TRUSTVect< _TYPE_, _SIZE_ >::get_span(), Champ_P1NC_implementation::nb_colonnes(), TRUSTTab< _TYPE_, _SIZE_ >::operator=(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), and Solv_GCP::resoudre_().
size_reelle_ok()
template<typename _TYPE_ , typename _SIZE_ > _SIZE_ TRUSTVect< _TYPE_, _SIZE_ >::size_reelle_ok () const inline
Referenced by Op_Correlation::completer(), Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), Champ_Face_PolyMAC_P0P1NC::init_auxiliary_variables(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Champ_Inc_base::nb_valeurs_nodales(), TRUSTTab< _TYPE_, _SIZE_ >::operator=(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), and Solv_GCP::resoudre_().
line_size()
template<typename _TYPE_ , typename _SIZE_ > int TRUSTVect< _TYPE_, _SIZE_ >::line_size () const inline
Referenced by Champ_Face_PolyMAC_P0::affecter_(), TRUSTTab< _TYPE_, _SIZE_ >::ajoute_produit_tensoriel(), Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Diff_PolyMAC_Elem::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Iterateur_Source_EF_Som< _TYPE_ >::ajouter(), Iterateur_Source_Elem< _TYPE_ >::ajouter(), Iterateur_Source_Face< _TYPE_ >::ajouter(), Source_Generique_VEF::ajouter(), Iterateur_Source_VEF_Face< _TYPE_ >::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Decroissance_Radioactive_VEF_Face::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Diff_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0_Face::ajouter_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), Op_Diff_PolyMAC_P0_Elem::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_base::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Solveur_Masse_Face_proto::ajouter_blocs_proto(), Solveur_Masse_Elem_proto::ajouter_blocs_proto(), Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_bord_gen(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Iterateur_VDF_Elem< _TYPE_ >::ajouter_contribution_autre_pb(), Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_contribution_bord_gen(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_interne_gen(), Masse_PolyMAC_Elem::ajouter_masse(), Solveur_Masse_base::ajouter_masse(), Masse_PolyMAC_Elem::ajouter_masse(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Diff_EF::ajouter_scalaire_template(), Op_Dift_EF_Q1::ajouter_scalaire_template(), Op_Conv_EF::ajouter_sous_cond(), Op_Conv_EF::ajouter_sous_cond_template(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Diff_EF::ajouter_vectoriel_template(), Op_Dift_EF_Q1::ajouter_vectoriel_template(), Op_Dift_VDF_Multi_inco_Elem::alpha_(), Op_Dift_VDF_Multi_inco_Elem_Axi::alpha_(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_Face::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_PolyMAC_P0P1NC_Face::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Solveur_Masse_Elem_proto::appliquer_impl_proto(), SETS::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Assembleur_P_PolyMAC_P0::assembler_continuite(), Assembleur_P_VDF::assembler_continuite(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_elem(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_faces(), Op_Evanescence_Homogene_VDF_Face::calc_grad_alpha_faces(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Loi_paroi_log::calc_y_plus(), Champ_Face_VDF::calcul_critere_Q(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_duidxj(), Champ_Face_VDF::calcul_grad_u(), Champ_Face_VDF::calcul_S_barre(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Perte_Charge_Singuliere::calculate_Q(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Equation_base::calculer_champ_conserve(), Moyenne_volumique::calculer_convolution(), Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Op_Conv_EF_Stab_PolyMAC_P0_Face::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Loi_Etat_rhoT_GR_QC::calculer_H(), Champ_P1NC::calculer_integrale_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_rhoT_GR_QC::calculer_masse_volumique(), Loi_Etat_base::calculer_nu(), Fluide_base::calculer_nu(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Op_Conv_VDF_base::calculer_pour_post(), Convection_Diffusion_Temperature::calculer_rho_cp_T(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_S_barre(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_Sij2(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Loi_Etat_rhoT_GR_QC::calculer_temperature(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Op_Diff_PolyMAC_Elem::completer(), Op_Diff_PolyMAC_P0_Elem::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Navier_Stokes_Fluide_Dilatable_base::completer(), Source_Flux_interfacial_base::completer(), Solv_Externe::construit_renum(), Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Terme_Source_Decroissance_Radioactive_VEF_Face::contribuer_a_avec(), Op_Div_PolyMAC_P0::contribuer_a_avec(), Iterateur_VDF_Elem< _TYPE_ >::contribuer_au_second_membre(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Masse_VDF_Face::corriger_solution(), Solveur_Masse_base::corriger_solution(), Masse_PolyMAC_P0P1NC_Face::corriger_solution(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), MD_Vector_tools::creer_md_vect_renum(), Op_EF_base::dimensionner(), Op_VDF_Face::dimensionner(), Op_VEF_Face::dimensionner(), Op_Diff_PolyMAC_Elem::dimensionner(), Op_Div_PolyMAC_P0::dimensionner(), Solveur_Masse_base::dimensionner(), Masse_PolyMAC_Elem::dimensionner(), Masse_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_VDF_Face::dimensionner_blocs(), Masse_VDF_base::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0_Face::dimensionner_blocs(), Op_Grad_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Op_Evanescence_Homogene_Elem_base::dimensionner_blocs(), Op_Evanescence_Homogene_Face_base::dimensionner_blocs(), Source_Flux_interfacial_base::dimensionner_blocs(), Source_Force_Tchen_base::dimensionner_blocs(), Source_Frottement_interfacial_base::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), DP_Impose_VEF_Face::dimensionner_blocs(), Dispersion_bulles_PolyMAC_P0::dimensionner_blocs_aux(), Force_Tchen_PolyMAC_P0::dimensionner_blocs_aux(), Frottement_interfacial_PolyMAC_P0::dimensionner_blocs_aux(), Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs_aux(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Op_Diff_PolyMAC_P0P1NC_Elem::dimensionner_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Op_Conv_VDF_base::dimensionner_blocs_face(), Solveur_Masse_Face_proto::dimensionner_blocs_proto(), Solveur_Masse_Elem_proto::dimensionner_blocs_proto(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Loi_Etat_rhoT_GR_QC::Drho_DP(), Loi_Etat_rhoT_GR_QC::Drho_DT(), Loi_Etat_rhoT_GR_QC::DT_DH(), MD_Vector_tools::dump_vector_with_md(), Debog_Pb::ecrire_gen(), Debog_Pb::ecrire_partie(), Viscosite_turbulente_WALE::eddy_viscosity(), Discretisation_tools::faces_to_cells(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Transformation::get_champ(), VDF_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Equation_base::init_champ_conserve(), Energie_Multiphase::init_champ_convecte(), Equation_base::initialise_residu(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Champ_Fonc_Interp::initialiser(), Champ_P0_VDF::integrale_espace(), Champ_Fonc_Face_PolyMAC::interp_valeurs_elem(), Champ_Face_PolyMAC_P0P1NC::interp_ve(), Simple::iterer_eqn(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), Dirichlet_loi_paroi::liste_faces_loi_paroi(), Echange_global_impose_turbulent::liste_faces_loi_paroi(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), QDM_Multiphase::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Interface_base::mettre_a_jour(), Saturation_base::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Op_Dift_VEF_Face_Gen< DERIVED_T >::modifie_pour_cl_gen(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Viscosite_turbulente_base::modifier_mu(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_PolyMAC_P0P1NC::modifier_secmem_pour_incr_p(), EOS_Tools_VEF::moyenne_vol(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_L2(), TRUSTTab< _TYPE_, _SIZE_ >::operator=(), Operateur_base::ouvrir_fichier(), Convection_Diffusion_Temperature::penalisation_L2(), Sonde::postraiter(), Postraitement::postraiter_tableau(), SSOR::prepare_(), Solv_GCP::prepare_data(), TRUSTTab< _TYPE_, _SIZE_ >::printOn(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::ref_tab(), Champ_Q1NC_implementation::remplir_coord_noeuds(), Op_Diff_VEF_base::remplir_nu(), VDF_discretisation::residu(), VEF_discretisation::residu(), PolyMAC_P0_discretisation::residu(), PolyMAC_P0P1NC_discretisation::residu(), Solv_GCP::resoudre_(), Solv_Petsc::resoudre_systeme(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), Vecteur3::set(), Solv_Gen::solve(), VDF_discretisation::t_paroi(), PolyMAC_P0_discretisation::taux_cisaillement(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Face_PolyMAC_P0P1NC::trace(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_elem_distant(), Frontiere_32_64< _SIZE_ >::trace_elem_local(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant(), Frontiere_32_64< _SIZE_ >::trace_face_local(), Frontiere_32_64< _SIZE_ >::trace_som_local(), TRUSTTrav< _TYPE_ >::TRUSTTrav(), SETS::unknown_positivation(), Champ_front_debit_massique::update_coeff(), Op_Diff_PolyMAC_Elem::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), grad_Champ_Face_PolyMAC_P0::update_ge(), Op_Grad_PolyMAC_P0_Face::update_grad(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Face_PolyMAC_P0::update_ve2(), Champ_Face_VDF::v_norm(), Dirichlet::val_imp_au_temps(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_Composite::valeur_aux(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux(), Champ_implementation_sommet::valeur_aux_bords(), Champ_Inc_base::valeur_aux_bords(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), TRUSTChamp_Divers_generique< _TYPE_ >::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Face_PolyMAC::valeur_aux_elems_(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_Face_PolyMAC_P0::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Face_PolyMAC_P0P1NC::valeur_aux_faces(), Champ_Fonc_Face_PolyMAC::valeur_aux_faces(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_sommet::valeur_aux_sommets_impl(), Champ_implementation_P1::value_interpolation(), Vecteur3::Vecteur3(), Debog_Pb::verifier_gen(), Debog_Pb::verifier_partie(), and Debog_Pb::verifier_partie_std().
resize()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::resize (_SIZE_ n, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
Referenced by Matrice_Morse::affecte_prod(), Domaine_32_64< _SIZE_ >::ajouter(), Iterateur_Source_VEF_Face< _TYPE_ >::ajouter(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Op_Div_VEFP1B_Elem::ajouter_som(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Domaine_Cl_VDF::associer(), Source_PDF_EF::associer_pb(), Matrice_Grossiere::build_matrix(), Champ_front_contact_VEF::calcul_grads_locaux(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Op_Diff_P1NC_barprim::calculer(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Domaine_EF::calculer_h_carre(), Domaine_Poly_base::calculer_h_carre(), Domaine_VEF::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), Echange_contact_Correlation_VDF::calculer_h_solide(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Modele_turbulence_hyd_LES_VEF_base::calculer_longueurs_caracteristiques(), Faces_VDF::calculer_orientation(), Domaine_EF::calculer_porosites_sommets(), Faces_32_64< _SIZE_ >::calculer_surfaces(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Smago_VEF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), Domaine_EF::calculer_volumes_sommets(), Champ_front_recyclage::Champ_front_recyclage(), Multigrille_base::coarse_solver(), Perte_Charge_Circulaire_PolyMAC_Face::coeffs_perte_charge(), Perte_Charge_Circulaire_VEF_P1NC::coeffs_perte_charge(), Matrice_Morse::compacte(), Matrice_Morse_Sym::compacte(), Faces_32_64< _SIZE_ >::compare(), Source_base::completer(), Champ_front_calc_interne::completer(), DP_Impose_PolyMAC_Face::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Source_Neutronique::completer(), Sortie_libre_Gradient_Pression_impose::completer(), Sortie_libre_Pression_imposee_Orlansky::completer(), Sortie_libre_Gradient_Pression_libre_VEF::completer(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::completer(), DP_Impose_VEF_Face::completer(), Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), Partitionneur_Fichier_MED::construire_partition(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Domaine::construire_partition(), Partitionneur_Sous_Domaines::construire_partition(), Partitionneur_Union::construire_partition(), Matrice_Dense::convert_to_morse_matrix(), Terme_Source_Solide_SWIFT_VDF::correspondance_SWIFT_coarse(), Matrice_Morse::dimensionner(), Matrice_Morse::dimensionner(), Matrice_Diagonale::dimensionner(), Aretes::dimensionner(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Ensemble_Lagrange_base::Ensemble_Lagrange_base(), Paroi_scal_hyd_base_EF::equivalent_distance_name(), Paroi_scal_hyd_base_VEF::equivalent_distance_name(), Paroi_scal_hyd_base_VDF::equivalent_distance_name(), Champ_val_tot_sur_vol_VDF::eval_contrib_loc(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Matrix_tools::extend_matrix(), Champ_Generique_Reduction_0D::extraire(), Milieu_base::fill_section_passage_face(), Echange_contact_Correlation_VEF::init(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Traitement_particulier_Solide_canal::init_calcul_stats(), Traitement_particulier_Solide_canal_VDF::init_calcul_stats(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_negligeable_VEF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), Equation_base::initialise_residu(), Sonde::initialiser(), Sonde_Int::initialiser(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Ch_front_Vortex::initialiser(), Champ_front_contact_VEF::initialiser(), Navier_Stokes_std::initTimeStep(), Matrice_Morse::inverse(), Matrice_Morse::inverse(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), Traitement_particulier_NS_Profils::lire(), Traitement_particulier_NS_Brech_VEF::lire(), Champ_front_recyclage::lire_motcle_non_standard(), Terme_Source_Coriolis_base::lire_motcle_non_standard(), Source_Neutronique::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), Champ_front_recyclage::mettre_a_jour(), Terme_Puissance_Thermique_Echange_Impose_Elem_base::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Assembleur_P_VDF_Q4::modifier_secmem(), Matrice_Morse::partie_sup(), Solv_GCP::prepare_data(), Traitement_particulier_NS_canal::preparer_calcul_particulier(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_implementation_P0::remplir_coord_noeuds_et_polys(), Champ_Q4_implementation::remplir_coord_noeuds_et_polys(), Champ_Face_VDF_implementation::remplir_coord_noeuds_et_polys(), Champ_P1NC_implementation::remplir_coord_noeuds_et_polys(), Champ_Q1NC_implementation::remplir_coord_noeuds_et_polys(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), Champ_front_contact_VEF::remplir_faces_coin(), DP_Impose_PolyMAC_Face::remplir_num_faces(), Perte_Charge_Singuliere_PolyMAC_Face::remplir_num_faces(), DP_Impose_VEF_Face::remplir_num_faces(), Perte_Charge_Singuliere_VEF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Traitement_particulier_NS_canal::remplir_reordonne_Y_tot(), Traitement_particulier_NS_canal_VDF::remplir_Y(), Traitement_particulier_NS_canal_VEF::remplir_Y(), Traitement_particulier_NS_canal::reprendre_stat_canal(), Solv_TDMA::resoudre(), Solv_Gen::resoudre_systeme(), MD_Vector_tools::restore_vector_with_md(), Raccord_distant_homogene_32_64< _SIZE_ >::trace_face_distant(), Traitement_particulier_NS_canal::Traitement_particulier_NS_canal(), Echange_contact_Correlation_VDF::trier_coord(), Champ_front_recyclage::UPb(), champ_init_canal_sinal::valeur_a(), Champ_som_lu_VEF::valeur_a_compo(), champ_init_canal_sinal::valeur_aux_compo(), Champ_front_base::valeurs_face(), Champ_Front_Composite::valeurs_face(), Champ_front_uniforme::valeurs_face(), and Champ_front_instationnaire_base::valeurs_face().
copy() [1/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::copy (const TRUSTArray< _TYPE_, _SIZE_ > & v, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Source_Dirac_VDF_Elem::associer_pb(), Source_Dirac_VEF_Face::associer_pb(), EDO_Pression_th_VEF::masse_totale(), EDO_Pression_th_VEF::masse_totale(), Matrice_Morse::operator=(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), and Solv_GCP::resoudre_().
copy() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::copy (const TRUSTVect< _TYPE_, _SIZE_ > & v, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline
operator+=() [1/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::operator+= (const TRUSTVect< _TYPE_, _SIZE_ > & v) inline
operator+=() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::operator+= (const _TYPE_ x) inline
operator-=() [1/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::operator-= (const TRUSTVect< _TYPE_, _SIZE_ > & v) inline
operator-=() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::operator-= (const _TYPE_ x) inline
operator*=() [1/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::operator*= (const TRUSTVect< _TYPE_, _SIZE_ > & v) inline
operator*=() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::operator*= (const _TYPE_ x) inline
operator/=() [1/2]
template<typename _TYPE_ , typename _SIZE_ > template<typename _T_ > void TRUSTVect< _TYPE_, _SIZE_ >::operator/= (const TRUSTVect< _T_, _SIZE_ > & v) inline
operator/=() [2/2]
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::operator/= (const _TYPE_ x) inline
get_md_vector()
template<typename _TYPE_ , typename _SIZE_ > virtual const MD_Vector & TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector () const inline virtual
References TRUSTVect< _TYPE_, _SIZE_ >::md_vector_.
Referenced by TRUSTTab< _TYPE_, _SIZE_ >::ajoute_produit_tensoriel(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), SETS::assembler(), EOS_Tools_VEF::associer_domaines(), Faces_32_64< _SIZE_ >::Calculer_centres_gravite(), Champ_front_base::calculer_derivee_en_temps(), Op_Conv_VDF_base::calculer_dt_stab(), Navier_Stokes_std::calculer_la_pression_en_pa(), Domaine_32_64< _SIZE_ >::calculer_volumes(), Domaine_VEF::calculer_volumes_entrelaces(), Periodique::completer(), Champ_Generique_Transformation::completer(), Champ_Post_Operateur_Eqn::completer(), Op_Correlation::completer(), Scatter::construire_espace_virtuel_traduction(), Domaine_VEF::construire_ok_arete(), Domaine_VEF::construire_renum_arete_perio(), Solv_Externe::construit_renum(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), MD_Vector_tools::creer_md_vect_renum(), Champ_Fonc_base::creer_tableau_distribue(), Champ_Inc_base::creer_tableau_distribue(), Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl(), Domaine_VF::discretiser(), Milieu_base::discretiser_diametre_hydro(), Milieu_base::discretiser_porosite(), MD_Vector_tools::dump_vector_with_md(), Debog_Pb::ecrire_gen(), Debog_Pb::ecrire_partie(), EcritureLectureSpecial::ecriture_special(), Debog_Pb::find_renum_vector(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Domaine_VF::info_elem_som(), Domaine_VF::init_dist_paroi_globale(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Paroi_hyd_base_EF::init_lois_paroi_(), Paroi_hyd_base_VDF::init_lois_paroi_(), Paroi_hyd_base_VEF::init_lois_paroi_(), Test_solveur::interpreter(), Simple::iterer_eqs(), Solveur_U_P::iterer_NS(), EcritureLectureSpecial::lecture_special(), TRUSTTab< _TYPE_, _SIZE_ >::lit(), Domaine_32_64< _SIZE_ >::md_vector_sommets(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Transport_turbulent_GGDH::modifier_mu(), Domaine_VEF::modifier_pour_Cl(), SSOR::prepare_(), Solv_GCP::prepare_data(), Debog_Pb::read_geometry_data(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Scatter::reordonner_faces_de_joint(), Solv_GCP::resoudre_(), Solv_Gen::solve(), Champ_Elem_PolyMAC::trace(), TRUSTTrav< _TYPE_ >::TRUSTTrav(), Debog_Pb::verifier_gen(), Debog_Pb::verifier_partie(), Debog_Pb::verifier_partie_std(), and Domaine_VF::xv_bord().
resize_tab()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::resize_tab (_SIZE_ n, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline override virtual
Methode virtuelle (dans Array_base) identique a resize_array(), permet de traiter de facon generique les ArrOf, Vect et Tab. Si l'objet est de type TRUSTArray, appel a resize_array(n)
Prerequis: le tableau doit etre "resizable" (voir resize_array()). S'il est d'un type derive (Vect ou Tab), il ne doit pas avoir de descripteur parallele si la taille est effectivement modifiee.
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
from_tid_to_int()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::from_tid_to_int (TRUSTVect< int, int > & out) const inline
References Process::exit(), TRUSTArray< _TYPE_, _SIZE_ >::from_tid_to_int(), and TRUSTVect< _TYPE_, _SIZE_ >::line_size_.
ref_as_big()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ref_as_big (TRUSTVect< _TYPE_, trustIdType > & out) const inline
References Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size_, and TRUSTArray< _TYPE_, _SIZE_ >::ref_as_big().
ref_as_small()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ref_as_small (TRUSTVect< _TYPE_, int > & out) const inline
References Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size_, and TRUSTArray< _TYPE_, _SIZE_ >::ref_as_small().
abs()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::abs (Mp_vect_options opt = VECT_ALL_ITEMS) inline
Referenced by Op_Ecart_type::calculer_valeurs().
carre()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::carre (Mp_vect_options opt = VECT_ALL_ITEMS) inline
racine_carree()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::racine_carree (Mp_vect_options opt = VECT_ALL_ITEMS) inline
Referenced by Op_Ecart_type::calculer_valeurs().
ajoute()
template<typename _TYPE_ , typename _SIZE_ > template<typename _SCALAR_TYPE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ajoute (_SCALAR_TYPE_ alpha, const TRUSTVect< _TYPE_, _SIZE_ > & y, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Referenced by Operateur::ajouter(), Terme_Source_Qdm_lambdaup_VEF_Face::ajouter(), Equation_base::derivee_en_temps_conv(), Leap_frog::faire_un_pas_de_temps_eqn_base(), RRK2::faire_un_pas_de_temps_eqn_base(), Source_Neutronique::faire_un_pas_de_temps_RK(), Simple::iterer_NS(), Integrale_tps_Champ::mettre_a_jour_integrale(), PrecondA::preconditionner_(), Navier_Stokes_std::projeter(), Solv_GCP_NS::resoudre_systeme(), and Navier_Stokes_std::uzawa().
ajoute_sans_ech_esp_virt()
template<typename _TYPE_ , typename _SIZE_ > template<typename _SCALAR_TYPE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ajoute_sans_ech_esp_virt (_SCALAR_TYPE_ alpha, const TRUSTVect< _TYPE_, _SIZE_ > & y, Mp_vect_options opt = VECT_REAL_ITEMS) inline
Referenced by Operateur::ajouter(), Traitement_particulier_NS_Profils_VDF::calculer_integrale_temporelle(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_integrales_temporelles(), Traitement_particulier_Solide_canal_VDF::calculer_integrales_temporelles(), and Fluide_Quasi_Compressible::secmembre_divU_Z().
ajoute_produit_scalaire()
template<typename _TYPE_ , typename _SIZE_ > template<typename _SCALAR_TYPE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ajoute_produit_scalaire (_SCALAR_TYPE_ alpha, const TRUSTVect< _TYPE_, _SIZE_ > & x, const TRUSTVect< _TYPE_, _SIZE_ > & y, Mp_vect_options opt = VECT_ALL_ITEMS) inline
ajoute_carre()
template<typename _TYPE_ , typename _SIZE_ > template<typename _SCALAR_TYPE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ajoute_carre (_SCALAR_TYPE_ alpha, const TRUSTVect< _TYPE_, _SIZE_ > & y, Mp_vect_options opt = VECT_ALL_ITEMS) inline
Referenced by Op_Ecart_type::calculer_valeurs(), and Integrale_tps_Champ::mettre_a_jour_integrale().
local_max_vect()
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTVect< _TYPE_, _SIZE_ >::local_max_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const inline
Referenced by Solveur_Masse_base::ajouter_masse_dt_local().
local_min_vect()
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const inline
Referenced by Champ_P1NC::calcul_y_plus(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Paroi_negligeable_VEF::calculer_hyd(), and Paroi_negligeable_VEF::calculer_hyd().
local_max_abs_vect()
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTVect< _TYPE_, _SIZE_ >::local_max_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const inline
Referenced by Op_Diff_VEFP1NCP1B_Face::test().
local_min_abs_vect()
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTVect< _TYPE_, _SIZE_ >::local_min_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const inline
mp_max_vect()
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTVect< _TYPE_, _SIZE_ >::mp_max_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const inline
Referenced by Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab().
mp_min_vect()
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTVect< _TYPE_, _SIZE_ >::mp_min_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const inline
Referenced by ExtrudeParoi::extrude(), Matrice_Morse::imprimer_formatte(), and Matrice_Morse::imprimer_image().
mp_max_abs_vect()
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTVect< _TYPE_, _SIZE_ >::mp_max_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const inline
Referenced by Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), and Operateur_base::tester_contribuer_a_avec().
mp_min_abs_vect()
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTVect< _TYPE_, _SIZE_ >::mp_min_abs_vect (Mp_vect_options opt = VECT_REAL_ITEMS) const inline
mp_norme_vect()
template<typename _TYPE_ , typename _SIZE_ > _TYPE_ TRUSTVect< _TYPE_, _SIZE_ >::mp_norme_vect () const inline
Referenced by Solv_rocALUTION::resoudre_systeme().
ref()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ref (const TRUSTVect< _TYPE_, _SIZE_ > & v) inline virtual
Reimplemented in TRUSTTab< _SIZE_ >, TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< double, int >, TRUSTTab< int >, TRUSTTab< int, int >, and TRUSTTab< trustIdType, int >.
Referenced by Eval_Gravite_VDF_Face::associer(), Op_Grad_PolyMAC_Face::associer(), Op_Diff_VDF_Face_Axi_base::associer(), Op_Dift_VDF_Face_Axi_base::associer(), Op_Grad_VDF_Face_base::associer(), Force_Centrifuge_VDF_Face_Axi::associer_domaines(), Evaluateur_PolyMAC::associer_domaines(), Evaluateur_VDF::associer_domaines(), Evaluateur_PolyMAC::associer_porosite(), Evaluateur_VDF::associer_porosite(), Faces_VDF::calculer_orientation(), Evaluateur_Source_VEF_Face::changer_volumes_entrelaces_Cl(), Evaluateur_Source_Elem::completer(), Evaluateur_Source_Face::completer(), Op_Conv_EF_Stab_PolyMAC_Face::completer(), Op_Diff_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0P1NC_Face::completer(), Eval_Puiss_Th_QC_VEF_Face::completer(), Eval_Puiss_Th_VEF_Face::completer(), Eval_Source_C_VEF_Face::completer(), Evaluateur_Source_VEF_Face::completer(), Eval_Gravite_VDF_Face::Eval_Gravite_VDF_Face(), Evaluateur_PolyMAC::Evaluateur_PolyMAC(), Evaluateur_Source_Elem::Evaluateur_Source_Elem(), Evaluateur_Source_Face::Evaluateur_Source_Face(), Evaluateur_Source_VEF_Face::Evaluateur_Source_VEF_Face(), Evaluateur_VDF::Evaluateur_VDF(), Iterateur_VDF_Face< _TYPE_ >::Iterateur_VDF_Face(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), Solv_GCP::resoudre_(), and MD_Vector_tools::restore_vector_with_md().
echange_espace_virtuel()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel () inline virtual
References MD_Vector_tools::echange_espace_virtuel(), and Process::is_sequential().
Referenced by Champ_base::affecter(), Champ_Inc_base::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Face_VDF::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Champ_Elem_PolyMAC::affecter_(), Champ_Elem_PolyMAC_P0P1NC::affecter_(), Operateur::ajouter(), Op_Grad_EF::ajouter(), Op_Div_PolyMAC::ajouter(), Op_Div_PolyMAC_P0::ajouter(), Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Diff_VEFP1NCP1B_Face::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Op_Grad_P1NC_to_P0::ajouter(), Source_Generique_P0_Elem::ajouter(), Source_WC_Chaleur::ajouter_(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Matrice_Base::ajouter_multTab(), Matrice_Base::ajouter_multvect(), Matrice_Base::ajouter_multvectT(), Op_Conv_EF::ajouter_sous_cond_template(), Solveur_Masse_EF::appliquer_impl(), Masse_PolyMAC_Elem::appliquer_impl(), Masse_PolyMAC_P0_Face::appliquer_impl(), Masse_PolyMAC_P0P1NC_Face::appliquer_impl(), Masse_VDF_Elem::appliquer_impl(), Solveur_Masse_Face_proto::appliquer_impl_proto(), Assembleur_P_VEF::assembler(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie(), Assembleur_P_VEFPreP1B::assembler_mat(), Simpler_Base::assembler_matrice_pression_implicite(), Domaine_Cl_VEF::associer(), Champ_P1NC::cal_rot_ordre1(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Milieu_base::calculate_face_porosity(), Op_Diff_P1NC_barprim::calculer(), Terme_Source_Acceleration::calculer(), Terme_Source_inc_th_VDF_Face::calculer(), Terme_Source_inc_VDF_Face::calculer(), Loi_Etat_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Simple::calculer_correction_en_vitesse(), Loi_Etat_Multi_GP_base::calculer_Cp(), Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Convection_Diffusion_Chaleur_QC::calculer_div_u_ou_div_rhou(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Domaine_EF::calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), Loi_Etat_base::calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_TPPI_QC_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_TPPI_WC_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_mu_wilke(), Loi_Etat_base::calculer_nu(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Navier_Stokes_std::calculer_pression_hydrostatique(), EOS_Tools_VDF::calculer_rho_face_np1(), Loi_Etat_Multi_GP_base::calculer_tab_mu(), Echange_contact_VDF::calculer_Teta_equiv(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Domaine_EF::calculer_volumes_entrelaces(), Domaine_VDF::calculer_volumes_entrelaces(), Domaine_VEF::calculer_volumes_entrelaces(), Domaine_PolyMAC::calculer_volumes_entrelaces(), Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces(), Domaine_EF::calculer_volumes_sommets(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Assembleur_P_VEFPreP1B::changer_base_second_membre(), Solv_Cholesky::Cholesky(), Multigrille_base::coarse_solver(), Navier_Stokes_std::completer(), Loi_paroi_base::completer(), Domaine_Cl_VDF::completer(), Domaine_32_64< _SIZE_ >::construire_elem_virt_pe_num(), Domaine_VF::construire_face_virt_pe_num(), Scatter::construire_md_vector(), Domaine_VEF::construire_ok_arete(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Scatter::construire_structures_paralleles(), Solv_Externe::construit_renum(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Navier_Stokes_std::corriger_derivee_impl(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Assembleur_P_PolyMAC::corriger_vitesses(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Equation_base::derivee_en_temps_conv(), Equation_base::derivee_en_temps_inco(), Convection_Diffusion_Temperature::derivee_en_temps_inco(), Navier_Stokes_std::derivee_en_temps_inco(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Domaine_Poly_base::discretiser(), Domaine_VF::discretiser(), Domaine_VEF::discretiser(), Domaine_VEF::discretiser_arete(), EOS_Tools_VDF::divu_discvit(), DomaineCutter_32_64< _SIZE_ >::ecrire_domaines(), Viscosite_turbulente_Smagorinsky::eddy_viscosity(), Viscosite_turbulente_WALE::eddy_viscosity(), Champ_val_tot_sur_vol_base::evaluer(), Extraire_surface::extraire_surface_without_cleaning(), Discretisation_tools::faces_to_cells(), Discretisation_tools::faces_to_cells(), Leap_frog::faire_un_pas_de_temps_eqn_base(), Pred_Cor::faire_un_pas_de_temps_eqn_base(), Schema_Explicite_Multi_TimeStep_base::faire_un_pas_de_temps_eqn_base(), Convection_Diffusion_Temperature::filtrage_si_appart_ibc(), Source_PDF_EF::filtre_CLD(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Source_PDF_EF::get_champ(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_Generique_Correlation::get_champ(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Ecart_Type::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Moyenne::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Post_Operateur_Eqn::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Solveur_Masse_base::get_masse_divide_by_local_dt(), Solveur_Masse_base::get_masse_dt_local(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), Domaine_VF::init_dist_paroi_globale(), Champ_implementation_P1::init_from_file(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Domaine_PolyMAC::init_m1_3d(), Domaine_VDF::init_virt_e_map(), Domaine_PolyMAC::init_virt_ef_map(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Champ_front_lu::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Champ_front_var::initialiser(), Champ_front_softanalytique::initialiser(), Loi_Etat_base::initialiser_inco_ch(), Champ_Face_PolyMAC::interp_gve(), Test_solveur::interpreter(), Sch_CN_iteratif::iterateTimeStepOnEquation(), Sch_CN_EX_iteratif::iterateTimeStepOnNS(), Sch_CN_EX_iteratif::iterateTimeStepOnOther(), Simple::iterer_eqs(), Piso::iterer_NS(), Simple::iterer_NS(), Simpler::iterer_NS(), EcritureLectureSpecial::lecture_special(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), grad_Champ_Face_PolyMAC_P0::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Chimie::mettre_a_jour(), Champ_front_bruite::mettre_a_jour(), Champ_front_t::mettre_a_jour(), Champ_front_txyz::mettre_a_jour(), Champ_Front_xyz_Tabule::mettre_a_jour(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Champ_Fonc_Tabule_Morceaux_Interp::mettre_a_jour(), Champ_Don_base::mettre_a_jour(), Champ_Fonc_base::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_contact_fictif_VEF::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Interface_base::mettre_a_jour(), Champ_Fonc_Interp::mettre_a_jour(), Fluide_base::mettre_a_jour(), Saturation_base::mettre_a_jour(), Modele_turbulence_scal_Prandtl::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Convection_Diffusion_Temperature::mise_en_place_domaine_fantome(), Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu(), Viscosite_turbulente_base::modifier_mu(), Domaine_VEF::modifier_pour_Cl(), Assembleur_P_VDF_Q4::modifier_secmem(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VDF::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Matrice_Base::multTab(), Matrice_Base::multvect(), Matrice_Base::multvectT(), Discretisation_tools::nodes_to_cells(), Convection_Diffusion_Temperature::penalisation_L2(), SSOR::preconditionner_(), Equation_base::preparer_calcul(), Navier_Stokes_std::preparer_calcul(), Navier_Stokes_std::projeter(), Domaine_Poly_base::pvol_som(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Champ_front_MED::remplir_tab(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), Domaine_EF::reordonner(), Domaine_Poly_base::reordonner(), Domaine_VEF::reordonner(), Precond_local::res_syst_loc_hybride(), Solv_GCP::resoudre_(), Solv_Petsc::resoudre_systeme(), Solv_GCP_NS::resoudre_systeme(), Solv_rocALUTION::resoudre_systeme(), Multigrille_base::resoudre_systeme_template(), Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl(), EOS_Tools_VEF::secmembre_divU_Z(), Champ_Input_Proto::setValueOnTab(), Solv_Gen::solve(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_implementation_P0::trace(), Champ_P1NC_implementation::trace(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Op_Diff_PolyMAC_Elem::update_delta(), Op_Diff_PolyMAC_Elem::update_delta_int(), Eval_Diff_VDF::update_diffusivite(), Eval_Dift_Multiphase_VDF::update_diffusivite_turbulente(), Champ_Face_PolyMAC_P0::update_ve2(), Navier_Stokes_std::uzawa(), TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >::valeur_a_compo(), Champ_Composite::valeur_aux(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), and Domaine_VF::xv_bord().
set_md_vector()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::set_md_vector (const MD_Vector & md_vector) inline virtual
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< _SIZE_ >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< double, int >, TRUSTTab< int >, TRUSTTab< int, int >, and TRUSTTab< trustIdType, int >.
References MD_Vector_base::get_nb_items_reels(), MD_Vector::non_nul(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and MD_Vector_base::validate().
Referenced by Multigrille_base::coarse_solver(), Domaine_VF::discretiser(), Test_solveur::interpreter(), Solv_GCP::prepare_data(), MD_Vector_tools::restore_vector_with_md(), and TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector().
jump()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::jump (Entree & is) inline virtual
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< _SIZE_ >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< double, int >, TRUSTTab< int >, TRUSTTab< int, int >, and TRUSTTab< trustIdType, int >.
References TRUSTVect< _TYPE_, _SIZE_ >::lit().
lit()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::lit (Entree & is, bool resize_and_read = 1) inline virtual
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< _SIZE_ >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< double, int >, TRUSTTab< int >, TRUSTTab< int, int >, and TRUSTTab< trustIdType, int >.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Process::exit(), and Entree::get().
Referenced by TRUSTVect< _TYPE_, _SIZE_ >::jump(), and TRUSTTab< _TYPE_, _SIZE_ >::lit().
ecrit()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ecrit (Sortie & os) const inline virtual
Reimplemented in TRUSTTab< _TYPE_, _SIZE_ >, TRUSTTab< _SIZE_ >, TRUSTTab< _TYPE_ >, TRUSTTab< _TYPE_, int >, TRUSTTab< double, int >, TRUSTTab< int >, TRUSTTab< int, int >, and TRUSTTab< trustIdType, int >.
References TRUSTArray< _TYPE_, _SIZE_ >::printOn().
Referenced by TRUSTTab< _TYPE_, _SIZE_ >::ecrit(), Domaine_Poly_base::ecrit(), and Solv_rocALUTION::resoudre_systeme().
detach_vect()
template<typename _TYPE_ , typename _SIZE_ > virtual void TRUSTVect< _TYPE_, _SIZE_ >::detach_vect () inline virtual
References MD_Vector::detach(), and TRUSTVect< _TYPE_, _SIZE_ >::md_vector_.
ref_data()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ref_data (_TYPE_ * ptr, _SIZE_ size) inline override virtual
See TRUSTArray::ref_data(). Create an array without any parallel structure.
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References TRUSTArray< _TYPE_, _SIZE_ >::ref_data().
Referenced by Matrice_Bloc::ajouter_multvect_(), Matrice_Bloc_Sym::ajouter_multvect_(), Matrice_Bloc::ajouter_multvectT_(), Solv_GCP::prepare_data(), and TRUSTTab< _TYPE_, _SIZE_ >::ref_data().
ref_array()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::ref_array (TRUSTArray< _TYPE_, _SIZE_ > & m, _SIZE_ start = 0, _SIZE_ size = -1) inline override virtual
Make the current array point to the data of another existing array. Ownership of the data is hence shared.
The current array is first detached (see detach_array()), and then attached to the provided data (see attach_array()) Wanring: virtual -> in derived classes this method initializes structures to create a sequential array.
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References TRUSTArray< _TYPE_, _SIZE_ >::ref_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Source_Flux_interfacial_base::ajouter_blocs(), Assembleur_P_PolyMAC::assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Equation_base::dimensionner_matrice(), Equation_base::dimensionner_matrice_sans_mem(), TRUSTTab< _TYPE_, _SIZE_ >::ref_array(), and TRUSTTab< _TYPE_, _SIZE_ >::ref_tab().
get_span() [1/2]
template<typename _TYPE_ , typename _SIZE_ > Span_ TRUSTVect< _TYPE_, _SIZE_ >::get_span () inline override virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References TRUSTVect< _TYPE_, _SIZE_ >::size_reelle().
Referenced by Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Loi_Etat_TPPI_QC_base::calculer_masse_volumique(), Loi_Etat_TPPI_WC_base::calculer_masse_volumique(), Interface_base::mettre_a_jour(), and Saturation_base::mettre_a_jour().
get_span_tot() [1/2]
template<typename _TYPE_ , typename _SIZE_ > Span_ TRUSTVect< _TYPE_, _SIZE_ >::get_span_tot () inline override virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
Referenced by Fluide_reel_base::calculate_fluid_properties(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::mettre_a_jour(), and Saturation_base::mettre_a_jour().
get_span() [2/2]
template<typename _TYPE_ , typename _SIZE_ > const Span_ TRUSTVect< _TYPE_, _SIZE_ >::get_span () const inline override virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References TRUSTVect< _TYPE_, _SIZE_ >::size_reelle().
get_span_tot() [2/2]
template<typename _TYPE_ , typename _SIZE_ > const Span_ TRUSTVect< _TYPE_, _SIZE_ >::get_span_tot () const inline override virtual
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
reset()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::reset () inline override virtual
met l'objet dans l'etat obtenu par le constructeur par defaut.
Reimplemented from TRUSTArray< _TYPE_, _SIZE_ >.
References MD_Vector::detach(), TRUSTVect< _TYPE_, _SIZE_ >::line_size_, TRUSTVect< _TYPE_, _SIZE_ >::md_vector_, TRUSTArray< _TYPE_, _SIZE_ >::reset(), and TRUSTVect< _TYPE_, _SIZE_ >::size_reelle_.
Referenced by Op_Conv_Centre_old_VEF_Face::associer(), Matrice_Grossiere::build_matrix(), Domaine_VEF::calculer_volumes_entrelaces(), Matrix_tools::extend_matrix(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Matrice_Morse::operator=(), Solv_GCP::prepare_data(), TRUSTTab< _TYPE_, _SIZE_ >::reset(), Solv_GCP::resoudre_(), and MD_Vector_tools::restore_vector_with_md().
set_line_size_()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::set_line_size_ (int n) inline protected
Referenced by TRUSTTab< _TYPE_, _SIZE_ >::readOn(), TRUSTTab< _TYPE_, _SIZE_ >::ref_tab(), TRUSTTab< _TYPE_, _SIZE_ >::reshape(), TRUSTTab< _TYPE_, _SIZE_ >::reshape(), TRUSTTab< _TYPE_, _SIZE_ >::reshape(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab(), TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab(), TRUSTTab< _TYPE_, _SIZE_ >::TRUSTTab(), and TRUSTTrav< _TYPE_ >::TRUSTTrav().
resize_vect_()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::resize_vect_ (_SIZE_ n, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline protected
Referenced by TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTTab< _TYPE_, _SIZE_ >::resize_dim0().
copy_()
template<typename _TYPE_ , typename _SIZE_ > void TRUSTVect< _TYPE_, _SIZE_ >::copy_ (const TRUSTVect< _TYPE_, _SIZE_ > & v, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) inline protected
References TRUSTArray< _TYPE_, _SIZE_ >::isDataOnDevice(), TRUSTVect< _TYPE_, _SIZE_ >::md_vector_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array_(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by TRUSTTab< _TYPE_, _SIZE_ >::copy(), and TRUSTTab< _TYPE_, _SIZE_ >::operator=().
Friends And Related Symbol Documentation
TRUSTVect
template<typename _TYPE_ , typename _SIZE_ > template<typename _TYPE2_ , typename _SIZE2_ > friend class TRUSTVect friend
Referenced by TRUSTVect< _TYPE_, _SIZE_ >::duplique().
Member Data Documentation
md_vector_
template<typename _TYPE_ , typename _SIZE_ > MD_Vector TRUSTVect< _TYPE_, _SIZE_ >::md_vector_ protected
Referenced by TRUSTVect< int, int >::ajoute_carre(), TRUSTVect< _TYPE_, _SIZE_ >::copy_(), TRUSTVect< _TYPE_, _SIZE_ >::detach_vect(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), TRUSTVect< _TYPE_, _SIZE_ >::printOn(), TRUSTVect< _TYPE_, _SIZE_ >::readOn(), and TRUSTVect< _TYPE_, _SIZE_ >::reset().
size_reelle_
template<typename _TYPE_ , typename _SIZE_ > _SIZE_ TRUSTVect< _TYPE_, _SIZE_ >::size_reelle_ protected
Referenced by TRUSTVect< int, int >::ajoute_carre(), TRUSTVect< _TYPE_, _SIZE_ >::readOn(), and TRUSTVect< _TYPE_, _SIZE_ >::reset().
line_size_
template<typename _TYPE_ , typename _SIZE_ > int TRUSTVect< _TYPE_, _SIZE_ >::line_size_ protected
Referenced by TRUSTVect< int, int >::ajoute_carre(), TRUSTVect< _TYPE_, _SIZE_ >::from_tid_to_int(), TRUSTVect< _TYPE_, _SIZE_ >::readOn(), TRUSTVect< _TYPE_, _SIZE_ >::ref_as_big(), TRUSTVect< _TYPE_, _SIZE_ >::ref_as_small(), and TRUSTVect< _TYPE_, _SIZE_ >::reset().