CEA TRUST Platform: Assembleur_P_PolyMAC Class Reference
Assembleur_P_PolyMAC Class Reference
#include <Assembleur_P_PolyMAC.h>
Public Member Functions
int assembler_QC (const DoubleTab &, Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
Public Member Functions inherited from Assembleur_base
int set_resoudre_en_u (int flag)
int set_resoudre_increment_pression (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_domaine_dis_base()
void Assembleur_P_PolyMAC::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis) override virtual
Implements Assembleur_base.
associer_domaine_cl_dis_base()
void Assembleur_P_PolyMAC::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis) override virtual
Implements Assembleur_base.
domaine_dis_base()
const Domaine_dis_base & Assembleur_P_PolyMAC::domaine_dis_base () const override virtual
Implements Assembleur_base.
domaine_Cl_dis_base()
const Domaine_Cl_dis_base & Assembleur_P_PolyMAC::domaine_Cl_dis_base () const override virtual
Implements Assembleur_base.
assembler()
int Assembleur_P_PolyMAC::assembler (Matrice & la_matrice) override virtual
Implements Assembleur_base.
References assembler_mat().
Referenced by assembler_QC().
assembler_rho_variable()
int Assembleur_P_PolyMAC::assembler_rho_variable (Matrice & mat, const Champ_Don_base & rho) override virtual
Assemblage de la matrice div(porosite/rho * grad P) Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, .
..) Pour le front-tracking par exemple.
Reimplemented from Assembleur_base.
References Process::abort().
assembler_QC()
int Assembleur_P_PolyMAC::assembler_QC (const DoubleTab & tab_rho, Matrice & matrice) override virtual
Assemble la matrice de pression pour un fluide quasi compressible laplacein(P) est remplace par div(grad(P)/rho).
Parameters
(DoubleTab& tab_rho) mass volumique Valeurs par dPolyMACaut:
Returns
(int) renvoie toujours 1
Exceptions
PolyMACfets de bord:
Reimplemented from Assembleur_base.
References Process::abort(), assembler(), Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Process::je_suis_maitre(), Matrice_Sym::set_est_definie(), Assembleur_base::set_resoudre_en_u(), and Assembleur_base::set_resoudre_increment_pression().
assembler_mat()
int Assembleur_P_PolyMAC::assembler_mat (Matrice & la_matrice, const DoubleVect & diag, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0, and Assembleur_P_PolyMAC_P0P1NC.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Statistiques::begin_count(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Statistiques::end_count(), Champ_Face_base::fcl(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), has_P_ref, Statistiques::last_time(), Process::me(), rec, TRUSTVect< _TYPE_, _SIZE_ >::ref_array(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Matrice_Morse::set_nb_columns(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), TRUSTVect< _TYPE_, _SIZE_ >::size(), stencil_done, tab1, and tab2.
Referenced by assembler().
modifier_secmem()
int Assembleur_P_PolyMAC::modifier_secmem (DoubleTab & secmem) override virtual
Implements Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0P1NC.
References Cond_lim_base::champ_front(), Champ_front_base::derivee_en_temps(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Cond_lim_base::frontiere_dis(), Assembleur_base::get_resoudre_en_u(), Assembleur_base::get_resoudre_increment_pression(), Champ_front_base::instationnaire(), les_coeff_pression, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Debog::verifier().
modifier_solution()
int Assembleur_P_PolyMAC::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0P1NC.
References has_P_ref, and Debog::verifier().
completer()
void Assembleur_P_PolyMAC::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
References stencil_done.
equation()
const Equation_base & Assembleur_P_PolyMAC::equation () const inline
Referenced by Assembleur_P_PolyMAC_P0::assembler_continuite(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), Assembleur_P_PolyMAC_P0::dimensionner_continuite(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Assembleur_P_PolyMAC_P0P1NC::modifier_secmem_pour_incr_p(), and Assembleur_P_PolyMAC_P0P1NC::norme_continuite().
corriger_vitesses()
void Assembleur_P_PolyMAC::corriger_vitesses (const DoubleTab & dP, DoubleTab & dv) const inline override virtual
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_PolyMAC_P0P1NC.
References Matrice_Base::ajouter_multvect(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and rec.
OBS_PTR() [1/3]
Assembleur_P_PolyMAC::OBS_PTR (Equation_base) protected
OBS_PTR() [2/3]
Assembleur_P_PolyMAC::OBS_PTR (Domaine_PolyMAC) protected
OBS_PTR() [3/3]
Assembleur_P_PolyMAC::OBS_PTR (Domaine_Cl_PolyMAC) protected
Member Data Documentation
les_coeff_pression
DoubleTab Assembleur_P_PolyMAC::les_coeff_pression protected
Referenced by modifier_secmem().
has_P_ref
int Assembleur_P_PolyMAC::has_P_ref = 0 protected
Referenced by assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), modifier_solution(), and Assembleur_P_PolyMAC_P0P1NC::modifier_solution().
stencil_done
int Assembleur_P_PolyMAC::stencil_done = 0 protected
Referenced by assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), Assembleur_P_PolyMAC_P0P1NC::assembler_mat(), and completer().
tab1
IntVect Assembleur_P_PolyMAC::tab1 protected
Referenced by assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), and Assembleur_P_PolyMAC_P0P1NC::assembler_mat().
tab2
IntVect Assembleur_P_PolyMAC::tab2 protected
Referenced by assembler_mat(), Assembleur_P_PolyMAC_P0::assembler_mat(), and Assembleur_P_PolyMAC_P0P1NC::assembler_mat().
rec
Matrice_Morse Assembleur_P_PolyMAC::rec protected
Referenced by assembler_mat(), and corriger_vitesses().