CEA TRUST Platform: Op_Diff_negligeable Class Reference
Op_Diff_negligeable Class Reference
Public Member Functions
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const override
void associer_diffusivite (const Champ_base &) override
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const override
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
const Champ_base & diffusivite () const override
void dimensionner (Matrice_Morse &) const override
void mettre_a_jour (double) override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Operateur_negligeable
DoubleTab & ajouter (const DoubleTab &, DoubleTab &) const
DoubleTab & calculer (const DoubleTab &, DoubleTab &) const
void mettre_a_jour (double)
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual int impr (Sortie &os) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Protected Member Functions
void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &, const Champ_Inc_base &) override
Protected Member Functions inherited from Operateur_negligeable
void associer (const Domaine_dis_base &, const Domaine_Cl_dis_base &, const Champ_Inc_base &)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
Lorsqu'un operateur de ce type est utilise dans une equation cela revient a negliger le terme de diffusion. Les methodes de modification et de participation a un calcul de l'operateur sont en fait des appels aux meme methodes de Operateur_negligeable qui ne font rien.
See also
Operateur_Diff_base Operateur_negligeable
Member Function Documentation
ajouter()
DoubleTab & Op_Diff_negligeable::ajouter (const DoubleTab & x, DoubleTab & y) const inline override virtual
Ajoute la contribution de l'operateur a un tableau passe en parametre.
Simple appel a Operateur_negligeable::ajouter(const DoubleTab&,DoubleTab&)
Parameters
(DoubleTab& x) le tableau sur lequel on applique l'operateur
(DoubleTab& y) tableau auquel on ajoute la contribution de l'operateur
Returns
(DoubleTab&) le parametre d'entree y non modifie
Reimplemented from Operateur_base.
References Operateur_negligeable::ajouter().
calculer()
DoubleTab & Op_Diff_negligeable::calculer (const DoubleTab & x, DoubleTab & y) const inline override virtual
Initialise le parametre tableau avec la contribution de l'operateur negligeable: initialise le tableau a ZERO.
Simple appel a Operateur_negligeable::(calculer(const DoubleTab&, DoubleTab&)
Parameters
(DoubleTab& x) le tableau sur lequel on applique l'operateur
(DoubleTab& y) tableau dans lequel stocke la contribution de l'operateur
Returns
(DoubleTab&) le tableau d'entree y mis a zero
Reimplemented from Operateur_base.
References Operateur_negligeable::calculer().
contribuer_a_avec()
void Op_Diff_negligeable::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & amatrice) const inline override virtual
Mise a jour en temps d'un operateur negligeable: NE FAIT RIEN Simple appel a Operateur_negligeable::mettre_a_jour(double)
Parameters
(double temps)
on assemble la matrice.
Reimplemented from Operateur_base.
contribuer_au_second_membre()
void Op_Diff_negligeable::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
modifier_pour_Cl()
void Op_Diff_negligeable::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
dimensionner()
void Op_Diff_negligeable::dimensionner (Matrice_Morse & mat) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
mettre_a_jour()
void Op_Diff_negligeable::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
References Operateur_negligeable::mettre_a_jour().
associer_diffusivite()
void Op_Diff_negligeable::associer_diffusivite (const Champ_base & ch) override virtual
Associe la diffusivite a l'operateur.
Parameters
(Champ_Don_base& ch) le champ representant la diffusivite
Implements Operateur_Diff_base.
diffusivite()
const Champ_base & Op_Diff_negligeable::diffusivite () const override virtual
Renvoie le champ representant la diffusivite.
Returns
(Champ_Don_base&) le champ representant la diffusivite
Implements Operateur_Diff_base.
associer_champ_masse_volumique()
void Op_Diff_negligeable::associer_champ_masse_volumique (const Champ_base & ch) inline override virtual
Methode a appeler dans la preparation du probleme pour demander a l'objet de tenir compte du champ de masse volumique en parametre.
Reimplemented from Support_Champ_Masse_Volumique.
calculer_pour_post()
void Op_Diff_negligeable::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::calculer_dt_stab(), Operateur_base::calculer_pour_post(), and Champ_Proto::valeurs().
get_localisation_pour_post()
Motcle Op_Diff_negligeable::get_localisation_pour_post (const Nom & option) const override virtual
Reimplemented from Operateur_base.
ajouter_flux()
void Op_Diff_negligeable::ajouter_flux (const DoubleTab & inconnue, DoubleTab & contribution) const override virtual
Reimplemented from Operateur_base.
calculer_flux()
void Op_Diff_negligeable::calculer_flux (const DoubleTab & inconnue, DoubleTab & flux) const override virtual
Reimplemented from Operateur_base.
has_interface_blocs()
int Op_Diff_negligeable::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
dimensionner_blocs()
void Op_Diff_negligeable::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const inline override virtual
Reimplemented from Operateur_base.
ajouter_blocs()
void Op_Diff_negligeable::ajouter_blocs (matrices_t matrices, DoubleTab & resu, const tabs_t & semi_impl = { }) const inline override virtual
Reimplemented from Operateur_base.
check_multiphase_compatibility()
void Op_Diff_negligeable::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
OBS_PTR()
Op_Diff_negligeable::OBS_PTR (Champ_base) protected
associer()
void Op_Diff_negligeable::associer (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & ch) inline override protected virtual
Associe divers objets a un operateurs negligeable: NE FAIT RIEN Simple appel a Operateur_negligeable::associer(const Domaine_dis_base&,.
                                                const Domaine_Cl_dis_base&,
                                                const Champ_Inc_base&)
Parameters
(Domaine_dis_base& z)
(Domaine_Cl_dis_base& zcl)
(Champ_Inc_base& ch)
Implements Operateur_base.
References Operateur_negligeable::associer().