CEA TRUST Platform: Hexaedre_axi_32_64< _SIZE_ > Class Template Reference
Hexaedre_axi_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void calculer_centres_gravite (DoubleTab_t &c) const override
void calculer_volumes (DoubleVect_t &vols) const override
int contient (const ArrOfDouble &pos, int_t elem) const override
int contient (const SmallArrOfTID_t &soms, int_t elem) const override
const Nom & nom_lml () const override
Type_Face type_face (int=0) const override
Public Member Functions inherited from Hexaedre_32_64< _SIZE_ >
void calculer_normales (const IntTab_t &faces_sommets, DoubleTab_t &face_normales) const override
int face_sommet (int i, int j) const override
int face_sommet0 (int i) const
int face_sommet1 (int i) const
int face_sommet2 (int i) const
int face_sommet3 (int i) const
int face_sommet4 (int i) const
int face_sommet5 (int i) const
int nb_faces (int=0) const override
int nb_som_face (int=0) const override
Public Member Functions inherited from Elem_geom_base_32_64< _SIZE_ >
void creer_faces_elem (Faces_t &, int_t) const
virtual void creer_faces_elem (Faces_t &, int_t, Type_Face) const
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
virtual int nb_type_face () const
virtual int num_face (int face, Type_Face &type) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Hexaedre_axi_32_64< _SIZE_ >
le cas d'un maillage en coordonnees cylindriques Les methodes de la classe Hexaedre dont Hexaedre_axi derive sont surchargees pour effectuer les calculs en coordonnees cylindrique.
See also
Hexaedre Elem_geom_base Elem_geom
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Hexaedre_axi_32_64< _SIZE_ >::int_t = _SIZE_
IntTab_t
template<typename _SIZE_ > using Hexaedre_axi_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Hexaedre_axi_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Hexaedre_axi_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Hexaedre_axi_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Hexaedre_axi_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Member Function Documentation
nom_lml()
template<typename _SIZE_ > const Nom & Hexaedre_axi_32_64< _SIZE_ >::nom_lml override virtual
Renvoie le nom LML d'un triangle = "VOXEL8".
Returns
(Nom&) toujours egal a "VOXEL8"
Reimplemented from Hexaedre_32_64< _SIZE_ >.
contient() [1/2]
template<typename _SIZE_ > int Hexaedre_axi_32_64< _SIZE_ >::contient (const ArrOfDouble & pos, int_t element) const override virtual
NE FAIT RIEN: A CODER,renvoie toujours 0.
Renvoie 1 si l'element "elemen" du domaine associe a l'element geometrique contient le point de coordonnees specifiees par le parametre "pos". Renvoie 0 sinon.
Parameters
(DoubleVect& pos) coordonnees du point que l'on cherche a localiser
(int element) le numero de l'element du domaine dans lequel on cherche le point.
Returns
(int) 1 si le point de coordonnees specifiees appartient a l'element "element" 0 sinon
Reimplemented from Hexaedre_32_64< _SIZE_ >.
References Domaine_32_64< _SIZE_ >::coord(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_32_64< _SIZE_ >::sommet_elem().
contient() [2/2]
template<typename _SIZE_ > int Hexaedre_axi_32_64< _SIZE_ >::contient (const SmallArrOfTID_t & som, int_t element) const override virtual
Renvoie 1 si les sommets specifies par le parametre "pos" sont les sommets de l'element "element" du domaine associe a.
l'element geometrique.
Parameters
(IntVect& pos) les numeros des sommets a comparer avec ceux de l'elements "element"
(int element) le numero de l'element du domaine dont on veut comparer les sommets
Returns
(int) 1 si les sommets passes en parametre sont ceux de l'element specifie, 0 sinon
Reimplemented from Hexaedre_32_64< _SIZE_ >.
References Domaine_32_64< _SIZE_ >::sommet_elem().
type_face()
template<typename _SIZE_ > Type_Face Hexaedre_axi_32_64< _SIZE_ >::type_face (int i = 0) const inline override virtual
Renvoie le i-ieme type de face.
Un Hexaedre (Axi) n'a qu'un seul type de face.
Parameters
(int i) le rang du type de face a renvoyer
Returns
(Type_Face) un type de face
Reimplemented from Hexaedre_32_64< _SIZE_ >.
calculer_centres_gravite()
template<typename _SIZE_ > void Hexaedre_axi_32_64< _SIZE_ >::calculer_centres_gravite (DoubleTab_t & xp) const override virtual
Calcule les centres de gravites de tous les elements du domaine associe a l'element goemetrique.
Parameters
(DoubleTab& xp) le tableau contenant les coordonnees des centres de gravite
Reimplemented from Elem_geom_base_32_64< _SIZE_ >.
References Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
calculer_volumes()
template<typename _SIZE_ > void Hexaedre_axi_32_64< _SIZE_ >::calculer_volumes (DoubleVect_t & volumes) const override virtual
Calcule les volumes des elements du domaine associe.
Parameters
(DoubleVect& volumes) le vecteur contenant les valeurs des des volumes des elements du domaine
Reimplemented from Hexaedre_32_64< _SIZE_ >.
References Domaine_32_64< _SIZE_ >::coord(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Domaine_32_64< _SIZE_ >::sommet_elem().