CEA TRUST Platform: Solv_Petsc Class Reference
Solv_Petsc Class Reference
#include <Solv_Petsc.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Solv_Petsc()
Solv_Petsc::Solv_Petsc () inline
References instance, and read_matrix_.
~Solv_Petsc()
Solv_Petsc::~Solv_Petsc () inline override
References instance, and reset().
Member Function Documentation
solveur_direct()
int Solv_Petsc::solveur_direct () const inline override virtual
Implements SolveurSys_base.
resoudre_systeme() [1/2]
int Solv_Petsc::resoudre_systeme (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
References Matrice_Base::ajouter_multvect(), amgx_, Statistiques::begin_count(), Solv_Externe::construit_matrice_morse_intermediaire(), Solv_Externe::construit_renum(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Statistiques::end_count(), Process::exit(), SolveurSys_base::fixer_nouvelle_matrice(), Statistiques::get_time_now(), gpu_, TRUSTArray< _TYPE_, _SIZE_ >::isDataOnDevice(), Process::je_suis_maitre(), SolveurSys_base::limpr(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Solv_Externe::matrice_symetrique_, Process::mp_max(), nb_it_previous_, Solv_Externe::nb_rows_, Solv_Externe::nb_rows_tot_, SolveurSys_base::nouvelle_matrice(), read_matrix_, rebuild_matrix_, Solv_Externe::secmem_sz_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Solv_Externe::Update_solution(), and verbose.
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_Petsc::resoudre_systeme (const Matrice_Base & M, const DoubleVect & A, DoubleVect & B, int niter_max) inline override virtual
Reimplemented from SolveurSys_base.
References resoudre_systeme().
create_solver()
void Solv_Petsc::create_solver (Entree & entree)
References allow_realloc_, amgx_, clean_matrix_, config(), PE_Groups::current_group(), option::defined, Objet_U::dimension, Objet_U::disable_TU, Entree_Fichier_base::eof(), Process::exit(), SolveurSys_base::fixer_limpr(), SolveurSys_base::get_chaine_lue(), Entree_Fichier_base::get_ifstream(), PE_Groups::get_nb_groups(), gpu_, ignore_new_nonzero_, instance, Process::is_parallel(), Process::is_sequential(), Process::je_suis_maitre(), SolveurSys_base::lecture(), SolveurSys_base::limpr(), Solv_Externe::matrice_symetrique_, option::name, Objet_U::nom_du_cas(), Objet_U::nommer(), Process::nproc(), numero_solveur, read_matrix_, rebuild_matrix_, reduce_ram_, reorder_matrix_, reuse_preconditioner_nb_it_max_, SolveurSys_base::save_matrice_, Motcles::search(), SolveurSys_base::set_reuse_preconditioner(), Nom::suffix(), option_string::value(), option_double::value(), and verbose.
reset()
void Solv_Petsc::reset () inline
Referenced by ~Solv_Petsc().
read_matrix()
bool Solv_Petsc::read_matrix () const inline
References read_matrix_.
config()
const Nom Solv_Petsc::config () protected
References amgx_, Process::exit(), Objet_U::nom_du_cas(), and Nom::prefix().
Referenced by create_solver().
Member Data Documentation
instance
int Solv_Petsc::instance =-1 static
Referenced by create_solver(), Solv_Petsc(), and ~Solv_Petsc().
numero_solveur
int Solv_Petsc::numero_solveur =0 static
Referenced by create_solver().
solveur_direct_
int Solv_Petsc::solveur_direct_ = no protected
read_matrix_
int Solv_Petsc::read_matrix_ protected
Referenced by create_solver(), read_matrix(), resoudre_systeme(), and Solv_Petsc().
gpu_
bool Solv_Petsc::gpu_ = false protected
Referenced by create_solver(), resoudre_systeme(), and Solv_Petsc_GPU::Solv_Petsc_GPU().
amgx_
bool Solv_Petsc::amgx_ = false protected
Referenced by config(), create_solver(), resoudre_systeme(), and Solv_AMGX::Solv_AMGX().
amgx_initialized_
bool Solv_Petsc::amgx_initialized_ = false protected
ignore_new_nonzero_
bool Solv_Petsc::ignore_new_nonzero_ = false protected
Referenced by create_solver().
rebuild_matrix_
bool Solv_Petsc::rebuild_matrix_ = false protected
Referenced by create_solver(), and resoudre_systeme().
allow_realloc_
bool Solv_Petsc::allow_realloc_ = true protected
Referenced by create_solver().
clean_matrix_
bool Solv_Petsc::clean_matrix_ = true protected
Referenced by create_solver().
reduce_ram_
bool Solv_Petsc::reduce_ram_ = false protected
Referenced by create_solver().
verbose
bool Solv_Petsc::verbose = false protected
Referenced by create_solver(), and resoudre_systeme().
reorder_matrix_
bool Solv_Petsc::reorder_matrix_ = false protected
Referenced by create_solver().
nb_it_previous_
int Solv_Petsc::nb_it_previous_ =-1 protected
Referenced by resoudre_systeme().
reuse_preconditioner_nb_it_max_
int Solv_Petsc::reuse_preconditioner_nb_it_max_ =-1 protected
Referenced by create_solver().