CEA TRUST Platform: Champ_base Class Reference
Champ_base Class Reference abstract
Public Member Functions
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Ses membres sont les attributs et les methodes communs
a toutes les classes qui representent des champs.
Champ_base derive de Champ_Proto, afin d'avoir une interface conforme
a tous les champs, et d'heriter des operations courantes sur les
Champs.
Un champ possede un nom, une unite et des valeurs.
See also
Champ_Proto Ch_Inc_base Ch_Don_base, Classe abstraite, Methodes abstraites:, Champ_base& affecter_(const Champ_base&), Champ_base& affecter_compo(const Champ_base&, int compo)
Constructor & Destructor Documentation
Champ_base()
Champ_base::Champ_base ()
Constructeur par defaut d'un Champ_base.
Mets le champ au temps 0, specifie une unite vide, donne le nom "anonyme" au champ et lui donne une nature scalaire.
References changer_temps(), Field_base::fixer_nature_du_champ(), Field_base::fixer_unite(), Field_base::nb_compo_, and Field_base::nommer().
Member Function Documentation
nb_valeurs_nodales()
virtual int Champ_base::nb_valeurs_nodales () const inline virtual
Reimplemented in Champ_Face_PolyMAC_P0P1NC, Champ_Face_PolyMAC, Champ_Elem_PolyMAC_P0P1NC, Champ_Parametrique, Champ_Inc_base, and Champ_Don_base.
References Process::exit().
temps()
double Champ_base::temps () const
Renvoie le temps du champ.
Returns
(double) le temps du champ
References temps_.
Referenced by Modele_turbulence_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Champ_Elem_PolyMAC_P0::calc_grad(), Navier_Stokes_std::calculer_la_pression_en_pa(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), VDF_discretisation::courant_maille(), Fluide_base::creer_e_int(), Fluide_base::creer_temperature_multiphase(), VDF_discretisation::critere_Q(), EF_discretisation::critere_Q(), VEF_discretisation::critere_Q(), Champ_P1iP1B_implementation::filtrage(), Equation_base::get_champ(), Pb_MED::get_champ(), Convection_Diffusion_Temperature::get_champ(), Convection_Diffusion_Temperature_base::get_champ(), Navier_Stokes_std::get_champ(), Conduction::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_refChamp::get_time(), EF_discretisation::grad_T(), VEF_discretisation::grad_T(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), EF_discretisation::h_conv(), VEF_discretisation::h_conv(), Champ_Fonc_Tabule_P0_EF::initialiser(), Champ_Parametrique::initialiser(), Champ_Fonc_Tabule_Elem_PolyMAC::initialiser(), Ch_front_var_instationnaire_dep::initialiser(), Champ_Fonc_Interp::initialiser(), Ecrire_Champ_MED::interpreter(), Champ_Tabule_Temps::me_calculer(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Champ_Inc_base::mettre_a_jour(), Champ_Parametrique::mettre_a_jour(), Champ_Fonc_Elem_PolyMAC_P0_rot::mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour(), Champ_Fonc_Elem_PolyMAC_P0_TC::mettre_a_jour(), grad_Champ_Face_PolyMAC_P0::mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour_integrale(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::residu(), VEF_discretisation::residu(), PolyMAC_P0_discretisation::residu(), PolyMAC_P0P1NC_discretisation::residu(), VDF_discretisation::reynolds_maille(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), VDF_discretisation::t_paroi(), VEF_discretisation::t_paroi(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), Champ_Generique_Correlation::temps(), Champ_Generique_Ecart_Type::temps(), Champ_Generique_Moyenne::temps(), Op_Correlation::temps(), Op_Ecart_type::temps(), Op_Moyenne::temps(), Champ_Inc_base::valeurs(), Champ_Parametrique::valeurs(), EF_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), and VEF_discretisation::y_plus().
changer_temps()
double Champ_base::changer_temps (const double t) virtual
Fixe le temps auquel se situe le champ.
Parameters
(double& t) le nouveau temps auquel se situe le champ
Returns
(double) le nouveau temps auquel se situe le champ
Reimplemented in Champ_Inc_base, and Champ_Input_P0_Composite.
References temps_.
Referenced by Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Champ_base(), Champ_Input_P0_Composite::changer_temps(), Op_Correlation::completer(), Op_Ecart_type::completer(), VDF_discretisation::courant_maille(), Champ_Fonc_MED::creer(), EF_discretisation::creer_champ_vorticite(), PolyMAC_P0_discretisation::creer_champ_vorticite(), VDF_discretisation::creer_champ_vorticite(), VEF_discretisation::creer_champ_vorticite(), VDF_discretisation::critere_Q(), VEF_discretisation::critere_Q(), EF_discretisation::distance_paroi(), PolyMAC_discretisation::distance_paroi(), VEF_discretisation::distance_paroi(), VDF_discretisation::grad_u(), VEF_discretisation::grad_u(), PolyMAC_discretisation::grad_u(), PolyMAC_P0_discretisation::grad_u(), VEF_discretisation::h_conv(), Champ_Don_base::mettre_a_jour(), Champ_Fonc_base::mettre_a_jour(), Champ_Ostwald_VDF::mettre_a_jour(), Champ_Ostwald_VEF::mettre_a_jour(), Rotationnel_Champ_P1_EF::mettre_a_jour(), Rotationnel_Champ_Q1_EF::mettre_a_jour(), Y_plus_Champ_Q1::mettre_a_jour(), Champ_Uniforme_inst::mettre_a_jour(), Champ_Uniforme_Morceaux_inst::mettre_a_jour(), Integrale_tps_produit_champs::mettre_a_jour(), grad_U_Champ_Face_PolyMAC::mettre_a_jour(), Fluide_Dilatable_base::mettre_a_jour(), Correlation_Vec_Sca_VDF::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Critere_Q_Champ_Face::mettre_a_jour(), grad_U_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Rotationnel_Champ_Face::mettre_a_jour(), T_paroi_Champ_P0_VDF::mettre_a_jour(), Taux_cisaillement_P0_VDF::mettre_a_jour(), Y_plus_Champ_Face::mettre_a_jour(), Correlation_Vec_Sca_VEF::mettre_a_jour(), Critere_Q_Champ_P1NC::mettre_a_jour(), grad_T_Champ_P1NC::mettre_a_jour(), grad_U_Champ_P1NC::mettre_a_jour(), h_conv_Champ_P1NC::mettre_a_jour(), Rotationnel_Champ_P1NC::mettre_a_jour(), Rotationnel_Champ_Q1NC::mettre_a_jour(), T_paroi_Champ_P1NC::mettre_a_jour(), Taux_cisaillement_P0_VEF::mettre_a_jour(), Y_plus_Champ_P1NC::mettre_a_jour(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), VEF_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::reynolds_maille(), VDF_discretisation::t_paroi(), VEF_discretisation::t_paroi(), PolyMAC_P0_discretisation::taux_cisaillement(), VDF_discretisation::taux_cisaillement(), VEF_discretisation::taux_cisaillement(), EF_discretisation::vorticite(), VDF_discretisation::vorticite(), VEF_discretisation::vorticite(), VDF_discretisation::y_plus(), EF_discretisation::y_plus(), and VEF_discretisation::y_plus().
fixer_nb_valeurs_nodales()
int Champ_base::fixer_nb_valeurs_nodales (int n) virtual
Reimplemented in Champ_P1_isoP1Bulle, Champ_Fonc_Q1NC, Champ_Fonc_P1NC, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Face_VDF, Champ_Inc_base, Champ_P1NC, Champ_Ostwald, Champ_Parametrique, Champ_Fonc_base, Champ_Don_base, Champ_Inc_Q1_base, Champ_Inc_P1_base, Champ_Fonc_Q1_base, Champ_Fonc_P1_base, Champ_Q1NC, grad_Champ_Face_PolyMAC_P0, Champ_Fonc_Face_PolyMAC, Champ_Face_PolyMAC_P0P1NC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC, Champ_Elem_PolyMAC_P0P1NC, Champ_Elem_PolyMAC, Champ_Inc_P0_base, Champ_Fonc_P0_base, and Champ_Elem_DG.
References Process::exit(), and Objet_U::que_suis_je().
associer_domaine_dis_base()
void Champ_base::associer_domaine_dis_base (const Domaine_dis_base & domaine_dis) virtual
Reimplemented in Champ_Input_P0_Composite, Champ_Fonc_Tabule, Champ_Fonc_Q1_MED, Champ_Fonc_P1_MED, Champ_Fonc_P0_MED, Champ_Fonc_MED, Champ_Inc_base, Champ_Fonc_base, and Champ_Elem_DG.
References Process::exit(), Field_base::le_nom(), and Objet_U::que_suis_je().
domaine_dis_base()
const Domaine_dis_base & Champ_base::domaine_dis_base () const virtual
Reimplemented in Champ_Fonc_Q1_MED, Champ_Fonc_P1_MED, Champ_Fonc_P0_MED, Champ_Fonc_MED, Champ_Inc_base, Champ_Fonc_base, Champ_Input_P0_Composite, and Champ_Fonc_Tabule.
References Process::exit(), Field_base::le_nom(), and Objet_U::que_suis_je().
Referenced by Champ_implementation_P0::affecter_(), Fluide_base::calculer_e_int(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Champ_Generique_Transformation::completer(), Champ_Fonc_base::domaine_dis_base(), EcritureLectureSpecial::ecriture_special(), Discretisation_tools::faces_to_cells(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_Generique_refChamp::get_ref_connectivity(), EcritureLectureSpecial::lecture_special(), Discretisation_tools::nodes_to_cells(), valeur_aux_bords(), valeur_aux_centres_de_gravite(), and valeur_aux_faces().
a_un_domaine_dis_base()
virtual int Champ_base::a_un_domaine_dis_base () const inline virtual
Reimplemented in Champ_Inc_base, and Champ_Fonc_base.
Referenced by Champ_implementation_P0::affecter_(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), and Champ_Generique_Transformation::completer().
mettre_a_jour()
void Champ_base::mettre_a_jour (double) virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented in Y_plus_Champ_P1NC, Taux_cisaillement_P0_VEF, T_paroi_Champ_P1NC, Rotationnel_Champ_Q1NC, Rotationnel_Champ_P1NC, h_conv_Champ_P1NC, grad_U_Champ_P1NC, grad_T_Champ_P1NC, Critere_Q_Champ_P1NC, Correlation_Vec_Sca_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_P1NC, Champ_Fonc_P1_VEF, Champ_Fonc_P1_isoP1Bulle, Y_plus_Champ_Face, Taux_cisaillement_P0_VDF, T_paroi_Champ_P0_VDF, Rotationnel_Champ_Face, Reynolds_maille_Champ_Face, grad_U_Champ_Face, Critere_Q_Champ_Face, Courant_maille_Champ_Face, Correlation_Vec_Sca_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Face_VDF, grad_U_Champ_Face_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Fonc_Tabule_Elem_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_reprise, Champ_Fonc_Q1_MED, Champ_Fonc_P1_MED, Champ_Fonc_P0_MED, Champ_Fonc_MED, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, Champ_Fonc_P0_base, Champ_Fonc_Interp, Champ_Uniforme_Morceaux_inst, Champ_Uniforme_inst, Champ_Input_P0_Composite, Champ_input_P0, Y_plus_Champ_Q1, Rotationnel_Champ_Q1_EF, Rotationnel_Champ_P1_EF, Champ_Fonc_Tabule_P0_EF, Champ_Fonc_Q1_EF, Champ_Fonc_P1_EF, Champ_Fonc_Tabule, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Elem_PolyMAC_P0, Champ_Composite, Champ_P1NC, Champ_Ostwald_VEF, Champ_Ostwald_VDF, Champ_Face_VDF, Champ_Ostwald, Champ_Fonc_MED_Tabule, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, Champ_Parametrique, Champ_Inc_base, Champ_Fonc_base, Champ_Don_base, Champ_Fonc_Tabule_Morceaux_Interp, and Champ_Fonc_Tabule_Morceaux.
abortTimeStep()
void Champ_base::abortTimeStep () virtual
Reimplemented in Champ_P1NC.
Referenced by Equation_base::abortTimeStep().
resetTime()
virtual void Champ_base::resetTime (double time) pure virtual
Implemented in Champ_Parametrique, Champ_Inc_base, and Champ_Don_base.
affecter_()
virtual Champ_base& Champ_base::affecter_ (const Champ_base &) pure virtual
Implemented in Champ_Fonc_Elem_PolyMAC, Champ_Elem_PolyMAC_P0P1NC, Champ_Elem_PolyMAC_P0, Champ_Elem_PolyMAC, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, Champ_Parametrique, Champ_Uniforme_Morceaux, Champ_Uniforme, Champ_Fonc_P1_DG, Champ_Fonc_Elem_DG, Champ_Elem_DG, Champ_P1NC, Champ_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Face_VDF, Champ_Ostwald, Champ_Fonc_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC, Champ_Inc_base, Champ_Fonc_base, Champ_Don_base, Champ_Inc_P0_base, Champ_Fonc_P0_base, Ch_input_uniforme, and Champ_Fonc_Tabule.
Referenced by affecter(), Fluide_Weakly_Compressible::completer(), and Loi_Etat_rhoT_GP_QC::initialiser_rho().
affecter()
Champ_base & Champ_base::affecter (const Champ_base & ch)
Affecter un champ dans un autre.
Rebvoie le resultat de l'affectation.
Parameters
(Champ_base& ch) partie droite de l'affectation
Returns
(Champ_base&) le resultat de l'affectation (*this)
References affecter_(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and Champ_Proto::valeurs().
Referenced by Champ_Parametrique::affecter_(), Echange_couplage_thermique::initialiser(), Equation_base::lire_cond_init(), and Navier_Stokes_std::lire_cond_init().
affecter_erreur()
void Champ_base::affecter_erreur ()
References Process::exit(), and Objet_U::que_suis_je().
Referenced by TRUSTChamp_Don_generique< _TYPE_ >::affecter().
affecter_compo()
virtual Champ_base& Champ_base::affecter_compo (const Champ_base & , int compo) pure virtual
Implemented in Champ_Parametrique, Champ_Don_base, Champ_Inc_base, and Champ_Fonc_base.
imprime()
virtual int Champ_base::imprime (Sortie & , int) const pure virtual
Implemented in Champ_Fonc_Face_VDF, Champ_P0_VDF, Champ_Parametrique, Champ_P1NC, Champ_P1_VEF, Champ_P0_VEF, Champ_Fonc_Q1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VDF, Champ_Fonc_P0_VDF, Champ_Face_VDF, Champ_Som_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Elem_PolyMAC, Champ_Inc_base, Champ_Don_base, Champ_Fonc_P0_base, Champ_Q1_EF, Champ_P1_EF, Champ_P0_EF, Champ_Fonc_Q1_EF, Champ_Fonc_P1_EF, and Champ_Elem_DG.
trace()
DoubleTab & Champ_base::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const virtual
Calcule la trace d'un champ sur une frontiere au temps tps.
WEC : La frontiere passee en parametre doit faire partie du domaine sur lequel s'appuie le champ Le resultat est calcule sur cette frontiere et la taille du DoubleTab x correspond au nombre de faces de la frontiere. x peut avoir un espace virtuel, la fonction trace apelle echange_espace_virtuel.
Cas particulier (malheureusement) du Champ_P0_VDF : Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Parameters
(Frontiere_dis_base&) frontiere discretisee sur laquelle on veut calculer la trace du champ au temps tps
(DoubleTab& x , double tps) les valeurs du champ sur la frontiere au temps tps
Returns
(DoubleTab&) les valeurs du champ sur la frontiere au temps tps
Reimplemented in Champ_Elem_PolyMAC, Champ_Q1NC, Champ_P1NC, Champ_P1_isoP1Bulle, Champ_Fonc_Q1NC, Champ_Fonc_P1NC, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Face_VDF, Champ_Face_PolyMAC_P0P1NC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC, Champ_Inc_base, Champ_Inc_P1_base, Champ_Inc_P0_base, and Champ_Fonc_P0_base.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Champ_Generique_Extraction::get_champ(), and Champ_Front_Fonction::mettre_a_jour().
valeur_a()
DoubleVect & Champ_base::valeur_a (const DoubleVect & pos, DoubleVect & les_valeurs) const virtual
Calcule les "valeurs" du champ au point de coordonnees "pos".
Dans cette classe de base, l'implementation appelle valeur_aux(const DoubleTab &, DoubleTab &)
Parameters
(DoubleVect&) les coordonnees du point ou evaluer le champ
(DoubleVect& valeurs) En entree: doit avoir la bonne taille (nb_comp), en sortie contient les composantes du champ.
Returns
(reference a "valeurs")
Reimplemented in Champ_som_lu, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, Champ_Fonc_MED, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, Champ_Inc_base, champ_init_canal_sinal, TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, and TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >.
References TRUSTVect< _TYPE_, _SIZE_ >::size(), and valeur_aux().
Referenced by valeur_a_compo(), Champ_Fonc_MED::valeur_a_elem(), and valeur_a_sommet().
valeur_a_elem()
DoubleVect & Champ_base::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented in TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, Champ_Fonc_MED, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, Champ_Q1NC, Champ_P1NC, Champ_P1_isoP1Bulle, Champ_Fonc_Q1NC, Champ_Fonc_P1NC, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Face_VDF, Champ_Fonc_Face_PolyMAC, Champ_Face_PolyMAC, Champ_Inc_Q1_base, Champ_Inc_P1_base, Champ_Inc_P0_base, Champ_Fonc_Q1_base, Champ_Fonc_P1_base, Champ_Fonc_P0_base, and Champ_Fonc_Tabule.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Champ_Face_base::get_elem_vector(), Champ_Inc_base::valeur_a(), Champ_Fonc_MED::valeur_a(), and Champ_Fonc_Tabule::valeur_a_elem().
valeur_a_compo()
double Champ_base::valeur_a_compo (const DoubleVect & pos, int compo) const virtual
Calcule la valeur ponctuelle de la composante "compo" du champ au point de coordonnees pos.
Dans la classe de base, l'implementation appelle valeur_a(const DoubleVect &, DoubleVect &)
Parameters
(DoubleVect&) les coordonnees du point de calcul
(int) l'index de la composante du champ a calculer
Returns
(double)
Reimplemented in TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, Champ_som_lu_VEF, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, and TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >.
References Field_base::nb_comp(), and valeur_a().
Referenced by Perte_Charge_PolyMAC::ajouter(), Perte_Charge_VEF::ajouter(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Perte_Charge_PolyMAC::contribuer_a_avec(), and Perte_Charge_VEF::contribuer_a_avec().
valeur_a_elem_compo()
double Champ_base::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented in Champ_Fonc_Face_PolyMAC, Champ_Face_PolyMAC, Champ_Inc_Q1_base, Champ_Inc_P1_base, Champ_Inc_P0_base, Champ_Fonc_Q1_base, Champ_Fonc_P1_base, Champ_Fonc_P0_base, Champ_som_lu_VEF, Champ_Q1NC, Champ_P1NC, Champ_P1_isoP1Bulle, Champ_Fonc_Q1NC, Champ_Fonc_P1NC, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Face_VDF, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, champ_init_canal_sinal, Champ_Fonc_Tabule, TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, and TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Champ_Fonc_Tabule::valeur_a_elem_compo().
valeur_aux_centres_de_gravite()
DoubleTab & Champ_base::valeur_aux_centres_de_gravite (const Domaine & dom, DoubleTab & valeurs) const virtual
Cette methode, generique mais lente (calcul des centres de gravite, remplissage les_poly, utilisation des fonctions de forme dans le Champ discretise) peut etre surchargee par le champ dicretise pour une implementation beaucoup plus rapide.
Reimplemented in Champ_P1NC, Champ_Fonc_P1NC, and Champ_Fonc_P0_base.
References Domaine_32_64< _SIZE_ >::calculer_centres_gravite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_dis_base(), Objet_U::que_suis_je(), valeur_aux_elems(), and Domaine_VF::xp().
Referenced by Champ_implementation_P0::affecter_(), calculer_valeurs_elem_post(), and Champ_Generique_Transformation::get_champ().
valeur_aux()
DoubleTab & Champ_base::valeur_aux (const DoubleTab & positions, DoubleTab & les_valeurs) const virtual
Provoque une erreur ! Doit etre surchargee par les classes derivees.
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented in TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, Champ_Parametrique, Champ_Inc_base, Tayl_Green, Init_par_partie, champ_init_canal_sinal, Champ_Elem_DG, TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >, Champ_Composite, and Champ_Fonc_base.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Champ_Fonc_base::affecter_(), Champ_Inc_base::affecter_(), Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Ostwald::affecter_(), Champ_Face_VDF::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Champ_P1NC::affecter_(), Champ_Elem_DG::affecter_(), Champ_Fonc_Elem_DG::affecter_(), Champ_Fonc_P1_DG::affecter_(), Champ_Elem_PolyMAC::affecter_(), Champ_Elem_PolyMAC_P0P1NC::affecter_(), Champ_Fonc_Elem_PolyMAC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), calculer_valeurs_elem_post(), calculer_valeurs_som_post(), Champ_Generique_Transformation::get_champ(), Domaine_EF_axi::remplir_tableau_origine(), valeur_a(), Champ_Parametrique::valeur_aux(), valeur_aux_bords(), valeur_aux_compo(), valeur_aux_faces(), Champ_implementation::valeur_aux_sommets(), and Ecrire_fichier_xyz_valeur::write_fields().
valeur_aux_compo()
DoubleVect & Champ_base::valeur_aux_compo (const DoubleTab & pos, DoubleVect & les_valeurs, int compo) const virtual
Idem que valeur_aux(const DoubleTab &, DoubleTab &), mais calcule uniquement la composante compo du champ.
Dans l'implementation de champ_base, on appelle valeur_aux(const DoubleTab &, DoubleTab &)
Parameters
(pos) le tableau des coordonnees des points de calcul (on ne traite pas l'espace virtuel du tableau)
(les_valeurs) tableau destination des valeurs a calculer. Le tableau valeurs doit avoir la bonne taille en entree, soit les_valeurs.size() == pos.dimension(0)
(compo) l'index de la composante du champ a calculer
Returns
(reference au tableau les_valeurs)
Reimplemented in Champ_Fonc_reprise, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, Champ_Inc_base, Tayl_Green, champ_init_canal_sinal, Champ_Fonc_Face_VDF, TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, and TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Field_base::nb_comp(), and valeur_aux().
Referenced by Champ_Fonc_Face_VDF::affecter_(), Champ_Fonc_base::affecter_compo(), Champ_Inc_base::affecter_compo(), calculer_valeurs_elem_compo_post(), calculer_valeurs_som_compo_post(), and Champ_implementation::valeur_aux_sommets_compo().
valeur_aux_elems()
DoubleTab & Champ_base::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented in Champ_Fonc_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC, Champ_Inc_Q1_base, Champ_Inc_P1_base, Champ_Inc_P0_base, Champ_Fonc_Q1_base, Champ_Fonc_P1_base, Champ_Fonc_P0_base, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, Champ_som_lu_VEF, Champ_P1_isoP1Bulle, Champ_Fonc_MED, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, Champ_Parametrique, Champ_som_lu, Champ_Fonc_P1_DG, Champ_Elem_DG, Champ_Q1NC, Champ_P1NC, Champ_Fonc_Q1NC, Champ_Fonc_P1NC, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Face_VDF, Champ_Fonc_reprise, Champ_Fonc_Tabule, TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, and TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Champ_Ostwald::affecter_(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Champ_Face_base::get_elem_vector_field(), Probleme_base::getOutputPointValues(), Champ_Fonc_base::valeur_aux(), Champ_Inc_base::valeur_aux(), valeur_aux_centres_de_gravite(), Champ_Fonc_Tabule::valeur_aux_elems(), Champ_Fonc_reprise::valeur_aux_elems(), Champ_Parametrique::valeur_aux_elems(), Champ_Fonc_MED::valeur_aux_elems(), and valeur_aux_sommets().
valeur_aux_elems_passe()
virtual DoubleTab& Champ_base::valeur_aux_elems_passe (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) const inline virtual
Reimplemented in Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC, and Champ_Face_VDF.
References Process::exit().
Referenced by Champ_Face_base::get_elem_vector_field().
valeur_aux_elems_compo()
DoubleVect & Champ_base::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented in Champ_Fonc_Face_PolyMAC, Champ_Face_PolyMAC_P0, Champ_Face_PolyMAC, Champ_Inc_Q1_base, Champ_Inc_P1_base, Champ_Inc_P0_base, Champ_Fonc_Q1_base, Champ_Fonc_P1_base, Champ_Fonc_P0_base, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, Champ_som_lu_VEF, Champ_P1_isoP1Bulle, Champ_Fonc_MED, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, Champ_som_lu, Champ_Q1NC, Champ_P1NC, Champ_Fonc_Q1NC, Champ_Fonc_P1NC, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Face_VDF, Champ_Fonc_reprise, TRUSTChamp_Divers_generique< _TYPE_ >, TRUSTChamp_Divers_generique< Champ_Divers_Type::CANAL >, TRUSTChamp_Divers_generique< Champ_Divers_Type::INUTILE >, and TRUSTChamp_Divers_generique< Champ_Divers_Type::UNIFORME >.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Champ_Fonc_base::affecter_compo(), Champ_Inc_base::affecter_compo(), calculer_valeurs_elem_compo_post(), Probleme_base::getOutputPointValues(), Champ_Inc_base::valeur_aux_compo(), Champ_Fonc_reprise::valeur_aux_elems_compo(), Champ_Fonc_MED::valeur_aux_elems_compo(), and valeur_aux_sommets_compo().
valeur_aux_elems_smooth()
DoubleTab & Champ_base::valeur_aux_elems_smooth (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) virtual
Reimplemented in Champ_P1NC, and Champ_Fonc_P1NC.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Sonde::fill_local_values().
valeur_aux_elems_compo_smooth()
DoubleVect & Champ_base::valeur_aux_elems_compo_smooth (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & valeurs, int ncomp) virtual
Reimplemented in Champ_P1NC, and Champ_Fonc_P1NC.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Sonde::fill_local_values().
valeur_a_sommet()
DoubleVect & Champ_base::valeur_a_sommet (int sommet, const Domaine & dom, DoubleVect & val) const virtual
Mise a jour en temps.
NE FAIT RIEN (dans la classe de base)
Parameters
(double) temps de mise a jour
References Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, and valeur_a().
valeur_a_sommet_compo()
double Champ_base::valeur_a_sommet_compo (int sommet, int le_poly, int compo) const virtual
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
Reimplemented in Champ_Q1NC, and Champ_P1NC.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), and Op_Conv_VEF_Face::remplir_fluent().
valeur_aux_sommets()
DoubleTab & Champ_base::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented in Champ_Fonc_Face_PolyMAC, Champ_Inc_Q1_base, Champ_Inc_P1_base, Champ_Inc_P0_base, Champ_Fonc_Q1_base, Champ_Fonc_P1_base, Champ_Fonc_P0_base, Champ_Q1NC, Champ_P1NC, Champ_Fonc_Q1NC, Champ_Fonc_P1NC, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Face_VDF, Champ_P1_isoP1Bulle, Champ_Fonc_reprise, Champ_Fonc_Tabule, and Champ_Fonc_MED.
References Domaine_32_64< _SIZE_ >::chercher_elements(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and valeur_aux_elems().
Referenced by calculer_valeurs_som_post(), Champ_Fonc_MED::valeur_aux_sommets(), Champ_Fonc_Tabule::valeur_aux_sommets(), and Champ_Fonc_reprise::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_base::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented in Champ_Fonc_Face_PolyMAC, Champ_Inc_Q1_base, Champ_Inc_P1_base, Champ_Inc_P0_base, Champ_Fonc_Q1_base, Champ_Fonc_P1_base, Champ_Fonc_P0_base, Champ_Q1NC, Champ_P1NC, Champ_Fonc_Q1NC, Champ_Fonc_P1NC, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Face_VDF, Champ_P1_isoP1Bulle, Champ_Fonc_reprise, Champ_Fonc_Tabule, and Champ_Fonc_MED.
References Domaine_32_64< _SIZE_ >::chercher_elements(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and valeur_aux_elems_compo().
Referenced by calculer_valeurs_som_compo_post(), Champ_Fonc_MED::valeur_aux_sommets_compo(), Champ_Fonc_Tabule::valeur_aux_sommets_compo(), and Champ_Fonc_reprise::valeur_aux_sommets_compo().
eval_elem()
DoubleTab & Champ_base::eval_elem (DoubleTab & valeurs) const virtual
Reimplemented in Champ_Elem_DG.
References Process::exit().
Referenced by Champ_Generique_Transformation::get_champ().
valeur_aux_faces()
DoubleTab & Champ_base::valeur_aux_faces (DoubleTab & result) const virtual
renvoie la valeur du champ aux faces
Reimplemented in Champ_Elem_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Face_PolyMAC_P0P1NC, and Champ_Face_PolyMAC.
References domaine_dis_base(), and valeur_aux().
Referenced by Champ_Generique_Transformation::get_champ(), and valeur_aux_faces_post().
valeur_aux_bords()
DoubleTab Champ_base::valeur_aux_bords () const virtual
renvoie la valeur du champ aux faces de bord
Reimplemented in Champ_Inc_base, and Champ_Fonc_P1_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), domaine_dis_base(), valeur_aux(), and Champ_Proto::valeurs().
Referenced by Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Equation_base::calculer_champ_conserve(), Fluide_base::calculer_e_int(), and Champ_front_debit_massique::update_coeff().
valeur_aux_faces_post()
virtual DoubleTab& Champ_base::valeur_aux_faces_post (DoubleTab & result) const inline virtual
Reimplemented in Champ_Fonc_Face_VDF, and Champ_Face_VDF.
References valeur_aux_faces().
Referenced by Postraitement::postprocess_field_values().
calculer_valeurs_som_post()
void Champ_base::calculer_valeurs_som_post (DoubleTab & valeurs, int nbsom, Nom & nom_post, const Domaine & dom) const
References Objet_U::axi, Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), MorEqn::equation(), Process::exit(), Frontiere_32_64< _SIZE_ >::faces(), Frontiere_dis_base::frontiere(), Equation_base::inconnue(), Field_base::le_nom(), Domaine_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), MorEqn::mon_equation_non_nul(), Field_base::nb_compo_, Domaine_Cl_dis_base::nb_cond_lim(), Faces_32_64< _SIZE_ >::nb_faces(), Faces_32_64< _SIZE_ >::nb_faces_tot(), Domaine_32_64< _SIZE_ >::nb_som(), Faces_32_64< _SIZE_ >::nb_som_faces(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Faces_32_64< _SIZE_ >::sommet(), Dirichlet::val_imp(), valeur_aux(), and valeur_aux_sommets().
calculer_valeurs_som_compo_post()
void Champ_base::calculer_valeurs_som_compo_post (DoubleTab & valeurs, int ncomp, int nbsom, Nom & nom_post, const Domaine & dom, int appliquer_cl = 0) const
References Domaine_32_64< _SIZE_ >::coord_sommets(), Equation_base::domaine_Cl_dis(), MorEqn::equation(), Frontiere_32_64< _SIZE_ >::faces(), Frontiere_dis_base::frontiere(), Equation_base::inconnue(), Field_base::le_nom(), Domaine_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), Faces_32_64< _SIZE_ >::nb_faces_tot(), Domaine_32_64< _SIZE_ >::nb_som(), Faces_32_64< _SIZE_ >::nb_som_faces(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Faces_32_64< _SIZE_ >::sommet(), Dirichlet::val_imp(), Dirichlet_homogene::val_imp(), valeur_aux_compo(), and valeur_aux_sommets_compo().
calculer_valeurs_elem_post()
void Champ_base::calculer_valeurs_elem_post (DoubleTab & valeurs, int nbelem, Nom & nom_post, const Domaine & dom) const
References Objet_U::axi, Domaine_32_64< _SIZE_ >::calculer_centres_gravite(), Objet_U::dimension, Domaine_base::le_nom(), Field_base::nb_compo_, Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), valeur_aux(), and valeur_aux_centres_de_gravite().
Referenced by Champ_Generique_Interpolation::get_champ_with_calculer_champ_post().
calculer_valeurs_elem_compo_post()
void Champ_base::calculer_valeurs_elem_compo_post (DoubleTab & valeurs, int ncomp, int nbelem, Nom & nom_post, const Domaine & dom) const
References Domaine_32_64< _SIZE_ >::calculer_centres_gravite(), Objet_U::dimension, Domaine_base::le_nom(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), valeur_aux_compo(), valeur_aux_elems_compo(), and Domaine_VF::xp().
Referenced by Champ_Generique_Interpolation::get_champ_with_calculer_champ_post().
corriger_unite_nom_compo()
void Champ_base::corriger_unite_nom_compo ()
cette methode va fixer les unites et le nom des compos elle n'est pas const en realite !!!
References Objet_U::axi, Field_base::fixer_noms_compo(), Field_base::le_nom(), Field_base::nb_compo_, Field_base::nom_compo(), and Field_base::unite_.
Referenced by Pb_MED::creer_champ(), Ecrire_Champ_MED::interpreter(), and Champ_Generique_refChamp::lire_motcle_non_standard().
completer_post_champ()
int Champ_base::completer_post_champ (const Domaine & dom, const int axi, const Nom & loc_post, const Nom & le_nom_champ_post, Format_Post_base & format) const virtual
References Format_Post_base::completer_post(), Field_base::nature_du_champ(), Field_base::nb_comp(), and Field_base::noms_compo().
Referenced by Operateur_Statistique_tps_base::completer_post_statistiques().
completer()
void Champ_base::completer (const Domaine_Cl_dis_base & zcl) virtual
Reimplemented in Champ_P1_isoP1Bulle, and Champ_Fonc_P1_isoP1Bulle.
Member Data Documentation
temps_
double Champ_base::temps_ protected
Referenced by Champ_Inc_base::avancer(), changer_temps(), Champ_Inc_base::changer_temps(), Champ_Ostwald_VDF::me_calculer(), Champ_Ostwald_VEF::me_calculer(), h_conv_Champ_P1NC::me_calculer(), Champ_Inc_base::mettre_a_jour(), Champ_Inc_base::reculer(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), temps(), and Champ_P1_isoP1Bulle::trace().