CEA TRUST Platform: Op_Conv_VDF< OP_TYPE > Class Template Reference
Op_Conv_VDF< OP_TYPE > Class Template Reference
#include <Op_Conv_VDF.h>
Member Function Documentation
dimensionner_elem()
template<typename OP_TYPE > void Op_Conv_VDF< OP_TYPE >::dimensionner_elem (Matrice_Morse & matrice) const inline protected
References Op_VDF_Elem::dimensionner().
Referenced by Op_Conv_VDF< OP_TYPE >::dimensionner_blocs_impl().
modifier_pour_Cl_elem()
template<typename OP_TYPE > void Op_Conv_VDF< OP_TYPE >::modifier_pour_Cl_elem (Matrice_Morse & matrice, DoubleTab & secmem) const inline protected
References Op_VDF_Elem::modifier_pour_Cl().
dimensionner_face()
template<typename OP_TYPE > void Op_Conv_VDF< OP_TYPE >::dimensionner_face (Matrice_Morse & matrice) const inline protected
References Op_VDF_Face::dimensionner().
Referenced by Op_Conv_VDF< OP_TYPE >::dimensionner_blocs_impl().
modifier_pour_Cl_face()
template<typename OP_TYPE > void Op_Conv_VDF< OP_TYPE >::modifier_pour_Cl_face (Matrice_Morse & matrice, DoubleTab & secmem) const inline protected
References Op_VDF_Face::modifier_pour_Cl().
associer_impl() [1/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_CONV_ELEM, void > Op_Conv_VDF< OP_TYPE >::associer_impl (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_transporte) inline protected
associer_impl() [2/2]
template<typename OP_TYPE > template<Type_Operateur _TYPE_, typename EVAL_TYPE > std::enable_if_t< _TYPE_==Type_Operateur::Op_CONV_FACE, void > Op_Conv_VDF< OP_TYPE >::associer_impl (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_vit) inline protected
dimensionner_blocs_impl()
template<typename OP_TYPE > template<Type_Operateur _TYPE_> void Op_Conv_VDF< OP_TYPE >::dimensionner_blocs_impl (matrices_t mats) const inline protected
References Op_Conv_VDF< OP_TYPE >::dimensionner_elem(), Op_Conv_VDF< OP_TYPE >::dimensionner_face(), and Matrice_Morse::nb_colonnes().
associer_vitesse_impl()
template<typename OP_TYPE > template<typename EVAL_TYPE > void Op_Conv_VDF< OP_TYPE >::associer_vitesse_impl (const Champ_base & ch_vit) inline protected
vitesse_impl() [1/2]
template<typename OP_TYPE > template<typename EVAL_TYPE > const Champ_base & Op_Conv_VDF< OP_TYPE >::vitesse_impl () const inline protected
vitesse_impl() [2/2]
template<typename OP_TYPE > template<typename EVAL_TYPE > Champ_base & Op_Conv_VDF< OP_TYPE >::vitesse_impl () inline protected