CEA TRUST Platform: Viscosite_turbulente_base Class Reference
Viscosite_turbulente_base Class Reference abstract
#include <Viscosite_turbulente_base.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Methodes implementees :
eddy_viscosity(nu_t) -> remplit le DoubleTab "nu_t" tel que <u'_i u'_j> = - nu_t (dui / dx_j + duj / dx_i + (partie trace))
reynolds_stress(R_ij) -> remplit R_ij = < u'_i u'_j> (pour utilisation par un modele GGDH dans une autre equation) format : R_ij(e, n, i, j) avec e l'indice d'element, n l'indice de phase, (i, j) les composantes
k_over_eps(k_sur_eps) -> renvoie la quantite "k / epsilon" (utilisee par exemple dans le GGDH) Dans les deux cas, les tableaux doivent etre dimensionnes par la fonction appelante.
Member Function Documentation
modifier_mu()
void Viscosite_turbulente_base::modifier_mu (DoubleTab & nu_t) const virtual
References Process::abort(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), eddy_viscosity(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and TRUSTTab< _TYPE_, _SIZE_ >::nb_dim().
eddy_viscosity()
virtual void Viscosite_turbulente_base::eddy_viscosity (DoubleTab & nu_t) const pure virtual
Implemented in Viscosite_turbulente_l_melange, Viscosite_turbulente_multiple, Viscosite_turbulente_Smagorinsky, and Viscosite_turbulente_WALE.
Referenced by Source_Flux_interfacial_base::ajouter_blocs(), Transport_turbulent_Prandtl::modifier_mu(), Transport_turbulent_SGDH::modifier_mu(), and modifier_mu().
reynolds_stress()
virtual void Viscosite_turbulente_base::reynolds_stress (DoubleTab & R_ij) const pure virtual
Implemented in Viscosite_turbulente_l_melange, Viscosite_turbulente_LES_base, and Viscosite_turbulente_multiple.
Referenced by Transport_turbulent_GGDH::modifier_mu().
k_over_eps()
virtual void Viscosite_turbulente_base::k_over_eps (DoubleTab & k_sur_eps) const pure virtual
Implemented in Viscosite_turbulente_l_melange, Viscosite_turbulente_LES_base, and Viscosite_turbulente_multiple.
Referenced by Transport_turbulent_GGDH::modifier_mu().
eps()
virtual void Viscosite_turbulente_base::eps (DoubleTab & eps) const pure virtual
Implemented in Viscosite_turbulente_l_melange, Viscosite_turbulente_LES_base, and Viscosite_turbulente_multiple.
limiteur()
double Viscosite_turbulente_base::limiteur () const inline
Referenced by Transport_turbulent_GGDH::modifier_mu().
gradu_required()
virtual int Viscosite_turbulente_base::gradu_required () const inline virtual
Reimplemented in Viscosite_turbulente_l_melange, Viscosite_turbulente_multiple, and Viscosite_turbulente_WALE.