CEA TRUST Platform: Eval_Diff_VDF_Elem_aniso Class Reference
Eval_Diff_VDF_Elem_aniso Class Reference
#include <Eval_Diff_VDF_leaves.h>
Detailed Description
Le champ diffuse est scalaire (Champ_P0_VDF).
See also
Eval_Diff_VDF
Member Function Documentation
associer()
void Eval_Diff_VDF_Elem_aniso::associer (const Champ_base & diffu) inline override virtual
Reimplemented from Eval_Diff_VDF.
References Eval_Diff_VDF::associer(), Objet_U::dimension, Process::exit(), Field_base::le_nom(), and Field_base::nb_comp().
Member Data Documentation
IS_ANISO
constexpr bool Eval_Diff_VDF_Elem_aniso::IS_ANISO = true static constexpr