CEA TRUST Platform: Modele_turbulence_hyd_LES_VDF_base Class Reference
Modele_turbulence_hyd_LES_VDF_base Class Reference
#include <Modele_turbulence_hyd_LES_VDF_base.h>
Additional Inherited Members
Public Member Functions inherited from Modele_turbulence_hyd_LES_base
void imprimer (Sortie &is) const override
int preparer_calcul () override
int reprendre (Entree &is) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
maille en VDF
.SECTION voir aussi Modele_turbulence_hyd_LES_base
Member Function Documentation
calculer_longueurs_caracteristiques()
void Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques () override virtual
Implements Modele_turbulence_hyd_LES_base.
References Domaine_VDF::dim_elem(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Process::exit(), Modele_turbulence_hyd_LES_base::l_, Modele_turbulence_hyd_LES_base::methode_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VDF::orientation(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().