CEA TRUST Platform: Iterateur_Source_Face< _TYPE_ > Class Template Reference
Iterateur_Source_Face< _TYPE_ > Class Template Reference
#include <Iterateur_Source_Face.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Iterateur_Source_Face() [1/2]
template<class _TYPE_ > Iterateur_Source_Face< _TYPE_ >::Iterateur_Source_Face () inline
Iterateur_Source_Face() [2/2]
template<class _TYPE_ > Iterateur_Source_Face< _TYPE_ >::Iterateur_Source_Face (const Iterateur_Source_Face< _TYPE_ > & iter) inline
Member Function Documentation
ajouter()
template<class _TYPE_ > DoubleTab & Iterateur_Source_Face< _TYPE_ >::ajouter (DoubleTab & resu) const override virtual
Implements Iterateur_Source_base.
References Milieu_base::equation(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and Champ_Proto::valeurs().
completer_()
template<class _TYPE_ > void Iterateur_Source_Face< _TYPE_ >::completer_ () inline override virtual
Implements Iterateur_Source_base.
References Iterateur_Source_Face< _TYPE_ >::nb_faces, and Iterateur_Source_Face< _TYPE_ >::premiere_face_interne.
evaluateur()
template<class _TYPE_ > Evaluateur_Source & Iterateur_Source_Face< _TYPE_ >::evaluateur () inline override virtual
Implements Iterateur_Source_base.
References Iterateur_Source_Face< _TYPE_ >::evaluateur_source_face.
ajouter_faces_internes()
template<class _TYPE_ > template<typename Type_Double > DoubleTab & Iterateur_Source_Face< _TYPE_ >::ajouter_faces_internes (const int ncomp, DoubleTab & resu) const protected
ajouter_faces_bords()
template<class _TYPE_ > template<typename Type_Double > DoubleTab & Iterateur_Source_Face< _TYPE_ >::ajouter_faces_bords (const int ncomp, DoubleTab & resu) const protected
References Front_VF::nb_faces(), and Front_VF::num_premiere_face().
faces_doubles()
template<class _TYPE_ > const int & Iterateur_Source_Face< _TYPE_ >::faces_doubles (int num_face) const inline protected
Member Data Documentation
evaluateur_source_face
template<class _TYPE_ > _TYPE_ Iterateur_Source_Face< _TYPE_ >::evaluateur_source_face protected
Referenced by Iterateur_Source_Face< _TYPE_ >::evaluateur().
nb_faces
template<class _TYPE_ > int Iterateur_Source_Face< _TYPE_ >::nb_faces protected
Referenced by Iterateur_Source_Face< _TYPE_ >::completer_().
premiere_face_interne
template<class _TYPE_ > int Iterateur_Source_Face< _TYPE_ >::premiere_face_interne protected
Referenced by Iterateur_Source_Face< _TYPE_ >::completer_().
coef
template<class _TYPE_ > DoubleTab Iterateur_Source_Face< _TYPE_ >::coef mutable protected