CEA TRUST Platform: Pb_Hydraulique_Concentration Class Reference
Pb_Hydraulique_Concentration Class Reference
#include <Pb_Hydraulique_Concentration.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
const Equation_base & equation (int) const override
Equation_base & equation (int) override
int nombre_d_equations () const override
int verifier () override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
virtual void finir ()
double futureTime () const override
void getInputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_U
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual bool run ()
virtual bool runUntil (double time)
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
d'un ou plusieurs constituants:
Equations de Navier_Stokes en regime laminaire pour un fluide incompressible
Equations de convection-diffusion en regime laminaire En fait si on transporte plusieurs constituants on utilisera une seule equation de convection-diffusion avec une inconnue vectorielle. En general, on couple les 2 equations par l'intermediaire du terme source des forces de volume de Navier_Stokes dans lequel on prend en compte de petites variations de la masse volumique en fonction du ou des constituants
See also
Pb_Fluide_base
Member Function Documentation
nombre_d_equations()
int Pb_Hydraulique_Concentration::nombre_d_equations () const override virtual
Renvoie le nombre d'equation, Renvoie 2 car il y a 2 equations a un probleme.
hydraulique avec transport:
l'equation de Navier Stokes
une equation de convection-diffusion (eventuellement vectorielle)
Returns
(int) le nombre d'equation
Implements Probleme_base.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration >.
equation() [1/2]
const Equation_base & Pb_Hydraulique_Concentration::equation (int i) const override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0 Renvoie l'equation de convection-diffusion de type.
Convection_Diffusion_Concentration si i=1 (l'equation de convection diffusion peut-etre vectorielle) (version const)
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation correspondante a l'index
Implements Probleme_base.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration >.
References eq_concentration, eq_hydraulique, and Process::exit().
equation() [2/2]
Equation_base & Pb_Hydraulique_Concentration::equation (int i) override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0 Renvoie l'equation de convection-diffusion de type.
Convection_Diffusion_Concentration si i=1 (l'equation de convection diffusion peut-etre vectorielle)
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation correspondante a l'index
Implements Probleme_base.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration >.
References eq_concentration, eq_hydraulique, and Process::exit().
associer_milieu_base()
void Pb_Hydraulique_Concentration::associer_milieu_base (const Milieu_base & mil) override virtual
Associe un milieu au probleme, Si le milieu est de type.
 - Fluide_Incompressible, il sera associe a l'equation de l'hydraulique
 - Constituant, il sera associe a l'equation de convection-diffusion
Un autre type de milieu provoque une erreur
Parameters
(Milieu_base& mil) le milieu physique a associer au probleme
Exceptions
mauvais type de milieu physique
Reimplemented from Probleme_base.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Hydraulique_Concentration >.
References Convection_Diffusion_Concentration::associer_milieu_base(), Navier_Stokes_std::associer_milieu_base(), eq_concentration, eq_hydraulique, Process::exit(), and Objet_U::que_suis_je().
verifier()
int Pb_Hydraulique_Concentration::verifier () override virtual
Teste la compatibilite des equations de convection-diffusion et de l'hydraulique.
Le test se fait sur les conditions aux limites discretisees de chaque equation. Appel la fonction de librairie hors classe: tester_compatibilite_hydr_concentration(const Domaine_Cl_dis_base&,const Domaine_Cl_dis_base&)
Returns
(int) code de retour propage
Reimplemented from Probleme_base.
References Equation_base::domaine_Cl_dis(), eq_concentration, and eq_hydraulique.
Member Data Documentation
eq_hydraulique
Navier_Stokes_std Pb_Hydraulique_Concentration::eq_hydraulique protected
Referenced by associer_milieu_base(), equation(), equation(), and verifier().
eq_concentration
Convection_Diffusion_Concentration Pb_Hydraulique_Concentration::eq_concentration protected
Referenced by associer_milieu_base(), equation(), equation(), and verifier().