CEA TRUST Platform: Domaine_dis_cache Class Reference
Domaine_dis_cache Class Reference
Public Member Functions
Domaine_dis_base & build_or_get (const Nom &type, const Domaine &dom)
Additional Inherited Members
Static Public Member Functions inherited from TClearable
static void Clear_all ()
static void Register_clearable (TClearable *c)
Detailed Description
This is a singleton class.
Member Function Documentation
Get_instance()
Domaine_dis_cache & Domaine_dis_cache::Get_instance () static
Get the unique instance of the cache.
References TClearable::Register_clearable().
Referenced by Build_or_get(), Build_or_get_poly_post(), and Clear().
Clear()
void Domaine_dis_cache::Clear () static
Clear the content of the cache. Useful to exit nicely making sure everything is deallocated.
References Get_instance().
Build_or_get()
Domaine_dis_base & Domaine_dis_cache::Build_or_get (const Nom & type, const Domaine & dom) static
References build_or_get(), and Get_instance().
Referenced by Discretisation_base::discretiser(), Champ_Generique_Extraction::discretiser_domaine(), Champ_Generique_Interpolation::discretiser_domaine(), and Postraiter_domaine::ecrire().
Build_or_get_poly_post()
Domaine_dis_base & Domaine_dis_cache::Build_or_get_poly_post (const Nom & type, const Domaine & dom) static
References build_or_get_poly_post(), and Get_instance().
build_or_get()
Domaine_dis_base & Domaine_dis_cache::build_or_get (const Nom & type, const Domaine & dom)
Get a discretized domain from the cache, building it and recording it if not there yet.
Process is as follows: type might start with "NO_FACE_" indicating that we just need a simplified discretisation. (see Domaine_dis_base::discretiser_no_face()) Otherwise we want the full discretisation. The full discr can be used in place of a "NO_FACE", but not the inverse. In the cache, we save both the full and the NO_FACE if the full was requested. Otherwise just the NO_FACE is saved. The cache key also uses the current interpretor address to handle weird cases like: domaine dom probleme pb Discretize pb dis { Domaine dom Probleme pb Discretize pb dis Lire pb { ... } } Lire pb { ... }
References Nom::getString(), Interprete_bloc::interprete_courant(), Domaine_base::le_nom(), and Nom::suffix().
Referenced by Build_or_get(), and build_or_get_poly_post().
build_or_get_poly_post()
Domaine_dis_base & Domaine_dis_cache::build_or_get_poly_post (const Nom & type, const Domaine & dom)
References build_or_get(), Nom::getString(), and Domaine_base::le_nom().
Referenced by Build_or_get_poly_post().
clear()
void Domaine_dis_cache::clear () inline override virtual
Implements TClearable.