CEA TRUST Platform: Champ_implementation Class Reference
Champ_implementation Class Reference abstract
#include <Champ_implementation.h>
Constructor & Destructor Documentation
~Champ_implementation()
virtual Champ_implementation::~Champ_implementation () inline virtual
Member Function Documentation
valeur_a_elem()
virtual DoubleVect & Champ_implementation::valeur_a_elem (const DoubleVect & position, DoubleVect & result, int poly) const pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Q4_implementation, Champ_Face_VDF, Champ_Face_VDF_implementation, Champ_Fonc_Face_VDF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_P1NC, Champ_P1NC_implementation, Champ_Q1NC, and Champ_Q1NC_implementation.
Referenced by Champ_Fonc_P1_base::valeur_a_elem(), Champ_Fonc_Q1_base::valeur_a_elem(), Champ_Inc_P1_base::valeur_a_elem(), and Champ_Inc_Q1_base::valeur_a_elem().
valeur_a_elem_compo()
virtual double Champ_implementation::valeur_a_elem_compo (const DoubleVect & position, int poly, int ncomp) const pure virtual
Implemented in Champ_Q4_implementation, Champ_Face_VDF, Champ_Face_VDF_implementation, Champ_Fonc_Face_VDF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_P1NC, Champ_P1NC_implementation, Champ_Q1NC, Champ_Q1NC_implementation, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Referenced by Champ_Fonc_P1_base::valeur_a_elem_compo(), Champ_Fonc_Q1_base::valeur_a_elem_compo(), Champ_Inc_P1_base::valeur_a_elem_compo(), and Champ_Inc_Q1_base::valeur_a_elem_compo().
valeur_aux_elems()
virtual DoubleTab & Champ_implementation::valeur_aux_elems (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const pure virtual
Implemented in Champ_Face_VDF, Champ_Fonc_Face_VDF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Q4_implementation, Champ_Face_VDF_implementation, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_P1NC_implementation, Champ_Q1NC_implementation, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Referenced by Champ_Fonc_P1_base::valeur_aux_elems(), Champ_Fonc_Q1_base::valeur_aux_elems(), Champ_Inc_P1_base::valeur_aux_elems(), and Champ_Inc_Q1_base::valeur_aux_elems().
valeur_aux_elems_compo()
virtual DoubleVect & Champ_implementation::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & polys, DoubleVect & result, int ncomp) const pure virtual
Implemented in Champ_Face_VDF, Champ_Fonc_Face_VDF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Q4_implementation, Champ_Face_VDF_implementation, Champ_P1_isoP1Bulle, Champ_P1iP1B_implementation, Champ_P1NC_implementation, Champ_Q1NC_implementation, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
Referenced by Champ_Fonc_P1_base::valeur_aux_elems_compo(), Champ_Fonc_Q1_base::valeur_aux_elems_compo(), Champ_Inc_P1_base::valeur_aux_elems_compo(), and Champ_Inc_Q1_base::valeur_aux_elems_compo().
remplir_coord_noeuds()
virtual DoubleTab & Champ_implementation::remplir_coord_noeuds (DoubleTab & positions) const pure virtual
Implemented in Champ_P0_VDF, Champ_P1_isoP1Bulle, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Q4_implementation, Champ_Face_VDF, Champ_Face_VDF_implementation, Champ_Fonc_Face_VDF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1iP1B_implementation, Champ_P1NC, Champ_P1NC_implementation, Champ_Q1NC, and Champ_Q1NC_implementation.
Referenced by Champ_Fonc_P1_base::remplir_coord_noeuds(), Champ_Fonc_Q1_base::remplir_coord_noeuds(), Champ_Inc_P1_base::remplir_coord_noeuds(), and Champ_Inc_Q1_base::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
virtual int Champ_implementation::remplir_coord_noeuds_et_polys (DoubleTab & positions, IntVect & polys) const pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_implementation_P0, Champ_implementation_sommet, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Q4_implementation, Champ_Face_VDF, Champ_Face_VDF_implementation, Champ_Fonc_Face_VDF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1iP1B_implementation, Champ_P1NC, Champ_P1NC_implementation, Champ_Q1NC, and Champ_Q1NC_implementation.
Referenced by Champ_Fonc_P1_base::remplir_coord_noeuds_et_polys(), Champ_Fonc_Q1_base::remplir_coord_noeuds_et_polys(), Champ_Inc_P1_base::remplir_coord_noeuds_et_polys(), and Champ_Inc_Q1_base::remplir_coord_noeuds_et_polys().
valeur_aux_sommets()
DoubleTab & Champ_implementation::valeur_aux_sommets (const Domaine & domain, DoubleTab & result) const virtual
Reimplemented in Champ_Q4_implementation, Champ_Face_VDF_implementation, Champ_P1iP1B_implementation, Champ_Q1NC_implementation, Champ_implementation_divers, Champ_P1NC_implementation, Champ_P1_isoP1Bulle, Champ_Face_VDF, Champ_Fonc_Face_VDF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
References Domaine_32_64< _SIZE_ >::coord_sommets(), get_domaine_geom(), le_champ(), Champ_base::valeur_aux(), and valeur_aux_sommets_impl().
Referenced by Champ_Fonc_P0_base::valeur_aux_sommets(), Champ_Fonc_P1_base::valeur_aux_sommets(), Champ_Fonc_Q1_base::valeur_aux_sommets(), Champ_Inc_P0_base::valeur_aux_sommets(), Champ_Inc_P1_base::valeur_aux_sommets(), and Champ_Inc_Q1_base::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_implementation::valeur_aux_sommets_compo (const Domaine & domain, DoubleVect & result, int ncomp) const virtual
Reimplemented in Champ_Q4_implementation, Champ_Face_VDF_implementation, Champ_P1iP1B_implementation, Champ_Q1NC_implementation, Champ_implementation_divers, Champ_P1NC_implementation, Champ_P1_isoP1Bulle, Champ_Face_VDF, Champ_Fonc_Face_VDF, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, Champ_P1NC, Champ_Q1NC, Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, and Champ_Inc_Q1_base.
References Domaine_32_64< _SIZE_ >::coord_sommets(), get_domaine_geom(), le_champ(), Champ_base::valeur_aux_compo(), and valeur_aux_sommets_compo_impl().
Referenced by Champ_Fonc_P0_base::valeur_aux_sommets_compo(), Champ_Fonc_P1_base::valeur_aux_sommets_compo(), Champ_Fonc_Q1_base::valeur_aux_sommets_compo(), Champ_Inc_P0_base::valeur_aux_sommets_compo(), Champ_Inc_P1_base::valeur_aux_sommets_compo(), and Champ_Inc_Q1_base::valeur_aux_sommets_compo().
get_domaine_dis()
const Domaine_VF & Champ_implementation::get_domaine_dis () const protected
References Champ_Fonc_base::domaine_dis_base(), Champ_Inc_base::domaine_dis_base(), Process::exit(), get_domaine_dis(), le_champ(), and Objet_U::que_suis_je().
Referenced by get_domaine_dis(), get_domaine_geom(), Champ_Face_VDF_implementation::remplir_coord_noeuds(), Champ_implementation_sommet::valeur_aux_bords(), Champ_Q1NC_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets_compo(), and Champ_implementation_P1::value_interpolation().
get_domaine_geom()
const Domaine & Champ_implementation::get_domaine_geom () const protected
References Domaine_dis_base::domaine(), and get_domaine_dis().
Referenced by Champ_implementation_P0::imprime_P0(), Champ_Q4_implementation::imprime_Q4(), Champ_implementation_P0::remplir_coord_noeuds(), Champ_implementation_sommet::remplir_coord_noeuds(), Champ_Q4_implementation::remplir_coord_noeuds(), Champ_implementation_P0::remplir_coord_noeuds_et_polys(), Champ_implementation_sommet::remplir_coord_noeuds_et_polys(), Champ_Q4_implementation::remplir_coord_noeuds_et_polys(), Champ_Q1NC_implementation::transforme_coord2D(), Champ_Q1NC_implementation::transforme_coord3D(), Champ_Q4_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_Q1NC_implementation::valeur_a_sommet_compo(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_Q4_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), valeur_aux_sommets(), valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_P1::value_interpolation(), and Champ_implementation_Q1::value_interpolation().
le_champ() [1/2]
virtual Champ_base & Champ_implementation::le_champ () protected pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, and Champ_implementation_P1.
Referenced by Champ_implementation_P0::affecter_(), Champ_Q1NC_implementation::calcule_valeur_a_elem_compo(), Champ_P1NC_implementation::filtrer_H1(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), get_domaine_dis(), Champ_Face_VDF_implementation::imprime_Face(), Champ_implementation_P0::imprime_P0(), Champ_P1NC_implementation::imprime_P1NC(), Champ_Q4_implementation::imprime_Q4(), Champ_P1NC_implementation::nb_colonnes(), Champ_P1NC_implementation::nb_colonnes_tot(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_sommet::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem(), Champ_Face_VDF_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q1NC_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_Face_VDF_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_implementation_sommet::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_implementation_sommet::valeur_aux_bords(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_Q4_implementation::valeur_aux_elems(), Champ_Face_VDF_implementation::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_implementation_sommet::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_Q1NC_implementation::valeur_aux_elems_compo(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_implementation_sommet::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_Face_VDF_implementation::valeur_aux_elems_passe(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Q4_implementation::valeur_aux_sommets(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_P1iP1B_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), valeur_aux_sommets(), Champ_Q4_implementation::valeur_aux_sommets_compo(), Champ_Face_VDF_implementation::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_sommet::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), and Champ_implementation_sommet::valeur_aux_sommets_impl().
le_champ() [2/2]
virtual const Champ_base & Champ_implementation::le_champ () const protected pure virtual
Implemented in Champ_Fonc_P0_base, Champ_Fonc_P1_base, Champ_Fonc_Q1_base, Champ_Inc_P0_base, Champ_Inc_P1_base, Champ_Inc_Q1_base, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_P1NC, Champ_Fonc_Q1NC, and Champ_implementation_P1.
valeur_aux_sommets_impl()
virtual DoubleTab & Champ_implementation::valeur_aux_sommets_impl (DoubleTab & result) const protected pure virtual
Implemented in Champ_implementation_divers, Champ_implementation_P0, and Champ_implementation_sommet.
Referenced by valeur_aux_sommets().
valeur_aux_sommets_compo_impl()
virtual DoubleVect & Champ_implementation::valeur_aux_sommets_compo_impl (DoubleVect & result, int ncomp) const protected pure virtual
Implemented in Champ_implementation_divers, Champ_implementation_P0, and Champ_implementation_sommet.
Referenced by valeur_aux_sommets_compo().