CEA TRUST Platform: Traitement_particulier_NS_canal_VEF Class Reference
Traitement_particulier_NS_canal_VEF Class Reference
#include <Traitement_particulier_NS_canal_VEF.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
pour le calcul d'un canal plan :
    * conservation du debit
    * calculs de moyennes
See also
Navier_Stokes_Turbulent, Traitement_particulier_base, Traitement_particulier_VEF
Member Function Documentation
lire() [1/2]
Entree & Traitement_particulier_NS_canal_VEF::lire (const Motcle & , Entree &)
lire() [2/2]
Entree & Traitement_particulier_NS_canal_VEF::lire (Entree & is) override virtual
Reimplemented from Traitement_particulier_NS_canal.
References Traitement_particulier_NS_canal::lire().
remplir_Y()
void Traitement_particulier_NS_canal_VEF::remplir_Y (DoubleVect & tabY, DoubleVect & tabcompt, int & aNy) const override protected virtual
Implements Traitement_particulier_NS_canal.
References Domaine_VF::faces_doubles(), Domaine_VF::nb_faces(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::xv().
calculer_moyenne_spatiale_vitesse_rho_mu()
void Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu (DoubleTab & val_moy) const override protected virtual
Implements Traitement_particulier_NS_canal.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), Domaine_VF::face_voisins(), Domaine_VF::faces_doubles(), Milieu_base::masse_volumique(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), Traitement_particulier_NS_canal::Ny, Champ_Don_base::valeurs(), Champ_Proto::valeurs(), Fluide_base::viscosite_dynamique(), Domaine_VF::xv(), and Traitement_particulier_NS_canal::Y.
calculer_moyenne_spatiale_nut()
void Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut (DoubleTab & val_moy) const override protected virtual
Implements Traitement_particulier_NS_canal.
References Domaine_VF::face_voisins(), Domaine_VF::faces_doubles(), Equation_base::get_modele(), Domaine_VF::nb_faces(), Traitement_particulier_NS_canal::Ny, TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Modele_turbulence_hyd_base::viscosite_turbulente(), Domaine_VF::xv(), and Traitement_particulier_NS_canal::Y.
calculer_moyenne_spatiale_Temp()
void Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_Temp (DoubleTab & val_moy) const override protected virtual
Implements Traitement_particulier_NS_canal.
References Objet_U::dimension, Domaine_VF::faces_doubles(), Domaine_VF::nb_faces(), Traitement_particulier_NS_canal::Ny, Domaine_VF::xv(), and Traitement_particulier_NS_canal::Y.