CEA TRUST Platform: Domaine_base Class Reference
Domaine_base Class Reference
Public Member Functions
const Nom & le_nom () const override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Domaine class which inherits from Domaine_base and is templatized on entity index size (32 / 64b)
Member Function Documentation
le_nom()
const Nom& Domaine_base::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
References nom_.
Referenced by Modele_turbulence_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), Champ_implementation_P0::affecter_(), Rectify_Mesh::apply(), Refine_Mesh::apply(), Domaine_dis_cache::build_or_get(), Domaine_dis_cache::build_or_get_poly_post(), Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Terme_Boussinesq_base::check(), Reordonner_faces_periodiques_32_64< _SIZE_ >::chercher_direction_perio(), Faces_32_64< _SIZE_ >::compare(), Champ_Generique_Extraction::completer(), Champ_Generique_Interpolation::completer(), Domaine_32_64< _SIZE_ >::comprimer(), Champ_front_contact_VEF::connectivity_failed(), Extruder_en3::construire_bords(), Partitionneur_Partition::construire_partition(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Pb_MED::creer_champ(), Postraitement::creer_champ_post_stat(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::data_a_sauvegarder(), DecoupeBord_32_64< _SIZE_ >::decouper(), Domaine_Poly_base::discretiser(), Postraiter_domaine::ecrire(), Format_Post_Med::ecrire_champ_med(), Champ_Generique_Reduction_0D::extraire(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Postraitement::init(), Domaine_VF::init_dist_paroi_globale(), Domaine_PolyMAC::init_equiv(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC::init_ve(), Raccord_distant_homogene_32_64< _SIZE_ >::initialise(), Sonde::initialiser(), Champ_front_contact_VEF::initialiser(), Champ_front_calc::initialiser(), Ecrire_Champ_MED::interpreter(), Lata_2_Other::interpreter(), DecoupeBord_32_64< _SIZE_ >::interpreter_(), Dilate::interpreter_(), Distanceparoi::interpreter_(), Extraire_surface::interpreter_(), RegroupeBord_32_64< _SIZE_ >::interpreter_(), VerifierCoin::interpreter_(), Domaine_VEF::lecture_ok_arete(), Modele_turbulence_hyd_base::lire_distance_paroi(), ScatterMED::lire_domaine(), LireMED_32_64< _SIZE_ >::lire_geom(), Decouper_multi::lire_motcle_non_standard(), Postraitement::lire_motcle_non_standard(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), Champ_Generique_Interpolation::nommer_source(), Champ_Generique_refChamp::nommer_source(), Postraitement::postraiter_champs(), Postraitement::postraiter_tableau(), Postraitement::postraiter_tableaux(), Domaine_dis_base::rang_frontiere(), Remove_elem::remove_elem_(), Champ_front_contact_VEF::remplir_connect_bords(), Equation_base::reprendre(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::reprendre(), Navier_Stokes_IBM_Turbulent::reprendre(), Navier_Stokes_std::reprendre(), Navier_Stokes_Turbulent::reprendre(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Parallel_io_parameters::run_bench_read(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder(), Modele_turbulence_hyd_null::sauvegarder(), Postraitement::sauvegarder(), Champ_implementation::valeur_aux_sommets(), Champ_implementation::valeur_aux_sommets_compo(), and Echange_contact_VDF::verifier_correspondance().
nommer()
void Domaine_base::nommer (const Nom &) inline override virtual
Donne un nom a l'Objet_U Methode virtuelle a surcharger.
Parameters
(const Nom&) le nom a affectuer a l'Objet_U
Reimplemented from Objet_U.
References nom_.
Referenced by DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Extraire_surface::extraire_surface_without_cleaning(), Domaine_IJK::init_subregion(), Lata_2_Other::interpreter(), Create_domain_from_sub_domain::interpreter_(), ScatterMED::lire_domaine(), and Multigrille_base::multigrille_().
epsilon()
double Domaine_base::epsilon () const inline
References epsilon_.
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), and Octree_32_64< _SIZE_ >::get_epsilon().
initialiser()
virtual void Domaine_base::initialiser (double temps, Domaine_dis_base & , Probleme_base &) inline virtual
Referenced by Probleme_base_interface_proto::initialize_impl().
set_dt()
virtual void Domaine_base::set_dt (double & dt_) inline virtual
Referenced by Probleme_base_interface_proto::initTimeStep_impl().
mettre_a_jour()
virtual void Domaine_base::mettre_a_jour (double temps, Domaine_dis_base & , Probleme_base &) inline virtual
Referenced by Probleme_base_interface_proto::iterateTimeStep_impl(), and Pb_Dilatable_base::mettre_a_jour().
update_after_post()
virtual void Domaine_base::update_after_post (double temps) inline virtual
getUpdateTheGrid()
virtual bool Domaine_base::getUpdateTheGrid () inline virtual
Referenced by Probleme_base_interface_proto::iterateTimeStep_impl().
setUpdateTheGrid()
virtual void Domaine_base::setUpdateTheGrid (bool) inline virtual
Referenced by Probleme_base_interface_proto::iterateTimeStep_impl(), and Probleme_base::mettre_a_jour().
associer_bords_a_imprimer()
void Domaine_base::associer_bords_a_imprimer (LIST(Nom) liste) inline
associer_bords_a_imprimer_sum()
void Domaine_base::associer_bords_a_imprimer_sum (LIST(Nom) liste) inline
lire_bords_a_imprimer()
Entree & Domaine_base::lire_bords_a_imprimer (Entree & s)
References Process::exit().
Referenced by Imprimer_flux::interpreter_().
lire_bords_a_imprimer_sum()
Entree & Domaine_base::lire_bords_a_imprimer_sum (Entree & s)
References Process::exit().
Referenced by Imprimer_flux_sum::interpreter_().
LIST() [1/4]
const Domaine_base::LIST (Nom) const & inline
LIST() [2/4]
const Domaine_base::LIST (Nom) const & inline
moments_a_imprimer() [1/2]
int Domaine_base::moments_a_imprimer () const inline
References moments_a_imprimer_.
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Iterateur_VDF_Face< _TYPE_ >::impr(), and Calculer_Moments::interpreter_().
moments_a_imprimer() [2/2]
int& Domaine_base::moments_a_imprimer () inline
References moments_a_imprimer_.
axi1d()
bool Domaine_base::axi1d () const inline
References Objet_U::que_suis_je().
Referenced by LireMED_32_64< _SIZE_ >::lire_geom().
fixer_epsilon()
void Domaine_base::fixer_epsilon (double eps) inline
References epsilon_.
Referenced by Mailler_32_64< _SIZE_ >::interpreter_().
deformable() [1/2]
bool Domaine_base::deformable () const inline
References deformable_.
Referenced by Postraitement::init(), and Postraitement::postraiter_champs().
deformable() [2/2]
bool& Domaine_base::deformable () inline
References deformable_.
set_fichier_lu()
void Domaine_base::set_fichier_lu (Nom & nom) inline
References fichier_lu_.
Referenced by ScatterMED::lire_domaine().
get_fichier_lu()
const Nom& Domaine_base::get_fichier_lu () const inline
References fichier_lu_.
LIST() [3/4]
Domaine_base::LIST (Nom) protected
LIST() [4/4]
Domaine_base::LIST (Nom) protected
duplique_bords_internes()
void Domaine_base::duplique_bords_internes () protected
Member Data Documentation
nom_
Nom Domaine_base::nom_ protected
Domaine name.
Referenced by Domaine_32_64< _SIZE_ >::fill_from_list(), le_nom(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), and nommer().
moments_a_imprimer_
int Domaine_base::moments_a_imprimer_ protected
Referenced by moments_a_imprimer().
epsilon_
double Domaine_base::epsilon_ protected
Referenced by epsilon(), and fixer_epsilon().
deformable_
bool Domaine_base::deformable_ = false protected
Referenced by deformable().
fichier_lu_
Nom Domaine_base::fichier_lu_ protected
Referenced by get_fichier_lu(), and set_fichier_lu().
volume_total_
double Domaine_base::volume_total_ protected
Volume total du domaine (somme sur tous les processeurs)