CEA TRUST Platform: Assembleur_P_VEF Class Reference
Assembleur_P_VEF Class Reference
Public Member Functions
int assembler_QC (const DoubleTab &, Matrice &) override
virtual int modifier_matrice (Matrice &)
Public Member Functions inherited from Assembleur_base
virtual int assembler_rho_variable (Matrice &, const Champ_Don_base &rho)
int set_resoudre_en_u (int flag)
int set_resoudre_increment_pression (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_domaine_dis_base()
void Assembleur_P_VEF::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis) override virtual
Implements Assembleur_base.
associer_domaine_cl_dis_base()
void Assembleur_P_VEF::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis) override virtual
Implements Assembleur_base.
domaine_dis_base()
const Domaine_dis_base & Assembleur_P_VEF::domaine_dis_base () const override virtual
Implements Assembleur_base.
domaine_Cl_dis_base()
const Domaine_Cl_dis_base & Assembleur_P_VEF::domaine_Cl_dis_base () const override virtual
Implements Assembleur_base.
assembler()
int Assembleur_P_VEF::assembler (Matrice & la_matrice) override virtual
Implements Assembleur_base.
Reimplemented in Assembleur_P_VEFPreP1B.
References assembler_mat(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by Assembleur_P_VEFPreP1B::assembler(), and assembler_QC().
assembler_mat()
int Assembleur_P_VEF::assembler_mat (Matrice & la_matrice, const DoubleVect & volumes_entrelaces, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_base.
Reimplemented in Assembleur_P_VEFPreP1B.
References calculer_inv_volume(), modifier_matrice(), remplir(), Assembleur_base::set_resoudre_en_u(), and Assembleur_base::set_resoudre_increment_pression().
Referenced by assembler().
remplir() [1/2]
int Assembleur_P_VEF::remplir (Matrice & la_matrice, const DoubleTab & inverse_quantitee_entrelacee)
References Objet_U::dimension, Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), Domaine_dis_base::domaine(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), has_P_ref, les_coeff_pression, Domaine_Cl_dis_base::les_conditions_limites(), Process::mp_max(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_Cl_dis_base::nb_faces_Cl(), Front_VF::nb_faces_tot(), Front_VF::num_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Matrice_Sym::set_est_definie(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by assembler_mat().
remplir() [2/2]
int Assembleur_P_VEF::remplir (Matrice & , const DoubleVect &) inline
References Process::exit().
assembler_QC()
int Assembleur_P_VEF::assembler_QC (const DoubleTab & tab_rho, Matrice & matrice) override virtual
Assemble la matrice de pression pour un fluide quasi compressible laplacein(P) est remplace par div(grad(P)/rho).
Parameters
(DoubleTab& tab_rho) mass volumique
Returns
(int) renvoie toujours 1
Reimplemented from Assembleur_base.
References assembler(), and Assembleur_base::set_resoudre_en_u().
modifier_secmem()
int Assembleur_P_VEF::modifier_secmem (DoubleTab & secmem) override virtual
Implements Assembleur_base.
Reimplemented in Assembleur_P_VEFPreP1B.
References Cond_lim_base::champ_front(), Champ_front_base::derivee_en_temps(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Cond_lim_base::frontiere_dis(), Assembleur_base::get_resoudre_en_u(), Assembleur_base::get_resoudre_increment_pression(), Champ_front_base::instationnaire(), les_coeff_pression, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
modifier_solution()
int Assembleur_P_VEF::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
Reimplemented in Assembleur_P_VEFPreP1B.
References has_P_ref.
modifier_matrice()
int Assembleur_P_VEF::modifier_matrice (Matrice & matrice) virtual
Modifier eventuellement la matrice pour la rendre definie si elle ne l'est pas Valeurs par defaut:
Contraintes: Acces: entree
Returns
(int) renvoie 1 si la matrice est modifiee 0 sinon
Reimplemented in Assembleur_P_VEFPreP1B.
References Objet_U::dimension, Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Process::me(), Process::mp_min(), and Matrice_Sym::set_est_definie().
Referenced by assembler_mat(), and Assembleur_P_VEFPreP1B::modifier_matrice().
completer()
void Assembleur_P_VEF::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
Reimplemented in Assembleur_P_VEFPreP1B.
Referenced by Assembleur_P_VEFPreP1B::completer().
equation()
const Equation_base & Assembleur_P_VEF::equation () const inline
References Process::exit().
Referenced by calculer_inv_volume().
OBS_PTR() [1/3]
Assembleur_P_VEF::OBS_PTR (Equation_base) protected
OBS_PTR() [2/3]
Assembleur_P_VEF::OBS_PTR (Domaine_VEF) protected
OBS_PTR() [3/3]
Assembleur_P_VEF::OBS_PTR (Domaine_Cl_VEF) protected
calculer_inv_volume()
void Assembleur_P_VEF::calculer_inv_volume (DoubleTab & inv_volumes_entrelaces, const Domaine_Cl_VEF & domaine_Cl_VEF, const DoubleVect & volumes_entrelaces) protected
References Solveur_Masse_base::appliquer(), Objet_U::dimension, MorEqn::equation(), equation(), Process::exit(), Equation_base::milieu(), Milieu_base::porosite_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Equation_base::solv_masse().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), and assembler_mat().
Member Data Documentation
les_coeff_pression
DoubleTab Assembleur_P_VEF::les_coeff_pression protected
Referenced by modifier_secmem(), and remplir().
has_P_ref
int Assembleur_P_VEF::has_P_ref = 0 protected
Referenced by Assembleur_P_VEFPreP1B::modifier_matrice(), modifier_solution(), and remplir().