CEA TRUST Platform: Eval_Forchheimer_VEF_Face Class Reference
Eval_Forchheimer_VEF_Face Class Reference
Constructor & Destructor Documentation
Eval_Forchheimer_VEF_Face() [1/2]
Eval_Forchheimer_VEF_Face::Eval_Forchheimer_VEF_Face () inline
Eval_Forchheimer_VEF_Face() [2/2]
Eval_Forchheimer_VEF_Face::Eval_Forchheimer_VEF_Face (const Eval_Forchheimer_VEF_Face & eval) inline
Member Function Documentation
mettre_a_jour()
void Eval_Forchheimer_VEF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
calculer_terme_source_standard()
template<typename Type_Double > void Eval_Forchheimer_VEF_Face::calculer_terme_source_standard (const int num_face, Type_Double & source) const inline
References Evaluateur_Source_Face::volumes_entrelaces.
calculer_terme_source_non_standard()
template<typename Type_Double > void Eval_Forchheimer_VEF_Face::calculer_terme_source_non_standard (const int num_face, Type_Double & source) const inline
References Evaluateur_Source_VEF_Face::volumes_entrelaces_Cl.
setCf()
void Eval_Forchheimer_VEF_Face::setCf (double c) inline
Referenced by Source_Forchheimer_VEF_Face::lire_motcle_non_standard().
associer()
void Eval_Forchheimer_VEF_Face::associer (const Champ_Inc_base & v) inline
Referenced by Source_Forchheimer_VEF_Face::associer_pb().
setPorosite()
void Eval_Forchheimer_VEF_Face::setPorosite (double p) inline
Referenced by Source_Forchheimer_VEF_Face::lire_motcle_non_standard().
OWN_PTR()
Eval_Forchheimer_VEF_Face::OWN_PTR (Modele_Permeabilite_base)