CEA TRUST Platform: Multi_Sch_ThHyd Class Reference
Multi_Sch_ThHyd Class Reference
#include <Multi_Sch_ThHyd.h>
Public Member Functions
void changer_temps_courant (const double) override
bool corriger_dt_calcule (double &) const override
int faire_un_pas_de_temps_eqn_base (Equation_base &) override
void imprimer (Sortie &) const override
int mettre_a_jour () override
int nb_valeurs_futures () const override
int nb_valeurs_temporelles () const override
int stop () const override
double temps_defaut () const override
double temps_futur (int i) const override
Public Member Functions inherited from Schema_Temps_base
int diffusion_implicite () const
double & facteur_securite_pas ()
double facteur_securite_pas () const
virtual int impr (Sortie &os) const
virtual int impr (Sortie &os, Probleme_base &pb) const
void imprimer (Sortie &os, Probleme_base &pb) const
virtual bool isStationary () const
const Nom & le_nom () const override
int limpr () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nb_impr () const
int nb_pas_dt () const
int nb_pas_dt_max () const
int nb_pas_dt_max_atteint () const
int nb_sauv_max () const
void nommer (const Nom &) override
double pas_de_temps () const
double & pas_temps_max ()
double pas_temps_max () const
double & pas_temps_min ()
double pas_temps_min () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
double seuil_statio () const
int stop_lu () const
double temps_calcul () const
double temps_courant () const
int temps_final_atteint () const
double temps_impr () const
double temps_init () const
double temps_max () const
double temps_precedent () const
double temps_sauv () const
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Schema_Temps_base
Member Function Documentation
nb_valeurs_temporelles()
int Multi_Sch_ThHyd::nb_valeurs_temporelles () const override virtual
Renvoie le nombre de valeurs temporelles a conserver.
Ici : le max des deux schemas utilises.
Implements Schema_Temps_base.
nb_valeurs_futures()
int Multi_Sch_ThHyd::nb_valeurs_futures () const override virtual
Renvoie le nombre de valeurs temporelles futures.
Ici : la valeur commune aux deux schemas utilises.
Implements Schema_Temps_base.
temps_futur()
double Multi_Sch_ThHyd::temps_futur (int i) const override virtual
Renvoie le le temps a la i-eme valeur future.
Ici : la valeur commune aux deux schemas utilises.
Implements Schema_Temps_base.
temps_defaut()
double Multi_Sch_ThHyd::temps_defaut () const override virtual
Renvoie le le temps le temps que doivent rendre les champs a l'appel de valeurs()
Ici : la valeur commune aux deux schemas utilises.
Implements Schema_Temps_base.
faire_un_pas_de_temps_eqn_base()
int Multi_Sch_ThHyd::faire_un_pas_de_temps_eqn_base (Equation_base & eqn) override virtual
Effectue un pas de temps d'Euler explicite sur l'equation passee en parametre.
Parameters
(Equation_base& eqn) l'equation que l'on veut faire avancer d'un pas de temps
Returns
(int) renvoie toujours 1
Implements Schema_Temps_base.
References Schema_Temps_base::facteur_securite_pas(), Schema_Temps_base::pas_de_temps(), and Schema_Temps_base::set_stationnaire_atteint().
Referenced by iterateTimeStep().
iterateTimeStep()
bool Multi_Sch_ThHyd::iterateTimeStep (bool & converged) override virtual
Calculate the U(n+1) unknown for each equation (if solved) of the problem with the selected time scheme.
Reimplemented from Schema_Temps_base.
References Equation_base::derivee_en_temps_inco(), Equation_base::domaine_Cl_dis(), Schema_Temps_base::dt_, Probleme_base::equation(), Equation_base::equation_non_resolue(), faire_un_pas_de_temps_eqn_base(), Equation_base::inconnue(), Domaine_Cl_dis_base::mettre_a_jour(), Schema_Temps_base::nb_pas_dt(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pb_base(), Objet_U::que_suis_je(), Equation_base::schema_temps(), Schema_Temps_base::temps_courant_, and Champ_Inc_base::valeurs().
set_param()
void Multi_Sch_ThHyd::set_param (Param & titi) override virtual
Reimplemented from Schema_Temps_base.
References Param::ajouter(), and Schema_Temps_base::set_param().
mettre_a_jour()
int Multi_Sch_ThHyd::mettre_a_jour () override virtual
Mise a jour du temps courant (t+=dt) et du nombre de pas de temps effectue (nb_pas_dt_++).
Returns
(int) retourne toujours 1
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::mettre_a_jour().
corriger_dt_calcule()
bool Multi_Sch_ThHyd::corriger_dt_calcule (double & dt) const override virtual
Corrige le pas de temps dt_min <= dt <= dt_max.
Returns
(int) retourne corriger_pas_temps de la classe mere
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::corriger_dt_calcule().
completer()
void Multi_Sch_ThHyd::completer () override virtual
Implements Schema_Temps_base.
References Schema_Temps_base::diffusion_implicite(), Schema_Temps_base::facteur_securite_pas(), Schema_Temps_base::indice_nb_pas_dt_max_atteint(), Schema_Temps_base::indice_tps_final_atteint(), Schema_Temps_base::isStationary(), Schema_Temps_base::lu(), Schema_Temps_base::mode_dt_start(), Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max(), Schema_Temps_base::niter_max_diffusion_implicite(), Schema_Temps_base::pas_de_temps(), Schema_Temps_base::pas_temps_max(), Schema_Temps_base::pas_temps_min(), Schema_Temps_base::set_diffusion_implicite(), Schema_Temps_base::set_dt(), Schema_Temps_base::set_dt_impr(), Schema_Temps_base::set_dt_max(), Schema_Temps_base::set_dt_min(), Schema_Temps_base::set_dt_sauv(), Schema_Temps_base::set_facsec(), Schema_Temps_base::set_indice_nb_pas_dt_max_atteint(), Schema_Temps_base::set_indice_tps_final_atteint(), Schema_Temps_base::set_lu(), Schema_Temps_base::set_mode_dt_start(), Schema_Temps_base::set_nb_pas_dt(), Schema_Temps_base::set_nb_pas_dt_max(), Schema_Temps_base::set_niter_max_diffusion_implicite(), Schema_Temps_base::set_seuil_diffusion_implicite(), Schema_Temps_base::set_seuil_statio(), Schema_Temps_base::set_stationnaire_atteint(), Schema_Temps_base::set_temps_courant(), Schema_Temps_base::set_temps_init(), Schema_Temps_base::set_temps_max(), Schema_Temps_base::seuil_diffusion_implicite(), Schema_Temps_base::seuil_statio(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_impr(), Schema_Temps_base::temps_init(), Schema_Temps_base::temps_max(), and Schema_Temps_base::temps_sauv().
changer_temps_courant()
void Multi_Sch_ThHyd::changer_temps_courant (const double t) override virtual
Appel a l'objet sous-jacent Change le temps courant.
Parameters
(double& t) la nouvelle valeur du temps courant
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::changer_temps_courant().
stop()
int Multi_Sch_ThHyd::stop () const override virtual
Appel a l'objet sous-jacent Renvoie 1 si il y lieu de stopper le calcul pour differente raisons:
   - le temps final est atteint
   - le nombre de pas de temps maximum est depasse
   - l'etat stationnaire est atteint
   - indicateur d'arret fichier
Renvoie 0 sinon
Returns
(entier) 1 si il y a lieu de s'arreter 0 sinon
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::stop().
imprimer()
void Multi_Sch_ThHyd::imprimer (Sortie & os) const override virtual
Appel a l'objet sous-jacent Imprime le schema en temp sur un flot de sortie (si il y a lieu).
Parameters
(Sortie& os) le flot de sortie
Reimplemented from Schema_Temps_base.
References Schema_Temps_base::imprimer().