CEA TRUST Platform: Periodique Class Reference
Periodique Class Reference
Public Member Functions
void mettre_a_jour (double temps) override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
virtual int initialiser (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
On peut specifier une periodicite en X, Y ou Z.
Toutes les faces de la frontiere associee a cette condition doivent
avoir la meme orientation
See also
Cond_lim_base, Toutes les faces de la frontiere associee a cette condition doivent, avoir la meme orientation
Member Function Documentation
mettre_a_jour()
void Periodique::mettre_a_jour (double temps) inline override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Cond_lim_base.
face_associee() [1/2]
int Periodique::face_associee (int i) const inline
References face_front_associee_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Div_VEFP1B_Elem::ajouter_som(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Domaine_VEF::construire_renum_arete_perio(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Op_PolyMAC_Elem::dimensionner(), Champ_P1NC_implementation::filtrer_resu(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_VEF::initialiser(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Assembleur_P_VDF::liste_faces_periodiques(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_VEF_Face_Gen< DERIVED_T >::modifie_pour_cl_gen(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Assembleur_P_VEF::remplir(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), and Champ_Q1NC::verifie_valeurs_cl().
face_associee() [2/2]
const ArrOfInt& Periodique::face_associee () const inline
References face_front_associee_.
distance()
double Periodique::distance () const inline
References distance_.
Referenced by Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face(), and Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face().
direction_perio()
const ArrOfDouble& Periodique::direction_perio () const inline
References direction_perio_.
Referenced by Terme_Source_Canal_perio::completer().
direction_periodicite()
int Periodique::direction_periodicite () const
References direction_xyz_, est_periodique_selon_un_axe(), and Process::exit().
Referenced by Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio::completer(), and Domaine_VEF::construire_renum_arete_perio().
est_periodique_selon_un_axe()
int Periodique::est_periodique_selon_un_axe () const inline
References direction_xyz_.
Referenced by Terme_Source_Canal_perio::completer(), and direction_periodicite().
compatible_avec_eqn()
int Periodique::compatible_avec_eqn (const Equation_base &) const inline override protected virtual
Reimplemented from Cond_lim_base.
completer()
void Periodique::completer () override protected virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
References Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Domaine_VF::creer_tableau_faces_bord(), direction_perio_, direction_xyz_, distance_, Frontiere_32_64< _SIZE_ >::domaine(), Cond_lim_base::domaine_Cl_dis(), Process::exit(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Frontiere_32_64< _SIZE_ >::le_nom(), Objet_U::precision_geom, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Member Data Documentation
face_front_associee_
ArrOfInt Periodique::face_front_associee_ protected
Referenced by face_associee().
direction_perio_
ArrOfDouble Periodique::direction_perio_ protected
Referenced by completer(), and direction_perio().
distance_
double Periodique::distance_ = -500. protected
Referenced by completer(), and distance().
direction_xyz_
int Periodique::direction_xyz_ = -100 protected
Referenced by completer(), direction_periodicite(), and est_periodique_selon_un_axe().