CEA TRUST Platform: FichierHDF Class Reference
FichierHDF Class Reference
Detailed Description
..) It intentionally does not place itself in the Sortie_Fichier_base or Entree_Fichier_base hierarchy since it is rather the datasets inside the HDF file that are regarded as TRUST Fichier objects.
Constructor & Destructor Documentation
FichierHDF()
FichierHDF::FichierHDF ()
References Process::exit().
~FichierHDF()
FichierHDF::~FichierHDF () virtual
Member Function Documentation
create()
void FichierHDF::create (Nom filename) virtual
Referenced by Save_Restart::finir(), and Save_Restart::sauver().
open()
void FichierHDF::open (Nom filename, bool readOnly) virtual
close()
void FichierHDF::close () virtual
Referenced by Save_Restart::finir(), and Save_Restart::sauver().
create_and_fill_dataset_MW() [1/2]
void FichierHDF::create_and_fill_dataset_MW (Nom dataset_basename, Sortie_Brute & sortie) virtual
Referenced by Save_Restart::finir(), and Save_Restart::sauver().
create_and_fill_dataset_MW() [2/2]
void FichierHDF::create_and_fill_dataset_MW (Nom dataset_basename, SChaine & sortie) virtual
create_and_fill_dataset_SW()
void FichierHDF::create_and_fill_dataset_SW (Nom datasetname, Sortie_Brute & sortie) virtual
read_dataset()
void FichierHDF::read_dataset (Nom dataset_basename, int proc_rank, Entree_Brute & entree) virtual
create_datasets()
void FichierHDF::create_datasets (Noms dataset_names, long length) inline
fill_dataset()
void FichierHDF::fill_dataset (Nom dataset_name, Sortie_Brute & sortie)
exists()
bool FichierHDF::exists (const char * dataset_name) virtual
is_hdf5()
bool FichierHDF::is_hdf5 (const char * file_name) static
Referenced by Scatter::lire_domaine().
check_int_size()
void FichierHDF::check_int_size (Nom filename)
set_int_size()
void FichierHDF::set_int_size ()
prepare_file_props()
void FichierHDF::prepare_file_props () protected virtual
Reimplemented in FichierHDFPar.
Referenced by FichierHDFPar::prepare_file_props().
prepare_dataset_props()
void FichierHDF::prepare_dataset_props () protected virtual
Reimplemented in FichierHDFPar.
Referenced by FichierHDFPar::prepare_dataset_props().