CEA TRUST Platform: Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face Class Reference
Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face Class Reference
#include <Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face.h>
Public Member Functions
double calculer_dt_stab () const override
Public Member Functions inherited from Op_Conv_EF_Stab_PolyMAC_Face
void completer () override
void dimensionner (Matrice_Morse &mat) const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Conv_PolyMAC_base
double calculer_dt_stab () const override
void completer () override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
calculer_dt_stab()
double Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Process::mp_min(), Milieu_base::porosite_elem(), and Milieu_base::porosite_face().
has_interface_blocs()
int Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
dimensionner_blocs()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), MorEqn::equation(), Champ_Face_base::fcl(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const override virtual
Reimplemented from Operateur_base.
References Masse_ajoutee_base::ajouter(), Op_Conv_EF_Stab_PolyMAC_Face::alpha_, Statistiques::begin_count(), Equation_base::champ_conserve(), Objet_U::dimension, Statistiques::end_count(), MorEqn::equation(), Pb_Multiphase::equation_masse(), Champ_Face_base::fcl(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Operateur_Conv_base::incompressible_, Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Champ_Proto::passe(), Champ_Inc_base::passe(), Op_Conv_EF_Stab_PolyMAC_Face::porosite_e, Op_Conv_EF_Stab_PolyMAC_Face::porosite_f, and Champ_Inc_base::valeurs().
check_multiphase_compatibility()
void Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.