CEA TRUST Platform: Modele_turbulence_hyd_base Class Reference
Modele_turbulence_hyd_base Class Reference abstract
Public Member Functions
void associer_eqn (const Equation_base &)
Equation_base & equation ()
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
qui representent un modele de turbulence pour les equations de Navier-Stokes. Il existe deja deux classes derivees qui representent le modele de turbulence (k,e) et le modele de turbulence sous maille. Ces deux modeles ont en commun le calcul d'une viscosite turbulente.
B.Mat. : la classe herite de support_champ_masse_volumique. en Front-Tracking (et plus tard en qc), elle fournit le mecanisme pour recuperer rho.
Member Function Documentation
viscosite_turbulente() [1/2]
const Champ_Fonc_base& Modele_turbulence_hyd_base::viscosite_turbulente () const inline
Referenced by Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Op_Dift_EF_base::completer(), Op_Diff_PolyMAC_Face::completer(), Modele_turbulence_scal_diffturb_base::completer(), Op_Dift_VEF_base::completer(), Op_Diff_Dift_VDF< OP_TYPE >::completer_impl(), and limiter_viscosite_turbulente().
viscosite_turbulente() [2/2]
Champ_Fonc_base& Modele_turbulence_hyd_base::viscosite_turbulente () inline
equation() [1/2]
Equation_base & Modele_turbulence_hyd_base::equation () inline
Renvoie l'equation associee au modele de turbulence.
(c'est une equation du type Equation_base)
Returns
(Equation_base&) l'equation associee au modele de turbulence
References Process::exit().
Referenced by a_faire(), discretiser_visc_turb(), limiter_viscosite_turbulente(), lire_distance_paroi(), lire_motcle_non_standard(), Transport_2eq_base::lire_op_diff_turbulent(), preparer_calcul(), Modele_turbulence_hyd_Longueur_Melange_VEF::preparer_calcul(), Modele_turbulence_hyd_null::sauvegarder(), Turbulence_paroi_base::typer_lire_turbulence_paroi(), and Modele_turbulence_hyd_LES_base::verifie_loi_paroi_diphasique().
equation() [2/2]
const Equation_base & Modele_turbulence_hyd_base::equation () const inline
References Process::exit().
loi_paroi() [1/2]
const Turbulence_paroi_base& Modele_turbulence_hyd_base::loi_paroi () const inline
Referenced by Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Champ_P1NC_implementation::filtrer_L2(), Y_plus_Champ_Face::me_calculer(), Y_plus_Champ_P1NC::me_calculer(), and Turbulence_paroi_scal_base::typer_lire_turbulence_paroi_scal().
loi_paroi() [2/2]
Turbulence_paroi_base& Modele_turbulence_hyd_base::loi_paroi () inline
utiliser_loi_paroi()
bool Modele_turbulence_hyd_base::utiliser_loi_paroi () const inline
Referenced by Champ_P1NC_implementation::filtrer_L2().
has_loi_paroi_hyd()
bool Modele_turbulence_hyd_base::has_loi_paroi_hyd () const inline
calcul_tenseur_Re()
virtual bool Modele_turbulence_hyd_base::calcul_tenseur_Re (const DoubleTab & nu_turb, const DoubleTab & grad, DoubleTab & Re) const inline virtual
set_param()
void Modele_turbulence_hyd_base::set_param (Param & param) virtual
Reimplemented in Modele_turbulence_hyd_Longueur_Melange_VEF, Modele_turbulence_hyd_LES_Wale_VEF, Modele_turbulence_hyd_LES_Smago_VEF, Modele_turbulence_hyd_Longueur_Melange_VDF, Modele_turbulence_hyd_LES_Wale_VDF, Modele_turbulence_hyd_LES_Smago_VDF, Modele_turbulence_hyd_LES_base, Modele_turbulence_hyd_0_eq_base, and Modele_turbulence_hyd_2_eq_base.
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), and Param::REQUIRED.
Referenced by Modele_turbulence_hyd_2_eq_base::set_param(), Modele_turbulence_hyd_0_eq_base::set_param(), and Modele_turbulence_hyd_LES_base::set_param().
lire_motcle_non_standard()
int Modele_turbulence_hyd_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
< liste stockant tous les noms de frontiere du domaine
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_Longueur_Melange_VEF.
References Frontiere_32_64< _SIZE_ >::add(), boundaries_, Probleme_base::domaine(), dt_impr_ustar_, dt_impr_ustar_mean_only_, equation(), Process::exit(), Domaine_32_64< _SIZE_ >::frontiere(), Probleme_U::le_nom(), Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), LIST(), Domaine_32_64< _SIZE_ >::nb_front_Cl(), Objet_U::nom_du_cas(), nom_fichier_, Equation_base::probleme(), Objet_U::que_suis_je(), and Turbulence_paroi_base::typer_lire_turbulence_paroi().
Referenced by Modele_turbulence_hyd_2_eq_base::lire_motcle_non_standard(), and Modele_turbulence_hyd_Longueur_Melange_VEF::lire_motcle_non_standard().
preparer_calcul()
int Modele_turbulence_hyd_base::preparer_calcul () virtual
Prepare le calcul.
Initialise la loi de paroi. Remplit le champ wall_length en cas de post traitemetn de la distance_paroi
Returns
(int) code de retour de Turbulence_paroi::init_lois_paroi()
Reimplemented in Modele_turbulence_hyd_Longueur_Melange_VEF, Modele_turbulence_hyd_Longueur_Melange_VDF, and Modele_turbulence_hyd_LES_base.
References boundaries_, Nom::contient(), equation(), lire_distance_paroi(), and nom_fichier_.
Referenced by Modele_turbulence_hyd_LES_base::preparer_calcul(), Modele_turbulence_hyd_Longueur_Melange_VDF::preparer_calcul(), and Modele_turbulence_hyd_Longueur_Melange_VEF::preparer_calcul().
initTimeStep()
bool Modele_turbulence_hyd_base::initTimeStep (double dt) virtual
mettre_a_jour()
virtual void Modele_turbulence_hyd_base::mettre_a_jour (double) pure virtual
Implemented in Modele_turbulence_hyd_null, and Modele_turbulence_hyd_0_eq_base.
discretiser()
void Modele_turbulence_hyd_base::discretiser () virtual
Discretise le modele de turbulence.
Reimplemented in Modele_turbulence_hyd_0_eq_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), champs_compris_, Discretisation_base::discretiser_champ(), discretiser_corr_visc_turb(), discretiser_visc_turb(), and wall_length_.
Referenced by Modele_turbulence_hyd_0_eq_base::discretiser().
discretiser_visc_turb()
void Modele_turbulence_hyd_base::discretiser_visc_turb (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Fonc_base)& ch) const
References Discretisation_base::discretiser_champ(), equation(), Probleme_base::is_dilatable(), Equation_base::probleme(), and Schema_Temps_base::temps_courant().
Referenced by discretiser().
discretiser_corr_visc_turb()
void Modele_turbulence_hyd_base::discretiser_corr_visc_turb (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Fonc_base)& ch) const
References Discretisation_base::discretiser_champ(), and Schema_Temps_base::temps_courant().
Referenced by discretiser().
discretiser_K()
void Modele_turbulence_hyd_base::discretiser_K (const Schema_Temps_base & sch, Domaine_dis_base & z, OWN_PTR(Champ_Fonc_base)& ch) const
References Discretisation_base::discretiser_champ(), and Schema_Temps_base::temps_courant().
Referenced by Modele_turbulence_hyd_0_eq_base::discretiser().
completer()
virtual void Modele_turbulence_hyd_base::completer () inline virtual
Reimplemented in Modele_turbulence_hyd_LES_base, and Modele_turbulence_hyd_0_eq_base.
associer_eqn()
void Modele_turbulence_hyd_base::associer_eqn (const Equation_base & eqn)
Associe l'equation passe en parametre au modele de turbulence.
Parameters
(Equation_base& eqn) l'equation a laquelle l'objet s'associe
associer()
virtual void Modele_turbulence_hyd_base::associer (const Domaine_dis_base & , const Domaine_Cl_dis_base &) inline virtual
Reimplemented in Modele_turbulence_hyd_0_eq_base.
reprendre()
int Modele_turbulence_hyd_base::reprendre (Entree & is) override virtual
Reprend la loi de paroi.
Parameters
(Entree&) un flot d'entree
Returns
(int) renvoie toujours 0
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_LES_base.
Referenced by Modele_turbulence_hyd_LES_base::reprendre().
creer_champ()
void Modele_turbulence_hyd_base::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
get_champ()
const Champ_base & Modele_turbulence_hyd_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champs_compris_, Nom::getString(), Champs_compris_T< FIELD_TYPE >::has_champ(), and OBS_PTR().
get_noms_champs_postraitables()
void Modele_turbulence_hyd_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References champs_compris_, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
has_champ() [1/2]
bool Modele_turbulence_hyd_base::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
has_champ() [2/2]
bool Modele_turbulence_hyd_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
champs_compris()
Champs_compris& Modele_turbulence_hyd_base::champs_compris () inline
References champs_compris_.
imprimer()
void Modele_turbulence_hyd_base::imprimer (Sortie & os) const virtual
Effectue l'impression si cela est necessaire.
Returns
renvoie toujours 1
Reimplemented in Modele_turbulence_hyd_LES_base, and Modele_turbulence_hyd_0_eq_base.
References boundaries_, dt_impr_ustar_, dt_impr_ustar_mean_only_, limpr_ustar(), nom_fichier_, Schema_Temps_base::pas_de_temps(), Schema_Temps_base::temps_courant(), and Schema_Temps_base::temps_precedent().
Referenced by Modele_turbulence_hyd_0_eq_base::imprimer(), and Modele_turbulence_hyd_LES_base::imprimer().
a_faire()
void Modele_turbulence_hyd_base::a_faire (Sortie & os) const
Effectue l'ecriture d'une identite si cela est necessaire.
References Probleme_base::domaine(), equation(), Sortie::flush(), Equation_base::inconnue(), EcritureLectureSpecial::is_ecriture_special(), Domaine_base::le_nom(), Equation_base::probleme(), Objet_U::que_suis_je(), and Champ_base::temps().
Referenced by sauvegarder().
sauvegarder()
int Modele_turbulence_hyd_base::sauvegarder (Sortie & os) const override virtual
Sauvegarde le modele de turbulence sur un flot de sortie.
Sauvegarde le type de l'objet.
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Objet_U.
Reimplemented in Modele_turbulence_hyd_null.
References a_faire(), TRUST_2_PDI::is_PDI_checkpoint(), Process::mp_sum(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Nom::substr_old().
data_a_sauvegarder()
std::vector< YAML_data > Modele_turbulence_hyd_base::data_a_sauvegarder () const virtual
for PDI IO: retrieve name, type and dimensions of the fields to save/restore
limpr_ustar()
int Modele_turbulence_hyd_base::limpr_ustar (double temps_courant, double temps_prec, double dt, double dt_ustar) const
References Schema_Temps_base::nb_pas_dt(), Schema_Temps_base::nb_pas_dt_max_atteint(), Schema_Temps_base::stationnaire_atteint(), Schema_Temps_base::stop_lu(), Schema_Temps_base::temps_cpu_max_atteint(), and Schema_Temps_base::temps_final_atteint().
Referenced by imprimer(), and Modele_turbulence_hyd_0_eq_base::imprimer().
get_Cmu()
double Modele_turbulence_hyd_base::get_Cmu () const inline
References LeCmu_.
lire_distance_paroi()
void Modele_turbulence_hyd_base::lire_distance_paroi ()
Lit le fichier dom_Wall_length.
xyz pour remplir le champs wall_length en vue d'un post-traitement de distance_paroi
References Probleme_base::domaine(), equation(), Process::exit(), Domaine_base::le_nom(), EcritureLectureSpecial::lecture_special(), LecFicDiffuse::ouvrir(), Equation_base::probleme(), Lec_Diffuse_base::set_bin(), and wall_length_.
Referenced by preparer_calcul().
limiter_viscosite_turbulente()
void Modele_turbulence_hyd_base::limiter_viscosite_turbulente ()
References Operateur_Diff_base::calculer_borne_locale(), Domaine_dis_base::domaine(), Equation_base::domaine_dis(), Operateur_Conv_base::dt_stab_conv(), equation(), Process::je_suis_maitre(), Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), Debog::verifier(), and viscosite_turbulente().
OWN_PTR() [1/2]
Modele_turbulence_hyd_base::OWN_PTR (Champ_Fonc_base) protected
OBS_PTR()
Modele_turbulence_hyd_base::OBS_PTR (Equation_base) protected
Referenced by get_champ().
OWN_PTR() [2/2]
Modele_turbulence_hyd_base::OWN_PTR (Turbulence_paroi_base) protected
LIST()
Modele_turbulence_hyd_base::LIST (Nom) protected
Referenced by lire_motcle_non_standard().
Member Data Documentation
LeCmu_
double Modele_turbulence_hyd_base::LeCmu_ = CMU protected
Referenced by get_Cmu().
wall_length_
Modele_turbulence_hyd_base::wall_length_ protected
Referenced by Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_viscosite_turbulente(), discretiser(), Modele_turbulence_hyd_0_eq_base::imprimer(), lire_distance_paroi(), and Modele_turbulence_hyd_Longueur_Melange_VEF::lire_distance_paroi().
dt_impr_ustar_
double Modele_turbulence_hyd_base::dt_impr_ustar_ = 1.e20 protected
Referenced by imprimer(), Modele_turbulence_hyd_0_eq_base::imprimer(), and lire_motcle_non_standard().
dt_impr_ustar_mean_only_
double Modele_turbulence_hyd_base::dt_impr_ustar_mean_only_ = 1.e20 protected
Referenced by imprimer(), Modele_turbulence_hyd_0_eq_base::imprimer(), and lire_motcle_non_standard().
boundaries_
int Modele_turbulence_hyd_base::boundaries_ = 0 protected
Referenced by imprimer(), lire_motcle_non_standard(), and preparer_calcul().
nom_fichier_
Nom Modele_turbulence_hyd_base::nom_fichier_ = "" protected
Referenced by imprimer(), lire_motcle_non_standard(), and preparer_calcul().
champs_compris_
Champs_compris Modele_turbulence_hyd_base::champs_compris_ protected
Referenced by champs_compris(), discretiser(), Modele_turbulence_hyd_0_eq_base::discretiser(), get_champ(), get_noms_champs_postraitables(), and has_champ().