CEA TRUST Platform: Op_Conv_PolyMAC_iterateur_base Class Reference
Op_Conv_PolyMAC_iterateur_base Class Reference abstract
Public Member Functions
double calculer_dt_stab () const override
void completer () override
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
void contribuer_au_second_membre (DoubleTab &resu) const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void dimensionner (Matrice_Morse &) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Op_Conv_PolyMAC_iterateur_base()
Op_Conv_PolyMAC_iterateur_base::Op_Conv_PolyMAC_iterateur_base (const Iterateur_PolyMAC_base & iter_base) inline
Member Function Documentation
ajouter()
DoubleTab& Op_Conv_PolyMAC_iterateur_base::ajouter (const DoubleTab & inco, DoubleTab & resu) const inline override virtual
Reimplemented from Operateur_base.
calculer()
DoubleTab& Op_Conv_PolyMAC_iterateur_base::calculer (const DoubleTab & inco, DoubleTab & resu) const inline override virtual
Reimplemented from Operateur_base.
contribuer_a_avec()
void Op_Conv_PolyMAC_iterateur_base::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
contribuer_bloc_vitesse()
void Op_Conv_PolyMAC_iterateur_base::contribuer_bloc_vitesse (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
Reimplemented from Operateur_base.
contribuer_au_second_membre()
void Op_Conv_PolyMAC_iterateur_base::contribuer_au_second_membre (DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
vitesse() [1/2]
virtual const Champ_base& Op_Conv_PolyMAC_iterateur_base::vitesse () const pure virtual
Implemented in Op_Conv_Centre_PolyMAC_Elem, and Op_Conv_Amont_PolyMAC_Elem.
Referenced by calculer_dt_stab(), and calculer_pour_post().
vitesse() [2/2]
virtual Champ_base& Op_Conv_PolyMAC_iterateur_base::vitesse () pure virtual
Implemented in Op_Conv_Centre_PolyMAC_Elem, and Op_Conv_Amont_PolyMAC_Elem.
completer()
void Op_Conv_PolyMAC_iterateur_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer().
calculer_dt_stab()
double Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), MorEqn::equation(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Operateur_Conv_base::fixer_dt_stab_conv(), Objet_U::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Process::mp_min(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Champ_Proto::valeurs(), vitesse(), and Domaine_VF::volumes().
calculer_pour_post()
void Op_Conv_PolyMAC_iterateur_base::calculer_pour_post (Champ_base & espace_stockage, const Nom & option, int comp) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::calculer_pour_post(), Domaine_dis_base::domaine(), MorEqn::equation(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Objet_U::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_dis_base::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Champ_Proto::valeurs(), vitesse(), and Domaine_VF::volumes().
get_localisation_pour_post()
Motcle Op_Conv_PolyMAC_iterateur_base::get_localisation_pour_post (const Nom & option) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::get_localisation_pour_post().
impr()
int Op_Conv_PolyMAC_iterateur_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
associer_domaine_cl_dis()
void Op_Conv_PolyMAC_iterateur_base::associer_domaine_cl_dis (const Domaine_Cl_dis_base & zcl) override virtual
Reimplemented from Operateur_base.
OWN_PTR()
Op_Conv_PolyMAC_iterateur_base::OWN_PTR (Iterateur_PolyMAC_base) protected