CEA TRUST Platform: Champ_Post_Operateur_Eqn Class Reference
Champ_Post_Operateur_Eqn Class Reference
#include <Champ_Post_Operateur_Eqn.h>
Public Member Functions
Entity get_localisation (const int index=-1) const override
const Noms get_property (const Motcle &query) const override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Generique_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
La classe porte un operateur statistique "gradient"
Syntaxe a respecter pour jdd
nom_choisi operateur_eqn { sources { refchamp { pb_champ nom_pb nom_inconnue } } numero_source/numero op 1 } Il faut entrer le nom de l'inconnue et pas celui de l'equation Le numero des termes sources est celui du jdd, bien respecter l'ordre Pour les operateurs : 0 diffusion, 1 convection
Member Function Documentation
get_property()
const Noms Champ_Post_Operateur_Eqn::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References compo_, Champ_Gen_de_Champs_Gen::get_property(), Champ_Gen_de_Champs_Gen::nb_comp, Champ_Generique_base::nom_post_, and Motcles::search().
get_localisation()
Entity Champ_Post_Operateur_Eqn::get_localisation (const int index = -1) const override virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un.
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans parametre, sauf si on sait quoi faire pour les champs multi-supports.
See also
get_nb_localisations() Parametre : index Signification : index de la localisation demandee (pour les champs multi-support). Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support. Si index >= 0 : on renvoie le i-ieme support. Valeur par defaut : -1 Exceptions:
GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques (il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
References localisation_inco_.
get_champ()
const Champ_base & Champ_Post_Operateur_Eqn::get_champ (OWN_PTR(Champ_base)& espace_stockage) const override
References Operateur_base::ajouter(), compo_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), get_champ_compo_without_evaluation(), get_champ_without_evaluation(), numero_masse_, numero_op_, numero_source_, Operateur(), Champ_Gen_de_Champs_Gen::OWN_PTR(), and sans_solveur_masse_.
get_champ_without_evaluation()
const Champ_base & Champ_Post_Operateur_Eqn::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const override virtual
Implements Champ_Generique_base.
Referenced by get_champ().
get_champ_compo_without_evaluation()
const Champ_base & Champ_Post_Operateur_Eqn::get_champ_compo_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const
References Process::exit(), Field_base::fixer_nature_du_champ(), localisation_inco_, Champ_Gen_de_Champs_Gen::nb_comp, and Champ_Gen_de_Champs_Gen::OWN_PTR().
Referenced by get_champ().
Operateur() [1/2]
const Operateur_base & Champ_Post_Operateur_Eqn::Operateur () const override virtual
Implements Champ_Generique_Operateur_base.
References numero_op_.
Referenced by get_champ().
Operateur() [2/2]
Operateur_base & Champ_Post_Operateur_Eqn::Operateur () override virtual
Implements Champ_Generique_Operateur_base.
References numero_op_.
completer()
void Champ_Post_Operateur_Eqn::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Gen_de_Champs_Gen::completer(), Domaine_dis_base::domaine(), Probleme_base::equation(), Process::exit(), Domaine_VF::face_sommets(), Champ_Generique_base::get_champ(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Champ_Gen_de_Champs_Gen::get_source(), Equation_base::inconnue(), Field_base::le_nom(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), localisation_inco_, Probleme_base::nombre_d_equations(), Champ_Gen_de_Champs_Gen::OWN_PTR(), Objet_U::que_suis_je(), MD_Vector::valeur(), Champ_Inc_base::valeurs(), and verification_cas_compo().
nommer_source()
void Champ_Post_Operateur_Eqn::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References compo_, Champ_Generique_base::nom_post_, Champ_Generique_base::nommer(), numero_masse_, numero_op_, and numero_source_.
set_param()
void Champ_Post_Operateur_Eqn::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Param::ajouter(), Param::ajouter_flag(), compo_, numero_masse_, numero_op_, numero_source_, sans_solveur_masse_, and Champ_Gen_de_Champs_Gen::set_param().
verification_cas_compo()
void Champ_Post_Operateur_Eqn::verification_cas_compo () const
References compo_, and Process::exit().
Referenced by completer().
OBS_PTR()
Champ_Post_Operateur_Eqn::OBS_PTR (Equation_base) protected
Member Data Documentation
numero_source_
int Champ_Post_Operateur_Eqn::numero_source_ protected
Referenced by get_champ(), nommer_source(), and set_param().
numero_op_
int Champ_Post_Operateur_Eqn::numero_op_ protected
Referenced by get_champ(), nommer_source(), Operateur(), Operateur(), and set_param().
numero_masse_
int Champ_Post_Operateur_Eqn::numero_masse_ protected
Referenced by get_champ(), nommer_source(), and set_param().
sans_solveur_masse_
bool Champ_Post_Operateur_Eqn::sans_solveur_masse_ = false protected
Referenced by get_champ(), and set_param().
localisation_inco_
Entity Champ_Post_Operateur_Eqn::localisation_inco_ = Entity::NODE protected
Referenced by completer(), get_champ_compo_without_evaluation(), and get_localisation().
compo_
int Champ_Post_Operateur_Eqn::compo_ protected
Referenced by get_champ(), get_property(), nommer_source(), set_param(), and verification_cas_compo().