CEA TRUST Platform: Champ_implementation_P1 Class Reference
Champ_implementation_P1 Class Reference abstract
#include <Champ_implementation_P1.h>
Static Public Member Functions
static void init_from_file (DoubleTab &val, const Domaine &dom, int nb_comp, double tolerance, Entree &input)
Constructor & Destructor Documentation
~Champ_implementation_P1()
Champ_implementation_P1::~Champ_implementation_P1 () inline override
Member Function Documentation
init_from_file()
void Champ_implementation_P1::init_from_file (DoubleTab & val, const Domaine & dom, int nb_comp, double tolerance, Entree & input) static
Initialise le tableau de valeurs aux sommets du domaine dom a partir de valeurs lues dans "input".
(on dimensionne, associe la structure parallele et remplit les valeurs reelles et virtuelles) Le fichier doit avoir le format suivant (n est le nombre de valeurs nodales stockees, x, y, z sont les coordonnees des sommets, compo1... sont les valeurs des composantes. n (int) x y [z] compo1 [compo2 [compo3 ... ]] (type double)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Octree_Double_32_64< _SIZE_ >::build_nodes(), Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_32_64< _SIZE_ >::creer_tableau_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Entree::get(), Domaine_32_64< _SIZE_ >::nb_som(), TRUSTArray< _TYPE_, _SIZE_ >::ref_array(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Octree_Double_32_64< _SIZE_ >::search_elements_box(), Octree_Double_32_64< _SIZE_ >::search_nodes_close_to(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
value_interpolation()
void Champ_implementation_P1::value_interpolation (const DoubleTab & positions, const ArrOfInt & cells, const DoubleTab & values, DoubleTab & resu, int ncomp = -1) const override protected virtual
Implements Champ_implementation_sommet.
References Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_Poly_base::elem_som_d(), Champ_implementation::get_domaine_dis(), Champ_implementation::get_domaine_geom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Domaine_Poly_base::vol_elem_som(), and Domaine_VF::volumes().
le_champ() [1/2]
Champ_base & Champ_implementation_P1::le_champ () override protected pure virtual
Implements Champ_implementation.
Implemented in Champ_Fonc_P1_base, and Champ_Inc_P1_base.
le_champ() [2/2]
const Champ_base & Champ_implementation_P1::le_champ () const override protected pure virtual
Implements Champ_implementation.
Implemented in Champ_Fonc_P1_base, and Champ_Inc_P1_base.