CEA TRUST Platform: Op_Conv_DI_L2_VEF_Face Class Reference
Op_Conv_DI_L2_VEF_Face Class Reference
#include <Op_Conv_DI_L2_VEF_Face.h>
Additional Inherited Members
Public Member Functions inherited from Op_Conv_VEF_base
double calculer_dt_stab () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe represente l'operateur de convection associe a une equation de transport d'un scalaire. La discretisation est VEF Le champ convecte est scalaire ou vecteur de type Champ_P1NC Le schema de convection est du type Amont
See also
Operateur_Conv_base
Member Function Documentation
associer_vitesse()
void Op_Conv_DI_L2_VEF_Face::associer_vitesse (const Champ_base & vit) override virtual
Implements Operateur_Conv_base.
ajouter()
DoubleTab & Op_Conv_DI_L2_VEF_Face::ajouter (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References Elem_VEF_base::calcul_vc(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_VEF::facette_normales(), Op_Conv_VEF_base::fluent_, Operateur_base::flux_bords_, Elem_VEF_base::KEL(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Op_VEF_Face::modifier_flux(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_premiere_face(), poly_DI_L2_2d(), poly_DI_L2_3d(), Milieu_base::porosite_face(), Domaine_VEF::rang_elem_non_std(), reconst_DI_L2_2d(), reconst_DI_L2_3d(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), Neumann_sortie_libre::val_ext(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse().
poly_DI_L2_2d()
void Op_Conv_DI_L2_VEF_Face::poly_DI_L2_2d (int N, int M, DoubleTab & derive, int poly, int ncomp, const DoubleTab & transporte, int & sing) const protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by ajouter().
poly_DI_L2_3d()
void Op_Conv_DI_L2_VEF_Face::poly_DI_L2_3d (int N, int M, DoubleTab & derive, int poly, int ncomp, const DoubleTab & transporte, int & sing) const protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_voisins(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by ajouter().
reconst_DI_L2_2d()
void Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_2d (DoubleTab & derive, int poly, double psc, int num1, int num2, const DoubleTab & transporte, int ncomp, DoubleTab & resu, DoubleVect & tab_fluent, int sing, int & nlim) const protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Champ_Inc_base::valeurs(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by ajouter().
reconst_DI_L2_3d()
void Op_Conv_DI_L2_VEF_Face::reconst_DI_L2_3d (DoubleTab & derive, int poly, double psc, int num1, int num2, const DoubleTab & transporte, int ncomp, DoubleTab & resu, DoubleVect & tab_fluent, int sing, int first, DoubleVect & trans, int & nlim) const protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Schema_Temps_base::pas_de_temps(), Equation_base::schema_temps(), Champ_Inc_base::valeurs(), Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by ajouter().