CEA TRUST Platform: Conduction Class Reference
Conduction Class Reference
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
void associer_solide (const Solide &)
const Motcle & domaine_application () const override
int impr (Sortie &os) const override
const Champ_Inc_base & inconnue () const override
Champ_Inc_base & inconnue () override
int lire_motcle_non_standard (const Motcle &, Entree &) override
void mettre_a_jour (double temps) override
const Milieu_base & milieu () const override
Milieu_base & milieu () override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
Solide & solide ()
const Solide & solide () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
de la temperature dans un solide de conductivite k et de masse volumique rho et chaleur specifique Cp (rho.Cp) . dT/dt - div (k grad T) = (rho.Cp) . f Les termes rho et Cp peuvent etre non uniformes car cette classe ne fait pas le raccourci de calculer la diffusivite k/(rho*Cp).
See also
Equation_base, Conduction
Constructor & Destructor Documentation
Conduction()
Conduction::Conduction ()
Member Function Documentation
set_param()
void Conduction::set_param (Param & param) override virtual
Reimplemented from Equation_base.
Reimplemented in Conduction_IBM.
References Param::ajouter_condition(), Param::ajouter_non_std(), and Equation_base::set_param().
Referenced by Conduction_IBM::set_param().
lire_motcle_non_standard()
int Conduction::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
References Operateur_Diff::associer_diffusivite(), Operateur_Diff::associer_diffusivite_pour_pas_de_temps(), diffusivite_pour_transport(), Equation_base::discretisation(), Process::exit(), Equation_base::lire_motcle_non_standard(), milieu(), and Objet_U::que_suis_je().
associer_solide()
void Conduction::associer_solide (const Solide & un_solide)
Associe le milieu solide a l'equation.
Parameters
(Solide& un_solide) le milieu solide a associer a l'equation
Referenced by associer_milieu_base().
associer_milieu_base()
void Conduction::associer_milieu_base (const Milieu_base & le_milieu) override virtual
Associe un milieu physique a l'equation, le milieu est en fait caste en Solide.
Parameters
(Milieu_base& un_milieu)
Implements Equation_base.
References associer_solide().
milieu() [1/2]
const Milieu_base & Conduction::milieu () const override virtual
Renvoie le milieu physique associe a l'equation.
Ici Solide upcaste en Milieu_base. (version const)
Returns
(Milieu_base&) le milieu physique associe a l'equation (Solide upcaste en Milieu_base)
Implements Equation_base.
References solide().
Referenced by diffusivite_pour_transport(), and lire_motcle_non_standard().
milieu() [2/2]
Milieu_base & Conduction::milieu () override virtual
Renvoie le milieu physique associe a l'equation.
Ici Solide upcaste en Milieu_base.
Returns
(Milieu_base&) le milieu physique associe a l'equation (Solide upcaste en Milieu_base)
Implements Equation_base.
References solide().
solide() [1/2]
const Solide & Conduction::solide () const
Renvoie le milieu solide associe a l'equation.
(version const)
Returns
(Solide&) le milieu solide associe a l'equation
Exceptions
pas de milieu solide associe a l'equation
References Process::exit(), Probleme_U::le_nom(), and Equation_base::probleme().
Referenced by milieu().
solide() [2/2]
Solide & Conduction::solide ()
Renvoie le milieu solide associe a l'equation.
Returns
(Solide&) le milieu solide associe a l'equation
Exceptions
pas de milieu solide associe a l'equation
References Process::exit().
nombre_d_operateurs()
int Conduction::nombre_d_operateurs () const override virtual
Renvoie le nombre d'operateurs de l'equation pour l'equation de conduction standart renvoie toujours 1.
Returns
(int) le nombre d'operateurs de l'equation
Implements Equation_base.
operateur() [1/2]
const Operateur & Conduction::operateur (int i) const override virtual
Renvoie l'operateur d'index specifie de l'equation.
Renvoie terme_diffusif si i=0 exit si i>0 (version const)
Parameters
(int i) index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur d'index specifie (uniquement terme_diffusif)
Exceptions
l'equation de conduction standard ne contient qu'un operateur
Implements Equation_base.
References Process::exit().
operateur() [2/2]
Operateur & Conduction::operateur (int i) override virtual
Renvoie l'operateur d'index specifie de l'equation.
Renvoie terme_diffusif si i=0 exit si i>0
Parameters
(int i) index de l'operateur a renvoyer
Returns
(Operateur&) l'operateur d'index specifie (uniquement terme_diffusif)
Exceptions
l'equation de conduction standard ne contient qu'un operateur
Implements Equation_base.
References Process::exit().
inconnue() [1/2]
const Champ_Inc_base & Conduction::inconnue () const inline override virtual
Renvoie le champ inconnue de l'equation, i. e. la temperature. (version const)
Returns
(Champ_Inc_base&) le champ inconnue de l'equation: la temperature
Implements Equation_base.
Referenced by Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), and Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne().
inconnue() [2/2]
Champ_Inc_base & Conduction::inconnue () inline override virtual
Renvoie le champ inconnue de l'equation, i. e. la temperature.
Returns
(Champ_Inc_base&) le champ inconnue de l'equation: la temperature
Implements Equation_base.
discretiser()
void Conduction::discretiser () override virtual
Discretise l'equation.
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::discretisation(), Equation_base::discretiser(), Equation_base::domaine_dis(), Equation_base::schema_temps(), and Discret_Thermique::temperature().
impr()
int Conduction::impr (Sortie & os) const override virtual
Imprime le terme diffusif sur un flot de sortie.
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
References Equation_base::impr().
domaine_application()
const Motcle & Conduction::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
mettre_a_jour()
void Conduction::mettre_a_jour (double temps) override virtual
La valeur de l'inconnue sur le pas de temps a ete calculee.
Cette methode avance le present jusqu'au temps passe en parametre. Elle met aussi a jour les proprietes du milieu.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Equation_base.
References Equation_base::mettre_a_jour().
diffusivite_pour_transport()
const Champ_Don_base & Conduction::diffusivite_pour_transport () const virtual
References Milieu_base::conductivite(), and milieu().
Referenced by lire_motcle_non_standard().
diffusivite_pour_pas_de_temps()
const Champ_base & Conduction::diffusivite_pour_pas_de_temps () const virtual
References Operateur_Diff::diffusivite().
creer_champ()
void Conduction::creer_champ (const Motcle & motlu) override virtual
Reimplemented from Equation_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Equation_base::champs_compris_, Equation_base::creer_champ(), Equation_base::discretisation(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), and Discret_Thermique::t_paroi().
get_champ()
const Champ_base & Conduction::get_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Equation_base::champs_compris_, Champs_compris_T< FIELD_TYPE >::get_champ(), Nom::getString(), Equation_base::has_champ(), Champ_Fonc_base::mettre_a_jour(), Equation_base::schema_temps(), Champ_base::temps(), and Schema_Temps_base::temps_init().
Referenced by has_champ().
get_noms_champs_postraitables()
void Conduction::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Reimplemented from Equation_base.
References Equation_base::champs_compris_, Equation_base::get_noms_champs_postraitables(), and Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
has_champ() [1/2]
bool Conduction::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
References get_champ(), and Equation_base::has_champ().
has_champ() [2/2]
bool Conduction::has_champ (const Motcle & nom) const override virtual
Reimplemented from Equation_base.
References Equation_base::has_champ().
OWN_PTR()
Conduction::OWN_PTR (Traitement_particulier_Solide_base) protected