CEA TRUST Platform: Solv_GCP Class Reference
Solv_GCP Class Reference
#include <Solv_GCP.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Solv_GCP()
Solv_GCP::Solv_GCP ()
References nb_it_max_, optimized_, precond_diag_, reinit_, and solv_iteratif::seuil_.
Member Function Documentation
resoudre_systeme() [1/2]
int Solv_GCP::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
References resoudre_().
Referenced by Op_Diff_RotRot::calculer_vorticite(), and Op_Diff_RotRot::tester().
resoudre_systeme() [2/2]
int Solv_GCP::resoudre_systeme (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int nmax) override virtual
Reimplemented from SolveurSys_base.
References resoudre_().
OWN_PTR() [1/3]
const Solv_GCP::OWN_PTR (Precond_base) const & inline
Referenced by set_precond().
OWN_PTR() [2/3]
Solv_GCP::OWN_PTR (Precond_base) & inline
set_precond()
void Solv_GCP::set_precond (const OWN_PTR(Precond_base)& pre) inline
References OWN_PTR().
reinit()
void Solv_GCP::reinit () override virtual
Reimplemented from SolveurSys_base.
References SolveurSys_base::reinit(), and reinit_.
supporte_matrice_morse_sym()
int Solv_GCP::supporte_matrice_morse_sym () inline override virtual
Reimplemented from SolveurSys_base.
get_flag_updated_input()
int Solv_GCP::get_flag_updated_input () const inline override virtual
Reimplemented from SolveurSys_base.
prepare_data()
void Solv_GCP::prepare_data (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution) protected
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), MD_Vector_tools::creer_md_vect_renum_auto(), Process::exit(), Matrice_Bloc::get_bloc(), Matrice_Morse::get_coeff(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector_base::get_nb_items_reels(), MD_Vector_base::get_nb_items_tot(), Matrice_Morse::get_set_coeff(), Matrice_SuperMorse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_SuperMorse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_SuperMorse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), Process::Journal(), Matrice_SuperMorse::lignes_non_vides_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), precond_diag_, TRUSTVect< _TYPE_, _SIZE_ >::ref_data(), TRUSTArray< _TYPE_, _SIZE_ >::ref_data(), reinit_, renum_, TRUSTVect< _TYPE_, _SIZE_ >::reset(), residu_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), resu_, TRUSTVect< _TYPE_, _SIZE_ >::set_md_vector(), Matrice_Morse::set_nb_columns(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), tmp_data_block_, tmp_mat_, tmp_mat_virt_, tmp_p_, tmp_p_avec_items_virt_, and tmp_solution_.
Referenced by resoudre_().
resoudre_()
int Solv_GCP::resoudre_ (const Matrice_Base & matrice, const DoubleVect & secmem, DoubleVect & solution, int nmax) protected
References Matrice_SuperMorse::ajouter_mult_vect_et_prodscal(), TRUSTVect< _TYPE_, _SIZE_ >::copy(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), SolveurSys_base::get_flag_updated_result(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), SolveurSys_base::limpr(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_sum(), Process::mpsum_multiple(), Matrice_Base::multvect(), Matrice_Base::multvect_(), Matrice_Morse_Sym::multvect_et_prodscal(), nb_it_max_, MD_Vector_base::nb_items_seq_tot(), optimized_, prepare_data(), TRUSTVect< _TYPE_, _SIZE_ >::ref(), TRUSTVect< _TYPE_, _SIZE_ >::reset(), residu_, resu_, solv_iteratif::seuil_, TRUSTVect< _TYPE_, _SIZE_ >::size_reelle(), TRUSTVect< _TYPE_, _SIZE_ >::size_reelle_ok(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), tmp_mat_, tmp_mat_virt_, tmp_p_, tmp_p_avec_items_virt_, and tmp_solution_.
Referenced by resoudre_systeme(), and resoudre_systeme().
OWN_PTR() [3/3]
Solv_GCP::OWN_PTR (Precond_base) protected
Member Data Documentation
optimized_
bool Solv_GCP::optimized_ protected
Referenced by resoudre_(), and Solv_GCP().
precond_diag_
bool Solv_GCP::precond_diag_ protected
Referenced by prepare_data(), and Solv_GCP().
tmp_p_avec_items_virt_
DoubleVect Solv_GCP::tmp_p_avec_items_virt_ protected
Referenced by prepare_data(), and resoudre_().
resu_
DoubleVect Solv_GCP::resu_ protected
Referenced by prepare_data(), and resoudre_().
residu_
DoubleVect Solv_GCP::residu_ protected
Referenced by prepare_data(), and resoudre_().
tmp_p_
DoubleVect Solv_GCP::tmp_p_ protected
Referenced by prepare_data(), and resoudre_().
tmp_solution_
DoubleVect Solv_GCP::tmp_solution_ protected
Referenced by prepare_data(), and resoudre_().
tmp_mat_
Matrice_Morse_Sym Solv_GCP::tmp_mat_ protected
Referenced by prepare_data(), and resoudre_().
tmp_mat_virt_
Matrice_SuperMorse Solv_GCP::tmp_mat_virt_ protected
Referenced by prepare_data(), and resoudre_().
tmp_data_block_
ArrOfDouble Solv_GCP::tmp_data_block_ protected
Referenced by prepare_data().
renum_
IntVect Solv_GCP::renum_ protected
Referenced by prepare_data().
inv_sqrt_diag_
DoubleVect Solv_GCP::inv_sqrt_diag_ protected
reinit_
int Solv_GCP::reinit_ protected
Referenced by prepare_data(), reinit(), and Solv_GCP().
nb_it_max_
int Solv_GCP::nb_it_max_ protected
Referenced by resoudre_(), and Solv_GCP().