CEA TRUST Platform: Domaine_32_64< _SIZE_ > Class Template Reference
Domaine_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void ajouter (const DoubleTab_t &soms)
void ajouter (const DoubleTab_t &soms, IntVect_t &nums)
int associer_ (Objet_U &) override
Bord_Interne_t & bords_interne (int i)
void build_mc_mesh () const
void calculer_centres_gravite (DoubleTab_t &xp) const
void calculer_centres_gravite_aretes (DoubleTab_t &xa) const
virtual void calculer_volumes (DoubleVect_t &volumes, DoubleVect_t &inv_volumes) const
SmallArrOfTID_t & chercher_aretes (const DoubleTab &pos, SmallArrOfTID_t &arr, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleTab &pos, SmallArrOfTID_t &elem, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleVect &pos, SmallArrOfTID_t &elem, int reel=0) const
int_t chercher_elements (double x, double y=0, double z=0, int reel=0) const
SmallArrOfTID_t & chercher_sommets (const DoubleTab &pos, SmallArrOfTID_t &som, int reel=0) const
int_t chercher_sommets (double x, double y=0, double z=0, int reel=0) const
virtual void clear ()
void construire_elem_virt_pe_num ()
void correct_type_of_borders_after_merge ()
virtual void creer_tableau_elements (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
virtual void creer_tableau_sommets (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
void ecrire_noms_bords (Sortie &) const
int_t face_bords_interne_conjuguee (int_t face) const
void fill_from_list (std::list< Domaine_32_64 * > &lst)
const Frontiere_t & frontiere (int i) const
const ArrOfInt_t & ind_faces_virt_bord () const
SmallArrOfTID_t & indice_elements (const IntTab &som, SmallArrOfTID_t &elem, int reel=0) const
void init_renum_perio ()
const LIST (OBS_PTR(Domaine_32_64)) &domaines_frontieres() const
int nb_bords () const
int nb_faces_elem (int=0) const
int_t nb_faces_frontiere (Type_Face type) const
int_t nb_faces_specifiques () const
int_t nb_faces_specifiques (Type_Face type) const
int nb_groupes_faces () const
int nb_joints () const
int nb_raccords () const
int nb_som_elem () const
void renum (const IntVect_t &nums)
void renum_joint_common_items (const IntVect_t &nums, const int_t elem_offset)
void typer (const Nom &)
Public Member Functions inherited from Domaine_base
const Nom & le_nom () const override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static int identifie_item_unique (IntList &item_possible, DoubleTab &coord_possible, const DoubleVect &coord_ref)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Additional Inherited Members
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Domaine_32_64< _SIZE_ >
Les differents types d'elements sont des objets de classes derivees de Elem_geom_base. Une domaine est constitue de noeuds, d'elements, de bords, de bords periodiques, de joints, de raccords et de bords internes.
This class is templatized on the 32/64 bit configuration. All the methods/members not sensitive to this are in Domaine_base.
See also
Domaine, Domaine_64, Sous_Domaine, Frontiere, Elem_geom, Elem_geom_base, Bord, Bord_perio, Joint, Raccord, Bords_Interne
This include file should be used in place of the former
 class Domaine;
forward declaration.
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntVect_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
ArrOfDouble_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::ArrOfDouble_t = ArrOfDouble_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
ArrsOfInt_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::ArrsOfInt_t = ArrsOfInt_T<_SIZE_>
DoubleTabs_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::DoubleTabs_t = DoubleTabs_T<_SIZE_>
OctreeRoot_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::OctreeRoot_t = OctreeRoot_32_64<_SIZE_>
Sous_Domaine_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Sous_Domaine_t = Sous_Domaine_32_64<_SIZE_>
Bord_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Bord_t = Bord_32_64<_SIZE_>
Bords_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Bords_t = Bords_32_64<_SIZE_>
Bord_Interne_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Bord_Interne_t = Bord_Interne_32_64<_SIZE_>
Bords_Internes_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Bords_Internes_t = Bords_Internes_32_64<_SIZE_>
Groupe_Faces_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Groupe_Faces_t = Groupe_Faces_32_64<_SIZE_>
Groupes_Faces_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Groupes_Faces_t = Groupes_Faces_32_64<_SIZE_>
Frontiere_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Frontiere_t = Frontiere_32_64<_SIZE_>
Raccord_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Raccord_t = OWN_PTR(Raccord_base_32_64<_SIZE_>)
Raccords_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Raccords_t = Raccords_32_64<_SIZE_>
Joint_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Joint_t = Joint_32_64<_SIZE_>
Joints_t
template<typename _SIZE_ > using Domaine_32_64< _SIZE_ >::Joints_t = Joints_32_64<_SIZE_>
Constructor & Destructor Documentation
Domaine_32_64()
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::Domaine_32_64 () inline
References Domaine_32_64< _SIZE_ >::clear().
Member Function Documentation
typer()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::typer (const Nom & typ) inline
Type les elements du domaine avec le nom passe en parametre.
Et associe le type d'element au domaine.
Parameters
(Nom& typ) le nom du type des elements geometriques du domaine.
Referenced by DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Decouper_Bord_coincident::decouper_(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Extraire_surface::extraire_surface_without_cleaning(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Lire_Tgrid::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), LireMED_32_64< _SIZE_ >::lire_geom(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Domaine_VEF::typer_elem(), Domaine_EF::typer_elem(), Domaine_Poly_base::typer_elem(), and Refine_Mesh::update_octree().
OWN_PTR() [1/4]
template<typename _SIZE_ > const Domaine_32_64< _SIZE_ >::OWN_PTR (Elem_geom_base_32_64< _SIZE_ >) const & inline
OWN_PTR() [2/4]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::OWN_PTR (Elem_geom_base_32_64< _SIZE_ >) & inline
reordonner()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::reordonner () inline
Referenced by TroisDto2D_32_64< _SIZE_ >::extraire_2D(), LireMED_32_64< _SIZE_ >::lire_geom(), and Remove_elem::remove_elem_().
coord() [1/2]
template<typename _SIZE_ > double Domaine_32_64< _SIZE_ >::coord (int_t i, int j) const inline
References Domaine_32_64< _SIZE_ >::sommets_.
Referenced by Rectangle_axi_32_64< _SIZE_ >::calculer_centres_gravite(), Hexaedre_axi_32_64< _SIZE_ >::calculer_centres_gravite(), Faces_VDF::calculer_orientation(), Faces_32_64< _SIZE_ >::calculer_surfaces(), Polyedre_32_64< _SIZE_ >::calculer_un_centre_gravite(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Segment_axi_32_64< _SIZE_ >::calculer_volumes(), Hexaedre_axi_32_64< _SIZE_ >::calculer_volumes(), Hexaedre_VEF_32_64< _SIZE_ >::calculer_volumes(), Rectangle_32_64< _SIZE_ >::calculer_volumes(), Rectangle_axi_32_64< _SIZE_ >::calculer_volumes(), Segment_32_64< _SIZE_ >::calculer_volumes(), Tetraedre_32_64< _SIZE_ >::calculer_volumes(), Hexaedre_32_64< _SIZE_ >::contient(), Hexaedre_axi_32_64< _SIZE_ >::contient(), Point_32_64< _SIZE_ >::contient(), Prisme_32_64< _SIZE_ >::contient(), Quadrangle_VEF_32_64< _SIZE_ >::contient(), Rectangle_32_64< _SIZE_ >::contient(), Rectangle_axi_32_64< _SIZE_ >::contient(), Segment_32_64< _SIZE_ >::contient(), Triangle_32_64< _SIZE_ >::contient(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Op_Diff_VEF_Face_Penalise::longueur(), OctreeRoot_32_64< _SIZE_ >::rang_sommet(), Segment_32_64< _SIZE_ >::reordonner(), Rectangle_32_64< _SIZE_ >::reordonner_elem(), Champ_Face_VDF_implementation::valeur_a_elem_compo(), Champ_base::valeur_a_sommet(), Champ_Q1NC_implementation::valeur_a_sommet_compo(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets(), Champ_Face_VDF_implementation::valeur_aux_sommets_compo(), and Champ_Q1NC_implementation::valeur_aux_sommets_compo().
coord() [2/2]
template<typename _SIZE_ > double& Domaine_32_64< _SIZE_ >::coord (int_t i, int j) inline
References Domaine_32_64< _SIZE_ >::sommets_.
coord_sommets()
template<typename _SIZE_ > const DoubleTab_t& Domaine_32_64< _SIZE_ >::coord_sommets () const inline
References Domaine_32_64< _SIZE_ >::sommets_.
Referenced by Champ_P1_isoP1Bulle::affecter_(), Champ_P1NC::affecter_(), Op_Grad_EF::ajouter_bord(), Domaine_EF::calculer_Bij(), Domaine_EF_axi::calculer_Bij_gen(), Faces_32_64< _SIZE_ >::calculer_centres_gravite(), EDO_Pression_th_VEF::calculer_grad(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Domaine_EF_axi::calculer_IPhi(), Hexaedre_32_64< _SIZE_ >::calculer_normales(), Rectangle_32_64< _SIZE_ >::calculer_normales(), Tetraedre_32_64< _SIZE_ >::calculer_normales(), Triangle_32_64< _SIZE_ >::calculer_normales(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Reordonner_faces_periodiques_32_64< _SIZE_ >::chercher_direction_perio(), Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), OctreeRoot_32_64< _SIZE_ >::construire(), Octree_32_64< _SIZE_ >::construire(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Hexa_VEF::creer_normales_facettes_Cl(), Tetraedriser_homogene_compact::creer_sommet(), Tetraedriser_homogene_fin::creer_sommet(), DecoupeBord_32_64< _SIZE_ >::decouper(), Decouper_Bord_coincident::decouper_(), Domaine_Poly_base::detecter_faces_non_planes(), Domaine_Poly_base::discretiser(), Domaine_Poly_base::discretiser_aretes(), Domaine_VDF::dist_face_period(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_PolyMAC_P0::fgrad(), Champ_Generique_Transformation::get_champ(), Champ_Generique_Interpolation::get_ref_coordinates(), Champ_Generique_refChamp::get_ref_coordinates(), Domaine_Cl_EF::imposer_cond_lim(), Champ_Elem_DG::imprime(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Champ_P1_VEF::imprime(), Champ_Q4_implementation::imprime_Q4(), Echange_contact_Correlation_VEF::init(), Domaine_VF::init_dist_paroi_globale(), Domaine_PolyMAC::init_m1_2d(), Champ_Face_PolyMAC::init_ra(), Domaine_PolyMAC::init_rf(), Champ_Face_PolyMAC::init_va(), Domaine_PolyMAC::init_we_2d(), Decouper_multi::interpreter(), Distanceparoi::interpreter_(), Extruder_en3::interpreter_(), Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Domaine_PolyMAC_P0P1NC::M1(), Assembleur_P_VEFPreP1B::modifier_matrice(), Hexa_EF::normale(), Quadri_EF::normale(), Segment_EF_axi::normale(), Tetra_EF::normale(), Tri_EF::normale(), Hexa_poly::normale(), Polyedre_poly::normale(), Polygone_poly::normale(), Quadri_poly::normale(), Tetra_poly::normale(), Tri_poly::normale(), Hexa_VEF::normale(), Quadri_VEF::normale(), Tetra_VEF::normale(), Tri_VEF::normale(), Domaine_Poly_base::orthocentrer(), Debog_Pb::read_geometry_data(), Champ_Q4_implementation::remplir_coord_noeuds(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Reorienter_tetraedres_32_64< _SIZE_ >::reorienter(), Reorienter_triangles_32_64< _SIZE_ >::reorienter(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Trianguler_fin::trianguler(), Champ_P1NC_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_base::valeur_aux_sommets(), Champ_implementation::valeur_aux_sommets(), Champ_base::valeur_aux_sommets_compo(), Champ_implementation::valeur_aux_sommets_compo(), Domaine_VEF::vecteur_face_facette(), Domaine_Poly_base::vol_elem_som(), and Domaine_PolyMAC_P0P1NC::W1().
les_sommets() [1/2]
template<typename _SIZE_ > DoubleTab_t& Domaine_32_64< _SIZE_ >::les_sommets () inline
References Domaine_32_64< _SIZE_ >::sommets_.
Referenced by Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Refine_Mesh::build_new_nodes(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Navier_Stokes_std::calculer_pression_hydrostatique(), Faces_32_64< _SIZE_ >::calculer_surfaces(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Scatter::check_consistancy_remote_items(), Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Champ_Generique_Extraction::completer(), Champ_Generique_Reduction_0D::completer(), Champ_Generique_Transformation::completer(), Domaine_DG::compute_mesh_param(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Scatter::construire_structures_paralleles(), Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Remove_elem::creer_faces(), Decouper_Bord_coincident::decouper_(), Domaine_VEF::discretiser_arete(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Extraire_surface::extraire_surface_without_cleaning(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Scatter::init_sequential_domain(), Sonde::initialiser(), Moyenne_volumique::interpreter(), Lata_2_Other::interpreter(), Dilate::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Lire_Tgrid::interpreter_(), Redresser_hexaedres_vdf::interpreter_(), VerifierCoin::interpreter_(), LireMED_32_64< _SIZE_ >::lire_geom(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), Raffiner_anisotrope_32_64< _SIZE_ >::raffiner_(), Scatter::read_domain_no_comm(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), Remove_elem::remove_elem_(), Hexaedre_VEF_32_64< _SIZE_ >::reordonner(), Scatter::reordonner_faces_de_joint(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Q1NC_implementation::transforme_coord2D(), Champ_Q1NC_implementation::transforme_coord3D(), Transformer_32_64< _SIZE_ >::transformer(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Scatter::uninit_sequential_domain(), Refine_Mesh::update_nodes(), and NettoieNoeuds_32_64< _SIZE_ >::verifie_noeuds().
les_sommets() [2/2]
template<typename _SIZE_ > const DoubleTab_t& Domaine_32_64< _SIZE_ >::les_sommets () const inline
References Domaine_32_64< _SIZE_ >::sommets_.
saveSommetsCoordinates()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::saveSommetsCoordinates () inline
References Domaine_32_64< _SIZE_ >::sommets_, and Domaine_32_64< _SIZE_ >::sommets_n.
resetSommetsCoordinates()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::resetSommetsCoordinates () inline
References Domaine_32_64< _SIZE_ >::sommets_, and Domaine_32_64< _SIZE_ >::sommets_n.
getBoundingBox()
template<typename _SZ_ > DoubleTab Domaine_32_64< _SZ_ >::getBoundingBox
ajouter() [1/2]
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::ajouter (const DoubleTab_t & soms)
Ajoute des noeuds (ou sommets) au domaine (sans verifier les doublons)
Parameters
(DoubleTab& soms) le tableau contenant les coordonnees des noeuds a ajouter au domaine
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTTab< _TYPE_, _SIZE_ >::dimension_int().
Referenced by ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Extruder_en3::interpreter_(), and Scatter::read_domain_no_comm().
ajouter() [2/2]
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::ajouter (const DoubleTab_t & soms, IntVect_t & nums)
Ajoute des noeuds au domaine avec elimination des noeuds double au retour nums contient les nouveaux numeros des noeuds de soms.
apres elimination des doublons.
Parameters
(DoubleTab& soms) le tableau contenant les coordonnees des noeuds a ajouter au domaine
(IntVect& nums) le tableau des nouveaux numeros apres ajout des nouveaux noeuds et elimination des doublons.
Exceptions
des noeuds double ont ete trouve
References Octree_Double_32_64< _SIZE_ >::build_nodes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Octree_Double_32_64< _SIZE_ >::search_elements_box(), Octree_Double_32_64< _SIZE_ >::search_nodes_close_to(), TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
nb_som()
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_som () const inline
Renvoie le nombre de sommets du domaine.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and Domaine_32_64< _SIZE_ >::sommets_.
Referenced by Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Assembleur_P_EF::assembler_mat(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_espace_distant_sommets(), EDO_Pression_th_VEF::calculer_grad(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Source_PDF_EF::calculer_variable_imposee_elem_fluid(), Source_PDF_EF::calculer_variable_imposee_hybrid(), Source_PDF_EF::calculer_variable_imposee_mean_grad(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Domain_Graph::construire_graph_elem_elem(), Partitionneur_Partition::construire_partition(), Scatter::corriger_espace_distant_elements_perio(), Champ_Fonc_MED::creer(), Decouper_Bord_coincident::decouper_(), Postraiter_domaine::ecrire(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Source_PDF_EF::get_champ(), Domaine_Cl_EF::imposer_symetrie_matrice_secmem(), Champ_Elem_DG::imprime(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_P0_EF::imprime(), Champ_P1_EF::imprime(), Champ_Q1_EF::imprime(), Champ_Elem_PolyMAC::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Som_PolyMAC::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Champ_P1_VEF::imprime(), Postraitement::init(), Champ_Face_PolyMAC_P0::init_ve2(), Decouper_multi::interpreter(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), Domaine_dis_base::nb_som(), Postraitement::postraiter_champs(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets(), Champ_Face_VDF_implementation::valeur_aux_sommets_compo(), Champ_Q1NC_implementation::valeur_aux_sommets_compo(), and Champ_P1NC_implementation::valeur_aux_sommets_compo().
nb_som_tot()
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_som_tot () const inline
Renvoie le nombre total de sommets du domaine i.e. le nombre de sommets reels et virtuels sur le processeur courant.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), and Domaine_32_64< _SIZE_ >::sommets_.
Referenced by Op_Dift_VEF_P1NCP1B_Face::ajouter(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Div_VEFP1B_Elem::ajouter_som(), Assembleur_P_EF::assembler_mat(), Source_PDF_EF::compute_coeff_matrice(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Triangle_32_64< _SIZE_ >::contient(), Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_liste(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Champ_P1NC_implementation::filtrer_H1(), Champ_Generique_Transformation::get_champ(), Domaine_Cl_EF::imposer_symetrie(), Champ_Q4_implementation::imprime_Q4(), Domaine_PolyMAC::init_m1_2d(), Domaine_PolyMAC_P0::init_stencils(), DomaineCutter_32_64< _SIZE_ >::initialiser(), Distanceparoi::interpreter_(), Extraire_surface::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Domaine_dis_base::nb_som_tot(), Domaine_Cl_EF::remplir_type_elem_Cl(), Source_PDF_EF::rotate_imposed_velocity(), Op_Diff_VEFP1NCP1B_Face::test(), and Champ_P1NC_implementation::valeur_aux_sommets().
read_vertices()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::read_vertices (Entree & s)
only read vertices from the stream s
Referenced by Scatter::read_domain_no_comm().
les_elems() [1/2]
template<typename _SIZE_ > IntTab_t& Domaine_32_64< _SIZE_ >::les_elems () inline
References Domaine_32_64< _SIZE_ >::mes_elems_.
Referenced by Champ_P1_isoP1Bulle::affecter_(), Op_Div_EF::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Source_PDF_EF::ajouter_(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Assembleur_P_EF::assembler_mat(), Refine_Mesh::build_edges(), Refine_Mesh::build_new_cells_2D(), Refine_Mesh::build_new_cells_3D(), Champ_Q1_EF::calcul_y_plus(), Domaine_EF::calculer_Bij(), Domaine_EF::calculer_Bij_gen(), Domaine_EF_axi::calculer_Bij_gen(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Scatter::calculer_espace_distant_elements(), Scatter::calculer_espace_distant_sommets(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Domaine_EF_axi::calculer_IPhi(), Domaine_EF::calculer_volumes_sommets(), Discretisation_tools::cells_to_nodes(), Assembleur_P_VEFPreP1B::changer_base(), Rectify_Mesh::check_cell_enumeration_3D(), Rectify_Mesh::check_cell_orientation_2D(), Rectify_Mesh::check_cell_orientation_3D(), Champ_Generique_Reduction_0D::completer(), Champ_Generique_Transformation::completer(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Domaine_DG::compute_mesh_param(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Octree_32_64< _SIZE_ >::construire(), Extruder_en3::construire_bords(), Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Scatter::construire_structures_paralleles(), Point_32_64< _SIZE_ >::contient(), Source_PDF_EF::contribuer_a_avec(), Source_PDF_EF::correct_incr_pressure(), Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_liste(), Scatter::corriger_espace_distant_elements_perio(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Hexa_VEF::creer_normales_facettes_Cl(), Decouper_Bord_coincident::decouper_(), Op_EF_base::dimensionner(), Postraiter_domaine::ecrire(), Domaine_Poly_base::elem_som_d(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extruder::extruder_hexa(), Champ_input_P0::getTemplate(), Champ_Q1_EF::gradient(), Scatter::init_sequential_domain(), Domaine_PolyMAC_P0::init_stencils(), Champ_Face_PolyMAC_P0::init_ve2(), Sonde::initialiser(), DomaineCutter_32_64< _SIZE_ >::initialiser(), Decouper_multi::interpreter(), Distanceparoi::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Lire_Tgrid::interpreter_(), VerifierCoin::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), LireMED_32_64< _SIZE_ >::lire_geom(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), Discretisation_base::mesh_numbering(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), Discretisation_tools::nodes_to_cells(), Polyedre_poly::normale(), Champ_P1_isoP1Bulle::norme_L2(), Domaine_VF::numero_sommet_local(), Domaine_Poly_base::orthocentrer(), Assembleur_P_VEFPreP1B::projete_L2(), Domaine_Poly_base::pvol_som(), Debog_Pb::read_geometry_data(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), Remove_elem::remove_elem_(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Hexaedre_VEF_32_64< _SIZE_ >::reordonner(), Reorienter_tetraedres_32_64< _SIZE_ >::reorienter(), Reorienter_triangles_32_64< _SIZE_ >::reorienter(), Source_PDF_EF::rotate_imposed_velocity(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler::trianguler(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), Scatter::uninit_sequential_domain(), Refine_Mesh::update_cells(), Champ_P1NC_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_P1NC_implementation::valeur_aux_sommets(), Domaine_VEF::vecteur_face_facette(), Source_PDF_EF::verif_ajouter_contrib(), and Domaine_Poly_base::vol_elem_som().
les_elems() [2/2]
template<typename _SIZE_ > const IntTab_t& Domaine_32_64< _SIZE_ >::les_elems () const inline
References Domaine_32_64< _SIZE_ >::mes_elems_.
nb_elem()
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_elem () const inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and Domaine_32_64< _SIZE_ >::mes_elems_.
Referenced by Champ_Elem_DG::affecter_(), Champ_Fonc_P1_DG::affecter_(), Op_Div_EF::ajouter(), Assembleur_P_EF::assembler_mat(), Terme_Source_Solide_SWIFT_VDF::calcul_moyenne(), Champ_Face_VDF::calcul_S_barre_sans_contrib_paroi(), Moyenne_volumique::calculer_convolution_champ_elem(), Op_Diff_DG_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Domaine_EF::calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), Modele_turbulence_hyd_LES_VDF_base::calculer_longueurs_caracteristiques(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_Profils_thermo_VDF::calculer_moyennes_spatiales_thermo(), Traitement_particulier_Solide_canal_VDF::calculer_moyennes_spatiales_thermo(), Op_Dift_VEF_base::calculer_pour_post(), Modele_turbulence_hyd_LES_Smago_VDF::calculer_viscosite_turbulente(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_viscosite_turbulente(), OctreeRoot_32_64< _SIZE_ >::construire(), Domain_Graph::construire_graph_elem_elem(), Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), Partitionneur_Partition::construire_partition(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Scatter::corriger_espace_distant_elements_perio(), Champ_Fonc_MED::creer(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Postraiter_domaine::ecrire(), Champ_Elem_DG::eval_elem(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Inc_P0_base::fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_Generique_Transformation::get_champ(), Modele_turbulence_hyd_0_eq_base::imprimer(), Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne(), Traitement_particulier_Solide_canal_VDF::init_calcul_moyenne(), Terme_Source_Solide_SWIFT_VDF::init_calcul_moyenne(), Terme_Source_Canal_RANS_LES_VDF_Face::init_calcul_moyenne_spat(), Champ_Face_PolyMAC_P0::init_ve2(), Champ_Face_PolyMAC::interp_gve(), Moyenne_volumique::interpreter(), Create_domain_from_sub_domain::interpreter_(), VerifierCoin::interpreter_(), Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Correlation_Vec_Sca_VDF::mettre_a_jour(), Domaine_dis_base::nb_elem(), Champ_P1NC::norme_H1(), Scatter::read_domain_no_comm(), Assembleur_P_VEF::remplir(), Champ_Q4_implementation::remplir_coord_noeuds_et_polys(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Traitement_particulier_NS_canal_VDF::remplir_Y(), Hexaedre_VEF_32_64< _SIZE_ >::reordonner(), Champ_Face_PolyMAC_P0::update_ve2(), and TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_compo().
nb_elem_tot()
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_elem_tot () const inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), and Domaine_32_64< _SIZE_ >::mes_elems_.
Referenced by Champ_Elem_PolyMAC_P0P1NC::affecter_(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Source_PDF_EF::ajouter_(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Assembleur_P_EF::assembler_mat(), Champ_Q1_EF::cal_rot_ordre1(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Champ_Face_VDF::calcul_duidxj(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Conv_EF::calculer_dt_stab(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Modele_turbulence_hyd_LES_Wale_VDF::calculer_OP1_OP2(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Hexaedre_axi_32_64< _SIZE_ >::calculer_volumes(), Hexaedre_VEF_32_64< _SIZE_ >::calculer_volumes(), Rectangle_32_64< _SIZE_ >::calculer_volumes(), Rectangle_axi_32_64< _SIZE_ >::calculer_volumes(), Domaine_EF::calculer_volumes_sommets(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Champ_Elem_DG::compute_stab_param(), OctreeRoot_32_64< _SIZE_ >::construire(), Partitionneur_Partition::construire_partition(), Partitionneur_Sous_Domaines::construire_partition(), Triangle_32_64< _SIZE_ >::contient(), Source_PDF_EF::contribuer_a_avec(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Postraiter_domaine::ecrire(), Champ_Face_base::get_elem_vector_field(), Champ_Q1_EF::gradient(), Champ_implementation_P0::imprime_P0(), Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables(), DomaineCutter_32_64< _SIZE_ >::initialiser(), Perte_Charge_Singuliere::lire_surfaces(), Domaine_dis_base::nb_elem_tot(), Assembleur_P_VEF::remplir(), Porosites::remplir_champ(), Traitement_particulier_NS_canal_VDF::remplir_Tab_recap(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), Champ_Elem_PolyMAC_P0::reprendre(), Source_PDF_EF::rotate_imposed_velocity(), Champ_Face_PolyMAC_P0::trace(), Champ_Elem_PolyMAC::trace(), grad_Champ_Face_PolyMAC_P0::update_ge(), Champ_Face_PolyMAC_P0::update_ve(), Champ_Elem_PolyMAC::valeur_aux_faces(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Face_VDF_implementation::valeur_aux_sommets_compo(), Champ_Q1NC_implementation::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Source_PDF_EF::verif_ajouter_contrib(), Op_Div_EF::volumique(), Op_Div_PolyMAC::volumique(), and Op_Div_VDF_Elem::volumique().
nb_som_elem()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::nb_som_elem inline
Renvoie le nombre de sommets des elements geometriques constituants le domaine.
Tous les elements du domaine etant du meme type ils ont tous le meme nombre de sommets qui est le nombre de sommet du type des elements geometriques du domaine.
Returns
(int) le nombre de sommets par element
Referenced by Op_Diff_EF::ajouter(), Op_Dift_EF_Q1::ajouter(), Op_Div_EF::ajouter(), Source_Qdm_EF::ajouter(), Source_Scalaire_EF::ajouter(), Source_PDF_EF::ajouter_(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_EF::ajouter_contribution(), Op_Dift_EF_Q1::ajouter_contribution(), Op_Diff_EF::ajouter_contribution_new(), Op_Dift_EF_Q1::ajouter_contribution_new(), Op_Conv_EF::ajouter_contribution_sous_cond(), Op_Diff_EF::ajouter_new(), Op_Dift_EF_Q1::ajouter_new(), Op_Conv_EF::ajouter_sous_cond(), Champ_Q1_EF::calcul_y_plus(), Domaine_EF::calculer_Bij(), Domaine_EF::calculer_Bij_gen(), Domaine_EF_axi::calculer_Bij_gen(), Op_Conv_EF::calculer_dt_stab(), Scatter::calculer_espace_distant_elements(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Domaine_EF::calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), Domaine_EF::calculer_volumes_sommets(), Source_PDF_EF::compute_coeff_elem(), Source_PDF_EF::compute_coeff_matrice(), Source_PDF_EF::compute_indicateur_nodal_champ_aire(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Octree_32_64< _SIZE_ >::construire(), Source_PDF_EF::contribuer_a_avec(), Source_PDF_EF::correct_incr_pressure(), Op_EF_base::dimensionner(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Champ_Q1_EF::gradient(), ExtrudeBord::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Domaine_VF::numero_sommet_local(), OctreeRoot_32_64< _SIZE_ >::rang_sommet(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Source_PDF_EF::rotate_imposed_velocity(), Champ_Q4_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_Q4_implementation::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Face_VDF_implementation::valeur_aux_sommets_compo(), Champ_Q1NC_implementation::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), and Source_PDF_EF::verif_ajouter_contrib().
nb_faces_elem()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::nb_faces_elem (int i = 0) const inline
Renvoie le nombre de face de type i des elements geometriques constituants le domaine.
Ex: les objets de la classe Prisme ont 2 types de faces: triangle ou quadrangle.
Parameters
(int i) le type de face
Returns
(int) le nombre de face de type i des elements geometriques constituants le domaine
Referenced by Op_Diff_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Diff_VEF_Face_Stab::ajouter_antidiffusion(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_diffusion(), Op_Diff_VEF_Face_Stab::ajouter_operateur_centre(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Diff_VEF_Face_Penalise::autre_face(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_y_plus(), Domaine_EF::calculer_Bij_gen(), Domaine_EF_axi::calculer_Bij_gen(), Op_Diff_VEF_Face_Stab::calculer_coefficients(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_elem(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_gradients(), Domaine_EF::calculer_h_carre(), Domaine_Poly_base::calculer_h_carre(), Domaine_VEF::calculer_h_carre(), Domaine_PolyMAC::calculer_h_carre(), Paroi_negligeable_VEF::calculer_hyd(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Domaine_EF::calculer_volumes_entrelaces(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_VEF_Face::dimensionner(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Champ_P1NC_implementation::filtrer_L2(), Champ_Generique_Tparoi_VEF::get_champ(), Sonde::initialiser(), Perte_Charge_Singuliere::lire_surfaces(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Champ_P1NC::norme_H1(), Porosites::remplir_champ(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), and Op_Diff_VEF_Face_Penalise::voisinage().
sommet_elem()
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::sommet_elem (int_t i, int j) const inline
Renvoie le numero (global) du j-ieme sommet du i-ieme element.
References Domaine_32_64< _SIZE_ >::mes_elems_.
Referenced by Hexaedre_axi_32_64< _SIZE_ >::calculer_volumes(), Hexaedre_VEF_32_64< _SIZE_ >::calculer_volumes(), Rectangle_32_64< _SIZE_ >::calculer_volumes(), Rectangle_axi_32_64< _SIZE_ >::calculer_volumes(), Hexaedre_32_64< _SIZE_ >::contient(), Hexaedre_axi_32_64< _SIZE_ >::contient(), Hexaedre_VEF_32_64< _SIZE_ >::contient(), Rectangle_32_64< _SIZE_ >::contient(), Rectangle_axi_32_64< _SIZE_ >::contient(), Triangle_32_64< _SIZE_ >::contient(), Point_32_64< _SIZE_ >::contient(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Perte_Charge_Singuliere::lire_surfaces(), OctreeRoot_32_64< _SIZE_ >::rang_sommet(), Champ_Q4_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_Q4_implementation::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_Q1NC_implementation::valeur_aux_sommets(), Champ_Face_VDF_implementation::valeur_aux_sommets_compo(), Champ_Q1NC_implementation::valeur_aux_sommets_compo(), and Champ_P1NC_implementation::valeur_aux_sommets_compo().
nb_aretes()
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_aretes () const inline
Renvoie le nombre d'aretes reelles.
References Domaine_32_64< _SIZE_ >::aretes_som_, and TRUSTTab< _TYPE_, _SIZE_ >::dimension().
Referenced by PolyMAC_discretisation::discretiser_champ(), PolyMAC_P0P1NC_discretisation::discretiser_champ(), Champ_Face_PolyMAC::fixer_nb_valeurs_nodales(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_secmem(), and Domaine_VEF::verifie_ok_arete().
nb_aretes_tot()
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_aretes_tot () const inline
renvoie le nombre d'aretes total (reelles+virtuelles).
References Domaine_32_64< _SIZE_ >::aretes_som_, and TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot().
Referenced by Masse_PolyMAC_Face::appliquer_impl(), Domaine_VEF::construire_renum_arete_perio(), Domaine_Poly_base::discretiser_aretes(), Domaine_PolyMAC::init_m1_3d(), and Domaine_VEF::verifie_ok_arete().
arete_sommets()
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::arete_sommets (int_t i, int j) const inline
renvoie le numero du jeme sommet de la ieme arete.
References Domaine_32_64< _SIZE_ >::aretes_som_.
elem_aretes() [1/2]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::elem_aretes (int_t i, int j) const inline
renvoie le numero de la jeme arete du ieme element.
References Domaine_32_64< _SIZE_ >::elem_aretes_.
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Domaine_VEF::construire_renum_arete_perio(), Domaine_Poly_base::elem_arete_d(), Domaine_PolyMAC::init_m1_3d(), Domaine_PolyMAC_P0P1NC::M1(), Domaine_PolyMAC_P0P1NC::surf_elem_arete(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), and Domaine_PolyMAC_P0P1NC::W1().
aretes_som()
template<typename _SIZE_ > const IntTab_t& Domaine_32_64< _SIZE_ >::aretes_som () const inline
renvoie le tableau de connectivite aretes/sommets.
References Domaine_32_64< _SIZE_ >::aretes_som_.
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Domaine_VEF::construire_ok_arete(), Domaine_VEF::construire_renum_arete_perio(), Domaine_VEF::discretiser_arete(), Domaine_Poly_base::discretiser_aretes(), Domaine_PolyMAC_P0P1NC::M1(), Domaine_VEF::verifie_ok_arete(), Assembleur_P_VEFPreP1B::verifier_dirichlet(), and Domaine_PolyMAC_P0P1NC::W1().
elem_aretes() [2/2]
template<typename _SIZE_ > const IntTab_t& Domaine_32_64< _SIZE_ >::elem_aretes () const inline
renvoie le tableau de connectivite elements/aretes.
References Domaine_32_64< _SIZE_ >::elem_aretes_.
set_aretes_som()
template<typename _SIZE_ > IntTab_t& Domaine_32_64< _SIZE_ >::set_aretes_som () inline
References Domaine_32_64< _SIZE_ >::aretes_som_.
Referenced by Domaine_Poly_base::discretiser_aretes().
set_elem_aretes()
template<typename _SIZE_ > IntTab_t& Domaine_32_64< _SIZE_ >::set_elem_aretes () inline
References Domaine_32_64< _SIZE_ >::elem_aretes_.
Referenced by Domaine_Poly_base::discretiser_aretes().
nb_faces_bord() [1/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_bord () const inline
References Domaine_32_64< _SIZE_ >::mes_faces_bord_, and Bords_32_64< _SIZE_ >::nb_faces().
Referenced by DecoupeBord_32_64< _SIZE_ >::decouper().
nb_faces_bord() [2/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_bord (int num_bord) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_bord_, and Bords_32_64< _SIZE_ >::nb_faces().
nb_faces_bord() [3/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_bord (Type_Face type) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_bord_, and Bords_32_64< _SIZE_ >::nb_faces().
nb_faces_joint() [1/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_joint () const inline
References Domaine_32_64< _SIZE_ >::mes_faces_joint_, and Joints_32_64< _SIZE_ >::nb_faces().
Referenced by Domain_Graph::construire_graph_elem_elem().
nb_faces_joint() [2/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_joint (int num_joint) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_joint_, and Joints_32_64< _SIZE_ >::nb_faces().
nb_faces_joint() [3/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_joint (Type_Face type) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_joint_, and Joints_32_64< _SIZE_ >::nb_faces().
nb_faces_raccord() [1/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_raccord () const inline
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_, and Raccords_32_64< _SIZE_ >::nb_faces().
Referenced by DecoupeBord_32_64< _SIZE_ >::decouper().
nb_faces_raccord() [2/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_raccord (int num_rac) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_, and Raccords_32_64< _SIZE_ >::nb_faces().
nb_faces_raccord() [3/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_raccord (Type_Face type) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_, and Raccords_32_64< _SIZE_ >::nb_faces().
nb_faces_bords_int() [1/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_bords_int () const inline
References Domaine_32_64< _SIZE_ >::mes_bords_int_, and Bords_Internes_32_64< _SIZE_ >::nb_faces().
nb_faces_bords_int() [2/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_bords_int (int num_bord) const inline
References Domaine_32_64< _SIZE_ >::mes_bords_int_, and Bords_Internes_32_64< _SIZE_ >::nb_faces().
nb_faces_bords_int() [3/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_bords_int (Type_Face type) const inline
References Domaine_32_64< _SIZE_ >::mes_bords_int_, and Bords_Internes_32_64< _SIZE_ >::nb_faces().
nb_faces_groupes_faces() [1/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_groupes_faces () const inline
References Domaine_32_64< _SIZE_ >::mes_groupes_faces_, and Groupes_Faces_32_64< _SIZE_ >::nb_faces().
nb_faces_groupes_faces() [2/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_groupes_faces (int num_g) const inline
References Domaine_32_64< _SIZE_ >::mes_groupes_faces_, and Groupes_Faces_32_64< _SIZE_ >::nb_faces().
nb_faces_groupes_faces() [3/3]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::nb_faces_groupes_faces (Type_Face type) const inline
References Domaine_32_64< _SIZE_ >::mes_groupes_faces_, and Groupes_Faces_32_64< _SIZE_ >::nb_faces().
nb_faces_frontiere() [1/2]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::int_t Domaine_32_64< _SIZE_ >::nb_faces_frontiere inline
Renvoie le nombre de faces frontiere du domaine (somme des nombres de bords, de raccords et de bords internes)
Referenced by Domain_Graph::construire_graph_elem_elem(), Domaine_VF::nb_faces_bord(), Domaine_Cl_dis_base::nb_faces_Cl(), Domaine_EF::reordonner(), Domaine_Poly_base::reordonner(), Domaine_VDF::reordonner(), and Domaine_VEF::reordonner().
nb_faces_frontiere() [2/2]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::int_t Domaine_32_64< _SIZE_ >::nb_faces_frontiere (Type_Face type) const inline
Renvoie le nombre de faces frontiere du domaine du type specifie.
C'est la somme des nombres de bords, de raccords et de bords internes du type specifie.
Parameters
(Type_Face type) un type de face (certains elements geometriques ont plusieurs types de faces)
Returns
(int) le nombre de faces frontiere du domaine du type specifie
nb_faces_specifiques() [1/2]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::int_t Domaine_32_64< _SIZE_ >::nb_faces_specifiques inline
Renvoie le nombre de faces speciales du domaine.
C'est la somme des nombres de bords, de raccords, de bords internes et de groupes de faces specifies
nb_faces_specifiques() [2/2]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::int_t Domaine_32_64< _SIZE_ >::nb_faces_specifiques (Type_Face type) const inline
Renvoie le nombre de faces specifique du domaine du type specifie.
C'est la somme des nombres de bords, de raccords de bords internes et de groupes de faces du type specifie.
Parameters
(Type_Face type) un type de face (certains elements geometriques ont plusieurs types de faces)
Returns
(int) le nombre de faces frontiere du domaine du type specifie
face_bords_interne_conjuguee()
template<typename _SZ_ > Domaine_32_64< _SZ_ >::int_t Domaine_32_64< _SZ_ >::face_bords_interne_conjuguee (int_t face) const
Renvoie -1 si face n'est pas une face de bord interne Renvoie le numero de la face dupliquee sinon.
Parameters
(int face) le numero de la face de bord interne a chercher
Returns
(int) -1 si la face specifiee n'est pas une face de bord interne le numero de la face dupliquee sinon
Exceptions
erreur TRUST (face non trouvee)
References Process::exit(), and Faces_32_64< _SIZE_ >::nb_faces().
nb_bords()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::nb_bords () const inline
Bords
References Domaine_32_64< _SIZE_ >::mes_faces_bord_, and Bords_32_64< _SIZE_ >::nb_bords().
Referenced by Refine_Mesh::build_new_boundary_faces_2D(), Refine_Mesh::build_new_boundary_faces_3D(), DecoupeBord_32_64< _SIZE_ >::decouper(), Postraiter_domaine::ecrire(), Domaine_32_64< _SIZE_ >::nb_front_Cl(), and Domaine_VF::remplir_face_numero_bord().
bord() [1/4]
template<typename _SIZE_ > Bord_t& Domaine_32_64< _SIZE_ >::bord (int i) inline
References Domaine_32_64< _SIZE_ >::mes_faces_bord_.
Referenced by Scatter::corriger_espace_distant_elements_perio(), DecoupeBord_32_64< _SIZE_ >::decouper(), Postraiter_domaine::ecrire(), Modif_bord_to_raccord_32_64< _SIZE_ >::interpreter_(), SupprimeBord_32_64< _SIZE_ >::interpreter_(), TroisDto2D_32_64< _SIZE_ >::interpreter_(), Corriger_frontiere_periodique_32_64< _SIZE_ >::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), RegroupeBord_32_64< _SIZE_ >::regroupe_bord(), and Domaine_VF::remplir_face_numero_bord().
bord() [2/4]
template<typename _SIZE_ > const Bord_t& Domaine_32_64< _SIZE_ >::bord (int i) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_bord_.
bord() [3/4]
template<typename _SIZE_ > Bord_t& Domaine_32_64< _SIZE_ >::bord (const Nom & nom) inline
References Domaine_32_64< _SIZE_ >::mes_faces_bord_.
bord() [4/4]
template<typename _SIZE_ > const Bord_t& Domaine_32_64< _SIZE_ >::bord (const Nom & nom) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_bord_.
faces_bord() [1/2]
template<typename _SIZE_ > Bords_t& Domaine_32_64< _SIZE_ >::faces_bord () inline
References Domaine_32_64< _SIZE_ >::mes_faces_bord_.
Referenced by Extruder_en3::construire_bords(), DecoupeBord_32_64< _SIZE_ >::decouper(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), ExtrudeParoi::extrude(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), LireMED_32_64< _SIZE_ >::fill_frontieres(), Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), Create_domain_from_sub_domain::interpreter_(), Extraire_domaine::interpreter_(), Lire_Tgrid::interpreter_(), Modif_bord_to_raccord_32_64< _SIZE_ >::interpreter_(), SupprimeBord_32_64< _SIZE_ >::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), RegroupeBord_32_64< _SIZE_ >::regroupe_bord(), Remove_elem::remove_elem_(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), and Trianguler_fin::trianguler().
faces_bord() [2/2]
template<typename _SIZE_ > const Bords_t& Domaine_32_64< _SIZE_ >::faces_bord () const inline
References Domaine_32_64< _SIZE_ >::mes_faces_bord_.
fixer_premieres_faces_frontiere()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::fixer_premieres_faces_frontiere
Referenced by Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), Extraire_domaine::interpreter_(), Mailler_32_64< _SIZE_ >::interpreter_(), Modif_bord_to_raccord_32_64< _SIZE_ >::interpreter_(), and RegroupeBord_32_64< _SIZE_ >::regroupe_bord().
correct_type_of_borders_after_merge()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::correct_type_of_borders_after_merge
Correcting type of borders if they were empty before merge (ie equal to vide_0D)
Difference with corriger_type is that we don't want to delete faces inside borders afterwards. Int version handles joints, not the 64b one.
ecrire_noms_bords()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::ecrire_noms_bords (Sortie & os) const
Ecriture des noms des bords sur un flot de sortie.
Ecrit les noms des: bords, bords periodiques, raccords et groupes de faces.
Parameters
(Sortie& os) un flot de sortie
Referenced by Domaine_dis_base::ecrire_noms_bords().
bords_interne() [1/4]
template<typename _SIZE_ > Bord_Interne_t& Domaine_32_64< _SIZE_ >::bords_interne (int i) inline
Bords internes
References Domaine_32_64< _SIZE_ >::mes_bords_int_.
bords_interne() [2/4]
template<typename _SIZE_ > const Bord_Interne_t& Domaine_32_64< _SIZE_ >::bords_interne (int i) const inline
References Domaine_32_64< _SIZE_ >::mes_bords_int_.
bords_interne() [3/4]
template<typename _SIZE_ > Bord_Interne_t& Domaine_32_64< _SIZE_ >::bords_interne (const Nom & nom) inline
References Domaine_32_64< _SIZE_ >::mes_bords_int_.
bords_interne() [4/4]
template<typename _SIZE_ > const Bord_Interne_t& Domaine_32_64< _SIZE_ >::bords_interne (const Nom & nom) const inline
References Domaine_32_64< _SIZE_ >::mes_bords_int_.
bords_int() [1/2]
template<typename _SIZE_ > Bords_Internes_t& Domaine_32_64< _SIZE_ >::bords_int () inline
References Domaine_32_64< _SIZE_ >::mes_bords_int_.
Referenced by Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), and Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain().
bords_int() [2/2]
template<typename _SIZE_ > const Bords_Internes_t& Domaine_32_64< _SIZE_ >::bords_int () const inline
References Domaine_32_64< _SIZE_ >::mes_bords_int_.
nb_groupes_faces()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::nb_groupes_faces () const inline
Groupes_Faces
References Domaine_32_64< _SIZE_ >::mes_groupes_faces_, and Groupes_Faces_32_64< _SIZE_ >::nb_groupes_faces().
groupe_faces() [1/3]
template<typename _SIZE_ > Groupe_Faces_t& Domaine_32_64< _SIZE_ >::groupe_faces (int i) inline
References Domaine_32_64< _SIZE_ >::mes_groupes_faces_.
Referenced by Perte_Charge_Singuliere::lire_surfaces().
groupe_faces() [2/3]
template<typename _SIZE_ > const Groupe_Faces_t& Domaine_32_64< _SIZE_ >::groupe_faces (int i) const inline
References Domaine_32_64< _SIZE_ >::mes_groupes_faces_.
groupe_faces() [3/3]
template<typename _SIZE_ > const Groupe_Faces_t& Domaine_32_64< _SIZE_ >::groupe_faces (const Nom & nom) const inline
References Domaine_32_64< _SIZE_ >::mes_groupes_faces_.
groupes_faces() [1/2]
template<typename _SIZE_ > Groupes_Faces_t& Domaine_32_64< _SIZE_ >::groupes_faces () inline
References Domaine_32_64< _SIZE_ >::mes_groupes_faces_.
Referenced by LireMED_32_64< _SIZE_ >::fill_frontieres(), Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), and Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain().
groupes_faces() [2/2]
template<typename _SIZE_ > const Groupes_Faces_t& Domaine_32_64< _SIZE_ >::groupes_faces () const inline
References Domaine_32_64< _SIZE_ >::mes_groupes_faces_.
frontiere() [1/4]
template<typename _SIZE_ > const Domaine_32_64< _SIZE_ >::Frontiere_t & Domaine_32_64< _SIZE_ >::frontiere (int i) const inline
Frontieres
References Process::exit().
Referenced by Op_Div_VEFP1B_Elem::ajouter_som(), Reordonner_faces_periodiques_32_64< _SIZE_ >::chercher_direction_perio(), Conds_lim::completer(), DecoupeBord_32_64< _SIZE_ >::decouper(), Postraiter_domaine::ecrire(), Domaine_bord_32_64< _SIZE_ >::extraire_domaine_bord(), ExtrudeParoi::extrude(), Distanceparoi::interpreter_(), RegroupeBord_32_64< _SIZE_ >::interpreter_(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), RegroupeBord_32_64< _SIZE_ >::rassemble_bords(), and RegroupeBord_32_64< _SIZE_ >::regroupe_bord().
frontiere() [2/4]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::Frontiere_t & Domaine_32_64< _SIZE_ >::frontiere (int i) inline
References Process::exit().
rang_frontiere()
template<typename _SZ_ > int Domaine_32_64< _SZ_ >::rang_frontiere (const Nom & un_nom) const
References Process::exit().
Referenced by Postraiter_domaine::ecrire(), Distanceparoi::interpreter_(), SupprimeBord_32_64< _SIZE_ >::interpreter_(), and RegroupeBord_32_64< _SIZE_ >::regroupe_bord().
frontiere() [3/4]
template<typename _SZ_ > const Domaine_32_64< _SZ_ >::Frontiere_t & Domaine_32_64< _SZ_ >::frontiere (const Nom & un_nom) const
frontiere() [4/4]
template<typename _SZ_ > Domaine_32_64< _SZ_ >::Frontiere_t & Domaine_32_64< _SZ_ >::frontiere (const Nom & un_nom)
nb_frontieres_internes()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::nb_frontieres_internes () const inline
References Domaine_32_64< _SIZE_ >::mes_bords_int_, and Bords_Internes_32_64< _SIZE_ >::nb_bords_internes().
Referenced by Refine_Mesh::build_new_internal_frontier_faces_2D(), Refine_Mesh::build_new_internal_frontier_faces_3D(), and Domaine_32_64< _SIZE_ >::nb_front_Cl().
nb_front_Cl()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::nb_front_Cl () const inline
References Domaine_32_64< _SIZE_ >::nb_bords(), Domaine_32_64< _SIZE_ >::nb_frontieres_internes(), and Domaine_32_64< _SIZE_ >::nb_raccords().
Referenced by DecoupeBord_32_64< _SIZE_ >::decouper(), ExtrudeParoi::extrude(), RegroupeBord_32_64< _SIZE_ >::interpreter_(), Modele_turbulence_hyd_base::lire_motcle_non_standard(), Modele_turbulence_scal_base::lire_motcle_non_standard(), Domaine_dis_base::nb_front_Cl(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), RegroupeBord_32_64< _SIZE_ >::rassemble_bords(), and RegroupeBord_32_64< _SIZE_ >::regroupe_bord().
LIST() [1/4]
template<typename _SIZE_ > const Domaine_32_64< _SIZE_ >::LIST (OBS_PTR(Domaine_32_64< _SIZE_ >)) const & inline
Domaines frontieres
nb_raccords()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::nb_raccords () const inline
Raccords
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_, and Raccords_32_64< _SIZE_ >::nb_raccords().
Referenced by Refine_Mesh::build_new_connector_faces_2D(), Refine_Mesh::build_new_connector_faces_3D(), Postraiter_domaine::ecrire(), Domaine_32_64< _SIZE_ >::nb_front_Cl(), and Domaine_VF::remplir_face_numero_bord().
raccord() [1/4]
template<typename _SIZE_ > Raccord_t& Domaine_32_64< _SIZE_ >::raccord (int i) inline
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_.
Referenced by Echange_contact_VDF::calculer_h_autre_pb(), DecoupeBord_32_64< _SIZE_ >::decouper(), Postraiter_domaine::ecrire(), Echange_contact_VDF::initialiser(), SupprimeBord_32_64< _SIZE_ >::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), RegroupeBord_32_64< _SIZE_ >::regroupe_bord(), and Domaine_VF::remplir_face_numero_bord().
raccord() [2/4]
template<typename _SIZE_ > const Raccord_t& Domaine_32_64< _SIZE_ >::raccord (int i) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_.
raccord() [3/4]
template<typename _SIZE_ > Raccord_t& Domaine_32_64< _SIZE_ >::raccord (const Nom & nom) inline
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_.
raccord() [4/4]
template<typename _SIZE_ > const Raccord_t& Domaine_32_64< _SIZE_ >::raccord (const Nom & nom) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_.
faces_raccord() [1/2]
template<typename _SIZE_ > Raccords_t& Domaine_32_64< _SIZE_ >::faces_raccord () inline
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_.
Referenced by Extruder_en3::construire_bords(), DecoupeBord_32_64< _SIZE_ >::decouper(), Decouper_Bord_coincident::decouper_(), TroisDto2D_32_64< _SIZE_ >::extraire_2D(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), LireMED_32_64< _SIZE_ >::fill_frontieres(), Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), Create_domain_from_sub_domain::interpreter_(), Modif_bord_to_raccord_32_64< _SIZE_ >::interpreter_(), SupprimeBord_32_64< _SIZE_ >::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), and RegroupeBord_32_64< _SIZE_ >::regroupe_bord().
faces_raccord() [2/2]
template<typename _SIZE_ > const Raccords_t& Domaine_32_64< _SIZE_ >::faces_raccord () const inline
References Domaine_32_64< _SIZE_ >::mes_faces_raccord_.
nb_joints()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::nb_joints () const inline
Joints
References Domaine_32_64< _SIZE_ >::mes_faces_joint_, and Joints_32_64< _SIZE_ >::nb_joints().
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Scatter::calculer_espace_distant_elements(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Scatter::corriger_espace_distant_elements_perio(), Postraiter_domaine::ecrire(), Domaine_VF::nb_joints(), and Scatter::read_domain_no_comm().
joint() [1/4]
template<typename _SIZE_ > Joint_t& Domaine_32_64< _SIZE_ >::joint (int i) inline
References Domaine_32_64< _SIZE_ >::mes_faces_joint_.
Referenced by Assembleur_P_VEFPreP1B::assembler_mat(), Scatter::calculer_espace_distant_elements(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), Scatter::corriger_espace_distant_elements_perio(), Postraiter_domaine::ecrire(), and Domaine_VF::joint().
joint() [2/4]
template<typename _SIZE_ > const Joint_t& Domaine_32_64< _SIZE_ >::joint (int i) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_joint_.
joint() [3/4]
template<typename _SIZE_ > Joint_t& Domaine_32_64< _SIZE_ >::joint (const Nom & nom) inline
References Domaine_32_64< _SIZE_ >::mes_faces_joint_.
joint() [4/4]
template<typename _SIZE_ > const Joint_t& Domaine_32_64< _SIZE_ >::joint (const Nom & nom) const inline
References Domaine_32_64< _SIZE_ >::mes_faces_joint_.
faces_joint() [1/2]
template<typename _SIZE_ > Joints_t& Domaine_32_64< _SIZE_ >::faces_joint () inline
References Domaine_32_64< _SIZE_ >::mes_faces_joint_.
Referenced by Scatter::ajouter_joints(), Echange_contact_Correlation_VDF::calculer_CL(), Echange_contact_Correlation_VEF::calculer_CL(), Scatter::calculer_espace_distant(), Scatter::check_consistancy_remote_items(), Scatter::construire_correspondance_aretes_par_coordonnees(), Scatter::construire_correspondance_sommets_par_coordonnees(), Scatter::construire_md_vector(), Scatter::construire_structures_paralleles(), Domaine_VF::discretiser(), LireMED_32_64< _SIZE_ >::fill_frontieres(), Echange_contact_Correlation_VDF::init_tab_echange(), Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), Create_domain_from_sub_domain::interpreter_(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), Scatter::read_domain_no_comm(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), Domaine_VDF::reordonner(), Scatter::reordonner_faces_de_joint(), and Domaine_VEF::verifie_ok_arete().
faces_joint() [2/2]
template<typename _SIZE_ > const Joints_t& Domaine_32_64< _SIZE_ >::faces_joint () const inline
References Domaine_32_64< _SIZE_ >::mes_faces_joint_.
joint_of_pe() [1/2]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::Joint_t & Domaine_32_64< _SIZE_ >::joint_of_pe (int pe) inline
joint_of_pe() [2/2]
template<typename _SIZE_ > const Domaine_32_64< _SIZE_ >::Joint_t & Domaine_32_64< _SIZE_ >::joint_of_pe (int pe) const inline
comprimer_joints()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::comprimer_joints
Concatene les joints de meme nom.
References Frontiere_32_64< _SIZE_ >::add(), and Frontiere_32_64< _SIZE_ >::le_nom().
renum_joint_common_items()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::renum_joint_common_items (const IntVect_t & Les_Nums, const int_t elem_offset)
Renumerotation des noeuds et des elements presents dans les items communs des joints.
Le noeud de numero k devient le noeud de numero Les_Nums[k] l'element de numero e devient l'element de numero e+elem_offset
Parameters
(IntVect& Les_Nums) le vecteur contenant la nouvelle numerotation Nouveau_numero_noeud_i = Les_Nums[Ancien_numero_noeud_i]
Referenced by Scatter::read_domain_no_comm().
init_renum_perio()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::init_renum_perio
Initialize the renumerotation array for periodicity.
Periodicity
get_renum_som_perio() [1/2]
template<typename _SIZE_ > int_t Domaine_32_64< _SIZE_ >::get_renum_som_perio (int_t i) const inline
References Domaine_32_64< _SIZE_ >::renum_som_perio_.
Referenced by Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Assembleur_P_VEFPreP1B::changer_base(), Domaine_VEF::construire_renum_arete_perio(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), Op_Diff_VEFP1NCP1B_Face::isInStencil(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Domaine_VEF::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), and Domaine_VEF::verifie_ok_arete().
construire_renum_som_perio()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::construire_renum_som_perio (const Conds_lim & les_cl, const Domaine_dis_base & domaine_dis)
Referenced by Conds_lim::completer().
set_renum_som_perio()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::set_renum_som_perio (IntTab_t & renum) inline
References Domaine_32_64< _SIZE_ >::renum(), and Domaine_32_64< _SIZE_ >::renum_som_perio_.
get_renum_som_perio() [2/2]
template<typename _SIZE_ > const ArrOfInt_t& Domaine_32_64< _SIZE_ >::get_renum_som_perio () const inline
References Domaine_32_64< _SIZE_ >::renum_som_perio_.
nb_ss_domaines()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::nb_ss_domaines () const inline
Referenced by Refine_Mesh::build_new_sub_domaines_descriptions(), Partitionneur_Sous_Domaines::construire_partition(), Domaine_dis_base::discretiser_root(), Postraiter_domaine::ecrire(), Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), and Refine_Mesh::update_sub_domaines().
ss_domaine() [1/4]
template<typename _SIZE_ > const Sous_Domaine_t& Domaine_32_64< _SIZE_ >::ss_domaine (int i) const inline
Referenced by Eval_Puiss_Neutr_VDF_Elem::associer_repartition(), Refine_Mesh::build_new_sub_domaines_descriptions(), Perte_Charge_Gen::completer(), Op_Conv_EF_VEF_P1NC_Stab::completer(), Perte_Charge_VEF::completer(), Partitionneur_Sous_Domaines::construire_partition(), Domaine_dis_base::discretiser_root(), Postraiter_domaine::ecrire(), Ensemble_Lagrange_base::generer_marqueurs_sz(), Perte_Charge_Singuliere::lire_surfaces(), Interprete_geometrique_base_32_64< _SIZE_ >::mettre_a_jour_sous_domaine(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), Perte_Charge_Reguliere_VDF_Face::remplir_num_faces(), Perte_Charge_Reguliere_VEF_P1NC::remplir_num_faces(), Domaine_VF::typer_discretiser_ss_domaine(), and Refine_Mesh::update_sub_domaines().
ss_domaine() [2/4]
template<typename _SIZE_ > Sous_Domaine_t& Domaine_32_64< _SIZE_ >::ss_domaine (int i) inline
ss_domaine() [3/4]
template<typename _SIZE_ > const Sous_Domaine_t& Domaine_32_64< _SIZE_ >::ss_domaine (const Nom & nom) const inline
ss_domaine() [4/4]
template<typename _SIZE_ > Sous_Domaine_t& Domaine_32_64< _SIZE_ >::ss_domaine (const Nom & nom) inline
add()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::add (const Sous_Domaine_t & sd) inline
associer_()
template<typename _SZ_ > int Domaine_32_64< _SZ_ >::associer_ (Objet_U & ob) override virtual
Association d'un Sous_Domaine au Domaine.
L'interface permet de passer n'importe quel Objet_U mais ne gere (dynamiquement) que l'association d'un objet derivant Sous_Domaine.
Parameters
(Objet_U& ob) l'objet a associer
Returns
(int) 1 si l'association a reussie 0 sinon (l'objet n'etait pas derive Sous_Domaine)
Reimplemented from Objet_U.
References Objet_U::associer_().
LIST() [2/4]
template<typename _SIZE_ > const Domaine_32_64< _SIZE_ >::LIST (OBS_PTR(Sous_Domaine_t)) const & inline
calculer_centres_gravite()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::calculer_centres_gravite (DoubleTab_t & xp) const inline
Calcule les centres de gravites des elements du domaine.
Geometric computations
Parameters
(DoubleTab_t& xp) le tableau contenant les centres de gravites des elements du domaine
Referenced by Champ_base::calculer_valeurs_elem_compo_post(), Champ_base::calculer_valeurs_elem_post(), Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition(), Partitionneur_Partition::construire_partition(), Champ_Generique_Transformation::get_champ(), Champ_implementation_P0::imprime_P0(), Moyenne_volumique::interpreter(), Distanceparoi::interpreter_(), VerifierCoin::interpreter_(), Perte_Charge_Singuliere::lire_surfaces(), Remove_elem::remove_elem_(), Champ_P0_VDF::remplir_coord_noeuds(), Domaine_EF_axi::remplir_tableau_origine(), Trianguler_fin::trianguler(), Trianguler_H::trianguler(), and Champ_base::valeur_aux_centres_de_gravite().
calculer_centres_gravite_aretes()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::calculer_centres_gravite_aretes (DoubleTab_t & xa) const
Calcule les centres de gravites des aretes du domaine.
Parameters
(DoubleTab& xa) le tableau contenant les centres de gravites des aretes du domaine
References TRUSTTab< _TYPE_, _SIZE_ >::resize().
calculer_volumes()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::calculer_volumes (DoubleVect_t & volumes, DoubleVect_t & inverse_volumes) const virtual
Calcule les volumes des elements du domaine.
Parameters
(DoubleVect& volumes) le tableau contenant les volumes des elements du domaine
Reimplemented in DomaineAxi1d_32_64< _SIZE_ >.
References TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), and MD_Vector::non_nul().
Referenced by DomaineAxi1d_32_64< _SIZE_ >::calculer_volumes(), and Domaine_VF::discretiser_no_face().
calculer_mon_centre_de_gravite()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::calculer_mon_centre_de_gravite (ArrOfDouble & c)
Calcule le centre de gravite du domaine.
Referenced by Calculer_Moments::interpreter_().
volume_total()
template<typename _SZ_ > double Domaine_32_64< _SZ_ >::volume_total
Referenced by Navier_Stokes_std::impr(), Navier_Stokes_Fluide_Dilatable_Proto::impr_impl(), Terme_Source_Canal_perio::source_convection_diffusion(), and Terme_Source_Canal_perio_VDF_P0::source_convection_diffusion().
cg_moments() [1/2]
template<typename _SIZE_ > const ArrOfDouble& Domaine_32_64< _SIZE_ >::cg_moments () const inline
References Domaine_32_64< _SIZE_ >::cg_moments_.
cg_moments() [2/2]
template<typename _SIZE_ > ArrOfDouble& Domaine_32_64< _SIZE_ >::cg_moments () inline
References Domaine_32_64< _SIZE_ >::cg_moments_.
exporter_mon_centre_de_gravite()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::exporter_mon_centre_de_gravite (ArrOfDouble c) inline
References Domaine_32_64< _SIZE_ >::cg_moments_.
Referenced by Calculer_Moments::interpreter_().
chercher_elements() [1/3]
template<typename _SZ_ > Domaine_32_64< _SZ_ >::SmallArrOfTID_t & Domaine_32_64< _SZ_ >::chercher_elements (const DoubleTab & positions, SmallArrOfTID_t & elements, int reel = 0) const
Recherche des elements contenant les points dont les coordonnees sont specifiees.
Lookup methods and mapping arrays
Parameters
(DoubleTab& positions) les coordonnees des points dont on veut connaitre l'element correspondant
(ArrOfInt_t& elements) le tableau des numeros des elements contenant les points specifies
Returns
(ArrOfInt_t&) le tableau des numeros des elements contenant les points specifies
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
Referenced by Interpolation_IBM_elem_fluid::computeFluidElems(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_contact_VEF::connectivity_failed(), Partitionneur_Fichier_MED::construire_partition(), Partitionneur_Sous_Domaines::construire_partition(), Tetraedriser_homogene_fin::creer_sommet(), Sonde::initialiser(), Sonde_Int::initialiser(), Distanceparoi::interpreter_(), Champ_Inc_base::valeur_a(), Champ_Fonc_MED::valeur_a(), Champ_Fonc_base::valeur_aux(), Champ_Inc_base::valeur_aux(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux(), Champ_Fonc_Face_VDF::valeur_aux_compo(), Champ_Inc_base::valeur_aux_compo(), TRUSTChamp_Morceaux_generique< _TYPE_ >::valeur_aux_compo(), Champ_base::valeur_aux_sommets(), and Champ_base::valeur_aux_sommets_compo().
chercher_elements() [2/3]
template<typename _SZ_ > Domaine_32_64< _SZ_ >::SmallArrOfTID_t & Domaine_32_64< _SZ_ >::chercher_elements (const DoubleVect & positions, SmallArrOfTID_t & elements, int reel = 0) const
Recherche des elements contenant les points dont les coordonnees sont specifiees.
Parameters
(DoubleVect_t<<em>SZ</em>>& positions) les coordonnees du point dont on veut connaitre l'element correspondant
(ArrOfInt_t& elements) le tableau des numeros des elements contenant les points specifies
Returns
(ArrOfInt_t&) le tableau des numeros des elements contenant les points specifies
References Process::exit(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
chercher_elements() [3/3]
template<typename _SZ_ > Domaine_32_64< _SZ_ >::int_t Domaine_32_64< _SZ_ >::chercher_elements (double x, double y = 0, double z = 0, int reel = 0) const
Renvoie le rang de l'element contenant le point dont les coordonnees sont specifiees.
Parameters
(double x) coordonnee en X
(double y) coordonnee en Y
(double z) coordonnee en Z
Returns
(int) le rang de l'element contenant le point dont les coordonnees sont specifiees.
References OctreeRoot_32_64< _SIZE_ >::rang_elem().
indice_elements()
template<typename _SZ_ > Domaine_32_64< _SZ_ >::SmallArrOfTID_t & Domaine_32_64< _SZ_ >::indice_elements (const IntTab & sommets, SmallArrOfTID_t & elem, int reel = 0) const
Cherche les numeros (indices) des elements contenants les sommets specifies par le parametre "sommets".
Utilise: ArrOfInt_t& Domaine_32_64<SZ>::chercher_elements(const DoubleTab&,ArrOfInt_t&) const
Parameters
(IntTab& sommets) le tableau des numeros des sommets dont on cherche les elements correspondants
(ArrOfInt_t& elem_) le tableau contenant les numeros des elements contenant les sommets specifies
Returns
(ArrOfInt_t&) le tableau des numeros des sommets dont on cherche les elements correspondants
chercher_sommets() [1/2]
template<typename _SZ_ > Domaine_32_64< _SZ_ >::SmallArrOfTID_t & Domaine_32_64< _SZ_ >::chercher_sommets (const DoubleTab & pos, SmallArrOfTID_t & som, int reel = 0) const
Parameters
(DoubleTab& pos)
(ArrOfInt_t& som)
Returns
(ArrOfInt_t&)
References OctreeRoot_32_64< _SIZE_ >::rang_sommet().
chercher_sommets() [2/2]
template<typename _SZ_ > Domaine_32_64< _SZ_ >::int_t Domaine_32_64< _SZ_ >::chercher_sommets (double x, double y = 0, double z = 0, int reel = 0) const
Parameters
(double x) coordonnee en X
(double y) coordonnee en Y
(double z) coordonnee en Z
References OctreeRoot_32_64< _SIZE_ >::rang_sommet().
chercher_aretes()
template<typename _SZ_ > Domaine_32_64< _SZ_ >::SmallArrOfTID_t & Domaine_32_64< _SZ_ >::chercher_aretes (const DoubleTab & pos, SmallArrOfTID_t & aretes, int reel = 0) const
Parameters
(DoubleTab& pos)
(IntTab& aretes_som) la definition des aretes par leurs sommets
Returns
(ArrOfInt_t& aretes) Liste des aretes trouvees
References OctreeRoot_32_64< _SIZE_ >::rang_arete().
rang_elems_sommet()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::rang_elems_sommet (SmallArrOfTID_t & elems, double x, double y = 0, double z = 0) const
References OctreeRoot_32_64< _SIZE_ >::rang_elems_sommet().
construit_octree() [1/2]
template<typename _SZ_ > const Domaine_32_64< _SZ_ >::OctreeRoot_t & Domaine_32_64< _SZ_ >::construit_octree
References OctreeRoot_32_64< _SIZE_ >::associer_Domaine(), OctreeRoot_32_64< _SIZE_ >::construire(), and OctreeRoot_32_64< _SIZE_ >::construit().
Referenced by Decouper_Bord_coincident::decouper_(), ExtrudeParoi::extrude(), Perte_Charge_Singuliere::lire_surfaces(), Remove_elem::remove_elem_(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler_fin::trianguler(), and Refine_Mesh::update_octree().
construit_octree() [2/2]
template<typename _SZ_ > const Domaine_32_64< _SZ_ >::OctreeRoot_t & Domaine_32_64< _SZ_ >::construit_octree (int & reel) const
construction de l'octree si pas deja fait
References OctreeRoot_32_64< _SIZE_ >::associer_Domaine(), OctreeRoot_32_64< _SIZE_ >::construire(), OctreeRoot_32_64< _SIZE_ >::construit(), and OctreeRoot_32_64< _SIZE_ >::reel().
invalide_octree()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::invalide_octree
Referenced by Decouper_Bord_coincident::decouper_(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), Remove_elem::remove_elem_(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Trianguler_fin::trianguler(), and Refine_Mesh::update_octree().
clear()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::clear virtual
Reset the Domaine completely except for its name.
Various
Referenced by Domaine_32_64< _SIZE_ >::Domaine_32_64(), and Scatter::lire_domaine().
renum()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::renum (const IntVect_t & Les_Nums)
Renumerotation des noeuds: Le noeud de numero k devient le noeud de numero Les_Nums[k].
Parameters
(IntVect& Les_Nums) le vecteur contenant la nouvelle numerotation Nouveau_numero_noeud_i = Les_Nums[Ancien_numero_noeud_i]
Referenced by Domaine_32_64< _SIZE_ >::fill_from_list(), Scatter::read_domain_no_comm(), and Domaine_32_64< _SIZE_ >::set_renum_som_perio().
check_domaine()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::check_domaine
associate the read objects to the domaine and check that the reading objects are coherent
imprimer()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::imprimer
References Process::mp_sum_as_double().
Referenced by Decouper_32_64< _SIZE_ >::lire().
comprimer()
template<typename _SZ_ > int Domaine_32_64< _SZ_ >::comprimer
Concatene les bords de meme nom et ceci pour: les bords, les bords periodiques, les bords internes et les groupes de faces.
References Frontiere_32_64< _SIZE_ >::add(), Frontiere_32_64< _SIZE_ >::associer_domaine(), Frontiere_32_64< _SIZE_ >::domaine(), Domaine_base::le_nom(), and Frontiere_32_64< _SIZE_ >::le_nom().
read_former_domaine()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::read_former_domaine (Entree & s)
read what was (before TRUST 1.9.2) the "domaine" part from the input stream i.e. (roughly) the element description.
References Process::exit().
Referenced by Scatter::read_domain_no_comm().
merge_wo_vertices_with()
template<typename _SIZE_ > void Domaine_32_64< _SZ_ >::merge_wo_vertices_with (Domaine_32_64< _SIZE_ > & z)
Merge another Domaine into this, without considering vertices which are handled separately.
References Bords_32_64< _SIZE_ >::associer_domaine(), Bords_Internes_32_64< _SIZE_ >::associer_domaine(), Groupes_Faces_32_64< _SIZE_ >::associer_domaine(), Joints_32_64< _SIZE_ >::associer_domaine(), Raccords_32_64< _SIZE_ >::associer_domaine(), Domaine_32_64< _SIZE_ >::bords_int(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_32_64< _SIZE_ >::groupes_faces(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_base::nom_, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Scatter::read_domain_no_comm().
fill_from_list()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::fill_from_list (std::list< Domaine_32_64< _SIZE_ > * > & lst)
Fills the Domaine from a list of Domaine objects by aggregating them.
See Mailler for example
References Process::exit(), Process::is_parallel(), Domaine_base::nom_, Objet_U::que_suis_je(), Domaine_32_64< _SIZE_ >::renum(), and Domaine_32_64< _SIZE_ >::sommets_.
Referenced by Mailler_32_64< _SIZE_ >::interpreter_().
reordering()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::reordering
References Process::exit(), Scatter::init_sequential_domain(), Process::nproc(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
build_mc_mesh()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::build_mc_mesh
Build the MEDCoupling mesh corresponding to the TRUST mesh.
MEDCoupling:
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Objet_U::dimension, Polyedre_32_64< _SIZE_ >::getFacesIndex(), Polyedre_32_64< _SIZE_ >::getPolyhedronIndex(), Objet_U::que_suis_je(), Polyedre_32_64< _SIZE_ >::remplir_Nodes_glob(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
is_mc_mesh_ready()
template<typename _SIZE_ > bool Domaine_32_64< _SIZE_ >::is_mc_mesh_ready () const inline
set_mc_mesh_ready()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::set_mc_mesh_ready (bool flag) const inline
Referenced by Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), and LireMED_32_64< _SIZE_ >::lire_geom().
ind_faces_virt_bord()
template<typename _SIZE_ > const ArrOfInt_t& Domaine_32_64< _SIZE_ >::ind_faces_virt_bord () const inline
Parallelism and virtual items management
References Domaine_32_64< _SIZE_ >::ind_faces_virt_bord_.
Referenced by Domaine_Cl_VDF::completer(), and Domaine_VF::ind_faces_virt_bord().
construire_elem_virt_pe_num() [1/2]
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::construire_elem_virt_pe_num
Construction du tableau elem_virt_pe_num_ a partir du tableau mes_elems (on se sert des espaces distants et virtuels de mes_elems). Algorithme non optimal en memoire : on duplique mes_elems alors qu'on a besoin que d'un tableau a deux colonnes. Voir Domaine.h : elem_virt_pe_num_
Referenced by Domain_Graph::construire_graph_elem_elem().
construire_elem_virt_pe_num() [2/2]
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::construire_elem_virt_pe_num (IntTab_t & elem_virt_pe_num_cpy) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
elem_virt_pe_num()
template<typename _SIZE_ > const IntTab_t& Domaine_32_64< _SIZE_ >::elem_virt_pe_num () const inline
References Domaine_32_64< _SIZE_ >::elem_virt_pe_num_.
creer_tableau_elements()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::creer_tableau_elements (Array_base & x, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) const virtual
creation d'un tableau parallele de valeurs aux elements.
Voir MD_Vector_tools::creer_tableau_distribue()
References MD_Vector_tools::creer_tableau_distribue().
Referenced by Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Dift_VEF_Face_Gen< Op_Dift_Stab_VEF_Face >::ajouter_bord_gen(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Dift_VEF_Face_Gen< Op_Dift_Stab_VEF_Face >::ajouter_contribution_bord_gen(), Assembleur_P_VEFPreP1B::assembler_mat(), Champ_Q1_EF::cal_rot_ordre1(), Champ_Q1NC::cal_rot_ordre1(), Champ_Face_PolyMAC::calcul_S_barre(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Domaine_EF::calculer_IPhi(), Domaine_EF_axi::calculer_IPhi(), Hexa_VEF::creer_facette_normales(), Quadri_VEF::creer_facette_normales(), Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Extraire_surface::extraire_surface_without_cleaning(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Domaine_VF::init_dist_paroi_globale(), Domaine_PolyMAC::init_m1_3d(), Domaine_VDF::init_virt_e_map(), Domaine_PolyMAC::init_virt_ef_map(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Champ_Face_PolyMAC::interp_gve(), Extraire_domaine::interpreter_(), Convection_Diffusion_Temperature::lire_motcle_non_standard(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Domaine_EF_axi::remplir_tableau_origine(), Domaine_EF::reordonner(), Domaine_Poly_base::reordonner(), Domaine_VEF::reordonner(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC_P0P1NC::trace(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), and Champ_Face_PolyMAC::valeur_aux_elems_().
md_vector_elements()
template<typename _SZ_ > const MD_Vector & Domaine_32_64< _SZ_ >::md_vector_elements virtual
renvoie le descripteur parallele des tableaux aux elements du domaine
References Process::exit(), and MD_Vector::non_nul().
Referenced by Tetra_VEF::creer_facette_normales(), Tri_VEF::creer_facette_normales(), Domaine_VEF::discretiser_suite(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Champ_Inc_P0_base::fixer_nb_valeurs_nodales(), Echange_contact_VDF::initialiser(), Champ_Elem_PolyMAC_P0::reprendre(), and Debog_Pb::write_geometry_data().
creer_tableau_sommets()
template<typename _SZ_ > void Domaine_32_64< _SZ_ >::creer_tableau_sommets (Array_base & v, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) const virtual
Cree un tableau ayant une "ligne" par sommet du maillage.
Voir MD_Vector_tools::creer_tableau_distribue()
References MD_Vector_tools::creer_tableau_distribue().
Referenced by Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Domaine_EF::discretiser(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Champ_implementation_P1::init_from_file(), Op_Diff_VEFP1NCP1B_Face::initialiser(), Domaine_VEF::modifier_pour_Cl(), Domaine_Poly_base::pvol_som(), and Op_Diff_VEFP1NCP1B_Face::test().
md_vector_sommets()
template<typename _SIZE_ > virtual const MD_Vector& Domaine_32_64< _SIZE_ >::md_vector_sommets () const inline virtual
References TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), and Domaine_32_64< _SIZE_ >::sommets_.
Referenced by Domaine_VEF::discretiser_suite(), Champ_Fonc_P1_base::fixer_nb_valeurs_nodales(), Champ_Fonc_Q1_base::fixer_nb_valeurs_nodales(), Champ_Inc_P1_base::fixer_nb_valeurs_nodales(), Champ_Inc_Q1_base::fixer_nb_valeurs_nodales(), Op_Diff_VEFP1NCP1B_Face::remplir_nu_p1(), and Debog_Pb::write_geometry_data().
identifie_item_unique()
template<typename _SIZE_ > int Domaine_32_64< _SIZE_ >::identifie_item_unique (IntList & item_possible, DoubleTab & coord_possible, const DoubleVect & coord_ref) static
Methods only used in 32 bits (i.e. after Scatter)
init_faces_virt_bord()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::init_faces_virt_bord (const MD_Vector & md_vect_faces, MD_Vector & md_vect_faces_bord)
creer_aretes()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::creer_aretes
Referenced by Domaine_VEF::discretiser_arete(), and Domaine_Poly_base::discretiser_aretes().
creer_mes_domaines_frontieres()
template<typename _SIZE_ > void Domaine_32_64< _SIZE_ >::creer_mes_domaines_frontieres (const Domaine_VF & domaine_vf)
OWN_PTR() [3/4]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::OWN_PTR (Elem_geom_base_32_64< _SIZE_ >) protected
OWN_PTR() [4/4]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::OWN_PTR (OctreeRoot_t) mutable protected
LIST() [3/4]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::LIST (OBS_PTR(Sous_Domaine_t)) protected
LIST() [4/4]
template<typename _SIZE_ > Domaine_32_64< _SIZE_ >::LIST (OBS_PTR(Domaine_32_64< _SIZE_ >)) protected
Member Data Documentation
sommets_
template<typename _SIZE_ > DoubleTab_t Domaine_32_64< _SIZE_ >::sommets_ protected
Referenced by Domaine_32_64< _SIZE_ >::coord(), Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_32_64< _SIZE_ >::fill_from_list(), Domaine_32_64< _SIZE_ >::les_sommets(), Domaine_32_64< _SIZE_ >::md_vector_sommets(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_tot(), Domaine_32_64< _SIZE_ >::resetSommetsCoordinates(), and Domaine_32_64< _SIZE_ >::saveSommetsCoordinates().
sommets_n
template<typename _SIZE_ > DoubleTab_t Domaine_32_64< _SIZE_ >::sommets_n protected
Referenced by Domaine_32_64< _SIZE_ >::resetSommetsCoordinates(), and Domaine_32_64< _SIZE_ >::saveSommetsCoordinates().
renum_som_perio_
template<typename _SIZE_ > ArrOfInt_t Domaine_32_64< _SIZE_ >::renum_som_perio_ protected
Referenced by Domaine_32_64< _SIZE_ >::get_renum_som_perio(), and Domaine_32_64< _SIZE_ >::set_renum_som_perio().
mes_elems_
template<typename _SIZE_ > IntTab_t Domaine_32_64< _SIZE_ >::mes_elems_ protected
Referenced by Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and Domaine_32_64< _SIZE_ >::sommet_elem().
aretes_som_
template<typename _SIZE_ > IntTab_t Domaine_32_64< _SIZE_ >::aretes_som_ protected
Referenced by Domaine_32_64< _SIZE_ >::arete_sommets(), Domaine_32_64< _SIZE_ >::aretes_som(), Domaine_32_64< _SIZE_ >::nb_aretes(), Domaine_32_64< _SIZE_ >::nb_aretes_tot(), and Domaine_32_64< _SIZE_ >::set_aretes_som().
elem_aretes_
template<typename _SIZE_ > IntTab_t Domaine_32_64< _SIZE_ >::elem_aretes_ protected
Referenced by Domaine_32_64< _SIZE_ >::elem_aretes(), and Domaine_32_64< _SIZE_ >::set_elem_aretes().
ind_faces_virt_bord_
template<typename _SIZE_ > ArrOfInt_t Domaine_32_64< _SIZE_ >::ind_faces_virt_bord_ protected
Referenced by Domaine_32_64< _SIZE_ >::ind_faces_virt_bord().
elem_virt_pe_num_
template<typename _SIZE_ > IntTab_t Domaine_32_64< _SIZE_ >::elem_virt_pe_num_ protected
Referenced by Domaine_32_64< _SIZE_ >::elem_virt_pe_num().
cg_moments_
template<typename _SIZE_ > ArrOfDouble Domaine_32_64< _SIZE_ >::cg_moments_ protected
Referenced by Domaine_32_64< _SIZE_ >::cg_moments(), and Domaine_32_64< _SIZE_ >::exporter_mon_centre_de_gravite().
mes_faces_bord_
template<typename _SIZE_ > Bords_t Domaine_32_64< _SIZE_ >::mes_faces_bord_ protected
Referenced by Domaine_32_64< _SIZE_ >::bord(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::nb_bords(), and Domaine_32_64< _SIZE_ >::nb_faces_bord().
mes_faces_raccord_
template<typename _SIZE_ > Raccords_t Domaine_32_64< _SIZE_ >::mes_faces_raccord_ protected
Referenced by Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_32_64< _SIZE_ >::nb_faces_raccord(), Domaine_32_64< _SIZE_ >::nb_raccords(), and Domaine_32_64< _SIZE_ >::raccord().
mes_bords_int_
template<typename _SIZE_ > Bords_Internes_t Domaine_32_64< _SIZE_ >::mes_bords_int_ protected
Referenced by Domaine_32_64< _SIZE_ >::bords_int(), Domaine_32_64< _SIZE_ >::bords_interne(), Domaine_32_64< _SIZE_ >::nb_faces_bords_int(), and Domaine_32_64< _SIZE_ >::nb_frontieres_internes().
mes_groupes_faces_
template<typename _SIZE_ > Groupes_Faces_t Domaine_32_64< _SIZE_ >::mes_groupes_faces_ protected
Referenced by Domaine_32_64< _SIZE_ >::groupe_faces(), Domaine_32_64< _SIZE_ >::groupes_faces(), Domaine_32_64< _SIZE_ >::nb_faces_groupes_faces(), and Domaine_32_64< _SIZE_ >::nb_groupes_faces().
mes_faces_joint_
template<typename _SIZE_ > Joints_t Domaine_32_64< _SIZE_ >::mes_faces_joint_ protected
Referenced by Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::joint(), Domaine_32_64< _SIZE_ >::nb_faces_joint(), and Domaine_32_64< _SIZE_ >::nb_joints().