CEA TRUST Platform: Iterateur_Source_VEF_Face< _TYPE_ > Class Template Reference
Iterateur_Source_VEF_Face< _TYPE_ > Class Template Reference
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Iterateur_Source_VEF_Face() [1/2]
template<typename _TYPE_ > Iterateur_Source_VEF_Face< _TYPE_ >::Iterateur_Source_VEF_Face () inline
Iterateur_Source_VEF_Face() [2/2]
template<typename _TYPE_ > Iterateur_Source_VEF_Face< _TYPE_ >::Iterateur_Source_VEF_Face (const Iterateur_Source_VEF_Face< _TYPE_ > & iter) inline
Member Function Documentation
ajouter()
template<typename _TYPE_ > DoubleTab & Iterateur_Source_VEF_Face< _TYPE_ >::ajouter (DoubleTab & resu) const override virtual
Implements Iterateur_Source_base.
References TRUSTVect< _TYPE_, _SIZE_ >::line_size(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
completer_()
template<typename _TYPE_ > void Iterateur_Source_VEF_Face< _TYPE_ >::completer_ () inline override virtual
Implements Iterateur_Source_base.
evaluateur() [1/2]
template<typename _TYPE_ > Evaluateur_Source_VEF_Face& Iterateur_Source_VEF_Face< _TYPE_ >::evaluateur () inline override virtual
Implements Iterateur_Source_base.
evaluateur() [2/2]
template<typename _TYPE_ > const Evaluateur_Source_VEF_Face& Iterateur_Source_VEF_Face< _TYPE_ >::evaluateur () const inline
initialiser()
template<typename _TYPE_ > int Iterateur_Source_VEF_Face< _TYPE_ >::initialiser (double tps) inline override protected virtual
Reimplemented from Iterateur_Source_base.
remplir_volumes_cl_dirichlet()
template<typename _TYPE_ > void Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet protected
References Domaine_VF::creer_tableau_faces(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Domaine_VEF::premiere_face_std(), and Domaine_Cl_VEF::volumes_entrelaces_Cl().
faces_doubles()
template<typename _TYPE_ > const int& Iterateur_Source_VEF_Face< _TYPE_ >::faces_doubles (int num_face) const inline protected
volumes_entrelaces_Cl()
template<typename _TYPE_ > double Iterateur_Source_VEF_Face< _TYPE_ >::volumes_entrelaces_Cl (int & num_face) const inline protected
volumes_entrelaces()
template<typename _TYPE_ > double Iterateur_Source_VEF_Face< _TYPE_ >::volumes_entrelaces (int & num_face) const inline protected
face_voisins()
template<typename _TYPE_ > int Iterateur_Source_VEF_Face< _TYPE_ >::face_voisins (int num_face, int dir) const inline protected
elem_faces()
template<typename _TYPE_ > int Iterateur_Source_VEF_Face< _TYPE_ >::elem_faces (int num_elem, int i) const inline protected