CEA TRUST Platform: Champ_front_Parametrique Class Reference
Champ_front_Parametrique Class Reference
#include <Champ_front_Parametrique.h>
Public Member Functions
void associer_fr_dis_base (const Frontiere_dis_base &fr) override
int avancer (double temps) override
void calculer_coeffs_echange (double temps) override
Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat) override
void fixer_nb_comp (int i) override
void fixer_nb_valeurs_temporelles (int nb_cases) override
const Frontiere_dis_base & frontiere_dis () const override
Frontiere_dis_base & frontiere_dis () override
int initialiser (double temps, const Champ_Inc_base &inco) override
void mettre_a_jour (double temps) override
int reculer (double temps) override
virtual const DoubleTab & valeurs () const override
virtual const DoubleTab & valeurs () const=0
virtual DoubleTab & valeurs () override
virtual DoubleTab & valeurs ()=0
void valeurs_face (int i, DoubleVect &val) const override
Public Member Functions inherited from Field_base
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Member Function Documentation
valeurs() [1/6]
virtual DoubleTab & Champ_front_Parametrique::valeurs () inline override virtual
Renvoie le tableau des valeurs du champ.
Returns
(DoubleTab&) le tableau des valeurs du champ au temps par defaut.
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::valeurs().
valeurs() [2/6]
virtual const DoubleTab & Champ_front_Parametrique::valeurs () const inline override virtual
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
Returns
(DoubleTab&) le tableau des valeurs du champ
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::valeurs().
valeurs_au_temps() [1/2]
DoubleTab & Champ_front_Parametrique::valeurs_au_temps (double temps) inline override virtual
Implements Champ_front_base.
References champ(), and Champ_front_base::valeurs_au_temps().
Referenced by calculer_derivee_en_temps().
valeurs_au_temps() [2/2]
const DoubleTab & Champ_front_Parametrique::valeurs_au_temps (double temps) const inline override virtual
Implements Champ_front_base.
References champ(), and Champ_front_base::valeurs_au_temps().
frontiere_dis() [1/2]
const Frontiere_dis_base & Champ_front_Parametrique::frontiere_dis () const inline override virtual
Renvoie la frontiere discretisee associee au champ.
(version const)
Returns
(Frontiere_dis_base&) la frontiere discretisee associee au champ
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::frontiere_dis().
frontiere_dis() [2/2]
Frontiere_dis_base & Champ_front_Parametrique::frontiere_dis () inline override virtual
Renvoie la frontiere discretisee associee au champ.
Returns
(Frontiere_dis_base&) la frontiere discretisee associee au champ
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::frontiere_dis().
domaine_dis()
const Domaine_dis_base & Champ_front_Parametrique::domaine_dis () const inline override virtual
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::domaine_dis().
affecter_()
Champ_front_base & Champ_front_Parametrique::affecter_ (const Champ_front_base & ch) inline override virtual
Implements Champ_front_base.
References Champ_front_base::affecter_(), and champ().
mettre_a_jour()
void Champ_front_Parametrique::mettre_a_jour (double temps) inline override virtual
NE FAIT RIEN, a surcharger.
Cette methode est appelee au debut de chaque pas de temps ou sous-pas-de-temps, elle peut eventuellement utiliser des donnees exterieures a l'equation. A charge a l'algorithme de s'assurer que ces donnees sont pertinentes... Calcule la valeur de la condition aux limites au temps demande.
Parameters
(double)
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::mettre_a_jour().
calculer_coeffs_echange()
void Champ_front_Parametrique::calculer_coeffs_echange (double temps) inline override virtual
NE FAIT RIEN, a surcharger Cette methode peut calculer et stocker des donnees utiles a la.
CL, et dependant uniquement de l'inconnue sur laquelle porte cette CL (pas de l'exterieur). cf Champ_front_contact_VEF par exemple. Elle est appelee lorsque l'inconnue est modifiee.
Parameters
(double)
Reimplemented from Champ_front_base.
References Champ_front_base::calculer_coeffs_echange(), and champ().
valeurs_face()
void Champ_front_Parametrique::valeurs_face (int num_face, DoubleVect & val) const inline override virtual
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des valeurs porte nb_faces * nb_compo_ valeurs. Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parameters
(num_face) l'indice d'une face sur la frontiere 0 <= num_face < frontiere_dis().frontiere().nb_faces()
(val) On resize ce tableau et on le remplit.
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::valeurs_face().
verifier()
void Champ_front_Parametrique::verifier (const Cond_lim_base & la_cl) const inline override virtual
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::verifier().
get_temps_defaut()
double Champ_front_Parametrique::get_temps_defaut () const inline override virtual
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::get_temps_defaut().
set_temps_defaut()
void Champ_front_Parametrique::set_temps_defaut (double temps) inline override virtual
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::set_temps_defaut().
changer_temps_futur()
void Champ_front_Parametrique::changer_temps_futur (double temps, int i) inline override virtual
Change la valeur du temps pour la ieme valeur temporelle apres le present.
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::changer_temps_futur().
avancer()
int Champ_front_Parametrique::avancer (double temps) inline override virtual
A implementer dans les classes derivees.
Avance en temps : le nouveau temps present sera le temps passe en parametre.
Returns
(int) 1 si OK, 0 sinon
Reimplemented from Champ_front_base.
References Champ_front_base::avancer(), and champ().
reculer()
int Champ_front_Parametrique::reculer (double temps) inline override virtual
A implementer dans les classes derivees.
Recule en temps : le nouveau temps present sera le temps passe en parametre.
Returns
(int) 1 si OK, 0 sinon
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::reculer().
fixer_nb_comp()
void Champ_front_Parametrique::fixer_nb_comp (int i) inline override virtual
Fixe le nombre de composantes du champ.
Le champ est vectoriel s'il est de meme dimension que l'espace.
Parameters
(int i) le nombre de composantes du champs
Reimplemented from Field_base.
References champ(), and Field_base::fixer_nb_comp().
nb_comp()
int Champ_front_Parametrique::nb_comp () const inline override virtual
Reimplemented from Field_base.
References champ(), and Field_base::nb_comp().
nature_du_champ()
Nature_du_champ Champ_front_Parametrique::nature_du_champ () const inline override virtual
Reimplemented from Field_base.
References champ(), and Field_base::nature_du_champ().
fixer_nature_du_champ()
Nature_du_champ Champ_front_Parametrique::fixer_nature_du_champ (Nature_du_champ n) inline override virtual
Fixer la nature d'un champ: scalaire, multiscalaire, vectoriel.
Le type (enum) Nature_du_champ est defini dans Ch_base.h.
Parameters
(Nature_du_champ n) la nature a donner au champ
Reimplemented from Field_base.
References champ(), and Field_base::fixer_nature_du_champ().
associer_fr_dis_base()
void Champ_front_Parametrique::associer_fr_dis_base (const Frontiere_dis_base & fr) inline override virtual
Associe une frontiere discretisee au champ.
Parameters
(Frontiere_dis_base& fr) la frontiere discretisee a associer au champ
Reimplemented from Champ_front_base.
initialiser()
int Champ_front_Parametrique::initialiser (double temps, const Champ_Inc_base & inco) inline override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees externes a l'equation (couplage). Si mettre_a_jour le fait, alors initialiser ne doit pas appeler mettre_a_jour.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Champ_front_base.
completer()
virtual void Champ_front_Parametrique::completer () inline override virtual
Reimplemented from Champ_front_base.
fixer_nb_valeurs_temporelles()
void Champ_front_Parametrique::fixer_nb_valeurs_temporelles (int nb_cases) inline override virtual
Appele par Conds_lim::completer Par defaut ne fait rien.
A surcharger dans les champs_front instationnaires.
Reimplemented from Champ_front_base.
calculer_derivee_en_temps()
void Champ_front_Parametrique::calculer_derivee_en_temps (double t1, double t2) override virtual
Calcule le taux d'accroissement du champ entre t1 et t2 et le stocke dans Gpoint_.
Reimplemented from Champ_front_base.
References Champ_front_base::calculer_derivee_en_temps(), champ(), Champ_front_base::derivee_en_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_front_base::Gpoint_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and valeurs_au_temps().
derivee_en_temps()
const DoubleTab & Champ_front_Parametrique::derivee_en_temps () const override virtual
Reimplemented from Champ_front_base.
References Champ_front_base::Gpoint_.
instationnaire()
bool Champ_front_Parametrique::instationnaire () const inline override virtual
Reimplemented from Champ_front_base.
References champ(), and Champ_front_base::instationnaire().
newCompute()
std::string Champ_front_Parametrique::newCompute () const
References champ(), Champ_Parametrique::dirnameCompute(), and Objet_U::que_suis_je().
Referenced by Probleme_base::newCompute().
champ() [1/2]
Champ_front_base & Champ_front_Parametrique::champ () inline
Referenced by affecter_(), avancer(), calculer_coeffs_echange(), calculer_derivee_en_temps(), changer_temps_futur(), domaine_dis(), fixer_nature_du_champ(), fixer_nb_comp(), frontiere_dis(), frontiere_dis(), get_temps_defaut(), instationnaire(), mettre_a_jour(), nature_du_champ(), nb_comp(), newCompute(), reculer(), set_temps_defaut(), valeurs(), valeurs(), valeurs_au_temps(), valeurs_au_temps(), valeurs_face(), and verifier().
champ() [2/2]
const Champ_front_base & Champ_front_Parametrique::champ () const inline
valeurs() [3/6]
virtual DoubleTab & Champ_Proto::valeurs () virtual
Renvoie le tableau des valeurs du champ.
Returns
(DoubleTab&) le tableau des valeurs du champ au temps par defaut.
Reimplemented from Champ_front_base.
valeurs() [4/6]
virtual const DoubleTab & Champ_Proto::valeurs () const virtual
Renvoie le tableau des valeurs du champ au temps par defaut.
(version const)
Returns
(DoubleTab&) le tableau des valeurs du champ
Reimplemented from Champ_front_base.
valeurs() [5/6]
virtual DoubleTab & Champ_Proto::valeurs (double temps) inline virtual
Reimplemented from Champ_front_base.
valeurs() [6/6]
virtual const DoubleTab & Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented from Champ_front_base.