CEA TRUST Platform: Op_Diff_VEF_Anisotrope_Face Class Reference
Op_Diff_VEF_Anisotrope_Face Class Reference
#include <Op_Diff_VEF_Anisotrope_Face.h>
Public Member Functions
void completer () override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Diff_VEF_base
double calculer_dt_stab () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
associer_diffusivite()
void Op_Diff_VEF_Anisotrope_Face::associer_diffusivite (const Champ_base & diffu) override virtual
associe le champ de diffusivite
Implements Operateur_Diff_base.
completer()
void Op_Diff_VEF_Anisotrope_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer().
diffusivite()
const Champ_base & Op_Diff_VEF_Anisotrope_Face::diffusivite () const override virtual
Implements Operateur_Diff_base.
ajouter()
DoubleTab & Op_Diff_VEF_Anisotrope_Face::ajouter (const DoubleTab & inconnue_org, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References ajouter_cas_multi_scalaire(), ajouter_cas_scalaire(), ajouter_cas_vectoriel(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Operateur_base::flux_bords_, Equation_base::inconnue(), Equation_base::milieu(), Op_VEF_Face::modifier_flux(), Field_base::nature_du_champ(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), and Op_Diff_VEF_base::remplir_nu().
Referenced by calculer().
calculer()
DoubleTab & Op_Diff_VEF_Anisotrope_Face::calculer (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References ajouter().
Referenced by verifier().
verifier()
void Op_Diff_VEF_Anisotrope_Face::verifier () const
References calculer(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xv().
dimensionner()
void Op_Diff_VEF_Anisotrope_Face::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice.
Reimplemented from Operateur_base.
References Op_VEF_Face::dimensionner().
modifier_pour_Cl()
void Op_Diff_VEF_Anisotrope_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_VEF_Face::modifier_pour_Cl().
contribuer_a_avec()
void Op_Diff_VEF_Anisotrope_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice.
Reimplemented from Operateur_base.
References ajouter_contribution(), ajouter_contribution_multi_scalaire(), MorEqn::equation(), Equation_base::inconnue(), and Field_base::nature_du_champ().
contribuer_au_second_membre()
void Op_Diff_VEF_Anisotrope_Face::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
References contribue_au_second_membre().
contribue_au_second_membre()
void Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre (DoubleTab & resu) const
References Neumann::flux_impose(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), and Domaine_VF::surface().
Referenced by contribuer_au_second_membre().
ajouter_contribution()
void Op_Diff_VEF_Anisotrope_Face::ajouter_contribution (const DoubleTab & transporte, Matrice_Morse & matrice) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Echange_impose_base::h_imp(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Domaine_VF::premiere_face_int(), Op_Diff_VEF_base::remplir_nu(), Champ_Inc_base::valeurs(), and Op_Diff_VEF_base::viscA().
Referenced by contribuer_a_avec().
ajouter_contribution_multi_scalaire()
void Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire (const DoubleTab & transporte, Matrice_Morse & matrice) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Domaine_VF::premiere_face_int(), TRUSTArray< _TYPE_, _SIZE_ >::ref_array(), Op_Diff_VEF_base::remplir_nu(), and Op_Diff_VEF_base::viscA().
Referenced by contribuer_a_avec().
ajouter_cas_scalaire()
void Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Domaine_Cl_VEF & domaine_Cl_VEF, const Domaine_VEF & domaine_VEF) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Echange_impose_base::emissivite(), Periodique::face_associee(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Echange_impose_base::h_imp(), Echange_impose_base::has_emissivite(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::surface(), Echange_impose_base::T_ext(), and Op_Diff_VEF_base::viscA().
Referenced by ajouter().
ajouter_cas_vectoriel()
void Op_Diff_VEF_Anisotrope_Face::ajouter_cas_vectoriel (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Domaine_Cl_VEF & domaine_Cl_VEF, const Domaine_VEF & domaine_VEF, int nb_comp) const
References Process::exit().
Referenced by ajouter().
ajouter_cas_multi_scalaire()
void Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire (const DoubleTab & inconnue, DoubleTab & resu, DoubleTab & flux_bords, DoubleTab & nu, const Domaine_Cl_VEF & domaine_Cl_VEF, const Domaine_VEF & domaine_VEF, int nb_comp) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Echange_impose_base::emissivite(), Periodique::face_associee(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Echange_impose_base::h_imp(), Echange_impose_base::has_emissivite(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), TRUSTArray< _TYPE_, _SIZE_ >::ref_array(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::surface(), Echange_impose_base::T_ext(), and Op_Diff_VEF_base::viscA().
Referenced by ajouter().
OBS_PTR()
Op_Diff_VEF_Anisotrope_Face::OBS_PTR (Champ_base) protected