CEA TRUST Platform: Cond_lim_utilisateur_base Class Reference
Cond_lim_utilisateur_base Class Reference
Public Member Functions
int is_pb_rayo ()
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
elles vont transformer le jdd la cl_utilisateur est typee est passe dans la methode complement(ajout) Dans le jdd on aviat bord cl_util champ.... tout se passe comme si on n avait pas cl_util mais ajout champ...
Member Function Documentation
lire()
void Cond_lim_utilisateur_base::lire (Entree & s, Equation_base & mon_eq, const Nom & nom_bord)
References complement(), ecrire(), la_cl_, and nom_bord_.
complement()
void Cond_lim_utilisateur_base::complement (Nom &) virtual
Reimplemented in Paroi_flux_impose, Paroi_contact_rayo, Paroi_contact_fictif_rayo, Paroi_contact_fictif, Paroi_contact, Paroi_adiabatique, and Paroi_Temperature_imposee.
Referenced by lire().
compatible_avec_eqn()
int Cond_lim_utilisateur_base::compatible_avec_eqn (const Equation_base &) const inline override virtual
Reimplemented from Cond_lim_base.
References Process::exit().
la_cl()
Cond_lim & Cond_lim_utilisateur_base::la_cl ()
References la_cl_.
is_pb_rayo()
int Cond_lim_utilisateur_base::is_pb_rayo ()
renvoit 0 si le pb n'est pas rayonnant 1 si il est semi_transp
                2 si il est transparent
References Milieu_base::is_rayo_semi_transp(), Milieu_base::is_rayo_transp(), and Probleme_base::milieu().
Referenced by Paroi_Temperature_imposee::complement(), Paroi_adiabatique::complement(), Paroi_contact_fictif_rayo::complement(), Paroi_contact_rayo::complement(), and Paroi_flux_impose::complement().
ecrire()
void Cond_lim_utilisateur_base::ecrire (const Nom & ajout) virtual
References Process::je_suis_maitre().
Referenced by lire().
OBS_PTR()
Cond_lim_utilisateur_base::OBS_PTR (Equation_base) protected
Member Data Documentation
la_cl_
Cond_lim* Cond_lim_utilisateur_base::la_cl_ = nullptr protected
Referenced by la_cl(), and lire().
nom_bord_
Nom Cond_lim_utilisateur_base::nom_bord_ protected
Referenced by Paroi_contact::complement(), Paroi_contact_fictif::complement(), Paroi_contact_rayo::complement(), and lire().