CEA TRUST Platform: Terme_Source_inc_VDF_Face Class Reference
Terme_Source_inc_VDF_Face Class Reference
#include <Terme_Source_inc_VDF_Face.h>
Public Member Functions
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int initialiser (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
temporelle de inc
See also
Terme_Source_inc
Member Function Documentation
associer_pb()
void Terme_Source_inc_VDF_Face::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References Terme_Source_inc_base::associer_eqn(), Probleme_base::equation(), Process::exit(), and Objet_U::que_suis_je().
calculer()
DoubleTab & Terme_Source_inc_VDF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References Source_base::ajouter(), and TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel().
mettre_a_jour()
void Terme_Source_inc_VDF_Face::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Terme_Source_inc_base.
References Terme_Source_inc_base::mettre_a_jour().
dimensionner_blocs()
void Terme_Source_inc_VDF_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const inline override virtual
Reimplemented from Source_base.
ajouter_blocs()
void Terme_Source_inc_VDF_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Reimplemented from Source_base.
References Domaine_VDF::dim_elem(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Process::me(), Equation_base::milieu(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Domaine_VDF::orientation(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), and Domaine_VF::volumes_entrelaces().
has_interface_blocs()
int Terme_Source_inc_VDF_Face::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
OBS_PTR() [1/2]
Terme_Source_inc_VDF_Face::OBS_PTR (Domaine_VDF) protected
OBS_PTR() [2/2]
Terme_Source_inc_VDF_Face::OBS_PTR (Domaine_Cl_VDF) protected
associer_domaines()
void Terme_Source_inc_VDF_Face::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.