CEA TRUST Platform: Dirichlet_loi_paroi Class Reference
Dirichlet_loi_paroi Class Reference abstract
Public Member Functions
void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &zcl) override
void associer_fr_dis_base (const Frontiere_dis_base &fr) override
virtual void calculer_coeffs_echange (double temps) override
virtual const Frontiere_dis_base & frontiere_dis () const override
virtual Frontiere_dis_base & frontiere_dis () override
virtual int initialiser (double temps) override
void mettre_a_jour (double tps) override
virtual double val_imp (int i) const override
virtual double val_imp (int i, int j) const override
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
void set_modifier_val_imp (int)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Le flux impose est calcule a partir de la correlation de loi de paroi adaptative.
See also
Neumann
Member Function Documentation
initialiser()
int Dirichlet_loi_paroi::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour Contrairementaux methodes mettre_a_jour, les methodes initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Cond_lim_base.
References d_, Cond_lim_base::domaine_Cl_dis(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
liste_faces_loi_paroi()
void Dirichlet_loi_paroi::liste_faces_loi_paroi (IntTab & tab) virtual
References TRUSTVect< _TYPE_, _SIZE_ >::line_size().
compatible_avec_eqn()
int Dirichlet_loi_paroi::compatible_avec_eqn (const Equation_base & eqn) const override virtual
Reimplemented from Cond_lim_base.
References Equation_base::domaine_application(), and Cond_lim_base::err_pas_compatible().
avancer()
virtual int Dirichlet_loi_paroi::avancer (double temps) inline override virtual
Tourne la roue de la CL.
Reimplemented from Cond_lim_base.
mettre_a_jour()
void Dirichlet_loi_paroi::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Cond_lim_base.
References me_calculer(), and mon_temps.
associer_correlation()
virtual void Dirichlet_loi_paroi::associer_correlation (const Correlation_base & corr) inline virtual
associer_fr_dis_base()
void Dirichlet_loi_paroi::associer_fr_dis_base (const Frontiere_dis_base & fr) inline override virtual
Associe la frontiere a l'objet.
L'objet Frontiere_dis_base est en fait associe au membre OWN_PTR(Champ_front_base) de l'objet Cond_lim_base qui represente le champ des conditions aux limites imposees a la frontiere.
Parameters
(Frontiere_dis_base& fr) la frontiere sur laquelle on impose les conditions aux limites
Reimplemented from Cond_lim_base.
associer_domaine_cl_dis_base()
void Dirichlet_loi_paroi::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & zcl) inline override virtual
Associe le Domaine_Cl_dis_base (Domaine des conditions aux limites discretisees) a l'objet.
Ce Domaine_Cl_dis_base stocke (reference) toutes les conditions aux limites relative a un Domaine geometrique.
Parameters
(Domaine_Cl_dis_base& zcl) un Domaine des conditions aux limites discretisees a laquelle l'objet Cond_lim_base se rapporte
Reimplemented from Cond_lim_base.
completer()
virtual void Dirichlet_loi_paroi::completer () inline override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
fixer_nb_valeurs_temporelles()
virtual void Dirichlet_loi_paroi::fixer_nb_valeurs_temporelles (int nb_cases) inline override virtual
Appele par Conds_lim::completer Appel cha_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Cond_lim_base.
frontiere_dis() [1/2]
virtual Frontiere_dis_base& Dirichlet_loi_paroi::frontiere_dis () inline override virtual
Renvoie la frontiere discretisee a laquelle les conditions aux limites s'appliquent.
Returns
(Frontiere_dis_base&) la frontiere discretisee a laquelle les conditions aux limites sont associees
Reimplemented from Cond_lim_base.
frontiere_dis() [2/2]
virtual const Frontiere_dis_base& Dirichlet_loi_paroi::frontiere_dis () const inline override virtual
Renvoie la frontiere discretisee a laquelle les conditions aux limites s'appliquent.
(version const)
Returns
(Frontiere_dis_base&) la frontiere discretisee a laquelle les conditions aux limites sont associees
Reimplemented from Cond_lim_base.
changer_temps_futur()
virtual void Dirichlet_loi_paroi::changer_temps_futur (double temps, int i) inline override virtual
Change le i-eme temps futur de la CL.
Reimplemented from Cond_lim_base.
set_temps_defaut()
virtual void Dirichlet_loi_paroi::set_temps_defaut (double temps) inline override virtual
Change le i-eme temps futur de la cl.
Reimplemented from Cond_lim_base.
calculer_coeffs_echange()
virtual void Dirichlet_loi_paroi::calculer_coeffs_echange (double temps) inline override virtual
Calcul des coefficient d'echange pour un couplage par Champ_front_contact_VEF.
Ces calculs sont locaux au probleme et dependant uniquement de l'inconnue. Ils doivent donc etre faits chaque fois que l'inconnue est modifiee. Ils sont disponibles pour l'exterieur et stockes dans les CLs. WEC : Les Champ_front_contact_VEF devraient disparaitre et cette methode avec !!!
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Cond_lim_base.
verifie_ch_init_nb_comp()
void Dirichlet_loi_paroi::verifie_ch_init_nb_comp () const inline override virtual
Appel la verification du champ lu par l intermediaire de l equation pour laquelle on considere la condition limite.
La methode est surchargee dans les cas ou l utilisateur doit specifier le champ frontiere
Reimplemented from Dirichlet.
val_imp() [1/2]
virtual double Dirichlet_loi_paroi::val_imp (int i) const inline override virtual
Renvoie la valeur imposee sur la i-eme composante du champ a la frontiere au temps par defaut du champ_front.
Parameters
(int i) indice suivant la premiere dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Exceptions
deuxieme dimension du champ de frontiere superieur a 1
Reimplemented from Dirichlet.
References d_.
val_imp() [2/2]
virtual double Dirichlet_loi_paroi::val_imp (int i, int j) const inline override virtual
Renvoie la valeur imposee sur la (i,j)-eme composante du champ a la frontiere au temps par defaut du champ_front.
Parameters
(int i) indice suivant la premiere dimension du champ
(int j) indice suivant la deuxieme dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Reimplemented from Dirichlet.
References d_.
val_imp_au_temps() [1/2]
virtual double Dirichlet_loi_paroi::val_imp_au_temps (double temps, int i) const inline override virtual
Renvoie la valeur imposee sur la i-eme composante du champ a la frontiere au temps precise.
Reimplemented from Dirichlet.
References Process::exit(), and Objet_U::que_suis_je().
val_imp_au_temps() [2/2]
virtual double Dirichlet_loi_paroi::val_imp_au_temps (double temps, int i, int j) const inline override virtual
Renvoie la valeur imposee sur la (i,j)-eme composante du champ a la frontiere au temps precise.
Reimplemented from Dirichlet.
References Process::exit(), and Objet_U::que_suis_je().
me_calculer()
virtual void Dirichlet_loi_paroi::me_calculer () protected pure virtual
Referenced by mettre_a_jour().
OBS_PTR() [1/2]
Dirichlet_loi_paroi::OBS_PTR (Correlation_base) protected
OBS_PTR() [2/2]
Dirichlet_loi_paroi::OBS_PTR (Frontiere_dis_base) protected
Member Data Documentation
mon_temps
double Dirichlet_loi_paroi::mon_temps = -1.e8 protected
Referenced by mettre_a_jour().
d_
DoubleTab Dirichlet_loi_paroi::d_ protected
Referenced by initialiser(), and val_imp().