CEA TRUST Platform: Eval_Amont_PolyMAC_Elem Class Reference
Eval_Amont_PolyMAC_Elem Class Reference
Detailed Description
Evaluateur PolyMAC pour la convection Le champ convecte est scalaire (Champ_Elem_PolyMAC) Schema de convection Amont Rq:Les evaluateurs de flux convectifs calculent en fait le terme convectif qui figure au second membre de l'equation d'evolution c.a.d l'oppose du flux convectif pour la methode EXPLICITE.
Dans le cas de la methode IMPLICITE les evaluateurs calculent la quantite qui figure dans le premier membre de l'equation, nous ne prenons pas par consequent l'oppose en ce qui concerne les termes pour la matrice, par contre pour le second membre nous procedons comme en explicite mais en ne fesant intervenir que les valeurs fournies par les conditions limites.
Constructor & Destructor Documentation
Eval_Amont_PolyMAC_Elem()
Eval_Amont_PolyMAC_Elem::Eval_Amont_PolyMAC_Elem () inline
Member Function Documentation
calculer_flux_faces_echange_externe_impose()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_echange_externe_impose () const inline override virtual
Implements Eval_PolyMAC_Elem.
calculer_flux_faces_echange_global_impose()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_echange_global_impose () const inline override virtual
Implements Eval_PolyMAC_Elem.
calculer_flux_faces_entree_fluide()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_entree_fluide () const inline override virtual
Implements Eval_PolyMAC_Elem.
calculer_flux_faces_paroi()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_paroi () const inline override virtual
Implements Eval_PolyMAC_Elem.
calculer_flux_faces_paroi_adiabatique()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_paroi_adiabatique () const inline override virtual
Implements Eval_PolyMAC_Elem.
calculer_flux_faces_paroi_defilante()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_paroi_defilante () const inline override virtual
Implements Eval_PolyMAC_Elem.
calculer_flux_faces_paroi_fixe()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_paroi_fixe () const inline override virtual
Implements Eval_PolyMAC_Elem.
calculer_flux_faces_sortie_libre()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_sortie_libre () const inline override virtual
Implements Eval_PolyMAC_Elem.
calculer_flux_faces_symetrie()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_symetrie () const inline override virtual
Implements Eval_PolyMAC_Elem.
calculer_flux_faces_periodique()
int Eval_Amont_PolyMAC_Elem::calculer_flux_faces_periodique () const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [1/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const inline override virtual
Implements Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
flux_face() [2/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [3/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [4/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [5/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [6/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [7/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [8/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const inline override virtual
Implements Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
flux_face() [9/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [10/20]
double Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int) const inline override virtual
Implements Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
flux_faces_interne() [1/2]
double Eval_Amont_PolyMAC_Elem::flux_faces_interne (const DoubleTab & inco, int face) const inline override virtual
Implements Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
flux_face() [11/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Symetrie & , int , DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [12/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Periodique & la_cl, int num1, DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Evaluateur_PolyMAC::surface.
flux_face() [13/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
flux_face() [14/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
flux_face() [15/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int , DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [16/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int , DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [17/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int , DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [18/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Neumann_paroi & , int , DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [19/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , int , int , const Echange_externe_impose & , int , DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_face() [20/20]
void Eval_Amont_PolyMAC_Elem::flux_face (const DoubleTab & , int , const Echange_global_impose & , int , DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
flux_faces_interne() [2/2]
void Eval_Amont_PolyMAC_Elem::flux_faces_interne (const DoubleTab & inco, int face, DoubleVect & flux) const inline override virtual
Implements Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Evaluateur_PolyMAC::surface.
coeffs_face() [1/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Symetrie & , double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [2/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Neumann_sortie_libre & la_cl, double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
coeffs_face() [3/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Dirichlet_entree_fluide & la_cl, double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
coeffs_face() [4/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [5/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [6/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [7/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Neumann_paroi & , double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [8/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [9/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Echange_global_impose & , double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [10/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Periodique & la_cl, double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
coeffs_faces_interne() [1/2]
void Eval_Amont_PolyMAC_Elem::coeffs_faces_interne (int face, double & aii, double & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
coeffs_face_bloc_vitesse() [1/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Dirichlet_entree_fluide & la_cl, int num1) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
coeffs_face_bloc_vitesse() [2/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_defilante & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face_bloc_vitesse() [3/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Dirichlet_paroi_fixe & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face_bloc_vitesse() [4/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , int , int , const Echange_externe_impose & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face_bloc_vitesse() [5/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Echange_global_impose & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face_bloc_vitesse() [6/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face_bloc_vitesse() [7/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Neumann_paroi_adiabatique & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face_bloc_vitesse() [8/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Neumann_sortie_libre & la_cl, int num1) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
coeffs_face_bloc_vitesse() [9/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & , int , const Symetrie & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face_bloc_vitesse() [10/10]
double Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse (const DoubleTab & inco, int face, const Periodique & la_cl, int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
coeffs_faces_interne_bloc_vitesse()
double Eval_Amont_PolyMAC_Elem::coeffs_faces_interne_bloc_vitesse (const DoubleTab & inco, int face) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, and Evaluateur_PolyMAC::surface.
secmem_face() [1/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Symetrie & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [2/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int face, const Neumann_sortie_libre & la_cl, int num1) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
secmem_face() [3/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
secmem_face() [4/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [5/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [6/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [7/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Neumann_paroi & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [8/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [9/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Echange_global_impose & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [10/20]
double Eval_Amont_PolyMAC_Elem::secmem_face (int , const Periodique & , int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_faces_interne() [1/2]
double Eval_Amont_PolyMAC_Elem::secmem_faces_interne (int) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [11/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Symetrie & , DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [12/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Neumann_sortie_libre & la_cl, DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Evaluateur_PolyMAC::surface.
coeffs_face() [13/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Dirichlet_entree_fluide & la_cl, DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Evaluateur_PolyMAC::surface.
coeffs_face() [14/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Dirichlet_paroi_fixe & , DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [15/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Dirichlet_paroi_defilante & , DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [16/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Neumann_paroi_adiabatique & , DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [17/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Neumann_paroi & , DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [18/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , int , int , const Echange_externe_impose & , DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [19/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int , int , const Echange_global_impose & , DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
coeffs_face() [20/20]
void Eval_Amont_PolyMAC_Elem::coeffs_face (int face, int , const Periodique & la_cl, DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Evaluateur_PolyMAC::surface.
coeffs_faces_interne() [2/2]
void Eval_Amont_PolyMAC_Elem::coeffs_faces_interne (int face, DoubleVect & aii, DoubleVect & ajj) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Evaluateur_PolyMAC::surface.
secmem_face() [11/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Symetrie & , int , DoubleVect &) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [12/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int face, const Neumann_sortie_libre & la_cl, int num1, DoubleVect & flux) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), Evaluateur_PolyMAC::surface, and Neumann_sortie_libre::val_ext().
secmem_face() [13/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int face, const Dirichlet_entree_fluide & la_cl, int num1, DoubleVect & flux) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
References Eval_Conv_PolyMAC::dt_vitesse, Evaluateur_PolyMAC::elem_, Evaluateur_PolyMAC::porosite, TRUSTVect< _TYPE_, _SIZE_ >::size(), Evaluateur_PolyMAC::surface, and Dirichlet::val_imp().
secmem_face() [14/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Dirichlet_paroi_fixe & , int , DoubleVect &) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [15/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Dirichlet_paroi_defilante & , int , DoubleVect &) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [16/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Neumann_paroi_adiabatique & , int , DoubleVect &) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [17/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Neumann_paroi & , int , DoubleVect &) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [18/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int , int , int , const Echange_externe_impose & , int , DoubleVect &) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [19/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Echange_global_impose & , int , DoubleVect &) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_face() [20/20]
void Eval_Amont_PolyMAC_Elem::secmem_face (int , const Periodique & , int , DoubleVect &) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.
secmem_faces_interne() [2/2]
void Eval_Amont_PolyMAC_Elem::secmem_faces_interne (int , DoubleVect & flux) const inline override virtual
Reimplemented from Eval_PolyMAC_Elem.