CEA TRUST Platform: Solv_Cholesky Class Reference
Solv_Cholesky Class Reference
#include <Solv_Cholesky.h>
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Solv_Cholesky()
Solv_Cholesky::Solv_Cholesky () inline
References matrice_bande_factorisee_fortran_.
~Solv_Cholesky()
Solv_Cholesky::~Solv_Cholesky () inline override
Member Function Documentation
resoudre_systeme() [1/2]
int Solv_Cholesky::resoudre_systeme (const Matrice_Base & la_matrice, const DoubleVect & secmem, DoubleVect & solution) override virtual
Implements SolveurSys_base.
References Cholesky(), Process::exit(), Matrice_Bloc::get_bloc(), matrice_de_travail, Matrice_Bloc::nb_bloc_lignes(), and SolveurSys_base::nouvelle_matrice().
Referenced by resoudre_systeme().
resoudre_systeme() [2/2]
int Solv_Cholesky::resoudre_systeme (const Matrice_Base & M, const DoubleVect & A, DoubleVect & B, int niter_max) inline override virtual
Reimplemented from SolveurSys_base.
References resoudre_systeme().
solveur_direct()
int Solv_Cholesky::solveur_direct () const inline override virtual
Implements SolveurSys_base.
set_param()
void Solv_Cholesky::set_param (Param & param) protected
References Param::ajouter_flag(), Param::ajouter_non_std(), and SolveurSys_base::save_matrice_.
lire_motcle_non_standard()
int Solv_Cholesky::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References SolveurSys_base::fixer_limpr().
Cholesky()
int Solv_Cholesky::Cholesky (const Matrice_Morse_Sym & matrice, const DoubleVect & secmem, DoubleVect & solution) protected
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Fact_Cholesky(), SolveurSys_base::fixer_nouvelle_matrice(), Matrice_Sym::get_est_definie(), largeur_de_bande_, matrice_bande_factorisee_fortran_, Matrice_Morse_Sym::matrice_renumerotee(), SolveurSys_base::nouvelle_matrice(), Process::nproc(), Matrice_Morse::ordre(), Matrice_Morse_Sym::permutation(), Matrice_Morse_Sym::permutation_inverse(), Matrice_Morse_Sym::renumerote(), and TRUSTVect< _TYPE_, _SIZE_ >::size_totale().
Referenced by resoudre_systeme().
Fact_Cholesky()
int Solv_Cholesky::Fact_Cholesky (const Matrice_Morse_Sym & mat1, const int size_reelle) protected
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Process::exit(), Matrice_Morse_Sym::imprimer_formatte(), Matrice_Morse::largeur_de_bande(), largeur_de_bande_, matrice_bande_factorisee_fortran_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Cholesky().
Member Data Documentation
largeur_de_bande_
int Solv_Cholesky::largeur_de_bande_ = -100 protected
Referenced by Cholesky(), and Fact_Cholesky().
matrice_bande_factorisee_fortran_
ArrOfDouble Solv_Cholesky::matrice_bande_factorisee_fortran_ protected
Referenced by Cholesky(), Fact_Cholesky(), and Solv_Cholesky().
matrice_de_travail
Matrice_Morse_Sym Solv_Cholesky::matrice_de_travail protected
Referenced by resoudre_systeme().