CEA TRUST Platform: Interprete Class Reference
Interprete Class Reference abstract
Static Public Member Functions
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Ces objets definissent des actions a realiser lorsqu'on les rencontre dans le jeu de donnees. L'action est declenchee par un appel a la methode interpreter(). L'interprete peut ensuite lire des parametres supplementaires dans l'entree pour realiser sa tache. En general, l'interprete agit sur d'autres objets declares dans le jeu de donnees. Il peut y acceder par les methodes objet() et objet_existant(). Voir par exemple la classe Lire ou la classe Associer
See also
Interprete_bloc qui lit une serie d'instructions a executer dans le jeu de donnees.
Member Function Documentation
interpreter()
virtual Entree& Interprete::interpreter (Entree &) pure virtual
Implemented in Lml_2_Lata, Lata_2_Other, Link_CGNS_Files, Testeur_MEDCoupling, MaillerParallel, Interprete_geometrique_base_32_64< _SIZE_ >, Decouper_multi, Decouper_32_64< _SIZE_ >, Debog_Pb_Wrapper, Test_SSE_Kernels, EcritureLectureSpecial, Option_VDF, Option_PolyMAC, Typer_Lire, System, Stat_per_proc_perf_log, Option_Interpolation, My_Comm_Group, MultipleFiles, Mkdir, Lire_Fichier_Bin, Lire_Fichier, Lire, Execute_parallel, Ecrire_Fichier_Formatte, Ecrire_Fichier, Ecrire, Disable_TU, Deactivate_SIGINT_Catch, Moyenne_volumique, Merge_MED, Lata_2_MED, Ecrire_MED_32_64< _SIZE_ >, Ecrire_MED_32_64< int >, Ecrire_Champ_MED, Option_CGNS, Lata_2_CGNS, Integrer_champ_med, Test_solveur, Parallel_io_parameters, DebogIJK, Pilote_ICoCo, Scatter, PrecisionGeom, ModifyDomaineAxi1D, Dimension, Bidim_Axi, Axi, Analyse_Angle, Testeur, Resoudre, Porosites_champ, Discretiser, Diametre_hyd_champ, Build_Map_to_Structured, Associer, IJK_Lata_Swap_JK, Option_IJK, IJK_Test_Multigrille, and Option_DG.
Referenced by Interprete_bloc::interpreter_bloc().
objet()
Objet_U & Interprete::objet (const Nom & nom) static
Voir Interprete_bloc::objet_global() BM: la classe Interprete n'est pas le meilleur endroit pour cette.
methode mais on verra ca plus tard...
References Interprete_bloc::objet_global().
Referenced by Champ_front_recyclage::associer_champ_evaluateur(), Terme_Source_Rappel_T_VEF_Face::completer(), Champ_Generique_Extraction::completer(), Champ_Generique_Transformation::completer(), Partitionneur_Sous_Domaine::construire_partition(), Partitionneur_Union::construire_partition(), Champ_front_calc::creer(), Champ_front_contact_VEF::creer(), Moyenne_volumique::get_champ(), Champ_Generique_refChamp_special::get_champ(), Champ_Generique_base::get_discretisation(), Champ_Generique_base::get_ref_domain(), Champ_Generique_base::get_ref_domaine_dis_base(), Champ_Fonc_Tabule_Morceaux::initialiser(), TRUSTChamp_Don_generique< _TYPE_ >::interprete_get_domaine(), Associer::interpreter(), Discretiser::interpreter(), Resoudre::interpreter(), Analyse_Angle::interpreter(), ModifyDomaineAxi1D::interpreter(), Scatter::interpreter(), Pilote_ICoCo::interpreter(), Integrer_champ_med::interpreter(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::interpreter(), Ecrire::interpreter(), Lire::interpreter(), Lire_Fichier::interpreter(), Typer_Lire::interpreter(), MaillerParallel::interpreter(), Testeur_MEDCoupling::interpreter(), Create_domain_from_sub_domain::interpreter_(), Extraire_domaine::interpreter_(), Extraire_plan::interpreter_(), Extraire_surface::interpreter_(), ExtrudeBord::interpreter_(), Ecrire_Fichier::interpreter_(), Champ_Generique_refChamp::lire_motcle_non_standard(), Postraitement::lire_motcle_non_standard(), Perte_Charge_Singuliere::lire_surfaces(), Terme_Source_Canal_RANS_LES_VDF_Elem::mettre_a_jour(), Terme_Source_Canal_RANS_LES_VDF_Face::mettre_a_jour(), Discretisation_base::nommer_completer_champ_physique(), Champ_Input_Proto::read(), Porosites::remplir_champ(), Champ_Generique_Interpolation::set_domaine(), and Moyenne_volumique::traiter_champs().
objet_existant()
int Interprete::objet_existant (const Nom & nom) static
Renvoie 1 si l'objet existe, 0 sinon voir Interprete_bloc::objet_global_existant()
References Interprete_bloc::objet_global_existant().
Referenced by Lire::interpreter(), and Typer_Lire::interpreter().