CEA TRUST Platform: Paroi_hyd_base_EF Class Reference
Paroi_hyd_base_EF Class Reference
Additional Inherited Members
Public Member Functions inherited from Turbulence_paroi_base
void associer_modele (const Modele_turbulence_hyd_base &)
int calculer_hyd (Champ_Fonc_base &, Champ_Fonc_base &)
int calculer_hyd (Champ_Inc_base &)
virtual void imprimer_premiere_ligne_ustar (int, const LIST(Nom)&, const Nom &) const
virtual void imprimer_ustar_mean_only (Sortie &, int, const LIST(Nom)&, const Nom &) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Static Public Member Functions inherited from Turbulence_paroi_base
static void typer_lire_turbulence_paroi (OWN_PTR(Turbulence_paroi_base)&, const Modele_turbulence_hyd_base &, Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer()
void Paroi_hyd_base_EF::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override virtual
Implements Turbulence_paroi_base.
init_lois_paroi_()
void Paroi_hyd_base_EF::init_lois_paroi_ ()
References Turbulence_paroi_base::Cisaillement_paroi_, Domaine_VF::creer_tableau_faces_bord(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Domaine_VF::nb_faces_bord(), MD_Vector::non_nul(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Turbulence_paroi_base::tab_d_plus_, and Turbulence_paroi_base::tab_u_star_.
corriger_derivee_impl()
DoubleTab & Paroi_hyd_base_EF::corriger_derivee_impl (DoubleTab & d) const override virtual
Reimplemented from Turbulence_paroi_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), face_keps_imposee_, flag_face_keps_imposee_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
face_keps_imposee()
const ArrOfInt& Paroi_hyd_base_EF::face_keps_imposee () const inline
References face_keps_imposee_.
creer_champ()
void Paroi_hyd_base_EF::creer_champ (const Motcle & motlu) override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Turbulence_paroi_base::champs_compris_, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), and Equation_base::probleme().
get_champ()
const Champ_base & Paroi_hyd_base_EF::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Turbulence_paroi_base::champs_compris_, Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins(), Champs_compris_T< FIELD_TYPE >::get_champ(), Nom::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Equation_base::schema_temps(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Turbulence_paroi_base::tab_u_star_, and Schema_Temps_base::temps_courant().
Referenced by has_champ().
has_champ() [1/2]
bool Paroi_hyd_base_EF::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
References Turbulence_paroi_base::champs_compris_, get_champ(), Champs_compris_T< FIELD_TYPE >::has_champ(), and Nom::le_nom().
has_champ() [2/2]
bool Paroi_hyd_base_EF::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Turbulence_paroi_base::champs_compris_, Champs_compris_T< FIELD_TYPE >::has_champ(), and Nom::le_nom().
get_noms_champs_postraitables()
void Paroi_hyd_base_EF::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References Turbulence_paroi_base::get_noms_champs_postraitables().
Member Data Documentation
face_keps_imposee_
IntVect Paroi_hyd_base_EF::face_keps_imposee_ protected
Referenced by corriger_derivee_impl(), and face_keps_imposee().
flag_face_keps_imposee_
int Paroi_hyd_base_EF::flag_face_keps_imposee_ = 0 protected
Referenced by corriger_derivee_impl().