CEA TRUST Platform: Front_VF Class Reference
Front_VF Class Reference
Additional Inherited Members
Public Member Functions inherited from Frontiere_dis_base
void associer_frontiere (const Frontiere &)
Frontiere & frontiere ()
const Frontiere & frontiere () const
const Nom & le_nom () const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Frontiere_dis_base
Member Function Documentation
nb_faces()
int Front_VF::nb_faces () const inline
References Frontiere_dis_base::frontiere(), and Frontiere_32_64< _SIZE_ >::nb_faces().
Referenced by Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Source_Generique_VEF::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_bord_gen(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_bords(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Iterateur_VDF_Elem< _TYPE_ >::ajouter_contribution_autre_pb(), Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_contribution_bord_gen(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Iterateur_Source_Face< _TYPE_ >::ajouter_faces_bords(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Solveur_Masse_EF::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Champ_front_contact_VEF::calcul_coeff_amort(), Champ_P1NC::calcul_duidxj_paroi(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Champ_front_recyclage::calcul_moyenne_imposee(), Champ_front_recyclage::calcul_moyenne_recyclee(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Operateur_base::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Echange_contact_VDF::calculer_Teta_equiv(), Echange_contact_VDF::calculer_Teta_paroi(), Champ_front_calc_interne::completer(), Echange_contact_Correlation_VDF::completer(), Echange_interne_impose::completer(), Echange_contact_Correlation_VEF::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Diff_DG_Elem::contribuer_au_second_membre(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_bords(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Source_WC_Chaleur::correct_grad_boundary(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Domaine_VDF::creer_elements_fictifs(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Paroi_scal_hyd_base_EF::equivalent_distance_name(), Paroi_scal_hyd_base_VEF::equivalent_distance_name(), Paroi_scal_hyd_base_VDF::equivalent_distance_name(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Source_Masse_Fluide_Dilatable_base::fill_val_flux_tab(), Champ_P1NC_implementation::filtrer_resu(), Neumann::flux_impose(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_front_recyclage::get_coord_faces(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Iterateur_VDF_Elem< _TYPE_ >::impr(), Iterateur_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Turbulence_paroi_scal_base::imprimer_nusselt_mean_only(), Turbulence_paroi_base::imprimer_ustar_mean_only(), Echange_contact_Correlation_VEF::init(), Sonde::init_bords(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Paroi_scal_hyd_base_EF::init_lois_paroi(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Paroi_negligeable_VEF::init_lois_paroi(), Paroi_scal_hyd_base_VEF::init_lois_paroi(), Echange_contact_PolyMAC::initialiser(), Echange_contact_VDF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::initialiser(), Domaine_Cl_VEF::initialiser(), Champ_front_recyclage::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Assembleur_P_VDF::liste_faces_periodiques(), Domaine_VF::marquer_faces_double_contrib(), T_paroi_Champ_P0_VDF::me_calculer(), T_paroi_Champ_P1NC::me_calculer(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Champ_front_recyclage::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_synt::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Echange_interne_impose::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_VEF_Face_Gen< DERIVED_T >::modifie_pour_cl_gen(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Domaine_VDF::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VDF::modifier_secmem_pression_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), Domaine_Cl_VDF::nb_faces_sortie_libre(), Domaine_Cl_VEF::nb_faces_sortie_libre(), num_face(), num_local_face(), Assembleur_P_VDF::remplir(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), Op_Conv_VEF_Face::remplir_fluent(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC_P0::trace(), Champ_Face_PolyMAC_P0P1NC::trace(), Champ_Face_VDF_implementation::trace(), Champ_P1iP1B_implementation::trace(), Champ_Elem_PolyMAC::trace(), Echange_contact_Correlation_VDF::trier_coord(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Echange_interne_impose::update_inv_lambda(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), Echange_contact_VDF::verifier_correspondance(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
nb_faces_tot()
int Front_VF::nb_faces_tot () const inline
References Frontiere_dis_base::frontiere(), Frontiere_32_64< _SIZE_ >::get_faces_virt(), Frontiere_32_64< _SIZE_ >::nb_faces(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_EF::ajouter_bord(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Champ_Q1_EF::calcul_y_plus(), Champ_front_xyz_debit::calculer_champ_vitesse(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Domaine_VEF::construire_renum_arete_perio(), Source_PDF_EF::filtre_CLD(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Neumann::flux_impose(), Robin_VEF::flux_robin_normal_imp(), Robin_VEF::flux_robin_tangentiel_imp(), Champ_Generique_Tparoi_VEF::get_champ(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Champ_Inc_P0_base::init_fcl(), Champ_Face_base::init_fcl(), Champ_front_softanalytique::initialiser(), Champ_front_xyz_debit::initialiser_coefficient(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Domaine_VF::marquer_faces_double_contrib(), Champ_Front_Fonction::mettre_a_jour(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Op_EF_base::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), num_face(), Assembleur_P_VEF::remplir(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Domaine_Cl_EF::remplir_type_elem_Cl(), Echange_impose_base::tab_emissivite(), Echange_impose_base::tab_h_imp(), Echange_impose_base::tab_T_ext(), Dirichlet::tab_val_imp(), Frontiere_ouverte_rho_u_impose::tab_val_imp(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_front_debit_massique::update_coeff(), Neumann_sortie_libre::val_ext(), and Champ_Inc_base::valeur_aux_bords().
num_premiere_face()
int Front_VF::num_premiere_face () const inline
References Frontiere_dis_base::frontiere(), and Frontiere_32_64< _SIZE_ >::num_premiere_face().
Referenced by Op_Grad_PolyMAC_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Diff_VEF_Face_Q1::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Terme_Source_Qdm_Face_PolyMAC::ajouter(), Source_Generique_VEF::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Op_Grad_P0_to_Face::ajouter_blocs(), Op_Grad_VDF_Face::ajouter_blocs(), Terme_Source_Canal_perio_VDF_Face::ajouter_blocs(), Force_Centrifuge_VDF_Face_Axi::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_Coriolis_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Terme_Source_inc_VDF_Face::ajouter_blocs(), Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_bord_gen(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_bords(), Op_Diff_EF::ajouter_bords(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution(), Op_Diff_VEF_Face::ajouter_contribution(), Op_Diff_VEF_Face_Q1::ajouter_contribution(), Op_Diff_VEF_Face_Stab::ajouter_contribution(), Iterateur_VDF_Elem< _TYPE_ >::ajouter_contribution_autre_pb(), Op_Dift_VEF_Face_Gen< DERIVED_T >::ajouter_contribution_bord_gen(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords(), Iterateur_PolyMAC_Elem< _TYPE_ >::ajouter_contribution_bords_vitesse(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_elem(), Op_Diff_VEF_Anisotrope_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face::ajouter_contribution_multi_scalaire(), Op_Diff_VEF_Face_Stab::ajouter_contribution_multi_scalaire(), Op_Diff_EF::ajouter_contributions_bords(), Op_Dift_EF_Q1::ajouter_contributions_bords(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Iterateur_Source_Face< _TYPE_ >::ajouter_faces_bords(), Source_Fluide_Dilatable_VDF_Proto::ajouter_impl(), Source_Fluide_Dilatable_VEF_Proto::ajouter_impl(), Source_Masse_Fluide_Dilatable_VDF::ajouter_projection(), Source_Masse_Fluide_Dilatable_VEF::ajouter_projection(), Op_Grad_VEF_P1B_Face::ajouter_som(), Solveur_Masse_EF::appliquer_impl(), Masse_VDF_Face::appliquer_impl(), Masse_VEF_P1NC::appliquer_impl(), Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl(), BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Traitement_particulier_NS_chmoy_faceperio_VEF::calcul_chmoy_faceperio(), Champ_front_contact_VEF::calcul_coeff_amort(), Champ_P1NC::calcul_duidxj_paroi(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Champ_front_recyclage::calcul_moyenne_imposee(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Terme_Source_Canal_perio_VDF_Face::calculer_debit(), Terme_Source_Canal_perio_VEF_P1NC::calculer_debit(), Op_Diff_P1NC_barprim::calculer_divergence(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_dt_stab(), Iterateur_PolyMAC_Elem< _TYPE_ >::calculer_flux_bord(), Op_Grad_EF::calculer_flux_bords(), Op_Grad_VDF_Face::calculer_flux_bords(), EDO_Pression_th_VEF::calculer_grad(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Operateur_base::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Echange_contact_Correlation_VDF::calculer_Q(), Echange_contact_Correlation_VEF::calculer_Q(), Echange_contact_VDF::calculer_Teta_paroi(), Echange_contact_Correlation_VEF::completer(), Terme_Source_Canal_perio::compute_heat_flux(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Op_Conv_Amont_old_VEF_Face::contribue_au_second_membre(), Op_Conv_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Anisotrope_Face::contribue_au_second_membre(), Op_Diff_VEF_Face::contribue_au_second_membre(), Op_Diff_VEF_Face_Q1::contribue_au_second_membre(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Op_Grad_PolyMAC_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), Iterateur_PolyMAC_Elem< _TYPE_ >::contribuer_au_second_membre_bords(), Source_WC_Chaleur::correct_grad_boundary(), Op_Dift_VEF_P1NCP1B_Face::corriger_div_pour_Cl(), Domaine_VDF::creer_elements_fictifs(), Op_EF_base::dimensionner(), Op_PolyMAC_Elem::dimensionner(), Op_VDF_Face::dimensionner(), Domaine_Poly_base::dist_norm_bord(), Domaine_VDF::dist_norm_bord(), Source_Masse_Fluide_Dilatable_base::fill_val_flux_tab(), Paroi_hyd_base_EF::get_champ(), Turbulence_paroi_base::get_champ(), Champ_front_recyclage::get_coord_faces(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Iterateur_PolyMAC_Elem< _TYPE_ >::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Iterateur_VDF_Elem< _TYPE_ >::impr(), Iterateur_VDF_Face< _TYPE_ >::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Paroi_scal_hyd_base_EF::imprimer_nusselt(), Paroi_scal_hyd_base_VDF::imprimer_nusselt(), Paroi_scal_hyd_base_VEF::imprimer_nusselt(), Turbulence_paroi_scal_base::imprimer_nusselt_mean_only(), Turbulence_paroi_base::imprimer_ustar_mean_only(), Echange_contact_Correlation_VEF::init(), Sonde::init_bords(), Traitement_particulier_NS_chmoy_faceperio_VEF::init_calcul_stats(), Paroi_negligeable_VEF::init_lois_paroi(), Sortie_libre_Gradient_Pression_libre_VEF::initialiser(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::initialiser(), Domaine_Cl_VEF::initialiser(), Champ_front_tangentiel_VEF::initialiser(), Champ_front_recyclage::initialiser_moyenne_imposee(), Champ_front_recyclage::lire_fichier_format2(), Champ_front_recyclage::lire_fichier_format3(), Assembleur_P_VDF::liste_faces_periodiques(), Domaine_VF::marquer_faces_double_contrib(), T_paroi_Champ_P0_VDF::me_calculer(), T_paroi_Champ_P1NC::me_calculer(), Source_Masse_Fluide_Dilatable_base::mettre_a_jour(), Champ_front_pression_from_u::mettre_a_jour(), Champ_front_debit_QC::mettre_a_jour(), Champ_front_debit_QC_fonc_t::mettre_a_jour(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEF::mettre_a_jour(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::mettre_a_jour(), Boundary_field_inward::mettre_a_jour(), Champ_front_fonc_gradient_VDF::mettre_a_jour(), Sortie_libre_Gradient_Pression_impose::mettre_a_jour(), Sortie_libre_Pression_imposee_Orlansky::mettre_a_jour(), Echange_contact_Correlation_VEF::mettre_a_jour(), Sonde::mettre_a_jour_bords(), Op_Dift_VEF_Face_Gen< DERIVED_T >::modifie_pour_cl_gen(), Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Domaine_VDF::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Assembleur_P_EF::modifier_secmem(), Assembleur_P_PolyMAC::modifier_secmem(), Assembleur_P_VEF::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VDF::modifier_secmem_pression_imposee(), Assembleur_P_VDF::modifier_secmem_vitesse_imposee(), num_face(), num_local_face(), Assembleur_P_VDF::remplir(), Champ_front_contact_VEF::remplir_connect_bords(), Champ_front_contact_VEF::remplir_elems_voisin_bord(), Op_Conv_VEF_Face::remplir_fluent(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Champ_front_contact_VEF::test_faces_coin(), Champ_Face_PolyMAC::trace(), Champ_Face_PolyMAC_P0::trace(), Champ_Face_PolyMAC_P0P1NC::trace(), Champ_Face_VDF_implementation::trace(), Champ_P1iP1B_implementation::trace(), Echange_contact_Correlation_VDF::trier_coord(), Champ_Face_VDF::verifie_valeurs_cl(), Champ_P1NC::verifie_valeurs_cl(), Champ_Q1NC::verifie_valeurs_cl(), Echange_contact_VDF::verifier_correspondance(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
num_face() [1/2]
int Front_VF::num_face (const int ind_face) const inline
References Frontiere_dis_base::frontiere(), Frontiere_32_64< _SIZE_ >::get_faces_virt(), nb_faces(), and num_premiere_face().
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Div_VEFP1B_Elem::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Op_Grad_EF::ajouter_bord(), Op_Dift_EF_Q1::ajouter_bords(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Face::ajouter_cas_multi_scalaire(), Op_Diff_VEF_Anisotrope_Face::ajouter_cas_scalaire(), Op_Diff_VEF_Face::ajouter_cas_scalaire(), Op_Diff_VEFP1NCP1B_Face::ajouter_contribution_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Champ_Q1_EF::calcul_y_plus(), Op_Diff_VEFP1NCP1B_Face::calculer_divergence_som(), Op_Conv_VDF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab(), Op_Diff_VEFP1NCP1B_Face::calculer_dt_stab_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_elem(), Op_Diff_VEFP1NCP1B_Face::calculer_flux_bords_som(), Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEF_Face_Stab::calculer_max(), Op_Diff_VEF_Face_Stab::calculer_min(), Champ_front_xyz_debit::calculer_normales_et_integrale(), Sortie_libre_Gradient_Pression_impose_VEFPreP1B::calculer_trace_pression(), Op_Diff_VEF_Face_Stab::completer(), Op_Dift_Stab_VEF_Face::completer(), Domaine_VEF::construire_renum_arete_perio(), Op_Diff_DG_Elem::contribuer_au_second_membre(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Op_Diff_VDF_Elem_base::contribuer_termes_croises(), Op_Diff_VEFP1NCP1B_Face::corriger_Cl_test(), Op_Diff_VEFP1NCP1B_Face::corriger_div_pour_Cl(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), Op_Diff_VDF_Elem_base::dimensionner_termes_croises(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Source_PDF_EF::filtre_CLD(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::filtrer_resu(), Champ_Generique_Tparoi_VEF::get_champ(), Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_VEF::imposer_cond_lim(), Domaine_Cl_EF::imposer_symetrie_partiellement(), Champ_Inc_P0_base::init_fcl(), Champ_Face_base::init_fcl(), Paroi_scal_hyd_base_VDF::init_lois_paroi(), Echange_contact_VDF::initialiser(), Champ_front_softanalytique::initialiser(), Op_Diff_VEFP1NCP1B_Face::isFaceOfSymetry(), Op_Diff_VEFP1NCP1B_Face::liste_face(), Domaine_VF::marquer_faces_double_contrib(), Champ_Front_Fonction::mettre_a_jour(), Op_Diff_VEF_Face_Stab::modifie_pour_Cl(), Op_Dift_VEF_Face_Gen< DERIVED_T >::modifie_pour_cl_gen(), Domaine_EF::modifier_pour_Cl(), Domaine_Poly_base::modifier_pour_Cl(), Domaine_VF::modifier_pour_Cl(), Domaine_PolyMAC::modifier_pour_Cl(), Domaine_VEF::modifier_pour_Cl(), Op_EF_base::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem_elem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VEF::remplir(), Op_Dift_EF_Q1::remplir_marqueur_elem_CL_paroi(), Domaine_Cl_EF::remplir_type_elem_Cl(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), Op_Diff_VEFP1NCP1B_Face::test(), Champ_Elem_PolyMAC::trace(), Champ_front_debit_massique::update_coeff(), Echange_contact_PolyMAC::update_coeffs(), Echange_contact_PolyMAC::update_delta(), Echange_interne_impose::update_inv_lambda(), and Champ_Inc_base::valeur_aux_bords().
num_local_face()
int Front_VF::num_local_face (const int ind_global_face) const inline
References Frontiere_dis_base::frontiere(), Frontiere_32_64< _SIZE_ >::get_faces_virt(), nb_faces(), num_premiere_face(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Paroi_scal_hyd_base_VDF::compute_nusselt().
num_face() [2/2]
const ArrOfInt & Front_VF::num_face () const inline
References nb_faces_tot(), num_face_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Member Data Documentation
num_face_
ArrOfInt Front_VF::num_face_ mutable protected
Referenced by num_face().