CEA TRUST Platform: Pb_Multiphase Class Reference
Pb_Multiphase Class Reference
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
double calculer_pas_de_temps () const override
const Equation_base & equation (int) const override
Equation_base & equation (int) override
int nombre_d_equations () const override
int verifier () override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
virtual void finir ()
double futureTime () const override
void getInputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_U
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual bool run ()
virtual bool runUntil (double time)
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
 - QDM_Multiphase : equations de Navier-Stokes et de continuite pour chaque phase
                    inconnues : v_k (vitesses par phase)
                    champs auxiliaires : pression p, taux de presence a_k (sum a_k = 1)
 - Energie_Multiphase : equations de conservation de l'energie pour chaque phase
                        inconnues : T_k (temperatures)
schema de resolution typique : 1) QDM_Multiphase -> prediction des vitesses conservation de la masse -> Newton (etape "semi-implicite") 3) Energie_Multiphase -> advection/dffusion implicite de l'energie
See also
Pb_Fluide_base QDM_Multiphase Masse_Multiphase Energie_Multiphase
Member Function Documentation
typer_lire_milieu()
void Pb_Multiphase::typer_lire_milieu (Entree & is) override virtual
Reimplemented from Probleme_base.
References associer_milieu_base(), Equation_base::associer_milieu_equation(), Milieu_base::discretiser(), Probleme_base::discretiser_equations(), equation(), Process::exit(), Probleme_base::le_milieu_, Equation_base::milieu(), nombre_d_equations(), noms_phases_, and Objet_U::que_suis_je().
nombre_d_equations()
int Pb_Multiphase::nombre_d_equations () const override virtual
Renvoie le nombre d'equation, Renvoie 2 car il y a 2 equations a un probleme de.
thermo-hydraulique standard: l'equation de Navier Stokes l' equation de la thermique de type Convection_Diffusion_Temperature
Returns
(int) le nombre d'equation
Implements Probleme_base.
Referenced by calculer_pas_de_temps(), SETS::iterer_NS(), lire_equations(), and typer_lire_milieu().
equation() [1/2]
const Equation_base & Pb_Multiphase::equation (int i) const override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0 Renvoie l'equation de la thermique de type.
Convection_Diffusion_Temperature si i=1 (version const)
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation correspondante a l'index
Implements Probleme_base.
Reimplemented in Pb_Multiphase_Enthalpie.
References eq_energie_, eq_masse_, eq_qdm_, and Process::exit().
Referenced by Solveur_Masse_Face_proto::ajouter_blocs_proto(), Solveur_Masse_Face_proto::appliquer_impl_proto(), Assembleur_P_VDF::assembler_continuite(), calculer_pas_de_temps(), Solveur_Masse_Face_proto::dimensionner_blocs_proto(), Assembleur_P_VDF::dimensionner_continuite(), Pb_Multiphase_Enthalpie::equation(), SETS::iterer_NS(), and typer_lire_milieu().
equation() [2/2]
Equation_base & Pb_Multiphase::equation (int i) override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0 Renvoie l'equation de la thermique de type.
Convection_Diffusion_Temperature si i=1
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation correspondante a l'index
Implements Probleme_base.
Reimplemented in Pb_Multiphase_Enthalpie.
References eq_energie_, eq_masse_, eq_qdm_, and Process::exit().
associer_milieu_base()
void Pb_Multiphase::associer_milieu_base (const Milieu_base & mil) override virtual
Associe le milieu au probleme Le milieu doit etre de type fluide incompressible.
Parameters
(Milieu_base& mil) le milieu physique a associer au probleme
Exceptions
mauvais type de milieu physique
Reimplemented from Probleme_base.
Reimplemented in Pb_Multiphase_Enthalpie.
References Equation_base::associer_milieu_base(), equation_energie(), equation_masse(), and equation_qdm().
Referenced by typer_lire_milieu().
lire_equations()
Entree & Pb_Multiphase::lire_equations (Entree & is, Motcle & dernier_mot) override virtual
Lecture des equations du probleme.
Reimplemented from Probleme_base.
References Process::exit(), Probleme_base::getset_equation_by_name(), Probleme_base::lire_correlations(), nombre_d_equations(), Probleme_base::read_optional_equations(), and typer_lire_correlation_hem().
verifier()
int Pb_Multiphase::verifier () override virtual
Teste la compatibilite des equations de la thermique et de l'hydraulique.
Le test se fait sur les conditions aux limites discretisees de chaque equation. Appel la fonction de librairie hors classe: tester_compatibilite_hydr_thermique(const Domaine_Cl_dis_base&,const Domaine_Cl_dis_base&)
Returns
(int) code de retour propage
Reimplemented from Probleme_base.
Reimplemented in Pb_Multiphase_Enthalpie.
References Equation_base::domaine_Cl_dis(), equation_energie(), and equation_qdm().
preparer_calcul()
void Pb_Multiphase::preparer_calcul () override virtual
Prepare le calcul: initialise les parametres du milieu et prepare le calcul de chacune des equations.
Reimplemented from Probleme_base.
References Probleme_base::mettre_a_jour(), Probleme_base::preparer_calcul(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
nb_phases()
int Pb_Multiphase::nb_phases () const inline
References noms_phases_.
Referenced by QDM_Multiphase::alpha_res(), Flux_interfacial_Chen_Mayinger::completer(), Flux_interfacial_Kim_Park::completer(), Flux_interfacial_Ranz_Marshall::completer(), Flux_interfacial_Wolfert::completer(), Flux_interfacial_Wolfert_composant::completer(), Flux_interfacial_Zeitoun::completer(), Source_Portance_interfaciale_base::creer_champ(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::get_noms_champs_postraitables(), QDM_Multiphase::get_noms_champs_postraitables(), Op_Conv_VDF_base::get_noms_champs_postraitables(), and Pb_Multiphase_HEM::typer_lire_correlation_hem().
nom_phase()
const Nom& Pb_Multiphase::nom_phase (int i) const inline
References noms_phases_.
Referenced by Flux_interfacial_Chen_Mayinger::completer(), Flux_interfacial_Kim_Park::completer(), Flux_interfacial_Ranz_Marshall::completer(), Flux_interfacial_Wolfert::completer(), Flux_interfacial_Wolfert_composant::completer(), Flux_interfacial_Zeitoun::completer(), Energie_Multiphase::discretiser(), Energie_Multiphase_Enthalpie::discretiser(), Masse_Multiphase::discretiser(), and Pb_Multiphase_HEM::typer_lire_correlation_hem().
noms_phases()
const Noms& Pb_Multiphase::noms_phases () const inline
References noms_phases_.
calculer_pas_de_temps()
double Pb_Multiphase::calculer_pas_de_temps () const override virtual
Calcul la valeur du prochain pas de temps du probleme.
On calcule le minimum des pas de temps des equations associees au probleme.
Returns
(double) le pas de temps maximum autorise pour ce probleme
Reimplemented from Probleme_base.
References Operateur::calculer_pas_de_temps(), Probleme_base::calculer_pas_de_temps(), equation(), Operateur::l_op_base(), nombre_d_equations(), Equation_base::nombre_d_operateurs(), Equation_base::operateur(), Schema_Temps_base::pas_temps_max(), Objet_U::que_suis_je(), and Probleme_base::schema_temps().
typer_lire_correlation_hem()
virtual void Pb_Multiphase::typer_lire_correlation_hem () inline virtual
Reimplemented in Pb_Multiphase_HEM.
Referenced by lire_equations().
equation_qdm() [1/2]
virtual Equation_base& Pb_Multiphase::equation_qdm () inline virtual
References eq_qdm_.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), associer_milieu_base(), Pb_Multiphase_Enthalpie::associer_milieu_base(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), Interface_base::mettre_a_jour(), Saturation_base::mettre_a_jour(), verifier(), and Pb_Multiphase_Enthalpie::verifier().
equation_qdm() [2/2]
virtual const Equation_base& Pb_Multiphase::equation_qdm () const inline virtual
References eq_qdm_.
equation_masse() [1/2]
virtual Equation_base& Pb_Multiphase::equation_masse () inline virtual
References eq_masse_.
Referenced by Perte_Charge_Singuliere_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Perte_Charge_Singuliere_PolyMAC_P0P1NC_Face::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Travail_pression_Elem_base::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Solveur_Masse_Face_proto::ajouter_blocs_proto(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), associer_milieu_base(), Pb_Multiphase_Enthalpie::associer_milieu_base(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_elem(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_faces(), Op_Evanescence_Homogene_VDF_Face::calc_grad_alpha_faces(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), and Op_Evanescence_Homogene_VDF_Face::preparer_calcul().
equation_masse() [2/2]
virtual const Equation_base& Pb_Multiphase::equation_masse () const inline virtual
References eq_masse_.
equation_energie() [1/2]
virtual Equation_base& Pb_Multiphase::equation_energie () inline virtual
Reimplemented in Pb_Multiphase_Enthalpie.
References eq_energie_.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), associer_milieu_base(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), Interface_base::mettre_a_jour(), and verifier().
equation_energie() [2/2]
virtual const Equation_base& Pb_Multiphase::equation_energie () const inline virtual
Reimplemented in Pb_Multiphase_Enthalpie.
References eq_energie_.
resolution_en_T()
virtual bool Pb_Multiphase::resolution_en_T () const inline virtual
Reimplemented in Pb_Multiphase_Enthalpie.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), and SETS::iterer_NS().
Member Data Documentation
noms_phases_
Noms Pb_Multiphase::noms_phases_ protected
Referenced by nb_phases(), nom_phase(), noms_phases(), and typer_lire_milieu().
eq_qdm_
QDM_Multiphase Pb_Multiphase::eq_qdm_ protected
Referenced by equation(), and equation_qdm().
eq_energie_
Energie_Multiphase Pb_Multiphase::eq_energie_ protected
Referenced by equation(), and equation_energie().
eq_masse_
Masse_Multiphase Pb_Multiphase::eq_masse_ protected
Referenced by equation(), and equation_masse().