CEA TRUST Platform: Static_Int_Lists_32_64< _SIZE_ > Class Template Reference
Static_Int_Lists_32_64< _SIZE_ > Class Template Reference
#include <Static_Int_Lists.h>
Public Member Functions
void set_data (const ArrOfInt_t &data)
void set_list_sizes (const ArrOfInt_t &sizes)
void trier_liste (int_t i)
Detailed Description
template<typename _SIZE_>
class Static_Int_Lists_32_64< _SIZE_ >
La taille des listes ne peut pas changer sans perdre le contenu (ce sont des listes statiques). Exemple: Static_Int_List l; ArrOfInt tailles(3); tailles[0] = 2; tailles[1] = 3; tailles[2] = 0; // On reserve la memoire pour trois listes de taille 2, 3 et 0: l.set_list_sizes(tailles); // On affecte une valeur au deuxieme element de la premiere liste: l.set_value(0,1,765); // Affiche la valeur Cout << l(0,1);
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Static_Int_Lists_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Static_Int_Lists_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
ArrsOfInt_t
template<typename _SIZE_ > using Static_Int_Lists_32_64< _SIZE_ >::ArrsOfInt_t = ArrsOfInt_T<_SIZE_>
Member Function Documentation
set_list_sizes()
template<typename _SIZE_ > void Static_Int_Lists_32_64< _SIZE_ >::set_list_sizes (const ArrOfInt_t & sizes)
detruit les listes existantes et en cree de nouvelles.
On cree autant de listes que d'elements dans le tableau sizes. La i-ieme liste a une taille sizes[i] Les valeurs sizes doivent etre positives ou nulles.
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by MD_Vector_std::append_from_other_std(), Refine_Mesh::build_incidence_from_node_to_edges(), Scatter::calculer_espace_distant_elements(), Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), and Decouper_multi::interpreter().
reset()
template<typename _SIZE_ > void Static_Int_Lists_32_64< _SIZE_ >::reset ()
detruit toutes les listes
copy_list_to_array()
template<typename _SIZE_ > void Static_Int_Lists_32_64< _SIZE_ >::copy_list_to_array (int_t i_liste, ArrOfInt_t & array) const
copie la i-ieme liste dans le tableau fourni Le tableau array doit etre resizable.
References TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by MD_Vector_std::append_from_other_std(), and Refine_Mesh::find_edge().
set_value()
template<typename _SIZE_ > void Static_Int_Lists_32_64< _SIZE_ >::set_value (int_t i_liste, int_t i_element, int_t valeur) inline
affecte la "valeur" au j-ieme element de la i-ieme liste avec 0 <= i < get_nb_lists() et 0 <= j < get_list_size(i)
Referenced by Refine_Mesh::build_incidence_from_node_to_edges(), Scatter::calculer_espace_distant_elements(), Partitionneur_base_32_64< _SIZE_ >::calculer_graphe_connexions_periodiques(), and Decouper_multi::interpreter().
operator()()
template<typename _SIZE_ > Static_Int_Lists_32_64< _SIZE_ >::int_t Static_Int_Lists_32_64< _SIZE_ >::operator() (int_t i_liste, int_t i_element) const inline
renvoie le j-ieme element de la i-ieme liste avec 0 <= i < get_nb_lists() et 0 <= j < get_list_size(i)
get_list_size()
template<typename _SIZE_ > Static_Int_Lists_32_64< _SIZE_ >::int_t Static_Int_Lists_32_64< _SIZE_ >::get_list_size (int_t i_liste) const inline
renvoie le nombre d'elements de la liste i
Referenced by MD_Vector_std::append_from_other_std(), Assembleur_P_EF::assembler_mat(), Scatter::calculer_espace_distant_elements(), Domain_Graph::construire_graph_elem_elem(), Domaine_VEF::construire_ok_arete(), Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_graphe(), Partitionneur_base_32_64< _SIZE_ >::corriger_multiperiodique(), Partitionneur_base_32_64< _SIZE_ >::corriger_sommets_bord(), Domaine_PolyMAC_P0::fgrad(), MD_Vector_std::fill_md_vect_renum(), MD_Vector_std::MD_Vector_std(), and Domaine_Cl_EF::remplir_type_elem_Cl().
get_nb_lists()
template<typename _SIZE_ > Static_Int_Lists_32_64< _SIZE_ >::int_t Static_Int_Lists_32_64< _SIZE_ >::get_nb_lists () const inline
renvoie le nombre de listes stockees
Referenced by Partitionneur_Metis_32_64< _SIZE_ >::construire_partition(), Partitionneur_Parmetis::construire_partition(), Partitionneur_Ptscotch::construire_partition(), Partitionneur_base_32_64< _SIZE_ >::corriger_bords_avec_graphe(), Faces_builder::creer_faces_reeles(), Raffiner_Simplexes_32_64< _SIZE_ >::refine_domain(), and Domaine_Poly_base::som_elem().
get_index()
template<typename _SIZE_ > const ArrOfInt_t & Static_Int_Lists_32_64< _SIZE_ >::get_index () const inline
get_data()
template<typename _SIZE_ > const ArrOfInt_t & Static_Int_Lists_32_64< _SIZE_ >::get_data () const inline
Referenced by MD_Vector_std::fill_md_vect_renum(), and MD_Vector_std::MD_Vector_std().
set_data()
template<typename _SIZE_ > void Static_Int_Lists_32_64< _SIZE_ >::set_data (const ArrOfInt_t & data)
remplace les valeurs stockes par toutes les listes par celles du tableau data.
data doit avoir pour taille la somme des tailles de toutes les listes.
Referenced by MD_Vector_std::append_from_other_std().
set_index_data()
template<typename _SIZE_ > void Static_Int_Lists_32_64< _SIZE_ >::set_index_data (const ArrOfInt_t & index, const ArrOfInt_t & data)
remplace index et data.
Referenced by MD_Vector_std::fill_md_vect_renum().
trier_liste()
template<typename _SIZE_ > void Static_Int_Lists_32_64< _SIZE_ >::trier_liste (int_t num_liste)
tri par ordre croissant des valeurs de la i-ieme liste.
Si num_liste < 0, on trie toutes les listes.
References TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array(), and TRUSTArray< _TYPE_, _SIZE_ >::ref_array().
Referenced by Refine_Mesh::build_incidence_from_node_to_edges().
set()
template<typename _SIZE_ > void Static_Int_Lists_32_64< _SIZE_ >::set (const ArrsOfInt_t & src)
References TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by MD_Vector_std::MD_Vector_std().
printOn()
template<typename _SIZE_ > Sortie & Static_Int_Lists_32_64< _SIZE_ >::printOn (Sortie & os) const
readOn()
template<typename _SIZE_ > Entree & Static_Int_Lists_32_64< _SIZE_ >::readOn (Entree & is)
ecrire()
template<typename _SIZE_ > Sortie & Static_Int_Lists_32_64< _SIZE_ >::ecrire (Sortie & os) const