CEA TRUST Platform: OctreeRoot_32_64< _SIZE_ > Class Template Reference
OctreeRoot_32_64< _SIZE_ > Class Template Reference
Public Member Functions
int construit () const
int_t rang_arete (const DoubleTab &positions, SmallArrOfTID_t &aretes) const
int_t rang_arete (double x, double y=0, double z=0) const
int_t rang_elem (const DoubleTab &positions, SmallArrOfTID_t &elem) const
int_t rang_elem (double x, double y=0, double z=0) const
int_t rang_elem_depuis (const DoubleTab &positions, const SmallArrOfTID_t &prems, SmallArrOfTID_t &elems) const
int_t rang_elem_depuis (int_t prems, double x, double y=0, double z=0) const
void rang_elems_sommet (SmallArrOfTID_t &, double x, double y=0, double z=0) const
int_t rang_sommet (const DoubleTab &positions, SmallArrOfTID_t &sommets) const
int_t rang_sommet (double x, double y=0, double z=0) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Octree_32_64< _SIZE_ >
void construire (int, const ArrOfInt_t &, const OctreeLoc &, Octree_t *p=0)
virtual int_t rang_elem_depuis_loc (const OctreeLoc &, int_t prems, double x, double y=0, double z=0) const
virtual int_t rang_elem_loc (const OctreeLoc &, double x, double y=0, double z=0) const
virtual int_t taille () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Octree_32_64< _SIZE_ >
void detruire ()
Detailed Description
template<typename _SIZE_>
class OctreeRoot_32_64< _SIZE_ >
See also
OctreeLoc Octree OctreeFloor
Member Typedef Documentation
int_t
template<typename _SIZE_ > using OctreeRoot_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using OctreeRoot_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using OctreeRoot_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using OctreeRoot_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using OctreeRoot_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using OctreeRoot_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Octree_t
template<typename _SIZE_ > using OctreeRoot_32_64< _SIZE_ >::Octree_t = Octree_32_64<_SIZE_>
Constructor & Destructor Documentation
OctreeRoot_32_64() [1/3]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::OctreeRoot_32_64 () inline
OctreeRoot_32_64() [2/3]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::OctreeRoot_32_64 (const Domaine_t & z) inline
References OctreeRoot_32_64< _SIZE_ >::associer_Domaine(), and OctreeRoot_32_64< _SIZE_ >::construire().
OctreeRoot_32_64() [3/3]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::OctreeRoot_32_64 (const OctreeRoot_32_64< _SIZE_ > & oc) inline
References OctreeRoot_32_64< _SIZE_ >::associer_Domaine(), OctreeRoot_32_64< _SIZE_ >::construire(), OctreeRoot_32_64< _SIZE_ >::construit(), OctreeRoot_32_64< _SIZE_ >::domaine(), and OctreeRoot_32_64< _SIZE_ >::valid_.
Member Function Documentation
rang_sommet() [1/2]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::int_t OctreeRoot_32_64< _SIZE_ >::rang_sommet (double x, double y = 0, double z = 0) const
Parameters
(double x)
(double y)
(double z)
Returns
(int)
Exceptions
Erreur dans OctreeRoot_32_64<SIZE>::rang_sommet
On a pas trouve de sommet a ces coordonnees
References Domaine_32_64< _SIZE_ >::coord(), Objet_U::dimension, Process::exit(), Domaine_32_64< _SIZE_ >::nb_som_elem(), and Domaine_32_64< _SIZE_ >::sommet_elem().
Referenced by Domaine_32_64< _SIZE_ >::chercher_sommets().
rang_arete() [1/2]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::int_t OctreeRoot_32_64< _SIZE_ >::rang_arete (double x, double y = 0, double z = 0) const
Parameters
(double x)
(double y)
(double z)
Returns
(int)
Exceptions
Erreur dans OctreeRoot_32_64<SIZE>::rang_arete
On a pas trouve d'arete a ces coordonnees
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), and Process::exit().
Referenced by Domaine_32_64< _SIZE_ >::chercher_aretes().
rang_elem() [1/2]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::int_t OctreeRoot_32_64< _SIZE_ >::rang_elem (double x, double y = 0, double z = 0) const
Parameters
(double x)
(double y)
(double z)
Returns
(int)
References Octree_32_64< _SIZE_ >::rang_elem_loc().
Referenced by Domaine_32_64< _SIZE_ >::chercher_elements().
rang_elem_depuis() [1/2]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::int_t OctreeRoot_32_64< _SIZE_ >::rang_elem_depuis (int_t prems, double x, double y = 0, double z = 0) const
Parameters
(int prems)
(double x)
(double y)
(double z)
References Octree_32_64< _SIZE_ >::rang_elem_depuis_loc().
rang_elem_depuis() [2/2]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::int_t OctreeRoot_32_64< _SIZE_ >::rang_elem_depuis (const DoubleTab & positions, const SmallArrOfTID_t & prems, SmallArrOfTID_t & elems) const
Parameters
(DoubleTab& positions)
(ArrOfInt& prems)
(ArrOfInt& elems)
Exceptions
dimension d'espace non prevue
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
rang_sommet() [2/2]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::int_t OctreeRoot_32_64< _SIZE_ >::rang_sommet (const DoubleTab & positions, SmallArrOfTID_t & sommets) const
Parameters
(DoubleTab& positions)
(ArrOfInt& sommets)
Returns
(int)
Exceptions
dimension d'espace non prevue
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
rang_arete() [2/2]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::int_t OctreeRoot_32_64< _SIZE_ >::rang_arete (const DoubleTab & positions, SmallArrOfTID_t & aretes) const
Parameters
(IntTab& elem_aretes) Definition des aretes par leur sommet
(DoubleTab& positions)
(ArrOfInt& aretes) Les aretes trouvees
Returns
(int)
Exceptions
dimension d'espace non prevue
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
rang_elem() [2/2]
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::int_t OctreeRoot_32_64< _SIZE_ >::rang_elem (const DoubleTab & positions, SmallArrOfTID_t & elems) const
Parameters
(DoubleTab& positions)
(ArrOfInt& elems)
Returns
(int)
Exceptions
dimension d'espace non prevue
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::exit(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
rang_elems_sommet()
template<typename _SIZE_ > void OctreeRoot_32_64< _SIZE_ >::rang_elems_sommet (SmallArrOfTID_t & elements, double x, double y = 0, double z = 0) const
Parameters
(ArrOfInt& elements) we suppose we look for a small number of elements!
(double x)
(double y)
(double z)
References Octree_32_64< _SIZE_ >::rang_elem_depuis_loc(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by Perte_Charge_Singuliere::lire_surfaces(), and Domaine_32_64< _SIZE_ >::rang_elems_sommet().
domaine()
template<typename _SIZE_ > const Domaine_t& OctreeRoot_32_64< _SIZE_ >::domaine () const inline override virtual
Reimplemented from Octree_32_64< _SIZE_ >.
Referenced by OctreeRoot_32_64< _SIZE_ >::OctreeRoot_32_64().
associer_Domaine()
template<typename _SIZE_ > void OctreeRoot_32_64< _SIZE_ >::associer_Domaine (const Domaine_t & d) inline
Referenced by Domaine_32_64< _SIZE_ >::construit_octree(), and OctreeRoot_32_64< _SIZE_ >::OctreeRoot_32_64().
construire()
template<typename _SIZE_ > void OctreeRoot_32_64< _SIZE_ >::construire (int reel = 0)
References Octree_32_64< _SIZE_ >::construire(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_32_64< _SIZE_ >::nb_elem(), and Domaine_32_64< _SIZE_ >::nb_elem_tot().
Referenced by Domaine_32_64< _SIZE_ >::construit_octree(), and OctreeRoot_32_64< _SIZE_ >::OctreeRoot_32_64().
construit()
template<typename _SIZE_ > int OctreeRoot_32_64< _SIZE_ >::construit
Renvoie vrai si le domaine associe a l'octree est non nulle.
Returns
(int) code de retour propage
Referenced by Domaine_32_64< _SIZE_ >::construit_octree(), and OctreeRoot_32_64< _SIZE_ >::OctreeRoot_32_64().
invalide()
template<typename _SIZE_ > void OctreeRoot_32_64< _SIZE_ >::invalide
reel()
template<typename _SIZE_ > int OctreeRoot_32_64< _SIZE_ >::reel () const inline
References OctreeRoot_32_64< _SIZE_ >::reel_.
Referenced by Domaine_32_64< _SIZE_ >::construit_octree().
OBS_PTR()
template<typename _SIZE_ > OctreeRoot_32_64< _SIZE_ >::OBS_PTR (Domaine_t) protected
Member Data Documentation
loc
template<typename _SIZE_ > OctreeLoc OctreeRoot_32_64< _SIZE_ >::loc protected
valid_
template<typename _SIZE_ > int OctreeRoot_32_64< _SIZE_ >::valid_ protected
Referenced by OctreeRoot_32_64< _SIZE_ >::OctreeRoot_32_64().
reel_
template<typename _SIZE_ > int OctreeRoot_32_64< _SIZE_ >::reel_ = -1 protected
Referenced by OctreeRoot_32_64< _SIZE_ >::reel().
les_octrees
template<typename _SIZE_ > Octree_32_64** Octree_32_64< _SIZE_ >::les_octrees protected
pere
template<typename _SIZE_ > Octree_32_64* Octree_32_64< _SIZE_ >::pere protected