CEA TRUST Platform: Dispersion_bulles_base Class Reference
Dispersion_bulles_base Class Reference abstract
#include <Dispersion_bulles_base.h>
Classes
struct input_t
struct output_t
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
 exercee sur le gaz par le liquide prend la forme
 F_{kl} = - F_{lk} = - C_{kl} grad(alpha{k}) + C_{lk} grad(alpha{l}) ou la phase
 l est la phase liquide porteuse et k != 0 une phase quelconque
 cette classe definit une fonction C_{kl}!=C_{lk} dependant de :
   alpha, p, T -> inconnues (une valeur par phase chacune)
   rho, mu, sigma, nut, k_turb -> proprietes physiques (idem)
   ndv(k, l) -> ||v_k - v_l||, a remplir pour k < l
sortie : coeff(k, l, 0/1) -> coefficient C_{kl} et sa derivee en ndv(k, l), rempli pour k < l
Member Function Documentation
coefficient()
virtual void Dispersion_bulles_base::coefficient (const input_t & input, output_t & output) const pure virtual
Implemented in Dispersion_bulles_constante.
Referenced by Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), and Vitesse_derive_Forces::evaluate_C0_vg0().