CEA TRUST Platform: Pb_Hydraulique Class Reference
Pb_Hydraulique Class Reference
#include <Pb_Hydraulique.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
const Equation_base & equation (int) const override
Equation_base & equation (int) override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
virtual void finir ()
double futureTime () const override
void getInputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual void mettre_a_jour (double temps)
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual bool run ()
virtual bool runUntil (double time)
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
on resout les equations de Navier Stokes en regime laminaire
pour un fluide incompressible
La formulation est de type vitesse pression
See also
Navier_Stokes_std Pb_Fluide_base Fluide_base
Member Function Documentation
nombre_d_equations()
int Pb_Hydraulique::nombre_d_equations () const inline override virtual
Implements Probleme_base.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_Concentration_Gen< Pb_Hydraulique, Convection_Diffusion_Concentration, Constituant >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique, Convection_Diffusion_Concentration, Constituant >, Pb_Thermohydraulique, and Pb_Thermohydraulique_Concentration.
equation() [1/2]
const Equation_base & Pb_Hydraulique::equation (int i) const override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0, sort (exit) sinon.
(version const)
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation d'hydraulique de type Navier_Stokes_std
Implements Probleme_base.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_Concentration_Gen< Pb_Hydraulique, Convection_Diffusion_Concentration, Constituant >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique, Convection_Diffusion_Concentration, Constituant >, Pb_Thermohydraulique, and Pb_Thermohydraulique_Concentration.
References eq_hydraulique, and Process::exit().
equation() [2/2]
Equation_base & Pb_Hydraulique::equation (int i) override virtual
Renvoie l'equation d'hydraulique de type Navier_Stokes_std si i=0, sort (exit) sinon.
Parameters
(int i) l'index de l'equation a renvoyer
Returns
(Equation_base&) l'equation d'hydraulique de type Navier_Stokes_std
Implements Probleme_base.
Reimplemented in TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >, TRUSTProblem_Concentration_Gen< Pb_Hydraulique, Convection_Diffusion_Concentration, Constituant >, TRUSTProblem_Concentration_Gen< Pb_Thermohydraulique, Convection_Diffusion_Concentration, Constituant >, Pb_Thermohydraulique, and Pb_Thermohydraulique_Concentration.
References eq_hydraulique, and Process::exit().
associer_milieu_base()
void Pb_Hydraulique::associer_milieu_base (const Milieu_base & mil) override virtual
Associe le milieu au probleme.
Le milieu doit etre de type fluide incompressible.
Parameters
(Milieu_base& mil) le milieu physique a associer au probleme
Exceptions
le milieu n'est pas du type Fluide_base
Reimplemented from Probleme_base.
Reimplemented in Pb_Thermohydraulique, Pb_Thermohydraulique_Concentration, TRUSTProblem_sup_eqns< Pb_Thermohydraulique >, and TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Concentration >.
References Navier_Stokes_std::associer_milieu_base(), eq_hydraulique, Process::exit(), and Objet_U::que_suis_je().
Referenced by Pb_Thermohydraulique::associer_milieu_base().
Member Data Documentation
eq_hydraulique
Navier_Stokes_std Pb_Hydraulique::eq_hydraulique protected
Referenced by associer_milieu_base(), equation(), Pb_Thermohydraulique::equation(), equation(), Pb_Thermohydraulique::equation(), Pb_Thermohydraulique::verifier(), and Pb_Thermohydraulique_Concentration::verifier().