CEA TRUST Platform: Chimie Class Reference
Chimie Class Reference
#include <Chimie.h>
Public Member Functions
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
completer()
void Chimie::completer (const Probleme_base & pb) virtual
References alias, Probleme_base::equation(), espece_en_competition_micro_melange_, Process::exit(), Convection_Diffusion_Concentration::inconnue(), Field_base::le_nom(), LIST(), liste_ai_, liste_C_, marqueur_espece_en_competition_micro_melange_, Convection_Diffusion_Concentration::masse_molaire(), nb_grains_, Probleme_base::nombre_d_equations(), OBS_PTR(), Puissance_volumique_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
preparer_calcul()
int Chimie::preparer_calcul () virtual
mettre_a_jour()
void Chimie::mettre_a_jour (double temps)
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Reaction::beta_, Reaction::c_r_Ea_, Reaction::calcul_proportion_implicite(), Reaction::coeff_activite_, Reaction::coeff_stoechio_, Reaction::coeff_Y_, constante_modele_micro_melange_, Reaction::constante_taux_reaction_, Reaction::contre_reaction_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Reaction::Ea_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Domaine_VF::face_voisins(), liste_C_, marqueur_espece_en_competition_micro_melange_, modele_micro_melange_, Reaction::nb_sous_pas_de_temps_reaction(), Reaction::reagir(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Domaine_VF::volumes().
calculer_pas_de_temps()
double Chimie::calculer_pas_de_temps () const
discretiser()
void Chimie::discretiser (const Probleme_base & pb)
get_champ()
const Champ_base & Chimie::get_champ (const Motcle & nom) const virtual
References Nom::getString().
has_champ() [1/2]
virtual bool Chimie::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const virtual
References OBS_PTR().
has_champ() [2/2]
bool Chimie::has_champ (const Motcle & nom) const virtual
get_noms_champs_postraitables()
void Chimie::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const virtual
sauvegarder()
int Chimie::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
reprendre()
int Chimie::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
LIST()
Chimie::LIST (Reaction) protected
Referenced by completer().
OBS_PTR()
Chimie::OBS_PTR (Probleme_base) protected
Referenced by completer(), and has_champ().
VECT()
Chimie::VECT (OBS_PTR(Champ_Inc_base)) protected
Member Data Documentation
alias
Motcles Chimie::alias protected
Referenced by completer().
liste_ai_
Chimie::liste_ai_ protected
Referenced by completer().
liste_nd10_
Chimie::liste_nd10_ protected
liste_ngrains_
Chimie::liste_ngrains_ protected
liste_C_
Chimie::liste_C_ protected
Referenced by completer(), and mettre_a_jour().
nb_grains_
int Chimie::nb_grains_ = -10 protected
Referenced by completer().
Puissance_volumique_
DoubleTab Chimie::Puissance_volumique_ protected
Referenced by completer().
modele_micro_melange_
int Chimie::modele_micro_melange_ = 0 protected
Referenced by mettre_a_jour().
constante_modele_micro_melange_
double Chimie::constante_modele_micro_melange_ =-1.0 protected
Referenced by mettre_a_jour().
espece_en_competition_micro_melange_
Motcle Chimie::espece_en_competition_micro_melange_ protected
Referenced by completer().
marqueur_espece_en_competition_micro_melange_
int Chimie::marqueur_espece_en_competition_micro_melange_ = -1 protected
Referenced by completer(), and mettre_a_jour().