CEA TRUST Platform: Faces_32_64< _SIZE_ > Class Template Reference
Faces_32_64< _SIZE_ > Class Template Reference
#include <Faces.h>
Public Member Functions
void ajouter (const IntTab_t &)
void calculer_centres_gravite (DoubleTab_t &xv) const
void calculer_surfaces (DoubleVect_t &surf) const
IntVect_t & compare (const Faces_32_64 &other_fac, IntVect_t &renum)
void completer (int_t face, int_t num_elem)
int_t dimensionner (int_t)
Sortie & ecrit (Sortie &) const
void initialiser_faces_joint (int_t nb_faces_joints)
void initialiser_sommets_faces_joint (int_t nb_faces_joints)
Entree & lit (Entree &)
void reordonner ()
int_t & sommet (int_t, int)
int_t sommet (int_t, int) const
Type_Face type (const Motcle &) const
Motcle & type (const Type_Face &) const
void typer (const Motcle &)
void typer (const Type_Face &)
int_t & voisin (int_t, int)
int_t voisin (int_t, int) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Faces_32_64< _SIZE_ >
See also
IntTab Frontiere
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Faces_32_64< _SIZE_ >::int_t = _SIZE_
IntVect_t
template<typename _SIZE_ > using Faces_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Faces_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Faces_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Faces_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Faces_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Faces_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
DomaineAxi1d_t
template<typename _SIZE_ > using Faces_32_64< _SIZE_ >::DomaineAxi1d_t = DomaineAxi1d_32_64<_SIZE_>
Member Function Documentation
type_face()
template<typename _SIZE_ > Type_Face Faces_32_64< _SIZE_ >::type_face () const inline
nb_faces()
template<typename _SIZE_ > int_t Faces_32_64< _SIZE_ >::nb_faces () const inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
Referenced by Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Champ_base::calculer_valeurs_som_post(), Faces_32_64< _SIZE_ >::compare(), Extruder_en3::construire_bord_lateral(), Domaine_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Domaine_32_64< _SIZE_ >::face_bords_interne_conjuguee(), Domaine_VF::infobord(), Domaine_VF::renumeroter(), and Domaine_VDF::reordonner().
nb_faces_tot()
template<typename _SIZE_ > int_t Faces_32_64< _SIZE_ >::nb_faces_tot () const inline
Renvoie le nombre total de Faces i (reelles et virt) sur le proc courant.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot().
Referenced by Faces_VDF::calculer_orientation(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), and Remove_Invalid_Internal_Boundaries::interpreter_().
nb_som_faces()
template<typename _SIZE_ > int Faces_32_64< _SIZE_ >::nb_som_faces () const inline
Renvoie le nombre de sommet par face.
Referenced by Faces_VDF::calculer_orientation(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Remove_Invalid_Internal_Boundaries::interpreter_(), and Champ_front_MED::remplir_tab().
sommet() [1/2]
template<typename _SIZE_ > Faces_32_64< _SIZE_ >::int_t Faces_32_64< _SIZE_ >::sommet (int_t i, int j) const inline
Renvoie le numero du j-ieme sommet de la i-ieme face.
Parameters
(int i) indice de la face du sommet a renvoyer
(int j) indice du sommet a renvoyer
Returns
(int) le numero du j-ieme sommet de la i-ieme face
Referenced by Faces_VDF::calculer_orientation(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Extruder_en3::construire_bord_lateral(), Extruder::extruder(), Extruder_en20::extruder(), Ch_front_Vortex::initialiser(), Champ_front_fonc_pois_ipsn::initialiser(), Champ_front_fonc_pois_tube::initialiser(), Remove_Invalid_Internal_Boundaries::interpreter_(), and Champ_front_MED::remplir_tab().
sommet() [2/2]
template<typename _SIZE_ > Faces_32_64< _SIZE_ >::int_t & Faces_32_64< _SIZE_ >::sommet (int_t i, int j) inline
Renvoie une reference sur le numero du j-ieme sommet de la i-ieme face.
Parameters
(int i) indice de la face du sommet a renvoyer
(int j) indice du sommet a renvoyer
Returns
(int&) reference sur le numero du j-ieme sommet de la i-ieme face
les_sommets() [1/2]
template<typename _SIZE_ > const IntTab_t & Faces_32_64< _SIZE_ >::les_sommets () const inline
Renvoie le tableau des sommets de toutes les faces.
Referenced by Refine_Mesh::build_new_frontier_faces_2D(), Refine_Mesh::build_new_frontier_faces_3D(), Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), Remove_elem::creer_faces(), Faces_builder::creer_faces_reeles(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), Decouper_Bord_coincident::decouper_(), Domaine_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extraire_domaine::interpreter_(), Remove_elem::recreer_faces(), Domaine_VF::renumeroter(), Domaine_VDF::reordonner(), Trianguler_fin::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_connector_faces(), and Refine_Mesh::update_internal_frontier_faces().
les_sommets() [2/2]
template<typename _SIZE_ > IntTab_t & Faces_32_64< _SIZE_ >::les_sommets () inline
type() [1/2]
template<typename _SIZE_ > Type_Face Faces_32_64< _SIZE_ >::type (const Motcle & mot) const
Renvoie un objet de Type_Face representant le type de nom specifie.
Les noms de types reconnus sont: "vide_0D" "point_1D" "point_1D_axi" "segment_2D" "triangle_3D" "quadrangle_3D" "segment_2D_axi" "quadrangle_3D_axi" "quadrilatere_2D_axi"
Parameters
(Motcle& mot) le mot clef representant un type de face
Returns
(Type_Face) le type de face correspondant au parametre mo
Exceptions
type de face non reconnu
References Process::me(), and Motcles::search().
type() [2/2]
template<typename _SIZE_ > Motcle & Faces_32_64< _SIZE_ >::type (const Type_Face & typ) const
Renvoie le nom associe a un type de face.
(inverse de Type_Face Faces_32_64<SIZE>type(const Motcle&) const)
Parameters
(Type_Face& typ) un type de face
Returns
(Motcle&) le nom correspondant au type speficie en parametre
Exceptions
type de face non reconnu
ajouter()
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::ajouter (const IntTab_t & tab_sommet)
Ajoute des faces.
Ajouter des faces revient a ajouter des sommets.
Parameters
(IntTab& sommet) le tableau des sommets a ajouter
Exceptions
les sommets specifies n'ont pas la bonne dimension (1D,2D,3D)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
typer() [1/2]
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::typer (const Motcle & typ)
Type les faces.
Parameters
(Motcle& typ) le type a donner aux faces
Referenced by Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), Decouper_Bord_coincident::decouper_(), Domaine_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extruder::extruder_hexa(), Distanceparoi::interpreter_(), Remove_elem::remove_elem_(), Tetraedriser::trianguler(), Tetraedriser_homogene::trianguler(), Tetraedriser_homogene_compact::trianguler(), Tetraedriser_homogene_fin::trianguler(), Tetraedriser_par_prisme::trianguler(), Trianguler_fin::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_connector_faces(), and Refine_Mesh::update_internal_frontier_faces().
typer() [2/2]
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::typer (const Type_Face & typ)
Type les faces.
Parameters
(Type_Face& typ) le type a donner aux faces
Exceptions
type de face inconnu
dimensionner()
template<typename _SIZE_ > Faces_32_64< _SIZE_ >::int_t Faces_32_64< _SIZE_ >::dimensionner (int_t i)
(Re-)dimensionne les faces On redimensionne les voisins en consequence.
Les sommets implicitement ajoutes sont initialises a -1.
Parameters
(int i) le nouveau nombre de face
Returns
(int) le nouveau nombre de face
Referenced by Remove_elem::creer_faces().
voisin() [1/2]
template<typename _SIZE_ > Faces_32_64< _SIZE_ >::int_t Faces_32_64< _SIZE_ >::voisin (int_t face, int i) const inline
Renvoie le numero du i-ieme voisin de face.
Parameters
(int face) le numero de la face dont on cherche un voisin
(int i) l'indice du voisin a renvoyer
Returns
(int) le numero i-ieme voisin de face
Referenced by Extruder::extruder(), Extruder_en20::extruder(), Domaine_EF::reordonner(), Domaine_Poly_base::reordonner(), Domaine_VEF::reordonner(), and Raccord_distant_homogene_32_64< _SIZE_ >::trace_elem_distant().
voisin() [2/2]
template<typename _SIZE_ > Faces_32_64< _SIZE_ >::int_t & Faces_32_64< _SIZE_ >::voisin (int_t face, int i) inline
Renvoie une reference le numero du i-ieme voisin de face.
Parameters
(int face) le numero de la face dont on cherche un voisin
(int i) l'indice du voisin a renvoyer
Returns
(int&) reference sur le numero du i-ieme voisin de face
voisins() [1/2]
template<typename _SIZE_ > IntTab_t & Faces_32_64< _SIZE_ >::voisins () inline
Renvoie le tableau des voisins (des faces).
Referenced by Extruder_en3::construire_bord_lateral(), Extruder_en3::construire_bords(), Faces_builder::creer_faces_reeles(), Tetraedriser_homogene_compact::decoupe(), Tetraedriser_homogene_fin::decoupe(), Decouper_Bord_coincident::decouper_(), Domaine_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder_dvt(), Extruder_en20::extruder_dvt(), Extruder::extruder_dvt_hexa(), Extraire_domaine::interpreter_(), Domaine_VF::renumeroter(), Domaine_VDF::reordonner(), Trianguler_fin::trianguler(), Refine_Mesh::update_boundary_faces(), Refine_Mesh::update_connector_faces(), and Refine_Mesh::update_internal_frontier_faces().
voisins() [2/2]
template<typename _SIZE_ > const IntTab_t & Faces_32_64< _SIZE_ >::voisins () const inline
completer()
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::completer (int_t face, int_t num_elem)
Complete la face specifie: met a jour ses voisins.
Parameters
(int face) l'indice de la face a completer
(int num_elem) le numero de l'element voisin de la face
Exceptions
face deja complete
associer_domaine()
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::associer_domaine (const Domaine_t & z) inline
Referenced by Domaine_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), Domaine_VF::infobord(), and Distanceparoi::interpreter_().
domaine()
template<typename _SIZE_ > const Domaine_t & Faces_32_64< _SIZE_ >::domaine () const inline
Referenced by Faces_VDF::calculer_orientation(), and Faces_32_64< _SIZE_ >::compare().
calculer_surfaces()
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::calculer_surfaces (DoubleVect_t & surfaces) const
Calcule la surface des faces.
Parameters
(DoubleVect& surfaces) le vecteur contenant la surface de chacune des faces.
Exceptions
type de face non reconnu
calcul de la surface de ce type de face non code
calcul de surface errone (surface <= 0)
type de face ne correspondant pas a la dimension d'espace
References Domaine_32_64< _SIZE_ >::coord(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), Domaine_32_64< _SIZE_ >::les_sommets(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by Champ_front_recyclage::calcul_moyenne_recyclee(), Domaine_VF::discretiser(), Domaine_VF::infobord(), and Champ_front_synt::mettre_a_jour().
calculer_centres_gravite()
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::calculer_centres_gravite (DoubleTab_t & xv) const
Calcule les centres de gravite de chaque face.
Parameters
(DoubleTab& xv) tableau contenant les coordonnees des centres de gravite de chaque face. xv(i,j) contient la coordonnee j du centre de gravite de la i-ieme face. On resize le tableau xv et on lui affecte le descripteur parallele du tableau des sommets avant de le remplir.
References Faces_32_64< _SIZE_ >::Calculer_centres_gravite(), and Domaine_32_64< _SIZE_ >::coord_sommets().
Referenced by Domaine_VF::discretiser(), Distanceparoi::interpreter_(), and Champ_front_synt::mettre_a_jour().
reordonner()
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::reordonner ()
Reordonne les faces.
(on ne reordonne que les quadrangles)
Exceptions
type de face non reconnu
References Domaine_32_64< _SIZE_ >::coord(), Domaine_32_64< _SIZE_ >::les_sommets(), Vecteur3::produit_scalaire(), and Vecteur3::produit_vectoriel().
compare()
template<typename _SIZE_ > Faces_32_64< _SIZE_ >::IntVect_t & Faces_32_64< _SIZE_ >::compare (const Faces_32_64< _SIZE_ > & faces, IntVect_t & renum)
Compare l'objet Faces_32_64 passe en parametre avec l'objet Faces_32_64 lui-meme (this)
Parameters
(Faces_32_64& faces) les faces avec lesquel on compare l'objet
(IntVect& renum) le vecteur renumerotation - renum est de taille 1 et renum contient -1 si il n'y pas le meme nombre de face dans l'objet que dans le parametre faces. - renum autant d'elements que de nombre de face sinon. et renum(i) = le rang de la face i du parametre faces dans l'objet courant
Returns
(IntVect&)
References Faces_32_64< _SIZE_ >::domaine(), Faces_32_64< _SIZE_ >::nb_faces(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and TRUSTList_Curseur< _TYPE_ >::valeur().
initialiser_faces_joint()
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::initialiser_faces_joint (int_t nb_faces_joint)
Initialise les voisins des faces joints a -1.
Parameters
(int nb_faces_joint) le nombre de faces representant des Joints
initialiser_sommets_faces_joint()
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::initialiser_sommets_faces_joint (int_t nb_faces_joint)
Initialise les sommets des faces joints a -1.
Parameters
(int nb_faces_joint) le nombre de faces representant des Joints
lit()
template<typename _SIZE_ > Entree & Faces_32_64< _SIZE_ >::lit (Entree & s)
Lit les specifications d'un objet face a partir d'un flot d'entree.
On lit:
le type des faces
les sommets
les voisins Et on reordonne les sommets. Ne fait rien si le type lu est "vide_0D"
Parameters
(Entree& s) un flot d'entree
Returns
(Entree&) le flot d'entree modifie
ecrit()
template<typename _SIZE_ > Sortie & Faces_32_64< _SIZE_ >::ecrit (Sortie & s) const
Ecrit les faces sur un flots de sortie.
On ecrit:
le type des faces
les sommets
les voisins On ecrit juste le type Type_Face::vide_0D, si le nombre de faces est nul.
Parameters
(Sortie& s) un flot de sortie
Returns
(Sortie&) le flot de sortie modifie
Calculer_centres_gravite()
template<typename _SIZE_ > void Faces_32_64< _SIZE_ >::Calculer_centres_gravite (DoubleTab_t & xv, Type_Face type_face_, const DoubleTab_t & coord, const IntTab_t & sommet) static
References Objet_U::axi, TRUSTTab< _TYPE_, _SIZE_ >::dimension_int(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector().
Referenced by Faces_32_64< _SIZE_ >::calculer_centres_gravite().