CEA TRUST Platform: Champ_Generique_Correlation Class Reference
Champ_Generique_Correlation Class Reference
#include <Champ_Generique_Correlation.h>
Public Member Functions
const Noms get_property (const Motcle &query) const override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
Entity get_localisation (const int index=-1) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Generique_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Champ destine a post-traiter une correlation d un champ generique La classe porte un operateur statistique "Op_Correlation"
Member Function Documentation
get_property()
const Noms Champ_Generique_Correlation::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Gen_de_Champs_Gen::get_property(), integrale(), Integrale_tps_Champ::le_champ_calcule(), Field_base::noms_compo(), Motcles::search(), and Field_base::unites().
Referenced by completer(), and get_info_type_post().
temps()
double Champ_Generique_Correlation::temps () const inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Correlation::integrale(), Integrale_tps_Champ::le_champ_calcule(), Op_Correlation_, and Champ_base::temps().
Referenced by get_champ().
integrale()
const Integrale_tps_Champ & Champ_Generique_Correlation::integrale () const inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Correlation::integrale(), and Op_Correlation_.
Referenced by Postraitement::creer_champ_post_stat(), get_champ(), get_champ_without_evaluation(), get_directive_pour_discr(), and get_property().
Operateur_Statistique() [1/2]
const Operateur_Statistique_tps_base & Champ_Generique_Correlation::Operateur_Statistique () const inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Correlation_.
Operateur_Statistique() [2/2]
Operateur_Statistique_tps_base & Champ_Generique_Correlation::Operateur_Statistique () inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Correlation_.
completer()
void Champ_Generique_Correlation::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Op_Correlation::associer(), Op_Correlation::associer_op_stat(), Champ_Gen_de_Champs_Gen::completer(), Op_Correlation::completer(), Postraitement::comprend_champ_post(), Process::exit(), Postraitement::get_champ_post(), Champ_Generique_base::get_property(), get_property(), Champ_Gen_de_Champs_Gen::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), Champ_Gen_de_Champs_Gen::get_source(), Probleme_U::le_nom(), Postraitement_base::le_nom(), Op_Correlation_, Champ_Gen_de_Champs_Gen::parent_name_, Champ_Generique_Statistiques_base::tstat_deb_, Champ_Generique_Statistiques_base::tstat_fin_, and Champ_Generique_Statistiques_base::use_source_name_only_.
get_directive_pour_discr()
const Motcle Champ_Generique_Correlation::get_directive_pour_discr () const override virtual
Renvoie la directive (champ_elem, champ_sommets, champ_face ou pression) pour lancer la discretisation de l espace de stockage rendu par get_champ()
Reimplemented from Champ_Gen_de_Champs_Gen.
References integrale(), Op_Moyenne::integrale(), Op_Correlation::la_moyenne_a(), and Op_Correlation_.
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Correlation::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const override virtual
Implements Champ_Generique_base.
References integrale(), Integrale_tps_Champ::le_champ_calcule(), Champ_Gen_de_Champs_Gen::nb_comp, and Field_base::nb_comp().
get_champ()
const Champ_base & Champ_Generique_Correlation::get_champ (OWN_PTR(Champ_base)& espace_stockage) const override
References Op_Correlation::calculer_valeurs(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), integrale(), Integrale_tps_Champ::le_champ_calcule(), Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), Op_Correlation_, and temps().
nommer_source()
void Champ_Generique_Correlation::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
get_info_type_post()
int Champ_Generique_Correlation::get_info_type_post () const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References get_property().
Member Data Documentation
Op_Correlation_
Op_Correlation Champ_Generique_Correlation::Op_Correlation_ protected
Referenced by completer(), get_champ(), get_directive_pour_discr(), integrale(), Operateur_Statistique(), Operateur_Statistique(), and temps().