CEA TRUST Platform: Pb_Couple_Optimisation_IBM Class Reference
Pb_Couple_Optimisation_IBM Class Reference
Public Member Functions
int associer_ (Objet_U &) override
void initialize () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_Couple
void ajouter (Probleme_base &)
virtual void associer_sch_tps_base (Schema_Temps_base &)
double computeTimeStep (bool &stop) const override
virtual void discretiser (Discretisation_base &)
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
virtual Schema_Temps_base & schema_temps ()
virtual const Schema_Temps_base & schema_temps () const
bool updateGivenFields () override
Public Member Functions inherited from Couplage_U
void abortTimeStep () override
double futureTime () const override
void getInputFieldsNames (Noms &noms) const override
bool isStationary () const override
int postraiter (int force=1) override
double presentTime () const override
void resetTime (double t) override
void terminate () override
Public Member Functions inherited from Probleme_U
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual bool run ()
virtual bool runUntil (double time)
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_()
int Pb_Couple_Optimisation_IBM::associer_ (Objet_U & ob) override virtual
Surcharge Objet_U::associer_(Objet_U&) Associe un objet au probleme couple, en verifiant le type.
dynamiquement. L'objet peut-etre:
un schema en temps (Schema_Temps_base), et on l'associe aux problemes
un probleme (Probleme_base), on l'ajoute a la liste
Parameters
(Objet_U& ob) l'objet a associer
Returns
(int) 1 si l'association a reussie 0 sinon
Exceptions
l'objet n'est pas d'un type attendu
Reimplemented from Probleme_Couple.
References Probleme_Couple::associer_().
validateTimeStep()
void Pb_Couple_Optimisation_IBM::validateTimeStep () override virtual
Validates the calculated unknown by moving the present time at the end of the time step.
This method is allowed to free past values of the unknown and given fields.
Exceptions
WrongContext
Reimplemented from Couplage_U.
References Couplage_U::validateTimeStep().
initialize()
void Pb_Couple_Optimisation_IBM::initialize () override virtual
This method is called once at the beginning, before any other one of the interface Problem.
Exceptions
WrongContext
Reimplemented from Probleme_Couple.
References Probleme_Couple::initialize().
le_modele_interpolation_IBM()
void Pb_Couple_Optimisation_IBM::le_modele_interpolation_IBM (const Interpolation_IBM_base & un_modele_d_interpolation)
my_interpolation_IBM()
Interpolation_IBM_base& Pb_Couple_Optimisation_IBM::my_interpolation_IBM () inline
OBS_PTR()
Pb_Couple_Optimisation_IBM::OBS_PTR (Interpolation_IBM_base) protected