CEA TRUST Platform: Modele_turbulence_hyd_null Class Reference
Modele_turbulence_hyd_null Class Reference
Public Member Functions
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
mettre_a_jour()
void Modele_turbulence_hyd_null::mettre_a_jour (double) inline override virtual
Implements Modele_turbulence_hyd_base.
sauvegarder()
int Modele_turbulence_hyd_null::sauvegarder (Sortie & os) const override virtual
Sauvegarde le modele de turbulence sur un flot de sortie.
Sauvegarde le type de l'objet.
Parameters
(Sortie& os) un flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Modele_turbulence_hyd_base.
References Probleme_base::domaine(), Modele_turbulence_hyd_base::equation(), Sortie::flush(), EcritureLectureSpecial::is_ecriture_special(), Domaine_base::le_nom(), Equation_base::probleme(), Objet_U::que_suis_je(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().