CEA TRUST Platform: EDO_Pression_th_VDF_Gaz_Parfait Class Reference
EDO_Pression_th_VDF_Gaz_Parfait Class Reference
#include <EDO_Pression_th_VDF_Gaz_Parfait.h>
Public Member Functions
double resoudre (double) override
Public Member Functions inherited from EDO_Pression_th_VDF
double masse_totale (double P, const DoubleTab &T) override
Detailed Description
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VDF et pour les gaz parfaits.
See also
Fluide_Quasi_Compressible EDO_Pression_th_base
Member Function Documentation
resoudre() [1/2]
double EDO_Pression_th_VDF_Gaz_Parfait::resoudre (double Pth_n) override
Resoud l'EDO.
Parameters
(double Pth_n) La pression a l'etape precedente
Returns
(double) La nouvelle valeur de la pression
References EDO_Pression_th_VDF::calculer_grad(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), Loi_Etat_GP_base::R(), Dirichlet::val_imp(), and Navier_Stokes_std::vitesse().
resoudre() [2/2]
void EDO_Pression_th_VDF_Gaz_Parfait::resoudre (DoubleTab & Pth_n) override
References Process::exit(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), and Dirichlet::val_imp().