CEA TRUST Platform: Elem_geom_base_32_64< _SIZE_ > Class Template Reference
Elem_geom_base_32_64< _SIZE_ > Class Template Reference abstract
Public Member Functions
virtual void calculer_centres_gravite (DoubleTab_t &) const
virtual void calculer_normales (const IntTab_t &faces_sommets, DoubleTab_t &face_normales) const
void creer_faces_elem (Faces_t &, int_t) const
virtual void creer_faces_elem (Faces_t &, int_t, Type_Face) const
virtual void get_tab_aretes_sommets_locaux (IntTab &aretes_som_local) const
virtual int get_tab_faces_sommets_locaux (IntTab &faces_som_local) const
virtual int nb_type_face () const
virtual int num_face (int face, Type_Face &type) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Elem_geom_base_32_64< _SIZE_ >
geometriques constituant un maillage (i.e. un Domaine geometrique) Un element geometrique a un Domaine associe auquel il fournit les routines de base pour la manipulation des ses elements. (Un domaine n'a qu'un seul type d'element geometrique)
See also
Hexaedre Prisme Rectangle Segment Tetraedre Triangle, Domaine, Classe abstraite, Methodes abstraites:, int face_sommet(int i, int j) const, int nb_som() const, int nb_faces(int=0) const, int nb_som_face(int=0) const, int est_structure() const, const Nom& nom_lml() const, int contient(const ArrOfDouble&, int) const, int contient(const ArrOfInt&, int) const, Type_Face type_face(int=0) const, void calculer_volumes(DoubleVect&) const, void calculer_normales(const IntTab& , DoubleTab&) const
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntVect_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
SmallArrOfTID_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::SmallArrOfTID_t = SmallArrOfTID_T<_SIZE_>
ArrOfDouble_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::ArrOfDouble_t = ArrOfDouble_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Faces_t
template<typename _SIZE_ > using Elem_geom_base_32_64< _SIZE_ >::Faces_t = Faces_32_64<_SIZE_>
Member Function Documentation
creer_faces_elem() [1/2]
template<typename _SIZE_ > void Elem_geom_base_32_64< _SIZE_ >::creer_faces_elem (Faces_t & les_faces, int_t num_elem, Type_Face type) const virtual
Cree les faces de l'element geometrique specifie du domaine en precisant le type de face a creer.
Parameters
(Faces_t& les_faces) les faces a creer
(int num_elem) le numero de l'element dont on veut creer les faces
(Type_Face type) le type de face a creer
References Faces_32_64< _SIZE_ >::associer_domaine(), Faces_32_64< _SIZE_ >::completer(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Faces_32_64< _SIZE_ >::dimensionner(), and Faces_32_64< _SIZE_ >::sommet().
creer_faces_elem() [2/2]
template<typename _SIZE_ > void Elem_geom_base_32_64< _SIZE_ >::creer_faces_elem (Faces_t & faces, int_t elem) const inline
Cree les faces de l'element du domaine specifie.
Parameters
(Faces_t& faces) les faces de l'elements a creer
(int elem) le numero de element du domaine dont veut creer les faces
face_sommet()
template<typename _SIZE_ > virtual int Elem_geom_base_32_64< _SIZE_ >::face_sommet (int i, int j) const pure virtual
Renvoie le numero du j-ieme sommet de la i-ieme face de l'element.
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
associer_domaine()
template<typename _SIZE_ > void Elem_geom_base_32_64< _SIZE_ >::associer_domaine (const Domaine_32_64< int_t > & dom) inline
nb_som()
template<typename _SIZE_ > virtual int Elem_geom_base_32_64< _SIZE_ >::nb_som () const pure virtual
Nb of vertices for the element.
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
nb_faces()
template<typename _SIZE_ > virtual int Elem_geom_base_32_64< _SIZE_ >::nb_faces (int = 0) const pure virtual
Nb of faces for the element.
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
nb_som_face()
template<typename _SIZE_ > virtual int Elem_geom_base_32_64< _SIZE_ >::nb_som_face (int = 0) const pure virtual
Nb of vertices for one face of the element.
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
est_structure()
template<typename _SIZE_ > virtual bool Elem_geom_base_32_64< _SIZE_ >::est_structure () const pure virtual
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Poly_geom_base_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
nom_lml()
template<typename _SIZE_ > virtual const Nom& Elem_geom_base_32_64< _SIZE_ >::nom_lml () const pure virtual
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_axi_32_64< _SIZE_ >, Rectangle_2D_axi_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, Hexaedre_axi_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
contient() [1/2]
template<typename _SIZE_ > virtual int Elem_geom_base_32_64< _SIZE_ >::contient (const ArrOfDouble & pos, int_t elem) const pure virtual
DOes the element 'elem' contains the point 'pos'.
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_axi_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, Hexaedre_axi_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
contient() [2/2]
template<typename _SIZE_ > virtual int Elem_geom_base_32_64< _SIZE_ >::contient (const SmallArrOfTID_t & soms, int_t elem) const pure virtual
Renvoie 1 si les sommets specifies par le parametre "pos" sont les sommets de l'element "element" du domaine associe.
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_axi_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, Hexaedre_axi_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
nb_type_face()
template<typename _SIZE_ > int Elem_geom_base_32_64< _SIZE_ >::nb_type_face virtual
Nb of face types of the elemnt (for example 2 for a prism)
Renvoie le nombre de type de face de l'element geometrique.
Par exemple un prisme (Classe Prisme) a 2 types de faces: un triangle ou un quadrangle.
Returns
(int) renvoie toujours 1
Reimplemented in Prisme_32_64< _SIZE_ >, and Poly_geom_base_32_64< _SIZE_ >.
num_face()
template<typename _SIZE_ > int Elem_geom_base_32_64< _SIZE_ >::num_face (int face, Type_Face & type) const virtual
Renvoie le parametre face si le type de face specifie est le meme que celui de l'element geometrique.
Parameters
(int face)
(Type_Face& type) un type de face
Exceptions
mauvais type de face specifie
type_face()
template<typename _SIZE_ > virtual Type_Face Elem_geom_base_32_64< _SIZE_ >::type_face (int face_typ = 0) const pure virtual
Type of the face of the element - face_typ < nb_type_face()
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_axi_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_axi_32_64< _SIZE_ >, Rectangle_2D_axi_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, Hexaedre_axi_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
calculer_centres_gravite()
template<typename _SIZE_ > void Elem_geom_base_32_64< _SIZE_ >::calculer_centres_gravite (DoubleTab_t & tab_xp) const virtual
Compute all centers of mass of all elements in the domain.
Calcule les centres de gravites de tous les elements du domaine associe a l'element goemetrique.
Parameters
(DoubleTab& xp) le tableau contenant les coordonnees des centres de gravite
Reimplemented in Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Hexaedre_axi_32_64< _SIZE_ >, Rectangle_axi_32_64< _SIZE_ >, and Rectangle_2D_axi_32_64< _SIZE_ >.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Rectangle_2D_axi_32_64< _SIZE_ >::calculer_centres_gravite(), and Debog_Pb::read_geometry_data().
reordonner()
template<typename _SIZE_ > virtual void Elem_geom_base_32_64< _SIZE_ >::reordonner () inline virtual
Reimplemented in Segment_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
calculer_volumes()
template<typename _SIZE_ > virtual void Elem_geom_base_32_64< _SIZE_ >::calculer_volumes (DoubleVect_t & vols) const pure virtual
Compute vols of all elements in the domain.
Implemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_axi_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, Hexaedre_axi_32_64< _SIZE_ >, Hexaedre_32_64< _SIZE_ >, Segment_axi_32_64< _SIZE_ >, and Rectangle_2D_axi_32_64< _SIZE_ >.
calculer_normales()
template<typename _SIZE_ > void Elem_geom_base_32_64< _SIZE_ >::calculer_normales (const IntTab_t & faces_sommets, DoubleTab_t & face_normales) const virtual
Sort en erreur.
Cette methode n'est pas virtuelle pure pour des raisons de commodite
Parameters
(DoubleTab& xp) le tableau contenant les coordonnees des centres de gravite
Reimplemented in Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
get_tab_faces_sommets_locaux()
template<typename _SIZE_ > int Elem_geom_base_32_64< _SIZE_ >::get_tab_faces_sommets_locaux (IntTab & faces_som_local) const virtual
remplit le tableau faces_som_local(i,j) qui donne pour 0 <= i < nb_faces() et 0 <= j < nb_som_face(i) le numero local du sommet
sur l'element. On a 0 <= faces_sommets_locaux(i,j) < nb_som() Si toutes les faces de l'element n'ont pas le meme nombre de sommets, le nombre de colonnes du tableau est le plus grand nombre de sommets, et les cases inutilisees du tableau sont mises a -1 On renvoie 1 si toutes les faces ont le meme nombre d'elements, 0 sinon.
Reimplemented in Poly_geom_base_32_64< _SIZE_ >, Triangle_32_64< _SIZE_ >, Tetraedre_32_64< _SIZE_ >, Segment_32_64< _SIZE_ >, Rectangle_32_64< _SIZE_ >, Quadrangle_VEF_32_64< _SIZE_ >, Prisme_32_64< _SIZE_ >, Polygone_32_64< _SIZE_ >, Polyedre_32_64< _SIZE_ >, Point_32_64< _SIZE_ >, Hexaedre_VEF_32_64< _SIZE_ >, and Hexaedre_32_64< _SIZE_ >.
Referenced by Domain_Graph::construire_graph_elem_elem().
get_tab_aretes_sommets_locaux()
template<typename _SIZE_ > void Elem_geom_base_32_64< _SIZE_ >::get_tab_aretes_sommets_locaux (IntTab & aretes_som_local) const virtual
idem que Elem_geom_base::get_tab_faces_sommets_locaux mais pour les aretes: aretes_som_local.
dimension(0) = nombre d'aretes sur l'element de reference aretes_som_local.dimension(1) = 2 (nombre de sommets par arete) aretes_som_local(i,j) = numero d'un sommet de l'element (0 <= n < nb_sommets_par_element)
Reimplemented in Tetraedre_32_64< _SIZE_ >.
OBS_PTR()
template<typename _SIZE_ > Elem_geom_base_32_64< _SIZE_ >::OBS_PTR (Domaine_t) protected