CEA TRUST Platform: Domaine_PolyMAC_P0P1NC Class Reference
Domaine_PolyMAC_P0P1NC Class Reference
Additional Inherited Members
Public Member Functions inherited from Domaine_Poly_base
void reordonner (Faces &) override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
const Frontiere_dis_base & frontiere_dis (const Nom &) const
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
discretiser()
void Domaine_PolyMAC_P0P1NC::discretiser () override virtual
Reimplemented from Domaine_PolyMAC.
References Domaine_Poly_base::discretiser(), and Domaine_Poly_base::discretiser_aretes().
calculer_volumes_entrelaces()
void Domaine_PolyMAC_P0P1NC::calculer_volumes_entrelaces () override virtual
Reimplemented from Domaine_PolyMAC.
References Domaine_VF::creer_tableau_faces(), Domaine_PolyMAC::dot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_normales_, Domaine_VF::face_voisins_, Domaine_VF::nb_faces(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::volumes_entrelaces_, Domaine_VF::volumes_entrelaces_dir_, Domaine_VF::xp_, and Domaine_VF::xv_.
surf_elem_arete()
const DoubleTab & Domaine_PolyMAC_P0P1NC::surf_elem_arete () const
References Domaine_32_64< _SIZE_ >::coord_sommets(), Domaine_VF::cross(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_PolyMAC::dot(), Domaine_Poly_base::elem_arete_d(), Domaine_32_64< _SIZE_ >::elem_aretes(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_Poly_base::som_arete, Domaine_Poly_base::ta_, Domaine_VF::xa_, Domaine_VF::xp(), and Domaine_VF::xv().
Referenced by M1(), and W1().
M1()
void Domaine_PolyMAC_P0P1NC::M1 (const DoubleTab * nu, int e, DoubleTab & m1) const
References Domaine_32_64< _SIZE_ >::aretes_som(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Domaine_PolyMAC::dot(), Domaine_Poly_base::elem_arete_d(), Domaine_32_64< _SIZE_ >::elem_aretes(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets(), Domaine_Poly_base::nu_dot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), surf_elem_arete(), and Domaine_VF::volumes().
W1()
void Domaine_PolyMAC_P0P1NC::W1 (const DoubleTab * nu, int e, DoubleTab & w1, DoubleTab & v_e, DoubleTab & v_ea) const
References Domaine_32_64< _SIZE_ >::aretes_som(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Domaine_PolyMAC::dot(), Domaine_Poly_base::elem_arete_d(), Domaine_32_64< _SIZE_ >::elem_aretes(), Domaine_VF::elem_faces(), Domaine_VF::face_sommets(), Domaine_Poly_base::nu_dot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), surf_elem_arete(), and Domaine_VF::volumes().