CEA TRUST Platform: Schema_Implicite_base Class Reference
Schema_Implicite_base Class Reference
Additional Inherited Members
Public Member Functions inherited from Schema_Temps_base
virtual void changer_temps_courant (const double)
virtual bool corriger_dt_calcule (double &dt) const
int diffusion_implicite () const
double & facteur_securite_pas ()
double facteur_securite_pas () const
virtual int impr (Sortie &os) const
virtual int impr (Sortie &os, Probleme_base &pb) const
virtual void imprimer (Sortie &os) const
void imprimer (Sortie &os, Probleme_base &pb) const
virtual bool isStationary () const
const Nom & le_nom () const override
int limpr () const
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int mettre_a_jour ()
int nb_impr () const
int nb_pas_dt () const
int nb_pas_dt_max () const
int nb_pas_dt_max_atteint () const
int nb_sauv_max () const
void nommer (const Nom &) override
double pas_de_temps () const
double & pas_temps_max ()
double pas_temps_max () const
double & pas_temps_min ()
double pas_temps_min () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
double seuil_statio () const
virtual int stop () const
int stop_lu () const
double temps_calcul () const
double temps_courant () const
int temps_final_atteint () const
double temps_impr () const
double temps_init () const
double temps_max () const
double temps_precedent () const
double temps_sauv () const
void update_critere_statio (const DoubleTab &tab_critere, Equation_base &equation)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Il porte un objet de type Solveur (ex le Simpler)
Member Function Documentation
OWN_PTR() [1/3]
Schema_Implicite_base::OWN_PTR (Solveur_Implicite_base) & inline
OWN_PTR() [2/3]
const Schema_Implicite_base::OWN_PTR (Solveur_Implicite_base) const & inline
set_param()
void Schema_Implicite_base::set_param (Param & param) override virtual
Reimplemented from Schema_Temps_base.
Reimplemented in Schema_Implicite_Multi_TimeStep_base.
References Param::ajouter(), Param::REQUIRED, and Schema_Temps_base::set_param().
Referenced by Schema_Euler_Implicite::set_param(), and Schema_Implicite_Multi_TimeStep_base::set_param().
OWN_PTR() [3/3]
Schema_Implicite_base::OWN_PTR (Solveur_Implicite_base) protected