CEA TRUST Platform: VDF_to_IJK Class Reference
VDF_to_IJK Class Reference
Member Function Documentation
initialize()
void VDF_to_IJK::initialize (const Domaine_VF & domaine_vf, const Domaine_IJK & splitting, Domaine_IJK::Localisation localisation, int direction_for_x, int direction_for_y, int direction_for_z)
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Entree::eof(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, Domaine_IJK::get_nb_elem_local(), Domaine_IJK::get_nb_items_global(), Domaine_IJK::get_node_coordinates(), Domaine_IJK::get_processor_mapping(), Domaine_IJK::get_slice_offsets(), Domaine_IJK::get_slice_size(), ijk_ni_, ijk_nj_, Process::me(), Process::nproc(), Domaine_VF::orientation(), pe_recv_, pe_recv_data_, pe_send_, pe_send_data_, Objet_U::precision_geom, Schema_Comm::recv_buffer(), Schema_Comm::send_buffer(), and Schema_Comm::set_send_recv_pe_list().
convert_from_ijk()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void VDF_to_IJK::convert_from_ijk (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & ijk_x, DoubleVect & x, bool add = false) const
References Schema_Comm_Vecteurs::add_recv_area_template(), Schema_Comm_Vecteurs::add_send_area_template(), Schema_Comm_Vecteurs::begin_comm(), Schema_Comm_Vecteurs::begin_init(), Schema_Comm_Vecteurs::end_comm(), Schema_Comm_Vecteurs::end_init(), Schema_Comm_Vecteurs::exchange(), Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), Schema_Comm_Vecteurs::get_next_area_template(), ijk_ni_, ijk_nj_, pe_recv_, pe_recv_data_, pe_send_, pe_send_data_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Multigrille_base::convert_from_ijk().
convert_to_ijk()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void VDF_to_IJK::convert_to_ijk (const DoubleVect & x, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & ijk_x) const
References Schema_Comm_Vecteurs::add_recv_area_template(), Schema_Comm_Vecteurs::add_send_area_template(), Schema_Comm_Vecteurs::begin_comm(), Schema_Comm_Vecteurs::begin_init(), Schema_Comm_Vecteurs::end_comm(), Schema_Comm_Vecteurs::end_init(), Schema_Comm_Vecteurs::exchange(), Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), Schema_Comm_Vecteurs::get_next_area_template(), ijk_ni_, ijk_nj_, pe_recv_, pe_recv_data_, pe_send_, pe_send_data_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Multigrille_base::convert_to_ijk().
Member Data Documentation
pe_send_
ArrOfInt VDF_to_IJK::pe_send_ protected
Referenced by convert_from_ijk(), convert_to_ijk(), and initialize().
pe_recv_
ArrOfInt VDF_to_IJK::pe_recv_ protected
Referenced by convert_from_ijk(), convert_to_ijk(), and initialize().
pe_recv_size_
ArrOfInt VDF_to_IJK::pe_recv_size_ protected
pe_send_data_
Static_Int_Lists VDF_to_IJK::pe_send_data_ protected
Referenced by convert_from_ijk(), convert_to_ijk(), and initialize().
pe_recv_data_
Static_Int_Lists VDF_to_IJK::pe_recv_data_ protected
Referenced by convert_from_ijk(), convert_to_ijk(), and initialize().
ijk_ni_
int VDF_to_IJK::ijk_ni_ protected
Referenced by convert_from_ijk(), convert_to_ijk(), and initialize().
ijk_nj_
int VDF_to_IJK::ijk_nj_ protected
Referenced by convert_from_ijk(), convert_to_ijk(), and initialize().