CEA TRUST Platform: Champ_Elem_PolyMAC_P0P1NC Class Reference
Champ_Elem_PolyMAC_P0P1NC Class Reference
Public Member Functions
int reprendre (Entree &fich) override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Champ correspondant a une inconnue scalaire (type temperature ou pression) Degres de libertes : valeur aux elements + flux aux faces
Member Function Documentation
affecter_()
Champ_base & Champ_Elem_PolyMAC_P0P1NC::affecter_ (const Champ_base & ch) override virtual
Reimplemented from Champ_Elem_PolyMAC.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_Inc_base::domaine(), domaine_PolyMAC_P0P1NC(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), init_auxiliary_variables(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), TRUSTTab_parts< _TYPE_ >::size(), Champ_base::valeur_aux(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
fixer_nb_valeurs_nodales()
int Champ_Elem_PolyMAC_P0P1NC::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_Elem_PolyMAC.
References Champ_Inc_base::creer_tableau_distribue(), Champ_Inc_base::domaine(), and Champ_Inc_base::domaine_dis_base().
domaine_PolyMAC_P0P1NC()
const Domaine_PolyMAC_P0P1NC & Champ_Elem_PolyMAC_P0P1NC::domaine_PolyMAC_P0P1NC () const
Referenced by affecter_(), and init_auxiliary_variables().
nb_valeurs_nodales()
int Champ_Elem_PolyMAC_P0P1NC::nb_valeurs_nodales () const override virtual
Returns the number of "real" geometric positions of the degrees of freedom, or -1 if not applicable (fields with multiple localisations)
Reimplemented from Champ_Inc_base.
init_auxiliary_variables()
void Champ_Elem_PolyMAC_P0P1NC::init_auxiliary_variables () virtual
Reimplemented in Champ_Elem_PolyMAC_P0.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_Inc_base::domaine(), domaine_PolyMAC_P0P1NC(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Inc_base::futur(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Champ_Inc_base::nb_valeurs_temporelles(), TRUSTTab< _TYPE_, _SIZE_ >::resize_dim0(), TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector(), and TRUSTVect< _TYPE_, _SIZE_ >::size_reelle_ok().
Referenced by affecter_(), Op_Diff_PolyMAC_P0P1NC_Elem::completer(), and reprendre().
reprendre()
int Champ_Elem_PolyMAC_P0P1NC::reprendre (Entree & fich) override virtual
Lecture d'un champ inconnue a partir d'un flot d'entree en vue d'une reprise.
Parameters
(Entree& fich) un flot d'entree
Returns
(int) renvoie toujours 1
Reimplemented from Champ_Inc_base.
References MorEqn::equation(), init_auxiliary_variables(), MorEqn::mon_equation_non_nul(), Champ_Inc_base::reprendre(), and Champ_Inc_base::via_ch_fonc_reprise().