CEA TRUST Platform: Convection_Diffusion_Fluide_Dilatable_base Class Reference
Convection_Diffusion_Fluide_Dilatable_base Class Reference abstract
Public Member Functions
int impr (Sortie &os) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
virtual std::vector< YAML_data > data_a_sauvegarder () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
virtual DoubleTab & derivee_en_temps_inco (DoubleTab &)
const Discretisation_base & discretisation () const
virtual void discretiser ()
virtual const Motcle & domaine_application () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
virtual int preparer_calcul ()
Probleme_base & probleme ()
const Probleme_base & probleme () const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Detailed Description
See also
Conv_Diffusion_std Convection_Diffusion_Temperature
Member Function Documentation
associer_fluide()
void Convection_Diffusion_Fluide_Dilatable_base::associer_fluide (const Fluide_Dilatable_base & un_fluide)
Referenced by associer_milieu_base().
associer_milieu_base()
void Convection_Diffusion_Fluide_Dilatable_base::associer_milieu_base (const Milieu_base & un_milieu) override virtual
Implements Equation_base.
References associer_fluide().
impr()
int Convection_Diffusion_Fluide_Dilatable_base::impr (Sortie & os) const override virtual
Imprime les operateurs de l'equation sur un flot de sortie, de facon inconditionnelle.
appelle Operateur_base::impr(os)
Parameters
(Sortie& os) le flot de sortie
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
References Equation_base::impr().
diffusivite_pour_transport()
const Champ_Don_base & Convection_Diffusion_Fluide_Dilatable_base::diffusivite_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_std.
References Milieu_base::conductivite(), is_thermal(), and milieu().
Referenced by Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_Turbulent_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Binaire_Turbulent_QC::lire_motcle_non_standard(), and Convection_Diffusion_Espece_Multi_Turbulent_QC::lire_motcle_non_standard().
fluide() [1/2]
const Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::fluide () const
References Process::exit(), Probleme_U::le_nom(), and Equation_base::probleme().
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Convection_Diffusion_Espece_Multi_QC::completer(), Convection_Diffusion_Espece_Multi_WC::completer(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), and milieu().
fluide() [2/2]
Fluide_Dilatable_base & Convection_Diffusion_Fluide_Dilatable_base::fluide ()
milieu() [1/2]
const Milieu_base & Convection_Diffusion_Fluide_Dilatable_base::milieu () const override virtual
Implements Equation_base.
References fluide().
Referenced by Convection_Diffusion_Chaleur_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps(), and diffusivite_pour_transport().
milieu() [2/2]
Milieu_base & Convection_Diffusion_Fluide_Dilatable_base::milieu () override virtual
Implements Equation_base.
References fluide().
set_param()
void Convection_Diffusion_Fluide_Dilatable_base::set_param (Param & titi) override virtual
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Chaleur_QC.
References Convection_Diffusion_std::set_param().
Referenced by Convection_Diffusion_Espece_Binaire_base::set_param(), Convection_Diffusion_Espece_Multi_base::set_param(), Convection_Diffusion_Chaleur_QC::set_param(), and Convection_Diffusion_Chaleur_WC::set_param().
lire_motcle_non_standard()
int Convection_Diffusion_Fluide_Dilatable_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Espece_Multi_Turbulent_QC, Convection_Diffusion_Espece_Binaire_Turbulent_QC, Convection_Diffusion_Chaleur_Turbulent_QC, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Chaleur_QC.
References Convection_Diffusion_std::lire_motcle_non_standard().
Referenced by Convection_Diffusion_Espece_Binaire_base::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard(), Convection_Diffusion_Chaleur_QC::lire_motcle_non_standard(), Convection_Diffusion_Espece_Multi_QC::lire_motcle_non_standard(), and Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard().
calculer_div_u_ou_div_rhou()
void Convection_Diffusion_Fluide_Dilatable_base::calculer_div_u_ou_div_rhou (DoubleTab & res) const override pure virtual
Implements Convection_Diffusion_Fluide_Dilatable_Proto.
Implemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Chaleur_QC, and Convection_Diffusion_Espece_Fluide_Dilatable_base.
is_thermal()
bool Convection_Diffusion_Fluide_Dilatable_base::is_thermal () const override pure virtual
Implements Convection_Diffusion_Fluide_Dilatable_Proto.
Implemented in Convection_Diffusion_Espece_Fluide_Dilatable_base, and Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
Referenced by diffusivite_pour_transport().
is_generic()
bool Convection_Diffusion_Fluide_Dilatable_base::is_generic () const override pure virtual
Implements Convection_Diffusion_Fluide_Dilatable_Proto.
Implemented in Convection_Diffusion_Chaleur_Fluide_Dilatable_base, Convection_Diffusion_Chaleur_WC, Convection_Diffusion_Chaleur_QC, and Convection_Diffusion_Espece_Fluide_Dilatable_base.
inconnue() [1/2]
const Champ_Inc_base& Convection_Diffusion_Fluide_Dilatable_base::inconnue () const inline override virtual
Implements Convection_Diffusion_std.
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl(), Convection_Diffusion_Chaleur_WC::completer(), Convection_Diffusion_Espece_Multi_QC::derivee_en_temps_inco(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::sauvegarder().
inconnue() [2/2]
Champ_Inc_base& Convection_Diffusion_Fluide_Dilatable_base::inconnue () inline override virtual
Implements Convection_Diffusion_std.
domaine_cl_modif() [1/2]
const Domaine_Cl_dis_base& Convection_Diffusion_Fluide_Dilatable_base::domaine_cl_modif () const inline
Referenced by Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl().
domaine_cl_modif() [2/2]
Domaine_Cl_dis_base& Convection_Diffusion_Fluide_Dilatable_base::domaine_cl_modif () inline
OWN_PTR() [1/2]
Convection_Diffusion_Fluide_Dilatable_base::OWN_PTR (Champ_Inc_base) protected
OWN_PTR() [2/2]
Convection_Diffusion_Fluide_Dilatable_base::OWN_PTR (Domaine_Cl_dis_base) protected
OBS_PTR()
Convection_Diffusion_Fluide_Dilatable_base::OBS_PTR (Fluide_Dilatable_base) protected
Referenced by Convection_Diffusion_Espece_Multi_base::get_champ(), Convection_Diffusion_Chaleur_Turbulent_QC::get_champ(), and Convection_Diffusion_Espece_Multi_Turbulent_QC::get_champ().