CEA TRUST Platform: Operateur_Statistique_tps_base Class Reference
Operateur_Statistique_tps_base Class Reference abstract
#include <Operateur_Statistique_tps_base.h>
Public Member Functions
const Nom & le_nom () const override=0
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Des operateurs statistiques sont utilises pour le postraitement.
See also
Operateurs_Statistique_tps Postraitement, Classe abstraite, Methodes abstraites:, void completer(const Probleme_base&)
Member Function Documentation
localisation_post()
const Nom & Operateur_Statistique_tps_base::localisation_post () const inline
References localisation_post_.
Referenced by completer_post_statistiques().
associer() [1/2]
void Operateur_Statistique_tps_base::associer (const Nom & loc_post) inline
References localisation_post_.
associer_op_stat()
virtual void Operateur_Statistique_tps_base::associer_op_stat (const Operateur_Statistique_tps_base &) inline virtual
Reimplemented in Op_Correlation, and Op_Ecart_type.
associer() [2/2]
virtual void Operateur_Statistique_tps_base::associer (const Domaine_dis_base & , const Champ_Generique_base & , double , double) pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
fixer_tstat_deb()
virtual void Operateur_Statistique_tps_base::fixer_tstat_deb (double , double) pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by Champ_Generique_Statistiques_base::fixer_serie(), and Champ_Generique_Statistiques_base::fixer_tstat_deb().
fixer_tstat_fin()
virtual void Operateur_Statistique_tps_base::fixer_tstat_fin (double) pure virtual
Implemented in Op_Moyenne, Op_Correlation, and Op_Ecart_type.
Referenced by Champ_Generique_Statistiques_base::fixer_serie().
mettre_a_jour()
virtual void Operateur_Statistique_tps_base::mettre_a_jour (double temps) pure virtual
Implemented in Op_Moyenne, Op_Correlation, and Op_Ecart_type.
Referenced by Champ_Generique_Statistiques_base::mettre_a_jour().
le_nom()
const Nom & Operateur_Statistique_tps_base::le_nom () const override pure virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Reimplemented from Objet_U.
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by completer_post_statistiques().
temps()
virtual double Operateur_Statistique_tps_base::temps () const pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
integrale()
virtual const Integrale_tps_Champ & Operateur_Statistique_tps_base::integrale () const pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by completer_post_statistiques(), and Moyenne_volumique::get_champ().
initialiser()
virtual void Operateur_Statistique_tps_base::initialiser (double val) pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by Champ_Generique_Statistiques_base::fixer_serie().
completer()
virtual void Operateur_Statistique_tps_base::completer (const Probleme_base & , const Nom & post_name) pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
calculer_valeurs()
virtual DoubleTab Operateur_Statistique_tps_base::calculer_valeurs () const pure virtual
Implemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by Moyenne_volumique::get_champ(), and Ecrire_fichier_xyz_valeur::write_fields().
completer_post_statistiques()
int Operateur_Statistique_tps_base::completer_post_statistiques (const Domaine & dom, const int is_axi, Format_Post_base & format) virtual
Reimplemented in Op_Correlation.
References Objet_U::axi, Champ_base::completer_post_champ(), integrale(), le_nom(), and localisation_post().
tstat_deb()
double Operateur_Statistique_tps_base::tstat_deb () const inline
References tstat_deb_.
tstat_fin()
double Operateur_Statistique_tps_base::tstat_fin () const inline
References tstat_fin_.
tstat_dernier_calcul()
double Operateur_Statistique_tps_base::tstat_dernier_calcul () const inline
References tstat_dernier_calcul_.
data_a_sauvegarder()
virtual std::vector< YAML_data > Operateur_Statistique_tps_base::data_a_sauvegarder () const inline virtual
Reimplemented in Op_Correlation, Op_Ecart_type, and Op_Moyenne.
Referenced by Champ_Generique_Statistiques_base::data_a_sauvegarder().
Member Data Documentation
localisation_post_
Nom Operateur_Statistique_tps_base::localisation_post_ protected
Referenced by associer(), and localisation_post().
tstat_deb_
double Operateur_Statistique_tps_base::tstat_deb_ =-123. protected
Referenced by tstat_deb().
tstat_dernier_calcul_
double Operateur_Statistique_tps_base::tstat_dernier_calcul_ =-123. protected
Referenced by tstat_dernier_calcul().
tstat_fin_
double Operateur_Statistique_tps_base::tstat_fin_ =-123. protected
Referenced by tstat_fin().