CEA TRUST Platform: Champ_P0_VDF Class Reference
Champ_P0_VDF Class Reference
#include <Champ_P0_VDF.h>
Public Member Functions
double integrale_espace (int ncomp) const override
DoubleVect moyenne (const DoubleVect &porosite_elem) const
Public Member Functions inherited from Champ_Inc_P0_base
Champ_base & affecter_ (const Champ_base &) override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Champ_implementation_P0
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Champ_Inc_P0_base
Member Function Documentation
domaine_VDF()
const Domaine_VDF & Champ_P0_VDF::domaine_VDF () const
Referenced by integrale_espace(), moyenne(), and moyenne().
moyenne() [1/2]
DoubleVect Champ_P0_VDF::moyenne (const DoubleVect & porosite_elem) const
renvoie la moyenne du champ au sens P0 i.
e la somme, divisee par le volume total du domaine, des valeurs constantes par element multipliees par les volumes des elements
References domaine_VDF(), Field_base::nb_comp(), Domaine_dis_base::nb_elem(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
moyenne() [2/2]
double Champ_P0_VDF::moyenne (const DoubleVect & porosite_elem, int ncomp) const
Cette fonction effectue le calcul de la moyenne au sens P0 de la kieme composante du champ.
References domaine_VDF(), Domaine_dis_base::nb_elem(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
remplir_coord_noeuds()
DoubleTab & Champ_P0_VDF::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Reimplemented from Champ_Inc_P0_base.
References Domaine_32_64< _SIZE_ >::calculer_centres_gravite(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Domaine_dis_base::domaine(), Champ_Inc_base::domaine_dis_base(), Domaine_dis_base::nb_elem(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::xp().
imprime()
int Champ_P0_VDF::imprime (Sortie & os, int nb_compo_) const override virtual
Ecrit le champ sous la forme IJK.
Reimplemented from Champ_Inc_base.
References Objet_U::dimension, Process::exit(), Field_base::nb_compo_, Objet_U::nom_du_cas(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Inc_base::valeur_aux().
integrale_espace()
double Champ_P0_VDF::integrale_espace (int ncomp) const override virtual
Appel a l'objet sous-jacent calcule l'integrale de l'une des composantes.
du champ sur le domaine qui lui correspond
Parameters
(int ncomp) le numero de la composante integree en espace
Returns
(double) valeur de l'integrale
Reimplemented from Champ_Inc_base.
References domaine_VDF(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().