CEA TRUST Platform: ILU_SP Class Reference
ILU_SP Class Reference
#include <ILU_SP.h>
Protected Member Functions
void prepare_ (const Matrice_Base &, const DoubleVect &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Precond_base
int preconditionner (const Matrice_Base &, const DoubleVect &src, DoubleVect &solution)
void prepare (const Matrice_Base &, const DoubleVect &src)
void reinit (Init_Status x=REINIT_ALL)
void set_echange_espace_virtuel_resultat (int flag)
virtual int supporte_matrice_morse_sym ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Member Enumeration Documentation
Type_Precond
enum ILU_SP::Type_Precond protected
Enumerator
PRECOND_NUL
PRECOND_GAUCHE
PRECOND_DROITE
PRECOND_GAUCHE_DROITE
Member Function Documentation
a_un_interet()
int ILU_SP::a_un_interet () inline
type_precond()
int ILU_SP::type_precond () inline
References precond_.
Referenced by Solv_Gen::solve().
prepare_()
void ILU_SP::prepare_ (const Matrice_Base & m, const DoubleVect & v) override protected virtual
this method must be overloaded if some preparation is necessary.
It is called after a call to reinit() and before the next call to preconditionner_(). Do not forget to call the prepare_() method of the ancestor (at the end of the routine, otherwise status will be put to READY) and use get_status() to know what should be prepared.
Reimplemented from Precond_base.
References Process::exit(), factorisation(), Matrice_Bloc::get_bloc(), Precond_base::get_status(), Precond_base::prepare_(), and Precond_base::READY.
preconditionner_()
int ILU_SP::preconditionner_ (const Matrice_Base & la_matrice, const DoubleVect & u, DoubleVect & s) override protected virtual
Calcule la solution du systeme lineaire: A * solution = b avec la methode de relaxation ILU.
Implements Precond_base.
References ilu(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
factorisation()
int ILU_SP::factorisation (const Matrice_Morse & mat, const DoubleVect & secmem) protected
References Matrice_Morse::dimensionner(), factoriser(), Matrice_Morse::get_coeff(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_set_tab1(), Matrice_Morse::get_set_tab2(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), MLOC, Process::nproc(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by prepare_().
factoriser()
int ILU_SP::factoriser (const Matrice_Morse & mat, const DoubleVect & b) protected virtual
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), alu, Process::exit(), Matrice_Morse::get_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), jlu, ju, lfil_, Matrice_Morse::nb_coeff(), Matrice_Morse::nb_lignes(), precond_, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by factorisation().
ilu()
int ILU_SP::ilu (int n, const DoubleVect & u, DoubleVect & s) protected
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), alu, jlu, and ju.
Referenced by preconditionner_().
ilut()
int ILU_SP::ilut (int n, const DoubleVect & u, DoubleVect & s) protected
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), alu, jlu, and ju.
Member Data Documentation
ju
ArrOfInt ILU_SP::ju protected
Referenced by factoriser(), ilu(), and ilut().
alu
ArrOfDouble ILU_SP::alu protected
Referenced by factoriser(), ilu(), and ilut().
jlu
ArrOfInt ILU_SP::jlu protected
Referenced by factoriser(), ilu(), and ilut().
precond_
int ILU_SP::precond_ = 2 protected
Referenced by factoriser(), and type_precond().
lfil_
int ILU_SP::lfil_ = 1 protected
Referenced by factoriser().
MLOC
Matrice_Morse ILU_SP::MLOC protected
Referenced by factorisation().