CEA TRUST Platform: Champ_Proto Class Reference
Champ_Proto Class Reference abstract
Public Member Functions
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Detailed Description
Tous les classes representant des champs derivent de Champ_proto. Champ_proto offre des methodes classiques sur des champs (min, max, norme, += ...) mais ne contient pas de membre representant des donnees. La plupart des methodes de Champ_proto font appel aux methodes de meme nom d'un objet DoubleTab renvoye par la methode abstraite de Champ_proto valeurs().
See also
Champ_base DoubleTab, Classe abstraite., Methode abstraite:, DoubleTab& valeurs()=0, const DoubleTab& valeurs() const
Constructor & Destructor Documentation
~Champ_Proto()
virtual Champ_Proto::~Champ_Proto () inline virtual
Member Function Documentation
valeurs() [1/4]
virtual DoubleTab& Champ_Proto::valeurs () pure virtual
Implemented in Champ_front_Parametrique, Champ_front_base, Champ_Don_base, Champ_Input_P0_Composite, Champ_front_Parametrique, Champ_front_base, Champ_Don_base, Champ_Input_P0_Composite, Champ_front_Parametrique, Champ_front_base, Champ_Don_base, Champ_Input_P0_Composite, Champ_Fonc_reprise, Champ_Fonc_MED, Champ_Parametrique, Champ_Inc_base, Champ_front_Parametrique, Champ_front_base, Champ_Don_base, Champ_Input_P0_Composite, Champ_Fonc_Tabule, Champ_front_Parametrique, Champ_front_base, Champ_Don_base, and Champ_Input_P0_Composite.
Referenced by Champ_base::affecter(), Champ_Fonc_Tabule::affecter_(), Champ_Face_PolyMAC::affecter_(), Champ_Face_PolyMAC_P0::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Face_VDF::affecter_(), Champ_Fonc_Face_VDF::affecter_(), Champ_P1_isoP1Bulle::affecter_(), Champ_Uniforme::affecter_(), Champ_Elem_PolyMAC_P0P1NC::affecter_(), Integrale_tps_produit_champs::ajoute_produit_tensoriel(), Op_Diff_VDF_base::ajoute_terme_pour_axi(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Iterateur_Source_EF_Som< _TYPE_ >::ajouter(), Source_Generique_P0_Elem::ajouter(), Source_Generique_Face_PolyMAC::ajouter(), Source_Generique_Face_PolyMAC_P0P1NC::ajouter(), Source_Generique_VEF::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Source_QC_Gravite_VDF::ajouter_blocs(), Source_Generique_VDF_Face::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::ajouter_blocs(), DP_Impose_PolyMAC_Face::ajouter_blocs(), Op_Evanescence_Homogene_Elem_base::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), DP_Impose_VEF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Op_Conv_EF::ajouter_contribution_sous_cond(), Source_Masse_Fluide_Dilatable_VEF::ajouter_eq_espece(), Op_Dift_VDF_Multi_inco_Elem::alpha_(), Op_Dift_VDF_Multi_inco_Elem_Axi::alpha_(), Op_Diff_Dift_VDF< OP_TYPE >::alpha_impl(), Convection_Diffusion_Espece_Multi_QC::assembler(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_blocs(), Assembleur_P_PolyMAC_P0P1NC::assembler_continuite(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_vort_elem(), Champ_P1NC::calcul_h_conv(), Convection_Diffusion_Temperature::calcul_indic_pena_global(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_temperature_VEF::calcul_temperature(), Perte_Charge_Singuliere::calculate_Q(), Champ_Q1NC_implementation::calcule_valeur_a_elem_compo(), Op_Diff_P1NC_barprim::calculer(), Masse_Multiphase::calculer_alpha_rho(), Energie_Multiphase::calculer_alpha_rho_e(), Energie_Multiphase::calculer_alpha_rho_h(), Op_Dift_EF_base::calculer_borne_locale(), Op_Dift_VDF_Face_base::calculer_borne_locale(), Op_Dift_VEF_base::calculer_borne_locale(), Equation_base::calculer_champ_conserve(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_EF_base::calculer_dt_stab(), Op_Dift_EF_Q1::calculer_dt_stab(), Op_Conv_PolyMAC_iterateur_base::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Conv_VDF_base::calculer_dt_stab(), Op_Diff_VDF_Elem_base::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Elem::calculer_dt_stab(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Diff_VDF_base::calculer_dt_stab_(), Fluide_base::calculer_e_int(), Traitement_particulier_NS_EC::calculer_Ec(), Terme_Source_Coriolis_VDF_Face::calculer_force_de_Coriolis(), Navier_Stokes_std::calculer_la_pression_en_pa(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Operateur_base::calculer_pour_post(), Op_Diff_negligeable::calculer_pour_post(), Op_Conv_PolyMAC_iterateur_base::calculer_pour_post(), Op_Conv_VDF_base::calculer_pour_post(), Op_Conv_VEF_base::calculer_pour_post(), Op_Diff_VEF_base::calculer_pour_post(), Op_Dift_VEF_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Convection_Diffusion_Temperature::calculer_rho_cp_T(), Fluide_base::calculer_temperature_multiphase(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl(), Source_PDF_EF::calculer_vitesse_imposee_power_law_tbl_u_star(), Discretisation_tools::cells_to_faces(), Discretisation_tools::cells_to_nodes(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Op_Diff_PolyMAC_P0_base::completer(), Champ_Generique_Transformation::completer(), Fluide_Weakly_Compressible::completer(), Op_Ecart_type::completer(), Op_Moyenne::completer(), Convection_Diffusion_Fluide_Dilatable_Proto::derivee_en_temps_inco_sans_solveur_masse_impl(), Op_Dift_EF_Q1::diffusivite(), Op_Dift_VEF_base::diffusivite(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Elem::dimensionner_blocs(), Terme_Source_Decroissance_Radioactive_Elem_PolyMAC::dimensionner_blocs(), Source_Flux_interfacial_base::dimensionner_blocs(), Source_Travail_pression_Elem_base::dimensionner_blocs(), Op_Conv_VDF_base::dimensionner_blocs_elem(), Assembleur_P_PolyMAC_P0P1NC::dimensionner_continuite(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), EcritureLectureSpecial::ecriture_special(), Champ_Elem_DG::eval_elem(), Discretisation_tools::faces_to_cells(), Champ_P1iP1B_implementation::filtrage(), Champ_P1NC_implementation::filtrer_L2(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), Sortie_libre_pression_imposee_QC::flux_impose(), Sortie_libre_pression_moyenne_imposee::flux_impose(), Sortie_libre_pression_imposee::flux_impose(), futur(), Champ_Generique_Divergence::get_champ(), Champ_Generique_Extraction::get_champ(), Champ_Generique_Gradient::get_champ(), Champ_Generique_Reduction_0D::get_champ(), Champ_Generique_Transformation::get_champ(), Champ_Generique_modifier_pour_QC::get_champ(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_Generique_Interpolation::get_champ_with_calculer_champ_post(), Champ_Generique_refChamp::get_ref_values(), Convection_Diffusion_Temperature::get_time_factor(), Probleme_base::getOutputPointValues(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Champ_implementation_P0::imprime_P0(), Champ_P1NC_implementation::imprime_P1NC(), Champ_Q4_implementation::imprime_Q4(), Champ_Fonc_Interp::initialiser(), Loi_Etat_rhoT_GP_QC::initialiser_rho(), EcritureLectureSpecial::lecture_special(), Op_EF_base::marque_elem(), Aire_interfaciale::mettre_a_jour(), Fluide_reel_base::mettre_a_jour(), Modele_turbulence_scal_Prandtl::mettre_a_jour(), Op_Conv_VDF_base::mettre_a_jour(), Integrale_tps_Champ::mettre_a_jour_integrale(), Milieu_composite::mettre_a_jour_tabs(), Iterateur_PolyMAC_Elem< _TYPE_ >::modifier_flux(), Op_EF_base::modifier_flux(), Op_VEF_Face::modifier_flux(), Assembleur_P_PolyMAC_P0P1NC::modifier_secmem_pour_incr_p(), Discretisation_tools::nodes_to_cells(), passe(), Convection_Diffusion_Temperature::penalisation_L2(), Postraitement::postprocess_field_values(), Op_Diff_VEF_base::remplir_nu(), Op_Diff_EF::remplir_nu(), Op_Dift_EF_Q1::remplir_nu(), Source_PDF_EF::rotate_imposed_velocity(), Op_Diff_Dift_VDF< OP_TYPE >::tab_alpha_impl(), Champ_front_debit_massique::update_coeff(), Champ_Fonc_Interp::update_fields(), Op_Diff_DG_base::update_nu(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), Op_Diff_PolyMAC_P0P1NC_base::update_nu(), Champ_implementation_P0::valeur_a_elem(), Champ_implementation_sommet::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem(), Champ_P1NC_implementation::valeur_a_elem(), Champ_Q1NC_implementation::valeur_a_elem(), Champ_Q4_implementation::valeur_a_elem_compo(), Champ_Face_VDF_implementation::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_elem_compo(), Champ_implementation_P0::valeur_a_elem_compo(), Champ_implementation_sommet::valeur_a_elem_compo(), Champ_P1NC_implementation::valeur_a_sommet_compo(), Champ_implementation_sommet::valeur_aux_bords(), Champ_base::valeur_aux_bords(), Champ_implementation_P0::valeur_aux_centres_de_gravite(), Champ_P1NC_implementation::valeur_aux_centres_de_gravite(), Champ_Elem_DG::valeur_aux_elems(), Champ_Fonc_P1_DG::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems(), Champ_P1NC_implementation::valeur_aux_elems(), Champ_Q1NC_implementation::valeur_aux_elems(), Champ_implementation_P0::valeur_aux_elems(), Champ_implementation_sommet::valeur_aux_elems(), Champ_Fonc_Face_PolyMAC::valeur_aux_elems(), Champ_Q4_implementation::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo(), Champ_Q1NC_implementation::valeur_aux_elems_compo(), Champ_implementation_P0::valeur_aux_elems_compo(), Champ_implementation_sommet::valeur_aux_elems_compo(), Champ_Face_PolyMAC::valeur_aux_elems_compo(), Champ_P1NC_implementation::valeur_aux_elems_compo_smooth(), Champ_P1NC_implementation::valeur_aux_elems_smooth(), Champ_Face_PolyMAC::valeur_aux_faces(), Champ_Face_PolyMAC_P0P1NC::valeur_aux_faces(), Champ_Fonc_Face_PolyMAC::valeur_aux_faces(), Champ_Face_VDF_implementation::valeur_aux_faces_post_impl(), Champ_Q4_implementation::valeur_aux_sommets(), Champ_Face_VDF_implementation::valeur_aux_sommets(), Champ_P1NC_implementation::valeur_aux_sommets(), Champ_Q4_implementation::valeur_aux_sommets_compo(), Champ_P1NC_implementation::valeur_aux_sommets_compo(), Champ_implementation_P0::valeur_aux_sommets_compo_impl(), Champ_implementation_sommet::valeur_aux_sommets_compo_impl(), Champ_implementation_P0::valeur_aux_sommets_impl(), Champ_implementation_sommet::valeur_aux_sommets_impl(), and Ecrire_fichier_xyz_valeur::write_fields().
valeurs() [2/4]
virtual const DoubleTab& Champ_Proto::valeurs () const pure virtual
Implemented in Champ_Fonc_reprise, Champ_Fonc_MED, Champ_Parametrique, Champ_Inc_base, Champ_front_Parametrique, Champ_front_base, Champ_Don_base, Champ_Input_P0_Composite, and Champ_Fonc_Tabule.
valeurs() [3/4]
virtual DoubleTab& Champ_Proto::valeurs (double temps) inline virtual
Reimplemented in Champ_Parametrique, and Champ_Inc_base.
References valeurs().
Referenced by valeurs().
valeurs() [4/4]
virtual const DoubleTab& Champ_Proto::valeurs (double temps) const inline virtual
Reimplemented in Champ_Parametrique, and Champ_Inc_base.
References valeurs().
Referenced by valeurs().
futur() [1/2]
virtual DoubleTab& Champ_Proto::futur (int i = 1) inline virtual
Reimplemented in Champ_Inc_base.
References valeurs().
futur() [2/2]
virtual const DoubleTab& Champ_Proto::futur (int i = 1) const inline virtual
Reimplemented in Champ_Inc_base.
References valeurs().
passe() [1/2]
virtual DoubleTab& Champ_Proto::passe (int i = 1) inline virtual
Reimplemented in Champ_Inc_base.
References valeurs().
Referenced by Terme_Source_Qdm_VDF_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0_Face::ajouter_blocs(), Op_Conv_EF_Stab_PolyMAC_P0P1NC_Face::ajouter_blocs(), Correction_Antal_PolyMAC_P0::ajouter_blocs(), Correction_Tomiyama_PolyMAC_P0::ajouter_blocs(), Dispersion_bulles_PolyMAC_P0::ajouter_blocs(), Frottement_interfacial_PolyMAC_P0::ajouter_blocs(), Portance_interfaciale_PolyMAC_P0::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Terme_Source_Qdm_Face_PolyMAC_P0P1NC::ajouter_blocs(), Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Source_Flux_interfacial_base::ajouter_blocs(), Source_Force_Tchen_base::ajouter_blocs(), Correction_Antal_VDF::ajouter_blocs(), Dispersion_bulles_VDF::ajouter_blocs(), Frottement_interfacial_VDF::ajouter_blocs(), Portance_interfaciale_VDF::ajouter_blocs(), Op_Conv_Amont_VPoly_VDF_Face::ajouter_blocs(), Masse_PolyMAC_P0_Face::ajouter_blocs(), Masse_VDF_Face::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), Force_Tchen_PolyMAC_P0::ajouter_blocs_aux(), Op_Diff_PolyMAC_P0P1NC_Elem::ajouter_blocs_ext(), Op_Evanescence_Homogene_Face_base::calc_vort_faces(), Op_Dift_Multiphase_VDF_Face::calculer_dt_stab(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Portance_interfaciale_PolyMAC_P0::mettre_a_jour(), Aire_interfaciale::mettre_a_jour(), Transport_turbulent_aire_interfaciale::modifier_mu(), Transport_turbulent_GGDH::modifier_mu(), Transport_turbulent_Prandtl::modifier_mu(), Transport_turbulent_SGDH::modifier_mu(), and Op_Diff_Turbulent_PolyMAC_P0_Face::modifier_mu().
passe() [2/2]
virtual const DoubleTab& Champ_Proto::passe (int i = 1) const inline virtual
Reimplemented in Champ_Inc_base.
References valeurs().
lire_dimension() [1/2]
int Champ_Proto::lire_dimension (Entree & is, const Nom & le_nom_)
Verification de la dimension du champ Renvoie la dimension du champ.
Returns
(int) la dimension du champ
lire_dimension() [2/2]
int Champ_Proto::lire_dimension (int dim, const Nom & le_nom_)
Verification de la dimension du champ Renvoie la dimension du champ.
Returns
(int) la dimension du champ
References Process::exit().
operator()() [1/4]
double Champ_Proto::operator() (int i, int j) const delete
operator()() [2/4]
double& Champ_Proto::operator() (int i, int j) delete
operator()() [3/4]
double Champ_Proto::operator() (int i) const delete
operator()() [4/4]
double& Champ_Proto::operator() (int i) delete