CEA TRUST Platform: EDO_Pression_th_VEF Class Reference
EDO_Pression_th_VEF Class Reference
Additional Inherited Members
Public Member Functions inherited from EDO_Pression_th_base
void associer_fluide (const Fluide_Dilatable_base &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF.
See also
Fluide_Quasi_Compressible EDO_Pression_th_base
Member Function Documentation
completer()
void EDO_Pression_th_VEF::completer () override virtual
Reimplemented from EDO_Pression_th_base.
References EDO_Pression_th_base::completer(), and Process::exit().
calculer_grad()
void EDO_Pression_th_VEF::calculer_grad (const DoubleTab & inco, DoubleTab & grad)
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VEF::nb_faces_joint(), Domaine_dis_base::nb_front_Cl(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Front_VF::num_premiere_face(), Domaine_VF::premiere_face_int(), Domaine_VEF::premiere_face_std(), Domaine_VF::volumes(), Domaine_VF::volumes_entrelaces(), and Domaine_VF::xp().
Referenced by EDO_Pression_th_VEF_Gaz_Reel::resoudre().
masse_totale() [1/2]
double EDO_Pression_th_VEF::masse_totale (double P, const DoubleTab & T) override virtual
Implements EDO_Pression_th_base.
References TRUSTVect< _TYPE_, _SIZE_ >::copy(), and Domaine_VF::nb_faces().
masse_totale() [2/2]
double EDO_Pression_th_VEF::masse_totale (const DoubleTab & P, const DoubleTab & T) override virtual
Implements EDO_Pression_th_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and Domaine_VF::nb_faces().