CEA TRUST Platform: Cond_lim Class Reference
Cond_lim Class Reference
#include <Cond_lim.h>
Public Member Functions
void adopt (Cond_lim &cl)
Detailed Description
derivee de la classe Cond_lim_base La plupart des methodes appellent les methodes de l'objet Probleme sous-jacent via la methode valeur() declaree grace a la macro
See also
Cond_lim_base
Constructor & Destructor Documentation
Cond_lim()
Cond_lim::Cond_lim (const Cond_lim &) default
Member Function Documentation
operator=() [1/2]
Cond_lim & Cond_lim::operator= (const Cond_lim_base & cl_base) inline
References operator=().
Referenced by operator=(), and operator=().
operator=() [2/2]
Cond_lim & Cond_lim::operator= (const Cond_lim & cl) inline
References operator=().
adopt()
void Cond_lim::adopt (Cond_lim & cl)
Adopte la Cond_lim passee en parametre.
Il n'y a pas de copie. La Cond_lim_base eventuellement detenue avant l'appel est detruite. ATTENTION cl est nul ensuite
Parameters
(Cond_lim& cl)
operator==()
int Cond_lim::operator== (const Cond_lim & x) const inline