CEA TRUST Platform: Champ_Fonc_Face_PolyMAC Class Reference
Champ_Fonc_Face_PolyMAC Class Reference
Public Member Functions
Champ_base & affecter_ (const Champ_base &) override
int fixer_nb_valeurs_nodales (int n) override
void mettre_a_jour (double) override
DoubleTab & remplir_coord_noeuds (DoubleTab &positions) const override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void resetTime (double time) override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
mettre_a_jour()
void Champ_Fonc_Face_PolyMAC::mettre_a_jour (double un_temps) override virtual
Mise a jour en temps du champ.
Parameters
(double temps) le temps de mise a jour
Reimplemented from Champ_Fonc_base.
Reimplemented in grad_Champ_Face_PolyMAC_P0.
References Champ_Fonc_base::mettre_a_jour().
interp_valeurs_elem()
void Champ_Fonc_Face_PolyMAC::interp_valeurs_elem (const DoubleTab & tab_ch, DoubleTab & val) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Fonc_base::domaine(), Champ_Fonc_base::domaine_vf(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and TRUSTTab< _TYPE_, _SIZE_ >::nb_dim().
Referenced by valeur_aux_elems().
valeur_a_elem()
DoubleVect & Champ_Fonc_Face_PolyMAC::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
valeur_a_elem_compo()
double Champ_Fonc_Face_PolyMAC::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
valeur_aux_elems()
DoubleTab & Champ_Fonc_Face_PolyMAC::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Champ_Fonc_base::domaine_vf(), Process::exit(), interp_valeurs_elem(), le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces_tot(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Proto::valeurs().
valeur_aux_elems_compo()
DoubleVect & Champ_Fonc_Face_PolyMAC::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_base.
valeur_aux_sommets()
DoubleTab & Champ_Fonc_Face_PolyMAC::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
valeur_aux_sommets_compo()
DoubleVect & Champ_Fonc_Face_PolyMAC::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
valeur_aux_faces()
DoubleTab & Champ_Fonc_Face_PolyMAC::valeur_aux_faces (DoubleTab & result) const override virtual
renvoie la valeur du champ aux faces
Reimplemented from Champ_base.
References Objet_U::dimension, Champ_Fonc_base::domaine(), Champ_Fonc_base::domaine_vf(), Process::exit(), le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Proto::valeurs().
remplir_coord_noeuds()
DoubleTab & Champ_Fonc_Face_PolyMAC::remplir_coord_noeuds (DoubleTab & coord) const override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab& coord)
Returns
(DoubleTab&) renvoie toujours le parametre coord
Reimplemented from Champ_Fonc_base.
remplir_coord_noeuds_et_polys()
int Champ_Fonc_Face_PolyMAC::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented from Champ_Fonc_base.
affecter_()
Champ_base & Champ_Fonc_Face_PolyMAC::affecter_ (const Champ_base & ch) override virtual
Affecte un Champ_base dans un Champ_Fonc_base.
Parameters
(Champ_base& ch) le champ partie droite de l'affectation
Returns
(Champ_base&) le resultat de l'affectation (*this) (avec upcast)
Reimplemented from Champ_Fonc_base.
References Process::abort(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Field_base::nb_compo_, Domaine_VF::nb_faces(), Champ_base::valeur_aux(), Champ_Don_base::valeurs(), Champ_Proto::valeurs(), and Domaine_VF::xv().
fixer_nb_valeurs_nodales()
int Champ_Fonc_Face_PolyMAC::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Fixe le nombre de degres de liberte par composante.
Parameters
(int nb_noeuds) le nombre de degre de liberte par composante
Reimplemented from Champ_Fonc_base.
Reimplemented in grad_Champ_Face_PolyMAC_P0.
References Champ_Fonc_base::creer_tableau_distribue(), Objet_U::dimension, Champ_Fonc_base::domaine_dis_base(), Domaine_VF::md_vector_faces(), Field_base::nb_compo_, and Domaine_VF::nb_faces().
le_champ() [1/2]
virtual Champ_base& Champ_Fonc_Face_PolyMAC::le_champ () inline protected virtual
Referenced by valeur_aux_elems(), and valeur_aux_faces().
le_champ() [2/2]
virtual const Champ_base& Champ_Fonc_Face_PolyMAC::le_champ () const inline protected virtual