CEA TRUST Platform: Partitionneur_Tranche_32_64< _SIZE_ > Class Template Reference
Partitionneur_Tranche_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void initialiser (const ArrOfInt &nb_tranches)
Public Member Functions inherited from Partitionneur_base_32_64< _SIZE_ >
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static void chercher_direction_perio (const Domaine_t &domaine, const Noms &liste_bords_perio, ArrOfInt &directions_perio)
Static Public Member Functions inherited from Partitionneur_base_32_64< _SIZE_ >
static int_t calculer_graphe_connexions_periodiques (const Domaine_t &domaine, const Noms &liste_bords_periodiques, const Static_Int_Lists_t &som_elem, const int_t my_offset, Static_Int_Lists_t &graph)
static int_t corriger_bords_avec_graphe (const Static_Int_Lists_t &graph_elements_perio, const Static_Int_Lists_t &som_elem, const Domaine_t &domaine, const Noms &liste_bords_perio, BigIntVect_ &elem_part)
static void corriger_bords_avec_liste (const Domaine_t &dom, const Noms &liste_bords_periodiques, const int_t my_offset, BigIntVect_ &elem_part)
static void corriger_elem0_sur_proc0 (BigIntVect_ &elem_part)
static int_t corriger_multiperiodique (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
static int_t corriger_sommets_bord (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Additional Inherited Members
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Partitionneur_Tranche_32_64< _SIZE_ >
Voir construire_partition
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Partitionneur_Tranche_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Partitionneur_Tranche_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntVect_t
template<typename _SIZE_ > using Partitionneur_Tranche_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Partitionneur_Tranche_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Partitionneur_Tranche_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
BigIntVect_
template<typename _SIZE_ > using Partitionneur_Tranche_32_64< _SIZE_ >::BigIntVect_ = TRUSTVect<int, _SIZE_>
Member Function Documentation
set_param()
template<typename _SIZE_ > void Partitionneur_Tranche_32_64< _SIZE_ >::set_param (Param & param) override virtual
Implements Partitionneur_base_32_64< _SIZE_ >.
References Param::ajouter_arr_size_predefinie(), and Param::REQUIRED.
associer_domaine()
template<typename _SIZE_ > void Partitionneur_Tranche_32_64< _SIZE_ >::associer_domaine (const Domaine_t & domaine) override virtual
Premiere etape d'initialisation du partitionneur: on associe un domaine.
Implements Partitionneur_base_32_64< _SIZE_ >.
initialiser()
template<typename _SIZE_ > void Partitionneur_Tranche_32_64< _SIZE_ >::initialiser (const ArrOfInt & nb_tranches)
Deuxieme etape d'initialisation: on definit le nombre de tranches.
(on peut utiliser readOn a la place).
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
construire_partition()
template<typename _SIZE_ > void Partitionneur_Tranche_32_64< _SIZE_ >::construire_partition (BigIntVect_ & elem_part, int & nb_parts_tot) const override virtual
Implements Partitionneur_base_32_64< _SIZE_ >.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), TRUSTArray< _TYPE_, _SIZE_ >::begin(), Domaine_32_64< _SIZE_ >::calculer_centres_gravite(), Objet_U::dimension, TRUSTArray< _TYPE_, _SIZE_ >::end(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTArray< _TYPE_, _SIZE_ >::ref_data(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
chercher_direction_perio()
template<typename _SIZE_ > void Partitionneur_Tranche_32_64< _SIZE_ >::chercher_direction_perio (const Domaine_t & domaine, const Noms & liste_bords_perio, ArrOfInt & directions_perio) static
Remplissage du tableau directions perio a partir des noms des bords periodiques.
Pour 0 <= i < Objet_U::dimension directions_perio[i] vaut 1 s'il existe un bord periodique pour lequel le vecteur delta est dirige dans la direction i.
References Reordonner_faces_periodiques_32_64< _SIZE_ >::check_faces_periodiques(), Objet_U::dimension, Process::exit(), Objet_U::precision_geom, and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().