CEA TRUST Platform: Faces_builder Class Reference
Faces_builder Class Reference
#include <Faces_builder.h>
Public Member Functions
void creer_faces_reeles (Domaine &domaine, const Static_Int_Lists &connect_som_elem, Faces &les_faces, IntTab &elem_faces)
Constructor & Destructor Documentation
Faces_builder()
Faces_builder::Faces_builder ()
Member Function Documentation
reset()
void Faces_builder::reset ()
References TRUSTTab< _TYPE_, _SIZE_ >::reset().
Referenced by creer_faces_reeles().
creer_faces_reeles()
void Faces_builder::creer_faces_reeles (Domaine & domaine, const Static_Int_Lists & connect_som_elem, Faces & les_faces, IntTab & elem_faces)
A partir de la description des elements du domaine et des frontieres (bords, raccords, groupe de faces et joints) :
Remplissage des structures suivantes:
pour les frontieres du domaine: fixer_num_premiere_face
les_faces.faces_sommets (faces reeles)
les_faces.faces_voisins (faces reeles)
elem_faces (pour les faces reeles des elements reels) (on initialise elem_faces de taille nb_elem_reels, nb_faces_par_elem)
joints.items_communs(FACE)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::exit(), Static_Int_Lists_32_64< _SIZE_ >::get_nb_lists(), Faces_32_64< _SIZE_ >::les_sommets(), reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and Faces_32_64< _SIZE_ >::voisins().
Referenced by Domaine_VF::discretiser(), ExtrudeParoi::extrude(), Extruder::extruder(), Extruder_en20::extruder(), Extruder_en3::extruder(), Extruder::extruder_hexa(), and Distanceparoi::interpreter_().
chercher_face_element()
template<typename _SIZE_ > int Faces_builder::chercher_face_element (const IntTab_T< _SIZE_ > & elem_som, const IntTab & faces_element_ref, const SmallArrOfTID_T< _SIZE_ > & une_face, const _SIZE_ elem) static
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().