CEA TRUST Platform: Champ_Face_PolyMAC Class Reference
Champ_Face_PolyMAC Class Reference
Public Member Functions
Champ_base & affecter_ (const Champ_base &) override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &result, int poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &polys, DoubleTab &result) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &polys, DoubleVect &result, int ncomp) const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
valeur_a_elem()
DoubleVect & Champ_Face_PolyMAC::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
valeur_a_elem_compo()
double Champ_Face_PolyMAC::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
valeur_aux_elems()
DoubleTab & Champ_Face_PolyMAC::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
Reimplemented in Champ_Face_PolyMAC_P0.
References le_champ(), valeur_aux_elems_(), and Champ_Inc_base::valeurs().
valeur_aux_elems_passe()
DoubleTab & Champ_Face_PolyMAC::valeur_aux_elems_passe (const DoubleTab & positions, const IntVect & polys, DoubleTab & result) const override virtual
Reimplemented from Champ_base.
Reimplemented in Champ_Face_PolyMAC_P0.
References le_champ(), Champ_Inc_base::passe(), and valeur_aux_elems_().
valeur_aux_elems_compo()
DoubleVect & Champ_Face_PolyMAC::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_base.
Reimplemented in Champ_Face_PolyMAC_P0.
References Objet_U::dimension, Champ_Inc_base::domaine_vf(), Champ_Face_base::fcl(), interp_ve(), le_champ(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Champ_Proto::valeurs().
Referenced by Champ_Face_PolyMAC_P0::valeur_aux_elems_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Face_PolyMAC::remplir_coord_noeuds (DoubleTab & positions) const override virtual
Implements Champ_Inc_base.
remplir_coord_noeuds_et_polys()
int Champ_Face_PolyMAC::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const override virtual
NE FAIT RIEN Methode a surcharger.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented from Champ_Inc_base.
valeur_aux_faces()
DoubleTab & Champ_Face_PolyMAC::valeur_aux_faces (DoubleTab & result) const override virtual
renvoie la valeur du champ aux faces
Reimplemented from Champ_base.
Reimplemented in Champ_Face_PolyMAC_P0P1NC.
References Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_vf(), Process::exit(), le_champ(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Proto::valeurs().
calcul_S_barre_sans_contrib_paroi()
DoubleVect & Champ_Face_PolyMAC::calcul_S_barre_sans_contrib_paroi (const DoubleTab & vitesse, DoubleVect & SMA_barre) const
References Process::abort(), and calcul_S_barre().
calcul_S_barre()
DoubleVect & Champ_Face_PolyMAC::calcul_S_barre (const DoubleTab & vitesse, DoubleVect & SMA_barre) const
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_vf(), and interp_gve().
Referenced by calcul_S_barre_sans_contrib_paroi().
trace()
DoubleTab & Champ_Face_PolyMAC::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Reimplemented from Champ_Inc_base.
Reimplemented in Champ_Face_PolyMAC_P0P1NC, and Champ_Face_PolyMAC_P0.
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_vf(), Champ_Face_base::init_fcl(), interp_ve(), le_champ(), Field_base::nb_comp(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Champ_Inc_base::valeurs().
affecter_()
Champ_base & Champ_Face_PolyMAC::affecter_ (const Champ_base & ch) override virtual
Affectation d'un OWN_PTR(Champ_base) generique (Champ_base) dans un champ inconnue.
Parameters
(Champ_base& ch) le champ partie droite de l'affectation
Returns
(Champ_base&) le resultat de l'affectation (*this)
Reimplemented from Champ_Inc_base.
Reimplemented in Champ_Face_PolyMAC_P0.
References Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Domaine_VF::nb_faces(), Champ_base::valeur_aux(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), and Domaine_VF::xv().
nb_valeurs_nodales()
int Champ_Face_PolyMAC::nb_valeurs_nodales () const override virtual
Returns the number of "real" geometric positions of the degrees of freedom, or -1 if not applicable (fields with multiple localisations)
Reimplemented from Champ_Inc_base.
Reimplemented in Champ_Face_PolyMAC_P0P1NC.
References Champ_Inc_base::valeurs().
fixer_nb_valeurs_nodales()
int Champ_Face_PolyMAC::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_Inc_base.
Reimplemented in Champ_Face_PolyMAC_P0P1NC, and Champ_Face_PolyMAC_P0.
References Champ_Inc_base::creer_tableau_distribue(), Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_dis_base(), Domaine_32_64< _SIZE_ >::nb_aretes(), Field_base::nb_compo_, and Domaine_32_64< _SIZE_ >::nb_som().
init_ra()
void Champ_Face_PolyMAC::init_ra () const
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_vf(), Champ_Face_base::fcl_, Champ_Face_base::init_fcl(), init_va(), racf, raci, radeb, rajf, raji, TRUSTTab< _TYPE_, _SIZE_ >::resize(), vacf, vaci, vadeb, vajf, and vaji.
Referenced by Masse_PolyMAC_Face::ajouter_masse(), Op_Diff_PolyMAC_Face::completer(), and Masse_PolyMAC_Face::dimensionner().
init_va()
void Champ_Face_PolyMAC::init_va () const
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_vf(), MorEqn::equation(), Champ_Face_base::fcl_, Matrice33::inverse(), Equation_base::milieu(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), vacf, vaci, vadeb, vajf, and vaji.
Referenced by init_ra().
interp_ve() [1/2]
void Champ_Face_PolyMAC::interp_ve (const DoubleTab & inco, DoubleTab & val, bool is_vit = true) const virtual
Reimplemented in Champ_Face_PolyMAC_P0P1NC.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_Cl_dis(), Champ_Inc_base::domaine_vf(), MorEqn::equation(), Champ_Face_base::fcl_, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), MorEqn::mon_equation_non_nul(), Milieu_base::porosite_elem(), and Milieu_base::porosite_face().
Referenced by interp_gve(), trace(), valeur_aux_elems_(), and valeur_aux_elems_compo().
interp_ve() [2/2]
void Champ_Face_PolyMAC::interp_ve (const DoubleTab & inco, const IntVect & les_polys, DoubleTab & val, bool is_vit = true) const virtual
Reimplemented in Champ_Face_PolyMAC_P0P1NC.
References Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_vf(), MorEqn::equation(), Equation_base::milieu(), MorEqn::mon_equation_non_nul(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
interp_gve()
void Champ_Face_PolyMAC::interp_gve (const DoubleTab & inco, DoubleTab & vals) const final virtual
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Champ_Inc_base::domaine(), Champ_Inc_base::domaine_Cl_dis(), Champ_Inc_base::domaine_vf(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Face_base::fcl_, interp_ve(), Domaine_Cl_dis_base::les_conditions_limites(), and Domaine_32_64< _SIZE_ >::nb_elem().
Referenced by calcul_S_barre().
le_champ() [1/2]
virtual Champ_base& Champ_Face_PolyMAC::le_champ () inline protected virtual
Referenced by trace(), Champ_Face_PolyMAC_P0::trace(), Champ_Face_PolyMAC_P0P1NC::trace(), valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems(), valeur_aux_elems_(), valeur_aux_elems_compo(), valeur_aux_elems_passe(), Champ_Face_PolyMAC_P0::valeur_aux_elems_passe(), valeur_aux_faces(), and Champ_Face_PolyMAC_P0P1NC::valeur_aux_faces().
le_champ() [2/2]
virtual const Champ_base& Champ_Face_PolyMAC::le_champ () const inline protected virtual
valeur_aux_elems_()
DoubleTab & Champ_Face_PolyMAC::valeur_aux_elems_ (const DoubleTab & val_face, const DoubleTab & positions, const IntVect & les_polys, DoubleTab & valeurs) const protected virtual
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Nom::debute_par(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Champ_Inc_base::domaine_vf(), Process::exit(), interp_ve(), le_champ(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Field_base::nb_comp(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem(), Objet_U::que_suis_je(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by valeur_aux_elems(), Champ_Face_PolyMAC_P0::valeur_aux_elems(), valeur_aux_elems_passe(), and Champ_Face_PolyMAC_P0::valeur_aux_elems_passe().
Member Data Documentation
radeb
IntTab Champ_Face_PolyMAC::radeb mutable
Referenced by Op_Diff_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Op_Diff_PolyMAC_Face::dimensionner(), and init_ra().
raji
IntTab Champ_Face_PolyMAC::raji
Referenced by Op_Diff_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Op_Diff_PolyMAC_Face::dimensionner(), and init_ra().
rajf
IntTab Champ_Face_PolyMAC::rajf
Referenced by Op_Diff_PolyMAC_Face::ajouter(), and init_ra().
raci
DoubleTab Champ_Face_PolyMAC::raci mutable
Referenced by Op_Diff_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), and init_ra().
racf
DoubleTab Champ_Face_PolyMAC::racf
Referenced by Op_Diff_PolyMAC_Face::ajouter(), and init_ra().
vadeb
IntTab Champ_Face_PolyMAC::vadeb mutable
Referenced by init_ra(), and init_va().
vaji
IntTab Champ_Face_PolyMAC::vaji
Referenced by init_ra(), and init_va().
vajf
IntTab Champ_Face_PolyMAC::vajf
Referenced by init_ra(), and init_va().
vaci
DoubleTab Champ_Face_PolyMAC::vaci mutable
Referenced by init_ra(), and init_va().
vacf
DoubleTab Champ_Face_PolyMAC::vacf
Referenced by init_ra(), and init_va().