CEA TRUST Platform: Champ_front_instationnaire_base Class Reference
Champ_front_instationnaire_base Class Reference
Public Member Functions
int avancer (double temps) override
int initialiser (double temps, const Champ_Inc_base &inco) override
int reculer (double temps) override
const DoubleTab & valeurs_au_temps (double temps) const override
DoubleTab & valeurs_au_temps (double temps) override
void valeurs_face (int, DoubleVect &) const override
Public Member Functions inherited from Champ_front_base
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
virtual void mettre_a_jour (double temps)
virtual const DoubleTab & valeurs () const override
virtual DoubleTab & valeurs () override
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
mais uniformes en espace.
Les aspects temporels sont equivalents a ceux de
Ch_front_var_instationnaire.
En revanche, le tableau de valeurs est dimensionne a une seule
valeur et n'a pas d'espace virtuel.
See also
Champ_front_base
Member Function Documentation
fixer_nb_valeurs_temporelles()
void Champ_front_instationnaire_base::fixer_nb_valeurs_temporelles (int nb_cases) override virtual
Surcharge Champ_front_base::fixer_nb_valeurs_temporelles.
Reimplemented from Champ_front_base.
References Roue::fixer_nb_cases(), and Champ_front_base::les_valeurs.
initialiser()
int Champ_front_instationnaire_base::initialiser (double temps, const Champ_Inc_base & inco) override virtual
Initialisation en debut de calcul.
Imperativement cette methode ne doit pas utiliser de donnees externes a l'equation (couplage). Si mettre_a_jour le fait, alors initialiser ne doit pas appeler mettre_a_jour.
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Champ_front_base.
References Champ_front_base::changer_temps_futur(), Champ_front_base::initialiser(), Champ_front_base::les_valeurs, Roue::nb_cases(), Field_base::nb_comp(), Champ_front_base::set_instationnaire(), and Champ_front_base::temps_defaut.
Referenced by Ch_front_input_uniforme::initialiser(), and Champ_front_Tabule::initialiser().
has_valeurs_au_temps()
bool Champ_front_instationnaire_base::has_valeurs_au_temps (double temps) const override virtual
Reimplemented from Champ_front_base.
References Champ_front_base::les_valeurs, Roue::nb_cases(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Roue::valeurs().
valeurs_au_temps() [1/2]
DoubleTab & Champ_front_instationnaire_base::valeurs_au_temps (double temps) override virtual
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
Implements Champ_front_base.
References Process::exit(), Champ_front_base::les_valeurs, Roue::nb_cases(), and Champ_front_base::valeurs().
Referenced by Champ_front_Tabule::mettre_a_jour().
valeurs_au_temps() [2/2]
const DoubleTab & Champ_front_instationnaire_base::valeurs_au_temps (double temps) const override virtual
Renvoie les valeurs au temps desire.
Sinon, sort en erreur.
Implements Champ_front_base.
References Process::exit(), Champ_front_base::les_valeurs, Roue::nb_cases(), and Champ_front_base::valeurs().
avancer()
int Champ_front_instationnaire_base::avancer (double temps) override virtual
Avance jusqu'au temps desire.
Sinon, sort en erreur.
Reimplemented from Champ_front_base.
References Process::exit(), Champ_front_base::les_valeurs, Roue::nb_cases(), and Roue::temps().
reculer()
int Champ_front_instationnaire_base::reculer (double temps) override virtual
Recule jusqu'au temps desire.
Sinon, sort en erreur.
Reimplemented from Champ_front_base.
References Process::exit(), Champ_front_base::les_valeurs, and Roue::nb_cases().
valeurs_face()
void Champ_front_instationnaire_base::valeurs_face (int num_face, DoubleVect & val) const override virtual
Renvoie le vecteur des valeurs du champ pour la face donnee.
Par defaut pour les champs fonc, on suppose que le tableau des valeurs porte nb_faces * nb_compo_ valeurs. Exemple de cas particulier: champ_front_uniforme::valeurs_face
Parameters
(num_face) l'indice d'une face sur la frontiere 0 <= num_face < frontiere_dis().frontiere().nb_faces()
(val) On resize ce tableau et on le remplit.
Reimplemented from Champ_front_base.
References Field_base::nb_compo_, TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Champ_front_base::valeurs().