CEA TRUST Platform: Navier_Stokes_Fluide_Dilatable_Proto Class Reference
Navier_Stokes_Fluide_Dilatable_Proto Class Reference
#include <Navier_Stokes_Fluide_Dilatable_Proto.h>
Public Member Functions
DoubleTab & derivee_en_temps_inco_impl (Navier_Stokes_std &, DoubleTab &res)
Constructor & Destructor Documentation
Navier_Stokes_Fluide_Dilatable_Proto()
Navier_Stokes_Fluide_Dilatable_Proto::Navier_Stokes_Fluide_Dilatable_Proto ()
Member Function Documentation
impr_impl()
int Navier_Stokes_Fluide_Dilatable_Proto::impr_impl (const Navier_Stokes_std & eqn, Sortie & os) const
References Operateur_Div::ajouter(), Navier_Stokes_std::div(), Probleme_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Navier_Stokes_std::fluide(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Probleme_U::le_nom(), MD_Vector::non_nul(), Navier_Stokes_std::operateur_divergence(), Schema_Temps_base::pas_de_temps(), Equation_base::probleme(), Fluide_Dilatable_base::rho_face_np1(), rho_vitesse_impl(), Probleme_base::schema_temps(), Fluide_Dilatable_base::secmembre_divU_Z(), tab_W, Champ_Inc_base::valeurs(), Navier_Stokes_std::vitesse(), Domaine_32_64< _SIZE_ >::volume_total(), and Operateur_Div::volumique().
Referenced by Navier_Stokes_Turbulent_QC::impr(), and Navier_Stokes_Fluide_Dilatable_base::impr().
assembler_impl()
void Navier_Stokes_Fluide_Dilatable_Proto::assembler_impl (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem)
References Process::exit().
Referenced by Navier_Stokes_Fluide_Dilatable_base::assembler(), and Navier_Stokes_Turbulent_QC::assembler().
assembler_avec_inertie_impl()
void Navier_Stokes_Fluide_Dilatable_Proto::assembler_avec_inertie_impl (const Navier_Stokes_std & eqn, Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem)
References Operateur::ajouter(), Sources::ajouter(), Solveur_Masse_base::ajouter_masse(), Matrice_Base::ajouter_multvect(), Operateur_base::contribuer_a_avec(), Sources::contribuer_a_avec(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), Cond_lim_base::frontiere_dis(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Navier_Stokes_std::inconnue(), Operateur::l_op_base(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Navier_Stokes_std::milieu(), Operateur_base::modifier_pour_Cl(), Front_VF::nb_faces(), Matrice_Morse::nb_lignes(), Navier_Stokes_std::nombre_d_operateurs(), Front_VF::num_premiere_face(), Navier_Stokes_std::operateur(), Schema_Temps_base::pas_de_temps(), Champ_Inc_base::passe(), Fluide_Dilatable_base::rho_face_n(), Fluide_Dilatable_base::rho_face_np1(), rho_vitesse_impl(), Equation_base::schema_temps(), Equation_base::solv_masse(), and Equation_base::sources().
Referenced by Navier_Stokes_Fluide_Dilatable_base::assembler_avec_inertie(), and Navier_Stokes_Turbulent_QC::assembler_avec_inertie().
assembler_blocs_avec_inertie()
void Navier_Stokes_Fluide_Dilatable_Proto::assembler_blocs_avec_inertie (const Navier_Stokes_std & eqn, matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl)
References Operateur_base::ajouter_blocs(), Solveur_Masse_base::ajouter_masse(), Matrice_Base::ajouter_multvect(), Statistiques::begin_count(), Objet_U::dimension, Equation_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Statistiques::end_count(), Cond_lim_base::frontiere_dis(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Nom::getString(), Navier_Stokes_std::inconnue(), Operateur::l_op_base(), Field_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Navier_Stokes_std::milieu(), Operateur_base::modifier_pour_Cl(), Front_VF::nb_faces(), Matrice_Morse::nb_lignes(), Navier_Stokes_std::nombre_d_operateurs(), Front_VF::num_premiere_face(), Navier_Stokes_std::operateur(), Navier_Stokes_std::operateur_gradient(), Schema_Temps_base::pas_de_temps(), Champ_Inc_base::passe(), Fluide_Dilatable_base::rho_face_n(), Fluide_Dilatable_base::rho_face_np1(), rho_vitesse_impl(), Equation_base::schema_temps(), Equation_base::solv_masse(), Equation_base::sources(), and Champ_Inc_base::valeurs().
Referenced by Navier_Stokes_Fluide_Dilatable_base::assembler_blocs_avec_inertie().
derivee_en_temps_inco_impl()
DoubleTab & Navier_Stokes_Fluide_Dilatable_Proto::derivee_en_temps_inco_impl (Navier_Stokes_std & eqn, DoubleTab & vpoint)
Calcule la derivee en temps de l'inconnue vitesse, i.
e. l'acceleration dU/dt et la renvoie. Appelle Equation_base::derivee_en_temps_inco(DoubleTab&) Calcule egalement la pression.
Parameters
(DoubleTab& vpoint) le tableau des valeurs de l'acceleration dU/dt
Returns
(DoubleTab&) le tableau des valeurs de l'acceleration (derivee de la vitesse)
References TRUSTTab< _TYPE_, _SIZE_ >::copy(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Navier_Stokes_std::has_champ(), Navier_Stokes_std::milieu(), MD_Vector::non_nul(), Navier_Stokes_std::pression(), tab_W, Champ_Inc_base::valeurs(), and Navier_Stokes_std::vitesse().
Referenced by Navier_Stokes_Fluide_Dilatable_base::derivee_en_temps_inco(), and Navier_Stokes_Turbulent_QC::derivee_en_temps_inco().
rho_vitesse_impl()
DoubleTab & Navier_Stokes_Fluide_Dilatable_Proto::rho_vitesse_impl (const DoubleTab & tab_rho, const DoubleTab & vit, DoubleTab & rhovitesse) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Debog::verifier().
Referenced by assembler_avec_inertie_impl(), assembler_blocs_avec_inertie(), impr_impl(), Navier_Stokes_Fluide_Dilatable_base::initTimeStep(), and Navier_Stokes_Turbulent_QC::initTimeStep().
OWN_PTR()
Navier_Stokes_Fluide_Dilatable_Proto::OWN_PTR (Champ_Inc_base) protected
Member Data Documentation
orientation_VDF_
IntVect Navier_Stokes_Fluide_Dilatable_Proto::orientation_VDF_ protected
tab_W
DoubleTab Navier_Stokes_Fluide_Dilatable_Proto::tab_W protected
Referenced by derivee_en_temps_inco_impl(), and impr_impl().