CEA TRUST Platform: Op_Conv_VEF_Face Class Reference
Op_Conv_VEF_Face Class Reference
Public Member Functions
void completer () override
Public Member Functions inherited from Op_Conv_VEF_base
double calculer_dt_stab () const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe represente l'operateur de convection associe a une equation de transport d'un scalaire. La discretisation est VEF Le champ convecte est scalaire ou vecteur de type Champ_P1NC Le schema de convection est du type Decentre ou Centre
See also
Operateur_Conv_base
Member Enumeration Documentation
type_lim_type
enum Op_Conv_VEF_Face::type_lim_type protected
Enumerator
type_lim_minmod
type_lim_vanleer
type_lim_vanalbada
type_lim_chakravarthy
type_lim_superbee
type_operateur
enum Op_Conv_VEF_Face::type_operateur protected
Enumerator
amont
muscl
centre
Constructor & Destructor Documentation
Op_Conv_VEF_Face()
Op_Conv_VEF_Face::Op_Conv_VEF_Face () inline
Member Function Documentation
completer()
void Op_Conv_VEF_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer(), Domaine_dis_base::nb_elem_tot(), Domaine_VEF::rang_elem_non_std(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Domaine_Cl_VEF::type_elem_Cl(), and type_elem_Cl_.
Referenced by Op_Conv_EF_VEF_P1NC_Stab::completer(), and Op_Conv_Muscl_New_VEF_Face::completer().
ajouter()
DoubleTab & Op_Conv_VEF_Face::ajouter (const DoubleTab & transporte, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References amont, Champ_P1NC::calcul_gradient(), centre, Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), est_une_face_de_dirichlet_, Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_VF::faces_doubles(), Domaine_VEF::facette_normales(), Cond_lim_base::frontiere_dis(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), gradient_elem_, gradient_face_, Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), muscl, TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_VF::nb_faces_tot(), Front_VF::nb_faces_tot(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_dis_base::nb_som_tot(), MD_Vector::non_nul(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_face(), Front_VF::num_premiere_face(), ordre_, Op_Conv_VEF_base::phi_u_transportant(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), Objet_U::que_suis_je(), Domaine_VEF::rang_elem_non_std(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), traitement_pres_bord_, Domaine_VEF::type_elem(), type_lim_chakravarthy, type_lim_int, type_lim_minmod, type_lim_superbee, type_lim_vanalbada, type_lim_vanleer, type_op, Champ_Inc_base::valeurs(), Domaine_Cl_VEF::vecteur_face_facette_Cl(), and Op_Conv_VEF_base::vitesse().
remplir_fluent()
void Op_Conv_VEF_Face::remplir_fluent () const override virtual
Reimplemented from Op_Conv_VEF_base.
References Elem_VEF_base::calcul_vc(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VEF::facette_normales(), Op_Conv_VEF_base::fluent_, Elem_VEF_base::KEL(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_premiere_face(), Op_Conv_VEF_base::phi_u_transportant(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Objet_U::que_suis_je(), Domaine_VEF::rang_elem_non_std(), Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), type_elem_Cl_, Champ_base::valeur_a_sommet_compo(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse().
dimensionner()
void Op_Conv_VEF_Face::dimensionner (Matrice_Morse & matrice) const inline override virtual
on dimensionne notre matrice au moyen de la methode dimensionner de la classe Op_VEF_Face.
Reimplemented from Operateur_base.
References Op_VEF_Face::dimensionner().
modifier_pour_Cl()
void Op_Conv_VEF_Face::modifier_pour_Cl (Matrice_Morse & matrice, DoubleTab & secmem) const inline override virtual
On modifie le second membre et la matrice dans le cas des conditions de dirichlet.
Reimplemented from Operateur_base.
References Op_VEF_Face::modifier_pour_Cl().
Referenced by Op_Conv_EF_VEF_P1NC_Stab::modifier_pour_Cl(), and Op_Conv_Muscl_New_VEF_Face::modifier_pour_Cl().
contribuer_a_avec()
void Op_Conv_VEF_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
on assemble la matrice des inconnues implicite.
Reimplemented from Operateur_base.
References ajouter_contribution().
contribuer_au_second_membre()
void Op_Conv_VEF_Face::contribuer_au_second_membre (DoubleTab & resu) const inline override virtual
on ajoute la contribution du second membre.
Reimplemented from Operateur_base.
References contribue_au_second_membre().
contribue_au_second_membre()
void Op_Conv_VEF_Face::contribue_au_second_membre (DoubleTab & resu) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Neumann_sortie_libre::val_ext(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse().
Referenced by contribuer_au_second_membre().
ajouter_contribution()
void Op_Conv_VEF_Face::ajouter_contribution (const DoubleTab & tab_transporte, Matrice_Morse & matrice_morse) const virtual
Reimplemented in Op_Conv_Muscl_New_VEF_Face, and Op_Conv_EF_VEF_P1NC_Stab.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VEF::facette_normales(), Elem_VEF_base::KEL(), Process::Kokkos_exit(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Elem_VEF_base::nb_facette(), Domaine_dis_base::nb_front_Cl(), Domaine_Cl_VEF::normales_facettes_Cl(), Front_VF::num_premiere_face(), Op_Conv_VEF_base::phi_u_transportant(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Objet_U::que_suis_je(), Domaine_VEF::rang_elem_non_std(), Domaine_VEF::type_elem(), Domaine_Cl_VEF::type_elem_Cl(), Champ_Inc_base::valeurs(), and Op_Conv_VEF_base::vitesse().
Referenced by Op_Conv_EF_VEF_P1NC_Stab::ajouter_contribution(), and contribuer_a_avec().
get_ordre()
void Op_Conv_VEF_Face::get_ordre (int & ord) const
References ordre_.
get_type_lim()
void Op_Conv_VEF_Face::get_type_lim (Motcle & typelim) const
References type_lim.
get_alpha()
void Op_Conv_VEF_Face::get_alpha (double & alp) const
References alpha_.
get_type_op()
void Op_Conv_VEF_Face::get_type_op (int & typeop) const
References type_op.
Member Data Documentation
type_lim
Motcle Op_Conv_VEF_Face::type_lim protected
Referenced by get_type_lim().
type_lim_int
type_lim_type Op_Conv_VEF_Face::type_lim_int = type_lim_minmod protected
Referenced by ajouter().
ordre_
int Op_Conv_VEF_Face::ordre_ = 1 protected
Referenced by ajouter(), and get_ordre().
alpha_
double Op_Conv_VEF_Face::alpha_ =1. protected
Referenced by get_alpha().
type_op
type_operateur Op_Conv_VEF_Face::type_op = amont protected
Referenced by ajouter(), and get_type_op().
LIMITEUR
double(* Op_Conv_VEF_Face::LIMITEUR) (double, double) = nullptr protected
traitement_pres_bord_
ArrOfInt Op_Conv_VEF_Face::traitement_pres_bord_ mutable protected
Referenced by ajouter().
est_une_face_de_dirichlet_
ArrOfInt Op_Conv_VEF_Face::est_une_face_de_dirichlet_ mutable protected
Referenced by ajouter().
type_elem_Cl_
ArrOfInt Op_Conv_VEF_Face::type_elem_Cl_ mutable protected
Referenced by completer(), and remplir_fluent().
gradient_face_
DoubleTab Op_Conv_VEF_Face::gradient_face_ mutable protected
Referenced by ajouter().
gradient_elem_
DoubleTab Op_Conv_VEF_Face::gradient_elem_ mutable protected
Referenced by ajouter().