CEA TRUST Platform: Matrice_Sym Class Reference
Matrice_Sym Class Reference abstract
Detailed Description
matrices symetriques. Cette classe est en fait une classe "interface" qui donne acces a des methodes de resolutions de systemes lineaires dont la matrice est symetrique: Gradient conjugue (preconditionne), solveur SSOR, precondtionneur polynomial. Cette classe ne contient pas de membre de donnee (hors mis ceux herites de Process) car elle sera utilisee par heritage multiple. Elle "accede" a la matrice via la methode de multiplication matrice-vecteur DoubleVect& multvect(const DoubleVect&, DoubleVect& resu) const qui est une methode abstraite.
See also
Matrice_Morse_Sym, Cette classe n'herite pas d'objet U car elle est utilisee par, heritage multiple avec d'autre classe heritant deja d'objet U., Classe abstraite
Constructor & Destructor Documentation
~Matrice_Sym()
virtual Matrice_Sym::~Matrice_Sym () inline virtual
Matrice_Sym()
Matrice_Sym::Matrice_Sym () inline
Member Function Documentation
get_est_definie()
int Matrice_Sym::get_est_definie () const
Referenced by Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Solv_Cholesky::Cholesky(), Solv_Externe::construit_matrice_morse_intermediaire(), Matrice_Morse_Sym::Matrice_Morse_Sym(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Matrice_Morse_Sym::operator=(), Precond_local::prepare_(), Precond_local::res_syst_loc_hybride(), and Precond_local::res_syst_loc_simple().
set_est_definie()
void Matrice_Sym::set_est_definie (int val)
Referenced by Assembleur_P_EF::assembler_mat(), Assembleur_P_EF::assembler_QC(), Assembleur_P_PolyMAC::assembler_QC(), Assembleur_P_VDF::assembler_QC(), Matrice_Bloc_Sym::BlocSymToMatMorseSym(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Equation_base::derivee_en_temps_inco(), Domaine_PolyMAC::init_m2solv(), Matrice_Morse_Sym::Matrice_Morse_Sym(), Assembleur_P_VEF::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_matrice(), Matrice_Morse_Sym::operator=(), Precond_local::prepare_(), Assembleur_P_VEF::remplir(), Precond_local::res_syst_loc_hybride(), and Precond_local::res_syst_loc_simple().
unsymmetrize_stencil()
void Matrice_Sym::unsymmetrize_stencil (const int nb_lines, const IntTab & symmetric_stencil, IntTab & stencil) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Matrice_Bloc_Sym::get_stencil(), and Matrice_Morse_Sym::get_stencil().
unsymmetrize_stencil_and_coefficients()
void Matrice_Sym::unsymmetrize_stencil_and_coefficients (const int nb_lines, const IntTab & symmetric_stencil, const ArrOfDouble & symmetric_coefficients, IntTab & stencil, ArrOfDouble & coefficients) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by Matrice_Bloc_Sym::get_stencil_and_coefficients(), and Matrice_Morse_Sym::get_stencil_and_coefficients().
ajouter_multTab_()
virtual DoubleTab& Matrice_Sym::ajouter_multTab_ (const DoubleTab & , DoubleTab &) const protected pure virtual
Implemented in Matrice_Bloc_Sym, Matrice_Morse_Sym, and Matrice_Morse_Diag.
ajouter_multvect_()
virtual DoubleVect& Matrice_Sym::ajouter_multvect_ (const DoubleVect & , DoubleVect &) const protected pure virtual
Implemented in Matrice_Morse_Diag, Matrice_Bloc_Sym, and Matrice_Morse_Sym.
ajouter_multvectT_()
virtual DoubleVect& Matrice_Sym::ajouter_multvectT_ (const DoubleVect & , DoubleVect &) const protected pure virtual
Implemented in Matrice_Bloc_Sym, Matrice_Morse_Sym, and Matrice_Morse_Diag.