CEA TRUST Platform: Domaine_VEF Class Reference
Domaine_VEF Class Reference
#include <Domaine_VEF.h>
Public Member Functions
void reordonner (Faces &) override
Public Member Functions inherited from Domaine_VF
void build_map_mc_Cmesh (const bool with_faces) override
void build_mc_dual_mesh () const
void build_mc_face_mesh () const
void construire_face_virt_pe_num ()
int elem_faces (int i, int j) const
int face_voisins (int num_face, int i) const
void init_dist_paroi_globale (const Conds_lim &conds_lim) override
int nb_faces_bord () const
int nb_faces_bord_tot () const
int nb_faces_internes () const
int nb_faces_tot () const
int nb_som_face () const
int premiere_face_bord () const
int premiere_face_int () const
Public Member Functions inherited from Domaine_dis_base
void associer_domaine (const Domaine &)
const Domaine & domaine () const
void ecrire_noms_bords (Sortie &) const
const Frontiere_dis_base & frontiere_dis (const Nom &) const
int nombre_de_sous_domaines_dis () const
int rang_frontiere (const Nom &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
    Classe instanciable qui derive de Domaine_VF.
    Cette classe contient les informations geometriques que demande la methode des Volumes Elements Finis (element de Crouzeix-Raviart)
    La classe porte un certain nombre d'informations concernant les faces
    Dans cet ensemble de faces on fait figurer aussi les faces du bord et des joints. Pour manipuler les faces on distingue 2 categories:
      - les faces non standard qui sont sur un joint, un bord ou qui sont
        internes tout en appartenant a un element du bord
      - les faces standard qui sont les faces internes n'appartenant pas
        a un element du bord
 Cette distinction correspond au traitement des conditions aux limites:les faces standard ne "voient pas" les conditions aux limites.
 L'ensemble des faces est numerote comme suit:
      - les faces qui sont sur un Domaine_joint apparaissent en premier
              (dans l'ordre du vecteur les_joints)
           - les faces qui sont sur un Domaine_bord apparaissent ensuite
          (dans l'ordre du vecteur les_bords)
          - les faces internes non standard apparaissent ensuite
      - les faces internes standard en dernier
 Finalement on trouve regroupees en premier toutes les faces non standard qui vont necessiter un traitement particulier
 On distingue deux types d'elements
      - les elements non standard : ils ont au moins une face de bord
      - les elements standard : ils n'ont pas de face de bord
 Les elements standard (resp. les elements non standard) ne sont pas ranges de maniere consecutive dans l'objet Domaine. On utilise le tableau
 rang_elem_non_std pour acceder de maniere selective a l'un ou l'autre des types d'elements
Member Function Documentation
discretiser()
void Domaine_VEF::discretiser () override virtual
Reimplemented from Domaine_dis_base.
References calculer_h_carre(), calculer_volumes_entrelaces(), Domaine_VF::creer_tableau_faces(), Domaine_32_64< _SIZE_ >::creer_tableau_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_VF::discretiser(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_normales_, Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), facette_normales(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), rang_elem_non_std(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), typer_elem(), and Domaine_VF::volumes().
discretiser_suite()
void Domaine_VEF::discretiser_suite (const VEF_discretisation & discr) virtual
References MD_Vector_composite::add_part(), MD_Vector::copy(), discretiser_arete(), Domaine_dis_base::domaine(), VEF_discretisation::get_alphaA(), VEF_discretisation::get_alphaE(), VEF_discretisation::get_alphaRT(), VEF_discretisation::get_alphaS(), VEF_discretisation::get_cl_pression_sommet_faible(), VEF_discretisation::get_modif_div_face_dirichlet(), VEF_discretisation::get_P1Bulle(), Domaine_VF::md_vector_aretes(), Domaine_32_64< _SIZE_ >::md_vector_elements(), and Domaine_32_64< _SIZE_ >::md_vector_sommets().
discretiser_arete()
void Domaine_VEF::discretiser_arete ()
References Domaine_32_64< _SIZE_ >::aretes_som(), Domaine_32_64< _SIZE_ >::creer_aretes(), Domaine_VF::creer_tableau_aretes(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MD_Vector_tools::echange_espace_virtuel(), Domaine_32_64< _SIZE_ >::elem_aretes(), MD_Vector_tools::EV_SOMME_ECHANGE, Domaine_32_64< _SIZE_ >::les_sommets(), Domaine_VF::md_vector_aretes_, Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Domaine_VF::volumes(), and Domaine_VF::xa_.
Referenced by discretiser_suite().
construire_ok_arete()
void Domaine_VEF::construire_ok_arete ()
References Domaine_32_64< _SIZE_ >::aretes_som(), EcrFicPartage::close(), TRUSTTab< _TYPE_, _SIZE_ >::copy(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Domaine_32_64< _SIZE_ >::get_renum_som_perio(), MD_Vector_base::get_sequential_items_flags(), Process::je_suis_maitre(), Domaine_32_64< _SIZE_ >::les_sommets(), Domaine_VF::md_vector_aretes(), MD_Vector_base::nb_items_seq_tot(), Domaine_dis_base::nb_som(), Objet_U::nom_du_cas(), EcrFicPartage::ouvrir(), ArrOfBit_32_64< _SIZE_ >::size_array(), EcrFicPartage::syncfile(), verifie_ok_arete(), and Domaine_VF::xa_.
Referenced by modifier_pour_Cl().
lecture_ok_arete()
int Domaine_VEF::lecture_ok_arete ()
References Octree_Double_32_64< _SIZE_ >::build_nodes(), Entree_Fichier_base::close(), Domaine_VF::creer_tableau_aretes(), Domaine_dis_base::domaine(), Domaine_VF::md_vector_aretes(), Objet_U::nom_du_cas(), Entree_Fichier_base::ouvrir(), Objet_U::precision_geom, Octree_Double_32_64< _SIZE_ >::search_elements_box(), Octree_Double_32_64< _SIZE_ >::search_nodes_close_to(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Domaine_VF::xa_.
Referenced by modifier_pour_Cl().
verifie_ok_arete()
void Domaine_VEF::verifie_ok_arete (int nombre_aretes_superflues_prevues_sur_le_dom) const
References Domaine_32_64< _SIZE_ >::aretes_som(), Domaine_dis_base::domaine(), Process::exit(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::get_renum_som_perio(), Process::is_sequential(), Process::je_suis_maitre(), Process::me(), Process::mp_sum(), Process::mp_sum_as_double(), Domaine_32_64< _SIZE_ >::nb_aretes(), Domaine_32_64< _SIZE_ >::nb_aretes_tot(), Domaine_dis_base::nb_som(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by construire_ok_arete().
construire_renum_arete_perio()
void Domaine_VEF::construire_renum_arete_perio (const Conds_lim & conds_lim)
References Debog::active(), Domaine_32_64< _SIZE_ >::aretes_som(), Domaine_VF::creer_tableau_aretes(), Periodique::direction_periodicite(), Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::elem_aretes(), Periodique::face_associee(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins_, Cond_lim_base::frontiere_dis(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Domaine_32_64< _SIZE_ >::get_renum_som_perio(), Domaine_32_64< _SIZE_ >::nb_aretes_tot(), Front_VF::nb_faces_tot(), Front_VF::num_face(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Debog::verifier_indices_items(), and Domaine_VF::xa().
Referenced by modifier_pour_Cl().
creer_tableau_p1bulle()
void Domaine_VEF::creer_tableau_p1bulle (Array_base & x, RESIZE_OPTIONS opt = RESIZE_OPTIONS::COPY_INIT) const virtual
References MD_Vector_tools::creer_tableau_distribue(), and md_vector_p1b().
swap()
void Domaine_VEF::swap (int fac1, int fac2, int nb_som_faces)
reordonner()
void Domaine_VEF::reordonner (Faces & les_faces) override virtual
Methode appelee par Domaine_VF::discretiser apres la creation des faces reelles.
On reordonne les faces de sorte a placer les faces "non standard" au debut de la liste des faces. Les faces non standard sont celles dont les volumes de controles sont modifies par les conditions aux limites.
Reimplemented from Domaine_VF.
References MD_Vector_tools::creer_md_vect_renum_auto(), Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_32_64< _SIZE_ >::nb_faces_frontiere(), Domaine_VF::rang_elem_non_std_, Domaine_VF::renumeroter(), and Faces_32_64< _SIZE_ >::voisin().
modifier_pour_Cl()
void Domaine_VEF::modifier_pour_Cl (const Conds_lim & conds_lim) override virtual
Implements Domaine_dis_base.
References Debog::active(), Domaine_VF::construire_num_fac_loc(), construire_ok_arete(), construire_renum_arete_perio(), Domaine_VF::creer_tableau_aretes(), Domaine_32_64< _SIZE_ >::creer_tableau_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Periodique::face_associee(), Domaine_VF::face_normales_, Domaine_VF::face_voisins_, Cond_lim_base::frontiere_dis(), get_alphaA(), get_alphaS(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Domaine_32_64< _SIZE_ >::get_renum_som_perio(), Process::Journal(), lecture_ok_arete(), Domaine_VF::marquer_faces_double_contrib(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_som(), Front_VF::num_face(), Front_VF::num_premiere_face(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Debog::verifier_getref(), Debog::verifier_indices_items(), Domaine_VF::volumes(), Domaine_VF::volumes_entrelaces_, Domaine_VF::xp_, and Domaine_VF::xv_.
typer_elem()
void Domaine_VEF::typer_elem (Domaine & domaine_geom) override virtual
Reimplemented from Domaine_VF.
References Process::exit(), and Domaine_32_64< _SIZE_ >::typer().
Referenced by discretiser().
calculer_volumes_entrelaces()
void Domaine_VEF::calculer_volumes_entrelaces ()
References Domaine_VF::creer_tableau_faces(), Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_voisins_, TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Domaine_VF::md_vector_faces(), Domaine_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), MD_Vector::non_nul(), Domaine_VF::premiere_face_int(), TRUSTVect< _TYPE_, _SIZE_ >::reset(), Domaine_VF::volumes(), and Domaine_VF::volumes_entrelaces_.
Referenced by discretiser().
calculer_h_carre()
void Domaine_VEF::calculer_h_carre ()
References Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Domaine_VF::face_surfaces(), Process::mp_min(), Process::mp_sum(), Domaine_dis_base::nb_elem(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::volumes().
Referenced by discretiser().
vecteur_face_facette()
DoubleTab & Domaine_VEF::vecteur_face_facette ()
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Elem_VEF_base::KEL(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_dis_base::nb_elem_tot(), Elem_VEF_base::nb_facette(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), type_elem(), Domaine_VF::xp(), and Domaine_VF::xv_.
type_elem()
const Elem_VEF_base & Domaine_VEF::type_elem () const inline
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_New_VEF_Face::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Domaine_Cl_VEF::associer(), Op_Conv_Muscl_New_VEF_Face::calculer_dt_stab(), Op_Conv_VEF_Face::remplir_fluent(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Domaine_Cl_VEF::remplir_type_elem_Cl(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), vecteur_face_facette(), and VEF_discretisation::vorticite().
nb_elem_Cl()
int Domaine_VEF::nb_elem_Cl () const inline
References Domaine_dis_base::nb_elem(), and Domaine_VF::nb_elem_std_.
nb_faces_joint()
int Domaine_VEF::nb_faces_joint () const inline
Referenced by EDO_Pression_th_VEF::calculer_grad().
nb_faces_std()
int Domaine_VEF::nb_faces_std () const inline
References Domaine_VF::nb_faces_std_.
nb_elem_std()
int Domaine_VEF::nb_elem_std () const inline
References Domaine_VF::nb_elem_std_.
premiere_face_std()
int Domaine_VEF::premiere_face_std () const inline
References Domaine_VF::nb_faces(), and Domaine_VF::nb_faces_std_.
Referenced by Terme_Source_Rappel_T_VEF_Face::ajouter(), Masse_VEF_P1NC::appliquer_impl(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_stab(), EDO_Pression_th_VEF::calculer_grad(), Op_Conv_VEF_base::calculer_pour_post(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), and Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet().
nb_faces_non_std()
int Domaine_VEF::nb_faces_non_std () const inline
References Domaine_VF::nb_faces(), and Domaine_VF::nb_faces_std_.
Referenced by Domaine_Cl_VEF::associer(), and Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl().
carre_pas_du_maillage()
double Domaine_VEF::carre_pas_du_maillage () const inline
Referenced by Op_Diff_P1NC_barprim::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), and Op_Diff_VEF_Face_Q1::calculer_dt_stab().
carre_pas_maille()
const DoubleVect & Domaine_VEF::carre_pas_maille () const inline
Referenced by Op_Dift_VEF_base::calculer_borne_locale(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_pour_post(), and Op_Dift_VEF_base::calculer_pour_post().
facette_normales() [1/2]
DoubleTab & Domaine_VEF::facette_normales () inline
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), discretiser(), and Op_Conv_VEF_Face::remplir_fluent().
facette_normales() [2/2]
const DoubleTab & Domaine_VEF::facette_normales () const inline
rang_elem_non_std() [1/2]
IntVect & Domaine_VEF::rang_elem_non_std () inline
References Domaine_VF::rang_elem_non_std_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Div_VEFP1B_Elem::ajouter_som(), Domaine_Cl_VEF::associer(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), Op_Conv_VEF_Face::completer(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), discretiser(), Op_Conv_VEF_Face::remplir_fluent(), Domaine_Cl_VEF::remplir_normales_facettes_Cl(), Domaine_Cl_VEF::remplir_type_elem_Cl(), and Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl().
rang_elem_non_std() [2/2]
const IntVect & Domaine_VEF::rang_elem_non_std () const inline
References Domaine_VF::rang_elem_non_std_.
oriente_normale()
int Domaine_VEF::oriente_normale (int face_opp, int elem2) const inline
References Domaine_VF::face_voisins().
Referenced by Champ_front_contact_VEF::calcul_grads_locaux(), Champ_Generique_Tparoi_VEF::get_champ(), Champ_front_tangentiel_VEF::initialiser(), Champ_front_fonc_gradient_VEF::mettre_a_jour(), Terme_Source_Qdm_lambdaup_VEF_Face::norme_H1(), Op_Diff_RotRot::vecteur_normal(), Op_Curl_VEFP1B::vecteur_normal(), and Op_Rot_VEFP1B::vecteur_normal().
volume_au_sommet()
double Domaine_VEF::volume_au_sommet (int som) const inline
volume_aux_sommets()
const DoubleVect & Domaine_VEF::volume_aux_sommets () const inline
Referenced by Op_Diff_VEFP1NCP1B_Face::calculer_gradient_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_CL(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_perio(), Op_Diff_VEFP1NCP1B_Face::coeff_matrice_som_symetrie(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som(), Op_Diff_VEFP1NCP1B_Face::gradient_som_CL(), EOS_Tools_VEF::secmembre_divU_Z(), and Op_Div_VEFP1B_Elem::volumique().
get_P1Bulle()
int Domaine_VEF::get_P1Bulle () const inline
get_alphaE()
int Domaine_VEF::get_alphaE () const inline
Referenced by Champ_P1_isoP1Bulle::affecter_(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Assembleur_P_VEFPreP1B::assembler_mat(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Champ_P1iP1B_implementation::filtrage(), Assembleur_P_VEFPreP1B::modifier_matrice(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_secmem_som(), Assembleur_P_VEFPreP1B::modifier_solution(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), EOS_Tools_VEF::secmembre_divU_Z(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_sommets(), and Op_Div_VEFP1B_Elem::volumique().
get_alphaS()
int Domaine_VEF::get_alphaS () const inline
Referenced by Champ_P1_isoP1Bulle::affecter_(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_elem(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Assembleur_P_VEFPreP1B::assembler_mat(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Champ_P1iP1B_implementation::filtrage(), Domaine_Cl_VEF::imposer_cond_lim(), Assembleur_P_VEFPreP1B::modifier_matrice(), modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), Champ_P1iP1B_implementation::remplir_coord_noeuds(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), EOS_Tools_VEF::secmembre_divU_Z(), Champ_P1iP1B_implementation::valeur_aux_elems(), Champ_P1iP1B_implementation::valeur_aux_sommets(), and Op_Div_VEFP1B_Elem::volumique().
get_alphaA()
int Domaine_VEF::get_alphaA () const inline
Referenced by Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Assembleur_P_VEFPreP1B::assembler_mat(), Assembleur_P_VEFPreP1B::modifier_matrice(), modifier_pour_Cl(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl(), EOS_Tools_VEF::secmembre_divU_Z(), and Op_Div_VEFP1B_Elem::volumique().
get_alphaRT()
int Domaine_VEF::get_alphaRT () const inline
get_modif_div_face_dirichlet()
int Domaine_VEF::get_modif_div_face_dirichlet () const inline
Referenced by Op_Div_VEFP1B_Elem::ajouter_som(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), and Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl().
get_cl_pression_sommet_faible()
int Domaine_VEF::get_cl_pression_sommet_faible () const inline
Referenced by Op_Div_VEFP1B_Elem::ajouter(), Assembleur_P_VEFPreP1B::assembler_mat(), Domaine_Cl_VEF::imposer_cond_lim(), and Assembleur_P_VEFPreP1B::modifier_matrice().
get_renum_arete_perio()
const ArrOfInt & Domaine_VEF::get_renum_arete_perio () const inline
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Assembleur_P_VEFPreP1B::modifier_secmem(), and Assembleur_P_VEFPreP1B::modifier_solution().
get_ok_arete()
const IntVect & Domaine_VEF::get_ok_arete () const inline
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), and Assembleur_P_VEFPreP1B::verifier_dirichlet().
get_volumes_aretes()
const DoubleVect & Domaine_VEF::get_volumes_aretes () const inline
Referenced by Op_Div_VEFP1B_Elem::volumique().
md_vector_p1b()
virtual const MD_Vector & Domaine_VEF::md_vector_p1b () const inline virtual
References MD_Vector::non_nul().
Referenced by creer_tableau_p1bulle(), Champ_Fonc_P1_isoP1Bulle::fixer_nb_valeurs_nodales(), and Champ_P1_isoP1Bulle::fixer_nb_valeurs_nodales().
numero_premier_element()
int Domaine_VEF::numero_premier_element () const inline
numero_premier_sommet()
int Domaine_VEF::numero_premier_sommet () const inline
References Domaine_dis_base::nb_elem_tot().
Referenced by Champ_P1_isoP1Bulle::affecter_(), Op_Div_VEFP1B_Elem::ajouter(), Op_Grad_VEF_P1B_Face::ajouter_som(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Dift_VEF_P1NCP1B_Face::calculer_divergence_som(), Op_Grad_VEF_P1B_Face::calculer_flux_bords(), Op_Dift_VEF_P1NCP1B_Face::calculer_gradient_som(), Domaine_Cl_VEF::imposer_cond_lim(), Assembleur_P_VEFPreP1B::modifier_secmem(), Assembleur_P_VEFPreP1B::modifier_solution(), Champ_P1_isoP1Bulle::norme_L2(), Champ_P1_isoP1Bulle::valeur_au_bord(), Champ_P1iP1B_implementation::valeur_aux_elems(), and Champ_P1iP1B_implementation::valeur_aux_sommets().
numero_premiere_arete()
int Domaine_VEF::numero_premiere_arete () const inline
References Domaine_dis_base::nb_elem_tot(), and Domaine_dis_base::nb_som_tot().
Referenced by Op_Div_VEFP1B_Elem::ajouter_aretes(), Op_Grad_VEF_P1B_Face::ajouter_aretes(), Assembleur_P_VEFPreP1B::modifier_secmem(), and Assembleur_P_VEFPreP1B::modifier_solution().
dist_face_elem0()
double Domaine_VEF::dist_face_elem0 (int num_face, int n0) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::dot(), Domaine_VF::face_normales_, Domaine_VF::face_surfaces(), Domaine_VF::xp_, and Domaine_VF::xv_.
dist_face_elem1()
double Domaine_VEF::dist_face_elem1 (int num_face, int n1) const inline override virtual
Reimplemented from Domaine_VF.
References Domaine_VF::dot(), Domaine_VF::face_normales_, Domaine_VF::face_surfaces(), Domaine_VF::xp_, and Domaine_VF::xv_.