CEA TRUST Platform: Op_Dift_VDF_Face_Axi_base Class Reference
Op_Dift_VDF_Face_Axi_base Class Reference abstract
#include <Op_Dift_VDF_Face_Axi_base.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
void contribuer_a_avec (const DoubleTab &inco, Matrice_Morse &matrice) const override
void contribuer_au_second_membre (DoubleTab &resu) const override
void dimensionner (Matrice_Morse &matrice) const override
void mettre_a_jour (double) override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Dift_VDF_Face_base
double calculer_dt_stab () const override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Diff_VDF_base
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
calculer_dt_stab()
double Op_Dift_VDF_Face_Axi_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Op_Dift_VDF_Face_base::calculer_dt_stab().
completer()
void Op_Dift_VDF_Face_Axi_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_VDF_base.
References associer_modele_turbulence(), Operateur_base::completer(), Champ_Face_VDF::dimensionner_tenseur_Grad(), MorEqn::equation(), Equation_base::get_modele(), Equation_base::inconnue(), and TRUST_Ref_Objet_U::valeur().
associer()
void Op_Dift_VDF_Face_Axi_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_transporte) override virtual
Implements Operateur_base.
References Domaine_VF::elem_faces(), elem_faces, Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), face_voisins, Domaine_VDF::orientation(), orientation, porosite, Domaine_VDF::Qdm(), Qdm, TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTVect< _TYPE_, _SIZE_ >::ref(), surface, Domaine_Cl_VDF::type_arete_bord(), type_arete_bord, Domaine_VF::volumes_entrelaces(), volumes_entrelaces, Domaine_VF::xp(), xp, Domaine_VF::xv(), and xv.
associer_modele_turbulence()
void Op_Dift_VDF_Face_Axi_base::associer_modele_turbulence (const Modele_turbulence_hyd_base & mod)
References associer_diffusivite_turbulente(), and associer_loipar().
Referenced by completer().
mettre_a_jour()
void Op_Dift_VDF_Face_Axi_base::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
References TRUSTTab< _TYPE_, _SIZE_ >::ref(), and tau_tan.
contribue_au_second_membre()
void Op_Dift_VDF_Face_Axi_base::contribue_au_second_membre (DoubleTab & resu) const
References MorEqn::equation(), Process::exit(), TypeAreteBordVDF::FLUIDE_FLUIDE, is_var(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), mettre_a_jour_var(), TypeAreteBordVDF::NAVIER_NAVIER, orientation, TypeAreteBordVDF::PAROI_FLUIDE, TypeAreteBordVDF::PAROI_PAROI, Qdm, Equation_base::schema_temps(), surface, tau_tan, Schema_Temps_base::temps_courant(), and type_arete_bord.
Referenced by contribuer_au_second_membre().
calculer()
DoubleTab & Op_Dift_VDF_Face_Axi_base::calculer (const DoubleTab & inco, DoubleTab & resu) const override virtual
calcule la contribution de la diffusion, la range dans resu
Reimplemented from Op_Diff_VDF_base.
contribuer_a_avec()
void Op_Dift_VDF_Face_Axi_base::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
contribuer_au_second_membre()
void Op_Dift_VDF_Face_Axi_base::contribuer_au_second_membre (DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Op_Dift_VDF_base.
References contribue_au_second_membre().
associer_loipar()
void Op_Dift_VDF_Face_Axi_base::associer_loipar (const Turbulence_paroi_base &) inline
Referenced by associer_modele_turbulence().
associer_diffusivite_turbulente()
void Op_Dift_VDF_Face_Axi_base::associer_diffusivite_turbulente (const Champ_Fonc_base & visc_turb) inline
References Op_Diff_Turbulent_base::associer_diffusivite_turbulente().
Referenced by associer_modele_turbulence().
dimensionner()
void Op_Dift_VDF_Face_Axi_base::dimensionner (Matrice_Morse & mat) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_VDF_Face::dimensionner().
modifier_pour_Cl()
void Op_Dift_VDF_Face_Axi_base::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_VDF_Face::modifier_pour_Cl().
OBS_PTR() [1/4]
Op_Dift_VDF_Face_Axi_base::OBS_PTR (Modele_turbulence_hyd_base) protected
OBS_PTR() [2/4]
Op_Dift_VDF_Face_Axi_base::OBS_PTR (Champ_Face_VDF) protected
OBS_PTR() [3/4]
Op_Dift_VDF_Face_Axi_base::OBS_PTR (Domaine_VDF) protected
OBS_PTR() [4/4]
Op_Dift_VDF_Face_Axi_base::OBS_PTR (Domaine_Cl_VDF) protected
mettre_a_jour_var()
virtual void Op_Dift_VDF_Face_Axi_base::mettre_a_jour_var (double) const protected pure virtual
Implemented in Op_Dift_VDF_Face_Axi.
Referenced by contribue_au_second_membre().
is_var()
virtual bool Op_Dift_VDF_Face_Axi_base::is_var () const protected pure virtual
Implemented in Op_Dift_VDF_Face_Axi.
Referenced by contribue_au_second_membre().
nu_()
virtual double Op_Dift_VDF_Face_Axi_base::nu_ (const int) const protected pure virtual
Implemented in Op_Dift_VDF_Face_Axi.
nu_mean_2_pts_()
virtual double Op_Dift_VDF_Face_Axi_base::nu_mean_2_pts_ (const int , const int) const protected pure virtual
Implemented in Op_Dift_VDF_Face_Axi.
nu_mean_4_pts_() [1/2]
virtual double Op_Dift_VDF_Face_Axi_base::nu_mean_4_pts_ (const int , const int) const protected pure virtual
Implemented in Op_Dift_VDF_Face_Axi.
nu_mean_4_pts_() [2/2]
virtual double Op_Dift_VDF_Face_Axi_base::nu_mean_4_pts_ (const int , const int , const int , const int) const protected pure virtual
Implemented in Op_Dift_VDF_Face_Axi.
Member Data Documentation
orientation
IntVect Op_Dift_VDF_Face_Axi_base::orientation protected
Referenced by associer(), and contribue_au_second_membre().
type_arete_bord
IntVect Op_Dift_VDF_Face_Axi_base::type_arete_bord protected
Referenced by associer(), and contribue_au_second_membre().
Qdm
IntTab Op_Dift_VDF_Face_Axi_base::Qdm protected
Referenced by associer(), and contribue_au_second_membre().
face_voisins
IntTab Op_Dift_VDF_Face_Axi_base::face_voisins protected
Referenced by associer(), and Op_Dift_VDF_Face_Axi::nu_mean_4_pts_().
elem_faces
IntTab Op_Dift_VDF_Face_Axi_base::elem_faces protected
Referenced by associer().
surface
DoubleVect Op_Dift_VDF_Face_Axi_base::surface protected
Referenced by associer(), and contribue_au_second_membre().
volumes_entrelaces
DoubleVect Op_Dift_VDF_Face_Axi_base::volumes_entrelaces protected
Referenced by associer().
porosite
DoubleVect Op_Dift_VDF_Face_Axi_base::porosite protected
Referenced by associer().
xp
DoubleTab Op_Dift_VDF_Face_Axi_base::xp protected
Referenced by associer().
xv
DoubleTab Op_Dift_VDF_Face_Axi_base::xv protected
Referenced by associer().
tau_tan
DoubleTab Op_Dift_VDF_Face_Axi_base::tau_tan protected
Referenced by contribue_au_second_membre(), and mettre_a_jour().