CEA TRUST Platform: Champ_P1NC Class Reference
Champ_P1NC Class Reference
#include <Champ_P1NC.h>
Public Member Functions
Champ_base & affecter_ (const Champ_base &) override
void mettre_a_jour (double temps) override
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &tab_valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Champ_P1NC_implementation
DoubleTab & valeur_aux_centres_de_gravite (const Domaine &, DoubleTab &valeurs) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
fixer_nb_valeurs_nodales()
int Champ_P1NC::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Reimplemented from Champ_Inc_base.
References Champ_Inc_base::creer_tableau_distribue(), domaine_vef(), Champ_P1NC_implementation::fixer_nb_valeurs_nodales(), and Domaine_VF::md_vector_faces().
mettre_a_jour()
void Champ_P1NC::mettre_a_jour (double un_temps) override virtual
Effectue une mise a jour en temps du champ inconnue.
WEC : Maintenant si on l'appelle 2 fois de suite avec le meme argument, la 2eme ne fait rien.
Parameters
(double temps) le nouveau temps
Reimplemented from Champ_Inc_base.
References Champ_P1NC_implementation::filtrer_L2_deja_appele_, and Champ_Inc_base::mettre_a_jour().
abortTimeStep()
void Champ_P1NC::abortTimeStep () override virtual
Reimplemented from Champ_base.
References Champ_P1NC_implementation::ch_som_.
calcul_y_plus()
void Champ_P1NC::calcul_y_plus (const Domaine_Cl_VEF & domaine_Cl_VEF, DoubleVect & y_plus) const
References Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), Domaine_VF::elem_faces(), MorEqn::equation(), Process::exit(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Equation_base::get_modele(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::local_min_vect(), Modele_turbulence_hyd_base::loi_paroi(), Equation_base::milieu(), Front_VF::nb_faces(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Domaine_dis_base::nb_front_Cl(), TRUST_Ref_Objet_U::non_nul(), Front_VF::num_premiere_face(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Turbulence_paroi_base::tab_d_plus(), Turbulence_paroi_base::use_shear(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), Fluide_base::viscosite_cinematique(), Domaine_VF::xp(), and Domaine_VF::xv().
calcul_y_plus_diphasique()
void Champ_P1NC::calcul_y_plus_diphasique (const Domaine_Cl_VEF & , DoubleVect &) const
calcul_grad_T()
void Champ_P1NC::calcul_grad_T (const Domaine_Cl_VEF & domaine_Cl_VEF, DoubleTab & grad_T) const
References domaine_vef(), and Champ_Inc_base::valeurs().
calcul_grad_U()
void Champ_P1NC::calcul_grad_U (const Domaine_Cl_VEF & domaine_Cl_VEF, DoubleTab & tab_grad_u) const
References Objet_U::dimension, domaine_vef(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), and Champ_Inc_base::valeurs().
calcul_h_conv()
void Champ_P1NC::calcul_h_conv (const Domaine_Cl_VEF & domaine_Cl_VEF, DoubleTab & h_conv, int temp_ref) const
References Milieu_base::capacite_calorifique(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_vef(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Operateur_base::flux_bords(), Process::je_suis_maitre(), Operateur::l_op_base(), Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Milieu_base::masse_volumique(), Equation_base::milieu(), Process::mp_sum(), Field_base::nb_comp(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Equation_base::operateur(), Equation_base::schema_temps(), Sortie_Fichier_base::setf(), Schema_Temps_base::temps_courant(), Champ_Don_base::valeurs(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
compo_normale_sortante()
int Champ_P1NC::compo_normale_sortante (int num_face) const
References domaine_vef(), Domaine_VF::face_normales(), Field_base::nb_comp(), and Champ_Inc_base::valeurs().
trace()
DoubleTab & Champ_P1NC::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Reimplemented from Champ_Inc_base.
References Champ_P1NC_implementation::trace(), and Champ_Inc_base::valeurs().
cal_rot_ordre1()
void Champ_P1NC::cal_rot_ordre1 (DoubleTab & tab_vorticite) const
References Objet_U::dimension, domaine_vef(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), gradient(), Domaine_dis_base::nb_elem(), and Domaine_dis_base::nb_elem_tot().
Referenced by Op_Conv_Vort_VEF_Face::ajouter(), and Rotationnel_Champ_P1NC::me_calculer().
gradient()
void Champ_P1NC::gradient (DoubleTab & gradient_elem) const
References Champ_Inc_base::domaine_Cl_dis(), domaine_vef(), MorEqn::equation(), and Champ_Inc_base::valeurs().
Referenced by cal_rot_ordre1().
imprime()
int Champ_P1NC::imprime (Sortie & os, int ncomp) const override virtual
Reimplemented from Champ_Inc_base.
References Champ_P1NC_implementation::imprime_P1NC().
calcul_critere_Q()
void Champ_P1NC::calcul_critere_Q (DoubleVect & tab_Critere_Q) const
References calcul_gradient(), Objet_U::dimension, Champ_Inc_base::domaine_Cl_dis(), domaine_vef(), MorEqn::equation(), Domaine_dis_base::nb_elem(), Domaine_dis_base::nb_elem_tot(), and Champ_Inc_base::valeurs().
Referenced by Critere_Q_Champ_P1NC::me_calculer().
norme_L2()
double Champ_P1NC::norme_L2 (const Domaine & dom) const virtual
References domaine_vef(), filtrer_L2(), norme_L2(), and Champ_Inc_base::valeurs().
Referenced by norme_L2(), and norme_L2_H1().
affecter_()
Champ_base & Champ_P1NC::affecter_ (const Champ_base & ch) override virtual
Affectation d'un OWN_PTR(Champ_base) generique (Champ_base) dans un champ inconnue.
Parameters
(Champ_base& ch) le champ partie droite de l'affectation
Returns
(Champ_base&) le resultat de l'affectation (*this)
Reimplemented from Champ_Inc_base.
References Champ_Inc_base::affecter_(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Champ_Inc_base::domaine(), Domaine_VF::face_sommets(), Field_base::nb_compo_, Domaine_VF::nb_faces(), remplir_coord_noeuds(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_base::valeur_aux(), and Champ_Inc_base::valeurs().
verifie_valeurs_cl()
void Champ_P1NC::verifie_valeurs_cl () override virtual
Reimplemented from Champ_Inc_base.
References Equation_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Periodique::face_associee(), Cond_lim_base::frontiere_dis(), Domaine_Cl_dis_base::les_conditions_limites(), Field_base::nb_comp(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Champ_Inc_base::valeurs().
calcul_S_barre()
DoubleVect & Champ_P1NC::calcul_S_barre (const DoubleTab & la_vitesse, DoubleVect & SMA_barre, const Domaine_Cl_VEF & domaine_Cl_VEF) static
References calcul_gradient(), Objet_U::dimension, Domaine_Cl_VEF::domaine_vef(), Domaine_dis_base::nb_elem(), and Domaine_dis_base::nb_elem_tot().
Referenced by Modele_turbulence_hyd_LES_Smago_VEF::calculer_S_barre().
calcul_gradient()
DoubleTab & Champ_P1NC::calcul_gradient (const DoubleTab & champ, DoubleTab & gij, const Domaine_Cl_VEF & domaine_Cl_VEF) static
References Domaine_Cl_VEF::domaine_vef().
Referenced by Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Grad_P1NC_to_P0::ajouter(), Op_Diff_VEF_Face::ajouter_cas_vectoriel(), calcul_critere_Q(), calcul_S_barre(), Champ_Ostwald_VEF::calculer_dscald(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_Sij2(), Modele_turbulence_hyd_LES_Wale_VEF::calculer_viscosite_turbulente(), and Op_Dift_VEF_Face::contribuer_au_second_membre().
calcul_duidxj_paroi()
DoubleTab & Champ_P1NC::calcul_duidxj_paroi (DoubleTab & tab_gij, const DoubleTab & tab_nu, const DoubleTab & tab_nu_turb, const DoubleTab & tab_tau_tan, const Domaine_Cl_VEF & domaine_Cl_VEF) static
References Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_Cl_VEF::domaine_vef(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Milieu_base::porosite_face().
Referenced by Op_Dift_VEF_Face::contribuer_au_second_membre().
norme_H1()
double Champ_P1NC::norme_H1 (const Domaine & dom) const virtual
References Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), Domaine_VF::elem_faces(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Field_base::nb_comp(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_faces_elem(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
Referenced by norme_L2_H1().
norme_L2_H1()
double Champ_P1NC::norme_L2_H1 (const Domaine & dom) const virtual
References MorEqn::equation(), norme_H1(), norme_L2(), Schema_Temps_base::pas_de_temps(), and Equation_base::schema_temps().
calculer_integrale_volumique()
double Champ_P1NC::calculer_integrale_volumique (const Domaine_VEF & domaine, const DoubleVect & v, Ok_Perio ok) static
References Champ_Inc_base::domaine(), Process::exit(), and TRUSTVect< _TYPE_, _SIZE_ >::line_size().
Referenced by EDO_Pression_th_VEF::masse_totale(), EDO_Pression_th_VEF::masse_totale(), EOS_Tools_VEF::moyenne_vol(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), and EDO_Pression_th_VEF_Gaz_Parfait::resoudre().
domaine_vef()
const Domaine_VEF & Champ_P1NC::domaine_vef () const inline override virtual
Implements Champ_P1NC_implementation.
Referenced by cal_rot_ordre1(), calcul_critere_Q(), calcul_grad_T(), calcul_grad_U(), calcul_h_conv(), calcul_y_plus(), compo_normale_sortante(), Champ_P1NC_implementation::filtrer_L2(), fixer_nb_valeurs_nodales(), gradient(), norme_H1(), and norme_L2().
valeur_a_elem()
DoubleVect & Champ_P1NC::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_a_elem().
valeur_a_elem_compo()
double Champ_P1NC::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_a_elem_compo().
valeur_a_sommet_compo()
double Champ_P1NC::valeur_a_sommet_compo (int sommet, int le_poly, int compo) const inline override virtual
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_a_sommet_compo().
valeur_aux_centres_de_gravite()
DoubleTab & Champ_P1NC::valeur_aux_centres_de_gravite (const Domaine & dom, DoubleTab & valeurs) const inline override virtual
Cette methode, generique mais lente (calcul des centres de gravite, remplissage les_poly, utilisation des fonctions de forme dans le Champ discretise) peut etre surchargee par le champ dicretise pour une implementation beaucoup plus rapide.
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_aux_centres_de_gravite().
valeur_aux_elems()
DoubleTab & Champ_P1NC::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_P1NC::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_aux_elems_compo().
valeur_aux_elems_smooth()
DoubleTab & Champ_P1NC::valeur_aux_elems_smooth (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & tab_valeurs) inline override virtual
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_aux_elems_smooth().
valeur_aux_elems_compo_smooth()
DoubleVect & Champ_P1NC::valeur_aux_elems_compo_smooth (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & tab_valeurs, int ncomp) inline override virtual
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_aux_elems_compo_smooth().
valeur_aux_sommets()
DoubleTab & Champ_P1NC::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_P1NC::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const inline override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
References Champ_P1NC_implementation::valeur_aux_sommets_compo().
remplir_coord_noeuds()
DoubleTab & Champ_P1NC::remplir_coord_noeuds (DoubleTab & positions) const inline override virtual
Implements Champ_Inc_base.
References Champ_P1NC_implementation::remplir_coord_noeuds().
Referenced by affecter_().
remplir_coord_noeuds_et_polys()
int Champ_P1NC::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN Methode a surcharger.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented from Champ_Inc_base.
References Champ_P1NC_implementation::remplir_coord_noeuds_et_polys().
filtrer_L2()
void Champ_P1NC::filtrer_L2 (DoubleTab & x) const inline
References Champ_P1NC_implementation::filtrer_L2().
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), Op_Diff_P1NC_barprim::calculer(), and norme_L2().
filtrer_H1()
void Champ_P1NC::filtrer_H1 (DoubleTab & x) const inline
References Champ_P1NC_implementation::filtrer_H1().
filtrer_resu()
void Champ_P1NC::filtrer_resu (DoubleTab & x) const inline
References Champ_P1NC_implementation::filtrer_resu().
Referenced by Op_Conv_EF_VEF_P1NC::ajouter(), and Op_Diff_P1NC_barprim::calculer().