CEA TRUST Platform: Correlation_base Class Reference
Correlation_base Class Reference
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
mettre_a_jour()
virtual void Correlation_base::mettre_a_jour (double temps) inline virtual
Reimplemented in Loi_paroi_base.
completer()
virtual void Correlation_base::completer () inline virtual
Reimplemented in Loi_paroi_base, Vitesse_derive_Forces, Frottement_interfacial_Tomiyama, Frottement_interfacial_Ishii_Zuber, Frottement_interfacial_bulles_constant, Flux_interfacial_Zeitoun, Flux_interfacial_Wolfert_composant, Flux_interfacial_Wolfert, Flux_interfacial_Ranz_Marshall, Flux_interfacial_Kim_Park, and Flux_interfacial_Chen_Mayinger.
associer_pb()
void Correlation_base::associer_pb (const Probleme_base & pb)
Referenced by typer_lire_correlation().
typer_lire_correlation()
void Correlation_base::typer_lire_correlation (OWN_PTR(Correlation_base)& cor, const Probleme_base & pb, const Nom & type, Entree & is) static
References associer_pb().
Referenced by Probleme_base::lire_correlations().
creer_champ()
void Correlation_base::creer_champ (const Motcle & motlu) inline override virtual
Implements Champs_compris_interface.
get_champ()
const Champ_base& Correlation_base::get_champ (const Motcle & nom) const inline override virtual
Implements Champs_compris_interface.
Reimplemented in Gravite_Multiphase, Diametre_bulles_musig, Diametre_bulles_constant, and Diametre_bulles_champ.
References Nom::getString().
get_noms_champs_postraitables()
void Correlation_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const inline override virtual
Implements Champs_compris_interface.
has_champ() [1/2]
bool Correlation_base::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
has_champ() [2/2]
bool Correlation_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
Reimplemented in Gravite_Multiphase, Diametre_bulles_musig, Diametre_bulles_constant, and Diametre_bulles_champ.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
OBS_PTR()
Correlation_base::OBS_PTR (Probleme_base) protected
Member Data Documentation
champs_compris_
Champs_compris Correlation_base::champs_compris_ protected
Referenced by Diametre_bulles_champ::get_champ(), Diametre_bulles_constant::get_champ(), Diametre_bulles_musig::get_champ(), Gravite_Multiphase::get_champ(), has_champ(), Diametre_bulles_champ::has_champ(), Diametre_bulles_constant::has_champ(), Diametre_bulles_musig::has_champ(), and Gravite_Multiphase::has_champ().