CEA TRUST Platform: Probleme_Couple Class Reference
Probleme_Couple Class Reference
Public Member Functions
void ajouter (Probleme_base &)
int associer_ (Objet_U &) override
virtual void associer_sch_tps_base (Schema_Temps_base &)
double computeTimeStep (bool &stop) const override
virtual void discretiser (Discretisation_base &)
void initialize () override
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
virtual Schema_Temps_base & schema_temps ()
virtual const Schema_Temps_base & schema_temps () const
bool updateGivenFields () override
Public Member Functions inherited from Couplage_U
void abortTimeStep () override
double futureTime () const override
void getInputFieldsNames (Noms &noms) const override
bool isStationary () const override
int postraiter (int force=1) override
double presentTime () const override
void resetTime (double t) override
void terminate () override
void validateTimeStep () override
Public Member Functions inherited from Probleme_U
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual bool run ()
virtual bool runUntil (double time)
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Il s'agit d'un Couplage_U particulier.
Le Probleme_Couple ne couple que des Probleme_base, tous
associes au meme schema en temps.
Il possede son propre mecanisme d'echange de champs par "raccords".
Les problemes sont groupes. Chaque groupe fait un iteration, puis les
nouveaux champs sont disponibles pour les groupes suivants. A l'interieur
d'un groupe, ce sont les anciens champs qui sont echanges.
See also
Probleme_base Probleme
Member Function Documentation
initTimeStep()
bool Probleme_Couple::initTimeStep (double dt) override virtual
This method allocates and initializes the unknown and given fields for the future time step.
The value of the interval is imposed through the parameter dt. In case of error, returns false.
Parameters
(double dt) the time interval to allocate
Returns
(bool) true=OK, false=error, not able to tackle this dt
Exceptions
WrongContext,WrongArgument
Reimplemented from Couplage_U.
References Couplage_U::initTimeStep().
computeTimeStep()
double Probleme_Couple::computeTimeStep (bool & stop) const override virtual
Compute the value the Problem would like for the next time step.
This value will not necessarily be used at the call of initTimeStep, but it is a hint. This method may use all the internal state of the Problem.
Parameters
(stop) Does the Problem want to stop ?
Returns
(double) The desired time step
Exceptions
WrongContext
Reimplemented from Probleme_U.
References Probleme_U::computeTimeStep(), Couplage_U::nb_problemes(), and Couplage_U::probleme().
solveTimeStep()
bool Probleme_Couple::solveTimeStep () override virtual
pour recodage eventuel et appel unifie en python
Reimplemented from Probleme_U.
References Schema_Temps_base::facteur_securite_pas(), Schema_Euler_Implicite::faire_un_pas_de_temps_pb_couple(), Couplage_U::nb_problemes(), Couplage_U::probleme(), Schema_Temps_base::residu(), schema_temps(), Probleme_U::solveTimeStep(), and Schema_Temps_base::stationnaire_atteint().
iterateTimeStep()
bool Probleme_Couple::iterateTimeStep (bool & converged) override virtual
In the case solveTimeStep uses an iterative process, this method executes a single iteration.
It is thus possible to modify the given fields between iterations. converged is set to true if the process has converged, ie if the unknown fields are solution to the problem on the next time step. Otherwise converged is set to false. The return value indicates if the convergence process behaves normally. If false, the Problem wishes to abort the time step resolution.
Parameters
(bool& converged) It is a return value : true if the process has converged, false otherwise.
Returns
(bool) true=OK, false=unable to converge
Exceptions
WrongContext
Reimplemented from Couplage_U.
References groupes, Probleme_U::iterateTimeStep(), Couplage_U::nb_problemes(), Couplage_U::probleme(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Probleme_U::updateGivenFields().
updateGivenFields()
bool Probleme_Couple::updateGivenFields () override virtual
ATTENTION :
Rentre ici tout ce qui ne correspond pas a l'API normale de Problem.
Actuellement on y met a jour les CLs et les termes sources, sachant que certains vont chercher eux-memes des informations dans les problemes voisins...
Programme de travail : tout ce qui est dans cette methode doit etre rendu independant de l'exterieur, et peut du coup rejoindre initTimeStep. Le reste passe dans l'interface d'echange de champs. Ce travail sera fini quand updateGivenFields sera vide et supprime !
Returns
(true=OK, false=error)
Reimplemented from Couplage_U.
ajouter()
void Probleme_Couple::ajouter (Probleme_base & pb)
Ajoute un probleme a la liste des problemes couples.
Met en place la reference du probleme vers this. Verifie que l'ordre conduction, thHyd est respecte.
Parameters
(Probleme_base& pb) le probleme a ajouter au couplage
References Couplage_U::addProblem(), Probleme_base::associer_pb_couple(), Process::exit(), Probleme_U::le_nom(), Couplage_U::nb_problemes(), Nom::prefix(), Couplage_U::probleme(), and Objet_U::que_suis_je().
Referenced by associer_().
associer_()
int Probleme_Couple::associer_ (Objet_U & ob) override virtual
Surcharge Objet_U::associer_(Objet_U&) Associe un objet au probleme couple, en verifiant le type.
dynamiquement. L'objet peut-etre:
un schema en temps (Schema_Temps_base), et on l'associe aux problemes
un probleme (Probleme_base), on l'ajoute a la liste
Parameters
(Objet_U& ob) l'objet a associer
Returns
(int) 1 si l'association a reussie 0 sinon
Exceptions
l'objet n'est pas d'un type attendu
Reimplemented from Objet_U.
Reimplemented in Pb_Couple_Optimisation_IBM.
References ajouter(), and associer_sch_tps_base().
Referenced by Pb_Couple_Optimisation_IBM::associer_().
associer_sch_tps_base()
void Probleme_Couple::associer_sch_tps_base (Schema_Temps_base & sch) virtual
Associe une copie du schema en temps a chaque probleme du Probleme couple.
Parameters
(Schema_Temps_base& sch) le schema en temps a associer
References Probleme_base::associer_sch_tps_base(), Couplage_U::nb_problemes(), Couplage_U::probleme(), Schema_Temps_base::schema_impr(), and Probleme_base::schema_temps().
Referenced by associer_().
schema_temps() [1/2]
const Schema_Temps_base & Probleme_Couple::schema_temps () const virtual
Renvoie le schema en temps associe aux problemes couples.
(version const)
Returns
(Schema_Temps_base&) le schema en temps associe
References Process::exit(), Probleme_U::le_nom(), Couplage_U::nb_problemes(), Couplage_U::probleme(), and Probleme_base::schema_temps().
Referenced by Discretiser::interpreter(), and solveTimeStep().
schema_temps() [2/2]
Schema_Temps_base & Probleme_Couple::schema_temps () virtual
Renvoie le schema en temps associe aux problemes couples.
Returns
(Schema_Temps_base&) le schema en temps associe
References Process::exit(), Probleme_U::le_nom(), Couplage_U::nb_problemes(), Couplage_U::probleme(), and Probleme_base::schema_temps().
discretiser()
void Probleme_Couple::discretiser (Discretisation_base & dis) virtual
Associe une discretisation a tous les problemes du probleme couple.
Appelle Probleme_Base::discretiser(const Discretisation_base&) sur chacun des problemes du probleme couple. voir Probleme_Base::discretiser(const Discretisation_base&)
Parameters
(Discretisation_base& dis) une discretisation pour tous les problemes
References Probleme_base::discretiser(), Probleme_U::le_nom(), Couplage_U::nb_problemes(), and Couplage_U::probleme().
Referenced by Discretiser::interpreter().
mettre_a_jour_modele_rayo()
void Probleme_Couple::mettre_a_jour_modele_rayo (double temps) inline virtual
References Process::exit().
initialize()
void Probleme_Couple::initialize () override virtual
This method is called once at the beginning, before any other one of the interface Problem.
Exceptions
WrongContext
Reimplemented from Couplage_U.
Reimplemented in Pb_Couple_Optimisation_IBM.
References Couplage_U::initialize(), Couplage_U::nb_problemes(), Couplage_U::probleme(), Schema_Temps_base::schema_impr(), and Probleme_base::schema_temps().
Referenced by Pb_Couple_Optimisation_IBM::initialize().
sauver()
void Probleme_Couple::sauver () const override virtual
Sauvegarder l'etat du probleme sur disque.
Reimplemented from Couplage_U.
References Ecrire_YAML::add_pb_base(), Probleme_base::checkpoint_filename(), Probleme_base::checkpoint_format(), Process::exit(), Nom::getString(), TRUST_2_PDI::init(), TRUST_2_PDI::is_PDI_initialized(), Probleme_U::le_nom(), Couplage_U::nb_problemes(), Couplage_U::probleme(), Ecrire_YAML::write_checkpoint_file(), and Probleme_base::yaml_filename().
VECT()
Probleme_Couple::VECT (OWN_PTR(Schema_Temps_base)) protected
Member Data Documentation
groupes
ArrOfInt Probleme_Couple::groupes protected
Referenced by iterateTimeStep().