CEA TRUST Platform: Traitement_particulier_NS_Profils_VDF Class Reference
Traitement_particulier_NS_Profils_VDF Class Reference
#include <Traitement_particulier_NS_Profils_VDF.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
for computations which have a periodic BC (ie homogeneous direction)
and on which we want profiles in a specific direction and position :
    + mean velocity profiles
    + fluctuations
See also
Navier_Stokes_Turbulent, Traitement_particulier_base, Traitement_particulier_VDF
Member Function Documentation
post_traitement_particulier()
void Traitement_particulier_NS_Profils_VDF::post_traitement_particulier () override virtual
Implements Traitement_particulier_NS_Profils.
References calculer_integrale_temporelle(), calculer_moyenne_spatiale_nut(), calculer_moyenne_spatiale_uv(), calculer_moyenne_spatiale_vitesse(), compt_uv_m, compt_uv_p, compt_x_m, compt_x_p, compt_y_m, compt_y_p, compt_z_m, compt_z_p, corresp_u_m, corresp_u_p, corresp_uv_m, corresp_uv_p, corresp_v_m, corresp_v_p, corresp_w_m, corresp_w_p, delta_Um, delta_Up, delta_UVm, delta_UVp, delta_Vm, delta_Vp, delta_Wm, delta_Wp, Traitement_particulier_NS_Profils::dt_post_inst, Traitement_particulier_NS_Profils::dt_post_stat, ecriture_fichiers_moy_spat(), ecriture_fichiers_moy_spat_1col(), ecriture_fichiers_moy_temp(), ecriture_fichiers_moy_temp_1col(), Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Traitement_particulier_NS_Profils::nu_t_temp, Traitement_particulier_NS_Profils::Nuv, Traitement_particulier_NS_Profils::Nxy, Traitement_particulier_NS_Profils::Nyy, Traitement_particulier_NS_Profils::Nzy, Traitement_particulier_NS_Profils::oui_profil_nu_t, Traitement_particulier_NS_Profils::oui_repr, Traitement_particulier_NS_Profils::oui_stat, Traitement_particulier_NS_Profils::oui_u_inst, Traitement_particulier_NS_Profils::temps_deb, Traitement_particulier_NS_Profils::temps_fin, Traitement_particulier_NS_Profils::u2_moy_temp, Traitement_particulier_NS_Profils::u3_moy_temp, Traitement_particulier_NS_Profils::u4_moy_temp, Traitement_particulier_NS_Profils::u_moy_temp_x, Traitement_particulier_NS_Profils::u_moy_temp_y, Traitement_particulier_NS_Profils::u_moy_temp_z, Traitement_particulier_NS_Profils::uv_moy_temp, Traitement_particulier_NS_Profils::v2_moy_temp, Traitement_particulier_NS_Profils::v3_moy_temp, Traitement_particulier_NS_Profils::v4_moy_temp, Traitement_particulier_NS_Profils::w2_moy_temp, Traitement_particulier_NS_Profils::w3_moy_temp, Traitement_particulier_NS_Profils::w4_moy_temp, xUm, xUp, xUVm, xUVp, xVm, xVp, xWm, xWp, Yu_m, Yuv_m, Yv_m, and Yw_m.
Referenced by Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier().
lire() [1/2]
Entree & Traitement_particulier_NS_Profils_VDF::lire (const Motcle & motlu, Entree & is) override virtual
Implements Traitement_particulier_NS_Profils.
References Process::exit(), and Traitement_particulier_NS_Profils::Nap.
Referenced by Traitement_particulier_NS_Profils_thermo_VDF::lire(), and Traitement_particulier_NS_Profils_thermo_VDF::lire().
lire() [2/2]
Entree & Traitement_particulier_NS_Profils_VDF::lire (Entree & is) override virtual
Reimplemented from Traitement_particulier_NS_Profils.
References Traitement_particulier_NS_Profils::lire().
init_calcul_moyenne()
void Traitement_particulier_NS_Profils_VDF::init_calcul_moyenne () override protected virtual
Implements Traitement_particulier_NS_Profils.
References compt_uv_m, compt_uv_p, compt_x_m, compt_x_p, compt_y_m, compt_y_p, compt_z_m, compt_z_p, corresp_u_m, corresp_u_p, corresp_uv_m, corresp_uv_p, corresp_v_m, corresp_v_p, corresp_w_m, corresp_w_p, delta_Um, delta_Up, delta_UVm, delta_UVp, delta_Vm, delta_Vp, delta_Wm, delta_Wp, Traitement_particulier_NS_Profils::dir_profil, Domaine_dis_base::domaine(), Process::exit(), Traitement_particulier_NS_Profils::homo_dir, Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_VF::nb_faces(), Traitement_particulier_NS_Profils::Nuv, Traitement_particulier_NS_Profils::Nxy, Traitement_particulier_NS_Profils::Nyy, Traitement_particulier_NS_Profils::Nzy, Domaine_VDF::orientation(), Traitement_particulier_NS_Profils::positions, TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Domaine_VF::xp(), xUm, xUp, xUVm, xUVp, Domaine_VF::xv(), xVm, xVp, xWm, xWp, Yu_m, Yu_p, Yuv_m, Yuv_p, Yv_m, Yv_p, Yw_m, and Yw_p.
Referenced by Traitement_particulier_NS_Profils_thermo_VDF::init_calcul_moyenne(), and Traitement_particulier_NS_Profils_thermo_VDF::preparer_calcul_particulier().
calculer_moyenne_spatiale_vitesse()
void Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_vitesse (DoubleTab & u_moy, DoubleTab & u_moy_2, DoubleTab & u_moy_3, DoubleTab & u_moy_4, const IntTab & corresp, const IntTab & compt, const IntVect & NN, const int ori, const DoubleTab & xU) protected
References Traitement_particulier_NS_Profils::dir_profil, Process::je_suis_maitre(), Process::me(), Traitement_particulier_NS_Profils::n_probes, Domaine_VF::nb_faces(), Process::nproc(), Domaine_VDF::orientation(), and Domaine_VF::xv().
Referenced by post_traitement_particulier().
calculer_moyenne_spatiale_uv()
void Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_uv (DoubleTab & uv_moy, const IntTab & corresp, const IntTab & compt, const IntVect & NN, const DoubleTab & xUV) protected
References Objet_U::dimension, Traitement_particulier_NS_Profils::dir_profil, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Process::je_suis_maitre(), Process::me(), Traitement_particulier_NS_Profils::n_probes, Traitement_particulier_NS_Profils::Nap, Domaine_32_64< _SIZE_ >::nb_elem(), Process::nproc(), and Domaine_VF::xp().
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_spat()
void Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat (const DoubleTab & umoy_m, const DoubleTab & umoy_2_m, const DoubleTab & umoy_3_m, const DoubleTab & umoy_4_m, const DoubleTab & umoy_p, const DoubleTab & umoy_2_p, const DoubleTab & umoy_3_p, const DoubleTab & umoy_4_p, const DoubleVect & delta_m, const DoubleVect & delta_p, const IntVect & NN, const DoubleTab & Y, const int ori) protected
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, Sortie_Fichier_base::flush(), Process::je_suis_maitre(), Traitement_particulier_NS_Profils::n_probes, and Traitement_particulier_NS_Profils::positions.
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_spat_1col()
void Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_spat_1col (const DoubleTab & umoy_m, const DoubleTab & umoy_p, const DoubleTab & Y, const DoubleVect & delta_m, const DoubleVect & delta_p, const IntVect & NN, const int ori) protected
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, Sortie_Fichier_base::flush(), Process::je_suis_maitre(), Traitement_particulier_NS_Profils::n_probes, and Traitement_particulier_NS_Profils::positions.
Referenced by post_traitement_particulier().
calculer_moyenne_spatiale_nut()
void Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut (DoubleTab & u_moy, const IntTab & corresp, const IntTab & compt, const IntVect & tab_Nuv, const DoubleTab & xUV) protected
References Traitement_particulier_NS_Profils::dir_profil, Domaine_dis_base::domaine(), Process::je_suis_maitre(), Process::me(), Traitement_particulier_NS_Profils::n_probes, Domaine_32_64< _SIZE_ >::nb_elem(), Process::nproc(), TRUST_Ref_Objet_U::valeur(), Champ_Don_base::valeurs(), Modele_turbulence_hyd_base::viscosite_turbulente(), and Domaine_VF::xp().
Referenced by post_traitement_particulier().
calculer_integrale_temporelle()
void Traitement_particulier_NS_Profils_VDF::calculer_integrale_temporelle (DoubleTab & u_moy_temp, DoubleTab & umoy_m, DoubleTab & umoy_p, const DoubleVect & delta_m, const DoubleVect & delta_p) protected
References TRUSTVect< _TYPE_, _SIZE_ >::ajoute_sans_ech_esp_virt(), Process::je_suis_maitre(), Traitement_particulier_NS_Profils::n_probes, and Traitement_particulier_NS_Profils::Nap.
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_temp()
void Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp (const DoubleTab & umoy, const DoubleTab & umoy_2, const DoubleTab & umoy_3, const DoubleTab & umoy_4, const DoubleTab & Y, const IntVect & NN, const int ori, const double dt) protected
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, Sortie_Fichier_base::flush(), Process::je_suis_maitre(), Traitement_particulier_NS_Profils::n_probes, and Traitement_particulier_NS_Profils::positions.
Referenced by post_traitement_particulier().
ecriture_fichiers_moy_temp_1col()
void Traitement_particulier_NS_Profils_VDF::ecriture_fichiers_moy_temp_1col (const DoubleTab & umoy, const DoubleTab & Y, const IntVect & NN, const int ori, const double dt) protected
References Sortie_Fichier_base::close(), Traitement_particulier_NS_Profils::dir_profil, Sortie_Fichier_base::flush(), Process::je_suis_maitre(), Traitement_particulier_NS_Profils::n_probes, and Traitement_particulier_NS_Profils::positions.
Referenced by post_traitement_particulier().
Member Data Documentation
Yu_m
DoubleTab Traitement_particulier_NS_Profils_VDF::Yu_m protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
Yv_m
DoubleTab Traitement_particulier_NS_Profils_VDF::Yv_m protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
Yw_m
DoubleTab Traitement_particulier_NS_Profils_VDF::Yw_m protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
Yuv_m
DoubleTab Traitement_particulier_NS_Profils_VDF::Yuv_m protected
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
Yu_p
DoubleTab Traitement_particulier_NS_Profils_VDF::Yu_p protected
Referenced by init_calcul_moyenne().
Yv_p
DoubleTab Traitement_particulier_NS_Profils_VDF::Yv_p protected
Referenced by init_calcul_moyenne().
Yw_p
DoubleTab Traitement_particulier_NS_Profils_VDF::Yw_p protected
Referenced by init_calcul_moyenne().
Yuv_p
DoubleTab Traitement_particulier_NS_Profils_VDF::Yuv_p protected
Referenced by init_calcul_moyenne().
compt_x_m
IntTab Traitement_particulier_NS_Profils_VDF::compt_x_m protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_y_m
IntTab Traitement_particulier_NS_Profils_VDF::compt_y_m protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_z_m
IntTab Traitement_particulier_NS_Profils_VDF::compt_z_m protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_uv_m
IntTab Traitement_particulier_NS_Profils_VDF::compt_uv_m protected
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
compt_x_p
IntTab Traitement_particulier_NS_Profils_VDF::compt_x_p protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_y_p
IntTab Traitement_particulier_NS_Profils_VDF::compt_y_p protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_z_p
IntTab Traitement_particulier_NS_Profils_VDF::compt_z_p protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
compt_uv_p
IntTab Traitement_particulier_NS_Profils_VDF::compt_uv_p protected
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
corresp_u_m
IntTab Traitement_particulier_NS_Profils_VDF::corresp_u_m protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_v_m
IntTab Traitement_particulier_NS_Profils_VDF::corresp_v_m protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_w_m
IntTab Traitement_particulier_NS_Profils_VDF::corresp_w_m protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_uv_m
IntTab Traitement_particulier_NS_Profils_VDF::corresp_uv_m protected
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
corresp_u_p
IntTab Traitement_particulier_NS_Profils_VDF::corresp_u_p protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_v_p
IntTab Traitement_particulier_NS_Profils_VDF::corresp_v_p protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_w_p
IntTab Traitement_particulier_NS_Profils_VDF::corresp_w_p protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
corresp_uv_p
IntTab Traitement_particulier_NS_Profils_VDF::corresp_uv_p protected
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
xUm
DoubleTab Traitement_particulier_NS_Profils_VDF::xUm protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xUp
DoubleTab Traitement_particulier_NS_Profils_VDF::xUp protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xWm
DoubleTab Traitement_particulier_NS_Profils_VDF::xWm protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xWp
DoubleTab Traitement_particulier_NS_Profils_VDF::xWp protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xVm
DoubleTab Traitement_particulier_NS_Profils_VDF::xVm protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xVp
DoubleTab Traitement_particulier_NS_Profils_VDF::xVp protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
xUVm
DoubleTab Traitement_particulier_NS_Profils_VDF::xUVm protected
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
xUVp
DoubleTab Traitement_particulier_NS_Profils_VDF::xUVp protected
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
delta_Um
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Um protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Up
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Up protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Wm
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Wm protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Wp
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Wp protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Vm
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Vm protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_Vp
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_Vp protected
Referenced by init_calcul_moyenne(), and post_traitement_particulier().
delta_UVm
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_UVm protected
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().
delta_UVp
DoubleVect Traitement_particulier_NS_Profils_VDF::delta_UVp protected
Referenced by init_calcul_moyenne(), Traitement_particulier_NS_Profils_thermo_VDF::post_traitement_particulier(), and post_traitement_particulier().