CEA TRUST Platform: Domaine_Cl_EF Class Reference
Domaine_Cl_EF Class Reference
Public Member Functions
void imposer_symetrie (DoubleTab &, int tous_les_sommets_sym=0) const
int initialiser (double temps) override
Public Member Functions inherited from Domaine_Cl_dis_base
virtual int calculer_coeffs_echange (double temps)
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
int contient_Cl (const Nom &)
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
const Nom & le_nom () const override
Conds_lim & les_conditions_limites ()
const Conds_lim & les_conditions_limites () const
Cond_lim & les_conditions_limites (int)
const Cond_lim & les_conditions_limites (int) const
virtual void mettre_a_jour (double temps)
virtual void mettre_a_jour_ss_pas_dt (double temps)
int nb_cond_lim () const
void nommer (const Nom &nom) override
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
completer()
void Domaine_Cl_EF::completer (const Domaine_dis_base & un_domaine_dis) override virtual
remplissage des tableaux
Implements Domaine_Cl_dis_base.
References Process::exit(), and remplir_type_elem_Cl().
initialiser()
int Domaine_Cl_EF::initialiser (double temps) override virtual
Initialise les CLs Contrairement aux methodes mettre_a_jour, les methodes.
initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(int) 1 si OK, 0 sinon
Reimplemented from Domaine_Cl_dis_base.
References Process::abort(), Domaine_Cl_dis_base::initialiser(), and nb_bord_periodicite().
imposer_cond_lim()
void Domaine_Cl_EF::imposer_cond_lim (Champ_Inc_base & ch, double temps) override virtual
Impose les conditions aux limites a la valeur temporelle "temps" du Champ_Inc.
Implements Domaine_Cl_dis_base.
References Cond_lim_base::champ_front(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_EF(), Process::exit(), Domaine_VF::face_sommets(), Cond_lim_base::frontiere_dis(), imposer_symetrie(), Domaine_Cl_dis_base::les_conditions_limites(), Field_base::nature_du_champ(), Field_base::nb_comp(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), Front_VF::num_face(), Objet_U::que_suis_je(), type_sommet_, Dirichlet::val_imp_au_temps(), Champ_front_var_instationnaire::valeur_au_temps_et_au_point(), Champ_front_var_instationnaire::valeur_au_temps_et_au_point_disponible(), and Champ_Inc_base::valeurs().
imposer_symetrie()
void Domaine_Cl_EF::imposer_symetrie (DoubleTab & values, int tous_les_sommets_sym = 0) const
Impose les conditions de symetrie c.
a.d annules les composantes du champ sur la ou les normales si tous_les_sommets_sym =1 alors meme les sommets appartenant aussi a un dirichlet sont mis a zero.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Domaine_Cl_dis_base::domaine_dis(), Domaine_32_64< _SIZE_ >::nb_som_tot(), normales_symetrie_bis_, normales_symetrie_ter_, and type_sommet_.
Referenced by Op_Grad_EF::ajouter_bord(), Solveur_Masse_EF::appliquer_impl(), Source_PDF_EF::filtre_CLD(), and imposer_cond_lim().
imposer_symetrie_partiellement()
void Domaine_Cl_EF::imposer_symetrie_partiellement (DoubleTab & values, const Noms & a_exclure) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_EF(), Domaine_VF::face_sommets(), Cond_lim_base::frontiere_dis(), Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces_tot(), normales_symetrie_bis_, normales_symetrie_ter_, Front_VF::num_face(), Noms::rang(), and type_sommet_.
imposer_symetrie_matrice_secmem()
void Domaine_Cl_EF::imposer_symetrie_matrice_secmem (Matrice_Morse & la_matrice, DoubleTab & secmem) const
On transforme la_matrice et le secmem pour avoir un secmem normal aux bords , plus la matrice pour assurer que la solution sera correcte.
References Matrice_Morse::coef(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_Cl_dis_base::domaine_dis(), MorEqn::equation(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Equation_base::inconnue(), Domaine_32_64< _SIZE_ >::nb_som(), normales_symetrie_bis_, normales_symetrie_ter_, type_sommet_, and Champ_Inc_base::valeurs().
Referenced by Op_EF_base::modifier_pour_Cl().
modifie_gradient()
void Domaine_Cl_EF::modifie_gradient (ArrOfDouble & grad_mod, const ArrOfDouble & grad, int num_som) const
References Objet_U::dimension, normales_symetrie_bis_, normales_symetrie_ter_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and type_sommet_.
Referenced by Assembleur_P_EF::assembler_mat().
nb_faces_sortie_libre()
int Domaine_Cl_EF::nb_faces_sortie_libre () const
References Process::exit().
domaine_EF() [1/2]
Domaine_EF & Domaine_Cl_EF::domaine_EF ()
References Domaine_Cl_dis_base::domaine_dis().
Referenced by imposer_cond_lim(), and imposer_symetrie_partiellement().
domaine_EF() [2/2]
const Domaine_EF & Domaine_Cl_EF::domaine_EF () const
References Domaine_Cl_dis_base::domaine_dis().
nb_bord_periodicite()
int Domaine_Cl_EF::nb_bord_periodicite () const
References Domaine_Cl_dis_base::les_conditions_limites_.
Referenced by initialiser().
get_type_sommet()
const ArrOfInt& Domaine_Cl_EF::get_type_sommet () const inline
References type_sommet_.
Referenced by Assembleur_P_EF::assembler_mat().
remplir_type_elem_Cl()
void Domaine_Cl_EF::remplir_type_elem_Cl (const Domaine_EF & le_dom_EF) protected
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Probleme_base::discretisation(), Discretisation_base::discretiser_champ(), Domaine_dis_base::domaine(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::front_VF(), Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites_, Field_base::nature_du_champ(), Front_VF::nb_faces_tot(), Domaine_32_64< _SIZE_ >::nb_som_tot(), normales_symetrie_bis_, normales_symetrie_ter_, Front_VF::num_face(), Equation_base::probleme(), Objet_U::que_suis_je(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and type_sommet_.
Referenced by completer().
OWN_PTR()
Domaine_Cl_EF::OWN_PTR (Champ_Don_base) protected
Member Data Documentation
modif_perio_fait_
int Domaine_Cl_EF::modif_perio_fait_ =0 protected
type_sommet_
ArrOfInt Domaine_Cl_EF::type_sommet_ protected
Referenced by get_type_sommet(), imposer_cond_lim(), imposer_symetrie(), imposer_symetrie_matrice_secmem(), imposer_symetrie_partiellement(), modifie_gradient(), and remplir_type_elem_Cl().
normales_symetrie_bis_
Domaine_Cl_EF::normales_symetrie_bis_ protected
Referenced by imposer_symetrie(), imposer_symetrie_matrice_secmem(), imposer_symetrie_partiellement(), modifie_gradient(), and remplir_type_elem_Cl().
normales_symetrie_ter_
Domaine_Cl_EF::normales_symetrie_ter_ protected
Referenced by imposer_symetrie(), imposer_symetrie_matrice_secmem(), imposer_symetrie_partiellement(), modifie_gradient(), and remplir_type_elem_Cl().