CEA TRUST Platform: Fluide_stiffened_gas Class Reference
Fluide_stiffened_gas Class Reference
#include <Fluide_stiffened_gas.h>
Additional Inherited Members
Public Member Functions inherited from Fluide_reel_base
void mettre_a_jour (double temps) override
Public Member Functions inherited from Fluide_base
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Fluide_base
void creer_nu ()
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Fluide_stiffened_gas()
Fluide_stiffened_gas::Fluide_stiffened_gas ()
Member Function Documentation
set_param()
void Fluide_stiffened_gas::set_param (Param & param) override virtual
Reimplemented from Fluide_reel_base.
References Param::ajouter(), and Fluide_reel_base::set_param().
rho_()
void Fluide_stiffened_gas::rho_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dP_rho_()
void Fluide_stiffened_gas::dP_rho_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dT_rho_()
void Fluide_stiffened_gas::dT_rho_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
h_()
void Fluide_stiffened_gas::h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dP_h_()
void Fluide_stiffened_gas::dP_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dT_h_()
void Fluide_stiffened_gas::dT_h_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
References cp_().
cp_()
void Fluide_stiffened_gas::cp_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
Referenced by cp_h_(), and dT_h_().
beta_()
void Fluide_stiffened_gas::beta_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
mu_()
void Fluide_stiffened_gas::mu_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
Referenced by mu_h_().
lambda_()
void Fluide_stiffened_gas::lambda_ (const SpanD T, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
Referenced by lambda_h_().
rho_h_()
void Fluide_stiffened_gas::rho_h_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dP_rho_h_()
void Fluide_stiffened_gas::dP_rho_h_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dh_rho_h_()
void Fluide_stiffened_gas::dh_rho_h_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
T_()
void Fluide_stiffened_gas::T_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dP_T_()
void Fluide_stiffened_gas::dP_T_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
dh_T_()
void Fluide_stiffened_gas::dh_T_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
cp_h_()
void Fluide_stiffened_gas::cp_h_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
References cp_().
beta_h_()
void Fluide_stiffened_gas::beta_h_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
mu_h_()
void Fluide_stiffened_gas::mu_h_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
References mu_().
lambda_h_()
void Fluide_stiffened_gas::lambda_h_ (const SpanD H, const SpanD P, SpanD res, int ncomp = 1, int id = 0) const override protected virtual
Implements Fluide_reel_base.
References lambda_().