CEA TRUST Platform: Entree_complete Class Reference
Entree_complete Class Reference
#include <Entree_complete.h>
Public Member Functions
int get (char *buf, std::streamsize bufsize) override
void set_bin (bool bin) override
void set_check_types (bool flag) override
void set_error_action (Error_Action) override
Public Member Functions inherited from Entree
void set_bin (bool bin) override
Additional Inherited Members
Protected Member Functions inherited from Entree
virtual int error_handle_ (int fail_flag)
Detailed Description
La suite est lue dans entree2 passee en parametre. check_types() et error_action() sont identiques a ceux de entree2
Constructor & Destructor Documentation
Entree_complete()
Entree_complete::Entree_complete (const char * str, Entree & entree2)
References chaine_str_, Entree::check_types(), entree2_, Entree::get_error_action(), EChaine::init(), Process::Journal(), num_entree_, Entree::set_check_types(), Entree::set_error_action(), and str_size_.
~Entree_complete()
Entree_complete::~Entree_complete () override
References entree2_.
Member Function Documentation
operator>>() [1/16]
Entree & Entree_complete::operator>> (True_int & ob) override virtual
Reimplemented from Entree.
operator>>() [2/16]
Entree & Entree_complete::operator>> (long & ob) override virtual
Reimplemented from Entree.
operator>>() [3/16]
Entree & Entree_complete::operator>> (long long & ob) override virtual
Reimplemented from Entree.
operator>>() [4/16]
Entree & Entree_complete::operator>> (float & ob) override virtual
Reimplemented from Entree.
operator>>() [5/16]
Entree & Entree_complete::operator>> (double & ob) override virtual
Reimplemented from Entree.
get() [1/6]
int Entree_complete::get (True_int * ob, std::streamsize n) override virtual
Reimplemented from Entree.
get() [2/6]
int Entree_complete::get (long * ob, std::streamsize n) override virtual
Reimplemented from Entree.
get() [3/6]
int Entree_complete::get (long long * ob, std::streamsize n) override virtual
Reimplemented from Entree.
get() [4/6]
int Entree_complete::get (float * ob, std::streamsize n) override virtual
Reimplemented from Entree.
get() [5/6]
int Entree_complete::get (double * ob, std::streamsize n) override virtual
Reimplemented from Entree.
get() [6/6]
int Entree_complete::get (char * ob, std::streamsize bufsize) override virtual
Lecture d'une chaine dans ostream_ bufsize est la taille du buffer alloue pour ob (y compris.
le caractere 0 final). La chaine contient toujours un 0 meme en cas d'echec. La methode renvoie 1 si la lecture est bonne, 0 sinon. Si le buffer est trop petit, pour l'instant on fait exit() mais par la suite on pourra tester: si strlen(ob)==bufsize-1, alors refaire lire() jusqu'a arriver au bout. Si le lire() suivant renvoie une chaine de longueur nulle, cela signifie que la taille de la chaine etait exactement bufsize-1. Attention: le comportement est different en binaire et en ascii. En binaire, on lit la chaine jusqu'au prochain '\0'. En ascii, on lit la chaine jusqu'au prochain separateur (espace, tab, fin ligne)
Reimplemented from Entree.
References Entree::get(), and get_input().
eof()
int Entree_complete::eof () override virtual
Reimplemented from Entree.
References Entree::eof(), and get_input().
fail()
int Entree_complete::fail () override virtual
Reimplemented from Entree.
References Entree::fail(), and get_input().
good()
int Entree_complete::good () override virtual
Reimplemented from Entree.
References get_input(), and Entree::good().
set_bin()
void Entree_complete::set_bin (bool bin) override
Il est interdit de changer de type d'entree.
exit()
References Process::exit().
set_error_action()
void Entree_complete::set_error_action (Error_Action action) override virtual
affecte la valeur aux deux entrees sources Attention, la valeur de entree2 est modifiee !
Voir Entree::set_error_action()
Reimplemented from Entree.
References chaine_str_, entree2_, and Entree::set_error_action().
set_check_types()
void Entree_complete::set_check_types (bool flag) override virtual
affecte le drapeau aux deux entrees sources Attention, le drapeau de entree2 est modifie !
Voir Entree::set_check_types()
Reimplemented from Entree.
References chaine_str_, entree2_, and Entree::set_check_types().
get_input()
Entree & Entree_complete::get_input () protected
References chaine_str_, entree2_, Entree::get_istream(), and num_entree_.
Referenced by eof(), fail(), get(), and good().
operator>>() [6/16]
Entree & Entree::operator>> (Entree &(*)(Entree &) f)
operator>>() [7/16]
Entree & Entree::operator>> (istream &(*)(istream &) f)
operator>>() [8/16]
Entree & Entree::operator>> (ios &(*)(ios &) f)
operator>>() [9/16]
template<typename T > Entree & Entree::operator>> (const TRUST_Ref< T > &) inline
operator>>() [10/16]
Entree & Entree::operator>> (const TRUST_Ref_Objet_U &) inline
operator>>() [11/16]
Entree & Entree::operator>> (True_int & ob) virtual
Reimplemented from Entree.
operator>>() [12/16]
Entree & Entree::operator>> (long & ob) virtual
Reimplemented from Entree.
operator>>() [13/16]
Entree & Entree::operator>> (long long & ob) virtual
Reimplemented from Entree.
operator>>() [14/16]
Entree & Entree::operator>> (float & ob) virtual
Reimplemented from Entree.
operator>>() [15/16]
Entree & Entree::operator>> (double & ob) virtual
Reimplemented from Entree.
operator>>() [16/16]
Entree & Entree::operator>> (Objet_U & ob) final virtual
Reimplemented from Entree.
Member Data Documentation
num_entree_
int Entree_complete::num_entree_ protected
Referenced by Entree_complete(), and get_input().
str_size_
int Entree_complete::str_size_ protected
Referenced by Entree_complete().
chaine_str_
EChaine Entree_complete::chaine_str_ protected
Referenced by Entree_complete(), get_input(), set_check_types(), and set_error_action().
entree2_
Entree* Entree_complete::entree2_ protected
Referenced by Entree_complete(), get_input(), set_check_types(), set_error_action(), and ~Entree_complete().