CEA TRUST Platform: Pave_32_64< _SIZE_ > Class Template Reference
Pave_32_64< _SIZE_ > Class Template Reference
#include <Pave.h>
Protected Member Functions
double & coord_noeud (int i)
double & coord_noeud (int i, int j, int k, int l)
double & coord_noeud (int i, int j, int l)
void lire_front (Entree &, Frontiere_t &)
void lire_longueurs (Entree &is)
void lire_noeuds (Entree &is)
void maille2D ()
int_t & maille_sommet (int i, int j, int k, int l)
int_t & maille_sommet (int i, int j, int l)
int_t & maille_sommet (int i, int l)
int_t numero_maille (int i)
int_t numero_maille (int i, int j)
int_t numero_maille (int i, int j, int k)
int_t numero_sommet (int i)
int_t numero_sommet (int i, int j)
int_t numero_sommet (int i, int j, int k)
void typer_ ()
Additional Inherited Members
Public Member Functions inherited from Domaine_32_64< _SIZE_ >
void ajouter (const DoubleTab_t &soms)
void ajouter (const DoubleTab_t &soms, IntVect_t &nums)
int associer_ (Objet_U &) override
Bord_Interne_t & bords_interne (int i)
void build_mc_mesh () const
void calculer_centres_gravite (DoubleTab_t &xp) const
void calculer_centres_gravite_aretes (DoubleTab_t &xa) const
void calculer_volumes (DoubleVect_t &volumes, DoubleVect_t &inv_volumes) const
SmallArrOfTID_t & chercher_aretes (const DoubleTab &pos, SmallArrOfTID_t &arr, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleTab &pos, SmallArrOfTID_t &elem, int reel=0) const
SmallArrOfTID_t & chercher_elements (const DoubleVect &pos, SmallArrOfTID_t &elem, int reel=0) const
int_t chercher_elements (double x, double y=0, double z=0, int reel=0) const
SmallArrOfTID_t & chercher_sommets (const DoubleTab &pos, SmallArrOfTID_t &som, int reel=0) const
int_t chercher_sommets (double x, double y=0, double z=0, int reel=0) const
virtual void clear ()
void construire_elem_virt_pe_num ()
void correct_type_of_borders_after_merge ()
virtual void creer_tableau_elements (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
virtual void creer_tableau_sommets (Array_base &, RESIZE_OPTIONS opt=RESIZE_OPTIONS::COPY_INIT) const
void ecrire_noms_bords (Sortie &) const
int_t face_bords_interne_conjuguee (int_t face) const
void fill_from_list (std::list< Domaine_32_64 * > &lst)
const Frontiere_t & frontiere (int i) const
const ArrOfInt_t & ind_faces_virt_bord () const
SmallArrOfTID_t & indice_elements (const IntTab &som, SmallArrOfTID_t &elem, int reel=0) const
void init_renum_perio ()
const LIST (OBS_PTR(Domaine_32_64)) &domaines_frontieres() const
int nb_bords () const
int nb_faces_elem (int=0) const
int_t nb_faces_frontiere (Type_Face type) const
int_t nb_faces_specifiques () const
int_t nb_faces_specifiques (Type_Face type) const
int nb_groupes_faces () const
int nb_joints () const
int nb_raccords () const
int nb_som_elem () const
void renum (const IntVect_t &nums)
void renum_joint_common_items (const IntVect_t &nums, const int_t elem_offset)
void typer (const Nom &)
Static Public Member Functions inherited from Domaine_32_64< _SIZE_ >
static int identifie_item_unique (IntList &item_possible, DoubleTab &coord_possible, const DoubleVect &coord_ref)
Detailed Description
template<typename _SIZE_>
class Pave_32_64< _SIZE_ >
La structure du jeu de donnee pour specifier un Pave est: Pave nom_pave { Origine OX OY (OZ) Longueurs LX LY (LZ) Nombre_de_noeuds NX NY (NZ) Facteurs Fx Fy (Fz) (Symx) (Symy) (Symz) } { (Bord) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1 ... (Raccord) local homogene nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1 ... (Internes) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1 ... (Joint) nom X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1 PE_voisin ... }
See also
Domaine Mailler, Actuellemnt c'est le seul type d'objet reconnu par Trio-U pour mailler, un domaine
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Pave_32_64< _SIZE_ >::int_t = _SIZE_
IntVect_t
template<typename _SIZE_ > using Pave_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Pave_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
DoubleVect_t
template<typename _SIZE_ > using Pave_32_64< _SIZE_ >::DoubleVect_t = DoubleVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using Pave_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Pave_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Frontiere_t
template<typename _SIZE_ > using Pave_32_64< _SIZE_ >::Frontiere_t = Frontiere_32_64<_SIZE_>
Member Function Documentation
numero_maille() [1/3]
template<typename _SIZE_ > Pave_32_64< _SIZE_ >::int_t Pave_32_64< _SIZE_ >::numero_maille (int i) inline protected
Renvoie le numero de la i-ieme maille (suivant X)
Parameters
(int i) le rang de la maille suivant X dont on veut le numero
Returns
(int) le numero de la maille cherchee
numero_maille() [2/3]
template<typename _SIZE_ > Pave_32_64< _SIZE_ >::int_t Pave_32_64< _SIZE_ >::numero_maille (int i, int j) inline protected
Renvoie le numero de la (i,j)-ieme maille (suivant (X,Y)).
Parameters
(int i) le rang de la maille suivant X
(int j) le rang de la maille suivant Y
Returns
(int) le numero de la maille cherchee
numero_maille() [3/3]
template<typename _SIZE_ > Pave_32_64< _SIZE_ >::int_t Pave_32_64< _SIZE_ >::numero_maille (int i, int j, int k) inline protected
Renvoie le numero de la (i,j,k)-ieme maille (suivant (X,Y,Z)).
Parameters
(int i) le rang de la maille suivant X
(int j) le rang de la maille suivant Y
(int k) le rang de la maille suivant Z
Returns
(int) le numero de la maille cherchee
numero_sommet() [1/3]
template<typename _SIZE_ > Pave_32_64< _SIZE_ >::int_t Pave_32_64< _SIZE_ >::numero_sommet (int i) inline protected
Renvoie le numero du i-ieme sommet (suivant X)
Parameters
(int i) le rang du sommet suivant X dont on veut le numero
Returns
(int) le numero du sommet cherche
numero_sommet() [2/3]
template<typename _SIZE_ > Pave_32_64< _SIZE_ >::int_t Pave_32_64< _SIZE_ >::numero_sommet (int i, int j) inline protected
Renvoie le numero du (i,j)-ieme sommet (suivant (X,Y)).
Parameters
(int i) le rang du sommet suivant X
(int j) le rang du sommet suivant Y
Returns
(int) le numero du sommet cherche
numero_sommet() [3/3]
template<typename _SIZE_ > Pave_32_64< _SIZE_ >::int_t Pave_32_64< _SIZE_ >::numero_sommet (int i, int j, int k) inline protected
Renvoie le numero du (i,j,k)-ieme sommet (suivant (X,Y,Z)).
Parameters
(int i) le rang du sommet suivant X
(int j) le rang du sommet suivant Y
(int k) le rang du sommet suivant Z
Returns
(int) le numero du sommet cherche
maille_sommet() [1/3]
template<typename _SIZE_ > Pave_32_64< _SIZE_ >::int_t & Pave_32_64< _SIZE_ >::maille_sommet (int i, int l) inline protected
Renvoie une reference sur le numero du l-ieme sommet de la i-ieme maille (suivant X) du pave.
Parameters
(int i) le rang de la maille suivant X
(int l) le rang du sommet cherche
Returns
(int&) reference sur le numero du sommet cherche
maille_sommet() [2/3]
template<typename _SIZE_ > Pave_32_64< _SIZE_ >::int_t & Pave_32_64< _SIZE_ >::maille_sommet (int i, int j, int l) inline protected
Renvoie une reference sur le numero du l-ieme sommet de la (i,j)-ieme maille (suivant (X,Y)) du pave.
Parameters
(int i) le rang de la maille suivant X
(int j) le rang de la maille suivant Y
(int l) le rang du sommet cherche
Returns
(int&) reference sur le numero du sommet cherche
maille_sommet() [3/3]
template<typename _SIZE_ > Pave_32_64< _SIZE_ >::int_t & Pave_32_64< _SIZE_ >::maille_sommet (int i, int j, int k, int l) inline protected
Renvoie une reference sur le numero du l-ieme sommet de la (i,j,k)-ieme maille (suivant (X,Y,Z)) du pave.
Parameters
(int i) le rang de la maille suivant X
(int j) le rang de la maille suivant Y
(int j) le rang de la maille suivant Z
(int l) le rang du sommet cherche
Returns
(int&) reference sur le numero du sommet cherche
coord_noeud() [1/3]
template<typename _SIZE_ > double & Pave_32_64< _SIZE_ >::coord_noeud (int i) inline protected
Renvoie une reference sur les coordonnees du i-ieme noeud.
Parameters
(int i) le rang du noeud suivant X
Returns
(double&) reference sur les coordonnees du noeud cherche
coord_noeud() [2/3]
template<typename _SIZE_ > double & Pave_32_64< _SIZE_ >::coord_noeud (int i, int j, int l) inline protected
Renvoie une reference sur les coordonnees du (i,j)-ieme noeud.
Parameters
(int i) le rang du noeud suivant X
(int j) le rang du noeud suivant Y
Returns
(double&) reference sur les coordonnees du noeud cherche
coord_noeud() [3/3]
template<typename _SIZE_ > double & Pave_32_64< _SIZE_ >::coord_noeud (int i, int j, int k, int l) inline protected
Renvoie une reference sur les coordonnees du (i,j,k)-ieme noeud.
Parameters
(int i) le rang du noeud suivant X
(int j) le rang du noeud suivant Y
(int k) le rang du noeud suivant Z
Returns
(double&) reference sur les coordonnees du noeud cherche
maille2D()
template<typename _SIZE_ > void Pave_32_64< _SIZE_ >::maille2D () protected
Effectue un maillage 1D, du pave avec les valeurs des parametres lus par ReadOn.
‍/ template <typename _SIZE_> void Pave_32_64<SIZE>::maille1D() { Cerr << "Step of 1D mesh in progress... " << finl; double epsilon_geom=Objet_U::precision_geom; int i; if(longueurs_(0)<0) { origine_(0)+=longueurs_(0); longueurs_(0)=-longueurs_(0); facteurs_(0)=1./facteurs_(0); } if((!symetrique_(0)) || (std::fabs(facteurs_(0)-1.)<epsilon_geom)) { if(std::fabs(facteurs_(0)-1.)>epsilon_geom) pas_(0)=longueurs_(0)*(facteurs_(0)-1)/(pow(facteurs_(0),Nx)-1); else pas_(0)=longueurs_(0)/Nx; double dx=pas_(0); double x=origine_(0); for (i=0; i<Nx; i++) { coord_noeud(i)=x; x+=dx; dx*=facteurs_(0); } coord_noeud(Nx)=origine_(0)+longueurs_(0); } else { int Ix=Nx/2; if((Ix*2)==Nx) pas_(0)=0.5*longueurs_(0)*(facteurs_(0)-1)/(pow(facteurs_(0),Ix)-1); else { if(Ix) { Ix+=1; pas_(0)=0.5*longueurs_(0)/((pow(facteurs_(0),Ix-1)-1)/(facteurs_(0)-1) +0.5*pow(facteurs_(0),Ix)); } else { Ix+=1; pas_(0)=0; } } double dx=pas_(0); double x=0; for (i=0; i<Ix; i++) { coord_noeud(i)=origine_(0)+x; coord_noeud(Nx-i)=origine_(0)+longueurs_(0)-x; x+=dx; dx*=facteurs_(0); } if((Ix*2)==Nx) coord_noeud(Ix)=0.5*(coord_noeud(Ix+1)+coord_noeud(Ix-1)); } Cerr << finl; Cerr << "Step of mesh ended " << finl; }
/*! Effectue un maillage 2D, du pave avec les valeurs des parametres lus par ReadOn.
Maillage en x en tanh
Maillage en y en tanh
References Objet_U::precision_geom.
maille3D()
template<typename _SIZE_ > void Pave_32_64< _SIZE_ >::maille3D () protected
Effectue un maillage 3D, du pave avec les valeurs des parametres lus par ReadOn.
Maillage en x en tanh
Maillage en y en tanh
Maillage en z en tanh
References Objet_U::precision_geom.
typer_()
template<typename _SIZE_ > void Pave_32_64< _SIZE_ >::typer_ () protected
Type le pave suivant la dimension d'espace et suivant le repere de coordonnees demande (cylindrique.
ou cartesien) En dimension 1 : le pave est maille avec des segments En dimension 2 (axi): la pave est maille avec des rectangle (axi) En dimension 3 (axi): la pave est maille avec des hexaedres (axi)
lire_longueurs()
template<typename _SIZE_ > void Pave_32_64< _SIZE_ >::lire_longueurs (Entree & is) protected
Lit les longueurs LX LY [LZ] du jeu de donnee a partir d'un flot d'entree.
Methode appelee par readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Exceptions
La Longueur est en nombre de tour en axi, comprise entre 0 et 1
References Process::exit().
lire_noeuds()
template<typename _SIZE_ > void Pave_32_64< _SIZE_ >::lire_noeuds (Entree & is) protected
Lit le nombre de noeuds dans le jeu de donnee a partir d'un flot d'entree et construit les noeuds.
Methode appelee par readOn(Entree&)
Parameters
(Entree& is) un flot d'entree
Exceptions
en coordonnees axi il faut lire les longueurs d'abord
dimension d'espace non prevue
References Objet_U::dimension, and Process::exit().
lire_front()
template<typename _SIZE_ > void Pave_32_64< _SIZE_ >::lire_front (Entree & is, Frontiere_t & front) protected
Lit les specifications d'une frontiere du jeu de donnee a partir d'un flot d'entree et la construit.
Format: nom_front X = X0 Y0 <= Y <= Y1 Z0 <= Z <= Z1
Parameters
(Entree& is) un flot d'entree
(Frontiere& front) la frontiere lue
Exceptions
mot clef "X" attendu
mot clef "=" attendu
extremite en X invalide
mot clef "X" ou "Y" attendu
mot clef "<=" attendu
mot clef "Y" attendu
extremite en Y invalide
il n'y a pas de bord en teta, vous avez maille une couronne complete
mot clef "X" ou "Y" ou "Z" attendu
mot clef "Z" attendu
extremite en Z invalide
References Frontiere_32_64< _SIZE_ >::ajouter_faces(), Frontiere_32_64< _SIZE_ >::associer_domaine(), Frontiere_32_64< _SIZE_ >::dimensionner(), Process::exit(), Frontiere_32_64< _SIZE_ >::nommer(), and Frontiere_32_64< _SIZE_ >::typer_faces().
Member Data Documentation
origine_
template<typename _SIZE_ > DoubleVect Pave_32_64< _SIZE_ >::origine_ protected
longueurs_
template<typename _SIZE_ > DoubleVect Pave_32_64< _SIZE_ >::longueurs_ protected
facteurs_
template<typename _SIZE_ > DoubleVect Pave_32_64< _SIZE_ >::facteurs_ protected
pas_
template<typename _SIZE_ > DoubleVect Pave_32_64< _SIZE_ >::pas_ protected
symetrique_
template<typename _SIZE_ > IntVect Pave_32_64< _SIZE_ >::symetrique_ protected
nb_noeuds_
template<typename _SIZE_ > IntVect Pave_32_64< _SIZE_ >::nb_noeuds_ protected
Nx
template<typename _SIZE_ > int Pave_32_64< _SIZE_ >::Nx = -1 protected
Ny
template<typename _SIZE_ > int Pave_32_64< _SIZE_ >::Ny = -1 protected
Nz
template<typename _SIZE_ > int Pave_32_64< _SIZE_ >::Nz = -1 protected
Mx
template<typename _SIZE_ > int Pave_32_64< _SIZE_ >::Mx = -1 protected
My
template<typename _SIZE_ > int Pave_32_64< _SIZE_ >::My = -1 protected
Mz
template<typename _SIZE_ > int Pave_32_64< _SIZE_ >::Mz = -1 protected
a_tanh
template<typename _SIZE_ > double Pave_32_64< _SIZE_ >::a_tanh = 10. protected
tanh_dilatation
template<typename _SIZE_ > int Pave_32_64< _SIZE_ >::tanh_dilatation =0 protected
xa_tanh
template<typename _SIZE_ > double Pave_32_64< _SIZE_ >::xa_tanh = 10. protected
xtanh_dilatation
template<typename _SIZE_ > int Pave_32_64< _SIZE_ >::xtanh_dilatation =0 protected
za_tanh
template<typename _SIZE_ > double Pave_32_64< _SIZE_ >::za_tanh = 10. protected
ztanh_dilatation
template<typename _SIZE_ > int Pave_32_64< _SIZE_ >::ztanh_dilatation =0 protected
rep_VEF
template<typename _SIZE_ > bool Pave_32_64< _SIZE_ >::rep_VEF =false protected
tour_complet
template<typename _SIZE_ > bool Pave_32_64< _SIZE_ >::tour_complet = false protected