CEA TRUST Platform: EDO_Pression_th_base Class Reference
EDO_Pression_th_base Class Reference abstract
Public Member Functions
void associer_fluide (const Fluide_Dilatable_base &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
associees a la resolution du schema pour les fluides dilatables
See also
Fluide_Dilatable_base, Classe abstraite dont toutes les lois d'etat doivent deriver., Methodes abstraites:, void calculer_coeff_T(), void Resoudre_EDO_PT(), void calculer_masse_volumique()
Member Function Documentation
associer_fluide()
void EDO_Pression_th_base::associer_fluide (const Fluide_Dilatable_base & fl)
Associe le fluide a l'EDO.
Parameters
(Fluide_Dilatable_base& fl) le fluide associe
associer_domaines()
void EDO_Pression_th_base::associer_domaines (const Domaine_dis_base & dds, const Domaine_Cl_dis_base & domaine_cl)
getM0()
const double& EDO_Pression_th_base::getM0 () const inline
References M0.
completer()
void EDO_Pression_th_base::completer () virtual
Reimplemented in EDO_Pression_th_VEF.
References M0, and masse_totale().
Referenced by EDO_Pression_th_VEF::completer().
mettre_a_jour_CL()
void EDO_Pression_th_base::mettre_a_jour_CL (double P)
References Sortie_libre_pression_imposee_QC::set_Pth().
masse_totale() [1/2]
virtual double EDO_Pression_th_base::masse_totale (double P, const DoubleTab & T) pure virtual
Implemented in EDO_Pression_th_VEF, and EDO_Pression_th_VDF.
Referenced by completer().
masse_totale() [2/2]
virtual double EDO_Pression_th_base::masse_totale (const DoubleTab & P, const DoubleTab & T) pure virtual
Implemented in EDO_Pression_th_VEF, and EDO_Pression_th_VDF.
resoudre() [1/2]
virtual double EDO_Pression_th_base::resoudre (double P) pure virtual
Implemented in EDO_Pression_th_VEF_Gaz_Reel, EDO_Pression_th_VEF_Gaz_Parfait, EDO_Pression_th_VDF_Gaz_Reel, and EDO_Pression_th_VDF_Gaz_Parfait.
resoudre() [2/2]
virtual void EDO_Pression_th_base::resoudre (DoubleTab & P) pure virtual
Implemented in EDO_Pression_th_VEF_Gaz_Reel, EDO_Pression_th_VEF_Gaz_Parfait, EDO_Pression_th_VDF_Gaz_Reel, and EDO_Pression_th_VDF_Gaz_Parfait.
OBS_PTR() [1/3]
EDO_Pression_th_base::OBS_PTR (Fluide_Dilatable_base) protected
OBS_PTR() [2/3]
EDO_Pression_th_base::OBS_PTR (Domaine_Cl_dis_base) protected
OBS_PTR() [3/3]
EDO_Pression_th_base::OBS_PTR (Domaine_VF) protected
Member Data Documentation
M0
double EDO_Pression_th_base::M0 = -1. protected
Referenced by completer(), and getM0().