CEA TRUST Platform: StatComm Class Reference
StatComm Class Reference
Constructor & Destructor Documentation
StatComm()
StatComm::StatComm ()
Member Function Documentation
stat()
void StatComm::stat (int size)
get_szmin()
int StatComm::get_szmin ()
get_szmax()
int StatComm::get_szmax ()
get_nbmsg()
int StatComm::get_nbmsg ()
get_szmoy()
double StatComm::get_szmoy ()
Referenced by print_stat().
print_stat()
void StatComm::print_stat (Sortie & os)
References get_szmoy(), and Process::me().