CEA TRUST Platform: Iterateur_VDF_Face< _TYPE_ > Class Template Reference
Iterateur_VDF_Face< _TYPE_ > Class Template Reference
#include <Iterateur_VDF_Face.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Iterateur_VDF_Face() [1/2]
template<class _TYPE_ > Iterateur_VDF_Face< _TYPE_ >::Iterateur_VDF_Face () inline
Iterateur_VDF_Face() [2/2]
template<class _TYPE_ > Iterateur_VDF_Face< _TYPE_ >::Iterateur_VDF_Face (const Iterateur_VDF_Face< _TYPE_ > & iter) inline
References Iterateur_VDF_Face< _TYPE_ >::elem, Iterateur_VDF_Face< _TYPE_ >::elem_faces, Iterateur_VDF_Face< _TYPE_ >::orientation, Iterateur_VDF_Face< _TYPE_ >::Qdm, TRUSTTab< _TYPE_, _SIZE_ >::ref(), TRUSTVect< _TYPE_, _SIZE_ >::ref(), Iterateur_VDF_Face< _TYPE_ >::type_arete_bord, and Iterateur_VDF_Face< _TYPE_ >::type_arete_coin.
Member Function Documentation
evaluateur() [1/2]
template<class _TYPE_ > Evaluateur_VDF & Iterateur_VDF_Face< _TYPE_ >::evaluateur () inline override virtual
Implements Iterateur_VDF_base.
References Iterateur_VDF_Face< _TYPE_ >::flux_evaluateur.
evaluateur() [2/2]
template<class _TYPE_ > const Evaluateur_VDF & Iterateur_VDF_Face< _TYPE_ >::evaluateur () const inline override virtual
Implements Iterateur_VDF_base.
References Iterateur_VDF_Face< _TYPE_ >::flux_evaluateur.
impr()
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::impr (Sortie & os) const override virtual
Implements Iterateur_VDF_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Schema_Temps_base::imprimer_temps_courant(), Frontiere_dis_base::le_nom(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), EcrFicPartage::syncfile(), and Schema_Temps_base::temps_courant().
completer_()
template<class _TYPE_ > void Iterateur_VDF_Face< _TYPE_ >::completer_ () override virtual
Implements Iterateur_VDF_base.
ajouter_blocs()
template<class _TYPE_ > void Iterateur_VDF_Face< _TYPE_ >::ajouter_blocs (matrices_t mats, DoubleTab & secmem, const tabs_t & semi_impl) const override virtual
Implements Iterateur_VDF_base.
References TRUSTTab< _TYPE_, _SIZE_ >::resize().
Member Data Documentation
flux_evaluateur
template<class _TYPE_ > _TYPE_ Iterateur_VDF_Face< _TYPE_ >::flux_evaluateur protected
Referenced by Iterateur_VDF_Face< _TYPE_ >::evaluateur(), and Iterateur_VDF_Face< _TYPE_ >::evaluateur().
nb_elem
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::nb_elem = -100 protected
premiere_arete_interne
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::premiere_arete_interne = -100 protected
derniere_arete_interne
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::derniere_arete_interne = -100 protected
premiere_arete_mixte
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::premiere_arete_mixte = -100 protected
derniere_arete_mixte
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::derniere_arete_mixte = -100 protected
premiere_arete_bord
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::premiere_arete_bord = -100 protected
derniere_arete_bord
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::derniere_arete_bord = -100 protected
premiere_arete_coin
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::premiere_arete_coin = -100 protected
derniere_arete_coin
template<class _TYPE_ > int Iterateur_VDF_Face< _TYPE_ >::derniere_arete_coin = -100 protected
Flux
template<class _TYPE_ > SFichier Iterateur_VDF_Face< _TYPE_ >::Flux mutable protected
Flux_moment
template<class _TYPE_ > SFichier Iterateur_VDF_Face< _TYPE_ >::Flux_moment protected
Flux_sum
template<class _TYPE_ > SFichier Iterateur_VDF_Face< _TYPE_ >::Flux_sum protected
Qdm
template<class _TYPE_ > IntTab Iterateur_VDF_Face< _TYPE_ >::Qdm protected
Referenced by Iterateur_VDF_Face< _TYPE_ >::Iterateur_VDF_Face().
elem
template<class _TYPE_ > IntTab Iterateur_VDF_Face< _TYPE_ >::elem protected
Referenced by Iterateur_VDF_Face< _TYPE_ >::Iterateur_VDF_Face().
elem_faces
template<class _TYPE_ > IntTab Iterateur_VDF_Face< _TYPE_ >::elem_faces protected
Referenced by Iterateur_VDF_Face< _TYPE_ >::Iterateur_VDF_Face().
orientation
template<class _TYPE_ > IntVect Iterateur_VDF_Face< _TYPE_ >::orientation protected
Referenced by Iterateur_VDF_Face< _TYPE_ >::Iterateur_VDF_Face().
type_arete_bord
template<class _TYPE_ > IntVect Iterateur_VDF_Face< _TYPE_ >::type_arete_bord protected
Referenced by Iterateur_VDF_Face< _TYPE_ >::Iterateur_VDF_Face().
type_arete_coin
template<class _TYPE_ > IntVect Iterateur_VDF_Face< _TYPE_ >::type_arete_coin protected
Referenced by Iterateur_VDF_Face< _TYPE_ >::Iterateur_VDF_Face().