CEA TRUST Platform: Traitement_particulier_NS_THI Class Reference
Traitement_particulier_NS_THI Class Reference abstract
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
pour les calculs de THI, en particulier initialisation
particuliere et calculs des spectres!!
See also
Navier_Stokes_Turbulent, Traitement_particulier_base, Traitement_particulier_VEF
Member Function Documentation
lire()
Entree & Traitement_particulier_NS_THI::lire (Entree & is) override virtual
Implements Traitement_particulier_NS_base.
References Ec_init, Process::exit(), fac_init, init, oui_calc_spectre, and Motcles::search().
preparer_calcul_particulier()
void Traitement_particulier_NS_THI::preparer_calcul_particulier () override virtual
Implements Traitement_particulier_NS_base.
References calcul_spectre(), fac_init, init, init_calc_spectre(), oui_calc_spectre, renorm_Ec(), and sorties_globales().
post_traitement_particulier()
void Traitement_particulier_NS_THI::post_traitement_particulier () override virtual
Implements Traitement_particulier_NS_base.
References calcul_spectre(), oui_calc_spectre, and sorties_globales().
en_cours_de_resolution()
void Traitement_particulier_NS_THI::en_cours_de_resolution (int nb_op, DoubleTab & u, DoubleTab & u_av, double dt) override virtual
Implements Traitement_particulier_NS_base.
References calcul_spectre_operateur(), and oui_transf.
sauver_stat()
void Traitement_particulier_NS_THI::sauver_stat () const inline override virtual
Implements Traitement_particulier_NS_base.
reprendre_stat()
void Traitement_particulier_NS_THI::reprendre_stat () inline override virtual
Implements Traitement_particulier_NS_base.
a_pour_Champ_Fonc()
int Traitement_particulier_NS_THI::a_pour_Champ_Fonc (const Motcle & mot, OBS_PTR(Champ_base)& ch_ref) const inline
comprend_champ()
int Traitement_particulier_NS_THI::comprend_champ (const Motcle & mot) const inline
renorm_Ec()
virtual void Traitement_particulier_NS_THI::renorm_Ec () protected pure virtual
Referenced by preparer_calcul_particulier().
calcul_spectre_operateur()
virtual void Traitement_particulier_NS_THI::calcul_spectre_operateur (int , DoubleTab & , DoubleTab & , double) protected pure virtual
Referenced by en_cours_de_resolution().
init_calc_spectre()
virtual void Traitement_particulier_NS_THI::init_calc_spectre () protected pure virtual
Referenced by preparer_calcul_particulier().
calcul_spectre()
virtual void Traitement_particulier_NS_THI::calcul_spectre () protected pure virtual
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
sorties_globales()
virtual void Traitement_particulier_NS_THI::sorties_globales () protected pure virtual
Referenced by post_traitement_particulier(), and preparer_calcul_particulier().
calcul_nb_som_dir()
int & Traitement_particulier_NS_THI::calcul_nb_som_dir (const Domaine & domaine) protected
References Process::mp_sum(), msg_erreur_maillage(), and nb_som_dir.
calcul_nb_elem_dir()
int & Traitement_particulier_NS_THI::calcul_nb_elem_dir (const Domaine & domaine) protected
References Process::mp_sum(), msg_erreur_maillage(), and nb_elem_dir.
msg_erreur_maillage()
void Traitement_particulier_NS_THI::msg_erreur_maillage (const char * methode_actuelle) protected
References Process::abort(), and Process::je_suis_maitre().
Referenced by calcul_nb_elem_dir(), and calcul_nb_som_dir().
Member Data Documentation
init
int Traitement_particulier_NS_THI::init = 0 protected
Referenced by lire(), and preparer_calcul_particulier().
oui_transf
int Traitement_particulier_NS_THI::oui_transf = 0 protected
Referenced by en_cours_de_resolution().
oui_calc_spectre
int Traitement_particulier_NS_THI::oui_calc_spectre = 0 protected
Referenced by lire(), post_traitement_particulier(), and preparer_calcul_particulier().
Ec_init
double Traitement_particulier_NS_THI::Ec_init = -100. protected
Referenced by lire().
nb_som_dir
int Traitement_particulier_NS_THI::nb_som_dir = 0 protected
Referenced by calcul_nb_som_dir().
nb_elem_dir
int Traitement_particulier_NS_THI::nb_elem_dir = 0 protected
Referenced by calcul_nb_elem_dir().
fac_init
int Traitement_particulier_NS_THI::fac_init = 0 protected
Referenced by lire(), and preparer_calcul_particulier().