CEA TRUST Platform: Synonyme_info Class Reference
Synonyme_info Class Reference
#include <Synonyme_info.h>
Public Member Functions
Synonyme_info (const char *name, const char *org)
Static Public Member Functions
static void ajouter_synonyme (const Synonyme_info &synonyme_info)
static int est_un_synonyme (const char *)
static Sortie & hierarchie (Sortie &)
static const Synonyme_info * synonyme_info_from_name (const char *synonyme_name)
Detailed Description
See also
Objet_U Nom
Constructor & Destructor Documentation
Synonyme_info() [1/2]
Synonyme_info::Synonyme_info () inline
~Synonyme_info()
Synonyme_info::~Synonyme_info ()
References nom().
Synonyme_info() [2/2]
Synonyme_info::Synonyme_info (const char * un_nom, const char * org_name)
Constructeur par un nom, un tableau de meres.
Parameters
(const char* nom) le nom du synonyme a creer
(int nb_base) le nombre de meres dans le tableau bases[]
(const Synonyme_info* bases[]) le tableau specifiant les synonymes de bases (meres) du synonyme a creer
Exceptions
Sort en erreur si le nom n'est pas defini (null)
References ajouter_synonyme(), and Process::exit().
Member Function Documentation
org_name_()
const char * Synonyme_info::org_name_ () const inline
Referenced by Probleme_base::equation(), Probleme_base::equation(), hierarchie(), and Objet_U_ptr::typer().
nom()
const char * Synonyme_info::nom () const inline
Referenced by est_un_synonyme(), hierarchie(), and ~Synonyme_info().
hierarchie()
Sortie & Synonyme_info::hierarchie (Sortie & os) static
Ecriture de toute la hierarchie du synonyme considere sur un flux de sortie.
Parameters
(Sortie& os) flot de sortie
Returns
(Sortie&) le flot de sortie modifie
References nom(), and org_name_().
Referenced by Process::exit().
est_un_synonyme()
int Synonyme_info::est_un_synonyme (const char * nom) static
Test d'existence d'une classe du synonyme indique si il existe une classe T dont le Synonyme_info a.
le nom nom, alors est_un_synonyme renvoie 1
renvoie le pointeur nul sinon.
Parameters
(const char* nom) chaine de caractere associee a un synonyme
Returns
(int) code de retour (0 ou 1)
References nom(), and synonyme_info_from_name().
synonyme_info_from_name()
const Synonyme_info * Synonyme_info::synonyme_info_from_name (const char * synonyme_name) static
Methode statique qui renvoie un pointeur vers le Synonyme_info dont le nom est "synonyme_name".
Si synonyme_name n'est pas un synonyme, renvoie un pointeur nul.
Referenced by Probleme_base::equation(), Probleme_base::equation(), est_un_synonyme(), and Objet_U_ptr::typer().
ajouter_synonyme()
void Synonyme_info::ajouter_synonyme (const Synonyme_info & synonyme_info) static
Methode statique appelee par les constructeurs de Synonyme_info pour ajouter un nouveau synonyme a la liste des synonymes enregistres.
Verifie que le nom du synonyme n'existe pas encore.
References Type_info::est_un_type(), and Process::exit().
Referenced by Synonyme_info().