CEA TRUST Platform: Equation_IBM_proto Class Reference
Equation_IBM_proto Class Reference
Member Function Documentation
assembler_ibm_proto()
void Equation_IBM_proto::assembler_ibm_proto (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem)
References Source_base::contribuer_a_avec(), Perf_counters::end_count(), is_IBM(), and Discretisation_base::VIA_CONTRIBUER_AU_SECOND_MEMBRE.
Referenced by Convection_Diffusion_Temperature_IBM::assembler(), Navier_Stokes_IBM::assembler(), and Conduction_IBM::assembler().
set_param_ibm_proto()
void Equation_IBM_proto::set_param_ibm_proto (Param & param)
References Param::ajouter(), correction_variable_initiale_, and Param::OPTIONAL.
Referenced by Convection_Diffusion_Temperature_IBM::set_param(), Navier_Stokes_IBM::set_param(), and Conduction_IBM::set_param().
readOn_ibm_proto()
Entree & Equation_IBM_proto::readOn_ibm_proto (Entree & is, Equation_base & eq)
References Process::exit(), Nom::getSuffix(), i_source_pdf_, Nom::le_nom(), and Equation_base::sources().
initTimeStep_ibm_proto()
bool Equation_IBM_proto::initTimeStep_ibm_proto (double ddt)
References Source_PDF_base::calculer_variable_imposee(), and i_source_pdf_.
Referenced by Convection_Diffusion_Temperature_IBM::initTimeStep(), Navier_Stokes_IBM::initTimeStep(), and Conduction_IBM::initTimeStep().
derivee_en_temps_inco_ibm_proto()
DoubleTab & Equation_IBM_proto::derivee_en_temps_inco_ibm_proto (DoubleTab & derivee)
References Source_PDF_base::calculer(), Source_PDF_base::calculer_pdf(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Process::exit(), Source_PDF_base::get_modele(), i_source_pdf_, PDF_model::pdf_bilan(), and Source_PDF_base::set_sec_mem_pdf().
Referenced by Convection_Diffusion_Temperature_IBM::derivee_en_temps_inco_sources(), Navier_Stokes_IBM::derivee_en_temps_inco_sources(), and Conduction_IBM::derivee_en_temps_inco_sources().
preparer_calcul_ibm_proto()
void Equation_IBM_proto::preparer_calcul_ibm_proto ()
References champ_coeff_pdf_som_, Source_PDF_base::compute_coeff_matrice(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), i_source_pdf_, modify_initial_variable_ibm_proto(), and Source_PDF_base::updateChampRho().
Referenced by Convection_Diffusion_Temperature_IBM::preparer_calcul(), Navier_Stokes_IBM::preparer_calcul(), and Conduction_IBM::preparer_calcul().
modify_initial_variable_ibm_proto()
void Equation_IBM_proto::modify_initial_variable_ibm_proto (DoubleTab & variable)
References champ_coeff_pdf_som_, Source_PDF_base::correct_variable(), correction_variable_initiale_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and i_source_pdf_.
Referenced by Navier_Stokes_IBM::modify_initial_variable(), and preparer_calcul_ibm_proto().
get_correction_variable_initiale()
int Equation_IBM_proto::get_correction_variable_initiale () const inline
References correction_variable_initiale_.
get_i_source_pdf()
int Equation_IBM_proto::get_i_source_pdf () const inline
References i_source_pdf_.
get_champ_coeff_pdf_som()
const DoubleTab& Equation_IBM_proto::get_champ_coeff_pdf_som () const inline
References champ_coeff_pdf_som_.
set_champ_coeff_pdf_som()
void Equation_IBM_proto::set_champ_coeff_pdf_som (DoubleTab & coeff) inline
References champ_coeff_pdf_som_.
Referenced by Navier_Stokes_IBM::initTimeStep().
is_IBM()
bool Equation_IBM_proto::is_IBM () inline
References i_source_pdf_.
Referenced by assembler_ibm_proto(), and Convection_Diffusion_Temperature_IBM::verify_scheme().
OBS_PTR()
Equation_IBM_proto::OBS_PTR (Equation_base) protected
Referenced by Convection_Diffusion_Temperature_IBM_Turbulent::get_champ(), and Navier_Stokes_IBM_Turbulent::get_champ().
Member Data Documentation
champ_coeff_pdf_som_
DoubleTab Equation_IBM_proto::champ_coeff_pdf_som_ protected
Referenced by get_champ_coeff_pdf_som(), Navier_Stokes_IBM::initTimeStep(), Navier_Stokes_IBM::modify_initial_gradP(), modify_initial_variable_ibm_proto(), Navier_Stokes_IBM::preparer_calcul(), preparer_calcul_ibm_proto(), and set_champ_coeff_pdf_som().
i_source_pdf_
int Equation_IBM_proto::i_source_pdf_ = -1 protected
Referenced by derivee_en_temps_inco_ibm_proto(), get_i_source_pdf(), Navier_Stokes_IBM::initTimeStep(), initTimeStep_ibm_proto(), is_IBM(), modify_initial_variable_ibm_proto(), Navier_Stokes_IBM::preparer_calcul(), preparer_calcul_ibm_proto(), and readOn_ibm_proto().
correction_variable_initiale_
int Equation_IBM_proto::correction_variable_initiale_ = -1 protected
Referenced by get_correction_variable_initiale(), Navier_Stokes_IBM::modify_initial_variable(), modify_initial_variable_ibm_proto(), and set_param_ibm_proto().