CEA TRUST Platform: Sous_domaine_VF Class Reference
Sous_domaine_VF Class Reference
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
On suppose que chaque face a au plus deux elements voisins dans la domaine, ce qui est toujours le cas en maillage conforme.
Le tableau les_faces contient l'ensemble des faces du Domaine_dis qui appartiennent a ce sous-domaine, classees de la facon suivante : Les faces internes au sous-domaine Les faces internes au domaine, mais dont seul le premier element voisin appartient au sous-domaine Les faces internes au domaine, mais dont seul le deuxieme element voisin appartient au sous-domaine Les faces qui ne presentent qu'un element dans le domaine. Les separations sont indiquees respectivement par les variables premiere_face_bord_0, premiere_face_bord_1, et premiere_face_bord.
les_faces : nb_dim=1 dimension(0) = le nombre de faces du sous_domaine valeur de l'entier = indice dans les tableaux le_dom_VF->face_voisins_, le_dom_VF->face_sommets_,...
volumes_entrelaces(int face) renvoie le volume entrelace restreint au sous-domaine. Le numero de la face fait reference au tableau les_faces. Seuls sont stockes localement les volumes entrelaces differents de ceux du domaine.
Member Function Documentation
les_faces() [1/2]
const IntTab& Sous_domaine_VF::les_faces () const inline
References les_faces_.
Referenced by Perte_Charge_VEF::ajouter(), Op_Conv_EF_VEF_P1NC_Stab::completer(), and Perte_Charge_VEF::contribuer_a_avec().
les_faces() [2/2]
IntTab& Sous_domaine_VF::les_faces () inline
References les_faces_.
premiere_face_bord_0()
int Sous_domaine_VF::premiere_face_bord_0 () const inline
References premiere_face_bord_0_.
premiere_face_bord_1()
int Sous_domaine_VF::premiere_face_bord_1 () const inline
References premiere_face_bord_1_.
premiere_face_bord()
int Sous_domaine_VF::premiere_face_bord () const inline
References premiere_face_bord_.
volumes_entrelaces()
double Sous_domaine_VF::volumes_entrelaces (int face) const inline
Renvoie le volume entrelace restreint au sous-domaine. face est l'indice dans le tableau les_faces_.
References les_faces_, premiere_face_bord_, premiere_face_bord_0_, and volumes_entrelaces_.
Referenced by Perte_Charge_VEF::ajouter(), and Perte_Charge_VEF::contribuer_a_avec().
discretiser()
void Sous_domaine_VF::discretiser () override virtual
Genere les_faces en parcourant les faces du domaine_dis et en cherchant quels voisins appartiennent a le_sous_domaine.
Implements Sous_domaine_dis_base.
References Process::je_suis_maitre(), les_faces_, Process::mp_sum(), premiere_face_bord_, premiere_face_bord_0_, premiere_face_bord_1_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and volumes_entrelaces_.
OBS_PTR()
Sous_domaine_VF::OBS_PTR (Domaine_VF) protected
Member Data Documentation
les_faces_
IntTab Sous_domaine_VF::les_faces_ protected
Referenced by discretiser(), les_faces(), and volumes_entrelaces().
premiere_face_bord_0_
int Sous_domaine_VF::premiere_face_bord_0_ = -10 protected
Referenced by discretiser(), premiere_face_bord_0(), and volumes_entrelaces().
premiere_face_bord_1_
int Sous_domaine_VF::premiere_face_bord_1_ = -10 protected
Referenced by discretiser(), and premiere_face_bord_1().
premiere_face_bord_
int Sous_domaine_VF::premiere_face_bord_ = -10 protected
Referenced by discretiser(), premiere_face_bord(), and volumes_entrelaces().
volumes_entrelaces_
DoubleTab Sous_domaine_VF::volumes_entrelaces_ protected
Referenced by discretiser(), and volumes_entrelaces().