CEA TRUST Platform: VDF_discretisation Class Reference
VDF_discretisation Class Reference
Public Member Functions
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, OWN_PTR(Champ_Don_base)&champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, double temps, OWN_PTR(Champ_Fonc_base) &champ) const override
void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, OWN_PTR(Champ_Inc_base) &champ, const Nom &sous_type=NOM_VIDE) const override
void proprietes_physiques_fluide_Ostwald (const Domaine_dis_base &, Fluide_Ostwald &, const Navier_Stokes_std &, const Champ_Inc_base &) const override
Public Member Functions inherited from Discretisation_base
virtual void discretiser_champ (const Motcle &directive, const Domaine_dis_base &z, Nature_du_champ nature, const Noms &nom, const Noms &unite, int nb_comp, int nb_pas_dt, double temps, OWN_PTR(Champ_Inc_base)&champ, const Nom &sous_type=NOM_VIDE) const
virtual Nom get_name_of_type_for (const Nom &class_operateur, const Nom &type_operteur, const Equation_base &eqn, const OBS_PTR(Champ_base)&champ_supp=OBS_PTR(Champ_base)()) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Discretisation_base
static void creer_champ (OWN_PTR(Champ_Don_base)&ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (OWN_PTR(Champ_Fonc_base)&ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
static void creer_champ (OWN_PTR(Champ_Inc_base)&ch, const Domaine_dis_base &z, const Nom &type, const Nom &nom, const Nom &unite, int nb_comp, int nb_ddl, int nb_pas_dt, double temps, const Nom &directive=NOM_VIDE, const Nom &nom_discretisation=NOM_VIDE)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
discretiser_champ() [1/3]
void VDF_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, int nb_pas_dt, double temps, OWN_PTR(Champ_Inc_base) & champ, const Nom & sous_type = NOM_VIDE) const override
Discretisation d'un OWN_PTR(Champ_Inc_base) pour le VDF en fonction d'une directive de discretisation.
La directive est un Motcle comme "vitesse", "pression", "temperature", "champ_elem" (cree un champ de type P0 ...), ... Cette methode determine le type du champ a creer en fonction du type d'element et de la directive de discretisation. Elle determine ensuite le nombre de ddl et fixe l'ensemble des parametres du champ (type, nb_compo, nb_ddl, nb_pas_dt, nom(s), unite(s), nature du champ et attribue un temps) et associe le Domaine_dis au champ. Voir le code pour avoir la correspondance entre les directives et le type de champ cree.
References Discretisation_base::creer_champ(), Nom::debute_par(), Discretisation_base::DEMANDE_DESCRIPTION, Objet_U::dimension, Discretisation_base::discretiser_champ(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Discretisation_base::NOM_VIDE, Objet_U::que_suis_je(), Motcles::search(), and Discretisation_base::verifie_sous_type().
Referenced by distance_paroi_globale(), and y_plus().
discretiser_champ() [2/3]
void VDF_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, OWN_PTR(Champ_Fonc_base) & champ) const override
Idem que VDF_discretisation::discretiser_champ(.
.. , Champ_Inc) pour un Champ_Fonc.
discretiser_champ() [3/3]
void VDF_discretisation::discretiser_champ (const Motcle & directive, const Domaine_dis_base & z, Nature_du_champ nature, const Noms & noms, const Noms & unites, int nb_comp, double temps, OWN_PTR(Champ_Don_base)& champ) const override virtual
Idem que VDF_discretisation::discretiser_champ(.
.. , Champ_Inc) pour un Champ_Don.
Reimplemented from Discretisation_base.
domaine_cl_dis_type()
Nom VDF_discretisation::domaine_cl_dis_type () const inline override virtual
Implements Discretisation_base.
distance_paroi_globale()
void VDF_discretisation::distance_paroi_globale (const Schema_Temps_base & , Domaine_dis_base & , OWN_PTR(Champ_Fonc_base)&) const override virtual
Reimplemented from Discret_Thyd.
References discretiser_champ().
proprietes_physiques_fluide_Ostwald()
void VDF_discretisation::proprietes_physiques_fluide_Ostwald (const Domaine_dis_base & z, Fluide_Ostwald & le_fluide, const Navier_Stokes_std & eqn_hydr, const Champ_Inc_base &) const override virtual
discretise en VDF le fluide incompressible, donc K e N
Parameters
(Domaine_dis_base&) domaine a discretiser
(Fluide_Ostwald&) fluide a discretiser
(Champ_Inc_base&) vitesse
(Champ_Inc_base&) temperature
Reimplemented from Discret_Thyd.
References Champ_Ostwald_VDF::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_Ostwald::associer_fluide(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Navier_Stokes_std::inconnue(), Domaine_dis_base::nb_elem(), Champ_base::temps(), and Fluide_base::viscosite_dynamique().
vorticite()
void VDF_discretisation::vorticite (Domaine_dis_base & , const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)&) const
References Rotationnel_Champ_Face::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Champ_base::temps().
creer_champ_vorticite()
void VDF_discretisation::creer_champ_vorticite (const Schema_Temps_base & , const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)&) const override virtual
Reimplemented from Discret_Thyd.
References Rotationnel_Champ_Face::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Champ_Inc_base::domaine_dis_base(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), Field_base::nommer(), Schema_Temps_base::temps_courant(), and Champ_Inc_base::valeurs().
grad_u()
void VDF_discretisation::grad_u (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)&) const override virtual
Reimplemented from Discret_Thyd.
References grad_U_Champ_Face::associer_champ(), grad_U_Champ_Face::associer_domaine_Cl_dis_base(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), Field_base::nommer(), Champ_base::temps(), and Champ_Inc_base::valeurs().
critere_Q()
void VDF_discretisation::critere_Q (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)&) const override virtual
Reimplemented from Discret_Thyd.
References Critere_Q_Champ_Face::associer_champ(), Critere_Q_Champ_Face::associer_domaine_Cl_dis_base(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), and Champ_base::temps().
reynolds_maille()
void VDF_discretisation::reynolds_maille (const Domaine_dis_base & , const Fluide_base & , const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)&) const override virtual
Reimplemented from Discret_Thyd.
References Reynolds_maille_Champ_Face::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_Fonc_Face_VDF::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Domaine_VF::nb_faces(), Field_base::nommer(), Champ_base::temps(), and Fluide_base::viscosite_cinematique().
courant_maille()
void VDF_discretisation::courant_maille (const Domaine_dis_base & , const Schema_Temps_base & , const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)&) const override virtual
Reimplemented from Discret_Thyd.
References Courant_maille_Champ_Face::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Objet_U::dimension, Field_base::fixer_nb_comp(), Champ_Fonc_Face_VDF::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), Domaine_VF::nb_faces(), Field_base::nommer(), and Champ_base::temps().
taux_cisaillement()
void VDF_discretisation::taux_cisaillement (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)&) const override virtual
Reimplemented from Discret_Thyd.
References Taux_cisaillement_P0_VDF::associer_champ(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_nom_compo(), Field_base::fixer_unite(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), Field_base::nommer(), Champ_base::temps(), and Champ_Inc_base::valeurs().
y_plus()
void VDF_discretisation::y_plus (const Domaine_dis_base & , const Domaine_Cl_dis_base & , const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)&) const override virtual
Reimplemented from Discret_Thyd.
References Y_plus_Champ_Face::associer_champ(), Y_plus_Champ_Face::associer_domaine_Cl_dis_base(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Nom::debute_par(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), discretiser_champ(), MorEqn::equation(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), Domaine_dis_base::nb_elem(), Field_base::nommer(), Equation_base::probleme(), Objet_U::que_suis_je(), Champ_base::temps(), and Champ_Don_base::valeurs().
t_paroi()
void VDF_discretisation::t_paroi (const Domaine_dis_base & z, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base & ch_temp, OWN_PTR(Champ_Fonc_base)& ch) const override virtual
Reimplemented from Discret_Thermique.
References Field_base::add_synonymous(), T_paroi_Champ_P0_VDF::associer_champ(), T_paroi_Champ_P0_VDF::associer_domaine_Cl_dis_base(), Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), Field_base::fixer_nb_comp(), Champ_Fonc_P0_base::fixer_nb_valeurs_nodales(), Field_base::fixer_unite(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem(), Field_base::nommer(), Champ_base::temps(), and Champ_Inc_base::valeurs().
residu()
void VDF_discretisation::residu (const Domaine_dis_base & , const Champ_Inc_base & , OWN_PTR(Champ_Fonc_base)&) const override virtual
Reimplemented from Discretisation_base.
References Nom::debute_par(), Objet_U::dimension, Discretisation_base::discretiser_champ(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Objet_U::que_suis_je(), Champ_base::temps(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
is_vdf()
bool VDF_discretisation::is_vdf () const inline override virtual
Reimplemented from Discretisation_base.