CEA TRUST Platform: Sondes_Int Class Reference
Sondes_Int Class Reference
Public Member Functions
void mettre_a_jour (double temps, double tinit)
Detailed Description
See also
Sonde_Int Postraitement
Member Function Documentation
ouvrir_fichiers()
void Sondes_Int::ouvrir_fichiers () inline
Ouvre tous les fichiers associes a chacune des sondes de la liste.
Referenced by Postraitement::lire_motcle_non_standard().
fermer_fichiers()
void Sondes_Int::fermer_fichiers () inline
Ferme tous les fichiers des sondes de la liste.
Referenced by Postraitement::finir().
associer_post()
void Sondes_Int::associer_post (const Postraitement & post)
Associe un postraitement a la liste des sondes.
Referenced by Postraitement::lire_motcle_non_standard().
postraiter()
void Sondes_Int::postraiter (double temps)
Effectue le postraitement sur chacune des sondes de la liste.
Referenced by Postraitement::postraiter_sondes().
mettre_a_jour()
void Sondes_Int::mettre_a_jour (double temps, double tinit)
Effectue une mise a jour en temps de chacune des sondes de la liste.
Parameters
(double temps) le temps de mise a jour
(double tinit) le temps initial des sondes