CEA TRUST Platform: Champ_Q1NC Class Reference
Champ_Q1NC Class Reference
#include <Champ_Q1NC.h>
Public Member Functions
int remplir_coord_noeuds_et_polys (DoubleTab &positions, IntVect &polys) const override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &tab_valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &tab_valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
verifie_valeurs_cl()
void Champ_Q1NC::verifie_valeurs_cl () override virtual
Reimplemented from Champ_Inc_base.
References Equation_base::domaine_Cl_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Periodique::face_associee(), Cond_lim_base::frontiere_dis(), Domaine_Cl_dis_base::les_conditions_limites(), Field_base::nb_comp(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Champ_Inc_base::valeurs().
fixer_nb_valeurs_nodales()
int Champ_Q1NC::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_Inc_base.
References Champ_Inc_base::creer_tableau_distribue(), domaine_vef(), and Domaine_VF::md_vector_faces().
compo_normale_sortante()
int Champ_Q1NC::compo_normale_sortante (int num_face) const
References domaine_vef(), Domaine_VF::face_normales(), Field_base::nb_comp(), and Champ_Inc_base::valeurs().
trace()
DoubleTab & Champ_Q1NC::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Reimplemented from Champ_Inc_base.
References Champ_Q1NC_implementation::trace(), and Champ_Inc_base::valeurs().
cal_rot_ordre1()
void Champ_Q1NC::cal_rot_ordre1 (DoubleTab & vorticite)
References Domaine_32_64< _SIZE_ >::creer_tableau_elements(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), gradient(), Domaine_dis_base::nb_elem(), and Debog::verifier().
Referenced by Rotationnel_Champ_Q1NC::me_calculer().
gradient()
void Champ_Q1NC::gradient (DoubleTab & gradient_elem)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_vef(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Equation_base::inconnue(), Domaine_dis_base::nb_elem(), Domaine_VF::nb_faces(), Domaine_VF::premiere_face_int(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
Referenced by cal_rot_ordre1().
domaine_vef()
const Domaine_VEF & Champ_Q1NC::domaine_vef () const inline override virtual
Implements Champ_Q1NC_implementation.
Referenced by cal_rot_ordre1(), compo_normale_sortante(), fixer_nb_valeurs_nodales(), and gradient().
valeur_a_elem()
DoubleVect & Champ_Q1NC::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
References Champ_Q1NC_implementation::valeur_a_elem().
valeur_a_elem_compo()
double Champ_Q1NC::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
References Champ_Q1NC_implementation::valeur_a_elem_compo().
valeur_a_sommet_compo()
double Champ_Q1NC::valeur_a_sommet_compo (int sommet, int le_poly, int compo) const inline override virtual
renvoi la compo eme corrdonne des valeurs a l'element le_poly au sommet sommet
Reimplemented from Champ_base.
References Champ_Q1NC_implementation::valeur_a_sommet_compo().
valeur_aux_elems()
DoubleTab & Champ_Q1NC::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References Champ_Q1NC_implementation::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_Q1NC::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_base.
References Champ_Q1NC_implementation::valeur_aux_elems_compo().
valeur_aux_sommets()
DoubleTab & Champ_Q1NC::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
References Champ_Q1NC_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect & Champ_Q1NC::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const inline override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
References Champ_Q1NC_implementation::valeur_aux_sommets_compo().
remplir_coord_noeuds()
DoubleTab & Champ_Q1NC::remplir_coord_noeuds (DoubleTab & positions) const inline override virtual
Implements Champ_Inc_base.
References Champ_Q1NC_implementation::remplir_coord_noeuds().
remplir_coord_noeuds_et_polys()
int Champ_Q1NC::remplir_coord_noeuds_et_polys (DoubleTab & , IntVect &) const inline override virtual
NE FAIT RIEN Methode a surcharger.
Parameters
(DoubleTab&)
(IntVect&)
Returns
(int) renvoie toujours 0
Reimplemented from Champ_Inc_base.
References Champ_Q1NC_implementation::remplir_coord_noeuds_et_polys().