CEA TRUST Platform: Modele_turbulence_hyd_2_eq_base Class Reference
Modele_turbulence_hyd_2_eq_base Class Reference abstract
Public Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Modele_turbulence_hyd_base
void associer_eqn (const Equation_base &)
Equation_base & equation ()
virtual void imprimer (Sortie &) const
void lire_distance_paroi ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual int preparer_calcul ()
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
See also
Modele_turbulence_hyd_base
Member Function Documentation
set_param()
void Modele_turbulence_hyd_2_eq_base::set_param (Param & param) override virtual
Reimplemented from Modele_turbulence_hyd_base.
References Param::ajouter(), Param::ajouter_flag(), Param::ajouter_non_std(), K_MIN_, lquiet_, and Modele_turbulence_hyd_base::set_param().
lire_motcle_non_standard()
int Modele_turbulence_hyd_2_eq_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Transport_2eq_base::associer_modele_turbulence(), Process::exit(), get_set_eq_transport(), and Modele_turbulence_hyd_base::lire_motcle_non_standard().
verifie_loi_paroi()
void Modele_turbulence_hyd_2_eq_base::verifie_loi_paroi () virtual
References Process::exit(), and Objet_U::que_suis_je().
reprendre_generique()
int Modele_turbulence_hyd_2_eq_base::reprendre_generique (Entree & is)
References Process::exit(), TRUST_2_PDI::is_PDI_restart(), and TRUSTTab< _TYPE_, _SIZE_ >::jump().
nombre_d_equations()
virtual int Modele_turbulence_hyd_2_eq_base::nombre_d_equations () const inline virtual
get_EPS_MIN()
double Modele_turbulence_hyd_2_eq_base::get_EPS_MIN () const inline
References EPS_MIN_.
get_EPS_MAX()
double Modele_turbulence_hyd_2_eq_base::get_EPS_MAX () const inline
References EPS_MAX_.
get_OMEGA_MIN()
double Modele_turbulence_hyd_2_eq_base::get_OMEGA_MIN () const inline
References OMEGA_MIN_.
get_OMEGA_MAX()
double Modele_turbulence_hyd_2_eq_base::get_OMEGA_MAX () const inline
References OMEGA_MAX_.
get_Sigma_K()
double Modele_turbulence_hyd_2_eq_base::get_Sigma_K () const inline
References Sigma_K_.
get_Sigma_Eps()
double Modele_turbulence_hyd_2_eq_base::get_Sigma_Eps () const inline
References Sigma_Eps_.
get_Sigma_Omega()
double Modele_turbulence_hyd_2_eq_base::get_Sigma_Omega () const inline
References Sigma_Omega_.
get_K_MIN()
double Modele_turbulence_hyd_2_eq_base::get_K_MIN () const inline
References K_MIN_.
get_lquiet()
int Modele_turbulence_hyd_2_eq_base::get_lquiet () const inline
References lquiet_.
get_set_eq_transport()
virtual Transport_2eq_base& Modele_turbulence_hyd_2_eq_base::get_set_eq_transport () inline virtual
Referenced by get_set_unknown(), and lire_motcle_non_standard().
get_eq_transport()
const Transport_2eq_base & Modele_turbulence_hyd_2_eq_base::get_eq_transport () const virtual
Referenced by get_unknown().
get_set_unknown()
Champ_Inc_base & Modele_turbulence_hyd_2_eq_base::get_set_unknown ()
References get_set_eq_transport(), and Equation_base::inconnue().
get_unknown()
const Champ_Inc_base & Modele_turbulence_hyd_2_eq_base::get_unknown () const
References get_eq_transport(), and Equation_base::inconnue().
controler()
virtual void Modele_turbulence_hyd_2_eq_base::controler () pure virtual
OWN_PTR()
Modele_turbulence_hyd_2_eq_base::OWN_PTR (Transport_2eq_base) protected
Member Data Documentation
Sigma_K_
double Modele_turbulence_hyd_2_eq_base::Sigma_K_ =1. protected
Referenced by get_Sigma_K().
Sigma_Eps_
double Modele_turbulence_hyd_2_eq_base::Sigma_Eps_ =1.3 protected
Referenced by get_Sigma_Eps().
Sigma_Omega_
double Modele_turbulence_hyd_2_eq_base::Sigma_Omega_ =1./2. protected
Referenced by get_Sigma_Omega().
K_MIN_
double Modele_turbulence_hyd_2_eq_base::K_MIN_ = 1.e-20 protected
Referenced by get_K_MIN(), and set_param().
EPS_MIN_
double Modele_turbulence_hyd_2_eq_base::EPS_MIN_ = 1.e-20 protected
Referenced by get_EPS_MIN().
EPS_MAX_
double Modele_turbulence_hyd_2_eq_base::EPS_MAX_ = 1.e+10 protected
Referenced by get_EPS_MAX().
OMEGA_MIN_
double Modele_turbulence_hyd_2_eq_base::OMEGA_MIN_ = 1.e-5 protected
Referenced by get_OMEGA_MIN().
OMEGA_MAX_
double Modele_turbulence_hyd_2_eq_base::OMEGA_MAX_ = 1.e+20 protected
Referenced by get_OMEGA_MAX().
lquiet_
bool Modele_turbulence_hyd_2_eq_base::lquiet_ = false protected
Referenced by get_lquiet(), and set_param().