CEA TRUST Platform: Loi_Etat_base Class Reference
Loi_Etat_base Class Reference abstract
Public Member Functions
virtual void associer_fluide (const Fluide_Dilatable_base &)
void assoscier_probleme (const Probleme_base &pb)
void mettre_a_jour (double)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Elle definit un fluide dilatable
See also
Fluide_Dilatable_base, Classe abstraite dont toutes les lois d'etat doivent deriver., Methodes abstraites:, void calculer_coeff_T(), void calculer_masse_volumique()
Constructor & Destructor Documentation
Loi_Etat_base()
Loi_Etat_base::Loi_Etat_base ()
Member Function Documentation
assoscier_probleme()
void Loi_Etat_base::assoscier_probleme (const Probleme_base & pb)
Associe le probleme a la loi d'etat.
Parameters
(Fluide_Dilatable_base& fl) le fluide associe
mettre_a_jour()
void Loi_Etat_base::mettre_a_jour (double temps)
Met a jour la loi d'etat et le champ rho.
Parameters
(double temps) le temps de calcul
References tab_rho_n, and tab_rho_np1.
Referenced by initialiser_inco_ch(), and preparer_calcul().
calculer_nu()
void Loi_Etat_base::calculer_nu ()
Calcule la viscosite cinematique.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), and Debog::verifier().
ch_temperature() [1/2]
Champ_Don_base & Loi_Etat_base::ch_temperature ()
ch_temperature() [2/2]
const Champ_Don_base & Loi_Etat_base::ch_temperature () const
Renvoie le champ de le temperature.
associer_fluide()
void Loi_Etat_base::associer_fluide (const Fluide_Dilatable_base & fl) virtual
Associe le fluide a la loi d'etat.
Parameters
(Fluide_Dilatable_base& fl) le fluide associe
Reimplemented in Loi_Etat_Melange_GP_base, and Loi_Etat_GP_base.
Referenced by Loi_Etat_GP_base::associer_fluide(), and Loi_Etat_Melange_GP_base::associer_fluide().
preparer_calcul()
void Loi_Etat_base::preparer_calcul () virtual
Prepare le fluide au calcul.
Reimplemented in Loi_Etat_TPPI_QC_base, and Loi_Etat_TPPI_base.
References calculer_masse_volumique(), mettre_a_jour(), and remplir_T().
Referenced by Loi_Etat_TPPI_base::preparer_calcul().
abortTimeStep()
void Loi_Etat_base::abortTimeStep () virtual
References tab_rho_n, and tab_rho_np1.
initialiser_inco_ch()
void Loi_Etat_base::initialiser_inco_ch () virtual
Initialise l'inconnue de l'equation de chaleur : ne fai rien.
Reimplemented in Loi_Etat_Multi_GP_WC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Multi_GP_base, and Loi_Etat_GR_base.
References calculer_masse_volumique(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), mettre_a_jour(), tab_rho_n, and tab_rho_np1.
Referenced by Loi_Etat_Multi_GP_base::initialiser_inco_ch(), and Loi_Etat_rhoT_GP_QC::initialiser_inco_ch().
calculer_mu()
void Loi_Etat_base::calculer_mu () virtual
Calcule la viscosite.
Reimplemented in Loi_Etat_TPPI_base, Loi_Etat_Multi_GP_base, and Loi_Etat_Binaire_GP_base.
References Process::exit(), Champ_Don_base::mettre_a_jour(), and Objet_U::que_suis_je().
calculer_lambda()
void Loi_Etat_base::calculer_lambda () virtual
Calcule la conductivite.
Reimplemented in Loi_Etat_TPPI_base, Loi_Etat_Multi_GP_base, Loi_Etat_GR_base, Loi_Etat_GP_base, and Loi_Etat_Binaire_GP_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Pr_, TRUSTVect< _TYPE_, _SIZE_ >::size(), and Champ_Don_base::valeurs().
calculer_alpha()
void Loi_Etat_base::calculer_alpha () virtual
Calcule la diffusivite.
Reimplemented in Loi_Etat_TPPI_base, Loi_Etat_Multi_GP_base, Loi_Etat_GP_base, and Loi_Etat_Binaire_GP_base.
References TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Don_base::valeurs(), and Debog::verifier().
calculer_mu_sur_Sc()
void Loi_Etat_base::calculer_mu_sur_Sc () virtual
Ne fait rien Surcharge dans Loi_Etat_Melange_GP.
Reimplemented in Loi_Etat_Multi_GP_WC, Loi_Etat_Multi_GP_QC, and Loi_Etat_Binaire_GP_base.
calculer_nu_sur_Sc()
void Loi_Etat_base::calculer_nu_sur_Sc () virtual
Ne fait rien Surcharge dans Loi_Etat_Melange_Binaire.
Reimplemented in Loi_Etat_Multi_GP_WC, and Loi_Etat_Binaire_GP_base.
calculer_masse_volumique() [1/2]
void Loi_Etat_base::calculer_masse_volumique () virtual
Recalcule la masse volumique.
Reimplemented in Loi_Etat_GP_base, Loi_Etat_TPPI_WC_base, Loi_Etat_TPPI_QC_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_base, Loi_Etat_TPPI_WC_base, Loi_Etat_Multi_GP_WC, Loi_Etat_GP_WC, Loi_Etat_Binaire_GP_WC, Loi_Etat_TPPI_QC_base, Loi_Etat_rhoT_GR_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_GP_QC, Loi_Etat_Binaire_GP_QC, Loi_Etat_GR_base, and Loi_Etat_GP_base.
References compute_tab_rho(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and tab_rho_np1.
Referenced by Loi_Etat_GR_base::calculer_masse_volumique(), compute_tab_rho(), initialiser_inco_ch(), EDO_Pression_th_VDF::masse_totale(), and preparer_calcul().
calculer_H()
double Loi_Etat_base::calculer_H (double Pth_, double T_) const virtual
Cas gaz parfait : ne fait rien Cas gaz Reel : doit recalculer l'enthalpie a partir de la pression et la temperature.
Reimplemented in Loi_Etat_GR_base, and Loi_Etat_rhoT_GR_QC.
Drho_DP()
double Loi_Etat_base::Drho_DP (double , double) const virtual
Reimplemented in Loi_Etat_GR_base, and Loi_Etat_rhoT_GR_QC.
References Process::abort(), and Objet_U::que_suis_je().
Drho_DT()
double Loi_Etat_base::Drho_DT (double , double) const virtual
Reimplemented in Loi_Etat_GR_base, and Loi_Etat_rhoT_GR_QC.
References Process::abort(), and Objet_U::que_suis_je().
De_DP()
double Loi_Etat_base::De_DP (double , double) const virtual
Reimplemented in Loi_Etat_GR_base.
References Process::abort(), and Objet_U::que_suis_je().
De_DT()
double Loi_Etat_base::De_DT (double , double) const virtual
Reimplemented in Loi_Etat_GR_base.
References Process::abort(), and Objet_U::que_suis_je().
get_champ()
const Champ_base & Loi_Etat_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::get_champ().
creer_champ()
void Loi_Etat_base::creer_champ (const Motcle & motlu) inline override virtual
Implements Champs_compris_interface.
get_noms_champs_postraitables()
void Loi_Etat_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::liste_noms_compris().
has_champ() [1/2]
bool Loi_Etat_base::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
has_champ() [2/2]
bool Loi_Etat_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References Champs_compris_T< FIELD_TYPE >::has_champ().
type_fluide()
virtual const Nom Loi_Etat_base::type_fluide () const pure virtual
Implemented in Loi_Etat_GR_base, Loi_Etat_GP_base, and Loi_Etat_Binaire_GP_base.
initialiser()
virtual void Loi_Etat_base::initialiser () pure virtual
Implemented in Loi_Etat_GR_base, and Loi_Etat_GP_base.
remplir_T()
virtual void Loi_Etat_base::remplir_T () pure virtual
Implemented in Loi_Etat_GR_base, and Loi_Etat_GP_base.
Referenced by preparer_calcul().
calculer_Cp()
virtual void Loi_Etat_base::calculer_Cp () pure virtual
Implemented in Loi_Etat_TPPI_WC_base, Loi_Etat_TPPI_QC_base, Loi_Etat_Multi_GP_base, Loi_Etat_GR_base, Loi_Etat_GP_base, and Loi_Etat_Binaire_GP_base.
calculer_masse_volumique() [2/2]
virtual double Loi_Etat_base::calculer_masse_volumique (double , double) const pure virtual
Implemented in Loi_Etat_GR_base, Loi_Etat_Multi_GP_WC, Loi_Etat_GP_WC, Loi_Etat_rhoT_GR_QC, Loi_Etat_rhoT_GP_QC, Loi_Etat_Multi_GP_QC, Loi_Etat_GP_QC, Loi_Etat_TPPI_base, Loi_Etat_Multi_GP_base, Loi_Etat_Binaire_GP_WC, Loi_Etat_Binaire_GP_QC, Loi_Etat_Binaire_GP_base, and Loi_Etat_GP_base.
inverser_Pth()
virtual double Loi_Etat_base::inverser_Pth (double , double) pure virtual
Implemented in Loi_Etat_GP_WC, Loi_Etat_TPPI_base, Loi_Etat_GR_base, Loi_Etat_GP_base, Loi_Etat_Binaire_GP_base, and Loi_Etat_rhoT_GP_QC.
champs_compris()
Champs_compris& Loi_Etat_base::champs_compris () inline
References Milieu_base::champs_compris_.
temperature()
const DoubleTab& Loi_Etat_base::temperature () const inline
rho_n()
const DoubleTab& Loi_Etat_base::rho_n () const inline
References tab_rho_n.
Referenced by Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), and Loi_Etat_GP_QC::compute_tab_rho().
rho_np1()
const DoubleTab& Loi_Etat_base::rho_np1 () const inline
References tab_rho_np1.
Referenced by Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), and Loi_Etat_GP_QC::compute_tab_rho().
Prandt()
double Loi_Etat_base::Prandt () const inline
References Pr_.
OBS_PTR() [1/2]
Loi_Etat_base::OBS_PTR (Fluide_Dilatable_base) protected
Referenced by Loi_Etat_Multi_GP_base::associer_inconnue().
OBS_PTR() [2/2]
Loi_Etat_base::OBS_PTR (Probleme_base) protected
OWN_PTR()
Loi_Etat_base::OWN_PTR (Champ_Don_base) protected
compute_tab_rho()
void Loi_Etat_base::compute_tab_rho (DoubleTab & tab_rho) protected virtual
Reimplemented in Loi_Etat_GP_QC.
References calculer_masse_volumique(), TRUSTVect< _TYPE_, _SIZE_ >::size(), tab_rho_n, and tab_rho_np1.
Referenced by calculer_masse_volumique().
Friends And Related Function Documentation
Fluide_Quasi_Compressible
friend class Fluide_Quasi_Compressible friend
Fluide_Weakly_Compressible
friend class Fluide_Weakly_Compressible friend
Member Data Documentation
tab_rho_n
DoubleTab Loi_Etat_base::tab_rho_n protected
Referenced by abortTimeStep(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_TPPI_QC_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_TPPI_WC_base::calculer_masse_volumique(), compute_tab_rho(), Loi_Etat_GP_QC::compute_tab_rho(), Loi_Etat_GP_base::initialiser(), Loi_Etat_GR_base::initialiser(), initialiser_inco_ch(), Loi_Etat_GR_base::initialiser_inco_ch(), mettre_a_jour(), and rho_n().
tab_rho_np1
DoubleTab Loi_Etat_base::tab_rho_np1 protected
Referenced by abortTimeStep(), calculer_masse_volumique(), Loi_Etat_Binaire_GP_QC::calculer_masse_volumique(), Loi_Etat_Multi_GP_QC::calculer_masse_volumique(), Loi_Etat_rhoT_GP_QC::calculer_masse_volumique(), Loi_Etat_TPPI_QC_base::calculer_masse_volumique(), Loi_Etat_Binaire_GP_WC::calculer_masse_volumique(), Loi_Etat_GP_WC::calculer_masse_volumique(), Loi_Etat_Multi_GP_WC::calculer_masse_volumique(), Loi_Etat_TPPI_WC_base::calculer_masse_volumique(), compute_tab_rho(), Loi_Etat_GP_QC::compute_tab_rho(), initialiser_inco_ch(), Loi_Etat_GR_base::initialiser_inco_ch(), mettre_a_jour(), and rho_np1().
Pr_
double Loi_Etat_base::Pr_ protected
Referenced by calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), and Prandt().
debug
int Loi_Etat_base::debug protected