CEA TRUST Platform: Grid_Level_Data_template< _TYPE_ > Class Template Reference
Grid_Level_Data_template< _TYPE_ > Class Template Reference
Protected Member Functions
Sortie & printOn (Sortie &os) const override
Entree & readOn (Entree &is) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
const Nom & que_suis_je () const
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Grid_Level_Data_template()
template<typename _TYPE_ > Grid_Level_Data_template< _TYPE_ >::Grid_Level_Data_template
Referenced by Grid_Level_Data_template< _TYPE_ >::duplique().
Member Function Documentation
taille_memoire()
template<typename _TYPE_ > unsigned Grid_Level_Data_template< _TYPE_ >::taille_memoire () const inline override protected virtual
Implements Objet_U.
duplique()
template<typename _TYPE_ > int Grid_Level_Data_template< _TYPE_ >::duplique () const inline override protected virtual
Implements Objet_U.
References Process::exit(), Grid_Level_Data_template< _TYPE_ >::Grid_Level_Data_template(), and Objet_U::numero().
printOn()
template<typename _TYPE_ > Sortie& Grid_Level_Data_template< _TYPE_ >::printOn (Sortie & s) const inline override protected virtual
Ecriture de l'objet sur un flot de sortie Methode a surcharger.
Parameters
(Sortie& s) flot de sortie
Returns
(Sortie&) flot de sortie modifie
Reimplemented from Objet_U.
readOn()
template<typename _TYPE_ > Entree& Grid_Level_Data_template< _TYPE_ >::readOn (Entree & s) inline override protected virtual
Lecture d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree& s) flot d'entree
Returns
(Entree& s) flot d'entree modifie
Reimplemented from Objet_U.
initialize()
template<typename _TYPE_ > void Grid_Level_Data_template< _TYPE_ >::initialize (const Domaine_IJK & dom, int ghost, int additional_k_layers)
References IJK_Shear_Periodic_helpler::defilement_, Domaine_IJK::ELEM, Domaine_IJK::get_periodic_flag(), IJK_Shear_Periodic_helpler::rho_liq_ref_for_poisson_, and IJK_Shear_Periodic_helpler::rho_vap_ref_for_poisson_.
get_ghost_size()
template<typename _TYPE_ > int Grid_Level_Data_template< _TYPE_ >::get_ghost_size () const inline
References Grid_Level_Data_template< _TYPE_ >::ghost_size_.
get_domaine()
template<typename _TYPE_ > const Domaine_IJK& Grid_Level_Data_template< _TYPE_ >::get_domaine () const inline
References Grid_Level_Data_template< _TYPE_ >::domaine_ijk_.
compute_faces_coefficients_from_rho()
template<typename _TYPE_ > void Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_rho
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, Process::exit(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
compute_faces_coefficients_from_inv_rho()
template<typename _TYPE_ > void Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_inv_rho
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::allocate(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Domaine_IJK::ELEM, Process::exit(), Domaine_IJK::FACES_I, Domaine_IJK::FACES_J, Domaine_IJK::FACES_K, IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk().
compute_faces_coefficients_from_double_coeffs()
template<class _TYPE_ > template<class MY_TYPE > std::enable_if_t< std::is_same< MY_TYPE, float >::value, void > Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_double_coeffs (const Grid_Level_Data_template< double > & dbl_coeffs)
References Grid_Level_Data_template< _TYPE_ >::get_faces_coefficients(), and IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost().
get_update_rho()
template<typename _TYPE_ > IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> >& Grid_Level_Data_template< _TYPE_ >::get_update_rho () inline
References Grid_Level_Data_template< _TYPE_ >::ijk_rho_.
get_rho()
template<typename _TYPE_ > const IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> >& Grid_Level_Data_template< _TYPE_ >::get_rho () const inline
References Grid_Level_Data_template< _TYPE_ >::ijk_rho_.
get_update_x()
template<typename _TYPE_ > IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> >& Grid_Level_Data_template< _TYPE_ >::get_update_x () inline
References Grid_Level_Data_template< _TYPE_ >::ijk_x_.
get_update_rhs()
template<typename _TYPE_ > IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> >& Grid_Level_Data_template< _TYPE_ >::get_update_rhs () inline
References Grid_Level_Data_template< _TYPE_ >::ijk_rhs_.
get_update_residue()
template<typename _TYPE_ > IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> >& Grid_Level_Data_template< _TYPE_ >::get_update_residue () inline
References Grid_Level_Data_template< _TYPE_ >::ijk_residue_.
get_faces_coefficients()
template<typename _TYPE_ > const IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> >& Grid_Level_Data_template< _TYPE_ >::get_faces_coefficients () const inline
References Grid_Level_Data_template< _TYPE_ >::ijk_faces_coefficients_.
Referenced by Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_double_coeffs().
compute_faces_coefficients_from_rho_cst_i_cst_j_cst_k()
template<typename _TYPE_ > void Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_rho_cst_i_cst_j_cst_k protected
compute_faces_coefficients_from_inv_rho_cst_i_cst_j_cst_k()
template<typename _TYPE_ > void Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_inv_rho_cst_i_cst_j_cst_k protected
compute_faces_coefficients_from_rho_cst_i_cst_j_var_k()
template<typename _TYPE_ > void Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_rho_cst_i_cst_j_var_k protected
References IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost(), and IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::resize().
compute_faces_coefficients_from_inv_rho_cst_i_cst_j_var_k()
template<typename _TYPE_ > void Grid_Level_Data_template< _TYPE_ >::compute_faces_coefficients_from_inv_rho_cst_i_cst_j_var_k protected
References IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::ghost(), and IJKArray_with_ghost< _TYPE_, _TYPE_ARRAY_ >::resize().
VECT()
template<typename _TYPE_ > Grid_Level_Data_template< _TYPE_ >::VECT (ArrOfDouble_with_ghost) protected
Member Data Documentation
domaine_ijk_
template<typename _TYPE_ > Domaine_IJK Grid_Level_Data_template< _TYPE_ >::domaine_ijk_ protected
Referenced by Grid_Level_Data_template< _TYPE_ >::get_domaine().
ghost_size_
template<typename _TYPE_ > int Grid_Level_Data_template< _TYPE_ >::ghost_size_ protected
Referenced by Grid_Level_Data_template< _TYPE_ >::get_ghost_size().
perio_k_
template<typename _TYPE_ > bool Grid_Level_Data_template< _TYPE_ >::perio_k_ = false protected
uniform_
template<typename _TYPE_ > bool Grid_Level_Data_template< _TYPE_ >::uniform_[3] protected
ijk_rho_
template<typename _TYPE_ > IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> > Grid_Level_Data_template< _TYPE_ >::ijk_rho_ protected
Referenced by Grid_Level_Data_template< _TYPE_ >::get_rho(), and Grid_Level_Data_template< _TYPE_ >::get_update_rho().
ijk_faces_coefficients_
template<typename _TYPE_ > IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> > Grid_Level_Data_template< _TYPE_ >::ijk_faces_coefficients_ protected
Referenced by Grid_Level_Data_template< _TYPE_ >::get_faces_coefficients().
ijk_x_
template<typename _TYPE_ > IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> > Grid_Level_Data_template< _TYPE_ >::ijk_x_ protected
Referenced by Grid_Level_Data_template< _TYPE_ >::get_update_x().
ijk_rhs_
template<typename _TYPE_ > IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> > Grid_Level_Data_template< _TYPE_ >::ijk_rhs_ protected
Referenced by Grid_Level_Data_template< _TYPE_ >::get_update_rhs().
ijk_residue_
template<typename _TYPE_ > IJK_Field_template<_TYPE_,TRUSTArray<_TYPE_> > Grid_Level_Data_template< _TYPE_ >::ijk_residue_ protected
Referenced by Grid_Level_Data_template< _TYPE_ >::get_update_residue().