CEA TRUST Platform: Eval_Diff_VDF_Elem_Gen< DERIVED_T > Class Template Reference
Eval_Diff_VDF_Elem_Gen< DERIVED_T > Class Template Reference
Detailed Description
template<typename DERIVED_T>
class Eval_Diff_VDF_Elem_Gen< DERIVED_T >
See also
Eval_VDF_Elem, Evaluateur_VDF
Member Function Documentation
flux_face() [1/9]
template<typename DERIVED_T > template<typename BC , typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face (const DoubleTab & , const DoubleTab & , const int , const BC & , int , Type_Double &) const inline
flux_face() [2/9]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face (const DoubleTab & inco, const DoubleTab & val_b, const int face, const Dirichlet_entree_fluide & la_cl, const int num1, Type_Double & flux) const inline
References Dirichlet::val_imp().
flux_face() [3/9]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face (const DoubleTab & inco, const DoubleTab & val_b, const int face, const Scalaire_impose_paroi & la_cl, const int num1, Type_Double & flux) const inline
flux_face() [4/9]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face (const DoubleTab & inco, const DoubleTab & val_b, const int face, const Dirichlet_loi_paroi & la_cl, const int num1, Type_Double & flux) const inline
flux_face() [5/9]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face (const DoubleTab & , const DoubleTab & val_b, const int face, const Neumann_paroi & la_cl, const int num1, Type_Double & flux) const inline
References Neumann::flux_impose().
flux_face() [6/9]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face (const DoubleTab & inco, const DoubleTab & , const int face, const Periodique & la_cl, const int , Type_Double & flux) const inline
References Periodique::distance().
flux_face() [7/9]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face (const DoubleTab & inco, const DoubleTab & , const int face, const Echange_global_impose & la_cl, const int num1, Type_Double & flux) const inline
References Echange_global_impose::flux_exterieur_impose(), Echange_impose_base::h_imp(), Echange_global_impose::has_phi_ext(), and Echange_impose_base::T_ext().
flux_face() [8/9]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face (const DoubleTab & inco, const DoubleTab & val_b, const int face, const Dirichlet_paroi_fixe & , const int num1, Type_Double & flux) const inline
flux_face() [9/9]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face (const DoubleTab & inco, const int boundary_index, const int face, const int local_face, const Echange_externe_impose & la_cl, const int num1, Type_Double & flux) const inline
Approach to computing the equivalent heat transfer coefficient and heat flux.
The problem consists of a solid exchanging heat with an external medium. Heat transfer occurs via conduction within the solid and convection at the surface. Our objective is to express the total heat flux in terms of an equivalent heat transfer coefficient h_eq.
Step-by-step Demonstration:
Expression for convective flux at the surface:
where:
h_{imp} is the convective heat transfer coefficient (W/m2.K),
T_b is the temperature at the solid's surface,
T_{ext} is the external temperature.
Expression for conductive flux inside the solid:
where:
\lambda is the thermal conductivity of the solid (W/m.K),
e is the distance between the reference point inside the solid and the surface,
T_{elem} is the internal temperature of the solid element.
Equating the two flux expressions (continuity of heat transfer):
Solving for (T_b):
By adding these two equations:
**Extracting (\phi)**:
Defining the equivalent heat transfer coefficient (h_{eq}):
Final flux expression:
This demonstrates that the system can be treated as a single equivalent convection problem with h_eq, which accounts for both conduction inside the solid and convection at the surface, involving the VDF unknown T_{elem}
Case of Convection + Radiative Transfer:
When radiative heat transfer is also present, the substitution method used above is no longer valid because the radiative flux depends non-linearly on the surface temperature (T_b). The total flux at the surface then becomes:
where:
(\sigma) is the Stefan-Boltzmann constant,
(\varepsilon) is the emissivity of the surface,
(T_{ext}) is the effective radiative temperature of the surroundings.
Since this equation is non-linear in (T_b), we cannot directly substitute it as in the purely convective case. Instead, we solve for (T_b) using an iterative method such as Newton-Raphson. Once (T_b) is found, we use it to determine the heat flux.
References Echange_impose_base::emissivite(), Champ_front_calc_interne::face_map(), Echange_impose_base::h_imp(), Echange_impose_base::has_emissivite(), and Echange_impose_base::T_ext().
flux_faces_interne()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_faces_interne (const DoubleTab & inco, const int face, Type_Double & flux) const inline
coeffs_face() [1/8]
template<typename DERIVED_T > template<typename BC , typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face (const int , const int , const BC & , Type_Double & , Type_Double &) const inline
coeffs_face() [2/8]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face (const int face, const int , const Dirichlet_entree_fluide & la_cl, Type_Double & aii, Type_Double & ajj) const inline
coeffs_face() [3/8]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face (const int face, const int , const Scalaire_impose_paroi & la_cl, Type_Double & aii, Type_Double & ajj) const inline
coeffs_face() [4/8]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face (const int face, const int , const Dirichlet_loi_paroi & la_cl, Type_Double & aii, Type_Double & ajj) const inline
coeffs_face() [5/8]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face (const int face, const int , const Periodique & la_cl, Type_Double & aii, Type_Double & ajj) const inline
References Periodique::distance().
coeffs_face() [6/8]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face (const int face, const int num1, const Echange_global_impose & la_cl, Type_Double & aii, Type_Double & ajj) const inline
References Echange_global_impose::derivee_flux_exterieur_imposee(), Echange_impose_base::h_imp(), and Echange_global_impose::has_phi_ext().
coeffs_face() [7/8]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face (const int face, const int num1, const Dirichlet_paroi_fixe & , Type_Double & aii, Type_Double & ajj) const inline
coeffs_face() [8/8]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_face (const DoubleTab & inco, const int boundary_index, const int face, const int local_face, const int num1, const Echange_externe_impose & la_cl, Type_Double & aii, Type_Double & ajj) const inline
References Echange_impose_base::emissivite(), Echange_impose_base::h_imp(), and Echange_impose_base::has_emissivite().
coeffs_faces_interne()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::coeffs_faces_interne (const int face, Type_Double & aii, Type_Double & ajj) const inline
secmem_face() [1/5]
template<typename DERIVED_T > template<typename BC , typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_face (const int , const BC & , const int , Type_Double &) const inline
secmem_face() [2/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_face (const int face, const Dirichlet_entree_fluide & la_cl, const int num1, Type_Double & flux) const inline
References Dirichlet::val_imp().
secmem_face() [3/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_face (const int face, const Neumann_paroi & la_cl, const int num1, Type_Double & flux) const inline
References Neumann::flux_impose().
secmem_face() [4/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_face (const int face, const Echange_global_impose & la_cl, const int num1, Type_Double & flux) const inline
References Echange_global_impose::flux_exterieur_impose(), Echange_impose_base::h_imp(), Echange_global_impose::has_phi_ext(), and Echange_impose_base::T_ext().
secmem_face() [5/5]
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_face (const int boundary_index, const int face, const int local_face, const Echange_externe_impose & la_cl, const int num1, Type_Double & flux) const inline
References Echange_impose_base::h_imp(), and Echange_impose_base::T_ext().
secmem_faces_interne()
template<typename DERIVED_T > template<typename Type_Double > void Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_faces_interne (const int , Type_Double &) const inline
Member Data Documentation
IS_MULTD
template<typename DERIVED_T > constexpr bool Eval_Diff_VDF_Elem_Gen< DERIVED_T >::IS_MULTD = true static constexpr
IS_AXI
template<typename DERIVED_T > constexpr bool Eval_Diff_VDF_Elem_Gen< DERIVED_T >::IS_AXI = false static
IS_DEQUIV
template<typename DERIVED_T > constexpr bool Eval_Diff_VDF_Elem_Gen< DERIVED_T >::IS_DEQUIV = false static
IS_MODIF_DEQ
template<typename DERIVED_T > constexpr bool Eval_Diff_VDF_Elem_Gen< DERIVED_T >::IS_MODIF_DEQ = false static
IS_QUASI
template<typename DERIVED_T > constexpr bool Eval_Diff_VDF_Elem_Gen< DERIVED_T >::IS_QUASI = false static
IS_ANISO
template<typename DERIVED_T > constexpr bool Eval_Diff_VDF_Elem_Gen< DERIVED_T >::IS_ANISO = false static
IS_RANS
template<typename DERIVED_T > constexpr bool Eval_Diff_VDF_Elem_Gen< DERIVED_T >::IS_RANS = false static
IS_MULTI_SCALAR_DIFF
template<typename DERIVED_T > constexpr bool Eval_Diff_VDF_Elem_Gen< DERIVED_T >::IS_MULTI_SCALAR_DIFF = false static