CEA TRUST Platform: Assembleur_P_EF Class Reference
Assembleur_P_EF Class Reference
#include <Assembleur_P_EF.h>
Public Member Functions
int assembler_QC (const DoubleTab &, Matrice &) override
int assembler_rho_variable (Matrice &, const Champ_Don_base &rho) override
Public Member Functions inherited from Assembleur_base
int set_resoudre_en_u (int flag)
int set_resoudre_increment_pression (int flag)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_domaine_dis_base()
void Assembleur_P_EF::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis) override virtual
Implements Assembleur_base.
associer_domaine_cl_dis_base()
void Assembleur_P_EF::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis) override virtual
Implements Assembleur_base.
domaine_dis_base()
const Domaine_dis_base & Assembleur_P_EF::domaine_dis_base () const override virtual
Implements Assembleur_base.
domaine_Cl_dis_base()
const Domaine_Cl_dis_base & Assembleur_P_EF::domaine_Cl_dis_base () const override virtual
Implements Assembleur_base.
assembler()
int Assembleur_P_EF::assembler (Matrice & la_matrice) override virtual
Implements Assembleur_base.
References assembler_mat(), and Domaine_EF::volumes_sommets_thilde().
Referenced by assembler_QC().
assembler_rho_variable()
int Assembleur_P_EF::assembler_rho_variable (Matrice & mat, const Champ_Don_base & rho) override virtual
Assemblage de la matrice div(porosite/rho * grad P) Le type du champ "rho" a fournir depend de la discretisation (vdf, vef, p1b, .
..) Pour le front-tracking par exemple.
Reimplemented from Assembleur_base.
References assembler_mat(), Process::exit(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Champ_Don_base::valeurs().
assembler_QC()
int Assembleur_P_EF::assembler_QC (const DoubleTab & tab_rho, Matrice & matrice) override virtual
Assemble la matrice de pression pour un fluide quasi compressible laplacein(P) est remplace par div(grad(P)/rho).
Parameters
(DoubleTab& tab_rho) mass volumique
Returns
(int) renvoie toujours 1
Reimplemented from Assembleur_base.
References assembler(), Matrice_Bloc::get_bloc(), Matrice_Sym::get_est_definie(), Process::je_suis_maitre(), Matrice_Sym::set_est_definie(), Assembleur_base::set_resoudre_en_u(), and Assembleur_base::set_resoudre_increment_pression().
assembler_mat()
int Assembleur_P_EF::assembler_mat (Matrice & la_matrice, const DoubleVect & volumes_som, int incr_pression, int resoudre_en_u) override virtual
Reimplemented from Assembleur_base.
References Domaine_EF::Bij_thilde(), Matrice_Morse::coef(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Matrice_Bloc::dimensionner(), Matrice_Morse::dimensionner(), Domaine_dis_base::domaine(), Matrice_Bloc::get_bloc(), Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), Matrice_Morse::get_set_coeff(), Domaine_Cl_EF::get_type_sommet(), has_P_ref, Matrice_Morse_Sym::imprimer_formatte(), Process::je_suis_maitre(), les_coeff_pression, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_Cl_EF::modifie_gradient(), Process::mp_max(), Matrice_Base::multvect(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Domaine_Cl_dis_base::nb_faces_Cl(), Domaine_dis_base::nb_front_Cl(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Matrice_Sym::set_est_definie(), Assembleur_base::set_resoudre_en_u(), Assembleur_base::set_resoudre_increment_pression(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by assembler(), and assembler_rho_variable().
modifier_secmem()
int Assembleur_P_EF::modifier_secmem (DoubleTab & secmem) override virtual
Implements Assembleur_base.
References Cond_lim_base::champ_front(), Champ_front_base::derivee_en_temps(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Cond_lim_base::frontiere_dis(), Assembleur_base::get_resoudre_en_u(), Assembleur_base::get_resoudre_increment_pression(), Champ_front_base::instationnaire(), les_coeff_pression, Domaine_Cl_dis_base::les_conditions_limites(), Domaine_Cl_dis_base::nb_cond_lim(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Debog::verifier().
modifier_solution()
int Assembleur_P_EF::modifier_solution (DoubleTab & pression) override virtual
Implements Assembleur_base.
References has_P_ref, Process::mp_min(), and Debog::verifier().
completer()
void Assembleur_P_EF::completer (const Equation_base & Eqn) override virtual
Implements Assembleur_base.
equation()
const Equation_base & Assembleur_P_EF::equation () const inline
References Process::exit().
OBS_PTR() [1/3]
Assembleur_P_EF::OBS_PTR (Equation_base) protected
OBS_PTR() [2/3]
Assembleur_P_EF::OBS_PTR (Domaine_EF) protected
OBS_PTR() [3/3]
Assembleur_P_EF::OBS_PTR (Domaine_Cl_EF) protected
Member Data Documentation
les_coeff_pression
DoubleTab Assembleur_P_EF::les_coeff_pression protected
Referenced by assembler_mat(), and modifier_secmem().
has_P_ref
int Assembleur_P_EF::has_P_ref = 0 protected
Referenced by assembler_mat(), and modifier_solution().