CEA TRUST Platform: Op_Div_PolyMAC Class Reference
Op_Div_PolyMAC Class Reference
Public Member Functions
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &matrice) const override
void dimensionner (Matrice_Morse &matrice) const override
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe represente l'operateur de divergence La discretisation est PolyMAC On calcule la divergence d'un champ_P1NC (la vitesse)
See also
Operateur_Div_base
Member Function Documentation
associer()
void Op_Div_PolyMAC::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const Champ_Inc_base &) override virtual
Implements Operateur_base.
ajouter()
DoubleTab & Op_Div_PolyMAC::ajouter (const DoubleTab & vit, DoubleTab & div) const override virtual
Reimplemented from Operateur_Div_base.
Reimplemented in Op_Div_PolyMAC_P0.
References Operateur_Div_base::ajouter(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Operateur_base::flux_bords_, Operateur_base::has_interface_blocs(), Equation_base::milieu(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_bord(), Domaine_Poly_base::oriente_normale(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Debog::verifier().
Referenced by calculer().
calculer()
DoubleTab & Op_Div_PolyMAC::calculer (const DoubleTab & vit, DoubleTab & div) const override virtual
Reimplemented from Operateur_base.
References ajouter().
impr()
int Op_Div_PolyMAC::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Sortie::add_col(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Operateur_base::flux_bords_, Operateur_Div_base::Flux_div, Process::je_suis_maitre(), Frontiere_dis_base::le_nom(), Process::mp_sum(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Equation_base::probleme(), Probleme_base::schema_temps(), EcrFicPartage::syncfile(), and Schema_Temps_base::temps_courant().
volumique()
void Op_Div_PolyMAC::volumique (DoubleTab & div) const override virtual
Implements Operateur_Div_base.
References Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), and Domaine_VF::volumes().
dimensionner()
void Op_Div_PolyMAC::dimensionner (Matrice_Morse & mat) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
Reimplemented in Op_Div_PolyMAC_P0.
References Matrix_tools::allocate_morse_matrix(), Operateur_base::dimensionner(), Domaine_VF::face_voisins(), Operateur_base::has_interface_blocs(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Domaine_VF::nb_faces_tot(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
contribuer_a_avec()
void Op_Div_PolyMAC::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
Reimplemented in Op_Div_PolyMAC_P0.
References Operateur_base::contribuer_a_avec(), MorEqn::equation(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Operateur_base::has_interface_blocs(), Equation_base::milieu(), Domaine_VF::nb_faces(), and Milieu_base::porosite_face().
OBS_PTR() [1/2]
Op_Div_PolyMAC::OBS_PTR (Domaine_PolyMAC) protected
OBS_PTR() [2/2]
Op_Div_PolyMAC::OBS_PTR (Domaine_Cl_PolyMAC) protected