CEA TRUST Platform: IJK_Test_Multigrille Class Reference
IJK_Test_Multigrille Class Reference
#include <IJK_Test_Multigrille.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
interpreter()
Entree & IJK_Test_Multigrille::interpreter (Entree & is) override virtual
Implements Interprete.
References Param::ajouter(), Statistiques::begin_count(), Statistiques::end_count(), expression_rho_, expression_rhs_, fichier_reprise_rho_, fichier_reprise_rhs_, Multigrille_Adrien::initialize(), Statistiques::last_time(), Param::lire_avec_accolades(), Statistiques::new_counter(), Interprete_bloc::objet_global(), poisson_solver_, Objet_U::que_suis_je(), Param::REQUIRED, Multigrille_base::resoudre_systeme_IJK(), resu_, rho_, rhs_, Multigrille_Adrien::set_rho(), timestep_reprise_rho_, and timestep_reprise_rhs_.
Member Data Documentation
splitting_
Domaine_IJK IJK_Test_Multigrille::splitting_
rho_
IJK_Field_double IJK_Test_Multigrille::rho_
Referenced by interpreter().
rhs_
IJK_Field_double IJK_Test_Multigrille::rhs_
Referenced by interpreter().
resu_
IJK_Field_double IJK_Test_Multigrille::resu_
Referenced by interpreter().
poisson_solver_
Multigrille_Adrien IJK_Test_Multigrille::poisson_solver_
Referenced by interpreter().
fichier_reprise_rho_
Nom IJK_Test_Multigrille::fichier_reprise_rho_
Referenced by interpreter().
timestep_reprise_rho_
int IJK_Test_Multigrille::timestep_reprise_rho_ = -2
Referenced by interpreter().
fichier_reprise_rhs_
Nom IJK_Test_Multigrille::fichier_reprise_rhs_
Referenced by interpreter().
timestep_reprise_rhs_
int IJK_Test_Multigrille::timestep_reprise_rhs_ = -2
Referenced by interpreter().
expression_rho_
Nom IJK_Test_Multigrille::expression_rho_
Referenced by interpreter().
expression_rhs_
Nom IJK_Test_Multigrille::expression_rhs_
Referenced by interpreter().