CEA TRUST Platform: EDO_Pression_th_VEF_Gaz_Parfait Class Reference
EDO_Pression_th_VEF_Gaz_Parfait Class Reference
#include <EDO_Pression_th_VEF_Gaz_Parfait.h>
Public Member Functions
double resoudre (double) override
Detailed Description
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF et pour les gaz parfaits.
See also
Fluide_Quasi_Compressible EDO_Pression_th_base
Member Function Documentation
resoudre() [1/2]
double EDO_Pression_th_VEF_Gaz_Parfait::resoudre (double Pth_n) override
Resoud l'EDO.
Parameters
(double Pth_n) La pression a l'etape precedente
Returns
(double) La nouvelle valeur de la pression
References Champ_P1NC::calculer_integrale_volumique(), TRUSTVect< _TYPE_, _SIZE_ >::copy(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Dirichlet::val_imp_au_temps().
resoudre() [2/2]
void EDO_Pression_th_VEF_Gaz_Parfait::resoudre (DoubleTab & Pth_n) override
References Champ_P1NC::calculer_integrale_volumique(), TRUSTVect< _TYPE_, _SIZE_ >::copy(), Process::exit(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Objet_U::que_suis_je(), and Dirichlet::val_imp_au_temps().