CEA TRUST Platform: Moyenne_volumique Class Reference
Moyenne_volumique Class Reference
Public Member Functions
virtual void calculer_convolution_champ_elem (const Domaine_VF &domaine_source, const DoubleTab &champ_source, const DoubleTab &coords_to_compute, DoubleTab &resu) const
virtual void calculer_convolution_champ_face (const Domaine_VF &domaine_source, const DoubleTab &champ_source, const DoubleTab &coords_to_compute, DoubleTab &resu) const
Entree & interpreter (Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
virtual void calculer_convolution (const Domaine_VF &domaine_source, const DoubleTab &champ_source, const DoubleTab &coords_to_compute, DoubleTab &resu) const
int get_champ (const Nom &nom_pb, const Nom &nom_champ, OBS_PTR(Champ_base) &ref_champ)
void traiter_champs (const Motcles &noms_champs, const Nom &nom_pb, const Nom &nom_dom, const DoubleTab &coords, Format_Post_base &post, double temps, const Motcle &localisation)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de certains champs d'un probleme avec une fonction filtre arbitraire. On peut l'utiliser comme un interprete (voir Moyenne_volumique::interpreter()) ou n'importe ou a l'interieur du code comme ceci: Moyenne_volumique moy; is >> moy; // lecture de la fonction filtre moy.calculer_convolution_champ_elem/face(...)
Member Enumeration Documentation
Type
enum Moyenne_volumique::Type protected
Enumerator
ERROR
BOITE
CHAPEAU
GAUSSIENNE
PARSER
QUADRA
Member Function Documentation
interpreter()
Entree & Moyenne_volumique::interpreter (Entree & is) override virtual
Lecture des parametres dans le jeu de donnees.
Format attendu: Moyenne_volumique { nom_pb NOM_DU_PROBLEME (ou chercher les champs sources) nom_domaine DOMAINE_CIBLE (on evalue la convolution aux elements de ce domaine) noms_champs N CHAMP1 CHAMP2 ... (noms des champs a filtrer dans le probleme) [ nom_fichier_post NOM_SANS_EXTENSION ] (soit on donne nom_fichier et format_post, soit on donne fichier_post) [ format_post lata|lml|med|... ] (par defaut lata) [ fichier_post Format_Post_XXX { ... } ] (lecture par readOn du Format_Post_XXX) fonction_filtre ... (format : voir Moyenne_volumique::readOn()) [ localisation ELEM|SOM ] }
Implements Interprete.
References Param::ajouter(), Process::barrier(), Domaine_32_64< _SIZE_ >::calculer_centres_gravite(), Param::dictionnaire(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Format_Post_base::ecrire_domaine(), Format_Post_base::ecrire_entete(), Format_Post_base::ecrire_temps(), Process::exit(), Format_Post_base::finir(), get_champ(), Domaine_32_64< _SIZE_ >::les_sommets(), Param::lire_avec_accolades_depuis(), Domaine_32_64< _SIZE_ >::nb_elem(), Objet_U::nom_du_cas(), Interprete::objet(), Objet_U::que_suis_je(), Param::REQUIRED, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and traiter_champs().
calculer_convolution_champ_elem()
void Moyenne_volumique::calculer_convolution_champ_elem (const Domaine_VF & domaine_source, const DoubleTab & champ_source, const DoubleTab & coords_to_compute, DoubleTab & resu) const virtual
Calcule le produit de convolution entre la fonction filtre et le champ "champ_source" qui doit etre discretise aux elements de la "domaine_source".
Le tableau resu aura le meme nombre de colonnes que le tableau "champ_source", et le meme nombre de lignes que le tableau coords_to_compute. On suppose que la fonction filtre a un support inclu dans un cube de demi-cote box-size centre sur l'origine (on ne calcule pas la contribution des elements hors de ce cube).
References calculer_convolution(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_dis_base::domaine(), and Domaine_32_64< _SIZE_ >::nb_elem().
Referenced by traiter_champs().
calculer_convolution_champ_face()
void Moyenne_volumique::calculer_convolution_champ_face (const Domaine_VF & domaine_source, const DoubleTab & champ_source, const DoubleTab & coords_to_compute, DoubleTab & resu) const virtual
Idem que calculer_convolution_champ_elem pour un champ VDF aux faces.
(on suppose que le champ source est un champ vectoriel contenant pour chaque face la composante normale du champ a cette face) Pour chaque colonne du tableau champ_source, on remplit "dimension" colonnes du tableau resu : la premiere utilisant uniquement les faces de normale X, la deuxieme avec les faces de normale Y, etc...
References Process::exit().
eval_filtre()
void Moyenne_volumique::eval_filtre (const DoubleTab & coords, ArrOfDouble & result) const virtual
Evalue la fonction filtre en chaque coordonnee coord Methode appelee dans la classe Calcul_integrale_locale.
References BOITE, CHAPEAU, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Parser::eval(), Process::exit(), GAUSSIENNE, l_, PARSER, parser_, QUADRA, Parser::setVar(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and type_.
box_size()
double Moyenne_volumique::box_size () const inline
References box_size_.
traiter_champs()
void Moyenne_volumique::traiter_champs (const Motcles & noms_champs, const Nom & nom_pb, const Nom & nom_dom, const DoubleTab & coords, Format_Post_base & post, double temps, const Motcle & localisation) protected
fonction outil permettant de faire les calculs et d'ecrire le resultat dans un fichier lata pour tous les champs d'un type donne de la liste noms_champs.
Methode appelee par interpreter() type_champ=0 => traiter les champs aux elements type_champ=1 => traiter les champs aux faces
References Process::barrier(), calculer_convolution_champ_elem(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Format_Post_base::ecrire_champ(), Process::exit(), get_champ(), Nom::le_nom(), Domaine_dis_base::nb_elem(), Interprete::objet(), TRUSTTab< _TYPE_, _SIZE_ >::reset(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Domaine_VF::xp().
Referenced by interpreter().
get_champ()
int Moyenne_volumique::get_champ (const Nom & nom_pb, const Nom & nom_champ, OBS_PTR(Champ_base) & ref_champ) protected
Cherche le champ de nom "nom_champ" dans le probleme de nom "nom_pb" dans les objers de l'interprete.
Methode appelee par traiter_champs()
References Operateur_Statistique_tps_base::calculer_valeurs(), Probleme_base::get_champ(), Operateur_Statistique_tps_base::integrale(), Integrale_tps_Champ::le_champ_calcule(), Objet_U::le_nom(), Postraitement::les_statistiques(), Interprete::objet(), Probleme_base::postraitements(), and Champ_Don_base::valeurs().
Referenced by interpreter(), and traiter_champs().
calculer_convolution()
void Moyenne_volumique::calculer_convolution (const Domaine_VF & domaine_source, const DoubleTab & champ_source, const DoubleTab & coords_to_compute, DoubleTab & resu) const protected virtual
methode generale pour calculer une convolution a partir d'un champ aux elements ou aux faces.
Methode appelee par calculer_convolution_champ_elem() et calculer_convolution_champ_face()
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_max(), and Process::nproc().
Referenced by calculer_convolution_champ_elem().
Member Data Documentation
type_
Type Moyenne_volumique::type_ = ERROR protected
Referenced by eval_filtre().
l_
double Moyenne_volumique::l_ = -1. protected
Referenced by eval_filtre().
box_size_
double Moyenne_volumique::box_size_ = -100. protected
Referenced by box_size().
expression_parser_
Nom Moyenne_volumique::expression_parser_ protected
parser_
Parser Moyenne_volumique::parser_ mutable protected
Referenced by eval_filtre().