CEA TRUST Platform: Champ_Don_base Class Reference
Champ_Don_base Class Reference
Public Member Functions
void dimensionner (int, int)
int fixer_nb_valeurs_nodales (int nb_noeuds) override
int imprime (Sortie &, int) const override
virtual int initialiser (const double temps)
void mettre_a_jour (double temps) override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &valeurs, int le_poly) const
virtual double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
les proprietes physiques sont des Champs donnes
mais peuvent etre variables dans le temps dans l'espace
fonctions d'autres champs ...
See also
Champ_base OWN_PTR(Champ_Don_base) Champ_Fonc_base
Member Function Documentation
mettre_a_jour()
void Champ_Don_base::mettre_a_jour (double t) override virtual
Mise a jour en temps.
Parameters
(double) le temps de mise a jour
Reimplemented from Champ_base.
Reimplemented in Y_plus_Champ_P1NC, Taux_cisaillement_P0_VEF, T_paroi_Champ_P1NC, Rotationnel_Champ_Q1NC, Rotationnel_Champ_P1NC, h_conv_Champ_P1NC, grad_U_Champ_P1NC, grad_T_Champ_P1NC, Critere_Q_Champ_P1NC, Correlation_Vec_Sca_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Fonc_Q1NC, Champ_Fonc_Q1_VEF, Champ_Fonc_P1NC, Champ_Fonc_P1_VEF, Champ_Fonc_P1_isoP1Bulle, Y_plus_Champ_Face, Taux_cisaillement_P0_VDF, T_paroi_Champ_P0_VDF, Rotationnel_Champ_Face, Reynolds_maille_Champ_Face, grad_U_Champ_Face, Critere_Q_Champ_Face, Courant_maille_Champ_Face, Correlation_Vec_Sca_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Fonc_Q1_VDF, Champ_Fonc_P1_VDF, Champ_Fonc_Face_VDF, grad_U_Champ_Face_PolyMAC, grad_Champ_Face_PolyMAC_P0, Champ_Fonc_Tabule_Elem_PolyMAC, Champ_Fonc_Som_PolyMAC, Champ_Fonc_Face_PolyMAC, Champ_Fonc_Elem_PolyMAC_P0_TC, Champ_Fonc_reprise, Champ_Fonc_Q1_MED, Champ_Fonc_P1_MED, Champ_Fonc_P0_MED, Champ_Fonc_MED, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, Champ_Fonc_Elem_PolyMAC_P0_rot, Champ_Ostwald_VEF, Champ_Ostwald_VDF, Champ_Ostwald, Champ_Fonc_MED_Tabule, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, Champ_Parametrique, and Champ_Fonc_base.
References Champ_base::changer_temps(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), and valeurs_.
Referenced by Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_base::calculer_mu(), Loi_Etat_Multi_GP_base::calculer_mu(), initialiser(), Champ_Parametrique::mettre_a_jour(), Champ_Ostwald_VDF::mettre_a_jour(), Champ_Ostwald_VEF::mettre_a_jour(), Fluide_Dilatable_base::mettre_a_jour(), and resetTime().
dimensionner()
void Champ_Don_base::dimensionner (int nb_noeuds, int nb_compo)
Fixe le nombre de composantes et le nombre de valeurs nodales.
Parameters
(int) le nombre de noeud par composante du champ (le nombre de dl par composante)
(int) le nombre de composante du champ
References Field_base::fixer_nb_comp(), and fixer_nb_valeurs_nodales().
Referenced by Op_Conv_EF::calculer_dt_stab(), Champ_front_contact_VEF::connectivity_failed(), Fluide_Dilatable_base::set_Cp(), and Tayl_Green::Tayl_Green().
imprime()
int Champ_Don_base::imprime (Sortie & os, int ncomp) const override virtual
NE FAIT RIEN.
EXIT ! A surcharger dans les classes derivees
Implements Champ_base.
Reimplemented in Champ_Fonc_Face_VDF, Champ_Parametrique, Champ_Fonc_Q1_VEF, Champ_Fonc_P1NC, Champ_Fonc_Q1_VDF, Champ_Fonc_P0_VDF, and Champ_Fonc_Som_PolyMAC.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Champ_Parametrique::imprime().
fixer_nb_valeurs_nodales()
int Champ_Don_base::fixer_nb_valeurs_nodales (int nb_noeuds) override virtual
Fixe le nombre de degres de liberte par composante.
Parameters
(int nb_noeuds) le nombre de degre de liberte par composante
Reimplemented from Champ_base.
Reimplemented in Champ_Fonc_Q1NC, Champ_Fonc_P1NC, Champ_Fonc_P1_isoP1Bulle, Champ_Fonc_Face_VDF, Champ_Ostwald, Champ_Parametrique, Champ_Fonc_base, grad_Champ_Face_PolyMAC_P0, and Champ_Fonc_Face_PolyMAC.
References Field_base::nb_compo_, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and valeurs_.
Referenced by dimensionner(), and Champ_Parametrique::fixer_nb_valeurs_nodales().
reprendre()
int Champ_Don_base::reprendre (Entree &) override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees
Reimplemented from Objet_U.
Reimplemented in Champ_Parametrique, and Champ_Fonc_base.
Referenced by Champ_Parametrique::reprendre().
sauvegarder()
int Champ_Don_base::sauvegarder (Sortie &) const override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees
Reimplemented from Objet_U.
Reimplemented in Champ_Parametrique, and Champ_Fonc_base.
Referenced by Champ_Parametrique::sauvegarder().
resetTime()
void Champ_Don_base::resetTime (double time) override virtual
See comments in Probleme_base_interface_proto::resetTime_impl() Here we update.
Implements Champ_base.
Reimplemented in Champ_Parametrique.
References mettre_a_jour().
Referenced by Champ_Parametrique::resetTime().
valeurs() [1/6]
DoubleTab& Champ_Don_base::valeurs () inline override virtual
Surcharge Champ_base::valeurs() Renvoie le tableau des valeurs.
Returns
(DoubleTab&) le tableau des valeurs du champs
Implements Champ_Proto.
Reimplemented in Champ_Input_P0_Composite, Champ_Input_P0_Composite, Champ_Input_P0_Composite, Champ_Fonc_reprise, Champ_Fonc_MED, Champ_Parametrique, and Champ_Input_P0_Composite.
References valeurs_.
Referenced by Champ_Fonc_base::affecter_(), Champ_Fonc_Face_PolyMAC::affecter_(), Champ_Ostwald::affecter_(), Champ_Fonc_Face_VDF::affecter_(), Champ_Fonc_Elem_DG::affecter_(), Champ_Uniforme::affecter_(), Champ_Uniforme_Morceaux::affecter_(), Champ_Fonc_Elem_PolyMAC::affecter_(), Champ_Fonc_base::affecter_compo(), Op_Dift_VDF_base::ajoute_terme_pour_axi_turb(), Op_Dift_Stab_VEF_Face::ajouter(), Op_Dift_standard_VEF_Face::ajouter(), Op_Dift_VEF_Face::ajouter(), Op_Dift_VEF_Face_Q1::ajouter(), Op_Dift_VEF_P1NCP1B_Face::ajouter(), Perte_Charge_PolyMAC::ajouter(), Perte_Charge_Reguliere_VEF_P1NC::ajouter(), Perte_Charge_VEF::ajouter(), Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Th_TdivU_VEF_Face::ajouter(), Perte_Charge_Reguliere_VDF_Face::ajouter_(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), Terme_Source_inc_th_VDF_Face::ajouter_blocs(), Perte_Charge_PolyMAC::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), Perte_Charge_VDF_base::ajouter_blocs(), Solveur_Masse_base::appliquer(), Masse_DG_base::appliquer_coef(), Masse_PolyMAC_base::appliquer_coef(), Convection_Diffusion_Fluide_Dilatable_Proto::assembler_impl(), Assembleur_P_VEFPreP1B::assembler_rho_variable(), Assembleur_P_EF::assembler_rho_variable(), Eval_Gravite_VDF_Face::associer(), Eval_Puiss_Th_DG_Elem::associer_champs(), Eval_Puiss_Th_EF::associer_champs(), Eval_Puiss_Th_PolyMAC_Elem::associer_champs(), Eval_Source_C_PolyMAC_Elem::associer_champs(), Eval_Dirac_VDF_Elem::associer_champs(), Eval_Puiss_Neutr_VDF_Elem::associer_champs(), Eval_Puiss_Th_VDF_Elem::associer_champs(), Eval_Source_C_VDF_Elem::associer_champs(), Eval_Dirac_VEF_Face::associer_champs(), Eval_Puiss_Th_VEF_Face::associer_champs(), Eval_Source_C_VEF_Face::associer_champs(), Eval_Dift_VDF::associer_diff_turb(), Eval_Puiss_Th_QC_EF::associer_puissance(), Eval_Puiss_Th_QC_VEF_Face::associer_puissance(), Eval_Puiss_Th_QC_VDF_Elem::associer_puissance(), grad_Champ_Face_PolyMAC_P0::calc_gradfve(), Champ_front_contact_VEF::calcul_coeff_amort(), Champ_front_contact_VEF::calcul_grads_locaux(), Champ_P1NC::calcul_h_conv(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Loi_Etat_base::calculer_alpha(), Loi_Etat_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_alpha(), Loi_Etat_Multi_GP_base::calculer_Cp(), Loi_Etat_TPPI_QC_base::calculer_Cp(), Loi_Etat_TPPI_WC_base::calculer_Cp(), Modele_turbulence_scal_Prandtl::calculer_diffusivite_turbulente(), Op_Diff_DG_base::calculer_dt_stab(), Op_Conv_EF::calculer_dt_stab(), Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_VEF_base::calculer_dt_stab(), Op_Dift_VEF_base::calculer_dt_stab(), Op_Dift_VDF_Face_base::calculer_dt_stab(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_axi(), Op_Dift_VDF_Elem_base::calculer_dt_stab_elem_var_axi(), Op_Dift_VEF_base::calculer_dt_stab_P1NCP1B(), Traitement_particulier_NS_EC::calculer_Ec(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Echange_contact_Correlation_VEF::calculer_h_solide(), Echange_contact_Correlation_VDF::calculer_h_solide(), Turbulence_paroi_base::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Loi_Etat_base::calculer_lambda(), Loi_Etat_GP_base::calculer_lambda(), Loi_Etat_GR_base::calculer_lambda(), Loi_Etat_Multi_GP_base::calculer_lambda(), Loi_Etat_Multi_GP_WC::calculer_masse_molaire(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_Profils_VDF::calculer_moyenne_spatiale_nut(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Loi_Etat_Binaire_GP_base::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_mu_sur_Sc(), Loi_Etat_base::calculer_nu(), Loi_Etat_Binaire_GP_base::calculer_nu_sur_Sc(), Loi_Etat_Multi_GP_WC::calculer_nu_sur_Sc(), Op_Dift_VEF_base::calculer_pour_post(), Navier_Stokes_std::calculer_pression_hydrostatique(), Convection_Diffusion_Temperature::calculer_rho_cp_T(), Loi_Etat_Multi_GP_WC::calculer_tab_Cp(), Op_Correlation::calculer_valeurs(), Echange_global_impose::champ_exterieur(), Echange_couplage_thermique::champ_exterieur(), Navier_Stokes_Fluide_Dilatable_base::completer(), Sortie_libre_pression_imposee_QC::completer(), Sortie_libre_pression_imposee::completer(), Sortie_libre_pression_moyenne_imposee::completer(), Source_WC_Chaleur_VEF::compute_interpolate_gradP(), Paroi_scal_hyd_base_EF::compute_nusselt(), Paroi_scal_hyd_base_VDF::compute_nusselt(), Paroi_scal_hyd_base_VEF::compute_nusselt(), Interpolation_IBM_mean_gradient_proto::computeSommetsVoisins(), Champ_front_contact_VEF::connectivity_failed(), Perte_Charge_PolyMAC::contribuer_a_avec(), Op_Dift_Stab_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_a_avec(), Op_Dift_VEF_Face_Q1::contribuer_a_avec(), Perte_Charge_Reguliere_VEF_P1NC::contribuer_a_avec(), Perte_Charge_VEF::contribuer_a_avec(), Op_Dift_VEF_Face::contribuer_au_second_membre(), TRUSTProblem_Concentration_Gen< _DERIVED_TYPE_, _EQUATION_TYPE_, _MEDIUM_TYPE_ >::create_constituants_echaines(), Champ_Fonc_base::data_a_sauvegarder(), Op_Correlation::data_a_sauvegarder(), Op_Ecart_type::data_a_sauvegarder(), Op_Moyenne::data_a_sauvegarder(), Discret_Thyd::diametre_hydraulique_face(), Convection_Diffusion_Temperature::ecrire_fichier_pena_th(), Champ_val_tot_sur_vol_base::evaluer(), Moyenne_volumique::get_champ(), Convection_Diffusion_Temperature::get_time_factor(), Sortie_libre_Gradient_Pression_impose::grad_P_imp(), Sortie_libre_Gradient_Pression_libre_VEF::Grad_P_lib_VEF(), Sortie_libre_Gradient_Pression_libre_VEFPreP1B::Grad_P_lib_VEFPreP1B(), PolyMAC_P0_discretisation::grad_u(), Champ_Fonc_P1_EF::imprime(), Champ_Fonc_Q1_EF::imprime(), Champ_Fonc_Som_PolyMAC::imprime(), Champ_Fonc_Q1_VDF::imprime(), Champ_Fonc_Q1_VEF::imprime(), Fluide_base::initialiser(), Op_Correlation::initialiser(), Op_Ecart_type::initialiser(), Op_Moyenne::initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), Ecrire_Champ_MED::interpreter(), Modele_turbulence_hyd_base::limiter_viscosite_turbulente(), Champ_Fonc_MED_Table_Temps::lire(), Champ_Fonc_t::me_calculer(), Champ_Tabule_Temps::me_calculer(), Champ_Uniforme_Morceaux_Tabule_Temps::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_TC::me_calculer(), Champ_Ostwald_VDF::me_calculer(), Champ_Ostwald_VEF::me_calculer(), grad_Champ_Face_PolyMAC_P0::me_calculer(), grad_U_Champ_Face_PolyMAC::me_calculer(), grad_U_Champ_Face::me_calculer(), T_paroi_Champ_P0_VDF::me_calculer(), grad_U_Champ_P1NC::me_calculer(), T_paroi_Champ_P1NC::me_calculer(), Rotationnel_Champ_Q1_EF::me_calculer(), Y_plus_Champ_Q1::me_calculer(), Critere_Q_Champ_Face::me_calculer(), Rotationnel_Champ_Face::me_calculer(), Y_plus_Champ_Face::me_calculer(), Critere_Q_Champ_P1NC::me_calculer(), grad_T_Champ_P1NC::me_calculer(), h_conv_Champ_P1NC::me_calculer(), Rotationnel_Champ_P1NC::me_calculer(), Rotationnel_Champ_Q1NC::me_calculer(), Y_plus_Champ_P1NC::me_calculer(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_2D(), Champ_Fonc_Elem_PolyMAC_P0_rot::me_calculer_3D(), Discretisation_base::mesh_numbering(), Champ_Fonc_Tabule_Morceaux::mettre_a_jour(), Champ_Fonc_Tabule_Morceaux_Interp::mettre_a_jour(), Champ_Fonc_base::mettre_a_jour(), Champ_Fonc_Tabule_P0_EF::mettre_a_jour(), Champ_Fonc_Interp::mettre_a_jour(), Champ_Fonc_Tabule_Elem_PolyMAC::mettre_a_jour(), Fluide_base::mettre_a_jour(), Modele_turbulence_scal_Prandtl::mettre_a_jour(), Champ_Fonc_Tabule_P0_VDF::mettre_a_jour(), Correlation_Vec_Sca_VDF::mettre_a_jour(), Courant_maille_Champ_Face::mettre_a_jour(), Reynolds_maille_Champ_Face::mettre_a_jour(), Taux_cisaillement_P0_VDF::mettre_a_jour(), Champ_Fonc_Tabule_P0_VEF::mettre_a_jour(), Correlation_Vec_Sca_VEF::mettre_a_jour(), Taux_cisaillement_P0_VEF::mettre_a_jour(), Iterateur_PolyMAC_Elem< _TYPE_ >::modifier_flux(), Op_VEF_Face::modifier_flux(), Champ_Fonc_P0_base::moyenne(), Champ_Parametrique::nb_valeurs_nodales(), Assembleur_P_VDF::remplir(), Champ_Fonc_base::reprendre(), VDF_discretisation::residu(), VEF_discretisation::residu(), PolyMAC_P0_discretisation::residu(), PolyMAC_P0P1NC_discretisation::residu(), Champ_Fonc_base::sauvegarder(), Discret_Thyd::section_passage(), Ch_input_uniforme::setValue(), Fluide_Dilatable_base::temperature(), Champ_Fonc_P0_base::trace(), Champ_Fonc_Face_VDF::trace(), Champ_Fonc_P1_isoP1Bulle::trace(), Champ_Fonc_P1NC::trace(), Champ_Fonc_Q1NC::trace(), Champ_Fonc_Interp::update_fields(), grad_Champ_Face_PolyMAC_P0::update_ge(), Op_Diff_DG_base::update_nu(), Op_Diff_PolyMAC_base::update_nu(), grad_Champ_Face_PolyMAC_P0::update_tab_grad(), Champ_Fonc_P0_base::valeur_au_bord(), Champ_som_lu::valeur_aux_elems(), Champ_som_lu_VEF::valeur_aux_elems(), Champ_som_lu::valeur_aux_elems_compo(), Champ_som_lu_VEF::valeur_aux_elems_compo(), Champ_Generique_Ecart_Type::valeurs(), Op_Moyenne::valeurs(), Champ_Fonc_Tabule::valeurs(), Champ_Input_P0_Composite::valeurs(), Champ_Parametrique::valeurs(), Champ_Fonc_MED::valeurs(), Op_Correlation::valeurs_ab(), Op_Ecart_type::valeurs_carre(), Champ_Generique_Ecart_Type::valeurs_carre(), Discretisation_base::volume_maille(), VDF_discretisation::y_plus(), and PolyMAC_P0P1NC_discretisation::y_plus().
valeurs() [2/6]
const DoubleTab& Champ_Don_base::valeurs () const inline override virtual
Implements Champ_Proto.
Reimplemented in Champ_Fonc_reprise, Champ_Fonc_MED, and Champ_Parametrique.
References valeurs_.
affecter_compo()
Champ_base & Champ_Don_base::affecter_compo (const Champ_base & , int) override virtual
Provoque une erreur ! A surcharger par les classes derivees ! non virtuelle pure par commoditees de developpement !
Implements Champ_base.
Reimplemented in Champ_Parametrique, and Champ_Fonc_base.
Referenced by Champ_Parametrique::affecter_compo().
initialiser()
int Champ_Don_base::initialiser (const double un_temps) virtual
NE FAIT RIEN.
A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire
Reimplemented in Champ_Fonc_Interp, Champ_Fonc_Tabule, Champ_Ostwald_VEF, Champ_Fonc_Tabule_P0_VEF, Champ_Ostwald_VDF, Champ_Fonc_Tabule_P0_VDF, Champ_Ostwald, Champ_Fonc_Tabule_Elem_PolyMAC, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, Champ_Parametrique, Champ_Fonc_Tabule_Morceaux_Interp, Champ_Fonc_Tabule_Morceaux, Champ_Fonc_Tabule_P0_EF, and Champ_Input_P0_Composite.
References mettre_a_jour().
Referenced by Champ_Input_P0_Composite::initialiser(), TRUSTChamp_Morceaux_generique< _TYPE_ >::initialiser(), Champ_Fonc_Tabule::initialiser(), and Champ_Fonc_Interp::initialiser().
set_instationnaire()
virtual void Champ_Don_base::set_instationnaire (bool flag) inline virtual
Referenced by Champ_Fonc_MED_Tabule::mettre_a_jour().
instationnaire()
virtual bool Champ_Don_base::instationnaire () const inline virtual
Reimplemented in Champ_Fonc_MED_Table_Temps, and Champ_Parametrique.
Referenced by Champ_Parametrique::instationnaire().
nb_valeurs_nodales()
int Champ_Don_base::nb_valeurs_nodales () const inline override virtual
Renvoie le nombre de degre de liberte par composante: le nombre de noeuds.
Reimplemented from Champ_base.
Reimplemented in Champ_Parametrique.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), and valeurs_.
Referenced by Champ_Ostwald_VDF::calculer_mu(), Champ_Ostwald_VEF::calculer_mu(), Champ_Composite::fill_valeurs_composite(), Champ_Ostwald_VEF::init_mu(), Fluide_base::initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), and Fluide_base::mettre_a_jour().
operator DoubleTab &()
Champ_Don_base::operator DoubleTab & () delete
operator const DoubleTab &()
Champ_Don_base::operator const DoubleTab & () const delete
affecter_()
Champ_base & Champ_Don_base::affecter_ (const Champ_base &) override protected virtual
Provoque une erreur ! A surcharger par les classes derivees ! non virtuelle pure par commoditees de developpement !
Implements Champ_base.
Reimplemented in Champ_Fonc_Elem_PolyMAC, TRUSTChamp_Morceaux_generique< _TYPE_ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::UNIFORME >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TXYZ >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC >, TRUSTChamp_Morceaux_generique< Champ_Morceaux_Type::FONC_TABULE >, TRUSTChamp_Don_generique< _TYPE_ >, TRUSTChamp_Don_generique< Champ_Don_Type::LU >, TRUSTChamp_Don_generique< Champ_Don_Type::XYZ >, TRUSTChamp_Don_generique< Champ_Don_Type::TXYZ >, Champ_Parametrique, Champ_Fonc_Face_VDF, Champ_Ostwald, Champ_Fonc_Face_PolyMAC, and Champ_Fonc_base.
References Objet_U::que_suis_je().
valeurs() [3/6]
virtual DoubleTab& Champ_Proto::valeurs virtual
Implements Champ_Proto.
valeurs() [4/6]
virtual const DoubleTab& Champ_Proto::valeurs virtual
Implements Champ_Proto.
valeurs() [5/6]
virtual DoubleTab& Champ_Proto::valeurs inline virtual
Implements Champ_Proto.
valeurs() [6/6]
virtual const DoubleTab& Champ_Proto::valeurs inline virtual
Implements Champ_Proto.
Member Data Documentation
valeurs_
DoubleTab Champ_Don_base::valeurs_ protected
Referenced by Champ_Fonc_P1_DG::affecter_(), Champ_Uniforme_Morceaux::affecter_(), Champ_Fonc_base::creer_tableau_distribue(), Champ_val_tot_sur_vol_base::evaluer(), Champ_Composite::fill_valeurs_composite(), fixer_nb_valeurs_nodales(), Champ_Ostwald::fixer_nb_valeurs_nodales(), Champ_Fonc_Interp::initialiser(), mettre_a_jour(), nb_valeurs_nodales(), Champ_input_P0::setValue(), and valeurs().