CEA TRUST Platform: Interprete_bloc Class Reference
Interprete_bloc Class Reference
#include <Interprete_bloc.h>
Public Member Functions
Objet_U & ajouter (const Nom &nom, DerObjU &object_to_add)
Entree & interpreter_bloc (Entree &is, Bloc_Type bloc_type, int verifier_sans_interpreter)
Public Member Functions inherited from Liste_bloc
Liste_bloc & dernier ()
Objet_U & operator[] (int)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static Interprete_bloc & interprete_courant ()
static Objet_U & objet_global (const Nom &nom)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Additional Inherited Members
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Voir Interprete_bloc::interpreter()
Member Enumeration Documentation
Bloc_Type
enum Interprete_bloc::Bloc_Type
Enumerator
ACCOLADE
BLOC_EOF
FIN
Member Function Documentation
interpreter_bloc()
Entree & Interprete_bloc::interpreter_bloc (Entree & is, Bloc_Type bloc_type, int verifie_sans_interpreter)
Interpretation d'un bloc d'instructions prises dans l'entree is.
Si le bloc commence par {, on suppose que l'accolade a deja ete lue. Le bloc se termine soit par }, soit par la fin du fichier, soit par le mot FIN en fonction de bloc_type (voir mon_main.cpp par exemple) Si verifie_sans_interpreter!=0, on ne cree aucun objet et on ne lance aucun interprete, on se contente de verifier la coherence des accolades (meme nombre de { que de }).
References ACCOLADE, ajouter(), BLOC_EOF, Entree::eof(), Entree::ERROR_CONTINUE, Entree::ERROR_EXIT, Process::exit(), FIN, Interprete::interpreter(), interpreter_bloc(), Process::Journal(), Entree::set_error_action(), Objet_U_ptr::typer(), and TRUST_Deriv_Objet_U::valeur().
Referenced by mon_main::dowork(), Execute_parallel::interpreter(), Lire_Fichier::interpreter(), Debog_Pb_Wrapper::interpreter(), interpreter_bloc(), and Postraitement::lire_motcle_non_standard().
ajouter()
Objet_U & Interprete_bloc::ajouter (const Nom & nom, DerObjU & ob)
Ajoute l'objet ob a la liste des objets de l'interprete, et nomme l'objet avec nom.
Si l'objet existe deja, exit()
References Liste_bloc::add_deplace(), Process::exit(), Process::Journal(), les_noms_, Objet_U::nommer(), Objet_U::que_suis_je(), and Noms::search().
Referenced by Lire::interpreter(), Typer_Lire::interpreter(), TroisDto2D_32_64< _SIZE_ >::interpreter_(), and interpreter_bloc().
objet_local()
Objet_U & Interprete_bloc::objet_local (const Nom & nom)
Renvoie l'Objet_U correspondant a nom contenu dans cet interprete_bloc Si l'objet n'existe pas, exit() (on ne cherche pas dans le pere).
References Process::exit(), les_noms_, Liste_bloc::operator[](), and Noms::search().
Referenced by objet_global().
objet_local_existant()
int Interprete_bloc::objet_local_existant (const Nom & nom)
renvoie un drapeau indiquant si un objet de ce nom est enregistre dans cet inteprete (ne teste pas le pere).
References les_noms_, and Noms::search().
Referenced by objet_global(), and objet_global_existant().
interprete_courant()
Interprete_bloc & Interprete_bloc::interprete_courant () static
renvoie l'interprete_bloc en train d'etre lu dans le jeu de donnees.
On change d'interprete courant quand on cree et on detruit un objet de type Interprete_bloc (par exemple quand on entre ou qu'on sort d'un bloc { })
References Liste_bloc::valeur().
Referenced by Domaine_dis_cache::build_or_get(), Lire::interpreter(), Typer_Lire::interpreter(), Debog_Pb_Wrapper::interpreter(), TroisDto2D_32_64< _SIZE_ >::interpreter_(), Postraitement::lire_motcle_non_standard(), objet_global(), and objet_global_existant().
objet_global()
Objet_U & Interprete_bloc::objet_global (const Nom & nom) static
cherche l'objet demande dans l'Interprete_bloc courant (Interprete_bloc::interprete_courant()) et dans tous
ses peres successifs. Si l'objet n'existe pas, exit()
References Process::exit(), interprete_courant(), objet_global(), objet_local(), objet_local_existant(), OBS_PTR(), and Liste_bloc::valeur().
Referenced by Multigrille_Adrien::completer(), Multigrille_base::convert_from_ijk(), Multigrille_base::convert_to_ijk(), IJK_Test_Multigrille::interpreter(), TroisDto2D_32_64< _SIZE_ >::interpreter_(), Postraitement::lire_motcle_non_standard(), Interprete::objet(), and objet_global().
objet_global_existant()
int Interprete_bloc::objet_global_existant (const Nom & nom) static
renvoie un drapeau indiquant si un objet de ce nom existe dans inteprete_courant() ou l'un de ses parents.
References interprete_courant(), objet_local_existant(), OBS_PTR(), and Liste_bloc::valeur().
Referenced by TroisDto2D_32_64< _SIZE_ >::interpreter_(), Postraitement::lire_motcle_non_standard(), and Interprete::objet_existant().
les_noms()
const Noms & Interprete_bloc::les_noms () const inline
References les_noms_.
OBS_PTR()
Interprete_bloc::OBS_PTR (Interprete_bloc) protected
Referenced by objet_global(), and objet_global_existant().
Member Data Documentation
les_noms_
Noms Interprete_bloc::les_noms_ protected
Referenced by ajouter(), les_noms(), objet_local(), and objet_local_existant().