CEA TRUST Platform: Champ_P1_isoP1Bulle Class Reference
Champ_P1_isoP1Bulle Class Reference
Public Member Functions
Champ_base & affecter_ (const Champ_base &) override
DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const override
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &val, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const override
Public Member Functions inherited from Champ_Inc_base
Champ_base & affecter_compo (const Champ_base &, int compo) override
virtual void associer_eqn (const Equation_base &)
Champ_Inc_base & avancer (int i=1)
double changer_temps (const double temps) override
double changer_temps_futur (double, int i=1)
double changer_temps_passe (double, int i=1)
virtual int fixer_nb_valeurs_temporelles (int)
DoubleTab & futur (int i=1) override
int lire_donnees (Entree &)
void mettre_a_jour (double temps) override
virtual int nb_valeurs_temporelles () const
DoubleTab & passe (int i=1) override
Champ_Inc_base & reculer (int i=1)
double recuperer_temps_futur (int i=1) const
double recuperer_temps_passe (int i=1) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const override
DoubleTab & valeur_aux (const DoubleTab &positions, DoubleTab &valeurs) const override
DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const override
DoubleTab & valeurs () override
const DoubleTab & valeurs (double temps) const override
DoubleTab & valeurs (double temps) override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
double temps () const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
fixer_nb_valeurs_nodales()
int Champ_P1_isoP1Bulle::fixer_nb_valeurs_nodales (int n) override virtual
Reimplemented from Champ_Inc_base.
References Champ_Inc_base::creer_tableau_distribue(), domaine_vef(), and Domaine_VEF::md_vector_p1b().
Referenced by Op_Diff_RotRot::associer(), and Traitement_particulier_NS_Pression_VEF::lire().
remplir_coord_noeuds()
DoubleTab & Champ_P1_isoP1Bulle::remplir_coord_noeuds (DoubleTab & coord) const override virtual
Implements Champ_Inc_base.
References Champ_P1iP1B_implementation::remplir_coord_noeuds().
Referenced by affecter_().
valeur_a_elem()
DoubleVect & Champ_P1_isoP1Bulle::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_a_elem().
valeur_a_elem_compo()
double Champ_P1_isoP1Bulle::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_a_elem_compo().
valeur_aux_elems()
DoubleTab & Champ_P1_isoP1Bulle::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_aux_elems().
valeur_aux_elems_compo()
DoubleVect & Champ_P1_isoP1Bulle::valeur_aux_elems_compo (const DoubleTab & positions, const IntVect & les_polys, DoubleVect & les_valeurs, int ncomp) const override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs d'une composante du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleVect& les_valeurs) le tableau des valeurs de la composante du champ aux points specifies
(int) l'index de la composante du champ a calculer
Returns
(DoubleVect&) le tableau des valeurs de la composante du champ aux points specifies
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::valeur_aux_elems_compo().
trace()
DoubleTab & Champ_P1_isoP1Bulle::trace (const Frontiere_dis_base & , DoubleTab & x, double tps, int distant) const override virtual
voir Champ_base Cas particulier (malheureusement) du Champ_P0_VDF :
Si la frontiere est un raccord, le resultat est calcule sur le raccord associe. Dans ce cas, le DoubleTab x doit etre dimensionne sur le raccord associe.
Reimplemented from Champ_Inc_base.
References Process::exit(), Champ_base::temps_, Champ_P1iP1B_implementation::trace(), and Champ_Inc_base::valeurs().
valeur_au_bord()
double Champ_P1_isoP1Bulle::valeur_au_bord (int face) const
References Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), Process::exit(), Domaine_VF::face_voisins(), Domaine_VF::get_num_fac_loc(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_VEF::numero_premier_sommet(), and Champ_Inc_base::valeurs().
affecter_()
Champ_base & Champ_P1_isoP1Bulle::affecter_ (const Champ_base & ch) override virtual
Affectation d'un OWN_PTR(Champ_base) generique (Champ_base) dans un champ inconnue.
Parameters
(Champ_base& ch) le champ partie droite de l'affectation
Returns
(Champ_base&) le resultat de l'affectation (*this)
Reimplemented from Champ_Inc_base.
References Domaine_32_64< _SIZE_ >::coord_sommets(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VEF::get_alphaE(), Domaine_VEF::get_alphaS(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_VEF::numero_premier_sommet(), remplir_coord_noeuds(), Champ_base::valeur_aux(), Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Debog::verifier(), and Domaine_VF::xp().
norme_L2()
double Champ_P1_isoP1Bulle::norme_L2 (const Domaine & dom) const
References Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_VEF::numero_premier_sommet(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_Inc_base::valeurs(), and Domaine_VF::volumes().
domaine_vef()
const Domaine_VEF& Champ_P1_isoP1Bulle::domaine_vef () const inline override virtual
Implements Champ_P1iP1B_implementation.
Referenced by affecter_(), fixer_nb_valeurs_nodales(), norme_L2(), and valeur_au_bord().
valeur_aux_sommets()
DoubleTab& Champ_P1_isoP1Bulle::valeur_aux_sommets (const Domaine & dom, DoubleTab & sommets) const inline override virtual
Implements Champ_implementation_divers.
References Champ_P1iP1B_implementation::valeur_aux_sommets().
valeur_aux_sommets_compo()
DoubleVect& Champ_P1_isoP1Bulle::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & sommets, int compo) const inline override virtual
Implements Champ_implementation_divers.
References Champ_P1iP1B_implementation::valeur_aux_sommets_compo().
completer()
void Champ_P1_isoP1Bulle::completer (const Domaine_Cl_dis_base & zcl) override protected virtual
Reimplemented from Champ_base.
References Champ_P1iP1B_implementation::completer().