CEA TRUST Platform: Op_Moyenne Class Reference
Op_Moyenne Class Reference
#include <Op_Moyenne.h>
Public Member Functions
const Nom & le_nom () const override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
lire_ch_moyenne()
Entree & Op_Moyenne::lire_ch_moyenne (Entree & is)
le_nom()
const Nom & Op_Moyenne::le_nom () const inline override virtual
Donne le nom de l'Objet_U Methode a surcharger : renvoie "neant" dans cette implementation.
Returns
(Nom&) le nom de l'Objet_U
Implements Operateur_Statistique_tps_base.
References integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), and Field_base::le_nom().
set_pdi_name()
void Op_Moyenne::set_pdi_name (const Nom & nom) inline
References integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Fonc_base::set_pdi_name().
temps()
double Op_Moyenne::temps () const inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_base::temps().
moyenne_convergee()
Champ_Don_base & Op_Moyenne::moyenne_convergee () inline
integrale()
const Integrale_tps_Champ & Op_Moyenne::integrale () const inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_champ_.
Referenced by Op_Correlation::completer(), Op_Ecart_type::completer(), Champ_Generique_Correlation::get_directive_pour_discr(), Champ_Generique_Moyenne::integrale(), Champ_Generique_Moyenne::temps(), and Champ_Generique_Ecart_Type::valeurs().
valeurs() [1/2]
const DoubleTab & Op_Moyenne::valeurs () const inline
References integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Don_base::valeurs().
Referenced by calculer_valeurs(), completer(), and mettre_a_jour().
valeurs() [2/2]
DoubleTab & Op_Moyenne::valeurs () inline
References integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Don_base::valeurs().
dt_integration()
double Op_Moyenne::dt_integration () const inline
References Integrale_tps_Champ::dt_integration(), and integrale_champ_.
Referenced by calculer_valeurs(), Champ_Generique_Ecart_Type::dt_integration(), and mettre_a_jour().
mettre_a_jour()
void Op_Moyenne::mettre_a_jour (double temps) inline override virtual
Implements Operateur_Statistique_tps_base.
References dt_integration(), integrale_champ_, Integrale_tps_Champ::mettre_a_jour(), and valeurs().
initialiser()
void Op_Moyenne::initialiser (double val) inline override virtual
Implements Operateur_Statistique_tps_base.
References integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Don_base::valeurs().
associer()
void Op_Moyenne::associer (const Domaine_dis_base & une_zdis, const Champ_Generique_base & le_champ, double t1, double t2) inline override virtual
Implements Operateur_Statistique_tps_base.
References Integrale_tps_Champ::associer(), Champ_Fonc_base::associer_domaine_dis_base(), Nom::debute_par(), Champ_Generique_base::get_champ(), integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), OWN_PTR(), Objet_U::que_suis_je(), Nom::suffix(), and Integrale_tps_Champ::typer_champ().
Referenced by Champ_Generique_Moyenne::completer().
fixer_tstat_deb()
void Op_Moyenne::fixer_tstat_deb (double tdeb, double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
References Integrale_tps_Champ::fixer_dt_integr(), Integrale_tps_Champ::fixer_t_debut(), Integrale_tps_Champ::fixer_tps_integrale(), and integrale_champ_.
fixer_tstat_fin()
void Op_Moyenne::fixer_tstat_fin (double tps) inline override virtual
Implements Operateur_Statistique_tps_base.
References Integrale_tps_Champ::fixer_t_fin(), and integrale_champ_.
data_a_sauvegarder()
std::vector< YAML_data > Op_Moyenne::data_a_sauvegarder () const inline override virtual
for PDI IO: retrieve name, type and dimensions of the field to save/restore
Reimplemented from Operateur_Statistique_tps_base.
References Champ_Fonc_base::get_pdi_name(), Nom::getString(), integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and Champ_Don_base::valeurs().
sauvegarder()
int Op_Moyenne::sauvegarder (Sortie &) const inline override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
References integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Fonc_base::sauvegarder().
reprendre()
int Op_Moyenne::reprendre (Entree &) inline override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
References integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), and Champ_Fonc_base::reprendre().
completer()
void Op_Moyenne::completer (const Probleme_base & Pb, const Nom & prefix) override virtual
Implements Operateur_Statistique_tps_base.
References Champ_Fonc_base::associer_domaine_dis_base(), Champ_base::changer_temps(), TRUSTTab< _TYPE_, _SIZE_ >::copy(), Probleme_base::domaine_dis(), Field_base::fixer_nb_comp(), Field_base::fixer_unite(), Field_base::fixer_unites(), integrale_champ_, Integrale_tps_Champ::le_champ_calcule(), Field_base::nb_comp(), Field_base::nommer(), OWN_PTR(), Probleme_base::schema_temps(), Champ_Fonc_base::set_pdi_name(), Schema_Temps_base::temps_courant(), Field_base::unite(), Field_base::unites(), valeurs(), and Champ_Proto::valeurs().
Referenced by Champ_Generique_Moyenne::completer().
calculer_valeurs()
DoubleTab Op_Moyenne::calculer_valeurs () const override virtual
Implements Operateur_Statistique_tps_base.
References dt_integration(), and valeurs().
Referenced by Champ_Generique_Moyenne::get_champ().
OWN_PTR()
Op_Moyenne::OWN_PTR (Champ_Don_base) protected
Referenced by associer(), and completer().
Member Data Documentation
integrale_champ_
Integrale_tps_Champ Op_Moyenne::integrale_champ_ protected
Referenced by associer(), completer(), data_a_sauvegarder(), dt_integration(), fixer_tstat_deb(), fixer_tstat_fin(), initialiser(), integrale(), le_nom(), mettre_a_jour(), reprendre(), sauvegarder(), set_pdi_name(), temps(), valeurs(), and valeurs().