CEA TRUST Platform: Multigrille_base Class Reference
Multigrille_base Class Reference abstract
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Enumeration Documentation
StorageId
enum Multigrille_base::StorageId protected
Enumerator
STORAGE_RHS
STORAGE_X
STORAGE_RESIDUE
Constructor & Destructor Documentation
Multigrille_base()
Multigrille_base::Multigrille_base ()
References precision_double_, TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), and solver_precision_.
Member Function Documentation
get_flag_updated_input()
int Multigrille_base::get_flag_updated_input () const override virtual
Reimplemented from SolveurSys_base.
resoudre_systeme() [1/2]
int Multigrille_base::resoudre_systeme (const Matrice_Base & a, const DoubleVect & b, DoubleVect & x, int n) override virtual
Reimplemented from SolveurSys_base.
resoudre_systeme() [2/2]
int Multigrille_base::resoudre_systeme (const Matrice_Base & a, const DoubleVect & b, DoubleVect & x) override virtual
Implements SolveurSys_base.
References precision_double_, precision_float_, and solver_precision_.
solveur_direct()
int Multigrille_base::solveur_direct () const inline override virtual
Implements SolveurSys_base.
resoudre_systeme_IJK()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_base::resoudre_systeme_IJK (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & rhs, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & x)
References precision_float_, and solver_precision_.
Referenced by IJK_Test_Multigrille::interpreter().
convert_from_ijk()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_base::convert_from_ijk (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & ijk_x, DoubleVect & x)
References VDF_to_IJK::convert_from_ijk(), Domaine_IJK::ELEM, IJK_VDF_converter::get_conventional_name(), IJK_VDF_converter::get_vdf_to_ijk(), and Interprete_bloc::objet_global().
Referenced by resoudre_systeme_template().
convert_to_ijk()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_base::convert_to_ijk (const DoubleVect & x, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & ijk_x)
References VDF_to_IJK::convert_to_ijk(), Domaine_IJK::ELEM, IJK_VDF_converter::get_conventional_name(), IJK_VDF_converter::get_vdf_to_ijk(), and Interprete_bloc::objet_global().
Referenced by resoudre_systeme_template().
multigrille()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > double Multigrille_base::multigrille (IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & x, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & b, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & residu)
References multigrille_().
Referenced by resoudre_avec_gmres(), and solve_ijk_in_storage_template().
prepare_secmem() [1/2]
virtual void Multigrille_base::prepare_secmem (IJK_Field_float & x) const pure virtual
Implemented in Multigrille_Adrien.
Referenced by multigrille_(), resoudre_avec_gmres(), and solve_ijk_in_storage_template().
prepare_secmem() [2/2]
virtual void Multigrille_base::prepare_secmem (IJK_Field_double & x) const pure virtual
Implemented in Multigrille_Adrien.
alloc_field() [1/2]
virtual void Multigrille_base::alloc_field (IJK_Field_float & x, int level, bool with_additional_k_layers = false) const pure virtual
Implemented in Multigrille_Adrien.
Referenced by resoudre_avec_gmres().
alloc_field() [2/2]
virtual void Multigrille_base::alloc_field (IJK_Field_double & x, int level, bool with_additional_k_layers = false) const pure virtual
Implemented in Multigrille_Adrien.
dump_lata() [1/2]
virtual void Multigrille_base::dump_lata (const Nom & field, const IJK_Field_float & data, int tstep) const pure virtual
Implemented in Multigrille_Adrien.
Referenced by solve_ijk_in_storage_template().
dump_lata() [2/2]
virtual void Multigrille_base::dump_lata (const Nom & field, const IJK_Field_double & data, int tstep) const pure virtual
Implemented in Multigrille_Adrien.
nb_grid_levels()
virtual int Multigrille_base::nb_grid_levels () const pure virtual
Implemented in Multigrille_Adrien.
Referenced by multigrille_().
ajouter_param()
void Multigrille_base::ajouter_param (Param & param) protected virtual
Reimplemented in Multigrille_Adrien.
References Param::ajouter(), Param::ajouter_flag(), Param::dictionnaire(), precision_double_, precision_float_, precision_mix_, and solver_precision_.
Referenced by Multigrille_Adrien::ajouter_param().
set_coarse_matrix()
Matrice_Grossiere& Multigrille_base::set_coarse_matrix () inline protected
needed_kshift_for_jacobi()
virtual int Multigrille_base::needed_kshift_for_jacobi (int level) const protected pure virtual
Implemented in Multigrille_Adrien.
Referenced by multigrille_(), resoudre_avec_gmres(), resoudre_systeme_IJK_template(), resoudre_systeme_template(), and solve_ijk_in_storage_template().
nsweeps_jacobi_residu()
int Multigrille_base::nsweeps_jacobi_residu (int level) const protected
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
coarse_solver()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_base::coarse_solver (IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & x, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & b) protected
!!!!!!!!!!!!!!!!! ToDo WARNING: potentiellement conversion de double en float!!!!!!!!!!!!!!!!!!!!!!!!!!!!
References IJK_Shear_Periodic_helpler::defilement_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MD_Vector_base::get_nb_items_tot(), Matrice_Grossiere::matrice(), Matrice_Grossiere::md_vector(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Matrice_Grossiere::renum(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), SolveurSys::resoudre_systeme(), and TRUSTVect< _TYPE_, _SIZE_ >::set_md_vector().
Referenced by multigrille_().
resoudre_avec_gcp()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_base::resoudre_avec_gcp (IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & x, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & b, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & residu) protected
Referenced by solve_ijk_in_storage_template().
resoudre_avec_gmres()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_base::resoudre_avec_gmres (IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & x, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & b, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & residu) protected
References TRUST_Vector< _CLASSE_ >::add(), alloc_field(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), Process::exit(), jacobi_residu(), Process::mp_sum(), multigrille(), needed_kshift_for_jacobi(), prepare_secmem(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by solve_ijk_in_storage_template().
resoudre_systeme_template()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_base::resoudre_systeme_template (const Matrice_Base & a, const DoubleVect & b, DoubleVect & x) protected
References convert_from_ijk(), convert_to_ijk(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Matrice_Bloc::get_bloc(), Process::je_suis_maitre(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_shift(), Matrice_Base::multvect(), needed_kshift_for_jacobi(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::shift_k_origin(), STORAGE_RHS, and STORAGE_X.
resoudre_systeme_IJK_template()
template<typename _TYPE_FUNC_ , typename _TYPE_ , typename _TYPE_ARRAY_ > void Multigrille_base::resoudre_systeme_IJK_template (const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & rhs, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & x) protected
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_shift(), needed_kshift_for_jacobi(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::shift_k_origin(), STORAGE_RHS, and STORAGE_X.
solve_ijk_in_storage_template() [1/3]
template<typename _TYPE_ > void Multigrille_base::solve_ijk_in_storage_template () protected
get_storage_float()
virtual IJK_Field_float& Multigrille_base::get_storage_float (StorageId , int level) protected pure virtual
Implemented in Multigrille_Adrien.
Referenced by get_storage_template(), and solve_ijk_in_storage_template().
get_storage_double()
virtual IJK_Field_double& Multigrille_base::get_storage_double (StorageId , int level) protected pure virtual
Implemented in Multigrille_Adrien.
Referenced by get_storage_template(), and solve_ijk_in_storage_template().
get_storage_template() [1/2]
template<typename _TYPE_ > std::enable_if_t<std::is_same<_TYPE_, float>::value, IJK_Field_template<_TYPE_, TRUSTArray<_TYPE_> >&> Multigrille_base::get_storage_template (StorageId id, int level) inline protected
References get_storage_float().
get_storage_template() [2/2]
template<typename _TYPE_ > std::enable_if_t<std::is_same<_TYPE_, double>::value, IJK_Field_template<_TYPE_, TRUSTArray<_TYPE_> >&> Multigrille_base::get_storage_template (StorageId id, int level) inline protected
References get_storage_double().
jacobi_residu() [1/2]
virtual void Multigrille_base::jacobi_residu (IJK_Field_float & x, const IJK_Field_float * secmem, const int grid_level, const int n_jacobi, IJK_Field_float * residu) const protected pure virtual
Implemented in Multigrille_Adrien.
Referenced by multigrille_(), resoudre_avec_gmres(), and solve_ijk_in_storage_template().
jacobi_residu() [2/2]
virtual void Multigrille_base::jacobi_residu (IJK_Field_double & x, const IJK_Field_double * secmem, const int grid_level, const int n_jacobi, IJK_Field_double * residu) const protected pure virtual
Implemented in Multigrille_Adrien.
coarsen() [1/2]
virtual void Multigrille_base::coarsen (const IJK_Field_float & fine, IJK_Field_float & coarse, int fine_level) const protected pure virtual
Implemented in Multigrille_Adrien.
Referenced by multigrille_().
coarsen() [2/2]
virtual void Multigrille_base::coarsen (const IJK_Field_double & fine, IJK_Field_double & coarse, int fine_level) const protected pure virtual
Implemented in Multigrille_Adrien.
interpolate_sub_shiftk() [1/2]
virtual void Multigrille_base::interpolate_sub_shiftk (const IJK_Field_float & coarse, IJK_Field_float & fine, int fine_level) const protected pure virtual
Implemented in Multigrille_Adrien.
Referenced by multigrille_().
interpolate_sub_shiftk() [2/2]
virtual void Multigrille_base::interpolate_sub_shiftk (const IJK_Field_double & coarse, IJK_Field_double & fine, int fine_level) const protected pure virtual
Implemented in Multigrille_Adrien.
multigrille_()
template<typename _TYPE_ , typename _TYPE_ARRAY_ > double Multigrille_base::multigrille_ (IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & x, const IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & b, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ > & residu, int grid_level, int iter_number) protected
References Perf_counters::begin_count(), coarse_solver(), coarsen(), Perf_counters::create_custom_counter(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Shear_Periodic_helpler::defilement_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Perf_counters::end_count(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), interpolate_sub_shiftk(), jacobi_residu(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_shift(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::linear_index(), nb_grid_levels(), needed_kshift_for_jacobi(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), Field_base::nommer(), Domaine_base::nommer(), prepare_secmem(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::shift_k_origin(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), STORAGE_RESIDUE, STORAGE_RHS, and STORAGE_X.
Referenced by multigrille().
relax_jacobi()
double Multigrille_base::relax_jacobi (int level) const inline protected
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().
multigrille_failure()
virtual double Multigrille_base::multigrille_failure () protected pure virtual
Implemented in Multigrille_Adrien.
Referenced by solve_ijk_in_storage_template().
solve_ijk_in_storage_template() [2/3]
template<> void Multigrille_base::solve_ijk_in_storage_template () protected
References IJK_Shear_Periodic_helpler::defilement_, IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Process::exit(), get_storage_float(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), multigrille(), prepare_secmem(), STORAGE_RESIDUE, STORAGE_RHS, and STORAGE_X.
solve_ijk_in_storage_template() [3/3]
template<> void Multigrille_base::solve_ijk_in_storage_template () protected
References IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::data(), IJK_Shear_Periodic_helpler::defilement_, dump_lata(), IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::echange_espace_virtuel(), Process::exit(), get_storage_double(), get_storage_float(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ghost(), jacobi_residu(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::k_shift(), multigrille(), multigrille_failure(), needed_kshift_for_jacobi(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), precision_double_, prepare_secmem(), resoudre_avec_gcp(), resoudre_avec_gmres(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::shift_k_origin(), solver_precision_, STORAGE_RESIDUE, STORAGE_RHS, and STORAGE_X.
Member Data Documentation
precision_double_
const int Multigrille_base::precision_double_ protected
Referenced by ajouter_param(), Multigrille_base(), resoudre_systeme(), and solve_ijk_in_storage_template().
precision_float_
const int Multigrille_base::precision_float_ protected
Referenced by ajouter_param(), resoudre_systeme(), and resoudre_systeme_IJK().
precision_mix_
const int Multigrille_base::precision_mix_ protected
Referenced by ajouter_param().
solver_precision_
int Multigrille_base::solver_precision_ protected
Referenced by ajouter_param(), Multigrille_base(), resoudre_systeme(), resoudre_systeme_IJK(), and solve_ijk_in_storage_template().