CEA TRUST Platform: Op_Diff_PolyMAC_Gen_base Class Reference
Op_Diff_PolyMAC_Gen_base Class Reference abstract
Public Member Functions
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
Classe de base generique pour la diffusion PolyMAC
Member Function Documentation
associer()
void Op_Diff_PolyMAC_Gen_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base &) override virtual
Implements Operateur_base.
associer_diffusivite()
void Op_Diff_PolyMAC_Gen_base::associer_diffusivite (const Champ_base & diffu) inline override virtual
Implements Operateur_Diff_base.
diffusivite()
const Champ_base& Op_Diff_PolyMAC_Gen_base::diffusivite () const inline override virtual
Implements Operateur_Diff_base.
Referenced by Op_Diff_PolyMAC_base::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0P1NC_base::completer(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), and Op_Diff_PolyMAC_P0P1NC_base::update_nu().
calculer()
DoubleTab & Op_Diff_PolyMAC_Gen_base::calculer (const DoubleTab & inco, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::ajouter().
modifier_mu()
virtual void Op_Diff_PolyMAC_Gen_base::modifier_mu (DoubleTab &) const inline virtual
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Face.
Referenced by Op_Diff_PolyMAC_P0_base::update_nu(), and Op_Diff_PolyMAC_P0P1NC_base::update_nu().
dimension_min_nu()
virtual int Op_Diff_PolyMAC_Gen_base::dimension_min_nu () const inline virtual
Referenced by Op_Diff_PolyMAC_P0_base::completer(), and Op_Diff_PolyMAC_P0P1NC_base::completer().
nu()
const DoubleTab& Op_Diff_PolyMAC_Gen_base::nu () const inline
References nu_, nu_a_jour_, and update_nu().
Referenced by Op_Diff_PolyMAC_P0_base::update_phif().
update_nu()
virtual void Op_Diff_PolyMAC_Gen_base::update_nu () const pure virtual
Implemented in Op_Diff_PolyMAC_P0P1NC_base, Op_Diff_PolyMAC_P0_base, and Op_Diff_PolyMAC_base.
Referenced by nu().
impr()
int Op_Diff_PolyMAC_Gen_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Sortie::add_col(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Flux, Operateur_base::flux_bords(), Flux_moment, Flux_sum, Schema_Temps_base::imprimer_temps_courant(), Process::je_suis_maitre(), Frontiere_dis_base::le_nom(), Domaine_base::moments_a_imprimer(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), EcrFicPartage::syncfile(), and Schema_Temps_base::temps_courant().
domaine_poly()
const Domaine_PolyMAC& Op_Diff_PolyMAC_Gen_base::domaine_poly () const inline
domaine_cl_poly()
const Domaine_Cl_PolyMAC& Op_Diff_PolyMAC_Gen_base::domaine_cl_poly () const inline
OBS_PTR() [1/3]
Op_Diff_PolyMAC_Gen_base::OBS_PTR (Domaine_PolyMAC) protected
OBS_PTR() [2/3]
Op_Diff_PolyMAC_Gen_base::OBS_PTR (Domaine_Cl_PolyMAC) protected
OBS_PTR() [3/3]
Op_Diff_PolyMAC_Gen_base::OBS_PTR (Champ_base) protected
Member Data Documentation
Flux
SFichier Op_Diff_PolyMAC_Gen_base::Flux mutable protected
Referenced by impr().
Flux_moment
SFichier Op_Diff_PolyMAC_Gen_base::Flux_moment protected
Referenced by impr().
Flux_sum
SFichier Op_Diff_PolyMAC_Gen_base::Flux_sum protected
Referenced by impr().
nu_
DoubleTab Op_Diff_PolyMAC_Gen_base::nu_ mutable protected
Referenced by Op_Diff_PolyMAC_Face::ajouter(), Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0_Face::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Elem::calculer_dt_stab(), Op_Diff_PolyMAC_P0P1NC_Face::calculer_dt_stab(), Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_PolyMAC_P0P1NC_base::completer(), Op_Diff_PolyMAC_Face::contribuer_a_avec(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Op_Diff_PolyMAC_base::get_nu(), nu(), Op_Diff_PolyMAC_base::remplir_nu_ef(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), and Op_Diff_PolyMAC_P0P1NC_base::update_nu().
nu_a_jour_
int Op_Diff_PolyMAC_Gen_base::nu_a_jour_ = 0 mutable protected
Referenced by Op_Diff_PolyMAC_base::completer(), Op_Diff_PolyMAC_base::mettre_a_jour(), Op_Diff_PolyMAC_P0_base::mettre_a_jour(), Op_Diff_PolyMAC_P0P1NC_base::mettre_a_jour(), nu(), Op_Diff_PolyMAC_base::update_nu(), Op_Diff_PolyMAC_P0_base::update_nu(), and Op_Diff_PolyMAC_P0P1NC_base::update_nu().
nu_constant_
int Op_Diff_PolyMAC_Gen_base::nu_constant_ = 0 protected
Referenced by Op_Diff_PolyMAC_P0_base::completer(), Op_Diff_Turbulent_PolyMAC_P0_Face::completer(), Op_Diff_PolyMAC_P0_Face::dimensionner_blocs(), Op_Diff_PolyMAC_P0_Elem::dimensionner_blocs(), Op_Diff_PolyMAC_P0_base::mettre_a_jour(), and Op_Diff_PolyMAC_P0P1NC_base::mettre_a_jour().