CEA TRUST Platform: TRUST_Deriv_Objet_U Class Reference
TRUST_Deriv_Objet_U Class Reference
Public Member Functions
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U_ptr
int associer_ (Objet_U &objet) override
const Nom & le_nom () const override
Objet_U * typer (const char *nom_type)
Public Member Functions inherited from Objet_U
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U_ptr
int change_num (const int *const) override
Objet_U * get_Objet_U_ptr_check () const
void recopie (const Objet_U &)
~Objet_U_ptr () override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Il existe 3 methodes supplementaires :
deplace(TRUST_Deriv_Objet_U&)
reprendre
sauvegarder
Utilisation :
TRUST_Deriv_Objet_U ou
DerObjU
Constructor & Destructor Documentation
TRUST_Deriv_Objet_U() [1/3]
TRUST_Deriv_Objet_U::TRUST_Deriv_Objet_U ()
TRUST_Deriv_Objet_U() [2/3]
TRUST_Deriv_Objet_U::TRUST_Deriv_Objet_U (const TRUST_Deriv_Objet_U & t)
References Objet_U_ptr::non_nul(), Objet_U_ptr::recopie(), and valeur().
TRUST_Deriv_Objet_U() [3/3]
TRUST_Deriv_Objet_U::TRUST_Deriv_Objet_U (const Objet_U & t)
References Objet_U_ptr::recopie().
Member Function Documentation
set_Objet_U_ptr()
void TRUST_Deriv_Objet_U::set_Objet_U_ptr (Objet_U * ptr) override protected virtual
Fait pointer *this sur l'objet *ptr L'adresse peut etre nulle (pointeur nul).
Reimplemented from Objet_U_ptr.
References Objet_U_ptr::set_Objet_U_ptr().
Referenced by deplace(), and operator=().
get_info_ptr()
const Type_info & TRUST_Deriv_Objet_U::get_info_ptr () const override virtual
Implements Objet_U_ptr.
References Objet_U::info().
operator=() [1/2]
const TRUST_Deriv_Objet_U & TRUST_Deriv_Objet_U::operator= (const Objet_U & t)
References Objet_U_ptr::detach(), and Objet_U_ptr::recopie().
operator=() [2/2]
const TRUST_Deriv_Objet_U & TRUST_Deriv_Objet_U::operator= (const TRUST_Deriv_Objet_U & t)
References Objet_U_ptr::detach(), Objet_U_ptr::non_nul(), Objet_U_ptr::recopie(), set_Objet_U_ptr(), and valeur().
reprendre()
int TRUST_Deriv_Objet_U::reprendre (Entree &) override virtual
Reprise d'un Objet_U sur un flot d'entree Methode a surcharger.
Parameters
(Entree&) flot d'entree a utiliser pour la reprise
Returns
(int) code de retour
Reimplemented from Objet_U.
References Objet_U::reprendre(), and valeur().
sauvegarder()
int TRUST_Deriv_Objet_U::sauvegarder (Sortie &) const override virtual
Sauvegarde d'un Objet_U sur un flot de sortie Methode a surcharger.
Parameters
(Sortie&) flot de sortie a utiliser pour la sauvegarde
Returns
(int) code de retour
Reimplemented from Objet_U.
References Objet_U::sauvegarder(), and valeur().
deplace()
void TRUST_Deriv_Objet_U::deplace (TRUST_Deriv_Objet_U & deriv_obj)
References Objet_U_ptr::detach(), set_Objet_U_ptr(), and valeur().
Referenced by Liste_bloc::add_deplace().
valeur() [1/2]
const Objet_U& TRUST_Deriv_Objet_U::valeur () const inline
References Objet_U_ptr::get_Objet_U_ptr_check().
Referenced by deplace(), Interprete_bloc::interpreter_bloc(), operator=(), reprendre(), sauvegarder(), TRUST_Deriv_Objet_U(), and Liste_bloc::valeur().
valeur() [2/2]
Objet_U& TRUST_Deriv_Objet_U::valeur () inline
References Objet_U_ptr::get_Objet_U_ptr_check().
operator->()
Objet_U* TRUST_Deriv_Objet_U::operator-> () const inline
References Objet_U_ptr::get_Objet_U_ptr_check().