CEA TRUST Platform: Op_Dift_VEF_Face Class Reference
Op_Dift_VEF_Face Class Reference
#include <Op_Dift_VEF_Face.h>
Public Member Functions
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
void contribuer_au_second_membre (DoubleTab &resu) const override
Public Member Functions inherited from Op_Dift_VEF_base
double calculer_dt_stab () const override
void completer () override
void dimensionner (Matrice_Morse &matrice) const override
void mettre_a_jour (double temps) override
void modifier_pour_Cl (Matrice_Morse &matrice, DoubleTab &secmem) const override
Public Member Functions inherited from Op_Diff_VEF_base
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
ajouter()
DoubleTab & Op_Dift_VEF_Face::ajouter (const DoubleTab & inconnue_org, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References Op_Diff_Turbulent_base::diffusivite_turbulente(), MorEqn::equation(), Operateur_base::flux_bords_, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Op_VEF_Face::modifier_flux(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Op_Diff_VEF_base::remplir_nu(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_Don_base::valeurs(), and Debog::verifier().
contribuer_a_avec()
void Op_Dift_VEF_Face::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Op_Diff_Turbulent_base::diffusivite_turbulente(), MorEqn::equation(), Equation_base::milieu(), Op_VEF_Face::modifier_matrice_pour_periodique_apres_contribuer(), Op_VEF_Face::modifier_matrice_pour_periodique_avant_contribuer(), Op_Diff_VEF_base::nu_, Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Op_Diff_VEF_base::remplir_nu(), and Champ_Don_base::valeurs().
contribuer_au_second_membre()
void Op_Dift_VEF_Face::contribuer_au_second_membre (DoubleTab &) const override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
References Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_gradient(), Op_Diff_Turbulent_base::diffusivite_turbulente(), Op_Diff_VEF_base::domaine_cl_vef(), Op_Diff_VEF_base::domaine_vef(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Process::exit(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Op_Dift_VEF_Face_Gen< Op_Dift_VEF_Face >::grad_, Echange_impose_base::h_imp(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Op_Diff_VEF_base::nu_, Front_VF::num_premiere_face(), Op_Diff_VEF_base::phi_psi_diffuse(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Echange_impose_base::T_ext(), Op_Dift_VEF_base::tau_tan_, Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().