CEA TRUST Platform: Scatter Class Reference
Scatter Class Reference
#include <Scatter.h>
Public Member Functions
Entree & interpreter (Entree &) override
virtual void lire_domaine (Nom &, Noms &liste_bords_periodiques)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions
static void ajouter_joints (Domaine &domaine, ArrOfInt &pe_voisins)
static void calculer_espace_distant (Domaine &domaine, const int nb_items_reels, const ArrsOfInt &items_to_send, const JOINT_ITEM type_item)
static void calculer_espace_distant_elements (Domaine &dom)
static void calculer_espace_distant_sommets (Domaine &dom, const Noms &liste_bords_periodiques)
static void calculer_nb_items_virtuels (Joints &joints, const JOINT_ITEM type_item)
static void calculer_renum_items_communs (Joints &joints, const JOINT_ITEM type_item)
static void check_consistancy_remote_items (Domaine &dom, const ArrOfInt &mergedDomaines)
static int Chercher_Correspondance (const DoubleTab &sommets1, const DoubleTab &sommets2, ArrOfInt &correspondance, const double epsilon)
static void construire_correspondance_aretes_par_coordonnees (Domaine_VF &zvf)
static void construire_correspondance_sommets_par_coordonnees (Domaine &dom)
static void construire_espace_virtuel_traduction (const MD_Vector &md_indice, const MD_Vector &md_valeur, IntTab &tableau, const int error_is_fatal=1)
static void construire_structures_paralleles (Domaine &dom, const Noms &liste_bords_perio)
static void corriger_espace_distant_elements_perio (Domaine &dom, const Noms &liste_bords_periodiques)
template<typename _SIZE_ >
static void init_sequential_domain (Domaine_32_64< _SIZE_ > &dom)
static void reordonner_faces_de_joint (Domaine &dom)
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions
void read_domain_no_comm (Entree &fic)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
interpreter()
Entree & Scatter::interpreter (Entree & is) override virtual
Lit et complete un domaine parallele selon les motcles lus dans le jeu de donnees.
Format: Scatter [debug] file_name domain_name On lit les sommets, les elements et les sommets et faces de joint, On construit les espaces distants et virtuels en fonction de l'epaisseur de joint.
Implements Interprete.
References Process::barrier(), Statistiques::begin_count(), calculer_renum_items_communs(), construire_structures_paralleles(), Statistiques::end_count(), Process::exit(), Domaine_32_64< _SIZE_ >::faces_joint(), init_sequential_domain(), Process::is_sequential(), Process::je_suis_maitre(), Statistiques::last_time(), lire_domaine(), Process::me(), Process::mp_max(), Process::mp_min(), Process::mp_sum(), Domaine_32_64< _SIZE_ >::nb_elem(), Process::nproc(), Interprete::objet(), Objet_U::que_suis_je(), and uninit_sequential_domain().
lire_domaine()
void Scatter::lire_domaine (Nom & nomentree, Noms & liste_bords_periodiques) virtual
Lit le domaine dans le fichier de nom "nomentree", de type LecFicDistribueBin ou LecFicDistribue.
Format attendu : Domaine::ReadOn
Reimplemented in ScatterMED.
References Process::barrier(), Domaine_32_64< _SIZE_ >::bord(), check_consistancy_remote_items(), Domaine_32_64< _SIZE_ >::check_domaine(), Domaine_32_64< _SIZE_ >::clear(), Entree_Fichier_base::close(), FichierHDF::close(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine(), FichierHDF::exists(), Process::exit(), Domaine_32_64< _SIZE_ >::faces_joint(), Nom::getPrefix(), Nom::getString(), init_sequential_domain(), FichierHDF::is_hdf5(), Process::je_suis_maitre(), Domaine_32_64< _SIZE_ >::les_sommets(), Process::me(), Process::mp_max(), Process::mp_sum(), Nom::nom_me(), Process::nproc(), FichierHDF::open(), Entree_Fichier_base::ouvrir(), LecFicDistribue::ouvrir(), Objet_U::precision_geom, FichierHDF::read_dataset(), read_domain_no_comm(), and trier_les_joints().
Referenced by interpreter().
domaine()
Domaine & Scatter::domaine ()
Renvoi le domaine associe.
Referenced by ajouter_joints(), calculer_espace_distant(), calculer_espace_distant_aretes(), calculer_espace_distant_faces(), lire_domaine(), and ScatterMED::lire_domaine().
Chercher_Correspondance()
int Scatter::Chercher_Correspondance (const DoubleTab & sommets1, const DoubleTab & sommets2, ArrOfInt & correspondance, const double epsilon) static
Construit le tableau "correspondance" tel que Pour 0 <= i < sommets2.
size_array(), Si sommet2(i) existe dans le tableau sommet1, alors sommets2(i, ...) == sommets1(correspondance[i], ...) Sinon correspondance[i] = -1 L'egalite est verifiee a epsilon pres en absolu (soit abs(x1-x2)<epsilon) L'algorithme est generalement en n1*log(n1) + n2*log(n1) (recherche basee sur un quicksort). En cas d'echec du tri, on utilise un algorithme en n1*n2. Les tableaux sommets1 et sommets2 doivent etre de dimension 2 Le tableau correspondance doit etre de taille sommets2.size_array(). Valeur de retour: nombre de sommets de sommets2 non trouves dans le tableau sommets1.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Process::Journal(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by construire_correspondance_items_par_coordonnees().
construire_correspondance_sommets_par_coordonnees()
void Scatter::construire_correspondance_sommets_par_coordonnees (Domaine & dom) static
Construction des tableaux joint_item(JOINT_ITEM::SOMMET).
items_communs de tous les joints du domaine(0) du domaine dom
References construire_correspondance_items_par_coordonnees(), Domaine_32_64< _SIZE_ >::coord_sommets(), and Domaine_32_64< _SIZE_ >::faces_joint().
Referenced by MaillerParallel::interpreter().
construire_correspondance_aretes_par_coordonnees()
void Scatter::construire_correspondance_aretes_par_coordonnees (Domaine_VF & zvf) static
Construction des tableaux joint_item(JOINT_ITEM::ARETE).
items_communs de tous les joints du domaine
References construire_correspondance_items_par_coordonnees(), Domaine_dis_base::domaine(), Domaine_32_64< _SIZE_ >::faces_joint(), and Domaine_VF::xa().
construire_correspondance_items_par_coordonnees()
void Scatter::construire_correspondance_items_par_coordonnees (Joints & joints, const JOINT_ITEM type_item, const DoubleTab & coord_items) static
Methode obsolete (utilisee avec l'ancien decoupeur).
References Schema_Comm::begin_comm(), calculer_renum_items_communs(), Chercher_Correspondance(), Objet_U::dimension, Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Process::exit(), Process::me(), Objet_U::precision_geom, Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by construire_correspondance_aretes_par_coordonnees(), and construire_correspondance_sommets_par_coordonnees().
construire_structures_paralleles()
void Scatter::construire_structures_paralleles (Domaine & dom, const Noms & liste_bords_periodiques) static
Construction des structures paralleles du domaine et du domaine (determination des elements distants en fonction de l'epaisseur de joint,.
determination des sommets distants, creation des sommets et des elements virtuels)
References calculer_espace_distant_elements(), calculer_espace_distant_sommets(), calculer_nb_items_virtuels(), construire_espace_virtuel_traduction(), construire_md_vector(), corriger_espace_distant_elements_perio(), MD_Vector_tools::creer_tableau_distribue(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), reordonner_faces_de_joint(), and TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector().
Referenced by interpreter(), and MaillerParallel::interpreter().
calculer_espace_distant()
void Scatter::calculer_espace_distant (Domaine & domaine, const int nb_items_reels, const ArrsOfInt & items_to_send, const JOINT_ITEM type_item) static
Determination des items distants en fonction d'une liste d'items a envoyer et de listes d'items communs.
exemple: calculer_espace_distant_sommets calculer_espace_distant_faces Pour les sommets: les "items_to_send" sont les sommets des elements distants, Si le processeur A veut que le processeur B connaisse le sommet i, il faut que le processeur qui possede le sommet l'envoie a B. Le processeur qui "possede" le sommet est le plus petit parmi les PEs qui partagent ce sommet (item commun) (requis pour pouvoir faire echange_item_commun et echange_espace_virtuel en une seule passe). De plus, si plusieurs processeurs demandent a envoyer le meme sommet au meme processeur, il ne faut l'inserer qu'une seule fois dans l'espace distant.
Parameters
(joints) les joints dans lesquels on veut calculer un espace distant
(nb_items_reels) le nombre d'items reels (sommets, faces, ...)
(items_to_send) un vecteur de "nproc()" tableaux, pour chaque processeur, la liste des items qu'on veut lui envoyer (exemple:tous les sommets des elements distants, ou toutes les faces)
(type_item) les items dont on veut calculer l'espace distant
References ajouter_joints(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), calculer_nb_items_virtuels(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), domaine(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Entree::eof(), Domaine_32_64< _SIZE_ >::faces_joint(), Process::Journal(), Process::me(), Process::nproc(), TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array(), Schema_Comm::recv_buffer(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), TRUST_Vector< _CLASSE_ >::size(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
calculer_nb_items_virtuels()
void Scatter::calculer_nb_items_virtuels (Joints & joints, const JOINT_ITEM type_item) static
Pour un item geometrique "type_item", remplit le champ nb_items_virtuels_ des joints en fonction du nombre d'items distants :
Le nombre d'items virtuels sur un joint i du processeur j est le nombre d'items distants du joint j sur le processeur i.
References Schema_Comm::begin_comm(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Schema_Comm::recv_buffer(), Schema_Comm::send_buffer(), and Schema_Comm::set_send_recv_pe_list().
Referenced by calculer_espace_distant(), and construire_structures_paralleles().
calculer_renum_items_communs()
void Scatter::calculer_renum_items_communs (Joints & joints, const JOINT_ITEM type_item) static
On suppose que chaque joint[i].
joint_item(type_item).items_communs() contient les indices locaux des items de joint communs dans le meme ordre sur les deux processeurs (local et voisin) On remplit renum_items_communs : colonne 0=contenu du tableau items_communs sur le PE voisin colonne 1=contenu du tableau items_communs sur le PE local
References Schema_Comm::begin_comm(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by construire_correspondance_items_par_coordonnees(), Domaine_VF::discretiser(), interpreter(), and MaillerParallel::interpreter().
calculer_espace_distant_faces()
void Scatter::calculer_espace_distant_faces (Domaine & domaine, const int nb_faces_reelles, const IntTab & elem_faces) static
Idem que Scatter::calculer_espace_distant_sommets pour les faces.
References domaine(), and Process::je_suis_maitre().
Referenced by Domaine_VF::discretiser().
calculer_espace_distant_aretes()
void Scatter::calculer_espace_distant_aretes (Domaine & domaine, const int nb_aretes_reelles, const IntTab & elem_aretes) static
Idem que Scatter::calculer_espace_distant_sommets pour les aretes.
References domaine(), and Process::je_suis_maitre().
calculer_espace_distant_elements()
void Scatter::calculer_espace_distant_elements (Domaine & dom) static
Remplissage du tableau "espace_distant()" des elements dans les joints.
C'est ici qu'on determine les elements de joint en fonction de l'epaisseur de joint. Le tableau espace_distant contient les indices locaux des elements distants (a envoyer aux processeurs voisins) Pour un joint d'epaisseur 1, ce sont tous les elements voisins d'un sommet de joint (sommet sur un face de joint ou sommet isole). Pour un joint d'epaisseur n>1, ce sont tous les elements voisins d'un sommet d'un element du joint d'epaisseur n-1. Le voisinage s'entend sur le domaine global (toutes domaines confondues) Historique: premiere version B.Mathieu le 16/01/2007. Il existe une methode qui determine les elements distants au moment du decoupage (DomaineCutter::construire_elements_distants_ssdom). La methode ci-dessous a ete validee par comparaison avec la methode du decoupeur. Les sorties ont ete verifiees pour des epaisseurs jusqu'a 5 sur des maillages tetra. La difficulte de l'algorithme est d'obtenir les elements virtuels d'epaisseur > 1 qui se trouvent sur des sous-domaines qui ne sont pas en contact direct avec le sous-domaine local. Difficulte resolue par l'algorithme ci-dessous.
References ajouter_joints(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Entree::eof(), Process::exit(), Static_Int_Lists_32_64< _SIZE_ >::get_list_size(), Process::je_suis_maitre(), Domaine_32_64< _SIZE_ >::joint(), Process::Journal(), Domaine_32_64< _SIZE_ >::les_elems(), Process::me(), Process::mp_max(), Process::mp_or(), Domaine_32_64< _SIZE_ >::nb_joints(), Domaine_32_64< _SIZE_ >::nb_som(), Domaine_32_64< _SIZE_ >::nb_som_elem(), Process::nproc(), Schema_Comm::recv_buffer(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), Schema_Comm::send_buffer(), Static_Int_Lists_32_64< _SIZE_ >::set_list_sizes(), Schema_Comm::set_send_recv_pe_list(), Static_Int_Lists_32_64< _SIZE_ >::set_value(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by construire_structures_paralleles().
corriger_espace_distant_elements_perio()
void Scatter::corriger_espace_distant_elements_perio (Domaine & dom, const Noms & liste_bords_periodiques) static
Les algorithmes actuels pour le periodique (assembleur P1B, OpDivElem P1B) ont besoin que pour chaque face virtuelle periodique, la face opposee soit.
aussi virtuelle. Ceci n'est pas assure a la sortie de la methode calculer_elements_distants. Cette methode ajoute aux elements distants les elements manquants pour assurer cette condition: Si un element est distant pour un PE donne est voisin d'une face periodique, on ajoute a l'espace distant l'element adjacent a la face opposee.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Domaine_32_64< _SIZE_ >::bord(), ArrOfBit_32_64< _SIZE_ >::clearbit(), Process::exit(), Process::je_suis_maitre(), Domaine_32_64< _SIZE_ >::joint(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_joints(), Domaine_32_64< _SIZE_ >::nb_som(), TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array(), ArrOfBit_32_64< _SIZE_ >::setbit(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and ArrOfBit_32_64< _SIZE_ >::testsetbit().
Referenced by construire_structures_paralleles().
calculer_espace_distant_sommets()
void Scatter::calculer_espace_distant_sommets (Domaine & dom, const Noms & liste_bords_perio) static
En fonction de l'espace distant des elements, calcule l'espace distant des sommets.
Pour chaque joint, on envoie au processeur voisin l'ensemble des sommets de tous les elements du joint. C'est le processeur proprietaire du sommet (plus petit pe qui le possede) qui le met dans son espace distant. Attention, on cree de nouveaux joints. On remplit les tableaux dom.faces_joint(i).joint_item(JOINT_ITEM::SOMMET).items_distants();
References Process::je_suis_maitre(), Domaine_32_64< _SIZE_ >::les_elems(), and Domaine_32_64< _SIZE_ >::nb_som().
Referenced by construire_structures_paralleles().
construire_espace_virtuel_traduction()
void Scatter::construire_espace_virtuel_traduction (const MD_Vector & md_indice, const MD_Vector & md_valeur, IntTab & tableau, const int error_is_fatal = 1) static
Construit la structure items_communs + espaces virtuels d'un tableau contenant des indices d'items geometriques, indexe par un autre type d'item geometrique.
Exemple: tableau indexe par md_indice, contenant des indices md_valeur: type_indice type_valeur exemple de tableau: element sommet domaine.les_elems() face sommet faces_sommets element face elem_faces face element faces_voisins element element ? element arete elem_aretes Nb_valeurs_max est le nombre d'items reels de type "type_valeur".
References MD_Vector_tools::creer_tableau_distribue(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), MD_Vector_base::get_nb_items_reels(), MD_Vector_base::get_nb_items_tot(), Process::is_sequential(), Process::me(), TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector(), and MD_Vector::valeur().
Referenced by Periodique::completer(), construire_structures_paralleles(), and Domaine_VF::discretiser().
reordonner_faces_de_joint()
void Scatter::reordonner_faces_de_joint (Domaine & dom) static
Reordonne les faces de joint de sorte qu'elles apparaissent dans le meme ordre sur chaque couple de processeur voisin.
En pratique, pour un couple pe1 < pe2, pe1 envoie ses faces de joint a pe2 et pe2 les traduit en indices de sommets locaux. Les faces de joint du PE2 ne sont donc pas utilisees.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Process::exit(), Domaine_32_64< _SIZE_ >::faces_joint(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Domaine_32_64< _SIZE_ >::les_sommets(), Process::me(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by construire_structures_paralleles().
ajouter_joints()
void Scatter::ajouter_joints (Domaine & domaine, ArrOfInt & pe_voisins) static
Ajoute des joints avec tous les pe de pe_voisins.
Pour que l'ensemble des joints soit symetrique, on en cree aussi un joint sur le processeur destination: Si A ajoute un joint avec B, alors B ajoute un joint avec A. On trie les joints par ordre croissant du numero de PE. ATTENTION: les joints sont donc reordonnes ! On met dans pe_voisins la liste des joints effectivement crees.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), domaine(), Domaine_32_64< _SIZE_ >::faces_joint(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and trier_les_joints().
Referenced by calculer_espace_distant(), and calculer_espace_distant_elements().
trier_les_joints()
void Scatter::trier_les_joints (Joints & joints) static
Tri des joints dans l'ordre croissant des processeurs.
References TRUSTArray< _TYPE_, _SIZE_ >::ordonne_array().
Referenced by ajouter_joints(), DomaineCutter_32_64< _SIZE_ >::construire_sous_domaine(), and lire_domaine().
construire_md_vector()
void Scatter::construire_md_vector (const Domaine & dom, int nb_items_reels, const JOINT_ITEM type_item, MD_Vector & md_vector) static
construction d'un MD_Vector_std a partir des informations de joint du domaine pour le type d'item demande.
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), MD_Vector::copy(), MD_Vector_tools::creer_tableau_distribue(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_32_64< _SIZE_ >::faces_joint(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), Process::is_sequential(), Process::me(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and ArrOfBit_32_64< _SIZE_ >::testsetbit().
Referenced by construire_structures_paralleles(), and Domaine_VF::discretiser().
check_consistancy_remote_items()
void Scatter::check_consistancy_remote_items (Domaine & dom, const ArrOfInt & mergedDomaines) static
Merged domaines receive joints information from their neighbours to ensure that their common items (vertices) appear in the same order.
If it's not the case, the merged domaine reorders its common items so that it matches the neighbour's order When 2 neighbouring domaines have each been merged, only the processor with the lowest rank proceeds to reordering
References TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Schema_Comm::begin_comm(), Objet_U::dimension, Schema_Comm::echange_taille_et_messages(), Schema_Comm::end_comm(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::les_sommets(), Process::me(), Schema_Comm::recv_buffer(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Schema_Comm::send_buffer(), Schema_Comm::set_send_recv_pe_list(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by lire_domaine().
init_sequential_domain()
template<typename _SIZE_ > template void Scatter::init_sequential_domain (Domaine_32_64< _SIZE_ > & dom) static
Create parallel descriptors for the vertex and element arrays of the domain (necessary because Scatter is never invoked in sequential).
In 64bit the corresponding number of items might be big. This is here the main justification for the need of the class MD_Vector_seq which unique useful argument is the total number of items (with type trustIdType). Alternative would have been to make all members of MD_Vector_std compatible with trustIdType ...
References MD_Vector::copy(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), and TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector().
Referenced by Rectify_Mesh::apply_2D(), Refine_Mesh::apply_2D(), Rectify_Mesh::apply_3D(), Refine_Mesh::apply_3D(), Decouper_Bord_coincident::decouper_(), interpreter(), MaillerParallel::interpreter(), Create_domain_from_sub_domain::interpreter_(), ExtrudeBord::interpreter_(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Lire_Ideas::interpreter_(), Mailler_32_64< _SIZE_ >::interpreter_(), Polyedriser_32_64< _SIZE_ >::interpreter_(), Raffiner_anisotrope_32_64< _SIZE_ >::interpreter_(), Remove_elem::interpreter_(), Reorienter_tetraedres_32_64< _SIZE_ >::interpreter_(), Reorienter_triangles_32_64< _SIZE_ >::interpreter_(), Triangulation_base::interpreter_(), TroisDto2D_32_64< _SIZE_ >::interpreter_(), VerifierCoin::interpreter_(), Orienter_Simplexes::interpreter_(), Raffiner_Simplexes_32_64< _SIZE_ >::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), lire_domaine(), LireMED_32_64< _SIZE_ >::lire_geom(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), and Transformer_32_64< _SIZE_ >::transformation_complete().
uninit_sequential_domain()
template<typename _SIZE_ > template void Scatter::uninit_sequential_domain (Domaine_32_64< _SIZE_ > & dom) static
methode utilisee par les interpretes qui modifient le domaine (sequentiel), detruit les descripteurs des sommets et elements pour permettre la modification de ces tableaux.
References Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), and TRUSTTab< _TYPE_, _SIZE_ >::set_md_vector().
Referenced by Rectify_Mesh::apply_2D(), Refine_Mesh::apply_2D(), Rectify_Mesh::apply_3D(), Refine_Mesh::apply_3D(), Decouper_Bord_coincident::decouper_(), interpreter(), ExtrudeParoi::interpreter_(), Extruder::interpreter_(), Extruder_en20::interpreter_(), Extruder_en3::interpreter_(), Mailler_32_64< _SIZE_ >::interpreter_(), Polyedriser_32_64< _SIZE_ >::interpreter_(), Raffiner_anisotrope_32_64< _SIZE_ >::interpreter_(), Remove_elem::interpreter_(), Reorienter_tetraedres_32_64< _SIZE_ >::interpreter_(), Reorienter_triangles_32_64< _SIZE_ >::interpreter_(), Triangulation_base::interpreter_(), TroisDto2D_32_64< _SIZE_ >::interpreter_(), VerifierCoin::interpreter_(), Orienter_Simplexes::interpreter_(), Raffiner_Simplexes_32_64< _SIZE_ >::interpreter_(), Remove_Invalid_Internal_Boundaries::interpreter_(), LireMED_32_64< _SIZE_ >::lire_geom(), NettoieNoeuds_32_64< _SIZE_ >::nettoie(), read_domain_no_comm(), and Transformer_32_64< _SIZE_ >::transformation_complete().
OBS_PTR()
Scatter::OBS_PTR (Domaine) protected
read_domain_no_comm()
void Scatter::read_domain_no_comm (Entree & fic) protected
Does the exact same thing as the readOn of the class Domaine but without collective communication.
Necessary when the processors don't have the same numbers of file to read
References Domaine_32_64< _SIZE_ >::ajouter(), TRUSTArray< _TYPE_, _SIZE_ >::append_array(), Process::exit(), Domaine_32_64< _SIZE_ >::faces_joint(), Domaine_32_64< _SIZE_ >::les_sommets(), Domaine_32_64< _SIZE_ >::merge_wo_vertices_with(), Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_32_64< _SIZE_ >::nb_joints(), Domaine_32_64< _SIZE_ >::read_former_domaine(), Domaine_32_64< _SIZE_ >::read_vertices(), Domaine_32_64< _SIZE_ >::renum(), Domaine_32_64< _SIZE_ >::renum_joint_common_items(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and uninit_sequential_domain().
Referenced by lire_domaine().