CEA TRUST Platform: bprinter::TablePrinter Class Reference
bprinter::TablePrinter Class Reference
#include <TablePrinter.h>
Public Member Functions
void AddColumn (const std::string &header_name, int column_width)
Detailed Description
Print a pretty table into your output of choice.
Usage: TablePrinter tp(&std::cout); tp.AddColumn("Name", 25); tp.AddColumn("Age", 3); tp.AddColumn("Position", 30);
tp.PrintHeader(); tp << "Dat Chu" << 25 << "Research Assistant"; tp << "John Doe" << 26 << "Professional Anonymity"; tp << "Jane Doe" << tp.SkipToNextLine(); tp << "Tom Doe" << 7 << "Student"; tp.PrintFooter();
Todo:
Add support for padding in each table cell
Constructor & Destructor Documentation
TablePrinter()
bprinter::TablePrinter::TablePrinter (std::ostream * output, const std::string & separator = "│")
~TablePrinter()
bprinter::TablePrinter::~TablePrinter ()
Member Function Documentation
get_num_columns()
int bprinter::TablePrinter::get_num_columns () const
Referenced by operator<<(), and PrintHeader().
get_table_width()
int bprinter::TablePrinter::get_table_width () const
set_separator()
void bprinter::TablePrinter::set_separator (const std::string & separator)
set_flush_left()
void bprinter::TablePrinter::set_flush_left ()
set_flush_right()
void bprinter::TablePrinter::set_flush_right ()
AddColumn()
void bprinter::TablePrinter::AddColumn (const std::string & header_name, int column_width)
Add a column to our table.
Parameters
header_name Name to be print for the header
column_width the width of the column (has to be >=5)
Referenced by SETS::iterer_NS().
PrintHeader()
void bprinter::TablePrinter::PrintHeader ()
References get_num_columns().
Referenced by SETS::iterer_NS().
PrintFooter()
void bprinter::TablePrinter::PrintFooter ()
operator<<() [1/4]
TablePrinter & bprinter::TablePrinter::operator<< (endl input) inline
operator<<() [2/4]
TablePrinter & bprinter::TablePrinter::operator<< (float input)
operator<<() [3/4]
TablePrinter & bprinter::TablePrinter::operator<< (double input)
operator<<() [4/4]
template<typename T > TablePrinter & bprinter::TablePrinter::operator<< (T input) inline
References get_num_columns().