CEA TRUST Platform: Eval_Darcy_VDF_Face Class Reference
Eval_Darcy_VDF_Face Class Reference
#include <Eval_Darcy_VDF_Face.h>
Constructor & Destructor Documentation
Eval_Darcy_VDF_Face() [1/2]
Eval_Darcy_VDF_Face::Eval_Darcy_VDF_Face () inline
Eval_Darcy_VDF_Face() [2/2]
Eval_Darcy_VDF_Face::Eval_Darcy_VDF_Face (const Eval_Darcy_VDF_Face & eval) inline
Member Function Documentation
getPorosite()
double & Eval_Darcy_VDF_Face::getPorosite () inline
References porosite_.
Referenced by Source_Darcy_VDF_Face::lire_motcle_non_standard().
calculer_terme_source()
template<typename Type_Double > void Eval_Darcy_VDF_Face::calculer_terme_source (const int num_face, Type_Double & source) const
References db_diffusivite_, porosite_, Evaluateur_Source_Face::porosite_surf, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and Evaluateur_Source_Face::volumes_entrelaces.
Referenced by calculer_terme_source_bord().
calculer_terme_source_bord()
template<typename Type_Double > void Eval_Darcy_VDF_Face::calculer_terme_source_bord (int num_face, Type_Double & source) const inline
References calculer_terme_source().
mettre_a_jour()
void Eval_Darcy_VDF_Face::mettre_a_jour () inline override virtual
Implements Evaluateur_Source.
References db_diffusivite_.
Referenced by associer().
associer() [1/2]
void Eval_Darcy_VDF_Face::associer (const Champ_Don_base & diffu) inline
associe le champ de diffusivite
References db_diffusivite_, mettre_a_jour(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Source_Darcy_VDF_Face::associer_pb().
associer() [2/2]
void Eval_Darcy_VDF_Face::associer (const Champ_Inc_base & vit) inline
OWN_PTR()
Eval_Darcy_VDF_Face::OWN_PTR (Modele_Permeabilite_base)
OBS_PTR() [1/2]
Eval_Darcy_VDF_Face::OBS_PTR (Champ_Inc_base) protected
OBS_PTR() [2/2]
Eval_Darcy_VDF_Face::OBS_PTR (Champ_Don_base) protected
Member Data Documentation
db_diffusivite_
DoubleTab Eval_Darcy_VDF_Face::db_diffusivite_ protected
Referenced by associer(), calculer_terme_source(), and mettre_a_jour().
porosite_
double Eval_Darcy_VDF_Face::porosite_ protected
Referenced by calculer_terme_source(), and getPorosite().