CEA TRUST Platform: Terme_Source_Qdm_VEF_Face Class Reference
Terme_Source_Qdm_VEF_Face Class Reference
Public Member Functions
void mettre_a_jour (double) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int initialiser (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don_base & source () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Source_base
Member Function Documentation
associer_pb()
void Terme_Source_Qdm_VEF_Face::associer_pb (const Probleme_base &) override virtual
Implements Source_base.
ajouter()
DoubleTab & Terme_Source_Qdm_VEF_Face::ajouter (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References BilanQdmVEF::bilan_energie(), BilanQdmVEF::bilan_qdm(), Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), MorEqn::equation(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Domaine_Cl_dis_base::les_conditions_limites(), Domaine_32_64< _SIZE_ >::les_elems(), Domaine_32_64< _SIZE_ >::les_sommets(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_face(), Domaine_VEF::rang_elem_non_std(), Domaine_Cl_VEF::type_elem_Cl(), and Domaine_VF::volumes().
Referenced by Source_qdm_QC_VEF_P1NC::ajouter_mere(), and calculer().
calculer()
DoubleTab & Terme_Source_Qdm_VEF_Face::calculer (DoubleTab & resu) const override virtual
Reimplemented from Source_base.
References ajouter().
mettre_a_jour()
void Terme_Source_Qdm_VEF_Face::mettre_a_jour (double temps) override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
OBS_PTR() [1/2]
Terme_Source_Qdm_VEF_Face::OBS_PTR (Domaine_VEF) protected
OBS_PTR() [2/2]
Terme_Source_Qdm_VEF_Face::OBS_PTR (Domaine_Cl_VEF) protected
associer_domaines()
void Terme_Source_Qdm_VEF_Face::associer_domaines (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis) override protected virtual
Implements Source_base.