CEA TRUST Platform: DebogIJK Class Reference
DebogIJK Class Reference
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Member Enumeration Documentation
DebogMode
enum DebogIJK::DebogMode
Enumerator
DISABLED
WRITE_PASS
CHECK_PASS
Member Function Documentation
interpreter()
Entree & DebogIJK::interpreter (Entree & is) override virtual
Implements Interprete.
References Param::ajouter(), CHECK_PASS, debog_mode_, Param::dictionnaire(), DISABLED, filename_, infile_, Process::je_suis_maitre(), Param::lire_avec_accolades(), outfile_, Entree_Fichier_base::ouvrir(), Sortie_Fichier_base::ouvrir(), Objet_U::que_suis_je(), seuil_absolu_, seuil_minimum_relatif_, seuil_relatif_, and WRITE_PASS.
verifier() [1/3]
void DebogIJK::verifier (const char * msg, const IJK_Field_float & f) static
References compute_signature(), debog_mode_, DISABLED, Entree_Fichier_base::get_ifstream(), infile_, Process::je_suis_maitre(), Process::Journal(), outfile_, seuil_absolu_, seuil_minimum_relatif_, seuil_relatif_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and WRITE_PASS.
verifier() [2/3]
void DebogIJK::verifier (const char * msg, const IJK_Field_double & f) static
References compute_signature(), debog_mode_, DISABLED, Entree_Fichier_base::get_ifstream(), infile_, Process::je_suis_maitre(), Process::Journal(), outfile_, seuil_absolu_, seuil_minimum_relatif_, seuil_relatif_, TRUSTArray< _TYPE_, _SIZE_ >::size_array(), and WRITE_PASS.
verifier() [3/3]
static void DebogIJK::verifier (const double) static
compute_signature() [1/2]
void DebogIJK::compute_signature (const IJK_Field_float & field, ArrOfDouble & signature) static protected
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_offset_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nb_elem_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Referenced by verifier().
compute_signature() [2/2]
void DebogIJK::compute_signature (const IJK_Field_double & field, ArrOfDouble & signature) static protected
References IJK_Field_template< _TYPE_, _TYPE_ARRAY_ >::get_domaine(), Domaine_IJK::get_offset_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nb_elem_local(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::ni(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nj(), IJK_Field_local_template< _TYPE_, _TYPE_ARRAY_ >::nk(), and TRUSTArray< _TYPE_, _SIZE_ >::resize_array().
Member Data Documentation
seuil_absolu_
double DebogIJK::seuil_absolu_ = 1e-4 static protected
Referenced by interpreter(), and verifier().
seuil_relatif_
double DebogIJK::seuil_relatif_ = 1e-8 static protected
Referenced by interpreter(), and verifier().
seuil_minimum_relatif_
double DebogIJK::seuil_minimum_relatif_ = 1e-4 static protected
Referenced by interpreter(), and verifier().
debog_mode_
int DebogIJK::debog_mode_ = DebogIJK::DISABLED static protected
Referenced by interpreter(), and verifier().
filename_
Nom DebogIJK::filename_ static protected
Referenced by interpreter().
infile_
EFichier DebogIJK::infile_ static protected
Referenced by interpreter(), and verifier().
outfile_
SFichier DebogIJK::outfile_ static protected
Referenced by interpreter(), and verifier().