CEA TRUST Platform: Piso Class Reference
Piso Class Reference
#include <Piso.h>
Member Function Documentation
iterer_NS()
void Piso::iterer_NS (Equation_base & eqn, DoubleTab & current, DoubleTab & pression, double dt, Matrice_Morse & matrice, double seuil_resol, DoubleTrav & secmem, int nb_iter, int & converge, int & ok) override virtual
Implements Simpler_Base.
References Operateur_Div::ajouter(), Matrice_Base::ajouter_multvect(), Solveur_Masse_base::appliquer(), Equation_base::assembler_avec_inertie(), Equation_base::assembler_blocs_avec_inertie(), Simpler_Base::assembler_matrice_pression_implicite(), avancement_crank_, Operateur_Div::calculer(), Operateur_Grad::calculer(), Simple::calculer_correction_en_vitesse(), Solveur_Masse_base::corriger_solution(), Equation_base::discretisation(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), first_special_treatment(), Simpler_Base::get_and_set_parametre_implicite(), Navier_Stokes_std::has_interface_blocs(), Probleme_base::is_dilatable(), Discretisation_base::is_polymac_family(), Navier_Stokes_std::matrice_pression(), Equation_base::milieu(), nb_corrections_max_, Navier_Stokes_std::operateur_divergence(), Navier_Stokes_std::operateur_gradient(), Equation_base::probleme(), Objet_U::que_suis_je(), SolveurSys::resoudre_systeme(), Fluide_Dilatable_base::secmembre_divU_Z(), second_special_treatment(), Equation_base::solv_masse(), Parametre_implicite::solveur(), Navier_Stokes_std::solveur_pression(), Debog::verifier(), and Simple::with_d_rho_dt_.
first_special_treatment()
void Piso::first_special_treatment (Equation_base & eqn, Navier_Stokes_std & eqnNS, DoubleTab & current, double dt, DoubleTrav & resu) virtual
Reimplemented in Implicite.
Referenced by iterer_NS().
second_special_treatment()
void Piso::second_special_treatment (Equation_base & eqn, DoubleTab & current, DoubleTrav & resu, Matrice_Morse & matrice) virtual
Reimplemented in Implicite.
Referenced by iterer_NS().
lire()
Entree & Piso::lire (const Motcle & motlu, Entree & is) override protected virtual
Implements Simpler_Base.
References nb_corrections_max_, and Motcles::search().
Member Data Documentation
nb_corrections_max_
int Piso::nb_corrections_max_ = 21 protected
Referenced by iterer_NS(), and lire().
avancement_crank_
int Piso::avancement_crank_ = 0 protected
Referenced by iterer_NS().