CEA TRUST Platform: Source_Fluide_Dilatable_VDF_Proto Class Reference
Source_Fluide_Dilatable_VDF_Proto Class Reference
Member Function Documentation
associer_domaines_impl()
void Source_Fluide_Dilatable_VDF_Proto::associer_domaines_impl (const Domaine_dis_base & domaine, const Domaine_Cl_dis_base & domaine_cl) protected
Referenced by Source_QC_Chaleur_VDF::associer_domaines(), Source_QC_Gravite_VDF::associer_domaines(), Source_WC_Gravite_VDF::associer_domaines(), and Source_WC_Chaleur_VDF::associer_domaines().
associer_volume_porosite_impl()
void Source_Fluide_Dilatable_VDF_Proto::associer_volume_porosite_impl (const Domaine_dis_base & domaine, DoubleVect & volumes, DoubleVect & porosites) protected
References TRUSTVect< _TYPE_, _SIZE_ >::ref().
Referenced by Source_QC_Chaleur_VDF::associer_domaines(), and Source_WC_Chaleur_VDF::associer_domaines().
ajouter_impl()
void Source_Fluide_Dilatable_VDF_Proto::ajouter_impl (const DoubleVect & g, const double rho_m, const DoubleTab & tab_rho, DoubleTab & resu) const protected
References Front_VF::nb_faces(), and Front_VF::num_premiere_face().
Referenced by Source_QC_Gravite_VDF::ajouter_blocs(), and Source_WC_Gravite_VDF::ajouter_blocs().
OBS_PTR() [1/2]
Source_Fluide_Dilatable_VDF_Proto::OBS_PTR (Domaine_Cl_VDF) protected
OBS_PTR() [2/2]
Source_Fluide_Dilatable_VDF_Proto::OBS_PTR (Domaine_VDF) protected