CEA TRUST Platform: Masse_PolyMAC_P0_Face Class Reference
Masse_PolyMAC_P0_Face Class Reference
#include <Masse_PolyMAC_P0_Face.h>
Additional Inherited Members
Public Member Functions inherited from Solveur_Masse_base
virtual DoubleTab & appliquer (DoubleTab &) const
virtual void assembler ()
virtual void mettre_a_jour (double temps)
virtual void resetTime (double temps)
void set_name_of_coefficient_temporel (const Nom &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
completer()
void Masse_PolyMAC_P0_Face::completer () override virtual
Reimplemented from Masse_PolyMAC_base.
References Solveur_Masse_Face_proto::associer_masse_proto(), Solveur_Masse_base::completer(), MorEqn::equation(), Equation_base::inconnue(), and Champ_Face_PolyMAC_P0::init_auxiliary_variables().
appliquer_impl()
DoubleTab & Masse_PolyMAC_P0_Face::appliquer_impl (DoubleTab & sm) const override virtual
Implements Solveur_Masse_base.
References Solveur_Masse_Face_proto::appliquer_impl_proto(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Milieu_base::porosite_elem(), and Champ_Inc_base::valeurs().
corriger_solution()
DoubleTab & Masse_PolyMAC_P0_Face::corriger_solution (DoubleTab & x, const DoubleTab & y, int incr = 0) const override virtual
Reimplemented from Masse_PolyMAC_P0P1NC_Face.
References MorEqn::equation(), Option_PolyMAC::INTERP_VE1, Champ_Face_PolyMAC_P0::update_ve(), and Champ_Face_PolyMAC_P0::update_ve2().
dimensionner_blocs()
void Masse_PolyMAC_P0_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl) const override virtual
Reimplemented from Solveur_Masse_base.
References Matrix_tools::allocate_morse_matrix(), TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, Solveur_Masse_Face_proto::dimensionner_blocs_proto(), MorEqn::equation(), Probleme_base::get_correlation(), Nom::getString(), Probleme_base::has_correlation(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Matrice_Morse::nb_colonnes(), TRUSTVect< _TYPE_, _SIZE_ >::size_totale(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Masse_PolyMAC_P0_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, double dt, const tabs_t & semi_impl, int resoudre_en_increments) const override virtual
Reimplemented from Solveur_Masse_base.
References Masse_ajoutee_base::ajouter(), Equation_base::champ_conserve(), Objet_U::dimension, MorEqn::equation(), Pb_Multiphase::equation_masse(), Equation_base::get_champ(), Probleme_base::get_correlation(), Nom::getString(), Solveur_Masse_base::has_coefficient_temporel_, Probleme_base::has_correlation(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Solveur_Masse_base::name_of_coefficient_temporel_, Champ_Proto::passe(), Champ_Inc_base::passe(), Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().