CEA TRUST Platform: Champ_Generique_Extraction Class Reference
Champ_Generique_Extraction Class Reference
#include <Champ_Generique_Extraction.h>
Public Member Functions
void get_copy_domain (Domaine &) const override
Entity get_localisation (const int index=-1) const override
const Noms get_property (const Motcle &query) const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Generique_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Champ_Generique_Extraction()
Champ_Generique_Extraction::Champ_Generique_Extraction ()
References methode_, and Champ_Gen_de_Champs_Gen::reset().
Member Function Documentation
set_param()
void Champ_Generique_Extraction::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Param::ajouter(), dom_extrac_, methode_, nom_fr_, Param::REQUIRED, and Champ_Gen_de_Champs_Gen::set_param().
get_localisation()
Entity Champ_Generique_Extraction::get_localisation (const int index = -1) const override virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un.
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans parametre, sauf si on sait quoi faire pour les champs multi-supports.
See also
get_nb_localisations() Parametre : index Signification : index de la localisation demandee (pour les champs multi-support). Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support. Si index >= 0 : on renvoie le i-ieme support. Valeur par defaut : -1 Exceptions:
GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques (il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
get_champ()
const Champ_base & Champ_Generique_Extraction::get_champ (OWN_PTR(Champ_base)& espace_stockage) const override
Extraction des valeurs d un champ (trace ou champ frontiere) sur un bord du domaine.
References Objet_U::dimension, Equation_base::domaine_Cl_dis(), MorEqn::equation(), Process::exit(), Field_base::fixer_nature_du_champ(), Field_base::fixer_nb_comp(), Frontiere_dis_base::frontiere(), Domaine_dis_base::frontiere_dis(), Champ_Generique_base::get_champ(), Champ_Generique_base::get_discretisation(), Champ_Generique_base::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::get_time(), Discretisation_base::is_ef(), Discretisation_base::is_vdf(), Discretisation_base::is_vef(), Field_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), methode_, Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), Frontiere_32_64< _SIZE_ >::nb_faces(), nom_fr_, Champ_Gen_de_Champs_Gen::OWN_PTR(), Objet_U::que_suis_je(), Domaine_dis_base::rang_frontiere(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Champ_base::trace(), Champ_front_base::valeurs(), and Champ_Proto::valeurs().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Extraction::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const override virtual
Implements Champ_Generique_base.
References Champ_Generique_base::get_champ_without_evaluation(), Champ_Gen_de_Champs_Gen::get_source(), Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), and Champ_Gen_de_Champs_Gen::OWN_PTR().
get_property()
const Noms Champ_Generique_Extraction::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Gen_de_Champs_Gen::nb_comp, Champ_Generique_base::nom_post_, and Motcles::search().
Referenced by completer().
nommer_source()
void Champ_Generique_Extraction::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
completer()
void Champ_Generique_Extraction::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Gen_de_Champs_Gen::completer(), discretiser_domaine(), dom_extrac_, Process::exit(), Frontiere_32_64< _SIZE_ >::faces(), Frontiere_dis_base::frontiere(), Domaine_dis_base::frontiere_dis(), Champ_Generique_base::get_champ(), Champ_Generique_base::get_discretisation(), get_property(), Champ_Generique_base::get_ref_connectivity(), Champ_Generique_base::get_ref_domain(), Champ_Generique_base::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Objet_U::interprete(), Discretisation_base::is_vdf(), Discretisation_base::is_vef(), Field_base::le_nom(), Nom::le_nom(), Domaine_32_64< _SIZE_ >::les_sommets(), methode_, Frontiere_32_64< _SIZE_ >::nb_faces(), Domaine_VF::nb_frontiere_dis(), Domaine_VF::nb_som_face(), nom_fr_, Champ_Generique_base::nom_post_, Frontiere_32_64< _SIZE_ >::num_premiere_face(), Interprete::objet(), Champ_Gen_de_Champs_Gen::OWN_PTR(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::reset(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
get_ref_domain()
const Domaine & Champ_Generique_Extraction::get_ref_domain () const override virtual
Renvoie une ref au domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Gen_de_Champs_Gen.
References Process::exit(), and get_ref_domain().
Referenced by get_copy_domain(), and get_ref_domain().
get_copy_domain()
void Champ_Generique_Extraction::get_copy_domain (Domaine & domain) const override virtual
Cree une copie du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Gen_de_Champs_Gen.
References get_ref_domain().
get_ref_domaine_dis_base()
const Domaine_dis_base & Champ_Generique_Extraction::get_ref_domaine_dis_base () const override virtual
Renvoie une ref au domaine_discretisee du domaine sur lequel sera evalue l espace de stockage.
Par defaut le domaine associe au probleme.
Reimplemented from Champ_Gen_de_Champs_Gen.
References Process::exit(), and get_ref_domaine_dis_base().
Referenced by get_ref_domaine_dis_base().
discretiser_domaine()
void Champ_Generique_Extraction::discretiser_domaine ()
References Domaine_dis_cache::Build_or_get(), Probleme_base::discretisation(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), and Objet_U::que_suis_je().
Referenced by completer().
get_directive_pour_discr()
const Motcle Champ_Generique_Extraction::get_directive_pour_discr () const override virtual
Renvoie la directive (champ_elem, champ_sommets, champ_face ou pression) pour lancer la discretisation de l espace de stockage rendu par get_champ()
Reimplemented from Champ_Gen_de_Champs_Gen.
OBS_PTR() [1/2]
Champ_Generique_Extraction::OBS_PTR (Domaine) protected
OBS_PTR() [2/2]
Champ_Generique_Extraction::OBS_PTR (Domaine_dis_base) protected
Member Data Documentation
dom_extrac_
Nom Champ_Generique_Extraction::dom_extrac_ protected
Referenced by completer(), and set_param().
nom_fr_
Nom Champ_Generique_Extraction::nom_fr_ protected
Referenced by completer(), get_champ(), and set_param().
methode_
Nom Champ_Generique_Extraction::methode_ protected
Referenced by Champ_Generique_Extraction(), completer(), get_champ(), and set_param().