CEA TRUST Platform: Vitesse_relative_base Class Reference
Vitesse_relative_base Class Reference abstract
#include <Vitesse_relative_base.h>
Classes
struct input_t
struct output_t
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
correlations de vitesse relative de la forme ur = (v_k - v_l)
Member Function Documentation
vitesse_relative()
virtual void Vitesse_relative_base::vitesse_relative (const input_t & input, output_t & output) const pure virtual
Implemented in Vitesse_derive_base.
Referenced by Op_Evanescence_Homogene_Face_base::ajouter_blocs(), and Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux().
needs_grad_alpha()
virtual bool Vitesse_relative_base::needs_grad_alpha () const inline virtual
Reimplemented in Vitesse_derive_Forces.
Referenced by Op_Evanescence_Homogene_Face_base::ajouter_blocs(), Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux(), and Op_Evanescence_Homogene_VDF_Face::preparer_calcul().
needs_vort()
virtual bool Vitesse_relative_base::needs_vort () const inline virtual
Reimplemented in Vitesse_derive_Forces.
Referenced by Op_Evanescence_Homogene_Face_base::ajouter_blocs(), and Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux().
set_param()
virtual void Vitesse_relative_base::set_param (Param & param) inline virtual
Reimplemented in Vitesse_derive_base, Vitesse_derive_constante, Vitesse_derive_Forces, and Vitesse_derive_Ishii.
Referenced by Vitesse_derive_base::set_param().
Member Data Documentation
n_l
int Vitesse_relative_base::n_l = -1 protected
Referenced by Vitesse_derive_Forces::evaluate_C0_vg0(), Vitesse_derive_Ishii::evaluate_C0_vg0(), and Vitesse_derive_base::vitesse_relative().
n_g
int Vitesse_relative_base::n_g = -1 protected
Referenced by Vitesse_derive_Forces::evaluate_C0_vg0(), Vitesse_derive_Ishii::evaluate_C0_vg0(), and Vitesse_derive_base::vitesse_relative().