CEA TRUST Platform: Op_Diff_PolyMAC_P0_Face Class Reference
Op_Diff_PolyMAC_P0_Face Class Reference
Public Member Functions
void ajouter_blocs (matrices_t matrices, DoubleTab &secmem, const tabs_t &semi_impl={ }) const override
double calculer_dt_stab () const override
void completer () override
void dimensionner_blocs (matrices_t matrices, const tabs_t &semi_impl={ }) const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Op_Diff_PolyMAC_P0_base
void mettre_a_jour (double t) override
Public Member Functions inherited from Op_Diff_PolyMAC_Gen_base
int impr (Sortie &os) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
completer()
void Op_Diff_PolyMAC_P0_Face::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Op_Diff_PolyMAC_P0_base.
Reimplemented in Op_Diff_Turbulent_PolyMAC_P0_Face.
References Op_Diff_PolyMAC_P0_base::completer(), Objet_U::dimension, MorEqn::equation(), Process::exit(), Operateur_base::flux_bords_, Champ_Face_PolyMAC_P0::init_auxiliary_variables(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), porosite_e, porosite_f, TRUSTVect< _TYPE_, _SIZE_ >::ref(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Champ_Inc_base::valeurs().
Referenced by Op_Diff_Turbulent_PolyMAC_P0_Face::completer().
modifier_pour_Cl()
void Op_Diff_PolyMAC_P0_Face::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
has_interface_blocs()
int Op_Diff_PolyMAC_P0_Face::has_interface_blocs () const inline override virtual
Reimplemented from Operateur_base.
calculer_dt_stab()
double Op_Diff_PolyMAC_P0_Face::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Equation_base::inconnue(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Process::mp_min(), Op_Diff_PolyMAC_Gen_base::nu_, Milieu_base::porosite_elem(), Milieu_base::porosite_face(), Option_PolyMAC::TRAITEMENT_AXI, Op_Diff_PolyMAC_P0_base::update_nu(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
dimensionner_blocs()
void Op_Diff_PolyMAC_P0_Face::dimensionner_blocs (matrices_t matrices, const tabs_t & semi_impl = { }) const override virtual
Dimensions the blocks of matrices for the PolyMAC P0 face diffusion operator.
This method is responsible for dimensioning the matrix blocks used in the diffusion operation for the PolyMAC P0 face discretization scheme. It calculates the stencil for the diffusion operator and allocates the necessary memory for the matrix.
Parameters
matrices A map of matrices where the matrix for the unknown field will be stored.
semi_impl A map indicating semi-implicit fields.
Reimplemented from Operateur_base.
References Matrix_tools::allocate_morse_matrix(), Objet_U::dimension, MorEqn::equation(), Champ_Face_base::fcl(), Nom::getString(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Process::mp_sum_as_double(), Matrice_Morse::nb_colonnes(), Op_Diff_PolyMAC_Gen_base::nu_constant_, Op_Diff_PolyMAC_P0_base::phif_c, Op_Diff_PolyMAC_P0_base::phif_d, Op_Diff_PolyMAC_P0_base::phif_e, Op_Diff_PolyMAC_P0_base::update_phif(), and Champ_Inc_base::valeurs().
ajouter_blocs()
void Op_Diff_PolyMAC_P0_Face::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = { }) const override virtual
Adds blocks to the matrices for the PolyMAC P0 face diffusion operator.
This method adds the diffusion contributions to the matrix and the secondary memory. It handles both internal and boundary faces, and updates the matrix and secondary memory based on the diffusion coefficients and the stencil computed in the dimensioning step.
Parameters
matrices A map of matrices where the matrix for the unknown field will be stored.
secmem Secondary memory array to store additional contributions.
semi_impl A map indicating semi-implicit fields.
Reimplemented from Operateur_base.
References Objet_U::dimension, MorEqn::equation(), Champ_Face_base::fcl(), Nom::getString(), Equation_base::inconnue(), Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Op_Diff_PolyMAC_P0_base::phif_c, Op_Diff_PolyMAC_P0_base::phif_d, Op_Diff_PolyMAC_P0_base::phif_e, porosite_e, porosite_f, Op_Diff_PolyMAC_P0_base::update_phif(), and Champ_Inc_base::valeurs().
check_multiphase_compatibility()
void Op_Diff_PolyMAC_P0_Face::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.
Member Data Documentation
porosite_e
DoubleVect Op_Diff_PolyMAC_P0_Face::porosite_e protected
Referenced by ajouter_blocs(), and completer().
porosite_f
DoubleVect Op_Diff_PolyMAC_P0_Face::porosite_f protected
Referenced by ajouter_blocs(), and completer().