CEA TRUST Platform: Masse_VEF_P1NC Class Reference
Masse_VEF_P1NC Class Reference
#include <Masse_VEF_P1NC.h>
Additional Inherited Members
Public Member Functions inherited from Solveur_Masse_base
virtual DoubleTab & appliquer (DoubleTab &) const
virtual void assembler ()
virtual void mettre_a_jour (double temps)
virtual void resetTime (double temps)
void set_name_of_coefficient_temporel (const Nom &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_domaine_dis_base()
void Masse_VEF_P1NC::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis_base) override virtual
Implements Solveur_Masse_base.
associer_domaine_cl_dis_base()
void Masse_VEF_P1NC::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis_base) override virtual
Implements Solveur_Masse_base.
appliquer_impl()
DoubleTab & Masse_VEF_P1NC::appliquer_impl (DoubleTab & sm) const override virtual
Implements Solveur_Masse_base.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), MorEqn::equation(), Process::exit(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Equation_base::inconnue(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Equation_base::milieu(), Field_base::nature_du_champ(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Milieu_base::porosite_face(), Domaine_VF::premiere_face_int(), Domaine_VEF::premiere_face_std(), Domaine_VF::volumes_entrelaces(), and Domaine_Cl_VEF::volumes_entrelaces_Cl().
ajouter_masse() [1/2]
Matrice_Base & Masse_VEF_P1NC::ajouter_masse (double dt, Matrice_Base & matrice, int penalisation = 1) const override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_base::ajouter_masse(), MorEqn::equation(), Field_base::fixer_nature_du_champ(), and Equation_base::inconnue().
ajouter_masse() [2/2]
DoubleTab & Masse_VEF_P1NC::ajouter_masse (double dt, DoubleTab & x, const DoubleTab & y, int penalisation = 1) const override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_base::ajouter_masse(), MorEqn::equation(), Field_base::fixer_nature_du_champ(), and Equation_base::inconnue().
corriger_solution()
DoubleTab & Masse_VEF_P1NC::corriger_solution (DoubleTab & x, const DoubleTab & y, int incr = 0) const override virtual
Reimplemented from Solveur_Masse_base.
References Solveur_Masse_base::corriger_solution().