CEA TRUST Platform: Iterateur_Source_base Class Reference
Iterateur_Source_base Class Reference abstract
#include <Iterateur_Source_base.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
ajouter()
virtual DoubleTab & Iterateur_Source_base::ajouter (DoubleTab &) const pure virtual
Implemented in Iterateur_Source_EF_Som< _TYPE_ >, Iterateur_Source_Elem< _TYPE_ >, Iterateur_Source_Face< _TYPE_ >, and Iterateur_Source_VEF_Face< _TYPE_ >.
Referenced by calculer().
evaluateur()
virtual Evaluateur_Source & Iterateur_Source_base::evaluateur () pure virtual
Implemented in Iterateur_Source_EF_Som< _TYPE_ >, Iterateur_Source_Elem< _TYPE_ >, Iterateur_Source_Face< _TYPE_ >, and Iterateur_Source_VEF_Face< _TYPE_ >.
completer_()
virtual void Iterateur_Source_base::completer_ () pure virtual
Implemented in Iterateur_Source_EF_Som< _TYPE_ >, Iterateur_Source_Elem< _TYPE_ >, Iterateur_Source_Face< _TYPE_ >, and Iterateur_Source_VEF_Face< _TYPE_ >.
calculer()
virtual DoubleTab & Iterateur_Source_base::calculer (DoubleTab & resu) const inline virtual
References ajouter().
initialiser()
virtual int Iterateur_Source_base::initialiser (double) inline virtual
Reimplemented in Iterateur_Source_VEF_Face< _TYPE_ >.
References Process::exit().
associer()
void Iterateur_Source_base::associer (const Source_base & source) inline
equation_divisee_par_rho()
int Iterateur_Source_base::equation_divisee_par_rho () const inline
References Nom::debute_par(), and Objet_U::que_suis_je().
associer_domaines()
void Iterateur_Source_base::associer_domaines (const Domaine_dis_base & domaine, const Domaine_Cl_dis_base & domaine_cl) inline
impr()
virtual int Iterateur_Source_base::impr (Sortie &) const inline virtual
Reimplemented in Iterateur_Source_EF_Som< _TYPE_ >.
References Process::exit().
OBS_PTR() [1/3]
Iterateur_Source_base::OBS_PTR (Domaine_Cl_dis_base) protected
OBS_PTR() [2/3]
Iterateur_Source_base::OBS_PTR (Domaine_dis_base) protected
OBS_PTR() [3/3]
Iterateur_Source_base::OBS_PTR (Source_base) protected