CEA TRUST Platform: Echange_contact_PolyMAC Class Reference
Echange_contact_PolyMAC Class Reference
#include <Echange_contact_PolyMAC.h>
Public Member Functions
int initialiser (double temps) override
void mettre_a_jour (double) override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
void mettre_a_jour (double) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
void set_modifier_val_imp (int)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
completer()
void Echange_contact_PolyMAC::completer () override virtual
NE FAIT RIEN A surcharger dans les classes derivees.
Reimplemented from Cond_lim_base.
References Champ_front_base::associer_fr_dis_base(), Champ_front_base::completer(), Cond_lim_base::completer(), Cond_lim_base::frontiere_dis(), T_autre_pb(), and Echange_impose_base::T_ext().
initialiser()
int Echange_contact_PolyMAC::initialiser (double temps) override virtual
Initialisation en debut de calcul.
A appeler avant tout calculer_coeffs_echange ou mettre_a_jour Contrairementaux methodes mettre_a_jour, les methodes initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(0 en cas d'erreur, 1 sinon.)
Reimplemented from Cond_lim_base.
References MD_Vector_tools::creer_tableau_distribue(), Frontiere_32_64< _SIZE_ >::creer_tableau_faces(), Domaine_VF::creer_tableau_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Equation_base::domaine_application(), Cond_lim_base::domaine_Cl_dis(), Champ_front_calc::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Champ_front_calc::equation(), Domaine_VF::face_voisins(), Champ_front_calc::front_dis(), Frontiere_dis_base::frontiere(), Cond_lim_base::frontiere_dis(), Domaine_PolyMAC::init_m2(), Domaine_PolyMAC::init_virt_ef_map(), Echange_impose_base::initialiser(), Champ_front_calc::initialiser(), item, Operateur::l_op_base(), Domaine_PolyMAC::m2d, Domaine_Poly_base::mdv_elems_faces, Process::me(), monolithic, Process::mp_max(), Field_base::nb_comp(), Domaine_dis_base::nb_elem_tot(), Front_VF::nb_faces(), Equation_base::operateur(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), stab_, T_autre_pb(), Domaine_PolyMAC::virt_ef_map, Domaine_PolyMAC::w2i, and Domaine_PolyMAC::w2j.
calculer_correspondance()
void Echange_contact_PolyMAC::calculer_correspondance ()
update_coeffs()
void Echange_contact_PolyMAC::update_coeffs ()
References coeff, coeffs_a_jour_, Op_Diff_PolyMAC_Elem::delta_f_int, delta_int, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_front_calc::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Champ_front_calc::equation(), Domaine_VF::face_surfaces(), Domaine_VF::face_voisins(), Champ_front_calc::front_dis(), Frontiere_dis_base::frontiere(), h_paroi, Champ_front_calc::inconnue(), Domaine_PolyMAC::init_m2(), item, Operateur::l_op_base(), Domaine_PolyMAC::m2d, monolithic, Field_base::nb_comp(), Domaine_dis_base::nb_elem_tot(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_face(), Equation_base::operateur(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), stab_, T_autre_pb(), Echange_impose_base::T_ext(), Frontiere_32_64< _SIZE_ >::trace_face_distant(), Frontiere_32_64< _SIZE_ >::trace_face_local(), Op_Diff_PolyMAC_Elem::update_delta_int(), Champ_front_base::valeurs(), Champ_Inc_base::valeurs(), Domaine_VF::volumes(), Domaine_PolyMAC::w2c, Domaine_PolyMAC::w2i, and Domaine_PolyMAC::w2j.
update_delta()
void Echange_contact_PolyMAC::update_delta () const
References delta, delta_a_jour_, Op_Diff_PolyMAC_Elem::delta_e, Op_Diff_PolyMAC_Elem::delta_f, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Champ_front_calc::domaine_dis(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Champ_front_calc::equation(), Domaine_VF::face_voisins(), Champ_front_calc::front_dis(), Frontiere_dis_base::frontiere(), item, Operateur::l_op_base(), Domaine_PolyMAC::m2d, monolithic, Field_base::nb_comp(), Domaine_VF::nb_faces(), Front_VF::nb_faces(), Front_VF::num_face(), Equation_base::operateur(), Objet_U::que_suis_je(), T_autre_pb(), Frontiere_32_64< _SIZE_ >::trace_face_distant(), Frontiere_32_64< _SIZE_ >::trace_face_local(), Op_Diff_PolyMAC_Elem::update_delta(), Domaine_PolyMAC::w2i, and Domaine_PolyMAC::w2j.
mettre_a_jour()
void Echange_contact_PolyMAC::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps de la condition aux limites.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Cond_lim_base.
References coeffs_a_jour_, delta_a_jour_, Echange_impose_base::mettre_a_jour(), and stab_.
T_autre_pb() [1/2]
Champ_front_base & Echange_contact_PolyMAC::T_autre_pb () inline
Referenced by completer(), initialiser(), update_coeffs(), and update_delta().
T_autre_pb() [2/2]
const Champ_front_base & Echange_contact_PolyMAC::T_autre_pb () const inline
nom_autre_pb()
const Nom & Echange_contact_PolyMAC::nom_autre_pb () const inline
References nom_autre_pb_.
Referenced by Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), and Op_Diff_PolyMAC_Elem::dimensionner_termes_croises().
OWN_PTR()
Echange_contact_PolyMAC::OWN_PTR (Champ_front_base) protected
Member Data Documentation
item
IntTab Echange_contact_PolyMAC::item mutable
Referenced by Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), Op_Diff_PolyMAC_Elem::dimensionner_termes_croises(), initialiser(), update_coeffs(), and update_delta().
coeff
DoubleTab Echange_contact_PolyMAC::coeff mutable
Referenced by Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), and update_coeffs().
delta_int
DoubleTab Echange_contact_PolyMAC::delta_int
Referenced by update_coeffs().
delta
DoubleTab Echange_contact_PolyMAC::delta
Referenced by Op_Diff_PolyMAC_Elem::ajouter_termes_croises(), Op_Diff_PolyMAC_Elem::contribuer_a_avec(), Op_Diff_PolyMAC_Elem::contribuer_termes_croises(), and update_delta().
monolithic
int Echange_contact_PolyMAC::monolithic = 0
Referenced by initialiser(), update_coeffs(), and update_delta().
stab_
int Echange_contact_PolyMAC::stab_ = 0 protected
Referenced by initialiser(), mettre_a_jour(), and update_coeffs().
coeffs_a_jour_
int Echange_contact_PolyMAC::coeffs_a_jour_ = 0 mutable protected
Referenced by mettre_a_jour(), and update_coeffs().
delta_a_jour_
int Echange_contact_PolyMAC::delta_a_jour_ = 0 protected
Referenced by mettre_a_jour(), and update_delta().
h_paroi
double Echange_contact_PolyMAC::h_paroi = -123. protected
Referenced by update_coeffs().
nom_autre_pb_
Nom Echange_contact_PolyMAC::nom_autre_pb_ protected
Referenced by nom_autre_pb().