CEA TRUST Platform: Op_Diff_P1NC_barprim Class Reference
Op_Diff_P1NC_barprim Class Reference
#include <Op_Diff_P1NC_barprim.h>
Public Member Functions
double calculer_dt_stab () const override
void completer () override
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
void contribuer_au_second_membre (DoubleTab &) const override
void dimensionner (Matrice_Morse &) const override
void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Public Member Functions inherited from Op_VEF_Face
void dimensionner (const Domaine_VEF &, const Domaine_Cl_VEF &, Matrice_Morse &) const
void modifier_matrice_pour_periodique_apres_contribuer (Matrice_Morse &matrice, const Equation_base &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
calculer_dt_stab()
double Op_Diff_P1NC_barprim::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Domaine_VEF::carre_pas_du_maillage(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), and Objet_U::dimension.
associer()
void Op_Diff_P1NC_barprim::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_cl_dis, const Champ_Inc_base & ch_diffuse) override virtual
Implements Operateur_base.
References OBS_PTR().
associer_diffusivite()
void Op_Diff_P1NC_barprim::associer_diffusivite (const Champ_base & diffu) override virtual
Implements Operateur_Diff_base.
completer()
void Op_Diff_P1NC_barprim::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
References Operateur_base::completer().
diffusivite()
const Champ_base & Op_Diff_P1NC_barprim::diffusivite () const override virtual
Implements Operateur_Diff_base.
Referenced by calculer().
ajouter()
DoubleTab & Op_Diff_P1NC_barprim::ajouter (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References calculer().
calculer()
DoubleTab & Op_Diff_P1NC_barprim::calculer (const DoubleTab & inconnue, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References calculer_divergence(), diffusivite(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Champ_P1NC::filtrer_L2(), Champ_P1NC::filtrer_resu(), Op_VEF_Face::modifier_flux(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by ajouter().
dimensionner()
void Op_Diff_P1NC_barprim::dimensionner (Matrice_Morse & mat) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
modifier_pour_Cl()
void Op_Diff_P1NC_barprim::modifier_pour_Cl (Matrice_Morse & , DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(Matrice_Morse&) une matrice au format Morse
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
contribuer_a_avec()
void Op_Diff_P1NC_barprim::contribuer_a_avec (const DoubleTab & inco, Matrice_Morse & matrice) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
(Matrice_Morse&) une matrice au format Morse
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
contribuer_au_second_membre()
void Op_Diff_P1NC_barprim::contribuer_au_second_membre (DoubleTab &) const inline override virtual
DOES NOTHING - to override in derived classes.
Parameters
(DoubleTab&) un tableau de valeur (double)
Exceptions
methode a surcharger
Reimplemented from Operateur_base.
calculer_divergence()
void Op_Diff_P1NC_barprim::calculer_divergence (const DoubleTab & grad, const DoubleVect & nu, DoubleTab & resu) const protected
References Objet_U::dimension, Domaine_dis_base::domaine(), Domaine_VF::elem_faces(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
Referenced by calculer().
OBS_PTR() [1/3]
Op_Diff_P1NC_barprim::OBS_PTR (Domaine_VEF) protected
Referenced by associer().
OBS_PTR() [2/3]
Op_Diff_P1NC_barprim::OBS_PTR (Domaine_Cl_VEF) protected
OBS_PTR() [3/3]
Op_Diff_P1NC_barprim::OBS_PTR (Champ_Uniforme) protected