CEA TRUST Platform: Pb_Dilatable_base Class Reference
Pb_Dilatable_base Class Reference
#include <Pb_Dilatable_base.h>
Public Member Functions
void associer_milieu_base (const Milieu_base &) override
void associer_sch_tps_base (const Schema_Temps_base &) override
bool initTimeStep (double dt) override
bool iterateTimeStep (bool &converged) override
void mettre_a_jour (double temps) override
Public Member Functions inherited from Probleme_base
void abortTimeStep () override
int associer_ (Objet_U &) override
virtual void associer_domaine (const Domaine &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
double computeTimeStep (bool &stop) const override
const Discretisation_base & discretisation () const
virtual void discretiser (Discretisation_base &)
Domaine & domaine ()
const Domaine & domaine () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
Equation_base & equation (const Nom &)
const Equation_base & equation (const Nom &) const
virtual void finir ()
double futureTime () const override
void getInputFieldsNames (Noms &noms) const override
virtual void imprimer (Sortie &os) const
void initialize () override
bool initTimeStep (double dt) override
bool isStationary () const override
bool iterateTimeStep (bool &converged) override
int limpr () const override
int lsauv () const override
virtual Milieu_base & milieu ()
virtual const Milieu_base & milieu () const
int postraiter (int force=1) override
double presentTime () const override
int reprendre (Entree &) override
void resetTime (double time) override
int sauvegarder (Sortie &) const override
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
void terminate () override
bool updateGivenFields () override
void validateTimeStep () override
virtual int verifier ()
Public Member Functions inherited from Probleme_U
const Nom & le_nom () const override
void nommer (const Nom &name) override
virtual bool run ()
virtual bool runUntil (double time)
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
des problemes dilatables.
See also
Pb_Fluide_base
Member Function Documentation
initTimeStep()
bool Pb_Dilatable_base::initTimeStep (double dt) override virtual
This method allocates and initializes the unknown and given fields for the future time step.
The value of the interval is imposed through the parameter dt. In case of error, returns false.
Parameters
(double dt) the time interval to allocate
Returns
(bool) true=OK, false=error, not able to tackle this dt
Exceptions
WrongContext,WrongArgument
Reimplemented from Probleme_U.
References Probleme_base::initTimeStep().
preparer_calcul()
void Pb_Dilatable_base::preparer_calcul () override virtual
Prepare le calcul: initialise les parametres du milieu et prepare le calcul de chacune des equations.
Reimplemented from Probleme_base.
References Fluide_Dilatable_base::calculer_masse_volumique(), Fluide_Dilatable_base::completer(), Probleme_base::equation(), Equation_base::inconnue(), Probleme_base::milieu(), Field_base::nommer(), Probleme_base::preparer_calcul(), Fluide_Dilatable_base::preparer_calcul(), and Fluide_Dilatable_base::type_fluide().
mettre_a_jour()
void Pb_Dilatable_base::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du probleme.
Effectue la mise a jour sur toutes les equations du probleme.
Parameters
(double temps) le pas de temps de mise a jour
Reimplemented from Probleme_base.
References Probleme_base::domaine(), Probleme_base::domaine_dis(), Probleme_base::equation(), Probleme_U::le_nom(), Probleme_base::les_postraitements_, Equation_base::mettre_a_jour(), Loi_Fermeture_base::mettre_a_jour(), Postraitements::mettre_a_jour(), Probleme_base::nombre_d_equations(), and Debog::set_nom_pb_actuel().
associer_milieu_base()
void Pb_Dilatable_base::associer_milieu_base (const Milieu_base & mil) override virtual
Associe un milieu physique aux equations du probleme.
Choix du milieu physique.
Parameters
(Milieu_base& mil) le milieu a associer (Solide, Fluide Incompressible ...)
Reimplemented from Probleme_base.
Reimplemented in Pb_QC_base, Pb_WC_base, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_QC >, TRUSTProblem_sup_eqns< Pb_Thermohydraulique_Turbulent_QC >, and TRUSTProblem_sup_eqns< Pb_Thermohydraulique_WC >.
References Probleme_base::associer_milieu_base().
Referenced by Pb_QC_base::associer_milieu_base(), and Pb_WC_base::associer_milieu_base().
associer_sch_tps_base()
void Pb_Dilatable_base::associer_sch_tps_base (const Schema_Temps_base & un_schema_en_temps) override virtual
Associe un schema en temps au probleme.
Associe ensuite le schema en temps a toutes les equations du probleme.
Parameters
(Schema_Temps_base& un_schema_en_temps) le schema en temps a associer
Reimplemented from Probleme_base.
References Probleme_base::associer_sch_tps_base(), Process::exit(), Probleme_base::is_coupled(), and Objet_U::que_suis_je().
update_pressure_fields()
void Pb_Dilatable_base::update_pressure_fields (double t) virtual
Referenced by iterateTimeStep().
iterateTimeStep()
bool Pb_Dilatable_base::iterateTimeStep (bool & converged) override virtual
In the case solveTimeStep uses an iterative process, this method executes a single iteration.
It is thus possible to modify the given fields between iterations. converged is set to true if the process has converged, ie if the unknown fields are solution to the problem on the next time step. Otherwise converged is set to false. The return value indicates if the convergence process behaves normally. If false, the Problem wishes to abort the time step resolution.
Parameters
(bool& converged) It is a return value : true if the process has converged, false otherwise.
Returns
(bool) true=OK, false=unable to converge
Exceptions
WrongContext
Reimplemented from Probleme_U.
References Statistiques::begin_count(), Domaine_Cl_dis_base::calculer_coeffs_echange(), Equation_base::domaine_Cl_dis(), Statistiques::end_count(), Probleme_base::equation(), Schema_Temps_base::faire_un_pas_de_temps_eqn_base(), Equation_base::inconnue(), Probleme_U::le_nom(), Milieu_base::mettre_a_jour(), Champ_Inc_base::mettre_a_jour(), Equation_base::milieu(), Probleme_base::nombre_d_equations(), Schema_Temps_base::pas_de_temps(), Champ_Inc_base::reculer(), Probleme_base::schema_temps(), Debog::set_nom_pb_actuel(), Schema_Temps_base::temps_courant(), Schema_Temps_base::temps_defaut(), and update_pressure_fields().
OBS_PTR()
Pb_Dilatable_base::OBS_PTR (Fluide_Dilatable_base) protected