CEA TRUST Platform: Operateurs_Statistique_tps Class Reference
Operateurs_Statistique_tps Class Reference
Detailed Description
Les objets Postraitement portent un objet de ce type.
See also
Postraitement
Member Function Documentation
lserie()
int Operateurs_Statistique_tps::lserie () const inline
References lserie_.
dt_integr_serie()
double Operateurs_Statistique_tps::dt_integr_serie () const inline
References dt_integr_serie_.
sauvegarder()
int Operateurs_Statistique_tps::sauvegarder (Sortie & os) const override
reprendre()
int Operateurs_Statistique_tps::reprendre (Entree & is) override
References Process::exit(), Nom::getString(), TRUST_2_PDI::is_PDI_restart(), TRUSTTab< _TYPE_, _SIZE_ >::jump(), Nom::le_nom(), TRUST_2_PDI::read(), Objet_U::reprendre(), and TRUSTTab< _TYPE_, _SIZE_ >::reset().
OBS_PTR()
Operateurs_Statistique_tps::OBS_PTR (Postraitement) protected
Member Data Documentation
lserie_
int Operateurs_Statistique_tps::lserie_ = -123 protected
Referenced by lserie().
dt_integr_serie_
double Operateurs_Statistique_tps::dt_integr_serie_ = 123. protected
Referenced by dt_integr_serie().