CEA TRUST Platform: EDO_Pression_th_VEF_Gaz_Reel Class Reference
EDO_Pression_th_VEF_Gaz_Reel Class Reference
#include <EDO_Pression_th_VEF_Gaz_Reel.h>
Public Member Functions
double resoudre (double) override
Detailed Description
de calcul pour les fluides faiblement compressibles, et relatif a
discretisation de type VEF et pour les gaz reels.
See also
Fluide_Quasi_Compressible EDO_Pression_th_base
Member Function Documentation
resoudre() [1/2]
double EDO_Pression_th_VEF_Gaz_Reel::resoudre (double Pth_n) override
Resoud l'EDO.
Parameters
(double Pth_n) La pression a l'etape precedente
Returns
(double) La nouvelle valeur de la pression
References EDO_Pression_th_VEF::calculer_grad(), MorEqn::equation(), and Navier_Stokes_std::vitesse().
resoudre() [2/2]
void EDO_Pression_th_VEF_Gaz_Reel::resoudre (DoubleTab &) inline override
References Process::exit().