CEA TRUST Platform: Convection_Diffusion_Espece_Fluide_Dilatable_base Class Reference
Convection_Diffusion_Espece_Fluide_Dilatable_base Class Reference abstract
Public Member Functions
std::vector< YAML_data > data_a_sauvegarder () const override
DoubleTab & derivee_en_temps_inco (DoubleTab &) override=0
void discretiser () override
const Motcle & domaine_application () const override
int preparer_calcul () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_base
int impr (Sortie &os) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
virtual void completer ()
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
Probleme_base & probleme ()
const Probleme_base & probleme () const
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Detailed Description
quand le scalaire subissant le transport est la fraction massique
See also
Conv_Diffusion_std Convection_Diffusion_Chaleur_Fluide_Dilatable_base
Member Function Documentation
discretiser()
void Convection_Diffusion_Espece_Fluide_Dilatable_base::discretiser () override virtual
Discretise l'equation.
Type le domaine_Cl_dis, la formatte, l'associe a l'equation. Type le solveur masse, lui associe le domaine discretisee et le domaine des conditions aux limites discretisees.
Reimplemented from Equation_base.
References Equation_base::discretisation(), Equation_base::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Schema_Temps_base::nb_valeurs_temporelles(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
calculer_div_u_ou_div_rhou()
void Convection_Diffusion_Espece_Fluide_Dilatable_base::calculer_div_u_ou_div_rhou (DoubleTab & res) const override virtual
Implements Convection_Diffusion_Fluide_Dilatable_base.
References Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl().
data_a_sauvegarder()
std::vector< YAML_data > Convection_Diffusion_Espece_Fluide_Dilatable_base::data_a_sauvegarder () const override virtual
for PDI IO: retrieve name, type and dimensions of the data to save/restore. This has to be overrode for all the equations that either:
have extra fields (ie in addition to the unknown) or extra scalars to save/restore.
want to save the unknown but with a different name These data will then be written in a YAML file, to initialize PDI. They have to be shared with PDI afterwards, when they need to be read/written (via TRUST_2_PDI)
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_WC.
References Equation_base::data_a_sauvegarder().
sauvegarder()
int Convection_Diffusion_Espece_Fluide_Dilatable_base::sauvegarder (Sortie & os) const override virtual
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) le code de retour de Champ_Inc::sauvegarder()
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_WC.
References Equation_base::sauvegarder().
reprendre()
int Convection_Diffusion_Espece_Fluide_Dilatable_base::reprendre (Entree & fich) override virtual
On reprend l'inconnue a partir d'un flot d'entree.
[ON CHERCHE L'INCONNUE PAR SON NOM] [ON LIT L'INCONNUE] Voir Champ_Inc::reprendre(Entree&)
Parameters
(Entree& fich) le flot d'entree (fichier) a lire
Returns
(int) renvoie toujours 1
Exceptions
erreur de reprise, fin de fichier atteinte sans trouver l'inconnue
Reimplemented from Equation_base.
Reimplemented in Convection_Diffusion_Espece_Binaire_WC.
References Equation_base::reprendre().
preparer_calcul()
int Convection_Diffusion_Espece_Fluide_Dilatable_base::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Equation_base.
References Equation_base::domaine_Cl_dis(), and Equation_base::preparer_calcul().
Referenced by Convection_Diffusion_Espece_Binaire_base::preparer_calcul().
domaine_application()
const Motcle & Convection_Diffusion_Espece_Fluide_Dilatable_base::domaine_application () const override virtual
Renvoie le nom du domaine d'application de l'equation.
Ici "Thermique".
Returns
(Motcle&) le nom du domaine d'application de l'equation
Reimplemented from Equation_base.
assembler()
void Convection_Diffusion_Espece_Fluide_Dilatable_base::assembler (Matrice_Morse & mat_morse, const DoubleTab & present, DoubleTab & secmem) override pure virtual
Reimplemented from Equation_base.
Implemented in Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Binaire_base.
diffusivite_pour_pas_de_temps()
const Champ_base& Convection_Diffusion_Espece_Fluide_Dilatable_base::diffusivite_pour_pas_de_temps () const override pure virtual
Reimplemented from Convection_Diffusion_std.
Implemented in Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Binaire_base.
Referenced by Convection_Diffusion_Espece_Multi_base::lire_motcle_non_standard().
derivee_en_temps_inco()
DoubleTab& Convection_Diffusion_Espece_Fluide_Dilatable_base::derivee_en_temps_inco (DoubleTab & derivee) override pure virtual
Returns the time derivative of the unknown I of the equation: dI/dt = M-1*(sum(operators(I) + sources))
In : derivee contains I (but immediatly set to 0) Out: derivee contains dI/dt
Reimplemented from Equation_base.
Implemented in Convection_Diffusion_Espece_Multi_WC, Convection_Diffusion_Espece_Multi_QC, and Convection_Diffusion_Espece_Binaire_base.
is_thermal()
bool Convection_Diffusion_Espece_Fluide_Dilatable_base::is_thermal () const inline override virtual
Implements Convection_Diffusion_Fluide_Dilatable_base.
is_generic()
bool Convection_Diffusion_Espece_Fluide_Dilatable_base::is_generic () const inline override virtual
Implements Convection_Diffusion_Fluide_Dilatable_base.