CEA TRUST Platform: Dirichlet Class Reference
Dirichlet Class Reference
#include <Dirichlet.h>
Public Member Functions
virtual double val_imp (int i) const
virtual double val_imp (int i, int j) const
void verifie_ch_init_nb_comp () const override
Public Member Functions inherited from Cond_lim_base
virtual int a_mettre_a_jour_ss_pas_dt ()
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void associer_fr_dis_base (const Frontiere_dis_base &)
virtual void calculer_coeffs_echange (double temps)
virtual int compatible_avec_discr (const Discretisation_base &) const
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
void set_modifier_val_imp (int)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Implements Dirichlet boundary conditions for fields.
Une condition aux limites de type Dirichlet impose la valeur d'un champ inconnue sur une frontiere, ce qui correspond a:
vitesse imposee pour l'equation de Navier-Stokes
scalaire impose pour l'equation de transport d'un scalaire
See also
Cond_lim_base Dirichlet_homogene
This class defines the Dirichlet boundary condition, which imposes specific values on the field at the boundary. It provides methods to retrieve the imposed values at specified times and components of the field.
Member Function Documentation
val_imp() [1/3]
double Dirichlet::val_imp (int i) const virtual
Renvoie la valeur imposee sur la i-eme composante du champ a la frontiere au temps par defaut du champ_front.
Parameters
(int i) indice suivant la premiere dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Exceptions
deuxieme dimension du champ de frontiere superieur a 1
Reimplemented in Dirichlet_loi_paroi, Entree_fluide_temperature_imposee_H, Temperature_imposee_paroi_H, and Entree_fluide_T_h_imposee.
References val_imp_au_temps().
Referenced by Op_Grad_P0_to_Face::ajouter_blocs(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Champ_base::calculer_valeurs_som_compo_post(), Champ_base::calculer_valeurs_som_post(), Eval_Amont_PolyMAC_Elem::coeffs_face_bloc_vitesse(), Eval_Diff_VDF_Elem_Gen< DERIVED_T >::flux_face(), Eval_Amont_PolyMAC_Elem::flux_face(), Eval_centre_PolyMAC_Elem::flux_face(), Eval_Amont_PolyMAC_Elem::flux_face(), Eval_centre_PolyMAC_Elem::flux_face(), Domaine_Cl_VEF::imposer_cond_lim(), Op_EF_base::modifier_pour_Cl(), Op_VDF_Face::modifier_pour_Cl(), Op_VEF_Face::modifier_pour_Cl(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), EDO_Pression_th_VDF_Gaz_Parfait::resoudre(), Eval_Diff_VDF_Elem_Gen< DERIVED_T >::secmem_face(), Eval_Amont_PolyMAC_Elem::secmem_face(), Eval_centre_PolyMAC_Elem::secmem_face(), Eval_Amont_PolyMAC_Elem::secmem_face(), Eval_centre_PolyMAC_Elem::secmem_face(), and val_imp_au_temps().
val_imp() [2/3]
double Dirichlet::val_imp (int i, int j) const virtual
Renvoie la valeur imposee sur la (i,j)-eme composante du champ a la frontiere au temps par defaut du champ_front.
Parameters
(int i) indice suivant la premiere dimension du champ
(int j) indice suivant la deuxieme dimension du champ
Returns
(double) la valeur imposee sur la composante du champ specifiee
Reimplemented in Dirichlet_loi_paroi, Entree_fluide_temperature_imposee_H, Temperature_imposee_paroi_H, and Entree_fluide_T_h_imposee.
References val_imp_au_temps().
val_imp_au_temps() [1/3]
double Dirichlet::val_imp_au_temps (double temps, int i) const virtual
Renvoie la valeur imposee sur la i-eme composante du champ a la frontiere au temps precise.
Reimplemented in Dirichlet_loi_paroi, and Frontiere_ouverte_rho_u_impose.
References Process::exit(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by Domaine_Cl_EF::imposer_cond_lim(), Domaine_Cl_PolyMAC::imposer_cond_lim(), Domaine_Cl_VDF::imposer_cond_lim(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), EDO_Pression_th_VEF_Gaz_Parfait::resoudre(), val_imp(), val_imp(), and val_imp().
val_imp_au_temps() [2/3]
double Dirichlet::val_imp_au_temps (double temps, int i, int j) const virtual
Renvoie la valeur imposee sur la (i,j)-eme composante du champ a la frontiere au temps precise.
Reimplemented in Dirichlet_loi_paroi, and Frontiere_ouverte_rho_u_impose.
References TRUSTTab< _TYPE_, _SIZE_ >::dimension().
val_imp() [3/3]
const DoubleTab & Dirichlet::val_imp (double temps = DMAXFLOAT) const
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Cond_lim_base::frontiere_dis(), Front_VF::nb_faces_tot(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and val_imp_au_temps().
val_imp_au_temps() [3/3]
const DoubleTab & Dirichlet::val_imp_au_temps (double temps) const inline
References val_imp().
verifie_ch_init_nb_comp()
void Dirichlet::verifie_ch_init_nb_comp () const override virtual
Appel la verification du champ lu par l intermediaire de l equation pour laquelle on considere la condition limite.
La methode est surchargee dans les cas ou l utilisateur doit specifier le champ frontiere
Reimplemented from Cond_lim_base.
Reimplemented in Dirichlet_loi_paroi.
References Cond_lim_base::domaine_Cl_dis(), MorEqn::equation(), Equation_base::inconnue(), and Equation_base::verifie_ch_init_nb_comp_cl().