CEA TRUST Platform: Champ_Generique_Transformation Class Reference
Champ_Generique_Transformation Class Reference
#include <Champ_Generique_Transformation.h>
Public Member Functions
Entity get_localisation (const int index=-1) const override
const Noms get_property (const Motcle &query) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
Public Member Functions inherited from Champ_Generique_base
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Champ destine a post-traiter une "transformation" dependant de champs generiques et (ou) de x,y,z et t La classe porte un : -vecteur de Parseur (fxyz) -la (les) expression(s) pour exprimer la transformation (les_fct) -la methode de transformation choisie (methode_)
Member Function Documentation
set_param()
void Champ_Generique_Transformation::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Param::ajouter(), Param::ajouter_non_std(), localisation_, methode_, Param::REQUIRED, Champ_Gen_de_Champs_Gen::set_param(), and unite_.
lire_motcle_non_standard()
int Champ_Generique_Transformation::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Champ_Gen_de_Champs_Gen.
References Process::exit(), les_fct, Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), methode_, nature_ch, and nb_comp_.
verifier_coherence_donnees()
void Champ_Generique_Transformation::verifier_coherence_donnees ()
References Process::exit(), les_fct, methode_, nb_comp_, Objet_U::que_suis_je(), and Motcles::search().
verifier_localisation()
void Champ_Generique_Transformation::verifier_localisation ()
References Process::exit(), localisation_, Objet_U::que_suis_je(), and Motcles::search().
Referenced by completer().
get_property()
const Noms Champ_Generique_Transformation::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Gen_de_Champs_Gen::get_property(), nb_comp_, Champ_Generique_base::nom_post_, Motcles::search(), and unite_.
get_champ()
const Champ_base & Champ_Generique_Transformation::get_champ (OWN_PTR(Champ_base)& espace_stockage) const override
References Domaine_32_64< _SIZE_ >::calculer_centres_gravite(), Domaine_32_64< _SIZE_ >::coord_sommets(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Domaine_dis_base::domaine(), Parser_U::eval(), Champ_base::eval_elem(), Process::exit(), Domaine_VF::face_normales(), Domaine_VF::face_surfaces(), Champ_Generique_base::get_champ(), Champ_Generique_base::get_directive_pour_discr(), get_directive_pour_discr(), Champ_Gen_de_Champs_Gen::get_discretisation(), Domaine_VF::get_ind_integ_points(), Domaine_VF::get_nb_integ_points(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Domaine_VF::get_position(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_ref_domain(), Champ_Gen_de_Champs_Gen::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Gen_de_Champs_Gen::get_time(), Process::Kokkos_exit(), les_fct, TRUSTVect< _TYPE_, _SIZE_ >::line_size(), localisation_, methode_, nature_ch, Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), nb_comp_, Domaine_32_64< _SIZE_ >::nb_elem(), Domaine_dis_base::nb_elem_tot(), Domaine_32_64< _SIZE_ >::nb_som_tot(), Objet_U::que_suis_je(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Parser_U::setVar(), Champ_base::valeur_aux(), Champ_base::valeur_aux_centres_de_gravite(), Champ_base::valeur_aux_faces(), Champ_Proto::valeurs(), Domaine_VF::xp(), and Domaine_VF::xv().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Transformation::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const override virtual
Implements Champ_Generique_base.
References Champ_Gen_de_Champs_Gen::get_source(), Champ_Gen_de_Champs_Gen::get_time(), nature_ch, and nb_comp_.
get_localisation()
Entity Champ_Generique_Transformation::get_localisation (const int index = -1) const override virtual
Renvoie le type des entites geometriques sur auxquelles les valeurs discretes sont attachees (NODE pour un champ P1, FACE pour un champ P1NC, ELEMENT pour un.
champ P0, etc). Il est conseille d'utiliser la syntaxe get_localisation() sans parametre, sauf si on sait quoi faire pour les champs multi-supports.
See also
get_nb_localisations() Parametre : index Signification : index de la localisation demandee (pour les champs multi-support). Si index = -1 : si le champ est multi-support on leve une exception, sinon on renvoie le support. Si index >= 0 : on renvoie le i-ieme support. Valeur par defaut : -1 Exceptions:
GenericFieldError::INVALID : le champ n'est pas discretise sur ces entites geometriques (il peut s'agir d'un champ analytique ou d'un champ multi-localisation), ou le champ est multi-support alors qu'on a demande index = -1, ou le support "index" n'existe pas.
Reimplemented from Champ_Gen_de_Champs_Gen.
References localisation_, and Champ_Generique_base::nom_post_.
get_directive_pour_discr()
const Motcle Champ_Generique_Transformation::get_directive_pour_discr () const override virtual
Renvoie la directive (champ_elem, champ_sommets, champ_face ou pression) pour lancer la discretisation de l espace de stockage rendu par get_champ()
Reimplemented from Champ_Gen_de_Champs_Gen.
References Process::exit(), Champ_Gen_de_Champs_Gen::get_ref_domaine_dis_base(), localisation_, and Objet_U::que_suis_je().
Referenced by get_champ().
completer()
void Champ_Generique_Transformation::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_base::a_un_domaine_dis_base(), Process::abort(), Champ_Gen_de_Champs_Gen::completer(), Domaine_dis_base::domaine(), Champ_base::domaine_dis_base(), Probleme_base::equation(), Process::exit(), Domaine_VF::face_sommets(), Champ_Generique_base::get_champ_without_evaluation(), Champ_Generique_base::get_directive_pour_discr(), Champ_Gen_de_Champs_Gen::get_discretisation(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Equation_base::inconnue(), Objet_U::interprete(), Process::Journal(), Field_base::le_nom(), Probleme_U::le_nom(), Domaine_32_64< _SIZE_ >::les_elems(), les_fct, Domaine_32_64< _SIZE_ >::les_sommets(), localisation_, methode_, nature_ch, Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), nb_comp_, Champ_Generique_base::nom_post_, Interprete::objet(), preparer_macro(), Objet_U::que_suis_je(), MD_Vector::valeur(), Champ_Proto::valeurs(), verifier_localisation(), and Domaine_VF::xa().
nommer_source()
void Champ_Generique_Transformation::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References les_fct, Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
preparer_macro()
int Champ_Generique_Transformation::preparer_macro ()
References creer_expression_macro(), Process::exit(), Champ_Generique_base::get_champ(), Champ_Generique_base::get_champ_without_evaluation(), Champ_Gen_de_Champs_Gen::get_discretisation(), Champ_Gen_de_Champs_Gen::get_nb_sources(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Process::Journal(), les_fct, localisation_, methode_, nature_ch, Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), nb_comp_, and Champ_Generique_base::nom_post_.
Referenced by completer().
creer_expression_macro()
void Champ_Generique_Transformation::creer_expression_macro ()
References Objet_U::dimension, Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), les_fct, and methode_.
Referenced by preparer_macro().
VECT()
Champ_Generique_Transformation::VECT (Parser_U) mutable protected
Member Data Documentation
methode_
Nom Champ_Generique_Transformation::methode_ protected
Referenced by completer(), creer_expression_macro(), get_champ(), lire_motcle_non_standard(), preparer_macro(), set_param(), and verifier_coherence_donnees().
les_fct
Noms Champ_Generique_Transformation::les_fct protected
Referenced by completer(), creer_expression_macro(), get_champ(), lire_motcle_non_standard(), nommer_source(), preparer_macro(), and verifier_coherence_donnees().
nb_comp_
int Champ_Generique_Transformation::nb_comp_ = 1 protected
Referenced by completer(), get_champ(), get_champ_without_evaluation(), get_property(), lire_motcle_non_standard(), preparer_macro(), and verifier_coherence_donnees().
localisation_
Motcle Champ_Generique_Transformation::localisation_ protected
Referenced by completer(), get_champ(), get_directive_pour_discr(), get_localisation(), preparer_macro(), set_param(), and verifier_localisation().
unite_
Nom Champ_Generique_Transformation::unite_ protected
Referenced by get_property(), and set_param().
nature_ch
Nature_du_champ Champ_Generique_Transformation::nature_ch = scalaire protected
Referenced by completer(), get_champ(), get_champ_without_evaluation(), lire_motcle_non_standard(), and preparer_macro().