CEA TRUST Platform: DecoupeBord_32_64< _SIZE_ > Class Template Reference
DecoupeBord_32_64< _SIZE_ > Class Template Reference
Additional Inherited Members
Public Member Functions inherited from Interprete_geometrique_base_32_64< _SIZE_ >
void mettre_a_jour_sous_domaine (Domaine_t &domaine, int_t &elem, int_t num_premier_elem, int_t nb_elem) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Interprete
static Objet_U & objet (const Nom &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class DecoupeBord_32_64< _SIZE_ >
Le maillage obtenu n'a pas de directions preferentielles
See also
Interprete
Member Typedef Documentation
int_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
IntVect_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
DoubleTab_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::DoubleTab_t = DoubleTab_T<_SIZE_>
ArrsOfInt_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::ArrsOfInt_t = ArrsOfInt_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Faces_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::Faces_t = Faces_32_64<_SIZE_>
Bord_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::Bord_t = Bord_32_64<_SIZE_>
Bords_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::Bords_t = Bords_32_64<_SIZE_>
Frontiere_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::Frontiere_t = Frontiere_32_64<_SIZE_>
Raccord_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::Raccord_t = OWN_PTR(Raccord_base_32_64<_SIZE_>)
Raccords_t
template<typename _SIZE_ > using DecoupeBord_32_64< _SIZE_ >::Raccords_t = Raccords_32_64<_SIZE_>
Member Function Documentation
interpreter_()
template<typename _SIZE_ > Entree & DecoupeBord_32_64< _SIZE_ >::interpreter_ (Entree & is) override virtual
Implements Interprete_geometrique_base_32_64< _SIZE_ >.
References Param::ajouter(), Process::exit(), Domaine_base::le_nom(), Param::lire_avec_accolades_depuis(), Sortie_Fichier_base::ouvrir(), Param::REQUIRED, Sortie::set_bin(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
decouper()
template<typename _SIZE_ > void DecoupeBord_32_64< _SIZE_ >::decouper (Domaine_t & dom, const Nom & nom_file)
References Domaine_32_64< _SIZE_ >::bord(), Sortie_Fichier_base::close(), Domaine_32_64< _SIZE_ >::coord_sommets(), Faces_32_64< _SIZE_ >::dimensionner(), Process::exit(), Frontiere_32_64< _SIZE_ >::faces(), Domaine_32_64< _SIZE_ >::faces_bord(), Domaine_32_64< _SIZE_ >::faces_raccord(), Domaine_32_64< _SIZE_ >::frontiere(), Entree_Fichier_base::good(), Domaine_base::le_nom(), Frontiere_32_64< _SIZE_ >::le_nom(), Objet_U::le_type(), Faces_32_64< _SIZE_ >::les_sommets(), Domaine_32_64< _SIZE_ >::nb_bords(), Domaine_32_64< _SIZE_ >::nb_faces_bord(), Domaine_32_64< _SIZE_ >::nb_faces_raccord(), Domaine_32_64< _SIZE_ >::nb_front_Cl(), Faces_32_64< _SIZE_ >::nb_som_faces(), Frontiere_32_64< _SIZE_ >::nommer(), Sortie_Fichier_base::precision(), Nom::prefix(), Domaine_32_64< _SIZE_ >::raccord(), Sortie_Fichier_base::setf(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Faces_32_64< _SIZE_ >::type_face(), and Faces_32_64< _SIZE_ >::typer().