CEA TRUST Platform: Save_Restart Class Reference
Save_Restart Class Reference
Public Member Functions
int allocate_file_size (long int &size) const
Member Function Documentation
assoscier_pb_base()
void Save_Restart::assoscier_pb_base (const Probleme_base & pb)
Referenced by Probleme_base::associer().
allocation()
void Save_Restart::allocation () const
References EcritureLectureSpecial::Active, allocate_file_size(), Process::barrier(), Process::exit(), Process::je_suis_maitre(), Process::nproc(), and sauver_xyz().
Referenced by Probleme_base::allocation().
allocate_file_size()
int Save_Restart::allocate_file_size (long int & size) const
Verifie que la place necessaire existe sur le disque dur.
Parameters
l'espace disque requis
Returns
(int) retourne 1 si l'espace disque est suffisant, 0 sinon
References Objet_U::nom_du_cas().
Referenced by allocation().
reprise_format_temps()
const char * Save_Restart::reprise_format_temps () const inline
Referenced by Probleme_base::reprise_format_temps().
reprise_effectuee() [1/2]
bool& Save_Restart::reprise_effectuee () inline
Referenced by lire_sauvegarde_reprise(), and Probleme_base::reprise_effectuee().
reprise_effectuee() [2/2]
bool Save_Restart::reprise_effectuee () const inline
preparer_calcul()
void Save_Restart::preparer_calcul ()
References EcritureLectureSpecial::Active, Process::je_suis_maitre(), and sauver_xyz().
Referenced by Probleme_base::preparer_calcul().
sauver_xyz()
void Save_Restart::sauver_xyz (int verbose) const
References Perf_counters::begin_count().
Referenced by allocation(), finir(), and preparer_calcul().
is_restart_in_progress()
bool Save_Restart::is_restart_in_progress () const inline
set_restart_in_progress()
void Save_Restart::set_restart_in_progress (const bool res) inline
is_sauvegarde_simple()
int Save_Restart::is_sauvegarde_simple () const inline
Referenced by Probleme_base::is_sauvegarde_simple().
checkpoint_filename()
const Nom& Save_Restart::checkpoint_filename () const inline
Referenced by Probleme_base::checkpoint_filename().
restart_filename()
const Nom& Save_Restart::restart_filename () const inline
Referenced by Probleme_base::restart_filename().
checkpoint_format()
const Nom& Save_Restart::checkpoint_format () const inline
Referenced by Probleme_base::checkpoint_format().
yaml_filename()
const Nom& Save_Restart::yaml_filename () const inline
Referenced by Probleme_base::yaml_filename().
lire_sauvegarde_reprise()
void Save_Restart::lire_sauvegarde_reprise (Entree & is, Motcle & motlu)
References EcritureLectureSpecial::Active, Process::exit(), Process::force_single_file(), Nom::le_nom(), Objet_U::nom_du_cas(), Process::nproc(), and reprise_effectuee().
sauver()
int Save_Restart::sauver () const
Ecriture sur fichier en vue d'une reprise (sauvegarde)
References Ecrire_YAML::add_pb_base(), FichierHDF::close(), FichierHDF::create(), FichierHDF::create_and_fill_dataset_MW(), Process::exit(), PE_Groups::get_node_group(), Comm_Group::get_number_of_nodes(), EcritureLectureSpecial::get_Output(), Nom::getString(), TRUST_2_PDI::init(), TRUST_2_PDI::is_PDI_initialized(), Process::je_suis_maitre(), EcritureLectureSpecial::mode_ecr, Process::node_master(), Process::nproc(), TRUST_2_PDI::set_PDI_checkpoint(), TRUST_2_PDI::stop_sharing(), TRUST_2_PDI::stop_sharing_last_variable(), TRUST_2_PDI::trigger(), TRUST_2_PDI::TRUST_start_sharing(), TRUST_2_PDI::write(), and Ecrire_YAML::write_checkpoint_file().
finir()
void Save_Restart::finir ()
References EcritureLectureSpecial::Active, FichierHDF::close(), FichierHDF::create(), FichierHDF::create_and_fill_dataset_MW(), TRUST_2_PDI::finalize(), TRUST_2_PDI::is_PDI_initialized(), Process::je_suis_maitre(), and sauver_xyz().
Referenced by Probleme_base::finir().