CEA TRUST Platform: Matrice_Diagonale Class Reference
Matrice_Diagonale Class Reference
#include <Matrice_Diagonale.h>
Additional Inherited Members
Public Member Functions inherited from Matrice_Base
virtual DoubleTab & ajouter_multTab (const DoubleTab &, DoubleTab &r) const
virtual DoubleVect & ajouter_multvect (const DoubleVect &x, DoubleVect &r) const
virtual DoubleVect & ajouter_multvectT (const DoubleVect &x, DoubleVect &r) const
virtual DoubleTab & multTab (const DoubleTab &, DoubleTab &r) const
virtual DoubleVect & multvect (const DoubleVect &, DoubleVect &) const
virtual DoubleVect & multvectT (const DoubleVect &, DoubleVect &) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Matrice_Base
Constructor & Destructor Documentation
Matrice_Diagonale() [1/3]
Matrice_Diagonale::Matrice_Diagonale ()
References Matrice_Base::is_stencil_up_to_date_.
Matrice_Diagonale() [2/3]
Matrice_Diagonale::Matrice_Diagonale (int size)
References Matrice_Base::is_stencil_up_to_date_.
Matrice_Diagonale() [3/3]
Matrice_Diagonale::Matrice_Diagonale (const DoubleVect & coefficients)
References Matrice_Base::is_stencil_up_to_date_.
Member Function Documentation
ordre()
int Matrice_Diagonale::ordre () const override virtual
If square matrix, returns number of lines, otherwise 0.
Implements Matrice_Base.
References coefficients_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by get_stencil(), and get_stencil_and_coefficients().
nb_lignes()
int Matrice_Diagonale::nb_lignes () const override virtual
Return local number of lines (=size on the current proc)
Implements Matrice_Base.
References coefficients_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
nb_colonnes()
int Matrice_Diagonale::nb_colonnes () const override virtual
Return local number of columns (=size on the current proc)
Implements Matrice_Base.
References coefficients_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
ajouter_multvect_()
DoubleVect & Matrice_Diagonale::ajouter_multvect_ (const DoubleVect & x, DoubleVect & r) const override virtual
Implements Matrice_Base.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), coefficients_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by ajouter_multTab_(), and ajouter_multvectT_().
ajouter_multvectT_()
DoubleVect & Matrice_Diagonale::ajouter_multvectT_ (const DoubleVect & x, DoubleVect & r) const override virtual
Implements Matrice_Base.
References ajouter_multvect_().
ajouter_multTab_()
DoubleTab & Matrice_Diagonale::ajouter_multTab_ (const DoubleTab & x, DoubleTab & r) const override virtual
Implements Matrice_Base.
References ajouter_multvect_(), coefficients_, TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::nb_dim(), and TRUSTVect< _TYPE_, _SIZE_ >::size().
scale()
void Matrice_Diagonale::scale (const double x) override virtual
Implements Matrice_Base.
References coefficients_.
clean()
void Matrice_Diagonale::clean () override virtual
Reimplemented from Matrice_Base.
References coefficients_.
get_stencil()
void Matrice_Diagonale::get_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
References Matrice_Base::is_stencil_up_to_date_, ordre(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and Matrice_Base::stencil_.
Referenced by get_symmetric_stencil().
get_symmetric_stencil()
void Matrice_Diagonale::get_symmetric_stencil (IntTab & stencil) const override virtual
Reimplemented from Matrice_Base.
References get_stencil().
get_stencil_and_coefficients()
void Matrice_Diagonale::get_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
References Process::abort(), coefficients_, Matrice_Base::is_stencil_up_to_date_, ordre(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize_array(), TRUSTVect< _TYPE_, _SIZE_ >::size(), and Matrice_Base::stencil_.
Referenced by get_symmetric_stencil_and_coefficients().
get_symmetric_stencil_and_coefficients()
void Matrice_Diagonale::get_symmetric_stencil_and_coefficients (IntTab & stencil, ArrOfDouble & coefficients) const override virtual
Reimplemented from Matrice_Base.
References get_stencil_and_coefficients().
get_coefficients() [1/2]
DoubleVect & Matrice_Diagonale::get_coefficients ()
References coefficients_.
get_coefficients() [2/2]
const DoubleVect & Matrice_Diagonale::get_coefficients () const
References coefficients_.
dimensionner()
void Matrice_Diagonale::dimensionner (int size)
References coefficients_, and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Referenced by Matrix_tools::allocate_from_stencil(), and Solveur_U_P::iterer_NS().
coeff() [1/2]
double Matrice_Diagonale::coeff (int i, int j) const
References coefficients_.
Referenced by Solveur_U_P::iterer_NS().
coeff() [2/2]
double & Matrice_Diagonale::coeff (int i, int j)
References coefficients_, and Process::exit().
Member Data Documentation
coefficients_
DoubleVect Matrice_Diagonale::coefficients_ protected
Referenced by ajouter_multTab_(), ajouter_multvect_(), clean(), coeff(), coeff(), dimensionner(), get_coefficients(), get_coefficients(), get_stencil_and_coefficients(), nb_colonnes(), nb_lignes(), ordre(), and scale().