CEA TRUST Platform: Traitement_particulier_NS_base Class Reference
Traitement_particulier_NS_base Class Reference abstract
#include <Traitement_particulier_NS_base.h>
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Detailed Description
pour le calcul de l'energie cinetique par exemple (front-tracking)
voir Traitement_particulier_NS_EC
See also
Navier_Stokes_Standard
Member Function Documentation
associer_eqn()
void Traitement_particulier_NS_base::associer_eqn (const Equation_base & eqn) virtual
Reimplemented in Traitement_particulier_NS_Pression, Traitement_particulier_NS_Profils_thermo_VDF, and Traitement_particulier_NS_VEF.
Referenced by Traitement_particulier_NS_Pression::associer_eqn(), Traitement_particulier_NS_Profils_thermo_VDF::associer_eqn(), and Traitement_particulier_NS_VEF::associer_eqn().
preparer_calcul_particulier()
virtual void Traitement_particulier_NS_base::preparer_calcul_particulier () pure virtual
Implemented in Traitement_particulier_NS_canal, Traitement_particulier_NS_chmoy_faceperio, Traitement_particulier_NS_EC, Traitement_particulier_NS_Pression, Traitement_particulier_NS_Profils, Traitement_particulier_NS_temperature, Traitement_particulier_NS_THI, Traitement_particulier_NS_THI_new, Traitement_particulier_NS_Profils_thermo_VDF, and Traitement_particulier_NS_VEF.
post_traitement_particulier()
virtual void Traitement_particulier_NS_base::post_traitement_particulier () pure virtual
Implemented in Traitement_particulier_NS_canal, Traitement_particulier_NS_chmoy_faceperio, Traitement_particulier_NS_EC, Traitement_particulier_NS_Pression, Traitement_particulier_NS_temperature, Traitement_particulier_NS_THI, Traitement_particulier_NS_THI_new, Traitement_particulier_NS_Pression_VDF, Traitement_particulier_NS_Profils_thermo_VDF, Traitement_particulier_NS_Profils_VDF, Traitement_particulier_NS_Brech_VEF, Traitement_particulier_NS_Pression_VEF, Traitement_particulier_NS_VEF, and Traitement_particulier_NS_Profils.
lire()
virtual Entree & Traitement_particulier_NS_base::lire (Entree & is) pure virtual
Implemented in Traitement_particulier_NS_canal, Traitement_particulier_NS_chmoy_faceperio, Traitement_particulier_NS_EC, Traitement_particulier_NS_Pression, Traitement_particulier_NS_Profils, Traitement_particulier_NS_temperature, Traitement_particulier_NS_THI, Traitement_particulier_NS_THI_new, Traitement_particulier_NS_canal_VDF, Traitement_particulier_NS_Pression_VDF, Traitement_particulier_NS_Profils_VDF, Traitement_particulier_NS_Brech_VEF, Traitement_particulier_NS_canal_VEF, Traitement_particulier_NS_Pression_VEF, Traitement_particulier_NS_VEF, and Traitement_particulier_NS_Profils_thermo_VDF.
sauver_stat()
virtual void Traitement_particulier_NS_base::sauver_stat () const pure virtual
Implemented in Traitement_particulier_NS_canal, Traitement_particulier_NS_chmoy_faceperio, Traitement_particulier_NS_EC, Traitement_particulier_NS_Pression, Traitement_particulier_NS_Profils, Traitement_particulier_NS_temperature, Traitement_particulier_NS_THI, Traitement_particulier_NS_THI_new, Traitement_particulier_NS_Profils_thermo_VDF, and Traitement_particulier_NS_VEF.
reprendre_stat()
virtual void Traitement_particulier_NS_base::reprendre_stat () pure virtual
Implemented in Traitement_particulier_NS_canal, Traitement_particulier_NS_chmoy_faceperio, Traitement_particulier_NS_EC, Traitement_particulier_NS_Pression, Traitement_particulier_NS_Profils, Traitement_particulier_NS_temperature, Traitement_particulier_NS_THI, Traitement_particulier_NS_THI_new, Traitement_particulier_NS_Profils_thermo_VDF, and Traitement_particulier_NS_VEF.
en_cours_de_resolution()
virtual void Traitement_particulier_NS_base::en_cours_de_resolution (int , DoubleTab & , DoubleTab & , double) pure virtual
Implemented in Traitement_particulier_NS_canal, Traitement_particulier_NS_chmoy_faceperio, Traitement_particulier_NS_EC, Traitement_particulier_NS_Pression, Traitement_particulier_NS_Profils, Traitement_particulier_NS_temperature, Traitement_particulier_NS_THI, Traitement_particulier_NS_THI_new, and Traitement_particulier_NS_VEF.
creer_champ()
void Traitement_particulier_NS_base::creer_champ (const Motcle &) inline override virtual
Implements Champs_compris_interface.
get_champ()
const Champ_base & Traitement_particulier_NS_base::get_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::get_champ().
get_noms_champs_postraitables()
void Traitement_particulier_NS_base::get_noms_champs_postraitables (Noms & nom, Option opt = NONE) const override virtual
Implements Champs_compris_interface.
References champs_compris_, Champs_compris_T< FIELD_TYPE >::liste_noms_compris(), and Objet_U::que_suis_je().
has_champ() [1/2]
bool Traitement_particulier_NS_base::has_champ (const Motcle & nom, OBS_PTR(Champ_base) & ref_champ) const override
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
has_champ() [2/2]
bool Traitement_particulier_NS_base::has_champ (const Motcle & nom) const override virtual
Implements Champs_compris_interface.
References champs_compris_, and Champs_compris_T< FIELD_TYPE >::has_champ().
OBS_PTR()
Traitement_particulier_NS_base::OBS_PTR (Navier_Stokes_std) protected
Referenced by Traitement_particulier_NS_EC::calculer_Ec().
Member Data Documentation
champs_compris_
Champs_compris Traitement_particulier_NS_base::champs_compris_ protected
Referenced by get_champ(), get_noms_champs_postraitables(), has_champ(), has_champ(), Traitement_particulier_NS_Pression_VDF::lire(), Traitement_particulier_NS_Brech_VEF::lire(), and Traitement_particulier_NS_Pression_VEF::lire().