CEA TRUST Platform: Op_Evanescence_Homogene_PolyMAC_P0_Face Class Reference
Op_Evanescence_Homogene_PolyMAC_P0_Face Class Reference
Additional Inherited Members
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int impr (Sortie &os) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
dimensionner_blocs_aux()
void Op_Evanescence_Homogene_PolyMAC_P0_Face::dimensionner_blocs_aux (std::set< int > & idx, IntTab & sten, Matrice_Morse & mat) const override protected virtual
Reimplemented from Op_Evanescence_Homogene_Face_base.
References TRUSTTab< _TYPE_, _SIZE_ >::append_line(), Objet_U::dimension, MorEqn::equation(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Inc_base::valeurs().
ajouter_blocs_aux()
void Op_Evanescence_Homogene_PolyMAC_P0_Face::ajouter_blocs_aux (IntTrav & maj, DoubleTrav coeff, matrices_t matrices, DoubleTab & secmem) const override protected virtual
Reimplemented from Op_Evanescence_Homogene_Face_base.
References Process::abort(), Vitesse_relative_base::input_t::alpha, Op_Evanescence_Homogene_Face_base::alpha_res_, Op_Evanescence_Homogene_Face_base::alpha_res_min_, calc_grad_alpha_elem(), calc_vort_elem(), Vitesse_relative_base::input_t::d_bulles, Vitesse_relative_base::input_t::dh, Milieu_base::diametre_hydraulique_elem(), Objet_U::dimension, Vitesse_relative_base::output_t::dvr, MorEqn::equation(), Pb_Multiphase::equation_energie(), Pb_Multiphase::equation_masse(), Pb_Multiphase::equation_qdm(), Vitesse_relative_base::input_t::g, Probleme_base::get_champ(), Probleme_base::get_correlation(), Milieu_composite::get_interface(), Matrice_Morse::get_set_coeff(), Matrice_Morse::get_tab1(), Matrice_Morse::get_tab2(), Nom::getString(), Vitesse_relative_base::input_t::gradAlpha, Probleme_base::has_champ(), Probleme_base::has_correlation(), Milieu_composite::has_interface(), Equation_base::inconnue(), Vitesse_relative_base::input_t::k, Field_base::le_nom(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), Milieu_base::masse_volumique(), Equation_base::milieu(), Vitesse_relative_base::input_t::mu, Vitesse_relative_base::needs_grad_alpha(), Vitesse_relative_base::needs_vort(), Vitesse_relative_base::input_t::nut, Champ_Proto::passe(), Champ_Inc_base::passe(), Equation_base::probleme(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::resize(), Pb_Multiphase::resolution_en_T(), Vitesse_relative_base::input_t::rho, Vitesse_relative_base::input_t::sigma, Interface_base::sigma(), Interface_base::sigma_h(), Vitesse_relative_base::input_t::v, Champ_Inc_base::valeurs(), Champ_Proto::valeurs(), Vitesse_relative_base::vitesse_relative(), Vitesse_relative_base::input_t::vort, and Vitesse_relative_base::output_t::vr.
calc_grad_alpha_elem()
void Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_elem (DoubleTab & gradAlphaElem) const protected
References Objet_U::dimension, Champ_Inc_base::domaine_Cl_dis(), MorEqn::equation(), Pb_Multiphase::equation_masse(), Champ_Inc_P0_base::fcl(), Champ_Elem_PolyMAC_P0::fgrad_d, Champ_Elem_PolyMAC_P0::fgrad_e, Champ_Elem_PolyMAC_P0::fgrad_w, Equation_base::inconnue(), Champ_Elem_PolyMAC_P0::init_grad(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Inc_base::passe().
Referenced by ajouter_blocs_aux().
calc_grad_alpha_faces()
void Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_grad_alpha_faces (DoubleTab & gradAlphaFaces) const override protected virtual
Reimplemented from Op_Evanescence_Homogene_Face_base.
References Objet_U::dimension, Champ_Inc_base::domaine_Cl_dis(), MorEqn::equation(), Pb_Multiphase::equation_masse(), Champ_Inc_P0_base::fcl(), Champ_Elem_PolyMAC_P0::fgrad_d, Champ_Elem_PolyMAC_P0::fgrad_e, Champ_Elem_PolyMAC_P0::fgrad_w, Equation_base::inconnue(), Champ_Elem_PolyMAC_P0::init_grad(), Domaine_Cl_dis_base::les_conditions_limites(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), and Champ_Inc_base::passe().
calc_vort_elem()
void Op_Evanescence_Homogene_PolyMAC_P0_Face::calc_vort_elem (DoubleTab & vort) const protected
References Objet_U::dimension, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), Probleme_base::get_champ(), Equation_base::probleme(), and Champ_Proto::valeurs().
Referenced by ajouter_blocs_aux().