CEA TRUST Platform: Terme_Boussinesq_base Class Reference
Terme_Boussinesq_base Class Reference
#include <Terme_Boussinesq_base.h>
Public Member Functions
void mettre_a_jour (double temps) override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int initialiser (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
int lire_motcle_non_standard (const Motcle &, Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
de la dynamique divisee par la masse volumique de reference. On est dans le cadre de l'hypothese de Boussinesq:la masse volumique est supposee constante et egale a sa valeur de reference sauf dans le terme des forces de volumes ou on prend en compte une petite variation de la masse volumique en fonction d'un ou de plusieurs scalaires transportes par l'ecoulement (la temperature et/ou une ou plusieurs concentrations). Cas particulier de Terme_Boussinesq_base pour la temperature Le terme de gravite a pour expression: beta*(T-T0) ou beta represente la dilatabilite de la masse volumique et T0 une valeur de reference pour la temperature Cas particulier de Terme_Boussinesq_base pour une concentration Le terme de gravite a pour expression : beta*(C-C0) ou (beta[0]*(C[0]-C0[0]) + .....+ beta[i]*(C[i]-C0[i])) dans le cas d'un vecteur de concentrations beta represente la variation de la masse volumique en fonction de la concentration du constituant et C0 une valeur de reference pour la concentration
Member Function Documentation
associer_pb()
void Terme_Boussinesq_base::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
References Process::abort(), Fluide_base::beta_c(), Milieu_base::beta_t(), MorEqn::equation(), Probleme_base::equation(), Process::exit(), Milieu_base::gravite(), Fluide_base::has_beta_c(), Milieu_base::has_beta_t(), Equation_base::inconnue(), Field_base::le_nom(), Probleme_base::nombre_d_equations(), NomScalaire_, and Objet_U::que_suis_je().
gravite()
const Champ_Don_base & Terme_Boussinesq_base::gravite () const inline
Referenced by Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), and Terme_Boussinesq_PolyMAC_Face::ajouter_blocs().
verification()
int Terme_Boussinesq_base::verification () const inline
References verif_.
Scalaire0()
double Terme_Boussinesq_base::Scalaire0 (int i) const inline
References Scalaire0_.
Referenced by Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), and check().
beta()
const Champ_Don_base & Terme_Boussinesq_base::beta () const inline
Referenced by Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), and Terme_Boussinesq_PolyMAC_Face::ajouter_blocs().
equation_scalaire()
const Convection_Diffusion_std & Terme_Boussinesq_base::equation_scalaire () const inline
Referenced by Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), Terme_Boussinesq_PolyMAC_Face::ajouter_blocs(), and check().
calculer()
DoubleTab & Terme_Boussinesq_base::calculer (DoubleTab & resu) const inline override virtual
Reimplemented from Source_base.
References Source_base::ajouter().
mettre_a_jour()
void Terme_Boussinesq_base::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour en temps du terme source.
Parameters
(double) le pas de temps de mise a jour
Reimplemented from Source_base.
References Scalaire0_, and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
getScalaire0()
const ArrOfDouble & Terme_Boussinesq_base::getScalaire0 () const inline
References Scalaire0_.
Referenced by Terme_Boussinesq_VEF_Face::ajouter(), and Terme_Boussinesq_VEFPreP1B_Face::ajouter().
set_param()
void Terme_Boussinesq_base::set_param (Param & param) protected
References Param::ajouter(), Param::ajouter_non_std(), and verif_.
lire_motcle_non_standard()
int Terme_Boussinesq_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override protected virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References NomScalaire_, TRUSTArray< _TYPE_, _SIZE_ >::resize(), and Scalaire0_.
OBS_PTR() [1/3]
Terme_Boussinesq_base::OBS_PTR (Champ_Don_base) protected
VECT()
Terme_Boussinesq_base::VECT (Parser_U) protected
OBS_PTR() [2/3]
Terme_Boussinesq_base::OBS_PTR (Champ_Don_base) protected
OBS_PTR() [3/3]
Terme_Boussinesq_base::OBS_PTR (Convection_Diffusion_std) protected
check()
void Terme_Boussinesq_base::check () const inline protected
References Probleme_base::domaine(), equation_scalaire(), Process::exit(), Equation_base::probleme(), Scalaire0(), and verif_.
Referenced by Terme_Boussinesq_VEF_Face::ajouter(), Terme_Boussinesq_VEFPreP1B_Face::ajouter(), Terme_Boussinesq_VDF_Face::ajouter_blocs(), and Terme_Boussinesq_PolyMAC_Face::ajouter_blocs().
Member Data Documentation
verif_
int Terme_Boussinesq_base::verif_ =1 protected
Referenced by check(), set_param(), and verification().
Scalaire0_
ArrOfDouble Terme_Boussinesq_base::Scalaire0_ protected
Referenced by Terme_Boussinesq_VEF_Face::ajouter(), getScalaire0(), lire_motcle_non_standard(), mettre_a_jour(), and Scalaire0().
NomScalaire_
Nom Terme_Boussinesq_base::NomScalaire_ protected
Referenced by associer_pb(), and lire_motcle_non_standard().