CEA TRUST Platform: Loi_Fermeture_Test Class Reference
Loi_Fermeture_Test Class Reference
Public Member Functions
void discretiser (const Discretisation_base &) override
void mettre_a_jour (double temps) override
void set_param (Param &param) override
Public Member Functions inherited from Loi_Fermeture_base
virtual void associer_pb_base (const Probleme_base &)
virtual void completer ()
const Champ_base & get_champ (const Motcle &nom) const override
const Nom & le_nom () const override
void nommer (const Nom &nom) override
virtual void preparer_calcul ()
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Member Function Documentation
mettre_a_jour()
void Loi_Fermeture_Test::mettre_a_jour (double temps) override virtual
Cette methode est appelee par le probleme apres mettre_a_jour() des equations et du milieu.
Elle doit mettre a jour tous les champs qu'elle gere en fonction des autres champs du probleme.
Reimplemented from Loi_Fermeture_base.
References coef_, Loi_Fermeture_base::COMPLET, and Loi_Fermeture_base::status_.
discretiser()
void Loi_Fermeture_Test::discretiser (const Discretisation_base &) override virtual
Cette methode est appelee par le probleme apres la discretisation des equations et du milieu et avant.
l'appel a readOn() pour lecture des parametres. Dans les classes derivees elle doit discretiser au minimum les champs qui seront requis dans le readOn() des equations ou des autres lois de fermeture.
Reimplemented from Loi_Fermeture_base.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Loi_Fermeture_base::champs_compris_, Loi_Fermeture_base::discretiser(), Discretisation_base::discretiser_champ(), Probleme_base::domaine_dis(), Loi_Fermeture_base::mon_probleme(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
set_param()
void Loi_Fermeture_Test::set_param (Param & param) override virtual
Cette methode est appelee par le readOn de la classe.
Elle doit etre reimplementee dans les classes derivees pour ajouter dans "param" les differents parametres a lire dans le jeu de donnees et appeler la methode de l'ancetre. Dans la classe de base: aucun parametre.
Reimplemented from Loi_Fermeture_base.
References Param::ajouter(), and coef_.
OWN_PTR()
Loi_Fermeture_Test::OWN_PTR (Champ_Don_base) protected
Member Data Documentation
coef_
double Loi_Fermeture_Test::coef_ =1. protected
Referenced by mettre_a_jour(), and set_param().