CEA TRUST Platform: Convection_Diffusion_Chaleur_WC Class Reference
Convection_Diffusion_Chaleur_WC Class Reference
Public Member Functions
void completer () override
int lire_motcle_non_standard (const Motcle &, Entree &) override
int preparer_calcul () override
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
Public Member Functions inherited from Convection_Diffusion_Chaleur_Fluide_Dilatable_base
DoubleTab & derivee_en_temps_inco (DoubleTab &) override
void discretiser () override
const Motcle & domaine_application () const override
int remplir_cl_modifiee ()
Public Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_base
int impr (Sortie &os) const override
Public Member Functions inherited from Convection_Diffusion_std
void associer_vitesse (const Champ_base &)
int lire_motcle_non_standard (const Motcle &, Entree &) override
int nombre_d_operateurs () const override
const Operateur & operateur (int) const override
Operateur & operateur (int) override
const Champ_Inc_base & vitesse_transportante () const
Public Member Functions inherited from Equation_base
virtual void abortTimeStep ()
virtual void associer_domaine_dis (const Domaine_dis_base &)
virtual void associer_pb_base (const Probleme_base &)
virtual void associer_sch_tps_base (const Schema_Temps_base &)
virtual double calculer_pas_de_temps () const
DoubleTab & derivee_en_temps_conv (DoubleTab &, const DoubleTab &)
const Discretisation_base & discretisation () const
virtual Domaine_Cl_dis_base & domaine_Cl_dis ()
virtual const Domaine_Cl_dis_base & domaine_Cl_dis () const
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual void imprimer (Sortie &os) const
virtual bool initTimeStep (double dt)
const Nom & le_nom () const override
int limpr () const
virtual void mettre_a_jour (double temps)
Probleme_base & probleme ()
const Probleme_base & probleme () const
Schema_Temps_base & schema_temps ()
const Schema_Temps_base & schema_temps () const
Solveur_Masse_base & solv_masse ()
const Solveur_Masse_base & solv_masse () const
Sources & sources ()
const Sources & sources () const
virtual void valider_iteration ()
virtual void verifie_ch_init_nb_comp (const Champ_Inc_base &ch_ref, const int nb_comp) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Equation_base
virtual Entree & lire_cl (Entree &)
virtual Entree & lire_cond_init (Entree &)
virtual Entree & lire_sources (Entree &)
virtual int verif_Cl () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Convection_Diffusion_Fluide_Dilatable_Proto
DoubleTab & derivee_en_temps_inco_sans_solveur_masse_impl (Convection_Diffusion_Fluide_Dilatable_base &eqn, DoubleTab &derivee, const bool is_expl)
Detailed Description
quand le scalaire subissant le transport est la temperature en gaz parfaits,
ou l'enthalpie en gaz reels.
(generalisation de Convection_Diffusion_Temperature pour les gaz reels)
See also
Conv_Diffusion_std Convection_Diffusion_Temperature
Member Function Documentation
set_param()
void Convection_Diffusion_Chaleur_WC::set_param (Param & titi) override virtual
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
References Convection_Diffusion_Fluide_Dilatable_base::set_param().
completer()
void Convection_Diffusion_Chaleur_WC::completer () override virtual
Complete la construction (initialisation) des objets associes a l'equation.
Complete les sources, associe l'equation a l'inconnue complete les operateurs, complete les conditions aux limites discretisees. Voir les methodes Source_base::completer(), Operateur_base::completer() Domaine_Cl_dis_base::completer() Domaine_Cl_dis_base::completer(const Domaine_dis_base&)
Reimplemented from Equation_base.
References MorEqn::associer_eqn(), Operateur_base::associer_eqn(), Equation_base::completer(), Equation_base::domaine_Cl_dis(), Equation_base::domaine_dis(), Convection_Diffusion_Fluide_Dilatable_base::inconnue(), Operateur_Grad::l_op_base(), Op_Grad_WC_, and Operateur_Grad::typer().
vitesse_pour_transport()
const Champ_base & Convection_Diffusion_Chaleur_WC::vitesse_pour_transport () const override virtual
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References Convection_Diffusion_Chaleur_Fluide_Dilatable_base::vitesse_pour_transport().
lire_motcle_non_standard()
int Convection_Diffusion_Chaleur_WC::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Convection_Diffusion_Fluide_Dilatable_base.
References Equation_base::discretisation(), Equation_base::les_sources, Convection_Diffusion_Fluide_Dilatable_base::lire_motcle_non_standard(), Objet_U::que_suis_je(), and Source::typer_direct().
preparer_calcul()
int Convection_Diffusion_Chaleur_WC::preparer_calcul () override virtual
Tout ce qui ne depend pas des autres problemes eventuels.
Returns
(int) renvoie toujours 1
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References Convection_Diffusion_Chaleur_Fluide_Dilatable_base::preparer_calcul(), and Convection_Diffusion_Chaleur_Fluide_Dilatable_base::remplir_cl_modifiee().
sauvegarder()
int Convection_Diffusion_Chaleur_WC::sauvegarder (Sortie & os) const override virtual
On sauvegarde l'inconnue de l'equation sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) le code de retour de Champ_Inc::sauvegarder()
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References Convection_Diffusion_Fluide_Dilatable_Proto::Sauvegarder_WC().
reprendre()
int Convection_Diffusion_Chaleur_WC::reprendre (Entree & is) override virtual
Effectue une reprise a partir d'un flot d'entree.
Appelle Equation_base::reprendre() et reprend l'inconnue de la chaleur et la pression thermodynamique
Parameters
(Entree& is) un flot d'entree
Returns
(int) renvoie toujours 1
Exceptions
la reprise a echoue, identificateur de la pression non trouve
Reimplemented from Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References Equation_base::probleme(), Convection_Diffusion_Fluide_Dilatable_Proto::Reprendre_WC(), Equation_base::schema_temps(), and Schema_Temps_base::temps_courant().
operateur_gradient_WC()
const Operateur_Grad& Convection_Diffusion_Chaleur_WC::operateur_gradient_WC () const inline
References Op_Grad_WC_.
Referenced by Source_WC_Chaleur_VDF::compute_interpolate_gradP(), and Source_WC_Chaleur_VEF::compute_interpolate_gradP().
is_generic()
bool Convection_Diffusion_Chaleur_WC::is_generic () const inline override virtual
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
calculer_div_u_ou_div_rhou()
void Convection_Diffusion_Chaleur_WC::calculer_div_u_ou_div_rhou (DoubleTab & res) const override protected virtual
Implements Convection_Diffusion_Chaleur_Fluide_Dilatable_base.
References Convection_Diffusion_Fluide_Dilatable_Proto::calculer_div_rho_u_impl().
Member Data Documentation
Op_Grad_WC_
Operateur_Grad Convection_Diffusion_Chaleur_WC::Op_Grad_WC_ protected
Referenced by completer(), and operateur_gradient_WC().