CEA TRUST Platform: Echange_contact_Colburn_VDF Class Reference
Echange_contact_Colburn_VDF Class Reference
Public Member Functions
double calculer_coefficient_echange (int i) override
double volume (double s, double d) override
Public Member Functions inherited from Echange_contact_Correlation_VDF
void completer () override
virtual void imprimer (double) const
virtual int limpr (double, double) const
void mettre_a_jour (double) override
Public Member Functions inherited from Echange_global_impose
int compatible_avec_discr (const Discretisation_base &discr) const override
int initialiser (double temps) override
Public Member Functions inherited from Echange_impose_base
int a_mettre_a_jour_ss_pas_dt () override
void associer_fr_dis_base (const Frontiere_dis_base &) override
double emissivite (int num) const
double emissivite (int num, int k) const
virtual double h_imp (int num) const
virtual double h_imp (int num, int k) const
int initialiser (double temps) override
virtual Champ_front_base & T_ext ()
virtual double T_ext (int num) const
virtual double T_ext (int num, int k) const
Public Member Functions inherited from Cond_lim_base
virtual void associer_domaine_cl_dis_base (const Domaine_Cl_dis_base &)
virtual void calculer_coeffs_echange (double temps)
Domaine_Cl_dis_base & domaine_Cl_dis ()
const Domaine_Cl_dis_base & domaine_Cl_dis () const
virtual Frontiere_dis_base & frontiere_dis ()
virtual const Frontiere_dis_base & frontiere_dis () const
void set_modifier_val_imp (int)
virtual void verifie_ch_init_nb_comp () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Echange_contact_Correlation_VDF
void calculer_CL ()
void calculer_h_mon_pb (DoubleTab &)
void calculer_prop_physique ()
void calculer_Q ()
void calculer_Tfluide ()
void calculer_Vitesse ()
void init_tab_echange ()
int lire_motcle_non_standard (const Motcle &, Entree &) override
Protected Member Functions inherited from Cond_lim_base
void err_pas_compatible (const Discretisation_base &) const
void err_pas_compatible (const Equation_base &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
calculer_coefficient_echange()
double Echange_contact_Colburn_VDF::calculer_coefficient_echange (int i) override virtual
Calcule le coeff d echange suivant la correlation de Colburn
Reimplemented from Echange_contact_Correlation_VDF.
References Echange_contact_Correlation_VDF::getCp(), Echange_contact_Correlation_VDF::getDh(), Echange_contact_Correlation_VDF::getLambda(), Echange_contact_Correlation_VDF::getMu(), and Echange_contact_Correlation_VDF::getQh().
volume()
double Echange_contact_Colburn_VDF::volume (double s, double d) override virtual
Calcule le volume d'une tranche de la section de surface laterale s et de diametre hydraulique d.
Reimplemented from Echange_contact_Correlation_VDF.