CEA TRUST Platform: Sortie Class Reference
Sortie Class Reference
Public Member Functions
virtual Sortie & operator<< (const char *ob)
virtual Sortie & operator<< (const Objet_U &ob)
void set_bin (bool bin) override
Protected Attributes
std::unique_ptr< ostream > ostream_
Protected Attributes inherited from AbstractIO
bool avoid_conversion_ = false
Additional Inherited Members
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Detailed Description
Elle sait ecrire des types simples (entiers, flottants) et des Objet_U (via printOn de l'objet_U) Attention, certains classes derivees sont paralleles: dans ce cas, il faut appeler syncfile() periodiquement sur tous les processeurs. Voir class EcrFicPartage Attention: pour ecrire correctement un flux a la fois en ASCII et BINAIRE, il faut utiliser un Separateur (finl ou space) pour separer les objets ecrits.
See also
Entree
Constructor & Destructor Documentation
Sortie() [1/3]
Sortie::Sortie ()
Sortie() [2/3]
Sortie::Sortie (ostream & os)
References Process::exit(), and ostream_.
Sortie() [3/3]
Sortie::Sortie (const Sortie & os)
References has_ostream().
~Sortie()
virtual Sortie::~Sortie () inline virtual
Member Function Documentation
operator=() [1/2]
Sortie & Sortie::operator= (ostream & os)
References ostream_.
operator=() [2/2]
Sortie & Sortie::operator= (Sortie & os)
References has_ostream(), and ostream_.
set_bin()
void Sortie::set_bin (bool bin) override virtual
Change le mode d'ecriture du fichier.
Cette methode peut etre appelee n'importe quand. Attention cependant pour les fichiers Ecrire_Fichier_Partage : il faut faire le changement uniquement au debut de l'ecriture d'un bloc, juste apres syncfile() (sinon, mauvaise traduction des retours a la ligne lors du syncfile suivant).
Reimplemented from AbstractIO.
Reimplemented in Sortie_Brute.
References AbstractIO::bin_, Process::exit(), and ostream_.
Referenced by EcrFicCollecteBin::EcrFicCollecteBin(), Fichier_Lata::Fichier_Lata(), DecoupeBord_32_64< _SIZE_ >::interpreter_(), Ecrire_Fichier::interpreter_(), SolveurSys_base::save_matrice_secmem_conditionnel(), EcrFicPartage::set_bin(), SChaine::set_bin(), Sortie_Brute::set_bin(), SFichierBin::SFichierBin(), IJK_Striped_Writer::write_data_parallele_plan_template(), and IJK_Striped_Writer::write_data_template().
get_ostream() [1/2]
ostream& Sortie::get_ostream () inline
References ostream_.
Referenced by Sortie_Brute::get_data(), Sortie_Brute::get_size(), Ecrire_Fichier::interpreter_(), and EcrFicPartage::syncfile().
get_ostream() [2/2]
const ostream& Sortie::get_ostream () const inline
References ostream_.
set_col_width()
void Sortie::set_col_width (int w) inline
References col_width_.
Referenced by Terme_Source_Constituant::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), and Source_base::ouvrir_fichier().
operator<<() [1/16]
Sortie & Sortie::operator<< (ostream &(*)(ostream &) f)
References AbstractIO::bin_, and ostream_.
operator<<() [2/16]
Sortie & Sortie::operator<< (Sortie &(*)(Sortie &) f)
operator<<() [3/16]
Sortie & Sortie::operator<< (ios &(*)(ios &) f)
References ostream_.
flush()
Sortie & Sortie::flush () virtual
Reimplemented in Sortie_Nulle, Sortie_Fichier_base, OBuffer, and EcrFicPartage.
References ostream_.
Referenced by Modele_turbulence_hyd_base::a_faire(), Modele_turbulence_scal_base::a_faire(), operator<<(), Champ_Fonc_base::sauvegarder(), Champ_Inc_base::sauvegarder(), Modele_turbulence_hyd_null::sauvegarder(), and Postraitement::sauvegarder().
lockfile()
Sortie & Sortie::lockfile () virtual
Reimplemented in EcrFicPartage.
References Process::exit().
unlockfile()
Sortie & Sortie::unlockfile () virtual
Reimplemented in EcrFicPartage.
References Process::exit().
syncfile()
Sortie & Sortie::syncfile () virtual
Reimplemented in EcrFicPartage.
References Process::exit().
Referenced by EcritureLectureSpecial::ecriture_special(), and Fichier_Lata::syncfile().
setf()
void Sortie::setf (IOS_FORMAT code) virtual
Reimplemented in Sortie_Nulle, Sortie_Fichier_base, and SChaine.
References ostream_.
Referenced by SChaine::setf().
precision()
void Sortie::precision (int pre) virtual
Reimplemented in Sortie_Nulle, OBuffer, EcrFicPartage, and Sortie_Fichier_base.
References ostream_.
operator<<() [4/16]
template<typename T > Sortie& Sortie::operator<< (const TRUST_Ref< T > &) inline
operator<<() [5/16]
Sortie& Sortie::operator<< (const TRUST_Ref_Objet_U &) inline
operator<<() [6/16]
Sortie & Sortie::operator<< (const Separateur & ob) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
References AbstractIO::bin_, Separateur::ENDL, flush(), Separateur::get_type(), and Separateur::SPACE.
operator<<() [7/16]
Sortie & Sortie::operator<< (const Objet_U & ob) virtual
Ecriture d'un objet ou d'une variable.
Dans cette implementation (et dans la plupart des classes derivees) on appelle simplement ob.printOn (a l'exception de Sortie_Nulle) Attention, si on veut que le flux puisse etre indifferemment ASCII ou BINAIRE, il faut inserer "<< space <<" ou "<< finl <<" pour separer les objets.
Reimplemented in Sortie_Nulle, and EcrFicPartage.
References Objet_U::printOn().
operator<<() [8/16]
Sortie & Sortie::operator<< (const True_int ob) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
operator<<() [9/16]
Sortie & Sortie::operator<< (const unsigned ob) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
operator<<() [10/16]
Sortie & Sortie::operator<< (const long ob) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
operator<<() [11/16]
Sortie & Sortie::operator<< (const long long ob) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
operator<<() [12/16]
Sortie & Sortie::operator<< (const unsigned long ob) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
operator<<() [13/16]
Sortie & Sortie::operator<< (const float ob) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
operator<<() [14/16]
Sortie & Sortie::operator<< (const double ob) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
operator<<() [15/16]
Sortie & Sortie::operator<< (const char * ob) virtual
Ecriture d'une chaine de caracteres.
Attention, pour pouvoir relire correctement la chaine en mode ascii, celle-ci ne doit pas contenir de separateur (ni espace, ni retour a la ligne, ...)
Reimplemented in Sortie_Nulle, and EcrFicPartage.
References AbstractIO::bin_, and ostream_.
operator<<() [16/16]
Sortie & Sortie::operator<< (const std::string & str) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
add_col() [1/2]
int Sortie::add_col (const double ob) virtual
References AbstractIO::bin_, col_width_, and ostream_.
Referenced by Op_Grad_VEF_P1B_Face::impr(), Op_EF_base::impr(), Op_VEF_Face::impr(), Source_base::impr(), Op_Div_EF::impr(), Op_Grad_EF::impr(), Op_Conv_PolyMAC_base::impr(), Op_Diff_PolyMAC_Gen_base::impr(), Op_Div_PolyMAC::impr(), Op_Grad_VDF_Face::impr(), Op_Div_VEFP1B_Elem::impr(), Terme_Source_Constituant::ouvrir_fichier(), Operateur_base::ouvrir_fichier(), and Source_base::ouvrir_fichier().
add_col() [2/2]
int Sortie::add_col (const char * ob) virtual
References AbstractIO::bin_, col_width_, and ostream_.
put() [1/6]
int Sortie::put (const unsigned * ob, std::streamsize n, std::streamsize nb_colonnes = 1) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
Referenced by MD_Vector_tools::dump_vector_with_md(), Debog_Pb::ecrire_partie(), TRUSTTab< _TYPE_, _SIZE_ >::ecrit(), TRUSTArray< _TYPE_, _SIZE_ >::printOn(), TRUSTTab< _TYPE_, _SIZE_ >::printOn(), IJK_Striped_Writer::write_data_parallel2_template(), IJK_Striped_Writer::write_data_parallele_plan_template(), and IJK_Striped_Writer::write_data_template().
put() [2/6]
int Sortie::put (const True_int * ob, std::streamsize n, std::streamsize nb_colonnes = 1) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
put() [3/6]
int Sortie::put (const float * ob, std::streamsize n, std::streamsize nb_colonnes = 1) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
put() [4/6]
int Sortie::put (const double * ob, std::streamsize n, std::streamsize nb_colonnes = 1) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
put() [5/6]
int Sortie::put (const long * ob, std::streamsize n, std::streamsize nb_colonnes = 1) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
put() [6/6]
int Sortie::put (const long long * ob, std::streamsize n, std::streamsize nb_colonnes = 1) virtual
Reimplemented in Sortie_Nulle, and EcrFicPartage.
has_ostream()
bool Sortie::has_ostream () const inline
References ostream_.
Referenced by operator=(), and Sortie().
Member Data Documentation
col_width_
int Sortie::col_width_ protected
Referenced by add_col(), and set_col_width().
ostream_
std::unique_ptr<ostream> Sortie::ostream_ protected
A smart pointer to a std::ostream object, or any of its derived class. Explicit construction might be done in derived classes of Sortie.
Referenced by add_col(), flush(), get_ostream(), has_ostream(), OBuffer::new_buffer(), operator<<(), operator=(), OutputCommBuffer::OutputCommBuffer(), Sortie_Fichier_base::ouvrir(), precision(), set_bin(), setf(), Sortie(), and Sortie_Brute::Sortie_Brute().