CEA TRUST Platform: Flux_parietal_Nusselt Class Reference
Flux_parietal_Nusselt Class Reference
Public Member Functions
int lire_motcle_non_standard (const Motcle &mot, Entree &is) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
lire_motcle_non_standard()
int Flux_parietal_Nusselt::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
References Parser_U::addVar(), Objet_U::lire_motcle_non_standard(), Parser_U::parseString(), Parser_U::setNbVar(), and Parser_U::setString().
qp()
void Flux_parietal_Nusselt::qp (const input_t & input, output_t & output) const override virtual
Implements Flux_parietal_base.
References Flux_parietal_base::input_t::Cp, Flux_parietal_base::input_t::D_ch, Flux_parietal_base::input_t::D_h, Flux_parietal_base::output_t::dp_qpk, Flux_parietal_base::output_t::dTf_qpk, Flux_parietal_base::output_t::dTp_qpk, Parser_U::eval(), Flux_parietal_base::input_t::lambda, Flux_parietal_base::input_t::mu, Flux_parietal_base::output_t::qpk, Flux_parietal_base::input_t::rho, Parser_U::setVar(), Flux_parietal_base::input_t::T, Flux_parietal_base::input_t::Tp, and Flux_parietal_base::input_t::v.
T_at_wall()
int Flux_parietal_Nusselt::T_at_wall () const inline override virtual
Implements Flux_parietal_base.