CEA TRUST Platform: Perte_Charge_VDF_base Class Reference
Perte_Charge_VDF_base Class Reference
Additional Inherited Members
Public Member Functions inherited from Perte_Charge_Gen
void completer () override
Public Member Functions inherited from Source_base
virtual int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int initialiser (double temps)
virtual void mettre_a_jour (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from Terme_Source_Qdm
const Champ_Don_base & source () const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Perte_Charge_Gen
virtual void coeffs_perte_charge (const DoubleVect &u, const DoubleVect &pos, double t, double norme_u, double dh, double nu, double reynolds, double &coeff_ortho, double &coeff_long, double &u_l, DoubleVect &v_valeur) const =0
int lire_motcle_non_standard (const Motcle &, Entree &) override
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Perte_Charge_Isotrope, Perte_Charge_Directionnelle et Perte_Charge_Anisotrope heritent de Perte_Charge_VDF_base. Elles doivent surcharger essentiellement readOn() et perte_charge(). readOn() est suppose lire au moins diam_hydr et sous_domaine.
Member Function Documentation
ajouter_blocs()
void Perte_Charge_VDF_base::ajouter_blocs (matrices_t matrices, DoubleTab & secmem, const tabs_t & semi_impl = {}) const override virtual
Reimplemented from Source_base.
References Multiplicateur_diphasique_base::coefficient(), Perte_Charge_Gen::coeffs_perte_charge(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Pb_Multiphase::equation_masse(), Champ_Face_base::fcl(), Probleme_base::get_correlation(), Milieu_composite::get_saturation(), Interface_base::get_sigma_tab(), Nom::getString(), Probleme_base::has_correlation(), Milieu_composite::has_saturation(), Equation_base::inconnue(), Field_base::le_nom(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), Champ_Inc_base::passe(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), Equation_base::schema_temps(), Perte_Charge_Gen::sous_domaine, Schema_Temps_base::temps_courant(), Champ_base::valeur_a_compo(), and Champ_Don_base::valeurs().
has_interface_blocs()
int Perte_Charge_VDF_base::has_interface_blocs () const inline override virtual
Reimplemented from Source_base.
check_multiphase_compatibility()
void Perte_Charge_VDF_base::check_multiphase_compatibility () const inline override virtual
Reimplemented from MorEqn.