CEA TRUST Platform: Op_Diff_DG_base Class Reference
Op_Diff_DG_base Class Reference
Public Member Functions
double calculer_dt_stab () const override
void completer () override
int impr (Sortie &os) const override
void mettre_a_jour (double t) override
Public Member Functions inherited from Operateur_Diff_base
virtual void associer_diffusivite_pour_pas_de_temps (const Champ_base &)
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Support_Champ_Masse_Volumique
Support_Champ_Masse_Volumique ()
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Operateur_Diff_base
virtual const Champ_base & diffusivite_pour_pas_de_temps () const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Protected Member Functions inherited from Support_Champ_Masse_Volumique
virtual void declare_support_masse_volumique (int ok)
Member Function Documentation
associer()
void Op_Diff_DG_base::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & zcl, const Champ_Inc_base &) override virtual
Implements Operateur_base.
calculer_dt_stab()
double Op_Diff_DG_base::calculer_dt_stab () const override virtual
Calcul dt_stab.
Returns
(double) renvoie toujours 1.e30
Reimplemented from Operateur_base.
References Milieu_base::conductivite(), diffusivite(), Operateur_Diff_base::diffusivite_pour_pas_de_temps(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), Support_Champ_Masse_Volumique::get_champ_masse_volumique(), Echange_impose_base::h_imp(), Support_Champ_Masse_Volumique::has_champ_masse_volumique(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Process::mp_max(), Process::mp_min(), Domaine_Cl_dis_base::nb_cond_lim(), Domaine_32_64< _SIZE_ >::nb_elem(), TRUSTVect< _TYPE_, _SIZE_ >::size(), update_nu(), Champ_Don_base::valeurs(), Champ_front_base::valeurs(), and Champ_Proto::valeurs().
associer_diffusivite()
void Op_Diff_DG_base::associer_diffusivite (const Champ_base & diffu) inline override virtual
Implements Operateur_Diff_base.
completer()
void Op_Diff_DG_base::completer () override virtual
Associe l'operateur au domaine_dis, le domaine_Cl_dis, et a l'inconnue de son equation.
Exceptions
pas d'equation associee
Reimplemented from Operateur_base.
Reimplemented in Op_Diff_DG_Elem.
References Operateur_base::completer(), diffusivite(), MorEqn::equation(), nu_, nu_a_jour_, Objet_U::que_suis_je(), and TRUSTTab< _TYPE_, _SIZE_ >::resize().
Referenced by Op_Diff_DG_Elem::completer().
diffusivite()
const Champ_base& Op_Diff_DG_base::diffusivite () const inline override virtual
Implements Operateur_Diff_base.
Referenced by calculer_dt_stab(), completer(), and update_nu().
mettre_a_jour()
void Op_Diff_DG_base::mettre_a_jour (double temps) inline override virtual
DOES NOTHING - to override in derived classes.
Mise a jour de l'operateur
Parameters
(double) un pas de temps
Reimplemented from Operateur_base.
References Operateur_base::mettre_a_jour(), and nu_a_jour_.
update_nu()
void Op_Diff_DG_base::update_nu () const
References diffusivite(), Op_Diff_Turbulent_base::diffusivite_turbulente(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), MorEqn::equation(), TRUSTVect< _TYPE_, _SIZE_ >::get_md_vector(), Op_Diff_Turbulent_base::has_diffusivite_turbulente(), TRUSTArray< _TYPE_, _SIZE_ >::inject_array(), TRUSTVect< _TYPE_, _SIZE_ >::line_size(), MD_Vector::non_nul(), nu_, nu_a_jour_, Objet_U::que_suis_je(), Champ_Don_base::valeurs(), and Champ_Proto::valeurs().
Referenced by Op_Diff_DG_Elem::ajouter_blocs(), and calculer_dt_stab().
calculer()
DoubleTab & Op_Diff_DG_base::calculer (const DoubleTab & inco, DoubleTab & resu) const override virtual
Reimplemented from Operateur_base.
References Operateur_base::ajouter().
impr()
int Op_Diff_DG_base::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
OBS_PTR() [1/3]
Op_Diff_DG_base::OBS_PTR (Domaine_DG) protected
OBS_PTR() [2/3]
Op_Diff_DG_base::OBS_PTR (Domaine_Cl_DG) protected
OBS_PTR() [3/3]
Op_Diff_DG_base::OBS_PTR (Champ_base) protected
Member Data Documentation
Flux
SFichier Op_Diff_DG_base::Flux mutable protected
Flux_moment
SFichier Op_Diff_DG_base::Flux_moment protected
Flux_sum
SFichier Op_Diff_DG_base::Flux_sum protected
nu_a_jour_
int Op_Diff_DG_base::nu_a_jour_ = 0 mutable protected
Referenced by completer(), mettre_a_jour(), and update_nu().
nu_
DoubleTab Op_Diff_DG_base::nu_ mutable protected
Referenced by completer(), Op_Diff_DG_Elem::contribuer_au_second_membre(), and update_nu().