CEA TRUST Platform: Champ_Generique_modifier_pour_QC Class Reference
Champ_Generique_modifier_pour_QC Class Reference
#include <Champ_Generique_modifier_pour_QC.h>
Additional Inherited Members
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
Entity get_localisation (const int index=-1) const override
const Noms get_property (const Motcle &query) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Generique_base
int lire_motcle_non_standard (const Motcle &, Entree &) override
void nommer (const Nom &nom) override
int reprendre (Entree &is) override
int sauvegarder (Sortie &os) const override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
que l on souhaite multiplier ou diviser par la masse volumique (rho). La classe porte une REF au milieu qui doit etre de type Fluide_Quasi_Compressible.
Constructor & Destructor Documentation
Champ_Generique_modifier_pour_QC()
Champ_Generique_modifier_pour_QC::Champ_Generique_modifier_pour_QC ()
Member Function Documentation
set_param()
void Champ_Generique_modifier_pour_QC::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Param::ajouter_flag(), diviser_, and Champ_Gen_de_Champs_Gen::set_param().
completer()
void Champ_Generique_modifier_pour_QC::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Gen_de_Champs_Gen::completer(), Probleme_base::equation(), Equation_base::milieu(), and Postraitement::probleme().
get_champ()
const Champ_base & Champ_Generique_modifier_pour_QC::get_champ (OWN_PTR(Champ_base)& espace_stockage) const override
References diviser_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Champ_Generique_base::get_champ(), Champ_Gen_de_Champs_Gen::get_source(), Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), Champ_Gen_de_Champs_Gen::OWN_PTR(), and Champ_Proto::valeurs().
get_champ_without_evaluation()
const Champ_base & Champ_Generique_modifier_pour_QC::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const override virtual
Implements Champ_Generique_base.
References Champ_Generique_base::get_champ_without_evaluation(), Champ_Gen_de_Champs_Gen::get_source(), Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), and Champ_Gen_de_Champs_Gen::OWN_PTR().
nommer_source()
void Champ_Generique_modifier_pour_QC::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
OBS_PTR()
Champ_Generique_modifier_pour_QC::OBS_PTR (Milieu_base) protected
Member Data Documentation
diviser_
bool Champ_Generique_modifier_pour_QC::diviser_ = false protected
Referenced by get_champ(), and set_param().