CEA TRUST Platform: Loi_Etat_Multi_GP_QC Class Reference
Loi_Etat_Multi_GP_QC Class Reference
#include <Loi_Etat_Multi_GP_QC.h>
Public Member Functions
void associer_espece (const Convection_Diffusion_Espece_Multi_QC &eq)
Public Member Functions inherited from Loi_Etat_Multi_GP_base
virtual void associer_inconnue (const Champ_Inc_base &inconnue)
Public Member Functions inherited from Loi_Etat_Melange_GP_base
void associer_fluide (const Fluide_Dilatable_base &) override
Public Member Functions inherited from Loi_Etat_GP_base
void remplir_T () override
const Nom type_fluide () const override
Public Member Functions inherited from Loi_Etat_base
void assoscier_probleme (const Probleme_base &pb)
void mettre_a_jour (double)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
See also
Fluide_Dilatable_base Loi_Etat_base Loi_Etat_Multi_GP_base
Constructor & Destructor Documentation
Loi_Etat_Multi_GP_QC()
Loi_Etat_Multi_GP_QC::Loi_Etat_Multi_GP_QC ()
Member Function Documentation
associer_espece()
void Loi_Etat_Multi_GP_QC::associer_espece (const Convection_Diffusion_Espece_Multi_QC & eq)
Associe les proprietes physiques d une espece a la loi d'etat.
Parameters
(eq)
References Convection_Diffusion_Espece_Multi_QC::espece().
Referenced by Convection_Diffusion_Espece_Multi_QC::completer().
calculer_masse_molaire()
void Loi_Etat_Multi_GP_QC::calculer_masse_molaire (DoubleTab & M) const override virtual
Calcule la masse molaire du melange (M) M depend de la mase molaire de chaque espece et de la composition du melange (Yi)
Implements Loi_Etat_Multi_GP_base.
References dtol_fraction_, Process::exit(), ignore_check_fraction_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
calculer_tab_Cp()
void Loi_Etat_Multi_GP_QC::calculer_tab_Cp (DoubleTab & cp) const override virtual
Calcule le Cp du melange Le Cp depend du Cp de chaque espece et de la composition du melange (Yi)
Implements Loi_Etat_Multi_GP_base.
References TRUSTVect< _TYPE_, _SIZE_ >::size().
calculer_masse_volumique() [1/3]
void Loi_Etat_Multi_GP_QC::calculer_masse_volumique () override virtual
Recalcule la masse volumique.
Implements Loi_Etat_Multi_GP_base.
References Loi_Etat_Multi_GP_base::calculer_masse_molaire(), calculer_masse_volumique(), correction_fraction_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Loi_Etat_Multi_GP_base::masse_mol_mel, rabot(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Loi_Etat_base::tab_rho_n, Loi_Etat_base::tab_rho_np1, Champ_Proto::valeurs(), and Debog::verifier().
Referenced by calculer_masse_volumique(), EDO_Pression_th_VDF::masse_totale(), and EDO_Pression_th_VEF::masse_totale().
calculer_mu_sur_Sc()
void Loi_Etat_Multi_GP_QC::calculer_mu_sur_Sc () override virtual
Calcule la viscosite dynamique sur Schmidt.
Reimplemented from Loi_Etat_base.
References Champ_base::changer_temps(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Sc_, TRUSTVect< _TYPE_, _SIZE_ >::size(), Champ_base::temps(), and Champ_Don_base::valeurs().
calculer_masse_volumique() [2/3]
double Loi_Etat_Multi_GP_QC::calculer_masse_volumique (double P, double T) const override virtual
Reimplemented from Loi_Etat_Multi_GP_base.
References Loi_Etat_Multi_GP_base::calculer_masse_volumique().
calculer_masse_volumique() [3/3]
double Loi_Etat_Multi_GP_QC::calculer_masse_volumique (double P, double T, double r) const override virtual
Reimplemented from Loi_Etat_Multi_GP_base.
References Loi_Etat_Multi_GP_base::calculer_masse_volumique().
rabot()
void Loi_Etat_Multi_GP_QC::rabot (int futur = 0) protected
Corrections explicites pour les fractions massiques pour forcer la somme a 1 et sans valeurs negatives.
References dtol_fraction_, Process::exit(), ignore_check_fraction_, and TRUSTVect< _TYPE_, _SIZE_ >::size().
Referenced by calculer_masse_volumique().
LIST()
Loi_Etat_Multi_GP_QC::LIST (OBS_PTR(Espece)) protected
References Loi_Etat_base::OBS_PTR().
Member Data Documentation
correction_fraction_
bool Loi_Etat_Multi_GP_QC::correction_fraction_ = false protected
Referenced by calculer_masse_volumique().
ignore_check_fraction_
bool Loi_Etat_Multi_GP_QC::ignore_check_fraction_ = false protected
Referenced by calculer_masse_molaire(), and rabot().
Sc_
double Loi_Etat_Multi_GP_QC::Sc_ protected
Referenced by calculer_mu_sur_Sc().
dtol_fraction_
double Loi_Etat_Multi_GP_QC::dtol_fraction_ protected
Referenced by calculer_masse_molaire(), and rabot().