CEA TRUST Platform: Liste_bloc Class Reference
Liste_bloc Class Reference
#include <Liste_bloc.h>
Public Member Functions
Liste_bloc & dernier ()
Objet_U & operator[] (int)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Constructor & Destructor Documentation
Liste_bloc()
Liste_bloc::Liste_bloc () inline
References suivant_.
Referenced by add_deplace().
~Liste_bloc()
Liste_bloc::~Liste_bloc () override
References suivant_, and vide().
Member Function Documentation
est_vide()
int Liste_bloc::est_vide () const inline
References suivant_.
Referenced by add_deplace(), est_dernier(), Liste_bloc_curseur::Liste_bloc_curseur(), and vide().
valeur() [1/2]
Objet_U & Liste_bloc::valeur () inline
References data, and TRUST_Deriv_Objet_U::valeur().
Referenced by add_deplace(), Interprete_bloc::interprete_courant(), Interprete_bloc::objet_global(), Interprete_bloc::objet_global_existant(), operator->(), and operator->().
valeur() [2/2]
const Objet_U & Liste_bloc::valeur () const inline
References data, and TRUST_Deriv_Objet_U::valeur().
est_dernier()
int Liste_bloc::est_dernier () const inline
References est_vide(), and suivant_.
Referenced by add_deplace(), and dernier().
operator->() [1/2]
Objet_U * Liste_bloc::operator-> () inline
References valeur().
operator->() [2/2]
const Objet_U * Liste_bloc::operator-> () const inline
References valeur().
suivant() [1/2]
const Liste_bloc & Liste_bloc::suivant () const inline
References suivant_.
suivant() [2/2]
Liste_bloc & Liste_bloc::suivant () inline
References suivant_.
operator[]()
Objet_U & Liste_bloc::operator[] (int i)
Operateur d'acces au ieme element de la liste.
Parameters
(int i) l'indice de l'element a trouver
Returns
(Objet_U&) le ieme element de la liste
References Process::exit(), Objet_U::que_suis_je(), and Liste_bloc_curseur::valeur().
Referenced by Interprete_bloc::objet_local().
add_deplace()
Objet_U & Liste_bloc::add_deplace (DerObjU & to_add)
Ajout d'un Objet_U a la liste to_add est libere en sortie.
References add_deplace(), data, TRUST_Deriv_Objet_U::deplace(), dernier(), est_dernier(), est_vide(), Process::exit(), Liste_bloc(), suivant_, and valeur().
Referenced by add_deplace(), and Interprete_bloc::ajouter().
vide()
void Liste_bloc::vide ()
Vide la liste.
References data, est_vide(), and suivant_.
Referenced by ~Liste_bloc(), and mon_main::~mon_main().
dernier()
Liste_bloc & Liste_bloc::dernier ()
Renvoie le dernier element de la liste.
Returns
(Liste_bloc&) le dernier element de la liste
References est_dernier(), and Liste_bloc_curseur::list().
Referenced by add_deplace().
Member Data Documentation
data
DerObjU Liste_bloc::data protected
Referenced by add_deplace(), valeur(), valeur(), and vide().
suivant_
Liste_bloc* Liste_bloc::suivant_ = nullptr protected
Referenced by add_deplace(), est_dernier(), est_vide(), Liste_bloc(), suivant(), suivant(), vide(), and ~Liste_bloc().