CEA TRUST Platform: Terme_Source_Acceleration Class Reference
Terme_Source_Acceleration Class Reference abstract
Public Member Functions
int a_pour_Champ_Fonc (const Motcle &mot, OBS_PTR(Champ_base) &ch_ref) const override
Public Member Functions inherited from Source_base
virtual void associer_champ_rho (const Champ_base &champ_rho)
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void dimensionner (Matrice_Morse &) const
virtual int initialiser (double temps)
virtual void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
virtual void resetTime (double t)
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
const DoubleTab & calculer_la_source (DoubleTab &src_faces) const
virtual void lire_data (Entree &s)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Constructor & Destructor Documentation
Terme_Source_Acceleration()
Terme_Source_Acceleration::Terme_Source_Acceleration ()
Member Function Documentation
associer_pb()
void Terme_Source_Acceleration::associer_pb (const Probleme_base & pb) override virtual
Implements Source_base.
calculer()
DoubleTab & Terme_Source_Acceleration::calculer (DoubleTab & resu) const override virtual
resu=0; ajouter(resu); (appel a ajouter() de la classe derivee)
Reimplemented from Source_base.
References Source_base::ajouter(), and TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel().
a_pour_Champ_Fonc()
int Terme_Source_Acceleration::a_pour_Champ_Fonc (const Motcle & mot, OBS_PTR(Champ_base) & ch_ref) const override virtual
Methode surchargee de Source_base.
Les mots compris sont: "ACCELERATION" => renvoie terme_source_post_, homogene a d/dt(rho*v) Attention a l'effet de bord de ajouter() (voir commentaires de ajouter())
Reimplemented from Source_base.
champ_vitesse()
const Champ_Don_base& Terme_Source_Acceleration::champ_vitesse () const inline
Referenced by Traitement_particulier_NS_EC::calculer_Ec().
has_champ_vitesse()
bool Terme_Source_Acceleration::has_champ_vitesse () const inline
Referenced by Traitement_particulier_NS_EC::calculer_Ec().
omega()
const Champ_Don_base& Terme_Source_Acceleration::omega () const inline
Referenced by Traitement_particulier_NS_EC::calculer_Ec().
has_omega()
bool Terme_Source_Acceleration::has_omega () const inline
Referenced by Traitement_particulier_NS_EC::calculer_Ec().
lire_data()
void Terme_Source_Acceleration::lire_data (Entree & s) protected virtual
Methode appelee par readOn des classes derivees Terme_Source_Acceleration_VDF_Face, .
..
Le format attendu est le suivant { [ omega Un_Champ_uniforme domegadt Un_Champ_uniforme centre_rotation Un_Champ_uniforme option TERME_COMPLET | CORIOLIS_SEUL | ENTRAINEMENT_SEUL ] [ acceleration Un_Champ_uniforme ] } Un_Champ_uniforme est typiquement: Champ_Uniforme 3 x y z ou Champ_Fonc_t DOM 3 fx(t) fy(t) fz(t)
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), Source_base::champs_compris_, Objet_U::dimension, Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), MorEqn::equation(), Process::exit(), Process::je_suis_maitre(), Equation_base::schema_temps(), Motcles::search(), and Schema_Temps_base::temps_courant().
get_terme_source_post()
const Champ_Fonc_base & Terme_Source_Acceleration::get_terme_source_post () const protected virtual
get_set_terme_source_post()
Champ_Fonc_base & Terme_Source_Acceleration::get_set_terme_source_post () const protected virtual
Referenced by Terme_Source_Acceleration_VEF_Face::ajouter(), Terme_Source_Acceleration_VDF_Face::ajouter_blocs(), and mettre_a_jour().
calculer_vitesse_faces()
virtual const DoubleTab& Terme_Source_Acceleration::calculer_vitesse_faces (DoubleTab & stockage) const protected pure virtual
Implemented in Terme_Source_Acceleration_VEF_Face, and Terme_Source_Acceleration_VDF_Face.
Referenced by calculer_la_source().
calculer_la_source()
const DoubleTab & Terme_Source_Acceleration::calculer_la_source (DoubleTab & acceleration_aux_faces) const protected
Calcul de la valeur du champ la_source aux faces en fonction de - calculer_vitesse_faces()
champ_acceleration_
omega_
domegadt_
centre_rotation_
Parameters
(champ_source) un champ discretise aux elements du domaine_VF dans lequel on stocke le resultat du calcul. Espace virtuel a jour.
References calculer_vitesse_faces(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, MorEqn::equation(), and Domaine_VF::xv().
Referenced by Terme_Source_Acceleration_VEF_Face::ajouter(), and Terme_Source_Acceleration_VDF_Face::ajouter_blocs().
get_eq_hydraulique()
const Navier_Stokes_std & Terme_Source_Acceleration::get_eq_hydraulique () const protected virtual
Renvoie eq_hydraulique_ !
References MorEqn::equation().
Referenced by Terme_Source_Acceleration_VDF_Face::calculer_vitesse_faces(), and Terme_Source_Acceleration_VEF_Face::calculer_vitesse_faces().
mettre_a_jour()
void Terme_Source_Acceleration::mettre_a_jour (double temps) override protected virtual
Evalue les champs d'acceleration et de rotation au temps t.
Reimplemented from Source_base.
References get_set_terme_source_post(), and Champ_Fonc_base::mettre_a_jour().