CEA TRUST Platform: Matrice33 Class Reference
Matrice33 Class Reference
Public Member Functions
double norme_Linfini ()
Static Public Member Functions
static double inverse (const Matrice33 &m, Matrice33 &resu, int exit_on_error=1)
Detailed Description
Convention pour m(i,j): i est l'indice de ligne, j l'indice de colonne entre 0 et 2 inclus. Attention: le constructeur par defaut n'initialise pas la matrice !
Constructor & Destructor Documentation
Matrice33() [1/3]
Matrice33::Matrice33 () inline
Matrice33() [2/3]
Matrice33::Matrice33 (double m00, double m01, double m02, double m10, double m11, double m12, double m20, double m21, double m22) inline
References m.
Matrice33() [3/3]
Matrice33::Matrice33 (const DoubleTab & tab) inline
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), m, and TRUSTTab< _TYPE_, _SIZE_ >::nb_dim().
Member Function Documentation
operator()() [1/2]
double Matrice33::operator() (int i, int j) const inline
References m.
operator()() [2/2]
double& Matrice33::operator() (int i, int j) inline
References m.
norme_Linfini()
double Matrice33::norme_Linfini () inline
calcul de la norme Linfini de la matrice Propriete: on note |x| la norme Linfini de x (vecteur ou matrice)
On a |m * x| <= |m| * |x| En pratique: c'est le max sur j de la somme sur i de std::fabs(m(i,j))
References m.
produit()
void Matrice33::produit (const Matrice33 & m, const Vecteur3 & x, Vecteur3 & y) inline static
produit avec de la matrice avec le vecteur x.
References Vecteur3::init(), m, and Vecteur3::v.
produit_matriciel()
void Matrice33::produit_matriciel (const Matrice33 & m1, const Matrice33 & m2, Matrice33 & res) inline static
References init(), and m.
transpose()
void Matrice33::transpose (const Matrice33 & matrice, Matrice33 & matrice_transpose) inline static
References m.
inverse()
double Matrice33::inverse (const Matrice33 & matrice, Matrice33 & matrice_inv, int exit_on_error = 1) inline static
calcul de l'inverse.
Si le determinant de "matrice" est nul, exit() si exit_on_error (valeur par defaut) sinon on ne remplit pas matrice_inv et on renvoie 0. Valeur de retour: determinant de la "matrice" (pas de l'inverse !)
References Process::exit(), and m.
Referenced by Op_Diff_PolyMAC_P0P1NC_Face::ajouter_blocs_ext(), Op_Diff_PolyMAC_P0P1NC_Face::dimensionner_blocs_ext(), Champ_Face_PolyMAC::init_va(), Champ_Face_PolyMAC_P0::init_ve2(), and Domaine_PolyMAC::W_stabiliser().
init()
void Matrice33::init () inline protected
References m.
Referenced by produit_matriciel().
Member Data Documentation
m
double Matrice33::m[3][3] protected
Referenced by init(), inverse(), Matrice33(), norme_Linfini(), operator()(), produit(), produit_matriciel(), and transpose().