CEA TRUST Platform: Format_Post_base Class Reference
Format_Post_base Class Reference abstract
Public Member Functions
virtual int ecrire_champ (const Domaine &domaine, const Noms &unite_, const Noms &noms_compo, int ncomp, double temps_, const Nom &id_du_champ, const Nom &id_du_domaine, const Nom &localisation, const Nom &nature, const DoubleTab &data)
virtual int ecrire_domaine (const Domaine &domaine, const int est_le_premier_post)
virtual int ecrire_item_int (const Nom &id_item, const Nom &id_du_domaine, const Nom &id_domaine, const Nom &localisation, const Nom &reference, const IntVect &data, const int reference_size)
virtual int ecrire_temps (const double temps)
virtual int initialize_by_default (const Nom &file_basename)
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Utilisation de la classe par l'interface generique: -typer un objet format de postraitement -initialiser l objet format de postraitement -proceder a des operations de complement et verification -ecrire un domaine -ecrire_temps -ecrire_champ (un type de champ supporte: aux elements ou aux sommets, ou encore aux faces si on a ecrit les faces du domaine et si les faces sont supportees par le postraitement)
Member Function Documentation
reset()
virtual void Format_Post_base::reset () pure virtual
Implemented in Format_Post_Lml, Format_Post_Lata, Format_Post_Med, and Format_Post_CGNS.
resetTime()
void Format_Post_base::resetTime (double t, const std::string dirname) virtual
Reimplemented in Format_Post_Lata.
References Process::exit(), and Objet_U::que_suis_je().
set_param()
virtual void Format_Post_base::set_param (Param & param) pure virtual
Implemented in Format_Post_Lml, Format_Post_Lata, Format_Post_Med, and Format_Post_CGNS.
lire_motcle_non_standard()
int Format_Post_base::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Objet_U.
Reimplemented in Format_Post_Lata.
initialize_by_default()
int Format_Post_base::initialize_by_default (const Nom & file_basename) virtual
Initialise le fichier avec des parametres appropries pour son format (exemple: format ascii, efface le fichier existant, un.
fichier unique pour tous les processeurs etc...) Methode a surcharger dans les classes derivees. Valeur de retour: 1 si l'operation a reussi, 0 sinon.
Reimplemented in Format_Post_Lml, Format_Post_Lata, Format_Post_Med, and Format_Post_CGNS.
References Objet_U::que_suis_je().
Referenced by Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), and Lata_2_Other::interpreter().
initialize()
int Format_Post_base::initialize (const Nom & file_basename, const int format, const Nom & option_para) virtual
Reimplemented in Format_Post_Lml, Format_Post_Lata, Format_Post_Med, and Format_Post_CGNS.
References Objet_U::que_suis_je().
Referenced by Postraiter_domaine::ecrire(), and Lata_2_Other::interpreter().
modify_file_basename()
int Format_Post_base::modify_file_basename (const Nom file_basename, bool for_restart, const double tinit) virtual
Modification of the post processing file name. For save/restart this might also move and rename files around to avoid overriding existing files.
Reimplemented in Format_Post_Lata.
ecrire_entete()
int Format_Post_base::ecrire_entete (const double temps_courant, const int reprise, const int est_le_premier_post) virtual
Reimplemented in Format_Post_CGNS, Format_Post_Lml, Format_Post_Lata, and Format_Post_Med.
References Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::interpreter(), and Lata_2_Other::interpreter().
completer_post()
int Format_Post_base::completer_post (const Domaine & dom, const int axi, const Nature_du_champ & nature, const int nb_compo, const Noms & noms_compo, const Motcle & loc_post, const Nom & le_nom_champ_post) virtual
Reimplemented in Format_Post_Lml, Format_Post_Lata, Format_Post_Med, and Format_Post_CGNS.
References Objet_U::que_suis_je().
Referenced by Champ_base::completer_post_champ().
preparer_post()
int Format_Post_base::preparer_post (const Nom & id_du_domaine, const int est_le_premier_post, const int reprise, const double t_init) virtual
Reimplemented in Format_Post_Lml, Format_Post_Lata, Format_Post_Med, and Format_Post_CGNS.
References Objet_U::que_suis_je().
Referenced by Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), and Lata_2_Other::interpreter().
init_ecriture()
int Format_Post_base::init_ecriture (double temps_courant, double temps_post, int est_le_premier_postraitement_pour_nom_fich_, const Domaine & domaine) virtual
Referenced by Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), and Lata_2_Other::interpreter().
finir_ecriture()
int Format_Post_base::finir_ecriture (double temps_courant) virtual
Reimplemented in Format_Post_CGNS.
finir()
int Format_Post_base::finir (const int est_le_dernier_post) virtual
Reimplemented in Format_Post_CGNS, Format_Post_Lml, Format_Post_Lata, and Format_Post_Med.
References Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::interpreter(), and Lata_2_Other::interpreter().
ecrire_domaine()
int Format_Post_base::ecrire_domaine (const Domaine & domaine, const int est_le_premier_post) virtual
Ecriture d'un maillage.
L'ecriture du domaine a lieu soit au debut, avant le premier appel a ecrire_temps, soit plus tard (maillage dynamique), mais ce n'est pas forcement supporte par le postraitement.
Parameters
(id_domaine) le nom affecte au domaine dans le fichier lata.
(type_elem) le type de l'element geometrique (un type supporte par la classe derivee, en general on comprend au moins "TETRAEDRE", "HEXAEDRE", "TRIANGLE" et "RECTANGLE")
(dimension) la dimension du domaine (nombre de coordonnees des sommets) On peut avoir un domaine de dimension 3 et des elements de type triangle (postraitement d'une interface ou du bord d'un domaine volumique).
(sommets) Coordonnees des sommets. S'il n'est pas vide, il faut que dimension(1)==dimension
(elements) Indices des sommets de chaque element. dimension(1) doit correspondre au type de l'element (3 pour un triangle, 4 pour un rectangle ou un tetraedre, etc...)
Reimplemented in Format_Post_Lata, Format_Post_Med, Format_Post_Lml, and Format_Post_CGNS.
References Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), ecrire_domaine_dis(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::interpreter(), and Lata_2_Other::interpreter().
ecrire_domaine_dual()
void Format_Post_base::ecrire_domaine_dual (const Domaine & domaine, const int est_le_premier_post) virtual
Reimplemented in Format_Post_Med, and Format_Post_CGNS.
References Process::exit(), and Objet_U::que_suis_je().
Referenced by Postraiter_domaine::ecrire().
ecrire_domaine_dis()
int Format_Post_base::ecrire_domaine_dis (const Domaine & domaine, const OBS_PTR(Domaine_dis_base)& domaine_dis_base, const int est_le_premier_post) virtual
Reimplemented in Format_Post_Med, and Format_Post_CGNS.
References ecrire_domaine().
Referenced by Postraiter_domaine::ecrire().
ecrire_temps()
int Format_Post_base::ecrire_temps (const double temps) virtual
Commence l'ecriture d'un pas de temps.
La classe derivee doit accepter de recevoir plusieurs appels consecutifs a cette methode avec le meme temps.
Reimplemented in Format_Post_CGNS, Format_Post_Lml, Format_Post_Lata, and Format_Post_Med.
References Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), Moyenne_volumique::interpreter(), and Lata_2_Other::interpreter().
ecrire_champ()
int Format_Post_base::ecrire_champ (const Domaine & domaine, const Noms & unite_, const Noms & noms_compo, int ncomp, double temps_, const Nom & id_du_champ, const Nom & id_du_domaine, const Nom & localisation, const Nom & nature, const DoubleTab & data) virtual
Ecriture d'un champ dans le fichier de postraitement.
Parameters
(id_du_champ) identifiant du champ (permet d'identifier un champ unique si on donne en plus un numero de pas de temps)
(id_du_domaine) identifiant du domaine sur lequel le champ est defini Ce domaine doit avoir ete ecrit avant par "ecrire_domaine".
(localisation) localisation des valeurs du champ (SOMMETS, ELEMENTS, ou tout autre id. de tableau deja ecrit) (tout n'est pas obligatoirement supporte par tous les postraitements)
(data) tableau de valeurs a postraiter. Le nombre de lignes du tableau doit etre egal au nombre de lignes du tableau "localisation" (nombre de sommets, d'elements ou de faces ou autre). Valeur de retour: 1 si operation reussie, 0 sinon (par exemple, preconditions non remplies ou fonctionnalite non supportee par le format).
Reimplemented in Format_Post_Lml, Format_Post_Lata, Format_Post_Med, and Format_Post_CGNS.
References Objet_U::que_suis_je().
Referenced by Corriger_frontiere_periodique_32_64< _SIZE_ >::corriger_coordonnees_sommets_perio(), Postraiter_domaine::ecrire(), Ecrire_Champ_MED::interpreter(), Lata_2_Other::interpreter(), and Moyenne_volumique::traiter_champs().
ecrire_item_int()
int Format_Post_base::ecrire_item_int (const Nom & id_item, const Nom & id_du_domaine, const Nom & id_domaine, const Nom & localisation, const Nom & reference, const IntVect & data, const int reference_size) virtual
Ecriture d'un tableau d'entiers dans le fichier de postraitement.
See also
ecrire_champ
Parameters
(reference) Nom d'un autre tableau deja ecrit. data[i] est un indice dans ce tableau (exemple: on peut ecrire le tableau FACES_VOISINS, localisation=FACES, reference=ELEMENTS car le tableau est indexe par un numero de face et contient des indices d'elements) L'ecriture d'un domaine entraine automatiquement l'existence d'une tableau SOMMETS et d'un tableau ELEMENTS
(reference_size) la taille (locale) du tableau cite en reference (dimension(0) du tableau). Cette dimension est utilisee pour renumeroter le contenu du tableau data afin de creer une numerotation globale lorsque tous les processeurs ecrivent dans un fichier unique.
Reimplemented in Format_Post_Lml, Format_Post_Lata, Format_Post_Med, and Format_Post_CGNS.
References Objet_U::que_suis_je().
set_single_lata_option()
virtual void Format_Post_base::set_single_lata_option (const bool) inline virtual
Reimplemented in Format_Post_Lata.
Referenced by Postraiter_domaine::ecrire().
set_postraiter_domain()
virtual void Format_Post_base::set_postraiter_domain () inline virtual
Reimplemented in Format_Post_CGNS.
Referenced by Postraiter_domaine::ecrire().
set_deformable_domain()
virtual void Format_Post_base::set_deformable_domain () inline virtual
Reimplemented in Format_Post_CGNS.
set_loc_vector()
virtual void Format_Post_base::set_loc_vector (const std::vector< std::string > &) inline virtual
Reimplemented in Format_Post_CGNS.
Referenced by Lata_2_Other::get_fill_infos_loc().
OBS_PTR()
Format_Post_base::OBS_PTR (Domaine_dis_base) protected
Reference to the discretized domain - used for face fields.
Referenced by Format_Post_CGNS::ecrire_domaine(), Format_Post_Med::ecrire_domaine(), and Format_Post_Lata::ecrire_domaine().