CEA TRUST Platform: Masse_PolyMAC_base Class Reference
Masse_PolyMAC_base Class Reference
Additional Inherited Members
Public Member Functions inherited from Solveur_Masse_base
virtual DoubleTab & appliquer (DoubleTab &) const
virtual void assembler ()
virtual void mettre_a_jour (double temps)
virtual void resetTime (double temps)
void set_name_of_coefficient_temporel (const Nom &)
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer_domaine_dis_base()
void Masse_PolyMAC_base::associer_domaine_dis_base (const Domaine_dis_base & le_dom_dis_base) override virtual
Implements Solveur_Masse_base.
associer_domaine_cl_dis_base()
void Masse_PolyMAC_base::associer_domaine_cl_dis_base (const Domaine_Cl_dis_base & le_dom_Cl_dis_base) override virtual
Implements Solveur_Masse_base.
completer()
void Masse_PolyMAC_base::completer () override virtual
Reimplemented from Solveur_Masse_base.
Reimplemented in Masse_PolyMAC_P0P1NC_Face, Masse_PolyMAC_P0_Face, and Masse_PolyMAC_P0P1NC_base.
References MorEqn::equation(), Process::exit(), no_diff_, Equation_base::nombre_d_operateurs(), Objet_U::que_suis_je(), and Equation_base::schema_temps().
appliquer_coef()
void Masse_PolyMAC_base::appliquer_coef (DoubleVect & coef) const
References MorEqn::equation(), Equation_base::get_champ(), Solveur_Masse_base::has_coefficient_temporel_, Equation_base::inconnue(), Solveur_Masse_base::name_of_coefficient_temporel_, OBS_PTR(), TRUSTTab< _TYPE_, _SIZE_ >::ref(), Champ_Inc_base::remplir_coord_noeuds(), Champ_Don_base::valeurs(), and Champ_Inc_base::valeurs().
Referenced by Masse_PolyMAC_Elem::ajouter_masse(), and Masse_PolyMAC_Face::ajouter_masse().
OBS_PTR() [1/2]
Masse_PolyMAC_base::OBS_PTR (Domaine_PolyMAC) protected
Referenced by appliquer_coef().
OBS_PTR() [2/2]
Masse_PolyMAC_base::OBS_PTR (Domaine_Cl_PolyMAC) protected
Member Data Documentation
no_diff_
bool Masse_PolyMAC_base::no_diff_ = false protected
Referenced by Masse_PolyMAC_Elem::ajouter_masse(), Masse_PolyMAC_Face::ajouter_masse(), completer(), Masse_PolyMAC_Elem::dimensionner(), and Masse_PolyMAC_Face::dimensionner().