CEA TRUST Platform: Champ_Generique_Moyenne Class Reference
Champ_Generique_Moyenne Class Reference
#include <Champ_Generique_Moyenne.h>
Public Member Functions
const Noms get_property (const Motcle &query) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Champ_Gen_de_Champs_Gen
void get_copy_domain (Domaine &) const override
void get_copy_values (DoubleTab &) const override
int get_dimension () const override
Entity get_localisation (const int index=-1) const override
const IntTab & get_ref_connectivity (Entity index1, Entity index2) const override
const DoubleTab & get_ref_coordinates () const override
const Domaine & get_ref_domain () const override
const Domaine_dis_base & get_ref_domaine_dis_base () const override
const DoubleTab & get_ref_values () const override
void get_xyz_values (const DoubleTab &coords, DoubleTab &values, ArrOfBit &validity_flag) const override
Public Member Functions inherited from Champ_Generique_base
void nommer (const Nom &nom) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
La classe porte un operateur statistique "Op_Moyenne"
Member Function Documentation
set_param()
void Champ_Generique_Moyenne::set_param (Param & param) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Param::ajouter_non_std(), and Champ_Generique_Statistiques_base::set_param().
lire_motcle_non_standard()
int Champ_Generique_Moyenne::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Gen_de_Champs_Gen::lire_motcle_non_standard(), and Operateur_Statistique().
get_property()
const Noms Champ_Generique_Moyenne::get_property (const Motcle & query) const override virtual
Renvoie la propriete demandee.
Exemples: "DISCRETISATION" : type du champ discret (P0, P1, P1NC, etc...) "ELEMENT_TYPE" : type de l'element de plus grande dimension ({TRIANGLE}, {TETRAHEDRA}, {QUAD}, {HEXA}, etc) "DYNAMIC_MESH" : le maillage est-il dynamique ou pas ({STATIC}, {DYNAMIC}) "NAME" : nom du champ "COMPONENT_NAMES" : nom des composantes du champ ({K,EPSILON} ou {VITESSE_X,VITESSE_Y,VITESSE_Z}) "BOUNDARY_NAMES" : nom des bords "COORDINATES" : systeme de coordonnees des noeuds ({X}, {X,Y}, {X,Y,Z}, {R,THETA}, etc...) Exceptions:
GenericFieldError::INVALID : query non comprise
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Gen_de_Champs_Gen::nb_comp, Champ_Generique_base::nom_post_, and Motcles::search().
temps()
double Champ_Generique_Moyenne::temps () const inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Moyenne::integrale(), Integrale_tps_Champ::le_champ_calcule(), Op_Moyenne_, and Champ_base::temps().
Referenced by get_champ().
integrale()
const Integrale_tps_Champ & Champ_Generique_Moyenne::integrale () const inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Moyenne::integrale(), and Op_Moyenne_.
Referenced by get_champ(), and get_champ_without_evaluation().
Operateur_Statistique() [1/2]
const Operateur_Statistique_tps_base & Champ_Generique_Moyenne::Operateur_Statistique () const inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Moyenne_.
Referenced by lire_motcle_non_standard().
Operateur_Statistique() [2/2]
Operateur_Statistique_tps_base & Champ_Generique_Moyenne::Operateur_Statistique () inline override virtual
Implements Champ_Generique_Statistiques_base.
References Op_Moyenne_.
completer()
void Champ_Generique_Moyenne::completer (const Postraitement_base & post) override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Op_Moyenne::associer(), Champ_Gen_de_Champs_Gen::completer(), Op_Moyenne::completer(), Champ_Gen_de_Champs_Gen::get_ref_domaine_dis_base(), Champ_Gen_de_Champs_Gen::get_ref_pb_base(), Champ_Gen_de_Champs_Gen::get_source(), Probleme_U::le_nom(), Postraitement_base::le_nom(), Op_Moyenne_, Champ_Gen_de_Champs_Gen::parent_name_, Champ_Generique_Statistiques_base::tstat_deb_, Champ_Generique_Statistiques_base::tstat_fin_, and Champ_Generique_Statistiques_base::use_source_name_only_.
get_champ_without_evaluation()
const Champ_base & Champ_Generique_Moyenne::get_champ_without_evaluation (OWN_PTR(Champ_base)& espace_stockage) const override virtual
Implements Champ_Generique_base.
References integrale(), Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), and Champ_Generique_base::OBS_PTR().
get_champ()
const Champ_base & Champ_Generique_Moyenne::get_champ (OWN_PTR(Champ_base)& espace_stockage) const override
References Op_Moyenne::calculer_valeurs(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), integrale(), Field_base::nature_du_champ(), Champ_Gen_de_Champs_Gen::nb_comp, Field_base::nb_comp(), Champ_Generique_base::OBS_PTR(), Op_Moyenne_, and temps().
nommer_source()
void Champ_Generique_Moyenne::nommer_source () override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_base::nom_post_, and Champ_Generique_base::nommer().
get_champ_post()
const Champ_Generique_base & Champ_Generique_Moyenne::get_champ_post (const Motcle & nom) const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Gen_de_Champs_Gen::get_champ_post(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Nom::getString(), Champ_Gen_de_Champs_Gen::has_champ_post(), Champ_Generique_base::OBS_PTR(), Champ_Generique_Statistiques_base::tstat_deb_, and Champ_Generique_Statistiques_base::tstat_fin_.
has_champ_post()
bool Champ_Generique_Moyenne::has_champ_post (const Motcle & nom) const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Gen_de_Champs_Gen::has_champ_post(), Champ_Generique_Statistiques_base::tstat_deb_, and Champ_Generique_Statistiques_base::tstat_fin_.
comprend_champ_post()
int Champ_Generique_Moyenne::comprend_champ_post (const Motcle & identifiant) const override virtual
Reimplemented from Champ_Gen_de_Champs_Gen.
References Champ_Gen_de_Champs_Gen::comprend_champ_post(), Champ_Generique_base::get_property(), Champ_Gen_de_Champs_Gen::get_source(), Champ_Generique_Statistiques_base::tstat_deb_, and Champ_Generique_Statistiques_base::tstat_fin_.
Member Data Documentation
Op_Moyenne_
Op_Moyenne Champ_Generique_Moyenne::Op_Moyenne_ protected
Referenced by completer(), get_champ(), integrale(), Operateur_Statistique(), Operateur_Statistique(), and temps().