CEA TRUST Platform: Domaine_Cl_VEF Class Reference
Domaine_Cl_VEF Class Reference
Public Member Functions
int initialiser (double temps) override
void remplir_normales_facettes_Cl (const Domaine_VEF &)
Public Member Functions inherited from Domaine_Cl_dis_base
virtual int calculer_coeffs_echange (double temps)
const Cond_lim_base & condition_limite_de_la_face_reelle (int face_globale, int &face_locale) const
const Cond_lim_base & condition_limite_de_la_face_virtuelle (int face_globale, int &face_locale) const
Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere)
const Cond_lim_base & condition_limite_de_la_frontiere (Nom frontiere) const
int contient_Cl (const Nom &)
Domaine_dis_base & domaine_dis ()
const Domaine_dis_base & domaine_dis () const
virtual const Cond_lim & la_cl_de_la_face (int num_face) const
const Nom & le_nom () const override
Conds_lim & les_conditions_limites ()
const Conds_lim & les_conditions_limites () const
Cond_lim & les_conditions_limites (int)
const Cond_lim & les_conditions_limites (int) const
virtual void mettre_a_jour (double temps)
virtual void mettre_a_jour_ss_pas_dt (double temps)
int nb_cond_lim () const
void nommer (const Nom &nom) override
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Member Function Documentation
associer()
void Domaine_Cl_VEF::associer (const Domaine_dis_base & dom_dis) override virtual
Reimplemented from Domaine_Cl_dis_base.
References Domaine_VF::creer_tableau_faces(), Domaine_VEF::nb_faces_non_std(), Elem_VEF_base::nb_facette(), and Domaine_VEF::type_elem().
completer()
void Domaine_Cl_VEF::completer (const Domaine_dis_base & un_domaine_dis) override virtual
remplissage des tableaux
Implements Domaine_Cl_dis_base.
References Process::exit(), remplir_normales_facettes_Cl(), remplir_type_elem_Cl(), and remplir_volumes_entrelaces_Cl().
initialiser()
int Domaine_Cl_VEF::initialiser (double temps) override virtual
Initialise les CLs Contrairement aux methodes mettre_a_jour, les methodes.
initialiser des CLs ne peuvent pas dependre de l'exterieur (lui-meme peut ne pas etre initialise)
Returns
(int) 1 si OK, 0 sinon
Reimplemented from Domaine_Cl_dis_base.
References Domaine_Cl_dis_base::domaine_dis(), Periodique::face_associee(), Domaine_VF::front_VF(), Domaine_Cl_dis_base::initialiser(), Domaine_Cl_dis_base::les_conditions_limites_, modif_perio_fait_, nb_bord_periodicite(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), remplir_volumes_entrelaces_Cl(), Domaine_VF::volumes_entrelaces(), and volumes_entrelaces_Cl_.
imposer_cond_lim()
void Domaine_Cl_VEF::imposer_cond_lim (Champ_Inc_base & ch, double temps) override virtual
Impose les conditions aux limites a la valeur temporelle "temps" du Champ_Inc.
Implements Domaine_Cl_dis_base.
References Objet_U::dimension, Domaine_Cl_dis_base::domaine_dis(), domaine_vef(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), MorEqn::equation(), Process::exit(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Cond_lim_base::frontiere_dis(), Domaine_VEF::get_alphaS(), Domaine_VEF::get_cl_pression_sommet_faible(), Domaine_Cl_dis_base::les_conditions_limites(), Field_base::nature_du_champ(), Field_base::nb_comp(), Domaine_Cl_dis_base::nb_cond_lim(), Front_VF::nb_faces(), Front_VF::nb_faces_tot(), Domaine_dis_base::nb_som_tot(), Front_VF::num_face(), Front_VF::num_premiere_face(), Domaine_VEF::numero_premier_sommet(), Objet_U::que_suis_je(), Dirichlet::tab_val_imp(), and Champ_Inc_base::valeurs().
remplir_volumes_entrelaces_Cl()
void Domaine_Cl_VEF::remplir_volumes_entrelaces_Cl (const Domaine_VEF & le_dom_VEF) virtual
appele par completer() : remplissage de type_elem_Cl_ et volumes_entrelaces_Cl_
References Domaine_dis_base::domaine(), MorEqn::equation(), Domaine_VF::face_voisins(), Domaine_VF::front_VF(), Frontiere_dis_base::frontiere(), Domaine_VEF::get_alphaA(), Domaine_VEF::get_alphaE(), Domaine_VEF::get_alphaS(), Frontiere_32_64< _SIZE_ >::get_faces_virt(), Domaine_VEF::get_modif_div_face_dirichlet(), Domaine_Cl_dis_base::les_conditions_limites_, Elem_VEF_base::modif_volumes_entrelaces(), Elem_VEF_base::modif_volumes_entrelaces_faces_joints(), Domaine_32_64< _SIZE_ >::nb_elem_tot(), Front_VF::nb_faces(), Domaine_VEF::nb_faces_non_std(), Front_VF::num_premiere_face(), Domaine_VEF::rang_elem_non_std(), TRUSTArray< _TYPE_, _SIZE_ >::size_array(), Domaine_VEF::type_elem(), type_elem_Cl(), Domaine_VF::volumes_entrelaces(), volumes_entrelaces_Cl(), and volumes_entrelaces_Cl_.
Referenced by completer(), and initialiser().
remplir_normales_facettes_Cl()
void Domaine_Cl_VEF::remplir_normales_facettes_Cl (const Domaine_VEF & le_dom_VEF)
appele par completer() : remplissage de normales_facettes_Cl_ et vecteur_face_caette_Cl_
CHANGER LE NOM
References Elem_VEF_base::calcul_xg(), Domaine_32_64< _SIZE_ >::coord_sommets(), Elem_VEF_base::creer_normales_facettes_Cl(), Objet_U::dimension, Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Elem_VEF_base::KEL(), Domaine_32_64< _SIZE_ >::les_elems(), Elem_VEF_base::modif_normales_facettes_Cl(), Domaine_32_64< _SIZE_ >::nb_elem(), Elem_VEF_base::nb_facette(), Domaine_32_64< _SIZE_ >::nb_som_elem(), normales_facettes_Cl(), normales_facettes_Cl_, Domaine_VEF::rang_elem_non_std(), Domaine_VEF::type_elem(), type_elem_Cl_, vecteur_face_facette_Cl_, and Domaine_VF::xv().
Referenced by completer().
remplir_vecteur_face_facette_Cl()
void Domaine_Cl_VEF::remplir_vecteur_face_facette_Cl (const Domaine_VEF &)
volumes_entrelaces_Cl() [1/4]
DoubleVect& Domaine_Cl_VEF::volumes_entrelaces_Cl () inline
References volumes_entrelaces_Cl_.
Referenced by Masse_VEF_P1NC::appliquer_impl(), Op_Conv_VEF_base::calculer_dt_local(), Op_Conv_VEF_base::calculer_dt_stab(), Op_Conv_VEF_base::calculer_pour_post(), Champ_val_tot_sur_vol_VEF::eval_contrib_loc(), Iterateur_Source_VEF_Face< _TYPE_ >::remplir_volumes_cl_dirichlet(), and remplir_volumes_entrelaces_Cl().
volumes_entrelaces_Cl() [2/4]
const DoubleVect& Domaine_Cl_VEF::volumes_entrelaces_Cl () const inline
References volumes_entrelaces_Cl_.
volumes_entrelaces_Cl() [3/4]
const double& Domaine_Cl_VEF::volumes_entrelaces_Cl (int i) const inline
References volumes_entrelaces_Cl_.
volumes_entrelaces_Cl() [4/4]
double& Domaine_Cl_VEF::volumes_entrelaces_Cl (int i) inline
References volumes_entrelaces_Cl_.
normales_facettes_Cl() [1/4]
DoubleTab& Domaine_Cl_VEF::normales_facettes_Cl () inline
References normales_facettes_Cl_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Op_Conv_Muscl_old_VEF_Face::ajouter(), Op_Conv_VEF_Face::ajouter(), Op_Conv_Vort_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::remplir_fluent(), and remplir_normales_facettes_Cl().
normales_facettes_Cl() [2/4]
const DoubleTab& Domaine_Cl_VEF::normales_facettes_Cl () const inline
References normales_facettes_Cl_.
normales_facettes_Cl() [3/4]
const double& Domaine_Cl_VEF::normales_facettes_Cl (int num_poly, int num_fa7, int ncomp) const inline
References normales_facettes_Cl_.
normales_facettes_Cl() [4/4]
double& Domaine_Cl_VEF::normales_facettes_Cl (int num_poly, int num_fa7, int ncomp) inline
References normales_facettes_Cl_.
vecteur_face_facette_Cl() [1/2]
DoubleTab& Domaine_Cl_VEF::vecteur_face_facette_Cl () inline
References vecteur_face_facette_Cl_.
Referenced by Op_Conv_VEF_Face::ajouter().
vecteur_face_facette_Cl() [2/2]
const DoubleTab& Domaine_Cl_VEF::vecteur_face_facette_Cl () const inline
References vecteur_face_facette_Cl_.
type_elem_Cl() [1/2]
int Domaine_Cl_VEF::type_elem_Cl (int i) const inline
References type_elem_Cl_.
Referenced by Op_Conv_Amont_old_VEF_Face::ajouter(), Op_Conv_AmontNew_VEF_Face::ajouter(), Op_Conv_Centre_EF_VEF_Face::ajouter(), Op_Conv_Centre_old_VEF_Face::ajouter(), Op_Conv_DI_L2_VEF_Face::ajouter(), Op_Conv_kschemas_centre_VEF::ajouter(), Op_Conv_kschemas_VEF::ajouter(), Terme_Source_Qdm_VEF_Face::ajouter(), Op_Conv_Amont_old_VEF_Face::ajouter_contribution(), Op_Conv_VEF_Face::ajouter_contribution(), Op_Div_VEFP1B_Elem::ajouter_som(), Op_Grad_VEF_P1B_Face::calculer_coef_som(), Op_Conv_VEF_Face::completer(), and Op_Conv_VEF_Face::remplir_fluent().
type_elem_Cl() [2/2]
const IntVect& Domaine_Cl_VEF::type_elem_Cl () const inline
References type_elem_Cl_.
Referenced by remplir_volumes_entrelaces_Cl().
nb_faces_sortie_libre()
int Domaine_Cl_VEF::nb_faces_sortie_libre () const
References Domaine_Cl_dis_base::les_conditions_limites_, and Front_VF::nb_faces().
domaine_vef() [1/2]
Domaine_VEF & Domaine_Cl_VEF::domaine_vef ()
References Domaine_Cl_dis_base::domaine_dis().
Referenced by Champ_P1NC::calcul_duidxj_paroi(), Champ_P1NC::calcul_gradient(), Champ_P1NC::calcul_S_barre(), and imposer_cond_lim().
domaine_vef() [2/2]
const Domaine_VEF & Domaine_Cl_VEF::domaine_vef () const
References Domaine_Cl_dis_base::domaine_dis().
nb_bord_periodicite()
int Domaine_Cl_VEF::nb_bord_periodicite () const
References Domaine_Cl_dis_base::les_conditions_limites_.
Referenced by initialiser().
remplir_type_elem_Cl()
void Domaine_Cl_VEF::remplir_type_elem_Cl (const Domaine_VEF & le_dom_VEF) protected
appele par remplir_volumes_entrelaces_Cl() : remplissage de type_elem_Cl_
References Domaine_dis_base::domaine(), TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), Domaine_VF::elem_faces(), Process::exit(), Domaine_VF::face_voisins(), Domaine_VF::front_VF(), Domaine_Cl_dis_base::les_conditions_limites_, Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VEF::rang_elem_non_std(), Domaine_VEF::type_elem(), and type_elem_Cl_.
Referenced by completer().
Member Data Documentation
volumes_entrelaces_Cl_
DoubleVect Domaine_Cl_VEF::volumes_entrelaces_Cl_ protected
Referenced by initialiser(), remplir_volumes_entrelaces_Cl(), and volumes_entrelaces_Cl().
normales_facettes_Cl_
DoubleTab Domaine_Cl_VEF::normales_facettes_Cl_ protected
Referenced by normales_facettes_Cl(), and remplir_normales_facettes_Cl().
vecteur_face_facette_Cl_
DoubleTab Domaine_Cl_VEF::vecteur_face_facette_Cl_ protected
Referenced by remplir_normales_facettes_Cl(), and vecteur_face_facette_Cl().
type_elem_Cl_
IntVect Domaine_Cl_VEF::type_elem_Cl_ protected
Referenced by remplir_normales_facettes_Cl(), remplir_type_elem_Cl(), and type_elem_Cl().
modif_perio_fait_
int Domaine_Cl_VEF::modif_perio_fait_ = 0 protected
Referenced by initialiser().