CEA TRUST Platform: Champ_Fonc_Tabule Class Reference
Champ_Fonc_Tabule Class Reference
Public Member Functions
int initialiser (const double un_temps) override
const Champ_Fonc_base & le_champ_tabule_discretise () const
DoubleVect & valeur_a_elem (const DoubleVect &position, DoubleVect &les_valeurs, int le_poly) const override
double valeur_a_elem_compo (const DoubleVect &position, int le_poly, int ncomp) const override
DoubleTab & valeur_aux_elems (const DoubleTab &positions, const IntVect &les_polys, DoubleTab &les_valeurs) const override
Public Member Functions inherited from Champ_Fonc_base
Champ_base & affecter_ (const Champ_base &) override
Champ_base & affecter_compo (const Champ_base &, int compo) override
int fixer_nb_valeurs_nodales (int nb_noeuds) override
void mettre_a_jour (double temps) override
virtual DoubleTab & remplir_coord_noeuds (DoubleTab &) const
virtual DoubleTab & remplir_coord_noeuds_compo (DoubleTab &, int) const
virtual int remplir_coord_noeuds_et_polys (DoubleTab &, IntVect &) const
virtual int remplir_coord_noeuds_et_polys_compo (DoubleTab &, IntVect &, int) const
int reprendre (Entree &) override
int sauvegarder (Sortie &) const override
DoubleTab & valeur_aux (const DoubleTab &, DoubleTab &) const override
Public Member Functions inherited from Champ_Don_base
void dimensionner (int, int)
int imprime (Sortie &, int) const override
void resetTime (double time) override
DoubleTab & valeurs () override
Public Member Functions inherited from Champ_base
Champ_base & affecter (const Champ_base &)
Champ_base ()
virtual double changer_temps (const double t)
double temps () const
virtual DoubleTab & trace (const Frontiere_dis_base &, DoubleTab &, double, int distant) const
virtual DoubleVect & valeur_a (const DoubleVect &position, DoubleVect &valeurs) const
virtual double valeur_a_compo (const DoubleVect &position, int ncomp) const
virtual DoubleVect & valeur_a_sommet (int, const Domaine &, DoubleVect &) const
virtual DoubleVect & valeur_aux_compo (const DoubleTab &positions, DoubleVect &valeurs, int ncomp) const
virtual DoubleVect & valeur_aux_elems_compo (const DoubleTab &positions, const IntVect &les_polys, DoubleVect &valeurs, int ncomp) const
Public Member Functions inherited from Field_base
virtual Nature_du_champ fixer_nature_du_champ (Nature_du_champ nat)
virtual void fixer_nb_comp (int i)
virtual const Nom & fixer_nom_compo (const Nom &)
virtual const Nom & fixer_nom_compo (int, const Nom &)
virtual const Noms & fixer_noms_compo (const Noms &)
virtual const Nom & fixer_unite (const Nom &)
virtual const Nom & fixer_unite (int i, const Nom &)
virtual const Noms & fixer_unites (const Noms &)
const Nom & nom_compo (int) const
void nommer (const Nom &) override
const Nom & unite () const
const Nom & unite (int) const
const Noms & unites () const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
Public Member Functions inherited from Champ_Proto
int lire_dimension (Entree &, const Nom &)
int lire_dimension (int dim, const Nom &le_nom_)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
champs fonctions d'un autre champ par tabulation
L'objet porte un membre de type OWN_PTR(Champ_Fonc_base)  qui stocke
les valeurs du champ tabule.
See also
Champ_Fonc_base
Member Function Documentation
affecter_()
Champ_base & Champ_Fonc_Tabule::affecter_ (const Champ_base & ch) override virtual
Implements Champ_base.
References Field_base::le_nom(), Objet_U::que_suis_je(), valeurs(), and Champ_Proto::valeurs().
le_champ_tabule_discretise() [1/2]
const Champ_Fonc_base & Champ_Fonc_Tabule::le_champ_tabule_discretise () const inline
Renvoie le champ tabule calcule.
(version const)
Returns
(Champ_Fonc_base&) le champ tabule calcule
References Process::exit(), and Field_base::le_nom().
Referenced by associer_domaine_dis_base(), domaine_dis_base(), domaine_vf(), initialiser(), mettre_a_jour(), valeur_a_elem(), valeur_a_elem_compo(), valeur_aux_elems(), valeur_aux_sommets(), valeur_aux_sommets_compo(), and valeurs().
valeurs() [1/2]
const DoubleTab& Champ_Fonc_Tabule::valeurs () const inline override virtual
Implements Champ_Proto.
References le_champ_tabule_discretise(), and Champ_Don_base::valeurs().
Referenced by affecter_().
domaine_dis_base()
const Domaine_dis_base& Champ_Fonc_Tabule::domaine_dis_base () const inline override virtual
Reimplemented from Champ_base.
References Champ_Fonc_base::domaine_dis_base(), and le_champ_tabule_discretise().
domaine_vf()
const Domaine_VF& Champ_Fonc_Tabule::domaine_vf () const inline override virtual
Reimplemented from Champ_Fonc_base.
References Champ_Fonc_base::domaine_vf(), and le_champ_tabule_discretise().
le_champ_tabule_discretise() [2/2]
Champ_Fonc_base& Champ_Fonc_Tabule::le_champ_tabule_discretise () inline
typer_champ_tabule_discretise()
void Champ_Fonc_Tabule::typer_champ_tabule_discretise (const Nom & typ) inline
table() [1/2]
const Table& Champ_Fonc_Tabule::table () const inline
References la_table.
Referenced by Sutherland::lire_expression().
table() [2/2]
Table& Champ_Fonc_Tabule::table () inline
References la_table.
valeurs() [2/2]
DoubleTab& Champ_Fonc_Tabule::valeurs () inline override virtual
Implements Champ_Proto.
References le_champ_tabule_discretise(), and Champ_Don_base::valeurs().
initialiser()
int Champ_Fonc_Tabule::initialiser (const double un_temps) inline override virtual
NE FAIT RIEN.
A surcharger dans les classes derivees. Provoque l'initialisation du champ si necessaire
Reimplemented from Champ_Don_base.
References Champ_Don_base::initialiser(), and le_champ_tabule_discretise().
mettre_a_jour()
void Champ_Fonc_Tabule::mettre_a_jour (double) inline override virtual
mettre_a_jour de la classe de base Champ_base :ne fait rien !
Reimplemented from Champ_base.
References le_champ_tabule_discretise(), and Champ_Fonc_base::mettre_a_jour().
associer_domaine_dis_base()
void Champ_Fonc_Tabule::associer_domaine_dis_base (const Domaine_dis_base & domaine_dis) inline override virtual
Reimplemented from Champ_base.
References Champ_Fonc_base::associer_domaine_dis_base(), and le_champ_tabule_discretise().
valeur_a_elem()
DoubleVect& Champ_Fonc_Tabule::valeur_a_elem (const DoubleVect & position, DoubleVect & les_valeurs, int le_poly) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie la valeur du champ au point specifie par ses coordonnees, en indiquant que ce point est situe dans un element specifie.
Parameters
(DoubleVect&) les coordonnees du point de calcul
(DoubleVect& les_valeurs) la valeur du champ au point specifie
(int) l'element dans lequel est situe le point de calcul
Returns
(DoubleVect&) la valeur du champ au point specifie
Reimplemented from Champ_base.
References le_champ_tabule_discretise(), and Champ_base::valeur_a_elem().
valeur_aux_sommets_compo()
DoubleVect& Champ_Fonc_Tabule::valeur_aux_sommets_compo (const Domaine & dom, DoubleVect & val, int compo) const inline override virtual
renvoie la compo eme valeur aux sommets de dom.
Reimplemented from Champ_base.
References le_champ_tabule_discretise(), and Champ_base::valeur_aux_sommets_compo().
valeur_aux_elems()
DoubleTab& Champ_Fonc_Tabule::valeur_aux_elems (const DoubleTab & positions, const IntVect & les_polys, DoubleTab & les_valeurs) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement ! Renvoie les valeurs du champ aux points specifies par leurs coordonnees, en indiquant que les points de calculs sont situes dans les elements indiques.
Parameters
(DoubleTab&) le tableau des coordonnees des points de calcul
(IntVect&) le tableau des elements dans lesquels sont situes les points de calcul
(DoubleTab& les_valeurs) le tableau des valeurs du champ aux points specifies
Returns
(DoubleTab&) le tableau des valeurs du champ aux points specifies
Reimplemented from Champ_base.
References le_champ_tabule_discretise(), and Champ_base::valeur_aux_elems().
valeur_aux_sommets()
DoubleTab& Champ_Fonc_Tabule::valeur_aux_sommets (const Domaine & dom, DoubleTab & val) const inline override virtual
renvoie les valeurs aux sommets du Domaine dom
Reimplemented from Champ_base.
References le_champ_tabule_discretise(), and Champ_base::valeur_aux_sommets().
noms_champs_parametre()
Noms& Champ_Fonc_Tabule::noms_champs_parametre () inline
References noms_champs_parametre_.
noms_problemes()
Noms& Champ_Fonc_Tabule::noms_problemes () inline
References noms_pbs_.
valeur_a_elem_compo()
double Champ_Fonc_Tabule::valeur_a_elem_compo (const DoubleVect & position, int le_poly, int ncomp) const inline override virtual
provoque une erreur ! doit etre surchargee par les classes derivees
non virtuelle pure par commodite de developpement !
Reimplemented from Champ_base.
References le_champ_tabule_discretise(), and Champ_base::valeur_a_elem_compo().
Warn_old_chp_fonc_syntax_V_184()
void Champ_Fonc_Tabule::Warn_old_chp_fonc_syntax_V_184 (const char * nom_class, const Nom & val1, const Nom & val2) static
References Check_if_int(), and Process::exit().
Check_if_int()
bool Champ_Fonc_Tabule::Check_if_int (const Nom & val) static
Referenced by Warn_old_chp_fonc_syntax_V_184().
OWN_PTR()
Champ_Fonc_Tabule::OWN_PTR (Champ_Fonc_base) protected
Member Data Documentation
noms_champs_parametre_
Noms Champ_Fonc_Tabule::noms_champs_parametre_ protected
Referenced by noms_champs_parametre().
noms_pbs_
Noms Champ_Fonc_Tabule::noms_pbs_ protected
Referenced by noms_problemes().
nom_domaine
Nom Champ_Fonc_Tabule::nom_domaine protected
la_table
Table Champ_Fonc_Tabule::la_table protected
Referenced by table().