CEA TRUST Platform: Partitionneur_Metis_32_64< _SIZE_ > Class Template Reference
Partitionneur_Metis_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void construire_partition (BigIntVect_ &elem_part, int &nb_parts_tot) const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Additional Inherited Members
Static Public Member Functions inherited from Partitionneur_base_32_64< _SIZE_ >
static int_t calculer_graphe_connexions_periodiques (const Domaine_t &domaine, const Noms &liste_bords_periodiques, const Static_Int_Lists_t &som_elem, const int_t my_offset, Static_Int_Lists_t &graph)
static int_t corriger_bords_avec_graphe (const Static_Int_Lists_t &graph_elements_perio, const Static_Int_Lists_t &som_elem, const Domaine_t &domaine, const Noms &liste_bords_perio, BigIntVect_ &elem_part)
static void corriger_bords_avec_liste (const Domaine_t &dom, const Noms &liste_bords_periodiques, const int_t my_offset, BigIntVect_ &elem_part)
static void corriger_elem0_sur_proc0 (BigIntVect_ &elem_part)
static int_t corriger_multiperiodique (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
static int_t corriger_sommets_bord (const Domaine_t &domaine, const Noms &liste_bords_perio, const ArrOfInt_t &renum_som_perio, const Static_Int_Lists_t &som_elem, BigIntVect_ &elem_part)
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
template<typename _SIZE_>
class Partitionneur_Metis_32_64< _SIZE_ >
Voir construire_partition
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Partitionneur_Metis_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Partitionneur_Metis_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
IntVect_t
template<typename _SIZE_ > using Partitionneur_Metis_32_64< _SIZE_ >::IntVect_t = IntVect_T<_SIZE_>
IntTab_t
template<typename _SIZE_ > using Partitionneur_Metis_32_64< _SIZE_ >::IntTab_t = IntTab_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Partitionneur_Metis_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
BigIntVect_
template<typename _SIZE_ > using Partitionneur_Metis_32_64< _SIZE_ >::BigIntVect_ = TRUSTVect<int, _SIZE_>
Member Function Documentation
set_param()
template<typename _SIZE_ > void Partitionneur_Metis_32_64< _SIZE_ >::set_param (Param & param) override virtual
Implements Partitionneur_base_32_64< _SIZE_ >.
References Param::ajouter(), Param::ajouter_condition(), Param::ajouter_flag(), Param::ajouter_non_std(), and Param::REQUIRED.
lire_motcle_non_standard()
template<typename _SIZE_ > int Partitionneur_Metis_32_64< _SIZE_ >::lire_motcle_non_standard (const Motcle & motlu, Entree & is) override virtual
Lecture des parametres de type non simple d'un objet_U a partir d'un flot d'entree.
Parameters
(Motcle& motlu) le nom du terme a lire
(Entree& is) un flot d'entree
Returns
(int) negative value if the keyword is not understood, otherwise positive value.
Reimplemented from Partitionneur_base_32_64< _SIZE_ >.
References Process::exit(), Process::is_parallel(), and Partitionneur_base_32_64< _SIZE_ >::lire_motcle_non_standard().
associer_domaine()
template<typename _SIZE_ > void Partitionneur_Metis_32_64< _SIZE_ >::associer_domaine (const Domaine_t & domaine) inline override virtual
Implements Partitionneur_base_32_64< _SIZE_ >.
construire_partition()
template<typename _SIZE_ > void Partitionneur_Metis_32_64< _SIZE_ >::construire_partition (BigIntVect_ & elem_part, int & nb_parts_tot) const override virtual
Calcule le graphe de connectivite pour Metis, appelle le partitionneur et remplit elem_part (pour chaque element, numero de la partie qui lui.
est attribuee). Les parties sont equilibrees de facon a minimiser le nombre de faces de joint et a equilibrer le nombre d'elements par partie.
Implements Partitionneur_base_32_64< _SIZE_ >.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), Domain_Graph::adjncy, Domain_Graph::construire_graph_elem_elem(), Domain_Graph::construire_graph_from_segment(), Domain_Graph::ewgts, Process::exit(), Static_Int_Lists_32_64< _SIZE_ >::get_nb_lists(), Domain_Graph::nvtxs, TRUSTVect< _TYPE_, _SIZE_ >::resize(), Domain_Graph::vwgts, and Domain_Graph::xadj.