CEA TRUST Platform: Op_Grad_VEF_P1B_Face Class Reference
Op_Grad_VEF_P1B_Face Class Reference
#include <Op_Grad_VEF_P1B_Face.h>
Public Member Functions
int impr (Sortie &) const override
Public Member Functions inherited from Operateur_Grad_base
void contribuer_a_avec (const DoubleTab &, Matrice_Morse &) const override
void dimensionner (Matrice_Morse &) const override
Public Member Functions inherited from Operateur_base
void associer_eqn (const Equation_base &)
virtual double calculer_dt_stab () const
virtual void completer ()
virtual void contribuer_au_second_membre (DoubleTab &) const
virtual void mettre_a_jour (double temps)
virtual void modifier_pour_Cl (Matrice_Morse &, DoubleTab &) const
void ouvrir_fichier (SFichier &os, const Nom &, const int flag=1) const
void ouvrir_fichier_partage (EcrFicPartage &, const Nom &, const int flag=1) const
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Public Member Functions inherited from MorEqn
void associer_eqn (const Equation_base &)
Equation_base & equation ()
const Equation_base & equation () const
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
Cette classe represente l'operateur de gradient. La discretisation est VEF On calcule le gradient d'un champ_P1B_VEF (la pression)
See also
Operateur_Grad_base
Member Function Documentation
associer()
void Op_Grad_VEF_P1B_Face::associer (const Domaine_dis_base & domaine_dis, const Domaine_Cl_dis_base & domaine_Cl_dis, const Champ_Inc_base &) override virtual
Implements Operateur_base.
domaine_vef()
const Domaine_VEF & Op_Grad_VEF_P1B_Face::domaine_vef () const
Referenced by ajouter_aretes(), ajouter_elem(), ajouter_som(), calculer_flux_bords(), impr(), and modifier_grad_pour_Cl().
impr()
int Op_Grad_VEF_P1B_Face::impr (Sortie & os) const override virtual
DOES NOTHING - to override in derived classes.
Imprime l'operateur sur un flot de sortie.
Parameters
(Sortie& os)
Returns
(int) renvoie toujours 1
Reimplemented from Operateur_base.
References Sortie::add_col(), Domaine_VF::calculer_xgr(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), MorEqn::equation(), Operateur_base::flux_bords_, Operateur_Grad_base::Flux_grad, Operateur_Grad_base::Flux_grad_moment, Operateur_Grad_base::Flux_grad_sum, Schema_Temps_base::imprimer_temps_courant(), Process::je_suis_maitre(), Frontiere_dis_base::le_nom(), Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), Domaine_dis_base::nb_front_Cl(), Front_VF::num_premiere_face(), Operateur_base::ouvrir_fichier(), Operateur_base::ouvrir_fichier_partage(), Equation_base::probleme(), Probleme_base::schema_temps(), EcrFicPartage::syncfile(), Schema_Temps_base::temps_courant(), and Domaine_VF::xv().
ajouter()
DoubleTab & Op_Grad_VEF_P1B_Face::ajouter (const DoubleTab & pre, DoubleTab & grad) const override virtual
Reimplemented from Operateur_base.
References ajouter_aretes(), ajouter_elem(), ajouter_som(), Domaine_VEF::get_alphaA(), Domaine_VEF::get_alphaE(), Domaine_VEF::get_alphaS(), and modifier_grad_pour_Cl().
modifier_grad_pour_Cl()
DoubleTab & Op_Grad_VEF_P1B_Face::modifier_grad_pour_Cl (DoubleTab & tab_grad) const
References Objet_U::dimension, domaine_vef(), Periodique::face_associee(), Domaine_VF::face_normales(), Domaine_Cl_dis_base::les_conditions_limites(), Front_VF::nb_faces(), and Front_VF::num_premiere_face().
Referenced by ajouter().
ajouter_elem()
DoubleTab & Op_Grad_VEF_P1B_Face::ajouter_elem (const DoubleTab & pre, DoubleTab & tab_grad) const
References Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VF::face_voisins(), Neumann::flux_impose(), Domaine_VEF::get_alphaE(), Domaine_VEF::get_alphaS(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), and Milieu_base::porosite_face().
Referenced by ajouter().
ajouter_som()
DoubleTab & Op_Grad_VEF_P1B_Face::ajouter_som (const DoubleTab & tab_pre, DoubleTab & tab_grad) const
References calculer_coef_som(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_VEF::get_alphaS(), Domaine_32_64< _SIZE_ >::get_renum_som_perio(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VEF::numero_premier_sommet(), Milieu_base::porosite_face(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTArray< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().
Referenced by ajouter().
ajouter_aretes()
DoubleTab & Op_Grad_VEF_P1B_Face::ajouter_aretes (const DoubleTab & pre, DoubleTab & grad) const
References Domaine_32_64< _SIZE_ >::aretes_som(), Objet_U::dimension, Domaine_dis_base::domaine(), domaine_vef(), Domaine_32_64< _SIZE_ >::elem_aretes(), Domaine_VF::elem_faces(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Domaine_VEF::get_alphaA(), Domaine_VEF::get_ok_arete(), Domaine_VEF::get_renum_arete_perio(), Domaine_Cl_dis_base::les_conditions_limites(), Equation_base::milieu(), Front_VF::nb_faces(), Front_VF::num_premiere_face(), Domaine_VEF::numero_premiere_arete(), and Milieu_base::porosite_face().
Referenced by ajouter().
calculer_coef_som()
double Op_Grad_VEF_P1B_Face::calculer_coef_som (int elem, const Domaine_Cl_VEF & zcl, const Domaine_VEF & domaine_VEF) static
References Objet_U::dimension, Process::exit(), Domaine_VEF::get_modif_div_face_dirichlet(), Domaine_VEF::rang_elem_non_std(), and Domaine_Cl_VEF::type_elem_Cl().
Referenced by ajouter_som(), and Assembleur_P_VEFPreP1B::assembler_mat().
calculer_flux_bords()
void Op_Grad_VEF_P1B_Face::calculer_flux_bords () const override virtual
Reimplemented from Operateur_Grad_base.
References Champ_P1iP1B_implementation::champ_filtre(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, domaine_vef(), MorEqn::equation(), Domaine_VF::face_normales(), Domaine_VF::face_sommets(), Domaine_VF::face_voisins(), Champ_P1iP1B_implementation::filtrage(), Operateur_base::flux_bords_, Domaine_VEF::get_alphaE(), Domaine_VEF::get_alphaS(), Domaine_VF::nb_faces_bord(), Domaine_VEF::numero_premier_sommet(), Domaine_VF::premiere_face_int(), Navier_Stokes_std::pression_pa(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTArray< _TYPE_, _SIZE_ >::size_array().