CEA TRUST Platform: Fluide_base Class Reference
Fluide_base Class Reference
#include <Fluide_base.h>
Public Member Functions
void mettre_a_jour (double) override
void verifier_coherence_champs (int &err, Nom &message) override
Public Member Functions inherited from Milieu_base
virtual int a_gravite () const
int associer_ (Objet_U &) override
virtual void associer_gravite (const Champ_Don_base &)
virtual Champ_Don_base & beta_t ()
virtual const Champ_Don_base & beta_t () const
virtual Champ_Don_base & capacite_calorifique ()
virtual const Champ_Don_base & capacite_calorifique () const
virtual Champ_Don_base & conductivite ()
virtual const Champ_Don_base & conductivite () const
virtual Champ_Don_base & diffusivite ()
virtual const Champ_Don_base & diffusivite () const
virtual int est_deja_associe ()
virtual Champ_Don_base & gravite ()
virtual const Champ_Don_base & gravite () const
const Nom & le_nom () const override
int lire_motcle_non_standard (const Motcle &, Entree &) override
virtual Champ_base & masse_volumique ()
virtual const Champ_base & masse_volumique () const
void nommer (const Nom &) override
Public Member Functions inherited from Objet_U
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
const char * le_type () const
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Protected Member Functions
void creer_nu ()
Protected Member Functions inherited from Milieu_base
virtual void calculer_alpha ()
void ecrire (Sortie &) const
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Additional Inherited Members
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Detailed Description
ses proprietes:
viscosite cinematique, (mu)
viscosite dynamique, (nu)
masse volumique, (rho)
diffusivite, (alpha)
conductivite, (lambda)
capacite calorifique, (Cp)
dilatabilite thermique du constituant (beta_co)
See also
Milieu_base
Member Function Documentation
set_param()
void Fluide_base::set_param (Param & param) override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Dilatable_base, Fluide_Quasi_Compressible, Fluide_Weakly_Compressible, Fluide_Incompressible, Fluide_Ostwald, Fluide_reel_base, Fluide_stiffened_gas, Fluide_generique_CoolProp, and Fluide_generique_EOS.
References Param::ajouter(), ch_beta_co_, indice_refraction_, Param::REQUIRED, and Milieu_base::set_param().
Referenced by Fluide_Dilatable_base::set_param(), and Fluide_Incompressible::set_param().
verifier_coherence_champs()
void Fluide_base::verifier_coherence_champs (int & err, Nom & msg) override virtual
Verifie que les champs lus l'ont ete correctement.
Exceptions
la masse volumique (rho) n'est pas strictement positive
la masse volumique (rho) n'est pas de type Champ_Uniforme
la viscosite (mu) n'est pas strictement positive
l'une des proprietes (rho ou mu) du fluide n'a pas ete definie
la capacite calorifique (Cp) n'est pas strictement positive
la capacite calorifique (Cp) n'est pas de type Champ_Uniforme
la conductivite (lambda) n'est pas strictement positive
toutes les proprietes du fluide anisotherme n'ont pas ete definies
Reimplemented from Milieu_base.
Reimplemented in Fluide_Dilatable_base, and Fluide_Incompressible.
References Milieu_base::ch_beta_th_, Milieu_base::ch_Cp_, Milieu_base::ch_lambda_, indice_refraction_, and Milieu_base::verifier_coherence_champs().
Referenced by Fluide_Incompressible::verifier_coherence_champs().
initTimeStep()
bool Fluide_base::initTimeStep (double dt) override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_reel_base, and Milieu_composite.
References Champ_Inc_base::changer_temps_futur(), e_int_auto_, Milieu_base::equation_, Champ_Inc_base::futur(), Schema_Temps_base::nb_valeurs_futures(), Schema_Temps_base::temps_futur(), and Champ_Inc_base::valeurs().
mettre_a_jour()
void Fluide_base::mettre_a_jour (double temps) override virtual
Effectue une mise a jour en temps du milieu, et donc de ses parametres caracteristiques.
Les champs uniformes sont recalcules pour le nouveau temps specifie, les autres sont mis a par un appel a CLASSE_DU_CHAMP::mettre_a_jour(double temps).
Parameters
(double temps) le temps de mise a jour
Reimplemented from Milieu_base.
Reimplemented in Fluide_reel_base, Milieu_composite, Fluide_Dilatable_base, and Fluide_Ostwald.
References calculer_nu(), ch_beta_co_, ch_nu_, e_int_auto_, TRUSTVect< _TYPE_, _SIZE_ >::echange_espace_virtuel(), indice_refraction_, kappa(), longueur_rayo(), Milieu_base::mettre_a_jour(), Champ_Don_base::nb_valeurs_nodales(), and Champ_Don_base::valeurs().
initialiser()
int Fluide_base::initialiser (const double temps) override virtual
Initialise les parametres du fluide.
Reimplemented from Milieu_base.
Reimplemented in Fluide_Dilatable_base, Fluide_Ostwald, Fluide_MUSIG, Fluide_reel_base, and Milieu_composite.
References calculer_nu(), ch_beta_co_, ch_nu_, indice_refraction_, Milieu_base::initialiser(), kappa(), longueur_rayo(), Champ_Don_base::nb_valeurs_nodales(), and Champ_Don_base::valeurs().
creer_champs_non_lus()
void Fluide_base::creer_champs_non_lus () override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Dilatable_base, Fluide_Ostwald, and Fluide_reel_base.
References Milieu_base::creer_champs_non_lus(), and creer_nu().
discretiser()
void Fluide_base::discretiser (const Probleme_base & pb, const Discretisation_base & dis) override virtual
Reimplemented from Milieu_base.
Reimplemented in Fluide_Dilatable_base, Fluide_Quasi_Compressible, Fluide_Weakly_Compressible, Fluide_Ostwald, Fluide_reel_base, and Milieu_composite.
References Champs_compris_T< FIELD_TYPE >::ajoute_champ(), ch_beta_co_, ch_nu_, Milieu_base::champs_compris_, Milieu_base::discretiser(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), Probleme_base::equation(), Discretisation_base::nommer_completer_champ_physique(), OWN_PTR(), Probleme_base::schema_temps(), and Schema_Temps_base::temps_courant().
Referenced by Fluide_Dilatable_base::discretiser().
set_h0_T0()
void Fluide_base::set_h0_T0 (double h0, double T0) virtual
References h0_, and T0_.
is_incompressible()
virtual int Fluide_base::is_incompressible () const inline virtual
Reimplemented in Fluide_Incompressible, and Fluide_reel_base.
energie_interne() [1/2]
const Champ_base & Fluide_base::energie_interne () const
References creer_e_int().
Referenced by Energie_Multiphase::calculer_alpha_rho_e().
energie_interne() [2/2]
Champ_base & Fluide_base::energie_interne ()
References creer_e_int().
enthalpie() [1/2]
const Champ_base & Fluide_base::enthalpie () const
References ch_h_ou_T_, and creer_e_int().
Referenced by Source_Flux_interfacial_base::ajouter_blocs(), and Energie_Multiphase::calculer_alpha_rho_h().
enthalpie() [2/2]
Champ_base & Fluide_base::enthalpie ()
References ch_h_ou_T_, and creer_e_int().
temperature_multiphase() [1/2]
const Champ_base & Fluide_base::temperature_multiphase () const
References calculer_temperature_multiphase(), ch_h_ou_T_, and creer_temperature_multiphase().
temperature_multiphase() [2/2]
Champ_base & Fluide_base::temperature_multiphase ()
References calculer_temperature_multiphase(), ch_h_ou_T_, and creer_temperature_multiphase().
viscosite_cinematique() [1/2]
const Champ_Don_base & Fluide_base::viscosite_cinematique () const inline
References ch_nu_.
Referenced by Champ_Q1_EF::calcul_y_plus(), Champ_P1NC::calcul_y_plus(), Champ_Face_VDF::calcul_y_plus(), Modele_turbulence_hyd_Longueur_Melange_VEF::calculer_f_amortissement(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Paroi_negligeable_VDF::calculer_hyd(), Paroi_negligeable_VEF::calculer_hyd(), Navier_Stokes_Turbulent::diffusivite_pour_pas_de_temps(), Navier_Stokes_std::diffusivite_pour_transport(), Navier_Stokes_Turbulent::diffusivite_pour_transport(), and VDF_discretisation::reynolds_maille().
viscosite_cinematique() [2/2]
Champ_Don_base & Fluide_base::viscosite_cinematique () inline
References ch_nu_.
viscosite_dynamique() [1/2]
const Champ_Don_base & Fluide_base::viscosite_dynamique () const inline
Referenced by Source_Flux_interfacial_base::ajouter_blocs(), Traitement_particulier_NS_canal::calcul_reynolds_tau(), Traitement_particulier_NS_canal_VDF::calculer_moyenne_spatiale_vitesse_rho_mu(), Traitement_particulier_NS_canal_VEF::calculer_moyenne_spatiale_vitesse_rho_mu(), Fluide_Weakly_Compressible::completer(), Navier_Stokes_Turbulent_QC::diffusivite_pour_transport(), EF_discretisation::proprietes_physiques_fluide_Ostwald(), VDF_discretisation::proprietes_physiques_fluide_Ostwald(), and VEF_discretisation::proprietes_physiques_fluide_Ostwald().
viscosite_dynamique() [2/2]
Champ_Don_base & Fluide_base::viscosite_dynamique () inline
has_viscosite_dynamique()
bool Fluide_base::has_viscosite_dynamique () const inline
beta_c() [1/2]
const Champ_Don_base & Fluide_base::beta_c () const inline
References ch_beta_co_.
Referenced by Terme_Boussinesq_base::associer_pb().
beta_c() [2/2]
Champ_Don_base & Fluide_base::beta_c () inline
References ch_beta_co_.
has_beta_c()
bool Fluide_base::has_beta_c () const inline
References ch_beta_co_.
Referenced by Terme_Boussinesq_base::associer_pb().
kappa() [1/2]
Champ_Don_base & Fluide_base::kappa () inline
Referenced by initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), and mettre_a_jour().
kappa() [2/2]
const Champ_Don_base & Fluide_base::kappa () const inline
has_kappa()
bool Fluide_base::has_kappa () const inline
indice() [1/2]
Champ_Don_base & Fluide_base::indice () inline
References indice_refraction_.
indice() [2/2]
const Champ_Don_base & Fluide_base::indice () const inline
References indice_refraction_.
longueur_rayo()
Champ_Don_base & Fluide_base::longueur_rayo () inline
Referenced by initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), and mettre_a_jour().
longeur_rayo()
const Champ_Don_base & Fluide_base::longeur_rayo () const inline
typer_longeur_rayo()
void Fluide_base::typer_longeur_rayo (const Nom & typ) inline
is_rayo_semi_transp()
int Fluide_base::is_rayo_semi_transp () const override virtual
Reimplemented from Milieu_base.
References Milieu_base::indic_rayo_, and Milieu_base::SEMITRANSP.
is_rayo_transp()
int Fluide_base::is_rayo_transp () const override virtual
Reimplemented from Milieu_base.
References Milieu_base::indic_rayo_, and Milieu_base::TRANSP.
fixer_type_rayo()
void Fluide_base::fixer_type_rayo ()
References Milieu_base::indic_rayo_, indice_refraction_, Milieu_base::SEMITRANSP, and Milieu_base::TRANSP.
reset_type_rayo()
void Fluide_base::reset_type_rayo ()
References Milieu_base::indic_rayo_, and Milieu_base::NONRAYO.
longueur_rayo_is_discretised()
int Fluide_base::longueur_rayo_is_discretised ()
creer_e_int()
void Fluide_base::creer_e_int () const protected
References calculer_e_int(), Equation_base::discretisation(), Discretisation_base::discretiser_champ(), Equation_base::domaine_dis(), e_int_auto_, Milieu_base::equation(), Milieu_base::equation_, Equation_base::inconnue(), Champ_Inc_base::nb_valeurs_temporelles(), OWN_PTR(), and Champ_base::temps().
Referenced by creer_temperature_multiphase(), energie_interne(), energie_interne(), enthalpie(), and enthalpie().
creer_temperature_multiphase()
void Fluide_base::creer_temperature_multiphase () const protected
References ch_h_ou_T_, creer_e_int(), Milieu_base::equation(), Milieu_base::equation_, Equation_base::inconnue(), and Champ_base::temps().
Referenced by temperature_multiphase(), and temperature_multiphase().
calculer_temperature_multiphase()
void Fluide_base::calculer_temperature_multiphase () const protected
References Milieu_base::capacite_calorifique(), ch_h_ou_T_, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_base::domaine_dis_base(), Milieu_base::equation(), Milieu_base::equation_, h0_, Milieu_base::id_composite_, Equation_base::inconnue(), T0_, Champ_Inc_base::val_bord(), Champ_base::valeur_aux_bords(), Champ_Inc_base::valeurs(), and Champ_Proto::valeurs().
Referenced by Milieu_composite::initialiser(), temperature_multiphase(), and temperature_multiphase().
calculer_e_int()
void Fluide_base::calculer_e_int (const Objet_U & obj, DoubleTab & val, DoubleTab & bval, tabs_t & deriv) static protected
References Milieu_base::capacite_calorifique(), TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), Champ_base::domaine_dis_base(), Milieu_base::equation(), Milieu_base::equation_, Nom::getString(), h0_, Milieu_base::id_composite_, Equation_base::inconnue(), Field_base::le_nom(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), T0_, Champ_base::valeur_aux_bords(), and Champ_Proto::valeurs().
Referenced by creer_e_int().
OWN_PTR() [1/4]
Fluide_base::OWN_PTR (Champ_base) mutable protected
Referenced by creer_e_int(), discretiser(), and Fluide_reel_base::discretiser().
OWN_PTR() [2/4]
Fluide_base::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [3/4]
Fluide_base::OWN_PTR (Champ_Don_base) protected
OWN_PTR() [4/4]
Fluide_base::OWN_PTR (Champ_Don_base) protected
creer_nu()
void Fluide_base::creer_nu () protected
Si l'objet reference par nu et du type Champ_Uniforme type nu en "Champ_Uniforme" et le remplit.
avec mu(0,0)/rho(0,0).
Sinon n efait rien.
References ch_nu_.
Referenced by creer_champs_non_lus().
calculer_nu()
void Fluide_base::calculer_nu () protected virtual
Reimplemented in Fluide_Dilatable_base.
References TRUSTArray< _TYPE_, _SIZE_ >::addr(), ch_nu_, TRUSTTab< _TYPE_, _SIZE_ >::dimension_tot(), and TRUSTVect< _TYPE_, _SIZE_ >::line_size().
Referenced by initialiser(), and mettre_a_jour().
Member Data Documentation
e_int_auto_
int Fluide_base::e_int_auto_ = 0 mutable protected
Referenced by creer_e_int(), initTimeStep(), and mettre_a_jour().
ch_h_ou_T_
Fluide_base::ch_h_ou_T_ protected
Referenced by Fluide_reel_base::abortTimeStep(), Milieu_composite::abortTimeStep(), Fluide_reel_base::calculate_fluid_properties(), Fluide_reel_base::calculate_fluid_properties_enthalpie(), Fluide_reel_base::calculate_fluid_properties_enthalpie_incompressible(), Fluide_reel_base::calculate_fluid_properties_incompressible(), calculer_temperature_multiphase(), creer_temperature_multiphase(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), enthalpie(), enthalpie(), Fluide_reel_base::initialiser(), Milieu_composite::initialiser(), Fluide_reel_base::initTimeStep(), Milieu_composite::initTimeStep(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), temperature_multiphase(), and temperature_multiphase().
ch_nu_
Fluide_base::ch_nu_ protected
Referenced by calculer_nu(), creer_nu(), discretiser(), Fluide_reel_base::discretiser(), Milieu_composite::discretiser(), initialiser(), Fluide_reel_base::initialiser(), Fluide_reel_base::mettre_a_jour(), Milieu_composite::mettre_a_jour(), mettre_a_jour(), Milieu_composite::mettre_a_jour_tabs(), viscosite_cinematique(), and viscosite_cinematique().
ch_beta_co_
Fluide_base::ch_beta_co_ protected
Referenced by beta_c(), beta_c(), discretiser(), has_beta_c(), initialiser(), mettre_a_jour(), and set_param().
h0_
double Fluide_base::h0_ = 0 protected
Referenced by calculer_e_int(), calculer_temperature_multiphase(), and set_h0_T0().
T0_
double Fluide_base::T0_ = 0 protected
Referenced by calculer_e_int(), calculer_temperature_multiphase(), and set_h0_T0().
indice_refraction_
Fluide_base::indice_refraction_ protected
Referenced by fixer_type_rayo(), indice(), indice(), Fluide_Dilatable_base::initialiser(), initialiser(), Fluide_Dilatable_base::initialiser_radiatives(), mettre_a_jour(), set_param(), and verifier_coherence_champs().