CEA TRUST Platform: Groupes_Faces_32_64< _SIZE_ > Class Template Reference
Groupes_Faces_32_64< _SIZE_ > Class Template Reference
Public Member Functions
void associer_domaine (const Domaine_t &)
int_t nb_faces () const
int_t nb_faces (Type_Face type) const
void renumerote (ArrOfInt_t &reverse_index)
Detailed Description
template<typename _SIZE_>
class Groupes_Faces_32_64< _SIZE_ >
See also
Groupes_Faces
Member Typedef Documentation
int_t
template<typename _SIZE_ > using Groupes_Faces_32_64< _SIZE_ >::int_t = _SIZE_
ArrOfInt_t
template<typename _SIZE_ > using Groupes_Faces_32_64< _SIZE_ >::ArrOfInt_t = ArrOfInt_T<_SIZE_>
Domaine_t
template<typename _SIZE_ > using Groupes_Faces_32_64< _SIZE_ >::Domaine_t = Domaine_32_64<_SIZE_>
Member Function Documentation
associer_domaine()
template<typename _SIZE_ > void Groupes_Faces_32_64< _SIZE_ >::associer_domaine (const Domaine_t & un_domaine)
Associe un domaine a tous les objets Groupe_Faces de la liste.
Parameters
(Domaine& un_domaine) le domaine a associer aux Groupe_Faces de la liste
Referenced by Interprete_geometrique_base_32_64< _SIZE_ >::interpreter(), and Domaine_32_64< _SIZE_ >::merge_wo_vertices_with().
nb_faces() [1/2]
template<typename _SIZE_ > Groupes_Faces_32_64< _SIZE_ >::int_t Groupes_Faces_32_64< _SIZE_ >::nb_faces
Renvoie le nombre total de faces contenues dans la liste des Groupe_Faces, i.
e. la somme de toutes les faces de tous les objet Groupe_Faces contenu dans la liste.
Returns
(int) le nombre total de faces contenues dans la liste des Groupe_Faces
Referenced by Domaine_32_64< _SIZE_ >::nb_faces_groupes_faces().
nb_groupes_faces()
template<typename _SIZE_ > int Groupes_Faces_32_64< _SIZE_ >::nb_groupes_faces () const inline
Referenced by Domaine_32_64< _SIZE_ >::nb_groupes_faces().
nb_faces() [2/2]
template<typename _SIZE_ > Groupes_Faces_32_64< _SIZE_ >::int_t Groupes_Faces_32_64< _SIZE_ >::nb_faces (Type_Face type) const
Renvoie le nombre total de faces de type specifie contenues dans la liste des Groupe_Faces.
i.e. la somme de toutes les faces de type specifie de tous les objet Groupe_Faces contenu dans la liste.
Parameters
(Type_Face type) le type des faces a compter
Returns
(int) le nombre total de faces contenues dans la liste des Groupe_Faces
renumerote()
template<typename _SIZE_ > void Groupes_Faces_32_64< _SIZE_ >::renumerote (ArrOfInt_t & reverse_index)
Mise a jour des indices des groupes de faces avec table inversee: reverse_index[ancien_numero] = nouveau numero: necessaire lorsque les numeros des faces ont ete modifies
References TRUSTArray< _TYPE_, _SIZE_ >::size_array().