CEA TRUST Platform: SChaine Class Reference
SChaine Class Reference
Additional Inherited Members
Public Member Functions inherited from Sortie
virtual Sortie & operator<< (const char *ob)
virtual Sortie & operator<< (const Objet_U &ob)
void set_bin (bool bin) override
Protected Member Functions inherited from AbstractIO
template<typename _TYPE_ >
bool must_convert () const
Protected Attributes inherited from Sortie
std::unique_ptr< ostream > ostream_
Protected Attributes inherited from AbstractIO
bool avoid_conversion_ = false
Detailed Description
On recupere le contenu de la chaine avec get_str().
See also
EChaine
Constructor & Destructor Documentation
SChaine()
SChaine::SChaine ()
Member Function Documentation
get_str()
const char * SChaine::get_str () const
returns a copy of the string stored by the SChaine
Referenced by Refine_Mesh::build_new_sub_domaines_descriptions(), Op_Div_VEFP1B_Elem::degres_liberte(), Extraire_plan::interpreter_(), SolveurSys_base::lecture(), and LecFicDiffuse_JDD::ouvrir().
get_size()
unsigned SChaine::get_size () const
setf()
void SChaine::setf (IOS_FORMAT code) override virtual
Reimplemented from Sortie.
References Sortie::setf().
set_bin()
void SChaine::set_bin (bool bin) override virtual
Reimplemented from AbstractIO.
References Process::exit(), and Sortie::set_bin().
Member Data Documentation
string_
std::string SChaine::string_ mutable protected