CEA TRUST Platform: Ensemble_Lagrange_base Class Reference
Ensemble_Lagrange_base Class Reference abstract
Additional Inherited Members
Public Member Functions inherited from Objet_U
virtual int associer_ (Objet_U &)
virtual int change_num (const int *const)
virtual const Type_info * get_info () const
virtual const Nom & le_nom () const
const char * le_type () const
virtual int lire_motcle_non_standard (const Motcle &motlu, Entree &is)
virtual void nommer (const Nom &)
virtual Sortie & printOn (Sortie &) const
const Nom & que_suis_je () const
virtual Entree & readOn (Entree &)
virtual int reprendre (Entree &)
virtual int sauvegarder (Sortie &) const
Static Public Member Functions inherited from Objet_U
static Nom & get_set_nom_du_cas ()
static const Type_info * info ()
static const Nom & nom_du_cas ()
Static Public Member Functions inherited from Process
static void barrier ()
static void exit (int exit_code=-1)
static int je_suis_maitre ()
static Sortie & Journal (int message_level=0)
static int me ()
static double mp_sum (double)
static trustIdType mp_sum (trustIdType)
static trustIdType mppartial_sum (trustIdType i)
Protected Member Functions inherited from Objet_U
Objet_U ()
Objet_U (const Objet_U &)
Detailed Description
d'un ensemble de points dont on realise un suivi Lagrangien
Actuellement une seule classe derivant instanciable : Maillage_FT_Disc
-un ensemble Lagrangien est caracterise par les coordonnees de ses points
See also
Classe abstraite.
Methodes abstraites: void associer_equation_transport) Equation_base& equation_associee()
Constructor & Destructor Documentation
Ensemble_Lagrange_base()
Ensemble_Lagrange_base::Ensemble_Lagrange_base ()
References nb_marqs_par_dir, nb_marqs_sz, TRUSTTab< _TYPE_, _SIZE_ >::resize(), and TRUSTVect< _TYPE_, _SIZE_ >::resize().
Member Function Documentation
associer_equation_transport()
virtual void Ensemble_Lagrange_base::associer_equation_transport (const Equation_base & equation) pure virtual
equation_associee()
virtual const Equation_base& Ensemble_Lagrange_base::equation_associee () const pure virtual
associer_domaine()
void Ensemble_Lagrange_base::associer_domaine (const Domaine & domaine)
Referenced by Marqueur_Lagrange_base::discretiser().
domaine()
const Domaine & Ensemble_Lagrange_base::domaine () const inline virtual
remplir_sommets_tmp()
void Ensemble_Lagrange_base::remplir_sommets_tmp (DoubleTab & soms_tmp)
References TRUSTTab< _TYPE_, _SIZE_ >::dimension(), generer_marqueurs_sz(), nb_marqs_par_sz(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), sommets_lu(), and sommets_lu_.
generer_marqueurs_sz()
void Ensemble_Lagrange_base::generer_marqueurs_sz (DoubleTab & soms_tmp)
References Domaine_32_64< _SIZE_ >::coord(), TRUSTTab< _TYPE_, _SIZE_ >::dimension(), Objet_U::dimension, Process::je_suis_maitre(), Process::mp_max(), Process::mp_min(), Sous_Domaine_32_64< _SIZE_ >::nb_elem_tot(), nb_marqs_par_dir, nb_marqs_sz, Domaine_32_64< _SIZE_ >::nb_som_elem(), nom_sz, Process::nproc(), TRUSTTab< _TYPE_, _SIZE_ >::resize(), TRUSTVect< _TYPE_, _SIZE_ >::size(), Domaine_32_64< _SIZE_ >::sommet_elem(), and Domaine_32_64< _SIZE_ >::ss_domaine().
Referenced by remplir_sommets_tmp().
nb_marqs_par_sz()
const IntVect & Ensemble_Lagrange_base::nb_marqs_par_sz () const inline
References nb_marqs_sz.
Referenced by remplir_sommets_tmp().
sommets_lu() [1/2]
const DoubleTab & Ensemble_Lagrange_base::sommets_lu () const inline
References sommets_lu_.
Referenced by remplir_sommets_tmp().
sommets_lu() [2/2]
DoubleTab & Ensemble_Lagrange_base::sommets_lu () inline
References sommets_lu_.
OBS_PTR()
Ensemble_Lagrange_base::OBS_PTR (Domaine) protected
Member Data Documentation
nom_sz
Noms Ensemble_Lagrange_base::nom_sz protected
Referenced by generer_marqueurs_sz().
nb_marqs_sz
IntVect Ensemble_Lagrange_base::nb_marqs_sz protected
Referenced by Ensemble_Lagrange_base(), generer_marqueurs_sz(), and nb_marqs_par_sz().
nb_marqs_par_dir
IntTab Ensemble_Lagrange_base::nb_marqs_par_dir protected
Referenced by Ensemble_Lagrange_base(), and generer_marqueurs_sz().
sommets_lu_
DoubleTab Ensemble_Lagrange_base::sommets_lu_ protected
Referenced by remplir_sommets_tmp(), and sommets_lu().