CEA TRUST Platform: DeviceMemory Struct Reference
DeviceMemory Struct Reference
Static Public Member Functions
static void add (void *ptr, void *device_ptr, trustIdType bytes)
static void * addrOnDevice (void *)
static void del (void *ptr)
static bool isAllocatedOnDevice (void *)
static void printMemoryMap ()
Constructor & Destructor Documentation
DeviceMemory()
DeviceMemory::DeviceMemory () delete
Member Function Documentation
allocatedBytesOnDevice()
size_t DeviceMemory::allocatedBytesOnDevice () static
References deviceMemGetInfo().
Referenced by Process::imprimer_ram_totale().
deviceMemGetInfo()
size_t DeviceMemory::deviceMemGetInfo (bool print_total) static
References Process::exit().
Referenced by allocatedBytesOnDevice(), and Process::imprimer_ram_totale().
getMemoryMap()
static map_t& DeviceMemory::getMemoryMap () inline static
Referenced by add(), and del().
isAllocatedOnDevice()
bool DeviceMemory::isAllocatedOnDevice (void * ptr) static
Check if a chunk (even empty) is allocated on the device for the host ptr Return true/false
addrOnDevice()
void * DeviceMemory::addrOnDevice (void * ptr) static
Return the device address of the host ptr Return nullptr if ptr null or map empty Fatal error if address not found on the device
References Process::exit(), Process::Journal(), and printMemoryMap().
add()
void DeviceMemory::add (void * ptr, void * device_ptr, trustIdType bytes) static
Add a new line to the memory_map_ ptr should be non-null, device_ptr and size may be null
References getMemoryMap(), Process::Journal(), and printMemoryMap().
del()
void DeviceMemory::del (void * ptr) static
Delete a line into the memory_map_
References getMemoryMap(), Process::Journal(), and printMemoryMap().
printMemoryMap()
void DeviceMemory::printMemoryMap () static
Print the memory map for debug
References Process::Journal().
Referenced by add(), addrOnDevice(), and del().
warning()
bool DeviceMemory::warning (trustIdType nb_items) static
References internal_items_size_, Perf_counters::is_gpu_verbose_on(), and nb_pas_dt_.
Member Data Documentation
internal_items_size_
trustIdType DeviceMemory::internal_items_size_ = 1e9 static
Referenced by Domaine_VF::info_elem_som(), and warning().
nb_pas_dt_
int DeviceMemory::nb_pas_dt_ = -1 static
Referenced by Schema_Temps_base::mettre_a_jour_dt_stab(), and warning().