CEA TRUST Platform: Roue_ptr Struct Reference
Roue_ptr Struct Reference
Public Member Functions
Roue_ptr & operator= (const Roue_ptr &x)
Roue_ptr (const Roue_ptr &)
Detailed Description
La roue est creee dans le constructeur, detruite dans le destructeur. Elle est recopiee dans le constructeur par recopie et dans l'operateur d'affectation d'un Roue_ptr a un autre. Dans tous les autres cas seuls les pointeurs sont manipules.
See also
Champ_Inc
Constructor & Destructor Documentation
Roue_ptr() [1/4]
Roue_ptr::Roue_ptr (const Roue_ptr & x)
Constructeur par recopie.
Copie de l'ensemble de la roue. Utile pour les constructeurs par recopie des champs. (ce constructeur est appele quand on fait un OWN_PTR(Champ_base) = un autre Champ, la version precedente copie la reference, d'ou plantage a la destruction)
References ptr, and valeur().
Roue_ptr() [2/4]
Roue_ptr::Roue_ptr (Roue & x)
Roue_ptr() [3/4]
Roue_ptr::Roue_ptr ()
Roue_ptr() [4/4]
Roue_ptr::Roue_ptr (Roue * x) inline
~Roue_ptr()
Roue_ptr::~Roue_ptr ()
References ptr.
Member Function Documentation
operator->() [1/2]
Roue * Roue_ptr::operator-> () const inline
References ptr.
operator->() [2/2]
Roue * Roue_ptr::operator-> () inline
References ptr.
operator=() [1/3]
Roue_ptr & Roue_ptr::operator= (const Roue_ptr & x)
Constructeur par recopie.
Copie de l'ensemble de la roue.
References ptr, and valeur().
valeur() [1/2]
Roue& Roue_ptr::valeur () inline
References ptr.
Referenced by Roue::avancer(), Champ_Inc_base::changer_temps_futur(), Champ_Inc_base::changer_temps_passe(), operator=(), Roue::reculer(), Champ_Inc_base::recuperer_temps_futur(), Champ_Inc_base::recuperer_temps_passe(), Roue_ptr(), and Champ_Inc_base::valeurs().
valeur() [2/2]
const Roue& Roue_ptr::valeur () const inline
References ptr.
annule()
void Roue_ptr::annule () inline
References ptr.
operator bool()
Roue_ptr::operator bool () const inline
References ptr.
operator=() [2/3]
Roue& Roue_ptr::operator= (Roue & x) inline
References ptr.
operator=() [3/3]
Roue* Roue_ptr::operator= (Roue * x) inline
References ptr.
operator[]() [1/2]
Roue & Roue_ptr::operator[] (int i)
References Roue::futur(), and ptr.
operator[]() [2/2]
const Roue & Roue_ptr::operator[] (int i) const
References Roue::futur(), and ptr.
Member Data Documentation
ptr
Roue* Roue_ptr::ptr
Referenced by Roue::ajouter_case(), annule(), operator bool(), operator->(), operator=(), operator[](), Roue_ptr(), Roue::supprimer_case(), valeur(), Roue::~Roue(), and ~Roue_ptr().